### ISSUE TITLE
Compiler should add, support Literal types

### ISSUE THREAD

**Issue by mskasal** [ionic-team/stencil#1002]
**Stencil version:**
```
@stencil/core@0.11.0
```

**I'm submitting a:** (not sure if it's a bug or new feature)
[ x] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I create a  `literal type` for my component property, generated `components.d.ts` adding the type to component interface but not importing type from relative file.
As result cannot find type for component.
<img width="282" alt="screen shot 2018-08-08 at 10 12 02" src="https://user-images.githubusercontent.com/2426680/43834103-a6110350-9b15-11e8-87b3-680a7ea7d24a.png">

**Expected behavior:**
components.d.ts should add, support literal type.

**Related code:**
***my component***
_sm-icon.tsx_
```tsx
import { Component, Prop } from '@stencil/core';

import IIconName from '@literals/icon-literals';

@Component({
    tag: 'sm-icon',
    styleUrl: 'sm-icon.css',
    shadow: true
})
export class SmIcon {

    @Prop() name: IIconName;
    render() {
        const iconName = `fa fa-${this.name}`
        return (
            <i class={iconName}>{iconName}</i>
        );
    }
}
```

***my type file*** 
_icon-literals.ts_
```ts
type IIconName = 'truck' | 'profile';

export default IIconName;
```

***snippet from generated components.d.ts***
_components.d.ts_
```ts
declare global {

  namespace StencilComponents {
    interface SmIcon {
      'name': IIconName;
    }
  }
.
.

namespace JSXElements {
    export interface SmIconAttributes extends HTMLAttributes {
      'name'?: IIconName;
    }
  }
.
.
```

**Other information:**
https://github.com/ionic-team/stencil/issues/280 I found this issue most relatable.

**Comment by simonhaenisch** [comment]
Had a similar issue with this:

```tsx
import { Component, Prop } from '@stencil/core';
import moment from 'moment-timezone';

@Component({ tag: 'my-component' })
export class MyComponent {
  @Prop() date: moment.Moment;

  render() {
    return this.date.format();
  }
}
```

giving me

```
Cannot find namespace 'moment'.
```

Seems that Stencil is not able to include types from (synthetic) default imports in `components.d.ts`. As a workaround I can do

```ts
import moment, { Moment } from 'moment-timezone';
```

and then use `Moment` as a type instead of `moment.Moment`, which is nicer to read anyway. Then the `Moment` type gets imported in the component declarations file and no more problems.

Not sure if a non-default import is possible in your case though.

**Comment by adamdbradley** [comment]
Should be fixed in most recent versions
