### ISSUE TITLE
Only add esm files to sw.js

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil#1006]
Remove all the es5 versions from sw.js

**Comment by adamdbradley** [comment]
Use workbox `globIgnore` option: https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/entry-points/generate-sw.js#L62-L64

**Comment by joewoodhouse** [comment]
Could also be worth not caching all icons at the same time:
https://github.com/ionic-team/stencil/issues/1164
