### ISSUE TITLE
support for delegatesFocus

### ISSUE THREAD

**Issue by MrAntix** [ionic-team/stencil#1008]
**Stencil version:**

```
 @stencil/core@0.11.3<version>
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
not supported

**Expected behavior:**

https://developers.google.com/web/fundamentals/web-components/shadowdom#focus

**Comment by jthoms1** [comment]
@adamdbradley thoughts?

**Comment by zoofadoofa** [comment]
This is not really an edge case, anything that is slotting in content into shareable components will need delegatesFocus
See Demo

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil/commit/f45c919a9675827a5006702218982022b3e0ec0d
