### ISSUE TITLE
Stencil fails to polyfill Number.isFinite and Number.isNaN

### ISSUE THREAD

**Issue by apillard** [ionic-team/stencil#1009]
**Stencil version:**

```
 @stencil/core@0.11.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When using the Number.isFinite or Number.isNaN methods, Stencil does not polyfill correctly and IE11 silently fails executing code. If a browser supports these methods natively, it executes as expected

**Expected behavior:**

Stencil should polyfill these methods so all browsers behave the same regardless of built-in support

**Steps to reproduce:**

1. Clone this repo: https://github.com/apillard/stencil-polyfill-bug-repro
2. npm install
3. npm start
4. Open localhost:3333 in IE11, you will see it does not render the component as expected, and is missing the console.log statements that occur after the usage of Number.isFinite and Number.isNaN in my-component.tsx

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
thanks
