### ISSUE TITLE
Stencil in FF can't handle this SVG

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/stencil#1014]
**Stencil version:**

```
 @stencil/core@0.11.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

If use the SVG code below anywhere in a component, the render function will fail silently in Firefox

**Expected behavior:**

It should show the SVG and the rest of the results from the render function

**Steps to reproduce:**

Put the SVG in a render function and look at it in FF

**Related code:**

```tsx
<svg version="1.1"
			 xmlns="http://www.w3.org/2000/svg"
			 viewBox="0 0 512 512"
			 style="enable-background:new 0 0 512 512;">
<path d="M256,307c-2.4,0-4.8-0.4-7-1.2L78.3,246.3c-11.1-3.9-17-16-13.1-27.1c3.9-11.1,16.1-16.9,27.2-13l157.9,55.1
	c3.7,1.3,7.7,1.3,11.3,0l157.9-55.1c11.1-3.9,23.3,2,27.2,13c3.9,11.1-2,23.2-13.1,27.1L263,305.8C260.8,306.6,258.4,307,256,307z"
	/>
	</svg>
```

**Other information:**

Looked at this with Josh. It's related to [this tweet](https://twitter.com/neneodonkor/status/1027894027759374336), and is used in ionic-site [here](https://github.com/ionic-team/ionic-site/blob/master/assets/stencil/ionic-search/arrow.svg.tsx) which gets called by the render function [here](https://github.com/ionic-team/ionic-site/blob/master/assets/stencil/ionic-search/ionic-search.tsx#L145)

**Comment by LostInBrittany** [comment]
I am getting the same error with the SVG logo I'm using in my app, with FF 61.0.1.
Do you have more info on it?

**Comment by adamdbradley** [comment]
Just be fixed in most recent versions
