### ISSUE TITLE
dev-server: Sass imported style changes not reflected in browser

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#1019]
**Stencil version:**

```
 @stencil/core@0.14.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

While serving, changes to `@import`-ed sass files are not reflected in the component in any browser. If the server is restarted or the `stencil.config.ts` file is modified (in any way), then the changes are reflected.

**Expected behavior:**

Changes made in any sass file are reflected in the output dynamically.

**Steps to reproduce:**

1. `git clone -b sass-issue git@github.com:cary-smith/stencil-component-starter.git`
1. npm install
1. open the src/components/my-component/_core.scss file
1. change the background color to your favorite shade of whatever
1. notice the color does not change in the output

**Related code:**
```tsx
```
**Other information:**

Checking back, this first manifested in version 0.10.1.

Did I miss some configuration?

**Comment by cary-smith** [comment]
If I were to start digging into the code, could you at least point me in the likely area/location that may be involved? I assume you folks are super-busy and I might be able to track it down and provide a PR if I can get some time?

**Comment by cary-smith** [comment]
Still evident in 0.13.0-0 unfortunately.

**Comment by kairos666** [comment]
+1 i need to constantly stop/start dev server if i work actively on sass styles

**Comment by MoAsmar** [comment]
+1

**Comment by RobertApplandeo** [comment]
+1

**Comment by adamdbradley** [comment]
Thanks for the repo case! Should be fixed up in the next release, thanks

**Comment by cary-smith** [comment]
Thanks for the fix!
