### ISSUE TITLE
CSS Properties fail to resolve in IE11 inside shadow: true components

### ISSUE THREAD

**Issue by mattdsteele** [ionic-team/stencil#1020]
**Stencil version:**

```
 @stencil/core@0.11.4
```

**I'm submitting a:**

[x] bug report

**Steps to reproduce:**
Demo repo: https://github.com/mattdsteele/stencil-ie11-shadow-props

The component is the standard starter (`shadow: true`) with a few styles around CSS custom props:

```
:host {
  --some-value: green;
}
div {
  --some-value: blue;
  background-color: var(--some-value);
}
```

In non-IE browsers (Chrome, FF, Edge) it works fine:
![image](https://user-images.githubusercontent.com/389077/44118155-d50ed924-9fda-11e8-9696-ec636379438b.png)

But no styles are applied in IE11:
![image](https://user-images.githubusercontent.com/389077/44118176-e58c71f8-9fda-11e8-99ae-dd8bdee0bbe8.png)

Here's the style tag that gets added to the head of the page in IE11:

`<style>div.sc-my-component{background-color:}</style>`

**Other information:**

This appears to have started with 0.11.0. I tried with 0.10.10 and it was working fine.

Switching to `shadow: false` fixes it, but most of our components are using Shadow DOM features, so it's not really a great workaround.

**Comment by grahamlucid** [comment]
I was seeing a similar issue caused by what looked like a couple of issues:
 
1. incorrectly named styles e.g. in the style tag at the top of the page the classes are `.foo-bar-elem`, `.button.foo-bar-elem` etc but the class that is added to the element itself is `.foo-bar-elem-0`

2. in my older version of the component-starter (that worked with shadowDOM) it added an attribute to the custom elem rather than a class

**Comment by slavicandreev** [comment]
I am having the same issue with Stencil 0.11+ 

:host styles are not being applied at all in IE

**Comment by manucorporat** [comment]
Thanks for reporting the issue, I am actively working on it

**Comment by manucorporat** [comment]
This should be fixed in next 0.13.0-0 version!

**Comment by mattdsteele** [comment]
Looks good in our real app. Thanks again!

**Comment by kevinlandsberg** [comment]
> This should be fixed in next 0.13.0-0 version!

Hey @manucorporat ,

it seems to work in version 0.13.0-0, but i tried it with version higher, 0.13.0-8 and then it didnt work again. Maybe some code was overwritten which is creating this issue again?
Please fix this in the newest version!

**Comment by mattdsteele** [comment]
@kevinlandsberg Hmm, I just tried 0.13.0-8 in my app, and it still seems to be working well there. Could you create a test case/modify mine to reproduce what you're seeing?

(I repurposed my repo, but the commit w/ the issue as I saw it is at https://github.com/mattdsteele/stencil-ie11-shadow-slot/tree/6f4aea9de0e57eec259fcbf78d27f7bf9cb6c7e0 )

**Comment by dvelasquez** [comment]
I'm having similar issues with ie11 and css-vars. The strange is how variables are finally updated in the dom:
```
html {
    font-size: 10px;
    height: 100%;
    --content-color: brown: ;
    --BORDER-SMALL: 1px: ;
    --BORDER-COLOR: #eaeaea: ;
    --GRID-XS: 4px: ;
    --GRID-S: 8px: ;
    --GRID-BASE: 16px: ;
    --GRID-L: 24px: ;
    --GRID-XL: 32px: ;
    --GRID-XXL: 48px: ;
    --TYPOGRAPHY-BASE-SIZE: 1.6em: ;
    --TYPOGRAPHY-BASE-LINE: 1: ;
    --COLOR-PRIMARY: #69f: ;
    --COLOR-SECONDARY: #58e: ;
    --COLOR-ACCENT: red: ;
    --COLOR-BACKGROUND: #ddd: ;
}
```
Notice that an extra ":" is added at the end.

**Comment by inigotoro** [comment]
> I'm having similar issues with ie11 and css-vars. The strange is how variables are finally updated in the dom:
> 
> ```
> html {
>     font-size: 10px;
>     height: 100%;
>     --content-color: brown: ;
>     --BORDER-SMALL: 1px: ;
>     --BORDER-COLOR: #eaeaea: ;
>     --GRID-XS: 4px: ;
>     --GRID-S: 8px: ;
>     --GRID-BASE: 16px: ;
>     --GRID-L: 24px: ;
>     --GRID-XL: 32px: ;
>     --GRID-XXL: 48px: ;
>     --TYPOGRAPHY-BASE-SIZE: 1.6em: ;
>     --TYPOGRAPHY-BASE-LINE: 1: ;
>     --COLOR-PRIMARY: #69f: ;
>     --COLOR-SECONDARY: #58e: ;
>     --COLOR-ACCENT: red: ;
>     --COLOR-BACKGROUND: #ddd: ;
> }
> ```
> Notice that an extra ":" is added at the end.

I'm experiencing the same issue with version 0.18.0 and the way vars are rendered in IE11:
:root {
    --progress-color:red: ;
    --current-value:20: ;
    --max-value:50: ;
    --hrwidth:50%: ;
}
But the strangest part is that in the style that gets added in the head, it looks ok:
<style>:root{--progress-color:red;--current-value:20;--max-value:50;--hrwidth:50%}</style>
