### ISSUE TITLE
Type Imports left in dist/collection directory

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/stencil#1021]
If you create a file at the base of the src directory and it imports types from components.d.ts then a reference to components.d.ts will be left around in the dist/collection directories.
```
import * from './components'
```

It appears that there is an issue in Typescript with removing type imports when a directory exists in the same src root.  You can recreate using the following dir structure. Where index.ts imports components.d.ts

- src/
  - components/
  - components.d.ts
  - index.ts

This can be avoided by renaming the componets.d.ts file to something else.

**Comment by cary-smith** [comment]
Should this be listed as a breaking change?

`package.json` - "types" needs to be modified on all libraries that wish to use them

**Comment by jthoms1** [comment]
More details and documentation when we do a release of 0.12.0.
