### ISSUE TITLE
EXDEV: cross-device link not permitted, rename

### ISSUE THREAD

**Issue by ezraroda** [ionic-team/stencil#1022]
Getting the following when initiating a new project:

`[user@BOX develop]$ uname -a
Linux BOX 4.17.14-202.**fc28**.x86_64 x86_64 x86_64 x86_64 GNU/Linux
[user@BOX develop]$ node -v
v8.11.4
[user@BOX develop]$ npm -v
6.4.0
[user@BOX develop]$ npm init stencil component my-components
npx: installed 1 in 0.917s
⠋ Preparing starter
✖ **EXDEV: cross-device link not permitted, rename '/tmp/stencil-starter-1534687735383' -> '/home/user/develop/my-components'**

[user@BOX develop]$ 
`

**Comment by manucorporat** [comment]
This should be fixed, can you try `npm init stencil` again?

**Comment by ezraroda** [comment]
It's working fine now !
