### ISSUE TITLE
Error: spawn npm ENOENT on npm init stencil

### ISSUE THREAD

**Issue by bboyle** [ionic-team/stencil#1024]
**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
getting "Error: spawn npm ENOENT" when running `npm init stencil`

**Expected behavior:**
Expect to get started with stencil (sounds awesome, would love to use it!)

**Steps to reproduce:**
- Windows 10
- PowerShell
- node v8.11.3
- npm v6.3.0
- run `npm init stencil`
- picker a starter (doesn't matter which)
- "Project name" prompt appears
- error appears after short delay

**Other information:**
```
√ Pick a starter » ionic-pwa
? Project name » (node:19308) UnhandledPromiseRejectionWarning: Error: spawn npm ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:19308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
```

Any help greatly appreciated. I've love to try out stencil for generating web components!

**Comment by manucorporat** [comment]
can you run:
```
 npm init stencil --info
```
and let me know what's the output?

**Comment by bboyle** [comment]
sure can :)

```
npm init stencil --info
npx: installed 1 in 3.583s
create-stencil: 1.6.9
```

**Comment by bboyle** [comment]
@manucorporat it's working now! woot!! :)
