### ISSUE TITLE
Improve inline code documentation

### ISSUE THREAD

**Issue by DominicBoettger** [ionic-team/stencil#1028]
**Stencil version:**

```
 @stencil/core@all
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently it's sometimes hard to get the information about what a function does when. It's often needed to reverse engineer the code to get the needed information about the flow of the core and it's function.

**Expected behavior:**

There should be a detailed description about the function above its signature.

**Steps to reproduce:**

Open for instance src/client/platform-main-legacy.ts to get an example.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by jthoms1** [comment]
Is this specific to exported library functions or is more when you are reading the internals?

**Comment by DominicBoettger** [comment]
Reading the internals.

**Comment by adamdbradley** [comment]
Thanks. PRs accepted.
