### ISSUE TITLE
Question: How to get element references inside of a component?

### ISSUE THREAD

**Issue by ryan-edge-ck** [ionic-team/stencil#103]
I would like to integrate a 3rd party plugin with my component.  Currently the only way to do that is by grabbing a reference in `componentDidLoad` to the element and then doing a query:

```
this.inputRef = this['__el'].querySelector('input')
```

I am not sure if this is the best way, and it also means I lose intellisense because the element is not a property on the component.  It would be nice if there was a decorator that we could use to do this, similar to Angular's [ViewChild](http://learnangular2.com/viewChild/)

**Comment by peterblazejewicz** [comment]
There is `Element` decorator available:
```tsx
class BaseClass {
    @Element() element: HTMLElement;

    componentDidLoad() {
        this.element.removeAttribute("unresolved");
    }
}
```

**Comment by ryan-edge-ck** [comment]
Awesome, I just saw the documentation had been updated. Closing
