### ISSUE TITLE
Problems importing some external js libs

### ISSUE THREAD

**Issue by Leonavas** [ionic-team/stencil#1037]
**Stencil version:**

```
@stencil/core@0.11.4
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Adding external js libraries such as sockjs-client and stomp-websocket results in random warnings and errors on browser console.

**Expected behavior:**
Being able to import third party js to my Stencil web component

**Steps to reproduce:**
npm init stencil
choose component
name it
confirm

npm i --save sockjs-client

at my-component.tsx add

import SockJS from 'sockjs-client';

 componentDidLoad() {
   let socket = new SockJS('https://url');
}

**Other information:**
Terminal warnings: 
`[52:27.1]  generate styles finished in 974 ms
preferring built-in module 'punycode' over local alternative at '(...)/my-component/node_modules/punycode/punycode.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'punycode' over local alternative at '(...)/my-component/node_modules/punycode/punycode.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'string_decoder' over local alternative at (...)/my-component/node_modules/string_decoder/lib/string_decoder.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'string_decoder' over local alternative at '(...)/my-component/node_modules/string_decoder/lib/string_decoder.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
[52:29.9]  module map finished in 3.84 s`

Browser console:
`TypeError: Cannot read property 'map' of null at my-component.js:13771 "http://localhost:3333/build/mycomponent/my-component.js" @mycomponent.core.js:2193`

**Comment by jthoms1** [comment]
Could you try with @stencil/core@latest? We made a recent change to correctly account for default exports in Typescript.

**Comment by shaneparsons** [comment]
@jthoms1 I'm having similar issues, and @latest (i.e. 0.12.4) doesn't fix it.

**Comment by bitflower** [comment]
Are you sure SockJS exports what you import? Have you tried `import * as SockJS from 'sockjs-client';` or `import {SockJS} from 'sockjs-client';` ?

**Comment by shaneparsons** [comment]
I'm not actually using sockjs, but I have the same `punycode` and `string_decoder` errors with both [node-soap](https://github.com/vpulim/node-soap#readme) and [easy-soap-request](https://github.com/circa10a/easy-soap-request#readme). I've tried all forms of import, and it seems to see the libraries properly... it just errors out when I begin calling anything from them.
