### ISSUE TITLE
Silent rendering errors

### ISSUE THREAD

**Issue by threeaccents** [ionic-team/stencil#1038]
**Stencil version:**

```
 @stencil/core@<0.11.0>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When trying to return JSX from the `.map` function the component execution freezes.

**Expected behavior:**

The returned JSX should be added to the DOM.

**Steps to reproduce:**

**Related code:**

```tsx
// The components
import {Component, Prop} from '@stencil/core';

export interface SoliTabsHeader{
  key: string;
  value: string;
}

@Component({
  tag: 'soli-tabs',
  styleUrl: 'soli-tabs.scss',
  // shadow: true
})
export class SoliTabs {
  @Prop() headers: SoliTabsHeader[];

  render() {
    return (
      <div class={`soli-tabs__component`}>
        <div class="soli-tabs__header">
          {this.headers.map((h) => <div class="soli-tabs__header-item">{h.value}</div>)}
        </div>
        <div class="soli-tabs__body">
          <slot />
        </div>
      </div>
    );
  }
}

// The headers map function is returning JSX and for some reason the component won't load. If I however change the code to not return JSX it's displayed.

<div class="soli-tabs__header">
   {this.headers.map((h) => {
      console.log(h) // logs the correct header value
   })}
</div>

```

**Other information:**

No error is thrown in the console. When I inspect element I can see the component is attached with the correct css, the template for the component is not attached though.

**Comment by threeaccents** [comment]
Hello it seems naming the variable from the map `h` was causing the issue. Seems like maybe a JSX issue then. If I change the variable name to anything else it works.

**Comment by bitflower** [comment]
h is from `hyperscript` or something I guess. Don't use it.

**Comment by jthoms1** [comment]
Ya, h is a globally registered variable.  Thinking we will require this as an import in the future to reduce confusion.
