### ISSUE TITLE
SEO Stencil creates invalid html

### ISSUE THREAD

**Issue by DominicBoettger** [ionic-team/stencil#1039]
**Stencil version:**

```
>  @stencil/core@0.11
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Stencil creates invalid html. Tested with the w3c validator the following problems exists:

1. ssr attribute is not allowed on html
2. The inlined CSS has :host elements embedded.
3. The meta charset is after the first 1024 bytes because rendered after the inlined CSS.

**Expected behavior:**
Create valid html according to the spec.

**Comment by DominicBoettger** [comment]
I think 2. is created because the stylesheets for shadow components are also inlined.

**Comment by adamdbradley** [comment]
Should be fixed in most recent versions
