### ISSUE TITLE
Decorators do not work with arrow functions

### ISSUE THREAD

**Issue by hartjus** [ionic-team/stencil#1041]
**Stencil version:**

```
 @stencil/core@ 0.11.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm not sure if this is actually a bug (might be more of a question), but do the decorators work with Arrow functions?  For example, if I have the following code, the function never fires as expected.
```ts
@Listen('document:click')
myFunction = (event) => {
  ...
}
```

However, if I make it a class member, it does work.
```ts
@Listen('document:click')
myFunction (event) {
  ...
}
```

Is this just something that needs to be added to the documentation?  Or is this a bug?

**Comment by jthoms1** [comment]
'@Listen' is a method decorator.  We could probably change the type code to check this and throw an error when used incorrectly.

https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators

**Comment by hartjus** [comment]
Makes sense.  If there's some sort of type checking to add, that would be great (or a note in the docs!).  I appreciate the response!

**Comment by jthoms1** [comment]
I have added types and they should be available in the next release. 99d058e821181dee36af0793e3f47584e0bb60e8
