### ISSUE TITLE
Import of node_modules/@stencil/core/dist/src/global.js fails

### ISSUE THREAD

**Issue by mazlano27** [ionic-team/stencil#1044]
**Stencil version:**

```
 @stencil/core@0.12.1 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

After upgrading to stencil 0.12.1, running the npm run build command generates the following warnings in the terminal: 

[ WARN  ]  build warn '/PROJECT_PATH/node_modules/@stencil/core/dist/src/global.js' is imported by node_modules/@firebase/polyfill/dist/index.esm.js, but could not be resolved – treating it as an external dependency

[ WARN  ]  build warn '/PROJECT_PATH/node_modules/@stencil/core/dist/src/global.js' is imported by node_modules/@firebase/auth/dist/auth.esm.js, but could not be resolved – treating it as an external dependency

[ WARN  ]  build warn '/PROJECT_PATH/node_modules/@stencil/core/dist/src/global.js' is imported by node_modules/process-es6/browser.js, but could not be resolved – treating it as an external dependency

The project does not render in chrome, and the console shows the following error:
GET http://localhost:3333/build/node_modules/@stencil/core/dist/src/global.js 404 (Not Found)

**Expected behavior:**

The project should compile successfully.

**Steps to reproduce:**

**Related code:**

**Other information:**

• Downgraded back to v0.11.4 and everything works again.
• Checked @stencil/core/dist directory and there is no src folder.

**Comment by jthoms1** [comment]
Thanks we have had another report that might be related. Do you have a repo that I could take a look at to try to debug?

**Comment by DominicBoettger** [comment]
Same issue here

**Comment by kensodemann** [comment]
https://github.com/kensodemann/kws-weather-widgets

Check out the `bug/autofprefixer` branch...

**Comment by jomido** [comment]
Here's a small example: https://github.com/jomido/stencil-global-js-bug

The usage of a 3rd-party library, in combination with Stencil, causes this issue. Stencil alone does not exhibit the behaviour, and neither does the 3rd party (alone). The 3rd-party library is `es6-tween`. Maybe a rollup issue?

**Comment by DominicBoettger** [comment]
@jthoms1 I think this is fixed in 0.12.2, right?

**Comment by mazlano27** [comment]
@jthoms1 @DominicBoettger Just upgraded to 0.12.2 and the issue seems to have resolved for me. Thank you!

**Comment by jthoms1** [comment]
This is fixed in 0.12.2
