### ISSUE TITLE
Config `outputTargets` Type

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#1045]
**Stencil version:**

```
 0.12.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

If the `outputTargets` is defined as a variable and included in the config structure, an error is provided:

```tsx
import { Config } from '@stencil/core';
import { postcss } from '@stencil/postcss';
import autoprefixer from 'autoprefixer';

const outputTargets = [
  {
    type: 'dist'
  },
  {
    type: 'www'
  }
];

export const config: Config = {
  namespace: 'kwsweather',
  outputTargets,
  // outputTargets: [
  //   {
  //     type: 'dist'
  //   },
  //   {
  //     type: 'www'
  //   }
  // ],
  autoprefixCss: true,
  plugins: [
    postcss({
      plugins: [autoprefixer()]
    })
  ]
};
```

The error says: 

```
[ts]
Type '{ type: string; }[]' is not assignable to type 'OutputTarget[]'.
  Type '{ type: string; }' is not assignable to type 'OutputTarget'.
    Type '{ type: string; }' is not assignable to type 'OutputTargetDist'.
      Types of property 'type' are incompatible.
        Type 'string' is not assignable to type '"dist"'.
```

This occurs in the editor but does not appear to have any effect on the build.

**Expected behavior:**
No error

**Steps to reproduce:**

1. git clone git@github.com:kensodemann/kws-weather-widgets.git
1. git checkout bug/autoprefixer
1. have a look at `stencil.config.ts` file
1. switch over to defining inline instead of in a variable, everything is fine

**Other information:**

The person I am working with needs to be able to define the `outputTargets` in a variable since they need to be able to conditionally push targets based on whether running in CI or not.

**Comment by juanmiguelbesada** [comment]
Hi!
You can fix this error setting the type of  outputTargets to outputTargets[]

```tsx
import { Config } from '@stencil/core';
import {OutputTarget} from "@stencil/core/dist/declarations";

// https://stenciljs.com/docs/config

const outputTargets = [
  {
    type: 'dist'
  },
  {
    type: 'www'
  }
];


export const config: Config = {
  outputTargets: outputTargets as OutputTarget[],
  globalStyle: 'src/global/app.css',
};
```
or
```tsx
import { Config } from '@stencil/core';
import {OutputTarget} from "@stencil/core/dist/declarations";

// https://stenciljs.com/docs/config

const outputTargets: OutputTarget[] = [
  {
    type: 'dist'
  },
  {
    type: 'www'
  }
];


export const config: Config = {
  outputTargets: outputTargets,
  globalStyle: 'src/global/app.css',
};

```

**Comment by manucorporat** [comment]
This is hard to solve, since this type checking is not performed by stencil but directly by typescript. It's might be already fixed in the latest version of TS
