### ISSUE TITLE
Component render method not triggered consistently when using Firefox (ver 61.0.1) in my app

### ISSUE THREAD

**Issue by amittapalli** [ionic-team/stencil#1048]
**Stencil version:**

```
 @stencil/core@0.12.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The stencil component's render method is not getting triggered consistently in firefox.  It triggers consistently when testing it isolated in an index.html file though.  Our component is hosted inside an iframe as well.  I would refresh the page, render gets called, next time load or refresh the same page, render method does not get called, another time it does.  There is no clear pattern.

**Expected behavior:**

The component's render method should fire all the time similar to Chrome and Safari browsers.

**Steps to reproduce:**

**Related code:**

```tsx
import { Component, Element } from '@stencil/core';


@Component({
  tag: 'commerce-threecolumnlayout',
  styleUrl: 'three_column_layout.css',
  shadow: false
})

export class ThreeColumnLayout {

  @Element() elt: HTMLElement;
  @Element() el!: HTMLStencilElement;
  numberofcolumns=1;

  constructor() {
  }
  
  componentWillLoad() {
    this.numberofcolumns = 3
  }

  render(){
    alert("hi");
    return (
      <div style={{backgroundColor:'red'}}>
          <div class="dynamic-column-layout-section section group">
            <div class ="section-column span_1_of_3">
              <slot name= "region1"></slot>
          </div>
          <div class ="section-column span_1_of_3">
              <slot name= "region2"></slot>
          </div>
          <div class ="section-column span_1_of_3">
              <slot name= "region3"></slot>
          </div>
        </div>
      </div>
    )
  }
}
```

**Other information:**

I tried to add the following as well but still not consisten (when running inside an iframe)
  componentDidLoad() {
    this.el.forceUpdate();
  }

**Comment by coopaq** [comment]
Maybe a very old Firefox bug which is still relevant:

https://bugzilla.mozilla.org/show_bug.cgi?id=356558

Work around:
<iframe src="webpage2.html?var=xxx" id="theframe"></iframe>

<script>
var _theframe = document.getElementById("theframe");
_theframe.contentWindow.location.href = _theframe.src;
</script>

**Comment by manucorporat** [comment]
We can't not reproduce this issue, according our test everything is working fine in Stencil 1.0 in firefox!
