### ISSUE TITLE
TypeError: newLocation is undefined, ES5 Builds

### ISSUE THREAD

**Issue by ctrlshp** [ionic-team/stencil#1051]
**Stencil version:**

```
 @stencil/core@0.12.4
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When building with "stencil build --dev --watch --serve --es5", I am getting a "TypeError: newLocation is undefined" in the browser's console (Firefox 61.0.2 on macOS 10.13.6). And the page doesn't display anything within the stencil-router.

**Expected behavior:**

I just upgrade to @stencil/core 0.12.4 from 0.11.4 this morning and with 0.11.4 I could run the dev build in Firefox with no problem. The only thing that changed was @stencil/core (@stencil/router remained at 0.2.5).

**Steps to reproduce:**

Simply run ""stencil build --dev --watch --serve --es5" for an app using stencil-router and open in Firefox.

**Comment by jthoms1** [comment]
@ctrlshp This should be fixed with @stencil/router 0.2.6.  Just released.

**Comment by ctrlshp** [comment]
I confirm that the use case reported above now works with @stencil/router 0.2.6. Thanks !
