### ISSUE TITLE
Stenicl + AWS Amplify gives json parse error

### ISSUE THREAD

**Issue by gireeshkumar** [ionic-team/stencil#1053]
Getting below JSON parsor error when using Stencil with latest AWS amplify

My package.json

> {
  "name": "@ionic/pwa-toolkit",
  "private": true,
  "version": "0.0.1",
  "description": "Ionic PWA Toolkit",
  "files": [
    "dist/"
  ],
  "scripts": {
    "build": "stencil build",
    "start": "stencil build --dev --watch --serve",
    "start.sw": "npm run start --service-worker",
    "test": "jest",
    "test.watch": "jest --watch"
  },
  "dependencies": {
    "@ionic/core": "4.0.0-beta.6",
    "@stencil/core": "0.12.3",
    "aws-amplify": "^1.0.8"
  },
  "devDependencies": {
    "@types/jest": "^22.2.2",
    "jest": "^22.4.3",
    "rollup-plugin-json": "^3.0.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ionic-team/ionic-pwa-toolkit.git"
  },
  "author": "Ionic Team",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/ionic-team/stencil"
  },
  "homepage": "https://github.com/ionic-team/ionic-pwa-toolkit",
  "jest": {
    "transform": {
      "^.+\\.(js|ts|tsx)$": "<rootDir>/node_modules/@stencil/core/testing/jest.preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(tsx?|jsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json",
      "jsx"
    ]
  }
}

``
preferring built-in module 'url' over local alternative at '/Users/gireeshkumar/dev/pwa-ionic/pwa01/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
[43:07.7]  generate app files finished in 3.15 s

[ WARN  ]  build warn
           'url' is imported by node_modules/@aws-amplify/core/lib/Signer.js, but could not be resolved – treating it
           as an external dependency

[ WARN  ]  build warn
           'url' is imported by node_modules/@aws-amplify/api/lib/RestClient.js, but could not be resolved – treating
           it as an external dependency

[ WARN  ]  build warn
           'url' is imported by commonjs-external:url, but could not be resolved – treating it as an external
           dependency

[ ERROR ]  Parse Error: node_modules/aws-sdk/apis/s3-2006-03-01.paginators.json:2:14
           Unexpected token

      L1:  {
      L2:    "pagination": {
      L3:      "ListBuckets": {

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ionic/pwa-toolkit@0.0.1 build: `stencil build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ionic/pwa-toolkit@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gireeshkumar/.npm/_logs/2018-09-01T09_43_07_857Z-debug.log
``

**Comment by bubbleupdotnet** [comment]
I am also having this issue.

**Comment by jthoms1** [comment]
If you could create an example repo based on https://github.com/ionic-team/stencil-app-starter/ I could troubleshoot? Thank you!

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
