### ISSUE TITLE
[DISCUSSION] Documentation tool

### ISSUE THREAD

**Issue by vogloblinsky** [ionic-team/stencil#1056]
**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

I am the author of Compodoc, documentation tool for Angular applications. 

Someone requested the support of Stencil components. There is an issue on that in the repository : https://github.com/compodoc/compodoc/issues/640

I have started my tests with this application : https://github.com/jgw96/stencil-beer

Did you have links to others application build with Stencil that i can test also with Compodoc ?

The last thing i have to enhance in Compodoc is a correct display of all the decorators for a property or a function inside the component codebase. 
Do you have any example of a great design or existing documentation in another language using decorators or annotations that i can watch to update the display/design of compodoc for this.

**Comment by peterennis** [comment]
I have a stencil PWA test app here: https://aesvg.adaept.com/
Repo: https://github.com/peterennis/ae-svg-components

The stencil site is also a PWA using stencil :)
https://github.com/ionic-team/stencil-site/

**Comment by vogloblinsky** [comment]
Thanks @peterennis i will add them in my tests.
