### ISSUE TITLE
Component Types File ignores tsconfig compilerOptions.paths

### ISSUE THREAD

**Issue by tomsaunders** [ionic-team/stencil#1062]
**Stencil version:**

```
 @stencil/core@0.11.4 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
My project uses the tsconfig.json compilerOptions.paths to allow imports from the `src` folder down
```
"paths": {
      "*": ["src/*"]
    }
```
which allows an import like `components/` rather than `../../components` 

The generated component types file doesn't do anything to these imports, which means it can't be used as a library by another project because the imports don't resolve.

**Expected behavior:**

When the component types file is generated, it re-writes paths in the same way as the pathsResolver function used as a rollup plugin.

**Steps to reproduce:**

1. tsconfig.json as above
2. Make a component with a @Prop that uses a type imported with a non-relative reference.
e.g. 
```
import { DataType } from 'model/data-type' 
...
@Prop data: DataType
```
3. view generated components / generated.d.ts

**Comment by jthoms1** [comment]
Could you create a simple repo based on https://github.com/ionic-team/stencil-component-starter to show the issue? Thank you!

**Comment by tomsaunders** [comment]
Here you go: https://github.com/tomsaunders/stencil-tsconfig-repro

I found a thing with sass imports as well so that's also reproduced.

**Comment by woodgear** [comment]
how about this issue now?

**Comment by adamdbradley** [comment]
Should be fixed in most recent versions
