### ISSUE TITLE
Testing: @Method promise warning breaks jest tests

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#1064]
**Stencil version:**

```
 @stencil/core@0.13.0-0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running tests, components with `@Method()` now break regardless of async or promise return types with the error:

```console
External @Method() getSomething() should return a Promise or void.

     Consider prefixing the method with async, such as @Method async getSomething().
     Next minor release will error.
```

**Expected behavior:**

Should warn but not break the tests.

**Steps to reproduce:**

1. Clone the [stencil-component-starter](https://github.com/ionic-team/stencil-component-starter)
1. Update the stencil version to `0.13.0-0`
1. Run `npm i`
1. Add an `@Method` decorated method to my-component
1. Execute `npm test`

**Related code:**

```tsx
import { Component, Method, Prop } from "@stencil/core";

@Component({
  tag: "my-component",
  styleUrl: "my-component.scss",
  shadow: true
})
export class MyComponent {
  @Prop() 
  first: string;
  @Prop()
  last: string;

  /** This still throws a warning even with the prefix of "async" */
  @Method()
  async getSomething(): Promise<string> {
    return Promise.resolve("something");
  }

  render() {
    return (
      <div>
        Hello, World! I'm {this.first} {this.last}
      </div>
    );
  }
}
```

**Other information:**

[Clonable example if needed](https://github.com/cary-smith/stencil-sass-parent-issue/tree/stencil-method-test-issue)

**Comment by jthoms1** [comment]
This has been fixed in 0.13.0-4. Thanks!
