### ISSUE TITLE
Slotting a select element in a shadow:true component breaks in IE11

### ISSUE THREAD

**Issue by mattdsteele** [ionic-team/stencil#1066]
**Stencil version:**

```
 @stencil/core@0.13.0-3
```

**I'm submitting a:**

[x] bug report

**Current behavior:**

When slotting a `<select>` element into a component defined as a `shadow: true`, it fails in IE11. Elements are rendered out-of-order, and generate syntax errors. The problem is catastrophic in some environments such as Angular apps.

**Steps to reproduce:**

**Repro**: https://github.com/mattdsteele/stencil-ie11-shadow-slot

Component has a simple template: https://github.com/mattdsteele/stencil-ie11-shadow-slot/blob/master/src/components/my-component/my-component.tsx

And is used with a select element: https://github.com/mattdsteele/stencil-ie11-shadow-slot/blob/master/src/index.html

To reproduce, run `npm i`, `npm run start -- --es5`

In other browsers (Edge, FF, Chrome):
![image](https://user-images.githubusercontent.com/389077/45125543-902bb780-b134-11e8-9e75-e3f054c451e7.png)

IE11:
![image](https://user-images.githubusercontent.com/389077/45125547-9883f280-b134-11e8-95f1-3bd5f1f1da16.png)

Error in IE11:

```
Error: Invalid argument. 8 MY-COMPONENT
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid argument.",
      message: "Invalid argument.",
      name: "Error",
      number: -2147024809,
      stack: "Error: Invalid argument.
   at domApi.$remove (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:264:9)
   at patch (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:1430:13)
   at render (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:762:9)
   at renderUpdate (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:853:5)
   at update (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:847:7)
   at Anonymous function (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:801:9)
   at consume (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:1542:9)
   at Anonymous function (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:1583:11)
   at v (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:60:1795)
   at Anonymous function (http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:60:303)"
   }
   8
   "MY-COMPONENT"
```

**Other information:**
Other form elements seem to be okay, it just seems to be the `<select>` element that breaks things. I'm not sure when this began, but I started noticing it when upgrading from Stencil 0.10 to 0.13.

This end up having more catastrophic breakage in our Angular 6 app; our component doesn't render at all.

Here's a JSBin showing the issue with Ionic as well: https://output.jsbin.com/tadixehuwa

Possibly related: #874

**Comment by DMartMD** [comment]
This does seem to be the same issue as mine ([874](https://github.com/ionic-team/stencil/issues/874)).  Feel free to mark mine as duplicate.

**Comment by mattdsteele** [comment]
I've narrowed the issue down to:

* In IE11
* `<select>` elements
* That are slotted into a `shadow: true` component
* That are *not* contained within a `<form>` element.

So this continues to fail:

```html
<my-component>
  <select></select>
</my-component>
```

But this appears to be OK:

```html
<my-component>
  <form>  
    <select></select>
  </form>
</my-component>
```

I've updated [my test repo](https://github.com/mattdsteele/stencil-ie11-shadow-slot/blob/master/src/index.html#L28) to demonstrate this subtlety.

**Comment by CSchulz** [comment]
This also breaks with Stencil 1.1.3 and we have to support IE11.
