### ISSUE TITLE
Shadow DOM mode as closed - Event Emitter not working

### ISSUE THREAD

**Issue by chukwu** [ionic-team/stencil#1069]
I noticed after publishing/adding my stencil chat application component into my project, my event emitter stopped working. This is because there is a javascript plugin (Slim.js - image cropping plugin) in my project which conflicts with event emitters on stencil. I can't listen to my stencil event emitter due to this.

The block of code from the Slim.js image cropping plugin that is causing the break is below:
```
function t(t, i) {
    i = i || {
            bubbles: !1,
            cancelable: !1,
            detail: e
        };
    var n = document.createEvent("CustomEvent");
    return n.initCustomEvent(t, i.bubbles, i.cancelable, i.detail), n
}
t.prototype = window.CustomEvent.prototype, window.CustomEvent = t
```

The last line to be precise.

When i turn off shadow i.e set it to _false_. Everything works but my DOM elements are vulnerable to CSS overrides externally.

After abit of study, i considered trying to set the shadow root mode from open to closed. Unfortunately, I can't seem to do this because the mode property of shadow root is readonly.

What can i do?
Below is what i tried.
```
    if(this.chatEl.shadowRoot){
      let shadowRoot:any = this.chatEl.shadowRoot;
      shadowRoot.mode = "closed";
    }
```

**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
    if(this.chatEl.shadowRoot){
      let shadowRoot:any = this.chatEl.shadowRoot;
      shadowRoot.mode = "closed";
    }
```

**Other information:**

**Comment by jthoms1** [comment]
ShadowRoot closed vs open just defines whether you should be able to use javascript to access/modify the contents of a ShadowRoot it does not affect global browser APIs. Setting it to closed would not prevent this from occurring.
