### ISSUE TITLE
External lib included causes duplicate TS helpers and runtime error

### ISSUE THREAD

**Issue by MrAntix** [ionic-team/stencil#1080]
**Stencil version:**

```
 @stencil/core@0.13.0-7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Rxjs gets included in built component this includes a "function __external"
TS helper var _external is also emitted and they clash causing runtime error

**Expected behavior:**

**Steps to reproduce:**

1. yarn build the lib
2. yarn build the components
3. navigate to ./components/dist/esm/es5/build/my-component.js  - file contains duplicates described

I made a repro repo and included the built files
https://github.com/MrAntix/stencil-ts-duplicate-helper/blob/master/components/dist/esm/es5/build/my-component.js
https://github.com/MrAntix/stencil-ts-duplicate-helper

**Related code:**

see image lines 1 and 36

**Other information:**

![image](https://user-images.githubusercontent.com/873305/45327438-72ed5380-b54f-11e8-9d06-d941294690da.png)

**Comment by MrAntix** [comment]
Hello, may I get some steer on this, its completely blocking me
I have no idea if its something I can sort, Stencil can sort or its a problem in another lib

I can look to get round it by finding an removing the duplicates in a build step on my libs
but before I embark on that it would be great to get the Stencil teams opinion?

**Comment by MrAntix** [comment]
Workaround

stencil.config.ts

```
import { Config } from '@stencil/core';
import postprocess from 'rollup-plugin-postprocess';

export const config: Config = {
  namespace: 'muse-ui-dugout-components',
  outputTargets: [
    {
      type: 'dist'
    }
  ],
  plugins: [
    postprocess([
      [
        `function __extends\\(`,
        'function xx__extends ('
      ]
    ])
  ],
  globalScript: 'src/global'
};
```

**Comment by jthoms1** [comment]
@manucorporat I believe you were looking into this.

**Comment by MrAntix** [comment]
if we add importHelpers to the transpile for the es5 worker the code produced works file
but when the global script is wrapped the import ends up inside the wrapper
I did this to move it back out

https://github.com/ionic-team/stencil/commit/e298edb0b21357f93c007385e40fac58fdf3abad

**Comment by MrAntix** [comment]
is this in danger of being auto-closed?

**Comment by MrAntix** [comment]
Has anyone had a chance to look at this?

**Comment by MrAntix** [comment]
FYI using the version 14.0.0-1 works fine, however, the code produced causes the angular compiler to fall over

see https://github.com/angular/angular-cli/issues/12568

**Comment by adamdbradley** [comment]
The original issue should be fixed with the latest build. Thanks for the report.
