### ISSUE TITLE
Stencil components don't properly support cloning via cloneNode

### ISSUE THREAD

**Issue by maxjustus** [ionic-team/stencil#1083]
**Stencil version:**
```
 @stencil/core@0.12.4
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Using Stencil with Turbolinks I'm seeing all mounted components that don't use shadow DOM have their markup duplicated when Turbolinks renders a cached preview of a page. The root tag of each component isn't duplicated, but all of the markup inside of it is. The way Turbolinks caches pages for render is by doing `cloneNode(true)` on body. I've tried modifying the code to clone the components individually, but the behavior is the same. It seems that Stencil components don't handle being cloned properly. If I switch the components to use shadow DOM the issue no longer appears, but in my case that's not an option.

**Expected behavior:**
When a Stencil component is cloned using `cloneNode` I would expect that the stencil renderer would be able to handle it properly, or that stencil could provide some alternative means of cloning components.

**Steps to reproduce:**
Given an already hydrated component:

```
import { Component } from '@stencil/core';

@Component({ tag: 'my-cool-component' })
export class MyCoolComponent {
  render() {
    return <div>this should only appear once</div>
  }
}
```

```
<my-cool-component class="hydrated">
  <div>this should only appear once</div>
</div>
```

When I run this code:

```
var component = document.querySelector("my-cool-component");
component.replaceWith(component.cloneNode(true));
```

The component's markup becomes:

```
<my-cool-component class="hydrated">
  <div>this should only appear once</div>
  <div>this should only appear once</div>
</div>
```

**Comment by maxjustus** [comment]
This is also an issue when trying to use stencil components in conjunction with Draggable JS, since it uses cloneNode to create the mirror elements for dragging.

**Comment by johannesjo** [comment]
Can confirm this issue. This makes stencil effectively incompatible with a lot of 3rd party libs.
