### ISSUE TITLE
Improve collection-manifest.json methods and events properties

### ISSUE THREAD

**Issue by dpellier** [ionic-team/stencil#1085]
**Stencil version:**

```
 @stencil/core@0.13.0-8
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The collection-manifest.json generated contains a `methods` and `events` for each components of the bundle.
But of these only contains the `name` of the method/event.

I am using this file to generate a documentation website of a lib of stencil component, and I need to display more info than just the name of method/event.
One possibility would be to add some jsdoc on top of the Method.Event decorator but I find this pretty lame as all those info are already available with Typescript (which also ensure you'll always get the right value, as the jsdoc can easily get outdated if people forget to change the value there also).

**Expected behavior:**

It should be possible to expose more information like the return type and the list of arguments expected by the method.
All this info are available when transpiling the code and getting the metadata.
https://github.com/ionic-team/stencil/blob/master/src/compiler/transpile/datacollection/method-decorator.ts

**Steps to reproduce:**

Let's take a very basic component that expose a public method:
```
import { Component, Method, Prop } from '@stencil/core';

@Component({
	tag: 'dummy-component',
})
export class Dummy {
	@Prop() private someProp: string;

	@Method()
	public async dummy(str: string): Promise<boolean> {
		console.log(str);
		return true;
	}

	protected render(): JSX.Element {
		return (
			<span>{ this.someProp }</span>
		);
	}
}
```

This is the collection-manifest.json file generated:
```
{
  "components": [
    {
      "tag": "dummy-component",
      "dependencies": [],
      "componentClass": "Dummy",
      "componentPath": "dummy.js",
      "styles": {},
      "props": [
        {
          "name": "someProp",
          "type": "String",
          "attr": "some-prop"
        }
      ],
      "methods": [
        {
          "name": "dummy"
        }
      ]
    }
  ],
  "collections": [],
  "compiler": {
    "name": "@stencil/core",
    "version": "0.13.0-8",
    "typescriptVersion": "2.9.2"
  },
  "bundles": []
}
```

Would be nice to get something like:
```
"methods": [
  {
    "args": [
      { "name": "str", "type": "string" }
    ]
    "name": "dummy",
    "return": "Promise<Boolean>"
  }
]
```

**Other information:**

I would be glad to do a PR for that if the feature make sense for you;

**Comment by jthoms1** [comment]
Have you tried running `stencil build --docs` in order to get this information?  This will generate markdown files that correspond to each component.  It will get type info and jsdoc.

**Comment by dpellier** [comment]
Running `stencil build --docs` just generate the following in the md file:
```
## Methods

| Method  | Description |
| ------- | ----------- |
| `dummy` |             |
```

The idea is not to rely on markdown file, but on the manifest that already contain a lot of info regarding each component.

**Comment by adamdbradley** [comment]
This has since been improved. Thanks.
