### ISSUE TITLE
Feature: Add ability to disable lazy loading

### ISSUE THREAD

**Issue by chimon2000** [ionic-team/stencil#109]
Description of the Problem
it would be nice if it was possible to disable lazy loading of the components.

My use case is simple: I have an existing application that I would like to slowly move to using web components.  Speed is not a concern (we already load jQuery & jQueryUI on every page request so the 90kb I'm loading with stencil is negligible.  A configuration option of `lazy: false` would be awesome.  It would allow me to inject my bundles into the head of an existing html file.  

It would also be nice if I could configure the bundle names as I see fit.

**Comment by jgw96** [comment]
Hello! So just a question, is lazy loading causing an issue for you?

**Comment by adamdbradley** [comment]
You can just add the one file which stencil created and it'll manage loading all of the components you'll need. Going to close this for now since we've found that lazy loading has more pros than cons.

**Comment by uilyam** [comment]
By the one file stencil creates, I assume you mean (default config) "www/build/app.js"? In that file, it hard codes the paths to load, example "/build/app/app.96qsofmx".  This is fine in situations where you control the directory structure, but my situation is that I want to distribute these components without the need to specify a structure for them to use.  My situation is similar to [Issue 128](https://github.com/ionic-team/stencil/issues/128), and would mostly be resolved if I could turn off lazy load. Thanks again for this tremendous project!

**Comment by laurentperroteau** [comment]
@jgw96 , yes, the lazy load can cause issue. In webapp mode (in browser) in our project we allow access to some page offline... so if the user goes to a page for the first time without network, the chunk of the page is not found : ```Error: Loading chunk 24 failed```. Would be nice an option to disable it on some page/component.
