### ISSUE TITLE
JSX.IntrinsicElements error with typescript and react

### ISSUE THREAD

**Issue by ywwu1** [ionic-team/stencil#1090]
**Stencil version:**

```
@stencil/core@0.12.4
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I upgrade to version `@stencil/core@0.12.4`,  the latest typescript,  react, react-dom, and associated typings. After building the stencil component in it's own repo I imported the component using `defineCustomElements`, however typescript is throwing an error `Property 'hello-world' does not exist on type 'JSX.IntrinsicElements'` when I try to start the project.

**Expected behavior:**

There should be no errors.

**Steps to reproduce:**

I have created a repo demonstrating the bug, here.
https://github.com/ywwu1/__stencil-react-typescript-jsx-issue

The stencil component is located here.
https://github.com/ywwu1/hello-world

**Comment by hartjus** [comment]
I'm running into this issue as well.  I noticed that the typings for JSX in Typescript were removed in `0.12.4`.  Is there a recommended way to integrate built stencil components into a react/typescript application?  Do I need to author my own `d.ts` to get around the compile errors?

**Comment by cbyte** [comment]
Same problem here. I created manually an components.d.ts in the root folder of the project to define the element declarations by hand. This is not a good solution overall, but works for the moment.

Now i step into the problem, how to include multiple compiled packages, because `defineCustomElements()` cannot be called multiple times - it throws the error `Uncaught (in promise) TypeError: Cannot redefine property: queue`.

Here is the self defined component.d.ts as temporarily solution to include one compiled stencil package:

```
import { Components } from "@ionic/core";

declare global {
  namespace JSX {
    interface IntrinsicElements {
       [...]
      "ion-toggle": Components.IonToggleAttributes;
      "ion-toolbar": Components.IonToolbarAttributes;
      "ion-virtual-scroll": Components.IonVirtualScrollAttributes;
    }
  }
}
```

**Comment by lcgreen** [comment]
Also experiencing the same issue, is there no update on this?

**Comment by Dohxis** [comment]
+1

**Comment by Dohxis** [comment]
We are experiencing this as well.

**Comment by maraisr** [comment]
Bumping +1

**Comment by arjunyel** [comment]
Anyone have a workaround?

**Comment by Dohxis** [comment]
Right now we maintain our own types.d.ts file

**Comment by edgarordonez** [comment]
I found the same error when I was updating my library :( If you see something... I'll appreciate your help.

Thanks! 🙏

**Comment by alex-hall** [comment]
Any movement on this? 

Have gone with the following hack for now: 

```
//jsx-interfaces.d.ts
declare namespace JSX {
    interface IntrinsicElements {
        [tagName:string]: any
    }
}
```

Which basically just turns off Typescript JSX validation. NOTE: I do NOT like this solution. 

I feel like i'm missing something obvious here, as all of the types are seemingly defined in: 

<my_stencil_component>/dist/types/components

But I can't seem to get create-react-app to recognize them or import them.

**Comment by hartjus** [comment]
@alex-hall We ended up having to author (actually generate) our own d.ts for any stencil components that we pulled into our project.  Stencil is generating *most* of the type definitions required, however there's the last step of adding the JSX tag into the global definitions.

Here's the basic structure of what we generated:

```
import {Components as SomeOtherName} from 'your-stencil-component';

declare global {
    namespace JSX {
        export interface IntrinsicElements {
            'your-component-tag': SomeOtherName.YourComponentAttributes;
        }
    }
}
```

While this works, it's definitely not ideal.

**Comment by alex-hall** [comment]
Gotcha, Thanks for the quick response. 

I felt like I was doing the right thing but nothing was working. Your explanation makes a lot of sense.

**Comment by SimoneIrato** [comment]
Did anybody find a solution for this problem? Actually when using StencilJs in a monorepo, JSX typings from Stencil conflicts with those from React

**Comment by manucorporat** [comment]
Upcoming version of stencil will completely solve this problem by using locally scoped JSX namespaces, a new feature of typescript!

**Comment by vidarc** [comment]
@manucorporat has that made it in stencil/core version 1 yet? i'm currently using alpha 5, but not really seeing a way to get the typing in my react project to work. i can easily just ignore it by using one of the examples above and basically setting the component to an any type. would certainly prefer to not do that.

using any of my stencil components, like `<ma-icon>`, just gives the `Property 'ma-icon' does not exist on type 'JSX.IntrinsicElements'.` error

**Comment by manucorporat** [comment]
Stencil one uses locally scoped JSX, which is the final solution to the root of the problem, global styles conflicting with each other

**Comment by nireak** [comment]
I still have the same error when using, inside a CRA 3.0 typescript react app,  a webcomponent ("vertical-fields") created with "@stencil/core": "^1.0.0-beta.5"

Within the main "index.tsx" I'm loading the definitions with
```javascript
...
import { defineCustomElements } from 'mywebcomponent/dist/loader'
...
defineCustomElements(window)
```

the file at node_modules/mywebcomponent/dist/types/components.d.ts  seems to use locally scoped JSX

```javascript
import { HTMLStencilElement, JSXBase } from './stencil.core';


export namespace Components {
  interface VerticalFields {
    'colorvorh': string;
    'levels': number;
  }
}

declare namespace LocalJSX {
  interface VerticalFields extends JSXBase.HTMLAttributes {
    'colorvorh'?: string;
    'levels'?: number;
  }
  interface IntrinsicElements {
    'vertical-fields': VerticalFields;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}
declare global {
  interface HTMLVerticalFieldsElement extends Components.VerticalFields, HTMLStencilElement {}
  var HTMLVerticalFieldsElement: {
    prototype: HTMLVerticalFieldsElement;
    new (): HTMLVerticalFieldsElement;
  };
  interface HTMLElementTagNameMap {
    'vertical-fields': HTMLVerticalFieldsElement;
  }
  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}
```
Any ideas? Thank you

**Comment by Nibblesh** [comment]
for people struggling with this, I've gotten things working this way


```js
// register-web-components.ts
/* eslint-disable */
import { defineCustomElements, JSX as LocalJSX } from '@amplified/bybee/dist/loader';
import { DOMAttributes } from 'react';

type StencilToReact<T> = {
  [P in keyof T]?: T[P] & DOMAttributes<Element>;
} ;

declare global {
  export namespace JSX {
    interface IntrinsicElements extends StencilToReact<LocalJSX.IntrinsicElements> {
    }
  }
}

defineCustomElements(window)

```

```js
// index.ts
// ...
import './register-web-components';
// ...
```

eslint will shout about using declare global but this is keeping me going for now. gets auto complete working
