### ISSUE TITLE
Q: Other template engines like twig

### ISSUE THREAD

**Issue by bm-stschneider** [ionic-team/stencil#1092]
Let"s say I have symfony app and I want to feed it stencil components, but for the html part I want to reuse existing twig templates. Would Stencil be able to do that with an extra build step or something?

**Comment by adamdbradley** [comment]
This is something we've talked about in the past, for now it's not a feature we'll be adding to stencil. If you have any other questions please feel free to ask them in https://stencil-worldwide.herokuapp.com/ Thanks
