### ISSUE TITLE
Using events in JSX does not work as advertised

### ISSUE THREAD

**Issue by jaqmol** [ionic-team/stencil#1093]
**Stencil version:**

```
@stencil/core@0.11.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Trying to receive a stencil web component event in JSX within a React app is not working [as advertised in the documentation.](https://stenciljs.com/docs/events/#using-events-in-jsx) Instead nothing happens. The event cannot be received at all.

**Expected behavior:**

Events should work also in JSX within React apps [as advertised in the documentation.](https://stenciljs.com/docs/events/#using-events-in-jsx)

**Steps to reproduce:**

1. Compile a web component with stencil that exposes an Event
2. Use the web-component in a React JSX app.
3. Try to register for the exposed event [as advertised in the documentation.](https://stenciljs.com/docs/events/#using-events-in-jsx)

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by hartjus** [comment]
@jaqmol You need to add some glue code to the web components for the events to bubble up in React correctly.  See this:  https://github.com/ionic-team/stencil/issues/693#issuecomment-384682723

You can also do it manually if you have a ref handler on the element by calling `.addEventListener('yourEventName', () => {...});`.  (Be sure to remove the event listener as well!)

**Comment by adamdbradley** [comment]
The reference is in regards to Stencil's JSX, not React's.
