### ISSUE TITLE
Disable shadow dom and use polyfill

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#1094]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Shadow dom is always enabled for browsers that support it. 

**Expected behavior:**
Allow an option to disable the shadow dom and use a polyfill even for browsers that support it. 

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by dominikg** [comment]
I'd like to use this feature to work around issues with ShadowDom when trying to run selenium e2e tests with appium on ios devices.

**Comment by adamdbradley** [comment]
The querystring `?shadow=false` when in dev mode

**Comment by Tallyb** [comment]
Would be great to enable also on prod...

**Comment by gino8080** [comment]
would be great to change the shadow mode programmatically, for example to use on IE browsers
