### ISSUE TITLE
Component with @Prop({reflectToAttr: true}) property not working in another stencil app via npm install

### ISSUE THREAD

**Issue by seanwuapps** [ionic-team/stencil#1095]
**Stencil version:**

Components
```
@stencil/core@0.12.4
```

App
```
@stencil/core@0.12.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I'm trying to use a component in a separate Stencil app, but the attributes on the component itself is not rendered correctly.
This seems to be related to #529 but in my case the component is `npm install`d in the blank stencil app.

running `npm start` in stencil app, the browser renders
`<wu-burger theme="primary" animation="rotate"></wu-burger>` 
as 
`<wu-burger class="hydrated">...</wu-burger>`
![image](https://user-images.githubusercontent.com/10577684/45583222-33cd5280-b901-11e8-80f1-efe013a02741.png)

**Expected behavior:**

Browser keeps the **theme**, **animation** attributes in rendered html:
`<wu-burger theme="primary" animation="rotate" class="hydrated">...</wu-burger>` 

**Steps to reproduce:**

Directory setup:
```
| wu-components  // Components
| wu-components-docs // Stencil App
```

1. run `npm build` in component project `wu-components`
2. run `npm install ../wu-components` in `wu-components-docs`
3. run `npm start` in `wu-components-docs`
4. inspect rendered html in browser 

**Related code:**

Component code: 

```tsx
import { Component, Element, Prop } from '@stencil/core'
@Component({
  tag: 'wu-burger',
  styleUrls: ['vars.css','wu-burger.scss']
})
export class WuBurger {
  @Element() burger: HTMLElement;
  @Prop({reflectToAttr: true}) theme?: string;
  @Prop({reflectToAttr: true}) animation: string = 'middle-out';
  @Prop({reflectToAttr: true}) target: string;

  toggle() {
    let menu:HTMLElement = document.querySelector(this.target);

    if (this.burger.classList.contains('open')) {
      // close menu
      this.burger.classList.remove('open')
      if(menu){
        menu.classList.remove('open')
      }
    } else {
      // open menu
      this.burger.classList.add('open')
      if(menu){
        menu.classList.add('open')
        menu.focus();
      }
    }
  }

  render() {
    return (
      <button type="button" onClick={() => this.toggle()} class={this.animation}>
        <span />
        <span />
        <span />
      </button>
    )
  }
}

```

Stencil App: `app-root.tsx`

```tsx
import { Component } from '@stencil/core';
import 'wu-components';

@Component({
  tag: 'app-root',
  styleUrl: 'app-root.css'
})
export class AppRoot {

  render() {
    return (
      <div>
        <header>
          <wu-burger theme="primary" animation="rotate"></wu-burger>
        </header>
        ...
      </div>
    );
  }
}

```

**Other information:**

also tried publishing `wu-components` into npm and `npm install wu-components` and got the same results
Component repo https://github.com/seanwuapps/wu-components
App repo https://github.com/seanwuapps/wu-components-docs

**Comment by snaptopixel** [comment]
I'm experiencing this same issue, I have styling based on boolean attributes and they are not reflected in the consumer application. The props are set in the component itself, but are not properly reflected in the dom.

**Comment by snaptopixel** [comment]
Thanks @seanwuapps I just reverted to using classnames, thankfully stencil makes that easy since it supports an object with bool values 😁

**Comment by manucorporat** [comment]
Fixed in https://github.com/ionic-team/stencil/commit/49800425f089e43ec0e604d4e8532ccc7de6ae63
