### ISSUE TITLE
Can't set component properties before componentWillLoad is called when using TestWindow.load

### ISSUE THREAD

**Issue by ormejere** [ionic-team/stencil#1099]
**Stencil version:**

```
 @stencil/core@0.12.3
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
It is not possible to pass component properties to TestWindow.load().  It is a common pattern to inject services into a component using properties and then initialise the component in componentWillLoad.  The inability to set component properties when creating a component via TestWindow means that it is not possible to inject services until after componentWillLoad has been called.  Workarounds are hacky such as exposing the componentWillLoad method and invoking it from the test then adding guards inside it to return immediately if the properties aren't set (as will be the case for the first invocation when called from the test).

**Expected behavior:**
It would be great if there was a componentProps member in the test window options passed to TestWindow.load, similar to the property in the stencil-route component.

**Steps to reproduce:**
N/A

**Related code:**
N/A

**Other information:**

**Comment by adamdbradley** [comment]
`TestWindow` has been removed as of `0.13.0`. With the last testing updates it's broken up into unit testing and e2e testing: https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-0130-2018-09-26
