### ISSUE TITLE
publicPath not working as expected

### ISSUE THREAD

**Issue by chimon2000** [ionic-team/stencil#110]
## Description of Problem
When updating publicPath to`dist`, the actual output directory does not change but the reference in code does. This leads to runtime errors.  Also, it doesn't appear that there is a way to change the root output directory from `www`

## Expected Result
The output directory becomes `dist` instead of `build`

## Actual Result
The output directory remains the same

[Here](https://github.com/chimon2000/stencil-issues/tree/issue-110) is a sample reproducing the issue.

**Comment by adamdbradley** [comment]
The `publicPath` only changes the client side reference to the JS files, but it's not the build output directory. I'll leave this open until we update the docs and add `buildDir`: https://github.com/ionic-team/stencil/blob/b76afd0cebbdc1702fd52c08ed2b5709e992cdc3/src/compiler/build/validation.ts#L57

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil-site/commit/026b33cda5c2aea01e91d9af6c12dcaf8d506942
