### ISSUE TITLE
IE11 - CSS Variables not updated when loading Stencil components through Angular

### ISSUE THREAD

**Issue by pseudoramble** [ionic-team/stencil#1100]
**Stencil version:**

```
 @stencil/core@0.13.0-0+
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When loading Stencil components in an Angular app, we do not see the CSS variables being transformed. The transformation seems to work when loading from the www/ folder, but not when loading it from dist/.

**Expected behavior:**

CSS variables are resolved to actual color values in all browsers.

**Steps to reproduce:**

* Setup a new Angular app - `ng new stencil-test-app`
* Add in all polyfills and dependencies required for an Angular app to load in IE11
* Build a dependency with Stencil `0.13.0-0+`
* Load the dependency into the app using `defineCustomElements(window)`
* Add the dependency to the `app.component.html` file - `<my-stencil-component>hello</my-stencil-component>`
* Load the app in IE11. Inspect the Stencil-built component and notice that `var()` is still used in the CSS rules.

**Other information:**

We found that we were able to get this working by introducing our own polyfill into the Angular app (`css-var-ponyfill` specifically) but our understanding was that Stencil would manage loading the polyfills it needs.

**Comment by pseudoramble** [comment]
Also, this issue sounds somewhat related to this issue https://github.com/ionic-team/stencil/issues/1020. This issue was closed though, and it's a slightly different scenario.

**Comment by loudmouth** [comment]
Also seeing this in Internet Explorer

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Comment by vinothbabu** [comment]
It's still an issue in all the browsers. When trying to link the dist folder in an angular app, its still refering to `var(--app-plain-color)` instead of the actual output. 

the www folder of the stensiljs output works perfectly in all browsers from chrome to ie11.
