### ISSUE TITLE
[0.12.4] Uncorrect Workbox version (workbox-v3.4.1 -> workbox-v3.5.0)

### ISSUE THREAD

**Issue by kael** [ionic-team/stencil#1102]
**Stencil version:**

```
    "@ionic/core": "4.0.0-beta.8",
    "@stencil/core": "0.12.4"
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

The version of Workbox ìmported in the service worker is not the same than the one generated:

```bash
$ ls www/
assets  build  index.html  manifest.json  sw.js  workbox-v3.5.0  worker
```

whereas the service worker imports:
```js
importScripts('workbox-v3.4.1/workbox-sw.js')
```

**Comment by adamlacombe** [comment]
Ran into the same problem. Found this https://developers.google.com/web/tools/workbox/modules/workbox-sw#using_local_workbox_files_instead_of_cdn

My service worker file looks like this:
```javascript
importScripts('workbox-v3.4.1/workbox-sw.js');

workbox.setConfig({
  modulePathPrefix: 'workbox-v3.4.1/'
});
```

**Comment by kael** [comment]
Thanks for the tip, but it doesn't  solve the thing on my side.

In `www/`there's still `workbox-v3.5.0/` and then the client still can't fetch the correct version.

What am I missing ? :thinking:

**Comment by adamlacombe** [comment]
Try changing the references inside the sw.js file to point to v3.5.0 instead.
```javascript
importScripts('workbox-v3.5.0/workbox-sw.js');

workbox.setConfig({
  modulePathPrefix: 'workbox-v3.5.0/'
});
```

Even though Stencil is using 3.4.1 - Workbox by default will point to their CDN instead of your local files (and I'm assuming.. ignore the version and instead fetch the latest?).

If you're still having troubles could you point me to the repo you're working with?

**Comment by peterpeterparker** [comment]
same, when I try to update to user workbox v3.6.1, when I run a `npm run build` the v.3.4.1 is still fetched

```
[32:13.1]  Please wait while required dependencies are updated. This may take a few moments and will only be
           required for the initial run.
[32:13.1]  installing dependency: workbox-build ...

+ workbox-build@3.4.1
removed 9 packages and updated 1 package in 4.382s
```
