### ISSUE TITLE
Compile plugin error when using the latest router 0.2.7

### ISSUE THREAD

**Issue by threeaccents** [ionic-team/stencil#1106]
**Stencil version:**

```
 @stencil/core@0.11.4
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I tried updating the app to use the latest stencil router, when I run `npm start` this error appears
```bash
 Plugin Error
           Unexpected token (5:17675) in
           /Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/state-tunnel/dist/esm/es5/stencil-state-tunnel.core.js
```

**Expected behavior:**

No errors to appear

**Comment by jthoms1** [comment]
Please update to the latest @stencil/core. Also use router 0.2.8. There was an issue with 0.2.7 that was fixed. Thanks!

**Comment by threeaccents** [comment]
Working thxs!

**Comment by leetheguy** [comment]
I'm getting the same error with the most recent versions:

    "@stencil/core": "~0.16.2",
    "@stencil/router": "~0.3.1",

[ ERROR ]  Rollup: Plugin Error
           Unexpected token (5:17675) in
           /Users/leetheguy/works/development/apps/gqa/node_modules/@stencil/state-tunnel/dist/esm/es5/stencil-state-tunnel.core.js
