### ISSUE TITLE
Multiple component script inclusion fails on IE/Firefox

### ISSUE THREAD

**Issue by rahulbhooteshwar** [ionic-team/stencil#1113]
**Stencil version:**

```
 @stencil/core@0.12.4
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request 

**Current behavior:**

I am trying to use stencil component  using component script generated after build. It works fine on all browser. But whenever  component script for the same component is included more than once on a page, component doesn't appear on IE/Firefox but works fine on Chrome.

## Why to include script more than once?
In our case  these components (script + selector) are rendered using dynamic content and may come more than once in dynamic content.

**Expected behavior:**

Components should be rendered fine on all browser irrespective of no. of times script is included on page.

**Steps to reproduce:**

   * create one stencil component
   * build the component
   * include the generated script twice on an html page
   * Add selector of the component
   * open the page in IE

**Other information:**

This is not just about including script more than once on page. If some component is used by 2 different components using npm dependency & those 2 components are used on same page this will cause issue on IE.

It is observed that when it fails on IE in this scenario, "hydrated" class is missing on component which seems to control component life cycle.

**Comment by rahulbhooteshwar** [comment]
I have created a [demo project](https://github.com/rahulbhooteshwar/stencil_ie_issue) to reproduce the issue.

**Comment by MuhammadShaban** [comment]
the problem still exists ~0.16.0
any news?

**Comment by ps011** [comment]
@Muhammad, Yes, the problem still exists in 0.16.0. Is there any bug fix in recent versions related to this ?

**Comment by LalitKushwah** [comment]
This is very crucial issue, I am not getting why stencil guys are not even responding in this thread

**Comment by chrisbraddock** [comment]
@rahulbhooteshwar, I looked at your repo and am able to reproduce your result in IE.

I attempted to just [hack in a bypass to loading duplicate scripts](https://github.com/chrisbraddock/stencil/commit/41552e43a5ac0faeb64eb7ab2861488982608297), but no luck. There is no difference with that bit of code.

#1030 sounds related, so I tried with [this fork](https://github.com/ionic-team/stencil/issues/1030#issuecomment-459367364) as well, both with and without my patch, but still no juice.

Simply throwing a "hydrated" class on the component in IE fixes the rendering. I'll see if I can poke around a bit in that direction. If possible, maybe you can start looking in that direction as well and see where IE is getting hung up.

**Comment by richrd** [comment]
I saw this issue and wondered whether #1030 is related. To find out check the network tab in developer tools and see if any of the stencil assets is attempted to be loaded from an incorrect url (check for 404 errors).

If all the assets load properly then these two issues aren't related.

**Comment by simonhaenisch** [comment]
@rahulbhooteshwar I finally had some time to look into this, and I don't think it's related to #1030 (/cc @richrd) because the issue is not that the component doesn't load but that it's not getting hydrated, and therefore `visibility` is still set to `hidden` (waiting for the `hydrated` class to be added which overwrites this).

Don't have any more time to work on a fix at the moment but maybe @adamdbradley or @manucorporat can look into this?

**Comment by rahulbhooteshwar** [comment]
@simonhaenisch  @richrd  This is not just the case with multiple scripts. We have observed the same when we have interdependent components from a mono-repo .e.g. suppose we have a lerna based mono-repo having 2 components xyz-image  & xyz-banner where xyz-banner installs xyz-image as dependency and import the same in `tsx` file. When the dist files generated from both the components are inlcuded on same html page, this particular issue can be reproduced.


Reason:  xyz-image  code is coming twice on the page (individual as well as from within xyz-banner) & having some global conflict on IE.
