### ISSUE TITLE
0.13.1 Testing - Error: Cannot find module 'pixelmatch'

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#1115]
```
 @stencil/core@0.13.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

After reading the [changelog](https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-0130-2018-09-26), I updated my npm test script to `stencil test --spec`, but running it throws the following error:

```
[ ERROR ]  uncaught cli error: Error: Cannot find module 'pixelmatch'
```

**Expected behavior:**

The tests should run.

**Other information:**

Manually installing `pixelmatch` into my dev dependencies fixes it. I guess Stencil is missing the dependency or alternatively needs to install it when running the spec runner for the first time?

**Edit:** Commit 1fba6c85abbdc1325a69cf404777b71c8ca0251c from 0.13.1 changelog is probably related?

**Comment by adamdbradley** [comment]
Just to verify, you're seeing this in stencil `0.13.1`? Yeah, the commit you referenced should have fixed the issue.

**Comment by adamdbradley** [comment]
fixed https://github.com/ionic-team/stencil/commit/36a4b370bc5859863e2d8cd7dc17432e4c7ef95b
