### ISSUE TITLE
Stencil unit testing always installs jest if using yarn for npm client

### ISSUE THREAD

**Issue by bassettsj** [ionic-team/stencil#1118]
**Stencil version:**

```
 @stencil/core@v0.13.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Stencil will not resolve the jest installed and will auto install jest.

**Expected behavior:**

Stencil does not install new version of jest every time you run unit tests.

**Steps to reproduce:**

1. Install stencil project dependencies with yarn including jest
3. Verify that `npm ls jest` returns jest is installed
2. Run `yarn stencil test --spec`

**Related code:**

**Other information:**

**Comment by adamdbradley** [comment]
Currently we do no support or recommend yarn.
