### ISSUE TITLE
Unsupported Media Events in JSX

### ISSUE THREAD

**Issue by bioub** [ionic-team/stencil#1119]
**Stencil version:**
```
 @stencil/core@0.13.2
```

**I'm submitting a:**
[ ] bug report
[x ] feature request
[ ] support request

**Current behavior:**
In JSX when i'm listening to Media event on audio or video elements like

I get the following TypeScript error : 
`Property 'onTimeUpdate' does not exist on type 'AudioHTMLAttributes<HTMLAudioElement>'.`

**Expected behavior:**
onTimeUpdate and other event listed there should be supported on HTMLMediaElement : 
https://html.spec.whatwg.org/multipage/media.html#mediaevents
https://reactjs.org/docs/events.html#media-events

**Steps to reproduce:**
Return in a render() method something like
```tsx
<video onTimeUpdate={(event) => console.log(event)} src="audiofile.mp3" />
<audio onTimeUpdate={(event) => console.log(event)} src="videofile.mp4" />
```

**Related code:**
I think we have to update the definitions in `src/declarations/jsx.ts`

**Other information:**
I can do the pull request very quickly

**Comment by manucorporat** [comment]
Fixed by PR!
