### ISSUE TITLE
[meta] Can we have a stencil forum on forum.ionicframework.com

### ISSUE THREAD

**Issue by zwacky** [ionic-team/stencil#112]
Sometimes I feel like it's too to open a separate issue for some of my questions or ideas.

A forum would make it also easier to follow other people's thinking.
wouldn't mind to have a #stencil channel on ionic-worldwide slack as well, but I think forum is more important.

Cheers!

**Comment by mhartington** [comment]
For now, I think we're going to hold off on this. Our focus is to get stencil in a stable place and working with ionic-angular first. I think our idea is that users don't actually ever touch stencil, at least for now. 

We could revisit this down the road, but I think issues/question are fine, just as long as we can get answers directed back as documentation on the site.

**Comment by raae** [comment]
If so maybe not include the Slack logo on the stencil site (got my hopes up there).
