### ISSUE TITLE
Stencil components aren't hydrated in Angular Universal

### ISSUE THREAD

**Issue by diegozuber** [ionic-team/stencil#1122]
**Stencil version:**

```
 @stencil/core@13.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I'm building my stencil components with the prerender flag and use it in my angular project with angular universal. All my stencil components aren't hydrated.

**Expected behavior:**

Stencil components should hydrated too, same as the angular ones.

**Steps to reproduce:**

1. Setup an angular project with angular universal.
2. Build stencil components with prerender flag
3. import them in the angular projects

**Comment by manucorporat** [comment]
Stencil One introduces a new output target called dist-hydrate-script than can be integrated with angular universal, we will release further details very soon in the docs website!

**Comment by Palapapaa** [comment]
Hi !

Any documentation/indication about how to use the `dist-hydrate-script` ?

I'm also facing problems using Stencil components in an Angular Universal app.

Thank you =)

**Comment by materazu** [comment]
Maybe a solution?

**Comment by materazu** [comment]
Why this issue closed?
