### ISSUE TITLE
Type validation problem

### ISSUE THREAD

**Issue by Kogumelo** [ionic-team/stencil#1123]
**Stencil version:**

```
 @stencil/core@0.11.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
I created one component lwb-timer (a count back timer) with one property:
```tsx
export class LwbTimer {
   ... 
   @Prop init: number; 
   ...
}
```
When I use this component in index.html, like this:
```tsx
<body>
   <lwb-timer init="20"></lwb-timer>
</body>
```

that's ok, it works just fine. But when i try to use it inside another component, like this:

```tsx
export class LwbHeader {
  render() {
    return(
      <header>
        <lwb-timer init="20"></lwb-timer>
      </header>
    );
  }
```
the compiler informs that "init" is expected to be a number, not a string;
It worked again when i did this:

```tsx
export class LwbHeader {
  render() {
    return(
      <header>
        <lwb-timer init={20}></lwb-timer>
      </header>
    );
  }
```

**Expected behavior:**
I think it should work with quotes.

**Steps to reproduce:**
Above

**Related code:**
Above

**Comment by manucorporat** [comment]
JSX is not HTML, HTML only allows to pass string as attribute, but JSX allows for complex type passing. JSX actually set the object properties, not the HTML attributes.

If the type of the property is a number, you should pass an actual number using JS.
