### ISSUE TITLE
Classes decorated with @Component can not extend from a base class. Inherency is temporarily disabled for stencil components.

### ISSUE THREAD

**Issue by gusterwoei** [ionic-team/stencil#1127]
**Stencil version:**

```
@stencil/core@0.13.2
```

**I'm submitting a:**

[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
1. Run `npm start`
2. Output:
```
Classes decorated with @Component can not extend from a base class. Inherency is temporarily disabled for stencil components.
```

**Expected behavior:**
`npm start` successfully

**Steps to reproduce:**
Run `npm start`

**Other information:**
I went through the `CHANGELOG` and found out that since version `0.12.0`. The compiler prevents any inheritance for `@Component` decorated class. I wonder why this? It seems logical for component classes to extend a base class with common non-component related logic

**Comment by Sanderand** [comment]
This is probably relates or duplicates https://github.com/ionic-team/stencil/issues/1060#issue-356651082

**Comment by kael** [comment]
@gusterwoei AFAII, seems they removed inheritance because it doesn't work well with _"tree shaking"_. Searching about it, I've come across that blog post: [Concatenative Inheritance over Prototypal Inheritance](https://medium.com/simpl-under-the-hood/concatenative-inheritance-over-prototypal-inheritance-359e4ff47a8a):

> **Composition a.k.a. Concatenative Inheritance**
> 
> Unlike Prototypal inheritance with standard ES5 classes, the composition allows us to copy the properties from one object to another, without retaining a reference from the original object.
>
> [...]
>
> There are two immediate benefits with this approach:
>  1. The methods are reusable by other variants of the SDKs. So no more redundant or duplicate code.
>  2. _**The imports are tree-shakable with Webpack + Babel pipeline**_. [...]

Looks like another paradigm to learn.

**Comment by adamdbradley** [comment]
We're still evaluating how to best generate components from the compiler, which is why the message is there.
