### ISSUE TITLE
Module resolution fails

### ISSUE THREAD

**Issue by DominicBoettger** [ionic-team/stencil#1128]
Since upgrading to 0.14.0-0 all the modules which point to node_modules are not able to be resolved anymore. Independent from using named imports or default imports.

[ WARN  ]  build warn
           'axios' is imported by src\components\site-loader\site-loader.js, but could not be resolved – treating it as
           an external dependency

**Stencil version:**

```
 @stencil/core@0.14.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Build warnings and application can't be started

**Expected behavior:**
Build is able to locate the modules from node_module

**Steps to reproduce:**
Import external modules like axios, hammerjs.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by cbyte** [comment]
As example, here: https://github.com/axios/axios/issues/1820

For myself I have the same issue, when I only try to import aws-amplify and use it in the ionic-pwa-toolkit

**Comment by cbyte** [comment]
To be more specific, when using aws-amplify in a component, after installing and runing it throws this error in the browser:

> TypeError: Failed to resolve module specifier "supports-color". Relative references must start with either "/", "./", or "../". "http://localhost:3333/build/app/app-home.entry.js"

Here is the log:

C:\ionic-pwa-toolkit>npm run start

npm WARN lifecycle npm is using C:\Users\[...]\AppData\Roaming\npm\node_modules\node\bin\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @ionic/pwa-toolkit@0.0.1 start C:\ionic-pwa-toolkit
> npx stencil build --dev --watch --serve

[43:14.7]  @stencil/core v0.13.2
[43:15.8]  cache optimizations disabled
[43:16.2]  build, app, dev mode, started ...
[43:16.3]  transpile started ...
[43:22.5]  transpile finished in 6.14 s
[43:23.4]  module map started ...
[43:23.4]  generate styles started ...
[43:25.0]  compile global style start ...
[43:25.6]  compile global style finish in 600 ms
[43:25.6]  generate styles finished in 2.25 s
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\aws-sdk\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\aws-sdk\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\aws-sdk\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'punycode' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\punycode\punycode.es6.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'punycode' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\punycode\punycode.es6.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'querystring' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\querystring\index.js', pass 'preferBuiltins: false' to disablethis behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'querystring' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\querystring\index.js', pass 'preferBuiltins: false' to disablethis behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'querystring' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\querystring\index.js', pass 'preferBuiltins: false' to disablethis behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'querystring' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\querystring\index.js', pass 'preferBuiltins: false' to disablethis behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'querystring' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\querystring\index.js', pass 'preferBuiltins: false' to disablethis behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\url\url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'string_decoder' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\string_decoder\lib\string_decoder.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'string_decoder' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\string_decoder\lib\string_decoder.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'buffer' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\buffer\index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'string_decoder' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\string_decoder\lib\string_decoder.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'string_decoder' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\string_decoder\lib\string_decoder.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'string_decoder' over local alternative at 'C:\ionic-pwa-toolkit\node_modules\string_decoder\lib\string_decoder.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
[43:38.4]  module map finished in 15.05 s
[43:38.4]  module derive started ...
[43:38.4]  module derive finished in 9 ms
[43:38.4]  generate bundles started ...
[43:38.5]  generate bundles finished in 29 ms
[43:38.5]  generate app files started ...
[43:39.1]  generate app files finished in 631 ms

[ WARN  ]  build warn
           'supports-color' is imported by node_modules\follow-redirects\node_modules\debug\src\node.js, but could not
           be resolved – treating it as an external dependency

[ WARN  ]  build warn
           'supports-color' is imported by  commonjs-external:supports-color, but could not be resolved – treating it
           as an external dependency

[ WARN  ]  build warn
           'lib' is not exported by 'node_modules\crypto-js\index.js'

[ WARN  ]  build warn
           'SHA256' is not exported by 'node_modules\crypto-js\index.js'

[ WARN  ]  build warn
           'HmacSHA256' is not exported by 'node_modules\crypto-js\index.js'

[ WARN  ]  build warn
           'enc' is not exported by 'node_modules\crypto-js\index.js'

[ WARN  ]  build warn
           'set' is not exported by 'node_modules\js-cookie\src\js.cookie.js'

[ WARN  ]  build warn
           'get' is not exported by 'node_modules\js-cookie\src\js.cookie.js'

[ WARN  ]  build warn
           'remove' is not exported by 'node_modules\js-cookie\src\js.cookie.js'

[ WARN  ]  build warn
           Generated an empty bundle

[43:43.6]  dev server: http://localhost:3333/
[43:43.6]  build finished, watching for changes... in 27.43 s

**Comment by adamdbradley** [comment]
would you be able to test with the latest 0.14.0 prerelease?

**Comment by DominicBoettger** [comment]
Now it seems to find the modules (hopefully) but throws a process is not defined error.

ReferenceError: process is not defined. I checked this and this is caused by redux-logic. It uses process.env.NODE_ENV in the code. I wonder that this worked before... Was process.env available as globale before and has been removed?

```js
function isObservable(input) {
  return input && typeof input[result] === 'function';
}

var allowedOptions = ['name', 'type', 'cancelType', 'latest', 'debounce', 'throttle', 'validate', 'transform', 'process', 'processOptions', 'warnTimeout'];

var allowedProcessOptions = ['dispatchReturn', 'dispatchMultiple', 'successType', 'failType'];

var NODE_ENV = process.env.NODE_ENV;

var defaultOptions = {
  warnTimeout: 60000,
  latest: false,
  debounce: 0,
  throttle: 0
};
```

**Comment by adamdbradley** [comment]
Should be fixed in the latest release.
