### ISSUE TITLE
Questions about sharing components with outside world

### ISSUE THREAD

**Issue by ospatil** [ionic-team/stencil#113]
The `www` folder of a stencil app looks like this after running the production build `npm run build`. I'm using the default generated stencil application.
```sh
www
├── build
│   ├── app
│   │   ├── app.km4yb5pm.js
│   │   ├── app.pvj3bvwp.pf.js
│   │   ├── i5pk3j36.js
│   │   ├── uyykddxl.css
│   │   └── xdewmhiz.js
│   ├── app.js
│   └── app.registry.json
├── favicon.ico
└── index.html
```
Out of all these minified and name-mangled js files, only `xdewmhiz.js` corresponds to `my-name` component and rest of the js files are framework and application files.

Now, in order to share this `my-name` component with world, I would like to publish it on NPM with `main` field pointing to the js file for the component. 

I have two observations/questions regarding this - 

1. In the current scenario, since the generated js file names are random, it's not possible to do so. Therefore there should be some build configuration that will allow for providing name of the generated component js file.
2. Is is sufficient to make only the generated component js file (`xdewmhiz.js` in the example above along with any css and images) part of the the package distribution or does it have any dependencies on the other generated js files?

**Comment by jgw96** [comment]
Hello, thanks for using Stencil! We are building out our docs for this but for now you can check out the stencil config for the [stencil-router](https://github.com/ionic-team/stencil-router) for reference.
