### ISSUE TITLE
Lifecycle order of nested components is not always correct

### ISSUE THREAD

**Issue by eelcobrolman** [ionic-team/stencil#1130]
**Stencil version:**

```
 @stencil/core@0.13.2
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When nesting components the lifecycle order of the will and did load calls is not always correct.

I have 3 (identical) components, componentA, componentB and componentC. The only thing they do is console.log their did and will load functions and render the child compoments with ```<slot/>```:
```
import { Component } from '@stencil/core';

@Component({
  tag: 'my-comp-a'
})
export class MyComponentA {
  componentWillLoad() {
    console.log("Will load: comp-a");
  }

  componentDidLoad() {
    console.log("Did load: comp-a");
  }
  render() {
    return (
      <div>
        I am comp A<br/>
        <slot/>
      </div>
    );
  }
}
```

When using the html:
```
  <my-comp-a>
        <my-comp-b>
          <my-comp-c>
          </my-comp-c>
        </my-comp-b>
    </my-comp-a>
```

the following log entries are shown:
```
Will load: comp-a
Will load: comp-b
Will load: comp-c
Did load: comp-c
Did load: comp-b
Did load: comp-a
```

which is correct according to https://stenciljs.com/docs/component-lifecycle

BUT when using the html:
```
  <my-comp-a>
        <my-comp-c>
          <my-comp-b>
          </my-comp-b>
        </my-comp-c>
    </my-comp-a>
```

the following log entries are shown:
```
Will load: comp-a
Will load: comp-b
Did load: comp-b
Will load: comp-c
Did load: comp-c
Did load: comp-a
```

which is NOT the correct order.

**Expected behavior:**

The expected behaviour is ofcourse:
```
Will load: comp-a
Will load: comp-c
Will load: comp-b
Did load: comp-b
Did load: comp-c
Did load: comp-a
```

**Steps to reproduce:**
Write the 3 simple components and mess around with the order in the html

**Related code:**
See above.

**Other information:**

**Comment by adamdbradley** [comment]
Would you be able to replicate the issue in a karma test? 

We have tests around lifecycle events, but maybe we're missing something, so any help writing breaking tests would help. Thanks

https://github.com/ionic-team/stencil/tree/master/test/karma/test-app/lifecycle-basic
https://github.com/ionic-team/stencil/tree/master/test/karma/test-app/lifecycle-async
https://github.com/ionic-team/stencil/tree/master/test/karma/test-app/lifecycle-on-ready
https://github.com/ionic-team/stencil/tree/master/test/karma/test-app/lifecycle-unload

**Comment by eelcobrolman** [comment]
Well actually, I tried that. I wrote a karma test for it, and when opening it in Chrome (running ```npm start``` from the ```test/karma/test-app``` dir, it shows up wrong (http://localhost:3333/lifecycle-basic-slots). BUT when running ```npm run test.karma``` (from the main dir), everything is ok, so Chrome headless is doing it correctly it appears.

It get's even weirder when I tried to see if my tests are running at all by modifying the .spec.ts file and changing some expected value, then all weird things happen. Sometimes firefox reports only 1 entry (instead of 6 events), sometimes the order is indeed messed up. Even just adding a comment in the spec.ts file gives different karma results. Is the order of loading affected (different hash keys for the files?), I really don't get it anymore.

Anyway, my karma tests are here: https://github.com/eelcobrolman/stencil/tree/lifecycle-basic-slots-karma-test

**Comment by yupii7** [comment]
I reported an issue about life cycle a few months ago and I had a little repo to reproduce the issue. Today I changed a little bit to replicate this one: https://github.com/yupii7/embedded-cmps. It works on Edge an Firefox but not on Chrome.

**Comment by yupii7** [comment]
It appears that without the _slot_ in each, it's showing the content of the most nested component to the first component. With the _slot_ in each, it shows the content of the first one to the most nested. Edge, Firefox and Chrome show the correct html.

Here's what console output with Chrome(with and without _slot_ in components):      

The child component is about to be rendered 
The child component has been rendered
The grandchild component is about to be rendered
The grandchild component has been rendered
The parent component is about to be rendered
The parent component has been rendered

**Comment by dgibson666** [comment]
I'm seeing something similar where I have a component (using shadow DOM) that loads several others from it (none of these are slotted or using shadow DOM). This parent component is doing a querySelector() call down into one of the child components to attach an event to an input that it renders, but it cannot find that input. If the component updates asynchronously, it does then find the input and work. If I take the shadow DOM off or test in IE (flattened), it works. But with the shadow DOM on a parent component, it is consistently giving me trouble and seems like the lifecycle is not as documented (parent should not report that it did load until all children have). Without using the shadow DOM, it works fine.
