### ISSUE TITLE
ES5 fails for prod builds

### ISSUE THREAD

**Issue by arby50** [ionic-team/stencil#1132]
**Stencil version:**

```
@stencil/core@0.13.2
```

**I'm submitting a:**

[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
A 'dev' build works when using FireFox 62 and Edge ("npm start") but a 'prod' build ("npm build") produces a blank page.  In FF/Edge, the `ion-nav` tag is empty.  The app displays in chrome.  I can also duplicate this when running "npm start --prod".  I can confirm via FF Dev tools that the es5 files are being produced and are loaded.  I have been able to reproduce this using the bare Ionic PWA Toolkit as well as other PWA apps.

**Expected behavior:**
The prod build and minification process should produce ES5 compliant files that render in ES5-compliant browsers

**Steps to reproduce:**

using FF V63 or Edge (V42):
"npm start --prod" using the Ionic PWA toolkit:
https://github.com/ionic-team/ionic-pwa-toolkit

**Comment by lvanngo** [comment]
I'm not sure if this helps any but I think the es2015 target build with polyfills so you can polyfill to get the expected behavior in older browsers.  You can also try the --prerender option.  That worked for me when I needed to feed it to something that really needed es5 target.

**Comment by arby50** [comment]
Thanks for the help.  I can get an ES2015 target to work, I just have to use the dev build with an ES5 flag set: '`npm run dev --es5`'.  'dev' is defined in my package.json as `"dev": "stencil build --dev --service-worker"`
It only fails during production builds.  Which I can work around, but I just dont get the minification (and whatever other) benefits come with a prod build.
According to stencil: _Note that by default, ES5 builds and polyfills are enabled during production builds._

**Comment by manucorporat** [comment]
This already fixed in master! a upcoming version will have this fixed
