### ISSUE TITLE
Feature Request: Allow for a per-component css reset

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil#1133]
**Stencil version:**

```
 @stencil/core@latest
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When creating a component library using shadow dom it stands to reason that you'd want to share a css reset across components (just like you would with a website/app).

Stencil doesn't currently provide an easy way to achieve this, but it seems like a relevant and worthwhile thing to have built-in.

**Expected behavior:**

I can think of a few ways to solve it:

- Specify a `cssReset` file (sass,. css, styl, etc) in the build config and have it automatically added to all components.
- Allow an array to be passed to `globalStyle` so that we can generate multiple files with pre-processing etc
- Add a `cssReset` property to the component decorator which would inject a link tag **before** the cssUrl styles are added (to fix specificity issues)

**Related code:**
I'm currently able to achieve similar functionality by following this pattern:
1. Use `globalStyle` to generate a component reset file that looks like:
```stylus
:host
  *
    margin 0
    padding 0
  *, *::before, *::after
    box-sizing border-box
    font-family inherit
    font-size inherit
  // ...etc
```
- Then, include the built css file in each component's render fn:  
```tsx
render() {
  return [
    <link rel="stylesheet" href="/build/myfile.css"/>,
    // ...the rest
  ]
}
```

**Other information:**
The current pattern I'm using works but there are specificity issues and it'd be nice to "set it and forget it"

**Comment by adamdbradley** [comment]
Copying the same css into every components is not an API we'd like to provide with stencil.
