### ISSUE TITLE
Using the same `EventEmitter` name in child component leads to additional emission from parent component.

### ISSUE THREAD

**Issue by aszmyd** [ionic-team/stencil#1135]
**Stencil version:**
```
 @stencil/core@0.32.2
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Using the same `EventEmitter` name in child component leads to additional emission from parent component.

**Expected behavior:**
Child component events emitters should always be treated as separate ones as naming conflict in those can occur.

**Steps to reproduce:**
1. Have parent component with an event emitter, lets call it `buttonClicked`
2. Have child component with the same event emitter name `buttonClicked`
3. Use child component in parent and attach `onButtonClicked` to it
4. Use parent component after compilation and attach even listener using `addEventListener` function for `buttonClicked` event
5. Emit `buttonClicked` event from **child component** i.e. by click the actual button.

Result: outside `addEventListener` handler gets called **twice**

**Related code:**

```tsx
// src/my-parent.tsx
import { Component, Event, EventEmitter } from '@stencil/core';
@Component({
    tag: 'my-parent'
})
export class MyParentComponent {
    @Event() buttonClicked: EventEmitter;
    render() {
        return <my-child onButtonClicked={() => this.buttonClicked.emit()} />;
    }
}

// src/my-child.tsx
import { Component, Event, EventEmitter } from '@stencil/core';
@Component({
    tag: 'my-child'
})
export class MyChildComponent {
    @Event() buttonClicked: EventEmitter;
    render() {
        return <button onClick={() => this.buttonClicked.emit()}>Click Me</button>;
    }
}

// index.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>

<my-parent></my-parent>
<script src="www/build/app.js"></script>
<script>
    const component = document.getElementsByTagName('my-parent')[0];
    let counter = 0;
    component.addEventListener('buttonClicked', () => {
        console.log(`received buttonClicked event ${++counter} time`);
    })
</script>
</body>
</html>
```

**Other information:**
Reproducable code: https://github.com/aszmyd/stencil-event-emitter-issue

**Comment by manucorporat** [comment]
This is the expected behaviour, most of the DOM events bubble up by default: https://javascript.info/bubbling-and-capturing

Just configure your dom events to NOT bubble:

```
@Event({ bubbles: false }) buttonClicked: EventEmitter;
```

**Comment by aszmyd** [comment]
@manucorporat that makes sense but PLEASE write ANYTHING about such thing in docs. I don't even see any info about the fact that `Event` can event consume an parameter like that in docs. It would save a lot of time for everyone if a simple note will be out there.

**Comment by mattcosta7** [comment]
You may also want bubbling to be on, but just as a regular Dom event , you
can check the event target in your handler to ensure you're reacting to the
correct events only

**Comment by mattcosta7** [comment]
added a pr for documenting this: https://github.com/ionic-team/stencil-site/pull/220

**Comment by aszmyd** [comment]
Awesome, thanks @mattcosta7 !!

**Comment by gikey** [comment]
same problem, I try to set `bubbles: false`, but still doesn't work. Looking forward to your help @manucorporat
