### ISSUE TITLE
Running tests compiles differently

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#1137]
**Stencil version:**

```
"@stencil/core": "0.13.2"
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

I'm trying to use `moment-timezone` in my Stencil/Ionic 4 app. I use `import moment from 'moment-timezone'` and it works as expected. I run the unit tests and get an error

```
TypeError: moment_timezone_1.default is not a function
```

**Expected behavior:**

I want my app to be compiled in the same way for running the tests, so they don't break because of how I import some modules.

**Related code:**

```ts
// date-helpers.ts

import moment from 'moment-timezone';

export const formatDate = (d: string) => moment(d).format();
```

```ts
// date-helpers.spec.ts

import moment from 'moment-timezone';
import { formatDate } from './date-helpers';

describe('Date Helpers', () => {
  describe('formatDate(d: string)', () => {
    it('should format a date string', () => {
      const d = moment.format();
      expect(formatDate(d)).toBe(d);
    });
  });
```

**Other information:**

I used a custom rollup plugin

```js
{
  name: 'replace-moment-imports',
  transform: async code => ({
    code: code.replace(/import\s+\*\s+as\s+moment/g, 'import moment'),
    map: { mappings: '' },
  }),
}
```

to convert my imports from `import * as moment` to `import moment` only for the build but not for the tests, which makes both the build and the tests work. But that is a pretty hacky thing and breaks when enabling `esModuleInterop` in `tsconfig.json` (which should be enabled according to the [0.14 release notes](https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-0140-0-2018-10-02)).

**Comment by adamdbradley** [comment]
Would you be able to with the 0.14.0 prerelease?

**Comment by simonhaenisch** [comment]
Just tested on `0.14.0-6` and it works. Thanks!
