### ISSUE TITLE
Copy files in stencil.config is copying into collection folder

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#1139]
**Stencil version:**

```
 @stencil/core@0.13.2
```

**I'm submitting a:**

[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
when using the copy option on stencil.config - file is copied under the collection folder and not directly under the dist folder

**Expected behavior:**
one of 2 options: 
1) if this is unintentional - should copy to dist folder and not to collection
2) if this is intentional - documentation should reflect it

**Steps to reproduce:**
1) Add the following to stencil.config.js
```
copy: [
    {src: 'package.json', dest: 'package.json' }
  ],
``` 
(assumes you have a pakcage.json file in your src folder, but any file will do)
2) run build. 
3) package.json will be under the /collection folder in dist folder.

**Comment by manucorporat** [comment]
This should be fixed in Stencil one, as we have deprecated the global copy tasks and now they are local to each output target!
