### ISSUE TITLE
onDoubleClick does not trigger event

### ISSUE THREAD

**Issue by derkoe** [ionic-team/stencil#114]
Event onDoubleClick does not seem to fire.

To reproduce this I created a simple component with two buttons - one with `onClick` one with `onDoubleClick` - the former event fires, the latter doesn't.

Here is the code:

    import { Component } from '@stencil/core';

    @Component({
        tag: 'my-button'
    })
    export class MyButton {

        private onClick(event: MouseEvent) {
            console.log('onClick', event);
        }

        private onDoubleClick(event: MouseEvent) {
            console.log('onDoubleClick', event);
        }

        render() {
            return <div>
                <button onClick={(ev) => this.onClick(ev)}>Click</button>
                <button onDoubleClick={(ev) => this.onDoubleClick(ev)}>DoubleClick</button>
            </div>
        }
    }

**Comment by jgw96** [comment]
Hello, thanks for using Stencil! Would you mind trying ```<button onDblClick={(ev) => this.onDoubleClick(ev)}>DoubleClick</button> ``` and seeing if that works?

**Comment by derkoe** [comment]
That won't compile since the typings only contain `onDoubleClick`
