### ISSUE TITLE
Route change event

### ISSUE THREAD

**Issue by matteobortolazzo** [ionic-team/stencil#1143]
**Stencil version:**

```
 @stencil/core@0.13.2
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

**Expected behavior:**
stencil-router should have an event that fires when the page change.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by kael** [comment]
That's the repo https://github.com/ionic-team/stencil-router.

**Comment by matteobortolazzo** [comment]
Sorry, I didn't notice, thanks!
