### ISSUE TITLE
TypeScript: Invalid code in components.d.ts

### ISSUE THREAD

**Issue by pawsaw** [ionic-team/stencil#1146]
**Stencil version:**

```
@stencil/core@0.13.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request 

**Related code:**

grid-data.ts
```ts
export type GridDataRow = {
    [field: string]: any
};

export type GridData = GridDataRow[];
```

grid.tsx:
```tsx
// ...
@Method()
    setData(data: GridData): void {
        this.data = data;
    }
//...
```

generated components.d.ts:
```ts
import {
  GridData,
} from './components/grid/grid-data';

// ...

interface Grid {
    'setData': (data: GridDataRow[]) => void;
  }
```

As you can see, the generated signature of "setData" is wrong and doesn't work with the generated import ==> build fails.

**Comment by adamdbradley** [comment]
Should be fixed in most recent versions
