### ISSUE TITLE
Add tslint to the beginning of the compile process

### ISSUE THREAD

**Issue by DominicBoettger** [ionic-team/stencil#1147]
**Stencil version:**

```
 @stencil/core@0.13.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The compile run output lint errors at the end of the process instead of a instant reply of the error. 

**Expected behavior:**
For instance a variable is unused should be mentioned directly after starting the compile run to decrease wait times.

**Steps to reproduce:**
Add a variable which is unused to the sources and start the compiler. It will first transpile and generate the styles before it outputs the lint error.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
One of the reasons why the build process is fast is because type checking is done in another thread with another process. Making updates and rebuilding the app is a large part of the dev process, but typescript errors are occasional. I'd prefer to not slow down all builds for this reason.
