### ISSUE TITLE
Feature Request: Ability to add additional metadata to JSON component documentation.

### ISSUE THREAD

**Issue by nborelli** [ionic-team/stencil#1148]
**Stencil version:**

```
 @stencil/core@0.13.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

This is not a bug, but it would be really helpful if we had a way to add additional metadata to the documentation.json file that is generated by the `docs` output target.  AFAIK, there is no way to do this currently.

**Expected behavior:**

**Proposal**: Add a docsMetadata property of type `{ [key: string]: any }` to the `ComponentOptions` class.  This component metadata could be written to documentation.json file and provide additional contextual information for the component.

**Justification**: I would really like to add a category to the components in our library like 'Layout' or 'Input'.  I may also want to add something that indicates this component should not be listed in the list of components on the documentation site or that it related to some other component.

**Examples**:
```tsx
@Component({
    tag: 'tf-checkbox',
    styleUrl: 'checkbox.scss',
    shadow: true,
    docsMetadata: {
        category: 'Input'
    }
})
export class Checkbox {
}
```

```tsx
@Component({
    tag: 'tf-tab',
    styleUrl: 'checkbox.scss',
    shadow: true,
    docsMetadata: {
        category: 'Controls',
        parentTag: 'tf-tabs',
        hidden: true
    }
})
export class Tab {
}
```

**References**:  See the way components are grouped in other large projects like [https://grommet.io/docs/components](https://grommet.io/docs/components)

Obviously, the documentation generation code would also need to be modified to write the metadata to the documentation JSON file as well.

```json
{
    "components": [
        {
            "tag": "tf-tab",
            "readme": "...",
            "usage": {
                "javascript": "...",
            },
            "props": [],
            "methods": [],
            "events": [],
            "styles": [],
            "metadata": {
                "category": "Controls",
                "parentTag": "tf-tabs",
                "hidden": true
            }
      }
    ]
}
```

**Comment by adamdbradley** [comment]
Thanks for feature request, but at this time I think we're going to keep the docs feature simple and not add to the API. I'd suggest opening the json file that was generated and adding to it.
