### ISSUE TITLE
[0.14.0-5] - runtime helpers cause errors in socket.io

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#1149]
**Stencil version:**
```
 @stencil/core@0.14.0-5
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
A recent version of Stencil has introduced a bug that causes socket.io to no longer work.

Stencil executes the following code:
```ts
export function runtimeHelpers(win: any) {
  const nodeGlobals = ['process', 'Buffer'];

  nodeGlobals.forEach(nodeGlobal => {
    if (typeof win[nodeGlobal] === 'undefined') {
      Object.defineProperty(win, nodeGlobal, {
        get: () => {
          throw new Error(`The "${nodeGlobal}" property appears to be a node global, however, node globals cannot be executed from within a browser environment. The source of using a node global is often from a dependency and a common solution is to provide the "rollup-plugin-node-globals" plugin within the stencil config plugins. Please see the bundling docs for more information.`);
        },
        configurable: true
      });
    }
  });
}
```

This results in any access to `window.process` or `window.Buffer` to throw an exception.

The problem is that some code looks at those values to see if they are defined and the act of looking at the value causes the exception and stops code execution.

For example, Socket.io client uses:

```js
  if ((typeof global.Buffer === 'function' && global.Buffer.isBuffer && global.Buffer.isBuffer(obj)) ||
     (typeof global.ArrayBuffer === 'function' && obj instanceof ArrayBuffer) ||
     (withNativeBlob && obj instanceof Blob) ||
     (withNativeFile && obj instanceof File)
    ) {
    return true;
  }
```

This looks like they are checking if `global.Buffer` is a function and not using it if it is not defined.  The problem is that the Stencil property override throws an exception when ` if (typeof global.Buffer === 'function')` is evaluated.  This not only logs the exception, but also causes the code to stop running and Socket.io to not work.

**Comment by adamdbradley** [comment]
Ok, that's probably good enough reason to remove the runtime helpers. Thanks for opening the issue.

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil/commit/c4eddf04063e325605ff77227717705f8544904f
