### ISSUE TITLE
component tag should be optional

### ISSUE THREAD

**Issue by obedm503** [ionic-team/stencil#115]
when defining a component a tag is defined as part of the config
```ts
@Component({
  tag: 'my-component'
})
export class MyComponent {}
```
I believe the tag should be optional and if none given the kebab-cased name of the class should be used instead. so the above example would be reduced to:
```ts
@Component()
export class MyComponent {}
```
I can submit a pr, if this behavior is desired

**Comment by jgw96** [comment]
Hello, thanks for using Stencil and thanks for the feature suggestion! We have discussed this internally and at this time are not going to go forward with this feature. We feel this adds a little too much magic for little gain.
