### ISSUE TITLE
Add Fragment to @stencil/core

### ISSUE THREAD

**Issue by auderer** [ionic-team/stencil#1151]
**Stencil version:**

```
 @stencil/core@0.13.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Rendering multiple elements requires either a wrapping div or returning an array. Returning an array avoids rendering an unwanted `<div>`, but array format with JSX is hard to read and work with, especially in larger components.

**Expected behavior:**
Just like React, you could wrap multiple elements in a `<Fragment>` tag.

**Steps to reproduce:**
Without fragment:
```jsx
render() {
  return [
    <div>My first element</div>,
    <div>
        <span>Another element</span>
    </div>,
    <div>And another</div>
  ]
}
```

**Related code:**
With fragment:
```jsx
render() {
  return (
    <Fragment>
      <div>My first element</div>
      <div>
        <span>Another element</span>
      </div>
      <div>And another</div>
    </Fragment>
  )
}
```

**Other information:**

This is an extremely simple feature to add, I'm just not sure where it should go in the stencil repository. 
The working Fragment code is literally just this one line:

```js
export const Fragment = (props, children) => children
```

Or without ES6:
```js
export function Fragment(props, children) {
  return children
}
```

Used as a JSX element, this simply renders the children without rendering an arbitrary wrapping element.

I made a package [here](https://github.com/michaelauderer/stencil-fragment) to provide this feature, but it would be fantastic if it were available in @stencil/core. People coming from React will love this.

If someone can advise me where in the repo to add this code, I would be happy to make the PR myself.

**Comment by simonhaenisch** [comment]
But web components need a dash in the tag name, so maybe it should be called `ion-fragment` 🤓

**Comment by michaelauderer** [comment]
@simonhaenisch Yeah, this isn't a web component, it's just a JSX tag! So, no dash.

**Comment by manucorporat** [comment]
@michaelauderer we would like to be able to use the short-syntax:
```
<>

</>
```
but looks like it's not supported by typescript outside React, "React" is hardcoded into typescript: https://github.com/Microsoft/TypeScript/issues/20469

**Comment by o-t-w** [comment]
Is there any update on this? Not having full control over markup is a pretty drastic limitation.

**Comment by simonhaenisch** [comment]
@o-t-w not sure what you mean because this doesn't limit your ability to have full control over your markup? It's just syntactic sugar (that indeed increases readability a lot), i. e. you can already either return an array or add the suggested `Fragment` functional component into your project.

**Comment by michaelauderer** [comment]
@o-t-w For now, I've already built a solution for it here: https://github.com/michaelauderer/stencil-fragment

If someone can point out where it belongs in the Stencil repository, I'll make a PR. (@manucorporat, any thoughts?)

**Comment by manucorporat** [comment]
Stencil 1.0 introduces a new `<Host>` exported from `@stencil/core` that can act as a Fragment!

**Comment by liron-navon** [comment]
@manucorporat 
I found this super confusing,`<Host>` is nothing like react `<Fragment>`,

```
Error: The <Host> must be the single root component. Make sure:
- You are NOT using hostData() and <Host> in the same component.
- <Host> is used once, and it's the single root component of the render() function.
```

**Comment by nkint** [comment]
I've seen this: https://github.com/auderer/stencil-fragment

**Comment by sfmskywalker** [comment]
I, too would like to see`<Fragment>` be part of StencilJS. My use case is that I have a modular web component where consumers of the component can declare plugins, tat themselves render widgets. These renderings are either JSX (Vdom objects) or string values (in case the consumer is a vanilla JS app with no JSX support). When the widget is rendered as string, I need to set the `innerHTML` property of a containing element. Ideally, without having to use a `<div>`.

Kudos to @auderer for providing exactly that!

**Comment by sfmskywalker** [comment]
Looks like I celebrated too soon. I misunderstood Fragment to also have an InnerHTML property somehow causing that content to magically be rendered. Instead, it looks like it's just a container that renders child elements. It makes sense that it doesn't do what I expected with InnerHTML.

**Comment by milottit** [comment]
As @auderer said and did in his Github project, it is just a one-liner:

```
export default (props, children) => [ ...children ]
```

Why wouldn't be possible to add it in @stencil/core?

**Comment by simonhaenisch** [comment]
Actually, https://github.com/microsoft/TypeScript/pull/38720 was just merged so we can use the `<></>` syntax soon!

**Comment by milottit** [comment]
Ok. Good news. But in the meanwhile, it would be nice to have a `Fragment` functional component (without the syntactic sugar)

**Comment by simonhaenisch** [comment]
In the meanwhile you could also just add your one-liner into your project(s) 😬 Feel free to open a PR though, but no promises that it'll be merged (up to the maintainers). Especially with a better solution in sight already.

**Comment by milottit** [comment]
No worries. I wasn't going to wait before an action on the codeline would be made. I know how slow an organization is :) On top of that, majority of issues are closed as soon as possible even if the issue exists. We'll see what's happening with the new `<>..<>` TS syntax support.
