### ISSUE TITLE
Add Scroll Behavior polyfill

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#1153]
**Stencil version:**

```
 @stencil/core@0.14.0-6
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**

```tsx
element.scrollIntoView({ behavior: 'smooth' });
```

isn't polyfilled for older browsers.

**Expected behavior:**

It would be nice if Stencil loads a polyfill for that if required.

**Other information:**

There is a popular polyfill available here: https://github.com/iamdustan/smoothscroll

**Comment by adamdbradley** [comment]
Currently we're only adding polyfills when the minority of browsers do not support a web standard. In this case, only firefox supports it, and all browsers would have to download the polyfill that may not be used. At this time we won't be adding this polyfill for all bundles.

**Comment by simonhaenisch** [comment]
Are you sure, cause I'm using this in chrome and it works... maybe the docs are not up to date...

**Comment by Tallyb** [comment]
3 years later - scrollIntoView is supported on most browsers and should be added to the mockElement: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by splitinfinities** [comment]
@Tallyb I'm reopening to determine if we do still need to add this to mockElement or not.

**Comment by rwaskiewicz** [comment]
At the time of this writing, `scrollIntoView` is supported in most browsers (https://caniuse.com/?search=scrollintoview):

![Screenshot 2023-05-19 at 3 29 48 PM](https://github.com/ionic-team/stencil/assets/1930213/8e2185c9-7676-44b3-84ae-5de38b46a8f6)

`scrollIntoView` stub was added to `MockElement` in #3480. 

I'm going to close this issue, but please feel free to create a new issue if anyone feels this hasn't been sufficiently addressed. Thanks!
