### ISSUE TITLE
Built success but the site didn't work

### ISSUE THREAD

**Issue by shockw4ver** [ionic-team/stencil#1154]
**Stencil version:**

```
 @stencil/core@0.13.2<version>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Created a project by ``npm init stencil``, the type is 'app'.
Get to the website and the router didn't work.
Just like this:
![html](https://www.z4a.net/images/2018/10/17/image94fe6d4b5db08b5d.png)

**Expected behavior:**
The page work normally.

**Steps to reproduce:**

Created a project by ``npm init stencil``, the type is 'app'.
Ran ``yarn stencil build``, and deploy it to a sub directory of a item, then I get to the website, the router didn't work. The browser is newest Chrome.

**Related code:**

```tsx
import { Component } from '@stencil/core';


@Component({
  tag: 'app-root',
  styleUrl: 'app-root.css',
  shadow: true
})
export class AppRoot {

  render() {
    return (
      <div>
        <header>
          <h1>Stencil App Starter</h1>
        </header>

        <main>
          <stencil-router>
            <stencil-route-switch scrollTopOffset={0}>
              <stencil-route url='/' component='app-home' exact={true} />
              <stencil-route url='/profile/:name' component='app-profile' />
            </stencil-route-switch>
          </stencil-router>
        </main>
      </div>
    );
  }
}

```

**Other information:**

**Comment by adamdbradley** [comment]
Sorry but this is not enough information to debug what the issue may be.
