### ISSUE TITLE
Props values setted as html attributes are always strings

### ISSUE THREAD

**Issue by juanmiguelbesada** [ionic-team/stencil#1155]
**Stencil version:**

```
 @stencil/core@0.13.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Hi guys.

It would be awesome if props defined as html attributes can be parsed / converted / casted to other types instead of strings when they are complex types.

We already do something with booleans and number props. Why not use something like JSON.parse to convert strings to objects if possible?

I mean, currently we have something like this

```tsx
@Component({
  tag: 'my-component'
})
export class MyComponent implements ComponentDidLoad {
  @Prop() boolProp: boolean;
  @Prop() numberProp: number;
  @Prop() arrayProp: any;
  @Prop() jsonProp: any;

  componentDidLoad () {
    console.log(typeof this.boolProp, this.boolProp); //boolean, true
    console.log(typeof this.numberProp, this.numberProp); //number, 123456
    console.log(typeof this.arrayProp, this.arrayProp); //string, "[123456, 'string']"
    console.log(typeof this.jsonProp, this.jsonProp); //string, "'{"test": "foo", "bar": "baz"}"
  }
}
```

```html
<my-component bool-prop="false" number-prop="123456" array-prop="[123456, 'string']" json-prop='{"test": "foo", "bar": "baz"}'></my-component>
```

After:

```tsx
@Component({
  tag: 'my-component'
})
export class MyComponent implements ComponentDidLoad {
  @Prop() boolProp: boolean;
  @Prop() numberProp: number;
  @Prop() arrayProp: any;
  @Prop() jsonProp: any;

  componentDidLoad () {
    console.log(typeof this.boolProp, this.boolProp); //boolean, true
    console.log(typeof this.numberProp, this.numberProp); //number, 123456
    console.log(typeof this.arrayProp, this.arrayProp); //object, [123456, 'string']
    console.log(typeof this.jsonProp, this.jsonProp); //object, {"test": "foo", "bar": "baz"}
  }
}
```

```html
<my-component bool-prop="false" number-prop="123456" array-prop="[123456, 'string']" json-prop='{"test": "foo", "bar": "baz"}'></my-component>
```

My use case is that we have a component with lot of props that are complex types (objects) and can be setted via html attributes. And I have to pass throw all properties and do a JSON.parse to convert it to objects, (and setting Watch for each prop) and i think is a task we can to it automatically.

**Comment by adamdbradley** [comment]
Thank you for opening the issue, but we've decided that html attributes should not be parsing objects and arrays that have been stringified. Element properties can already be passed object and arrays, and if this logic was built into the core of stencil it could have a performance impact of constantly trying to parse strings.
