### ISSUE TITLE
HMR escapes chars with backslash and breaks Media Queries

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#1156]
**Stencil version:**

```
 @stencil/core@0.14.0 (and earlier)
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
When changing a CSS file that contains a media query, HMR pushes this new style to the browser via WS. But some characters, like `@` or `"` get escaped by a backslash `\`, e.g.:

Initial load using `F5`:
```css
@media () {
  background-image: url("img.png");
}
```

...after changing the css, HMR generates:
```css
\@media () {
  background-image: url(\"img.png\");
}
````

...and the browser fails to interpret and therefore breaks the layout.

**Expected behavior:**
HMR does not escape those special chars, like `@` or `"`.

**Steps to reproduce:**
1. git clone https://github.com/kraftwer1/stencil-component-starter
2. npm install && npm start
3. change browser width to e.g. 600px, so the media query gets triggered (font changes to Arial)
4. make a change in `my-component.css` and save - font is now wrong (not Arial anymore)

**Related code:**

```tsx
@media (max-width: 640px) {
  div {
    font-family: "Arial";
  }
}
```

**Other information:**

Initial load:
<img width="415" alt="bildschirmfoto 2018-10-17 um 09 56 15" src="https://user-images.githubusercontent.com/2146436/47072057-872f0b00-d1f5-11e8-95ab-28f03f417ca0.png">

After HMR change:
<img width="386" alt="bildschirmfoto 2018-10-17 um 09 56 48" src="https://user-images.githubusercontent.com/2146436/47072078-8f874600-d1f5-11e8-9c04-2fff8f26dde5.png">

Chrome WS inspector:
<img width="552" alt="bildschirmfoto 2018-10-17 um 10 04 35" src="https://user-images.githubusercontent.com/2146436/47072097-9ca43500-d1f5-11e8-9757-24cca97f3395.png">

**Comment by adamdbradley** [comment]
Thanks for the detailed issue, really helped track down the problem. Should be fixed in the next release, thanks!
