### ISSUE TITLE
Dynamic Styles not applied correctly with non --dev build

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#1159]
**Stencil version:**

```
 @stencil/core@0.14.0 (also occurs in 0.13.2 and probably before)
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Working with a community member. Duplicated the issue with some fairly simple code (their code is a.) private, and b.) more complex, but this code essentially mimics what they are trying to do).

The component is rendered as such:

```jsx
    return (
      <div style={this.getBackgroundStyle()}>
        <div class="condition-image">{url && <img src={url} />}</div>
        <div class="condition-label">
          {this.weatherCondition.description(this.condition)}
        </div>
      </div>
    );
```

The `getBackgroundStyle()` is:

```TypeScript
  getBackgroundStyle() {
    return this.bgColor && this.bgColor !== 'white' ? { 'background': this.bgColor, '--kws-font-color': 'white' } : {};
  }
```

The consuming app toggles `bgColor` on click via property binding.

When the Stencil lib is build with `--dev` everything works fine.

When the Stencil lib is build without `--dev`, the `div` starts with no style, then gets `{ 'background': this.bgColor, '--kws-font-color': 'white' }`, next click results in style being set to ` '--kws-font-color': 'white'`, subsequent clicks have no effect.

Adding `console.log` to the `getBackgroundStyle()` reveals that the style gets built properly in all cases, so it appears to be an issue in the actual rendering.

This video shows first the good behavior with `--dev` then the bad behavior without it: https://drive.google.com/file/d/16m3Qj83mxMytg_ZWrxFJCHRaucQavro4/view?usp=sharing

**Expected behavior:**
It should work like it works when the `--dev` flag is used.

**Steps to reproduce:**

1. `git clone https://github.com/kensodemann/kws-weather-widgets.git`
1. `cd kws-weather-widgets`
1. `npm i`
1. `npm run build -- --dev --es5`
1. `npm link`
1. `git clone https://github.com/kensodemann/ionic-weather.git`
1. `cd ionic-weather`
1. `npm i`
1. `npm link kws-weather-widgets`
1. `npm start`

Everything should work fine at this point.

Go back to `kws-weather-widgets` directory, do `npm run build` (without the --dev), wait for the library to build and for the Ioinic weather app to rebuild and reload. Now clicking on the condition component will turn the BG red once, but screw up completely after that.

**Comment by jrmlt** [comment]
Not really the same but might be linked with mine #1157.
It also concerns style attribute and a difference between --dev and prod.

**Comment by kensodemann** [comment]
More experimentation. If I change `getBackgroundStyle()` from this:

```TypeScript
  getBackgroundStyle() {
    return this.bgColor && this.bgColor !== 'white' ? { 'background': this.bgColor, '--kws-font-color': 'white' } : {};
  }
```

To this:

```TypeScript
  getBackgroundStyle() {
    return this.bgColor && this.bgColor !== 'white' ? { 'background': this.bgColor, 'color': 'white' } : {};
  }
```

And change the css to not use the custom property:

```css
.condition-label {
  font-size: var(--kws-condition-label-font-size);
  font-weight: var(--kws-condition-label-font-weight);
  /* color: var(--kws-font-color, #000); */
}
```

Then everything is cool in both dev and prod mode. So this seems to have _something_ to do with custom properties.

Obviously, this is a perfectly valid workaround for my tiny sample. Not sure if it is a valid workaround for the community member. Passed all this info on to them to see if it is something they can work around in the meantime.
