### ISSUE TITLE
Testing: Configured reporter is not reporting

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#1160]
**Stencil version:**

```
 @stencil/core@0.14.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Configured reporter is not creating any files/output

**Expected behavior:**

The configured reporter should be providing output

**Steps to reproduce:**

1. `git clone -b reporter-issue git@github.com:cary-smith/stencil-component-starter.git`
1. `npm install`
1. `npm test`
1. Notice the **target/junit/junit.xml** file is never created.

If the stencil version is set to 0.13.0, everything works as expected.

**Related code:**
```tsx
// nothing to see here
```

**Other information:**

**Comment by adamdbradley** [comment]
Which jest configuration are you using? I'm not seeing where the reporter is being added: https://github.com/cary-smith/stencil-component-starter

**Comment by mattdsteele** [comment]
In a branch here: 
https://github.com/cary-smith/stencil-component-starter/blob/reporter-issue/stencil.config.ts

**Comment by adamdbradley** [comment]
thanks
