### ISSUE TITLE
How can find the ancestor element that has a specific class/id or element

### ISSUE THREAD

**Issue by sudhakarlahane23** [ionic-team/stencil#1165]
**Stencil version:**

```
 @stencil/core@0.14.0-4
```

**I'm submitting a:**

[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

How can we find the ancestor element with the help of stenciljs.
**Expected behavior:**

How can find the parent element with the help of javaScript as examples shown in this link (https://stackoverflow.com/questions/22119673/find-the-closest-ancestor-element-that-has-a-specific-class). But is there any native provision in stencilJs to find the ancestor element?
**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
No, stencil does not provide an api for this since the dom already provides `closest()`.

**Comment by sudhakarlahane23** [comment]
Thanks for reply Adamdbradley and thanks for me update me about this.
But `closest()` not support for any version of IE. Hence we generally uses like following code.

```
function findAncestor (el, cls) {
    while ((el = el.parentElement) && !el.classList.contains(cls));
    return el;
}
```

**Comment by adamdbradley** [comment]
`closest()` is one of the polyfills provided to the the legacy build: https://github.com/ionic-team/stencil#polyfills

**Comment by sudhakarlahane23** [comment]
I tried it. Its working.
Thanks.
