### ISSUE TITLE
Less CSS Support

### ISSUE THREAD

**Issue by edsilv** [ionic-team/stencil#117]
Hi,

I'm lead dev on http://universalviewer.io and Stencil looks perfect for our plans to further componentise the project. After watching your presentation at the Polymer Summit it sounds like you're only supporting SASS compilation at the moment? The Universal Viewer already uses TypeScript extensively, but we've chosen Less as our CSS compiler - in part because it enabled us to keep the project 100% node.js.

Is Less support in the pipeline?

**Comment by jgw96** [comment]
Hello! Less support is not currently in the pipeline. We currently support sass or regular vanilla css. It would be possible to add Less support to Stencil though locally but would require some custom setup. It also looks like there are some tools available to help convert your less to sass http://csspre.com/convert/.

**Comment by edsilv** [comment]
It would be great to know more about how to create a custom setup. Is there any documentation for this?
