### ISSUE TITLE
Bundle size 

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#1172]
**Stencil version:**

```
 @stencil/core@0.14.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

Adding certain packages like Firebase increases the bundle size too much.

**Expected behavior:**

The bundle size shouldn't increase more than what the package would add if I included its distribution version (in fact, I could possibly get smaller bundles with tree shaking).

**Steps to reproduce:**

```
npx create-stencil ionic-pwa test
cd test
npm install @ionic/core@latest @stencil/core@latest
```

Change the service worker precaching in `stencil.config.ts` to ignore es5 stuff and ionicons:

```ts
serviceWorker: {
  swSrc: 'src/sw.js',
  globIgnores: ['build/app/*.es5.*.js', 'build/app/*.es5.js', 'build/app/svg/*.svg'], 
},
```

```
npm run build
```

Serve the `www` directory and after the service worker is done with pre-caching, **638 KB** were downloaded.

Now, I want to use Firebase in my project, so I install it with `npm install firebase` and modify my `app-root.tsx` to use it the recommended way:

```ts
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';

componentWillLoad() {
  firebase.initializeApp({ /* ... */ };
  const db = firebase.firestore();
  db.settings({ timestampsInSnapshots: true });
}
```

Rerunning `npm run build` and serving my `www` folder, I now have **2.1 MB** initial download size, which is way more than expected.

If I replace my imports with `declare const firebase;` and then in `index.html` include the scripts from unpkg.com:

```html
<script src="https://unpkg.com/firebase@5.5.5/firebase-app.js"></script>
<script src="https://unpkg.com/firebase@5.5.5/firebase-auth.js"></script>
<script src="https://unpkg.com/firebase@5.5.5/firebase-firestore.js"></script>
```

then my download size goes down to **782 KB**. But of course now I have the blocking scripts up front.

**Other information:**

In the last case, `firebase-app.js` downloads 12.2 KB, `firebase-auth.js` 45.1 KB and `firebase-firestore` 85.7 KB, which is a total of 143 KB, but the uncompressed size is 539 KB (I think it uses brotli compression).

**Comment by adamdbradley** [comment]
This probably comes down to using side-effect based imports. Since these are firebase imports, and stencil uses rollup, treeshaking and minifying, this isn't a stencil issue. Thanks
