### ISSUE TITLE
Incorrect implementation of CustomEvent polyfill

### ISSUE THREAD

**Issue by OndraM-Kentico** [ionic-team/stencil#1173]
**Stencil version:**

```
 @stencil/core@0.14.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Initializing a `CustomEvent` in IE11 (using Stencil polyfill) throws  `Unable to get property 'bubbles' of undefined or null reference` error.

**Expected behavior:**
Custom event created without error being thrown.

**Steps to reproduce:**
1. Clone `stencil-component-starter` repository
1. In `index.html` file, add the following inline script: 
```
var event = new window.CustomEvent("myevent");
```
3. Run project
1. In IE11, you get the following error in the console: `Unable to get property 'bubbles' of undefined or null reference` 

**Related code:**
Looking into generated file `~/dist/mycomponent/mycomponent.core.pf.js` where the polyfill takes place, I realize that the implementation is not very robust -- there's no null-check on `data` argument. Therefore, if a CustomEvent constructor is called with just one argument, the error mentioned above is thrown. 
```tsx
if ('function' !== typeof win.CustomEvent) {
// CustomEvent polyfill
win.CustomEvent = function(event, data, evt) {
  evt = doc.createEvent('CustomEvent');
  evt.initCustomEvent(event, data.bubbles, data.cancelable, data.detail);
  return evt;
};
win.CustomEvent.prototype = win.Event.prototype;
}
```

**Other information:**
By the specs, the second argument should be optional. See [specification](https://dom.spec.whatwg.org/#interface-customevent)   and sample polyfill [implementation](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill).

**Comment by adamdbradley** [comment]
Would you be able to submit a PR with unit tests updating this? https://github.com/ionic-team/stencil/blob/master/src/renderer/dom-api.ts#L20 Thanks
