### ISSUE TITLE
Flags in combination with --prerender are ignored when running build

### ISSUE THREAD

**Issue by matdec01** [ionic-team/stencil#1175]
**Stencil version:**
```
 @stencil/core@0.14.2
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The `--stats` and `--docs` flags are ignored in combination with `--prerender`.

**Expected behavior:**
Stencil generates `readme.md` and `stencil-stats.json`.

**Steps to reproduce:**
```bash
> stencil build --prerender --stats --docs
```

**Related code:**

❌ Does not generate stats and docs
```bash
> stencil build --prerender --stats --docs
> stencil build --stats --docs --prerender
```

❌ Does not generate docs
```bash
> stencil build --prerender --docs
> stencil build --docs --prerender
```

❌ Does not generate stats
```bash
> stencil build --prerender --stats
> stencil build --stats --prerender
```

✅ Generates stats and docs
```bash
> stencil build --stats --docs
```

✅ Generates stats
```bash
> stencil build --stats
```

✅ Generates docs
```bash
> stencil build --docs
```

**Additional information:**
Node v10.12.0

**Comment by adamdbradley** [comment]
Sorry with the latest version of Stencil, and tested against the stencil-site repo, I haven't been able to recreate this issue.
