### ISSUE TITLE
Build date month is one off

### ISSUE THREAD

**Issue by rjimenezda** [ionic-team/stencil#1176]
**Stencil version:**
```
 @stencil/core@latest
```

**I'm submitting a:**

[x] bug report
[x] feature request

**Current behavior:**

The build date output on the banner has the UTC Month, which made me very confused as to why I had a month old build.

**Expected behavior:**

Well, I would personally expect the build date would use the UTC Month + 1, but maybe this is 100% intended.

**Steps to reproduce:**

Generate a minified build with a banner.

I've submitted a PR (#1177) with the proposed change but I mean it's just adding one to the time, so feel free to discard it.

**Comment by adamdbradley** [comment]
merged
