### ISSUE TITLE
iOS Standalone mode and serviceWorker / importScripts

### ISSUE THREAD

**Issue by joewoodhouse** [ionic-team/stencil#1180]
**Stencil version:**
```
 @stencil/core@0.15.0-0
```

**I'm submitting a:**
[X ] bug report

**Current behavior:**
When a PWA generated with Stencil is added to home screen on iOS, the app will not function offline.

This is due to a bug in iOS Safari. These are some relevant issues:
https://github.com/GoogleChrome/workbox/issues/1494
https://github.com/GoogleChrome/workbox/issues/1583
https://bugs.webkit.org/show_bug.cgi?id=190269

The underlying issue is that scripts included via `importScripts` in a SW are not being cached properly. Apparently this bug has been fixed in Safari Tech Preview 59, but I'm not able to test that. 

**Expected behavior:**
The app and SW should work properly when offline.

**Steps to reproduce:**
Build a PWA (use the ionic-pwa-toolkit), load it on iOS Safari and click "Add To Homescreen". The load the app from homescreen whilst in airplane mode - the app will not load.

**Comment by manucorporat** [comment]
Could you submit a PR with a possible fix?

**Comment by joewoodhouse** [comment]
Do you have any suggestions what the fix might be?

I can't fix the issue in Webkit. I did consider trying to inline the workbox code, but unfortunately that also contains calls to `importScripts` so I don't think that will work either.

**Comment by manucorporat** [comment]
>I can't fix the issue in Webkit.
me neither :)

This issue does not seem related with stencil, and looks like Apple already fixed it in iOS 12.1
https://twitter.com/nekrtemplar/status/1057362949445181440

**Comment by joewoodhouse** [comment]
Just tried it on iOS12.1 and it's working now! Thanks for the heads up.
