### ISSUE TITLE
e2e tests deletes files/folder in the dist folder (using np for example)

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#1184]
**Stencil version:**
```
 @stencil/core@0.15.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Running the e2e tests deletes the `components` folder inside the `dist` folder. This is especially a problem when you run your tests before releasing to npm (for example using `np`).

This is before the tests were run:
<img width="243" alt="bildschirmfoto 2018-10-27 um 21 14 29" src="https://user-images.githubusercontent.com/6666636/47608426-d06d2f00-da2d-11e8-982b-453b81a964c3.png">

And this after:
<img width="236" alt="bildschirmfoto 2018-10-27 um 21 14 56" src="https://user-images.githubusercontent.com/6666636/47608428-d95e0080-da2d-11e8-9903-a5b31dd4b1bc.png">

While writing this issue I also saw in the images that the `loader` folder also gets deleted.

**Comment by adamdbradley** [comment]
thanks for the report!

**Comment by bitflower** [comment]
That was fast :-) Thanks
