### ISSUE TITLE
.ts files not included in bundle

### ISSUE THREAD

**Issue by mattcosta7** [ionic-team/stencil#1187]
**Stencil version:**

```
 @stencil/core@0.15.0
```

**I'm submitting a:**

[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Exported functions from .ts files are not bundle

**Expected behavior:**

They are included in the bundle

**Steps to reproduce:**

,Component starter.  Add a .ts file which exports some helper function.  Build (prod or Dev)
Try to import function

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
Would you be able to create a repo of how this doesn't work? Thanks

**Comment by mattcosta7** [comment]
Not sure what happened.  we had a couple builds fail yesterday (on regression tests checking for the imports),  changing fixed.  then today, changing back and it seems to work (no other code changes).  Not sure what happened, but i'll reopen if it comes back
