### ISSUE TITLE
The polyfill doesnt seem to be working in IE11

### ISSUE THREAD

**Issue by JimDrury** [ionic-team/stencil#119]
When using IE11:
I'm getting an error stating `'Promise' is undefined`, 
I then manually polyfilled it with using https://github.com/taylorhakes/promise-polyfill

After that, it started complaining for each component `TypeError: Object doesn't support property or method 'assign'`
I then polyfilled using https://github.com/rubennorte/es6-object-assign and it started working.

Please note that the bundled polyfill was downloaded.

Example URL: https://codepen.io/jimdrury/pen/RZqoRX (The contents of the JS tab are solely polyfills)

**Comment by adamdbradley** [comment]
Can you try this with version `0.0.5-8`? We just added the promise polyfill for IE11. cc @jgw96

**Comment by adamdbradley** [comment]
I just added some notes about browser support and polyfills to the readme. The next release will have the object assign polfill.

https://github.com/ionic-team/stencil#browser-support
