### ISSUE TITLE
No code coverage collected from Puppeteer tests.

### ISSUE THREAD

**Issue by Bmahecha123** [ionic-team/stencil#1191]
**Stencil version:**
@stencil/core@0.14.0

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
- When I run my tests with coverage `stencil test --spec --e2e --coverage`
A coverage report is only generated for unit tests. No coverage data is collected from Puppeteer Tests. 

**Expected behavior:**
-  I would expect coverage data to be aggregated and added to the overall coverage report that Jest generates. This is how it was prior to Puppeteer.

**Steps to reproduce:**
- Run `npm init stencil`
- Generate a component starter project (could be an app or an ionic app).
- Run `yarn run test --coverage` and you'll see a coverage report generated.
- Comment out or remove the unit tests `.spec.ts` and re run the same command.
- You'll see no coverage is shown even though E2E tests are being ran.

**Comment by adamdbradley** [comment]
I think there might be a misunderstanding on my part, but the tests are running and the coverage is working for spec files. But the e2e tests running the actual, fully compiled app through puppeteer, rather than importing individual modules.

**Comment by Bmahecha123** [comment]
Morning!
The tests all run as expected and coverage is collected from spec files as expected. How can a developer get integration test coverage confidence though? The amount of testing that can be done at a unit level for components won't give the same level of confidence as the testing that can be done at a Component Test level (fully rendered).

Since the addition of Puppeteer I converted my former TestWindow tests to Puppeteer tests and kept my unit tests the same and our overall coverage dropped by a drastic amount due to this inability to collect an lcov that can be aggregated with the lcov generated from our (spec) unit tests.

**Comment by mmakrzem** [comment]
I just filed https://github.com/ionic-team/stencil/issues/1219 which seems to be the same problem as what you have reported here @Bmahecha123

**Comment by Bmahecha123** [comment]
My issue was promptly closed after opening it even though I feel it's a valid issue/feature request.

**Comment by aveiga** [comment]
This is a valid concern, and something that you can do with WCT already (although that's not running Puppeteer, but Selenium)

**Comment by mandric** [comment]
I'll try to come up with some workaround and post them here: https://github.com/mandric/testing-web-components Please let me know if you have any suggestions, thanks!

**Comment by Scionar** [comment]
Currently we are trying to set code coverage restriction, but we cannot test some components. We have made e2e tests, because blur and focus events are unreachable from unit tests, [see another issue](https://github.com/ionic-team/stencil/issues/1964). Reason why we need to reach blur and focus states is testing of [Constraint validation API](https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation) with custom form components.

These two bugs together are preventing us to use code coverage.
