### ISSUE TITLE
The `componentWillLoad` method not included in core

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#1193]
**Stencil version:**

```
 @stencil/core@0.15.1
```

Also occurs in earlier versions

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Components are compiled ONCE and everything is fine. Compile again and `componentWillLoad()` is not called.

**Expected behavior:**
If `componentWillLoad()` exists, it should be called, consistently.

**Steps to reproduce:**
Grab this code and do the usual steps (documented in the README) to compile and link:

https://github.com/kensodemann/lifecycle-error-components

Then grab this code https://github.com/kensodemann/lifecycle-error-host and follow the steps in the README to link the component library and then serve.

Open the console.

Click the "Add Item to List" button. 

If this is working, you will see "description_data6" (7, 8, etc.) added to the **top** of the list. You will also see a full set of lifecycle events in the console log (did load, will update, and did update).

If this is failing, you will see "description_data5" added over and over to the **bottom** of the list. You will also only see "did load" and "did update" events in the console log and no "will update" events

This will most likely work the _first_ (and only the _first_) time that you clone the repo and do a build. If you do a second build it should start failing and stay failing. When that happens, I have found that changing some public properties on the component and then rebuilding will cause it to work properly _once_ but that rebuilding after that without change will put it in a failure state.

Here are the properties I have been changing to do this: https://github.com/kensodemann/lifecycle-error-components/blob/master/src/components/text-truncate/text-truncate.tsx#L21-L26

**Related code:**

For these tests, I did `npm run build -- --es5 --dev` to make the output reasonably readable.

For one test, I commented out the two lines here: https://github.com/kensodemann/lifecycle-error-components/blob/master/src/components/text-truncate/text-truncate.tsx#L24-L25

I then did a build, verified that it worked properly, and then copied `dist` to `dist.good`
I then rebuilt without changing the code at all, verified the host broke, and then copied the `dist` to `dist.bad`

Analyzing diffs between the two "dist" folders the following diff stood out as important:

**good:** https://github.com/kensodemann/lifecycle-error-components/blob/master/dist.good/design-system/design-system.core.js#L1535-L1550

**bad:** https://github.com/kensodemann/lifecycle-error-components/blob/master/dist.bad/design-system/design-system.core.js#L1535

```diff
--- dist.bad/design-system/design-system.core.js	2018-10-30 13:10:06.000000000 -0500
+++ dist.good/design-system/design-system.core.js	2018-10-30 13:08:57.000000000 -0500
@@ -1532,7 +1532,22 @@
       // https://www.youtube.com/watch?v=olLxrojmvMg
             instance = initComponentInstance(plt, elm, plt.hostSnapshotMap.get(elm), perf);
       false;
-    } else false;
+    } else if (true, instance) 
+    // component already initialized, this is an update
+    // already created an instance and this is an update
+    // fire off the user's componentWillUpdate method (if one was provided)
+    // componentWillUpdate runs BEFORE render() has been called
+    // but only BEFORE an UPDATE and not before the intial render
+    // get the returned promise (if one was provided)
+    try {
+      if (instance.componentWillUpdate) {
+        false;
+        await instance.componentWillUpdate();
+        false;
+      }
+    } catch (e) {
+      plt.onError(e, 5 /* WillUpdateError */ , elm);
+    }
     // if this component has a render function, let's fire
     // it off and generate a vnode for this
         render(plt, plt.getComponentMeta(elm), elm, instance, perf);
```

So this basically seems to have to do with something in the compiler that chooses whether or not to include the `componentWillUpdate()` call failing to properly detect the need for it on _second_ (and subsequent) builds unless the component itself is changed in some significant way.

**Comment by EdwardMCastrillon** [comment]
Hi @kensodemann have you ever tried make a test where the ComponentWillLoad needs to be called? I think it does not run at the time of testing neither.

**Comment by kensodemann** [comment]
@EdwardMCastrillon - are you talking e2e or unit tests? Also, do you have an example?
