### ISSUE TITLE
Pupeeteer's api instead of TestWindow

### ISSUE THREAD

**Issue by LalitKushwah** [ionic-team/stencil#1201]
**I'm submitting a:**

[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: 
[x] question
https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

Hello Everyone,

I have a question related to stencil 0.13.x. I am using stencil 0.9.x version in which I am using TestWindow but it will be deprecate in 0.13.x  so how can I use puppeteer's api instead of TestWindow. So can you please share some code base that how can I use puppeteer's api.

**Comment by mmakrzem** [comment]
See the stencil documentation on testing: https://stenciljs.com/docs/end-to-end-testing
