### ISSUE TITLE
No standalone components with `dist` output

### ISSUE THREAD

**Issue by bm-stschneider** [ionic-team/stencil#1204]
**Stencil version:**

```
 @stencil/core@latest
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[X] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I try to output to `dist` to have a component I can copy paste in the devtools console. It then tries to load related files from a location which obviously doesn't work. So it pretty much also acts as the `www` output.

**Expected behavior:**
When I emit for `dist` I want output that is runable ad-hoc in the browser and don't need uploading of files at specific location.
Conflicts with 

> component     Collection of web components that can be used anywhere

**Steps to reproduce:**
npm init stencil
npm build
try to run exported code in browser.

**Comment by adamdbradley** [comment]
The dist directory is an option to build a library to. That dist directory can live under any location and could be renamed. This is an example of a dist directory that can work in any directory, or any web location: https://www.npmjs.com/package/@ionic/core
