### ISSUE TITLE
Prerender is not correctly populating html contents for non-base index.html files

### ISSUE THREAD

**Issue by mistersender** [ionic-team/stencil#1205]
**Stencil version:**

```
 @stencil/core@0.15.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
On `--prerender`, the root `/index.html` file prerenders successfully, however other prerenders. For example, `/search/index.html`, correctly build a distribution that is in the location `/search/index.html`, but the index file itself is actually the base index.html file.

In other words, the folder structure/file structure it prerenders is correct, but the prerendered content is only the base index file. 

**Expected behavior:**
Prerendered files would be correctly derived from their actual original files (eg: `app/search/index.html` would yield a prerendered file in `www/search/index.html` that was based on that file in app.

**Steps to reproduce:**
create a file structure thusly:
/index.html (make sure has a link to `<a href="/search">search</a>` in the document).
/search/index.html
make the two index.html pages different.
run `stencil build --prerender`

**Other information:**
This appears to happen for prerenders that follow links naturally, and also for passing in the `prerenderLocations` to the config, eg: 
```
prerenderLocations: [
        { path: '/' }, { path: '/search' }
      ]
```

**Comment by JVelichko** [comment]
@mistersender do you found the solution how to create nested html structure only in prerender mode?

**Comment by manucorporat** [comment]
Prerendering has been completely refactor in stencil 1.0, and it's likely this issue does not longer apply, if it's still a problem in stencil 1.0, please open a new issue!
