### ISSUE TITLE
Mock CustomEvent has wrong usage of customEventInit args

### ISSUE THREAD

**Issue by marksyzm** [ionic-team/stencil#1206]
https://github.com/ionic-team/stencil/blob/badf06f12699a18ad1cbfd400e388ba65e5693e2/src/mock-doc/event.ts#L39

In here the second argument is being used as the detail itself when actually the detail should a property inside an object.

[Mozilla CustomEvent info](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent)

**Comment by adamdbradley** [comment]
Right you are. We'll get it fixed up, thanks
