### ISSUE TITLE
15.2 - merge - high severity vulnerability

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#1208]
**Stencil version:**

```
C:\ae\adaept.com\ae-icon-info>npm ls @stencil/core
@adaept/ae-icon-info@0.0.1 C:\ae\adaept.com\ae-icon-info
`-- @stencil/core@0.15.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

GitHub Security report
![capture431](https://user-images.githubusercontent.com/140737/47957813-4e738d80-df7a-11e8-93c2-dbdc4e6d6160.png)

**Expected behavior:**

No security issue
![capture432](https://user-images.githubusercontent.com/140737/47957835-aca07080-df7a-11e8-9a72-ed59f478b08c.png)

**Steps to reproduce:**

**Related code:**
npm list

This will show the problematic version of merge in use:
![capture433](https://user-images.githubusercontent.com/140737/47957845-ef624880-df7a-11e8-81ed-ec5d544b76e4.png)

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by manucorporat** [comment]
Fixed!
