### ISSUE TITLE
Styling root element not possible when using `scoped: true`

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil#1215]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When using `scoped: true` the parent element does not receive the base scoped classname, instead it receives the className with `-h` and `-s` postfixes, example:

```html
<picto-icon name="activity" class="sc-picto-icon-h sc-picto-icon-s hydrated">
```
This prevents styling of the parent tag since this css:

```css
picto-icon {
  /* styles */
}
```
Becomes
```css
picto-icon.sc-picto-icon {
  /* styles */
}
```

**Expected behavior:**

The parent element receives the same classname as the children and css styles are applied as expected.

**Steps to reproduce:**

```tsx
@Component({
  tag: 'picto-icon',
  styleUrl: 'icon.styl',
  scoped: true
})
export class Icon {
  componentDidLoad () {
    console.log(
      'has scoped class?',
      this.el.classList.contains(
        (this.el as any)['s-sc'] // false
      )
    )
  }
}
```

**Comment by manucorporat** [comment]
You need to the same styles as it was shadow-dom

**Comment by MiGlez90** [comment]
Hi @snaptopixel, I have the same issue, could you please explain to me how you solved this problem?  Thank you in advance.
