### ISSUE TITLE
Initial css transition

### ISSUE THREAD

**Issue by AkhmedovValikhan** [ionic-team/stencil#1217]
**Stencil version:**

```
 @stencil/core@0.15.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If a component has a styles with transitions, e.g. `transition: all .15 s` they get applied upon initial mount, which is different from static behaviour. Seems it is happening because styles tag getting inserted into DOM after component tag itself.

**Expected behavior:**
No initial transition applies, same as with static websites.

**Steps to reproduce:**
- Create a component with transition in css

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
