### ISSUE TITLE
Code coverage not calculated correctly

### ISSUE THREAD

**Issue by mmakrzem** [ionic-team/stencil#1219]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I have created a simple Stencil component like this:
```
import { Component, Element, Prop } from '@stencil/core';

type Placement = 'top' | 'bottom';

@Component( {
  tag: 'my-toolbar',
  styleUrl: 'toolbar.css',
  shadow: true,
} )
export class MyToolbar {
  @Element() _el! : HTMLStencilElement;

  @Prop( { reflectToAttr: true } ) _placement : Placement = 'top';

  componentWillLoad() {
    this._el.classList.add( 'ignoreGlobalPadding' );
  }

  render() {
    return (
      <slot />
    );
  }
}
```

I test this component using the following code:

```
import { E2EElement, E2EPage, newE2EPage } from '@stencil/core/testing';

describe( 'my-toolbar', () => {
  let page! : E2EPage;
  let toolbarEl1! : E2EElement;

  beforeEach( async () => {
    page = await newE2EPage( { html: `
      <div style="display: grid; grid-template-columns: 150px auto; grid-gap: 5px 5px; align-items: center; justify-items: start;">
        <span>default (placement=top)</span>
        <my-toolbar class="is1">
          <div style="height:25px; width:25px; background-color: red;">A</div>
          <div style="height:25px; width:25px; background-color: blue;">B</div>
        </my-toolbar>

        <span>placement=bottom</span>
        <my-toolbar class="is2" _placement="bottom">
          <div style="height:25px; width:25px; background-color: red;">A</div>
          <div style="height:25px; width:25px; background-color: blue;">B</div>
        </my-toolbar>
      </div>
    ` } );
    } );
    toolbarEl1 = await page.find( 'my-toolbar.is1' );
  } );

  test( 'Renders and attribute checks', async () => {
    expect( toolbarEl1 ).toBeDefined();
    expect( toolbarEl1 ).toHaveClasses( ['hydrated', 'ignoreGlobalPadding'] );
    expect( toolbarEl1.getAttribute( '_placement' ) ).toEqual( 'top' );

    const toolbarEl2 = await page.find( 'my-toolbar.is2' );
    expect( toolbarEl2.getAttribute( '_placement' ) ).toEqual( 'bottom' );
  } );

  test( 'Visual test', async () => {
    const diff = await page.compareScreenshot( { fullPage: false, clip: { x: 0, y: 0, width: 256, height: 150 }, omitBackground: true, } );
    expect( diff ).toMatchScreenshot( { allowableMismatchedPixels: 0, allowableMismatchedRatio: undefined } );
  } );
} );
```

I run the test this way:

```
stencil test --spec --e2e --screenshot --coverage
```

**Expected behavior:**
I'm expecting to see 100% code coverage of my toolbar component, however the coverage report shows this instead:

```
----------------------|----------|----------|----------|----------|-------------------|
File                  |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------------|----------|----------|----------|----------|-------------------|
 components/toolbar   |       40 |      100 |        0 |       40 |                   |
  toolbar.tsx         |       40 |      100 |        0 |       40 |          13,16,21 |
----------------------|----------|----------|----------|----------|-------------------|
```

Having a look at the generated coverage report (/coverage/lcov-report/components/toolbar/toolbar.tsx.html) shows that nothing in the MyToolbar class was tested.  This is incorrect, seeing as if I look at the generated screenshots, I see that the Toolbar component did initialize and render correctly onscreen.

I can **fake** 100% code coverage by adding the following tests:

```
import { MyToolbar } from './toolbar';

describe( 'fake my-toolbar tests', () => {
  let e! : MyToolbar;
  beforeEach( () => {
    e = new MyToolbar();
  } );

  test( 'Create instance & initial values', () => {
    expect( e ).toBeDefined();
    expect( e._placement ).toEqual( 'top' );
  } );

  test( 'Get 100% coverage', () => {
    //this is a fake test, it just makes sure we call each function defined on the MyToolbar class
   // so that the code coverage algorithm reports 100% coverage
    try {
      e.componentWillLoad();

      expect( true ).toBeFalsy(); //should not get here

    } catch( error ) {
      //we get an exception here because this._el was never initialized when new MyToolbar() is called
      const er = new TypeError( 'Cannot read property \'classList\' of undefined' );
      expect( error ).toEqual( er );
    }

    //toolbar is not actually rendered since puppeteer is not actually being used in this test
    expect( e.render() ).toBeTruthy();
  } );
} );
```

**Comment by mmakrzem** [comment]
I wonder if something like https://github.com/istanbuljs/puppeteer-to-istanbul can be used under the hood to get the code coverage reports from e2e tests

**Comment by nborelli** [comment]
I notice that nothing has happened with this issue in about 9 months and that it still has a triage tag on it.  This is an issue for us as well.  There is a lot of functionality in components that cannot be tested in a simple Jest unit test.  We need the code coverage metrics to also reflect the Puppeteer E2E tests.

Has anyone tried writing a Node.js script to run the the test together using the `puppeteer-to-istanbul` package referred to by @mmakrzem ?

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.

**Comment by mandric** [comment]
This is probably not a stenciljs feature as much as a need for a common solution for having puppeteer (e2e tests) accurately reflect code coverage?  So E2EPage and E2EElement both inherit from puppeteer, is there something we can pass to puppeteer to get accurate coverage output from it?  Maybe just give up on the idea of covering lines of code for frontend code all together because it seems to do the opposite of providing a source of truth/trust, maybe track something else like features?   Seems like a catch 22 because unit testing (jest, SpecPage) works great for accurate coverage because you are importing the modules directly and jest can introspect, but it's not so great for providing the context/mocking you need to traverse all code paths.  On the other hand e2e (puppeteer) is great for executing all code paths but provides poor coverage reporting?  Any thoughts or experiences worth sharing? I'm open to suggestions and feel like it should be addressed somehow or at least people could share common workarounds?

**Comment by mandric** [comment]
I'll try to come up with some workaround and post them here: https://github.com/mandric/testing-web-components
Please let me know if you have any suggestions, thanks!
