### ISSUE TITLE
E2E: Issues with waitForChanges()

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#1223]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

In an E2E test, I find an element and click it:

```ts
const button = await page.find('ion-button');
console.log(button);
await button.click();
```

The test logs the button but then fails because of a timeout. If I call the click without awaiting it, the test goes on and passes.

**Expected behavior:**

Awaiting a click shouldn't time out.

**Steps to reproduce:**

I tried reproducing this in a simpler test case but couldn't reproduce it. I will try to investigate further what exactly causes this behavior, but just thought I'd but this in an issue in case others are encountering it as well.

---

**Update:**

Might be related to this:

https://github.com/ionic-team/stencil/blob/71379389bc42840c956c2891b39c7dea07eb6e26/src/testing/puppeteer/puppeteer-element.ts#L51-L54

Why does it call `waitForChanges`?

**Comment by simonhaenisch** [comment]
After writing more E2E tests for our Ionic 4/Stencil app, it seems that `page.waitForChanges()` often times out. I was assuming that if there are no changes to be waited for anymore, `waitForChanges()` should immediately resolve? Would be nice to have some more info about how it exactly works because we're running into several issues, and I wonder whether it's got something to do with testing composed pages vs single components?

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
