### ISSUE TITLE
app doesn't render my component

### ISSUE THREAD

**Issue by pshergie** [ionic-team/stencil#1226]
**Stencil version:**
```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
I changed inner of `AppHome` component and it doesn't appear in DOM (and no console warning)

**Expected behavior:**
render component

**Steps to reproduce:**
delete `app-profile` component
change something in `AppHome` component

**Related code:**

```tsx
import { Component } from '@stencil/core';

@Component({
  tag: 'app-home',
  styleUrl: 'app-home.css',
  shadow: true
})
export class AppHome {
  render() {
    return (
      <div class='app-home'>
        <h1>Hello world</h1>
      </div>
    );
  }
}
```

```tsx
import { Component } from '@stencil/core';


@Component({
  tag: 'app-root',
  styleUrl: 'app-root.css',
  shadow: true
})
export class AppRoot {

  render() {
    return (
      <div>
        <header>Hello world</header>
        <main>
          <stencil-router>
            <stencil-route-switch scrollTopOffset={0}>
              <stencil-route url='/' component='app-home' exact={true} />
            </stencil-route-switch>
          </stencil-router>
        </main>
      </div>
    );
  }
}
```

**Other information:**

**Comment by NorthMcCormick** [comment]
I am also getting the same issue. To recreate I start a new 'app/website' with the CLI using Stencil 0.15.1 and 0.15.2, when I remove the profile component everything breaks.

Removing node_modules and/or the .stencil folder doesn't seem to resolve it for me. I'm really baffled at what is happening...

**Comment by natemoo-re** [comment]
Try adding the following to `app-root.tsx`:
```tsx
import '@stencil/router';
```

Not sure why, but in the current version of Stencil App Starter, `@stencil/router` is only imported by `app-profile`. Best practice is to place all imports in the `app-root` file, since you can get weird bugs like this otherwise.

**Comment by natemoo-re** [comment]
Related issues
- [stencil-app-starter#51](https://github.com/ionic-team/stencil-app-starter/issues/51)
- [stencil-app-starter#57](https://github.com/ionic-team/stencil-app-starter/pull/57)

**Comment by NorthMcCormick** [comment]
How wild, thank you @natemoo-re for the insights!

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
