### ISSUE TITLE
@stencil/core is totally empty

### ISSUE THREAD

**Issue by kevinbeal** [ionic-team/stencil#1231]
**Stencil version:**
```
 @stencil/core@0.15.2
```

**I'm submitting a:**
[x] bug report
[ ] feature request

**Current behavior:**
dist/index.js is empty. Importing from that file does nothing. Everything is undefined.

**Expected behavior:**
```
import { Prop, Component } from '@stencil/core';

console.debug(Prop); // => not equal to undefined
```

**Steps to reproduce:**
Add the example component to a parcel-bundled project using the example from here: https://stenciljs.com/docs/my-first-component

Use a typescript config that looks something like this:

```
{
    "compileOnSave": true,
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": false,
        "declaration": false,
        "alwaysStrict": true,
        "lib": ["dom", "esnext"],
        "typeRoots": ["node_modules/@types"],
        "experimentalDecorators": true,
        "jsx": "react",
        "jsxFactory": "h",
        "moduleResolution": "node",
        "module": "esnext",
        "target": "es2017"
    }
}
```

**Comment by manucorporat** [comment]
This is expected, Stencil decorators are pure compiler-time construction! they don't exist at runtime
