### ISSUE TITLE
preventDefault not working in IE11

### ISSUE THREAD

**Issue by tricki** [ionic-team/stencil#1233]
**Stencil version:**
@stencil/core@0.15.1

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
In IE11, when you emit a custom event and call `preventDefault()` in a listener the event returned from `event.emit()` always has  `defaultPrevented` set to `false`.

**Expected behavior:**
`event.defaultPrevented` should be `true` if `preventDefault()` was called.

**Steps to reproduce:**
- Add a custom event to a component
- Add a listener for that event
- Call `event.preventDefault()` in the listener
- Emit the custom event.
- Check the `defaultPrevented` property on the event returned from `emit()` in IE11

**Related code:**

```tsx

export class AppHome {

  @Event() testEvent: EventEmitter;

  @Listen('testEvent')
  testEventListener(e: CustomEvent) {
    e.preventDefault();
  }

  emitEvent() {
    const event = this.testEvent.emit();

    alert(`Default ${event.defaultPrevented ? '' : 'not'} prevented`);
  }

  render() {
    return (<button onClick={() => this.emitEvent()}>Fire Test Event</button>)
  }
```

**Other information:**
- inside the listener (after the call to `preventDefault()`) `defaultPrevented` is true
- the event received by the listener and the event returned from `.emit()`  are the same (`e === event`).
- `defaultPrevented` seems to get reset after the last event listener.

Possibly the same problem, with solution: https://stackoverflow.com/questions/23349191/event-preventdefault-is-not-working-in-ie-11-for-custom-events

**Comment by tricki** [comment]
Adding `{passive: false}` had no effect. Interestingly `defaultPrevented` is `true` in IE in the listener itself after calling `preventDefault()`. If I add multiple listeners `defaultPrevented` remains `true` in each successive one, but as soon as the event is returned from `emit()` it's `false`.

```jsx

  testEventListener(i, e: CustomEvent) {
    alert(`${i} Before preventDefault(): Default ${e.defaultPrevented ? '' : 'not'} prevented`);
    e.preventDefault();
    alert(`${i} After preventDefault(): Default ${e.defaultPrevented ? '' : 'not'} prevented`);
  }

  emitEvent() {
    this.el.addEventListener('testEvent', e => this.testEventListener(1, e as CustomEvent))
    this.el.addEventListener('testEvent', e => this.testEventListener(2, e as CustomEvent))
    this.el.addEventListener('testEvent', e => this.testEventListener(3, e as CustomEvent))
    this.el.addEventListener('testEvent', e => this.testEventListener(4, e as CustomEvent))

    const event = this.testEvent.emit();

    alert(`Emitter: Default ${event.defaultPrevented ? '' : 'not'} prevented`);
  }

```

In IE11 this outputs:
> 1 Before preventDefault(): Default not prevented
1 After preventDefault(): Default  prevented
2 Before preventDefault(): Default  prevented
2 After preventDefault(): Default  prevented
3 Before preventDefault(): Default  prevented
3 After preventDefault(): Default  prevented
Emitter: Default not prevented

Chrome output is the same except for the last one.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
