### ISSUE TITLE
Can't publish stencil starter 

### ISSUE THREAD

**Issue by liron-navon** [ionic-team/stencil#1235]
**Stencil version:**
```
 @stencil/core@0.15.1 
```

**I'm submitting a:**

[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I created a project from the stencil starter `npm init stencil` and tried to build, but the files have `// mycomponent: CommonJS Main`, including these files: `dist/index.js`, `dist/esm/esm.index.js` .

**Expected behavior:**
Be able to import and deploy stencil.js, the "main" file (according to package.json) should have some code in it?

**Steps to reproduce:**
1. initiate a stencil project: `npm init stencil`.
2. Choose the option of `component` template.
3. Run `npm run build`
4. Try to deploy, link or Import - doesn't work.

**Comment by bodinaren** [comment]
Did you check out the [Framework Integrations](https://stenciljs.com/docs/overview] part of the docs? They include instructions on how to use your stencil components in Angular, React, Vue, Ember and pure JavaScript (the last one is only available through the links on the left).
