### ISSUE TITLE
E2E tests: page.goTo is not a function

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#1237]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

```ts
const page = newE2EPage({ url: '/' });

page.goTo('/somewhere');
```

throws

```
TypeError: page.goTo is not a function
```

**Expected behavior:**

Should be able to go to a certain page, and would be nice if it considers `useHash` option of the router as well.

**Other information:**

https://github.com/ionic-team/stencil/blob/bb4823450f2e1539c79bdc9cd41e347f56f0eee4/src/testing/puppeteer/puppeteer-declarations.ts#L77-L83

This is never implemented in the `newE2EPage` function. There only is `_e2eGoto`, which is the same as `goto` on the Puppeteer page:

https://github.com/ionic-team/stencil/blob/bb4823450f2e1539c79bdc9cd41e347f56f0eee4/src/testing/puppeteer/puppeteer-page.ts#L22

But apparently `goto` gets overwritten with `e2eGoto` if no `url` or `html` is set in the `newE2EPage` options:

https://github.com/ionic-team/stencil/blob/bb4823450f2e1539c79bdc9cd41e347f56f0eee4/src/testing/puppeteer/puppeteer-page.ts#L70-L73

**Comment by rleal1995** [comment]
I'm also having this issue and dont know why its happening

**Comment by azchohfi** [comment]
Me too. Is this a regression?

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
