### ISSUE TITLE
autoFocus and autoComplete are not rendered as attribute

### ISSUE THREAD

**Issue by derkoe** [ionic-team/stencil#124]
When you create an input element with autoComplete or autoFocus the attributes are not added to the DOM.

The following example:

    <input class="new-todo" placeholder="What needs to be done?" autoComplete="on" autoFocus
       onKeyUp={event => this.onKeyUp(event)} />

results with this in the DOM:

    <input placeholder="What needs to be done?" class="new-todo" ssrc="0.1.">

**Comment by jgw96** [comment]
Thanks for opening a PR with us! We will review.

**Comment by adamdbradley** [comment]
Thanks for the PR!!!
