### ISSUE TITLE
HMR doesn't always update component correctly

### ISSUE THREAD

**Issue by matthew-dean** [ionic-team/stencil#1242]
**Stencil version:**

```
 @stencil/core@0.15.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If you change an element from `shadow: false` to `shadow: true`, it doesn't update the component to have shadow DOM in the browser after HMR. I think there were some other edge cases, but is the one I caught.

**Expected behavior:**
HMR reloads updated component.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
