### ISSUE TITLE
component selector starting with "js-" results in invalid-bundle-id

### ISSUE THREAD

**Issue by Farbdose** [ionic-team/stencil#1245]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
App loads forever. Manual reload results in 
    
    TypeError: Failed to fetch dynamically imported module: 
    http://localhost:3333/build/mycomponent/invalid-bundle-id.entry.js 

**Expected behavior:**
Sample app should start normally.

**Steps to reproduce:**

0. Clone `stencil-component-starter` & `npm install`
1. replace the component selector "my-component" with "js-component"
2. `npm run start` 

Demo repository: https://github.com/Farbdose/stencil-js-bug-demo

**Comment by jostschmithals** [comment]
I've noticed the same problem (not only with `js-`, but with something like `jsxyz-` as well); .
Since this is no restriction of native Web Components, I'd assume that this is a bug which should be fixable?

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Comment by jostschmithals** [comment]
Thanks for fixing it. I will try it out.
