### ISSUE TITLE
Stencil starter app tests are broken.

### ISSUE THREAD

**Issue by liron-navon** [ionic-team/stencil#1246]
I guess this is an issue with [stencil-component-starter](https://github.com/ionic-team/stencil-component-starter), so I made the same issue there and created a PR for this: [https://github.com/ionic-team/stencil-component-starter/issues/65](https://github.com/ionic-team/stencil-component-starter/issues/65)

**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[ X] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
Default tests fails with the starter app.

**Expected behavior:**
Default tests should pass.

**Steps to reproduce:**
In the terminal run:
```
npm init stencil # => component
npm test
```

**Related code:**
The default code for the default component spec:
```tsx
import { MyComponent } from './my-component';

describe('my-component', () => {
  it('builds', () => {
    expect(new MyComponent()).toBeTruthy();
  });

  describe('formatting', () => {
    it('returns empty string for no names defined', () => {
      const component = new MyComponent();

      // format does not exist on the component...

      expect(component.format()).toEqual('');
    });
  });
});
```

**Other information:**

I guess the "format" function was changed to "getText", but was not changed in the tests?

The error logs:
```
 PASS  src/components/my-component/my-component.e2e.ts
 FAIL  src/components/my-component/my-component.spec.ts
  ● my-component › formatting › returns empty string for no names defined

    TypeError: component.format is not a function

       9 |     it('returns empty string for no names defined', () => {
      10 |       const component = new MyComponent();
    > 11 |       expect(component.format()).toEqual('');
         |                        ^
      12 |     });
      13 | 
      14 |     it('formats just first names', () => {

```

**Comment by kensodemann** [comment]
Closing since this is being handled via the issue and PR in the starter.
