### ISSUE TITLE
Async await render and warnings

### ISSUE THREAD

**Issue by liron-navon** [ionic-team/stencil#1250]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[X ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm exporting a method using the @method decorator, and stencil gives me warnings about the method not being a promise, but if I will convert it to a promise I cannot use it the the render function since the render function doesn't support async await.

That leaves me stuck with a bunch of warnings.

**Expected behavior:**
The render function should support async await like the react render function.

**Steps to reproduce:**
1. Create a new stencil component
2. Make render an async function
3. Component won't render at all.

**Related code:**

```tsx
@Component({
  tag: 'my-component',
  styleUrl: 'my-component.scss',
  shadow: true
})
export class MyComponent {

 // without the async keyword stencil will throw warnings
  @Method()
  public async getText() {
    return 'why do I have to be a promise?';
  }

 // won't work with async, without async I can't use the method.
 async render() {
   const someValue = await this.getText();
   return <h1>{someValue}<h1>
 }
}
```

**Other information:**
Maybe remove the warning? or allow some way to use async render?
Here is the warning:
```
[ WARN  ]  @Method requires async: src/components/cw-collapsible/cw-collapsible.tsx
           External @Method() getContentDimentions() should return a Promise or void. Consider prefixing the method
           with async, such as @Method async getContentDimentions(). Next minor release will error.

```

**Comment by snaptopixel** [comment]
Also you can return promises from componentWill/DidLoad() to wait for your getText to finish

**Comment by snaptopixel** [comment]
What do you mean by "inside of it"? You need to return the promise... (That's what async does under the hood)

**Comment by dgibson666** [comment]
Does it seem right to do something like this? 

async componentWillLoad() {
        this.settings = await this.host.closest('parent-component').getSettings();
}
Where 'parent-component') replaces my real custom element and getSettings() is a public method (now made async) of a parent component? This is the only way I've been able to make it work as expected with an async method.

**Comment by mmakrzem** [comment]
How about restructuring your code like this:

```
private getTextInternal() {
  return 'why do I have to be a promise?';
}

@Method()
  public async getText() {
    return this.getTextInternal();
  }

 render() {
   const someValue = this.getTextInternal();
   return <h1>{someValue}<h1>
 }
```

**Comment by liron-navon** [comment]
> Instead of making the render async, which sounds like the wrong pattern to use (what happens, for instance if the awaited thing never returns
> 
> also the method decorator is for methods used outside of the stencil context. You would use those in imperative javascript after the component is in the dom somewhere. kind of like form.submit()
> 
> An async method that doesn't rely on the resolution of a promise, should probably not be an async method, since async inherently creates promises, when none are needed, so you're just knocking performance. unless you intended to call getText() from outside of this component (imperatively in js land), you shouldn't be annotating it as a method.
> 
> ```
> @State() text
> 
> // can have @Method, but doesnt need it if not external)
> async function getText() {
>   this.text = await somePromiseyThing()
>   return this.text
> }
> 
> render() {
>     if (!this.text) return null
>    return <h1>{this.text}</h1>
> }
> ```

Yea, but why would I call a function `getText`, if it sets the Text? that's an irrational naming convention.

I see what you're saying, but it seems that I have to create two functions that basically do the same thing as @mmakrzem says.
Though it seems very redundant to have one private function and another public function that simply calls the private one.

**Comment by manucorporat** [comment]
Unfortunately the render() cannot be async. The render() needs to render to the DOM in the same synchronously. You can use `componentWillUpdate` or `componentWillRender`.
