### ISSUE TITLE
Using transpiled libraries/dependencies breaks es5 builds

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil#1251]
**Stencil version:**

```
 @stencil/core@latest
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I'm using a [3rd party animation library](https://popmotion.io) that's written in typescript and transpiled to js when published to npm. Importing this library broke my app in Firefox with no console errors or indication of what went wrong. After debugging with @adamdbradley we discovered this was due to both Stencil and the aforementioned lib using different versions of the `tslib` helpers causing certain functions to be undefined, thus causing errors.

Once compiled with the `--debug` flag we saw the console errors in Firefox (and Chrome when using the `?core=es5` url param.

**Expected behavior:**

A developer can import a dependency/lib that's been transpiled to js from ts without things breaking.

**Steps to reproduce:**

Import Popmotion into a Stencil app and see it break in es5 builds.

**Related code:**
FWIW, I _was_ able to get the app working by importing the `dist` files and typing them:
```ts
// component.tsx
import Popmotion from 'popmotion/dist/popmotion';
Popmotion.tween(…)
```

```ts
// ambient.d.ts
declare module 'popmotion/dist/popmotion' {
  export * from 'popmotion';
}
```

**Other information:**

Here's what @adamdbradley said in our Slack chat for the record:
> Basically, there’s two copies of tslib going into the es5 version. The external library is importing tslib, but window already has it, and somewhere along the way the wrong functions are getting called
I think the fix is to make sure rollup requires the same copy

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
