### ISSUE TITLE
In production, compiler break css font-face url()

### ISSUE THREAD

**Issue by nonconforme** [ionic-team/stencil#1253]
**Stencil version:**
```
 @stencil/core@0.11.0
```

**I'm submitting a:**
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Adding an url() in the component's css was broken after compilation. But works fine in dev.

**Expected behavior:**
I would expect the component to resolve the image css url relatively inside the dist package that gets later used inside the consuming app.

**Steps to reproduce:**
```
@font-face {
  font-family: 'Roboto';
  font-display: swap;
  src: url("../../assets/fonts/roboto/roboto-blackitalic-webfont.eot");
  font-weight: 700;
  font-style: italic;
}
```
end up after compilation:
```
@font-face {
  font-family: 'Roboto';
  font-display: swap;
  src: url("src/assets/fonts/roboto/roboto-blackitalic-webfont.eot");
  font-weight: 700;
  font-style: italic;
}
```
but must be:
```
@font-face {
  font-family: 'Roboto';
  font-display: swap;
  src: url("collection/assets/fonts/roboto/roboto-blackitalic-webfont.eot");
  font-weight: 700;
  font-style: italic;
}
```

Directory "dist/src/assets" doesn't exist after compilation. We only have "dist/collection/assets" directory and there is no options to set the directory structure. There is a similar not resolved issue on old core version : issues/923
Our current solution was a custom bash script that replace urls in css compiled javascript files but it must be fixed in the compiler.

Thanks.

**Comment by stmoreau** [comment]
@nonconforme have a look at the `copy` config regarding the `assets` directory and the issue you have.
https://stenciljs.com/docs/config/#copy

It will help you resolve it 😉

**Comment by nonconforme** [comment]
Assets copy is not the problem.

Here is my stencil.config.js :
`export const config: Config = {
  namespace: 'usecase',
  outputTargets:[
    {
      type: 'dist'
    },
    {
      type: 'www',
      serviceWorker: null
    }
  ],
  copy: [{
    src: require('path').resolve('./src/assets'),
    dest: 'assets'
  }],
  plugins: [sass()],
  globalStyle: './src/assets/css/style.scss'
};
`

As you can see @stmoreau i already use this option. This options copy assets in 'src/' into 'collection/' but **the compiler doesn't translate url from 'src/' to 'collection/'.**

**Comment by nonconforme** [comment]
![stenciljs-compiler-issue](https://user-images.githubusercontent.com/5469120/49364154-e84a6980-f6e3-11e8-9230-34f65e6a8283.png)

- In the right window you can see the translated path.
- In left you can see my copied assets inthe collection directory, created by compiler.
- Right window is the content of compiled file "iw191as3.js"

As you can see the path is incorrect and must be 'collection/assets/font/...'

**Comment by nonconforme** [comment]
Another example of the problem:

[(https://forum.ionicframework.com/t/stenciljs-background-image-css-path/147270)]

**Comment by stmoreau** [comment]
@nonconforme have a look at this repo to check how I deal with this issue you linked.
https://github.com/stmoreau/stencil-image

**Comment by nonconforme** [comment]
@stmoreau i already look at your repo, but it's impossible to use css variables in fot-face...

**Comment by stmoreau** [comment]
@nonconforme Create a repo with the issue and link it here before complaining that people have not tested it and if you're lucky now someone else will look into it. Good luck.

**Comment by nonconforme** [comment]
@stmoreau lots of people try to reproduce problem to understand it before answer. That's why there is a "Steps to reproduce:" section. Your answear are not about my problem, it's not my fault. But if you have tried to reproduce the problem, you'll never post first your first and second answer. And know you are annoyed ?... You can see at this time nobody from stencil have a solution.

**Comment by aderaaij** [comment]
I'm having the exact same problem at the moment, If you're adamant on an example I can make one but @nonconforme's description seems pretty clear to me!

**Comment by nonconforme** [comment]
Yes i've solved this issue.

**Comment by JVelichko** [comment]
@nonconforme Hi, let me know, when plugin will be completed!

**Comment by nonconforme** [comment]
@JVelichko Yes no problem.

It's possible to add an option to compiler and edit createHostStyle() method from "custom-style.ts" from stencil project.
I currently work on a plugin and a custom createHostStyle() method.
I'll soon do a public release.

**Comment by tallcoder** [comment]
Running into the same problem ... but I don't use Stencil. Can someone post what they did to fix it, please?

**Comment by scottlepp** [comment]
@nonconforme can you post your update?

**Comment by bravetarget** [comment]
having issues with `@font-face` url references as well, can anyone provide a working example?
