### ISSUE TITLE
Add Source-Maps

### ISSUE THREAD

**Issue by mmakrzem** [ionic-team/stencil#1255]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm using the stencil starter project found here (https://github.com/ionic-team/stencil-component-starter) and I would like to debug the code in visual studio code. The following configuration lets me launch chrome from within visual studio code:

```
"configurations": [
 {
  "type": "chrome",
  "request": "launch",
  "name": "Launch Chrome against localhost",
  "url": "http://localhost:3333",
  "sourceMaps": true,
  "webRoot": "${workspaceFolder}/www"
 }
]
```

**Expected behavior:**
When I place a breakpoint in visual studio code, I expect execution to stop there.  This doesn't happen.  Instead I get a warning saying 'unverified breakpoint' for all the breakpoints I place in the code.

**Comment by tricki** [comment]
See my answer [on StackOverflow](https://stackoverflow.com/questions/53540548/need-visual-studio-code-configuration-for-debugging-stencil/53541426#53541426), specifically the part about source maps:

> But since Stencil does not generate source maps yet you will only be able to debug the compiled code.
> Source: https://github.com/ionic-team/stencil/issues/219
> 
> My method for finding the correct generated file is to just add a `debugger;` statement so that VS Code will automatically break.

**Comment by ggretz** [comment]
any update on this? is it maybe also possible to debug unit tests / e2e tests?

**Comment by jthoms1** [comment]
Sourcemaps are something we plan to add to the roadmap.  I will leave this issue open as the reference for implementing them.

**Comment by petermikitsh** [comment]
@jthoms1 Is this feature shipping in 1.x? Thanks in advance!

**Comment by tehdb** [comment]
still no source-maps? 😭

**Comment by leoafarias** [comment]
Just a bump for this.. seems like an important feature
