### ISSUE TITLE
CSS-vars not working on runtime IE 11

### ISSUE THREAD

**Issue by warapitiya** [ionic-team/stencil#1257]
**Stencil version:**

```
yarn list v1.12.3
├─ @stencil/core@0.16.0
├─ @stencil/postcss@0.1.0
└─ @stencil/sass@0.1.1
✨  Done in 0.30s.
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently I have CSS Properties in my main container component. Main container component uses multiple other components with `shadow: false`. Only the main container component have `shadow: true`.

Inside the Container component `SCSS` file, I have below:

```css
:host {
    --theme-color: aqua;
}

.hello {
    background-color: var(--theme-color);
}
```

Which will apply whole theme and many more `CSS properties` to the container and sub components.

This works well in `Chrome`, `Safari` and `Firefox`. When I test this on IE 11, It renders only defaults values. but they are not changing dynamically:

```js
this.element.style.setProperty('--theme-color', this.themeColor);
```

**Expected behavior:**

Like other browsers it should change css-vars.

**Steps to reproduce:**

[https://github.com/warapitiya/stenciljs-issue](url)

**Related code:**

https://github.com/warapitiya/stenciljs-issue

**Other information:**

In IE CSS-vars are not supported so I tried to integrate [css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill) which didn't work for me. Then I noticed that when building from Stencil, it creates multiple files:

```txt
dist
├── collection
│   ├── collection-manifest.json
│   ├── components
│   │   └── my-component
│   │       ├── my-component.css
│   │       └── my-component.js
│   ├── interface.js
│   └── utils
│       └── utils.js
├── esm
│   ├── es2017
│   │   ├── build
│   │   │   ├── qgxx45qd.entry.js
│   │   │   └── qgxx45qd.sc.entry.js
│   │   ├── index.js
│   │   ├── mycomponent.components.js
│   │   ├── mycomponent.core.js
│   │   └── mycomponent.define.js
│   ├── es5
│   │   ├── build
│   │   │   ├── qgxx45qd.entry.js
│   │   │   └── qgxx45qd.sc.entry.js
│   │   ├── index.js
│   │   ├── mycomponent.components.js
│   │   ├── mycomponent.core.js
│   │   ├── mycomponent.define.js
│   │   └── polyfills
│   │       ├── array.js
│   │       ├── css-shim.js
│   │       ├── dom.js
│   │       ├── fetch.js
│   │       ├── map.js
│   │       ├── object.js
│   │       ├── promise.js
│   │       ├── string.js
│   │       ├── tslib.js
│   │       └── url.js
│   └── index.js
├── index.js
├── loader
│   ├── index.d.ts
│   ├── index.es2017.js
│   ├── index.js
│   └── package.json
├── mycomponent
│   ├── mycomponent.0davhmcn.js
│   ├── mycomponent.ew4xvfi1.js
│   ├── qgxx45qd.entry.js
│   ├── qgxx45qd.es5.entry.js
│   ├── qgxx45qd.sc.entry.js
│   └── qgxx45qd.sc.es5.entry.js
├── mycomponent.js
└── types
    ├── components
    │   └── my-component
    │       └── my-component.d.ts
    ├── components.d.ts
    ├── stencil.core.d.ts
    └── utils
        └── utils.d.ts
```

For IE it loads `dist/mycomponent/qgxx45qd.sc.es5.entry.js` file, which also contains: 

```text
{return":host{--theme-color:#0ff}.hello{background-color:var(--theme-color)}"}
```

Maybe related to: https://github.com/ionic-team/stencil/commit/7ce800bb738e4c10338d42b444e2a5480bcae502

**Comment by mattcosta7** [comment]
I believe it's pretty much a no go to have dynamic ie11 css vars, due to the tax it would place on rendering (since they can be changed at any level you would basically need to recalculate everything all the time). 

Most ie11 polyfills (if not all) suggest root level definition support only, which I believe is the same as the stencil implementation

**Comment by warapitiya** [comment]
@mattcosta7 That's the same thing I thought. But 10 minitues ago I found this: [https://github.com/luwes/postcss-var-shim](postcss-var-shim) which seems to be working.

Needs to do some more digging.

**Comment by warapitiya** [comment]
Looks like its really impossible to do this. [postcss-var-shim](https://github.com/luwes/postcss-var-shim) could work for some scenarios. But for my scenario, it's kinda impossible.

Closing this ticket since I don't think its a limitation on Stencil.js.
