### ISSUE TITLE
Give a way to know if it's a dev environment or a production one.

### ISSUE THREAD

**Issue by matteobortolazzo** [ionic-team/stencil#1258]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Other information:**
It should be possible to have a way to know if the code is running in dev or prod. A prop like 'isServer'. 
To call different APIs, skip some calls, etc...

**Comment by AkhmedovValikhan** [comment]
Take a look on this one https://github.com/ionic-team/stencil/issues/598

**Comment by matteobortolazzo** [comment]
Thanks, it works :)
