### ISSUE TITLE
CSP Content Security Policy error

### ISSUE THREAD

**Issue by gc392** [ionic-team/stencil#1265]
**Stencil version:**

```
 @stencil/core@0.16.1-4
```

[x] feature request

I am serving a webcomponent through an API gateway in a secure environment, we have an strict policy and I am getting Content Security Policy (CSP) errors because of this line
https://github.com/ionic-team/stencil/blob/v0.16.1-4/src/client/core-esm.ts#L69
It'd be possible to rewrite this method to use normal function? like
`const createHostConstructor = (w) => {
  return class extends w.HTMLElement{}
}
`

**Comment by positlabs** [comment]
I'm also getting CSP errors due to script injection.

<img width="980" alt="Screen Shot 2019-03-20 at 1 48 28 PM" src="https://user-images.githubusercontent.com/1918844/54707370-4e35f200-4b17-11e9-86c6-6a4520fc8732.png">
