### ISSUE TITLE
Documentation regarding exporting classes and functions along with components

### ISSUE THREAD

**Issue by val-o** [ionic-team/stencil#1267]
Hello,
In my current project we have some packages which need to exports not only component but also auxiliary classes. It would be great if we had some guideline regarding this.
For example, let's say we have Dropdown package and apart from dropdown component itself is also exports some functional components and classes (let's say DropdownItem and it cannot be interface)
What is the best practice in such case to ship this package?

**I'm submitting a:**

[x] feature request

**Comment by snaptopixel** [comment]
You can create an `index.ts` in the same dir as your component and export types like so:

```ts
// src/components/my-dropdown/index.ts
export class DropdownItem {
  constructor(
    public label: string;
    public value: any;
  ) { }
  onSelect() { }
}

// src/components/my-dropdown/my-dropdown.tsx
import { DropdownItem } from '.'
class DropDown {
  items: DropdownItem[]
}

// src/components/my-form/my-form.tsx
import { DropdownItem } from '../my-dropdown'

render() {
  <my-dropdown items={[new DropdownItem('foo', 'bar')]}>
}

```

**Comment by AkhmedovValikhan** [comment]
@snaptopixel Hi, thanks for reply, but I want a class/interface/const to be importable from another package along with components. Same way as stencil-router does, i.e. `import { injectHistory } from '@stencil/router'` and you also importing its components. I managed to make it work by basically copying what router does, but I am not 100% sure it is a right way

**Comment by ericclemmons** [comment]
Yep, this is what I needed to know as well!  I'm not sure where this belongs in the docs...  https://stenciljs.com/docs/distribution?
