### ISSUE TITLE
TodoMVC implementation

### ISSUE THREAD

**Issue by kylecordes** [ionic-team/stencil#127]
In the process of getting familiar with Stencil, I've created yet another TodoMVC implementation with it:

https://github.com/kylecordes/stencil-todomvc

https://kylecordes.github.io/stencil-todomvc/

So far this is the only thing I've implemented, so I'm not any kind of expert. But Stencil is pretty new, so I don't know if there are any experts at all outside of the team creating it. Therefore this might be helpful for other people just arriving also.

If anyone has time to look at the code, I'd appreciate any comments. Here's a list of open questions, also in the readme:

* Is this good, idiomatic use of Stencil?
* Are there Stencil idioms yet?
* What about the unsightly flash when changing routes?
* Is this divided in to the "right" number of components?
* The original used UL/LI - but I split the inner component where the LI should
  be - is there anything that can be done to get the LI back?
* Should a better state management solution be used? Redux? MobX?

Stencil team - If this can be made reasonably idiomatic (or if it is already good enough), you can have this code/repo if you want it. Tell me and I'll click to hand over the repo.

**Comment by adamdbradley** [comment]
Awesome thanks. Would you be able to jump on our [slack channel](https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjQ2MzkyMTY0MTk0LTQ4ODgzYjFjNjdkNDY3YWVhMmNlMTljMWQxNTM3Yjg0ZTIyZTM1MmU2YWE5YzNjNzE1MmQ3ZTk2NjQ1YzM5ZDM) and we could help answer any of these questions? Thanks
