### ISSUE TITLE
Whitespace affects ordering of slotted content when `shadow: false`

### ISSUE THREAD

**Issue by scottopherson** [ionic-team/stencil#1270]
**Stencil version:**

```
 @stencil/core@0.9.7
 @stencil/core@0.15.2
```

**I'm submitting a:**

[x] bug report

**Current behavior:**

I noticed this behavior on a project using `0.9.7` but also reproduced with `0.15.2`.

Given:

```
@Component({
  tag: 'outer',
  styleUrl: 'outer.css'
})
export class Outer {
  render() {
    return (
      <inner>
        <slot />
      </inner>
    );
  }
}
```

```
@Component({
  tag: 'inner',
  styleUrl: 'inner.css'
})
export class Inner {
  render() {
    return (
      <slot />
    );
  }
}
```

The following code:

```
<outer>
  <p>Slotted 1 🥇</p>
  <p>Slotted 2 🥈</p>
  <p>Slotted 3 🥉</p>
</outer>
```

Renders _expectedly_ as:

<img width="150" src="https://user-images.githubusercontent.com/479121/49572247-a0e8f680-f8f8-11e8-8cd9-3121c63fae48.png" />

However, the same code with whitespace removed:

```
<outer><p>Slotted 1 🥇</p><p>Slotted 2 🥈</p><p>Slotted 3 🥉</p></outer>
```

Renders _unexpectedly_ as:

<img width="150" src="https://user-images.githubusercontent.com/479121/49572248-a1818d00-f8f8-11e8-9a73-2fc564874f74.png" />

--- 

Different behavior also occurs if `inner` and/or `outer` have more than one top-level element.

Given:

```
@Component({
  tag: 'outer',
  styleUrl: 'outer.css'
})
export class Outer {
  render() {
    return ([
      <div>Outer</div>,
      <inner>
        <slot />
      </inner>
    ]);
  }
}
```

```
@Component({
  tag: 'inner',
  styleUrl: 'inner.css'
})
export class Inner {
  render() {
    return ([
      <div>Inner</div>,
      <slot />
    ]);
  }
}
```

The following code:

```
<outer>
  <p>Slotted 1 🥇</p>
  <p>Slotted 2 🥈</p>
  <p>Slotted 3 🥉</p>
</outer>
```

Renders _unexpectedly_ as:

<img width="150" src="https://user-images.githubusercontent.com/479121/49572249-a1818d00-f8f8-11e8-896f-93495e5c9bc4.png" />

The same code with whitespace removed:

```
<outer><p>Slotted 1 🥇</p><p>Slotted 2 🥈</p><p>Slotted 3 🥉</p></outer>
```

Renders _unexpectedly_ as:

<img width="150" src="https://user-images.githubusercontent.com/479121/49572250-a1818d00-f8f8-11e8-87c7-8758fc10bc49.png" />

---

All of these scenarios render as expected when using `shadow: true`:

<img width="150" src="https://user-images.githubusercontent.com/479121/49572247-a0e8f680-f8f8-11e8-8cd9-3121c63fae48.png" />

**Expected behavior:**

Order of slotted content is not affected by whitespace and is the same regardless of `shadow` being `true` or `false`.

**Some workarounds / things to try:**

- Use `shadow: true`
- Wrap inner `<slot>` in a containing element (instead of being direct child of host)
- If using Angular, configure ng compiler to preserve whitespace `{ preserveWhitespaces: true }` https://angular.io/api/core/Component#preserveWhitespaces

**Steps to reproduce:**

1. Clone https://github.com/scottopherson/stencil-slot-order-repro
2. `npm install && npm start`

**Related code:**

`relocateSlotContent`, `initHostSnapshot`

**Other information:**

https://github.com/ionic-team/stencil/issues/840
https://github.com/ionic-team/stencil/issues/897
https://github.com/ionic-team/stencil/issues/818

**Comment by cary-smith** [comment]
Just saying thanks to @scottopherson for the workaround (wrapping the slot in an element). It solved a similar issue for us with shadow: true components and nested slots (i.e. using a custom component inside another's template with the content going to the nested component).

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
