### ISSUE TITLE
Docs claim Firefox 63 doesn't need es5 polyfill

### ISSUE THREAD

**Issue by LordPython** [ionic-team/stencil#1273]
**Stencil version:** 

```
 @stencil/core@0.16.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When running dev server, connecting with Firefox 63 results in the **This Stencil app is disabled for this browser.* page. This page lists the following diagnostics for why native build's aren't supported in Firefox

**Current Browser's Support:**
- ES Module Imports: true
- ES Dynamic Imports: false
- Custom Elements: true
- Shadow DOM: true
- fetch: true
- CSS Variables: true

**Expected behavior:**
https://stenciljs.com/docs/browser-support claims that Firefox 63+ does not require polyfills.

**Steps to reproduce:**
- Clone https://github.com/ionic-team/stencil-app-starter (this defaults to using `stencil-core@0.15.2` but the result is the same)
- Run `npm run start`
- Connect with Firefox 63

**Other information:**
Given that the actual error page produced by the dev server includes ES Dynamic Imports as a requirement, but https://stenciljs.com/docs/browser-support does not, I'm assuming this is just a matter of updating the docs to to include the additional requirement and list firefox as requiring polyfills for it.

**Comment by manucorporat** [comment]
Stencil One allows firefox to use type="module"!
