### ISSUE TITLE
Serve the prerender attrib generation as separate JS

### ISSUE THREAD

**Issue by DominicBoettger** [ionic-team/stencil#1276]
For the implementation of external prerender solution it would great to be able to be up to date with the current changes in the DOM tree on prerendered content.

I created a external file https://github.com/INSPIRATIONlabs/prerenderer-mt/blob/master/prerender.js for our prerenderer and it would be helpful to be able to stay up to date without checking the code on every release.

**Stencil version:**

```
 @stencil/core@0.16
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
At the moment it's needed to adjust and to check the changes in the stencil core to reflect them in the external solution.

**Expected behavior:**
Create a prerenderer.js file on a build to enable external prererenderer to prerender the content.

**Related code:**
https://github.com/INSPIRATIONlabs/prerenderer-mt/blob/master/prerender.js
https://github.com/INSPIRATIONlabs/prerenderer-mt

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
