### ISSUE TITLE
Chrome (v71) lighthouse, service worker of the PWA toolkit not detected

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#1279]
**Stencil version:**

Stencil core v0-15-2
Workbox v3.4.1

**I'm submitting a:**
[X] bug report

**Current behavior:**
As reported on the slack channel, the lighthouse test of Chrome (v71) seems to not detect the service worker of the PWA toolkit. I don't do anything special, I use the default `sw.js` and default workbox v3.4.1 and nothing special in `stencil.config.ts` neither (`serviceWorker: {swSrc: 'src/sw.js'}`)

**Expected behavior:**
A nice lighthouse test result and a recognized service worker

**Steps to reproduce:**
Lighthouse test on `https://deckdeckgo.app`

**Related code:**

Sources are on Git available: https://github.com/fluster/deckdeckgo-app

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
