### ISSUE TITLE
Built-in PWA Compat

### ISSUE THREAD

**Issue by ardatan** [ionic-team/stencil#1281]
**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

Instead of dealing with PWA Compatibility for each OS, PWACompat does that by using manifest.json. StencilJS can extend this feature like it did for workbox etc.

https://developers.google.com/web/updates/2018/07/pwacompat

It is just an NPM package.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
