### ISSUE TITLE
Assets fail to load if first build has an error

### ISSUE THREAD

**Issue by JCKodel** [ionic-team/stencil#1284]
**Stencil version:**

```
 @stencil/core@0.16.0
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

If you run npm start with some TSX error (for instance: using a method that doesn't yet exists), the build will fail (but it still be watching for changes). After you fix the code, the console is green and the app is loaded, but no assets are found anymore (they throw a 404):

![image](https://user-images.githubusercontent.com/379339/49874442-9f8e6100-fe05-11e8-996a-7976d33e6a8b.png)
(the bottom tabs are suposed to show svgs from assets folder, as well the "missing image" placeholders)

You need to stop stencil --dev and restart it.

**Expected behavior:**

Full recovery of build startup procedures on an initial error fix.

**Steps to reproduce:**

1) Make some component with an imagem from the assets folder
2) Create some error (i.e.: call a method that doesn't exist)
3) Run `npm start`
4) Wait for Stencil to be red on console (showing your error)
5) Fix the error (i.e.: creating the missing method)
6) Your asset won't load and Stencil will be green on console

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
