### ISSUE TITLE
Ie11 disconnect call back errors

### ISSUE THREAD

**Issue by mattcosta7** [ionic-team/stencil#1285]
**Stencil version:**

```
 @stencil/core@0.16.x
```

**I'm submitting a:**

[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

In ie11 when using custom vars without shadow or scope removehost in this line throws as not being a function on the customStyle

plt.customStyle && plt.customStyle.removeHost(elm)

Because of this nothing loads after the initial error.

This is found when consuming using defineCustomElements. I haven't been able to attempt with other build targets, however chrome seems to work without issue 

**Expected behavior:**

No error and components work properly

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by mattcosta7** [comment]
In prod builds the removehost is mangled, not sure if that's partly responsible

**Comment by adamdbradley** [comment]
@mattcosta7 thanks for debugging that! Should be fixed in the next release, thanks!
