### ISSUE TITLE
Better docs for prerendering

### ISSUE THREAD

**Issue by psmyrdek** [ionic-team/stencil#1286]
**Stencil version:**

```
 @stencil/core@0.16.1
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When looking at the most recent version of Stencil docs you can notice that docs regarding https://stenciljs.com/docs/prerendering are pretty limited. As a newcomer I would expect simple "how to" to create basic app with prerendering feature enabled. I discovered some gossips around this feature on Twitter, stackoverflow, github issues, etc., but there are no official updates regarding this feature. 

Somewhere on the Internet I've found that I can `stencil.createRenderer` but actually this method is missing in the newest version I have downloaded.

Can I ask what's the situation around it?

**Comment by balupton** [comment]
The lack of ssr docs for stencil ended up resulting with me going with the zeit now+next combo. I'd love to use zeit now with stencil though.
