### ISSUE TITLE
Tests: Use `callMethod` with a function as argument

### ISSUE THREAD

**Issue by julesjanssen** [ionic-team/stencil#1288]
**Stencil version:**

```
 @stencil/core@0.16.1
```

**I'm submitting a:**

[x] feature request

**Current behavior:**

When trying to call a @Method from an E2E test with a function as argument, that argument ends up in the component as null instead of the expected function (`typeof arg !== 'function'`)

**Expected behavior:**

I'd like to be able to call a method from E2E test passing functions as arguments.

**Steps to reproduce:**

For component, which has a `setCallback` method which expects a function as argument, in test:
```tsx
const cbFunction = function() {
 // something
}

await element.callMethod('setCallback', cbFunction)
```

The argument that arrives in the `setCallback` method is `null` instead of the expected function.

**Comment by vish063** [comment]
I am facing this issue with stencil/core@1.3.3. Any workaround would be highly appreciated.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
