### ISSUE TITLE
How to apply style to dynamically inserted (mapbox) html element inside a stencil component.

### ISSUE THREAD

**Issue by mtin79** [ionic-team/stencil#1289]
Hi everybody,
currently looking into how to use mapbox-gl with a stencil.

mapbox-gl dynamically inserts html elements to render the map into the stencil component via their reference js libraries. so they are inserted outside the shadow dom of the stencil component i am using it in.

is there a way to set styles of dynamically inserted html elements that are rendered into the regular dom?

or is there a good resource on how to style things when a stencil component is set to shadow: true?

thanks for help,
martin

**Comment by manucorporat** [comment]
Github issues are not the place for support requests, stencil shadow-dom is just like normal shadow-dom, there are plenty or resources only! Thanks!
