### ISSUE TITLE
Compiler error when decorator expression is not a call expression

### ISSUE THREAD

**Issue by karlbohlmark** [ionic-team/stencil#129]
If you use a decorator that is not a call expression (but just an identifier reference) you get a compiler error.

I.e,  code similar to the following
```
@Component({tag: 'my-tag'})
class C {
    @mydecorator
    f() {
    }
}
```
causes the following stack trace
```
 TypeError: Cannot read property 'getText' of undefined at
           /Users/karl/p/fail-app/node_modules/@stencil/core/dist/compiler/index.js:7002:111 at visitNodes
           (/Users/karl/p/fail-app/node_modules/typescript/lib/typescript.js:11909:30) at Object.forEachChild
           (/Users/karl/p/fail-app/node_modules/typescript/lib/typescript.js:11983:24) at NodeObject.forEachChild
           (/Users/karl/p/fail-app/node_modules/typescript/lib/typescript.js:90624:23) at
           /Users/karl/p/fail-app/node_modules/@stencil/core/dist/compiler/index.js:7001:20 at Array.forEach
           (<anonymous>) at getMethodDecoratorMeta
           (/Users/karl/p/fail-app/node_modules/@stencil/core/dist/compiler/index.js:6998:20) at visitClass
           (/Users/karl/p/fail-app/node_modules/@stencil/core/dist/compiler/index.js:7287:17) at visit
           (/Users/karl/p/fail-app/node_modules/@stencil/core/dist/compiler/index.js:7301:28) at
           /Users/karl/p/fail-app/node_modules/@stencil/core/dist/compiler/index.js:7304:32
```

**Comment by karlbohlmark** [comment]
There are a few places that needs fixing:

https://github.com/ionic-team/stencil/blob/master/src/compiler/transpile/transformers/method-decorator.ts#L15
https://github.com/ionic-team/stencil/blob/master/src/compiler/transpile/transformers/event-decorator.ts#L18
https://github.com/ionic-team/stencil/blob/master/src/compiler/transpile/transformers/listen-decorator.ts#L19

**Comment by adamdbradley** [comment]
Yeah so we can change it to not throw an error and just work without it requiring `()` if there are no options. But I think our docs will still use `@Prop()` just to stay consistent with `@Prop({ some option } )`. Thanks!

**Comment by karlbohlmark** [comment]
Sounds good! But I was actually more interested in ensuring that other non-stenciljs related decorators won't break the compiler.

**Comment by jthoms1** [comment]
@karlbohlmark I will write some tests and add them to ensure that we ignore decorators that we are not responsible for.  Thanks!

**Comment by jthoms1** [comment]
I have fixed this issues and created tests to validate with commit 18cdaf76. This should be corrected in the next release. Thanks!
