### ISSUE TITLE
pathsResolverPlugin compiler plugin does not support typescript's "baseUrl"

### ISSUE THREAD

**Issue by MattMcFarland** [ionic-team/stencil#1291]
**Stencil version:**
```
@stencil/core@0.16.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
The rollup plugin [pathsResolverPlugin](https://github.com/ionic-team/stencil/blob/03954a1dcf06391dbf7b09f6cb992e4971629cb5/src/compiler/bundle/rollup-plugins/paths-resolution.ts)  does not support [baseUrl](https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url) - a required field when using `paths`.

**Expected behavior:**

Given a directory structure like this:
```
./
  src/data
  src/utils
tsconfig.json
...
```
a tsconfig.json with contents such as:
```json
"compilerOptions": {
  "baseUrl": "src",
  "paths": {
    "@data/*": ["data/*"],
    "@utils/*": ["utils/*"]
  }
}
```
should compile without errors, providing users have import statements such as:
```js
import MyStateTunnel from '@data/myStateTunnel'
// should resolve to `src/data/myStateTunnel`
```

**But it doesn't:** The rollup-plugin does not have any code in it to check baseUrl when it normalizes paths, and there's no unit tests covering that edge case.

**workaround**
```json
"compilerOptions": {
  "baseUrl": "./",
  "paths": {
    "@src/*": ["src/*"]
  }
}
```
works when using an import statment such as:
```js
import MyStateTunnel from '@src/data/myStateTunnel'
// resolves to src/data/myStateTunnel when tsConfig exists one level up from src
```

**Steps to reproduce:**
Set your compilerOptions to use aliases and have a baseUrl other than `./`

**See Also**

 * [paths-resolution.ts](https://github.com/ionic-team/stencil/blob/03954a1dcf06391dbf7b09f6cb992e4971629cb5/src/compiler/bundle/rollup-plugins/paths-resolution.ts)
 * [typescript module resolution doc](https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url)

**Comment by MattMcFarland** [comment]
I believe this might be fixed by changing  [this section of code](https://github.com/ionic-team/stencil/blob/03954a1dcf06391dbf7b09f6cb992e4971629cb5/src/compiler/bundle/rollup-plugins/paths-resolution.ts#L23-L28) from this:

```js
      const paths = tsCompilerOptions.paths || {};

      // Parse each rule from tsconfig
      for (const rule in paths) {
        const normalizedRule = normalizePath(rule);

```

to this:

```js
      const paths = tsCompilerOptions.paths || {};
      const baseUrl = tsCompilerOptions.baseUrl;  // this is required no need to guard
      // Parse each rule from tsconfig
      for (const rule in paths) {
        const normalizedRule = normalizePath(Path.join(baseUrl, rule)));

```

**Comment by leoafarias** [comment]
@MattMcFarland I am currently having the issue on Stencil 1.0.7, even following the workaround suggestion. Guys is there a way we could prioritize this?

**Comment by leoafarias** [comment]
@MattMcFarland I am currently having this issue with 1.0.7 event with the workaround. Did you modify any of the stencil.config.ts, to get this to work?

`but could not be resolved – treating it as an
           external dependency`

**Comment by bjesuiter** [comment]
I'm having the same problem. 
I can't get paths to work with stencil components. 
Event the workaround with `baseUrl: "./"` does not work for me. 

Is there a solution in planning.

**Comment by MattMcFarland** [comment]
@leoafarias I never got this to work, I did point out where I think it could be fixed but didn't try - especially since I just dont have enough domain knowledge over stencil's build toolset.  In the end, my team moved away from stencil because we couldn't get some fundamental things to work, and moved to gatsby with reacyt instead.  I hope the best for stencil, and might still even use it for future projects, but I couldn't recommend it for a large organization, or big projects with a lot at stake.

**Comment by leoafarias** [comment]
@MattMcFarland I agree with your assessment. Not sure what is your use case but it seems stencil is really good if you want to build a design system but more complex cases tend to struggle with the basics

**Comment by FortinFred** [comment]
@leoafarias 
I don't see how the design system vs complexe cases is an argument here.  
Design systems still need some tests for which some paths could be define.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
