### ISSUE TITLE
Do not require dist to run e2e tests

### ISSUE THREAD

**Issue by psmyrdek** [ionic-team/stencil#1292]
**Stencil version:**

```
 @stencil/core@0.16.1
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
In regular CI/CD pipelines, project build is being executed *after* tests succeed. In the current version of stencil, to run e2e tests, `dist` folder containing distribution files have to be present. Otherwise, an error is being thrown:

```
[ ERROR ]  ENOENT: no such file or directory, open
           '<root>/dist/types/components.d.ts'
```

This is especially weird because it seems that before e2e tests some kind of build is being executed (probably the problem is that it's a dev mode build?):

```
09:56:24 [56:19.4]  @stencil/core v0.16.1 🐠
09:56:24 [56:19.4]  testing e2e files
09:56:24 [56:19.4]  build, questions-ui-components, dev mode, started ...
09:56:24 [56:19.5]  transpile started ...
09:56:24 [56:20.4]  transpile finished in 922 ms
09:56:24 [56:20.4]  module map started ...
09:56:24 [56:20.4]  generate styles started ...
09:56:24 [56:20.8]  generate styles finished in 379 ms
09:56:24 [56:20.9]  module map finished in 495 ms
09:56:24 [56:20.9]  generate bundles started ...
09:56:24 [56:20.9]  generate bundles finished in 2 ms
09:56:24 [56:20.9]  generate app files started ...
09:56:24 [56:21.5]  generate app files finished in 601 ms
09:56:24 
09:56:24 [ ERROR ]  ENOENT: no such file or directory, open
09:56:24            '<root on jenkins>/dist/types/components.d.ts'
```

If I reverse the order of tasks (build -> e2e) everything works fine, but logs from build are duplicated.

**Expected behavior:**
It should be possible to run e2e tests before a build.

**Comment by simonhaenisch** [comment]
I understand that you would want to run unit (spec) tests before building to make sure that your code works ok internally, however E2E tests kind of imply that you have a successfully built version of your component that you can run the tests on, so the task order build -> e2e makes more sense imo.

I get your point though about `stencil test --e2e` triggering a (dev) build anyway, so you wouldn't need to make one before. Should probably look into why the `components.d.ts` is missing... do you have `src/components.d.ts` in your source control or is it ignored?

**Comment by psmyrdek** [comment]
Yeah, I get it that e2e kinda run on the already built app, but yes, the redundant build doesn't make much sense for me.

component.d.ts is being tracked

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
