### ISSUE TITLE
can we replace the jest-preprocessor with something more vanilla?

### ISSUE THREAD

**Issue by MattMcFarland** [ionic-team/stencil#1294]
**Stencil version:**

```
 @stencil/core@0.16.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request

Can we separate the jets preproccessor from this project, or at least make it so that we don't need to use stencil's specific preprocessor?  This just adds a lot of overhead to the stencil project - if you could just use something like ts-jest maybe even the one that includes tsx, by perhaps just deprecating decorators (who needs them anyway) - you might gain a huge amount of bandwidth back.  

the preprocessor is a huge thorn in my side right now.  I want to use some jest features that are completely ignored by it.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
