### ISSUE TITLE
Setting --config flag to a ts config file fails

### ISSUE THREAD

**Issue by juanmiguelbesada** [ionic-team/stencil#1295]
**Stencil version:**

```
`-- @stencil/core@0.16.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When trying to build a stencil project passing the --config flag and point it to a ts config file, it do not work.

It looks like it do not transpile de ts file.

**Expected behavior:**

Stencil should build giving a custom stencil.config.ts file

**Steps to reproduce:**

you can test it yourself with the [ionicons](https://github.com/ionic-team/ionicons) repository.

```bash
git clone https://github.com/ionic-team/ionicons.git
cd ionicons
npm install
npm run dev
```

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by simonhaenisch** [comment]
The `--config` flag is being used here in the tests and works:

https://github.com/ionic-team/stencil/blob/48f590f7251d1fb2764978a6a13bda9251aa441c/test/karma/package.json#L9-L10

Could you give some more info please about what exactly isn't working?

**Comment by juanmiguelbesada** [comment]
@simonhaenisch it works because it points to a .js file. When it is a .ts file, fails

**Comment by juanmiguelbesada** [comment]
Fixed in https://github.com/ionic-team/stencil/pull/1339
