### ISSUE TITLE
CLI does not parse/escape parameters correctly

### ISSUE THREAD

**Issue by nagysz** [ionic-team/stencil#1296]
**Stencil version:**

```
 @stencil/core@0.16.1
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
After upgarding to version 0.16.1 (two apps, 0.15.0 and some older as well, other community members reported also strange behaviour upgrading from 0.16.0) the CLI does not parse/escape command line parameters correctly. The behaviour is experienced on Windows 10 and Linux as well (did not have the chance to verify on a mac). 
The erroneous behaviour is connected the additional parameters either as part of an npm script or appended manually.

**Expected behavior:**
`npm run-script test` executes tests just as `npm run test` where the `test` npm script is as follows:
```
"test": "stencil test --spec --e2e"
```

**Steps to reproduce:**

1. Take a component starter with @stencil/core version 0.16.1
2. Execute `npm run-script test` or provide command line parameters (such as test pattern) manually

**Related code:**

`npm run-script test` yields:

```
No tests found
In C:\workspace\slds-custom-components
  263 files checked.
  testMatch: **/*(*.)+(e2e|spec).+(ts)?(x) - 16 matches
  testPathIgnorePatterns: C:\\workspace\\slds-custom-components\.vscode,C:\\workspace\\slds-custom-components\.stencil,C:\\workspace\\slds-custom-components\\node_modules,C:\\workspace\\slds-custom-components\\dist,C:\\workspace\\
slds-custom-components\\www - 60 matches
Pattern: run-script - 0 matches
```

**Other information:**
Jest uses the `micromatch` library that caused inconveniences with the major release of `3.0.0`. It has been rolled back with Jest version 23.4 though. 

- https://github.com/facebook/jest/pull/6661 
- https://github.com/facebook/jest/issues/6546

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
