### ISSUE TITLE
E2E tests - Setting state via setProperty

### ISSUE THREAD

**Issue by matchatype** [ionic-team/stencil#1299]
**Stencil version:**

```
 @stencil/core@0.16.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Within a `component.e2e.ts` test file, setting a state property via `.setState()` is not working.

**Expected behavior:**

`isLoading` state property should be set to `false`.

**Related code:**

```ts
import { E2EElement, E2EPage, newE2EPage } from '@stencil/core/testing'
describe('component rendering', () => {
  let page: E2EPage
  let element: E2EElement

  beforeEach(async () => {
    page = await newE2EPage()
    await page.setContent('<my-component />')
    element = await page.find('my-component')
  })

  test('should change isLoading to true', async () => {
    element.setProperty('isLoading', true)
    await page.waitForChanges()

    const html = await element.find('.loading')
    expect(html).not.toBeTruthy()
  })
})
```

**Other information:**

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
