### ISSUE TITLE
Native DOM events causes type clashes

### ISSUE THREAD

**Issue by kasperisager** [ionic-team/stencil#1300]
Same as #777, which has been closed due to inactivity. However, the problem still persists and was never fixed.

**Comment by AkhmedovValikhan** [comment]
I believe stencil compiler throws a warning message during build if you have overlapping event names, so maybe you need to consider some prefix

**Comment by kasperisager** [comment]
I'm realizing now that the error is probably warranted 🙈 If an event with a name that overlaps with a global native DOM event is defined, both a custom and a native event is thrown causing the handler to be invoked twice.

**Comment by AkhmedovValikhan** [comment]
@kasperisager I had the same issue while developing custom button component, we ended up using react style handlers, i.e. @Prop onClick. It's working as expected in our case, hopefully it will not be broken in future releases
