### ISSUE TITLE
Stencil requires NPM v6 ?

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#1303]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Site shows NPM v6 as a requirement.

![capture476](https://user-images.githubusercontent.com/140737/50730286-9344ad80-10fe-11e9-9dc0-df8add0db1df.png)

**Expected behavior:**

Provide correct requirements definition.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by manucorporat** [comment]
`npm init stencil` is not the same as stencil itself. `npm init` is a npm v6 feature.

In any case, i would recommend to update npm:
```
npm i -g npm
```

**Comment by peterennis** [comment]
@manucorporat 

I am using the latest npm.
Your description resolves the ambiguity I experienced.

A clearer message on the page could be:

`npm init` Requires NPM v6

The link show this:

![capture524](https://user-images.githubusercontent.com/140737/51004936-a803b580-14f1-11e9-8a4e-bc90ac331129.PNG)

Using your clarification:

```txt
Note that you will need to use npm 6 or higher for the `npm init` feature.
```
