### ISSUE TITLE
Production build fails due to rollup issue

### ISSUE THREAD

**Issue by AkhmedovValikhan** [ionic-team/stencil#1306]
**Stencil version:**

```
 0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I am getting error while building prod version app. After quick googling I found that it is related rollup bug, which is fixed in version 1.0.2. Can you please update rollup version?

**Expected behavior:**

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/9393189/50815712-88c12880-1337-11e9-8fc9-24e9029134e7.png)

**Comment by nborelli** [comment]
I am also seeing the same issue as @AkhmedovValikhan has reported.  Here is the link to the Rollup issue:  https://github.com/rollup/rollup/issues/2625
