### ISSUE TITLE
Paths aliases are ignored in unit tests (*.spec.ts)

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/stencil#1307]
**Stencil version:**

```
@stencil/core@0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I have set a path alias in my tsconfig.json, which is ignored when running `npm run test` with the following error:
`Cannot find module '@/helpers/fragment' from 'app-home.tsx'`

This is related to Issue https://github.com/ionic-team/stencil/issues/444

**Expected behavior:**
The paths from the root tsconfig.json should be taken into account.
Angular does this with the file `src/tsconfig.spec.json` which uses `"extends": "../tsconfig.json",`

**Comment by Thiyagarajan-A** [comment]
I am also running in to the same issue. 

@RafaelKr Is worth trying ts-jest for this?

**Comment by RafaelKr** [comment]
It works without problems for me. So it's worth for me and pretty easy to setup.

**Comment by FortinFred** [comment]
I've found another workaround which also works with the VS Code jest extension (orta.vscode-jest).

**Given the following tsconfig paths config**
```
    "paths": {
      "~/*": ["./src/*"]
    },
```

1- Create a **jest.config.js** file
```
const preset = require('@stencil/core/testing/jest-preset')

module.exports = {
  ...preset,  // We need to keep Stencil's config (Mostly for VS Code Jest extension)
  moduleNameMapper: {
    ...preset.moduleNameMapper,  // We need to include Stencil's mappers
    "^~/(.*)$": "<rootDir>/src/$1",  // same as tsconfig
  }
};
```

2- Modify your **stencil.config.ts** to add the **testing** prop
```
import jestConfig from './jest.config';
export const config: Config = {
  ...
  testing: {
    ...jestConfig
  }
}
```

Voila!

Just make sure to keep **tsconfig.paths** and **js-config.moduleNameMapper** in sync

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Comment by FortinFred** [comment]
@adamdbradley IMHO The current issue seems to outlined quite clearly how to replicate the issue...

**Comment by RafaelKr** [comment]
@adamdbradley Do you mean v1.9.0-12? It's not published to npm yet.

It's still not working for v1.9.0-11. If it should be working there I would like to keep it in this issue.

I created a reproduction: https://github.com/RafaelKr/stencil-tsconfig-paths-repro

Steps to create own reproduction:
1. `npm init stencil`
2. `npm i @stencil/core@next` (or `npm i @stencil/core@v1.9.0-11`)
3. Add the following to your `tsconfig.json`:
```diff
{
  "compilerOptions": {
    ...
+   "baseUrl": "./",
+   "paths": {
+     "~/*": [
+       "src/*"
+     ]
+   }
  },
  ...
}
```

4. Create file `src/tsconfig-paths-test.ts` with the following content:
`export const tsConfigPathsAliasWorksText = 'The tsconfig path alias is working!'`

5. Import that file in `src/components/app-home.tsx`, `src/components/app-home.e2e.ts` and `src/components/app-home.spec.ts`.
```
import { tsConfigPathsAliasWorksText } from '~/tsconfig-paths-test'
console.log(tsConfigPathsAliasWorksText)
```

6. Now I tried to run `npm test` and got an error:
```
> stencil-tsconfig-paths-repro@0.0.1 test /home/rafael/coding/private/stencil/stencil-tsconfig-paths-repro
> stencil test --spec --e2e


[ ERROR ]  Cannot find module 'chalk' Require stack: -
           /home/rafael/coding/private/stencil/stencil-tsconfig-paths-repro/node_modules/@stencil/core/testing/index.js

[...]
```
I fixed it by running `npm i -D chalk`

7. Run `npm test` again. Now it should throw the error
```
...
Cannot find module '~/tsconfig-paths-test' from 'app-home.e2e.ts'
...
Cannot find module '~/tsconfig-paths-test' from 'app-home.tsx'
...
```

When running npm start it works without any problems.
