### ISSUE TITLE
SVG Text node breaks render patching.

### ISSUE THREAD

**Issue by daqst** [ionic-team/stencil#1309]
**Stencil version:**

```
 @stencil/core@0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When dynamically adding children to an SVG element (e.g. adding a new `path` on click of a button), if the `svg` contains a `text` node with text, any subsequent SVG elements will not render correctly.

**Expected behavior:**

The entire SVG element and all its children should render.

**Steps to reproduce:**

- Clone the following repo: [stencil-svg-test](https://github.com/daqst/stencil-svg-test)
- run `npm i`
- run `npm start`
- Click the button 'Add Path' one or more times.  Each time a rectangle is added to the SVG
- Click the button 'Add Text'.
- Any further click to either 'Add Path' or 'Add Text' will not render anything to the SVG, even though the elements are added to the DOM.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

The problem seems to be [`patch.ts:L395`](https://github.com/ionic-team/stencil/blob/644aeff2f8a0d10aea51a9c7a45026203b826890/src/renderer/vdom/patch.ts#L395) 

When the function is called on the text node inside an SVG Text Element, it does not have an `ownerSvgElement` property so the isSvgMode is broken early.  Any new SVG elements added are rendered without the SVG namespace.

Because of this, the bug only appears when adding a new child element to the SVG that already has a Text node.  When rendering with a fully defined SVG the createElm function does not have the same problem.

What's worse is that adding the elements themselves does not actually fail, it is just not being added with the correct namespace.  Stencil continues and adds other `<path>` or elements as `HTMLUnknownElement` (which then doesn't render).

Note:  I've only tested this in Chrome v71.

A possible solution would be to look if the patched element is text and parent element has a non-undefined `ownerSvgElement` property.

**Comment by daqst** [comment]
I have forked a copy of Stencil, and implemented the fix.

I could use some help writing tests for it.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
