### ISSUE TITLE
Plugins not compatible with rollup

### ISSUE THREAD

**Issue by RichiCoder1** [ionic-team/stencil#1312]
**Stencil version:**
```
@stencil/core@0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request

**Current behavior:**
Attempting to use a rollup plugin like `rollup-plugin-url` throws an error saying that importing a file like `example.svg` requires a plugin.

**Expected behavior:**
The svg file is properly transformed into a base64 export.

**Steps to reproduce:**
* `npm i -D rollup-plugin-url`
* In `stencil.config.js`
    * `import url from 'rollup-plugin-url`
    *  `plugins: [ url() ]`

**Related code:**
Where `example.svg` is a valid svg.
```tsx
import svg from './example.svg'
```

**Other information:**
Reading the documentation seems to imply that any ole rollup plugin should work, and in fact they share the same interface. However now plugin I've tried works (aside from stencil's official plugins). The issue with `url` specifically seems to be that `stencil` isn't respecting it's `load` hook.

**Comment by RichiCoder1** [comment]
I did that also, that sadly wasn't the issue here.

**Comment by brion-fuller** [comment]
I believe I am having a similar issue with using "rollup-plugin-svg" as it seems to be completely ignored.  I did add the svg.d.ts and seem to keep getting a Duplicate identifier issue.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
