### ISSUE TITLE
Using npm init stencil, build fails on fresh project

### ISSUE THREAD

**Issue by positlabs** [ionic-team/stencil#1313]
**Stencil version:**

```
 @stencil/core@~0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

Trying to build (`npm run build`) the project fails with an error.

It's worth noting that the `npm start` aka `stencil build --dev --watch --serve` command DOES work.

**Expected behavior:**

Project builds with no error

**Steps to reproduce:**

Using Node 8.15.0 and npm 6.4.1

`npm init stencil`
✔ Pick a starter › app
✔ Project name › stencil-test
`cd stencil-test/`
`npm run build`

```
[ Error ]  TypeError: Cannot read property 'toString' of undefined at e.getRenderedHash
           (/workspace/stencil-test/node_modules/@stencil/core/dist/sys/node/index.js:1:324262) at
           /workspace/stencil-test/node_modules/@stencil/core/dist/sys/node/index.js:1:325017 at
           e.visitDependencies
           (/workspace/stencil-test/node_modules/@stencil/core/dist/sys/node/index.js:1:324643) at
           e.computeContentHashWithDependencies
           (/workspace/stencil-test/node_modules/@stencil/core/dist/sys/node/index.js:1:324921) at
           /workspace/stencil-test/node_modules/@stencil/core/dist/sys/node/index.js:1:329531 at
           /workspace/stencil-test/node_modules/@stencil/core/dist/sys/node/index.js:1:313503 at
           String.replace (<anonymous>) at renderNamePattern
           (/workspace/stencil-test/node_modules/@stencil/core/dist/sys/node/index.js:1:313462) at
           e.generateId
           (/workspace/stencil-test/node_modules/@stencil/core/dist/sys/node/index.js:1:329417) at
           assignChunkIds
           (/workspace/stencil-test/node_modules/@stencil/core/dist/sys/node/index.js:1:455624)
```

**Comment by snaptopixel** [comment]
Yup, I generated a new project got the build error then deleted the `stencil-router-link` from `app-home.tsx` and it built fine.

**Comment by basudebpalfreelancer** [comment]
I have faced the same problem. npm start works, but npm run build fails with an error that matches to the error message in this bug report. I am using stencil v0.16.4

**Comment by basudebpalfreelancer** [comment]
seems like this is related to this problem
https://github.com/rollup/rollup/issues/2625

**Comment by basudebpalfreelancer** [comment]
creating **ionic pwa** with npm init stencil **does not result in a build failure** with stencil v0.16.4
creating **stencil component** with npm init stencil **does not result in a build failure** with stencil v0.16.4
creating **stencil app** with npm init stencil **results in a build failure** with stencil v0.16.4

**Comment by hcavalieri** [comment]
I was facing the same issue, but the new `0.17.0-0` version solves it somehow!

I'm using `stencil-router@0.3.2` :)

**Comment by basudebpalfreelancer** [comment]
v0.17.0 does not have build error
