### ISSUE TITLE
documentation code blocks are not generating properly in the readme

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/stencil#1314]
**Stencil version:**

```
@stencil/core@0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The generated documentation for a code block is including the `*`

**Expected behavior:**
It would show the code block without any `*`

**Steps to reproduce:**
Add the following documentation above a `@Method`:

```
/**
 * This method marks the tail the items array as dirty, so they can be re-rendered.
 *
 * It's equivalent to calling:
 *
 * ```js
 * virtualScroll.checkRange(lastItemLen);
 * ```
 */
```

See the README generate it as:

```
This method marks the tail the items array as dirty, so they can be re-rendered.

It's equivalent to calling:

```js
   * virtualScroll.checkRange(lastItemLen);
   * ```
```

**Related code:**
https://github.com/ionic-team/ionic/blob/master/core/src/components/virtual-scroll/virtual-scroll.tsx#L222-L231
https://github.com/ionic-team/ionic/tree/master/core/src/components/virtual-scroll#checkend--void

**Other information:**
I've confirmed this also happens above a Prop.

**Comment by brandyscarney** [comment]
Just FYI I am removing the code examples that break our site from Ionic, but this is still a bug with the docs generation: https://github.com/ionic-team/ionic/pull/18075

**Comment by adamdbradley** [comment]
Should be fixed in latest releases.
