### ISSUE TITLE
Is there a stenciljs roadmap?

### ISSUE THREAD

**Issue by LeoAlvarez** [ionic-team/stencil#1315]
Is there a roadmap and timelines for stenciljs? Don't see anything in the docs or site.

**Comment by shreeshbhat** [comment]
I like to check out the following link for work updates : 
https://github.com/ionic-team/stencil/projects/1

**Comment by claviska** [comment]
This was announced a couple days ago. https://stenciljs.com/blog/stencil-roadmap-fall-2019

**Comment by arjunyel** [comment]
Thank you for posting @claviska!
