### ISSUE TITLE
Missing type definitions for <video> element

### ISSUE THREAD

**Issue by JackuB** [ionic-team/stencil#1317]
**Stencil version:**

```
 @stencil/core@0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When adding event handlers on video element I get an error:

`Property 'onCanPlay' does not exist on type 'VideoHTMLAttributes<HTMLVideoElement>'.`

```
[ ERROR ]  TypeScript: src/components/video.tsx:28:9
           Type '{ onCanPlay: () => void; onEnded: () => void; src: string; controls: boolean; }' is not assignable to
           type 'VideoHTMLAttributes<HTMLVideoElement>'. Property 'onCanPlay' does not exist on type
           'VideoHTMLAttributes<HTMLVideoElement>'.

     L27:  <figure>
     L28:    <video
     L29:      onCanPlay={() => console.log('Video ready')}
```

Although the event is executed
![screen shot 2019-01-15 at 10 51 18](https://user-images.githubusercontent.com/1788727/51172500-a51f1100-18b3-11e9-8341-9a1a08dce9cf.png)

Looks like it's only missing from the tsx definition (along with some others from https://reactjs.org/docs/events.html)

**Related code:**

```tsx
<video onCanPlay={() => console.log('Video ready')}>
  <source src={url} />
</video>
```

**Comment by simonhaenisch** [comment]
Here is the full list of media events (for `<video />` and `<audio />`): https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events.

Here's the interface:

https://github.com/ionic-team/stencil/blob/48f590f7251d1fb2764978a6a13bda9251aa441c/src/declarations/jsx.ts#L385-L397
