### ISSUE TITLE
Importing stencil web component into Angular returns error with type JSX

### ISSUE THREAD

**Issue by stephenbe** [ionic-team/stencil#1318]
**Stencil version:**

```
 @stencil/core@0.16.1
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
when I do `ng serve` I get this error : 

```
ERROR in src/assets/n3-stencil/types/components/my-component/my-component.d.ts(17,15): error TS2503: Cannot find namespace 'JSX'.
src/assets/n3-stencil/types/components/n3-incrementeur/n3-incrementeur.d.ts(31,15): error TS2503: Cannot find namespace 'JSX'.

i ｢wdm｣: Failed to compile.
```

**Expected behavior:**
I expect it to be able to build without fail.

**Steps to reproduce:**
I added my dist folder into assets and added this line into my main.ts

`import { defineCustomElements } from "./assets/n3-stencil/loader"`

I renamed my dist folder to n3-stencil

If I delete the types folder inside my dist folder, angular does not output an error.

**Other information:**
```
Angular CLI: 7.2.1
Node: 8.9.4
OS: win32 x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cli                      7.2.1
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1
```

I can add a github repo if that would help.

Thanks

**Comment by aleix10kst** [comment]
Same here, using 0.16.2. 
Removing types folder from dist solves the problem, but I think that's not the right way to do.

**Comment by stephenbe** [comment]
okay I understand why it wasn't working, it's because you are suppose to use it as a node_module. If you add it manually thats when you start getting errors. Anyway we could add it manually without having to publish the package to npm?

**Comment by peterpeterparker** [comment]
@stephenbe copy your component at build time (add a rule in assets of your angular.json file) and then consume/load your component with a script tag in your index.html

like in angular.json

```
{
                "glob": "webphotofilter.js",
                "input": "node_modules/web-photo-filter/dist",
                "output": "./"
              },
              {
                "glob": "webphotofilter/*",
                "input": "node_modules/web-photo-filter/dist",
                "output": "./"
              }
```

and in index.html

```
<script async src="webphotofilter.js"></script>
```

it's what I do in my Ionic Angular app

hope it helps https://github.com/fluster/fluster-app
