### ISSUE TITLE
[URGENT] Click event not firing on chrome.

### ISSUE THREAD

**Issue by threeaccents** [ionic-team/stencil#1320]
**Stencil version:**

```
 @stencil/core@0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

If using an apple macbook trackpad and a user clicks instead of taps sometimes the click event is not registered; however, if a user taps the trackpad then it is registered every time. This only happens on chrome all other browsers tested the bug does not occur.

Chrome version = Version 71.0.3578.98 (Official Build) (64-bit)

**Expected behavior:**

click and tap events to be registered

**Steps to reproduce:**
I created a repo showing the bug. 

**Related code:**
https://github.com/threeaccents/chrome-jsx-click-bug

**Comment by AkhmedovValikhan** [comment]
Having same issue on windows pc

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
