### ISSUE TITLE
Importing stencil web component into React returns error with polyfills

### ISSUE THREAD

**Issue by stephenbe** [ionic-team/stencil#1321]
**Stencil version:**

```
 @stencil/core@0.16.1
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
when I do `npm start` I get this error : 

```
> react-scripts start

Failed to compile.

./src/n3stencil/esm/es5/polyfills/css-shim.js
  Line 3:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
```

**Expected behavior:**
I expect it to be able to build without fail.

**Steps to reproduce:**
I added my dist folder into src and here is my index.js
```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

// test-component is the name of our made up Web Component that we have
// published to npm:
import { defineCustomElements } from "./n3stencil/loader";

ReactDOM.render(<App />, document.getElementById("root"));
defineCustomElements(window);
serviceWorker.unregister();
```

I renamed my dist folder to n3-stencil

**Other information:**

create react app version 2.1.3 

I can add a github repo if that would help.

Thanks

**Comment by stephenbe** [comment]
I tested it as a node_module and it work perfectly, my errors are because that when you add it in the src folder, create react app reads parses it with linters and such. 

Is there anything you guys can do to make it work if you add it manually into src?

**Comment by gino8080** [comment]
yep same error, 
any fix / workaround?

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
