### ISSUE TITLE
support for custom polyfills in stencil.config.ts

### ISSUE THREAD

**Issue by Jimmysh** [ionic-team/stencil#1325]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

not supported

**Comment by cary-smith** [comment]
This is likely more of a documentation issue. 

It is possible to run polyfills via the `globalScript` option of the  stencil config. At least that is how we have been using it:

```ts
export const config: Config = {
   /** other config options */
    globalScript: 'src/global/index.ts',
};
```
Then set up the `src/global/index.ts` file to import all the polyfills you might need.

**Comment by Jimmysh** [comment]
I mean add custom polyfills loaded on-demand same as stencil
