### ISSUE TITLE
Build failed with namespaces from npm packages

### ISSUE THREAD

**Issue by MaFa961** [ionic-team/stencil#1327]
**Stencil version:**

```
 @stencil/core@<0.16.2>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I imported a namespace from a npm project and use the types.
The build failed with message: 
```
TypeScript: src/components.d.ts:16:16
Cannot find namespace 'DataModels'

L15:  interface MyComponent {
L16:    'userTask': DataModels.UserTasks.UserTask;
L17:  }
```

Inside of the components.d.ts is no import for the npm package.

The first load of the page prints `TypeScript Error`.
By reloading the page, it prints all the data like expected without error.

Tested with Chrome version 71.0.3578.98

**Expected behavior:**

1. It should import the npm package inside components.d.ts.
1. It should print the data also at the first load without error.

Expected output: `ID: USER-TASK-ID , Name: USER-TASK-NAME`

**Steps to reproduce:**

1. Start new Stencil project with component.

1. Add consumer_api_contracts to package.json

   `npm i @process-engine/consumer_api_contracts --save`

1. Copy the MyComponent class below.

1. Copy the index.html below.

1. Start the project.

**Related code:**

The first lines from components.d.ts
```tsx
import '@stencil/core';


export namespace Components {

  interface MyComponent {
    'userTask': DataModels.UserTasks.UserTask;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'userTask'?: DataModels.UserTasks.UserTask;
  }
}
```

The MyComponent class
```tsx
import { Component, Prop } from '@stencil/core';
import { DataModels } from '@process-engine/consumer_api_contracts';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {

  @Prop() userTask: DataModels.UserTasks.UserTask;


  private getText(): string {
    console.log(this.userTask.id);
    return "ID: " + this.userTask.id + " , Name: " + this.userTask.name;
  }

  render() {
    return <div>{this.getText()}</div>;
  }
}
```

The index.html
```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
  <title>Stencil Component Starter</title>
  <script src="/build/mycomponent.js"></script>


</head>
<body>

  <my-component id="test-comp"></my-component>

  <script>
      var userTaskData = {formFields: [{id: "USER-TASK-DATA-ID",
                                        type: 'string',
                                        enumValues: [{id: 'ENUM-VALUES-ID', name: 'ENUM-VALUES-NAME'}],
                                        label: 'USER-TASK-DATA-LABEL',
                                        defaultValue: 'USER-TASK-DATA-DEFAULT-VALUE',
                                        preferredControl: 'USER-TASK-DATA-PREFERRED-CONTROL',
                                      }]};

      var userTask = {id: "USER-TASK-ID",
                      flowNodeInstanceId: "",
                      name: "USER-TASK-NAME",
                      correlationId: "",
                      processInstanceId: "",
                      processModelId: "",
                      data: userTaskData,
                      tokenPayload: "USER-TASK-TEST-TOKEN"};
      var component = document.getElementById("test-comp");
      component.userTask = userTask;
  </script>

</body>
</html>
```

**Other information:**

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
