### ISSUE TITLE
RxJS operator causes serious runtime bug [v0.16.0 -> v0.16.1]

### ISSUE THREAD

**Issue by Nudelsieb** [ionic-team/stencil#1328]
**Stencil version:**

```
 @stencil/core@0.17.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Using an pipeable operator from RxJS causes Stencil to break with the following error:
`TypeError: Cannot read property 'h' of undefined`

**Expected behavior:**

The RxJS subscription should execute as expected and the Stencil component should render.

**Steps to reproduce:**

Stencil version 0.17.0
RxJS version 6.3.3

**Related code:**
This is a simlified version.

```tsx
import { Component, Prop, State, Watch } from '@stencil/core';
import { first } from 'rxjs/operators';

...

@Prop()
  observableList: [];

  @Watch('observableList')
  onDataChange(observableList) {
    this._readObservableList(observableList);
  }

  private _readObservableList(observableList) {
    observableList.forEach(obs => {
      obs
        .pipe(first())
        .subscribe(value => {
          console.log(value);
        });
    });
  }
```

**Other information:**

When I remove the pipe it works: no error appear and the comonent renders. I will need to use operators. So leaving them out is not a solution.

**EDIT**

I just tried to check if this problem existed with older versions of Stencil. So I rolled back to several releases before v0.17.0. In v0.16.0 the dev build still works fine. After upgrading to v0.16.1 the described error occurs and the component can't be used.

What I also found, and this is crucial: With all affected version doing `npm start --prod` stops the problem, no error on the console whatsoever and the component works as intended.

Something must have regressed from v0.16.0 -> v0.16.1.

**Comment by Nudelsieb** [comment]
I tried to include my component into this app https://github.com/nerdic-coder/stencil-tour-of-heroes

Here it works and I found out why. Stencil Router makes it work. The components included in that app are registered with the router. As long as I leave on component `<stencil-route-link>` the error disappears. It does not have to be my component, any component suffices. Somehow the router changes the component registration I guess, and therefore registration of external dependencies.

**Comment by kairos666** [comment]
Hi! Just my two cents here. 
Your code sample and package versions for stencil compiler and RxJS completely matches mine.
Only difference is that I don't use stencil-router (component library)

Fortunately never experienced such bugs. Hope it helps pipoint the origin of your bug.

**Comment by Nudelsieb** [comment]
Hi @kairos666 thanks for your 2 cents 😄 .

I believe you misunderstood. The original bug appears in a setup witho NO stencil router. I injected the component into a project that uses stencil router and, like a miracle, the bug disappeared. So stencil router must clearly do something different to regist the components.

May I ask whether your project is open source so I can look at a code example of yours?

**Comment by teious** [comment]
problem persists using v0.18.0

**Comment by tehdb** [comment]
I faced similar issue with stencil component generator: https://stackoverflow.com/questions/54892708/stencil-with-rxjs-6

**Comment by angulartist** [comment]
Same issue with Core.v.0.18.1

**Comment by Nudelsieb** [comment]
I can confirm that this works now with Stencil One. Could be closed.
