### ISSUE TITLE
--prerender freezes if a .tsx file has a number in it

### ISSUE THREAD

**Issue by MattMcFarland** [ionic-team/stencil#1329]
**Stencil version:**

```
 @stencil/core@0.17.0
```
**It should be noted here, that versions prior to 0.17.0 (0.15 and 0.16) fail to render the html, but do not freeze.  They dont report errors either.**

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
With pre-rendering enabled, any file with a number as part of its name will not successfully render to html, and instead, it freezes.

**Expected behavior:**
Pre-rendering should not have issues with filenames that contain numbers in them.  

**Steps to reproduce:**
With pre-rendering enabled, any file with a number as part of its name will not successfully render to html, and instead, it prerender will freeze.

**Other information:**
This issue has been around for at least the last previous two "minor" versions, but manifests itself differently.  In 0.17, we freeze, in 0.15 and 0.16 - it simply fails to render the file.  Unfortunately, it does not report any errors.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
