### ISSUE TITLE
How to extend custom elements?

### ISSUE THREAD

**Issue by psyrendust** [ionic-team/stencil#133]
Is there a way to extend custom elements that we create with Stencil? For instance, what if I have a bunch of elements with similar functionality that I would like to extend (`Control.ts`):

```js
// Control.ts
import { Element, Event, EventEmitter, Method, Prop, State } from '@stencil/core';

export class Control {
  @Element() element: HTMLElement;
  @Event() addControl: EventEmitter;
  @Prop() position: string = 'top-right';
  @State() app: any;

  componentDidLoad() {
    const position: string = this.position;
    const control: HTMLElement = this.element;
    this.addControl.emit({ control, position });
  }

  @Method()
  onAdd(app) {
    this.app = app;
    return this.element;
  }

  @Method()
  onRemove() {
    this.element.parentElement.removeChild(this.element);
  }
}
```

This would implement the basic functionality from `Control.ts`.
```js
// navigation-control.tsx
import { Component, Method } from '@stencil/core';
import Control from './Control';

@Component({
  tag: 'navigation-control',
})
export class NavigationControl extends Control {
  @Method()
  zoomIn() {
    this.app.zoomIn();
  }

  @Method()
  zoomOut() {
    this.app.zoomOut();
  }

  render() {
    return (
      <div class="app-ctrl">
        <button class="app-ctrl-zoom-in" type="button" aria-label="Zoom In" onClick={() => this.zoomIn()}></button>
        <button class="app-ctrl-zoom-out" type="button" aria-label="Zoom Out" onClick={() => this.zoomOut()}></button>
      </div>
    );
  }
}
```

I'm totally not sure if this would be the correct way to go about this, or if I would need to add the `@Component` decorator to `Control.ts`.

**Comment by adamdbradley** [comment]
You could have a common base class called `Control`, but it shouldn't need any decorators. Then, each component can extend Control. You could also look into more of a mixin pattern which Polymer is doing more of.

However, one last bit we need to add into our compiler is to ensure the code imported isn't duplicated, and with ES Modules now a reality we should be able to pull this off. But for now you should be able to extend, and later we'll have a good pattern to recommend. Stay tuned! Thanks

**Comment by alepop** [comment]
Extending works fine, but when you try to run test for component who extends some class, you got an error
