### ISSUE TITLE
Forms submit is reloading the page

### ISSUE THREAD

**Issue by juny58** [ionic-team/stencil#1330]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[x ] bug report

**Current behavior:**
The page is reloading on submit button press of form and I am not using ionic elements. I simply copied it from stencil forms.

**Expected behavior:**
It should prepare a form for submit on press of submit button.

**Steps to reproduce:**
Copy either of the examples from the stencil example page for form input and run.

**Related code:**

```tsx
<form onSubmit={(e) => this.handleSubmit(e)}>
        <label>
          Name:
          <input type="text" value={this.value} onInput={(event) => this.handleChange(event)} />
        </label>
        <input type="submit" value="Submit" />
</form>
```

**Other information:**
Please give more eloborated example of things please. Stencil seems potent but lacks serious documentation.

**Comment by paulstelzer** [comment]
That's normal behaviour of the browser to reload the page. If you don't want it, just put inside your handleSubmit() the following:

`e.preventDefault();`

**Comment by anujsulakhiya** [comment]
Reloading issue arise when we not declare the component in module.ts file.
