### ISSUE TITLE
docs outputTarget(s) do nothing if `--docs` flag is not passed to `stencil build`

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil#1337]
**Stencil version:**

```
 @stencil/core@0.17
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If you specify output targets of `docs` `docs-json` or `docs-custom` and don't add `--docs` in the package.json script your docs tasks never run.

**Expected behavior:**
docs outputTargets would trigger the appropriate action with or without the cli flag.

**Steps to reproduce:**
1. Make sure your package script doesn't include `--docs`
1. Add some docs outputTargets
1. Run stencil
1. No docs generated 😢

**Related code:**
```json
  "scripts": {
    "start": "stencil build --dev --watch --serve",
```
```ts
export const config: Config = {
  outputTargets: [
    {
      type: "docs"
    },
    {
      type: "docs-json",
      file: "foo.json"
    },
    {
      type: "docs-custom",
      generator(docs) {
        console.log("yeyy");
      }
    }
  ]
};

```

**Comment by adamdbradley** [comment]
This should be fixed in the 1.9.0 prerelease, thanks
