### ISSUE TITLE
Multiple Versions of same named component

### ISSUE THREAD

**Issue by drelementzero** [ionic-team/stencil#1342]
Hello
  Is it possible to for a consumer to have multiple versions of the same named component on one page?

test-dropdown I was loaded from collection 1.0 /test-dropdown
test-dropdown i was loaded from collection 1.1 /test-dropdown

**Comment by YanisGuerault** [comment]
I'm tried to have this but i don't find how to do. If you have a solution please send it here for all. Thank's

**Comment by mattcosta7** [comment]
It is not possible

How would the browser know which to use?  Part of the custom element spec only allows a component to be registered 1x (per tag)

**Comment by YanisGuerault** [comment]
I agree with you. My second option is added a prefix with the version like "<project-version-component>" = "<ada-5.6.1-button>". Someone have a solution to make this ?
