### ISSUE TITLE
Importing third party library

### ISSUE THREAD

**Issue by Snacketti90** [ionic-team/stencil#1347]
**Stencil version:**

```
@stencil/core@0.17.0 
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I ran 
```
npm install --save rss-parser
```

I use it like this:
```
render() {

let parser = new RSSParser();

    (async () => {
      let feed = await parser.parseURL('https://www.reddit.com/.rss');
      console.log(feed.title);

      feed.items.forEach(item => {
        console.log(item.title + ':' + item.link)
      });
    })();
    return (
      <div>

      </div>
    );
  }
```

Also I followed the bundling instructions from the StencilJS docs like so:
https://stenciljs.com/docs/module-bundling/

And I'm getting the error:
```
Bundling Error
Cannot read property 'warn' of undefined
```

**Expected behavior:**
A simple console log of the RSS Feed.

**Steps to reproduce:**
Same as I did.

**Other information:**
https://www.npmjs.com/package/rss-parser

and Git Repo of the library: 

https://github.com/bobby-brennan/rss-parser

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
