### ISSUE TITLE
On dev server videos cannot be seeked in chrome

### ISSUE THREAD

**Issue by lukasIO** [ionic-team/stencil#1350]
**Stencil version:**

```
@stencil/core@0.17.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
in Chrome: Videos hosted on the dev server in the assets/ directory cannot be seeked via controls and setting the time programatically sets the currentTime to 0.
in firefox it works as expected.
in chrome it works when the video is hosted somewhere else like src="http://techslides.com/demos/sample-videos/small.mp4"

**Expected behavior:**
Videos should be seekable and setting the time should be possible

**Steps to reproduce:**
put a sample.mp4 in the assets/ folder
`npm start`
go to
`localhost:3333/assets/sample.mp4`
try to jump in time with the controls

**Other information:**
I feel like this might be totally unrelated to stencil itself, but due to me not knowing any better, I had to put it here.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
