### ISSUE TITLE
Compile time error when EventEmitter type contains a period (static analysis error?)

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil#1352]
**Stencil version:**

```
 @stencil/core@0.17.0<version>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm using ambient type declarations with namespaces like `myComponent.SomeType` in my stencil lib. Works great, but the second I do this: `EventEmitter<myComponent.SomeType>` I get a cryptic error when compiling:
```
[ ERROR ]  /path/to/my-component.tsx
           Cannot read property 'toString' of undefined
```
The problem goes away when there is no period, if I do something like:
```ts
type SomeType = myComponent.SomeType;
// Omitted code
@Event() foo: EventEmitter<SomeType>;
```

**Expected behavior:**
If it is valid TypeScript it works with Stencil

**Comment by christian-bromann** [comment]
This has been released with Stencil 🚞 [v4.13.0](https://github.com/ionic-team/stencil/releases/tag/v4.13.0)
