### ISSUE TITLE
Error/bug during E2E tests

### ISSUE THREAD

**Issue by rafael-leal-mccormack** [ionic-team/stencil#1354]
**Stencil version:**

```
 @stencil/core@0.17.0
 @puppeteer@1.11.0
```

**I'm submitting a:**

[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Im not positive whether this is a bug or a feature that im request but ill state my problem and what I want under. 

Currently when running E2E tests on my main container component that holds my other components, I receive a cryptic error message and my component will not contain any innerHTML when checking for it in a snapshot test. I receive these errors and i believed it had to do with a prop not being passed into the page element, but even after adding them, they persist. It might not be playing nice with Tunnel.Provider or its not working well with states of the tunnel but I'm not too sure because these errors aren't very helpful.

```
console.error node_modules/@stencil/core/dist/testing/index.js:22589
      JSHandle@error 3 NU-NAV-CONTAINER
    console.error node_modules/@stencil/core/dist/testing/index.js:22589
      JSHandle@error 8 NU-NAV-CONTAINER
    console.error node_modules/@stencil/core/dist/testing/index.js:22589
      JSHandle@error 4 NU-NAV-CONTAINER
```

**Expected behavior:**

I'm trying to do a snapshot test but there wont be anything in the innerHTML when it gets printed out in the snapshot until i delete some important logic in my container. 

**Steps to reproduce:**

Its hard to exactly recreate this issue because im not sure what those errors mean or where they come from. 

**Related code:**

I cant include code because its company code, but i'd like some info on the error messaging because if i knew what was going on then maybe I could fix the issue.

**Other information:**

This is the function at the line that the stacktrace for the error leads too but im not positive about whats going on here or how to receive a better error message

```
function consoleMessage(c) {
    const type = c.type();
    if (typeof console[type] === 'function') {
        console[type](c.text());
    }
    else {
        console.log(type, c.text());
    }
}
```

**Comment by apillard** [comment]
Try this solution to get more details about your error: https://github.com/GoogleChrome/puppeteer/issues/3397#issuecomment-429325514

**Comment by simonhaenisch** [comment]
You can modify that `consoleMessage` function to get more output:

```
function consoleMessage(c) {
  console.log(c.args());
  // ...
}
```

That just helped me figure out what was wrong (a lib that I provide for my app as a browser global was not provided in the test).

**Comment by gforceg** [comment]
I was getting this issue as well. It turns out my render function depended upon properties that were not set during the initial render in my e2e tests. Example:

```TSX
@Component({
  tag: 'dt-filtercell'
})
export class FilterCell {
  @Prop() column: GridColumn
  render () {
    if (this.column.filter === false) {
      return <span></span>
    }
    return <some-other-component></some-other-component>
}
```

I would expect the above to fail on the line `if (this.column.filter === false)`  with a useful error like `no property filter on undefined` or better yet `column is undefined` but instead I get a passing test with vague error logs:

```bash
  console.error node_modules/@stencil/core/dist/testing/index.js:39886
    JSHandle@error
    Location: http://localhost:3334/build/core-4d7f2b58.js:71:36
```
