### ISSUE TITLE
Rollup plugins that implement "virtual modules" break

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil#1357]
**Stencil version:**

```
 @stencil/core@0.17.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Rollup allows plugins to define "virtual modules" [as denoted here](https://rollupjs.org/guide/en#a-simple-example)

In Stencil, plugins using this functionality do not work, you get an error like this:

```
[ ERROR ]  Rollup: undefined
           Could not load virtual:foo (imported by
           /src/components/form/form.js):
           The argument 'path' must be a string or Uint8Array without null bytes.
           Received '\u0000virtual:foo'
```

Here's an example plugin that breaks in Stencil: https://github.com/rollup/rollup-plugin-virtual

**Expected behavior:**

Rollup plugins work as expected

**Steps to reproduce:**

1. Install and configure the plugin listed above
1. See your build break

**Related code:**

```ts
// stencil.config.ts
import virtual from 'rollup-plugin-virtual';
…
plugins: [
    virtual({
      foo: 'export default 1',
      'src/bar.js': 'export default 2',
    }),
// component.tsx
import num from 'foo';
console.log('Virtual module foo', foo);
```

**Other information:**

**Comment by simonhaenisch** [comment]
Just verified that this also happens with the current Stencil One alpha. I think this might be related to Stencil overwriting `path.resolve`, which causes the error with the null bytes. However the null byte at the beginning is required to make other plugins skip that module.
