### ISSUE TITLE
Webpack loader/plugin

### ISSUE THREAD

**Issue by unlight** [ionic-team/stencil#136]
Is there a plan to release stencil compiler as a webpack loader/plugin?

**Comment by mhartington** [comment]
Hey @unlight ! At the moment, no, there is no such plan.
But curious, what benefit/need would you have for this? 
Curious as to what your use-case is

**Comment by mlynch** [comment]
Our philosophy with webpack right now is that we're not going to require it nor officially support is part of the build process. However, we'd *love* to see community approaches to making this work. We'd happily link to it for those wanting to use webpack.

**Comment by adamdbradley** [comment]
For some more background, each stencil app has a loader file, something like `build/app.loader.js` or something similar that has a hash in the file name. But really this file is like 600b (yes bytes, not kb), and is only a loader for the core file depending on what polyfills the user's browser will need. But really, stencil handles most of the work needed to lazy load any components.

But for apps that are already using webpack, the loader file could be another entry, so you'd save an extra request by concatenating it with the main bundle.

**Comment by siedentm** [comment]
A plugin is probably suited the most since the stencil ecosystem is rather closed and the target should be to let the stencil compiler do the job.

**Comment by jgw96** [comment]
Hello all! I am going to close this as we decided to go with this approach https://stenciljs.com/docs/angular-integration instead. Thanks for using Stencil all!

**Comment by apillard** [comment]
I have a use case for this. I am attempting to build a mapping component using Stencil and the ArcGIS js api. ArcGIS has a webpack plugin https://github.com/Esri/arcgis-webpack-plugin to support dojo module imports at build time. If the stencil compiler was exposed as a webpack loader i could combine the 2 tools, as is, I cannot use build time imports for my ArcGIS code.
