### ISSUE TITLE
There is no way to override the lazyDependencies

### ISSUE THREAD

**Issue by azchohfi** [ionic-team/stencil#1360]
**Stencil version:**
```
 @stencil/core@0.17.2
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

If I need to use a new puppeteer version, I can't.

**Expected behavior:**

I can change the restored version of puppeteer, or any lazyDependencies.

**Steps to reproduce:**

On a blank app, run npm install with a newer version of puppeteer (for example, 1.12.2). It will download the new version of chrome. Run npm test. It will ignore the new version and download the old version.

**Comment by pr3tori4n** [comment]
This is also true of Jest. Stuck on version 23.x. Latest is 24.x at the time of writing.

**Comment by adamdbradley** [comment]
Updated in https://github.com/ionic-team/stencil/commit/fdec36eb20f842b9dc446c70f722b9e98d9b2bf3 

It will be available in the upcoming 1.9.0 release
