### ISSUE TITLE
[Puppeteer] waitForNavigation is omitted.

### ISSUE THREAD

**Issue by azchohfi** [ionic-team/stencil#1365]
**Stencil version:**
```
 @stencil/core@0.17.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Can't use many methods from puppeteer. They are just omitted.

**Expected behavior:**
We should be able to use all the methods from puppeteer, or at least have proper documentation on why they are omitted.

**Steps to reproduce:**

I'm trying to create a test that navigates to a url:
```
const page = await newE2EPage({url: '/index.html'});
```
click on a button:
```
const myLogin= await page.find('login');
myLogin.click();
```
and then waits for the navigation to happens, which is forcibly removed from stencil, but available on puppeteer.

**Related code:**
https://github.com/ionic-team/stencil/blob/193cc6edb4f64841d78cc231ea5103d63f48a5d0/src/testing/puppeteer/puppeteer-declarations.ts#L13

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
