### ISSUE TITLE
slot polyfill mutates Redux state property values

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#1372]
**Stencil version:**
```
 @stencil/core@0.17.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
As soon as printing out variables that have been mapped from the `redux` state via `mapStateToProps` in the JSX template via `{myVar}` Stencil adds a result of some DOM node selection to the `redux` state. Leaving out the `{myVar}` fixes this - but obviously also defeats the absolut root use case of `{}`.

Imagine this code:
```
...
  protected componentWillLoad(): void {
    this.store.mapStateToProps(this, (state: GlobalStoreState): {} => {
      return {
        serviceData: state.caseOsServices.serviceData
      };
    });
  }
...
render() {
....
<tbody class='table-body'>
                    {serviceData.map((row: any) => {
                      return <tr>
                        {
                          Object.values(row)
                            .map((val: any) => {
                              return <td>{val}</td>;
                            })
                        }
                      </tr>;
                    })}
                  </tbody>
....
}
```
which simply renders all props of an array of objects to a table.

When you run this you get this in your `redux` state (for one object inside `serviceData`):
```
_id: "5c61e9ccdcedb0535cc9e44d"
name: "Bild Block Kim"
atom: "5c61e9a2dcedb0535cc9e44c"
__v: 0
src: "https://xn--sdwesthaus-9db.de/wp-content/uploads/2017/09/SUEDWESTHAUS_MASSIVBAUWEISE_HAUS_STUTTGART_NACHT_HEADER-600x460.jpg"
elm: {
s-hn: "co-service-state-provider"
}
```
See the `elm` property and it's children? It's not my data - it's been added by Stencil.

In pictures (before):
<img width="1053" alt="bildschirmfoto 2019-02-14 um 11 04 16" src="https://user-images.githubusercontent.com/6666636/52780057-b3df1c00-3049-11e9-9bed-8494b6af6d4c.png">

(after):
<img width="1059" alt="bildschirmfoto 2019-02-14 um 11 04 45" src="https://user-images.githubusercontent.com/6666636/52780084-bf324780-3049-11e9-8422-62ce5ed63f62.png">

Looking into the Stencil codebase I found this line: https://github.com/ionic-team/stencil/blob/9d790130e1b2ab26ade2ece71246168e79c07a8c/src/renderer/vdom/patch.ts#L136 which indicates the usage of `s-hn`.

I can make this work *without* the `redux` state being mutated by simply removing the actual printing of the value `{val}` - the state will no longer be mutated.

**Expected behavior:**
`redux` state is not mutated but values can be printed via `{myVar}`.

**Comment by corysmc** [comment]
I've seen the same issue... didn't realize it was happening until I started trying to save data to firestore... And it would fail because of the elm data that was added to my object.
I had to pull the elm out before saving to firestore to get it to save properly.

**Comment by bitflower** [comment]
Hi ionic! Let us know how we could possibly help out here with info, repos or smth?

**Comment by corysmc** [comment]
@bitflower any tricks you've done to work around this?

**Comment by bitflower** [comment]
Been a while since I had to deal with this. 

I've written a helper:
```
import { removeKeys } from './object-utils';

// Fix for https://github.com/ionic-team/stencil/issues/1372
export const workaroundElmProp: Function = (o: any): any => {
    removeKeys(o, ['elm']);

    return o;
};
```
and used like so:
```
  private onEdit(row: any): void {
    this.seletedRow = workaroundElmProp(row);
    this.presentModal();
  }
```
where the component dealing with the redux store would be in the modal component.

Actually I'm not using this part of the code anymore but using redux heavily in other parts so I wonder if this is realted to the ionic modal! I'm not using redux state right now inside modals...

Interesting.
