### ISSUE TITLE
Event handlers not always registered on child components on conditional rendering

### ISSUE THREAD

**Issue by michaelo** [ionic-team/stencil#1377]
**Stencil version:**

```
 @stencil/core@0.18.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Pseudo-code/structure:
my-component (shadow=true)
  - if condition: render sub-tree A
    - div
  - if !condition: render sub-tree B
    - div
      - my-other-component

Under sub-tree B I have a web components (my-other-component) upon which I register an (e.g.) onClick-handler. If the condition is such that sub-tree B is not initially rendered, but later is (e.g. due to Prop-changes) then the onClick-handler is not called. If the condition is such that the sub-tree B is initially rendered, then the onClick-handler is called as expected.

Other observations:
If the top-node of one of the sub-trees (illustrated as div above) is different (e.g. one of them is a span while the other a div) then the error does not occur. The error does also not occur if "my-component" does not use shadow DOM. Or if the component is re-rendered for any reason (e.g. due to some other prop being changed) the callback is also registered properly.

**Expected behavior:**
The onClick-callback on "my-other-component" should be called as long as the actual element is clicked.

**Steps to reproduce:**
See MWE below. I've created some automatic tests (foo.spec.ts) which explores the different variants I've observed.

**Related code:**
https://github.com/michaelo/stencil-bug-event

**Other information:**

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
