### ISSUE TITLE
Can't include shared code from parent directory (File '../../X' is not under 'rootDir')

### ISSUE THREAD

**Issue by cmaas** [ionic-team/stencil#1379]
**Stencil version:**
```
 @stencil/core@0.18.0
```

**I'm submitting a:**
[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I have my Stencil project in a subdirectory of a parent project (a Node webapp) like so:

```
/webapp <Node project>
    /src
        /utils.ts
    /client <Stencil project>
        /src
            /my-component.tsx
```

I want to use the code from `utils.ts` in `my-component.tsx`. Usually, this works by adding the respective path in the `tsconfig.json` of the Stencil project:

```
{
    "compilerOptions": {
        "paths": {
                "@web/*": ["../src/*"]
        }
    }
}
```

For VSCode, this works fine, no errors. But when I compile with Stencil (`npm run build`), I get the following error:

```
[ WARN  ]  Bundling Warning
           '@web/utils' is imported by src/my-component.js, but could not be resolved – treating it as an
           external dependency

[ ERROR ]  TypeScript
           File '../src/utils.ts' is not under 'rootDir' '/<PATH>/client/src'.
           'rootDir' is expected to contain all source files.
```

I tried to specify `rootDir`, but this apparently didn't work. I suspect that there's some error with `rollup`. At least,  there seems to be a plugin called `rollup-plugin-ts-paths`, which is not used in Stencil.

Before Stencil, I used React and my own simple build script with Webpack. Sharing code via `paths` worked perfectly. My guess is that somehow in Stencil's build settings, paths that are outside of the project directory aren't supported (even though they are by TypeScript).

**Expected behavior:**
Let me reference scripts correctly.

**Steps to reproduce:**
Create a Stencil project in a subfolder of another project and try to reference code of the parent project.

**Related code:**
Probably build config files.

**Comment by cmaas** [comment]
Two more things:

1. A minimal example is to init a Stencil project with the `app` starter, put some file like `utils.ts` in the parent directory and try to import this in a component, just like so: `import whatever from '../../utils'. This leads to the error of `utils.ts` not being in `rootDir`. It's not even necessary to specify `paths` in the TS config file.

2. Now there seems to be a mixture of two things: First, rollup seems to ignore everything outside of the project `rootDir` for whatever reason (I also tried the plugin `rollup-plugin-ts-paths` but no luck). Second, Stencil overwrites `rootDir` or `rootDirs` of `tsconfig.json` with its own `srcDir` config attribute.

**Comment by cjorasch** [comment]
I have been running into the same problem as well.  My desired use case is:

```
/my-workspace
    /shared
        <Shared typescript modules>
        my-utilities.ts
    /server
        <Node project>
    /client
        <Stencil project>
```

I was not able to find a way to get the Stencil project to build with references to the code in `shared`.

My current workaround is to put the shared code in the Stencil project:

```
/my-workspace
    /server
        <Node project>
    /client
        <Stencil project>
        /src
            /shared
                my-utilities.ts
```

The node project is then able to build with references to the `shared` folder within the client project.  The biggest downside is that the import paths in the server project get quite long and there are some issues with consistency in the `tsconfig.json` files.  There are also some challenges when doing refactoring to make sure both projects get updated.

**Comment by glenveegee** [comment]
+1

My use case is to pull in some information like version number from package.json into a component. It wouldn't make sense to change the location of the package.json file in my case.
```
/my-workspace
    package.json
    /src
        /components
            /my-component
                my-component.tsx   // imports ../../../package.json
```

**Comment by patrickvaler** [comment]
+1

I'm running into the same issue when I'm trying to include package.json to read the version number.

**Comment by hartjus** [comment]
We're running into a very similar issue.  We've setup a mono-repo with Lerna, and have a common `utils` package.  When we import code from the utils package, either via hoisted dependency or using a local dependency in the package.json (`"utils": "file:../utils",`), we get this error.  Is there a work around for this?

**Comment by cmaas** [comment]
@hartjus I ended up pushing my shared code into a Gitlab repository and referencing this in my Stencil project. Of course, this is more cumbersome than a direct reference, because with every little code change in the shared library, you need to go the entire route of compiling, pushing to Gitlab, and then update the dependency in Stencil. So a more direct solution would still be much appreciated :)

**Comment by arsenx** [comment]
+1

I am looking at developing a few packages without having to push and update npm every time so this would be essential to get a proper workflow going.

**Comment by DmitryEfimenko** [comment]
+1. This is a show-stopper for #1921 as well

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!

**Comment by pranav-js** [comment]
so what is the solution for using outside stencil projects with nx setup?
