### ISSUE TITLE
[suggestion] Possibility to use assets

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/stencil#138]
_From @Fdom92 on August 26, 2017 19:12_

Hi, i'm trying to use some svgs at assets folder but these folder its not being copied so the result is that the svgs are not found.

But if i copy the assets folder under the build path work as expected, so maybe just add a copy script from src/assets to build/assets?

I think this is quite useful but i let this on you.

Thanks!

_Copied from original issue: ionic-team/stencil-dev-server#10_

**Comment by jthoms1** [comment]
_From @janpio on August 27, 2017 12:5_

Any reason you can't just put it in `build/assets` directly?

**Comment by jthoms1** [comment]
_From @Fdom92 on August 27, 2017 13:47_

I can put it in build/assets yes but im asking if they can or have planned to add a 'copy' task on dev-server. 

If not ill just copy as you said :)

**Comment by jthoms1** [comment]
Sorry we would probably do this within the stencil build process not with the dev server.  I will move this issue over to the stencil core repo.

**Comment by jgw96** [comment]
Hey @Fdom92. We have a copy task now in the latest release of stencil. We need to document it but  it looks something like this in your stencil config
```
 copy: [
   {
      image: 'image.jpg'
   }
 ]
```

**Comment by motss** [comment]
@jgw96 How to copy an entire folder? I added even more assets into the same `img` directory but not everything that I added was being copied over to when it's compiled.
