### ISSUE TITLE
How to consume one stencil component in another stencil component?

### ISSUE THREAD

**Issue by basavarajk** [ionic-team/stencil#1383]
**I'm submitting a:**

[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Problem Statement**
How to consume one stencil component in another stencil component.
Example : 
 ***@test-lib/tool-tip***     -- > This is stand alone stencil component published in npm registry.

  ***@test-lib/bar-chart***     -- > This is stand alone stencil component , inside this component i want to consume @test-lib/tool-tip component.

 Much appreciated any leads over the same. Thanks

**Comment by bitflower** [comment]
`npm i @test-lib/tool-tip` inside `@test-lib/bar-chart`. Then "somewhere" in `@test-lib/bar-chart` add `import `@test-lib/tool-tip` in the compoment where you want to use it or in your app-root.
