### ISSUE TITLE
Differents build librairies with same components names bug

### ISSUE THREAD

**Issue by YanisGuerault** [ionic-team/stencil#1386]
**Stencil version:**

```
@stencil/core@0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When you have 2 differents libraries with different versions (same object name), only the first project loaded component was use, if you try to call the different component, the first was called (i know it's hard to understand).

In 1.0.1, the button text is "Hello i'm 1.0.1" but when you try, the text is "Hello i'm 1.0.0" because the 1.0.0 script is loaded before the 1.0.1 script
**Expected behavior:**

Two differents text between for the button in different version beacon.

**Steps to reproduce:**

Create two build project with the same components but different versions and try. (Only change the root beacons)
**Related code:**

```tsx
// insert any relevant code here
<component-v1.0.0><component-button></component-button></component-v1.0.0>
<component-v1.0.1><component-button></component-button></component-v1.0.1>

In reality : 
1.0.0 : <component-button> Hello i'm 1.0.0 </component-button>
1.0.1 : <component-button> Hello i'm 1.0.0 </component-button>

In project (and the excepted result) :+1: 
1.0.0 : <component-button> Hello i'm 1.0.0 </component-button>
1.0.1 : <component-button> Hello i'm 1.0.1 </component-button>
```

**Other information:**

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
