### ISSUE TITLE
Stencil component performance issues

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#1389]
**Stencil version:**
```
 @stencil/core@0.18.0
```

**I'm submitting a:**
[x] bug report

**Overview:**

Stencil components have significant memory usage and rendering performance implications related to the number of properties that exist on the components.

These test cases simulate a scenario where a page renders with a large number of component instances - in this case 1000.  This might occur for a list with many child components on each item or a grid composed of `<ion-row>` and `<ion-col>` instances.  Many pages do not require that many component instances but this is intended to check the case where there are many.

**Test Cases:**

I created minimal test components that simply return the child content and do not perform any additional processing.  The components that were tested include a Stencil component with 20 properties, a Stencil component with 0 properties, and a Functional component with 20 properties.

The test components are as follows:

```tsx
// test-component-20.tsx
@Component({
    tag: 'test-component-20',
})
export class TestComponent20 {
    @Prop() prop1: string;
    @Prop() prop2: string;
    @Prop() prop3: string;
    @Prop() prop4: string;
    @Prop() prop5: string;
    @Prop() prop6: string;
    @Prop() prop7: string;
    @Prop() prop8: string;
    @Prop() prop9: string;
    @Prop() prop10: string;
    @Prop() prop11: string;
    @Prop() prop12: string;
    @Prop() prop13: string;
    @Prop() prop14: string;
    @Prop() prop15: string;
    @Prop() prop16: string;
    @Prop() prop17: string;
    @Prop() prop18: string;
    @Prop() prop19: string;
    @Prop() prop20: string;
}

// test-component-base.tsx
@Component({
    tag: 'test-component-base',
})
export class TestComponentBase {}

// functional-component-base.tsx
export const FunctionalComponentBase: FunctionalComponent = (_props, children) => (
    <span>{children}</span>
);
```

A test page was setup to render the components:

```tsx
    repeatFunctionalComponentBase: () => {
        const result: JSX.Element[] = [];
        for (let i = 0; i < repeatCount; i++) {
            result.push(<FunctionalComponentBase>{i}</FunctionalComponentBase>);
        }
        return <div>{result}</div>;
    },

    repeatComponentBase: () => {
        const result: JSX.Element[] = [];
        for (let i = 0; i < repeatCount; i++) {
            result.push(<test-component-base>{i}</test-component-base>);
        }
        return <div>{result}</div>;
    },

    repeatComponent20: () => {
        const result: JSX.Element[] = [];
        for (let i = 0; i < repeatCount; i++) {
            result.push(<test-component-20>{i}</test-component-20>);
        }
        return <div>{result}</div>;
    },
```

**Memory Requirements:**

I tested the memory requirements of each approach using the developer tools in Chrome and using memory snapshots.

The results are as follows:
- Stencil component with 20 props: 10M
- Stencil component with 0 props: 2M
- Functional component: 300K

This indicates that stencil components use more memory than simple functional components which is not too surprising.  In this case an extra 1700 bytes per component instance.

What was more surprising is the component overhead related to properties - even if the properties are never used.  In this case almost 10K of memory overhead per instance of a component for a total of 10M.

Some of the overhead in the component with 0 props is probably related to the 2 props that are included automatically (mode and color).  This implies that the memory overhead of Stencil could be quite small if those properties were not automatically included.

One possible explanation for the large memory requirements is the number of getter and setter functions that are defined on every single component instance.  Typically classes have a single implementation of the getter and setter in the prototype so that there is not overhead for each class instance.  In this case they are copied to every instance that gets created.

**Rendering Performance:**

There is also a significant difference in the rendering performance for the various approaches.  I tested the performance in Chrome dev tools and observed the following:

- Stencil component with 20 props: 1350ms
- Stencil component with 0 props: 1150ms
- Functional component: 100ms

This rendering time results in a significant visual delay that is easily observed by the end user.

**Some Thoughts:**

When building Stencil apps it is easy to end up with a large number of components due to:
- Navigation stacks that have many pages rendered at the same time
- List oriented pages with many child components per item

Because of the high performance overhead for Stencil components developers should consider functional components for things that occur frequently on a page and don't require state.

**Comment by manucorporat** [comment]
We are drastically improving the runtime performance in https://github.com/ionic-team/stencil/tree/core-refactor

which will become Stencil One

**Comment by manucorporat** [comment]
We recently merged stencil one branch into master!
