### ISSUE TITLE
Blank page after first compile

### ISSUE THREAD

**Issue by johannesjo** [ionic-team/stencil#1391]
**Stencil version:**

```
 @stencil/core@0.16.4
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When first compiling everything works. After changing a file however the markup is there, but the javascript is not loaded any more. 
**Expected behavior:**

Reloads should work fine.
**Steps to reproduce:**

**Related code:**
Interestingly the main file still contains a function, but it is completely empty after the first compile.

This:
```tsx
/*! Built with http://stenciljs.com */
((w,d,x,n,h,c,r)=>{((s)=>{s&&(r=s.getAttribute('data-resources-url'))})(d.querySelector("script[data-namespace='myproject']"));
/**
 * SSR Attribute Names
 */
const SSR_VNODE_ID = 'ssrv';
// ...
// ...
```
Becomes this:
```tsx
/*! Built with http://stenciljs.com */
((w,d,x,n,h,c,r)=>{((s)=>{s&&(r=s.getAttribute('data-resources-url'))})(d.querySelector("script[data-namespace='myproject']"));

})(n, x, w, d, r, h, c);
})(window,document,{}, // ...
);
```

**Other information:**

**Comment by manucorporat** [comment]
This is not longer an issue in stencil 1.0, since we completely refactored the loaders to use rollup!
