### ISSUE TITLE
baseUrl does not affect app.css (globalStyle) path

### ISSUE THREAD

**Issue by henrikra** [ionic-team/stencil#1399]
**Stencil version:**
```
 @stencil/core@0.16.2
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Add any `baseUrl` to `stencil.config.ts` like this:
```ts
export const config: Config = {
  globalStyle: 'src/global/app.css',
  outputTargets: [
    {
      type: 'www',
      baseUrl: '/some-path'
    },
  ],
};
```
Then run `npm run build`. Then open built  `index.html` file from `www/index.html` and notice that css path stays always the same no matter what. 🔴  It is always like this `<link href="/build/app.css" rel="stylesheet" />`. But as you notice the path to js IS changed like this `<script data-resources-url="/some-path/build/app/">` as it should be 👍 

**Expected behavior:**
I expect that changing the `baseUrl` would affect the css path also. So it would be like this `<link href="/some-path/build/app.css" rel="stylesheet" />`

**Steps to reproduce:**
See part "Current behavior" 

**Related code:**
See part "Current behavior"

**Other information:**
This is currently blocking any body to deploy Stencil page to GitHub pages because there it is always deployed to sub path so you need to be able to change that :/ Please at least tell me if you guys agree with me and have the same bug.

**Comment by ivanbportugal** [comment]
I think this is related to https://github.com/ionic-team/stencil/issues/2006

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
