### ISSUE TITLE
Jsx and ::part type error

### ISSUE THREAD

**Issue by equinusocio** [ionic-team/stencil#1400]
**Stencil version:**
```
 @stencil/core@0.18.0
```

**I'm submitting a:**

[x] bug report

Adding the part attribute to an element i get a validator error:
```
Type '{ class: string; part: string; }' is not assignable to type 'HTMLAttributes<HTMLSpanElement>'.
  Property 'part' does not exist on type 'HTMLAttributes<HTMLSpanElement>'.ts(2322)
(property) JSXElements.DefaultIntrinsicElements.span: JSXElements.HTMLAttributes<HTMLSpanElement>
```

**Expected behavior:**
Part attributes should be available on all html elements.

**Steps to reproduce:**
Add a part attribute like `part="some-el"` and style it.

**Related code:**

```tsx
  render() {
    return (
      <span class="Element" part="some-el">
        <slot />
      </span>
    );
  }
```

```css
my-button::part(some-el) {
  background-color: cyan;
}
```

**Comment by manucorporat** [comment]
fixed by https://github.com/ionic-team/stencil/commit/abc7f65595f27f7d0b2e437e4cafb6d0b341b0c8
