### ISSUE TITLE
Performance marks not placed correctly

### ISSUE THREAD

**Issue by denniswiemer** [ionic-team/stencil#1403]
**Stencil version:**
```
 @stencil/core@0.18.0
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behaviour:**
When running a Stencil build on my components with the --profile argument I get really nice performance marks which I can use in my component performance tests (CI/CD pipeline). Awesome! Though when measuring the loading time of a component I noticed the last mark is placed but doesn't include the browser layout/paint/rendering.

**Expected behaviour:**
By moving the last performance mark into the next tick of the eventloop, the browser paint/rendering part is also included in the measurement.

**Steps to reproduce:**
Run: `stencil build --profile` on your project. Then make a performance timeline recording in Chrome devtools to see the actual measurements.

**Comment by dutscher** [comment]
btw safari 10.0 on ios has a old webkit.performance api https://developer.mozilla.org/de/docs/Web/Web_Components

and breaks silently at `performance.mark()`, `performance.measure` & `performance.getEntriesByName`

to get rid of use `stencil build --no-profile`

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
