### ISSUE TITLE
web-components.json does not match schema

### ISSUE THREAD

**Issue by little-king** [ionic-team/stencil#1405]
**Stencil version:**

```
 @stencil/core@0.18.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Output produced in web-components.json does not match the updated schema used in vscode - https://github.com/Microsoft/vscode-html-languageservice/blob/master/docs/customData.md.
Basically just missing the name attribute.

**Expected behavior:**
Output should match the schema, which admittedly seems to be still a moving target.

**Steps to reproduce:**
Generate web-components.json via 
stencil build --docs
Add web-components.json to vscode workspace settings via html.experimental.customData

**Other information:**
Fix by updating generate-web-components-json.ts 

```
export async function generateWebComponentsJson(config: d.Config, compilerCtx: d.CompilerCtx, distOutputs: d.OutputTargetDist[], docsData: d.JsonDocs) {
  const json = {
    'tags': docsData.components.map(cmp => ({
      'name': cmp.tag,
      'label': cmp.tag,
      'description': cmp.docs,
      'attributes': cmp.props.filter(p => p.attr).map(p => ({
        'name': p.attr,
        'label': p.attr,
        'description': p.docs,
        'required': p.required
      }))
    }))
  };
  const jsonContent = JSON.stringify(json, null, 2);
  await Promise.all(distOutputs.map(async distOutput => {
    const filePath = normalizePath(config.sys.path.join(distOutput.buildDir, WEB_COMPONENTS_JSON_FILE_NAME));
    await compilerCtx.fs.writeFile(filePath, jsonContent);
  }));
}


```

**Comment by manucorporat** [comment]
Vscode webcomponent.json is a moving target, for the moment nobody should rely on it, since it could change at any point, however, we have recently merged to master the generator so it follows the latest spec!
