### ISSUE TITLE
SGV is not rendered if its <path /> is taken from <slot />

### ISSUE THREAD

**Issue by KEMBL** [ionic-team/stencil#1408]
**Stencil version:**

```
 @stencil/core@0.18.0
```
checked in 
Chrome Version 72.0.3626.121 (Official Build) (64-bit)
FireFox Quantum 65.0.2 64-bin
Opera version: 58.0.3135.79

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Svg image  is not rendered if its path tag is taken from a slot

**Expected behavior:**

Svg image should be rendered

**Steps to reproduce:**

The demo is located at
https://github.com/KEMBL/StencilJs.playground/tree/feature/1903_SVG_issue_example

just clone and make npm install / start

**Related code:**
Try to do that:
```tsx
 <svg version="1.1" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" width=9 height=5 viewBox="0 0 9 5" fill="black" >
<slot />
</svg>
```
and return that from slot

```tsx
<path d="M0 0L4.00245 5L8.00489 0H0Z" />
```

**Other information:**

**Comment by stanley85** [comment]
This is still an issue with beta.2 but only affects IE11, icons are not rendered. In chrome and ff icons are rendered as expected. A slot is not needed for this to fail.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
