### ISSUE TITLE
@Component reflectToAttr doesn't work if field is named 'value'

### ISSUE THREAD

**Issue by covertcj** [ionic-team/stencil#1411]
**Stencil version:**

```
 @stencil/core@0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When using `@Prop({ reflectToAttr: true, mutable: true })` on a field named `value`, the property isn't reflected to the DOM.

**Expected behavior:**

When using `@Prop({ reflectToAttr: true, mutable: true })` on a field named `value`, the property should be reflected to the DOM.

**Steps to reproduce:**

I created a sample app with the npm init template to reproduce the problem and hosted it at: https://github.com/covertcj/stencil-value-reflect.  In the app, I added a simple `app-field` component with two fields, `value` and `otherValue`.  `otherValue` reflects as expected, while `value` does not.

**Related code:**

```tsx
@Component({
  tag: 'app-field',
  shadow: true
})
export class AppHome {
  // properly reflects to the DOM when its input is edited
  @Prop({ reflectToAttr: true, mutable: true })
  otherValue: string

  // unlike otherValue, no reflection occurs
  @Prop({ reflectToAttr: true, mutable: true })
  value: string

  render() {
    return (
      <div class='app-field'>
        <input type='text' value={this.value} onInput={e => this.value = (e.target as HTMLInputElement).value} />
        <input type='text' value={this.otherValue} onInput={e => this.otherValue = (e.target as HTMLInputElement).value} />
      </div>
    );
  }
}
```

**Other information:**

**Comment by tikri** [comment]
Maybe we found a workaround here, please try changing internal property name:
```typescript
@Prop({ reflectToAttr: true, mutable: true, attr: 'value' })
internalValue: string
```

**Comment by covertcj** [comment]
Thanks for the workaround, but I seem to be having some trouble getting that change to build.  It looks like the `attr: 'value'` isn't propagating into `components.d.ts`, and I get a type error.

**app-field.tsx**
```
@Component({ tag: 'app-field' })
export class AppField {
  @Prop({ reflectToAttr: true, mutable: true, attr: 'value' }) internalValue: string

  @Prop({ reflectToAttr: true, mutable: true }) otherValue: string
  ....
```

**components.d.ts**
```
interface AppFieldAttributes extends StencilHTMLAttributes {
    'internalValue'?: string;
    'otherValue'?: string;
}
```

**Build Error**
```
[ ERROR ]  TypeScript: src/components/app-home/app-home.tsx:20:9
           Type '{ value: string; otherValue: string; }' is not assignable to type 'AppFieldAttributes'. Property
           'value' does not exist on type 'AppFieldAttributes'.

     L20:          <app-field value="value" otherValue="otherValue"></app-field>
```

Is this user error on my part?  Thanks for the help

**Comment by tikri** [comment]
Please try ```<app-field internalValue="value" otherValue="otherValue"></app-field>```. I think internally it's a property assignment to your component and no attribute binding. From this point of view the name "internalValue" is confusing, maybe propValue would be better. But I think you just want the same as we do; having a clean component API with attribute and property both named "value" which doesn't work with "reflectToAttr" currently.

The only effect of this "workaround" is, that the attribute named "value" updates according to the component property. So it's no real workaround for this bug :(

**Comment by covertcj** [comment]
Ah, that's unfortunate.  We'd really like to have the DOM attribute named value.
