### ISSUE TITLE
Getting EEXIST errors on serve (0.18.1)

### ISSUE THREAD

**Issue by FdezRomero** [ionic-team/stencil#1412]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Running `npm start` on an Ionic PWA Toolkit project results in the following error in the console and browser. It seems to be related to the latest changes in copy tasks in 0.18.1. Previous versions are not affected.

```
EEXIST: file already exists, copyfile
           '/Users/rodrigo/Git/ionic-pwa/node_modules/ionicons/dist/collection/icon/svg/index.esm.d.ts' ->
           '/Users/rodrigo/Git/ionic-pwa/www/build/app/svg/index.esm.d.ts'
```

Deleting the `www` directory temporarily solves the issue, until `npm start` is used again.

**Expected behavior:**

The content in `www` is overwritten and the Stencil app is served without errors.

**Steps to reproduce:**

1. `npm init stencil`
2. Choose `ionic-pwa`
3. `cd ionic-pwa`
4. `npm install -D @stencil/core@latest`
5. `npm start`
6. An EEXIST error is shown.

**Related code:**
N/A

**Other information:**

Might be related to https://github.com/ionic-team/stencil/commit/e51c0a4c7e63e27ee72fc34754cd602391ff7056

**Comment by shreeshbhat** [comment]
After updating to Stencil 0.18.1, getting the following error on npm start :
```SyntaxError: Identifier 'h' has already been declared "http://localhost:3333/build/app/app-root.md.entry.js"```
White screen for UI.
node : v10.13.0
npm : 6.4.1
Might be related to same issue.

**Comment by sslotsky** [comment]
Getting the same error as @shreeshbhat, happens when I delete a component.

**Comment by matteocusinato** [comment]
Getting the same error after updating to Stencil 0.18.1, on 0.18.1-0 works fine.

**Comment by JurgenJocubeit** [comment]
Agree with @matteocusinato, rolling back from 0.18.1 to 0.18.0 and the issue disappears. Interestingly, I had the same issue before upgrading to 0.18.0 too.

**Comment by simonhaenisch** [comment]
BTW this only happened to me after upgrading to node 10 or 11, with node 8 it still works fine. So that's an alternative to downgrading stencil ;)

**Comment by Nightbr** [comment]
Hey, same issue on node 10 with stenciljs 0.18.1. I will try to downgrade. 
Link to https://github.com/ionic-team/stencil-app-starter/issues/66

**Comment by Nightbr** [comment]
Some tests:

- Not working on 0.18.1
- Working on 0.18.0

Bugs only with Node >= 10.

Workaround:

- Downgrade to node 8
- Downgrade to stenciljs 0.18.0

If you need more information and debug, let me know 👌

**Comment by manucorporat** [comment]
Fixes in master! we will release a new release soon shipping the fix!
