### ISSUE TITLE
Way to Load External HTML/Template Files

### ISSUE THREAD

**Issue by srsgores** [ionic-team/stencil#1414]
This is more of a question than an issue.

I come from a traditional web development background where writing HTML in JS is frowned upon, and I feel quite strongly about the topic today.  Moreover, I want to avert the crisis of locating template logic by separating view from display logic.

Currently, within other projects like the Polymer projects, the usage of the spec-compliant `<template>` element is supported.  However, [on your website, it appears only JSX is supported](https://stenciljs.com/docs/templating-jsx/).

Is there any planned support for spec-compliant usage of the `<template>` element, loaded in the component file?  I might expect something like this, where the corresponding `<template>` with an `id` is generated and then inserted into the DOM, and instead of a `render` function, we can pass a `template` property:

```
import ProgressBarTemplate from "progress-bar.template.html";
export default class ProgressBar {
    template: ProgressBarTemplate
}
```

**Comment by ManadayM** [comment]
I'm looking for such exact feature to supply html templates with template literals from externally. Let me explain it through a use case. Imagine there's a small tool that shows tabular data from a Stock Price REST API. The tool, based on the Stencil.js based Web Component, is a product of my company. Recognizing this fact, selection of data points for the tool will be different from client-to-client. If I keep template inside the component's source as JSX then client will be required to change my source code. That I don't want to happen. 

Hence, I'm looking for a solution that enables my clients (optionally) to supply a template with dynamic data placeholders of their choice. If they don't provide the template externally then I'll provision a default template inside the component itself.

**Expectation**

`<template id="share-price-ticker">`
`<div>`
`<p>Current price: ${currentPrice}</p>`
`<p>Percent change: ${percentChange}</p>`
`<p>Price change: ${priceChange}</p>`
`</div>`
`</template>`

`// following component is responsible to make API requests to pull the data and inject the loaded stuff in the placeholders like ${currentPrice} etc..`

`<share-price-ticker symbol="GOOGL" template-id="share-price-ticker">`
`</share-price-ticker>`

I'm relatively new to Web Components so any clue / guidance / help would be really great and appreciated. I hope this feature would be already there in the Stencil.js solution out-of-the-box.
