### ISSUE TITLE
Quitting test --watch does not kill node process

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#1416]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
Executing `stencil test --e2e --watch` starts a node process in the background:

    $ ps|grep node
    27909 ttys001    0:00.15 /usr/local/Cellar/node/11.10.0/bin/node /Users/me/stencil-component-starter/node_modules/@stencil/core/dist/dev-server/index.js

After quitting the watch mode by hitting `q`, the process still exists.

**Expected behavior:**
The process should be killed.

**Steps to reproduce:**
    $ stencil test --e2e --watch # hit "q"
    $ ps|grep node

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
