### ISSUE TITLE
CSS in JS styling

### ISSUE THREAD

**Issue by schadenn** [ionic-team/stencil#1417]
**Stencil version:**

```
 @stencil/core@0.18.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
You can only use .css or .scss files to style your components.

**Expected behavior:**
You shall be able to use .ts files to do your styling.

We're a team building a big component library with various UI components. Until now we developed everything in React, but we came to the conclusion that it might be better to build web components, because there are a lot of different tech stacks to be found at our client.

We've been using SASS for quite some time now and were using alot of mixins/functions throughout our lib.
One day I wanted to use a mixin and pass some parameters to the `@content` block. So I stumbled over this thread:
https://github.com/sass/sass/issues/871
So after 5 years you'll soon be able to do what I was trying to do - using syntax that is a little awkward in my opinion.

You'd be able to do the same thing quite easily using JS though. And since there are a lot of CSS in JS plugins rising in the React world, I was wondering if we could do the same within Stencil.

So I dug my way through the Stencil compiler and came up with this little plugin:
https://github.com/schadenn/stencil-plugin-tss

It works quite well but I'm not sure if I found all the pitfalls in the Stencil compiler, maybe one of you Stencil-guys can tell me what you think about it.
Of course this is a little different to styled components as you don't create new components for every style declaration and you won't be able to use runtime component properties to alter your CSS - using my plugin will only let you use Typescript syntax to create a static CSS file - butthat enables you to do a lot more than what we'd be able to do using SASS.

Within the project there's a `rewriteStencil.js` which alters some of the Stencil compilers lines. I'd be happy to open a Pull Request making those parts configurable so CSS in JS/CSS in TS/TSS/whatever-you'd-like-to-call-it will be officially supported,

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
