### ISSUE TITLE
Unable to import CommonJS modules

### ISSUE THREAD

**Issue by sauhard-bhushan** [ionic-team/stencil#1419]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I am trying to import `applicationinsights-js` into my app. 
This is my stencil configuration: 
```export const config: Config = {
  namespace: 'myapp',
  commonjs: {
    namedExports: {
      'node_modules/applicationinsights-js/': ['AppInsights','Util'],
      'node_modules/uuid/': ['v4']
    }
  },
  nodeResolve: { module: true },
  outputTargets: [{
      type: 'www',
      serviceWorker: null
    },
    {
      type: 'dist'
    }
  ],
  plugins: [
    globals(),
    builtins(),
...
```
And I'm trying to do this in one of my files:
```
import { AppInsights } from 'applicationinsights-js';
```
I have also tried ` import * as AppInsights from 'applicationinsights-js'`. 
This is the bug: 
```
[ ERROR ]  Rollup: Missing Export: src/components/xxxx
           'AppInsights' is not exported by node_modules\applicationinsights-js\bundle\ai.module.js
```
**Investigation**
1. Copy the main file and (move it somewhere other than `node_modules` ) from `applicationinsights-js` 
2. Change `module.exports` to `export const AppInsights`,
3. Remove lines which have `define(...)`
This is then fixed and I'm able to use the module.

So there seems to be problems importing commonJS modules.
I have also tried import `uuid` and I have the same issue.

**Expected behavior:**
I'm able to import any module using `module.exports` in my code.

**Comment by schadenn** [comment]
Not sure if this helps or not, but looking at your stencil.config plugins section, maybe you need this: https://github.com/rollup/rollup-plugin-commonjs

**Comment by sauhard-bhushan** [comment]
I think stencil already includes `rollup-plugin-commonjs`, but regardless - I've tried that and I get a new error: 
```
[ ERROR ]  TypeError: Cannot read property 'call' of undefined at Object.resolveId
```

**Comment by tomsisk** [comment]
Helpful comments here if you haven't seen already (was created 2 days after you created this): https://github.com/Microsoft/ApplicationInsights-JS/issues/816

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
