### ISSUE TITLE
uncorrected lifecycle happen when list data changes

### ISSUE THREAD

**Issue by rainke** [ionic-team/stencil#1424]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I have 2 components, `<p-board>` and `<p-box>`, but if i click one box, the first `<p-box>` will trigger `componentDidUnload` method.
**Expected behavior:**

`componentDidUnload` should not be executed;
**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here

@Component({
  tag: 'p-board',
  styleUrl: 'p-board.less',
  shadow: true
})
export class PBoard {
@State() list = [1,2]
@Listen('move')
handleMove(){
  this.list = [2,1]
}

render() {
  return <div>{
    this.list.map((id, idx) => <p-box key={id} bid={id} idx={idx}/>)
  }</div>
}
```

```tsx
@Component({
  tag: 'p-box',
  styleUrl: 'p-box.less',
  shadow: true
})
export class PBoard {
@Prop() bid:number;
@prop() idx: number;
@Event() move: EventEmitter;
handleClick = () => {
  this.move.emit({bid: this.bid})
}

componentDidUnload() {
    console.log(this.bid, 'unload');
}

render() {
  return <div onClick={this.handClick}>{this.bid}</div>
}
```

**Other information:**

```json
{
  "@stencil/core": "~0.16.2"
}
```

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
