### ISSUE TITLE
Issue Running MapBox inside Stencil Component in IE Edge

### ISSUE THREAD

**Issue by neeldeep** [ionic-team/stencil#1426]
I am using MapBox inside a Stencil component. It seems to be working fine in Chrome and Firefox. However when I run the same in IE 11 (Edge) it is giving an error: "Incorrect function".

**Comment by manucorporat** [comment]
Thanks for the issue! Could you please provide a repository or plunker that has a minimal amount of code to reproduce this?

In the future, please entirely fill out the provided issue template. We use this issue template in order to gather more information and further assist you.
