### ISSUE TITLE
VirtualDom needed?

### ISSUE THREAD

**Issue by nimo23** [ionic-team/stencil#1427]
After reading the docs https://stenciljs.com/docs/introduction, I am wondering why stencil needs a vdom on the client side when also using web components? In lit-elment, updates are done without using vdom-layer and only updates the minimal parts of the tree by using diffing instead of updating whole component-tree. 

Look at "lit-HTML DOM updating": https://medium.com/@lucamezzalira/a-night-experimenting-with-lit-html-585a8c69892a

Does stenciljs do the same when updating dom?

**Comment by manucorporat** [comment]
LitElement is another library that implements a different custom render, it's not web components.
Our v-dom implementation can be just as fast and small than the lit-html render, so no worries!

>Does stenciljs do the same when updating dom?
yes, stencil updates only the parts of the DOM that change, just like lit-html
