### ISSUE TITLE
WebAssembly usage and example

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [ionic-team/stencil#1428]
WebAssembly is supposed to become a standard way to develop  Webapps in near future soon.
As you may know, many of core javascript libraries/modules requiring gpu/cpu intensive computation have been 
 being built based on the Webassembly tech nowadays.

So, I'd like to know how to use webassembly module in stencil in a standard way(recommneded).

The core team of Stencil is considering of this feature to easily support webassembly component module integration?

**Comment by adamdbradley** [comment]
The 1.9.x release is adding support for wasm.
