### ISSUE TITLE
Dynamic imports fails

### ISSUE THREAD

**Issue by YahyaouiMalek** [ionic-team/stencil#1429]
**Stencil version:**

```
 @stencil/core@0.16.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I import dynamically a component the import fails.

**Expected behavior:**
Stencil should import the component without problem

**Steps to reproduce:**
Just import the script tag dynamically using js instead of putting it directly in the html file.

**Working Demo**
https://jsfiddle.net/vqe7wchb/1/

**Failing Demo**
https://jsfiddle.net/vqe7wchb/2/
 
**Other information:**
the second fiddle doesn't fail because of CORS, the script tag in the head has the wrong url.

**Comment by manucorporat** [comment]
Stencil One completely refactors how dynamic import is handled and updates rollup to latest version, which includes plenty of fixes!

**Comment by AchuthSankar** [comment]
where can I get stencil one ?
