### ISSUE TITLE
Syntax of array loops in JSX render function

### ISSUE THREAD

**Issue by OnnoGeorg** [ionic-team/stencil#143]
Just a minor issue, but this helps maybe others new to JSX (like me...): The loop example in the [documentation for templating](https://stenciljs.com/docs/templating) is currently:

    return (
      <div>
        this.todos.map( todo => {
          <div>
            <div>{todo.taskName}</div>
            <div>{todo.isCompleted}</div>
          </div>
        })
      </div>
    )

But this led to an empty output in my test system. I had to add brackets `{}` and another `return()` to get a correctly rendered output:

    return (
      <div>
        {this.todos.map( todo => {
          return (
            <div>
              <div>{todo.taskName}</div>
              <div>{todo.isCompleted}</div>
            </div>
          );
        })}
      </div>
    );

(I am quite excited about Stencil - great job!)

**Comment by OnnoGeorg** [comment]
Ah, ionic-team/stencil-site is the correct place for this issue... I close this one.

**Comment by robruiz** [comment]
This is still not fixed in the guide code on the stenciljs website. Thank goodness for this post.

**Comment by karstil** [comment]
I had the same problem. Why is this not fixed on the website?

**Comment by rramsey** [comment]
Yes, thank goodness for @OnnoGabriel because here it is  almost 6 years later and this is still a problem.
