### ISSUE TITLE
Incorrect require path in CommonJs output (/dist/index.js)

### ISSUE THREAD

**Issue by riovir** [ionic-team/stencil#1430]
**Stencil version:**

```
 @stencil/core@0.18.1 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
`/dist/index.js`, which by the generated comment should be CommonJs format contains
```JavaScript
module.exports = require('../esm/index.js');
```
It's causing the Jest with CommonJs preference to fail in dependent projects. The `../`also points outside of the `/dist` folder.

**Expected behavior:**
The output (I think) should be this, which would make CommonJs customers happy:
```JavaScript
// YourComponents: CommonJS Main
module.exports = require('./cjs/es5/index.js');
```

**Steps to reproduce:**
1. Take the latest Stencil component template
2. Add `/src/index.ts` with 
```JavaScript
export function registerIcon(icon) {
    console.log("Let's pretend that happened", icon);
}
```
3. Run the build then check out `/dist/index.js`
+4. Try `npm pack`, installing in another project using Jest and try testing something that imports the exported function

**Comment by DKirwan** [comment]
@manucorporat I'd like to open a PR to fix this. Should I branch off the 0.18.1 release branch? I see the latest master has some work ongoing towards a 1.0 release
