### ISSUE TITLE
Rollup: undefined - Could not load (file path)

### ISSUE THREAD

**Issue by angulartist** [ionic-team/stencil#1432]
**Stencil version:**
```
 @stencil/core@0.18.1
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Using the latest stencil core version and the fresh ionic-pwa starter, i'm getting an error that show up randomly in dev mode.
I'm just coding a component and then I got an error like this when stencil tries to compile at the run time : 
Rollup: undefined
```
Could not load /Users/techlead/Desktop/article13/article13memes/src/components/app-root/app-root.js
(imported by
/Users/techlead/Desktop/article13/article13memes/src/entry.app-root.ion-app.ion-nav.ion-route.ion-router.js):
 ENOENT: no such file or directory, open '/Users/techlead/Desktop/article13/article13memes/src/components/app-root/app-root.js'
```
**Expected behavior:**

Should not happens.

**Steps to reproduce:**

- Instanciate a new ionic-pwa project with the stencil CLI.
- Start a dev server
- Do some code
- Error appears randomly

**Related code:**

**app-root.tsx**
```tsx
/// <reference types="firebase" />

declare const auth: firebase.auth.Auth

import { Component, State } from '@stencil/core'
import { authState } from 'rxfire/auth'

@Component({
  tag: 'app-root',
  styleUrl: 'app-root.css'
})
export class AppRoot {
  @State() currentUserId: string

  componentDidLoad() {
    this.monitorAuth()
  }

  monitorAuth() {
    authState(auth).subscribe((user: firebase.User) => {
      if (user) {
        this.currentUserId = user.uid
      } else {
        return auth.signInAnonymously()
      }
    })
  }

  render() {
    return (
      <ion-app>
        <ion-router useHash={false}>
          <ion-route url='/' component='app-home' />
          <ion-route url='/connecting' component='app-connecting' />
          <ion-route-redirect
            from='*'
            to={this.currentUserId ? '/' : '/connecting'}
          />
        </ion-router>
        <ion-nav />
      </ion-app>
    )
  }
}

```

**Other information:**

This error show up whenever I'm trying to edit a component...

**Comment by arjunyel** [comment]
I believe 0.18.1 has errors, does rolling back to 0.18.0 fix it?

**Comment by arjunyel** [comment]
And also when you rollback, delete the .stencil folder if you have any issues

**Comment by angulartist** [comment]
> And also when you rollback, delete the .stencil folder if you have any issues

Updating @ionic/core to latest version seems to resolve this, thanks @arjunyel
