### ISSUE TITLE
Component methods with async results

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#1433]
**Stencil version:**
```
 @stencil/core@0.18.1
```

**I'm submitting a:**
[x] feature request

**Current behavior:**

All public methods on Stencil components that are decorated with `@Method()` currently need to be async and return a promise.

There are many cases where the async syntax makes it awkward to use the methods when rendering child components.

For example, one common use case is a parent component that renders a bunch of related child components.  For example, a grid control with some general settings in the parent component and then cell rendering handled by child components.

If the child component needs to make a call to a method on the parent component as part of its rendering process then it is difficult to perform the rendering because the child's render method is not async.  There is no way to render the child one pass.  So it then needs to keep some kind of state and refresh the rendering when the async result is received.

In the case where the parent is already initialized and ready to be called the child component still can not render in one pass.

For the parent/child scenario the parent is always rendering first because it is how the child component was created.

**Proposed behavior:**

- Allow component methods to be implemented as either sync or async methods.
- Provide sync property or method to indicate if a component is ready.  This could be used to check if the child can render and avoid the async delay in the common case where the parent is already ready.  It is important for this to be a sync call so that child rendering can continue if the parent is ready.
- Provide async onReady callback that can be used to re-render the child component if the parent component is not yet ready.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
