### ISSUE TITLE
--watch duplicates content of shadowRoot on update

### ISSUE THREAD

**Issue by Schoko19961** [ionic-team/stencil#1437]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
While in --watch mode, when a change is made in the .tsx file, Stencil will add the content of the render function to the shadowRoot, but not remove the old one.

**Expected behavior:**
Stencil should replace the old content of the shadowRoot with the new one.

**Steps to reproduce:**
Create a component which only has a render function.

**Related code:**

```tsx
import { Component } from '@stencil/core';

@Component({
  tag: 'test-header',
  // styleUrl: 'test-header.css',
  shadow: true
})
export class MyComponent { 
  
  render() {
    const styles = {
      height: '100px',
      backgroundColor: 'blue',
      marginBottom: '5px'
    }; 
    return (
      <header style={styles}>
      </header>
    );
  }  
}
```

**Other information:**
Under certain conditions, this behavior does not occure:

1. Component has @Prop()
2. Component has @State()

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
