### ISSUE TITLE
request: setup CI service

### ISSUE THREAD

**Issue by vvakame** [ionic-team/stencil#144]
I think We want a CI service (likes Circle CI).
it will help protect & make it easy to contribution the project.

I ❤️ Circle CI.
I tried to apply Circle CI 2.0 to this project. I can send a PR 👍 
https://github.com/ionic-team/stencil/compare/master...vvakame:try-circleci
https://circleci.com/gh/vvakame/stencil/2

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Please submit a pull request for the change you have linked above. That would be great!

**Comment by kensodemann** [comment]
Thank you for the pull request!! This has been merged in.

**Comment by vvakame** [comment]
👍 
Next, We should turn on Circle CI Webhook.
Maybe it can from https://circleci.com/gh/ionic-team/stencil .

And, I ❤️ CI badge in README.md 😉 
[![CircleCI](https://circleci.com/gh/ionic-team/stencil.svg?style=svg)](https://circleci.com/gh/ionic-team/stencil)
