### ISSUE TITLE
Add CSS Variables to Generated Docs

### ISSUE THREAD

**Issue by hartjus** [ionic-team/stencil#1440]
**Stencil version:**

```
 @stencil/core@latest
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

I think it's awesome that Stencil is generating docs during the build step--it's great!  However, the one thing that's missing is the ability to (automatically) document the CSS variables that the component exposes.  This is primarily a concern when using shadow dom `shadow: true` on a component.  In our case, we treat the CSS Variables as part of the API for the component, just like we would for props, events, and methods.  Since this is the recommend way to "theme" or "style" a shadow DOM component, this would be a great addition to the auto generated docs.

**Comment by manucorporat** [comment]
It's actually possible!
https://github.com/ionic-team/ionic/blob/master/core/src/components/alert/alert.scss#L7-L17

Just write your code like this in your .css files

**Comment by romulocintra** [comment]
> It's actually possible!
> https://github.com/ionic-team/ionic/blob/master/core/src/components/alert/alert.scss#L7-L17
> 
> Just write your code like this in your .css files

Unfortunately isn't working for me anymore 0.18.1

**Comment by hartjus** [comment]
@manucorporat Awesome, thank you!

**Comment by justindasilva** [comment]
@romulocintra, I also am not able to see this working. I am currently on 0.18.1

If I put the following code in one of my component CSS files:
```
/**
 * @prop --background: Background of the button
 * @prop --background-activated: Background of the button when activated
 * @prop --background-focused: Background of the button when focused
 */
```

Should I expect to see this in the generated `component-manifest.json` file? 
This is what I'm hoping to achieve.

**Comment by romulocintra** [comment]
@manucorporat  still not working for me to :(

**Comment by stevenpetryk** [comment]
Same, this isn't working for me either. It doesn't show up in the generated docs JSON in my case.
