### ISSUE TITLE
Drag n drop dropevent.preventDefault not working

### ISSUE THREAD

**Issue by elgervb** [ionic-team/stencil#1442]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'd like to implement a drag 'n drop component, but am unable to drop. To achieve this, I need to call `preventDefault` on the dragevent in `dragover` like so:
```
@Listen('dragover')
  dragOver(e: DragEvent) {
    e.preventDefault(); // Necessary. Allows us to drop.
  }
```
When I do this, there is an error in the console: `Unable to preventDefault inside passive event listener invocation`.

I've made a workaround to use `addEventListener('dragover', callback);` on the host, which does seem to work.

**Expected behavior:**

**Steps to reproduce:**
Just add the basic drag 'n drop events using the `@Listen` decorator and call preventDefault on one of the events.

**Related code:**

```tsx
  @Listen('dragover')
  dragOver(e: DragEvent) {
    e.preventDefault(); // Necessary. Allows us to drop.
  }

  @Listen('drop')
  drop(event: DragEvent) {
    event.stopPropagation();
  }
```

**Other information:**

**Comment by simonhaenisch** [comment]
Maybe have a look at https://developers.google.com/web/updates/2017/01/scrolling-intervention. You can disable passive mode for event listeners (if that's really what you want):

```ts
@Listen('dragover', { passive: false })
// ...
```

**Comment by elgervb** [comment]
Tnx @simonhaenisch, that seems to do the trick. Overlooked that setting.
