### ISSUE TITLE
Change end of line for markdown output (LF/CRLF)

### ISSUE THREAD

**Issue by kerosin** [ionic-team/stencil#1443]
**Stencil version:**

```
 @stencil/core@0.16.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**

- on a Windows machine the stencil build process generates markdown files with LF

**Expected behavior:**

- make it configurable to change the desired end-of-line style or consider .editorconfig which might define this option

**Steps to reproduce:**

- run```npm init stencil``` and create a component
- add ```end_of_line = crlf``` to your *.editorconfig* file (Windows machine)
- run ```stencil build --docs```
- look at md file (e.g. src\components\my-component\readme.md)

**Related code:**
*.editorconfig*
```

[*]
charset = utf-8
end_of_line = crlf
...
```

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
