### ISSUE TITLE
Component Starter App Fails to build in IE11: 1.0.0-alpha.5

### ISSUE THREAD

**Issue by kevinmpowell** [ionic-team/stencil#1444]
**Stencil version:**

```
@stencil/core@1.0.0-alpha.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Running the component starter app in IE11 with `npm start --es5` or `npm start --production` results in a JS error and nothing rendered.

**Expected behavior:**
Running the component starter app in IE11 with `npm start --es5` or `npm start --production` should render the component.

**Steps to reproduce:**
From scratch:
1. `npm init stencil` - choose component starter app
2. `npm start --es5` - confirmed working in IE11 with latest non-alpha version
3. Upgrade to alpha: `npm install @stencil/core@one --save-dev`
4. Add `import h` to `my-component.tsx` and update `src/index.html` to include `.mjs` file.
5. `npm start --es5` 

Blank page and JS console error in IE11:
![Screen Shot 2019-04-08 at 9 22 22 AM](https://user-images.githubusercontent.com/979463/55731745-51b6ed80-59e0-11e9-86b1-28c410fd564c.png)
![Screen Shot 2019-04-08 at 9 22 37 AM](https://user-images.githubusercontent.com/979463/55731763-5a0f2880-59e0-11e9-8bb2-1fd3616ce59f.png)

**Comment by manucorporat** [comment]
fixed by https://github.com/ionic-team/stencil/commit/e82a1b07b64a6d1d34b9caf6c370b49826abe783

Thanks for the issue!
