### ISSUE TITLE
alpha.5 Rollup: Plugin Error => Unexpected token e in JSON at position 0 (rollup plugins installed though)

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#1447]
**Stencil version:**
```
 @stencil/core@1.0.0-alpha.5
```

**I'm submitting a:**
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Throws without any further info although the necessary (I believe) rollup plugins are installed:

```
[ ERROR ]  Rollup: Plugin Error
           Unexpected token e in JSON at position 0
```

**Expected behavior:**
Builds without error.

**Related code:**
Repo: https://github.com/bitflower/caseos-ui/tree/stencil-one

**Comment by manucorporat** [comment]
Is this issue still a problem?
