### ISSUE TITLE
alpha.5 stencil.config copy does not work on "dist" (works on "www")

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#1448]
**Stencil version:**
```
 @stencil/core@1.0.0-alpha.5
```

**I'm submitting a:**
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Nothing is copied to the `/dist/collection` folder. It works for the `outputTarget` `www` though. See this slack discussion: https://stencil-worldwide.slack.com/archives/C9LTCKAN8/p1554820145084000

Config:
This would not copy to `/dist` as expected:
```
      type: 'dist',
      copy: [
        {
          src: '**/*.scss'
        },
        {
          src: '../node_modules/@fortawesome/fontawesome-free/webfonts',
          dest: 'assets/fonts'
        },
        {
          src: '../node_modules/@fortawesome/fontawesome-free/scss',
          dest: 'styles/vendor/fontawesome'
        }
      ]
    },
```

**Expected behavior:**
Copies files to `dist/collection` into their respective paths.

**Related code:**
Repo: https://github.com/bitflower/caseos-ui-kit/blob/stencil-one/stencil.config.ts

**Comment by manucorporat** [comment]
Already fixed in latest alpha
