### ISSUE TITLE
External Component into StencilJS bundle

### ISSUE THREAD

**Issue by rcidaleassumpo** [ionic-team/stencil#1453]
Hi, 

Just to picture the scenario first. 
I have two web components (A, B), both built separately, by that I mean, in different stencil projects. 
Component A is using component B in the render method. 
The way to make this work is to put both js outputs of both of the bundles inside of a index.html and it works as it should. 
What I wanted to know if it's possible, is to add component B as a dependency and add that to package.json, where Stencil would see the dependency and add component B to the bundle, and when I add to a index.html, I just need to add the bundle from Package A, and it would work. 
Is there any way to achieve this? 
So the idea is similar to when I use Rxjs for instance into a project, and then I don't need to put rxjs cdn into the index.html. 
I understand that with Rxjs I would be importing the whatever I want from the package.json, and then somehow making it active and adding that to the bundle. 
I hope I'm making myself understand. 
Thank you,

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now.

You can import other packages and web components into a stencil library by writing @import statements either within the component that's using the package in question, or if you are adding other web components, you can achieve this similarly with the globalScript here: https://stenciljs.com/docs/config#globalscript, by adding the import statements to the top of that file.

**Comment by nicolae536** [comment]
Does this work or maybe I don't understand it ? 🤔 

In my project I have

```
import { IonButton } from "@ionic/core/components/ion-button";
import { Component, Prop, h, JSX, Host, ComponentInterface } from '@stencil/core';
import { Color, AnimationBuilder, RouterDirection } from '../ionic-types';

@Component({
    tag: 'he-button',
    scoped: true,
})
export class ButtonComponent implements ComponentInterface {
    @Prop() public buttonType = 'button';

    @Prop() public color?: Color;

    @Prop() public disabled = false;

    @Prop() public expand?: 'full' | 'block';

    @Prop() public shape?: 'round';

    @Prop() public size?: 'small' | 'default' | 'large';

    @Prop() public fill?: 'clear' | 'outline' | 'solid' | 'default';

    @Prop() public routerDirection?: RouterDirection;

    @Prop() public routerAnimation?: AnimationBuilder | undefined;

    @Prop() public download: string | undefined;

    @Prop() public href: string | undefined;

    @Prop() public rel: string | undefined;

    @Prop() public strong = false;

    @Prop() public target: string | undefined;

    @Prop() public type: 'submit' | 'reset' | 'button' = 'button';

    @Prop() public form?: string | HTMLFormElement;

    public render(): JSX.Element {
        return (
            <Host>
                <IonButton
                    buttonType={this.buttonType}
                    color={this.color}
                    disabled={this.disabled}
                    expand={this.expand}
                    shape={this.shape}
                    size={this.size}
                    fill={this.fill}
                    routerDirection={this.routerDirection}
                    routerAnimation={this.routerAnimation}
                    download={this.download}
                    href={this.href}
                    rel={this.rel}
                    strong={this.strong}
                    target={this.target}
                    type={this.type}
                    form={this.form}
                >
                    <slot name="icon-only" />
                    <slot name="start" />
                    <slot />
                    <slot name="end" />
                </IonButton>
            </Host>
        );
    }
}
```

On the build output the `defineCustomElements` function is incorrect, it defines only my button not also the `IonButton` I also tried to use `<ion-button` but it didn't work, with importing it like this I get the code for it included in my element. Can you help me with an example ?
