### ISSUE TITLE
1.0.0-alpha.8 TypeError: Cannot read property 'replace' of undefined at escapeMarkdownTableColumn

### ISSUE THREAD

**Issue by gopherrdiggs** [ionic-team/stencil#1455]
**Stencil version:**

```
 @stencil/core@1.0.0-alpha.8
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Error is thrown when attempting to build the project. I've gone through the Breaking Changes notes and made what changes I think are needed.

![2019-04-11_13h11_24](https://user-images.githubusercontent.com/40251647/55982554-cd25d280-5c5e-11e9-9fab-b904afb724b6.png)

**Related code:**
GitHub branch:
https://github.com/anionic-components/anionic-components/tree/stencil-upgrade

**Other information:**

**Comment by manucorporat** [comment]
This is already fixed in master! Thanks for the issue!
