### ISSUE TITLE
Pre cache manifest - many unused files get loaded

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#1457]
**Stencil version:**
```
 @stencil/core@0.18.1
```

**I'm submitting a:**
[x] feature request

**Current behavior:**
When Stencil generates a service worker, it includes all of the js files in the pre cache manifest - even if they will not be needed at runtime.

Component bundles currently generate up to 8 versions of component code:
- iOS and md versions if different css is specified for any component in the bundle
- sc and non sc versions based on css shadow dom
- esm and es5 versions

Chunk files currently generate 2 versions:
- esm and es5 versions

When the app is started with a service worker, the service worker requests every file that is listed in the pre cache manifest so that it available to the app later.  This results in a significant amount of code that is loaded that will never be used.  This consumes network bandwidth and also takes up local storage space which goes against the app quota.

Total code loading could probably be reduced by 50-75% without any impact on the application.

**Enhanced behavior:**

Generate multiple `sw.js` files based on the browser capabilities.

In the script that is embedded in the `index.html` page, extend the code that decides which version of the app core to include and use that to select the appropriate sw.js file.

One thing that might be tricky is iOS vs. md versions of the components.  The typical use case is for the entire app to be rendered with the default mode so pre loading that probably makes sense.  In the rare case where a component is requested with a different mode then that would be a cache miss.  That still seems better that all the code overhead in case something is needed.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it.

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
