### ISSUE TITLE
Srcset causing redundant get requests on window resize

### ISSUE THREAD

**Issue by JustBlueTurtlin** [ionic-team/stencil#1458]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
Using srcset with local images during development causes many unnecessary get requests whenever the window is resized.  Seeing CPU spikes upwards of 40% on a decently spec'ed desktop.  

**Expected behavior:**
Images should only be requested when hitting the specified width.

**Steps to reproduce:**
npm init stencil, select app starter, update to @stencil/core@0.18.1.
Insert an ```<img srcSet="..."``` tag into any component and link to local files. Run npm start and resize the window with network tab open in dev tools.

**Other information:**
This is only an issue in development while using local files.

**Comment by arsenx** [comment]
I'm having the same issue created a new ticket in with a video reference #1480

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
