### ISSUE TITLE
Use of an external type in a @Prop signature results in a compile error in components.d.ts

### ISSUE THREAD

**Issue by apillard** [ionic-team/stencil#1461]
**Stencil version:**

```
 @stencil/core@0.18.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

This is a companion issue to https://github.com/ionic-team/stencil/issues/797. This differs from 797 in that I'm trying to use a type in a \@Prop instead of a \@Method

```
[ ERROR ]  TypeScript: src/components.d.ts:37:40
           Cannot find name 'Graphic'.

     L36:  */
     L37:  'infoTemplate': string | ((graphic: Graphic) => string);
     L38:  /**

[22:41.9]  build failed in 7.71 s
```

**Expected behavior:**

At the very least, the types should be replaced with an any like the current behavior for methods, ideally, the types would be preserved for both props and methods.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here

import Graphic from 'esri/graphic';

    @Prop() private infoTemplate: string | ((graphic: Graphic) => string);


```

**Other information:**

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
