### ISSUE TITLE
(1.0.0-alpha.8 / 1f4b0a) Copy task doesn't execute for rebuilds

### ISSUE THREAD

**Issue by adamlacombe** [ionic-team/stencil#1462]
**Stencil version:**

```
 @stencil/core@1.0.0-alpha.8
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Modifications to files included in the copy section of outputTargets are not being copied after the initial build.

**Expected behavior:**

Modifications to files included in the copy section of outputTargets should trigger the copy action again.

**Steps to reproduce:**

**Related code:**

```typescript
import {Config} from '@stencil/core';
import {sass} from '@stencil/sass';

export const config: Config = {
  globalScript: 'src/global/app.ts',
  globalStyle: 'src/global/app.css',
  plugins: [
    sass()
  ],
  enableCache: false,
  outputTargets: [
    {
      type: "dist",
      dir: 'dist'
    },
    {
      type: "www",
      dir: 'www',
      copy: [
        {
          src: 'test.html',
          dest: 'test.html'
        }
      ],
    }
  ]
};

```

**Other information:**

I'm testing against commit 1f4b0a8729c002fc1a127ae350c2be4cd53137c6

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
