### ISSUE TITLE
SyntaxError: Identifier 'h' has already been declared

### ISSUE THREAD

**Issue by FDiskas** [ionic-team/stencil#1464]
**Stencil version:**
```
 @stencil/core@0.18.1
```

**I'm submitting a:**
- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**
Project will open blank page

**Expected behavior:**
Should be working as it works with `"@stencil/core": "~0.16.2"`
**Steps to reproduce:**
1. `npm init stencil`
1. `npm i @stencil/core@0.18.1`
1. `@stencil/router@0.3.3`
1. `npm start`

**Related code:**

```
npm start
```

Project will not start some error in console.

**Comment by FDiskas** [comment]
I tried the 0.18.1-0 version but I got
![image](https://user-images.githubusercontent.com/468006/56292780-70c82480-6130-11e9-9fde-5721e1ff8e3e.png)

**Comment by JCKodel** [comment]
Same here.

I just created a new project (without Ionic) using npx init stencil, then upgraded StencilJS to 0.18.1.

**Comment by FDiskas** [comment]
@JCKodel instal directly `v0.18.1-0` version and it will work

**Comment by manucorporat** [comment]
Stencil One requires developers to explicitally import the {h} function, that should solve any of the issues described in this issue!
