### ISSUE TITLE
Copy with read-only files fails build

### ISSUE THREAD

**Issue by drdreo** [ionic-team/stencil#1468]
**Stencil version:**
```
@stencil/core@0.18.0
node: v8.11.4
npm: 6.9.0
```

**I'm submitting a:**

- [x] bug report

**Current behavior:**
The current copy behavior during build is to copy all assets from src/assets to www/assets and dist/collection/assets.
Although, when those asset files are read-only, they are copied with that permission restriction to the new location. I assume (because testing the node behavior was easy) stencil internal uses [copyFile](https://nodejs.org/api/fs.html#fs_fs_copyfile_src_dest_flags_callback) which throws an error when the destination file already exists and is not writeable.

Read-only files can occur when using VCS or you have to handle a "special" OS like Windows10.

**Expected behavior:**
You can build and rebuild even with read-only files.

**Steps to reproduce copy error:**
Create a folder with a file text.txt and set it to read-only. Run the node script twice --> error
```
const fs = require('fs');

fs.copyFile('text.txt', 'text2.txt', (err) => {
  if (err) throw err;
  console.log('text.txt was copied to text2.txt');
});
```

And directly related to stencil: Create a project, use some assets, make those assets read-only and build more than once.

**Other information:**
Error:
```
Error: EPERM: operation not permitted, copyfile ...
```

Probably don't throw an error but handle it internally would be the best solution. Otherwise, you could provide the option to always delete the whole destination folder (not only it contents) or even provide [compiler hooks](https://webpack.js.org/api/compiler-hooks/) like Webpack does.

**Comment by mmakrzem** [comment]
does anyone have a work around to this problem?  I have read-only assets and I can't run stencil build without first manually removing the read-only attributes from my files because successive runs of the stencil build command fails when it tries to overwrite the read-only assets in the dist or www folders

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
