### ISSUE TITLE
Support for vanilla custom elements in component registry w/ lazy loading

### ISSUE THREAD

**Issue by jpray** [ionic-team/stencil#1470]
**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Seems that only custom elements declared using the @Component decorator are included in the component registry.

**Desired behavior:**
Stencil's component registry and lazy loading functionality are 🔥.  I would like to be able to write vanilla web components without the @Component decorator and have them be packaged up similar to how the regular stencil components are.

**Steps to reproduce:**

src/components/hello-world/hello-word.ts
```
class HelloWorld extends HTMLElement {
    connectedCallback() {
        this.innerHTML = `
            hello world
        `;
    }
}
customElements.define('hello-world', HelloWorld);
```

Thanks for considering this...

**Comment by adamdbradley** [comment]
This is being added in the 1.9.x release. Thanks
