### ISSUE TITLE
Global components configuration object

### ISSUE THREAD

**Issue by Szymon-dziewonski** [ionic-team/stencil#1472]
**Stencil version:**
```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request

**Expected behavior:**
We try to build UI library on top of stencilJS, but we have faced problem with global components configuration. From our perspective it would be useful to give end developer possibility for configuring components in runtime - e.g. by passing configuration object inside of `defineCustomElements` 2nd arguments (options).

So, I would like to introduce new property in this options object, e.g. `globalConfig` or so. This object would be available from context of any component, so it could be used for example to bring extra CSS styles/paths to CSS files.

On component level config object could be visible under some kind of decorator (e.g. `@global`). In future maybe there should be a possibility to obtain only some path under global configuration object via `@global('path.to.your.option')`, so bundles can be better optimized.

Also, is there a possibility (now) to implement static `style` method (something working similar to current `render()`, but maybe will be fired less often), or all "dynamic" styles should be applied into `<style>` tag inside `render()`?

**Comment by psmyrdek** [comment]
Can't you set up some kind of a contract that there will be this global variable X your components can read and check its values?

**Comment by Szymon-dziewonski** [comment]
Not sure what you exactly had in mind. We can pollute e.g. `window` variable, but that's just wrong pattern and can lead to conflicts.
Functionality like this could be used in many cases since stencil-generated bundle is always provided as self-contained library - it just makes sense to have configuration possibilities available.

**Comment by psmyrdek** [comment]
Sure thing, but can't you use props for this?

**Comment by Szymon-dziewonski** [comment]
There is difference between a global configuration for some component and context-based configuration passed via props.
Forcing end-developer to pass the prop configuration to every component instance (while he wants to change something globally) IMO is not a good approach.

**Comment by manucorporat** [comment]
why not esm imports?

```
import {config} from '../my-config';
```

**Comment by Szymon-dziewonski** [comment]
not really, we don't know end-dev path/filename of configuration file for import during building stencil on our end. Unfortunately that's how stencil is working and compiling and providing already built package have it's downsides - which is this case.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Comment by Szymon-dziewonski** [comment]
@adamdbradley sorry unfortunately I can't I don't work with Stencil anymore
