### ISSUE TITLE
Add check for XSS

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/stencil#1473]
I am proposing that we add an error or warning message to ensure that props do not get passed directly to innerHTML.

```jsx
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'my-first-component',
})
export class MyComponent {
  @Prop() name: string;

  render() {
    return (
      <p>
        My name is <span innerHTML={this.name}></span>
      </p>
    );
  }
}
```

This should help prevent the possibility of developers creating an XSS vulnerability. We cannot stop it but at least we can inform them.

This will not catch all scenarios, but it will likely catch many common ones.  This issue was created in response to https://github.com/ionic-team/ionic/issues/18065.

**Comment by dgibson666** [comment]
Oops, I'm guilty of this. Is there a best practice for using this technique but making sure that data is safe?
