### ISSUE TITLE
Add requestAnimationFrame polyfill

### ISSUE THREAD

**Issue by XBDRX** [ionic-team/stencil#1478]
**Stencil version:**
```
@stencil/core@1.0.0-alpha.12
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
```
window.requestAnimationFrame() 
window.cancelAnimationFrame()
```
are not polyfilled for older browsers on embedded platforms.

**Expected behavior:**
The polyfill should account for the possible presence of vendor-specific methods such as                     

```
window.webkitRequestAnimationFrame
window.mozRequestAnimationFrame
window.oRequestAnimationFrame
window.msRequestAnimationFrame
```
If the polyfill makes use of Date.now() then this should also be polyfilled, as it is not supported natively on some devices.

**Steps to reproduce:**
Requires access to the specific devices.  I am happy to test any PRs.

**Comment by manucorporat** [comment]
Stencil does not officially support browsers older than IE11, and IE11 does support `requestAnimationFrame`, which browsers are you trying to support?

**Comment by adamdbradley** [comment]
If the device you're supporting doesn't support requestAnimationFrame then I would recommend including the polyfill in your build. RAF is in ie11 and that's as far back as our default polyfills are coming with.
