### ISSUE TITLE
Stencil test lazy loading not playing nice with Lerna & workspaces

### ISSUE THREAD

**Issue by hvgeertruy** [ionic-team/stencil#1479]
**Stencil version:**
```
 @stencil/core@0.18.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Stenciljs test task does not play nice with lerna & yarn workspaces. 
We use lerna & yarn workspaces to have multiple stenciljs packages in one repo. Workspaces helps us manage dependencies between those packages.

Stenciljs has a lazy loading mechanism for test related dependencies (jest, jest-cli, @types/jest, puppeteer, @types/puppeteer) and tries loading them when they are not available.

So far, so good. But...

The lazy loading mechanism ignores workspaces and tries installing the dependencies in our stencil packages. 

The problem with this, is that we want the components to use the shared dependencies instead. Because:
- We don't want to have to install those dependencies for every package we have in the monorepo
- It messes up our workspaces. It gets confused when there are dependencies in the package itself.

**Expected behavior:**
I saw in the code that the lazy loading setup is still experimental. So maybe it will change regardless?

There are a couple of solutions that could work for us
- fix the lazy loading so it recognizes if there is a lerna setup with workspaces and play nice
- an opt-out on the lazy loading, so that we can let lerna provide the dependencies instead.
- no lazy loading?

**Steps to reproduce:**
- set up a lerna monorepo with workspaces :)
- create a stenciljs package in a workspace
- run 'yarn test' (or run `stencil test --spec --e2e`)
- get the following notices (the ones we would like not to have):
```
[08:44.3] Please wait while required dependencies are updated. This may take a few moments and will only be required for the initial run.
[08:44.3] installing dependencies: jest, puppeteer, jest-cli, @types/jest ...
```

**Comment by hvgeertruy** [comment]
I just managed to get it working by commenting out some code:
- [core/dist/cli/index.js] function taskTest, commented out: `yield config.sys.lazyRequire.ensure(config.logger, config.rootDir, ensureModuleIds);`
- [core/dist/testing/index.js] function startPuppeteerBrowser, commented out: `const puppeteerModulePath = config.sys.lazyRequire.getModulePath('puppeteer');` and substituted the path to the puppeteer module in workspaces

Definitely not the way I want to fix this, but it proves my theory :)

**Comment by romulocintra** [comment]
> I just managed to get it working by commenting out some code:
> 
> * [core/dist/cli/index.js] function taskTest, commented out: `yield config.sys.lazyRequire.ensure(config.logger, config.rootDir, ensureModuleIds);`
> * [core/dist/testing/index.js] function startPuppeteerBrowser, commented out: `const puppeteerModulePath = config.sys.lazyRequire.getModulePath('puppeteer');` and substituted the path to the puppeteer module in workspaces
> 
> Definitely not the way I want to fix this, but it proves my theory :)

Yes, same here, i was doing --hoist and all worked well , but regarding tests puppeteer , jest-cli etc ... are installed.

**Comment by subgan82** [comment]
Yes observing the same issue , any update on this.

**Comment by adamdbradley** [comment]
Closed with https://github.com/ionic-team/stencil/commit/7f739a0cac7423e91ac8614206b71894796965d8
