### ISSUE TITLE
<img> and <picture> srcSet element issues

### ISSUE THREAD

**Issue by arsenx** [ionic-team/stencil#1480]
**Stencil version:**

```
 @stencil/core@0.16.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When creating a srcset attribute for the img element every time I resize the page I get a ton of requests sent to fetch the same image on every pixel count change. This issue **does not occur on Firefox.** I have only tested using firefox and chrome. I have also tried setting the media attribute and did not help. I also tested the picture element and get the same issue.
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
<img
    srcset="assets/dist-assets/200/tree-1.jpg 200w, assets/dist-assets/400/tree-1.jpg 400w, assets/dist-assets/800/tree-1.jpg 800w, assets/dist-assets/1200/tree-1.jpg 1200w,"
    src='assets/icon/icon.png'
    alt=""
 />

<picture>
  <source
    media="(min-width: 200px)"
    srcSet="assets/dist-assets/800/tree-1.jpg 800w, assets/dist-assets/1200/tree-1.jpg 1200w"
   />
  <img srcset="assets/dist-assets/200/tree-1.jpg 200w, assets/dist-assets/400/tree-1.jpg 400w" />
</picture>
```

**Other information:**

Here's a quick screen cap of what is happening. I will try to reproduce this using plain html to see if stencil's architecture has to do with this.

https://www.loom.com/share/a227e69f930e44fb800fac4abac6c3e0

**Comment by arsenx** [comment]
Just did a demo using a basic http-lite server and was not experiencing this issue

**Comment by arsenx** [comment]
Just tested on @stencil/core v1.0.0-alpha.13
Issue still present

I suspect it may have to do with the img tag being in the render method. But that's just a guess.

**Comment by manucorporat** [comment]
Can you provide the source code of a full component that reproduces the issue?

**Comment by arsenx** [comment]
Yup, i'll rebuild it and link a repo shortly.

**Comment by arsenx** [comment]
Here's a link to the repo i just created https://github.com/arsenx/stencil-issue-1480

**Comment by arsenx** [comment]
Any news on this issue?

**Comment by arsenx** [comment]
Just tried this out again a few months since ticket and it seems like it's been fixed on newer versions of both chrome and firefox. Closing!
