### ISSUE TITLE
Feature request "styleguidist"

### ISSUE THREAD

**Issue by FDiskas** [ionic-team/stencil#1482]
Would be nice to have such dock implementation as it is in https://github.com/styleguidist/react-styleguidist

Thank you

**Comment by jkarttunen** [comment]
I've been using Storybook, and it has worked fine.
https://whoisryosuke.com/blog/2019/using-stencil-with-storybook/

**Comment by dmartinjs** [comment]
Same here, Storybook who grow faster, have more features, have more bridge between design tools and work really good with Stencil.

It's the main tools for that currently.
https://designsystemssurvey.seesparkbox.com/2019/

**Comment by FDiskas** [comment]
Storybook has big bundle size and it's can't be used in production

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

This is an interesting idea, and we'll evaluate this at a later date. Thank you for the idea!
