### ISSUE TITLE
Feature Request: Configure builds to disable minification

### ISSUE THREAD

**Issue by petermikitsh** [ionic-team/stencil#1485]
**Stencil version:**

```
 @stencil/core@0.18.0
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Components built by Stencil are minified.

**Expected behavior:**

Builds are configurable to disable minification. When consuming components produced by Stencil, I am doing so in an environment where I am using webpack, rollup, etc. It is unnecessary for Stencil to force minification on my builds.

Additionally, when I consume my stencil components in another project and they throw an error, because the code is minified and there are no source maps, it is difficult to trace the origin of the error. Had the code not been minified (and that responsibility was left to my own bundler), I'd have an easier time reasoning about errors thrown by my Stencil components.

Consequently, the minification provides a sub-optimal developer experience, and should be optional.

**Comment by bodinaren** [comment]
In current version 1.0.0-alpha.14 you can add `minifyJs: false` to the stencil.config.ts file.
