### ISSUE TITLE
Allow rollup configuration overrides

### ISSUE THREAD

**Issue by liron-navon** [ionic-team/stencil#1489]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I have issues with stencil when I'm trying to use a monorepo, it would be helpful if we can supply a custom rollup setup to handle different [(rollup issues)](https://github.com/rollup/rollup-plugin-commonjs/issues/361).

**Expected behavior:**
Allow having a custom rollup configuration file

**Comment by Matthew-Smith** [comment]
This would likely help resolve issues around rollup plugin loading order:
https://github.com/ionic-team/stencil/issues/1305#issuecomment-488025036

**Comment by liron-navon** [comment]
@Matthew-Smith 
I added another issue, this one is a feature request, but the other is the actual bug which brought me to request it, [#1491](https://github.com/ionic-team/stencil/issues/1491)

I'm used to working with webpack and a lot of packages which use it like "**storybook**" or "**vue**" gives some way to extend it with custom configurations, so I think there is a need for it here, though I have no idea why you picked rollup instead of webpack/parcel, it's complicated and have a lot of issues  🤔

**Comment by nborelli** [comment]
I am also running into problems when trying to rollup a library that breaks when rollup freezes the module.  It would help to add the freeze option to the RollupOutputOptions interface in Stencil 1.  This would be the same as the Rollup CLI switch "--no-freeze" to prevent the freezing of namespace objects.

**Comment by adrianschmidt** [comment]
I would like to configure rollup to treat a specific node module as an external dependency, so it doesn't include that in my build output. I can't find any information that indicates Stencil would currently let me do that? Unless there is already a way to do that, the requested feature should resolve the problem I'm facing.
