### ISSUE TITLE
Using HyperScript h() in Stencil One

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/stencil#1494]
**Stencil version:**

```
@stencil/core@1.0.0-alpha.13
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When using Stencil One with the new way of importing h for typings I can no longer use hyperscript in my components. We use this sometimes in order to dynamically create an element and would like it to keep working or have some kind of alternative.

**Expected behavior:**

Use of h() will render a component just as it did prior

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by manucorporat** [comment]
Please share some code that reproduces the issue

**Comment by 4aficiona2** [comment]
Bumped into the same issue after upgrading to version 1.0.6. We need to dynamically create tags depending on the context. In our case headings. See component file.

[dynamic-heading.tsx.txt](https://github.com/ionic-team/stencil/files/3310364/dynamic-heading.tsx.txt)

How would you tackle this? Is there a possibility to alias / rename "h()"?

**Comment by popcorn245** [comment]
@4aficiona2 We actually got around this by finding something cute in Ionic's own components. The ion-button, uses it's own way of rendering a dynamic components so we have changed to using that. Here is the trick and a link to the code for the ion-button so you can check it out for yourself.

![image](https://user-images.githubusercontent.com/4184680/59979820-407a8780-95b2-11e9-8e9a-d365cbfb0830.png)

You set the component name string to a variable and you can use that variable as the tag name in JSX. You can even explode an object as component props. 🤯

https://github.com/ionic-team/ionic/blob/master/core/src/components/button/button.tsx

As far as I am concerned @manucorporat we can close this issue and hope this comments helps other who run across this.

**Comment by 4aficiona2** [comment]
@popcorn245 Thanks for your suggestion. Worked like a charm!

**Comment by mrfoster** [comment]
@popcorn245 This workaround is fine if you simply want to create the component and not set any attributes.  It seems like the typings are broken as it imports a namespace instead of the function.

```
export declare namespace h {
    function h(sel: any): d.VNode;
    function h(sel: Node, data: d.VNodeData): d.VNode;
    function h(sel: any, data: d.VNodeData): d.VNode;
    function h(sel: any, text: string): d.VNode;
    function h(sel: any, children: Array<d.VNode | undefined | null>): d.VNode;
    function h(sel: any, data: d.VNodeData, text: string): d.VNode;
    function h(sel: any, data: d.VNodeData, children: Array<d.VNode | undefined | null>): d.VNode;
    function h(sel: any, data: d.VNodeData, children: d.VNode): d.VNode;
    namespace JSX {
        interface IntrinsicElements extends d.JSX.IntrinsicElements, d.JSXBase.IntrinsicElements {
            [tagName: string]: any;
        }
    }
}
```
If I use ```h('test-component', { name: 'Test' }, null)```, I get a typescript compilation error of ```This expression is not callable. Type 'typeof h' has no call signatures```. It seems to work momentarily when ran locally but then fails with the same compile error.  If I use ```h.h('test-component', { name: 'Test' }, null)```, it compiles but then fails at runtime with ```h.h is not a function```.

There's possibly a good reason for it but I'm very new to Stencil and don't understand if it's a bug or intentional.  Fortunately I've found the following workaround but it feels a bit like a hack and has taken a bit of finding.  

```
// @ts-ignore
h('test-component', { name: 'Test' }, null)
```

Is it something that can be fixed?

**Comment by popcorn245** [comment]
@mrfoster this was an intentional choice by the Ionic team.  The method I depict in the screenshot using a string set as a variable for a tag in the JSX is the preferred method.  You can see how you can use that to create a dynamic component and using the spread operator (,..) we can even pass a dynamic set of props.

**Comment by mrfoster** [comment]
@popcorn245 Thanks I hadn't noticed or considered doing it like that.
