### ISSUE TITLE
Context is not defined Error in Stencil One

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/stencil#1495]
**Stencil version:**

```
 @stencil/core@1.0.0-alpha.16
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When upgrading an Ionic PWA Toolkit app to Stencil One it won't render in the browser and keeps throwing a Context is not defined error. (Screenshot Below)

It looks to be Ionic related and kills the whole app.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

![image](https://user-images.githubusercontent.com/4184680/57094787-fc1beb00-6cd6-11e9-8642-235bd8cad8bf.png)

**Comment by arjunyel** [comment]
Hello, they are currently working on a compatible version of Ionic https://stencil-worldwide.slack.com/archives/C9LTCKAN8/p1556805493209100?thread_ts=1556804121.206600&cid=C9LTCKAN8

**Comment by manucorporat** [comment]
This should be fixed in master now!
