### ISSUE TITLE
Scoped classes are broken in Stencil One

### ISSUE THREAD

**Issue by sh-a-v** [ionic-team/stencil#1500]
**Stencil version:**

```
 @stencil/core@1.0.0-alpha.19
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

![s103](https://user-images.githubusercontent.com/7159528/57163242-4b5a3c80-6df9-11e9-8a8d-7b1cdcdf5ebd.png)

`.native-button` without scoped classes

**Expected behavior:**

![s102](https://user-images.githubusercontent.com/7159528/57163224-3da4b700-6df9-11e9-8703-501d1f9e248f.png)

`.native-button` with scoped classes (it works well in 0.18)

**Steps to reproduce:**
**Related code:**

**Other information:**

![s104](https://user-images.githubusercontent.com/7159528/57163393-b441b480-6df9-11e9-9866-a0a64496ce83.png)

**Comment by manucorporat** [comment]
I can not reproduce the issue, https://github.com/ionic-team/stencil/commit/f62129405175bb415a5e75abfd8499a40be2e64e

**Comment by sh-a-v** [comment]
html:
```
<body>
  <app-root></app-root>
  <script type="module" src="build/app.esm.js"></script>
  <script nomodule src="build/app.js"></script>
</body>
```

app-root:
```
import { Component, h } from '@stencil/core'

@Component({
  tag: 'app-root',
  styleUrl: 'app-root.styl'
})
export class AppRoot {
  render() {
    return (
      <ui-button text="test"/>
    )
  }
}
```
ui-button:
```
import { Component, Prop, h } from '@stencil/core'

@Component({
  tag: 'ui-button',
  styleUrl: 'ui-button.styl',
  scoped: true
})
export class UIButton {
  @Prop() text?: string = ''
  @Prop() icon?: string = ''

  render() {
    return (
      <div class="native-button">
        { this.icon }
        { this.text }
      </div>
    )
  }
}
```

after `stencil build --dev --watch --serve` I have this issue

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/stencil/commit/bed9050898020b86828d5bb1b02c518ad3b7e8e1!
