### ISSUE TITLE
Rollup plugins not run at start, needs stencil.config reload

### ISSUE THREAD

**Issue by tanguyantoine** [ionic-team/stencil#1507]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

We want to use rollup plugin to inject environment variables into html so that we do not rely on hard coded values.

We use: `rollup-plugin-replace-html-vars` to replace `MY_VARIABLE` text to `REPLACEMENT`

when you start the dev server then nothing get replaced but if you touch the `stencil.config.ts` file and reload then it works

here's a repo containing the source code to reproduce the error: https://github.com/tanguyantoine/stencil-rollup-plugin-issue.

**Expected behavior:**

the rollup plugin used would convert the text without the need or reloading the configuration 

**Steps to reproduce:**

- clone this repository https://github.com/tanguyantoine/stencil-rollup-plugin-issue
- install dependencies: `npm install`
- start local server: `npm start`
- wait for browser to open: 
- you see `MY_VARIABLE` (`www/index.html` isn't properly generated)
- touch the config: `touch stencil.config.ts`
- refresh you browser
- you see `MY_VARIABLE` replaced by `REPLACEMENT`

**Related code:**

```tsx
// stencil config
import { Config } from '@stencil/core'
import replaceHtmlVars from 'rollup-plugin-replace-html-vars'

export const config: Config = {
  namespace: 'mycomponent',
  outputTargets: [
    { type: 'dist' },
    { type: 'docs' },
    {
      type: 'www',
      serviceWorker: null // disable service workers
    }
  ],
  plugins: [
    replaceHtmlVars({
      files: 'www/index.html',
      from: /MY_VARIABLE/g,
      to: 'REPLACEMENT'
    })
  ]
}
```

```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0" />
    <title>Stencil Component Starter</title>
    <script src="/build/mycomponent.js"></script>
  </head>
  <body>
    <h1>MY_VARIABLE</h1>

    <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>
  </body>
</html>

```

**Other information:**

- dev server config seems not to be fresh at the first run

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
