### ISSUE TITLE
Integration issue with css-vars-ponyfill when using css @import rule

### ISSUE THREAD

**Issue by petermikitsh** [ionic-team/stencil#1509]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Codepen: https://codepen.io/anon/pen/QRwxMz

In the codepen, I'm pulling in a set of stencil components from `https://unpkg.com/@anjuna/core@1.0.0-alpha.1/anjuna-core.js`.

Those components depend on CSS Variables defined in stylesheets (in the HTML section of the Codepen).

What I observe: CSS Variables are not getting replaced in IE 11, causing a funky rendering. (The table background color is missing, and the table's font colors are incorrect. See second image below for correct rendering). 

<img width="1748" alt="Screen Shot 2019-05-06 at 5 20 20 PM" src="https://user-images.githubusercontent.com/1571918/57263348-96f12e00-7025-11e9-8340-02f9222508b1.png">

**Expected behavior:**

CSS Variables are replaced, and a proper rendering is created (e.g., Chrome 74 on Mac OS looks correct):

<img width="1630" alt="Screen Shot 2019-05-06 at 5 21 42 PM" src="https://user-images.githubusercontent.com/1571918/57263353-9d7fa580-7025-11e9-88d2-7da9eb601539.png">

**Steps to reproduce:**

As discussed in https://github.com/jhildenbiddle/css-vars-ponyfill/issues/71, this issue only occurs when css files are imported via CSS `@import` rules. It does not occur when using the HTML `link` tag.

E.g., this breaks the polyfill:

```html
<style type="text/css">
  @import url("https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/theme.css");
  @import url("https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/icons.css");
  @import url("https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/navfont.css");
  @import url("https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/application.css");
</style>
```

But the polyfill works here:

```html
<link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/theme.css'>
<link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/icons.css'>
<link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/navfont.css'>
<link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/npm/@anjuna/theme@0.2.8/css/application.css'>
```

**Comment by manucorporat** [comment]
The CSS shim can not intercept dynamic @import of CSS, there is little we can do about it. I would recommend to bundle all the CSS in a single file, by resolving the imports at compiler time!

**Comment by petermikitsh** [comment]
@manucorporat `css-vars-ponyfill` supports `@import` rules. Are you referring to a different css shim? If so, that sounds separate from this bug report.
