### ISSUE TITLE
import of a namespace is not added to component.d.ts

### ISSUE THREAD

**Issue by chsami** [ionic-team/stencil#1512]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When you import a namespace like this :
```
import Konva from 'konva';
```
The import does not get imported in the component.d.ts file when building the stenciljs component.
**Expected behavior:**
I would expect the import to be added to the component.d.ts file that is auto generated by stencil.

**Steps to reproduce:**
A clean project with the issue can be found on my github: https://github.com/chsami/stenciljs-bug

**Related code:**
```
import { Component, Prop } from '@stencil/core';
import { format } from '../../utils/utils';
import Konva from 'konva';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: Konva.Animation;

  /**
   * The last name
   */
  @Prop() last: string;

  private getStages() {
      return Konva.stages
  }

  private getText(): string {
    return format(this.first, '', this.last);
  }

  render() {
    return <div>Hello, World! I'm {this.getStages()} - {this.getText()}</div>;
  }
}
```

component.d.ts:
```tsx

import '@stencil/core';

export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': Konva.Animation;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: Konva.Animation;
  }
}
```

**Other information:**

As you can see the import is missing in the component.d.ts file that is auto generated by stencil.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
