### ISSUE TITLE
Interface doesn't get added to components.d.ts when union type is used to type event detail

### ISSUE THREAD

**Issue by mcumpl** [ionic-team/stencil#1513]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When a union type is used to type event detail such as EventEmitter<MyEventDetail | MyEventDetail[]> the interface is not being imported to components.d.ts file and the build fails. It seems to me that the parser doesn't parse union types correctly.

```
[ ERROR ]  TypeScript: src/components.d.ts:42:37
           Cannot find name 'MyEventDetail'.

     L41:    'middle'?: string;
     L42:    'onFormat'?: (event: CustomEvent<MyEventDetail | MyEventDetail[]>) => void;
     L43:  }

[06:57.9]  build failed in 3.27 s
```

**Expected behavior:**

Interfaces should be imported to components.d.ts even if they are used in a union such as EventEmitter<MyEventDetail | MyEventDetail[]>.

**Steps to reproduce:**

See the code.

**Related code:**

```tsx
import { Component, Prop, Event, EventEmitter } from "@stencil/core";
import { format } from "../../utils/utils";
import { MyEventDetail } from "./my-component.types";

@Component({
  tag: "my-component",
  styleUrl: "my-component.css",
  shadow: true
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: string;

  /**
   * The last name
   */
  @Prop() last: string;

  @Event({
    eventName: "format",
    composed: true,
    cancelable: true,
    bubbles: true
  })
  formatEvent: EventEmitter<MyEventDetail | MyEventDetail[]>;

  private getText(): string {
    this.formatEvent.emit({
      first: this.first,
      middle: this.middle,
      last: this.last
    });
    return format(this.first, this.middle, this.last);
  }

  render() {
    return <div>Hello, World! I'm {this.getText()}</div>;
  }
}

```

**Other information:**

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
