### ISSUE TITLE
One Alpha22 Unit Test page.win.getComputedStyle(root).getPropertyValue('foo') does not work

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/stencil#1514]
**Stencil version:**

```
 @stencil/core@1.0.0-alpha.22
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

**Expected behavior:**

local css variable value should be returned
**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by jepiqueau** [comment]
see demo at  https://github.com/jepiqueau/stencil-one-testing.git

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
