### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by YYJay** [ionic-team/stencil#1517]
**Stencil version:**

```
 @stencil/core@0.16.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I want to use `process.env` when i run `npm start`, but i got `process is not defined`
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
console.log(process.env)
```

**Other information:**

MacOS

**Comment by MonsieurMan** [comment]
It's normal, stencil's runs in the browser and `process` is a node specific API.

**Comment by YYJay** [comment]
> It's normal, stencil's runs in the browser and `process` is a node specific API.

Does anyone know how to get env ? 
I want to provide different environment variables in different environments.

**Comment by flawyte** [comment]
One solution *might* be (I haven't tried, it's an idea) to store those variables in a `.json` file. If you have 2 possible environments, then create 2 files (e.g. `vars-dev.json` and `vars-prod.json`), but in your HTML always `fetch('vars.json')`, then in your `stencil.config.ts` you would have to `copy` and rename the right variables file based on the build type : dev or prod.

**Comment by simonhaenisch** [comment]
You can access `process.env` within `stencil.config.ts` which is executed in the node context, then either provide a virtual module or do search-and-replace through a custom rollup plugin. If you have more questions about this, please ask in Stencil Slack.
