### ISSUE TITLE
[1.0.0-alpha.27]: typings for function attributes

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#1520]
**Stencil version:**
```
 @stencil/core@1.0.0-alpha.27
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
Some attributes in Stencil One do not have strong types which results in typescript errors for code that worked in prior versions of Stencil.

Using the following tsconfig setting:
```
"noImplicitAny": true
```

Many attributes are typed as `any` vs. strongly typed.  This results in build errors.  For example:
```
// Error: Parameter 'ev' implicitly has an 'any' type.
<ion-button onClick={ev => this.onOkClick(ev)}>

// Error: Parameter 'el' implicitly has an 'any' type.
<ion-slides ref={el => this.setRef(el)}>

// Components with strongly typed function props also now have errors
// Error: Parameter 'value' implicitly has an 'any' type.
<my-component formatter={value => this.format(value)}>
```

**Expected behavior:**

Attributes should be strongly typed.  This helps reduce extra code to type them again every time they are used and also ensures that they are being used correctly.

For example:

```
// No error is generated even though the wrong type is specified
<ion-button onClick={(ev: number) => this.onOkClick(ev)}>
```

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
