### ISSUE TITLE
[1.0.0-alpha.27]: typings for component attributes

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#1521]
**Stencil version:**
```
 @stencil/core@1.0.0-alpha.27
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
Stencil 1 no longer provides interfaces for component attributes.

It used to be possible to use:
```tsx
const buttonAttr: Components.HTMLIonButtonAttributes;

return <ion-button {...buttonAttr} />;
```

It does not appear that the interface is available in the `components.d.ts` file.

This is the case for both ionic components and components defined within the app.

An approximation seems to be:
```tsx
const buttonAttr: Partial<HTMLIonButtonElement>;
```

But I am not sure that necessarily means the same thing.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
