### ISSUE TITLE
[1.0.0-alpha.27]: type for render result

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#1523]
**Stencil version:**
```
 @stencil/core@1.0.0-alpha.27
```

**I'm submitting a:**

[x] bug report

**Current behavior:**

There does not appear to be an appropriate type to use for the results of render functions.

In prior versions of Stencil it was possible to use `JSX.Element` but this does not appear to work anymore in functional components.

For example, the following now results in an error:

```tsx
export const MyFunctionalComponent: FunctionalComponent = () => {
    const list: JSX.Element[] = [];
    list.push(<span>Test</span>);
    return list;
};
```

It is possible that `VNode | VNode[] | undefined` could be used but it is not clear from the documentation if this is appropriate.

**Expected behavior:**

Have a defined type that is exported by Stencil and can be used for results of render functions and functional component results.

For example, something like:
```tsx
render(): JsxResult {...}

const result: JsxResult;
```

**Comment by manucorporat** [comment]
`JSX` is exported at Stencil/core now, you can use it:
```
import {JSX} from '@stencil/core';

JSX.Element
```

However, this type does not add much information, you could just leave render without a return type
