### ISSUE TITLE
Question: Stencil without all the site building wizz bang?

### ISSUE THREAD

**Issue by jennasalau** [ionic-team/stencil#1524]
Hi,

I really like the Stencil "Component" building api. Nice work!

I just don't need fancy stuff you have wrapped around it. For example, dev server, bundling, routing, lazy loading etc

**How can I use stencil to just output plain javascript?**

For example, I want to go from this `src`

```
import { Component } from '@stencil/core';

@Component({
  tag: 'my-component',
})
export class MyComponent {
   render() {
    return <div>Hello, World!</div>;
  }
}
```

To output similar to this in my dist folder:
```
customElements.define('my-component', class MyComponent extends HTMLElement {...});
```

I'm probably pushing my luck but I also want the pure scss next to it.

Im trying to use Stencil to make a "library" of components that can be themed later. It seems Stencil is design to build "projects" and not "libraries", would that be correct?

**Comment by luketheobscure** [comment]
Along the same lines, I was really hoping to use stencil to write a simple web component I could provide to third parties. Just include a single JS file, and then they could use `<my-component>` on their page, but I have no idea what to do with the output I get from `npm run build`. It somehow turn the 13 files in my `src` folder into 80 files.

**Comment by jennasalau** [comment]
Hey @luketheobscure we ended up using https://github.com/Polymer/lit-element if that helps you.. It doesn't use JSX for the templates which is a bit of a bummer but it suited our needs more.

**Comment by simonhaenisch** [comment]
Afaik they are working on a new output target `experimental-dist-module` to solve sth like this but could take a while.
