### ISSUE TITLE
ssrMiddleware with shadow: true

### ISSUE THREAD

**Issue by Vitalii-001** [ionic-team/stencil#1526]
**Stencil version:**

```
  "@stencil/core": "^0.17.2"
```

**I'm submitting a:**

[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Create a simple express server and use the component with shadow: true metadata
```app.use(express.static(path.join(__dirname, 'www')));```
the server is got stuck (localhost is always in status: pending)

**Expected behavior:**

The server should serve the index.html from www folder

**Steps to reproduce:**

**Related code:**

server.js
```
const express = require('express');
const stencil = require('@stencil/core/server');
const path = require('path');

// create the express app
const app = express();

// set which port express it will be using
const port = 3030;

// load the stencil config
const config = stencil.loadConfig(__dirname);

// serve-side render html pages
app.use(stencil.ssrPathRegex, stencil.ssrMiddleware({ config }));

// serve all static files from www directory
app.use(express.static(path.join(__dirname, 'www')));

// start the server
app.listen(port, () => config.logger.info(`server at http://localhost:${ port }/`));
```

**Other information:**

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
