### ISSUE TITLE
@Listen("keydown") not firing

### ISSUE THREAD

**Issue by callumvh** [ionic-team/stencil#1527]
@stencil/core@0.18.1

**I'm submitting a:**
[ x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
This code snippet directly from the docs in the events section(https://stenciljs.com/docs/events) is not fired when pressing the down arrow.
```typescript
@Listen('keydown')
handleKeyDown(ev: KeyboardEvent){
  if (ev.key === 'ArrowDown'){
    console.log('down arrow pressed')
  }
}
```
If I am not mistaken, an `@Event()` does not need to be emitted from a child component since this is a DOM event.

There are also no errors that come up in the terminal.

**Expected behavior:**
The expected behavior is to `console.log()` `"down arrow pressed"` but it does not do anything.

**Steps to reproduce:**
Windows 10 1809 (OS Build 17763.475)
Node v12.2.0
npm v6.9.0
Created new project and picked `ionic-pwa` starter.
Created new component and then added the code snippet to the component class.

**Other information:**
I am not sure if this is a bug with stencil or if I am just doing something wrong so please forgive me if it is the latter.

**Comment by Jefiozie** [comment]
hey @callumvh, I checked this at my stencil project and here it is working. Can you maybe share some example repo? Maybe I can have a look at it and help you. 
```
@stencil/core:0.18.1

```

**Comment by callumvh** [comment]
Hey @Jefiozie, since it's working for you, it must be a problem with my code, I created a repo for a project of mine, I put the `@Listen("keydown")` in the `app-todo` component, inside the class.

You can get to the component with a button or by typing `localhost:PORT/todo`
https://github.com/callumvh/stencil-listener-not-working

Any guidance would be greatly appreciated. Thank you so much for your help.

**Comment by Jefiozie** [comment]
So I see the issue, a `div` without a `tabindex` will not trigger a keydown event. By default `keyevents` won't work on a `div` without `tabindex`.

I added this to the div

```
<div tabindex="0">
```

After this you should focus/select the div (by example tabbing in to it) and you will see the `console.log`.

Hope this will help you

**Comment by callumvh** [comment]
Thank you so much, that works for me, do you by any chance know how I could make the keydown event work without having to tab into a div? Or so that the keydown event could work from anywhere in the site?

**Comment by Jefiozie** [comment]
I think this can be done by

```
@Listen('document:keydown)
```

I think we can close this issue as we resolved the main problem you had right?
If needed I'm on the slack channel of stencil 👍

**Comment by callumvh** [comment]
Yes thank you.

**Comment by remjx** [comment]
With Stencil 2, this can be accomplished with `@Listen('keydown', { target: 'document' })`

**Comment by illepic** [comment]
@remjx MVP, thank you. If anyone wants to see an example.

```
  @Listen('keydown', { target: 'document' })
  private keyListener(ev: KeyboardEvent) {
    if (ev.key === 'Escape') {
      this.hide()
    }
  }
```
