### ISSUE TITLE
SyntaxError: Identifier 'interval' has already been declared

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#1535]
**Stencil version:**

```
 C:\ae\adaept.com\d3-stencil>npm list @stencil/core
d3-stencil@1.0.2 C:\ae\adaept.com\d3-stencil
`-- @stencil/core@0.18.1-1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Breaks on upgrade from 0.18.1-0 to 0.18.1-1

**Expected behavior:**

Build and run

**Steps to reproduce:**

Details here:

https://github.com/edgarordonez/d3-stencil/pull/31

**Related code:**

Working at this:

![Capture246](https://user-images.githubusercontent.com/140737/57892661-a118e680-77f4-11e9-89b1-11f9ba6a4733.png)

Breaks on this:

https://github.com/peterennis/d3-stencil/commit/0e1c368699994b9912745bf8afbabd57baaeeba2

![Capture247](https://user-images.githubusercontent.com/140737/57892602-5ac38780-77f4-11e9-952e-62e7ddb3d82e.png)

This branch: https://github.com/peterennis/d3-stencil/tree/break0181

```tsx
// insert any relevant code here
```

**Other information:**

Related: https://github.com/ionic-team/stencil/issues/1525

@adamdbradley, @manucorporat, @edgarordonez

This is a blocker for starting an upgrade of D3-Stencil to the 1.0.0 release line.

Guidance appreciated 😄

**Comment by manucorporat** [comment]
It might be related with https://github.com/rollup/rollup/issues/2865
