### ISSUE TITLE
Plugins linting error with stencil one

### ISSUE THREAD

**Issue by techmind-git** [ionic-team/stencil#1538]
**Stencil version:**

```
 @stencil/core@1.0.0-beta.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I get lint errors when using sass and postcss plugin. An excerpt of the error:
```Type '{ name: string; transform(sourceText: string, fileName: string, context?: PluginCtx): Promise<PluginTransformResults>; }' is not assignable to type 'Plugin'.
  Types of property 'transform' are incompatible.
    Type '(sourceText: string, fileName: string, context?: PluginCtx) => Promise<PluginTransformResults>' is not assignable to type '(sourceText: string, id: string, context: PluginCtx) => string | PluginTransformResults | Promise<PluginTransformResults>'.
      Types of parameters 'context' and 'context' are incompatible.
        ...
```

I'm using the latest version of the plugins:
```
@stencil/postcss@0.1.0
@stencil/sass@0.2.1
```

**Expected behavior:**

No typing issues

**Steps to reproduce:**

Setup a basic stencil one project and add sass and postcss plugin in the stencil.config.ts. The plugins section of stencil.config.ts looks like:
```
plugins: [
    sass(),
    postcss({
        plugins: [
            autoprefixer({
                cascade: false,
            }),
        ],
    }),
],
```

**Comment by dgonzalezr** [comment]
Can confirm it. I'm facing the same issue with `stencil/sass` plugin:

<img width="1302" alt="Screenshot 2019-05-17 at 16 22 01" src="https://user-images.githubusercontent.com/328492/57930979-0259bc00-78c0-11e9-97fe-8587ad98949a.png">

**Comment by newtonmunene99** [comment]
I'm also facing the same issue with `@stencil/sass`

**Comment by matteocusinato** [comment]
Same issue, @stencil/sass errors

**Comment by de-dan** [comment]
For IntelliJ-Users: Invalidate your cache and restart:
File -> Invalidate Caches / Restart... -> Invalidate and Restart
For VS-Code users there might be similar solutions

**Comment by olivermuc** [comment]
sass plugin seems fixed,
`@stencil/postcss@0.1.0` still throws errors.

**Comment by techmind-git** [comment]
No issues with postcss anymore after upgrading to 1.0.1. In my opinion the issue can be closed since both issues (sass/postcss) are resolved now
