### ISSUE TITLE
Uncaught (in promise) Error: Constructor for "app-root#undefined" was not found     at initializeComponent

### ISSUE THREAD

**Issue by newtonmunene99** [ionic-team/stencil#1539]
**Stencil version:**

```
  "@stencil/core": "^1.0.0-beta.0"
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Build fine but shows a blank white screen in browser with the following errors in the browser console ;
```
Uncaught (in promise) Error: Constructor for "app-root#undefined" was not found
    at initializeComponent
```
and I'm using firebase in my project. Getting this in browser console
```
SyntaxError: Identifier 'firebase$1' has already been declared
```
**Expected behavior:**

Should show my stencil app in the browser.
**Steps to reproduce:**

- Upgrade to stencil one beta
- npm start

**Comment by manucorporat** [comment]
I am pretty sure i can't reproduce following that step, seems like there is some third party libraries involved, can you provide a repo case?

**Comment by newtonmunene99** [comment]
Here's is the repo for my project https://github.com/newtonmunene99/newtonmunene_public

**Comment by manucorporat** [comment]
After some initial debugging seems like rollup is emitting some duplicated identifiers, opened an issue:
https://github.com/rollup/rollup/issues/2865
