### ISSUE TITLE
why not write render at @Component

### ISSUE THREAD

**Issue by yozman** [ionic-team/stencil#154]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
 insert the output from npm list @stencil/core here
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

why not use render at @Component like
```
@Component({
  render: () => (
    <div />
  )
})
```

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by marvinhagemeister** [comment]
As a user this is certainly an interesting idea! I'm not convinced though that this would be a great fit for the way components are handled currently.

If you add this api, devs will ask for lifecycle methods too, and before you know it you've just rebuild component classes. Moreover other decorators like `@Prop` and `@State` wouldn't work anymore.

Nonetheless, the surface of components api is always a great field to toss ideas around 👍

**Comment by yozman** [comment]
@marvinhagemeister 
lifecycle methods should be a decorator like `@Hook('load')`

**Comment by adamdbradley** [comment]
We may end up having an option for a template in the component decorator, but as far as the render method, having it within the class instance allows it to access `this` vs. it being meta data about the class.
