### ISSUE TITLE
Buffer is undefined on https://github.com/typestack/class-transformer

### ISSUE THREAD

**Issue by JCKodel** [ionic-team/stencil#1544]
**Stencil version:**

```
@stencil/core@1.0.0-beta.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Error:
```
Uncaught (in promise) ReferenceError: Buffer is not defined
    at t.transform (p-39aba6d2.js:1)
    at t.plainToClass (p-39aba6d2.js:1)
    at e.plainToClass (p-39aba6d2.js:1)
    at Ki.querySingleClass (p-0a2d55c9.js:1)
    at async u.loadResume (p-elexrork.entry.js:1)
    at async u.onRouteDidChange (p-elexrork.entry.js:1)
```

Code at error:
```javascript
...
:null==e?e:new Date(e);if(a()&&(r===Buffer||e instanceof Buffer)&&!s)return null==e?e:Buffe
...
```

Context:
An StencilJS app using this code:
```typescript
import { plainToClass } from "class-transformer";

export class RecipeUser
{
	public id: string;
	public avatarUrl: string;
	public displayName: string;
}

export default class Recipe
{
	public sentBy: RecipeUser = plainToClass(RecipeUser, { avatarUrl: "assets/logo.svg", displayName: "Display Name" });
}
```

Details:
Works fine on dev, but when built to production it fails.

Possible causes:
StencilJS/RollUp tree shaking

Workaround (gives me a warning in StencilJS compilation :( ):
1) npm install buffer
2) Import and add Buffer to window manually on global\app.ts:
```typescript
import "reflect-metadata";
import "@ionic/core";
import { setupConfig } from "@ionic/core";
import * as buffer from "buffer";

(window as any).Buffer = buffer.Buffer;

setupConfig({ backButtonText: null });
```

(StencilJS warnings:
```
[ WARN  ]  Bundling Warning PLUGIN_WARNING
           preferring built-in module 'buffer' over local alternative at
           'E:\Projects\KD\MeuCronogramaCapilar\MeuCronogramaCapilar\node_modules\buffer\index.js', pass
           'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'buffer' is imported by src\global\app.js, but could not be resolved – treating it as an external dependency
```
)

Reproduction steps:
1) npm init stencil
2) Answer ionic-pwa, anyProjectName, Confirm Y
3) cd anyprojectname
4) npm install class-transformer reflect-metadata
5) Edit tsconfig.json to emit metadata decoration ("emitDecoratorMetadata": true)
6) On src/components/app-home/app-home.tsx, insert the following code:
```typescript
import "reflect-metadata";
import { plainToClass } from "class-transformer";

class User
{
  id: number
  firstName: string
  lastName: string
}
```

and in the render method:
```typescript
const user = plainToClass(User, { id: 1, firstName: "First", lastName: "Last" });

...
<ion-content padding>
    <p>{user.firstName} {user.lastName}</p>
...
```

7) npm install (sometimes stencil is not found)
8) Run with npm start (everything works just fine and home shows First Last.
9) Build with npm run build
10) Serve the folder www (maybe with npm install -g http-serve?)
11) Open in your browser (if http-serve is being used, it is http://localhost:8080)
12) Check the error:
```
p-1040ff6c.js:1 ReferenceError: Buffer is not defined
    at t.transform (p-j2o2unx7.entry.js:1)
    at t.plainToClass (p-j2o2unx7.entry.js:1)
    at e.plainToClass (p-j2o2unx7.entry.js:1)
    at T.render (p-j2o2unx7.entry.js:1)
    at ut (p-1040ff6c.js:1)
    at Array.<anonymous> (p-1040ff6c.js:1)
    at g (p-1040ff6c.js:1)
    at v (p-1040ff6c.js:1)
```

**Other information:**

https://github.com/typestack/class-transformer/issues/259

**Comment by manucorporat** [comment]
Buffer does not exist in the browser, you might need the: `rollup-plugin-node-builtins` and `rollup-plugin-node-globals` plugins, but remember that will add a lot of JS to your bundlers and it's not a perfect polyfill.

https://next.stenciljs.com/docs/module-bundling
