### ISSUE TITLE
I want to access all other attributes not specified by props

### ISSUE THREAD

**Issue by jfehrman** [ionic-team/stencil#1547]
**Stencil version:**
```
 @stencil/core@0.18.1
```

**I'm submitting a:**
[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
As of right now the only way to get access to a property is through @Prop() decorator.

**Expected behavior:**
I would like to gain access to all properties that have not been explicitly called out through the @Prop decorator.
```
@Props()
otherProps: any;
```
This would allow me to extend classes such as input by passing all attributes/properties down to a child component.

What this is trying to accomplish:
1) This would essentially allow Stencil to replicate the 'is-a' functionality that exists in native web components.
2) We could create a stateless functional component decorator that would allow us to "mount" a functional component directly to the DOM.

**Steps to reproduce:**
Try to provide "is-a" like functionality for extending an input field.  I'm trying to write input fields that come built-in with validation and I can't.

**Related code:**

What I want ...
```
<ez-validation-input class="test" regex="[0-9]" required />
```
and on the inside it would look like
```
@Component({
...
})
export class EzValidationInput {
  @Prop() required: boolean;
  
  @Prop()  regex: string;

  @Props() otherProps: any;

  render() {
    return <input {...otherProps} />;
  }
}
```
And in this example class should be applied to the inner input without me having to painfully describe the structure of an input html element.

**Other information:**
I've tried to read through the @Prop decorator source to build this out on my own, and I am happy to help contribute to building this, but I couldn't figure out up from down in the decorator file.  Not familiar enough with the project yet.  Perhaps if you don't think it is worth adding to the project could you at least help me get started writing the decorator. ;)

**Comment by jfehrman** [comment]
This is what I have come up with so far.   I think it will work but it isn't very elegant.  Can we do something better in Stencil? Sorry to me at least Stencil seems like a bit of a black box on how the compiling works.

**Component:**
```typescript
import { Component, Element, Prop } from "@stencil/core";

const getElementAttributes = (nodeMap: NamedNodeMap) => {
  if (nodeMap) {
    const length = nodeMap.length;
    console.log('namedNodeMap: ', nodeMap)
    return Object.keys(nodeMap).reduce((props, current) => {
      try {
        const numCurrent = parseInt(current);
        if (numCurrent < length) {
          const property = nodeMap[current];
          return {
            ...props,
            [property.name]: property.value,
          }
        }
      } catch (err) { }
    }, {});
  }
  return {};
}

@Component({
  tag: 'ez-input-validation',
  scoped: true,
})
export class EzInputValidation {
  @Prop({ reflectToAttr: true }) props: any;

  @Element() el: any;

  render() {
    const properties = getElementAttributes(this.el.attributes);
    console.log('properties: ', properties);
    return <input {...properties} />
  }
}
```

**Output:**
```html
<ez-input-validation class="hello-world hydrated" props="{&quot;class&quot;: &quot;test&quot;, &quot;name&quot;: &quot;hello&quot;}" data-hmr="3974445">
  <input class="hello-world hydrated" props="{&quot;class&quot;: &quot;test&quot;, &quot;name&quot;: &quot;hello&quot;}" data-hmr="3974445">
</ez-input-validation>
```

**Comment by simonhaenisch** [comment]
If you don't need state within your component, I think you can use a functional component, e. g.

```tsx
interface FooProps {
  bar: 'string';
  [key: string]: any;
}

export const Foo: FunctionalComponent<FooProps> = ({ bar, ...otherProps }) => (
  <input value={bar} {...otherProps} />
);
```

```jsx
import { Foo } from 'somewhere';

<Foo bar="foobar" disabled={true} />
```

**Comment by jfehrman** [comment]
The problem with functional components is they can't be mounted to the Dom directly.  I need it to be able to be called without another stencil component wrapping it.

**Comment by jfehrman** [comment]
What I meant by the last comment was I can't take your Foo element directly to an HTML file.  It has to be included inside of another stencil component in order to be used.  There is a circumstance that I would want to use "is" like functionality.

By "is" like I mean...
```html
<input is="ez-validation-input" regex="[0-9]" required="true" />
```
