### ISSUE TITLE
Rollup issue referencing external npm package

### ISSUE THREAD

**Issue by fredcicles** [ionic-team/stencil#1551]
**Stencil version:**
```
 @stencil/core@1.0.0-beta.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I get the following error and warning when I perform 'npm start'.

[ ERROR ]  Rollup: Invalid External Id
           'C:\Code\ui-ux\heatmap\node_modules\@stencil\core\dist\sys\src\empty.js' is imported as an external by
            C:\Code\ui-ux\heatmap\node_modules\@stencil\core\dist\sys\src\empty.js?commonjs-proxy, but is already an
           existing non-external module id.

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'C:\Code\ui-ux\heatmap\node_modules\@stencil\core\dist\sys\src\empty.js' is imported by
            C:\Code\ui-ux\heatmap\node_modules\@stencil\core\dist\sys\src\empty.js?commonjs-proxy, but could not be
           resolved – treating it as an external dependency

**Steps to reproduce:**
I have installed @amcharts4, which is when the issue arises.  I upgraded to beta 0 from 0.16.3 where I was not seeing this issue and the amcharts4 controls worked properly.

**Comment by peterennis** [comment]
FYI https://github.com/ionic-team/stencil/issues/1551
https://github.com/ionic-team/stencil/issues/1535

NOTE: https://github.com/rollup/rollup/issues/2865

Supposed to be fixed with the new release of rollup

**Comment by fredcicles** [comment]
How do I get that?  It currently is not a dependency on the project, so I am guessing that just installing it would not do the trick.

**Comment by peterennis** [comment]
https://github.com/ionic-team/stencil/releases

It was added in beta2

https://github.com/ionic-team/stencil/commit/6ce6e454d2a1a7bfefc24f50e8340d5de16361c3

**NOTE THIS:** https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md

**Comment by manucorporat** [comment]
can you provide a repo case?

**Comment by fredcicles** [comment]
I did install the beta 2 but got the exact same exception.

**Comment by fredcicles** [comment]
@manucorporat I am using @amcharts4.  Let me know how I can provide you a repo case and will gladly do so.

**Comment by fredcicles** [comment]
[heatmap-one.zip](https://github.com/ionic-team/stencil/files/3202985/heatmap-one.zip)
@manucorporat Here is a very basic project that I created.  It has issues with the rollup.

**Comment by fredcicles** [comment]
https://github.com/rollup/rollup/issues/2726
leads me to believe that the version of rollup being used by stenciljs is out of date.  He says that this issue is addressed in rollup v 1.32 and it appears to me that stencil beta 2 is using rollup version 1.12.3.

**Comment by simonhaenisch** [comment]
@fredcicles the fix is in rollup version `1.12.3` (see the tag next to the branch info in the blue box at https://github.com/rollup/rollup/commit/9f8498045fe0e5465b1339151f5155ff37dbef9e). I'll take a look at your repro.

**Comment by jpchip** [comment]
I crated a project recreating the specific problem from #495, but seems relevant here:

https://github.com/jpchip/stencil-socketio

**Comment by jpchip** [comment]
@fredcicles Your issue might be resolved in v1.0.1, it resolved #495 for me.
