### ISSUE TITLE
[ ERROR ]  write EPIPE Error: write EPIPE at ChildProcess.target._send

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#1555]
**Stencil version:**

```
C:\ae\adaept.com\d3-stencil>npm list @stencil/core
d3-stencil@2.0.0 C:\ae\adaept.com\d3-stencil
`-- @stencil/core@1.0.0-beta.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Run app and then Ctrl-C to exit shows the error

**Expected behavior:**

No error on exit

**Steps to reproduce:**

This issue: https://github.com/edgarordonez/d3-stencil/issues/38
This comment: https://github.com/edgarordonez/d3-stencil/issues/38#issuecomment-494238208
This commit: https://github.com/peterennis/d3-stencil/commit/313ccfb2b3c3ca1c26f3633abbf06a57d1e36312

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by simonhaenisch** [comment]
What node version are you using?

**Comment by peterennis** [comment]
```
C:\ae\adaept.com\d3-stencil>npm --version
6.9.0

C:\ae\adaept.com\d3-stencil>node --version
v10.15.3
```

**Comment by peterennis** [comment]
Looks like it is fixed with this: https://github.com/peterennis/d3-stencil/blob/fab55769c9e7090f93f863b3c010c6a05b0a4eb6/src/components/line-chart/line-chart.tsx#L72
