### ISSUE TITLE
dist/types/stencil.core"' has no exported member 'JSX'.

### ISSUE THREAD

**Issue by Immcse** [ionic-team/stencil#1557]
**Stencil version:**

```
app1@0.0.1 /Projects/IMI Mobile/UI SDK/UI SDK/DemoApp
└─┬ imiconnect@0.0.1 -> /Projects/IMI Mobile/UI SDK/UI SDK/components
  └── @stencil/core@1.0.0-beta.1  extraneous

npm ERR! extraneous: @stencil/core@1.0.0-beta.1 /Projects/IMI Mobile/UI SDK/UI SDK/DemoApp/node_modules/imiconnect/node_modules/@stencil/core
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
```Using stencil generated web components in Ionic app gives following error:
ERROR in node_modules/mycomponent/dist/types/components.d.ts(9,10): error TS2305: Module '"/DemoApp/node_modules/mycomponent/dist/types/stencil.core"' _**has no exported member 'JSX'.**_
```

**Expected behavior:**
"Ionic serve --prod" should run fine
"ionic cordova build android" should run fine

**Steps to reproduce:**
1. Create a web component using Stencil
2. Add to IONIC project using npm install and call defineCustomElements
3. Ionic serve runs fine and component can be seen in web
4. run ionic serve --**prod** OR try cordova build, both are giving above error.

**Other information:**
I have looked at similar posts as suggested. I tried the suggestion from https://github.com/ionic-team/stencil/issues/512 but that doesn't seem to help.

**Comment by manucorporat** [comment]
Should be fixed in beta.2!

**Comment by Immcse** [comment]
@manucorporat any other temporary hack so the Ionic App builds?
