### ISSUE TITLE
Core is forcing lower version of Jest than Stencil

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#1559]
**Stencil version:**

```
1.0.0-beta.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Run tests with Stencil and deps are downgraded

![Capture555](https://user-images.githubusercontent.com/140737/58147472-7de4a180-7c0f-11e9-9a7c-af09c90638e7.png)

**Expected behavior:**

Consistent testing framework

**Steps to reproduce:**

Stencil Jest 24
Here: https://github.com/ionic-team/stencil/blob/master/package.json

Core Jest 23
Here: https://github.com/ionic-team/ionic/blob/master/core/package.json

**Related code:**

Here: https://github.com/peterennis/d3-stencil/commit/293861d048f5045dd2aef8179d229506b2e1ad40

```tsx
// insert any relevant code here
```

**Other information:**

I have seen this a few times in the upgrade process from Stencil 0.16.2 to 1.0.0-beta.3

Ref: https://github.com/edgarordonez/d3-stencil/issues/30#issuecomment-494101822
Ref: https://github.com/edgarordonez/d3-stencil/pull/31#issuecomment-493170089

**Comment by peterennis** [comment]
@adamdbradley 
Is it expected that Core/Stencil testing framework will be kept in sync for the future?

**Comment by peterennis** [comment]
FYI, these security issues come from Jest 23

```
C:\ae\adaept.com\d3-stencil>npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 36311 packages in 8.798s
found 124 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

C:\ae\adaept.com\d3-stencil>
```

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
