### ISSUE TITLE
Mutating an array does not trigger a re-render

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil#156]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
 0.0.5-17
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Mutating an array, such as using `Array.push()` does not trigger a re-render. You have to return a new copy of the array to trigger a render.

**Expected behavior:**

Mutating the array would cause the component to re-render.

**Steps to reproduce:**

```
addItem() {
  // this does not trigger a render
  this.listItems.push(newListItem);
}

render() {
      return (
        <div class="main-page">
          <app-header searchbar={this.searchbar}/>
          <ion-content>
          {this.listItems.length > 0
            ? <ion-list> { this.listItems } </ion-list>
            : <p>Search some place to get weather info</p>
          }
          </ion-content>
        </div>
      );
  } 
```

**Comment by kylecordes** [comment]
From:

https://stenciljs.com/docs/decorators

"Change Detection
Stencil does not actively perform change detection. In order to trigger an efficient re-render, use the @State decorator to update the local state and trigger a re-render.

The example below WILL NOT trigger a re-render

... (code elided)

In the above example, we are changing the contents of the completedTodos array. A re-render is not performed because Stencil does not deeply watch items for change.
"

**Comment by adamdbradley** [comment]
We have decided to not implement this, but rather require a new reference to trigger re-render.

**Comment by adamdbradley** [comment]
@kylecordes Good catch, would you be able to submit a PR and fix up the docs? Thanks

**Comment by kylecordes** [comment]
@adamdbradley I will take a look and see if I can make the docs introduce the no-change-detection gently+firmly+helpfully.

**Comment by kylecordes** [comment]
@adamdbradley I took a stab at a more comprehensive explanation in the site/docs, see PR reference above.
