### ISSUE TITLE
Condtionally rendered shadow-DOM slots are visible all the time in IE11

### ISSUE THREAD

**Issue by Salet** [ionic-team/stencil#1560]
**Stencil version:**
```
 @stencil/core@0.18.1
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Components which are using **conditionally rendered native slots** are improperly rendered inside of Internet Explorer 11. Slotted content is visible no matter if condition is fulfilled or not. This is not the case in other supported browsers and is probably caused by the lack of shadow DOM polyfill in Stencil, since adding it manually fixes the issue.

**Expected behavior:**
Conditionally rendered slots behave the same way in all of the browsers, since full IE compatibility was supposed to be baked in into Stencil.

**Steps to reproduce:**
Create a new component using shadow DOM, slots and conditional rendering. Use production build for IE support: `stencil build --prod --watch --serve`

**Related code:**
Component:
```tsx
import { Component, Prop } from "@stencil/core";

@Component({
  tag: "my-test",
  shadow: true
})
export class MyTestComponent {
  @Prop() opened: boolean;

  render() {
    return this.opened ? (
      <div>
        Text outside of the slot <br />
        <slot />
      </div>
    ) : null;
  }
}
```
Usage:
```html
<my-test opened="true">Slotted text on rendered component</my-test><br /><br />
<my-test opened="false">Slotted text on not rendered component</my-test>
```

**Other information:**
How it looks in IE:
![ie](https://user-images.githubusercontent.com/1308234/58167424-394b1b80-7c8c-11e9-82d3-e2d006e1f775.png)

How it's supposed to look:
![chrome](https://user-images.githubusercontent.com/1308234/58167435-3bad7580-7c8c-11e9-8dc5-38cf56e2d741.png)

**Comment by simondiep** [comment]
@Salet How did you manually apply a Shadow DOM polyfill to bypass this?

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Comment by learnwithratnesh** [comment]
This issue is still present in 1.8.5
