### ISSUE TITLE
Stencil Redux not functioning anymore after upgrading to Stencil One

### ISSUE THREAD

**Issue by kelvincy** [ionic-team/stencil#1562]
**Stencil version:**

```
 @stencil/core@1.0.0-beta.2
 @stencil/redux@0.1.1
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Components using redux code do not function correctly anymore using @stencil/redux after upgrading to Stencil One. The store seems to be returning undefined.

**Expected behavior:**
The store should be defined when initiating with the predefined setStore(store) method. 

**Steps to reproduce:**
Create a store with reducers and initiate the store in a root component. 

**Related code:**
store/index.ts
```tsx
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import logger from 'redux-logger';
import reducers from '../reducers/index';
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';

const configureStore = (preloadedState: any) =>
  createStore(
    reducers,
    preloadedState,
    composeWithDevTools(applyMiddleware(logger, thunk)),
  );

export { configureStore };
```

Component
```tsx
import { Component, Prop } from "@stencil/core";
import { Store } from "@stencil/redux";
import { configureStore } from "../../redux/store/index";

@Component({
  tag: "my-test",
  shadow: true
})
export class MyTestComponent {
  @Prop({ context: "store" }) store: Store;

  componentWillLoad() {
    // Configure store once in this root component
    this.store.setStore(configureStore({}));
  }

  render() {
    return (
      <div></div>
    )
  }
}
```

**Other information:**
<img width="684" alt="Screenshot 2019-05-22 at 16 48 27" src="https://user-images.githubusercontent.com/14090502/58184477-74ac1100-7cb1-11e9-9594-8a6c81e137a1.png">

**Comment by kelvincy** [comment]
I found out that this is caused by:
```
@Prop({ context: "store" }) store: Store;
```
@Prop({ context: "" }) has been deprecated in Stencil One. Is there any alternative or work around for this functionality?

**Comment by manucorporat** [comment]
It has been deprecated but not removed, it should work, just make sure you import `@stencil/redux"` correctly:

you should have at least once, this piece of code:
```
import "@stencil/redux";
```

in your app

**Comment by miqmago** [comment]
That worked. Anyway I would be happy to know how to fix this, I've been reading documentation at https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md and it clearly says:

> Using the `@Prop` decorator with the `context` has been deprecated and their usage is highly unrecommended.

**Comment by rrdlpl** [comment]
@miqmago do you know how should it be used know ?

**Comment by miqmago** [comment]
**src/components/app-awesome-appfeel.tsx**:

```tsx
import { Component, h, State, Prop, Element, Listen, Watch } from '@stencil/core';
import { Store } from '@stencil/redux';

import { toggleTheme, ToggleThemeAction } from '../../store/actions/app';
import { IRootState } from '../../store/reducers';

@Component({
    tag: 'app-awesome-appfeel',
    styleUrl: 'app-awesome-appfeel.css',
})
export class AwesomeAppfeelComponent {
    @Prop({ context: 'store' }) store: Store;
    @Prop theme;
    toggleTheme: ToggleThemeAction;

   componentWillLoad() {
        this.store.mapDispatchToProps(this, { toggleTheme });
        this.store.mapStateToProps(this, (state: IRootState) => {
            const { theme } = state.app;
            return { theme };
        });
    }
}
```

**src/components/app-root/app-root.tsx**:

```tsx
import { Component, h, Prop, State, Watch, Element } from '@stencil/core';
import '@stencil/redux';
// tslint:disable-next-line: no-duplicate-imports
import { Store } from '@stencil/redux';

import { configureStore } from '../../store';

@Component({
    tag: 'app-root',
    styleUrl: 'app-root.css',
})
export class AppRoot {
    @State() error: any;
    @State() title: string;
    @State() isStatusBarLight = true;
    @Prop({ context: 'store' }) store: Store;

    componentWillLoad() {
        // Only do this once, in the root component
        this.store.setStore(configureStore({}));

        this.store.mapStateToProps(this, (state: IRootState) => {
            const { error, title, isStatusBarLight } = state.app;
            document.title = title;
            return {
                error, title, isStatusBarLight,
            };
        });

    }
}
```
