### ISSUE TITLE
Stencil One does not create component.esm.js file in --dev mode

### ISSUE THREAD

**Issue by kelvincy** [ionic-team/stencil#1563]
**Stencil version:**

```
  @stencil/core@1.0.0-beta.2
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
With the new Stencil One it is required to use two different script tags to optimise performance for browsers that support ES Modules.
```
    <script type="module" src="build/component.esm.js"></script>
    <script nomodule src="build/component.js"></script>
```

When running this command for local development:
```
stencil build --dev --watch --serve
```
Stencil does not always create a component.esm.js file that is required in the index.html for local development.

This only happens when in --dev mode. When using the --prod flag, this issue will not occur.

We are running a monorepo with different Stencil One projects and this issue does not seem to appear in every component, even though all the projects have identical configurations. 

**Expected behavior:**

The expected behavior is that the cli will always create a component.esm.js file when using the --dev flag.

**Steps to reproduce:**

I could not find out how to exactly reproduce this bug, because it occurs irregularly in different projects.

**Comment by romulocintra** [comment]
Have a look at https://github.com/ionic-team/stencil/issues/1488

**Comment by kelvincy** [comment]
It works! Thanks @romulocintra 

My component name had the same name as the namespace of my project. After changing the namespace, the esm.js file is being built correctly.

**Comment by romulocintra** [comment]
cc @manucorporat
