### ISSUE TITLE
[1.0.0-beta.5] Document generator & Windows vs. Mac

### ISSUE THREAD

**Issue by stanley85** [ionic-team/stencil#1566]
**Stencil version:**
```
 @stencil/core@1.0.0-beta.5
```

**I'm submitting a:**
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
We are using the latest build and are happy with the new documentation output. Today we discovered that when mac builds the docs it uses / (slashes) in the depends on links. On my windows machine this is build with \ (backslashes). It only works with slashes when markdown is read.

**Expected behavior:**
There should be no change to markdown depending on os.

**Steps to reproduce:**
Build on windows machine. Links to depending objects should have slashes.

**Comment by straningera** [comment]
The same happens for the generated component type definitions at `/dist/types/components/xyz/xyz.d.ts`.

**Current behavior:**

The import of stencil.core is like:

```
import { ComponentInterface } from "..\..\stencil.core";
```

The util function `normalizePath()` is probably not called.

**Expected behavior:**

The import of stencil.core should be like:

```
import { ComponentInterface } from "../../stencil.core";
```

**Comment by kerosin** [comment]
Not directly same problem, but maybe worth mentioning in this context:
The output of markdown files and components.d.ts are also stored with LF on Windows machines (see https://github.com/ionic-team/stencil/issues/1443)

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
