### ISSUE TITLE
[1.0.0-beta.5...1.0.0-alpha.15]  puppeteer`on` method not omitted from E2EPage but breaks if used

### ISSUE THREAD

**Issue by evaneus** [ionic-team/stencil#1567]
**Stencil version:**

```
 @stencil/core@1.0.0-beta.5
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Using `E2EPage.on` to intercept a request throws an exception in stencil `one`

**Expected behavior:**
Ability to intercept requests without an exception being thrown.

This was possible  in 0.18.x

**Steps to reproduce:**

Add an `on` method...

```ts
const page = await newE2EPage();
page.on('request', () => { request.respond(...) });
```

Will throw an exception with `Request Already Handled` because of:

https://github.com/ionic-team/stencil/blob/9c63d34c684ef8451dab4c5fb88c4f22d9907fa7/src/testing/puppeteer/puppeteer-page.ts#L172

**Other information:**

This may be just a question rather than a bug, if there's a workaround for doing this in stencil one.

**Comment by evaneus** [comment]
submitted a PR, but was shooting in the dark -I don't know if there was a purpose for the intercept there that I'm missing and as such can't be sure if removing it is safe. The tests do pass though.

**Comment by evaneus** [comment]
thanks @manucorporat , however this appears to still not work.

I created a clone of component-starter with a test that fails on request intercept.
Upgrading this to stencil 1.1.2 still fails on request intercept.

**Comment by evaneus** [comment]
relevant: https://github.com/GoogleChrome/puppeteer/issues/4524

**Comment by evaneus** [comment]
@manucorporat should this be re-opened? Or is there a workaround that I'm missing.

**Comment by evaneus** [comment]
as of 1.2 this seems to work for me now, with the caveat that you must use `page.setContent()` for the component before adding request interception to  the `Page` instance.

**Comment by edeustace** [comment]
This issue has re-appeared in the latest stencil - @manucorporat - the fix that you added:
https://github.com/ionic-team/stencil/blame/1414bf432a174d5da7f3e933a94fba27dec2d95a/src/testing/puppeteer/puppeteer-page.ts#L230-L231

Has been removed: 
https://github.com/ionic-team/stencil/blob/master/src/testing/puppeteer/puppeteer-page.ts#L247-L259

So the `Request is already handled!` is back.
