### ISSUE TITLE
[1.0.0-beta.5] --dev --serve: component does not unload when rebuilt

### ISSUE THREAD

**Issue by Matthew-Smith** [ionic-team/stencil#1571]
**Stencil version:**

```
 @stencil/core@1.0.0-beta.5
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Original components never unload when doing Hot Module Replacement in dev server.  

The HMR doesn't seem to fully replace the old component, just adds another instance of the component. 

In our case we register a bunch of event listeners on window in the `componentDidLoad` lifecycle method and then we de-register them in `componentDidUnload`. The `componentDidLoad` method gets called for every HMR but none of them ever unload. In our case one of the events will cause an audio file to be played and we hear that audio file playing twice.

**Expected behavior:**

When a component is rebuilt and loaded (HMR) in the dev server the original instance of it should be unloaded.

**Steps to reproduce:**

1) Add console logs to `componentDidLoad` and `componentDidUnload` of some component
2) run dev server
3) make and save any changes to the component
4) observe that the console log in `componentDidUnload` was never called
5) observe that the console log in `componentDidLoad` was called twice

**Related code:**

```tsx
componentDidLoad() {
  console.log('componentDidLoad')
}

componentDidUnload() {
  // Doesn't get called when the dev-server reloads the component
  console.log('componentDidUnload')
}
```

**Other information:**

Perhaps adding a configuration to HotModuleReplacement that forces full page refresh would be a way to get around this for our case.

**Comment by simonhaenisch** [comment]
Probably the same as #1316?

**Comment by Matthew-Smith** [comment]
you are correct, closing because of being a duplicate.
