### ISSUE TITLE
Conditional child of `ion-card` inserted in wrong location.

### ISSUE THREAD

**Issue by tricki** [ionic-team/stencil#1572]
**Stencil version:**
```
@stencil/core@1.0.0-beta.5
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When adding a conditional element as a direct and last child of an `ion-card` it is inserted into the wrong location in the DOM.

It appears that it's inserted one node too early.

**Expected behavior:**
The element should get inserted in the correct location.

**Steps to reproduce:**
Build the below `ConditionalTest` component, insert it into a page and set the `showText` property to `true`. The text will show between the second and third element instead of a the end.

**Related code:**

```tsx
import { h, Component, Prop } from '@stencil/core';

@Component({
  tag: 'conditional-test'
})
export class ConditionalTest {

  @Prop() showText: boolean = false;

  render() {
    return (
      <ion-card>
        <div>Element 1</div>
        <div>Element 2</div>
        <div>Element 3</div>
        {this.showText && <div>This should be the last element.</div>}
      </ion-card>
    );
  }
}
```

**Other information:**
Tested browsers:
- Firefox 67.0 (64-bit)
- Chrome 73, Chrome 76

I tested some other Ionic components and was able to reproduce this bug with `ion-slides`

I also experienced a similar bug a couple of months ago but only in IE11 (wrong location of conditional elements). Unfortunately I never figured out what the problem was.

**Possible workarounds:**

- don't use `ion-card`
- wrap the conditional element in a non-conditional element
- wrap all direct children of `ion-card` in an element (e.g. `<div>`)
- add a non-conditional element as the last child of `ion-card`

**Comment by tricki** [comment]
**Update:** With `shadow: true` the conditional element is inserted as the first child. And if I use `ion-slides` it's even rendered outside the `.swiper-wrapper` element [which should be impossible](https://github.com/ionic-team/ionic/blob/a8f9dfe0e126656c0ece9d594c2995b6cfa7f535/core/src/components/slides/slides.tsx#L484):

![image](https://user-images.githubusercontent.com/523154/58427968-7440bb00-80a1-11e9-932e-2bfb6a2da644.png)

**Comment by tricki** [comment]
Seems to have been resolved, thanks.

**Comment by DmitryAvanesov** [comment]
@tricki , did you end up adding `shadow: true` to solve this?
