### ISSUE TITLE
Not able to update nested object

### ISSUE THREAD

**Issue by lalitbansal457** [ionic-team/stencil#1573]
@State() abc  = {
	"key1": "abcd",
	"key2": "xyz",
	"nestedObject": {
		"key3": "abcds",
		"key4": "vdv"
	}
}

this.abc = {..this.abc, nestedObject.key3: "new value"}

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
