### ISSUE TITLE
The is no `loader` folder inside the `dist` folder. Can NOT use Stencil components inside an Ionic project.

### ISSUE THREAD

**Issue by JilReg** [ionic-team/stencil#1574]
**Stencil / Ionic version:**

```
 @stencil/core@<1.0.0-beta.5>
 @ionic/core@4.4.2
```

**I'm submitting a:**

[X] bug report

**Current behavior:**
The is no `loader` folder inside the `dist` folder.

**Expected behavior:**
I would expect the `loader` folder to be inside the `dist` folder, so I could use Stencil web components inside an Ionic project.

**Steps to reproduce:**

```
mkdir myIonicProject
cd myIonicProject
ionic start
? Project name: myIonicProjectName
? Starter template: blank

cd ../..

mkdir mystencilprojectname
cd mystencilprojectname
npm init stencil
✔ Pick a starter › component
✔ Project name › myStencilProjectName
npm run build
```
This is what I get from Stencil:
<img width="120" alt="Bildschirmfoto 2019-05-28 um 18 39 35" src="https://user-images.githubusercontent.com/33420668/58495505-fd2a2600-8177-11e9-94b3-6042c50ca1a3.png">

Shouldn't the `loader` folder be inside the `dist` folder?

If I then follow the instructions of [https://stenciljs.com/docs/angular](https://stenciljs.com/docs/angular) I am able to modify the file:

`myIonicProject/myIonicProjectName/src/app/app.module.ts` 

as described, but how do I continue from here?

I tried to copy the Stencil `loader` folder inside the `dist` folder, and the `dist` folder inside the Ionic `myIonicProject/myIonicProjectName/src/assets` folder and add 

`import { defineCustomElements } from './assets/mystencilprojectname/dist/loader';`

and

`defineCustomElements(window);`

to the file:

`myIonicProject/myIonicProjectName/src/main.ts` 

but I'm still not able to use `my-component` in Ionic.

The reason I think this is a bug, is because the is not `loader` folder inside the `dist` folder.

Does someone know how to use the Stencil web components in an Ionic project without publishing them to npm (so they stay private)?

**Comment by techmind-git** [comment]
The loader folder was placed outside for a little while (I think in beta.3), but has been placed back inside the dist folder. I'm using beta.5 now and it's generated inside dist when I do "npm run build"

**Comment by JilReg** [comment]
Hmmm, is there a chance I don't have the newest version even if `npm list ` says so?

![Artboard](https://user-images.githubusercontent.com/33420668/58510200-881b1880-8198-11e9-849a-f92f09d00782.png)

**Comment by JilReg** [comment]
This is how my **`package.json`** looks after creating the Stencil project, is it supposed to be like that?

 (`files` has a `dist` **and** a `loader` folder).

```{
  "name": "mystencilprojectname",
  "version": "0.0.1",
  "description": "Stencil Component Starter",
  "main": "dist/index.js",
  "module": "dist/index.mjs",
  "es2015": "dist/esm/index.mjs",
  "es2017": "dist/esm/index.mjs",
  "types": "dist/types/index.d.ts",
  "collection": "dist/collection/collection-manifest.json",
  "collection:main": "dist/collection/index.js",
  "unpkg": "dist/mystencilprojectname/mystencilprojectname.js",
  "files": [
    "dist/",
    "loader/"
  ],
  "scripts": {
    "build": "stencil build --docs",
    "start": "stencil build --dev --watch --serve",
    "test": "stencil test --spec --e2e",
    "test.watch": "stencil test --spec --e2e --watchAll"
  },
  "devDependencies": {
    "@stencil/core": "1.0.0-beta.5"
  },
  "license": "MIT"
}```

**Comment by techmind-git** [comment]
I tried creating a new project and within the new project the build is in fact creating a loader folder outside dist. My other project was an existing project which I upgraded and  then the loader folder is inside dist. So it looks like the change was reverted in stencil repo, but not in the "stencil-component-starter" repo. 
I think (parts of) this commit https://github.com/ionic-team/stencil-component-starter/commit/7c634142d76cc48f2402b74774f71b110228ca9d need to be reverted. 

In the meantime: I could get the newly created project to work correctly by deleting the property esmLoaderPath from the stencil.config.ts. After that line is removed the loader folder is created inside dist when doing "npm run build". 

Can you verify (and maybe raise an issue in the stencil-component-starter repo if you were able to verify my statement to get this aligned with stencil core :-)?

**Comment by JilReg** [comment]
Thank you for your reply! I'm on vacation until next week Wednesday and will check it off I'm back. 🤗

**Comment by joonaspi** [comment]
I have a similar case where I am building a components library with Stencil using ionic/core package to add some Ionic components to my custom components. This components library is consumed in Ionic 4 project. With removal of esmLoaderPath from stencil.config.ts the loader problem @JilReg had is fixed.

But in the Ionic 4 project I do get errors like:
`
ERROR in node_modules/@ionic/core/dist/types/components.d.ts(5309,13): error TS2320: Interface 'HTMLIonActionSheetControllerElement' cannot simultaneously extend types 'HTMLStencilElement' and 'HTMLStencilElement'.
  Named property 'componentOnReady' of types 'HTMLStencilElement' and 'HTMLStencilElement' are not identical.
node_modules/@ionic/core/dist/types/components.d.ts(5309,13): error TS2320: Interface 'HTMLIonActionSheetControllerElement' cannot simultaneously extend types 'HTMLStencilElement' and 'HTMLStencilElement'.
  Named property 'forceUpdate' of types 'HTMLStencilElement' and 'HTMLStencilElement' are not identical.
node_modules/@ionic/core/dist/types/components.d.ts(5315,13): error TS2320: Interface 'HTMLIonActionSheetElement' cannot simultaneously extend types 'HTMLStencilElement' and 'HTMLStencilElement'.
  Named property 'componentOnReady' of types 'HTMLStencilElement' and 'HTMLStencilElement' are not identical.
node_modules/@ionic/core/dist/types/components.d.ts(5315,13): error TS2320: Interface 'HTMLIonActionSheetElement' cannot simultaneously extend types 'HTMLStencilElement' and 'HTMLStencilElement'.
`

I was able to fix those errors by updating from the Ionic 4 project dependency ionic/angular from 4.3.0 to "one" similarly as the components library project is using ionic/core version "one".

This seems a bit odd with the version number "one". Do we now need to keep ionic/angular and ionic/core versions in sync even though they are in different projects? Ionic/angular is dependency of Ionic project 4 and ionic/core is a dependency of the Stencil components library project.

**Comment by glennlawyer** [comment]
Similar problem when using    "@stencil/core": "^1.0.2", solved with @joonaspi 's suggestion.

Gory details:

The auto-generated `stencil.config.js` contains:
```
 outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader'
    },
```
And the resulting project folder has `loader` as a separate folder from `dist`

 Removed the esmLoaderPath from outputTargets. This does result in creating a loader directory in `dist/`, however, since `package.json` still had 
```
"files": [
  "dist",
  "loader"
]
```
the build failed 
```
[ ERROR ]  Package Json: ./package.json:15:5
           Unable to find "loader/" within the package.json "files" array.

     L14:    "dist/",
     L15:    "loader/"
     L16:  ],

[21:59.9]  build failed in 4.14 s
```

Removing `loader` from package.json allowed for a successful build.

Then,

- increment the build number
- publish to npm 
- cd to other project and 
- npm update

and the other project now finds loader
```
import { defineCustomElements } from './assets/mystencilprojectname/dist/loader';
```

**Comment by joonaspi** [comment]
Now all of sudden the @angular/core@one is not anymore available.

npm install @ionic/angular@one
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ionic/core@4.6.0-dev.201906131724.645b9a9

Which version of @angular/core we should use in Ionic 4 project that uses Stencil components that are depending on ionic/core@one? I have tried the latest 4.x versions with all generating the errors mentioned above in my previous comment.

**Comment by manucorporat** [comment]
I think we can close this issue:
```
 outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader'
    },
```
just remove esmLoaderPath from `stencil.config.ts`

@joonaspi  unrelated issue, ionic using core is kind of beta too. Ionic 4.6 will ship with stencil one by default.

**Comment by JilReg** [comment]
@manucorporat 

But this should be a bug in https://github.com/ionic-team/stencil-component-starter, shouldn't it be?

[(Issue)](https://github.com/ionic-team/stencil-component-starter/issues/75)

**Comment by glennlawyer** [comment]
@manucorporat 

Seconding @JilReg's comment. 

Because stencil-component-starter

- creates  the emsLoaderPath in `stencil.config.js` and 
- adds the `loader` file to the files argument of `package.json`.

The current resolution to this issue, as presented in this thread, is for the user to manually remove these lines from the files created by `stencil-component-starter`

**Comment by glennlawyer** [comment]
Fix implemented and pull request created.

**Comment by glennlawyer** [comment]
Now I'm not so sure about the proposed solution. As far as I can tell, Stencil 1.0  has now removed the loader.:

See this from [Breaking Changes](https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md#indexhtmls-scripts-updated-to-use-typemodule)

```
 index.html's <script>s updated to use type="module"
Stencil used to generate a loader .js file that automatically decided which entry-point to load based
 in the browser's capabilities. In Stencil 1.0 we have decided to completely remove the overhead of
 this loader by directly loading the core using the web-standard type="module" script attribute. 
Less runtime and preferring native browser features. Win Win. For more for info, please see Using 
JavaScript modules on the web.
```

Unfortunately, the linked [Using Javascript modules on the web](https://v8.dev/features/modules#browser) doesn't say how to integrate with Ionic ):
