### ISSUE TITLE
[bug] - new mockFetch function doesn't work with reject

### ISSUE THREAD

**Issue by vidarc** [ionic-team/stencil#1580]
**Stencil version:**

```
 @stencil/core@1.0.0-beta-8
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Using the reject function, it fails at the response.headers.serialize step.

**Expected behavior:**

Should allow for promise rejections.

**Steps to reproduce:**

**Related code:**

https://github.com/ionic-team/stencil/blob/master/src/testing/mock-fetch.ts#L212

calls

https://github.com/ionic-team/stencil/blob/master/src/testing/mock-fetch.ts#L107

which has an undefined headers field, so fails here

https://github.com/ionic-team/stencil/blob/master/src/testing/mock-fetch.ts#L131

**Other information:**

**Comment by mexx** [comment]
Same problem when using `response` function directly.
I haven't found a way to create `MockHeaders` to work around the problem.

**Comment by muskand** [comment]
Any updates on this?

**Comment by thccorni** [comment]
Looking at the 1.9.x prereleases it seems that the types for `MockHeaders` and others related to `mockFetch` will be exported in these versions.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
