### ISSUE TITLE
<input list=*> not parsing correctly

### ISSUE THREAD

**Issue by ArturoRodriguezRomero** [ionic-team/stencil#1582]
**Stencil version:**

```
 @stencil/core@1.0.0-beta.5 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
`<input>` `list` attribute not parsing correctly when inside a Stencil component.

**Steps to reproduce:**

- Create a new component library proyect with `npm init stencil`. 
- Replace `MyComponent` `render()` with
``` tsx
render() {
    return (
      <div>
        <input list="list" />
        <datalist id="list">
          <option value="1" />
          <option value="2" />
          <option value="3" />
        </datalist>
      </div>
    );
  }
```
- Rendered code will be
![image](https://user-images.githubusercontent.com/19237413/58701951-b3725300-83a4-11e9-9725-a2002d3a44b3.png)

**Note that `list="list"` is gone from rendered code.**

**Other information:**

Have tried with both:
- `shadow: true`
- `shadow: false`

If used inside `index.html` like this
```html
<body>
  <input list="list" />
  <datalist id="list">
    <option value="1" />
    <option value="2" />
    <option value="3" />
  </datalist>
</body>
```

Behaviour works as expected

![image](https://user-images.githubusercontent.com/19237413/58702055-077d3780-83a5-11e9-9709-4a716c6a253d.png)

OS: macOS Sierra 10.14.5
Browser: Chrome, Firefox, Safari

**Comment by cynx** [comment]
Ran into same issue recently.

**Comment by cesalberca** [comment]
I can reproduce the issue too

**Comment by pfecht** [comment]
Same here in v1.4.0.

**Comment by matt-mcelhaney** [comment]
Still an issue as of v1.5.4.

**Comment by manucorporat** [comment]
Fixed! https://github.com/ionic-team/stencil/commit/73ea50e8007224f7f8bde9df29126dec39d3a943
