### ISSUE TITLE
[ ERROR ]  runJest: Error: Cannot find module 'jest-cli' - Stencil 1.0.0

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#1586]
**Stencil version:**

```
 @stencil/core@1.0.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

**Expected behavior:**

1. Bump dependencies for jest and puppeteer to fix security
2. If downgrade is forced then jest-cli should be found

**Steps to reproduce:**

![Capture565](https://user-images.githubusercontent.com/140737/58751574-191e1800-8455-11e9-8e2d-d9aa70598e10.png)

**Related code:**

peterennis@c4a87df

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by peterennis** [comment]
Possibly related: https://github.com/ionic-team/stencil/issues/1559

**Comment by peterennis** [comment]
Successful tests with jest version that has 124 low severity vulnerabilities

![Capture566](https://user-images.githubusercontent.com/140737/58751852-6308fd00-8459-11e9-9b0e-181989efad6a.png)

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
