### ISSUE TITLE
Issue with puppeteer in a Docker image when e2e testing

### ISSUE THREAD

**Issue by pantro14** [ionic-team/stencil#1587]
Hi folks, I'm currently diving into Stencil. When I run the script `stencil test --e2e` in my Jenkins Pipeline using a Docker image: I get the following  error:

Failed to launch chrome!
ERROR:zygote_host_impl_linux.cc(89)] Running as
root without --no-sandbox is not supported

According to google this is related to puppeteer by adding:

launch: {
  args: ['--no-sandbox', '--disable-setuid-sandbox'],
 }

Has anyone faced this type of issue or has an idea how to implement it in the JestConfig file? 
I'm trying to follow the documentation to perform this task, but for me int's not really clear how to accomplish it: 
https://stenciljs.com/docs/testing-config

Is there any example that I can follow to do this? thank you.

**Comment by adamdbradley** [comment]
Should be possible now, thanks: https://stenciljs.com/docs/end-to-end-testing#caveat-about-e2e-tests-automation-on-cd-ci
