### ISSUE TITLE
Import inline SVG in stencil/core@1.0.0

### ISSUE THREAD

**Issue by R0muald** [ionic-team/stencil#1588]
**Stencil version:**

```
 @stencil/core@1.0.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

To ensure that few core SVGs are part of our library without the needs of assets, we used to use Inline SVG but it's not working anymore since beta-8 (was working in beta-5). 

<img width="463" alt="Screen Shot 2019-06-03 at 11 56 31 AM" src="https://user-images.githubusercontent.com/1919134/58816050-b49abe80-85f6-11e9-8bab-9399d81ed44a.png">

**Expected behavior:**

The SVG should be embedded in the web-component and render correctly.

**Related code:**

```tsx
import { Component, h, Prop } from "@stencil/core";
import IconLogo from './icon-logo.svg';

@Component({
  tag: "se-icon-logo",
  styleUrl: "icon-logo.scss",
  shadow: true
})
export class IconLogoComponent {
  render() {
    return <div innerHTML={IconLogo}></div>;
  }
}
```

**Other information:**

We have been using the plugin `stencil-inline-svg` that started to break after beta-8. Stencil One does have some SVG types related making stencil-inline-svg redundant I suppose.

**Comment by manucorporat** [comment]
You should use:
```
<img src={IconLogo}>
```
