### ISSUE TITLE
Generated ES5 file incorrect filename when running start/debugging

### ISSUE THREAD

**Issue by lcgreen** [ionic-team/stencil#1595]
**Stencil version:**
 @stencil/core@1.0.0

**I'm submitting a:**
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When we use the dist outputTarget the file generated include mylibrary.esm.js and mylibrary-9859e6be.js. This does not conform to the docs that state:

<script type="module" src="./mylibrary/mylibrary.esm.js"></script>
<script nomodule src="./mylibraryy/mylibrary.js"></script>

This breaks ES5 compatibility due to IE not able the find the file. Also the file  mylibrary-9859e6be.js contains arrow functions and breaks in IE.

**Expected behavior:**
The file generated would be mylibrary.js

**Steps to reproduce:**
npm init stencil
select component
namespace mylibrary

npm run start
* dist folder contains mylibrary-9859e6be.js (or equivalent)
npm run build
* dist folder contains mylibrary.js

![image](https://user-images.githubusercontent.com/33125755/58967508-3849dc00-87ac-11e9-841f-240d9e742fa1.png)

**Comment by NRaf** [comment]
Encountered the same issue.

**Comment by NRaf** [comment]
Whoops, just noticed that ES5 files are only created when building for production by design!
