### ISSUE TITLE
IE11 generating duplicate style tags for non-shadow elements

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#1596]
**Stencil version:**

```
 @stencil/core@1.0.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
This specifically afflicts IE11 (surprise!). 

If a `shadow: false` component uses a custom css property _AND_ is part of the render template of a `shadow: true` component, then Stencil stamps out a separate `<style>` tag for each time it is used. 

In our case we have a date-picker that could show 3 months of dates. The date-picker was `shadow: true` as well as the months. The days were changed to `shadow: false` because the scoped CSS being added would make the screen pause whenever the element opened. 

In 0.15.2 we would only get one `<style>` tag for the day which was pretty performant. Now we get 3 months of days which causes a pretty aggressive stop for IE11's massive parsing powers.

**Expected behavior:**
Components set to `shadow: false` (or lacking a shadow designation) should only have one `<style>` tag stamped out especially in a browser without shadow DOM isolation since the scoping is not needed.

**Steps to reproduce:**
I apologize, I have a project fork of the component starter, but our proxy does not allow pushes to github at the moment. Luckily the code is quick and will stamp out 20 duplicate (content-wise) non-shadow style tags:

**Related code:**

*Shadow component*
```tsx
const VALUES = [];
for (let i = 0; i < 20; i++) { VALUES.push(1); }

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {
  render() {
    return <div class='content'>{ VALUES.map(() => <non-shadow />) }</div>;
  }
}
```

*Non-Shadow component*
```tsx
@Component({
  tag: 'non-shadow',
  styleUrl: 'non-shadow.css'
})
export class NonShadow {
  render() {
    return <div>Something to repeat</div>;
  }
}
```
*Non-Shadow CSS*
```css
non-shadow {
  color: var(--the-color-i-use, black); /* This is what causes the duplication */
  display: block;
  position: relative;
}
```

**Other information:**

Love the improvements to Stencil 1.0.0 and thanks for building such a beast!

**Comment by manucorporat** [comment]
So is it generating multiple style sheets for non-shadow, non-scoped?

**Comment by cary-smith** [comment]
@manucorporat - Yes, but _only_ if the non-shadow component is using a CSS custom property.

**Comment by manucorporat** [comment]
Should be fixed by: https://github.com/ionic-team/stencil/commit/56c5f68b7b998c0802f5fb82997d1222c85f4910
