### ISSUE TITLE
Transclusion? this.props.children?

### ISSUE THREAD

**Issue by zwacky** [ionic-team/stencil#160]
I'd like to have content within a component _transcluded_ later on.

I don't think it is possilbe yet, is it? If not, what are the challenges to make it work?

example:
```
render() {
  return (
    <div class="wrapper">
      { this.props.children }
    </div>
  )
}
```

**Comment by motss** [comment]
@zwacky You can use `<slot />` for that. But this suffers from a bug where slotted element(s) is/ are always the first child(ren).

**Comment by adamdbradley** [comment]
@zwacky Yes you can use `<slot>` to have user content placed within your component.

@motss Would you be able to provide an example of how to recreate the bug? Thanks
