### ISSUE TITLE
Stencil One does not load on old browsers (Firefox < 46) 

### ISSUE THREAD

**Issue by fabiolibre** [ionic-team/stencil#1603]
**Stencil version:**
```
 @stencil/core@1.0.1 
```

**I'm submitting a:**
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Stencil is not able to load at all in old browsers, like Firefox 33.

**Expected behavior:**
Even if not officially supported, I the page should still load properly.
0.18.1 works fine in the same Firefox version.

**Steps to reproduce:**
Initialize a new Stencil App Starter.
Try to load it in Firefox 33 or 28.
The page won't be shown and an error is thrown in the console.

**Other information:**
`SyntaxError: missing ; before statement` in `app.js:134` (---> SystemJS 3.1.3).
This error block any further javascript execution.
Old version of Firefox are still widely used because of Selenium.

**Comment by manucorporat** [comment]
This commit should help:
https://github.com/ionic-team/stencil/commit/06986ab6b593377488737f9692b751859bf6509f

But stencil does not officially support that old browser like Firefox 33 or 28.
If you can create a PR (or the community) fixing issues in this old browsers, we are happy to merge though.

**Comment by fabiolibre** [comment]
Hi! Thanks for your quick fix :) Indeed it helped, but didn't solve the issue. I will gladly create a PR for it.
