### ISSUE TITLE
How to only include the components the user wants

### ISSUE THREAD

**Issue by DominicTobias** [ionic-team/stencil#1605]
Hi thanks very much for stencil!

One thing that is unclear to me - although it seems like components are lazy loaded. There doesn't seem to be a way to only import ones that the user needs?

This doesn't seem viable for a large component library so I'm just wondering if I've missed something?

Thanks (and closing as this isn't an issue)

**Comment by romulocintra** [comment]
Did you tried Ionic!?

**Comment by romulocintra** [comment]
Did you gave a try to  Ionicframework ? That is built using stencil
