### ISSUE TITLE
Allow manifest icon validation to be turned off - so they may be generated rather than in src

### ISSUE THREAD

**Issue by MrAntix** [ionic-team/stencil#1608]
**Stencil version:**

```
@stencil/core@1.0.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
build errors because my icons do not exist in src

**Expected behavior:**
Allow us to not validate

**Steps to reproduce:**
remove the png icon from source

**Related code:**
https://github.com/ionic-team/stencil/blob/master/src/compiler/html/validate-manifest-json.ts

**Other information:**

**Comment by manucorporat** [comment]
Can you explain a little bit more your use case?

**Comment by MrAntix** [comment]
Yes, I have an SVG for my icon, I create the pngs at the required size on build from that ‘master’
The validation means I must have a png in the src folder with the names of the generated files

**Comment by MrAntix** [comment]
Is this a rejection or a fix?
