### ISSUE TITLE
No tests found after run test command

### ISSUE THREAD

**Issue by donskov** [ionic-team/stencil#1609]
**Stencil version:**

```
 @stencil/core@1.0.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

![image](https://user-images.githubusercontent.com/9417251/59159034-9b997e00-8acc-11e9-8037-a7333b84eff9.png)

**Expected behavior:**

![image](https://user-images.githubusercontent.com/9417251/59159038-aa803080-8acc-11e9-990f-de97361077e8.png)

**Steps to reproduce:**

Run command:
```bash
npm run-script test
```
instead:
```bash
npm run test
```

**Other information:**

I am using extension [npm](https://github.com/Microsoft/vscode-npm-scripts) for VS Code for run scripts

**Comment by patricksevat** [comment]
@manucorporat could you revisit this issue? I'm running into this issue with 1.3.0 as well.

Basically it appears that jest is adding the command name as a pattern.

It is very easily reproducable by renaming the `test` script in package.json to `test:unit`. I've just reproduced it by cloning a fresh stencil-component-starter. as you can see from the screenshot I'm on W10

![image](https://user-images.githubusercontent.com/16444755/63648755-94c9f100-c734-11e9-90e7-5caefe00a7b8.png)

**Comment by o-hook** [comment]
Exactly the same error occurs to me: I want to start tests with script named `test:unit` and it failes to run. If i place the exact same test into script `test` it works. 

runs:
`"test": "stencil test --spec",`

fails:
"test:unit": "stencil test --spec",

with error: _No tests found, exiting with code 1_

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Comment by bjankord** [comment]
Just ran into this issue. I've created a repo based on the component starter repo to reproduce this issue:
https://github.com/bjankord/stencil-component-starter/commit/408d81584d405b9e7eaf372aa30bf9efb0485b71

If you clone that repo and run `yarn test:foo` or `yarn preversion`, Jest fails to find any tests, but if you run `yarn test` it works perfectly.

**Comment by mplesec** [comment]
@bjankord yarn requires you to use the [run]((https://classic.yarnpkg.com/en/docs/cli/run/)) command (ie: `yarn run test:foo`), without `run` it won't work.
