### ISSUE TITLE
Ionic Components are not working after version 1

### ISSUE THREAD

**Issue by serdaraglamis** [ionic-team/stencil#1610]
**Stencil version:**

```
 @stencil/core@1.0.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Trying to use Ionic components inside Stencil project but it's not working.
**Expected behavior:**
I expect them to be worked as before. Simply importing ionic/core package or adding ionic script and CSS to HTML. But they are not working and throwing an error after Stencil One update.

**Steps to reproduce:**
- Add Ionic css and js to the HTML file and try to use an Ionic component
- or import '@ionic/core' package and try to use one of Ionic components

**Related code:**
When I import css and js script to html file I am getting;
```tsx
// Uncaught TypeError: Cannot redefine property: queue
// at Function.defineProperty (<anonymous>)
```
When I debug it, it throws an error at this block:
```tsx
Object.defineProperty(Ionic, 'queue', {
    get: () => Context['queue']
});
```

If I import it and try to use it in my application I am getting this errors;

```tsx
Uncaught (in promise) Error: Constructor for "ion-toolbar#undefined" was not found
    at initializeComponent (app-fd29fbb0.js:1711)
initializeComponent @ app-fd29fbb0.js:1711
Uncaught (in promise) Error: Constructor for "ion-header#undefined" was not found
    at initializeComponent (app-fd29fbb0.js:1711)
initializeComponent @ app-fd29fbb0.js:1711
Uncaught (in promise) Error: Constructor for "ion-list#undefined" was not found
    at initializeComponent (app-fd29fbb0.js:1711)
```

**Other information:**
Maybe it's related with Context change in Stencil One. 
Thanks

**Comment by manucorporat** [comment]
We are aware of that: https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md#dependencies

Next release likely IOnic 4.6 will use stencil one by default

**Comment by serdaraglamis** [comment]
Thank you very much. I was unaware that. I missed it while reading breaking changes file. Thanks again!
