### ISSUE TITLE
ReferenceError: 

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#1612]
**Stencil version:**

```
 @stencil/core@1.0.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Message from a community member I am working with:

After testing the other component where `Element` was failing, I fixed two issues I was having but now `NodeList` is undefined. Should just be a simple change like for adding `Element`

**Expected behavior:**
Using a `NodeList` in a unit test or in code covered by a unit test would not cause a ReferenceError.

**Other information:**
Likely need to expand the `MockWindow` some more...

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
