### ISSUE TITLE
Excluding --watch from the package.json npm start script terminates server

### ISSUE THREAD

**Issue by edsilv** [ionic-team/stencil#1613]
**Stencil version:**

```
 @stencil/core@1.0.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If I exclude `--watch` from:

`"start": "stencil build --dev --watch --serve"`

The server immediately terminates.

**Expected behavior:**

The server doesn't terminate and I'm able to manually refresh the page.

This is used in conjunction with a .vscode default build configuration to manually control the build (preferable if you don't want every file save to trigger a rebuild/refresh).

**Other information:**

From a slack conversation with `@manu` we think introducing the ability for `stencil serve` to read the stencil.config to get the www directory could be a solution. The npm start script becomes:

`"start": "stencil serve"`

**Comment by viljamis** [comment]
@edsilv Been running into this issue now as well with our team. This used to behave differently with the previous pre 1.0 beta versions and did not immediately terminate, so wondering if this is a regression or a change made on purpose(?)

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
