### ISSUE TITLE
Cannot resolve lazily loaded parts when testing with Testcafe

### ISSUE THREAD

**Issue by John0x** [ionic-team/stencil#1616]
**Stencil version:**

```
 @stencil/core@one
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
![image](https://user-images.githubusercontent.com/5455173/59270209-37ec8d80-8c51-11e9-8bfa-aa3343e25658.png)
Tesing a website that uses stencil components with Testcafe doesn't work, because the path of the lazily loaded parts doesn't resolve properly.

**Expected behavior:**

Lazy loading should work with Testcafe tests.

**Steps to reproduce:**

Take any stencil project and try to test it using testcafe.

**Comment by vogloblinsky** [comment]
This issue seems related to testcafe URL-rewriting proxy https://github.com/DevExpress/testcafe-hammerhead
Using a simple HTTP proxy like https://www.npmjs.com/package/http-reverse-proxy works fine.

**Comment by vogloblinsky** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/1725

**Comment by A30004314** [comment]
I am also having same issue as the stencil site does not load. can you provide some examples to use http reverse proxy in testcafe?
