### ISSUE TITLE
Please clarify Stencil's support of Edge

### ISSUE THREAD

**Issue by Aaron-Sterling** [ionic-team/stencil#1619]
**Stencil version:**

```
 @stencil/core@latest
```

**I'm submitting a:**

[ x ] documentation clarification request

**Current behavior:**

The browser support page contains this language: "Custom Elements are natively supported in Chrome, Firefox, and Safari (including iOS)! Support in Edge is currently in development."

I had a discussion with someone who is concerned that this means that Stencil's support for Edge is currently in development. I believe the intention is to say that Stencil supports Edge with polyfills, and Edge's support for Custom Elements is currently in development. (Specifically, looks to be solved with Edge 75.) Could you please clarify this? Thank you!
**Expected behavior:**

Clearer language that explains Stencil's exact relation to Edge.

**Comment by manucorporat** [comment]
Stencil support Edge and IE11 with polyfills, soon Edge will not need them!
