### ISSUE TITLE
Component state issues related to component re-use

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#1620]
**Stencil version:**
```
 @stencil/core@1.0.0
```

**I'm submitting a:**
[x] feature request

**Current behavior:**
The rendering process and lifecycle methods can make it very difficult to correctly manage component state related to changes in component property values.

Part of the complexity is related to the re-use of components when they are rendered again by their parent with different property values.  If this case the property values become mutable but may mean that prior state is no longer valid.

Here is a usage scenario for a contact management app:

```tsx
// contact-list.tsx
@Prop() firstName: string;
@Prop() lastName: string;
@State() contacts: Contact[];

componentWillLoad() {
    this.calcState();
}

calcState() {
    // fetch data from server
    // then update state
}
```

In this case, assume the calculation of the state information is expensive and/or async.

The initial component rendering is straightforward.

The challenge is to correctly handle changes when the component is rendered again by the parent with different property values.

Possible approaches include:
- `componentWillUpdate`
- `@Watch()`
- `key` attribute
- `render()`

*Using componentWillUpdate*

Performing calculations in `componentWillUpdate` does not work because:
- If multiple property values are updated then it is called after the first property is changed but before the second property is changed.  So if `firstName` and `lastName` are both updated then an calculations will only reflect one of the values.
- The method is called not only when property values are changed but also when state values are changed or `forceUpdate` is called.  This can result in recursive calls when the state value gets updated.

*Using `@Watch()`*

Some issues with using `@Watch()` include:
- It gets called for each property change and it is not possible to know if other values are going to be changed.  The results in state being calculated multiple times which can be expensive or challenging with multiple concurrent async operations.

*Using `key` attribute*

If the parent is able to associate a key with the state of the component then it can use the key to avoid component re-use when property values are changed.  This can work in some cases when there is tight coordination between the component code and the parent code but defeats the purpose of having a component be self contained.

*Using `render()`*

This can be done but requires some overhead.  If you keep a copy of all the property values from the prior render you can check for changes and then use prior state or calc state again if anything has changed.  While this can work it seems awkward to have yet another layer of comparing property values.

**Other issues**

Note that this issue applies not only to `@State()` value but also to any other fields that exist on the class.  The parent thinks it is rendering a new component instance but re-use causes prior state and field values to be carried forward.

Also,  there can be subtle issues when a child component performs initialization during `componentWillLoad`.  Typically this is used to initialize state or other calculated values but this may not be dependable if the component is re-used.  For example, async loading of content based on property values would not work unless the same code gets called in other property change scenarios.

**Potential improvements:**

Some possible improvements include:

- Pass arguments to `componentWillUpdate` that indicate the reason for the update and ensure that it is called after all values have been changed (vs. after the first property change).
- `@Watch` or other lifecycle method called once prior to component re-use.

**Issues in Ionic core**

There appear to be many subtle issues in Ionic core related to state.

```tsx
// label.tsx
componentWillLoad() {
    this.noAnimate = (this.position === 'floating');
    this.emitStyle();
}
```

In this case the animation state is based on the position but if the parent renders the label again with a different position then the old `noAnimate` setting will continue to be used.

```tsx
// radio.tsx
@Watch('checked')
checkedChanged(isChecked: boolean) {
    if (isChecked) {
      this.ionSelect.emit({
        checked: true,
        value: this.value
      });
    }
    this.emitStyle();
}
```

In this case it is possible to `checkedChanged` to be called prior to `this.value` being updated (if the parent renders again and changes both).  This may emit a checked event with the wrong value.

**Comment by manucorporat** [comment]
The problem with componentWillLoad and componentWillRender was fixed, the state should be consistent now
