### ISSUE TITLE
End 2 End Tests Fail when using { browserHeadless: false, browserDevtools:true } Config

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#1621]
**Stencil version:**

```
@stencil/core@1.0.0
```

**I'm submitting a:**
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
e2e tests ran inside a Chromium browser hang on the `await page.setContent(); line`

**Expected behavior:**
The tests run and `debugger;` statements trigger a breakpoint in the Chromium dev tools opened by Puppeteer

**Steps to reproduce:**
1. Add the following to stencil.config.ts
```testing: {
    browserHeadless: false,
    browserDevtools: true
  }```

2. Create an end2end test for any component. 
```describe('my-component', () => {
  it.only('should render', async () => {
    const page = await newE2EPage();
    await page.setContent(`<my-component></my-component>`);
   // Doesn't get past the above line.
    const el = await page.find('my-component');
    expect(el).not.toBeNull();
    console.log('render test end');
  });```
3. `$ npm test`


**Other information:**
The tests pass properly when running in headless mode. The main purpose of using headless mode is in an attempt to debug a test that is failing. Following guidelines found here:
https://github.com/GoogleChrome/puppeteer#debugging-tips

**Comment by pr3tori4n** [comment]
Also, it doesn't seem like the page.setContent provided by Stencil supports the options for when to consider done. https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-pagesetcontenthtml-options.
This may help certain scenarios.

**Comment by pr3tori4n** [comment]
Some extra info. If instead of await, I add a catch to the page.setContent promise, and log the error, I get this.
`TypeError: page._e2eGoto is not a function
          at e2eSetContent (C:\projects\esri\calcite-app-components\node_modules\@stencil\core\dist\testing\index.js:39000:28)
          at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by pr3tori4n** [comment]
Seems related. When I change the `waitUntil` option to 'load' on this line, things start working.
https://github.com/ionic-team/stencil/blob/f9a323ff6ed626032ee514acd8c9a360fc4887b1/src/testing/puppeteer/puppeteer-page.ts#L123
https://github.com/GoogleChrome/puppeteer/issues/2055

**Comment by pr3tori4n** [comment]
Found the issue. It was a missing await keyword. Closing

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
