### ISSUE TITLE
Implementation of element binding as in SvelteJS?

### ISSUE THREAD

**Issue by lcswillems** [ionic-team/stencil#1622]
Hi,

Do you plan to implement element binding as in SvelteJS?
https://svelte.dev/docs#Element_bindings

This is really convenient.

Thank you,
Lucas Willems

**Comment by manucorporat** [comment]
No, stencil pretends to limit itself to standard communication patterns, properties, attributes and dom events. It's out of scope to create a "stencil" way of communication, since it will not work outside stencil and probably not future-proof
