### ISSUE TITLE
Expose ShadowDOM properties

### ISSUE THREAD

**Issue by romulocintra** [ionic-team/stencil#1623]
**Stencil version:**

```
 @stencil/core@all
```

**I'm submitting a:**

[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Actually, in stencil component, you are able to set  

```js

@Component({
  tag: 'todo-list',
  styleUrl: 'todo-list.css',
  shadow : true / false 
})
```
**Expected behavior:**

I should able to control the ShadowDOM properties, exposing the same API as WC's to set `open` or `close` and in future DelegateFocus etc ... 

```js

@Component({
  tag: 'todo-list',
  styleUrl: 'todo-list.css',
  shadow : { mode : 'closed'  delegatesFocus : true } 
```

**Comment by kneyugn** [comment]
It has been a challenge trying to implement accessible components with focus events. A lot of times, the element that needs to trigger the focus is inside of the shadow dom and not the host element. Exposing delegatesFocus will be very helpful.

**Comment by romulocintra** [comment]
Another good reason

https://github.com/whatwg/html/pull/4796

**Comment by romulocintra** [comment]
Thir PR still open https://github.com/ionic-team/stencil/pull/1190

**Comment by adamdbradley** [comment]
Featured added in https://github.com/ionic-team/stencil/commit/ad94fd255e113d520b68ff4d06b1c938ba8f8ead
