### ISSUE TITLE
Update HTML attributes

### ISSUE THREAD

**Issue by lcswillems** [ionic-team/stencil#1624]
Hi,

I have a web component `my-component` with one property `a`. For example:

```
<my-component a="test"></my-component>
```

When I update the property `a` in the component class, I would like to have its value updated in the HTML code. How could I do that?

Thank you,
Lucas Willems

**Comment by romulocintra** [comment]
Just have a look at this example : 

https://stenciljs.com/docs/component-lifecycle#example

I believe that has all the things you asked for  👍

**Comment by LalitKushwah** [comment]
@lcswillems You have to use 'reflect' in meta data while declaring component

**Comment by lcswillems** [comment]
Thank you @romulocintra  and @LalitKushwah, this solves my issue!

Precisely, I found the answer here: https://stenciljs.com/docs/properties#reflect-properties-values-to-attributes
