### ISSUE TITLE
Click outside event

### ISSUE THREAD

**Issue by lcswillems** [ionic-team/stencil#1627]
Hi,

Does a "click outside" event exist for a component?

**Comment by donskov** [comment]
@lcswillems There are several options to make a click from the documentation:
1. https://stenciljs.com/docs/templating-jsx#handling-user-input
```jsx
export class MyComponent {
  handleClick(event: UIEvent) {
    alert('Received the button click!');
  }

  render() {
    return (
      <button onClick={ (event: UIEvent) => this.handleClick(event)}>Click Me!</button>
    );
  }
}
```

2. https://stenciljs.com/docs/events#target
```jsx
...
@Listen('click', { target: 'window' })
handleScroll(ev) {
  console.log('the body was clicked', ev);
}
```

3. https://stenciljs.com/docs/component-lifecycle
```jsx
...
export class MyComponent {
  componentDidLoad() {
    document.addEventListener('click', this.handleClick.bind(this));
  }

  handleClick(event: UIEvent) {
    alert('Received the document click!');
  }
}
```

I think this will help you.

**Comment by lcswillems** [comment]
Thank you for this fast answer! I will try them later today.

**Comment by donskov** [comment]
@lcswillems I think I don't understand well what you mean. Can you write some code example?

**Comment by lcswillems** [comment]
Something like:

```
<div onClickOutside={(e) => this.myCallback(e)}></div>
```

that will call `this.myCallback` when the user clicked out of the `div`. But I assume I should create my own `div` component maybe?

**Comment by donskov** [comment]
@lcswillems I didn't use but you can try - https://medium.com/@pitipatdop/little-neat-trick-to-capture-click-outside-react-component-5604830beb7f

**Comment by lcswillems** [comment]
Thank you for all the help! And the great tool you are developing :)

**Comment by donskov** [comment]
@lcswillems Not at all. I am not stencil developer)

**Comment by lcswillems** [comment]
Okay haha, thank you for the help anyway!

**Comment by filipe-torres** [comment]
Searching for a native stencil solution for click outside component I found this:
https://github.com/jarrvis/stencil-click-outside
I did use and works like a charm.

**Comment by splitinfinities** [comment]
Reopening as I believe this deserves better documentation.

**Comment by gkhan205** [comment]
> The following works for me:
> 
> ```ts
> // import {Listen, Element} from '@stencil/core';
> 
> @Element() el: HTMLElement;
> 
> @Listen('click', { target: 'window' })
> checkForClickOutside(ev) {
>   if (ev.path.some((el) => el === this.el)) {
>     return;
>   }
>   // If the click was outside the current component, do the following
>   console.log('Wasn\'t me');
> }
> ```

I was also looking for the same and your solution worked for me. I tried almost everything before, event listeners, stencil-click-outside library etc but none of them worked. 

Thanks a lot. :)

**Comment by mariohamann** [comment]
Hey @gkhan205 (and maybe @donskov) ,

I realised, that path isn't available in every browser. If you test e. g. in FireFox or Safari, it doesn't work.

I updated my code to the following:

```ts
// import {Listen, Element} from '@stencil/core';

@Element() el: HTMLElement;

@Listen('click', { target: 'window' })
checkForClickOutside(ev) {
  if (this.el.contains(ev.target)) {
    // If click was inside, stop here
    return;
  }
  // If the click was outside the current component, do the following
  console.log('Wasn\'t me');
}
```

Dpeending on the use case you could use onBlur-events as well: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/blur

**Comment by gkhan205** [comment]
> 

Thanks a lot for sharing your findings and solution. :)

**Comment by donskov** [comment]
@mariohamann You are the best. Thanks!
