### ISSUE TITLE
Convert a component into another

### ISSUE THREAD

**Issue by lcswillems** [ionic-team/stencil#1628]
Hi,

I have 2 components `my-cp1` and `my-cp2` and I would like `my-cp1` to be able to replace itself by `my-cp2`. Currently, I know how to nest `my-cp2` in `my-cp1` but not how to replace it.

Thank you

**Comment by manucorporat** [comment]
It's just the DOM you can write DOM code, for a component to remove itself and append a new one https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement

Github issues are for actual issues, not support. Please use the stencil slack for that.

**Comment by lcswillems** [comment]
Thank you!
