### ISSUE TITLE
No TSLint?

### ISSUE THREAD

**Issue by bfmatei** [ionic-team/stencil#163]
**Stencil version:**
```
@stencil/core@0.0.5-23
```

**I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
No ability to lint the TypeScript files while building.

**Expected behavior:**
It would be nice to be able to lint the .ts/.tsx files using TSLint when compiling the app. Even though you can manually run the lint before running the build, this is not quite a desired approach as you may want the linter to work when watching the files also.

**Comment by adamdbradley** [comment]
This is something we're debating, but honestly do not want to add custom 3rd party libraries into the compiler. We're still kicking around a few ideas for external processes to be notified when a file change has happened. In the meantime I would say to let your editor (I personally recommend VS Code) to do the linting for you.
