### ISSUE TITLE
How to prerender components?

### ISSUE THREAD

**Issue by lcswillems** [ionic-team/stencil#1630]
Hi,

I have this HTML code:

```
<my-cp1></my-cp1>
<my-cp2></my-cp2>
```

`my-cp1` and `my-cp2` are components defined in Stencil.

And I would like to prerender it? How could I do?

**Comment by ctestama** [comment]
We're trying to do something similar actually. It looks like prerendering might only work if you have an SPA set up with stencil-router?  I can get the default index.html (with the js <style> tags) to prerender, but can't seem to get it to follow a link to render another template, or render a single component without having it insert the <script> tags.

What we'd like to do, or to request, is to prerender a single component to a template, which would be able to be included and hydrated anywhere, regardless of whether it's part of an SPA or not. Does anyone know if that's possible?

**Comment by directionsForHal** [comment]
Bumping above. Does anyone know if that's possible? Docs seem sparse IMHO.

**Comment by lcswillems** [comment]
Yes, the doc on this topic is not very comprehensible.
