### ISSUE TITLE
JSXBase not exported from @stencil/core.

### ISSUE THREAD

**Issue by ckrack** [ionic-team/stencil#1632]
Since the move of `HTMLAttributes` to `JSXBase` was documented in `BREAKING_CHANGES.md`, there's one further bug.
`JSXBase` ist not exported by `@stencil/core` but `@stencil/core/internal`.
```diff
- import { JSXBase } from '@stencil/core';
+ import { JSXBase } from '@stencil/core/internal';
```
This should be documented or the export should be added.

**Stencil version:**
```
@stencil/core@1.0.2
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Comment by manucorporat** [comment]
You should never import JSXBase, this is by design a private API.

What's your use case?

**Comment by ckrack** [comment]
Hi @manucorporat, it's described in the [migration/breaking changes document](https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md#removed-global-htmlattributes)
I'm using `HTMLAttributes` type and this is supposed to be part of `JSXBase`:
> Now HTMLAttributes is part of JSXBase, exposed in @stencil/core:

**Comment by brion-fuller** [comment]
I have this same issue.  I have a lazy loaded component that has a placeholder property that takes an stencil component.
```jsx 
<lazy-component
            placeholder={<p>Loading</p>}
          />
```
```jsx
@Component({
  tag: "lazy-component"
})
export class LazyComponent {
  @Prop() placeholder: JSXBase.IntrinsicElements;

  render() {
    if(Status.Loading){
        return this.placeholder;
    }
    return <p>Component</p>
  }
}

```

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
