### ISSUE TITLE
Update page.setContent to accept all options Pupppeteer accepts

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#1633]
**Stencil version:**
```
 @stencil/core@1.0.0
```

**I'm submitting a:**
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Requested Feature**
The setContent method on Stencil's wrapper around the Puppeteer API should also accept overrides for the options object, specifically for `waitUntil`.

**Related code:**

```ts
//Expected to work in an end2end test
await page.setContent(`<foo-bar></foo-bar>`, { waitUntil: 'load' })
```

**Other information:**
- Puppeteer's API for page.setContent accepts a second options argument, the main purpose is to configure the `waitUntil` to change the behavior for when the promise should resolve after content has been added to the page.
- Currently this is hardcoded to `networkIdle0`. https://github.com/ionic-team/stencil/blob/f9a323ff6ed626032ee514acd8c9a360fc4887b1/src/testing/puppeteer/puppeteer-page.ts#L123
- There's a bug when using networkIdle0 when headless mode is disabled for puppeteer. #1621

**Comment by manucorporat** [comment]
Could try try to make a PR?

**Comment by pr3tori4n** [comment]
I believe this has been fixed with this change:
https://github.com/ionic-team/stencil/commit/62839d8e81c1d68bbc177ff35c4f1dd03cad8496#diff-48f1f03cd5c6791c397f1ce962aef19a

Closing.
