### ISSUE TITLE
Overriding setupTestFrameworkScriptFile Jest Config breaks the tests

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#1634]
**Stencil version:**
```
 @stencil/core@1.0.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Tests error when the stencil config contains an override for Jest v23 config option `setupTestFrameworkScriptFile`.
![image](https://user-images.githubusercontent.com/12614215/59381227-ccb5c080-8d0f-11e9-99cb-6e55043635fd.png)

**Expected behavior:**
A setup file can be supplied and runs properly, and the tests run properly.

**Steps to reproduce:**
1. Create a test setup file at `src/tests/setup.js`.
1. Add a new relative file path for setupTestFrameworkScriptFile in stencil.config.ts (Example below) pointing to this file.
1. $ npm test

**Related code:**

```ts
// stencil.config.ts
export const config: Config = {
  testing: {
    setupTestFrameworkScriptFile: "../src/tests/setup.js"
  }
}
```

### Other information
**Suggested Fix** 
Update to Jest v24. Jest v24 replaces `setupTestFrameworkScriptFile` config option with [setupFilesAfterEnv](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array), which accepts an array. Then. it would be easy to concat an array defined by Stencil as well as a user-defined array.

**Diagnosis**
The tests rely on [this internal jest setup file](https://github.com/ionic-team/stencil/blob/master/src/testing/jest/jest-setup-test-framework.ts). Attempts to alter that file will cause the tests to error. 

**Workaround**
You can include the Stencil Jest Setup manually in the newly created setup file and run the function, and follow that with additional setup code.
NOTE: If this workaround could be doc'd, that would be helpful until a better fix is available.

```js
// src/test/setup.js
const { jestSetupTestFramework } = require('@stencil/core/dist/testing');
jestSetupTestFramework();
// ...more setup
```

**Comment by manucorporat** [comment]
Latest stencil already uses jest 24 and uses setupFilesAfterEnv https://github.com/ionic-team/stencil/pull/1545/files

**Comment by pr3tori4n** [comment]
Tried updating and using setupFilesAfterEnv. It still errors without the workaround. This time the error is:
![image](https://user-images.githubusercontent.com/12614215/59700310-edff2c80-91a7-11e9-8ba5-28f6e7894ae9.png)


Workaround is at least more straightforward, but I'd still expect Stencil to handle an array concatenation if there's a mandatory script needed for this option.
```testing: {
    setupFilesAfterEnv: ['<rootDir>/node_modules/@stencil/core/dist/testing', '<rootDir>src/setup.js']
  }```

**Comment by pr3tori4n** [comment]
This is now (and probably has been for some time) working as expected. Closing.
