### ISSUE TITLE
[1.0.1] Cannot import from es6-tween npm module (worked in 1.0.0)

### ISSUE THREAD

**Issue by Matthew-Smith** [ionic-team/stencil#1637]
**Stencil version:**

```
 @stencil/core@1.0.1
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

We use [es6-tween](https://www.npmjs.com/package/es6-tween) in our project and importing from it broke when we tried to upgraded from 1.0.0 to 1.0.1 (also tried 1.0.2 and 1.0.3)

This is the error is reported when we try compiling:

```
[ ERROR ]  Rollup: Missing Export: src/components/visual/repl-graph/lazy_kiceaumtpiujvuzscftlmg-repl-graph.js:18:9
           'autoPlay' is not exported by node_modules/es6-tween/bundled/Tween.min.js

      L0:  16:     return c > 3 && r && Object.defineProperty(target, key, r), r;
      L0:  17: };
      L0:  18: import { autoPlay, Easing, Tween } from 'es6-tween';
      L0:               ^
      L0:  19: import joint from 'rappid';
      L0:  20: import { debounce } from 'typescript-debounce-decorator';
```

**Expected behavior:**

Expect that the code compiles properly.

**Steps to reproduce:**

In a new stencil project:
```shell
npm install --save es6-tween
```
Then in `app-root.tsx` add the following:
```tsx
import * as es6Tween from 'es6-tween';

es6Tween.autoPlay(true);
```

**Comment by Matthew-Smith** [comment]
confirmed still an issue in 1.0.4

**Comment by emilio-martinez** [comment]
This issue may be related to 'es6-tween' not being resolved to the ES modules distribution.

**Comment by Matthew-Smith** [comment]
@emilio-martinez I'm not sure I follow, I looked at [rollup package module](https://github.com/rollup/rollup/wiki/pkg.module) docs and the es6-tween `package.json` seems to specify the modle (along with other entry points properly:
```
  "browser": "bundled/Tween.min.js",
  "cdn": "bundled/Tween.min.js",
  "main": "bundled/Tween.js",
  "module": "src/index.js",
```

Is there something I should try adding or removing from the es6-tween `package.json`?

**Comment by Matthew-Smith** [comment]
Confirmed this is still an issue in 1.1.0.

@emilio-martinez was there any ideas on how to force es6-tween to be resolved to ES modules?

**Comment by Matthew-Smith** [comment]
Confirmed still an issue in 1.1.5

**Comment by Matthew-Smith** [comment]
Confirmed still an issue in 1.1.7

**Comment by Matthew-Smith** [comment]
Confirmed still an issue in 1.2.1

**Comment by apillard** [comment]
Try adding es6-tween to your named exports in stencil.config.ts

https://stenciljs.com/docs/module-bundling#namedmodules-x-is-not-exported-by-x

**Comment by Matthew-Smith** [comment]
Thanks @apillard, that worked!

I had to specify the named export very specifically because I think there is some pre-processing on the export directory so the final addition to the config was this:
```
export const config: Config = {
  commonjs: {
    namedExports: {
      'node_modules/es6-tween/bundled/Tween.min.js': ['autoPlay', 'Easing', 'Tween']
    }
  },
   ...
}
```

@manucorporat @adamdbradley is this an expected named export resolution? If so the docs should probably be updated to better reflect how that works instead of claiming to be able to just specify it like this:
```
...
    namedExports: {
      'es6-tween': ['autoPlay', 'Easing', 'Tween']
    }
...
```

But for now this has resolved this issue for me!
