### ISSUE TITLE
[1.12.2] Best Practice on theming IE with custom vars [works]

### ISSUE THREAD

**Issue by stanley85** [ionic-team/stencil#1638]
```
 @stencil/core@1.0.3
```

**I'm submitting a:**
[x] bug report
[x] feature request
[] support request

**Current behavior:**
We are building a main component having content seperated in child components. We had some issues with IE that finally could be resolved following some priciples. 
- having shadow dom disabled seems to cause issues: https://github.com/ionic-team/stencil/issues/1617

Because of this for now all our components have shadow-dom enabled. 
- the declaration of custom vars needs to be done inside each component, to have IE recognize the colors translated by the compiler. 

We use an scss @import of a file containing :host selector and the custom vars inside, this causes chrome and firefox to have massive redundancy in custom vars
- custom vars declared in a globalStyle scss file are not used on compile time to fix IE
- also applies to sass's injectGlobalPaths vars declared
-- this is another reason styles could not be stored somewhere global

What we are finally are trying to achive is having a easy way to theme the application with custom vars in cetralized place. This is easy with classes in chrome and firefox since they keep the declaration and know how to inherit them. For IE switching vars is not that easy. It would require us to have all diffrent themes stored somewhere precompiled. And not only containing a new set of custom vars but all of the compiled css using that set of vars.

**Expected behavior:**
Custom vars should be inherited during build (fix IE) time even with shadow dom enabled, so that the default inheritance the browser does inside the shadow-dom is also applied in the color fix. This would allow to have the color import in the main file and the extra import in every child is no longer needed.

**Feature request:**
The use of custom vars should be the way to go for any upcoming style requirements. Theming for IE is quite a hassle and an easy way to configure different sets of colors would be nice. We did several approches with dynamically loading custom vars from an external source, but this is not possible for IE since all linkage from the vars is gone. Overwriting vars by class does the trick for modern brwosers, but for IE there must be some prerender in place with different sets of scss and some magic to load the style on a property change or some other call.

**Best practice?**
Am I near a good solution to apply theming to this case? At the moment all colors are working for IE and chrome but changing them and keep them organized gives me headaches with all the restrictions I stumble upon. How is ionic handling theme changes in IE?

**Comment by stanley85** [comment]
We found a solution to apply theming to IE11 with sass, its a bit confusing at first but all css-vars are dynamically generated to enable different styles beforehand. Those styles can be switched later, because stencil already composed an IE11 variant of the given styles... here is what we did. I hope you can use it to your benefit.

**Create scss config file**
All CSS values that may vary between different themes / brands are not stored as single scss-var or css-custom-var but scss Map. This could look like this:

```
$themes: (
  default: (
    border-radius: (
      none: 0,
      sharp: 0.1rem,
      default: 0.3rem,
      round: 50%
    ),
    color: (
      primary: rgb(222, 33, 44)
    )
  ),
  brandtwo: (
    border-radius: (
      none: 0,
      sharp: 0.1rem,
      default: 0.3rem,
      round: 50%
    ),
    color: (
      primary: rgb(222, 33, 44)
    )
  )
) !default;
```

**Create ability to read the map**
Create the following inside a different file and add it to the "injectGlobalPaths" array of the sass plugin.

Your plugin section of stencil.config.ts may look like this

```
plugins: [
  sass({
    injectGlobalPaths: [
      'src/styles/theme-helper.scss',
      'src/styles/themes.scss'
    ]
  })
]
```

To read the config and apply custom vars in the right places during compile we need to address the value first. We went for a dotted approach to resemble the path to the value. This path is then splitted on dot and translated to its value. 

```
@function nested-get($map, $keysString) {
  $keys: str-split($keysString, ".");
  $value: $map;
  $path: "mapRoot";

  @each $key in $keys {
    $path: $path + "." + $key;

    @if (map-has-key($value, $key)) {
      $value: map-get($value, $key);
    } @else {
      @error "The map does not contain the key `#{$key}` at path `#{$path}`. Check if the key is present. If it is, this error might happen because you are using a reserved keyword, like a color name. Try to change your map key to a string, e.g.: (red : #ff0000) -> (\"red\" : #ff0000)";
    }
  }

  @return $value;
}

@function str-split($string, $separator) {
  $split-arr: ();
  $index: str-index($string, $separator);

  @while $index != null {
    $item: str-slice($string, 1, $index - 1);
    $split-arr: append($split-arr, $item);
    $string: str-slice($string, $index + 1);
    $index: str-index($string, $separator);
  }

  $split-arr: append($split-arr, $string);

  @return $split-arr;
}
```

**Create variable name based on path**
To have css-custom-vars dynamically created we used the path to create them.
```"brandone.color.primary" becomes "--brandone-color-primary"```

```
@function convert-to-css-variable-name($keysString) {
  $keys: str-split(inspect($keysString), ".");
  $length: length($keys);

  $value: "";
  @each $key in $keys {
    $value: $value + $key;
    @if ($length != index($keys, $key)) {
      $value: $value + "-";
    }
  }

  // replace quote symbol
  @return --#{str-replace($value, '\"', '')};
}

@function str-replace($string, $search, $replace: '') {
  $index: str-index($string, $search);

  @if $index {
    @return str-slice($string, 1, $index - 1) + $replace + str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
  }

  @return $string;
}
```

**Initially create all scc-vars per brand**
To have a basic rundown through the config and create all variables we did the following

```
@mixin generateCssVariables($theme, $prefix: "") {
  @each $variable, $value in $theme {
    @if (type-of($value) == "map") {
      @include generateCssVariables($value, $prefix + $variable + "-");
    } @else {
      --#{$prefix + $variable}: #{$value};
    }
  }
}
```

Inside the config file that houses the Map call this mixin for each brand
The pre-selector with brand is the mission critical part to have the vars separated and available to use

```
[brand="default"] {
  @include generateCssVariables(map-get($map: $themes, $key: default));
}

[brand="brandtwo"] {
  @include generateCssVariables(map-get($map: $themes, $key: brandtwo));
}
```

**Create the nested mixin**
To apply the theming to any css-selector we then created a mixin that translates the given keys to all styles needed. So if you like to have theming applied to an attribute e.g. border-radius you would call the mixin with "border-radius" and "border-radius.round" all brand related code generates. Create the mixin inside the global helper registered to your plugin.

```
@mixin useThemes($styles) {
  @each $cssProperty, $variableName in $styles {
    #{$cssProperty}: var(#{convert-to-css-variable-name($variableName)}, nested-get($themes, "default." + $variableName));
  }
  @at-root {
    @each $brand, $theme in $themes {
      $selectors: str-split(#{&}, ",");
      @each $selector in $selectors {
        [brand="#{$brand}"] #{$selector} {
          @each $cssProperty, $variableName in $styles {
            #{$cssProperty}: nested-get($themes, $brand + "." + $variableName);
          }
        }
      }
    }
  }
}

@mixin useTheme($cssPropertyOrStylesMap, $variableName: null) {
  @if (type-of($cssPropertyOrStylesMap) == "map") {
    @include useThemes($cssPropertyOrStylesMap);
  } @else {
    @if ($variableName == null) {
      @error "you must provide either a map (cssProperty : variableName) as the first argument or a propertyName as the first and a variableName as the second argument";
    }
    @include useThemes(($cssPropertyOrStylesMap: $variableName));
  }
}
```

A basic use would be like this - as you can see the mixin is called with a Map, this allows to have several attributes translated at once, like in the second example. The default style is directly applied to the element. Each pre-selector code is then added for each brand. 

```
:host {
  @include useTheme((
      background-color: "color.shade-light"
  ));
}

:host {
  @include useTheme((
      background-color: "color.shade-light",
      color: "color.primary",
      border-radius: "border-radius."
  ));
}
```

What do you think about this approach?

**Comment by stanley85** [comment]
I did not close this in order to provide an idea on how to enable theming on a shadow-dom context for IE11. The main component needs the brand prop in this example. Maybe any of this logic serves a new version of stencil-sass or tension to create something similar in the core but way more usable...

**Comment by AnonymousArthur** [comment]
Thank you

**Comment by stanley85** [comment]
You are welcome - glad it helped - we are still using this exact approach with the latest version (1.6.1)

**Comment by vinothbabu** [comment]
@stanley85 : Do you have any sample repo to look at how you are applying theming to stencilJs?

**Comment by stanley85** [comment]
@vinothbabu Just did that - working with version 1.12.2 https://github.com/stanley85/stencil-theming-starter
