### ISSUE TITLE
Consider Monorepo

### ISSUE THREAD

**Issue by mitchellsimoens** [ionic-team/stencil#164]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.4
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Description:**
Have you thought about using a monorepo instead of separate repos per module? For example, instead of a separate `ionic-team/stencil`, `ionic-team/stencil-dev-server`, `ionic-team/stencil-router` repos, you would just have `ionic-team/stencil` and all those modules living under `packages`. This is how [babel](https://github.com/babel/babel) does it and I have found it scales much better plus keeps development in sync with each other. Also, your tests can either be individual or together so if you make a change in the `@stencil/core` module, you can run tests for the router.

It's not much of an issue now since you only have a couple real modules but you also have a couple starter apps/boilerplates that could be merged in the `packages` so they can use the latest in the git branch also making development better for people working on it.

For my current job, I had 32 different modules and once I merged into a monorepo development was so much easier and safer. Plus, using a tool like [lerna](https://www.npmjs.com/package/lerna), it's easy to bootstrap everything (seriously, it's one command `npm bootstrap`) and you can even do this from `package.json` in a `postinstall` script:

    scripts: {
        "postinstall": "lerna bootstrap"
    }

So now all you have to do is run `npm install` in the root directory and you are good to go. I highly recommend it since there is a possibility of getting out of sync and adding more modules.

**Comment by mitchellsimoens** [comment]
Also note, I'd be willing to work on this altho it'd mean moving lots around. As another example, the modules I have for my current job can be seen [here](https://github.com/mitchellsimoens/sencha_node_modules).

**Comment by adamdbradley** [comment]
I put more thought into this and decided to not make it a mono repo. The other components such as our router should stay stand alone and easy to understand. Additionally we do not see many more core packages needed to be added to stencil. Thanks
