### ISSUE TITLE
[feature request] dynamic component

### ISSUE THREAD

**Issue by dingxin** [ionic-team/stencil#1640]
A dynamic component is needed to render components dynamically, so that we can pass the tag name of a component as a variable.

for example:
```tsx
<my-comp name="hello" value="100" />
```
equal to
```tsx
<Comp component="my-comp" name="hello" value="100" />
```
just like in VUE
```tsx
<component v-bind:is="my-comp"></component>
```

**Comment by ckrack** [comment]
You can use a const to define the tag name.

```typescript
const CompTag: string = 'my-comp';

return <CompTag>foo</CompTag>;
```

**Comment by manucorporat** [comment]
@ckrack is right, this can be done already with JSX.

**Comment by dingxin** [comment]
> You can use a const to define the tag name.
> 
> ```ts
> const CompTag: string = 'my-comp';
> 
> return <CompTag>foo</CompTag>;
> ```

I know it can be done by this way, but it's not convenient, especially in loops, you have to define a function to implement this. A built-in tag maybe more convenient.
