### ISSUE TITLE
Self-closing elements

### ISSUE THREAD

**Issue by lcswillems** [ionic-team/stencil#1643]
Hi,

I would like to do a component like:

```
<my-cp />
```

Is it possible?

**Comment by manucorporat** [comment]
In JSX it’s possible, but in HTML is not. https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements

We want to keep github issues for actual issue, not support or questions. Fortunately there is a very friendly community in slack: https://stencil-worldwide.herokuapp.com/

**Comment by lcswillems** [comment]
Okay thank you for your answer.

I will post in your Slack in the future. But for you, I don't think it is the best strategy because people will ask over and over the same questions in the Slack because of the lack of Google indexation.
