### ISSUE TITLE
Classes for slotted elements are not added in IE and Edge.

### ISSUE THREAD

**Issue by GeorgeTailor** [ionic-team/stencil#1645]
**Stencil version:**
```
 @stencil/core@1.0.0-beta.8
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
In IE and Edge classes to slotted elements are not added.
In this case this is slotted `<select>` element.
**Expected behavior:**
Classes to slotted elements should be added.

**Steps to reproduce:**
`git clone https://github.com/zooplus/zoo-components`
`npm run start-prod`
Open IE or Edge and look at elements with labels `Searchable multiple select` and `Searchable select`. In Firefox and Chrome selects are hidden, while in IE and Edge they are not.
**Related code:**

```tsx
export class ZooSearchableSelect {
...
	@Element() host: HTMLElement;
	slottedSelect: HTMLSelectElement;
...
	componentDidLoad() {
		let slotted = this.host.children;
		const select = (Array.from(slotted).find(el => el.nodeName === 'SELECT') as any);
		this.slottedSelect = select;
		...
		this.hideSelectOptions();
		...
	}
	hideSelectOptions() {
		this.slottedSelect.classList.add('hidden');
	}
...
}
```

I guess the problematic part for polyfills is 
```
let slotted = this.host.children;
const select = (Array.from(slotted).find(el => el.nodeName === 'SELECT') as any);
```
Can this be fixed on Stencil side or is there any other way of adding classes to slotted elements in browsers that require polyfills?

Similar behaviour can be seen for `button`. At the top element with label `Input type text` the `<input/>` elements should have `.error` class added. But it is not added.

**Comment by manucorporat** [comment]
As you pointed out, in IE11 there is not native shadow-dom, so the direct children of host are the nodes you render in your render function. You can use querySelector() to find them. Or move this code:
```
		const select = (Array.from(slotted).find(el => el.nodeName === 'SELECT') as any);
		this.slottedSelect = select;
```
to componentWillLoad, which happens before the render funcion is executed.
