### ISSUE TITLE
Array passed as property is not reflected in markup in IE.

### ISSUE THREAD

**Issue by GeorgeTailor** [ionic-team/stencil#1646]
**Stencil version:**
```
 @stencil/core@ 1.0.4
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Assignment of element's property is ignored in IE. Array elements are not rendered inside component.

**Expected behavior:**
Property assignment should be reflected in component's markup.

**Steps to reproduce:**
`git clone https://github.com/zooplus/zoo-components`
`npm run start-prod`
Open IE and observe that at the bottom of the page `<zoo-footer>` element does not render elements according to passed property.

**Related code:**
For setting the property:
```
	<script>
		window.addEventListener('load', function() {
			document.getElementById('zoo-footer').links = [
				{
					href: 'https://github.com/zooplus/zoo-web-components',
					text: 'Github',
					type: 'standard'
				}
			];
		});
	</script>
```
The `zoo-footer` itself:
```tsx
export class ZooFooter {
	@Prop({ reflect: true }) links = [];

	render() {
		return ([
			<div class="footer-links">
				<div class="list-holder">
					<ul>
						{this.links.map((link) => 
							<li>
								<zoo-link href={link.href} target={link.target} type={link.type}
								disabled={link.disabled} text={link.text}>
								</zoo-link>
							</li>
						)}
					</ul>
				</div>
			</div>
		])
	}
}
```

**Other information:**
It works OK in Edge, Firefox and Chrome.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
