### ISSUE TITLE
stencil build --prod --watch --serve throws error

### ISSUE THREAD

**Issue by GeorgeTailor** [ionic-team/stencil#1647]
**Stencil version:**
```
 @stencil/core@ 1.0.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
`stencil build --prod --watch --serve` throws error in console 
```
[ ERROR ]  Package Json: ./package.json:17:3
           package.json "types" property is set to "dist/types/index.d.ts" but cannot be found. It's recommended to set
           the "types" property to: dist/types/components.d.ts

     L17:    "types": "dist/types/index.d.ts",
```

**Expected behavior:**
No errors are thrown when running prod build.

**Steps to reproduce:**
`git clone https://github.com/zooplus/zoo-components`
`npm run start-prod`
Observe error in console.

**Related code:**
`package.json`
```
  "scripts": {
    "start-prod": "stencil build --prod --watch --serve"
  },
```

**Other information:**
Removing `"types": "dist/types/index.d.ts",` from `package.json` seems to help.

**Comment by manucorporat** [comment]
I can't reproduce, adding
```
  "types": "dist/types/index.d.ts",
```
works fine
