### ISSUE TITLE
Sourcemaps for node and browser

### ISSUE THREAD

**Issue by pittst3r** [ionic-team/stencil#1650]
**Stencil version:**

```
@stencil/core@1.0.3
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
There are no sourcemaps available for either the browser code or the node code. This makes debugging tests and components very difficult.

**Expected behavior:**
There should be sourcemaps available in all environments (test, dev, prod).

**Steps to reproduce:**
1. Create a new stencil component library with the starter project
2. Build or test component library
3. Observe that there are no sourcemaps

**Comment by petermikitsh** [comment]
Source maps are now on the fall roadmap! https://stenciljs.com/blog/stencil-roadmap-fall-2019

**Comment by sajTempler** [comment]
similar to #1744

**Comment by manucorporat** [comment]
Closing as duplicated, it's complicated but we are closer than ever, we are relaying more on TS and rollup than manual code modification
