### ISSUE TITLE
componentDidUpdate() is called before dom finished updating

### ISSUE THREAD

**Issue by ficoos** [ionic-team/stencil#1651]
**Stencil version:**

```
 @stencil/core@1.0.4
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

the callback `componentDidUpdate()` is called after the render command has been called but before the actual dom updates have taken place. This means that I can't do any operations that use any of the elements generated in the current render.

Specifically, instead of the frantic jittery update of the dom I would like to render to a `hidden=true` parent and change it to true when all the dom changes have taken place.

The current scheme of updating the dom little by little (and having no control over hiding the update) makes the application unusable as things keep shifting until all the dom updates are finished.

**Expected behavior:**

componentDidUpdate() is called after the component actually finished updating not when the update is queued.
**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by manucorporat** [comment]
This should be fixed
