### ISSUE TITLE
Screenshot testing compare.html not displaying

### ISSUE THREAD

**Issue by rainzhao2000** [ionic-team/stencil#1652]
**Stencil version:**

```
 @stencil/core@1.0.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The compare.html file in the screenshot folder generated by screenshot puppeteer tests is not displaying in the browser properly.

**Expected behavior:**

It is supposed to give graphical comparisons of screenshot differences in tests.

**Steps to reproduce:**

Sometime ago, the compare.html worked as intended, though not without its own bugs at the time. After upgrading from stencil v0.18 to v1.0.2, and running my tests to generate a screenshot folder, the compare.html file when opened in a browser displays raw text of screenshot descriptions, id, etc.

**Related code:**
![Untitled](https://user-images.githubusercontent.com/20288284/59624906-00c12500-9106-11e9-9146-fe15fd856ddd.png)

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by mmakrzem** [comment]
same problem with @stencil/core@1.0.6

**Comment by Rafael-Leal** [comment]
unsure if this is the same problem that you and me have, but i also created an issue https://github.com/ionic-team/stencil/issues/1704 with some errors that happened for me and a project that also has these issues

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
