### ISSUE TITLE
Dev server does not always render

### ISSUE THREAD

**Issue by Aaron-Sterling** [ionic-team/stencil#1658]
**Stencil version:**

```
 @stencil/core@1.0.6
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I would like to ask you to revisit issue #49 from stencil-component-starter. I am submitting it here, because I'm having the problem with the most recent version of Stencil, and an app that has minor changes to the starter.
The dev server renders sometimes, and sometimes does not. If I use lite-server, the www folder renders fine, under both dev and prod builds. But the Stencil dev server worked for me yesterday, but did not work two days ago and does not work now.
Windows 10
Tested both in IE11 and Chrome
Node 10.14

The problem is that "localhost didn't send any data" on port 3333, or any other port I've tried to use. I've tried 3000, 4000, 4200, no improvement.

**Expected behavior:**

For the dev server to serve the page.

**Steps to reproduce:**

I don't know what made the difference between yesterday and today. Everything feels the same to me. I initially had the problem with 1.0.1, so I upgraded to 1.0.6, no change.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by klerick** [comment]
try to change dev server port
https://stenciljs.com/docs/dev-server

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
