### ISSUE TITLE
Chrome treats styles as `user agent stylesheet` when `reloadStrategy` = `pageReload`

### ISSUE THREAD

**Issue by flawyte** [ionic-team/stencil#1659]
**Stencil version:**
```
 @stencil/core@1.0.3
```

**I'm submitting a:**
- [x] bug report

**Current behavior:**
When `devServer.reloadStrategy` is set to `pageReload`, the styles applied to custom elements and their children are considered by Chrome as `user agent stylesheet`, which prevents me as a developer to toggle/edit CSS rules in the Chrome DevTools :
![image](https://user-images.githubusercontent.com/1585006/59701931-e7e46c80-91f6-11e9-8314-20a50db9833d.png)

**Expected behavior:**
Elements' styles shouldn't be treated as `user agent stylesheet` but as 'normal' styles :
![image](https://user-images.githubusercontent.com/1585006/59702035-237f3680-91f7-11e9-8bcc-f7a474413b64.png)

**Related code:**

`stencil.config.ts`
```tsx
import { Config } from '@stencil/core';
import { sass } from '@stencil/sass';

export const config: Config = {
  devServer: {
    openBrowser: false,
    reloadStrategy: 'pageReload' // <-- THIS
  },
  globalStyle: 'src/global/app.css',
  globalScript: 'src/global/app.ts',
  outputTargets: [{
    type: 'www',
    serviceWorker: null,
    baseUrl: 'https://myapp.local/'
  }],
  plugins: [
    sass()
  ]
};
```

**Other information:**
- `shadow: false` in all of my components.
- I'm using `@stencil/sass`, so all style files are `.scss` files.

**Comment by dgibson666** [comment]
I noticed this too and was wondering if this was a side effect of Constructed Style Sheets they are using in Chrome now.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
