### ISSUE TITLE
Context.dom.raf is being minified

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#166]
`Context.dom.raf` is probably being minified by Google Closure Compiler, so it can't be used in production build

<img width="703" alt="screen shot 2017-09-20 at 11 46 14" src="https://user-images.githubusercontent.com/127379/30637762-96c0b0ae-9df9-11e7-861a-309d03fb6805.png">

Leading to this crash in production build:
<img width="398" alt="screen shot 2017-09-20 at 11 49 00" src="https://user-images.githubusercontent.com/127379/30637804-b8d0277e-9df9-11e7-84e2-89df96f30fcd.png">

**Comment by adamdbradley** [comment]
Yeah that's probably it, un momento

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil/commit/c7dbab752f4ac8e80b12a9240e99447e1d9a9a85
