### ISSUE TITLE
Does not export anything and no loader/ in dist

### ISSUE THREAD

**Issue by DominicTobias** [ionic-team/stencil#1662]
**Stencil version:**

```
 @stencil/core@1.0.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
- Docs say that for [integrations](https://stenciljs.com/docs/react) we should import `defineCustomElements ` from `dist/loader` but even after `npm run build` (lots of files missing on just `npm start` by the way) there is no `loader` folder in dist, only one outside it:

<img width="225" alt="Screenshot 2019-06-18 at 21 44 34" src="https://user-images.githubusercontent.com/760314/59718886-ffc9e980-9212-11e9-9132-24d608fafecc.png">

- packages "main" entry points to dist/index.js, which points to `./cjs/index.cjs.js` which has nothing in it except `'use strict';`, so that's a no-go too.

**Expected behavior:**
Library should export `defineCustomElements`.

**Steps to reproduce:**
npm init stencil

Note this generated files with v1 beta8, I manually updated to 1.0.4. Haven't done anything special except add the scss plugin and the start of a few custom components.

**Comment by DominicTobias** [comment]
PS I just ran `npm run build` on a completely new project via `npm init stencil` and same result:

![Screenshot 2019-06-19 at 13 48 20](https://user-images.githubusercontent.com/760314/59766869-fc794100-9298-11e9-9d7a-cf4a0ca86fd8.png)

**Comment by glennlawyer** [comment]
Please see https://github.com/ionic-team/stencil/issues/1649 which asks the same question.

Wish we had the answer, this is driving me crazy.

**Comment by DominicTobias** [comment]
Ah thanks I'll have a read
