### ISSUE TITLE
@stencil/router version is incorrectly installed as "one"

### ISSUE THREAD

**Issue by stowball** [ionic-team/stencil#1665]
**Stencil version:**

```
/Users/mattstow/stencil
└── (empty)
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
When you init a new `app` project,`@stencil/router` is added to `dependencies` as version `"one"`. While this works OOTB, as soon as you install another npm module, `router` can longer be found, and you have to `npm i @stencil/router` again.

**Expected behavior:**
When a new `app` is scaffolded, `@stencil/router` should be installed as `1.x`

**Steps to reproduce:**
```sh
npm init stencil

Pick a starter:
-> app
```

**Comment by stowball** [comment]
Looks like this should be logged against https://github.com/ionic-team/stencil-app-starter

**Comment by manucorporat** [comment]
Should be fixed now
