### ISSUE TITLE
Web Component issues on IE11

### ISSUE THREAD

**Issue by pantro14** [ionic-team/stencil#1666]
**Stencil version:**
```
 @stencil/core@1.0.0-beta.8
```

**I'm submitting a:**

[*] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
I created a web container that now is hosted by an angular 7 app. When I run it locally the Web Component (WC) is not displayed and it shows the following error:
![Local Error](https://user-images.githubusercontent.com/3803059/59748596-ba8dd200-927b-11e9-8b26-0772763bd9c2.png)

When the WC is deployed in the container in IE11, a lot of bugs in the console are displayed. 
![IE11 error](https://user-images.githubusercontent.com/3803059/59746505-5cf78680-9277-11e9-9fc6-215d01f5bc62.PNG)

**Expected behavior:**
Display the web component as in the other web browsers.
![chrome](https://user-images.githubusercontent.com/3803059/59746512-6123a400-9277-11e9-8045-beca18d4b4fa.PNG)

**Steps to reproduce:**
The WC works fine in the other browsers, this uses c3.js to render a graph. On internet explorer a lot of bugs are prompted and the application doesn't show the graph at all and doesn't calculate the results.

**Related code:**
Unfortunately the company I work for has its own private bitbucket repositories.

**Other information:**
I have added the following tag to the host app component (web component parent)
```<meta http-equiv="x-ua-compatible" content="IE=Edge"/> ```

**Comment by andreyleonardo** [comment]
Hi @pantro14,

Are you applying all necessary polyfills for IE?

Could you give a look at this #1635 and see if this helps?

**Comment by pantro14** [comment]
@andreyleonardo Thanks for your reply, and sorry for my late reply, I was on holidays.
I've tried to implement polyfills, but in our project we use jenkins pipeline in the conatiner when the script `ng build --prod` some issues pop up:

 ERROR in ./node_modules/cost-calculator-web-component/dist/esm/legacy/loader.mjs 4:8-21
  Can't import the named export 'b' from non EcmaScript module (only default export is available)
 ERROR in ./node_modules/cost-calculator-web-component/dist/esm/legacy/loader.mjs 3:11-19
 Can't import the named export 'c' from non EcmaScript module (only default export is available)
 ERROR in ./node_modules/cost-calculator-web-component/loader/index.mjs 20:0-47
 Can't reexport the namespace object from non EcmaScript module (only default export is available)
  ERROR in ./node_modules/cost-calculator-web-component/dist/esm/legacy/cost-calculator-web-component-2d3f4886.js 138:11
  Module parse failed: Unexpected token (138:11)
  You may need an appropriate loader to handle this file type.
 |     // loadModuleImport
 |     var bundleId = cmpMeta.$lazyBundleIds$;
 >     return import(
 |     /* webpackInclude: /\.entry\.js$/ */
 |     /* webpackExclude: /\.(system|cjs)\.entry\.js$/ */
  ERROR in ./node_modules/cost-calculator-web-component/dist/esm/polyfills/index.js 15:18
  Module parse failed: Unexpected token (15:18)
  You may need an appropriate loader to handle this file type.
 | 
 if (!win.customElements || (win.Element && (!win.Element.prototype.closest || !win.Element.prototype.matches || !win.Element.prototype.remove))) {
     promises.push(import('./dom.js'));
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cost-calculator-component-container@13.0.0 build-prod: `ng build --prod`

Sorry but I'm a bit lost here, if maybe in some integrations with angular you people have spotted this issue and try to fixi it, it'd  be nice to follow.

**Comment by andreyleonardo** [comment]
Hey @pantro14, 

sorry for the late response, did you figured out to solve this?

I would suggest you to follow a comment on the other issue that I sent before, saying that a work around for angular was to use Script tag head to load the WCs instead of es modules.
I don't know if this is an option for you, but have big chances to work because through the script tag head all polyfills are loaded together with no extra import necessity.
You could take the example for this from [Vanilla integration docs](https://stenciljs.com/docs/javascript).

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
