### ISSUE TITLE
Code completion / Intellisense in HTML when using Stencil Components

### ISSUE THREAD

**Issue by dasois** [ionic-team/stencil#1667]
**Stencil version:**

```
 @stencil/core@1.0.2
```

**I'm submitting a:**

[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

There is currently no code completion in HTML when consuming Stencil Components in e.g. a Angular project.

**Expected behavior:**

When consuming my generated stencil component in e.g. a Angular project, I want to have code completion in HTML in order to be able to configure the components (e.g. like in Ionic Components).

**Other information:**

I know that Stencil generates type definitions that helps me to use the components from TypeScript files, but that is not how I want to configure my components. I want to provider parameters via HTML.

**Comment by hypery2k** [comment]
any plans to add this feature? If not would like to help on this issue, Any suggestion where to look for the current loader "defineCustomElements" stuff?

**Comment by manucorporat** [comment]
This is already possible with the angular bindings:
https://github.com/ionic-team/stencil-ds-plugins#stencil-config-setup

and for react too. Stencil can generate an angular library with all type checking that a normal angular application would have, just like ionic
