### ISSUE TITLE
Bug - Unit Tests error if the component being tested imports from node_modules

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#1669]
**Stencil version:**
```
@stencil/core@1.0.6
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Unit Tests error when a component is instantiated in the test file, and the component contains an import statement pointing to an es6 module file in node_modules.
![image](https://user-images.githubusercontent.com/12614215/59796987-80302f00-9293-11e9-8faf-8ae2f116aa1a.png)

**Expected behavior:**
The test file and component file should compile without error and the test should run normally.

**Steps to reproduce:**
1. Create a component. 
1. At the top of that component file add a named import from a npm package, such as something from lodash-es.
1. Create a unit test for that component

**Related code:**

```tsx
// Sample Component File
import { Component, h } from "@stencil/core";
import { get } from "lodash-es";

const strings = {
  text: 'hello world'
};

@Component({
  tag: "hello-world",
  shadow: true
})
export class HelloWorld {
  getText() {
    return get(strings, 'text', 'hello world');
  }
  render() {
    return (
      <p>{this.getText()}</p>
    );
  }
}
```
```.ts
// Sample unit test
import { HelloWorld } from './hello-world';

describe('hello-world', () => {
  it('should render', () => {
    const helloWorld = new HelloWorld();
    expect(helloWorld.getText()).toEqual('hello world');
  })
})

```

**Other information:**
[Related Issue in Jest](https://github.com/facebook/jest/issues/6229) suggests a change in Babel 7 architecture introduced this behavior. A solution is posted in one of the comments.
I tried that solution, but adding a `transformIgnorePattern` option (which excludes the module from being ignored by the Jest transformer) in `stencil.config.js` does not work. https://github.com/facebook/jest/issues/6229#issuecomment-403539460
```.js
transformIgnorePatterns: [ "/node_modules/(?!lodash-es).+\\.js$" ]
```

**Comment by rafehi** [comment]
I'm also running into the same issue. `transformIgnorePattern` doesn't seem to do anything.

**Comment by nikber84** [comment]
Same issue, how to override "transformIgnorePatterns"?

**Comment by KillerCodeMonkey** [comment]
Ugly but it is working:

Instead of ignoring the transform just use the `moduleNameMapper` and replace the esmodule version with the original commonjs version.

babel has lodash as dependency so no additional changes to your package.json is needed.
But if you want to feel save, add `lodash` as dev depenency :).

```TS
import { Config } from '@stencil/core'

// https://stenciljs.com/docs/config

export const config: Config = {
  globalScript: 'src/global/app.ts',
  globalStyle: 'src/global/app.css',
  outputTargets: [
    {
      baseUrl: 'https://myapp.local/',
      // comment the following line to disable service workers in production
      serviceWorker: null,
      type: 'www'
    }
  ],
  testing: {
    moduleNameMapper: {
      '^lodash-es$': 'lodash'
    }
  }
}
```

**Comment by Paitum** [comment]
Same issue. Using third-party libraries within StencilJS components, like lodash-es and date-fns, should be a very common occurrence. I'm confused whether this is a StencilJS problem, a Jest problem, a Node ESM-support problem. It would be nice if the StencilJS documentation could provide some guidance on this, or close this ticket explaining why it's not their issue.
