### ISSUE TITLE
Allow creating custom decorators

### ISSUE THREAD

**Issue by jarrvis** [ionic-team/stencil#1671]
**Stencil version:**

```
 @stencil/core@1.0.6
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Custom decorator that hijacks lifecycle method require that this method is declared in at least one component in bundle. This is because of compiler optimization:
https://github.com/ionic-team/stencil/blob/8c5ae5131b89ecdcef8e79a519ae65a43d8d15ee/src/runtime/update-component.ts#L148

https://github.com/ionic-team/stencil/blob/8ac4ab910017ed837a74451f5263ea31aab20430/src/compiler/app-core/build-conditionals.ts#L8

If lifecycle method is not explicitly declared in the project, it will not be called. Because of this lifecycle methods cannot be added programatically, for instance from decorator. 

**Expected behavior:**
Lifecycle methods can be added from decorator
Compiler should be able to recognize decorator case and which lifecycle method is decorated. Then it should call that specific lifecycle method even if not explicitly defined in none of the components

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by gtranter** [comment]
This is a big problem for us - in our case we hijack `componentDidLoad`. Has anyone found a workaround until this is officially fixed (other than the obvious to implement the lifecycle method)? I would appreciate some comment/feedback about the chances (and timeline) for this being addressed. Thanks.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.

**Comment by TheCelavi** [comment]
Just to vote up - this would be nice feature to have.

**Comment by patrickhaug** [comment]
This would be awesome!
