### ISSUE TITLE
Missing documentation and examples for SSR in 1.0

### ISSUE THREAD

**Issue by StyleT** [ionic-team/stencil#1674]
Hi! I'm wondering if there any examples/documentation about how Stencil generated components can be used during SSR process? Examples that worked for 0.18 ([like this one](https://github.com/webpro/stencil-ssr-starter/blob/master/server.js)) are not relevant anymore :(

**Stencil version:** 1.0.7

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request

**Comment by pungggi** [comment]
same as https://github.com/ionic-team/stencil/issues/1606
