### ISSUE TITLE
Unit Test Stencil.1.0.7 pattern tag patternUnits attributes

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/stencil#1679]
**Stencil version:**

```
 @stencil/core@1.0.7
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

in npm run test.spec
```               <svg height="100%" width="100%">
                <defs>
    -             <pattern height="18.432" id="pattern-transparency" patternunits="userSpaceOnUse" width="18.432" x="0" y="0">
    +             <pattern height="18.432" id="pattern-transparency" patternUnits="userSpaceOnUse" width="18.432" x="0" y="0">
                    <rect class="pattern-cube" height="9.216" width="9.216" x="0" y="0"></rect>
                    <rect class="pattern-cube" height="9.216" width="9.216" x="9.216" y="9.216"></rect>
                  </pattern>
``` 
the expected should be patternUnits and not patternunits

**Expected behavior:**

the test will pass
**Steps to reproduce:**

see stencil-color-picker at ``` https://github.com/jepiqueau/stencil-color-picker/tree/stencilone ``` 
**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

the unit test was passing with @stencil/core@1.0.4

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
