### ISSUE TITLE
Evaluate queueUpdate in events

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#168]
In order to implement a fiber-like behaviour it is impotant to flush pending tasks per event, so important task can get their time in the main thread.

But I don't understand why it is needed to queue a new task unconditionally. Rendering tasks are already queued when a variable decorated with ` @Prop()` or `@State()` is changed, so I don't see the point of queueing a render update here:

https://github.com/ionic-team/stencil/blob/884c2595facec4517c5f6e0830e9b3b42f3fc290/src/core/instance/listeners.ts#L168

Here's my point again:

```ts
@State() position = 0;

@Listen('touchmove')
myHandler() {
  this.position = this.position + 10;
}
```

^here a queueUpdate will be always be scheduled, because the `this.position` state is changed, and the DOM will be updated properly.

Right now:
```ts
@State() position = 0;

@Listen('touchmove')
myHandler() {
 // nothing
}
```
^here a queueUpdate will be ALSO be scheduled internally, which I don't understand. Again flushing pending tasks does make sense, but create a new task imo does not.

@adamdbradley can you explain that to me? I might not seem something, because the fix looks like removing one line of code, too good to be true.

**Comment by adamdbradley** [comment]
Please test this against the fiber demo. Closing for now.
