### ISSUE TITLE
Make download of latest puppeteer version conditionally

### ISSUE THREAD

**Issue by de-dan** [ionic-team/stencil#1681]
**Stencil version:**

```
 @stencil/core@1.0.7
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm frequently updating stencil to the newest version. From time to time an update requires to download the latest puppeteer version which also requires to download the latest chromium version. The problem is, I develop inside a super secured intranet. Everytime puppeteer forces me to download the newest chromium (which aren't hosted on github and thus blocked by the intranet security settings) I have to put it inside our local artifactory first... Which is a time consuming process.

**Expected behavior:**
`npm test` tests the version of the current puppeteer **and asks, if it should download the newest version**. This step can be skipped via parameter (e.g. `--puppeteer-version-check=ask(default)|force|skip`).

**Comment by romulocintra** [comment]
Hi @de-dan  https://github.com/ionic-team/stencil/commit/01f0a932c9b2096f300d0267ecdf4ad3e60ec334 closes this issue :)

**Comment by de-dan** [comment]
Thank you @romulocintra . Updating to 1.1.1 fixes this.
