### ISSUE TITLE
fix(dev-server): make iframe's visibility hidden

### ISSUE THREAD

**Issue by MrGrigri** [ionic-team/stencil#1683]
**Stencil version:**

```
 @stencil/core@1.0.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running accessibility tests with Axe, the dev server iFrame is visible to screen readers and the DOM. This causes the iFrame to be analyzed by Axe which causes false-negative reports.

**Expected behavior:**

The iFrame should have the CSS property `visibility` with the value of `hidden` to remove it from screen readers. By rendering the iframe invisible but still present, the Axe plugin will ignore the iFrame. This is not a bug on Axe's part, as they need to analyze all iFrames. 

**Steps to reproduce:**

Using Chrome (v75) and the [Axe Chrome Extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US) (v3.8.0), analyze the page and a couple of errors will appear in regards to the iFrame.

* All page content must be contained by a landmark: E.g. the iframe is not inside a `main` tag. Which y'all shouldn't do as you can only have one `main` tag per page and that needs to be left to the author.
* Elements must have sufficient color contrast. E.g. the phrase "Stencil Dev Server Connector ⚡" does not have a computed height, therefore it is not visible and doesn't have sufficient color contrast. 

**Other information:**

**Comment by manucorporat** [comment]
would aria-hidden=true do the same effect?

**Comment by MrGrigri** [comment]
It does prevent the Axe extension from analyzing that iFrame. However, when testing with an actual screen reader (NVDA in my case). It still reads "Stencil Dev Server Connector [high voltage]". When it has the CSS values of `visibility: hidden` it prevents the screen reader from reading it altogether and makes it so that it's not focusable.
