### ISSUE TITLE
Type definition output error

### ISSUE THREAD

**Issue by Brocco** [ionic-team/stencil#1684]
**Stencil version:**

```
 @stencil/core@<version>
```
1.1.2

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

After performing a build component types from `dist/types/foo/foo.d.ts` have an import like this:
```
import { ComponentInterface } from '../../stencil.core';
```
however when navigating to `stencil.core` there is no definition for `ComponentInterface` which causes build issues in consuming applications.

**Expected behavior:**

The outputted types should match.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

Current master has this [code](https://github.com/ionic-team/stencil/blob/144e966f6aeae0e8ea001616e92d1331a16ceadd/src/testing/core.ts#L10) which hides `ComponentInstance` as `ComponentInterface` then when the components are output `ComponentInterface` is not defined in `stencil.core` while `ComponentInstance` is defined.

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/stencil/commit/e5bae1b8b73d87a6d0ee050c7b9696c81cc9d702

**Comment by Brocco** [comment]
Thanks! I wasn't sure if my fix was the right fix (obviously not), but thanks for fixing the issue!
