### ISSUE TITLE
Preload Strategy for Some Components

### ISSUE THREAD

**Issue by vagostep** [ionic-team/stencil#1687]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
All components are load lazy

**Expected behavior:**
A way to preload some components for offline functionality

In an Angular App, i have a functionality to show a Toastr when is offline. This Toastr element is a Stencil Component. So, when is offline try to download and fails. 

Please you can consider somehow in stencil.config maybe add an array of components to preload when the Angular or any app initialize?

**Comment by manucorporat** [comment]
The way to achieve offline functionality is thanks to service workers... not the chrome in-memory cache: https://angular.io/guide/service-worker-intro

**Comment by kraftwer1** [comment]
I guess here is the solution: https://github.com/ionic-team/stencil/pull/1558
