### ISSUE TITLE
new Prop option: partial copy/default for objects (and maybe arrays)

### ISSUE THREAD

**Issue by Mouvedia** [ionic-team/stencil#1688]
**Stencil version:**
```
 @stencil/core@1.0.7
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**

```
@Prop() bar: { [foo: string]: boolean } ;

componentWillLoad() {
  this.bar = Object.assign(defaultObjectWithManyProperties, this.bar);
}
```

If you are using `= { … }` you gotta pass every single properties even the unchanged ones. 
Moreover using `componentWillLoad` is impractical if you have many properties.

**Expected behavior:**

```
@Prop({ assign: true }) bar: { [foo: string]: boolean }  = defaultObjectWithManyProperties;

// or

@Prop({ partial: true }) bar: { [foo: string]: boolean }  = defaultObjectWithManyProperties;
```

The name of the property doesn't matter to me much, it could be something else.
The property would be ignored for anything but arrays and objects.

**Related code:**

```tsx
export interface PropOptions {
  attribute?: string;
  mutable?: boolean;
  reflect?: boolean;
  assign?: boolean; // or partial
}
```

**Other information:**

https://stenciljs.com/docs/properties#prop-options

**Comment by splitinfinities** [comment]
Hey Mouvedia, thank you for the patience getting back to you. Have you tried using [optional properties with TypeScript objects](https://www.typescriptlang.org/docs/handbook/interfaces.html#optional-properties)? I believe this should work best for your issue. I can see some specific use cases for this semantic sugar, but for now, we're going to pass on this. 

Thank you for the recommendation!
