### ISSUE TITLE
E2E tests: page.goto options not optional

### ISSUE THREAD

**Issue by ckrack** [ionic-team/stencil#1689]
**Stencil version:**
```
 @stencil/core@1.1.2
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When using `page.goto('/url')`in an E2E test, this fails with the following error:
```bash
TypeError: Cannot read property 'waitUntil' of undefined
306 |     await page.goto('/url');
at e2eGoTo (node_modules/@stencil/core/dist/testing/index.js:38881:18)
```

This is due to the options object not being initialized, when it is left out of the call.
`page.goto('/url', {});`fixes this.

**Expected behavior:**
Puppeteer describes the API of page.goto with options being optional.
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options

This should be the same in stencils `E2EPage`.

**Steps to reproduce:**

**Related code:**
in node_modules/@stencil/core/dist/testing/index.js:38866

```diff
+ async function e2eGoTo(page, url, options = {}) {
- async function e2eGoTo(page, url, options) {
```

**Comment by Mykola-Veryha** [comment]
For people who will find it on google. The method can be replaced with the next code

```
const pageFoo = await newE2EPage({ url: '/foo' });
```
