### ISSUE TITLE
 --max-workers=4 breaking e2e tests

### ISSUE THREAD

**Issue by romulocintra** [ionic-team/stencil#1693]
**Stencil version:**

```
 @stencil/core@1.1.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Running e2e test in CI stencil+jest automatic adds max-workers=4 this calculation probably is made based on resources from the machine. but having this limitation is breaking e2e tests.

**Expected behavior:**

Same behaviour than the previous  version

**How to reproduce** 

We only able to reproduce on CI machines, we running in docker instances and since this --max-workers are there when executing e2e tests they only work on MacBook pro 16gb.

Locally when i run test shows --max-workers=12 but in CI machine only 4. and times out some of the tests.

**Comment by manucorporat** [comment]
Please, fill the issue explaining how to reproduce and the error you are getting

**Comment by romulocintra** [comment]
Needs more investigation... locally with max-workers set to 2 still works... on CI env it fails and throws `async callback was not invoked within the 30000ms timeout specified by jest.setTimeout Error`

**Comment by telubeer** [comment]
same with v1.1.3 (last success ci run was on v1.0.3)
on local notebook it just work (--max-workers=4)
on gitlab ci runner it can not pass (--max-workers=8)
with errors like 
```
 TypeError: Cannot read property 'click' of null

      93 |         const suggestItem = await page.find('my-comp a:first-child');
      94 |         await page.waitFor(60);
    > 95 |         await suggestItem.click();
```

**Comment by romulocintra** [comment]
Another possible guess i have is the puppeteer compability with chrome version.
Actually is installing latest version of puppeteer-core and works locally cause my browser is the latest version. In CI docker image has chrome 75 - that matches with Puppeteer v1.15.0 and not with 1.18.0 now.

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

**Comment by romulocintra** [comment]
Closing issue cause i updated chrome to match the version required for Puppeteer 1.17 that is chromium 76 or chrome 76 beta
