### ISSUE TITLE
icon display behavior changed from 1.1.2 to 1.1.3

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#1695]
**Stencil version:**

```
1.1.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

![Capture597](https://user-images.githubusercontent.com/140737/60374072-6c817880-99b7-11e9-878c-74c639edd5bf.png)

**Expected behavior:**

Previous version:

![Capture598](https://user-images.githubusercontent.com/140737/60374139-c2eeb700-99b7-11e9-9640-b24e78289a94.png)

**Steps to reproduce:**

Repo:

1.1.2 at https://github.com/adaept/ae-icons-component/commit/ae0162cd62e3cebdc674689f87b8180f4c86411e

1.1.3 at https://github.com/adaept/ae-icons-component/commit/196c01efe3de1b9cc85b1c06a808d1ae40fcaeb1

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

@brandyscarney, @manucorporat, @adamdbradley 

Not really sure if this is stencil, ionic, or some mobile/desktop quirk.

**Comment by manucorporat** [comment]
Can you debug what is different in the dom?

**Comment by peterennis** [comment]
@manucorporat 

1.1.3
![Capture600](https://user-images.githubusercontent.com/140737/60375654-1ca6af80-99bf-11e9-8124-eed7e7ad531a.png)
![Capture599](https://user-images.githubusercontent.com/140737/60375658-24665400-99bf-11e9-87f6-d3290ee2db0e.png)

1.1.2
![Capture601](https://user-images.githubusercontent.com/140737/60375688-5a0b3d00-99bf-11e9-93f3-6462a90bae54.png)
![Capture602](https://user-images.githubusercontent.com/140737/60375696-62fc0e80-99bf-11e9-89b5-15477523aef2.png)

**Comment by peterennis** [comment]
@manucorporat 

More debugging and this is the issue:

![Capture604](https://user-images.githubusercontent.com/140737/60376943-03a1fc80-99c7-11e9-8d2b-9a700ac971af.png)

It should be Ionicons 4.6.1 and Ionic core 4.6.0

My bad. Now working as expected.

![Capture603](https://user-images.githubusercontent.com/140737/60376956-26ccac00-99c7-11e9-85d1-60d7c9c21fea.png)
