### ISSUE TITLE
refresh broken in 1.1.3

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#1696]
**Stencil version:**

```
1.1.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Refresh is broken.

**Expected behavior:**

**Steps to reproduce:**

Here: https://aeicons.adaept.com
app loads
pull down to refresh and it does not work (drag finger down on the screen)
tested on my android phone LG K20 V, Android 7.0
after a few minutes it may work again once or it may not

![Capture605](https://user-images.githubusercontent.com/140737/60378282-eecc6580-99d4-11e9-92c7-4bda5ff91d95.png)

![Capture606](https://user-images.githubusercontent.com/140737/60378284-f68c0a00-99d4-11e9-9286-fecc581f1e9c.png)

**Related code:**

Repo: https://github.com/adaept/ae-icons-component/commit/1fefcec73d8913a8504119da6465a1e9358226df

Added better version info: core/ionicons/stencil/component

```tsx
// insert any relevant code here
```

**Other information:**

It is working in 1.1.2 but the reload seems slower than before:

https://github.com/adaept/ae-icons-component/tree/Branch_ae0162cd

![refresh-112](https://user-images.githubusercontent.com/140737/60378089-369dbd80-99d2-11e9-9ff7-609439105d7e.gif)

@manucorporat 
After testing to resolve the changes it appears stencil 1.1.3 is causing the issue.

Could the manifest now be an issue/requirement where it did not cause problems before?

**Comment by manucorporat** [comment]
I don't understand the issue, is it broken? is it slow?
Can you debug it more?

**Comment by peterennis** [comment]
I would say broken compared to previous.
Did you test the site on a mobile device?
Drag down to refresh and it does not work correctly.
How should I debug it more?

**Comment by manucorporat** [comment]
Try to find the root of the problem,  when you see it not working, what is failing?
Why is it specific to Mobile Android? It's impossible for us to put time into debugging this issue, since we don't even know where to look at.

**Comment by peterennis** [comment]
I can try to step forward from 1.1.2
and test each deploy. Please confirm you saw the problem behavior.

**Comment by peterennis** [comment]
@manucorporat 
FYI just found this: https://github.com/mjackson/unpkg/issues/205#issuecomment-506390902

I have this code:
 <script src="https://unpkg.com/@ionic/core@4.6.0/dist/ionic.js"></script>

It may be related. TBD

Does Ionic have an alternate CDN that could be switched to based on response time?
If so how is it done?

**Comment by peterennis** [comment]
@manucorporat 

Looks like the CDN was the cause.

1. Remove CDN link
2. Load ionicons directly from my site
3. Do not load core

Fixed here: https://github.com/adaept/ae-icons-component/releases/tag/v4.6.1%2F1.1.3%2F0.3.3
