### ISSUE TITLE
Copy Tasks 1.1.3 Breaking Change

### ISSUE THREAD

**Issue by romulocintra** [ionic-team/stencil#1697]
**Stencil version:**

```
 @stencil/core@1.1.3
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behaviour:**

When I do a copy task in output targets using the following code : 

```ts
{
      type: 'www',
      copy: [ { src: '**/**/*.html', dest: './' }, { src: '*.css', dest: './' } ]
}
```
I would normally have my html files and css files copied over 

```bash
www/all-htmls.html 
www/all-htmls.html 
www/all-htmls.html 
www/all-htmls.html 
```

and now I have 

```bash
www/my-folder/src/all-htmls.html 
www/my-another-folder/src/all-htmls.html 
www/my-folder2/all-htmls.html 
```

**Expected behaviour:**

If current behaviour will stay a possibility to CWD would benefit people that need folder modifications and different paths

**Comment by manucorporat** [comment]
It should not be a breaking change, it might be a bug. Unfortunately, i don't understand what:
```
www/all-htmls.html 
www/all-htmls.html 
www/all-htmls.html 
www/all-htmls.html 
``` 
means

**Comment by romulocintra** [comment]
> It should not be a breaking change, it might be a bug. Unfortunately, i don't understand what:
> 
> ```
> www/all-htmls.html 
> www/all-htmls.html 
> www/all-htmls.html 
> www/all-htmls.html 
> ```
> 
> means

This previous behaviour copied all *.html files to the  dest : './' that by default is www meaning that all html files will be at `www/my-html-file.html` and now they are copied using same original path

**Comment by romulocintra** [comment]
Thanks
