### ISSUE TITLE
Command to create a new component

### ISSUE THREAD

**Issue by lcswillems** [ionic-team/stencil#1700]
**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Feature request**
Hi,
It would be nice to have a command to create a new component inside the projet. E.g. "npm run new-cp" that will create the folder, the files, etc...

**Comment by fanick-ber** [comment]
I also think it would be useful. 
In general also something the editor could care about. I use https://marketplace.visualstudio.com/items?itemName=natemoo-re.vscode-stencil-tools in vs code, unfortunately it is a bit buggy and it is not made for stencil-one.

**Comment by lcswillems** [comment]
I already saw this plugin, but not great...

**Comment by adamdbradley** [comment]
You can use `stencil generate` to create new components
