### ISSUE TITLE
Extend HTMLElement in components.d.ts

### ISSUE THREAD

**Issue by CSchulz** [ionic-team/stencil#1701]
**Stencil version:**
```
 @stencil/core@1.1.3
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
```
export namespace Components {
  interface HeroLogin {
```

**Expected behavior:**
```
export namespace Components {
  interface HeroLogin extends HTMLElement {
```

Otherwise you can manually always intersect the HeroLogin with HTMLElement, when you are querying a web components.

**Comment by manucorporat** [comment]
HeroLogin is not a HTML Element, it only exposes the API of your component, HTMLHeroLogin is what you are looking for!

**Comment by CSchulz** [comment]
Dooh! Thanks for your fast reply.

Is it possible to expose own interfaces as well?
For example we have a BaseComponent interface which always defines modifier and in the generated components.d.ts it is listed but the interface itself is missing.

If this would be another issue, I can open a new own or edit this one.
