### ISSUE TITLE
Safari (iOS and macOS) + onInput: Caret jumps to end

### ISSUE THREAD

**Issue by cmaas** [ionic-team/stencil#1702]
**Stencil version:**
```
 @stencil/core@1.1.3
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
On iOS (Safari + Mac, current stable version), if you have an input field that binds a value with the `onInput` event, it's hard to edit a typed text. If you type something and place the caret somewhere in the middle or at the beginning, the caret jumps to the end of the input control after 1 character.

Problem doesn't occur in Firefox and Chrome. It could be a bug in Safari.

**Expected behavior:**
Don't mess with the caret position when using `onInput`. `onChange` works, but this doesn't give "live updates".

**Steps to reproduce:**
- Install Stencil starter, include a simple custom element (see below).
- Type "aaaaaaa"
- Place caret somewhere else
- Type "bbbb"
- Resulting text is "aaabaaaabbbb"
- Instead of "aaabbbbbbbaaaa"

![safari-input](https://user-images.githubusercontent.com/6094364/60501591-90490500-9cbc-11e9-8a7d-b968e8e2cb23.gif)

**Related code:**

```tsx
import { Component, h, State } from '@stencil/core';

@Component({
    tag: 'custom-input'
})
export class CustomInput {
    @State() value: string;
    render() {
        return (
            <input value={this.value} onInput={(e) => this.value = e.target['value']} />
        );
    }
}
```

**Other information:**
Could be a bug in Safari, not sure.

**Comment by cmaas** [comment]
Well ok, this seems to be a bug in Safari. Here's a vanilla JS version with the same behavior:

https://codepen.io/cmaas/pen/ordNZg

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
