### ISSUE TITLE
Slow render performance after React and Ember integration

### ISSUE THREAD

**Issue by embargiel** [ionic-team/stencil#1703]
**Stencil version:**

```
 @stencil/core@1.1.3 and all older
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request
**Current behavior:**

I have projects in Ember and React. I created a library of Stencil components with components like:

- text (changing size/colors/weight via props)
- select
- multiselect
- textfield

I replaced Ember and React components with brand new Stencil components. I observed performance problems after this replacement. You can see differences in linked videos. First for old, React components, second for Stencil.

https://www.youtube.com/watch?v=fyLq41L3CCc
https://www.youtube.com/watch?v=A23JFnCYxro

The problem occurs both in Ember and React.

Render is slower in an unacceptable way. In youtube example, the difference is really small, but for 30 rows dashboard, the final result is visible 1.5 seconds later.

Observations in my app context:
- problem with rendering dashboard rows - each cell has a text component to format the text properly
- problem with rendering advance search - few fields should appear after clicking button

**Expected behavior:**

Rendering should be at least that quick as in original components

**Steps to reproduce:**

Create a container with several stencil components. Show/hide this container using a button with simple action and conditional statement in your template

**Related code:**

Example of usage:
```tsx
<BF sizeSm={2}>
  <select
    optionNameField={'name'}
    onSelect={this.onChange}
    optionsArray={this.props.names}
    valueObject={this.state.selectedName}
  />
</BF>
<BF sizeSm={3}>
  <ac-multiselect
    optionsArray={this.props.types}
    valuesArray={this.state.selectedTypes}
    onChangeHandler={this.onChangeType}
    optionNameField="name"
    optionValueField="type"
  />
</BF>
```

Example of component implementation:
```tsx
export class Text implements ComponentInterface {
  @Prop({ reflect: true }) color: TextColor = TextColor.black;
  @Prop({ reflect: true }) size: TextSize = TextSize.md;
  @Prop({ reflect: true }) weight: TextWeight = TextWeight.normal;
  @Prop({ reflect: true }) uppercase: boolean;

  private colorClass(): string {
    return `text-color-${this.color}`;
  }

  private sizeClass(): string {
    return `text-size-${this.size}`;
  }

  private weightClass(): string {
    return `text-weight-${this.weight}`;
  }

  private uppercaseClass(): string {
    return this.uppercase ? 'text-uppercase' : '';
  }

  private classes(): string[] {
    return [
      this.sizeClass(),
      this.weightClass(),
      this.colorClass(),
      this.uppercaseClass()
    ].filter(Boolean);
  }

  render() {
    return (
      <Host class={{ ...getClassMap(this.classes()) }}>
        <slot />
      </Host>
    );
  }
}
```

**Other information:**

I did a simple performance test. Render 1000 components (text field) on the plain React page. Stencil was faster than React. Problem is appearing only when I'm using components in a regular structure.

**Comment by maxjustus** [comment]
We're running into similar issues where updates in the state of a component that renders child components shows a flash of unstyled content even for child components that are already lazy loaded.

**Comment by beenotung** [comment]
Is the bottleneck related to virtual dom? would it be faster if stencil is built on top of svelte.js?

**Comment by embargiel** [comment]
I don't think so, I turned off virtual DOM

**Comment by DimitarChristoff** [comment]
try removing the `reflect: true` on the component and see if this improves things, seeing similar issues.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!

**Comment by beenotung** [comment]
I experienced similar performance downgrades when using the stencil based ionic components. (The render speed of original angular based ionic components was much faster).

My lesson learnt is to use stencil based components only for page layout, e.g. tabs, segment buttons, navbar e.t.c. and avoid using them for "hot path" (e.g. parts that will be looping for 20 times)

**Comment by beenotung** [comment]
As my understanding, it is impossible to meet your expected behavior "Rendering should be at least that quick as in original components".

Using stencil means it will use javascript and stencil's own virtual dom to do the rendering and props/state change detection.

Therefore, there will be extra overhead between your react app and the stencil web components
