### ISSUE TITLE
Stencil Screenshot compare.html errors with uncaught promise

### ISSUE THREAD

**Issue by Rafael-Leal** [ionic-team/stencil#1704]
**Stencil version:**

```
 @stencil/core@1.1.3 (but also not working with other versions of 1)
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When creating a screenshot test and checking the compare.html in the browser, i receive these errors.

`compare.html:1 Access to script at 'file:///Users/rafaell/Documents/Work/stencil-screenshot-issue/node_modules/@stencil/core/screenshot/compare/build/p-bb2725ef.system.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
p-bb2725ef.system.js:1 `

`Failed to load resource: net::ERR_FAILED`

`app.js:135 Uncaught (in promise) Error: Error loading file:///Users/rafaell/Documents/Work/stencil-screenshot-issue/node_modules/@stencil/core/screenshot/compare/build/p-bb2725ef.system.js
    at HTMLScriptElement.<anonymous> (app.js:135)`

The tests themselves run normally but its impossible to see the compare.html in the browser. 

**Expected behavior:**

The tests should run and the compare.html should be able to be viewed in the browser

**Steps to reproduce:**

Create a new project, add a screenshot test, run the tests and attempt to open the html. I already created a basic PWA project from stencil, upgraded out of stencil beta into 1.1.3, added a test and compare.html does not working with only those changes. 

https://github.com/Rafael-Leal/stencil-screenshot-issue

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

Dependencies

`    "@stencil/core": "1.1.3",
    "@types/jest": "24.0.15",
    "@types/puppeteer": "1.12.4",
    "jest": "24.8.0",
    "jest-cli": "24.8.0",
    "puppeteer": "1.17.0"`

Looked into it a little more and found that in V1.0.5 it stopped working. It may have been this commit (https://github.com/ionic-team/stencil/commit/4557148be508dfbb499d680d23952d81b451accb)

(07/03/19): It looks like it wants you to open the compare.html file while running the project (thats what the CORS issue is about) but then it looks in the wrong place or the browser prepends www/ so it cant really be opened that way for screenshot/compare/app.js and screenshot/compare/app.css that get auto generated in the compare.html.

**Comment by Rafael-Leal** [comment]
![Screen Shot 2019-07-02 at 12 11 38 PM](https://user-images.githubusercontent.com/31293027/60528521-97731180-9cc2-11e9-977a-b0916f6a42a5.png)

**Comment by MiguelC1990** [comment]
bump

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
