### ISSUE TITLE
Typescript rootDir is overriden by srcDir

### ISSUE THREAD

**Issue by adrm** [ionic-team/stencil#1710]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

There is no way to specify a Typescript rootDir that is different from Stencil srcDir, even setting rootDir in tsconfig.json gets ignored. I suspect this is because of this line which assigns the srcDir config directly to rootDir: https://github.com/ionic-team/stencil/blob/d058b44bcada91716a9a8b9480cc824d3e15ab75/src/compiler/transpile/compiler-options.ts#L50

**Expected behavior:**

I want to be able to restrict stencil components to a folder inside src, but also let Typescript know that all my source files are at the src level.

**Steps to reproduce:**

Try to set a srcDir in stencil config and a different rootDir in tsconfig.json. When compiling, Typescript will complain if you try to use code from outside srcDir.

**Other information:**

If this is intended, maybe some docs about the recommended way of easily sharing code without publishing a private NPM package or anything as convoluted would be appreciated. Maybe being able to manually set where our index.html and index.ts sits would help as well, as I could set srcDir to src and then I can signal that the index files could be found inside src/web, for example.

**Comment by liron-navon** [comment]
Please fix this!

**Comment by adamdbradley** [comment]
This should be fixed in the 1.9.x prereleases, thanks
