### ISSUE TITLE
WC issue with ZONE.js on an angular7 app (only IE11)

### ISSUE THREAD

**Issue by pantro14** [ionic-team/stencil#1717]
**Stencil version:**
```
 @stencil/core@1.1.5
```

**I'm submitting a:**
[x ] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
When I run the web component on an angular7 project in IE11, the following issue happens.
_Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)_

if I remove the web component the app loads perfectly.

**Expected behavior:**
the app starts normally showing the web component

**Steps to reproduce:**
- install the web component on an angular 7 app
- ng serve

**Other information:**
This issue is only happening in IE11

**Comment by dgibson666** [comment]
We're having this exact issue as well and would like to know a solution.

**Comment by pantro14** [comment]
@dgibson666 I see a new version 1.1.6 that fixes this bug:
Bug - polyfill: ensure window context w/ fetch polyfill
https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md

**Comment by dgibson666** [comment]
No, I think that is different. The PR above has not yet been merged. Am I wrong?

**Comment by manucorporat** [comment]
This PR should fix how we apply the promise polyfill in webpack setups: https://github.com/ionic-team/stencil/pull/1720

but it requires the promise polyfill to be applied manually by the user if IE11 is supported

**Comment by pantro14** [comment]
@manucorporat thank for your reply,
I'm updating version to 1.1.7, and also added 

`applyPolyfills().then(() => {
  defineCustomElements(window);
});`
in my main.ts file in Angular 7 app.

**Comment by pantro14** [comment]
Now I have an issue when I build the Angular App hosting the web component, after I added the polyfills for IE11, without this, the build runs normally and the app works except IE11.

`applyPolyfills().then(() => { defineCustomElements(window); });`

After `ng build --prod` the next error:

ERROR in ./node_modules/cost-calculator-web-component/dist/esm/legacy/loader.mjs 3:11-19
Can't import the named export 'a' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/cost-calculator-web-component/dist/esm/legacy/loader.mjs 4:8-21
Can't import the named export 'b' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/cost-calculator-web-component/loader/index.mjs 21:0-47
Can't reexport the namespace object from non EcmaScript module (only default export is available)
ERROR in ./node_modules/cost-calculator-web-component/dist/esm/legacy/chunk-04693fa8.js 144:11
Module parse failed: Unexpected token (144:11)
You may need an appropriate loader to handle this file type.
         return module[exportName];
     }
     return import(
     /* webpackInclude: /\.entry\.js$/ */
     /* webpackExclude: /\.system\.entry\.js$/ */
ERROR in ./node_modules/cost-calculator-web-component/dist/esm/polyfills/index.js 15:18
Module parse failed: Unexpected token (15:18)
You may need an appropriate loader to handle this file type.

if (!win.customElements || (win.Element && (!win.Element.prototype.closest || !win.Element.prototype.matches || !win.Element.prototype.remove))) {

     promises.push(import('./dom.js'));
  }

**Comment by pantro14** [comment]
I fixed the issue removing `import 'zone.js/dist/zone'` and placing it into the main.ts file after bootstrapping the app:

import { AppModule } from './app/app.module';
import 'zone.js/dist/zone';  // Included with Angular CLI.

I also installed core-js polyfills https://github.com/zloirock/core-js
The component is now shown in IE11 withou problems:
