### ISSUE TITLE
Unable to import aws-sdk in stencil project

### ISSUE THREAD

**Issue by mhiley** [ionic-team/stencil#1719]
**Stencil version:**

```
 @stencil/core@1.0.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Attempts to import `aws-sdk` and use it fail on build with the error:
```
[ ERROR ]  Node Polyfills Required
           For the import "buffer" to be bundled from node_modules/aws-sdk/lib/browserHashUtils.js, ensure the
           "rollup-plugin-node-polyfills" plugin is installed and added to the stencil config plugins. Please see the
           bundling docs for more information. Further information: https://stenciljs.com/docs/module-bundling
```

Note, I have already followed the instructions in the error message and at the provided link (install `rollup-plugin-node-polyfills` and add it to `plugins`), but I continue to receive the same error message.

**Expected behavior:**

I should be able to import and use aws-sdk without error.

**Steps to reproduce:**

I created a minimal demo repo here: https://github.com/mhiley/stencil-aws-sdk-test

This was initialized with `npm init stencil` using the `app` template. I then added the aws-sdk dependency and a minimal usage of it in this commit: https://github.com/mhiley/stencil-aws-sdk-test/commit/d62248b4f0c3d45c3188f79ba5fb32c8692c944a

**Related code:**

See the above demo repo and the commit with example aws-sdk usage.

**Other information:**

Potentially related to https://github.com/ionic-team/stencil/issues/1471

Thank you!

**Comment by mhiley** [comment]
I believe I have a workaround for this for the time being - as suggested by Josh Beckwith in the Slack #technical-questions room, if I include aws-sdk via a <script> tag and then use `window.AWS`, that seems to work ok.

**Comment by jordanranz** [comment]
It seems that when the nodeResolve plugin was moved below the commonjs plugin caused the error you are experiencing.

from this commit:
https://github.com/ionic-team/stencil/commit/3adfaad2e6878a8f819145dff23bf582cf76b301

In my Stencil fork I moved nodeResolve above commonjs and I no longer see this error. @manucorporat do you know why the nodeResolve plugin was moved below the commonjs plugin?

For what it is worth, I now am getting a runtime error:
`TypeError: Cannot read property 'memoizedProperty' of undefined` from `aws-sdk`

**Comment by cptflammin** [comment]
> I believe I have a workaround for this for the time being - as suggested by Josh Beckwith in the Slack #technical-questions room, if I include aws-sdk via a <script> tag and then use `window.AWS`, that seems to work ok.

Would you be so kind to share a snippet using the window object, configuration and execution of a service you used ? Struggling to make it work this way :/
