### ISSUE TITLE
Preamble is missing

### ISSUE THREAD

**Issue by CSchulz** [ionic-team/stencil#1723]
**Stencil version:**

```
 @stencil/core@1.1.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
No preamble can be found in the main files of the build.

**Expected behavior:**
User defined preamble or default preamble can be found in the main files of the build.

**Other information:**
https://stenciljs.com/docs/config#preamble

**Comment by LalitKushwah** [comment]
Hi CSchulz,
I am using 1.5.x version and getting the below header in the final build file:
   /*!
es6-promise - a tiny implementation of Promises/A+.
Copyright (c) 2014 Yehuda Katz, Tom Dale, Stefan Penner and contributors (Conversion to ES6 API by Jake Archibald)
Licensed under MIT license
See https://raw.githubusercontent.com/stefanpenner/es6-promise/master/LICENSE
https://cdn.jsdelivr.net/npm/es6-promise/dist/es6-promise.auto.min.js
v4.2.8
*/

I have used preamble config with empty string then too it is present.

**Comment by CSchulz** [comment]
@LalitKushwah the given extract is the normal header description of the es6-promise lib. That is not the preamble. You can't turn them off via configuration, they will be copied together.

**Comment by simonhaenisch** [comment]
https://github.com/ionic-team/stencil/search?q=generatePreamble

https://github.com/ionic-team/stencil/blob/a46fe4babfd83f915ab907ace835912718c6bbf3/src/utils/util.ts#L84

Seems like this function is not actually used anywhere.

**Comment by LalitKushwah** [comment]
@CSchulz is there any way to turn them off ?

**Comment by LalitKushwah** [comment]
@simonhaenisch I understand this just asking for the query purpose.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now.

Thanks for adding this. We don't have a timeframe, but we have identified the issue.

**Comment by splitinfinities** [comment]
Duplicate: #2169
