### ISSUE TITLE
Typescript should be a peer dependency

### ISSUE THREAD

**Issue by stefnoten** [ionic-team/stencil#1728]
**Stencil version:**

```
 @stencil/core@1.0.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
TypeScript is a direct dependency of @stencil/core. As a result:
* if you don't specify TypeScript as a dependency in your own package.json, other packages such as tslint cannot find TypeScript.
* if you do specify TypeScript, it is installed twice and Stencil will use a different version

**Expected behavior:**
Stencil specifies Typescript as a peer dependency, so that it is only installed once and other tools can find it.

**Steps to reproduce:**
N/A

**Other information:**

N/A

**Comment by adamdbradley** [comment]
If your app uses typescript, it should have typescript as a dep. Stencil depends on a specific version of typescript. If two versions of typescript is in the node_modules directory that's fine.
