### ISSUE TITLE
Add stencil 1.0 as a compiler to bit.dev

### ISSUE THREAD

**Issue by Mouvedia** [ionic-team/stencil#1729]
**Stencil version:**
```
@stencil/core@1.1.3
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**

Since [Component](https://github.com/ionic-team/stencil/blob/91fb61d57cf13fc6cfae384789082b55d8e223ff/src/index.ts#L50) is not a function I cannot manage to run `bit test` successfully using `@bit/bit.envs.compilers.react-typescript`.

```
    TypeError: (0 , _core.Component) is not a function

    > 4 | @Component({
        |  ^
```
**Expected behavior:**

version ^1.0.0 should be listed on https://bit.dev/components?labels=compiler&q=stencil

**Related code:**

```js
    plugins: [
      ["@babel/plugin-transform-typescript", { isTSX: true }],
      "@babel/plugin-transform-react-jsx",
      ["@babel/plugin-proposal-decorators", { "legacy": true }],
      ["@babel/plugin-proposal-class-properties", { "loose" : true }],
    ]
```

**Other information:**

https://docs.bit.dev/docs/ext-compiling.html

**Comment by adamdbradley** [comment]
We'll take another look when the 1.9.x compiler is released, thanks
