### ISSUE TITLE
Two string literals with the same name are not properly reflected in components.d.ts

### ISSUE THREAD

**Issue by dtieber** [ionic-team/stencil#1731]
**Stencil version:**
```
└── @stencil/core@1.1.3  extraneous
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Using two String Literals with the same name leads to confusion in components.d.ts. 
As you can see in the example below that there are two `Variant`, one in `rb-text`, one in `rb-heading`. The later one got import as `Variant1`, which is fine. Unfortunately, it is not used later on in the interface.

This is how the generated components.d.ts looks like:
```
import {
  Variant,
} from './components/rb-heading/rb-heading';
import {
  Variant as Variant1, //well done, postfix `1` added
} from './components/rb-text/rb-text';

export namespace Components {
  interface RbHeading {
    'variant': Variant;
  }
  interface RbText {
    'variant': Variant; //is not used here though; should be Variant1
  }
}
```

**Expected behavior:**
This is what I would have expected:
```
export namespace Components {
  interface RbHeading {
    'variant': Variant;
  }
  interface RbText {
    'variant': Variant1;
  }
}
```

**Steps to reproduce:**
Create two components and export two String Literals with the same name:

```
export type Variant =
  | 'black'
  | 'white';

@Component({
  tag: 'rb-text'
})
export class Text {
  @Prop() public variant: Variant = 'white’;
```

```
export type Variant =
  | 'blue'
  | 'red';

@Component({
  tag: 'rb-heading'
})
export class Heading {
  @Prop() public variant: Variant = 'red’;
  …
```
**Related code:**

**Other information:**

**Comment by antoniosZ** [comment]
I'm having the same issue

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
