### ISSUE TITLE
Cannot use toHaveLength matcher on element's children

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#1734]
**Stencil version:**

```
 @stencil/core@1.1.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Using the `toHaveLength` matcher on an element's `children` property fails as `length` is missing.

```tsx
import { newE2EPage } from "@stencil/core/testing";

describe("my-test", () => {
  it("children", async () => {
    const page = await newE2EPage();

    await page.setContent("<my-test><div>1</div><div>2</div></my-test>");
    const element = await page.find("my-test");

    const children = await element.getProperty("children");

    expect(Object.keys(children)).toHaveLength(2);
    expect(children).toHaveLength(2); // 💥
  });
});
```

**Expected behavior:**

Using the above snippet, `children` to have a length property and the `expect(children).toHaveLength(2);` assertion to not fail.

**Steps to reproduce:**

To reproduce, use 👇 alongside test case mentioned ☝️.

**Related code:**

```tsx
import { Component, Host, h } from "@stencil/core";

@Component({
  tag: "my-test",
  shadow: true
})
export class MyTest {

  render() {
    return (
      <Host>
        <section>
          <slot />
        </section>
      </Host>
    );
  }
}
```

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
