### ISSUE TITLE
[BUG] - Broadcast-channel package can't be imported : require is not defined

### ISSUE THREAD

**Issue by chilipote** [ionic-team/stencil#1741]
**Stencil version:**

```
@stencil/core@1.1.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Trying to use the `broadcast-channel` package https://github.com/pubkey/broadcast-channel, but I have an error when importing it. 

> require is not defined 

**Expected behavior:**

Be able to use the package

**Steps to reproduce:**

- npm install --save broadcast-channel
- const BroadcastChannel = require('broadcast-channel');

**Related code:**

**Other information:**

I tried using different package in the `stencil.config.js` as `rollup-plugin-node-polyfills` or `rollup-plugin-node-resolve`, or even I've read to add 
```tsx
nodeResolve: { 
  browser: true
},
```

But to be honest, Im a bit lost.

**Comment by nghuuphuoc** [comment]
@chilipote Did you figure it out? I had the same issue.
