### ISSUE TITLE
Allow manifest.webmanifest file name using official extension for Web Manifest

### ISSUE THREAD

**Issue by doppelganger9** [ionic-team/stencil#1743]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When renaming `manifest.json` file to the official spec name `manifest.webmanifest`, and running `npm run start` or `stencil build --serve`, the new webmanifest file is 404.

**Expected behavior:**
I would expect SencilJS and the PWA Toolkit to [support the official WebManifest extension](https://www.w3.org/TR/appmanifest/#media-type-registration).

**Steps to reproduce:**
- start a new Ionic PWA project
- rename `manifest.json` to `manifest.webmanifest`
- `npm run  start`
- in Web Dev Tools > Application > Manifest, there are errors, 
- and when opening the file it shows 404 

**Related code:**

Maybe in Stencil itself:
https://github.com/ionic-team/stencil/blob/9f79968b91a684e159cdc4a28d4220aa8ec4f072/src/compiler/config/validate-copy.ts#L27

**Other information:**
But rejoice! There is a workaround:
just add this in your stenciljs.config.js
```
  //...
  copy: [
    { src: 'manifest.webmanifest' }
  ],
  //...
```
And _voilà_ it will be copied and served correctly.

**Comment by arjunyel** [comment]
@doppelganger9 It looks like that webmanifest code is no longer there, are you still getting this issue? Thank you for filing!

**Comment by doppelganger9** [comment]
I think IIRC -- 8 months have passed -- it was more linked to https://github.com/ionic-team/ionic-pwa-toolkit

The webmanifest file is still there:

https://github.com/ionic-team/ionic-pwa-toolkit/blob/master/src/manifest.json

Thank you for the update!

**Comment by adamdbradley** [comment]
Going to close for now and if it's requested to have it changed we'll take another look. Thanks
