### ISSUE TITLE
Touch Events not firing on Desktop Chrome 

### ISSUE THREAD

**Issue by dpbayer** [ionic-team/stencil#1747]
**Stencil version:**

```
 @stencil/core@1.1.7
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When adding onTouchStart, onTouchMove to a Div, the events are not fired.
If I use native event binding, the events do fire
The following is a simple component with 2 divs. With the first div, there are no console messages. With the 2nd div, the console gets messages
```
import { Component, h } from '@stencil/core';

@Component({
  tag: 'app-home',
  styleUrl: 'app-home.css',
  shadow: true
})
export class AppHome {


  private div2: HTMLDivElement = null;

  componentDidLoad() {
    this.div2.addEventListener("touchstart", ()=> { console.log("Touch Start B") })
    this.div2.addEventListener("touchmove", ()=> { console.log("Touch Move B") })
  }

  render() {
    return (
      <div>
      
      <div style={{"position": "fixed", "top": "100px",
                 "left": "100px",
                 "background-color": "red", "width": "200px",
              "height":"200px"}}
        onTouchStart={ ()=> { console.log("Touch Start A")}}
        onTouchMove={ () => { console.log("Touch Move A")}}
       
      >
      </div>

      <div style={{"position": "fixed", "top": "100px",
                 "left": "500px",
                 "background-color": "blue", "width": "200px",
              "height":"200px"}}
       ref={ (el)=> { this.div2 = el; }}
       
      >
      </div>

      </div>
    );
  }
}

```
Looking at the developer tools, and inspecting the DOM.   The events have been bound with different names.

The working one, uses event listeners
touchmove and touchstart.

The non working one, uses event listeners.
touchMove
touchStart

Not sure if I am using the wrong names, but with other casings the component does not compile.

**Expected behavior:**

I would expect both divs to shown console messages, when I attempt to move them,

**Steps to reproduce:**

1. Take the Stencil App Starter Kit
2. Replace the app-home.tsx with the script above.
3. Run the App, and open in Chrome Desktop
4. Touch and drag and each box. The console should contain messages.

**Related code:**

```tsx
// insert any relevant code here
```

When looking in Chrome's Developer Tools, at the two DIV elements

![stencilA](https://user-images.githubusercontent.com/10091980/61567602-0fd62280-aa78-11e9-8ad3-38b1bfd4aac2.PNG)
![stencilB](https://user-images.githubusercontent.com/10091980/61567653-372cef80-aa78-11e9-8f61-69d0e5079a06.PNG)

**Other information:**

Chrome Version:  75.0.3770.142 (Official Build) (64-bit)
Windows 10 Laptop with Touch Screen

**Comment by manucorporat** [comment]
Desktop chrome does not emit touch events, it's not a stencil bug. Open the device simulator in chrome devtools to have touch events
