### ISSUE TITLE
Not able to set up ag-grid in stencil

### ISSUE THREAD

**Issue by harry101491** [ionic-team/stencil#1748]
**Stencil version:**
```
 @stencil/core@1.0.7
```

**I'm submitting a:**
Issue of trying to resolve the setup of ag-grid on stencil.

[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
ag-grid doesn’t show the required data. I have provide the rowData and columnDef.

**Expected behavior:**
should be able to get the required ag-grid on the screen

**Steps to reproduce:**
**Related code:**

```tsx
@Component({
  tag: 'my-component',
  styleUrl: 'my-component.scss',
  shadow: true
})
export class MyComponent {
  @Element() el: HTMLElement;

  agGrid: any;

  columnDefs = [
    {headerName: "Make", field: "make"},
    {headerName: "Model", field: "model"},
    {headerName: "Price", field: "price"}
  ];

  rowData = [
    {make: "Toyota", model: "Celica", price: 35000},
    {make: "Ford", model: "Mondeo", price: 32000},
    {make: "Porsche", model: "Boxter", price: 72000}
  ];

  gridOptions = {
    columnDefs: this.columnDefs,
    rowData: this.rowData,
    onGridReady: function () {
      this.gridOptions.api.sizeColumnsToFit();
    }
  };

  render() {
    console.log('Inside render function');
    return (
      <ag-grid
        id="my-grid"
        style={{ height: '150px', width: '600px' }}
        class="ag-theme-balham"
      >

      </ag-grid>
    );
  }

  componentDidLoad() {
    console.log('Inside component did load function');
    this.agGrid = document.querySelector('#my-grid');
    this.agGrid.gridOptions = this.gridOptions;
  }

  // @Watch('agGrid')
  // agGridInitializationHandler() {
  //   this.agGrid.gridOptions = this.gridOptions;
  // }

}
```

**Other information:**

**Comment by manucorporat** [comment]
Where is agGrid coming from?

Any reason to not just pass the gridOptions directly?

```tsx
    return (
      <ag-grid
        id="my-grid"
        style={{ height: '150px', width: '600px' }}
        class="ag-theme-balham"
        gridOptions={this.gridOptions}
      >
      </ag-grid>
```

It might be complicated for us to reproduce the issue without any other detail

**Comment by harry101491** [comment]
Hi @manucorporat 
Thank you for the reply. Actually, I eventually figured out but not fully that it might be the issue for not using shadow root. So, I changed my code a little bit and refactor the my-component.tsx into this.

import { Component, h, Element } from '@stencil/core';
import AgGrid from 'ag-grid';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.scss',
  shadow: true
})
export class MyComponent {

  @Element() el: HTMLElement;

  agGrid: HTMLElement;

  columnDefs: [
    {headerName: "Make", field: "make"},
    {headerName: "Model", field: "model"},
    {headerName: "Price", field: "price"}
  ]

  rowData: [
    {make: "Toyota", model: "Celica", price: 35000},
    {make: "Ford", model: "Mondeo", price: 32000},
    {make: "Porsche", model: "Boxter", price: 72000}
  ]

  gridOptions = {
    columnDefs: this.columnDefs,
    rowData: this.rowData,
    onGridReady: function () {
        this.gridOptions.api.sizeColumnsToFit();
    }
  };

  render() {
    return (
      <div
        id="myGrid"
        style={{height: '200px', width: '200px'}}
        class='ag-theme-balham"'
      >

      </div>
    );
  }

  componentDidLoad() {
    this.agGrid = this.el.shadowRoot.querySelector('#myGrid');
    new AgGrid.Grid(this.agGrid, this.gridOptions);
  }
}
It still doesn’t work as expected.
I have a [github ](https://github.com/harry101491/stencil-tester/) repo for this and tried to add another testing feature of highchart(which by the way worked when using the shadow root). Let me know if this doesn’t help I can create a jsfiddle or codepen too. Thanks for your help!
