### ISSUE TITLE
add an event handler or other props to slots

### ISSUE THREAD

**Issue by SylviaGonschior** [ionic-team/stencil#1749]
@stencil/core@<version>
latest version 

**I'm submitting a:**

[ ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

There is only the possibilty to add a "name" prop to a slot. 

**Expected behavior:**

I want to add an event handler, like onClick to a slot. My intention is to use a slot like and with the functionality of a button. So that collegues, if they want to use my web components they can decide which content in the slot fits, maybe a image, or a "x" or another text.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
