### ISSUE TITLE
Weird content projection

### ISSUE THREAD

**Issue by Fdom92** [ionic-team/stencil#175]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
 @stencil/core version 0.0.5
```

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
I have this template to add ion-bubbles:
<img width="424" alt="captura de pantalla 2017-09-21 a las 14 42 27" src="https://user-images.githubusercontent.com/7361737/30696700-e174a428-9edc-11e7-860e-075b2637c271.png">

And the code to re-render the array after push is:
<img width="566" alt="captura de pantalla 2017-09-21 a las 14 42 36" src="https://user-images.githubusercontent.com/7361737/30696751-02adfb12-9edd-11e7-95e8-ed9f46a4f584.png">

And the results on the DOM its weird like content projection or something like that:
<img width="466" alt="captura de pantalla 2017-09-21 a las 14 43 20" src="https://user-images.githubusercontent.com/7361737/30696778-19c6586c-9edd-11e7-9528-3d9952f78f8c.png">

**Expected behavior:**
Just add ion-bubbles but not the whole ion-scroll

**Related code:**
This make that works:
```
<div>
    { this.messages.map(ele => {
        return <ion-bubble message={ele}/>
    })}
</div>
```

**Comment by adamdbradley** [comment]
This should be fixed now as of 0.0.6-4, thanks
