### ISSUE TITLE
Missing TypeScript declaration files when importing the loader

### ISSUE THREAD

**Issue by ettoredn** [ionic-team/stencil#1750]
**Stencil version:**
```
 @stencil/core@1.1.7
```

**I'm submitting a:**
[x] bug report

**Current behavior:**

I get the following error when trying to load StencilJS components from a TypeScript project:
```
 assets/components/dist/loader/index.d.ts(2,15): error TS2307: Cannot find module '../types/components'.
```
The directory `assets/components/dist/types/components` does not contain any declaration file, it contains only directories named after my components with their declarations inside. Does Stencil forget to generate a index.d.ts in `dist/types/components`?

**Expected behavior:**
No such error while importing the loader from a TypeScript project.

**Steps to reproduce:**
Create a TypeScript project and try to import the loader.

```tsx
import { applyPolyfills, defineCustomElements } from '../components/dist/loader';

applyPolyfills().then(() => {
    defineCustomElements(window);
});
```

**Comment by justinwaite** [comment]
Make sure that your package.json has the following for `"types"`:
```
...
"types": "dist/types/components.d.ts",
...
```
instead of
```
"types": "dist/components.d.ts",
```

This seems to direct stencil on where to place `components.d.ts`. When it is placed in the `types` directory it will resolve to this declaration file rather than the components folder.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
