### ISSUE TITLE
KeyboardEvent#key is not normalized in IE11 and Edge (< 76).

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#1752]
**Stencil version:**

```
 @stencil/core@one
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The `key` event is not normalized in IE11 and Edge (< 76). 

**Expected behavior:**

The value for `key` should be normalized across browsers.

**Steps to reproduce:**

Using the component code below, place into a document and press the any of the arrow keys. The values should match `ArrowUp `, `ArrowRight`, `ArrowLeft`, `ArrowDown` in IE, but instead are `Up`, `Right`, `Left`, `Down`.

**Related code:**

```tsx
 import {
  Component,
  State,
  Listen,
  h
} from "@stencil/core";

@Component({
  tag: "my-test",
  shadow: true
})
export class MyTest {
  @State() pressed: string = "";

  render() {
    return <div>{this.pressed}</div>
  }

  @Listen("keydown", { target: "document" })
  onKeyDown(event: KeyboardEvent) {
    this.pressed = event.key;
    event.preventDefault();
  }
}
```

**Other information:**

`KeyboardEvent#key` is not normalized in IE and Edge and will lead to inconsistent browser behavior or unnecessary verbose code for handling other cases. I would expect this to be normalized since [ionic is using `key`](https://github.com/ionic-team/ionic/blob/34dfc3ce98d1e30af7e2f82276a63bc077726773/core/src/components/tab-button/tab-button.tsx#L123). 

Incorporating a simple shim like the following would be useful: https://github.com/shvaikalesh/shim-keyboard-event-key

Tested in IE11 + Win7

**Comment by manucorporat** [comment]
Ionic only uses Enter, which i think it's the same in IE11 no?
Ideally this seems like an easy fix, we add another polyfill and done, the problem comes with collision with more polyfills, new issues, more boilerplate and slower applications.

Stencil does not replace DOM events, if you want to support IE11 you might need to be aware of this problems and handle it yourself.

I am not totally opposed, but I need a stronger argument, in addition shipping a polyfill for Edge means shipping it also for Chrome, Firefox and Safari.

**Comment by jcfranco** [comment]
> Ionic only uses Enter

Ionic uses other keys ([including `ArrowX`](https://github.com/ionic-team/ionic/blob/03c1d19e0740365ed109298c013441138b28353f/core/src/components/range/range.tsx#L501-L509)).

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
