### ISSUE TITLE
IE11: Unable to get property 'insertBefore' of undefined or null reference

### ISSUE THREAD

**Issue by pantro14** [ionic-team/stencil#1754]
**Stencil version:**
```
 @stencil/core@0.18.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
the web component (wc) is displayed on an Angular APP and works fine in any other browser than IE11.
When there's a state change that renders the dom, and an this error only happens in IE11 

**Expected behavior:**
When the state change occurs the wc behaves normally in IE11

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/3803059/61697704-1a264400-ad38-11e9-8e87-e526a4892860.png)

-->

**Other information:**
I found a similar issue https://github.com/ionic-team/stencil/issues/1196 but I think might not be a related behavior.

**Comment by stanley85** [comment]
I guess this is related to IE's issue with slotted elements.

**Comment by Vladlan** [comment]
@pantro14  had the same issue. Try to avoid cases `parentNode.insertBefore(newNode, newNode)` or `parentNode.insertBefore(referenceNode, referenceNode)`. This solved problem for me in IE11.

**Comment by claviska** [comment]
I'm going to close this since Stencil is now at v2. If this is still an issue in the latest version, please provide a minimal test case or repo. 😄
