### ISSUE TITLE
Libraries imports

### ISSUE THREAD

**Issue by salmau** [ionic-team/stencil#1755]
**Stencil version:**

```
"@stencil/core": "1.1.9"
```

**I'm submitting a:**

[ x ] bug report

**Current behavior:**

I was using Angular/Ionic for my project and I am using Stencil for few weeks. 
In my older project, I have being using especially 'markup-js' and 'nanoid'.
I can't use these libraries with Stencil.
I import its as usual.
But,  `markup-js` is replaced by `undefined`, ie  function is not found (but there is the `markup-js` module in `node_modules`) .
With `nanoid` I've got an error thanks to TS : `This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.`
But I can't import it differently !

**Expected behavior:**

Imports successfully libraries.

**Steps to reproduce:**

```
npm init stencil
>PWA
npm install --save nanoid
npm install --save markup-js
```

Then edit the app-home with : 
```
import { Component, h } from '@stencil/core';
import * as Mark from 'markup-js'
// import * as nanoid from 'nanoid'

@Component({
  tag: 'app-home',
  styleUrl: 'app-home.css'
})
export class AppHome {

  render() {
    const variable = 'libraries'
    // const random = nanoid()
    return [
      <ion-header>
        <ion-toolbar color="primary">
          <ion-title>Home</ion-title>
        </ion-toolbar>
      </ion-header>,

      <ion-content class="ion-padding">
        <p>
          Welcome to the PWA Toolkit. You can use this starter to build entire
          apps with web components using Stencil and ionic/core! Check out the
          README for everything that comes in this starter out of the box and
          check out our docs on <a href="https://stenciljs.com">stenciljs.com</a> to get started.
        </p>
        {Mark.up('The world with Stencil is great but better with {{variable}}', {variable})}
        {/* {random} */}

        <ion-button href="/profile/ionic" expand="block">Profile page</ion-button>
      </ion-content>
    ];
  }
}
```
Throws error `TypeError: "undefined is not a function"` for Mark.up
For nanoid, throws error `Cannot call a namespace ('nanoid')` at build

**Related code:**

```tsx
import * as Mark from 'markup-js'
import * as nanoid from 'nanoid'

Mark.up('mystring with Variable', { Variable: 'variable'})
const radomString= nanoid()
```

**Other information:**

**Comment by salmau** [comment]
For nanoid, `import nanoid from 'nanoid'` is working. But not for Markup. I don't understand why there is a problem at first and secondly why it's solved the issue for `nanoid` and not for `Markup`.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
