### ISSUE TITLE
example of stencil with ionic and capacitor 

### ISSUE THREAD

**Issue by bhandaribhumin** [ionic-team/stencil#1756]
can anyone look my repo and check I'm doing right things, I'm trying to build mobile application with paw so work on capacitor with stencil. 
https://github.com/bhandaribhumin/ionic-stencil-capacitor

**Comment by jcesarmobile** [comment]
By checking the README, you don't have to do
```
cd ios/App
 pod install
 cd .. / ..
```
The `npx cap add ios` runs pod install internally

Also instead of "Open ios/App/App.xcworkspace in Xcode", you can use `npx cap open ios` command, it will open Xcode for you.
