### ISSUE TITLE
IE11 - Component does not load when class attribute is used in JSX template

### ISSUE THREAD

**Issue by nmina** [ionic-team/stencil#1757]
**Stencil version:**
```
 @stencil/core@1.1.8
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Web Component does not load in IE11 with `@stencil/core` versions 1.1.8 and above when `class` attribute is used in JSX template.

**Expected behavior:**
Component should load in IE11. 

**Steps to reproduce:**
Create a Stencil starter project using the CLI.
```
npm init stencil
Pick a starter > component
Project name > any-name
```

in `my-component.tsx`, add class attribute in the div tag:
```tsx
import {Component, Prop, h, Element} from '@stencil/core';
import {format} from '../../utils/utils';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: false
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop() first: string;
  
  /**
   * The middle name
   */
  @Prop() middle: string;
  
  /**
   * The last name
   */
  @Prop() last: string;
  
  @Element() el: HTMLElement;
  
  private getText(): string {
    return format(this.first, this.middle, this.last);
  }
  
  render() {
    return <div class="message">Hello, World! I'm {this.getText()}</div>;
  }
}
```

Add `--es5` in package.json's `start` script:
```
"start": "stencil build --dev --watch --serve --es5"
```

then run the app in IE11.

Console shows the following error:
![image](https://user-images.githubusercontent.com/13359095/61725594-12699e00-ad3e-11e9-9316-0826bda4d348.png)
**Related code:**

**Comment by viljamis** [comment]
If it helps, this regression was introduced in `"@stencil/core": "1.1.7"` and downgrading to ``"@stencil/core": "1.1.6"` fixes the issue.

**Comment by nmina** [comment]
Thanks @viljamis. Yes I have my application version set to `1.1.7` until this is fixed. I guess unless they decided to move forward and leave IE11 behind. lol

**Comment by cary-smith** [comment]
We are also stuck on 1.1.7 after finally getting off of 0.15.2. Woohoo! This is the only roadblock and I have submitted a pull.
