### ISSUE TITLE
Input autofocus stops working in "complex" components

### ISSUE THREAD

**Issue by schadenn** [ionic-team/stencil#1758]
**Stencil version:**

```
 @stencil/core@1.1.9
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
`<input>` element within a custom-component (scoped) will not receive focus although autofocus 
is set whenever there is another custom component being rendered besides the `<input>`-element

**Expected behavior:**
Focus shall be set accordingly.

**Steps to reproduce:**

You can reproduce the bug in @ionic/core components by using the code below.

**Related code:**
Just add a custom ion-* component in inputs' render function - for example an icon.

Within src/components/input/input.tsx
```tsx
render() {
    [...renderFunction...]
    return [
        <input
            {...inputProps}
        />,
        <ion-icon name={"heart"} />,
        (this.clearInput && !this.readonly && !this.disabled) && <button
            {...buttonProps}
        />
    ]
}

// Then use ion-input like:
<ion-input autofocus></ion-input> // autofocus won't work
```

**Other information:**
If anyone can hint me in the right direction I'd be happy to submit a PR. Right now I can't really think of why this might be happening (some timing issues come to mind).

**Comment by manucorporat** [comment]
This might not be a stencil issue, i think autofocus requires user interaction in safari (and maybe other browsers too).
https://stackoverflow.com/questions/6287478/mobile-safari-autofocus-text-field

**Comment by schadenn** [comment]
Don't really see the point in Safari doing that. From a UX point of view I think it's totally fine for the keyboard to open instantly on a TAN-input only page (which is our use case). But okay then. It won't work in Safari. 

As a workaround I just called .focus() in a 200ms timeout on componentDidLoad() and this works fine (in Chrome, Firefox and IE) - so they're not blocking the focus because of no user interaction.
Also the autofocus attribute will work if there is no other custom component being rendered (only the `<input>` is fine) .

**Comment by manucorporat** [comment]
I will close this issue, since it's unlikely stencil itself is doing something wrong regarding autofocus, stencil just render the attribute to the dom, we can't do anything else.

However feel free to reopen if you think something could be done in our side.

**Comment by goldenLunchbox** [comment]
I have a related Problem. It is nearly impossible to consistently set a autofocus on an input with an attribute, even on a nativ input, when it is nested inside of an other web-component. 
The solution from @schadenn is only working sometimes and I am confused about why it is necessary to set a timeout in the componentDidLoad() function.  At this point i would expect that the component is fully loaded and functional. 
I would suspect that the componentDidLoad() function might trigger to early. 
May be you might reconsider reopening this ticket.

**Comment by rjborba** [comment]
Hey, we're facing the same issue. 
autofocus is not consistent no matter what.

It does not work:
```javascript
 render() {
    return (
      <Host>
        <component-a />
        <component-b-with-input-with-autofocus/>
      </Host>
    )
  }
```

It does work
```javascript
 render() {
    return (
      <Host>
       {/*  <component-a /> /*}
        <component-b-with-input-with-autofocus/>
      </Host>
    )
  }
```
