### ISSUE TITLE
[1.1.9] [IE11] skeleton inside the component remains

### ISSUE THREAD

**Issue by stanley85** [ionic-team/stencil#1759]
**Stencil version:**
```
 @stencil/core@1.1.9
```

**I'm submitting a:**
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
We are currently adding skeletons to our components but stumble upon the fact that IE11 wont remove them as soon as the component has loaded.

**Expected behavior:**
We don't have a slot inside the component, hence we expect to have the skeleton inside the component removed.

**Steps to reproduce:**
Add inline-styled skeleton markup inside the component brackets. Dont add a slot inside the render method.

**Comment by manucorporat** [comment]
The lack of a <slot> does not mean the content is removed, it must still be in the DOM. IE11 does not support shadow-dom, so the slot implementation can't do much to workaround this issue

**Comment by stanley85** [comment]
@manucorporat do you see any path to enable such thing as skeletons for IE? Maybe remove all children if no slot is found?

**Comment by stanley85** [comment]
The behaviour is still the same, please help me on this

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
