### ISSUE TITLE
componentWillUpdate/componentDidUpdate should pass new values

### ISSUE THREAD

**Issue by mitchellsimoens** [ionic-team/stencil#176]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.5-24
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
As documented, `componentWillUpdate` and `componentDidUpdate` do not receive any arguments. This makes those methods a bit less useful. Say a prop or state was updated and they are both objects, since the new object is a new object the prop will then be new and the methods will execute. However, what if you only want to react on if a nested property of the objects changed, you'd need the new and old objects but there isn't a way (that I can see) to do this.

Looking at React, [`componentWillUpdate`](https://facebook.github.io/react/docs/react-component.html#componentwillupdate) will receive the new props and new state where [`componentDidUpdate`](https://facebook.github.io/react/docs/react-component.html#componentdidupdate) gets the old props and old state (since when these methods are executed is before and after the props/state are set).

Optionally, it'd be nice to have [`shouldComponentUpdate`](https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate) to also control if the component should be rerendered for the same reason.

I know there are the `PropWillChange` and `PropDidChange` decorators which work great (you get new/old props and it's a better API IMO) but since you have the same React component lifecycle methods it may be a good idea to also pass similar things. Don't have to be 100% the same API as React but not a stretch to think people would expect them. Or maybe it's a documentation issue where you can point them to the decorators if they want to get the props. May need state decorators also?

**Comment by adamdbradley** [comment]
Definitely up for debate, but at this stage we're trying to keep the API footprint as small as possible so we don't have breaking changes down the road. We'll keep this in mind, and if it keeps coming up then we'll reevaluate. Thanks

**Comment by jthoms1** [comment]
In many cases you will use PropWillChange and PropDidChange Decorators to accomplish the same thing for prop differences,  but we don't have a way of accomplishing this for state change.  @mlynch and I talked about it and agreed it would make sense to add them.

I propose we create @StateWillChange and @StateDidChange decorators that act in the same way.

@adamdbradley thoughts on this?

**Comment by jthoms1** [comment]
Well it appears that `PropWillChange` and `PropDidChange` decorators can be used as is for State watching.  So maybe we just rename them and update the docs, and write an upgrade transpile script.

**Comment by jthoms1** [comment]
@adamdbradley and I discussed this and we will create a more generic name for the decorators to support both Props and State. `WillChange` and `DidChange` will be the new decorator names.

We will still allow for `PropWillChange` / `PropDidChange` but throw a warning during build.

**Comment by UserGalileo** [comment]
+1 for implementing a _shouldComponentUpdate_ hook, I think it'd be quite necessary for performance tuning since we're working with a VDOM 👍

**Comment by bfmatei** [comment]
If think this was covered in v0.1.1 (PropWillChange and PropDidChange have been renamed to Watch).

**Comment by jthoms1** [comment]
Yep I am going to close this, it was resolved with release of 0.1.1. https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#011-2018-01-09

**Comment by jthoms1** [comment]
We will need to document this including the callbacks using the params (newValue, oldValue).

**Comment by jgw96** [comment]
Closing this as the new docs for this are live here https://stenciljs.com/docs/decorators
