### ISSUE TITLE
ReferenceError: h is not defined

### ISSUE THREAD

**Issue by cnhnet** [ionic-team/stencil#1761]
**Stencil version:**
Core 1.2.0

**I'm submitting a:**

[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
ion-icons no longer showing up after update to new Core 1.2.0. 
Console message: 
" #ReferenceError: h is not defined
    at Icon.__stencil_render (ion-icon.entry.js:175)
    at Icon.render (ion-icon.entry.js:183)
    at updateComponent (chunk-a0c8fea8.js:1221)
    at Array.update (chunk-a0c8fea8.js:1194)
    at consumeTimeout (chunk-a0c8fea8.js:120)
    at flush (chunk-a0c8fea8.js:143)"

**Expected behavior:**
ion-icons should properly display without errors.

**Steps to reproduce:**
Start any project containing ion-icons.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by manucorporat** [comment]
>ion-icons no longer showing up after update to new Core 1.2.0.

which version was working?

which version of ionicons are you using?

**Comment by cnhnet** [comment]
> > ion-icons no longer showing up after update to new Core 1.2.0.
> 
> which version of stencil was working?
> 
> which version of ionicons are you using?
> 
> > Steps to reproduce:
> > Start any project containing ion-icons.
> 
> This is not enough, can you provide some relevant source code?

Stencil Version that was working: "@stencil/core: 1.1.9"
Ionic Version: "@ionic/core": "one"
Ionicons Version: 4.5.8
[source.txt](https://github.com/ionic-team/stencil/files/3429170/source.txt)
