### ISSUE TITLE
Can't import multiple components on same page

### ISSUE THREAD

**Issue by misterjojo** [ionic-team/stencil#1765]
**Stencil version:**

```
 @stencil/core@1.2.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I try to import two stencil components into one single page like this with esm import. 
On chrome 75, it works on first access, if i refresh the page, only one component is loaded. i've got these errors in console :

````
component-b/dist/component-b/p-wfisufbz.entry.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
p-5c72aa3d.js:1 TypeError: Failed to fetch dynamically imported module: http://localhost:8080/component-b/dist/component-b/p-wfisufbz.entry.js
d @ p-5c72aa3d.js:1
p-5c72aa3d.js:1 TypeError: a is not a constructor
    at p-5c72aa3d.js:1
d @ p-5c72aa3d.js:1
p-5c72aa3d.js:1 Uncaught (in promise) TypeError: Cannot read property 'k' of undefined
    at p-5c72aa3d.js:1
````
It appears that component-a entries are loaded from component-b base path.
I've only seen this issue on Chrome and it appears only if you **don't have DevTools open**.

**Expected behavior:**
Components should load correctly.

**Steps to reproduce:**
You can reproduce the problem on this simple repo : 
https://github.com/misterjojo/stencil-import-issue

**Comment by manucorporat** [comment]
Opened an issue in V8: https://bugs.chromium.org/p/v8/issues/detail?id=9558
I guess we will need to find a workaround... in the meantime
