### ISSUE TITLE
Interesting issue when trying to use the public @Method calls, cannot call element methods inside components

### ISSUE THREAD

**Issue by bdanzer** [ionic-team/stencil#1769]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[ x] bug report?
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

So if create a component called toasty and put a method on it called test that spits a a console log and create an exported function in the utils.ts file. Then go into another component and import toasty and call var toast = await toasty() it will actually fire the public test method. But if I do it again after returning the element in the component toast.test() it will not do anything and if I console log the var set now it will console log the element. Is it not possible to do this?

```
export async function toasty() {
  const el = document.createElement('dp-alert');

  document.body.appendChild(el);
  // el.alerted = show;
  // el.text = text
  await setTimeout(() => {
    el.test(); //console.logs 'test'
  }, 0);

  return el;
}
```

**Expected behavior:**

I was expecting to be able to potentially export functions that could create components o the page, not really sure if this is a good idea or not.

**Steps to reproduce:**

```
//function in utls.ts
export async function toasty(text, show, ms) {
  const el = document.createElement('dp-alert');

  document.body.appendChild(el);
  // el.alerted = show;
  // el.text = text
  await setTimeout(() => {
    el.toasty(text, show, ms);
  }, 0);

  return el;
}
```

component it's calling:

```
import { Component, Method } from '@stencil/core';

@Component({
  tag: 'dp-alert',
  styleUrl: 'dp-alert.scss'
})
export class DpAlert {

  @Method()
  async test() {
    console.log('works');
  }

  render() {
    return '';
  }
}
```

how it's called in another component:

```
import { Component, Method } from '@stencil/core';
import { toasty } from '../../utils/utils';

@Component({
  tag: 'dp-test',
  styleUrl: 'dp-test.scss'
})
export class Test {
  componentDidLoad() {
      this.test();
  }

  async test() {
    var el = await toasty();
    el.test();
  }

  render() {
    return '';
  }
}
```

After doing that it should log to console.log messages but only does one;

**Comment by stanley85** [comment]
If I am right you are calling an async function from the Lifecycle Method. Make sure you return a Promise like mentioned here https://stenciljs.com/docs/component-lifecycle#async-lifecycle-methods then this should work.
