### ISSUE TITLE
SSR engine support for the platforms

### ISSUE THREAD

**Issue by ansarizafar** [ionic-team/stencil#177]
Stencil supports Node.js servers out of the box, and the SSR rendering engine is baked right into the @stencil/core package.

Is it possible to port SSR engine to other platforms? especially I am interested in Crystal web server [https://crystal-lang.org/](https://crystal-lang.org/)

**Comment by mortenson** [comment]
I'm starting to look at using [v8js](https://github.com/phpv8/v8js) to support SSR for PHP applications, I think a good first step would be for Stencil to support SSR outside of a Node.js environment.

React has its own v8js library for SSR, and it looks like Vue has discussed support as well (https://github.com/vuejs/vue/issues/4101).

If Stencil could do SSR without requiring Node.js, it _should_ enable SSR for any other language with a PHP engine like v8js.

**Comment by mortenson** [comment]
@ansarizafar I spent quite a long time trying to get server side rendering for Stencil working in a non-Node environment, and didn't end up with anything working. What I landed on was installing the Node command on my web server, then within PHP executing a flexible version of the SSR example which should work for a variety of other platforms. I've posted the code for the Node script here: https://gist.github.com/mortenson/24f4959b07acd4e0cef83d4344f53807

**Comment by adamdbradley** [comment]
I think this is a great idea, but will probably have to be community lead projects for each platform. We're willing to help along the way for each one, please join our stencil worldwide slack channel. Thanks

**Comment by mortenson** [comment]
@adamdbradley Not sure if you saw it but I published https://www.drupal.org/project/stencil yesterday, which adds basic support for Stencil to Drupal. It includes a smart loader that detects Stencil components in enabled modules and server side rendering.

**Comment by adamdbradley** [comment]
Whoa nice! This is awesome!
