### ISSUE TITLE
problem with stylesheet tag name with sass

### ISSUE THREAD

**Issue by devster19** [ionic-team/stencil#1770]
**Stencil version:**
@stencil/core@1.0.7 

**I'm submitting a:**
[ ] bug report
[ ] feature request
[x ] support request 

**Current behavior:**
I have add sass plugin to file stencil.config.ts  and create my own component 
It didnt work when i give a style to my component tag name but it works if I remove the tag name and just give style to normal html element in .scss file  for example.

my-first-component
{
 font-size:4em . <--- this doesn't work
}
p
{
 font-size:4em  <-- this is ok
}

please help

**Comment by DesignByOnyx** [comment]
This type of question is best left to StackOverflow or Slack (https://stencil-worldwide.slack.com). If you are using `stadow: true`, then you don't want to use your component's tag name. Instead, use `:host { ... }`.

**Comment by manucorporat** [comment]
Exactly, if using scoped: true or shadow-dom, :host { } must be used to target the host element
https://developer.mozilla.org/en-US/docs/Web/CSS/:host()
