### ISSUE TITLE
Prerendering does not work in IE11 from version 1.1.3

### ISSUE THREAD

**Issue by delwyn** [ionic-team/stencil#1772]
**Stencil version:**
```
 @stencil/core@1.1.3
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When upgrading from 1.1.2 to 1.1.3 and above, building with the `--prerender` flag stops working in ie11 - the components render but it looks like they are not being hydrated. Everything works fine in development when run with the `--es5` flag.

There were some changes made to the polyfills that are included in 1.1.3 so I assume it is something to do with that. In the docs, it looks like all the polyfills should be included automatically for ie11.

**Expected behavior:**
Building with the `--prerender` flag should work in ie11

**Steps to reproduce:**
I have created an example [repo](https://github.com/delwyn/stencil-ie11)
- master branch uses 1.1.2 and works as expected
- not-working-in-ie11 branch uses 1.1.3 and does not work in IE11

```
npm install
npm run build
cd www && serve
```

**Related code:**

**Other information:**

**Comment by cthos** [comment]
I can confirm that I can reproduce this in another project (I've stumbled upon this ticket because of the exact same issue).

Oddly enough, though, this does not appear to be a problem in the _app starter_, only the component starter. Which.... is weird?

**Comment by cthos** [comment]
Also for me, it appears that the problem is isolated to css variable replacement, the pre-hyrdating of text and whatnot works fine. 🤔
