### ISSUE TITLE
Escaped pipes in docs-readme markdown table are causing issues

### ISSUE THREAD

**Issue by robaxelsen** [ionic-team/stencil#1777]
**Stencil version:**

```
 @stencil/core@1.1.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When generating readme.md with the internal docs compiler, union types are output with single escaped special character `\|`:
https://github.com/ionic-team/stencil/blob/30aa0c792aa80545e0aaad02a830016ef0307d36/src/compiler/docs/readme/docs-util.ts#L35

This is causing issue for markdown parsers, storybook.js included as seen in this issue: https://github.com/storybookjs/storybook/issues/6869

**Expected behavior:**

Currently both `markdown-to-jsx` and `simple-markdown` libraries do not parse these escaped pipe characters correctly (nor does markdown preview in webstorm), resulting in broken tables. I except the fact that string literals when used in JavaScript regex ignores [single escaped special characters](https://www.regular-expressions.info/characters.html), as opposed to double escaped `\\|`, to be the main reason why this breaks markdown table parsing.

To make it easier to parse, and to avoid workarounds or new exception case supported in popular markdown parsers such as `simple-markdown`, in a non-standard way (as JS regex can't parse single escaped special characters), I would suggest to parse union types to `or` instead of `\|`.

**Steps to reproduce:**

Some simple code to illustrate, with sample markdown table generated from stencil.js, can be found here in test repo: https://github.com/robaxelsen/markdown-to-jsx-table-pipe-test

**Related code:**

See repo above.

**Other information:**

I am working on a PR for this.

**Comment by dutscher** [comment]
i need this aswell.
my table from readme looks like that:
![image](https://user-images.githubusercontent.com/14682/65035120-b8094a00-d948-11e9-8631-3b2f612b051b.png)

readme: 
![image](https://user-images.githubusercontent.com/14682/65035237-f56dd780-d948-11e9-9999-7db500313b23.png)

generated from comp:
![image](https://user-images.githubusercontent.com/14682/65035157-cf483780-d948-11e9-8b93-3187e823f8e7.png)

the PR from robaxelsen is simply clever! 
thanks for that and hopefully we got it into next release

cheers

**Comment by AntonRatnick** [comment]
`@stencil/core@1.13.0`

Looks like need reopen, change from [#1779 ]( https://github.com/ionic-team/stencil/pull/1779/files) has been lost in [master](https://github.com/ionic-team/stencil/blob/54ee75f6cb8130276a00af6fff479ea8e0741833/src/compiler/docs/readme/docs-util.ts#L34)

**Comment by manucorporat** [comment]
This don't need fix in stencil, good markdown parser should work fine!
https://github.com/Khan/simple-markdown/issues/68

**Comment by GuySurname** [comment]
> `@stencil/core@1.13.0`
> 
> Looks like need reopen, change from [#1779 ](https://github.com/ionic-team/stencil/pull/1779/files) has been lost in [master](https://github.com/ionic-team/stencil/blob/54ee75f6cb8130276a00af6fff479ea8e0741833/src/compiler/docs/readme/docs-util.ts#L34)
> Lost since `@stencil/core@1.10.0`

Yeah I'm seeing this as well. Do we like that 'or' solution? I'm happy to raise a PR and switch back to that, or I can look deeper into the issue-trail on simple-markdown/markdown-to-jsx and try and understand/restore the escaping pipe.

**Comment by leereichardt** [comment]
@adamdbradley It seems this issue needs to be reopened? Is this correct? The issue is still happening for me

**Comment by robaxelsen** [comment]
This issue was created from having issues with broken tables when documenting union type props, such as this:
![image](https://user-images.githubusercontent.com/14682/65035120-b8094a00-d948-11e9-8631-3b2f612b051b.png)

As @manucorporat mentioned, it depends on the parser if this is handled correctly or not. I am using Storybook to view the Stencil.js docs-readme, and I chased down the problem to be with the underlying dependcy `simple-markdown`, which again was used by `markdown-to-jsx` in Storybook. Got great help from @ariabuckles, and this was fixed: https://github.com/Khan/simple-markdown/issues/68

After this fix, the tables looked liked this (so not broken anymore, but also not "pretty"):
![Screenshot at 2020-07-22 12-07-22](https://user-images.githubusercontent.com/13132899/88267274-e5452800-ccd0-11ea-992c-d8cf329398ce.png)

The PR I submitted, which for some reason seems to be lost, changed it to have "or" instead of "/|", which looked prettier. 

Looking at the git history, it seems that this was deliberately removed here: https://github.com/ionic-team/stencil/commit/d19697164f25e01813430410581f517c149817d4

Seeing as `simple-markdown` does not remove the escaping `/` before the `|`, would you be fine with re-introducing `or`, @manucorporat?

**Comment by dutscher** [comment]
for me its clean. i have stencil/core ^1.13.0 and the readme looks well as expected
![image](https://user-images.githubusercontent.com/14682/88270752-6d79fc00-ccd6-11ea-8b42-729c98de7da4.png)
cheers

**Comment by robaxelsen** [comment]
@dutscher what are you parsing/rendering the markdown with?

**Comment by dutscher** [comment]
@robaxelsen my styleguide is build with fractal and this use https://www.npmjs.com/package/marked ^0.7.0.

cheers
