### ISSUE TITLE
Specify Chromium path Puppeteer should use

### ISSUE THREAD

**Issue by Scipionh** [ionic-team/stencil#1778]
**Stencil version:**
@stencil/core@1.2.1

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I can't specify the path of the Chromium I want to use

**Expected behavior:**
executablePath configure on stencil.config.ts the path to chrome I would like to execute same as :
`const browser = await puppeteer.launch({executablePath: '/path/to/Chrome'});`

This case is similar to the second part of this one https://github.com/ionic-team/stencil/issues/1529

**Comment by apillard** [comment]
The browserExecutablePath config option doesn't work for you?

https://stenciljs.com/docs/testing-config

**Comment by Scipionh** [comment]
It does, my very bad !
