### ISSUE TITLE
`waitForChanges` on spec pages does not wait for all events to emit

### ISSUE THREAD

**Issue by Minivera** [ionic-team/stencil#1781]
**Stencil version:**
```
 @stencil/core@1.2.3
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
We have components that, when clicked, will trigger one or more events depending on what happens. In this specific case, we send a "click" event with some data, a request to our API is sent and waited for, then an "error" or "success" event is triggered with the result of the API call.

Using JEST and `newSpecPage`, I want to test that all events are properly emitted with the right data. In my jest test, I check those events like this:

```tsx
    page = await newSpecPage({
      components: [APIButton],
      html: `<div></div>`,
    });
    element = page.doc.createElement('api-button');

  const onClick = jest.fn();
      const onSuccess = jest.fn();

      const root = page.root as HTMLElement;
      element.resourceLabel = Resource.body.label;
      root.appendChild(element);
      await page.waitForChanges();

      element.addEventListener('button-click', onClick);
      element.addEventListener('button-success', onSuccess);

      element.querySelector('button').click();
      await page.waitForChanges();

      expect(onClick).toHaveBeenCalledWith(/* Check for event */);
      expect(onSuccess).toHaveBeenCalledWith(/* Check for event */);
```

The second expect will always fail, yet the first passes. The only way to have the second work is to do something like this `await new Promise(resolve => setTimeout(resolve, 1000));` after the `await waitOnChange()`.

Worse is that, if I add some console.logs in the `jest.fn` above, I can see that both are getting called properly. `waitOnChanges` is simply not waiting for it.

The button code on click looks something like this:

```tsx
async click() {
    this.click.emit({ /* Some data */ });

    // We use a custom fetch function that returns the data or an error
    const response = await fetch(...);

    if (response instanceof Error) {
      this.error.emit({ /* Some data */ });
      return;
    }

    this.success.emit({ /* Some data */ });
  }
```

**Expected behavior:**
I would expect `waitOnChanges` to wait for all events to emit before resolving, removing the need to have the `setTimeout` hack.

**Steps to reproduce:**
Create a test file with the code shown above that tests a component rendering a button with the onclick linking to the `async click` shown above.

**Comment by manucorporat** [comment]
if click() is async, you need to wait for it too:
```
await element.querySelector('button').click();
```

**Comment by Minivera** [comment]
I did try awaiting on the `click` event, however it was still not waiting for the events to be emitted. The check for `expect(onSuccess).toHaveBeenCalledWith(/* Check for event */);` still fails where the check for `expect(onClick).toHaveBeenCalledWith(/* Check for event */);` succeeds (because it is called before an `await` I suppose).

My button is set-up like this:

```
render() {
    return (
      <button
        type="submit"
        onClick={this.click}
      >
        <slot />
      </button>
    );
  }
```

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
