### ISSUE TITLE
Ability to adjust component tag names during registration

### ISSUE THREAD

**Issue by mexx** [ionic-team/stencil#1783]
**Stencil version:**

```
 @stencil/core@1.2.3
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently the only way to adjust the tag name of a component is to update the `@Component` metadata. However this is not always possible, for example if you have no access to the source code or are not allowed to change it. As well there is currently no way to include different versions of the same component library on the same page, as the component registry can only contain one element for a given name. See related #1342.

**Expected behavior:**

An ability to adjust the tag name upon registration. For example by extending `defineCustomElements` options to provide an optional `adjustName` callback.

**Comment by adamdbradley** [comment]
With the 1.9.x release there will be additional output targets that should be able to provide these abilities.
