### ISSUE TITLE
System.js build can resolve wrong resources url when included with defer attribute

### ISSUE THREAD

**Issue by mofux** [ionic-team/stencil#1787]
**Stencil version:**

```
 @stencil/core@1.2.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Loading stencil's system.js loader with a `defer` flag can resolve the wrong resource path. For example, this will not work:

```html
<script defer src="path/to/stencil/system-js-build.js"></script>
<script src="path/to/some/other/lib"></script>
```

In the case above, the logic to resolve the resource url of the chunks will fail and point to `path/to/some/other/lib`.

https://github.com/ionic-team/stencil/blob/0b4d8142f19d508f5256558dddc9259349f12e92/src/compiler/component-lazy/generate-system.ts#L50-L59

The resolution logic selects all script tags, and then iterates backwards until it finds a script with a `src` or a `data-resources-url` attribute. At the time of executing the deferred script, the other script tag has already made it to the DOM and will be selected instead.

**Expected behavior:**
The system.js resource url should be resolved correctly, even if the entry file is loaded with a `defer` attribute.

**Suggested fixes:**
I guess an IE11 compatible approach would be to give that script tag a unique id or attribute for selection. E.g. `<script data-stencil-namespace="myproject" src="/path/to/stencil/system-js.build.js"></script>`.

Another workaround could be to modify the selector logic to first find a script with the `data-resources-url` attribute, and only if not found continue with the src resolution logic. This way, specifying the `data-resources-url` attribute will always lead to the correct path.

**Comment by tstrohecker** [comment]
Perhaps I do not understand how to include multiple stencil created web components, but this is an example of how I am importing on IE.

`<script type="module" src="/webcomponent/menu/menu/menu.esm.js"></script>
<script nomodule src="/webcomponent/menu/menu.js"></script>
<script type="module" src="/webcomponent/webalerts/web-alerts/web-alerts.esm.js"></script>
<script  nomodule src="/webcomponent/web-alerts/web-alerts.js"></script>`

the nomodule includes are the ones being used.

Because of the backwards forloop on all script tags, its going to attempt to resolve the first include with the second includes src attribute. Just adding a `data-resources-url` will also not fix this, It should somehow be utilizing a namespace of some sort. Unless I am just going about this incorrectly.

**Comment by tstrohecker** [comment]
Actually, I see in the commit that the whole loop has been wrapped in a self invoked function, which should do it.

**Comment by mofux** [comment]
@tstrohecker The problem is only with the system.js script (the one you would load with the nomodule flag). 

Getting the resource url based on the `data-resources-url` attribute is not a general fix for this problem, but at least the logic in the PR #1788 improves the situation in that it will resolve to the correct resources url if the script with `defer` attribute has `data-resources-url` set.

I'm happy to contribute towards a proper solution if you have a suggestion.

**Comment by tstrohecker** [comment]
@mofux I think the only solution would be to consider the namespace of the webcomponent itself. 

We cannot guarantee that the script that is loading is the last one on the page, that would imply no script tag gets loaded onto the dom until the current one is finished executing, which we know is not true. 

Same thing with data-resources-url, what if you have two `data-resources-url` attributes on two different elements.

I think your solution `<script data-stencil-namespace="myproject" src="/path/to/stencil/system-js.build.js"></script>` hits the nail on the head.

that data-stencil-namespace should match the namespace of your webcomponent, and it should be looking for a match on THAT, not on the just simply being the last script tag on the page.

**Comment by mofux** [comment]
I've added support for the `data-stencil-namespace` attribute in https://github.com/ionic-team/stencil/pull/1788/commits/0c5525e3fffee3d47e1dfc11da9071236f24edb0

So the script resolution logic goes as follows:
1. find script via `data-stencil-namespace`
2. find script via `data-resources-url`
3. find the last script with a `src` attribute set

If we were to merge this, we should add a note to the **docs**: 

When loading the nomodule script with a `defer` or `async` attribute, it is recommended to add the `data-stencil-namespace` attribute to the script tag:

```html
<script nomodule async src="/path/to/my-project.js" data-stencil-namespace="my-project"></script>
```

The value should match the `namespace` property in your `stencil.config.ts`.

**Comment by tstrohecker** [comment]
This is a good fix. I've seen some very inconsistent loading from IE11. This should be much more reliable than being the last script loaded. thanks @mofux

**Comment by lotz** [comment]
Unfortunately we are still seeing errors which appear to be related to the two components loading at the same time, possibly due to global namespace pollution? The stack below shows two web components in the same stack, which shouldn't be possible.

![image](https://user-images.githubusercontent.com/3892627/62569625-c4d05380-b85c-11e9-9147-cec56dc9abad.png)

**Comment by mofux** [comment]
@lotz Your problem looks different to the ones I've encountered. How did you include the loader file? Do you have more than one?

If I had to guess, it looks like both components were bundled in the same chunk file (stencil does that automatically if it detects that both depend on each other), which could explain the stack 🤔

**Comment by lotz** [comment]
They are actually two entirely different projects from different repositories, so there's no chance that they've crossed wires at build time. Sorry, I should have clarified that in my original message. 🙂

**Comment by mofux** [comment]
Interesting... is this happening every time, or only sometimes? Only in IE11, or also in other browsers? If not only in IE11, does it also happen if you use the ESM build? Does it also happen when you swap the order of the script tags of these components?

**Comment by lotz** [comment]
It was only sometimes, only in IE11. The ESM builds in Chrome were fine. We didn't try swapping script order, yet.

**Comment by CRHain88** [comment]
> Interesting... is this happening every time, or only sometimes? Only in IE11, or also in other browsers? If not only in IE11, does it also happen if you use the ESM build? Does it also happen when you swap the order of the script tags of these components?

Seeing the same issue consistently when not using esm modules. SystemJS throws the error.

**Comment by Jagget** [comment]
We created custom `loader.js` to bypass the issue:
```javascript
var SS = document.getElementsByTagName('script');
var F = SS[0];
var L = SS[SS.length - 1];
// Last script on the page should have data-resources-url to bypass the issue
L.setAttribute('data-resources-url', '%REPLACE_ME%/dist/uilib/');
if (F.parentNode) {
  var M = document.createElement('script');
  M.src = '%REPLACE_ME%/dist/uilib/uilib.esm.js';
  M.type = 'module';
  F.parentNode.insertBefore(M, F);
  var N = document.createElement('script');
  N.src = '%REPLACE_ME%/dist/uilib/uilib.js';
  N.setAttribute('nomodule', '');
  F.parentNode.insertBefore(N, F);
}
```

And we are using it like 
```html
<script src="%REPLACE_ME%/loader.js" defer></script>
```

Note that using `defer` is crucial for us
