### ISSUE TITLE
Toggling an attribute on a custom element in EDGE doesn't trigger a re-render.

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#1791]
**Stencil version:**
```
@stencil/core@1.1.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Toggling an attribute on a custom element in EDGE doesn't trigger a re-render.

**Expected behavior:**
Changing an attribute on a custom element should update the internal prop and cause the element to re-render.

**Steps to reproduce:**
1. Add a custom element to the page.
2. Use native DOM API to modify an attribute mapped to a prop on that element.

**Related code:**

```tsx
@Component({
  tag: "foo-element",
  shadow: true
})
export class Foo {
@Prop({ reflect: true}) active = false;
render() {
    return (
      <Host>
        { this.active ? <p>active</p> : null }
      </Host>
    );
  }
}
```
```html
  <foo-element id="foo"></foo-element>
```
```js
foo = document.querySelector("#foo");
foo.toggleAttribute("active", true);
```

**Other information:**
This works in all modern browsers with full web component support.
It's only broken in Edge Browser.
Seems to be an issue with the polyfill.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
