### ISSUE TITLE
EBUSY: resource busy or locked, copyfile

### ISSUE THREAD

**Issue by LalitKushwah** [ionic-team/stencil#1793]
**Stencil version:**
1.1.2
```

**I'm submitting a:**
<!-- (check one with "x") -->
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
In monorepo when I am using asserts directory in src then getting EBUSY: resource busy or locked, copyfile. 

**Expected behavior:**
It should be build
**Steps to reproduce:**
Create a monorepo in which some components have assets directory in src.

** Action Taken To Resolve**
clean npm/yarn cache
run build with administrator (using windows)

**Comment by Jason-Abbott** [comment]
I too am having this issue. I made an example repo with details in the README: https://github.com/toba/stencil-win-build

**Comment by LalitKushwah** [comment]
Hello @Jason-Abbott,
I have taken pull the repo you shared. When I created assets folder inside the component created and moved the svg folder inside it then getting no EBUSY error.

**Comment by LalitKushwah** [comment]
I have resolved the issue created  by removing the copy configuration from the stencil.config.ts.

I have copy configuration for coping "assets" folder to the dist and www and by default stencil copies the assets folder without any configuration.

**Comment by Jason-Abbott** [comment]
Thank you. I didn't realize the `assets` folder was special beyond being the default.

**Comment by leonheess** [comment]
Same issue here but for a single file, any ideas? 

Node v16.14.2
Stencil 2.12.1
Windows 10
