### ISSUE TITLE
how can i pass  a function props which return a React.jsx object  to custom content?

### ISSUE THREAD

**Issue by HerSoul** [ionic-team/stencil#1794]
**Stencil version:**

```
 @stencil/core@<1.0.7>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

React.jsx can‘t  compatibility with stencil
**Expected behavior:**

React.jsx return jsx object to stencil Component
**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
 class App extends React.Component {
      componentDidMount() {
        this.refs.bread.routes=routes;
        this.refs.bread.renderItem=this.renderItem;
      }
      renderItem=(info)=>{
        return (<span>
          {info.path}
        </span>)
      }
      render(){
        return (
          <div>
            <mi-breadcrumb ref="bread">
            </mi-breadcrumb>
          </div>
        )
      }
    }
    ReactDOM.render(
      <App/>,
      document.getElementById('root')
    );
  }
```

**Other information:**

**Comment by stanley85** [comment]
I am pretty sure you can pass the react object to your component by simply injecting it. If ref is a react property then dont use this on your component - if it has no ref property declared. You can pass your object including the renderItem method. I am not sure if handing down a render method to a child-component is brilliant or dirty.

`<mi-breadcrumb crumb={this.refs.bread}></mi-breadcrumb>`

**Comment by HerSoul** [comment]
react dont't support 
look react custom element attr/properties https://github.com/facebook/react/issues/11347

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

React and Stencil's JSX implementations are two very different ideas, even if they may seem similar.
