### ISSUE TITLE
Supporting d.ts files get excluded from dist

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#1797]
**Stencil version:**

```
 @stencil/core@1.1.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Supporting `src/components/interfaces.d.ts` file is not included in `dist/types/components/`. 

It is worth noting that `dist/types/components.d.ts` has the correct imports:

```ts
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Foo,
  Bar
} from './components/interfaces';

export namespace Test {
// ...
```

**Expected behavior:**

The output build includes `dist/types/components/interfaces.d.ts`.

**Steps to reproduce:**

*Assumes structure from component starter

1. Add `src/components/interfaces.d.ts` (see below).
2. Add a simple component and import from `interfaces.d.ts`
3. Run the Stencil build.

**Related code:**

```tsx
// interfaces.d.ts
export type Foo = "foo" | "Foo";

export type Bar = "bar" | "Bar";
```

**Other information:**

A workaround for this is to drop the declaration file extension and just use `.ts` (e.g., `interfaces.ts`)

**Comment by manucorporat** [comment]
Can you test `1.15.0-2`?

**Comment by jcfranco** [comment]
@manucorporat Sorry for the delay. Sadly, I don't see the interfaces file included. Here's a repro repo if it helps: https://github.com/jcfranco/stencil-declaration-files-not-included-in-dist
