### ISSUE TITLE
How to create stencil library base on @ionic/core?

### ISSUE THREAD

**Issue by Jimmysh** [ionic-team/stencil#1800]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by manucorporat** [comment]
Hi! we want to keep github issues for actual issues. Please refer to our slack for support!
https://stencil-worldwide.herokuapp.com/
