### ISSUE TITLE
CSS Variables do not get replaced for IE 11 on --prerender

### ISSUE THREAD

**Issue by cthos** [ionic-team/stencil#1805]
**Stencil version:**

```
@stencil/core@1.2.5 
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running a `--prerender` build on an app based on the `stencil-component-starter` CSS variables for components do not get replaced with concrete values when running in IE.

If you run `npm start --es5`, these variables _do_ get replaced properly.

**Expected behavior:**

`--prerender` builds should replace CSS variables with concrete values like the `es5` build does.

**Steps to reproduce:**

Reproduction Repo: https://github.com/cthos/var-ie-repro

**Related code:**

None aside from the repo.

**Other information:**

Oddly enough I can't get this to recur on something made from the _app starter_, with CSS variables in the related .css files, even with all the same permutations. I think there's something happening with either a polyfill or deep in the compiler which I don't fully understand.

Importing the components into a Stencil App Starter likewise _mostly_ works.

Here are some issues that I think are related, but maybe not 100% related enough to consider this a duplicate of them?

#1200 
#1772 
#1804 (?)

**Comment by cthos** [comment]
Based on a comment in Slack, I'm not trying to prerender the `dist` bundle, but the `www` bundle to produce something of a "brochure site" of the component lib and have it be prerendered.

**Comment by splitinfinities** [comment]
Hey @cthos! Good to see ya! Can you do me a favor and let me know if this issue still exists on newer versions of Stencil? This should have been addressed, but if not let me know.
