### ISSUE TITLE
Add option to disable CSS shim (for CSS variables in IE 11) at build time

### ISSUE THREAD

**Issue by lotz** [ionic-team/stencil#1806]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running in IE 11, the CSS shim provided to support CSS variables in IE 11 aggressively uses the fetch polyfill to load all stylesheets on the page (to find an create CSS variables). If stylesheets are loaded from a different domain, like a CDN, errors related to CORS access are thrown and show up in the console.

It would be nice to be able to disable the CSS shim at build time via a build config flag. We aren’t using CSS variables currently, and the stylesheets in our CDN certainly do not include variables, so attempting to load and process them is additional processing which is not needed.

**Expected behavior:**

A built time config flag to disable the CSS shim.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
This is now possible with `config.extras.cssVarsShim = false`

https://stenciljs.com/docs/config-extras#cssvarsshim
