### ISSUE TITLE
Tests with 404 and JSHandle console.error occurred, but no information whats wrong

### ISSUE THREAD

**Issue by dutscher** [ionic-team/stencil#1807]
Stencil version:

 @stencil/core 1.2.2
 puppeteer-core 1.17.0
I'm submitting a:

[x] bug report
[x] feature request
[ ] support request

Current behavior:

When i wrote a spec or e2e test in my application, i got errors between my tests and they look like an error but with no information.
![image](https://user-images.githubusercontent.com/14682/63030566-cc25db80-beb2-11e9-9f7f-598c765f6dba.png)

I found the place where the error messages will be logged:
https://github.com/ionic-team/stencil/blob/a595fe4035e198c40a32a8074af030b2ac0e7b35/src/testing/puppeteer/puppeteer-page.ts#L303

I fixxed that locally for me with:
![image](https://user-images.githubusercontent.com/14682/63031094-bfee4e00-beb3-11e9-9a42-6df1306691a0.png)
`
function consoleMessage(c) {
    const type = c.type();
    if (typeof console[type] === 'function') {
      const text = c.text() + '\n';
      if(text.indexOf('JSHandle@error') !== -1){
        console[type](text, c.args()[0]._remoteObject.description);
      } else if(text.indexOf('404') !== -1){
        console[type](text, c.location().url);
      } else {
        console[type](text);
      }
    }
    else {
        console.log(type, c.text());
    }
}
`

Because whats an error message with no details? or a 404 message with no path?
With my fix, we got an 404 with the location and an js error with a stacktrace.

![image](https://user-images.githubusercontent.com/14682/63030837-4eae9b00-beb3-11e9-8c99-e23350a4d563.png)

Can you please fix this?

Thanks a lot.
Cheers dutscher

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
