### ISSUE TITLE
Polyfills does not work at Edge browser with script tag

### ISSUE THREAD

**Issue by sean0923** [ionic-team/stencil#1809]
**Stencil version:**

```
"@stencil/core": "^1.0.7"
```

**I'm submitting a:**

[x] bug report

**Current behavior:**

Polyfills does not work at Edge browser with script tag

**Expected behavior:**

Polyfills should work at Edge browser with script tag

**Related code:**

```html
  <script type="module">

    import { applyPolyfills, defineCustomElements } from 'https://unpkg.com/<my-component>/loader/index.mjs';

    applyPolyfills().then(() => {

      defineCustomElements(window);

    });

  </script>

```

**Other information:**

Code above is inside of .html file. It works in Chrome browser.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
