### ISSUE TITLE
Incorrect rendering in Edge with sibling slots (default and named)

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#1811]
**Stencil version:**

```
 @stencil/core@1.2.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

In Edge, if you have a default slot with fallback content next to a named slot, the default slot won't get rendered if the component receives content for the named slot.

**Expected behavior:**

The default slot to display the fallback content next to the named slot content.

**Steps to reproduce:**

Use the following markup with the component code below:

```html
<my-test><div slot="secrets">shhh</div></my-test>
```

**Related code:**

```tsx
import {
  Component,
  Host,
  h,
} from "@stencil/core";

@Component({
  tag: "my-test",
  shadow: true
})
export class MyTest {
  render() {
    return (
      <Host>
        <slot>42</slot>
        <slot name="secrets"></slot>
      </Host>
    );
  }
}
```

**Other information:**

Generated HTML in Edge (Microsoft Edge 44.17763.1.0):

```html
<my-test className="sc-my-test-h hydrated sc-my-test-s"
         data-hmr="047118710229"><!---->
  <slot-fb className="sc-my-test" hidden="">42</slot-fb>
  <div slot="secrets">shhh</div>
</my-test>
```

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
