### ISSUE TITLE
Stencil build spawns too many child processes on CircleCI

### ISSUE THREAD

**Issue by dangodev** [ionic-team/stencil#1812]
**Stencil version:**

```
 @stencil/core@1.2.5
```

**I'm submitting a:**

[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When running `stencil build` on CircleCI, it frequently encounters the following error:
```
[29:58.9]  bundling components started ...
[29:59.8]  copy finished (0 files) in 957 ms
[30:00.7]  generate styles finished in 1.77 s
internal/child_process.js:394
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:540:9)
    at Object.fork (child_process.js:108:10)
```

This happens because of the `child_process` library in Node for spawning parallel workers during the **bundling** stage of Stencil CLI’s build process. Locally, this usually works, but in CI, with multiple jobs running in parallel, it frequently hits errors.

Jest had a similar problem on CircleCI with spawning child processes, but because of their [`--maxWorkers` flag](https://jestjs.io/docs/en/cli#maxworkers-num-string) this is controllable.

**Expected behavior:**

**Steps to reproduce:**
Run `stencil build` on CircleCI, on multiple jobs running in parallel (I can provide a config file if needed)

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

Could `stencil build` gain a `--maxWorkers` flag, or option in the config to limit the number of simultaneous child processes it uses? It’s necessary for us running Stencil on CI, and deploying via CI.

**Comment by adamdbradley** [comment]
The CLI has `--max-workers` and `--ci` command.
