### ISSUE TITLE
Element.toggleAttribute() no longer polyfilled

### ISSUE THREAD

**Issue by dgibson666** [ionic-team/stencil#1813]
**Stencil version:**
@stencil/core@1.1.7

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Element.toggleAttribute() is throwing an error in IE11. I have used it in the past and assumed it was polyfilled by Stencil, but that does not seem to be the case now. 

**Expected behavior:**
Element.toggleAttribute() is polyfilled and works on all browsers that Stencil supports.

**Other information:**
There's a simple polyfill on the MDN page here: https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute

**Comment by manucorporat** [comment]
while we could polyfill it, polyfills only apply to the ES5 build, iOS11 does not support this feature either. I would suggest to avoid using this API

**Comment by dgibson666** [comment]
Thanks for your response - I wasn't aware of the iOS case.
