### ISSUE TITLE
Cannot use defineCustomElements to integrate an external Stencil component into my current component

### ISSUE THREAD

**Issue by TommiChi** [ionic-team/stencil#1815]
**Stencil version:**
```
 @stencil/core@1.1.7
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Javascript error "TypeError: Cannot read property '$instanceValues$' of undefined"

**Expected behavior:**
External Stencil component successfully renders

**Steps to reproduce:**
1. Import the "defineCustomElements" method from the required external Stencil component
eg. `import { defineCustomElements } from 'external-component/loader';`
2. Execute "defineCustomElements(window)"

**Related code:**

```tsx
import { defineCustomElements } from 'external-component/loader';
defineCustomElements(window);
```

**Other information:**
defineCustomElements works as expected when used in other frameworks such as Angular, but not when called inside of a Stencil component (.tsx file)

**Comment by TommiChi** [comment]
Updating my version of Stencil to 1.2.5 yields the same behaviour

**Comment by TommiChi** [comment]
Hi guys,

Does anyone have some feedback for me?
Do you need more information?
Are there additional details I need to add to the ticket?

Thanks!

**Comment by arjunyel** [comment]
When using stencil in stencil instead of using that defineCustomElements function try to just import the library of the other component. Examples:

https://github.com/ionic-team/ionic-pwa-toolkit/blob/master/src/global/app.ts

https://stenciljs.com/docs/distribution#in-a-stencil-app-starter-app

**Comment by splitinfinities** [comment]
Hey folks! This is on an old version of Stencil. If you are still having this issue on latest versions, please make a new ticket!
