### ISSUE TITLE
Is it possible to render HTMLElement[] inside JSX Element?

### ISSUE THREAD

**Issue by luis-cortina** [ionic-team/stencil#1817]
Hi: 

I'm building a component that transforms the input into a different HTML structure, this is because I want to use a 3rd party css library and I need to follow a certain structure but at the same time, it doesn't make sense for my component consumers to follow it.
How the component is used:
<tabs>
```
  <tab title='title'>
    <tab-content>
      ...
    </tab-content>
  </tab>
</tabs>
```

I want to transform that into something else like this:
```
<div class="tabs">
  <div class="tab">
    <span class="tab-title">title</span>
    <div class="tab-content">
    ...
   </div>
  </div>
</div>
```

I can do the transformation using {innerHtml} but the problem is that if there are any elements inside the tab-content that have event listeners, those won't work anymore.
I can get an HTMLElement[] for the child content but I haven't found a way to render it using the render function.

Any ideas?

Luis

**Comment by maxjustus** [comment]
Unfortunately there's no simple way to introspect on event listeners and copy them to a new DOM node. And I don't think alternatives to innerHtml aren't much better for your use case. One approach to dealing with event listeners would be to add any event listeners to an element that wraps the tab structure and won't be transformed and have those event listeners check whether e.target is the thing you want to trigger the event for.

**Comment by luis-cortina** [comment]
Thanks @maxjustus 
I ended up changing my components to avoid using innerHtml. The one thing I would like to explore if is possible, is to ind a way to create JSX Elements from HTMLElement objects.
