### ISSUE TITLE
Changes to readme files in watch mode don't trigger docs-custom generator

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil#1822]
**Stencil version:**

```
 @stencil/core@1.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Editing a readme while in `--watch` mode does not run the docs-custom generator function.

**Expected behavior:**

Editing a readme while in `--watch` mode should run the docs-custom generator function, since the jsonDocs will have changed.

**Steps to reproduce:**

- Add a docs-custom generator to the stencil config like:
```ts
{
      type: 'docs-custom',
      generator(docs) {
        console.log('umm')
      }
}
```
- Run `stencil build --dev --serve --watch --docs`
- See `umm` print to console 🔥 
- Edit a component's `readme.md`
- Compiler sez `[20:46.4]  changed file: components/readme.md`
- Generator doesn't run and no `umm` in console 😭

**Comment by claviska** [comment]
Bumping as this is still an issue in the latest version 😭

**Comment by manucorporat** [comment]
This should be fixed in latest release

**Comment by snaptopixel** [comment]
Just getting around to trying this out @manucorporat it doesn't appear fixed, also, the cli no longer reports than a md file was modified.

I have output targets for docs-readme and docs-json, also passing `--docs` and `--docs-readme` to the cli. When I edit any readme.md or .md file in a usage folder, nothing happens.

**Comment by snaptopixel** [comment]
@manucorporat this isn't working in 1.13.0, markdown changes are not detected (in readme, or usage) I'm not using docs-custom, but am using docs-json and docs-readme

**Comment by snaptopixel** [comment]
I tried to pull down the latest 1.14.x but it doesn't run on my machine, has issues with axios
