### ISSUE TITLE
Stencil build fails at first run, but completes the build on second run without any changes to files

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [ionic-team/stencil#1823]
**Stencil version:**
```
 @stencil/core@1.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When ``npm run start`` is executed, stencil build breaks by throwing the following error
```
         Global Script: src/global/app.js
           The code to be executed should be placed within a default function that is
           exported by the global script. Ensure all of the code in the global script is
           wrapped in the function() that is exported.
```
But after going inside some random file/ going inside ``index.html`` file and just pressing ``Ctrl + S`` will re-run the build and this time the build gives a successful result without making any changes to the code

**Expected behavior:**
Build should not break at the first instance if everything is ok.

**Steps to reproduce:**
I am sharing a git repo to reproduce the error and sharing a URL where i did a screen recording of the behavior.

Git repo - https://github.com/JayaKrishnaNamburu/stencil-global-script-error
Video link - https://drive.google.com/file/d/1X8z8LKWxx3fYTF3QaCcFV8pZfiQq_n8n/view?usp=sharing

**Comment by lucascvassalli** [comment]
I came here to report the exact same issue. Built it with NPM on Debian testing amd64.

**Comment by reload-kurt** [comment]
Having the same issue, rewrote `node_modules/dist/collection/global.js` from 
`import { setMode } from '@stencil/core';
setMode((el) => el.tagName === 'ION-ICON' ? el.mode || el.getAttribute('mode') : null);`

to

`import { setMode } from '@stencil/core';

export default () => {
setMode((el) => el.tagName === 'ION-ICON' ? el.mode || el.getAttribute('mode') : null);
}
`

as a temporary solution

**Comment by JimGaleForce** [comment]
my "stencil build --dev --watch --serve" fails for the standard app.ts (app.js) with:
`[ ERROR ]  Global Script: ./src\global\app.js
           The code to be executed should be placed within a default function that is exported by the global script.
           Ensure all of the code in the global script is wrapped in the function() that is exported.`

where app.ts is only:
`import '@ionic/core';`

both stencil and ionic are absolute latest (1.3.0 and 4.8.0).

**Comment by cptflammin** [comment]
Same here and the same solution:
"But after going inside some random file/ going inside index.html file and just pressing Ctrl + S will re-run the build and this time the build gives a successful result without making any changes to the code"

**Comment by mikkokon** [comment]
If you deploy your app f.ex. with Netlify; deploy fails because Netlify system run command "npm install" internally in their pipes.
So, you can't make your tricks for node modules  , "Ctrl + S", etc ...
...waiting for fixing into node packages  :-)

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
