### ISSUE TITLE
Still seeing falsey JSX issues with empty string

### ISSUE THREAD

**Issue by dgibson666** [ionic-team/stencil#1824]
**Stencil version:**
 @stencil/core@1.3.0

**I'm submitting a:**
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
We experienced issues related to this fix previously and downgraded to Stencil 1.1.7.
https://github.com/ionic-team/stencil/issues/1780

I just upgraded to 1.3.0 and am still experiencing some issues related to empty strings. In particular, when rendering the default `<option value="">Label</option>`, no value is rendered, and therefore it's passing the label as the value, which causes an application issue. It is working as expected when the value="0", however.

**Expected behavior:**
Render an empty option value: `<option value="">`

**Comment by stanley85** [comment]
What happens if you pass this - just a quick thought
`<option value={""}>`

**Comment by dgibson666** [comment]
Nope, this doesn't work. It also wouldn't work if I'm looping over JSON values either and the default blank value option is included in it, e.g.,:

<option value={optionsJSON[i].value} selected={optionsJSON[i].value == this.value ? true : false}>
              {optionsJSON[i].label}
</option>

This seems somewhat minor, but is a show stopper for breaking application functionality and stopping us from upgrading past 1.1.7.

**Comment by dgibson666** [comment]
Nope, this doesn't work. It also wouldn't work if I'm looping over JSON values either and the default blank value option is included in it, e.g.,:

<option value={optionsJSON[i].value} selected={optionsJSON[i].value == this.value ? true : false}>
              {optionsJSON[i].label}
</option>

This seems somewhat minor, but is a show stopper for breaking application functionality and stopping us from upgrading past 1.1.7.

**Comment by dgibson666** [comment]
Any update on this issue? It seems pretty simple and related to one that was fixed, but this case just fell through the cracks. Yet it's significant enough to keep us from upgrading.

**Comment by psmyrdek** [comment]
I'm on `1.2.4` and it's causing us headaches :/ One option is to introduce "default default" like `value="EMPTY"` and then filter it out in `onChange` handler, but as you can guess, it's not something we'd expect.

**Comment by dgibson666** [comment]
Thanks, I'll check it out to confirm.

**Comment by dgibson666** [comment]
This appears to have been fixed. Thank you.
