### ISSUE TITLE
2 Web Components in ng7 App, polyfills issue in IE11

### ISSUE THREAD

**Issue by pantro14** [ionic-team/stencil#1825]
This is not a bug, but I'm struggling with this specific snerario.

I have created 2 web-components (WC), aka WC1 and WC2 (both independent of each other).
Both must be added to the same parent angular7 app. 

Here is the issue, ONLY on IE11, and only the first load (refreshing the web page solves the issue, but this is not an option for my customer).

I'm having a polyfill conflic trying to apply folyfill for both WCs, following this [documentation](https://stenciljs.com/docs/angular#edge-and-ie11-polyfills), this is only explained for 1 WC, but what if have 2?
I tried to do something like this but it's not working well.

```
import * as wc1Loader from 'wc1';
import * as wc2Loader from 'wc2';

wc1Loader.applyPolyfills().then(() => {
  wc1Loader.defineCustomElements(window);
});
wc2Loader.applyPolyfills().then(() => {
  wc2Loader.defineCustomElements(window);
});
```

Firstly, is this correct, or I need to apply another implementation?

**Comment by rjaguilar** [comment]
have you tried this?

```
import { applyPolyfills, defineCustomElements as wc1 } from 'wc1';
import { defineCustomElements as wc2 } from 'wc2';

applyPolyfills().then(() => {
    wc1(window);
    wc2(window);
})
```

**Comment by jgiordano-rms** [comment]
I'm having a similar issue, but it seems the issue is only one of the `defineCustomElements` calls are working and the other one is either being ignored or is overriding the other (not sure what though). I am getting `instance is undefined` when trying to use components from the second imported component library, but not when only using components from the first.

**Comment by jgiordano-rms** [comment]
This isn't localized to only angular, this is happening across all frameworks.
