### ISSUE TITLE
Emitted assets in rollup plugin are ignored

### ISSUE THREAD

**Issue by stalniy** [ionic-team/stencil#1833]
**Stencil version:**
```
 @stencil/core@1.3.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm writing a rollup plugin which emits additional assets when a specific file (`articles.mapping`) is imported. The issue is that emitted assets are not written to the disk (or probably not written anywhere or rewritten by stencil), that's why my app does not work. 

The same plugin works as expected with rollup@1.20.x and rollup@1.19.1 (which is used by stencil)

**Expected behavior:**

emitted assets should appear in `www/assets` folder when they emitted from rollup plugin by using [`this.emitFile` API](https://rollupjs.org/guide/en/#thisemitfileemittedfile-emittedchunk--emittedasset--string)

**Steps to reproduce:**
1. clone https://github.com/stalniy/freaksidea-pwa
2. run `npm run build`
3. check `www` folder for existance of `articles.all.en.json` or `articles.all.uk.json`. Emitted assets **do not** exist

To check the result with rollup:
1. run `npm run build.rollup`
2. check `www` folder for existance of `articles.all.en.json` or `articles.all.uk.json`. Emitted assets  **exist**

**Comment by stalniy** [comment]
stencil/core v1.7.4 the same issue

**Comment by stalniy** [comment]
it's a pitty that nobody can even provide some guidance how to fix or workaround. It's a blocker for me, I can't use stencil!

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

After you upgrade, could you let me know if there are any actionables we can take after adding on to the rollupPlugins in the config?

```javascript
export const config: Config = {
  // ...
  rollupPlugins: {
    before: [
      // Place your plugin her...
    ],
    after: [
      // ...or here
    ],
  },
  // ...
},
``` 

Let me know if you need anything else!

**Comment by stalniy** [comment]
Common guys, it took 2 years for somebody to respond to my issue :) Definitely, stencil is not my choice anymore, I switched to lit-html. So, I don't know whether the issue is still reproducable
