### ISSUE TITLE
[bug] version 1.3.0 breaks test coverage reporting

### ISSUE THREAD

**Issue by vidarc** [ionic-team/stencil#1834]
**Stencil version:**

```
 @stencil/core@1.3.0 and greater
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The test coverage reports are reporting on the compiled stencil code, so test coverage is not what it used to be pre 1.3.0. Coverage is also not lined up in the report files. Pre compiled code is shown, but compiled code is being used, so things like line coverage are not matched to their appropriate line.

**Expected behavior:**
Would expect coverage results to only apply to my code, not the code that stencil applies as well.

https://github.com/ionic-team/stencil/commit/225f488a4e39ef6cd8dfa4e0ae5fed75da136de2
this is the commit where the change occurred. 

using newSpecPage for testing somewhat resolves this, but the mismatching makes it impossible to find out what isn't being covered. for example, i have a test where 8/9 functions are covered. the last function is a stencil function that i have no idea how to cover and it is hidden in the reporter files

**Comment by d0whc3r** [comment]
any alternative to show correct coverage in tsx file?

**Comment by romulocintra** [comment]
Try to override stencil test config with all you need to pass to jest. Coverage is working for me using my own config instead of default

**Comment by d0whc3r** [comment]
yes, coverage is working but lines in reports are not matching code, some coverage lines indicates comments or blank lines

**Comment by d0whc3r** [comment]
![image](https://user-images.githubusercontent.com/1378986/65041326-d2e2bb00-d956-11e9-9e49-b9f5c67df63b.png)

**Comment by d0whc3r** [comment]
And using stencil 1.2.5
![image](https://user-images.githubusercontent.com/1378986/65041592-6916e100-d957-11e9-89ec-4339c1c025dc.png)

**Comment by silverspectro** [comment]
Seems to be fixed in 1.2.5, but it is absolutely not documented nor foundable (if i can say)

**Comment by d0whc3r** [comment]
Yes, but in 1.3.0+ isn't working

**Comment by LalitKushwah** [comment]
Yes, @d0whc3r For me too it is not working in 1.3..x+

**Comment by vidarc** [comment]
just tried out version 1.7.0 and the coverage looks to be working again

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
