### ISSUE TITLE
Stencil One produces less readme.md details, missing method parameter and return value documentation.

### ISSUE THREAD

**Issue by apillard** [ionic-team/stencil#1836]
**Stencil version:**

```
 @stencil/core@1.3.2
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running `stencil build` the readme.md documentation auto-generation should create documentation for method parameters and return types. When migrating a project from Stencil 0.18.0 to 1.3.2, the generated readme.md loses details

**Expected behavior:**

**Steps to reproduce:**

run 'stencil build'

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

Previous ticket that was fixed for 0.X but regressed under 1.X
https://github.com/ionic-team/stencil/issues/954

**Comment by manucorporat** [comment]
It should be fixed
