### ISSUE TITLE
ShadowDOM and CSS scoping polyfills scale poorly in IE11

### ISSUE THREAD

**Issue by abdulmhamid** [ionic-team/stencil#1837]
**Stencil version:**

```
 @stencil/core@1.3.0  // issues seen since initial install of 1.1.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When using large numbers of custom elements with shadowDOM or style scoping enabled, the web components can take an unreasonable amount of time to load (in general and as compared to other browsers). When shadowDOM and scoping are turned off performance improves dramatically but this would negatively affect our intended experience in other browser.

We attempted to create separate builds to allow use of shadow when usable and without in IE but ran into issues with the conditionality of decorator properties per https://github.com/ionic-team/stencil/issues/398 and https://github.com/ionic-team/stencil/issues/458.

***Performance Stats*** (for 100 instances of each element)

| **Component Name** | **Chrome**  |  **IE 11**  |  
|---|---|---|
|**custom-calendar** |~700ms | ~13500ms |  
| **custom-input** |  ~250ms | ~4650ms  | 
| **custom-dropdown** | ~1150ms | ~196,000ms  | 
| **custom-select** | ~1000ms | ~257,000ms (~153,000ms w/o optgroups)|

**Expected behavior:**
We would expect element load times to be within an order of magnitude of Chrome counterparts.

**Steps to reproduce:**
Render 100 instances of components all using shadowDOM, some with slotted content and nested webcomponents.  See snippet below for test code used.

**Related code:**

```tsx
// html
<custom-btn color="primary" class="perf">Test Element Performance</custom-btn>
<div class="performance-test-container"></div>

// js
 var calendarSeed = '<custom-calendar days-of-week-checksum="62" label="Calendar Label" aria-label="Calendar aria-label" value="2019-06-24" placeholder="placeholder text" button-label="button-label text" disabled-msg="disabled-msg text" disclaimer="disclaimer text" calendar-label="calendar-label text" ></custom-calendar>';

var inputSeed = '<custom-input maxlength="62" label="Calendar Label" aria-label="Calendar aria-label" value="2019-06-24"></custom-input>';

var dropdownSeed = '<custom-dropdown icon="options" aria-label="Select an Option"><custom-dropdown-item value="first" onclick="dropdownItemClick(event)" removable>First</custom-dropdown-item><custom-dropdown-item value="second"  onclick="dropdownItemClick(event)" removable>Second</custom-dropdown-item><custom-dropdown-item separator ></custom-dropdown-item><custom-dropdown-item value="third" onclick="dropdownItemClick(event)"  removable>Third</custom-dropdown-item><custom-dropdown-item value="fourth" onclick="dropdownItemClick(event)"  removable>Fourth</custom-dropdown-item></custom-dropdown>';

var selectSeed = '<custom-select label="Field label" searchable><custom-optgroup label="Optgroup 1"><custom-option value="1" display="Option 1">Option 1</custom-option><custom-option value="2" display="Option 2">Option 2</custom-option><custom-option value="3" display="Option 3" disabled>Option 3</custom-option><custom-option value="4" display="Option 4">Option 4</custom-option></custom-optgroup><custom-optgroup label="Optgroup 2"><custom-option value="5" display="Option 5">Option 5</custom-option><custom-option value="6" display="Option 6">Option 6</custom-option><custom-option value="7" display="Option 7" disabled>Option 7</custom-option><custom-option value="8" display="Option 8">Option 8</custom-option></custom-optgroup></custom-select>';

document.querySelector('.test-performance').addEventListener('click', function() {
    var element = 'select';
    var testElement = document.querySelector('.performance-test-container');
    var markup = testElement.innerHTML;

     if (!!markup) {
         markup = '';
      } else {
          var seed;
          switch (element) {
              case 'calendar':
                  seed = calendarSeed;
                  break;
              case 'input':
                  seed = inputSeed;
                  break;
              case 'dropdown':
                  seed = dropdownSeed;
                  break;
              case 'select':
                  seed = selectSeed;
                  break;
          }

          for (var i = 0; i < 100; i++) {
               markup += seed;
          }
    }
    testElement.innerHTML = markup;
});
```

**Other information:**
- In our testing we found `shadow: true` and `shadow: false, scoping: true` to perform similarly poorly.  The inefficiencies seem to be coming from the scoping shim.

- We ran these tests with the same elements using a combination of other libraries and the webcomponentsjs polyfill.  Stencil elements we much faster in Chrome but slower in all but one test in IE.  

- I am more familiar with webcomponentsjs polyfill than I am with the internals of the stencil library but I am curious about how this library watches VDOM changes and how it crawls for CSS variables.

What options are available other than having to maintain separate codebases?

**Comment by schadenn** [comment]
We're also experiencing big performance issues in IE11. A little remark on your "Other information" first point: `shadow: true` and `scoped: true` will behave the same in IE11. `scoped: true` will enable the shadow css polyfill for every browser, while `shadow: true` will use shadow DOM in browser that support it and shadow css polyfill in those that don't (IE11).

I'd really like to know what the thoughts of someone within the Stencil team are regarding this topic.

I think it's hard for them to do something. The scoped css polyfill is coming from Google - so they'd need to optimize (see [stencil/src/utils/shadow-css.ts](https://github.com/ionic-team/stencil/blob/master/src/utils/shadow-css.ts)). 

Also from what I can see, IE11 is not really in the Stencil roadmap. It'll be dead hopefully sooner than later anyways, so I'd understand if there isn't much effort to be put into IE11 optimization.

**Comment by abdulmhamid** [comment]
Right but our previous implementation used the Google polyfill directly and had much better render performance in IE. We imported the full webcomponents-bundle and styled the elements as we registered them or when the CSS was updated.

In the short term, I have forked our package and opted out of shadowDOM and style scoping in IE.

**Comment by adamdbradley** [comment]
With the 1.9.x prereleases of stencil, you can now opt out of using the css vars polyfill: https://github.com/ionic-team/stencil/commit/b3b69933528b7106ff69720797ecaabec74e4546
