### ISSUE TITLE
 Cannot find name 'AsyncIterableIterator'.

### ISSUE THREAD

**Issue by vandres** [ionic-team/stencil#1839]
**Stencil version: 1.3.2**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

After updating to the newst version, this error message occured for me `Cannot find name 'AsyncIterableIterator'.` I had to change my `tsconfig.json` and add `esnext.asynciterable` to the `lib`:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": false,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2017",
      "esnext.asynciterable"
    ],
    "moduleResolution": "node",
    "module": "esnext",
    "target": "es2017",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "react",
    "jsxFactory": "h"
  },
  "include": [
    "src",
    "types/jsx.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Expected behavior:**

Maybe a note for updating.

**Steps to reproduce:**

It also happens with this simple way:

```
npm init stencil
npm install @stencil/core@latest --save-exact
stencil build
```

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by david-poindexter** [comment]
I am having the same issue and the above workaround seems to work.

**Comment by mburger81** [comment]
I have the same issue, should we adopt this workaround as official solution?
