### ISSUE TITLE
dist/esm/index.mjs it's empty 

### ISSUE THREAD

**Issue by JEricaM** [ionic-team/stencil#1840]
**Stencil version:**
```
 "@stencil/core": "^1.3.0"
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I've developed a component but when I install it in another project, this file "dist/ems/index.mjs" it's empty.
I don't understand why it's empty because it is generated automatically and referenced by default in the json package.

```
"es2015": "dist/esm/index.mjs",
"es2017": "dist/esm/index.mjs",
```

**Expected behavior:**
I think that the index.mjs file should not be empty because it's needed for make the component work.

**Steps to reproduce:**
- Create a stencil component
- Import in a project that use es2015/es2017 
- See that the component don't work.

**Comment by schadenn** [comment]
I was asking the same question in the Stencil Slack. Those index files are supposed to be empty. If you want to use the components in a different project, you wouldn't do:
`import ... from { myStencilComponents }`.
Instead you want to: 
`import ... from { myStencilComponents/loader }`

There is another package.json in this folder that has `main`, `module`, `es2015` etc. resolution targets specified.

**Comment by beenotung** [comment]
In stencil 2.x the file 'dist/esm/index.mjs' referenced by 'es2015' and 'es2017' are missing (instead of being empty), is this expected behavior?
