### ISSUE TITLE
"excludeSrc" config option not working

### ISSUE THREAD

**Issue by lufego** [ionic-team/stencil#1843]
**Stencil version:**

```
 @stencil/core@^1.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Story file is inserted in the final dist collection folder

**Expected behavior:**
Prevent the story file that goes in the same directory as my component from being inserted in the final collection dist folder

**Steps to reproduce:**
I have the following structure:
```
stencil  
│
└───dist
│   └───collection
│       └───components
│           └───image-container
│                 image-container.css
│                 image-container.js
│                 image-container.stories.js //this file shouldn't be here
│   
└───src
    └───components
        └───image-container
              image-container.css
              image-container.tsx
              image-container.stories.js // this file is located here
```

**Related code:**
In my `stencil.config.js` I have:

```js
export const config: Config = {
  namespace: 'stencil',
  plugins: [
    postcss({
      plugins: [
        postcssCustomProperties({preserve: false}),
      ],
    })
  ],
  excludeSrc: ['**/*.stories.*'],
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'docs-readme'
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    }
  ]
};

```

but it still copies the file.

**Comment by Gomah** [comment]
@lufego I have a similar [config](https://github.com/Gomah/bulmil/blob/master/stencil.config.ts#L9) & it works for me, weird.

**Comment by jesseer9** [comment]
I'm encountering the same issue.  If I were to put all my stories under one folder, no nested sub-directories, then it works.  Also using glob pattern excludeSrc: ['**/*.stories.*']

Jessee

**Comment by LeeBurton** [comment]
"excludeSrc" is deprecated, it seems, and should be replaced by "exclude".

**Comment by Poimen** [comment]
In case someone else trips over this issue, you can fix this in the `tsconfig.json` by adding to the `exclude` patterns:
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": false,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2017"
    ],
    "moduleResolution": "node",
    "module": "esnext",
    "target": "es2017",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "react",
    "jsxFactory": "h"
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules",
    "**/stories"
  ]
}
```
