### ISSUE TITLE
SVG's viewBox is set to lowercase

### ISSUE THREAD

**Issue by aztack** [ionic-team/stencil#1847]
**Stencil version:**

```
@stencil/core@1.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
svg's viewBox attribute is lowercase causing the svg's size set to 0x0

**Expected behavior:**
viewBox attribute not set to 'viewbox'

**Steps to reproduce:**
https://github.com/aztack/functional-svg-bug

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**
There should be a white arrow before `Buttons`.
I searched the issues and found https://github.com/ionic-team/stencil/issues/1247 which is marked 'fixed'.

![image](https://user-images.githubusercontent.com/782871/64341289-9cce3e80-d01a-11e9-9734-69b768ef898e.png)

But, if I put a svg tag inside the render function, it will be rendered correctly: 

![image](https://user-images.githubusercontent.com/782871/64341899-f5520b80-d01b-11e9-8961-e898b3a01b5a.png)

Maybe it's hard to detect that one component is using a functional component which contains svg tag.
What about give compiler a hint `hasSvg`:

```tsx
@Component({
  hasSvg: true
});
```

**Comment by markargo** [comment]
appears to be fixed in 1.5.2

**Comment by aztack** [comment]
The bug is gone after upgrade @stencil/core to 1.5.2.

**Comment by eshtadc** [comment]
This has re-appeared now in 1.7.1 (and in some 1.6 I believe)

**Comment by mure** [comment]
This was making me lose my mind! I could not for the life of me figure out why my SVG wasn't scaling.

**Comment by mikaelkaron** [comment]
I get this in `2.18.1` as well, but only if the `svg` is defined inside a functional component
