### ISSUE TITLE
Mechanism for Force Update

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#185]
**Stencil version:**

```
@stencil/core@0.0.6-0
```

**I'm submitting a ...**
[x] feature request

**Current behavior:**
Components are rendered whenever there is a change to a `Prop` or `State` property.  If a `State` property is a complex object or array and a nested value is changed then the top level `State` property needs to be updated in order for the component to render again.

**Suggested behavior:**
There are some use cases where a `State` property does not fit the immutable pattern which makes it awkward to get the component to render.  For example, if a state property references a shared object that generates `changed` events then the component should respond to the `changed` event and render again.  If this object is owned by an external service then it may not be appropriate to copy the object properties into a new instance (since that would lose future changes to the object).

A current workaround is to add another `State` property that is a version counter and change it whenever the referenced object has changed.  This seems like a bit of a hack though.

Suggestion: have a method available on the component to trigger a component render.  React uses `this.forceUpdate()`.  This allows you to preserve the references to shared data instances and still render the component when the data has changed.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you mind posting a repo that shows the issue you are describing?

**Comment by cjorasch** [comment]
Consider the use case where you want to use a component to display information about a user.  

``` typescript

// my-interfaces.ts
export interface IUser {
  first?: string;
  last?: string;
  phone?: string;
}

// my-name.tsx
// Updated from stencil-app-starter
export class MyName {

  @Prop({
    // This is needed in order to be able to change the user property
    // but only really want to be able to update a child field within the user.
    mutable: true
  })
  user: IUser;

  updateFirstName() {

    // Note: this does not cause a new render
    // this.user.first = 'John';

    // Use immutable style to update the instance and
    // create a new instance with the updated property value.
    this.user = {...this.user, first: 'John'};
  }

  render() {
    return (
      <div onClick={this.updateFirstName.bind(this)}>
        Hello {this.user.first} {this.user.last}
      </div>
    );
  }
}

// my-name2.tsx
// Alternate approach with proposed feature
export class MyName2 {

  // Note: no longer required to be mutable.
  @Prop() user: IUser;

  updateFirstName() {
    // Update a property within the user object
    this.user.first = 'John';

    // Indicate that the component should be rendered.
    // This is the method name that React uses as an example placeholder.
    this.forceUpdate();
  }

  render() {
    return (
      <div onClick={this.updateFirstName.bind(this)}>
        Hello {this.user.first} {this.user.last}
      </div>
    );
  }
}
```

Because Stencil does not walk all the fields of a `Prop` it is not able to detect child changes.  Having Stencil add depth to the comparison probably does not make sense because it consumes time (especially for large arrays or complex object graphs).

Another important case is when a `Prop` specifies an object that is modified externally to the component and has a `changed` event available.  For example, the current user of the application.  In this case the component can register for the `changed` event but still needs to have a reference to the original `user` instance because it may continue to change.

**Comment by kylecordes** [comment]
I'm inclined to recommend **against** a specific API for this, and rather encourage users/developers to replace the object or array they have in a `Prop` to trigger re-render. This is straightforward to do, even if done as a sort of "hack" to trigger re-render of data deeper down in an object graph. With an object it's no more than `this.prop1 = {...this.prop1};` for example; and this avoids adding more to the API surface.

(I'm not convinced that encouraging references to shared mutable state is a good idea.  I have heard people call the widespread default approach of shared mutable state, a trillion-dollar mistake.)

**Comment by cjorasch** [comment]
I think there is a distinction between **allowing** the use of shared mutable objects vs. **encouraging** this approach.  Requiring immutable objects for the purpose of change detection seems like the right approach and I agree that Stencil should not implement deep comparisons or other overhead during property updates.  I do not agree that shared objects are never appropriate.

Some cases that come to mind:

- Database oriented apps.  A simple example is a Task list.  This is often a large list of Tasks where the display of each task would be handled by a. component.  If the user clicks on a checkbox to modify the completed state of a Task then this component must update the Task within the list.  If the component simply creates a new Task using the immutable pattern then the top level list will not be updated.  This then requires something like Redux.  Which then requires re-rendering the entire list (or maybe the entire app).  This then can cause loss of UX state (scroll position, in progress inputs, etc.) and adds a lot of complexity to the app.  Writing data entry components with complex UX that get re-rendered during every keypress can he hard.
- Working with external objects.  Many times objects will not be in complete control of the component author.  For example, objects returned from native apis, objects when working with third part libraries, etc.  In these cases you may not be able to enforce fully immutable data structures throughout the entire application.
- Data entry utilities.  E.g. click a button for drag and drop list sorting, general purpose forms for object editing, etc.

**Comment by jthoms1** [comment]
Unfortunately changing from an immutable patterns for state cannot be accomplished in a performant way.  We are pretty set on this.  Fortunately Typescript has the nice spread/rest features that should make this pattern much more palatable in JS.

That being said I agree that it should be possible and forceUpdate is something we are currently kicking around.  I will leave this issue open and consider it a feature request for a force update mechanisem.  Thanks!

**Comment by cjorasch** [comment]
Excellent - thanks!

**Comment by jthoms1** [comment]
fixed with commit 79ffef12d5f0868a66fe4eae5798682f0bdf283c.

**Comment by TheBrockEllis** [comment]
I realize that this is a very old issue, but I can't find much documentation on this method anywhere and I can't tell exactly how to use it by looking through the source code. Any chance there are any examples online on the usage for `this.forceUpdate()`?

**Comment by cjorasch** [comment]
The method is on the `HTMLElement` rather than on the component class.  You can use the following:

```tsx
export class MyComponent {
    @Element() el!: HTMLStencilElement;

    refresh() {
        this.el.forceUpdate();
    }
}
```

**Comment by JCKodel** [comment]
It is possible to force this update on component class, without this kind of hack:

```
@State()
public myState: ISomeComplexObject;

private forceRenderingAgain()
{
    const currentState = this.myState;

    this.myState = null;
    this.myState = currentState;
}
```

Wondering because I did a @Action() decorator that will force component update after the decorated method run, for example:
```
@Action("myState")
public doSomethingOnMyState()
{
    this.myState.someObject.someOtherObject = true;
}
```

This decorator will trigger an update with that hack.

**Comment by RienNeVaPlus** [comment]
@JCKodel you might be interessted in my approach: https://github.com/RienNeVaPlus/stencil-reflector

**Comment by beenotung** [comment]
I used to use a 'place holder' property to force update without 'costly' operations, for example updating and array, map, set or global variables.
For example:
```tsx
@Component()
class MyComponent {

  @State() tick = {}

  @State() aLargeMap = new Map<string, string>()

  constructor(){
    // the update can be triggered anytime
    setInterval(()=>this.someUpdateMethod(), 1000)
  }

  someUpdateMethod(){
    this.aLargeMap.set('foo', 'bar')
    this.tick = {} // will trigger re-render
  }

  render() {
    return Array.from(map.entries())
      .map(([key, value])=> <p> {key + ' => ' + value} </p>)
  }
}
```
