### ISSUE TITLE
MockElement in SpecPage causes unexpected behavior

### ISSUE THREAD

**Issue by dangodev** [ionic-team/stencil#1850]
**Stencil version:**

```
 @stencil/core@1.3.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When using Stencil’s `newSpecPage` for tests, elements are represented as mock elements. Take the following component:

```
@Element() el: HTMLElement;
…

const button = this.el.querySelector('button');
console.log(button.constructor.name);
```

**Expected behavior:**
`button.constructor.name` should be `HTMLButtonElement` or `HTMLElement` when running in a browser.

However, in the spec page, it’s `MockButtonElement`.

This causes problems because some libraries such as `good-listener` rely on checks such as if a reference is an [`instanceof HTMLElement`](https://github.com/zenorocha/good-listener/blob/master/src/is.js#L9).

While having a mock DOM is completely fine, and it doesn’t need to behave like a browser (that’s what the E2E tests are for), it still causes unexpected behavior when core things like `querySelector` don’t work as expected.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
