### ISSUE TITLE
Add option to log test results to file

### ISSUE THREAD

**Issue by liron-navon** [ionic-team/stencil#1853]
**Stencil version:**

```
 @stencil/core@1.3.0
```

**I'm submitting a:**

[ ] bug report
[ X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When running `stencil test --spec --e2e` it logs the test results, but doesn't allow to generate a file or generate parsable results.

**Expected behavior:**
I would like to create a file out of the results for CI tools that require that kind of things, for example in our Azure pipeline we publish XML results from protractor.

If we can define something like `stencil test --spec -o results.json` . or `stencil test --spec -o results.xml` that would be nice, maybe we can define how to parse the results through stencil config by exposing the results only as json?

**For example, this can be a nice, flexible way to do it:**
And will allow the community to create transformers for any CI pipeline out there and whatever will pop up in the future.
```
import { TestResults } from '@stencil/core/testing';

export const config: Config = {
  namespace: 'my-project',
  outputTargets: [ ... ],
  test:{
    e2e: {
       output:  'results/e2e.xml',
       transform: (results: TestResults) => json2xml(results)
     },
    spec: {
       // by default export the results object as json if an output file was defined
       output:  'results/spec.json'
    }
  }
};

```

**Steps to reproduce:**

Run tests

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
