### ISSUE TITLE
Prerendering does not place slot content correctly when not using Shadow DOM

### ISSUE THREAD

**Issue by maltemuth** [ionic-team/stencil#1854]
**Stencil version:**

```
@stencil/core@1.3.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Steps to reproduce:**
```
# git clone https://github.com/maltemuth/stencil-slot-bug.git
# stencil build --prerender
# npx http-serve www
```

**Current behavior:**

HEY
Hello, World! I'm Stencil 'Don't call me a framework' JS

**Expected behavior:**

Hello, HEYWorld! I'm Stencil 'Don't call me a framework' JS

**Related code:**

see `src/components/my-component.tsx` and notice the `<slot><slot/>` placement. When setting `shadow: true` in Line 7, the behavior is as expected.

**Other information:**

I think this is related: https://github.com/ionic-team/stencil/issues/781

**Comment by grewdev** [comment]
We also faced the issue. It looks for me like a regression bug.

**Comment by maltemuth** [comment]
This is a duplicate of #1454

**Comment by matt-mcelhaney** [comment]
Facing this issue as well. 

When prerendering a table component which has thead, tbody, rows, and cells each with their own slots, and none of the components are using shadow, the slotted content is rendered outside of the component markup.

**Comment by viljamis** [comment]
Same issue here. Created a new issue a couple days ago since did not find/see this issue previously: #2068

**Comment by dedd1993** [comment]
Same issue here... this is happening to me with angular ngIf (conditional that removes and sets of DOM)

**Comment by harrysolovay** [comment]
Also experiencing this issue.
