### ISSUE TITLE
Imported component generated two class definitions and constructors get called twice

### ISSUE THREAD

**Issue by aztack** [ionic-team/stencil#1855]
**Stencil version:**

```
@stencil/core@1.3.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Imported component compiled into two piece of code.
For example, I have <tree> comoponent which importing <tree-item> component
1. TreeItem's definition inlined into tree.entry.js
2. TreeItem also got it's own tree-item.entry.js
When Tree component nested TreeItem(s), constructor of TreeItem in above two files both get called.

**Expected behavior:**
1. Only inlined constructor get called
2. Imported component do not generated separate entry file

**Steps to reproduce:**
https://github.com/aztack/nest-comp-bug

**Other information:**
One more redundant tree root item generated.
Two different constructors of TreeItem get called: 
![image](https://user-images.githubusercontent.com/782871/64529024-7838d600-d33c-11e9-8790-d22a42f3b31f.png)

render function of TreeItem. `console.log(id)` get called twice. (where id is a global auto increased number for debugging purpose)
![image](https://user-images.githubusercontent.com/782871/64529298-23e22600-d33d-11e9-81a3-316922f5ac1b.png)

Seperate TreeItem definition in tree-item.entry.js:

![image](https://user-images.githubusercontent.com/782871/64529041-8981e280-d33c-11e9-820b-7fa4cb640ea9.png)

Inlined TreeItem definition in tree.entry.js:

![image](https://user-images.githubusercontent.com/782871/64529044-8d156980-d33c-11e9-8e87-b3e44c97f30f.png)

**Comment by manucorporat** [comment]
Why are you passing arguments in the constructor? I don’t think this could ever work... I might add an error in the compiler when creating a constructor with any argument
