### ISSUE TITLE
Cannot read property 'type' of undefined in forms on Enter click

### ISSUE THREAD

**Issue by bubbleupdotnet** [ionic-team/stencil#1859]
**Stencil version:**

```
myapp@0.0.1 /Users/ildar/www/myapp
└── (empty)
```
I'm using @stencil/core@^1.4.0

**I'm submitting a:**

[*] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I have a simple form like in your documentation. If I press Enter Key then I get the error in console:
`Cannot read property 'type' of undefined`
![Снимок экрана 2019-09-11 в 11 54 48](https://user-images.githubusercontent.com/7842567/64674796-0b802180-d48b-11e9-8ea8-ec5829782bfc.png)

**Related code:**

```tsx
@Component({
  tag: "app-login-form",
  styleUrl: "form.component.scss"
})
export class LoginFormComponent {
  private validateAndSubmit(e) {
    e.preventDefault();
    console.log('validate and submit');
  }

  @State() value: string;
  @State() value2: string;

  handleChange(event) {
    this.value = event.target.value;
  }
  handleChange2(event) {
    this.value2 = event.target.value;
  }

  render() {
    return (
      <div class="contact-form">
        <form onSubmit={(e) => this.validateAndSubmit(e)}>
          <input type="text" value={this.value} onInput={(event) => this.handleChange(event)} />
          <input type="text" value={this.value2} onInput={(event) => this.handleChange2(event)} />

          <input type="submit" value="Submit" />
        </form>

      </div>
    );
  }
}
```

**Other information:**

**Comment by manucorporat** [comment]
Onloadwff.js is not coming fro stencil, the code crashing is not stencil. Please feel free to reopen the issue if you feel otherwise
