### ISSUE TITLE
Plugins with stencil

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/stencil#186]
Could you (ionic team) create a tutorial about how make plugins with stencil?
For example I've create Autocomplete component with stencil, how can I publish it? So other people could download it from npm.
Thanks

**Comment by siedentm** [comment]
you are talking about collections, i believe. Take a look at the component starter @ [https://github.com/ionic-team/stencil-component-starter](https://github.com/ionic-team/stencil-component-starter). It serves as both as a starting point of creating web components as well as collections. Inside your stencil.config.js you can set the value `generateDistribution: true,` which will enable the dist-folder generation, in case you don't want to copy your components to the starter.

**Comment by jgw96** [comment]
Hello all! As this is more of a question than an issue, I am going to close this issue for now. @siedentm is correct. Also, we have more docs on this [here](https://stenciljs.com/docs/distribution).  If you have any more questions feel free to ask them on the [stencil-worldwide slack](https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjQ2MzkyMTY0MTk0LTQ4ODgzYjFjNjdkNDY3YWVhMmNlMTljMWQxNTM3Yjg0ZTIyZTM1MmU2YWE5YzNjNzE1MmQ3ZTk2NjQ1YzM5ZDM). Thanks!
