### ISSUE TITLE
system.js polyfill break app on firefox v52

### ISSUE THREAD

**Issue by nonconforme** [ionic-team/stencil#1864]
```
 @stencil/core@1.3.2
```

[x] bug report
[ ] feature request
[ ] support request

Hello all and stencil team, thanks for your support.

We have upgraded our applications from 0.18 to 1.0 and system.js polyfill break our apps.

We got this error: 

"Error: Module https://.../.../p-fdb93b0e.system.js did not instantiate"

To reproduce, juste create an app and open it with firefox v52 with --dev and --es5

https://diff.intrinsic.com/@stencil/core/1.0.0-alpha.9/1.0.0-alpha.21#file-dist__client__polyfills__es5__system.js
https://raw.githubusercontent.com/ionic-team/stencil/345fcc7ee9303c97819afb605ef98d4688dc5502/src/client/polyfills/system.js

Is there an option to bypass polyfill and use a custom file ? I can't find anything like that in doc. Before upgrade we haven't this error and our apps work nice on firefox v52. Our only solution actually is to downgrade core and lost optimisations and others importants things.

We are a big structure, we cannot upgrade firefox because there is specific intranet configuration deployed to all agency for an entire country. It's more than 800 computers...

Thanks for your support.

**Comment by nonconforme** [comment]
We have resolved the issue with by mixing 0.x and 1.x stencil core.

We wait for a asap resolution by stencil team.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
