### ISSUE TITLE
Stencil 1.2.4 fails if page contains SVG with <style> tag in IE11

### ISSUE THREAD

**Issue by Tims101** [ionic-team/stencil#1867]
**Stencil version:**

```
 @stencil/core@1.2.4
```
also happens for ` @stencil/core@0.18.1`

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

If a page in IE11 contains SVG with Style tag inside, web components are not being hydrated. 

**Expected behavior:**

If a page in IE11 contains SVG with Style tag inside, web components should work fine. 

**Steps to reproduce:**

Add SVG with style attribute to a page with a web component and open it in IE11.

**Other information:**

In CSS-Shim polyfill all [style tags on a page](
https://github.com/ionic-team/stencil/blob/5a458282a577bca98acc6e0d94b2349fd0f8d8a3/src/client/polyfills/css-shim/load-link-styles.ts#L21) are selected and processed to replace with variables and etc.
In IE11 innerHTML for style tag in SVG is [always undefined](https://stackoverflow.com/questions/28129956/get-innerhtml-of-svg-tag-result-in-undefined-in-ie), so CSS Shim is failing.

**Comment by sjanczewski** [comment]
We also found the problem with `style` tag inside of `svg` tag. On IE11 `innerHTML` property is not available for that style element. 

When is trying to be used `innerHTML` (see `addGlobalStyle()` function), we got undefined instead of `String`. So for example `clean()` function thrown the error as the function expects string:

```
function clean(cssText) {
    return cssText.replace(RX.comments, '').replace(RX.port, '');
}
```

**Comment by sjanczewski** [comment]
@Tims101 I opened a PR which should fix this problem: https://github.com/ionic-team/stencil/pull/1892
