### ISSUE TITLE
Start page shows ~/

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#187]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
C:\ae\ae-stencil-menu>npm list @stencil/core
@adaept/menu@0.0.1 C:\ae\ae-stencil-menu
`-- @stencil/core@0.0.6-2
```

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

First page shows ~/
Click on ~ goes to the page

![capture181](https://user-images.githubusercontent.com/140737/30899039-1308f496-a313-11e7-914b-a7724f53b4c1.png)

![capture182](https://user-images.githubusercontent.com/140737/30899044-17de6b90-a313-11e7-8cc4-3c367e84996a.png)

**Expected behavior:**
Starter app should work

**Steps to reproduce:**

Test repo here:

https://github.com/adaept/ae-stencil-menu

package.json
```
{
  "name": "@adaept/menu",
  "private": true,
  "version": "0.0.1",
  "description": "adaept Menu App",
  "files": [
    "dist/"
  ],
  "scripts": {
    "build": "stencil build --prerender",
    "dev": "sd concurrent \"stencil build --dev --watch\" \"stencil-dev-server\" ",
    "serve": "stencil-dev-server",
    "start": "npm run dev"
  },
  "dependencies": {
    "@stencil/core": "0.0.6-2",
    "@stencil/router": "0.0.16"
  },
  "devDependencies": {
    "@stencil/dev-server": "0.0.17",
    "@stencil/utils": "0.0.4"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ionic-team/stencil-starter.git"
  },
  "author": "Ionic Team",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/ionic-team/stencil"
  },
  "homepage": "https://github.com/ionic-team/stencil"
}
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us. I just tested this and can confirm this issue.

**Comment by jgw96** [comment]
@jthoms1 this looks to be possibly a dev server thing?

**Comment by jthoms1** [comment]
It appears that the www directory is git ignored. This directory is currently required.  I cloned the repo and run `npm run dev` and the process appeared to do nothing.  Stopped and created the www directory and then the process started correctly.

@jgw96 were you able to reproduce?

**Comment by peterennis** [comment]
Look here, it could be related:

https://github.com/ionic-team/stencil-component-starter/commit/dcca995814c35e1d268331b05261c1bb583fd386

**Comment by jgw96** [comment]
Hello all! In the latest release of stencil/core the www folder will always be generated now, even if there is not already one (unless you specify otherwise in the config). Thanks everyone!
