### ISSUE TITLE
Wait for hydration when library is loaded via <script> tag

### ISSUE THREAD

**Issue by petermikitsh** [ionic-team/stencil#1870]
**Stencil version:**

```
 @stencil/core@1.2.4
```

**I'm submitting a:**

[] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

If I load a stencil component library via a `<script>` tag, and try to use component APIs before hydration, they are undefined. But there is no way to know they are hydrated.

<img width="1850" alt="Screen Shot 2019-09-17 at 8 33 56 PM" src="https://user-images.githubusercontent.com/1571918/65109665-3b4c8f00-d98d-11e9-8a0b-5a80757a073a.png">

https://codepen.io/petermikitsh/pen/NWKOqBy

**Expected behavior:**

Some way to wait for the components to be loaded.

**Steps to reproduce:**

1. Go to https://codepen.io/petermikitsh/pen/NWKOqBy
2. Open console and observe API undefined at 0ms, and defined at 1000ms

**Comment by petermikitsh** [comment]
I attempted the using the `onload` event. Still undefined: https://codepen.io/petermikitsh/pen/pozxpOe

In Chrome, the `customElements.whenDefined` API seems to work: https://codepen.io/petermikitsh/pen/aboREMj

**Comment by AlexSerrano22** [comment]
if you are using green browsers you could use:
```
customElements.whenDefined('test-component'').then(function () {

});
```
if not, and you are supporting IE11 you could use:
```
<script nomodule src="..." onload="init()"></script>
```
*(But you should load the script that is not using chunks)*

and in this function emit something to fire the components I did something like this:
```
function init() {
        var event = new CustomEvent("component-ready", {});
        window.dispatchEvent(event);
    }

window.addEventListener('component-ready', stencilAPIsFunction(){
....
});
```

**Comment by Tims101** [comment]
A proper solution would be to use `customElements.whenDefined`. Kinda a workaround for this case for IE11:

Custom element triggers an event when it's ready.

```javascript

@Event({ bubbles: true, composed: true }) loaded: EventEmitter<boolean>;

componentWillLoad() {
     this.loaded.emit(true);
}
```

Application is waiting for the event if componentOnReady is not defined.

```javascript
       
        if (element.componentOnReady) {
            element.componentOnReady().then(onElementReady);
        } else {
            element.addEventListener('loaded', onElementReady);
        }
```

**Comment by christian-bromann** [comment]
I think the solution @AlexSerrano22 proposed is a good way to go about this. I will go ahead and close this issue. Let me know if you have any further questions.
