### ISSUE TITLE
Feature Request: Ability to extend a component

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#1872]
**Stencil version:**

```
 @stencil/core@1.3.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Feature Request:**
I'd like the ability to build a new component by extending an existing component.
Something like:

```js
export class FooComponent extends BarComponent {
  // Modified and added props/methods
}```

**Comment by manucorporat** [comment]
We have discussed this many times, we will not support this, there are other ways to share logic across components. base class involves many moving parts, and less to wrong abstractions in a component model
