### ISSUE TITLE
weird behavior when generating distribution

### ISSUE THREAD

**Issue by siedentm** [ionic-team/stencil#188]
**Stencil version:**

```
@stencil/core@0.0.6-2
```

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
www is required and index.html is going to be generated no matter what. deleting www results in no output.

![screenshot_20170927_170007](https://user-images.githubusercontent.com/6476810/30921276-5e163208-a3a6-11e7-84ac-be051974932c.png)

**Expected behavior:**
when we set generateDistribution to true and generateWWW to false, the we expect to not use the dev server so generating index.html or being reliant on www is questionable. (is it even used for anything in this case?)

**Related code:**
stencil.config.js:
```
exports.config = {
  namespace: 'myname',
  generateDistribution: true,
  generateWWW: false,
  hashFileNames: false,
  serviceWorker: false,
  bundles: [
    { components: ['my-name'] }
  ]
};
```

**Comment by jthoms1** [comment]
I think that asking for the www folder not to exist when generateWWW is false is a valid request.

**Comment by siedentm** [comment]
positive. and i ask for fixing the hash-names for the core and corePolyfill output files (myname.{hash}.js and myname.{hash}.pf.js)

**Comment by jthoms1** [comment]
Yep and it looks like hashFileNames is not being honored.  This is also a bug.

**Comment by siedentm** [comment]
i opened a seperate issue as this is not limited to hashes (#190)

**Comment by adamdbradley** [comment]
This should be working now, thanks
