### ISSUE TITLE
components.d.ts definition autogenerated types

### ISSUE THREAD

**Issue by d0whc3r** [ionic-team/stencil#1896]
**Stencil version:**

```
 @stencil/core@1.5.0 and 1.5.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

In generated `components.d.ts` all properties asigned by default it takes the value as type

**Expected behavior:**

The generated `components.d.ts` should get the type of the value and generate an interface with good types

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
@Prop() readonly test = 'hello';
@Prop() readonly test1 = false;
```

Then build the component and autogenerated `components.d.ts` file will fill the interface of component with `test: 'hello'` and `test1: false`

Then when you use this component in other stencil project, at build time of this new project it will fail because "test" property is "hello" type and could not be assigned to any other string and "test1" should not be other than "false" instead of boolean value

**Other information:**

**Comment by manucorporat** [comment]
I can't reproduce, can your provide a repo that reproduces it?

**Comment by d0whc3r** [comment]
Yes, I followed eslint rules and it only happens when the property is "readonly"

**Comment by d0whc3r** [comment]
Here is the repo to reproduce https://github.com/d0whc3r/stencil-component-types
And build output is:

```
> stencil build --prod --es5 --docs

[28:26.0]  @stencil/core v1.5.1 
[28:26.2]  build, test-components, prod mode, started ...
[28:26.5]  transpile started ...
[28:31.7]  transpile finished in 5.22 s
[28:31.7]  type checking started ...
[28:31.8]  copy started ...
[28:31.8]  generate styles started ...
[28:31.9]  bundling components started ...
[28:32.0]  copy finished (0 files) in 220 ms
[28:32.1]  generate styles finished in 317 ms
[28:32.2]  updated readme docs: my-component
[28:35.9]  bundling components finished in 4.01 s
[28:40.5]  type checking finished in 8.78 s

[ ERROR ]  TypeScript: ./src\components\my-other-component\my-other-component.tsx:12:23
           Type '"Malik"' is not assignable to type '"Mike"'.

     L11:  <p>
     L12:    <my-component first="Malik" middle="Abdul" last="Aziz"/>
     L13:  </p>

[ ERROR ]  TypeScript: ./src\components\my-other-component\my-other-component.tsx:12:52
           Type '"Aziz"' is not assignable to type '"Tyson"'.

     L11:  <p>
     L12:    <my-component first="Malik" middle="Abdul" last="Aziz"/>
     L13:  </p>

[28:40.5]  build failed in 14.29 s
```

**Comment by manucorporat** [comment]
so:
```
// insert any relevant code here
@Prop() test = 'hello';
@Prop() test1 = false;
```
^ this does not reproduce it, but this:
```
// insert any relevant code here
@Prop() readonly test = 'hello';
@Prop() readonly test1 = false;
```
?

**Comment by manucorporat** [comment]
I guess using readonly was not a good idea after all, i didn't know about this behaviour in Typescript

**Comment by d0whc3r** [comment]
ok, I will remove readonly
