### ISSUE TITLE
Duplicated elements when using conditional children

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil#191]
If I have this markup:

```jsx
       <ion-content padding>
          {chats.map(chat => {
            const chatTime = this.formatTime(chat.at);
            return (
              <div class="chat">
                <div class="chat-time">{chatTime}</div>
                <div class="chat-text"><span class="chat-username">{chat.username}</span> {chat.text}</div>
              </div>
            )
          })}
        </ion-content>
```

Then Stencil is outputing duplicate elements for each item in the `chats.map`:

<img width="874" alt="screenshot 2017-09-27 17 19 38" src="https://user-images.githubusercontent.com/11214/30940830-33f468bc-a3a8-11e7-8cf0-4424fbc87cf7.png">

### Workaround

If I wrap the conditional with a `<div>`, the problem goes away:

<img width="894" alt="screenshot 2017-09-27 17 21 18" src="https://user-images.githubusercontent.com/11214/30940860-48e2ff36-a3a8-11e7-8715-4153624a7144.png">

<img width="776" alt="screenshot 2017-09-27 17 21 35" src="https://user-images.githubusercontent.com/11214/30940869-545b5412-a3a8-11e7-8aee-d2e5ed80c572.png">

**Comment by adamdbradley** [comment]
Fixed in 0.0.6-4
