### ISSUE TITLE
stencil standalone component (using ionic core components) is throwing exception in ionic/angular 4 application

### ISSUE THREAD

**Issue by sanaadostmuhammad** [ionic-team/stencil#1915]
**Stencil version:**
 @stencil/core@1.5.2 

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I am trying to developing a stencil standalone component (using ionic core components) that can be used in an Ionic, angular, and Native Javascript Application.

- Ionic 4: Getting an exception in the tabs entry file (ionic/core). It works as expected if I remove the “@ionic/core” import from index.ts file but then it won’t work in the angular and native javascript projects.

**Expected behavior:**
The component should successfully render in the ionic app

**Steps to reproduce:**

- Create a stencil component type project
- use ionic core components in your custom component 
- import your component in the ionic photo-gallery project (https://ionicframework.com/docs/angular/your-first-app)
-You will see that the tabs are loaded but not the contents. An error is being thrown in the ion-tabs.entry.js file (ion-tabs.entry.js:141 tab with id: "undefined" does not exist) 

**Related code:**
My stencil component: 
*Stencil-component: password-reset.tsx*
`import { Component, h } from '@stencil/core';
@Component({
  tag: 'password-reset',
  styleUrl: 'password-reset.css',
  shadow: true
})
export class PasswordReset {
  render() {
    return [
      <ion-item>
        <ion-label position="floating">Floating Label</ion-label>
        <ion-input></ion-input>
      </ion-item>
    ];
  }
}
`

*Stencil-component: src/index.ts*
`
import '@ionic/core';`

*photo-gallery project: src/tab/tab3/tab3.page.html*
`<ion-content>
  <stock-finder></stock-finder>
</ion-content>`

*photo-gallery project: src/tab/tab3/tab3.module.ts*

`import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
@NgModule({
....
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
...
})`

*photo-gallery project: src/main.ts*
`import { defineCustomElements } from 'sanaa-stencil-components/loader';
platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch(err => console.log(err));
defineCustomElements(window);`

**Comment by jdnichollsc** [comment]
I am experiencing a similar error with the menus, they stop working as expected (enabling and disabling it), after remove that dependency the menu is working again 🤔
Guys, Is this configuration Ok to extend Ionic Components?
- https://github.com/proyecto26/stencil-ionic-components/blob/master/src/global/global.ts
- https://github.com/proyecto26/stencil-ionic-components/blob/master/src/global/global.scss
Thanks in advance! 😅

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize it took so long for someone on the team to acknowledge this issue. At this time, Stencil v1 and lower is no longer supported.  As a result, I'm going to close this issue.

If this issue is still occurring in Stencil v4, can you please create a new issue for us with an updated minimal reproduction case? Thanks!
