### ISSUE TITLE
*__awaiter_1 is not defined* when use with plugin of capacitor

### ISSUE THREAD

**Issue by lucascco** [ionic-team/stencil#1916]
**Stencil version:**

```
 @stencil/core@1.5.4
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When use plugin of capacitor, always that I call the @Method async, the error `__awaiter_1 is not defined` happen. This error happen when I try use the web component in Wordpress.

**Steps to reproduce:**

https://github.com/lucascco/reproduce-error-stencil-async

**Other information:**
Just follow steps in repository above to reproduce this erro.

**Comment by manucorporat** [comment]
Seems related with https://github.com/microsoft/TypeScript/issues/33547

**Comment by srclark213** [comment]
I'm seeing a similar issue with @aspnet/signalr library. Something is defining an __awaiter function inside the signalr library, so when it gets pulled into our stencil component all of our awaits get compiled to calls to __awaiter_1. However whatever generates the __awaiter function for the component doesn't call it __awaiter_1, it just re-declares __awaiter, such that in the output file I have two declarations of __awaiter, but all the calls are to __awaiter_1.

Tried setting `"noEmitHelpers": true` in my tsconfig which fixed other cases of these types of collisions but not the signalr collisions.

**Comment by lotz** [comment]
Thanks for working around this @manucorporat! This was blocking us from upgrading to a newer version of Stencil.

**Comment by robinsummerhill** [comment]
I'm also seeing this issue with Stencil 1.7.5. I can't upgrade to the version with the fix for this issue because it uses Typescript 3.7 and the generated component library is not compatible with Angular 8.
