### ISSUE TITLE
Use own service worker

### ISSUE THREAD

**Issue by kubii** [ionic-team/stencil#192]
**Stencil version:**

```
 @stencil/core@0.0.6-2
```

**I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
When serviceWorker.swSrc is specified in stencil.config.js file and I try to build the project then I get the following message:
```
The configuration options 'swSrc' will be ignored in the context of Workbox's generateSW mode.
```
According to the Workbox documentation the swSrc config is only valid with Workbox's injectManifest(). The goal was to use my own service worker implementation and build the manifest info into it.

**Expected behavior:**
If swSrc is defined then use injectManifest() to use the specified service worker and inject the manifest into it.

**Steps to reproduce:**
- clone stencil-starter project
- specify serviceWorker.swSrc config
- run the build task

**Related code:**

```
exports.config = {
  bundles: [
    { components: ['my-name'] }
  ],
  collections: [
    { name: '@stencil/router' }
  ],
  serviceWorker: {
    swSrc: 'pathToServiceWorkerImplementation'
  }
};
```

**Other information:**
Created a fork and changed the related code so the injectManifest() is used when swSrc is defined: [commit](https://github.com/kubii/stencil/commit/268487cf61665f7ad7c3bacfbf77ad450491c87b).
Let me know what do you think about this solution.

**Comment by jgw96** [comment]
Looking into this now @kubii , thanks!

**Comment by jgw96** [comment]
@kubii, would you mind making a PR for this? Im testing your fork, but it seems that its missing some of the stuff from the latest version of stencil/core. Besides that, it looks correct to me. Also, note to self, we are going to need some docs around this.

**Comment by kubii** [comment]
@jgw96 
Sure, I can create the PR later today.
