### ISSUE TITLE
Feature: Support NX workspace

### ISSUE THREAD

**Issue by DmitryEfimenko** [ionic-team/stencil#1921]
**Stencil version:**

```
Irrelevant
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request

**Expected behavior:**
I would like to add a Stencil project into my [nrwl/nx](https://github.com/nrwl/nx) workspace.
There should be a set of schematics built to support this behavior via [Angular Console](https://angularconsole.com/)

**Other information:**
Creating this issue per https://github.com/nrwl/nx/issues/1487
Similar (but broader) issue: https://github.com/ionic-team/stencil/issues/1877

**Comment by bellindj** [comment]
We're building a design system with StencilJS for core components and building a "supplemental" Angular library in a nrwl/nx repo to add things like ControlValueAccessors for our web component form controls. It would be amazing to be able to pull these both in to the same repo.

**Comment by petermikitsh** [comment]
@bellindj The Stencil DS plugins (Angular target) will setup value accessors for you. https://github.com/ionic-team/stencil-ds-plugins/tree/master/packages/angular-output-target/resources/control-value-accessors

**Comment by bellindj** [comment]
@petermikitsh thanks for the suggestion! We’re actually using those plugins along with an NX plugin for stencil by @aiao https://www.npmjs.com/package/@aiao/stencil-toolkit

**Comment by manucorporat** [comment]
PR accepted but it's not something the stencil team will focus for now!

**Comment by rgolea** [comment]
@bellindj does the stencil plugin by @aiao actually work?

**Comment by DmitryEfimenko** [comment]
well, why is this closed then? Shouldn't it be left open for tracking?

**Comment by rgolea** [comment]
@DmitryEfimenko https://github.com/nrwl/nx/pull/2957 should also fix this?

**Comment by DmitryEfimenko** [comment]
I don't know. Haven't tried it. It's my understanding that this is an unofficial set of schematics that adds this functionality. I'd personally prefer an official support - meaning the schematics would be a part of stencil project itself.
