### ISSUE TITLE
Testing: newSpecPage() should be able to handle object properties

### ISSUE THREAD

**Issue by guidoknoll** [ionic-team/stencil#1923]
**Stencil version:**

```
 @stencil/core@1.5.4
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**

When trying to pass object properties to the tested component in an unit test, it can only be passed after the generation of a new spec page like this:

```tsx
const config: WidgetConfiguration = {
    "language": "de",
    "retailPartner": "",
    ...
}
```

```tsx
const page = await newSpecPage({
       components: [ProductListing],
       html: `<product-listing></<product-listing>`
});

page.rootInstance.config = config;
await page.waitForChanges();
```

If you need such a property in a lifecycle function like _componentWillLoad()_ it is undefined and you get an error.

```tsx
public componentWillLoad() {
    if (this.config) {
      this.apiService = new ApiService(this.config.apiPath);
      this.fetchProducts();
    } else {
      throw new Error('Configuration must be provided!');
    }
 }
```

**Expected behavior:**

It should be possible to pass complex properties like objects to and web component during an unit test when creating ja new spec page.

**Other information:**

A option called _properties_ for the _newSpecPage()_ function could pass an array of properties to the root component of the spec page.

**Comment by manucorporat** [comment]
It is possible!
```
const page = await newSpecPage({
       components: [ProductListing],
       template: () => (
         <product-listing config={config}></<product-listing>
       )
});
```
in this case you are not testing `html`, but the component created using JSX (which allows complex prop passing), html is only html-attributes.

**Comment by mkay581** [comment]
I agree there should be some documentation around this. It doesn't look like there's any.

**Comment by chmerk** [comment]
Important note: You have to use .spec.tsx (instead .spec.ts) extension and `import { h } from '@stencil/core';`
See #2850
The Stencil 3.x docs now mention this (however, not very prominently ;)
