### ISSUE TITLE
@Method() not accessible outside component

### ISSUE THREAD

**Issue by aparnapatil01** [ionic-team/stencil#1926]
As per documentation - https://stenciljs.com/docs/methods, the methods declared using @Method can be accessed outside of component and there is no need of `componentOnReady()`. However, it throws error saying `customElementName.methodName()` is not a function.

Code

--my-component.tsx--

```
import { Component, h, Method } from '@stencil/core';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {
  @Method()
  myMethod() {
    return Promise.resolve(42);
  }

  render() {
    return <div>Hello, World! I'm StencilJS</div>;
  }
}
```

--index.html--

```
<my-component></my-component>
<script>
    const ele = document.querySelector('my-component')    ;
    ele.myMethod();
</script>
```

The above code throw error - `ele.myMethod is not a function`.

When used with `componentOnReady()` i:e `ele.componentOnReady().myMethod()`, this will throw `ele.componentOnReady is not a function`.

It would be great if you could help me to solve this issue. I'am using `@stencil/core` version `1.5.4`.

As well I have noticed a minor spelling mistake in word `business` in stencilJS doc. `Non-public methods can still be used to organize the businness logic of your component and they do NOT have to return a Promise.` in URL - https://stenciljs.com/docs/methods.

**Comment by turtledev1** [comment]
Our team used 2 different ways to solve this problem. The first is to call the method in a setTimeout. The first is to dispatch an event in the componentDidLoad(), and listen to that method where you want to call the function.

```
//my-component
componentDidLoad() {
     this.host.dispatchEvent('ready');
}

//index.html
document.querySelector('my-component').addEventListener('ready', event => event.target.myMethod()
```

**Comment by jdnichollsc** [comment]
Check this other option => https://stackoverflow.com/a/58861708/1532821

**Comment by tanner-reits** [comment]
Hey @aparnapatil01 👋 

Sorry that you never heard from the team on this issue! Hopefully the link @jdnichollsc posted pointed you in the right direction and you were able to get things working. Please let us know if you're still having issues, otherwise we'll look to close this out in the coming weeks!
