### ISSUE TITLE
The template is not updated after changes properties.

### ISSUE THREAD

**Issue by sjanczewski** [ionic-team/stencil#1929]
**Stencil version:**
```
 @stencil/core@1.5.1-1
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The component template is not updated after changes the properties.  The `render()` function is called normally with new values, but the DOM is not updated despite this.

**Expected behavior:**
After change element properties, the DOM template should be updated with new props.

**Steps to reproduce:**
Inspect the component element from Chrome Dev Tools and update the property: 
```
$0.propName = 'New value';
```

**Other information:**
Stencil version `1.5.1-0` works fine.
Probably something has been changed in this commit:
https://github.com/ionic-team/stencil/commit/3f436e2f46100f664268d077289750d84fd3871e

**Comment by sjanczewski** [comment]
Now I figured out that updating props updates the DOM only if template registers an event like `onClick`.

Without register events in the template. Updating properties are not available. Anything has been changed in the version `1.5.1-1` related to this?

**Comment by sjanczewski** [comment]
Ok, now I see that is not the issue. :)
I am seeing that the `vdomXlink` flag was added into the BUILD obj.

I am gonna just close this issue as that is not an issue anymore.

**Comment by sjanczewski** [comment]
I found the problem. I will try to make a PR with the fix in the next couple of days.

**Comment by manucorporat** [comment]
Can you test 1.6.0-1?

**Comment by sjanczewski** [comment]
Hi @manucorporat,
That problem is happen on all version since 1.5.1-1. 
But I see that you have already made a fix on master:
https://github.com/ionic-team/stencil/blob/master/src/compiler/transformers/static-to-meta/vdom.ts#L67

On master works as expected :)

**Comment by sjanczewski** [comment]
Fixed on version 1.6.0.
