### ISSUE TITLE
type="text" is not reflecting on input tag

### ISSUE THREAD

**Issue by rahul-rautwar** [ionic-team/stencil#1932]
**Stencil version:**

```
"@stencil/core": "1.2.0"
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**

Input tag type="text" is not reflecting on the DOM element,
```
<input> // type="text" not reflecting on DOM 
```
when using type="email/password", its wroking fine
```
 <input type="email"></input> or
<input type="password"></input>
```

**Expected behavior:**

For type="text" it should render like below 
```
<input type="text"></input>
```

**Comment by manucorporat** [comment]
Please use the latest release of stencil, this issue was already fixed!

**Comment by rahul-rautwar** [comment]
@manucorporat could you please share the version/PR where it's fixed.
