### ISSUE TITLE
Accessing Child Component Info Before Parent Render

### ISSUE THREAD

**Issue by harrysolovay** [ionic-team/stencil#1933]
**Stencil version:**

```
 @stencil/core@1.3.3
```

**I'm submitting a:**

[ish] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these

**Current behavior:**

There doesn't seem to be a way to access a child component or its properties (styles, for instance)––from within its parent––before a first render. When passing a child via slots, the only way to access that slot is to attach a ref callback to its parent (aka. must wait for first render to access the node). When passing a child via a prop, you can access the VNode before the first render... but not its `$elm$`. Even after the first render, the `$elm$` does not contain style properties.

**Expected behavior:**

I'd love a way to access a child element's properties, from within its parent, before the first render. Would it be possible to render children first?

**Steps to reproduce:**
Here is [a repro with comments](https://github.com/harrysolovay/parent-reading-children-problem) :)

**Comment by harrysolovay** [comment]
@manucorporat –– this is the problem we discussed. Any advice would be greatly appreciated! Incase this helps, the use case is as follows:

I'm building a layout component which takes in two elements: a header bar, and a side menu beneath it. The header bar is above the side menu should become fixed to the top of the viewport when it scrolls passed y0. Meanwhile, the side menu should become fixed to the bottom of the header. Because the header passed in could vary in height, setting the sticky `top` style on the menu bar needs to be dynamic (determined by the height of the header). Right now, I've managed to get this working, but only by setting variables in state, based on values drawn from the header after the first render. This isn't pretty... beyond the fact that it requires repaints, it causes problems for prerendering :/ Please let me know if you need any more information. I'm really hoping there's a solution. Thank you!!!

**Comment by manucorporat** [comment]
Before a components is rendered is does not exist in the DOM, it does not exist at all. You can use the @Element() decorator which you can use before the first render to get a reference to the host element.
