### ISSUE TITLE
Stencil prod build styling issue

### ISSUE THREAD

**Issue by RiteshSRajput** [ionic-team/stencil#1939]
We have done stencil upgrade recently and found styles issues in prod build package (stencil build). It is working fine when doing build with --dev parameter (stencil build --dev).

I have done more research and found the difference in style tag. In dev build I can see the style tag is coming under my shadow dom as it was coming in stencil previous version(0.15.x). But In prod build package, style tag is missing but styles is getting applied. I can understand stencil is disabling styles to be modified in prod build. But behaviour should not be changed.

Facing this issue in all stencil one versions

[Code Sample](https://github.com/RiteshSRajput/stencil_assets.git)

**Comment by adamdbradley** [comment]
During development stencil uses `<style>` within shadow dom, and [Constructable StyleSheets](https://developers.google.com/web/updates/2019/02/constructable-stylesheets) in production. Constructable StyleSheets offers superior performance when rendering many shadow dom components, but at this time they are difficult to work with during development. Would you be able to point out what is not working in your code example?

**Comment by Sidharth-Pandey** [comment]
@RiteshSRajput , did you find any solution?
I am also facing the same, the scrollbar is not applying in my component in prod mode

**Comment by rwaskiewicz** [comment]
Hey folks,

If this is still an issue in `@stencil/core` v2, can someone please provide a minimal reproduction case?  Thanks!
