### ISSUE TITLE
Setting element styles with PropDidChange whilst using ChromeVox causes infinite element duplication

### ISSUE THREAD

**Issue by CookieCookson** [ionic-team/stencil#194]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.6-3
```

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
When changing a style on a DOM element, the DOM element appears to duplicate itself infinitely. This only occurs when using the ChromeVox plugin which is an accessibility/screenreader plugin for Chrome.

![stencil-vox](https://user-images.githubusercontent.com/3473396/31024759-ffc30508-a537-11e7-93d9-31150755c322.gif)

**Expected behavior:**
The element should take the new style value, not create a new instance.

**Steps to reproduce:**
1. `git clone https://github.com/CookieCookson/stencil-vox stencil-vox`
2. `npm install`
3. `npm start`
4. Click the button, it should change to 0.5 opacity
5. Install [ChromeVox](https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn/related?hl=en)
6. Click the button, it creates an infinite amount of buttons

**Related code:**

https://github.com/CookieCookson/stencil-vox

**Comment by jgw96** [comment]
Out of curiosity, does this only happen with web components built with Stencil? Or does it happen in a polymer project too?

**Comment by CookieCookson** [comment]
Not sure, does it share similar methods with how Polymer does things?

I'd have to remake the example to find out.

**Comment by jgw96** [comment]
Reason i was asking was because Stencil uses web components and Polymer uses web components, so, in theory, they should behave similarly. I'm going to close this issue for now, but feel free to DM me on slack if you're still running into this issue. Thanks, @CookieCookson !

**Comment by CookieCookson** [comment]
Thanks @jgw96 - I've had to shift priorities lately so this hasn't been looked into. If I get the problem again I will bring it up.
