### ISSUE TITLE
Prerender only render root document since 1.6.0

### ISSUE THREAD

**Issue by DavidWiesner** [ionic-team/stencil#1940]
**Stencil version:**

```
 @stencil/core@1.6.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Prerender only render root document and failed to detect sub paths since `@stencil/core@1.6.0` 

**Expected behavior:**
Prerender should detect and render all sub path recursively

**Steps to reproduce:**

One simple example is your stencil site repo.
1. clone repo [`stencil-site`](https://github.com/ionic-team/stencil-site.git)
2. install latest stencil core `npm install @stencil/core@1.6.1`
3. run `npm run build`
4. inspect `www/sitemap.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
 <url><loc>https://stenciljs.com/</loc></url>
</urlset>
```

5. install older version of stencil core `npm install @stencil/core@1.6.1`
6. run build again `npm run build`
7. inspect `www/sitemap.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
 <url><loc>https://stenciljs.com/</loc></url>
 <url><loc>https://stenciljs.com/blog</loc></url>
 <url><loc>https://stenciljs.com/design-systems</loc></url>
 <url><loc>https://stenciljs.com/resources</loc></url>
 <url><loc>https://stenciljs.com/blog/how-lazy-loading-web-components-work</loc></url>
 <!-- ... and many more -->

</urlset>
```

**Comment by Nudelsieb** [comment]
`www/sitemap.xml` still only has one route in latest stencil versions.
