### ISSUE TITLE
E2E tests should fail if console.error is called or an error is thrown

### ISSUE THREAD

**Issue by CSchulz** [ionic-team/stencil#1942]
**Stencil version:**
```
 @stencil/core@1.3.4
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If the component throws an error the tests succeeds.
```
 PASS  components/input/input.e2e.ts
  ● Console

    console.error node_modules/@stencil/core/dist/testing/index.js:39752
      pageerror Error: TypeError: Cannot read property 'value' of undefined
          at Input.handleKeyEnter (http://localhost:3333/public/stylelib/js/input.entry.js:232:47)
          at HTMLDocument.Input.handleKeydown (http://localhost:3333/public/stylelib/js/input.entry.js:142:26)
```

**Expected behavior:**
The test should fail if any component throws an error or logs anything to console.error.

**Steps to reproduce:**
Write a component which throws an error and test it.

**Comment by manucorporat** [comment]
Not everybody agrees on this behaviour. There are strong arguments against breaking the test if there is a console.error(). It's not a uncaught exception. However, you can pass the `failOnConsoleError` config when creating the E2E page:

```js
newE2EPage({
  failOnConsoleError: true
});
```

**Comment by CSchulz** [comment]
Thanks for your fast reply, which version of stencil or puppeteer is required to use that feature?
