### ISSUE TITLE
Lazyloading is not working in JavaScript environnement 

### ISSUE THREAD

**Issue by stephenbe** [ionic-team/stencil#1945]
**Stencil version:**

```
 @stencil/core@1.5.4
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I have two components, if I just add one of the two components it still loads all of the components. 

**Expected behavior:**

I expect that only the component is used will be loaded. Right now both are loaded even though I only have one component on the page.

**Steps to reproduce:**

I made two components. One is the default component. The other I used npm run generate and I added a thousands divs of lorem ipsum is the jsx renderer. so Right now I have 1.5mb of components that is loaded even though I only have `<my-component></my-component>` in the page

**Related code:**
```tsx
export class DsButton {
  render() {
    return (
      <Host
        class={{
          "todo-list": true
        }}>
        <slot></slot>
        <div>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde rerum tenetur sapiente sit voluptatibus consectetur,
          aspernatur ipsa quae, blanditiis quod rem repellat impedit, aliquid quis provident consequuntur ut nobis illo.
        </div>
    ... (lorem ipsum x 1000 to make a huge component to test lazyloading)

```
**Other information:**
Here is my html page I am testing with  : 
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <script type="module" src="../dist/designsystem/designsystem.esm.js"></script>
    <script nomodule="" src="../dist/designsystem/designsystem.js"></script>
  </head>
  <body>
    <ds-button></ds-button>
    <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>
  </body>
</html>

```

If I remove ds-button, the resources loaded should be way lower than 1.5mb.

Thanks!

**Comment by manucorporat** [comment]
so the big component is never used and still part of the same bundle?
can you share a repo?

**Comment by manucorporat** [comment]
Stencil performs an static analysis on the components that are being used in the index.html, since it finds both components used at compiler time, it will bundle them together to reduce latency.

If you compile the app with one component in the index.html, they will not be bundled together.

**Comment by manucorporat** [comment]
If you want to make sure that stencil never tries to be too smart and bundle one component together, you can describe your own bundles in `stencil.config.ts`:
```
export const config: Config = {
  namespace: "designsystem",
  bundles: [
    { components: ['ds-button'] },
  ],
```

^ this will ensure that the component `ds-button` always have their own bundle

**Comment by stephenbe** [comment]
aaah ok so because I am creating a ui framework, I am going to need to define each component in the bundles. That's exactly what ionic does as well here : https://github.com/ionic-team/ionic/blob/master/core/stencil.config.ts#L9-L64
