### ISSUE TITLE
[feature request] - support mdx extension

### ISSUE THREAD

**Issue by vidarc** [ionic-team/stencil#1946]
**I'm submitting a:**

[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

Storybook's recent new [docs addon](https://github.com/storybookjs/storybook/tree/next/addons/docs) supports MDX for their doc page. Being able to specify mdx (or maybe even any type of extension) for the docs-readme generator would be very helpful.

**Comment by spaceemotion** [comment]
Is there a way to reopen this? While the docs target supports custom readme paths now, the usages still depend on .md files as can be seen here:

https://github.com/ionic-team/stencil/blob/bce12b92c560d3d90335ad43125969e913ea6e8d/src/compiler/docs/generate-doc-data.ts#L322
