### ISSUE TITLE
Reflecting a prop turns it from number to string on update

### ISSUE THREAD

**Issue by marksyzm** [ionic-team/stencil#1949]
**Stencil version:**

```
 @stencil/core@1.7.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request

**Current behavior:**

Setting a value on a component on first load that has `reflect` set returns the original value from the element when checked after `componentDidLoad()` but when set again it turns it into a string.

**Expected behavior:**
Value received from element should always return its original state

**Steps to reproduce:**
• Make a component with a prop with `reflect: true`
• Set that prop after it loads with a number
• Check the element prop value

**Related code:**

```tsx
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'item'
})
export class AppListRowItem {
  @Prop({ reflect: true }) val: number;
}
```

**Other information:**

**Comment by manucorporat** [comment]
Thanks for the issue, can you provide a full example that reproduces it?

**Comment by marksyzm** [comment]
Sure, I’ll try now to do so

**Comment by marksyzm** [comment]
Hmm, can't seem to do it in isolation! Oh well; close the ticket
