### ISSUE TITLE
package-lock not in sync with new release

### ISSUE THREAD

**Issue by peterennisrda** [ionic-team/stencil#195]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

@adamdbradley 
I would expect package.json and package-lock.json to be in sync.
Is this expected to be updated automagically?
If so, how? when?

![capture1112](https://user-images.githubusercontent.com/1280523/31038003-12a4032a-a529-11e7-813d-d98f5c6d88c0.PNG)
![capture1111](https://user-images.githubusercontent.com/1280523/31038002-128e7046-a529-11e7-8bca-bf113a83a1e8.PNG)

**Comment by adamdbradley** [comment]
Sorry i messed up this release. I'll fix up the publish script for the next one. Thanks for reporting this.

**Comment by adamdbradley** [comment]
Fixed as of `0.0.6-10`, thanks
