### ISSUE TITLE
Build still logging "[STENCIL-DEV-MODE] Stencil is running in the development mode." in deployment

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#1956]
**Stencil version:**

```
 @stencil/core@1.7.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When loading Stencil components via script tags, there is now a console message:

`[STENCIL-DEV-MODE] Stencil is running in the development mode.`

**Expected behavior:**

There should be no console message (beyond errors/warnings) when using tags from a `stencil build` output. 

**Steps to reproduce:**

1. Build a Stencil component
2. Run `stencil build` and place the output on a server
3. Reference the tags as intended:
```html
<script src="/my_element/my_elements.esm.js" type="module"></script>
<script src="/my_elements/my_elements.js" nomodule=""></script>
```
4. Check console log and see message.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

Seems like something may not be compiling properly or is permanently placing the build in 'Dev Mode'.

**Comment by viljamis** [comment]
@cary-smith I’m using 1.7.1 as well, but can’t reproduce this issue with the steps you’re describing. What does your stencil config/package.json look like?

**Comment by cary-smith** [comment]
@viljamis - I am looking into it and not completely convince this is Stencil. I am going to close this until it can be isolated.

**Comment by manucorporat** [comment]
Can't reproduce either, i wonder if you are actually deploying in fact a dev release. We added this log to detect those cases!

**Comment by cary-smith** [comment]
I don't think its Stencil. The more I thought about it, the more I think its related to the order of operations when we deploy (Jenkins job) it may not be prod compiled.

Sorry for the false alarm!

**Comment by cary-smith** [comment]
@manucorporat & @viljamis - Found the issue, we were running tests _after_ building which caused the problem. Yes it was a dev build and your tooling found it!

Nice work.

**Comment by trazek** [comment]
So running tests after building is a "problem"? Is this something to be avoided for some reason? Any way to turn off this logging in the event the components are built before testing?

**Comment by cary-smith** [comment]
@trazek - I am not sure what changes occur completely, but if you run build and look in the **dist/\<your-namespace\>** folder, there are no **core-\<somehash\>.js** files. If you then run test, **core-\<somehash\>.js** files show up (among other things). I have no idea if it changes anything else, but the core files are where the console log is coming from.

**Comment by trazek** [comment]
I see. Have you discovered a way to suppress the messages, perhaps with a log level? I suppose it's not a big deal but it's quite body lately noisy. Thanks for the information and report back if I find anything

**Comment by cary-smith** [comment]
@trazek - Just took some changes to our build process. Test compiles what it needs to including some extras (thos causing the console log). To avoid these being packaged with our product we reversed the order of the Jenkins steps (test then build) and added a bit to our npm 'build' command to delete the 'dist' folder before any build.

**Comment by trazek** [comment]
@cary-smith Interesting. I deleted the dist folder and ran the tests but still have the "c[STENCIL-DEV-MODE]" outputting.
