### ISSUE TITLE
Do not log compiler warnings when testing

### ISSUE THREAD

**Issue by MonsieurMan** [ionic-team/stencil#1959]
**Stencil version:**

```
 @stencil/core@1.7.2
```

**I'm submitting a:**

[x] feature request

**Current behavior:**
Compiler logs warning when running `stencil test`

**Wanted behavior:**
Either stop logging compiler warnings when testing and only log them on `stencil build`, I find this option more intuitive based on previous experience, or provide an option like `--no-warning` to hide them.

I have quite a few false positives in one of my components and it makes the test results complicated to read, I have to scroll a loooot to find the failing test.

**Steps to reproduce:**
Have a code that prints custom stencil compiler warning and launch `stencil test`.

**Comment by dutscher** [comment]
the quick win is use `stencil test --silent` but this ignores your debug console.log()...

cheers

**Comment by MonsieurMan** [comment]
@dutscher That's a good idea for CI at least. Thanks ! :)

**Comment by rwaskiewicz** [comment]
👋 

Hey folks - The team is still working through the backlog of untriaged issues here in GitHub; I apologize that this issue hasn't been responded to until now. 

After discussing this with the rest of the team, this isn't something we're interested in pursuing at this time. As a result, I'm going to close this ticket out. Thanks for using Stencil, and once again I apologize for the lack of response here.
