### ISSUE TITLE
Generated components.d.ts has lint errors with backslashes on windows 10

### ISSUE THREAD

**Issue by CookieCookson** [ionic-team/stencil#196]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.6-4
```

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
components.d.ts has slashes going both ways when generated on Windows 10, causing a lint error.

![slashes](https://user-images.githubusercontent.com/3473396/31045285-014a6060-a5d8-11e7-8ce2-83956330fb2d.png)

**Expected behavior:**
There should be no lint errors, should the slashes be going the other way too?

**Steps to reproduce:**
`npm start` on Windows 10

**Comment by timweightman** [comment]
I believe your path is incorrect. You should be using a forward slash `/` instead. `\` is an escape character in a JavaScript string. You can see that the error message has mangled the file path.
