### ISSUE TITLE
Screendiff test overflow

### ISSUE THREAD

**Issue by AlexBeje** [ionic-team/stencil#1960]
**Stencil version:**

```
 @stencil/core@1.7.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The first time of the e2e test execution with screendiff it generates the 900 master images correctly.
When executed the second time, it fails.

**Expected behavior:**
When executed the second time it should compare the screenshots with the master ones.

**Steps to reproduce:**
Run test with 900 test screenshots to generate the masters and then run for the second time to compare.

**Other information:**
Here you have a repo test: https://github.com/AlexBeje/screendiff.git

Steps:
 - npm run i
 - npm run build
 - npm run test (generate master)
 - npm run test (compare) - FAILS

**Comment by viljamis** [comment]
@AlexBeje What’s the error you’re seeing exactly? Can you show both console output and what the screenshot diff webpage (generated) is showing?

**Comment by d0whc3r** [comment]
The internat variable "process.env.__STENCIL_SCREENSHOT_BUILD__" is overflow in the second execution of the tests and test comparision could not continue
https://github.com/ionic-team/stencil/blob/master/src/testing/jest/jest-screenshot.ts#L47

**Comment by d0whc3r** [comment]
![image](https://user-images.githubusercontent.com/1378986/67075228-0f3e4c80-f18b-11e9-8317-28bed15b13c1.png)
I just tested in linux and it is working, `process.env.__STENCIL_SCREENSHOT_BUILD__` have arround 45k chars

**Comment by AlexBeje** [comment]
Here are the screenshots of the console and the output screenshot diff webpage:

![1 console_log](https://user-images.githubusercontent.com/54982557/67075542-a7d4cc80-f18b-11e9-9e0d-f4328e83f062.PNG)
![2 screendiff_before(master)](https://user-images.githubusercontent.com/54982557/67075543-a7d4cc80-f18b-11e9-8d91-1c1aa10e052e.PNG)
![3 screendiff_after(compared)](https://user-images.githubusercontent.com/54982557/67075544-a7d4cc80-f18b-11e9-8864-4760e79cd615.PNG)

**Comment by d0whc3r** [comment]
any update?

**Comment by krumpli84** [comment]
Any updates on this issue?

**Comment by AlexBeje** [comment]
> Any updates on this issue?

No, still not working on Windows OS. At the moment we are waiting for a linux solution. We don't have any updates on the environment variable unfortunately.

**Comment by christian-bromann** [comment]
Hey folks 👋 

sorry for not addressing this issue for so long. We have been working on improving the testing situation for Stencil and now support WebdriverIO and Playwright frameworks which have excellent visual testing capabilities. I recommend to use these test frameworks for testing Stencil components moving forward.

Cheers
