### ISSUE TITLE
bug: Not hydrating in iOS 10

### ISSUE THREAD

**Issue by tricki** [ionic-team/stencil#1963]
**Stencil version:**
```
 @stencil/core@1.7.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
No components get hydrated.

**Expected behavior:**
Components get hydrated.

**Steps to reproduce:**
Open app in Safari on iOS 10.

**Other information:**
After some digging I found that the `nomodule` script (app.js) is being downloaded, but not the `type="module"` script (p-********.js). `app.js` only runs to this line, which evaluates to `false`:

```
    // Safari 10 support type="module" but still download and executes the nomodule script
    if (!currentScript || !currentScript.hasAttribute('nomodule') || !('onbeforeload' in currentScript)) { 
```

Commit which seems to have introduced this bug: https://github.com/ionic-team/stencil/commit/35d61a4

**Comment by tricki** [comment]
Just found https://github.com/ionic-team/stencil/issues/1900 which describes the same bug in the comments. Feel free to close this issue if the discussion should take place there.

**Comment by dutscher** [comment]
we decided to use the "loader" variant. we raised from 1.3.0 -> 1.7.0 and all our safari 10 user can't use the page now. 

see: https://github.com/ionic-team/stencil/issues/1900#issuecomment-546251427

cheers

**Comment by dutscher** [comment]
btw safari 10.0 on ios has a old webkit.performance api https://developer.mozilla.org/de/docs/Web/Web_Components

and breaks silently at `performance.mark()`, `performance.measure` & `performance.getEntriesByName`

to get rid of use `stencil build --no-profile`

**Comment by adamdbradley** [comment]
Thanks for the fix!
