### ISSUE TITLE
Jest throwing TypeError : this.inputEl.focus is not a function

### ISSUE THREAD

**Issue by kartikjagdale** [ionic-team/stencil#1964]
**Stencil version:**

```
 @stencil/core@1.7.0
```

**Jest version:**

```
   "jest": "24.8.0"
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I am trying to focus  a input element on button click.
Which works fine, however upon trying to test the functionality using `npm test` , `jest` throws a `TypeError` saying **focus is not a function.**

This bug is being repeated for all the manual event invoke like `click`, `blur`, `focus` .
 Hence the test cases doesn't pass.

**Expected behavior:**

It should not throw error.

**Steps to reproduce:**

I am providing a related demo code for inspection purpose.
**Related code:**

#### **`demo-btn.tsx`**
```tsx
import { Component, h, Element } from '@stencil/core';

@Component({
  tag: 'demo-btn',
  styleUrl: 'demo-btn.css',
  shadow: true
})
export class DemoBtnComponent {
  @Element() el!: HTMLElement;
  private inputEl?: HTMLElement;

  onClick = () => {
    if (this.inputEl) {
      this.inputEl.focus();
    }
  }

  render() {
    return (
      <div class="input-container">
        <input ref={el => this.inputEl = el} type="text" />
        <button onClick={this.onClick}>
          Click Me
      </button>
      </div>
    );
  }
}
```

#### **`demo-btn.spec.tsx`**
```tsx
import { newSpecPage } from '@stencil/core/testing';
import { DemoBtnComponent } from './demo-btn';

describe('my-component', () => {
  it('should focus input el on btn click', async ()=> {
    const page = await newSpecPage({
      components: [DemoBtnComponent],
      html: '<demo-btn></demo-btn>',
    });

    const btn = page.root.shadowRoot.querySelector('button')
    btn.click(); // Throws error after this line
    await page.waitForChanges();
    expect(true).toBeTruthy(); // For sake of completion
  });
});

```

Any Help will be appreciated. :smiley:

**Comment by kartikjagdale** [comment]
I Resolved this issue by mocking `focus` of input element.
Below is the code I tried out:

```
import { newSpecPage } from '@stencil/core/testing';
import { DemoBtnComponent } from './demo-btn';

describe('my-component', () => {
  it('should focus input el on btn click', async ()=> {
    const page = await newSpecPage({
      components: [DemoBtnComponent],
      html: '<demo-btn></demo-btn>',
    });

    /** Mock Input Elements focus function */
    const inputEl = page.root.querySelector('input');
    inputEl.focus = jest.fn();


    const btn = page.root.querySelector('button')
    btn.click();
    await page.waitForChanges();
    expect(true).toBeTruthy();
  });
});
```

Closing this issue. :smiley:

**Comment by kartikjagdale** [comment]
Re-opening the issue for much better solutions.

**Comment by bmerigan** [comment]
Struggling with similar issues myself, testing click, focus, mouseout, etc.

I notice your test doesn't actually test anything though. Is it's purpose just to improve code coverage?
`expect(true).toBeTruthy();`

**Comment by kartikjagdale** [comment]
@bmerigan I purposely kept it there to make pass the test case. It just a demo test case.

**Comment by elis-jones** [comment]
I am also experiencing an issue similar to this, when trying to test an IonInput which has setFocus called on its ref. 

` const ref = useRef<HTMLIonInputElement>(null);

  useEffect(() => {
    if (value.length === inputLength && nextInputRef)
      nextInputRef.current?.setFocus();
  }, [value]);`

This works as expected in the application, without issues. Whereas, when trying to test the input, jest spits out the following error: 

`    TypeError: _nextInputRef$current.setFocus is not a function

      22 |   useEffect(() => {
      23 |     if (value.length === inputLength && nextInputRef)
    > 24 |       nextInputRef.current?.setFocus();
         |                             ^
      25 |   }, [value]);
      26 | 
      27 |   return [value, setValue, ref];`

**Comment by mkay581** [comment]
Also having this same issue. I was surprised as focusing or clicking seems like a very basic thing to do in tests.

**Comment by elis-jones** [comment]
Solution I came to was to cast the type of the input element when declaring it. The following change in the test resolved the TypeError:

```
const input = getByTestId("verification-input") as HTMLIonInputElement
```

**Comment by mkay581** [comment]
That works if the input focus is called in a test. But it wouldn't work if the input is inside of a component and `focus` is called on it there. Also `getByTestId` is not a part of the Jest API btw 😛

**Comment by jfcere** [comment]
When using `focus()` function inside a LifeCycle method such as `componentDidLoad` the [workaround](https://github.com/ionic-team/stencil/issues/1964#issuecomment-545254598) provided by @kartikjagdale cannot be used since the LifeCycle method is triggered when `newSpecPage()` is executed.

The only workaround I found is to provide the `focus()` method on the prototype of `HTMLInputElement`.

**my-input.tsx**

```typescript
import { Component, h } from '@stencil/core';

@Component({
  tag: 'my-input',
  styleUrl: 'my-input.scss',
})
export class MyInput {

  private inputElement: HTMLInputElement;

  componentDidLoad() {
    this.inputElement.focus();
  }

  render() {
    return (
      <input ref={el => this.inputElement = el} type="text" />
    );
  }
}
```

**my-input.spec.tsx**

```typescript
import { newSpecPage } from '@stencil/core/testing';
import { MyInput } from '../my-input';

describe('my-input', () => {
  it('renders', async () => {
    // mock HTMLInputElement focus function
    HTMLInputElement.prototype.focus = jest.fn();

    const page = await newSpecPage({
      components: [MyInput],
      html: `<my-input \>`,
    });

    expect(page.root).toEqualHtml(`
      <my-input>
        <input type="text" \>
      </my-input>
    `);
  });
});
```

**Comment by dnnsjsk** [comment]
Last optional chaining instance fixed it for me:

```js
(focusEls[state.focusIndex] as HTMLElement)?.focus?.();
```

**Comment by tanmayghosh2507** [comment]
> When using `focus()` function inside a LifeCycle method such as `componentDidLoad` the [workaround](https://github.com/ionic-team/stencil/issues/1964#issuecomment-545254598) provided by @kartikjagdale cannot be used since the LifeCycle method is triggered when `newSpecPage()` is executed.
> 
> The only workaround I found is to mock the `focus()` method on the prototype of `HTMLInputElement` before `newSpecPage()` is executed.
> 
> **my-input.tsx**
> 
> ```ts
> import { Component, h } from '@stencil/core';
> 
> @Component({
>   tag: 'my-input',
>   styleUrl: 'my-input.scss',
> })
> export class MyInput {
> 
>   private inputElement: HTMLInputElement;
> 
>   componentDidLoad() {
>     this.inputElement.focus();
>   }
> 
>   render() {
>     return (
>       <input ref={el => this.inputElement = el} type="text" />
>     );
>   }
> }
> ```
> 
> **my-input.spec.tsx**
> 
> ```ts
> import { newSpecPage } from '@stencil/core/testing';
> import { MyInput } from '../my-input';
> 
> describe('my-input', () => {
>   it('renders', async () => {
>     // mock HTMLInputElement focus function
>     HTMLInputElement.prototype.focus = jest.fn();
> 
>     const page = await newSpecPage({
>       components: [MyInput],
>       html: `<my-input />`,
>     });
> 
>     expect(page.root).toEqualHtml(`
>       <my-input>
>         <input type="text" />
>       </my-input>
>     `);
>   });
> });
> ```

I have the similar situation. However, my focus element is HTMLTextAreaElement, but when I try to do:
`HTMLTextAreaElement.prototype.focus = jest.fn();`
I get the below error:
ReferenceError: HTMLTextAreaElement is not defined
Does someone have any idea?

**Comment by SavvasNicoleCandiotti** [comment]
bumping to ask if we have any solution to this issue
