### ISSUE TITLE
e2e unit tests crashing page

### ISSUE THREAD

**Issue by Grand-Poobah** [ionic-team/stencil#1966]
**Stencil version:**
 @stencil/core@1.4.0

**I'm submitting a:**
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
running single unit test using VS code causes random results. It will run once then crash the page

**Expected behavior:**
unit test should complete

**Steps to reproduce:**
I cannot reproduce that except in this web component

**Related code:**
         let element: E2EElement;
         let page: E2EPage = await newE2EPage();
         await page.setContent(`<xxx></xxx>`);
         await page.waitForChanges();

         element = await page.find('xxx');
         expect(element).not.toBeNull;

**Other information:**
the component will load once then fail after that with an aw snap 
    Page crashed!

      at Page._onTargetCrashed (node_modules/puppeteer/lib/Page.js:215:24)
      at CDPSession.Page.client.on.event (node_modules/puppeteer/lib/Page.js:123:56)
      at CDPSession._onMessage (node_modules/puppeteer/lib/Connection.js:200:12)
      at Connection._onMessage (node_modules/puppeteer/lib/Connection.js:112:17)
      at WebSocketTransport._ws.addEventListener.event (node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
      at WebSocket.onMessage (node_modules/puppeteer/node_modules/ws/lib/event-target.js:120:16)
      at Receiver.receiverOnMessage (node_modules/puppeteer/node_modules/ws/lib/websocket.js:789:20)

Note: 
A sample project that c hanges the config of puppeteer would helpful :)

**Comment by m-pollack** [comment]
I have been able to trace the issue to a web component hosted in the web components
The nested web component is very small when it is removed the crash happens less often.
If shadow is true the page will crash every time.  When false the page will crash on the test less often.  It seems that waiting a few minutes between running the test does affect how often the page crashes.


import { Component, Prop, h } from '@stencil/core';

@Component({
  tag: 'xxxz-xxxxxx',
  styleUrl: 'xxxxxxxxxxxx.css',
  shadow: false
})

export class XXxxxXxxxxXxxx {

@Prop() data: string;
@Prop() text: string = 'export';

  render() {
    return (
          <i class="fa fa-download"><span id="export2">{this.text}</span></i>
      </div>
    )

**Comment by matdec01** [comment]
We are experiencing the same behaviour. This is happening since upgrading Stencil to v1.x.x.

**Comment by segevofer** [comment]
We are experiencing the same behaviour as well.
There is no additional information about the fail, and my use-case is pretty simple.
This fails any test (the click)
```javascript
      const element = await page.find('my-custom-tag');
      await element.click();
```

**Comment by matdec01** [comment]
We are still experiencing this (using v1.13.0)
