### ISSUE TITLE
Check if object is Stencil Element and Get Properties

### ISSUE THREAD

**Issue by jogibear9988** [ionic-team/stencil#1972]
Hello,

I'm working on a WebComponents Designer Framework, for this I need to know if a "object" is a stencily component and read out the properties. Is this possible? Is it possible without needing a reference to stencil form my Editor Framework?

**Comment by jogibear9988** [comment]
see 
https://github.com/node-projects/web-component-designer/tree/master/src/elements/propertyHandlers

**Comment by christian-bromann** [comment]
You can use the `observedWatchers` property to identify if it is a Stencil component, e.g. 

```ts
const el = document.querySelector('my-cmp')
const isStencilComponent = Boolean(el?.constructor.observedAttributes)
```

Let me know if this works for you!
