### ISSUE TITLE
Stencil config src directory does not support array of strings

### ISSUE THREAD

**Issue by supproduction** [ionic-team/stencil#1975]
**Stencil version:**

```
 @stencil/core@1.7.1
```

**I'm submitting a:**

[x] feature request

**Current behavior:**
Stencil config src directory does not support array of strings

**Expected behavior:**
In case if we have multiple src folders in one project but in the different modules. There is impossible to add multiple src folders to the stencil config

**Comment by stanley85** [comment]
So for example you have several teams working on different source folders, and you want to compile all projects with the same compiler in one run?

**Comment by supproduction** [comment]
Yes, is it possible?

**Comment by stanley85** [comment]
Hey @supproduction I guess the best would be that each team sticks to its own dev stencil environment and each of the component libraries is published to npm as a package. Then your website framework would depend on them - have a look https://www.joshmorony.com/publishing-a-web-component-using-stencil-and-using-it-anywhere/

**Comment by supproduction** [comment]
Do you suggest to create separate stencil compiler in th each module? If we have 200 modules,do I need to publish each module due to path in the different folders? Does stencil has opprortunity to combine different modules paths?

**Comment by stanley85** [comment]
I assume you have control over each component library each with its own stencil dev environment and you look for a way to compile all at once without tearing apart each repository?
Please give more detail on what you want to merge and why.
You are using different component libraries you have control over on the same page?
How are they included, via script tag? What framework is the website using?

I suggested to have one npm package per library each containing a buch of components then add these few libraries to the main website.

**Comment by supproduction** [comment]
Our framework has over 200 modules with each own controller and own presentation.
Now we want to move all our modules some compiler/framework which will give us an opportunity to transform our components to the web components. I've already investigated (direflow, svelte, lit element) and almost all of them have big cons for us - they don't supprort component inheritance. Unfortunately stencil too.

Yes have control over every component library each with its own backend dev environment and we are looking for a way to compile all UI at once without tearing apart each repository. That's why we need one bundle which will be collected from one place via one npm command from the root one of our project, and it should sniff all our modules to detect custom element, also we have two levels of modules (project and vendor) and I need to filter from vendor modules all same UI which exist in the vendor project, that's why we need entry points support. And it is impossible to add stencil compiler to each of them.

Thats why I had a question about multiple entries which give us an opprtunity to compile entries not only from src stencil folder.
