### ISSUE TITLE
Component fails in IE11 when <base target=""> is defined.

### ISSUE THREAD

**Issue by jpapillon** [ionic-team/stencil#1978]
**Stencil version:**
```
 @stencil/core@1.7.4
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
On a fresh component project install, if `<base target="">` is defined in `index.html`, a blank page is rendered in IE11.

**Expected behavior:**
The components should be rendered in IE11.

**Steps to reproduce:**
1. `npm init stencil`
2. Open `src/index.html` and add `<base target="">` inside the `<head>...</head>` section.
3. `npm start --es5`
4. Open IE11 and load the component app.

**Other information:**
* It works in other browsers.
* It works with IE using StencilJS up to version 1.1.3.

**Comment by tanner-reits** [comment]
Hey @jpapillon  👋 

Sorry you never heard from the team on this, but I'm going to close out this issue as Stencil has officially deprecated support for IE11 as a part of the v3 release (see [Stencil's browser support page](https://stenciljs.com/docs/browser-support)). But, please let us know if this behavior is experienced in any of our supported browsers.

Thanks!
