### ISSUE TITLE
Listening to an event on the host element will trigger re-render even if no attributes have changed

### ISSUE THREAD

**Issue by mortenson** [ionic-team/stencil#198]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
$ npm list @stencil/core
ame-components@0.0.1 /Users/samuelmortenson/repos/ame-components
└── @stencil/core@0.0.6-4
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

After adding a `@Listen('click')` callback to my component, it appears that every time the component is clicked `render()` will be called, even if no attributes have been changed.

**Expected behavior:**

For performance and usability reasons, listening to an event should not imply that every time that event is triggered `render()` will be called. Components should be responsible for changing attributes if a re-render is needed.

**Steps to reproduce:**

1. Clone https://github.com/mortenson/ame-components
1. Run `git checkout b8941e2bbe9de75c8e5b446fe8ae131003bf8e91` (commit before I started working around this by having the event trigger on a child element instead).
1. Run `npm install && npm start`
1. Open your browser's dev tools and find the `ame-text span` element, then click the "Hello, world!" text a few times. My listener should only trigger a `render()` one time when `this.editing` is set to `true`, but it appears that a render happens regardless of what's in my callback.

**Related code:**

The component I'm working with: https://github.com/mortenson/ame-components/blob/b8941e2bbe9de75c8e5b446fe8ae131003bf8e91/src/components/ame-text/ame-text.tsx#L15

**Other information:**

**Comment by mortenson** [comment]
This is fairly well documented here: https://github.com/ionic-team/stencil/blob/master/src/core/instance/listeners.ts#L162-L168
```typescript
    if ((elm as HostElement).$instance) {
      // only queue an update if this element itself is a host element
      // and only queue an update if host element's instance is ready
      // once its instance has been created, it'll then queue the update again

      // queue it up for an update which then runs a re-render
      (elm as HostElement)._queueUpdate();
```
But I'm not sure why this code exists - shouldn't an element only be rendered if a State or Prop attribute changes? For me the current behavior is not intuitive.

**Comment by adamdbradley** [comment]
Yeah this might be removable since some previous refactors. Thanks for creating the issue.

**Comment by adamdbradley** [comment]
Removed in this commit: https://github.com/ionic-team/stencil/commit/e92c79cd0407f9e32977afeb31bc5c4d83ca1ab5

Thanks!
