### ISSUE TITLE
Dynamic Import Not Working in IE11

### ISSUE THREAD

**Issue by caseywoolley** [ionic-team/stencil#1981]
**Stencil version:**

```
 @stencil/core@1.7.4
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Dynamically injecting a script tag referencing an es5 stencil bundle in IE11 will fail when it tries to load subsequent files.

**Expected behavior:**

Should bootstrap stencil components.

**Steps to reproduce:**

Inject a script tag referencing the es5 version of a stencil bundle on a webpage running in IE11.

**Related code:**

```tsx
    const script = document.createElement('SCRIPT');
    script.type = 'text/javascript';
    script.src = 'https://path/to/es5/stencil/bundle.js';
    div.appendChild(script); // Does not work.
    document.body.appendChild(script); // Works!
```

**Other information:**

The Stencil es5 loader script finds the last script on the page and determines that to be it's parent script.  If you inject the script anywhere other than the bottom of the page it will use the bottom script to determine the url for loading additional scripts and fail when it can't find it's bundles.

**Comment by julesjanssen** [comment]
Had the same problem, tried to fix it with #1918, but later found out it only works if the script is indeed at the bottom of the page.
You may want to work around this by setting a `data-resources-url` property on the script tag.

**Comment by caseywoolley** [comment]
The ```data-resources-url``` property doesn't help with this issue.  The stencil loader script always grabs the bottom script on the page to determine its resource url.  It won't read the ```data-resources-url``` property on your script tag unless it happens to be the bottom script tag on the page.

**Comment by TheILPlace** [comment]
we are facing a similar issue.
in our angular application, we wanted to load the stencil components dynamically with "createElement" method mentioned by the OP.
we do this, because in each environment, the location of the stencil components is different (and we cannot use relative paths".

so if create a tag loading the file from a http://localhost/mycomponents  location , and i use angular's ng serve   to run the application, stencil tried to fetch additional js files from localhost:4200 instead of the http://localhost/mycomponents

**Comment by TheILPlace** [comment]
@caseywoolley 

i've updaed to the latest version 1.8.1  and it seems to solve this issue !
seems to work fine now on IE11 with dynamically loading the stencil files.

**Comment by alicewriteswrongs** [comment]
Hi @caseywoolley, thanks for filing this issue and sorry you had trouble with dynamic imports in IE11. 

Just fyi, we [recently deprecated IE11 support in Stencil 3](https://stenciljs.com/docs/browser-support) although it is still supported in [Stencil 2 which is currently in maintenance](https://stenciljs.com/docs/support-policy#stencil-maintenance-and-support-status). 

Are you still experiencing this issue on newer versions of Stencil? If not, does updating to a newer version and doing some of the workarounds suggested above address the issue for you?
