### ISSUE TITLE
failed to run "npm start" after setting a namespace on stencil.config.ts

### ISSUE THREAD

**Issue by BrunoUY** [ionic-team/stencil#1982]
**Stencil version:**

```
 @stencil/core@<1.7.5>
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
After setting a namespace for an "ionic + stencil PWA", I run "npm start" to watch it, and nothing appears on the screen, but on the console, this message appears:

Failed to load resource: the server responded with a status of 404 (Not Found)
app.esm.js:1
Failed to load resource: the server responded with a status of 404 (Not Found)
app.css:1 

when run "npm start" on the console appears the error

**Expected behavior:**

**Steps to reproduce:**

I wanted to build a ./dist so I set the outputTarget as:

```
export const config: Config = {
  outputTargets: [
    {
      type: 'www',
      serviceWorker: null
    },
    {
      type: 'dist', // I add this
    }
  ],
  globalScript: 'src/global/app.ts',
  globalStyle: 'src/global/app.css'
};
```

then I run "npm run build" and I was asked to put a namespace so I put:
```
export const config: Config = {
  namespace: 'SmsLandings', // I add this
  outputTargets: [
    {
      type: 'www',
      serviceWorker: null
    },
    {
      type: 'dist',
    }
  ],
  globalScript: 'src/global/app.ts',
  globalStyle: 'src/global/app.css'
};
```

then run "npm run build" and everything works fine ( the /dist and /www ) folder is created, but when I do "npm start" the error on the browser reproduce

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

1) When I comment the code on stencil.config.ts the:
( namespace property, and object type: 'dist' ) and then run "npm start" everything works as expected.

2) Also, I have noted that on the /dist and /www folders the name of the files are created correctly, they nave the names:
smslandings.css, smslandings.esm.js, smslandings.js
So maybe it's the reference that is pointing to app.js, app.esm.js what is wrong.

3) Maybe it's related to this: ( I have the same issue when I was trying to use the baseUrl with a folder, I commented on this issue )
https://github.com/ionic-team/stencil/issues/651

It looks like in the console when it says "failed to load resource... app.esm.js" I don't know if "app" is the name of the namespace or not?

thank you.

**Comment by trollr** [comment]
same issue here

**Comment by Salman2301** [comment]
Had the same issue fixed by updating the index.html ( and package.json )

If anyone else have this issue just update the index.html with the correct namespace.

```
<script type="module" src="/build/{namespace}.esm.js"></script>
<script nomodule src="/build/{namespace}.js"></script>
```
