### ISSUE TITLE
CSS custom property with undefined value

### ISSUE THREAD

**Issue by Leandro-Albano** [ionic-team/stencil#1986]
**Stencil version:**
 @stencil/core@1.7.5

**I'm submitting a:**
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I set a css custom property in the style property of the component with `undefined` value it still been set to the style attribute with an string undefined.

**Expected behavior:**
Undefined properties should be ignored.

**Steps to reproduce:**
Create any element and set the style property with an css custom property with `undefined` value.

**Related code:**
```
import { Component, h } from "@stencil/core";

@Component({
  tag: "test-component",
  shadow: true
})
export class TestComponent {
  public render() {
    return (
      <div
        style={{
          "--test": false ? "10px" : undefined
        }}
      ></div>
    );
  }
}
```

**Other information:**

**Comment by stanley85** [comment]
This is a feature request :) If the div was the Host reference one may imply some magic, but here its a simple div, magic analysis in this case goes beyond what I would expect stencil todo.

**Comment by Leandro-Albano** [comment]
Sorry, I didn't get what mean with magic. I mean, there is no magic in the fact that it should ignore properties set to undefined. I don't see the use case where I would like to have an undefined style prop set with the string 'undefined'. Just to make sure you got what I'm saying this produces the same issue:

import { Component, h } from "@stencil/core";

```
@Component({
  tag: "test-component",
  shadow: true
})
export class TestComponent {
  public render() {
    return (
      <div
        style={{
          "--test": undefined
        }}
      ></div>
    );
  }
}
```
I just think undefined properties should be ignored on element's the style attribute.

**Comment by stanley85** [comment]
Put the value you want to place there inside a condition or build up the style settings by hand. 
Some similar like this:

`public render() {
    let styleAttributes = {};
    if (this.yourUndefinedValue) {
       styleAttributes["--test"] = this.yourUndefinedValue;
    }
    return (
      <div
        style={styleAttributes}
      ></div>
    );
  }`

**Comment by Leandro-Albano** [comment]
Yeah, I know I could do that, in fact is the workaround I've done.

My issue is not about how to workaround this, I'm just saying that it should not be necessary, `undefined` should be ignored.

**Comment by stanley85** [comment]
[X] feature request - described as a bug to a feature not implemented :D

**Comment by Leandro-Albano** [comment]
I got your point of view, but I don`t agree that is a feature request.
Like undefined values should be handled in the correct way.

Undefined value is not supposed to be serialized, I think that would be a feature request, a weird one btw.

**Comment by stanley85** [comment]
Ok but this I guess that is browser behaviour, open any dom node explorer and add test=undefined - becomes a string, chrome and firefox do this, ie wont let you do but i guess IE renders the same. So ignoring undefined as a value may become a bigger task.

**Comment by christian-bromann** [comment]
Hi @Leandro-Albano 👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
