### ISSUE TITLE
Minify css

### ISSUE THREAD

**Issue by javyxx** [ionic-team/stencil#1987]
**Stencil version:**

```
 @stencil/core@latest
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

**Expected behavior:**

It would be an interesting functionality to support the shaking of trees in the css

**Steps to reproduce:**

**Related code:**
Similar to how the uncss or PurgeCSS project does

**Other information:**

**Comment by adamdbradley** [comment]
This should be happening when prerendering.
