### ISSUE TITLE
Dependency conflicts when including multiple loaders on a page

### ISSUE THREAD

**Issue by mortenson** [ionic-team/stencil#199]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
$ npm list @stencil/core
component-1@0.0.1 /Users/samuelmortenson/repos/stencil-ssr-problem/component-1
└── @stencil/core@0.0.6-0
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

If two Stencil component collections define the same dependency as a part of the `config.collections` value in stencil.config.js, you can not include both collections on a page. "include" here means loading both collection loaders in `<script>` tags on the page.

**Expected behavior:**
I would assume that unless two collections explicitly define the same element as a part of their `src/` directories, that Stencil would be able to handle dependency conflicts.

**Steps to reproduce:**

Clone https://github.com/mortenson/stencil-dependency-heck and start a web server in the root directory, then visit index.html in your browser. You should see errors as two collections are included on the page that both rely on `@stencil/router`.

**Other information:**

This is going to become a bigger problem as more users adopt Stencil and start depending on common components (ex: `@ionic/core`) in their collections. It seems like the only way to handle this right now is to have one collection that includes all other collections, and only include one loader on each page. This is OK for advanced users, but I think there's a lot of benefits to being able to drop any number of Stencil components on any web page and have them all work together.

The Drupal integration I'm working on (https://www.drupal.org/project/stencil) is bringing web components to a less-technical audience who is definitely going to run into this. If the current behavior is just how Stencil works, then I'll have to write some code to prevent loaders with dependency conflicts from loading on the same page.

**Comment by adamdbradley** [comment]
Yeah good thinkin, thanks!
