### ISSUE TITLE
IE11 removing node with stencil component cause a crash

### ISSUE THREAD

**Issue by telubeer** [ionic-team/stencil#1990]
**Stencil version:**

```
 @stencil/core@1.7.5
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

at IE11 
```
var el = document.querySelector('my-component'); el.parentElement.removeChild(el);
```
cause a crash, where my-component is a stencil.js component

**Expected behavior:**

dom node removed without a crash

**Steps to reproduce:**

demo here https://github.com/telubeer/stencil-ie11-crash-demo

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
