### ISSUE TITLE
Disable copy command 

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/stencil#200]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
`-- @stencil/core@0.0.6-4
```

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When putting copy: {} in your stencil.config.js it doesn't stop the copying from occuring.

**Expected behavior:**

I should be able to put copy: false or {} to stop it from copying assets, ect.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by jgw96** [comment]
Thanks for using Stencil! We will look into getting this feature in, although it may be a little while before it does make it in. @popcorn245 would you be interested in doing a PR to implement this?

**Comment by adamdbradley** [comment]
This should be fixed as of `0.0.6-10`. To disable the copy task entirely, set the copy config to `false` or `null`. Thanks!
