### ISSUE TITLE
Prepare for puppeteer-firefox

### ISSUE THREAD

**Issue by romulocintra** [ionic-team/stencil#2000]
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
e2e are build on top of puppeteer that runs chrome.

**Expected behavior:**
I would like to use [puppeteer-firefox](https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox) to and run test in the future 2 most popular engines.

I know that it still in experimental phase... but just to keep it in radar

**Comment by romulocintra** [comment]
I did a quick review in the  code related with e2e and, IMHO codebase will benefit in some abstraction to enable connect webdriver etc etc ...

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. If more requests are made we'll reevaluate then. Thanks.
