### ISSUE TITLE
Slot Changes Re-Rendered in Wrong Location on IE11/Edge

### ISSUE THREAD

**Issue by umdjm** [ionic-team/stencil#2004]
**Stencil version:**
```
 @stencil/core@1.7.5
```

**I'm submitting a:**
[ X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Adding child element to a slot on IE11 or Edge displays below template.

**Expected behavior:**
Element displays adjacent to original slot content.

**Steps to reproduce:**
Open https://umdjm.github.io/StencilFallbackDemo/ on IE11
Code https://github.com/umdjm/StencilFallbackDemo

**Related code:**

```tsx
  render() {
    return <div>
      HEADER
      <br/>
      SLOT GOES HERE (
        <slot />
      )
      <br/>
      FOOTER
    </div>;
  }
```
```Usage
    <my-component>
      <p> Initial Slot Data </p>
    </my-component>
```
**Other information:**
## IE Screenshot
![IE Screenshot](https://umdjm.github.io/StencilFallbackDemo/assets/img/IE_Screenshot.png)
## Chrome Screenshot
![Chrome Screenshot](https://umdjm.github.io/StencilFallbackDemo/assets/img/Chrome_Screenshot.png)

**Comment by umdjm** [comment]
When I change [vdom-render](https://github.com/ionic-team/stencil/blob/master/src/runtime/vdom/vdom-render.ts#L602) to not reset checkSlotRelocate, I can get this to work on IE with a MutationObserver in my component.

```
export class MyComponent {
  observer!: MutationObserver;
  connectedCallback() {
    this.observer = new MutationObserver(this.handleChildrenChange);
    this.observer.observe(this.host, { childList: true });
  }

  @Element() host: HTMLElement;
  handleChildrenChange = () => {
    (this.host as any).forceUpdate();
  };
```

This does not seem like the right fix, but maybe this can help point others to a better fix?

**Comment by dutscher** [comment]
it seems tobe related to #1968
cheers

**Comment by umdjm** [comment]
Nice - thanks @dutscher.  Did you also see https://github.com/ionic-team/stencil/pull/1197 which had a commit yesterday: https://github.com/ionic-team/stencil/pull/1197/commits/5ea2a4822e0fee5414e840027510154f39a9745e

**Comment by dutscher** [comment]
@umdjm i updated the repo to 1.8.0 and the rerender bug still exists. 
see here https://dutscher.github.io/stencilslots/

cheers

**Comment by umdjm** [comment]
This is fixed for me in v1.8.0 (thanks to https://github.com/ionic-team/stencil/pull/1197).  

I still have to add a MutationObvserver as mentioned in https://github.com/ionic-team/stencil/issues/2004#issuecomment-552691394.

I'm having other issues with React using IE11 Stencil Components, but I'll try to create a tight repro and open that separately.

**Comment by umdjm** [comment]
FYI - @dutscher is still having issues with parent and child re-renders but my simpler use case looks fixed.

**Comment by umdjm** [comment]
Opened https://github.com/ionic-team/stencil/issues/2012 to track the React issue mentioned in https://github.com/ionic-team/stencil/issues/2004#issuecomment-554318171
