### ISSUE TITLE
Cannot deploy to a subfolder path

### ISSUE THREAD

**Issue by realharry** [ionic-team/stencil#2006]
**Stencil version:**

```
 @stencil/core@1.5.2
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

* If the app is deployed to a non-root path, it fails to display.

**Expected behavior:**

* The app should be deployable to any path on website.

**Steps to reproduce:**

* Create a blank app using ionic-pwa template.
* Deploy to github/gitlab pages. e.g., https://a.gitlab.io/starter/
* The page serves blank index.html with 404s for all assets and js files.

**Comment by realharry** [comment]
1. Upgraded @stencil/core to 1.8.0, but it didn't help.
1. Tried `baseUrl` per https://stenciljs.com/docs/www, but it didn't help. The output was written to www/subfolder, but all asset URLs were still hard-coded from the root "/".

**Comment by ChrisJAllan** [comment]
It seems you need to change the paths in `index.html` manually, the `baseUrl` setting doesn't do it for you.

**Comment by dodgyville** [comment]
Hi, I was wondering if there was a way around this?

I have a stenciljs web app I would like to deploy in a sub folder on apache2 (eg /var/www/html/genet/)

However, setting the baseURL to "/genet/" does not appear to affect assets or js files, so when it is deployed by copying the files from the stenciljs build in www/genet/ there are a lot of broken links.

**Comment by alicewriteswrongs** [comment]
Hi @realharry I'm sorry you experienced issues using Stencil and this issue went uncommented on by the Stencil team for so long.

To help us diagnose and fix issues like this it's tremendously helpful to have a reproduction case, for instance a github repo showcasing the problem. If you're still dealing with this issue we would greatly appreciate it if you provided one!
