### ISSUE TITLE
Feature Request: Ionic like serve on local network

### ISSUE THREAD

**Issue by kars-springbok** [ionic-team/stencil#2009]
**Stencil version:**

```
 @stencil/core@<1.7.5>
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently if you do a npm run start / serve it only does it for your local machine of course. 

**Expected behavior:**

What would be great is a serve option like the Ionic framework has. Allowing the local application also to be accessed by the local network IP, if you're on the same WiFi. This would make it easier to test Stencil components out on Mobile devices or other laptops (Windows for IE11) without having to go a lot of steps like deploying to a staging server.

**Other information:**

At the moment the Stencil package brings a lot of help in order to rapidly produce quality web components. However the ONLY thing I find lacking is the feature that Ionic has. Since it's from the same developers I hope it would be easier for you guys to implement that functionality into the Stencil project. This way individual developers in teams can test their components on IE and Mobile devices, instead of deploying for each branch to a staging server so they can test around on real devices and other browsers (IE 11)

**Comment by cjorasch** [comment]
I think it works that way already.

If I run `stencil build --dev --watch --serve` then I can access the app using either:
- `http://localhost:3333`- can be used on the dev computer
- `http://192.168.X.XXX:3333` - use the local IP address of the dev computer

This allows me to run in a browser on the dev machine or from a mobile device on the local network.

**Comment by kars-springbok** [comment]
Hmm it works indeed, just that the command doesn't actually outputs it. 

Thanks a lot @cjorasch this really helped me out :) 

Maybe worth putting it in the Documentation!
