### ISSUE TITLE
DOM events encapsulation polyfill

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#2010]
DOM events stop are shadow-dom boundaries, and the event that crosses the boundaries (composed), have a different target.

**Comment by christian-bromann** [comment]
Thanks @manucorporat for raising the issue.

At this point the StencilJS team is not sure anymore what to do about this and if this still applies to the latest Stencil version. Feel free to provide more background but I will go ahead and close the issue.

Thanks for all your work on this project!
