### ISSUE TITLE
Electron: avoid es module script pattern

### ISSUE THREAD

**Issue by Nudelsieb** [ionic-team/stencil#2011]
**Stencil version:**

```
 @stencil/core@1.8.0
```

**I'm submitting a:**

[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

In recent versions Stencil introduded the ES Module script pattern.

BEFORE:
```html
    <script src="/build/app.js"></script>
```
AFTER:
```html

  <script type="module" src="/build/app.esm.js"></script>
  <script nomodule src="/build/app.js"></script>
```

This is a huge problem in Electron, which does not support this syntax when packed. The app will attempt to load from the file system, which does not supply the right mime types (IIRC). Subsequently all requests to the js chuncks fail.

<img width="898" alt="Screenshot 2019-11-15 at 09 30 01" src="https://user-images.githubusercontent.com/12937991/68933836-68e76600-078d-11ea-9df4-d859c12dd20b.png">

To mitigate this issue, we  use the old `<script src="/build/app.js"></script>` in the `index.html`. However, during development, the browser (Electron render thread) is presented with an overlay telling us that we should use above newer syntax. 

![Screenshot 2019-11-14 at 11 30 26](https://user-images.githubusercontent.com/12937991/68933875-7ac90900-078d-11ea-86fb-fbcd91160e4d.png)
There is no way of getting rid of this nasty overlay. To mitigate this we use the `--es5` build flag in dev mode, which presents other issues (e.g. warnings on command line, slow builds, etc).
 
**Expected behavior:**

It would be nice if there were a way to use esnext in electron builds both in production and development. Maybe there needs to be a Stencil config override or additional Electron switch.

Thanks for your help.

**Comment by Nudelsieb** [comment]
Here is an explanation that might help https://stackoverflow.com/questions/51113097/electron-es6-module-import/56184515#56184515

**Comment by manucorporat** [comment]
In that case just use:
```
  <script src="/build/app.js"></script>
```

But we recommend you to use the module in electron too, it's possible to register HTML-like protocols, serving your app using file is a bad idea.

**Comment by Nudelsieb** [comment]
Yes, we're using `<script src="/build/app.js"></script>`, which works in production (built Electron package). But Stencil does not allow it during dev (when serving from a dev server), unless you use `--es5` command. Could we re-open that ticket?

**Comment by Nudelsieb** [comment]
I found a workaround:

Use `srcIndexHtml` inside stencil.config.ts to point to a different index.html during dev.

```typescript
const isDevMode = process.argv.includes('--dev');
const srcIndexHtml = isDevMode ? 'src/index.dev.html' : 'src/index.html';

export const config: Config = {
  srcIndexHtml,
...
};
```
