### ISSUE TITLE
Question: compile only component

### ISSUE THREAD

**Issue by zigomir** [ionic-team/stencil#202]
Would be nice if one could compile only component like so

```sh
npx stencil my-component.tsx > my-component.js
```

and only getting vanilla custom component (v1) back.

Is this something stencil will ever support or you're more focused on "wholesome" solution to provide everything there is needed for old browsers and dynamic loading?

**Comment by adamdbradley** [comment]
Yeah this has been in the back of our minds, and to wrap up one component to be one stand-alone file. It'll be a compiler option in the future. Thanks!

**Comment by zigomir** [comment]
Neat, thank you!
