### ISSUE TITLE
Compiler throws error regarding to `Matchers`

### ISSUE THREAD

**Issue by marchbox** [ionic-team/stencil#2022]
**Stencil version:**

```
 @stencil/core@1.8.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When running `stencil build`, the following errors showed up, this wasn't case with 0.8.0:

```
[ ERROR ]  TypeScript: node_modules/@stencil/core/dist/declarations/testing.d.ts:4:19
           All declarations of 'Matchers' must have identical type parameters.

      L3:  namespace jest {
      L4:      interface Matchers<R, T> {
      L5:          /**

[ ERROR ]  TypeScript: node_modules/@types/jest/index.d.ts:531:31
           Generic type 'Matchers<R, T>' requires 2 type argument(s).

    L530:   */
    L531:  <T = any>(actual: T): Matchers<T>;
    L532:  /**

[ ERROR ]  TypeScript: node_modules/@types/jest/index.d.ts:606:15
           All declarations of 'Matchers' must have identical type parameters.

    L606:      interface Matchers<R> {
    L607:          /**

[35:27.9]  build failed in 5.47 s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ark@0.0.1 build: `stencil build --docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ark@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by JohnHardy** [comment]
I ran into this error this morning. I updated all my node modules and set these specific versions, then it worked: https://github.com/ionic-team/stencil/issues/1976#issuecomment-547793960

**Comment by aharris** [comment]
I ran into this in the stencil-ds-plugin and put in PR rolling back to `24.0.19` https://github.com/ionic-team/stencil-ds-plugins/pull/20

**Comment by cary-smith** [comment]
@marchbox - Updating `@types/jest` fixed it for us.

**Comment by marchbox** [comment]
@cary-smith Thanks! I think it may have been fixed for me with that.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
