### ISSUE TITLE
npm install protobufjs not working but it works well from cdn

### ISSUE THREAD

**Issue by derldalfor100** [ionic-team/stencil#2025]
Why StencilJs not working well with protobufjs?
![WhatsApp Image 2019-11-19 at 23 27 32](https://user-images.githubusercontent.com/28383676/69188114-9123eb80-0b24-11ea-8b98-45a0f5b0a717.jpeg)

**Comment by rwaskiewicz** [comment]
Hey @derldalfor100 👋 

I apologize it took so long for someone on the team to take a look at this issue.  Given the age of the issue, it's hard to tell what version of Stencil/protobufjs you were using and how.  If you're willing/able, we'd love it if you could open a new issue in the repo here with the latest version of Stencil.  Thanks!
