### ISSUE TITLE
Spec page returns incorrect "root" value for nested components (easy fix)

### ISSUE THREAD

**Issue by DesignByOnyx** [ionic-team/stencil#2027]
**Stencil version:**
```
 @stencil/core@1.8 (also present in 1.7.5, probably earlier)
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
Regarding the spec-page, whenever a component is nested inside another element, the "root" property only returns the component on the first read. Every subsequent read returns the `body.firstElementChild`:

```jsx
const page = await newSpecPage({
	components: [MyComponent],
	html: '<div><my-component /></div>',
});
page.root === page.root; // FALSE:  my-component === div 
page.root === page.root; // TRUE:  div === div
```

**Expected behavior:**
Once a component is found, always return that component.

**Related code:**
https://github.com/ionic-team/stencil/blob/96eec7448bfc181f9ad4debd8d004d2ba1ac6a36/src/testing/spec-page.ts#L171-L183

The getter function will only return the "rootComponent" once. The fix is easy - just make sure to return the rootComponent if it has a value:

```tsx
    get() {
      if (rootComponent == null) {
        rootComponent = findRootComponent(cmpTags, page.body);
      }
      // the following condition must be moved OUTSIDE of the above condition
      if (rootComponent != null) {
        return rootComponent;
      }
      const firstElementChild = page.body.firstElementChild;
      if (firstElementChild != null) {
        return firstElementChild as any;
      }
      return null;
    }
```

**Comment by adamdbradley** [comment]
Good catch, thanks
