### ISSUE TITLE
Edge and IE CSS rendering issues.

### ISSUE THREAD

**Issue by toma-paul** [ionic-team/stencil#2029]
After many trials i've encountered an issue which i cannot find an adequate solution to. This is a problem which i've encountered mainly on Edge and IE 11. I have the following component which is structured in the following way:

`
```
@Component({
  tag: 'custom-product-component',
  styleUrl: 'product.scss',
  shadow: true,
})
export class Product {
render() {
    return (
    <div class="product__container__content__text">
                <custom-text-component  text={this.product.body}/>
            </div>
 );
  }
}

@Component({
  tag: 'custom-text-component',
  styleUrl: 'text.scss',
  shadow: true,
})
export class Text {
  @Prop() text: string;

 render() {
    return (
   <div class={this.type} innerHTML={this.text} />
    );
  }
}
```
`

The string, text prop ,that is being passed is the following : "`<ul><li><span>Lorem Ipsum <b>latin word</b></span></li></ul>`".

The issue that i've encountered is that the css that i've declared in the text.scss file is not being processed or applied to the <ul> <li> tags. What i've noticed is that after making small changes to the scss file and saving the styling gets applied to all the tags. My first guess would be , correct me if i'm wrong, is that the CSS gets processed before the elements are rendered to the screen . This works fine on other browsers but not on the mentioned ones. I'm guessing this is related to the use of the ShadowDOM because once i try setting the shadowdom to false on custom-text-component the css is properly processed and applied to the tags. 

What i've tried so far.
 - Polyfills would be the immediate obvious solution even though in this case the properties that are applied do not require them , so that is not the issue. 
- Targeting the elements with CSS specific syntax and not SCSS.
- Disabling the shadowDOm is the only thing that seems to have worked. I would much rather not go with this solution since scoped css is something which is required for this project.

If the issue turns out to be that the css is processed before the elements are rendered. Is there any work-around that enforces the reprocessing of the css after the render . Or do you guys have any other tips on how i might circumvent this issue?

**Comment by stanley85** [comment]
Try `getText(): string { return this.text; }` and in the render call this `innerHTML={this.getText()}` should do the trick.

**Comment by toma-paul** [comment]
I've tried this solution but it didn't work

**Comment by stanley85** [comment]
Hhm what happens if you add a watcher for this.text

`@Watch('text') textChangeHandler(newValue: string, oldValue: string) {`
`console.log(newValue);`
`}`

if that does not work try with some old fashioned code inside the watcher function

`@Element() element: HTMLElement`
`@Watch('text') textChangeHandler(newValue: string, oldValue: string) {`
`let elementToPaint = this.element.querySelector('.' + this.type);`
`elementToPaint.style.display='none';`
`elementToPaint.style.offsetHeight; // no need to store this anywhere, the reference is enough`
`elementToPaint.style..style.display='block';
`}`

**Comment by toma-paul** [comment]
Hey stanley , thank you for taking the time to answer this. I've tried the solutions you've suggested, unfortunately to no avail. The Watcher doesn't trigger as the prop is never updated. As for the second solution, i've tried placing that code into the componentDidLoad lifecycle. This does trigger and changes the styling but the end result is the same, the css is not applied.

**Comment by stanley85** [comment]
Ah I think the use of a slot is the better option, does this work?

```
@Component({
    tag: 'custom-product-component',
    styleUrl: 'product.scss',
    shadow: true,
})
export class Product {
    // [...]
    render() {
        return (
            <div class="product__container__content__text">
                <custom-text-component>
                    {this.product.body}
                </custom-text-component>
            </div>
        );
    }
}

@Component({
    tag: 'custom-text-component',
    styleUrl: 'text.scss',
    shadow: true,
})
export class Text {
    // [...]
    render() {
        return (
            <div class={this.type}>
                <slot></slot>
            </div>
        );
    }
}

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize that it took so long for a member of the team to acknowledge this ticket. With Stencil v3, we've officially deprecated support for IE 11/older versions of Edge. I've labeled this for the team to consider prior to dropping all support for IE 11. Thanks!
