### ISSUE TITLE
Type 'typeof h' has no call signatures.

### ISSUE THREAD

**Issue by Leandro-Albano** [ionic-team/stencil#2034]
**Stencil version:**

```
 @stencil/core@1.8.1
```

**I'm submitting a:**

[ X ] bug report

**Current behavior:**
It's not possible to call `h("tag-name")` without casting it to `any` before.
Typescript return a compile error

```
This expression is not callable.
  Type 'typeof h' has no call signatures.
```

**Expected behavior:**
calling `h("tag-name")` works fine

**Steps to reproduce:**

Just try to call `h("tag-name")` in any component

**Comment by jhesgodi** [comment]
Are there any updates on this issue? I'm having trouble with this as well

[BREAKING_CHANGES.md](https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md#import--h--is-required) states that `h` is  equivalent to React's `React.createElement` with following example:

```jsx
const jsx = <ion-button>;
// is the same as:
const jsx = h('ion-button', null, null);
```
I took a look and they are not equivalent.

### I'm facing an issue in where I can't render a component with props using `h` function.

- `React.createElement` takes a second argument as `props: any` and then pass it to the component.
- Stencil's `h` takes a second argument as `data: vNodeData` meaning that only `class|className|style` attributes will be passed to the component. [as seen here](https://github.com/ionic-team/stencil/commit/d9c50ad45c1ce7efce431dc29d7f36b91a323f95#diff-f41e9d04a45c83f3b6f6e630f10117feR71) leaving behind any other given keys in the props object.

Is there a way to achieve the same behavior as in `React.createElement`?

I'm just want to mount my kitchen sink components dynamically from a set of mocks, like this:

```jsx
import { mocks } from 'components/index';

...
  render() {
    return (
      <div>
        {mocks.map(({ children, ...props }) => h(tag, props, children))}
      </div>
    );
  }
```

**Comment by tanner-reits** [comment]
Hi @Leandro-Albano 👋 

Thanks for logging this issue and sorry it's sat for so long! I just ran a quick check in the latest version of Stencil and didn't run into any type of compiler warnings. If you're still experiencing issues, please update the issue with a minimum reproduction repo. Otherwise, the team will look to close out this issue in the near future. Thanks in advance!
