### ISSUE TITLE
The stenciljs.com website is laggy

### ISSUE THREAD

**Issue by trosel** [ionic-team/stencil#2035]
https://stenciljs.com/

Scrolling is laggy. And when I click and drag to highlight or copy text, it lags really badly. 

Is this how all stencil websites behave or is there some kind of scroll hijacking that is unique to stenciljs.com that is causing this?

I'm on a chromium browser if that makes a difference.

**Comment by adamdbradley** [comment]
Stencil site listens for scroll events for the left and right menu's, this isn't for all sites built by stencil. We'll take a look, thanks
