### ISSUE TITLE
package-lock not in sync with new release

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#204]
Ref: #195

![capture191](https://user-images.githubusercontent.com/140737/31159752-22a6410c-a880-11e7-858a-7bc98a629036.png)

![capture190](https://user-images.githubusercontent.com/140737/31159770-438a4f62-a880-11e7-90a5-7fedf86f4941.png)

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Comment by adamdbradley** [comment]
Thanks for the report. This was fixed in the `0.0.6-10` release, thx
