### ISSUE TITLE
web component load in different 

### ISSUE THREAD

**Issue by talgarusi** [ionic-team/stencil#2044]
**I'm submitting a:**

[ ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
hey. i created a web component with stencil and i am using it in my angular v8 app.
if i load it like that:
<script type="module" src="comp.esm.js"></script>
  <script nomodule src="comp.js"></script>
it works on ie11 and every other browser i tested.

but if i load it like that via service it not working on ie11
[webcomp.txt](https://github.com/ionic-team/stencil/files/3890961/webcomp.txt)
:
     
          this._loadedLibraries[url] = new ReplaySubject();
          const he = this.document.createElement('script');
          he.src = comp.js;
          debugger
          he.noModule
          he.crossOrigin = 'anonymous';
          he.onload = () => {
            this._loadedLibraries[url].next();
            this._loadedLibraries[url].complete();
          };
      
          const head = document.getElementsByTagName('head')[0];
          head.appendChild(he);
      

          /////////////
          this._loadedLibraries[url] = new ReplaySubject();
          const he2 = this.document.createElement('script');
          he2.type="module"
          he2.src =  this.host + "comp.js";
          he2.crossOrigin = 'anonymous';
          he2.onload = () => {
            this._loadedLibraries[url].next();
            this._loadedLibraries[url].complete();
          };
      
          head.appendChild(he2);

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize that it took so long for someone on the team to respond. If you're willing/able to, I'd really appreciate an updated reproduction case for the team and I to look into. If not, I completely understand. Thanks for taking the time to put this issue together, I appreciate it.
