### ISSUE TITLE
Re-render not triggered even though the State changes

### ISSUE THREAD

**Issue by leonheess** [ionic-team/stencil#2045]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If a State is changed by an onClick which bubbled up from a shadowChild re-renders are not triggered even though the State changes as expected

**Expected behavior:**
The State is changed and a re-render is triggered

**Steps to reproduce:**
1. Create a component with shadow children and a State
2. Give the Component an onClick wich changes the State (`onClick={() => this.visible= !this.visible}`)
3. Create another component which appears disappeared based on the before mentioned State (`class={this.visible ? "visible" : ""}`)
4. If you now click one of the shadow children, the click will bubble to the shadow parent and change the State but the other component will not appear until you click on the shadow parent itself

**Comment by manucorporat** [comment]
Can you share some source code?

**Comment by leonheess** [comment]
> Can you share some source code?

I will add a minified example very soon

**Comment by leonheess** [comment]
Fixed it with this: https://stackoverflow.com/questions/24078524/svg-click-events-not-firing-bubbling-when-using-use-element
