### ISSUE TITLE
Non-shadow Slot default content is being hidden

### ISSUE THREAD

**Issue by fictivecreations** [ionic-team/stencil#2054]
**Stencil version:**
```
 @stencil/core@1.8.2-1
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
I have component A that uses component B.
component A has a slot with default content.
component B has a slot with default content that is placed inside component A.

If, upon using component B, I supply content for the slot, it works fine. But if I don't put anything, the default content from component B is not being displayed in component A, and neither is component A's default content. 

**Expected behavior:**
If no slot content is supplied to component B, component B's default content should be displayed by the slot in component A.

**Related code:**
It ends up rendering to the browser like this:

```html
<slot-fb hidden>default content A</slot-fb> (component A with default content)
<slot-fb hidden>default content B</slot-fb> (component B with default content)
```

So I suspect something is going wrong in the logic of which slot should be marked with hidden, as I would expect only the first one to be hidden.

**Comment by LeeBurton** [comment]
We are having the same problem. Between 1.8.6 and 1.8.7 slots seem to have been broken. We are also seeing "hidden" attributes added to components, searched through our code and found nothing. When we downgraded to 1.8.6, it is working as it always did. These are serious problems.

**Comment by rwaskiewicz** [comment]
Hey folks, 

I'm taking a look at some of the issues that we've labeled as "slot-related". I'm unable to reproduce this with Stencil v4.8.1, but it's entirely possible I'm missing something here. If anyone still experiencing this is willing/able to create a minimal reproduction for us to take a look, it'd be much appreciated. Thanks!

**Comment by rwaskiewicz** [comment]
I'm going to close this issue out due to lack of activity. If you're experiencing this issue today, please feel free to open a new issue! Thanks!
