### ISSUE TITLE
StencilJs trying to update a removed dom node

### ISSUE THREAD

**Issue by toma-paul** [ionic-team/stencil#2055]
Hello guys,

I ran into this issue today with stencil. I have the following function which returns  JSX based on a State element which gets update.

`  listFilters = () => (this.selected.filters.map((filter : string) => <div class="nas__extension__options__filter" onClick={(event) => this.getFilters(event)}>{filter}</div>
)
  );`

This is how it gets called in the render() function:

`<div class="nas__extension__options">
                          {this.listFilters()}
                      </div>`

This works fine , and updating the state correctly updates the html on the page.

The issue that i've encountered is that : when one of the elements gets clicked, the onClick method triggers which runs the subsequent call  "event.path[0].remove();". This works fine and the node element gets removed. The issue that i ran into is that when the state is updated and the filters displayed are also update, if one of the DOM nodes has been removed that DOM element doesn't get re-rendered. 

I tried multiple options and the most obvious thing is that StencilJs when updating doesn't re-render some pre-existing cached nodes but tries to update them. This means that after removing that certain DOM node there is nothing to update and the element doesn't show.

What i've tried:

    -disabling shadowDOM(didn't work)
    - returning an array of jsx in the listFilter() function; (didn't work)
    - removing nodes by id (didn't work)

Is there anyway to force StencilJS to re-render the whole node and not try to update it?

**Comment by stanley85** [comment]
You need to render your nodes based on the state. If you want to remove nodes you need to change the state to a new one excluding the unwanted node. 
`
this.state = {...this.state, elements: this.state.elements.filter(() => {})};
`
