### ISSUE TITLE
Mobile performance concern

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#2058]
**Stencil version:**

```
 @stencil/core@1.x
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When multiple elements are added to a screen simultaneously using a documentFragment, the Stencil elements render in a rather random way. This becomes especially pronounced in lower-powered processor scenarios like a mobile device. 

After a bit of testing, I think stencil 1.x components may be rendering slower than pre-1.x components. Stencil 1.x is definitely first to _start_ rendering elements which is great, but the rather random introduction of completed elements is mildly confusing (more-so for the users). We were first alerted to this in a mobile application because all other html showed up quickly. Of all the html added, there were 200 Stencil components that showed up 'seemingly' slowly (I know part of this is due to the upgrade process when connected to the DOM), but the random rendering made it little weirder.

**Expected behavior:**

I think just more consistently? Prior to 1.x things output a bit more like one might expect. Raw web components seem to be rendered very similarly to the way pre-1.x renders them.

**Steps to reproduce:**

1. Copy the following into 2 files and open them in Chrome.
1. Change which head links are commented/uncommented in the 2nd file

I admit this example is excessive, but otherwise I would have to ask you to open developer tools and turn on CPU throttling. I used Ionic 4.5.0 since I think it was the last time Stencil non-1.x was used. The other is whatever the latest release includes. 

If you run them both, the latest version _starts_ rendering first, but the older version completes well before the latest finishes.

**Related code:**

```html
<html lang="en">
<head>
  <meta charset="UTF-8"> 
  <!-- <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
  <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script> 
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css"/> -->
  <script src="https://cdn.jsdelivr.net/npm/@ionic/core@4.5.0/dist/ionic.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core@4.5.0/css/ionic.bundle.css"/>
</head>
<body>
  <table>
    <tbody></tbody>
  </table>
  <script>
  const fragment = new DocumentFragment();
  const content = document.querySelector('tbody');
  const rowTemplate = document.createElement('tr');
  const cellTemplate = document.createElement('td');
  cellTemplate.innerHTML = `<ion-button color="primary">Primary</ion-button>`;

  function main() {
    const row = buildRow();
    for (let i = 0; i < 100; i++) {
      fragment.append(row.cloneNode(true));
    }
    // stops the process in case you wish to tag in metrics
    alert('Document fragment complete. Shall we append?'); 
    content.append(fragment);
  }
  function buildRow() {
    const row = rowTemplate.cloneNode();
    for (let i = 0; i < 100; i++) {
      row.append(buildCell());
    }
    return row;
  }
  function buildCell() {
    return cellTemplate.cloneNode(true);
  }  
  main();
</script>
</body>
</html>
```

**Other information:**

All of our testing for this issue was done in Chrome and the original issue was seen on an Android device during QA. 

As part of our testing, we created a simple, raw web component and added it to the screen with the same logic used above:
```js
const sheet = new CSSStyleSheet();
  sheet.replaceSync(`
    :host {
      display: inline-block;
      height: 24px;
      position: relative;
      vertical-align: top;
      width:24px;
    }
    svg {
      fill: currentColor;
    }
  `);
  const SVG = document.createElement('div');
  SVG.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path opacity=".87" fill="none" d="M0 0h24v24H0V0z"/><path d="M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm3.59-13L12 10.59 8.41 7 7 8.41 10.59 12 7 15.59 8.41 17 12 13.41 15.59 17 17 15.59 13.41 12 17 8.41z"/></svg>`;

  customElements.define('custom-icon', class extends HTMLElement {
    constructor() {
      super();
      const shadowRoot = this.attachShadow({ mode: 'open' });
      shadowRoot.appendChild(SVG.cloneNode(true));
      shadowRoot.adoptedStyleSheets = [sheet];
    }
  });
```
Under the same conditions it "seems" to render the same way pre-1.x did. I don't know if that helps but you never know. 

Let me know if you need any more information and thanks for the awesome library!

**Comment by cary-smith** [comment]
I have been tearing down one of our more problem components to look into issues surrounding mobile performance and noticed a few things that may be useful in the debug of this problem:

1. Shadow: true is far more performant (I assume because the DOM does not have to be re-worked to slot things
2. If the component is just native dom elements, then the render happens in an orderly fashion (i.e. elements render in the order they exist in the dom)
```jsx
render() {
    return (<span>{this.someValue}</span>);
}
```
3. If the component uses another component as part of its template, then the weird rendering behavior begins.
```jsx
render() {
    return (<span>
        {this.someValue}
        <my-other-component></my-other-component>
    </span>);
}
```

This affect can be visualized using `<ion-button>` because it has a `<ion-ripple-effect>` child element as part of its template. Something about the child component causes the parent to render out-of-order in the output.

I hope that helps!

**Comment by cary-smith** [comment]
Both from Chrome using 4x slowdown for a better look at the output:

No child component:
![no-child](https://user-images.githubusercontent.com/5806191/73397548-68993a00-42a9-11ea-966c-78ef8e582b6f.gif)

With a child component:
![child-component](https://user-images.githubusercontent.com/5806191/73397595-81095480-42a9-11ea-8df7-dffa2cb0998a.gif)

**Comment by cary-smith** [comment]
Just retested with 1.9.0-15 and its unfortunately running into the same.

**Comment by cary-smith** [comment]
This is a fairly significant and somewhat awkward hit for small, repeated components that are composed using others components as part of the template ...especially in the mobile space. Is this on the radar?

**Comment by cary-smith** [comment]
Tested with 1.9.0-22 and the slowdown still exists.

**Comment by beenotung** [comment]
My temporal workaround to get the first paint earlier is to congest the list update (or to insert items into the repeated list slower).

E.g. insert the long list of items (which will be rendered as ion-cards) into the list 3 by 3. Insert more after `componentDidRender()` and `setTimeout()` 1000~800ms.
If the interval is not long enough, e.g. shorter than 500ms, multiple inserts will be batched for a single batch of DOM repaint.

**Comment by cary-smith** [comment]
@beenotung - That is an _excellent_ suggestion. Unfortunately we build a library that other developers within our organization use so we have less control over the how-they-are-implemented-space. Not all developers are careful about how they place information on the screen. 😞 That particular pattern also has an issue with variably long lists, aggressively-scrolling users, plus it must be implemented by any team that "may" need a long list but won't know until run-time.

There is also a desire (at least on my part) to have Stencil perform with only slight overhead compared to native shadow dom in supporting browsers. I am currently looking into the `dist-custom-elements-bundle` of 1.9.0 to see if this issue is better handled there. 

Whatever the case, the slow-down and rather random render order have been noticed by our customers so we have had to implement stop-gaps and workarounds. This is not sustainable in the long run so we will keep an eye on things and make decisions accordingly. We have to be able to compose complex elements without worrying about how much it may slow down the output.

If you are interested, I created a [component starter branch](https://github.com/cary-smith/stencil-component-starter/tree/performance-check) to look into the cause as well as compare against native functionality. Be warned...it will not work in IE11. 😄

**Comment by beenotung** [comment]
@cary-smith Did I get it correctly, that your approach to make it faster is to manage the DOM update on your own, instead of relaying on the stencil's internal VDOM?

**Comment by cary-smith** [comment]
Nope. It started as an exercise of Stencil vs native functionality. I added lit as a third point of view (another library with potential overhead) to see for myself.

**Comment by beenotung** [comment]
Another workaround is to implement the layout using plain html/css for critical parts, instead of using ionic components.

Below stencil (not angular) demo has 49 items on each column. The data is inserted 33ms after `connectedCallback()` is called. It shows the significant different in rendering latency.
![speed-up](https://user-images.githubusercontent.com/6007292/76674624-5fabc000-65ec-11ea-82fd-b4845bb52040.gif)


Left used: plain text with table

Middle used: flex, ion-buttons, ion-button, ion-icon, ion-avatar

Right used: ion-card, ion-card-header, ion-card-content, ion-card-footer, ion-row, ion-col, ion-item, ion-avatar, ion-buttons, ion-button, ion-icon, ion-text, ion-chip

The "ionic version" is slow because it has too many level of shadow DOM. I tried to modify the @ionic/core code base, turned most shadow component into scoped component but it doesn't help much on the performance.

**Comment by cary-smith** [comment]
@beenotung  - We are already applying workarounds like this but that makes our component creations far less useful and defeats composition concepts. I am not sure the levels of shadow dom are the problem since the native example and lit example do not exhibit the same slowdown with a nested component.

**Comment by arjunyel** [comment]
Have you tried with the --next compiler option? If so I'd recommend joining the slack and bringing up the issue in there https://github.com/ionic-team/stencil/tree/master/CHANGELOG.md

**Comment by beenotung** [comment]
@cary-smith why should it be less useful if using own implementation rather than ionic components ? You can still implement it with stencil, so the lifecycles, typed properties, events, and functional component features can still be used.

**Comment by cary-smith** [comment]
@arjunyel  - We have tried the --next compiler and it has the same problems.

@beenotung - As mentioned previously, we build a component library using Stencil that other developers use to build websites. This provides consistency, branding and common functionality across our organization. Some of these components are quite complex and may require the nesting (which is where the problem starts). It is 'less useful' if our developers cannot use the same API consistently or have to work around performance oddities by dropping back to raw HTML. The reason I posted this issue is exactly because I would like to stay within the Stencil ecosystem without requiring other developers who depend on our library to use workarounds.

**Comment by romulocintra** [comment]
cc @manucorporat is same issue i was trying to describe.

**Comment by beenotung** [comment]
@arjunyel I tried --next flag, the "ionic heavy" version magically work as fast as the "plain html/css" version!
Though it has a small bug mentioned here https://github.com/ionic-team/stencil/issues/2260#issuecomment-600490718

**Comment by beenotung** [comment]
@cary-smith are you sure you're running 1.9x when testing with the --next flag?
My trial first ran `stencil build --dev --watch --serve --next` which is indeed running the global version, not the one in the project, Then I ran with `npx stencil ...`

**Comment by beenotung** [comment]
But the speed up only happens in Firefox, not in Chrome.

**Comment by cary-smith** [comment]
@beenotung - Currently running 1.10.1. Same performance issue easily exacerbated by mobile processor speeds.

**Comment by ryanhollister** [comment]
@cary-smith I investigated some similar concerns. Can you look at my report #2294 and see if you can play with the timeout calculation and get better results. Not sure if they are related, but might be.

**Comment by cary-smith** [comment]
@ryanhollister - I unfortunately have not delved that deep into the code and was more focused on the behavior. Flushing the queue is a likely suspect. 

Where is that line of code from?

**Comment by ryanhollister** [comment]
Sorry for the lack of clarity on that. The line of code is from this file:

https://github.com/ionic-team/stencil/blob/master/src/client/client-task-queue.ts#L63

I am not certain it is your issue here, but it seemed related when I was looking through the backlog of issues.

The way I've been able to test this is record a performance snapshot in chrome. You should end up with a flame chart that has lots of quick but tall flames like this:

![Screen Shot 2020-03-23 at 8 55 46 AM](https://user-images.githubusercontent.com/962404/77324069-383bae00-6ce4-11ea-8463-e64088dd0a0f.png)

If you just click on the first layer of the flame that is code, and then click the associated line number, it should take you that area of the code. 

Chrome lets you change the source code right in line and so I just observed this code execute and then started playing around with that formula calculation. I changed the 10 to 100 and it seemed to have a significant performance improvement.

If you have a publicly available version of your test up I can run some numbers and tests against it to see if changing that calculation changes the rendering performance.

**Comment by cary-smith** [comment]
I have a [component-starter beanch](https://github.com/cary-smith/stencil-component-starter/tree/performance-check) I was using for testing the behaviors.

**Comment by ryanhollister** [comment]
@cary-smith pretty substantial difference in my testing on 4x throttling, see here:

https://drive.google.com/file/d/1XMsjwost01GL8hXvIkUIzuC-5WJ7k_Ik/view?usp=sharing

**Comment by cary-smith** [comment]
@ryanhollister - Whoa! That definitely seems to be related.

**Comment by manucorporat** [comment]
Check out the pr: https://github.com/ionic-team/stencil/pull/2318

**Comment by beenotung** [comment]
@manucorporat I suspect your pr doesn't address the problem.
I've tried @stencil/core@1.12.0 from npm and github master branch, the slowness of 'ionic component' is obvious when compared with 'plain html/css component'.
I've extracted my appliation into a standalone test repo. It can run without relaying on server. Wish it can provide some insight to peers. https://github.com/beenotung/ionic-benchmark

**Comment by beenotung** [comment]
@manucorporat, how shall we test if pr: https://github.com/ionic-team/stencil/pull/2318 addressed this performance issue?

I tried the latest version of @ionic/core and @stencil/core, it's still slow.

I also tried to compile the master branch of ionic core with the master branch of stencil core but got some tsc error complaining some types reference in internal path are missing. Maybe it's problem with the new roll up config and the path mapping in tsconfig.

**Comment by beenotung** [comment]
I've added one more benchmark repo, using surplus, which directly operate on the DOM.
repo: https://github.com/beenotung/surplus-ionic-demo/tree/benchmark
demo: https://ionic-surplus-demo.surge.sh/

In the demo, the data will be loaded with 42ms delay after clicking the refresh button on the top toolbar.

The 'ionic heavy version' loads faster in this 'dom app' than the previous 'stencil vdom app' but still noticeably slower then the plain html/css version.

Taking reference from the conversation in your pr, it seems this slow down is caused by the stencil vdom actively postpone some dom writing, so as to ensure the css animation are smooth. If this is the cause, can we config the batch size something, so the stencil components will render in 'best effort manner'?

**Comment by cary-smith** [comment]
@manucorporat  - Conceptually I have to agree with @beenotung and I definitely have to agree with @ryanhollister.

Being able to change the task queue fixes the odd, out-of-order rendering issue but does little for how fast the large chunks of elements are output. Ryan already had a ticket open about the timeout mechanism and it does not feel that the fix provided solved that. 

Do we have any other options here? Some of our most-used elements are composed of several smaller ones and this can have significant side-affects in our increasingly mobile or data-dense desktop apps.

**Comment by beenotung** [comment]
Unfortunately, my temporary move is to only use ionic for the webapp skeleton, and use handmade component / css library for repeating items. This approach work fine by avoiding to use ion-card, ion-chip, ion-row, ion-col, ion-item.
Haven't found a good way to replace the `ion-buttons > ion-button > ion-icon` layout though.

I really appreciate the works done by the ionic team and the community. I've been using ionic since v1. But seeing the current version of ionic runs significantly slower than ionic 3 (although the dev UX is improved) makes me rethink about the tools at hand.
I'm not saying we should go back to the angular-mono approach. The concept behind stencil is great. It's portable and lightweight. But this issue is practically important.

**Comment by beenotung** [comment]
Can we re-open this issue? I think it's not solved.

**Comment by beenotung** [comment]
It seems the 'slowness of ionic component' comes from the implementation to archive isolation of css scope. Below screenshot shows each ion-col inject quite a large set of styles into the DOM.

![1](https://user-images.githubusercontent.com/6007292/79455993-51542800-8020-11ea-8213-a8c18756a276.png)

**Comment by manucorporat** [comment]
Hi there, some thoughts:

1. there will be always a performance difference when comparins simple html/css components that cover a single use case with complex components that simulate native ones.

2. Stencil ships with integrated lazy builds, not making all your components to be bundled in a single .js greatly improving performance in real world scenarios when the app scales to a lot more components.

3. The CSS isolation is how shadow-dom works, in Chrome stencil uses constructable stylesheets, a technlogy that reduces the performance impact of having a <style> inside each shadow-dom: https://developers.google.com/web/updates/2019/02/constructable-stylesheets

Try to use CSS apis directly for layout (flex and grid) and limit the usage of ion-grid might help.

**Comment by beenotung** [comment]
Appreciate the additional context from manucorporat.
I agree it's hard to resist the 'native looking' brought by ionic components.
Can we config the native looking at first loading time, instead of each rendering time?
E.g. If a page has 40 ion-item, it only needs to detect the platform once. Maybe design pattern like 'Singleton' can helps? Constructable stylesheets sounds helpful on the performance, can we go futher to improve also on the js side?

**Comment by danbucholtz** [comment]
Anyone still seeing this? I set the queue to `immediate` mode and I still see a similar behavior occurring. To my untrained eye, it appears that the deeper I nest components, the more prevalent the rendering choppiness is.

**Comment by cary-smith** [comment]
@danbucholtz - I updated my example to the latest, but the problem remains even when using an 'immediate' taskQueue.

**Comment by viljamis** [comment]
@danbucholtz Yes, this is still an issue I’d say.

**Comment by cary-smith** [comment]
Stall affected in 2.3.0. It unfortunately still has the 'random-render-order' occurring which is actually even more jarring. It only occurs on a fresh screen load but that might matter.
