### ISSUE TITLE
npm is lagging the release

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#206]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

Some explanation of the release cadence would be helpful in the readme to explain the difference
in versions if it is intentional.

This gives the impression that 0.0.5 is currently recommended.
![capture1125](https://user-images.githubusercontent.com/140737/31187705-8548168e-a8e7-11e7-8436-5597cd02e3ee.PNG)

**Comment by adamdbradley** [comment]
Our `latest` stable release is `0.0.5`. The `next` release is `0.0.6-11`. And when the 6-x releases pass our tests it'll become `0.0.6` which would be the `latest.

**Comment by peterennis** [comment]
Thanks!

**Comment by adamdbradley** [comment]
No thank you for keeping an eye out for any mistakes, we appreciate all your help.
