### ISSUE TITLE
componentShouldUpdate arguments are in wrong order

### ISSUE THREAD

**Issue by marksyzm** [ionic-team/stencil#2063]
**Stencil version:**

```
 @stencil/core@1.8.*
```

**I'm submitting a:**

[*] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
`propName` is the last argument used in `componentShouldUpdate`
```tsx
  componentShouldUpdate(...args) {
    const [, , propName] = args; // . this should not be necessary
    return propName !== 'myPropName';
  }
```
**Expected behavior:**

`propName` should be the first one as examples given in the slack channel:
```tsx
  componentShouldUpdate(propName) {
    return propName !== 'myPropName';
  }
```

**Steps to reproduce:**

**Other information:**

**Comment by adamdbradley** [comment]
This would introduce a breaking change. The arguments are `componentShouldUpdate(newVal, oldVal, propName)`

**Comment by marksyzm** [comment]
Bit weird, don’t you think? To put values in first that everyone would have to check against the property anyway whereas you’d just check the prop name usually? Doesn’t seem well thought out.
