### ISSUE TITLE
Test tasks not showing up in terminal

### ISSUE THREAD

**Issue by erwingeiger** [ionic-team/stencil#2065]
**Stencil version:**

```
@stencil/core@1.7.3
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running both Unit tests and E2E tests inside the terminal with 'npm run test' al my tests are running. So that's good. But al my tasks of a test are not showing up. When I have only a unit test or only a E2E test for a component I will see all my tasks but when having both unit and E2E tests not.

**Expected behavior:**

I would like to see all the tasks of a test

**Steps to reproduce:**

- Create both a component.e2e.ts and a component.spec.ts with some unit and some E2E tests.
- Run 'stencil test --spec --e2e'

**Comment by rwaskiewicz** [comment]
Hey @erwingeiger 👋 

I apologize that it took so long for someone on the team to respond to this issue.

I created a new Stencil project (`npm init stencil component test-output`). By default, we now include an e2e and spec test with the output of the CLI:
```
src
├── components
│   └── my-component
│       ├── my-component.css
│       ├── my-component.e2e.ts
│       ├── my-component.spec.ts
│       ├── my-component.tsx
│       └── readme.md
├── components.d.ts
├── index.html
├── index.ts
└── utils
    ├── utils.spec.ts
    └── utils.ts

3 directories, 10 files
```
I then installed dependencies (`npm i`) and ran the tests (`npx stencil test --spec --e2e`).  With Stencil 3.2.2, I get the following output:

![Screenshot 2023-05-01 at 10 33 59 AM](https://user-images.githubusercontent.com/1930213/235468315-589b8451-0a9e-468c-a700-9e1869e8b345.png)

I'm not sure I understand what a "task" is in this scenario. If you're willing and able, could you let me know what you were expecting to see? If not, I completely understand. Again, I apologize for the lack of response until now.

**Comment by erwingeiger** [comment]
Hello @rwaskiewicz. 

Ow that's a really old message. This is not a problem anymore. So you can close this issue.

Thank you for responding.

**Comment by rwaskiewicz** [comment]
Thank you, appreciate it!
