### ISSUE TITLE
Bug: Client-side hydration moves content out of <slot/> when Hydrate App or --prerender flag is used

### ISSUE THREAD

**Issue by viljamis** [ionic-team/stencil#2068]
**Stencil version:**
```
 @stencil/core@1.8.1
```
also tested in
```
 @stencil/core@1.9.0-1
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Using Hydrate App you’re now able to generate static HTML for your components. Thank you for the amazing work on this! There’re some issues still though which make it currently impossible to use this feature (at least for our team): 

If you try to hydrate the generated HTML on the client-side, any component that has `scoped: true` instead of `shadow: true` enabled will break. The content is basically moved outside of the original slot, thus breaking for example accessibility of the markup and CSS related as well. Same thing happens in the latest Edge and IE11 for `shadow: true` components as well (because of the current scoped fallback I guess).

**Expected behavior:**
I would expect the DOM structure to NOT change so drastically during client-side hydration that it breaks CSS styles and accessibility.

**Steps to reproduce:**
1. Create a simple Stencil.js component with `scoped: true` enabled:

```js
import { Component, h } from "@stencil/core"

@Component({
  tag: "my-test",
  scoped: true
})
export class MyTest {
  render() {
    return (
      <label>
        <slot></slot>
      </label>
    )
  }
}
```

2. Create a basic HTML page that imports your component library and the simple custom element:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="module" src="path-to-your-lib.esm.js"></script>
    <script nomodule="" src="path-to-your-lib.js"></script>
  </head>
  <body>
    <my-test>This is supposed to be inside a label</my-test>
  </body>
</html>
```

3. Build the app including `dist-hydrate-script` and render this page into string using the generated hydrate script, e.g. (simplified):

```
const results = await hydrate.renderToString(content)
return results.html
```

4. Examine the generated markup or use inspector JavaScript disabled. It’s 100% correct and accessible. If you now enable JavaScript in the browser again to do client-side hydration Stencil.js will move all content out of the slots for components that use `scoped: true`. Additionally all `<slot/>`s will also break in Edge and IE11 browsers.

**Other information:**

This is what the markup looks like for the above example JavaScript disabled. As you probably notice, the text is correctly inside a label:

<img width="507" alt="Screen Shot 2019-12-08 at 11 35 48" src="https://user-images.githubusercontent.com/671836/70387555-1295cd80-19af-11ea-82aa-bc33fd50e098.png">

Now if I enable JavaScript, this happens. The text content is moved outside of the label, thus breaking styles and accessibility:

<img width="447" alt="Screen Shot 2019-12-08 at 11 38 26" src="https://user-images.githubusercontent.com/671836/70387573-4670f300-19af-11ea-9a94-3ee61365f9cd.png">

Visually the results look like this:

<img width="275" alt="Screen Shot 2019-12-12 at 20 20 02" src="https://user-images.githubusercontent.com/671836/70738264-06966c80-1d1d-11ea-9acc-c27681cfeb21.png">

vs.

<img width="301" alt="Screen Shot 2019-12-12 at 20 20 09" src="https://user-images.githubusercontent.com/671836/70738281-0c8c4d80-1d1d-11ea-86e3-dda48d7fe840.png">

**Comment by viljamis** [comment]
I believe this is possibly related to and/or the same issue as in #2036

**Comment by viljamis** [comment]
Update: Just tested in the latest Edge and seems like there this happens for all kinds of components.  Basically all slotted content breaks during rehydration in Edge 18 and 17.

**Comment by viljamis** [comment]
Updated the title accordingly as the issue is related to <slot> usage in general, not just scoped:true.

**Comment by viljamis** [comment]
Just a quick update. This issue happens using the `--prerender` flag as well.

**Comment by viljamis** [comment]
I’ve now created a simple repro of this issue here: https://github.com/viljamis/stencil-prerendering-slot-issue. To test it you only need to:

1. `git clone git@github.com:viljamis/stencil-prerendering-slot-issue.git`
2. `cd stencil-prerendering-slot-issue`
3. `npm install`
4. `npm start`

This opens you a browser with a broken component. If you look at the results JavaScript disabled the slot content gets correct styles:

<img width="361" alt="Screen Shot 2019-12-13 at 20 41 28" src="https://user-images.githubusercontent.com/671836/70823803-707c4800-1de9-11ea-81fd-c8c48e4d4cdb.png">

Now enabling JS, and thus doing the client-side hydration, this happens. The slot contents are moved into wrong location:

<img width="353" alt="Screen Shot 2019-12-13 at 20 41 51" src="https://user-images.githubusercontent.com/671836/70823867-91449d80-1de9-11ea-8c2e-ecd65dd9031d.png">

**Comment by viljamis** [comment]
Created a pull that fixes the issue for IE11 and latest Edge versions. This leaves the scoped issue, but currently there’s a way around it. Basically you need to wrap the scoped components with slots inside additional <div> containers to fix this.

**Comment by adamdbradley** [comment]
Thanks @viljamis for putting in the time and research to figure this out. We just published 1.8.3-0 prerelease, would you be able to test it out? Thanks!

**Comment by viljamis** [comment]
@adamdbradley Awesome, will test it out now!

**Comment by viljamis** [comment]
@adamdbradley Looks like the issue is fully fixed in modern browsers! But unfortunately nothing is now fixed for IE11 or Edge. Slot contents still get thrown out of slots and the results look like this in e.g. latest Edge:

<img width="1536" alt="Screen Shot 2019-12-22 at 8 49 55" src="https://user-images.githubusercontent.com/671836/71318336-420d0580-2498-11ea-96be-4e71a1462deb.png">

compare to Chrome which works correctly using prerendering and slots:

<img width="1536" alt="Screen Shot 2019-12-22 at 8 50 05" src="https://user-images.githubusercontent.com/671836/71318344-56e99900-2498-11ea-9bf5-bcfe996e8bf5.png">

**Comment by viljamis** [comment]
@adamdbradley my previous pull prevented edge and ie11 from executing some of the code that causes this, would it be worth bringing some of that back since it was basically just one liner? Or alternatively doing something similar but in a different manner since it seemed like this would be really easy to fix for Edge and IE11 as well.

**Comment by viljamis** [comment]
@adamdbradley Actually, think I replied too early. Just tried switching our button component to use scoped:true instead of shadow:true and now getting the same problem again in the latest Chrome as well:

<img width="322" alt="Screen Shot 2019-12-22 at 14 11 42" src="https://user-images.githubusercontent.com/671836/71321636-1ce2bc00-24c5-11ea-8710-ef410836ca3b.png">

Seems like `1.8.3-0` does not unfortunately fix this problem. :-/

**Comment by viljamis** [comment]
@adamdbradley Wait, I just noticed there’s `1.8.3-1` as well. I originally tested `1.8.3-0` as you mentioned that version number, but looks like everything’s fixed on the newer prerelease. Tested on Safari, Chrome, Edge and IE11 and SSR is now fully working in every scenario I tested. 🥳
