### ISSUE TITLE
stencil cli: error output churn when no options are provided

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#207]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

![image](https://user-images.githubusercontent.com/1223799/31198533-ef18f9bc-a954-11e7-8c21-145459482215.png)

**Expected behavior:**

showing stencil cli options

**Steps to reproduce:**

```
yarn stencil
yarn stencil -h
```

**Comment by adamdbradley** [comment]
Thanks for the report, should be fixed in the next release. Thanks!
