### ISSUE TITLE
Allow pollyfill to be added to iframes

### ISSUE THREAD

**Issue by ncphillips** [ionic-team/stencil#2071]
I'm hoping to begin migrating an existing library from React to Stencil. Rather then rewrite we would like to refactor piece-by-piece until there's no React left. However a property of the current solution prevents us form doing so: we're isolating our library from the user via iframe, and any stencil 

**Stencil version:**

n/a

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The pollyfill cannot be added to iframes:

**Expected behavior:**

`applyPollyfill` should accept an optional `window` and that could be iframe could be passed

**Steps to reproduce:**

n/a

**Related code:**

I would expect `applyPolyfill` to be able to accept a `window` in much the same way that `defineCustomElements` does:

```tsx
// insert any relevant code here
export const MyFrame = ({ children }) => {
  return (
    <Frame>
      <FrameContextConsumer>
        {frameProps => {
          return (
            <StencilAdapter target={frameProps.window}>
                {children}
            </StencilAdapter>
          )
        }}
      </FrameContextConsumer>
    </Frame>
  )
}

import { applyPolyfill, defineCustomElements} from "my-stencil-app/loader"

function StencilAdapter({ target }) {
  useEffect(() => {
    applyPolyfill(target).then(() => defineCustomElements(target))
  }, [])
}
```

**Comment by chrisdmacrae** [comment]
@manucorporat this could be done if the `applyPolyfill` function was also output as an IIFE in the component bundle.

**Comment by manucorporat** [comment]
If this can be done, it will have to be done manually, stencil can not solve this problem for you out of the box.
