### ISSUE TITLE
StencilJS Custom Fonts not working

### ISSUE THREAD

**Issue by karsvaniersel** [ionic-team/stencil#2072]
**Stencil version:**

```
 @stencil/core@1.7.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Importing a custom font with the path: url(assets/fonts/FONTNAME.woff) However the Font Family does not appear. It seems like it just cannot get the path correct? I have tried a lot, ../assets, ../src/assets/ /dist/collection/assets etc, still the font is not being applied to my text.

**Expected behavior:**

The CSS using font-family: CUSTOMFONT would load and the text would have the custom font given.

**Comment by richrd** [comment]
Sorry to bring bad news but as far as I know, there's currently no way to load custom fonts at all from within a shadow DOM. If you want to hack around the issue you can inject the required css into the <head> tag on component load.

Chrome bug report https://bugs.chromium.org/p/chromium/issues/detail?id=336876

**Comment by ChrisLang** [comment]
hi, any work arounds for this

**Comment by richrd** [comment]
You can dynamically inject your CSS into the `<head>` tag as I suggested.
Something like this should work: 
```
    componentDidLoad() {
      // Add custom font to page DOM since font-face doesn't work within Shadow DOM.
      const fontCssUrl = 'https://example.com/font.css';
      let element = document.querySelector(`link[href="${fontCssUrl}"]`);

      // Only inject the element if it's not yet present
      if (!element) {
        element = document.createElement('link');
        element.setAttribute('rel', 'stylesheet');
        element.setAttribute('href', fontCssUrl);
        document.head.appendChild(element);
      }
    }
```

**Comment by pranav-js** [comment]
how to include google fonts here now? any help please? :(

**Comment by bleuscyther** [comment]
There seems to be another workaround:
https://github.com/google/material-design-icons/issues/1165#issuecomment-851128010

**Comment by ChrisMeye** [comment]
I wrote a detailed solution here. By the way this is not a StencilJS bug but for me those solutions work flawless.
https://stackoverflow.com/a/57623658/8196542

**Comment by SyedAli310** [comment]
@richrd , This workaround : https://github.com/ionic-team/stencil/issues/2072#issuecomment-588465875, also works only if `shadow` prop in the Component decorator is false.

**Comment by christian-bromann** [comment]
Thanks @ChrisMeye for this in depth solution, I will raise a PR for the Stencil docs to provide more guidance for our general audience.

**Comment by christian-bromann** [comment]
It looks like Stencil already recommends using global styles for things like:
- Theming: defining CSS variables used across the app
- Load fonts with @font-face
- App wide font-family
- CSS resets

@ChrisMeye it seems like this matches what you have outlined in _Option 1_. In what circumstances are _Option 2_ and _Option 3_ better alternatives than using global styles? Any feedback would be appreciated!
