### ISSUE TITLE
Framework Integration

### ISSUE THREAD

**Issue by mahadevmandole** [ionic-team/stencil#2075]
In stencil introduction part it is mentioned that "Since Stencil generates standards-compliant web components, they can work with many popular frameworks right out of the box" and  what here [https://stenciljs.com/docs/overview](https://stenciljs.com/docs/overview) mentioned, 

The following list contains the framework integrations that have been started. All of them are not yet completed.

Angular

React

Vue

Ember

 is confusing me, can some one clarify it for me?

**Comment by arjunyel** [comment]
Check out https://github.com/ionic-team/stencil-ds-plugins, for other frameworks many of them can use the web components Stencil outputs https://custom-elements-everywhere.com/
