### ISSUE TITLE
BUg: IE11 - Error when using CSS Variable inside the :host pseudo-selector. 

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#2076]
**Stencil version:**
```
 @stencil/core@1.8.1
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Global styles exist that use the `:host` selector and defines CSS variable key:value pairs within that selector.
IE11 is throwing a DOM Exception Error.
![image](https://user-images.githubusercontent.com/12614215/70752644-e39d9580-1ce7-11ea-8e5f-b0797f2942d4.png)

**Expected behavior:**
The CSS variables are properly polyfilled for IE11 in the global styles.
No errors are seen when CSS variables are used in the `:host:` selector in IE11.

**Steps to reproduce:**
* Clone the [Stencil-components-starter](https://github.com/ionic-team/stencil-component-starter) repo.
* Upgrade Stencil to v1.8.1
* install @stencil/sass
* update the stencil config to use the sass plugin.
* Either add a global stylesheet linked to index.html or a style block to the index.html page, and add a `:host` selector that contains a css variable.

**Related code:**

```scss
:host {
  --css-var: #000000;
}
```

**Other information:**
Note: This is only happening in the global styles. The component-specific CSS is being parsed or transpiled properly.
Note: using `@stencil/sass` not plain CSS
Note: IE11 doesn't support, but ignores without errors the above syntax on its own. It's only when introducing the built component javascript file that this error begins to appear.

**Comment by kensodemann** [comment]
> Note: using @stencil/sass not plain CSS

This only happens when using SASS and not when using plain CSS?

**Comment by pr3tori4n** [comment]
I'm not sure. Our project is using sass and that may play a part but it could also happen with vanilla CSS.

**Comment by kensodemann** [comment]
OK, thx for the clarification.

**Comment by adamdbradley** [comment]
Are you using the `globalStyle` config in the stencil config? https://stenciljs.com/docs/config#globalstyle

I'm not able to replicate this error. I did however fix a bug when ie11 is used but the es5 flag isn't during development (https://github.com/ionic-team/stencil/commit/df669c8d434e1c0fd75f037efb842b9e1d7015f7) which might be the error you posted. 

As for using `:host`, you cannot use it in just a `<style>` tag within index, it must be within a component file, and any sass must be in a globalStyle css file so that stencil can compile it.

**Comment by pr3tori4n** [comment]
> Are you using the globalStyle config in the stencil config?

Yes. `globalStyle: "src/assets/styles/includes.scss",`. This is where the `:host` selector resides.

> As for using :host, you cannot use it in just a <style> tag within index, it must be within a component file

Ok we'll ignore the inline style tag use case as that's not realistic. But we are still seeing the error when using `:host` selector in the global styles. Is your comment saying that you can't use the `:host` selector inline or that it can ONLY be used within the linked component .scss files, such as `@Component({ styleUrl: "./styles.scss" })`

> I'm not able to replicate this error. 

Which method are you using to reproduce, a freshly cloned starter project?

**Comment by adamdbradley** [comment]
Ok I see the style not applying and was able to fix that. Hopefully that also fixes the runtime error you were receiving, I wasn't able to replicate that.

**Comment by driskull** [comment]
Thanks @adamdbradley. We'll give it a shot when the next release is out. 👍

**Comment by driskull** [comment]
Hey @adamdbradley , Happy new year!

I am still able to reproduce the issue. I narrowed it down a bit though. It seems to only be a problem when defining a css variable in a `:host{}` global style. For example:

// global `app.css`
```
/* comment this block and works in IE11*/
:host {
  --css-var-red: red;
}
```

// component.css
```
:host {
  display: block;
  color: var(--css-var-red);
}
```

Using the Sass plugin is irrelevant. Its reproducible without Sass

I've created a modification to the starter component to show the issue.

Here is the component: https://github.com/driskull/stencil-component-starter/tree/ie11-test

Changes: https://github.com/ionic-team/stencil-component-starter/compare/master...driskull:ie11-test?expand=1

With that, you can see the runtime error in IE11. If you uncomment defining the CSS var in host in a global style, the error goes away.

**Comment by ericclemmons** [comment]
It's not just a global theme: when using component CSS:

```scss
:host {
  --header-color: var(--amplify-secondary-color);
  --header-size: var(--amplify-text-md);
  --footer-color: var(--amplify-grey);
  --footer-size: var(--amplify-text-sm);
  --font-family: var(--amplify-font-family);
}
```

**Converted to `@Component({ shadow: true })` fixed it for IE11**.

**Comment by rwaskiewicz** [comment]
Hey folks,

I apologize for the silence on this issue. Starting with Stencil v4, we are no longer supporting IE 11. As a result, I'm going to close out this issue. Once again, I apologize for the lack of engagement here in recent years and leaving this in limbo for so long
