### ISSUE TITLE
stencil-build error: when building components output doesn't provide files that are mentioned within docs

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#208]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

according to [docs](https://stenciljs.com/docs/distribution#distribution-config) when building components for npm publishing `stencil build` should provide

```
 "main": "dist/collection/index.js",
  "types": "dist/collection/index.d.ts",
  "collection": "dist/collection/collection-manifest.json",
```

- index.d.ts - doesn't exists
- index.js is empty file

![image](https://user-images.githubusercontent.com/1223799/31203283-ae520966-a966-11e7-9cad-95eb11edc3c5.png)

**Expected behavior:**

either update docs or this is a bug within stencil compiler

**Steps to reproduce:**

`stencil build`

**Related code:**

stencil.config.js
```
exports.config = {
  namespace: 'myname',
  generateDistribution: true,
  bundles: [
    { components: ['my-name'] }
  ]
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}
```

**Comment by jgw96** [comment]
Hey @Hotell , so yeah this is currently an issue of the starter and docs being slightly out of date with the latest @next release of @stencil/core. Im working on getting the setup correct in the starters now. Since this is not actually an issue with the compiler I am going to move this issue to the component-starter for now. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil-component-starter#20

**Comment by Hotell** [comment]
fair enough, thx :)
