### ISSUE TITLE
Performance profile API in Safari 10.0 iOS dont have methods 'mark', 'measure' and 'getEntriesByName'

### ISSUE THREAD

**Issue by dutscher** [ionic-team/stencil#2080]
**Stencil version:**
```
 @stencil/core@1.7.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Your Browser support says Safari 10.1+ https://stenciljs.com/docs/browser-support.
When we look onto the Mac Safari 10 https://en.wikipedia.org/wiki/Safari_version_history#Safari_10, we can see in 10.1 is new "New web technology additions and improvements".
BUT!
We talk about iOS. https://en.wikipedia.org/wiki/Safari_version_history#Safari_10_2
It is a 10.0 minor. 

I found, that in 1.7.0 the profiling was add or optimized:

**runtime:** add performance profiling ([f5817a0](https://github.com/ionic-team/stencil/commit/f5817a068610f90c2a4bed42732b68cef4cff143))

The API on iOS 10.0 for profiling exists, but dont has the methods `mark`, `measure` and `getEntriesByName`. 
![image](https://user-images.githubusercontent.com/14682/71000738-1545a080-20dc-11ea-8261-98716be22de7.png)
A workarround that all webcomponents are hydrating is to use `stencil build --no-profile`, which is nowhere documented.

Why is `BUILD.profile` default `true` and not `false`?
Is there a documentation?

**Expected behavior:**
iOS 10 works out of the box as the Browser Support says

**Steps to reproduce:**
See other issues:
https://github.com/ionic-team/stencil/issues/1900
https://github.com/ionic-team/stencil/issues/1963
https://github.com/ionic-team/stencil/issues/1403

**Related code:**
https://github.com/ionic-team/stencil/blob/master/src/runtime/profile.ts#L9
https://github.com/ionic-team/stencil/blob/master/src/runtime/profile.ts#L15
https://github.com/ionic-team/stencil/blob/master/src/runtime/profile.ts#L27

**Other information:**
Here is a Pullrequest https://github.com/ionic-team/stencil/pull/2081

cheers

**Comment by manucorporat** [comment]
Fixed by #2081! Thanks a lot for the PR!!
