### ISSUE TITLE
single file export

### ISSUE THREAD

**Issue by LeoDecking** [ionic-team/stencil#2084]
**Stencil version:**

```
 @stencil/core@1.8.1
```

**I'm submitting a:**

[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When you build a project, stencil generates a lot of files.

**Expected behavior:**

I've a stencil project [here](https://play.google.com/store/apps/details?id=de.schoolyourself.app) which is publishes as PWA and for mobile via Capacitor.
The users can install plugins, which help organizing their school day, i.e. timetable, substitution plan, orchestra-schedule.
Each of this plugins is downloaded from aa sql-database and then injected in the 'href' property of an iframe.
At the moment, the plugins are .html-files with embedded javascript, but I want to use the benefits of stencil.

Is it possible to bundle a stencil project into a single .html/.js file?

**Comment by yisar** [comment]
I have the same question and look forward to the answer.

**Comment by arjunyel** [comment]
On the roadmap https://stenciljs.com/blog/stencil-roadmap-fall-2019 , for experimental usage try `type: 'experimental-dist-module'` https://github.com/webcomponents/custom-elements-everywhere/blob/546fa1079485d5d31a5ddc0e15c8b3dd22017068/libraries/stencil/stencil.config.ts#L7

**Comment by Gbuomprisco** [comment]
I've solved this by adding Webpack on top and bundling the esm folder. Not ideal, but yeah.

In case the Stencil team is interested to know my use-case for having this feature, I simply want to create a runtime for widgets on a user's page.

Also tried the experimental output but it doesn't seem to work yet.
