### ISSUE TITLE
Framework best practice when waiting for web component to finish loading

### ISSUE THREAD

**Issue by robaxelsen** [ionic-team/stencil#2086]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

We (me + @rp6 and @andrew9994) are using web components with a Vue.js, but we don't have any clean way to inter-op framework life-cycles with stencil life-cycles.

If we use the web component in a Vue.js component, and try to invoke a web component method in mounted() life-cycle hook, it's undefined and throws an error.

If we however put it in a setTimeout() with 0ms, it works as expected.

If we use customElements.whenDefined(), it works as expected.

Using Vue.nextTick() does not work.

We can also solve this by emitting a 'loaded' event from inside the web component from within componentDidLoad(), but would like to avoid this if we can.

**Expected behavior:**

Be able to rely on mounted() hook to fire only when all web components are loaded.

**Steps to reproduce:**

**Related code:**

```ts
<template>
  <my-input
    ref="input"
    label="Telephone"
    :validation.prop="validation"
    required="true"
  />
</template>

<script lang="ts">
import Vue from "vue";
export default Vue.extend({
  data: () => {
    return {
      validation: {
        regex: '^[0-9]+$',
        errorMessage: 'Only numbers',
      },
    };
  },
  mounted: function() {
    const input: any = this.$refs.input;
    const validate = () => {
      input.validate();
    };

    // throws error
    try {
      console.log('on mounted:', input.validate);
      validate();
    } catch(err) {
      console.error('Error:', err);
    }

    // delayed by 0ms -> works
    try {
      window.setTimeout(() => {
        console.log('0ms later:', input.validate);
        validate();
      }, 0)
    } catch(err) {
     console.error('Error:', err);
    }

    // using customElements.whenDefined() -> works
    try {
      console.log('with whenDefined:', input.validate);
      customElements.whenDefined('my-input').then(() => {
        validate();
      })
    } catch(err) {
      console.error('Error:', err);
    }

  }
});

</script>

```

**Other information:**

We would love for this to be implemented or supported, and assume a Vue.js binding would be the only possible way of doing this.

If there already is a solution for this, that would be awesome, but we haven't been able to find it in Slack room, docs or here in issues.

Regardless of whether or not this is implemented, it would be helpful to improve the docs to include best practice info for this.

Any and all help appreciated :heart: :pray:

**Comment by simonhaenisch** [comment]
You can make `mounted` an async function and then do something like

```js
{
  mounted: async function () {
    await customElements.whenDefined('my-input');

    // now everything should work ...
  }
}
```

But i'm not aware of the implications of an async `mounted` callback.

**Comment by christian-bromann** [comment]
@simonhaenisch provides the answer 🎉  Thanks so much!
