### ISSUE TITLE
Prerender: ReferenceError: NodeList is not defined

### ISSUE THREAD

**Issue by tricki** [ionic-team/stencil#2087]
**Stencil version:**

```
 @stencil/core@1.8.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Using `NodeList` fails on prerender with the error `ReferenceError: NodeList is not defined`. Builds without prerendering work fine.

**Expected behavior:**
No error when using `NodeList`.

**Steps to reproduce:**

1. Create a new Stencil project with `npm init stencil` and choose the `app` starter.
2. Add the following code to app-root.tsx: `console.log(NodeList);`
3. Run `npm run build --prerender`

**Other information:**

I encounter the error in the [`a11y-dialog`](https://github.com/edenspiekermann/a11y-dialog/) package which tries to access [`NodeList.prototype.isPrototypeOf`](https://github.com/edenspiekermann/a11y-dialog/blob/a892696719969d28605b880287e802eeca507c20/a11y-dialog.js#L354).

Output:

```
> stencil-nodelist-test@0.0.1 build \stencil-nodelist-test
> stencil build

[21:07.3]  @stencil/core v1.8.1 
[21:08.5]  build, app, prod mode, started ...
[21:08.6]  transpile started ...
[21:10.1]  transpile finished in 1.55 s
[21:10.1]  type checking started ...
[21:10.1]  copy started ...
[21:10.1]  generate styles started ...
[21:10.1]  generate hydrate app started ...
[21:10.1]  bundling components started ...
[21:10.4]  copy finished (3 files) in 261 ms
[21:10.6]  generate styles finished in 449 ms
[21:12.0]  generate hydrate app finished in 1.85 s
[21:13.4]  type checking finished in 3.29 s
[21:13.8]  bundling components finished in 3.69 s
[21:13.9]  prerendering started ...
[21:14.0]  prerendering failed in 93 ms

[ ERROR ]  Hydrate Error: /
           ReferenceError: NodeList is not defined at AppRoot.render
           (\stencil-nodelist-test\dist\hydrate\app-hydrate.js:1814:21) at updateComponent
           (\stencil-nodelist-test\dist\hydrate\app-hydrate.js:955:81) at update
           (\stencil-nodelist-test\dist\hydrate\app-hydrate.js:925:26) at process.nextTick
           (\stencil-nodelist-test\dist\hydrate\app-hydrate.js:1724:13) at process._tickCallback
           (internal/process/next_tick.js:61:11)

[21:14.0]  build finished in 5.49 s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stencil-nodelist-test@0.0.1 build: `stencil build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stencil-nodelist-test@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by adamdbradley** [comment]
This should be fixed in 1.8.2, thanks
