### ISSUE TITLE
Component load order issue

### ISSUE THREAD

**Issue by betancourtl** [ionic-team/stencil#2089]
**Stencil version:**
```
@stencil/core@1.8.1 
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
The components do not load in the order that they appear in the DOM. Instead they load alphabetically. In this example there are 2 components

usn-ad loads first
usn-gpt loads second

<img width="1438" alt="Screen Shot 2019-12-18 at 10 11 58 PM" src="https://user-images.githubusercontent.com/7534346/71142396-4c53a900-21e5-11ea-9948-fc8e0d708987.png">

**Expected behavior:**

The components should fire the lifecycle methods starting from the elements at the top, regardless of the component name. stenciljs instead loads components alphabetically.

usn-aa (renamed so it loads first) should load first
usn-ad should load 2nd

<img width="1439" alt="Screen Shot 2019-12-18 at 10 12 43 PM" src="https://user-images.githubusercontent.com/7534346/71142334-17dfed00-21e5-11ea-96e2-bad3220197db.png">

Anyone knows how to fix this problem without having to change the component names?

**Comment by cary-smith** [comment]
Potentially related: https://github.com/ionic-team/stencil/issues/2058

**Comment by christian-bromann** [comment]
Issue #2058 has been addressed. Closing.
