### ISSUE TITLE
compiler/transpile/transformers: @Prop is not registered within attributeChangedCallback

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#209]
**Stencil version:** 
```
 @stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
`@Prop` is not registered within attributeChangedCallback when it's not explicitly annotated with Typescript type, so when component attribute is changed, no re-render nor syncing attr to property value is not happening. If we change property directly re-render occurs correctly.

![stencil-prop-bug](https://user-images.githubusercontent.com/1223799/31203966-c5340d02-a969-11e7-83de-2b08bd632b96.gif)

**Expected behavior:**

Be able to not have to explicitly set type of decorated property, and attribute reflection should still work

**Steps to reproduce:**

**Related code:**

```ts
@Component({
  tag: 'my-name',
  styleUrl: 'my-name.scss',
})
export class MyName {
  @Prop() first = ''
  @Prop() last = ''
  render() {
    return (
      <div>
        Hello, my name is {this.first} {this.last}
      </div>
    )
  }
}
```

**Comment by adamdbradley** [comment]
Great catch! And the fix is better at figuring out the Prop's type from the default value. Thanks!
