### ISSUE TITLE
Stencil docs command doesn't exit

### ISSUE THREAD

**Issue by d0whc3r** [ionic-team/stencil#2095]
**Stencil version:**

```
 @stencil/core@1.8.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When I execute `stencil docs` it generates the stencil docs of each component it doesn't finish (like watch mode)

**Expected behavior:**

When `stencil docs` is called it should generate docs and exit

**Steps to reproduce:**

Execute `stencil docs` and wait for finish

**Comment by adamdbradley** [comment]
This will be fixed in the next 1.9.0 prerelease, thanks
