### ISSUE TITLE
Relocate CanonicalLink instead of updateCanonicalLink

### ISSUE THREAD

**Issue by patrickalima98** [ionic-team/stencil#2097]
**Stencil version:**

```
 @stencil/core@1.8.3-1<version>
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I'm using the Stencil to make my Websites using RSS with AdonisJS, in my templates, I have the `canonical` HTML5 tag with address of the my website.

When I pass my HTML5 document string to `renderToString` function of the Stencil, it remove my `canonical` HTML Tag, the problem is here:
From: [src/compiler/html/canonical-link.ts](https://github.com/ionic-team/stencil/blob/master/src/compiler/html/canonical-link.ts)
```js
  if (typeof href === 'string') {
    // have a valid href to add
    if (canonicalLinkElm == null) {
      // don't have a <link> element yet, create one
      canonicalLinkElm = doc.createElement('link');
      canonicalLinkElm.setAttribute('rel', 'canonical');
      doc.head.appendChild(canonicalLinkElm);
    }

    // set the href attribute
    canonicalLinkElm.setAttribute('href', href);

  } else {
    // don't have a href
    if (canonicalLinkElm != null) {
      // but there is a canonical link in the head so let's remove it
      canonicalLinkElm.parentNode.removeChild(canonicalLinkElm);
    }
  }
```
**Expected behavior:**
Don't remove my `canonical` HTML tag with my document has the tag.

If you need a PR, I can make it, let me know :)

Regards

**Comment by patrickalima98** [comment]
Update 1: I forgot to say the problem present in other versions of Stencil, for example: 1.8.1, 1.8.2 and others.

**Comment by adamdbradley** [comment]
Yeah a PR with some unit tests would be great, then we could merge it in. Can you create a new spec file in here testing all the scenarios? https://github.com/ionic-team/stencil/tree/master/src/compiler/html/test 

Feel free to ping me on slack, thanks
