### ISSUE TITLE
Please allow variables inside decorators

### ISSUE THREAD

**Issue by Flowrome** [ionic-team/stencil#2098]
**Stencil version:**
```
 @stencil/core@<1.8.2>
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
Using the ```@Component``` decorator with external variables (like Environment) it won't accept their values due to variable literals check

**Expected behavior:**
It should be possible to change the ```@Component``` decorator properties with variable and functions that returns a variable

**Steps to reproduce:**
Use a variable inside the ```@Component``` decorator, for example a boolean that switch the shadow property (check the code below)

**Related code:**

```tsx
@Component({
  tag: 'pagename-page',
  styleUrl: Environment.no_page_shadow ? 'pagename.page.scss' : 'pagename.page.no-shadow.scss',
  shadow: !Environment.no_page_shadow,
})
```

This will give a compilation error:
```
[ ERROR ]  
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of
type string. Received type object at validateString
(internal/validators.js:112:11) at Object.dirname (path.js:1129:5)
at useCss
```

**Other information:**
Another issue that can be related to this: https://github.com/ionic-team/stencil/issues/398

**Comment by adamdbradley** [comment]
Sorry but decorators must be statically analyzable and cannot be dynamic at runtime.

**Comment by Flowrome** [comment]
hi @adamdbradley i understand what you are doing on Decorator analysis, but it should be possible at least compile with an environment variable, and if there is no listener for that property on change there shouldn't be any problem. just to specify that... however, there is the possibility to wrap your @component decorator? i can try to study a workaround.

Thank you for your quick response.

Happy new year

**Comment by Flowrome** [comment]
> hi @adamdbradley i understand what you are doing on Decorator analysis, but it should be possible at least compile with an environment variable, and if there is no listener for that property on change there shouldn't be any problem. just to specify that... however, there is the possibility to wrap your @component decorator? i can try to study a workaround.
> 
> Thank you for your quick response.
> 
> Happy new year

I'm sorry i thought that this was a limitation by Stencil compiler, it has turned out that typescript cannot reference to an instance of variable due to transpiling limitation. i think that passing a variable should be fine but typescript seems to do not allow this. 

https://stackoverflow.com/questions/34756294/how-to-pass-an-instance-variable-into-typescript-decorator-arguments
