### ISSUE TITLE
util/interfaces: make EventEmitter generic for better type safety

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#210]
**Stencil version:** 
```
 @stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

`EventEmitter` interface has turned off proper type checking -> any

```ts
export interface EventEmitter {
  emit: (data?: any) => void;
}
```

**Expected behavior:**

Better DX would be having generic type with default values if user doesn't want to provide any payload

```ts
export interface EventEmitter<T=any> {
  emit: (data?: T) => void;
}
```

even better provide an EventEmitter class so we can directly initialise the `@Event` emitter instead of using just type annotations

I can send a PR, if yo're ok with this :)

**Comment by adamdbradley** [comment]
Yeah that's a great idea! Would be happy to merge a PR, thanks!

**Comment by Hotell** [comment]
will do
