### ISSUE TITLE
Screenshot test differences should be generated inside of screenshot folder (feature)

### ISSUE THREAD

**Issue by rafael-leal-mccormack** [ionic-team/stencil#2102]
**Stencil version:**

```
 @stencil/core@1.8.3
```

**I'm submitting a:**

[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Currently, whenever your base images are added to the screenshot folder under /images, the subsequent test calls create png.js files inside of the `.stencil` that the compare.html looks for when comparing.

My screenshots are shared between my team through git. Normally,  we would gitignore the .stencil folder as those contain a lot of things unrelated to our project, but now we have to keep it with the `.png.js` files. That ends up bulking up that files and with the constant changes from multiple people, the `stencil-cache.json` is constantly out of sync and the `compare.html` doesn't show every image comparison once there are too many differences in the `stencil-cache.json` and too many `.png.js` files

**Expected behavior:**

It would be nice for the .png.js files to live inside of the screenshot folder instead of the .stencil folder. And for those `png.js` files to be completely regenerated every run so that folder does not become bloated with old cached versions which would allow the screenshots to be easily shared between teams through any content management system like Git. I wouldn't even mind if there was another folder called "comparisons" or something that held the most recently taken images (jpeg or png) for a test (not the base image), and the compare.html looked for it there rather than the `.stencil` folder. 

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
Would you be up for submitting a PR?

**Comment by rafael-leal-mccormack** [comment]
@adamdbradley i could but id probably need some help and direction on where to look

**Comment by trazek** [comment]
@adamdbradley we'd be happy to submit a PR but any assistance/information would be helpful. Wr can certainly start digging through the code however! Thanks

**Comment by adamdbradley** [comment]
Please feel free to joining the contributors channel https://stencil-worldwide.herokuapp.com/ if you have any questions. Thanks

**Comment by krumpli84** [comment]
Just out of curiosity and off-topic, how many screenshots are you generating?

**Comment by rafael-leal-mccormack** [comment]
Currently we have around 150 screenshot tests, since we are developing a component library, we will continously add more screenshot tests as we create and update new components

**Comment by trazek** [comment]
May need some help. Anyone?

**Comment by SheepFromHeaven** [comment]
Hey @trazek I am currently working on the whole screenshot system. Enhancing the screenshot app and for that reading in the reporting/connector features. I might be ab le to help @rafael-leal-mccormack ?

**Comment by SheepFromHeaven** [comment]
If I understand your issue correctly, I already added sth like this. Just to be sure. The cache is currently always generate for each screenshot run, but NOT for the current master. To fix this, I added the following line to my own local connector and called it with `results.masterBuild`:
https://github.com/ionic-team/stencil/blob/59933b76bd80cc0eb433070fe38d384b4d2f504a/src/screenshot/connector-local.ts#L33

**Comment by rafael-leal-mccormack** [comment]
@SheepFromHeaven From my what ive seen, i dont think theres any docs in stencil that explains connectors (if there is, then thats our bad we just havent found it) and how to use them. We've seen what ionic does in 
https://github.com/ionic-team/ionic-framework/blob/master/core/scripts/screenshot/dev.js 
and in
 https://github.com/ionic-team/ionic-framework/blob/1a2e5322fb7ac0dd6bd3d0705b8e32f9d3649bfc/core/scripts/screenshot/ionic.js#L6

but it seems very specific to what they do. Are there any docs or anything we should be looking at specifically for how to use that?

**Comment by SheepFromHeaven** [comment]
Hey @rafael-leal-mccormack good point! No there are no docs about connectors. I also just figured them out recently.

So: you commit the .stencil folder after running the tests locally. Does this mean you need several versions of your screenshots, or would one master to check against suffice?

I could help you put together a connector for your needs and also started writing docs.

**Comment by rafael-leal-mccormack** [comment]
@SheepFromHeaven Yea that would be appreciated. One master is fine. To be more specific about how we handle it, we only commit the `screenshot_xyz.png.js` and the `screenshot-cache.json` from the `.stencil` folder and nothing else. Without those, if we only commit the screenshot images and master.json, the compare.html file wont load any differences and only show the base image with no comparison image or recent image. 

But a LOT of those png.js files get generated. After enough different people have committed, usually a conflict occurs that causes a difference in the stencil-cache.json and we get things like this 
<img width="760" alt="Screen Shot 2020-10-20 at 7 54 15 PM" src="https://user-images.githubusercontent.com/20506958/96656659-469b8800-130e-11eb-8905-740f8c50e920.png">

After awhile the compare.html is essentially unusable and we have to delete both our `.stencil` folder and `screenshot` and rerun the screenshots to create new cached images in the `.stencil` and a new set of master.json and images.

If a connector can help with that, that would be pretty awesome.

**Comment by SheepFromHeaven** [comment]
@rafael-leal-mccormack Could you please try the following:
Create a connector file with the following content and add it to the stencil config, as shown in the code snippet:

**connector.js**
```
const { ScreenshotLocalConnector } = require('@stencil/core/screenshot');

module.exports = class ScreenshotCustomLocalConnector extends ScreenshotLocalConnector {
  async publishBuild(results) {
    const tempResults = await super.publishBuild(results);
    await this.generateJsonpDataUris(tempResults.masterBuild);
    return tempResults;
  }
};
```

**stencil.config.ts**
```
export const config: Config = {
  ...
  testing: {
    screenshotConnector: './connector.js'
  }
};
```

With this, you should not need to commit/track the .stencil folder. You can try this by just deleting it and let it run once. Everything should work fine 🙂

**Comment by trazek** [comment]
Thanks a lot!

**Comment by trazek** [comment]
Is there any documentation on what is going on in that connector file? By looking around, if we understand correctly, this connector allows us to generate JSON only for the master build rather than the current build? This will prevent different, conflicting cache files from being created? 

Thanks again for the help. We are going to try this and report back.

**Comment by SheepFromHeaven** [comment]
I'm currently writing docs on that, as @adamdbradley just told me what this thing is, and I looked into the usage of it under the hood.

To your question: publishBuild is being called after the tests ran, with the screenshot results. In the stenciljs localconnectors publishBuild, the cache (generateJsonpDataUris) is just being called for the current build,  and not for the master. So in case you are missing the master cache files, they will not be generated, because stencil assumes they are there.

I may propose this change actually to stencil itself, so it should work out of the Box.

Please keep in mind, that screenshot testing is still marked as experimental and therefore not fully tested/supported for All use cases.

Please let me know if my solution worked for you :)

**Comment by trazek** [comment]
The solution did indeed work for us. Thank you very much and thanks for the explanation. We know screenshots are "experimental" but have worked very well thus far.

Thanks again

**Comment by SheepFromHeaven** [comment]
You are welcome 👍 happy to help. I think we can close this Ticket then 🙂

**Comment by christian-bromann** [comment]
Thanks to everyone involved. I will go ahead and close the issue.
