### ISSUE TITLE
Slot inside iteration or loop

### ISSUE THREAD

**Issue by Vinoth-LearningThings** [ionic-team/stencil#2103]
**Stencil version:**

```
@stencil/core@1.8.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Slot inside a loop works for the 1st iteration but not the following ones.

**Expected behavior:**
Slot inside a loop should work for all the iterations.

**Steps to reproduce:**

Below is my stencil component.

```tsx
import { Component, h, State } from "@stencil/core";

@Component({
  tag: "list-body",
  styleUrl: "list-body.scss",
  shadow: false
})
export class Body {
  @State() data: Array<String> = ["James", "Carol"];

  render() {
    return (
      <div>
        <p>Teachers</p>
        {this.data.map(entry => {
          return (
            <div>
              <slot name="salutation"></slot>
              <span>{entry}</span>
            </div>
          );
        })}
      </div>
    );
  }
}
```
```index.html
<list-body>
    <span slot="salutation">Prof.</span>
</list-body>
```
**Expected Result:**
```
<list-body class="hydrated">
    <!---->
    <div>
        <p>Teachers</p>
        <div><span slot="salutation">Prof.</span><span>James</span></div>
        <div><span slot="salutation">Prof.</span><span>Carol</span></div>
    </div>
</list-body>
```

**Actual Result**
```
<list-body class="hydrated">
    <!---->
    <div>
        <p>Teachers</p>
        <div><span slot="salutation">Prof.</span><span>James</span></div>
        <div><span>Carol</span></div>
    </div>
</list-body>
```

I am not clear if I am doing anything illogical. I really appreciate the help. Thanks in advance!

**Comment by adamdbradley** [comment]
Is this for all browsers or just IE11 or old edge?

**Comment by juanmiguelbesada** [comment]
Does make sense use multiples slots with same name?

**Comment by xLama** [comment]
Seems related to https://github.com/ionic-team/stencil/issues/990

**Comment by cary-smith** [comment]
@Vinoth-LearningThings - I may be missing something in this scenario, but I think that may be a misused of named slots. The slot is intended as a key-value pairing under normal circumstances for dom placed inside a component (not part of its template but should go into a specific location). 

Conceptually (again I may be missing something here) if you want:
```html
<list-body class="hydrated">
    <!---->
    <div>
        <p>Teachers</p>
        <div><span slot="salutation">Prof.</span><span>James</span></div>
        <div><span slot="salutation">Prof.</span><span>Carol</span></div>
    </div>
</list-body>
```

...should not the render be:
```jsx
render() {
    return (
      <div>
        <p>Teachers</p>
        {this.data.map(entry => {
          return (
            <div>
              <span slot="salutation">
                <span>Prof.</span>
                <span>{entry}</span>
              </span>
            </div>
          );
        })}
      </div>
    );
}
```

**Comment by stanley85** [comment]
In the best case one would have the salutation for each teacher in the data. In this case using named slots to transport values is the wrong way. Have a property `@Prop() salutation: string = ""` on the list-body element `<list-body salutation="Prof." />` the listbody can add the value of  `this.salutation` to each JSX per teacher. `<span>{this.salutation}</span>`
