### ISSUE TITLE
file names change with --next compiler flag

### ISSUE THREAD

**Issue by zenwork** [ionic-team/stencil#2104]
**Stencil version:**
```
@stencil/core@1.9.0-9 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Compiling the `www` target results in changes to the generated files(absence of dash in file name) when using the `--next` comipilation flag.

from:
```
  www/build/my-app.esm.js
  www/build/my-app.js
```  
to
```
  www/build/myapp.esm.js
  www/build/myapp.js
```

**Expected behavior:**
no filename change

**Steps to reproduce:**
I upgraded my project from 1.3.3 to 1.9.0-9. Then I ran `stencil build --dev --watch --serve --next` to test the new compiler. removing the `--next` flag brings back the original file name

**Comment by adamdbradley** [comment]
Fixed in master https://github.com/ionic-team/stencil/commit/84ef0b2562f0d8776b28ae1da728e87e3884a29e

Thanks for opening the issue.
