### ISSUE TITLE
IE11 Encapsulation.

### ISSUE THREAD

**Issue by Mishurin** [ionic-team/stencil#2105]
**Stencil version:**

```
 @stencil/core@1.8.2
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
1. Emulation of web components encapsulation doesn't work properly for IE11. Global styles from a library/framework leak through component's own styles if the component has the same classes as the library/framework has. 
2. Styles defined for parent components don't propagate properly if a child component disables encapsulation (IE11)

**Expected behavior:**
Encapsulation should be controlled and work properly in IE11

**Steps to reproduce:**
Add spectre.css in index.html of your app.
Import nav.scss from bootstrap framework to a component scss file

**Related code:**

```html
// spectre.css has css rules defined for .nav that are applied for my-component
<link rel="stylesheet" href="/assets/css/spectre.css" />
```

```scss
// my-component.scss that has css rules defined for .nav
@import "../../../node_modules/bootstrap/scss/nav
```

**Other information:**
Link below is an example of the case 2. Alert is a standard bootstrap component. Cascading doesn't work.
https://github.com/Mishurin/stencil-pkg/blob/master/src/components/app-component/child-component/child-component.tsx

**Comment by manucorporat** [comment]
IE11 does not support shadow-dom, which is a web feature that can not be polyfilled 100%, it's a limitation of any shadow-dom polyfill

**Comment by Mishurin** [comment]
@manucorporat, i think it is worth then to exclude ie11 from supported browsers. Or at least limitations should be highlighted in the official documentation.
https://stenciljs.com/docs/browser-support
