### ISSUE TITLE
[BUG] - Readme doc generation with custom directory overwrites files everytime instead of updating it.

### ISSUE THREAD

**Issue by asifahmedfw** [ionic-team/stencil#2108]
**Stencil version:**

```
 @stencil/core@1.8.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

On using, the custom directory option for `docs-readme`, it always overwrites the entire file.
```
{
      type: 'docs-readme',
      dir: 'docs',
},
```

**Expected behavior:**
Any data above `<!-- Auto Generated Below -->` should be persisted.

**Steps to reproduce:**
1. Add a directory option to output targets in `stencil.config.ts` and generate readme-files by using `stencil build --docs`.
2. Add content above `<!-- Auto Generated Below -->`.
3. Run `stencil build --docs`.

**Comment by adamdbradley** [comment]
The source of the readme file should always be a sibling of the component.
