### ISSUE TITLE
Template renderers remove hydrated class

### ISSUE THREAD

**Issue by abdulmhamid** [ionic-team/stencil#2109]
**Stencil version:**

```
 @stencil/core@1.8.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When using conditional template logic on a Stencil element in an Ember application (and presumably with other template renderers), the `hydrated` class is removed, causing the element to lose its visibility.

**Expected behavior:**
Hydration state not lost on class update. 

**Steps to reproduce:**
1. In an Ember application, use a Stencil element in an `hbs` template
2. Bind the `class` property of the element to an ember property or use a conditional class
3. Update the bound property. The `hydrated` class is removed at this point.

**Related code:**

```hbs
<stencil-element type="foo" class="bar {{if baz "biz" }}"></stencil-element>
```

**Other information:**
 I would recommend surfacing hydration through a `data-` attribute instead of using something as often mutated as a class.

**Comment by abdulmhamid** [comment]
I developed my proposed solution locally but I cannot push to submit a pull request.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, at this time we've decided to not implement this feature. Instead I'd recommend always keeping the hydrated class on the element, or modifying the css of what hydrated does for your applications.

**Comment by abdulmhamid** [comment]
The issue here is that Ember's template rendering engine fully rewrites the class property when bound to something that changes in the Ember code.  We are not actively removing the `hydrated` class but are dependent on the visibility setting handled in Stencil nonetheless.  With this in its current state, our only recourse is to force the hydrated class on the elements at all times, overriding the rules set by the Stencil bootstrap and we will have elements visible before they are ready.

Do you know of any alternatives to this? If not, please reconsider the suggestion. We could also have the class and data attribute coexist.  The key here is that we need a way to know whether or not the elements are ready to be visible before manually implementing the `hydrated` class.

**Comment by d0whc3r** [comment]
maybe a parameter in config could be useful to indicate that you want to use attribute instead of a css class

**Comment by paulcpederson** [comment]
> maybe a parameter in config could be useful to indicate that you want to use attribute instead of a css class

This would be great. We've run into this issue in multiple frameworks. The component setting a class on the element is actually in direct violation of the [Custom Element Best Practices](https://developers.google.com/web/fundamentals/web-components/best-practices#do-not-self-apply-classes.)...

> Elements that need to express their state should do so using attributes. The class attribute is generally considered to be owned by the developer using your element, and writing to it yourself may inadvertently stomp on developer classes.

Allowing library authors to choose how they apply these visibility styles could be a nice opt-in way around this.

**Comment by paulcpederson** [comment]
Found out that this is possible now! 

```
  hydratedFlag: {
    selector: "attribute"
  },
```

Using the above in the stencil config will move to using attributes. ✨
