### ISSUE TITLE
provide correct type annotation for generated type definitions component.d.ts

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#211]
**Stencil version:**

```
 @stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

compiler produces generated ambient definitions for JSX namespace with turned off type checking -> **all props are `any`**.
Also those props are marked as optional which is also not correct assumption ( I guess there should be some other machinery how to say which props are optional )

for component:
```ts
@Component({})
export class MyName {
  @Prop() first: string = ''
  @Prop() last: string = ''
// ....
}
```

type definition:
```ts
namespace JSXElements {
      export interface MyNameAttributes extends HTMLAttributes {
        
          first?: any,
          last?: any
      }
  }
```

**Expected behavior:**

providing correct props types for improved type checking 

```ts
namespace JSXElements {
      export interface MyNameAttributes extends HTMLAttributes {
        
          first: string,
          last: string
      }
  }
```

**Comment by adamdbradley** [comment]
Yeah good call, this is an area where our transform needs to get smarter. The info is there, it's just not parsing it correctly. Thanks, we'll get this fixed up.
