### ISSUE TITLE
[Feature Request] - Methods to Add, Delete, Check Prop on Reference to JSX Object

### ISSUE THREAD

**Issue by aburkowsky9** [ionic-team/stencil#2111]
**Stencil version:**

```
 @stencil/core@<1.2.4>
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

There are times that references to JSX that has not yet been rendered / added to the DOM needs to be modified. It seems there are no available methods to add a prop, delete a prop, or check if a prop exists on these references to JSX items. The only available option, it seems, is to access properties on the JSX object that seem unintended for manipulation: `_$$attrs$$_` in modern browsers, `$attrs$` in IE11.

**Expected/Desired behavior:**

There would be a method to add, delete, or check if a prop exists on the JSX object.

```jsx
const cards = [ <x />, <y />, <z /> ];

cards[0].addProp('hasTabIndex', true);
```

```addProp()``` would take the new @Prop name and value as arguments.

**Related code:**
Assume we have a component with a class field of `cards` that takes in several types of JSX card components, and another method that dynamically passes a prop to the card if the slide index matches the index of the card.

```jsx
export class CurrentActivitiesCarousel {
  cards = [ <x />, <y />, <z /> ];

  @Prop() currentSlideIndex: number;
.....

  renderCardsForOneSlide(): HTMLElement[] {
    return this.cards.map((card, idx) => {
      if (idx === this.currentSlideIndex) {

       // check for which property is available, card is of JSX type
        const attrProp = card._$$attrs$$_ ? '_$$attrs$$_' : '$attrs$';
        const attrValue = card._$$attrs$$_ || card.$attrs$;
        card = {
          ...card,
          [attrProp]: {
            ...attrValue,
            hasTabIndex: true
          }
        };
      }
      return card;
    });
    }
  .....
  }
```

**Other information:**

`_$$attrs$$_`  and `$attrs$` seem to be unreliable properties and the names for this property seems to have been changed in stencil version updates.

**Comment by adamdbradley** [comment]
Thank you for opening the issue, however, this feature may not be a good fit for stencil. I'd recommend dynamically changing the JSX in the render function rather than providing a new api and runtime.
