### ISSUE TITLE
SVG attributes like stroke-dasharray

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#2114]
**Stencil version:**

```
 @stencil/core@1.9.0-9
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
In older versions (e.g. 0.15.1) of Stencil, it was no problem to use SVG attributes like `stroke-dasharray="0 30"`.

**Expected behavior:**
In newer versions (e.g. 1.9.0) it stopped working. The property strokeDasharray is always an empty string.

**Steps to reproduce:**

**Related code:**

```tsx
<svg>
  <circle stroke-dasharray="0 30" />
</svg>
```

**Comment by adamdbradley** [comment]
When you say the property is always an empty string, how are you reading that? I added to the svg karma test here and am able to see the results of the dashed attributes: https://github.com/ionic-team/stencil/commit/84b8e683b8b6bb2aaa2f541e963caa08140cf77e

How can I replicate the issue? Thanks

**Comment by kraftwer1** [comment]
See:

    componentDidLoad() {
        console.log(this.circle.style.strokeDasharray, typeof this.circle.style.strokeDasharray)
        // returns: "" string
    }

    render() {
        return (
            <svg>
                <circle ref={(el) => this.circle = el} stroke-dasharray="0 30" />
            </svg>
        );
    }
