### ISSUE TITLE
Stencil styles break in IE11 with webcomponentsjs polyfills

### ISSUE THREAD

**Issue by mkay581** [ionic-team/stencil#2117]
**Stencil version:**

```
 @stencil/core@1.8.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
Stencil styles are broken in IE11 when using the webcomponentsjs polyfills (I'm in a situation where I cannot remove the webcomponentsjs polyfills). This is how it looks in IE11

![VirtualBox_IE11 - Win7_07_01_2020_21_50_11](https://user-images.githubusercontent.com/1446916/71946848-f5fcd900-3198-11ea-8ae4-ada47adc19e3.png)

NOTE: When the webcomponentsjs polyfill is removed, the Stencil component works fine.

**Expected behavior:**
Stencil styles are applied correctly (like in Chrome)

<img width="1310" alt="Screen Shot 2020-01-07 at 9 59 59 PM" src="https://user-images.githubusercontent.com/1446916/71946910-19278880-3199-11ea-98dd-5238c811cb54.png">

**Steps to reproduce:**
I have created a test stencil repository that can be used to reproduce: https://github.com/mkay581/stencil-tests.

**Comment by adamdbradley** [comment]
Thanks for creating the issue and a repo case! Should be fixed now, thanks

**Comment by mkay581** [comment]
Wow that was fast! Thanks. Is there any idea when this will be included in any upcoming version?

**Comment by adamdbradley** [comment]
Just ship `1.8.5-0` for testing. Please let me know how it goes, thanks

**Comment by mkay581** [comment]
This works! Thanks so much!
