### ISSUE TITLE
Prerender removes `[contentId]` and breaks ion-menu

### ISSUE THREAD

**Issue by tricki** [ionic-team/stencil#2119]
**Stencil version:**

```
 @stencil/core@1.8.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Prerender removes the `ion-menu[contentId]` attribute and causes a console warning and an error:

```
WARN: [DEPRECATED][ion-menu] Using the [main] attribute is deprecated, please use the "contentId" property instead:
BEFORE:
  <ion-menu>...</ion-menu>
  <div main>...</div>

AFTER:
  <ion-menu contentId="my-content"></ion-menu>
  <div id="my-content">...</div>

ERROR: Menu: must have a "content" element to listen for drag events on.
```

**Expected behavior:**
No warnings / errors.

**Steps to reproduce:**
1. Create a new Stencil project with the `ionic-pwa` starter.
2. Add `<ion-menu contentId="main-content">`.
3. Add an `<ion-content contentId="main-content">`.
4. Run `npm run build --prerender` and launch in the browser.

**Related code:**

```tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'app-root',
})
export class AppRoot {

  render() {
    return (
      <ion-app>
        <ion-menu contentId="main-content">
          <ion-header>
            <ion-toolbar>
              <ion-title>Menu</ion-title>
            </ion-toolbar>
          </ion-header>
        </ion-menu>
        <ion-content id="main-content">
          <h1>Hello</h1>
        </ion-content>
        <ion-nav />
      </ion-app>
    );
  }
}
```

**Other information:**
The same problem exists with `<ion-split-pane>` (`split pane does not have a specified main node`).

**Workaround:**
Add an additional `content-id` attribute to `<ion-menu>` with the same value as `contentId`.

**Comment by adamdbradley** [comment]
We'll fix this in ionic by adding `reflectToAttr` to the props. But for now you can still set just the attribute `content-id`. Hope that helps, thanks
