### ISSUE TITLE
Add support to documentation system for CSS Shadow Parts

### ISSUE THREAD

**Issue by nborelli** [ionic-team/stencil#2121]
**Stencil version:**

```
 @stencil/core@1.8.4
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

With Chrome and FireFox 72 now officially support CSS Shadow Parts and Safari adding support in the technical preview, it would be nice to have a way of documenting the shadow parts for components we build.  We can document custom CSS variables, but I do not believe we can document CSS shadow parts currently.  If I am incorrect, can someone point me to documentation?

CSS Shadow Parts (see <https://drafts.csswg.org/css-shadow-parts>) are a great way to also consumes of the components more styling control and I anticipate that they will be used widely.

**Expected behavior:**

It would be nice to have a way to list the component parts that are inside the Shadow DOM and describe what they are.

Currently, we document CSS custom variables using this syntax in the CSS or SCSS file:

```scss
/**
* @prop --demo-widget-input-focused-outline: The outline for a focused element.
*/
```
And we document slots in the TSX file using a comment above the component that looks something like this

```tsx
/**
 * A simple dialog component that can display a header, footer and content.
 * @slot header The slot for the header content.
 * @slot footer The slot for the footer content.
 */
```
I propose that we also add support for documenting parts in the TSX file:

```tsx
/**
 * A simple dialog component that can display a header, footer and content.
 * @slot header The slot for the header content.
 * @slot footer The slot for the footer content.
 * @part close-button The close button displayed in the top right corner of the dialog.
 */
```

**Steps to reproduce:**

N/A

**Related code:**

See Expected Behavior

**Comment by adamdbradley** [comment]
Closed with #2122
