### ISSUE TITLE
Dist build does not minify JS neither CSS

### ISSUE THREAD

**Issue by danieldias51** [ionic-team/stencil#2126]
**Stencil version:**
```
 @stencil/core@1.8.4
```

**I'm submitting a:**
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When running `stencil build` or even `stencil build --prod`, it generates the dist folder, but none of the files, neither css or js are minified. 

On the stencil.config.ts file, I've also added the options   `minifyJs: true` and `minifyCss: true` to force it, but the output is still not minified.

**Expected behavior:**
The dist folder should be minified

**Steps to reproduce:**
Create a new empty project and run `stencil build`

**Comment by adamdbradley** [comment]
Which files are not being minified?

**Comment by danieldias51** [comment]
All the files inside the `dist` folder.

**Comment by danieldias51** [comment]
@adamdbradley 
Seems there's no issue at all, after your comment I went to check the other folder `www\build` and realised that one is minified. 

Seems I was relying on the wrong folder. I think this ticket can be closed

**Comment by jackchoumine** [comment]
> Which files are not being minified?

I hava the same problem.

my stencil.config:

```js
export const config: Config = {
  namespace: 'jack-ui',
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'dist-custom-elements',
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
  ],
};
```

npm scripts:
```bash
 "build": "stencil build --docs --prod",
```
![微信截图_20221018111403](https://user-images.githubusercontent.com/21340150/196327300-ec0f970b-5daa-4364-9f9f-9e749daa1ff8.png)

code in dist and loader dont minifly.

**Comment by mayerraphael** [comment]
Same here, code inside dist is not minifed. 

Running the Runtime (dist/esm/index-*.js) through some online minifier reduces the file size from 57kb to 13kb.
