### ISSUE TITLE
Pre-rendering doesn't work using stencil-redux in Stencil 1.9.X

### ISSUE THREAD

**Issue by corysmc** [ionic-team/stencil#2127]
Pre-rendering works on `@stencil/core@1.8.5` but not on `@stencil/core@1.9.0-11`

`ReferenceError: Context is not defined at hydrateAppClosure`

Does not show up on @stencil/core@latest
Repro repo: https://github.com/corysmc/ionic-pwa-stencil-redux/tree/stencil-1.9.x

Steps to reproduce:
1. clone `https://github.com/corysmc/ionic-pwa-stencil-redux/tree/stencil-1.9.x`
2. `npm run build.prerender`
3. observe error
4. `npm i @stencil/core@latest`
5. `npm run build.prerender`
6. No issue

**Comment by adamdbradley** [comment]
Closed by https://github.com/ionic-team/stencil/commit/d20f6edae3af4dfa13f88cc3b04bdc18f9ec617f
