### ISSUE TITLE
Styles not applied to child components in ES5 mode

### ISSUE THREAD

**Issue by jevenson** [ionic-team/stencil#2131]
**Stencil version:**

```
 @stencil/core@1.8.5
```

**I'm submitting a:**

[?] bug report
[?] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When using stenciljs in a modern web environment, a child component that is not a Shadow DOM Component can be styled by the parent component's styles.

When using stenciljs in the es5 environment (IE11 and Edge), a child component that is not a Shadow DOM Component **cannot** be styled by the parent component's styles.

In ES5 mode, styles are transformed to scope them since Shadow DOM is not supported in IE11 or Edge.

`h1 { color: red; }` is transformed into `h1.sc-my-parent-component { color: red; }`

`my-child-component > h1` is transformed into `my-child-component.sc-my-parent-component > h1.sc-my-parent-component`

**Expected behavior:**
I would expect the ability to style child components from a parent component, even in ES5 mode.

**Steps to reproduce:**
1. Clone the repository below
1. Run `npm run start` which will start in ES5 mode
1. Observe the text in Firefox or Chrome is green (styled by parent)
1. Observe the text in IE11 or Edge is black (un-styled by parent)

**Related code:**
https://github.com/jevenson/stenciljs-es5-bug-report

Parent Component
https://github.com/jevenson/stenciljs-es5-bug-report/blob/master/src/components/parent-component/parent-component.tsx#L1-L13

Parent Component Styles
https://github.com/jevenson/stenciljs-es5-bug-report/blob/master/src/components/parent-component/parent-component.css#L1-L11

Child Component
https://github.com/jevenson/stenciljs-es5-bug-report/blob/master/src/components/child-component/child-component.tsx#L1-L13

**Other information:**
I did have a discussion about this in the Slack Group
https://stencil-worldwide.slack.com/archives/C79EANFL7/p1578928433141900

**Comment by jevenson** [comment]
This is an issue for me because I am trying to use a component from npm and style it. Their component is

**Comment by jevenson** [comment]
^ Sorry, mistakenly closed this

**Comment by adamdbradley** [comment]
Thank you for opening the issue. However, the scoping is following how shadow dom would work. Since it is still not actually shadow dom, you should be able to select and style the elements in your scenario. If more requests are made we'll reevaluate then. Thanks.

**Comment by jevenson** [comment]
@adamdbradley I guess I'm confused then.

My child component is **not a shadowed component**, therefore I should be able to style it, correct?

As I described in the original issue, I am unable to do this in IE11 or Edge because my styles are being transformed.

```
<my-parent-component>
   <my-child-component>
        <h1>
```
Is transformed into:

```
<my-parent-component class="sc-my-parent-component-h">
   <my-child-component class="sc-my-parent-component">
        <h1>
```

If I have the following style in my parent component, it is transformed and disallows styling the child. But it still works in the non-es5 versions

`h1` selector becomes `h1.sc-my-parent-component`

**Comment by jevenson** [comment]
I've found that marking my parent component with `shadow: false` allows me to style the child.

**Comment by jflynn7** [comment]
Was there ever any other solution to this? I'm having the same problem. Whilst setting the parent component to `shadow: false` allows me to style the child component, I don't want to have to do that. I **want** my parent component to be shadowed, to prevent styling from above (amongst other things).
