### ISSUE TITLE
Spread over map iterator doesn't work in list build

### ISSUE THREAD

**Issue by rsmogura** [ionic-team/stencil#2132]
**Stencil version:**

```
 @stencil/core@1.8.2
```

**I'm submitting a:**
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: 

**Current behavior:**
When generated the *dist* build and loaded (with WebPack), the JS started throwing errors `RangeError: Invalid array length`

Error is not present with target `www` build in production or dev mode.

**Related code:**

```tsx
const keys: string[]  = [...this.map.keys()];
```

**Other information:**
Stack trace
```
RangeError: Invalid array length
    at __spreadArrays (component.entry.js:21)
    at Component.foo (component.entry.js:15099)
```
at this point `__spreadArrays` is used as pollyfill for `[...this.map.keys()]`, where `this.map` is a `Map`

**Comment by adamdbradley** [comment]
How can we replicate this? Thanks

**Comment by pszhang** [comment]
I separately encountered this bug, and it seems to be rooted in an issue with passing Iterators (at least, the ones from Map class) into the spread syntax. The ES5 polyfill doesn't seem to account for Iterators.

```
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
```

In the first loop, it sums up the length of all arguments, but Iterators don't have a length property, which turns the value of "s" into "NaN", which causes the initialization of "r" to "Array(NaN)"

I created a small sample app from the stencil scaffolding to illustrate this problem, it simply needs to be run with "npm run start --es5"

https://github.com/pszhang/stenciljs-spreadarray

Additionally, I found [Array.from()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) to be an acceptable workaround.

**Comment by pszhang** [comment]
After some more research, this seems closer to a TypeScript configuration/usage issue.

Iterators aren't part of ES5, and they aren't transpiled by default when targeting ES5 in TypeScript (which, I assume, is why the spread polyfill doesn't take them into account)

Typescript introduced the optional [downleveliteration flag](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#new---downleveliteration) which will actually test for, and transpile iterators, but it requires a global Symbol polyfill.

**Comment by rsmogura** [comment]
I think I used this flag, but it didn’t help.

**Comment by pszhang** [comment]
I'm not familiar with Stencil's build pipeline, the flag is from TypeScript and I don't think Stencil exposes it.

**Comment by pszhang** [comment]
Another workaround I found, setting "buildEs5" to false in stencil.config.ts

Then, I let my webpack/babel setup do the transpile/minification
