### ISSUE TITLE
Node polyglot causing import issues

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2136]
This issue is being submitted to provide the team with better visibility to an issue we have been working with a member of the community.

When the component library is used in the Angular application there seems to be a problem loading the `shams.js` library. When looking closely, in our form-input-helpers-88785f93.js we find this line var hasSymbolSham = require('./shams'); but there is no corresponding shams.js file inside the esm folder.

Node polyglot seems to be causing the issue, here are repos for reproduction:

https://github.com/miguelyoobic95/test-component-consumer/tree/reproduce-stencil-node-polyglot-bug

https://github.com/miguelyoobic95/test-component/tree/reproduce-stencil-node-polyglot-bug

**Comment by kensodemann** [comment]
Issue only happens with 1.9.0-x, and not with 1.8.5

**Comment by adamdbradley** [comment]
When I removed the `node-globals` plugin it's working. I may have to do with the order of the plugins.

**Comment by kensodemann** [comment]
There is a seemingly related issue with FileSaver as well: https://github.com/miguelyoobic95/test-component/tree/reproduce-stencil-next-bug
