### ISSUE TITLE
When I get warn messages on the terminal the index.html doesn't copy to www when rebuilding

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/stencil#2137]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When I get warn messages on the terminal the index.html doesn't copy to the www folder when building or rebuilding
**Expected behavior:**

For the index folder to copy to the www folder when I write 'npm start' on the console.
**Steps to reproduce:**

An example algo:
```
export function takeAttendance(opts: { date: number, student: IStudent, attendance: boolean }) {
    console.warn('TODO: Implement write records to DB method');
    const response = { success: true, error: 'Meh!' };
    return Promise.resolve(response);
}
```
I will get a squiggly line on VS Code and if I hover over the parameter it states (opts was declared but it's value was never read') on a message from the VS code IDE. On the terminal I get the same message
![Image 1-14-20 at 11 47 PM](https://user-images.githubusercontent.com/9807561/72403399-4b506180-3728-11ea-96c1-40b524b61503.jpeg)

That is an expected message as I am still developing the UI without any data. 

I expect the index.html to copy to the www folder but it doesn't. I get this window on the browser.
![Untitled](https://user-images.githubusercontent.com/9807561/72403502-9ff3dc80-3728-11ea-9907-f3952a71ac85.png)

If I get rid of the WARN messages by fixing what it says that doesn't happen and the index.html copy to the www folder as expected.

I am not sure if this is supposed to happen or not though...
**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
I just tested in the prereleases and this should be fixed now. Thanks for the report.
