### ISSUE TITLE
[1.9.0-12 --next] '$hostElement$' of undefined in LERNA context

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#2143]
**Stencil version:**
```
 @stencil/core@1.9.0-12>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The project consisting of several packages in a `lerna` environment builds but throws this error in the console in the browser:
```
index-7d8f9f58.js:2562 TypeError: Cannot read property '$hostElement$' of undefined
    at setValue (index-7d8f9f58.js:1696)
    at MyComponent.set [as first] (index-7d8f9f58.js:1774)
    at new MyComponent (my-component.entry.js:15)
    at initializeComponent (index-7d8f9f58.js:1872)
```

**Expected behavior:**
Compiles **AND** runs successfully.

Related Slack conversation:
https://stencil-worldwide.slack.com/archives/C9LTCKAN8/p1579115167152400

**Steps to reproduce:**
Repo that re-produces the case: https://github.com/bitflower/stencil-lerna/tree/stencil-next

**Comment by bitflower** [comment]
Adding info here in case someone else wants to track it down:

To set up the repo:

git clone https://github.com/bitflower/stencil-lerna.git
cd stencil-lerna
npm install
lerna bootstrap
npm run build

After that you can cd to packages/app and npm start

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil/commit/aa57ebc66b295ea606dc2e967cb4e6d3505da186

**Comment by bitflower** [comment]
Hey @adamdbradley :-)

Should we re-open or create new issue?

<img width="481" alt="Bildschirmfoto 2020-01-20 um 22 39 21" src="https://user-images.githubusercontent.com/6666636/72759374-d2dd1b00-3bd5-11ea-89b2-e6b81874c02d.png">

**Comment by bitflower** [comment]
The repo has been updated to `-14` with no success unfortunately.
