### ISSUE TITLE
Polyfill: insertBefore wrapper does not account for changing parent when shadowDOM polyfill used

### ISSUE THREAD

**Issue by abdulmhamid** [ionic-team/stencil#2146]
**Stencil version:**

```
 @stencil/core@1.8.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When executing `insertBefore` on a Stencil element in a polyfilled browsers, a `NotFoundError` occurs as the parent/child relationship between the element and reference node is changed by content in the shadowDOM in other browsers. This a primarily an issue for content slotted within a Stencil element.

The same issue occurs in the `removeChild` polyfill.

**Expected behavior:**
`insertBefore` wrapper verifies that the calling node is the parent of the reference node and adjusts accordingly.

**Steps to reproduce:**
In elements that support slotted content, mutate its children insert before.  Our case was a custom select with dynamically rendered options.  Below is an approximation of the implementation:

**Related code:**

```tsx
@Component({
    tag: 'custom-select',
    shadow: true,
    styleUrl: 'styles.css'
})
export class CustomSelect implements ComponentInterface {
 render() {
        return (
            <click-elsewhere (attrs)>
                <custom-input (attrs) />
                <div class="custom-select-dropdown custom-element-dropdown">
                    <div class="custom-select-options">
                        <slot />
                    </div>
                </div>
            </click-elsewhere>
        )
    }
}
```

```tsx
@Component({
    tag: 'custom-option',
    shadow: true,
    styleUrl: 'styles.css'
})
export class CustomOption implements ComponentInterface {
    render() {
        return (
            <div role="option" (attrs)>
                <div class="custom-option-selection">
                    {this.selected ? (<custom-icon type="checkmark" class="custom-option-selection-icon" />) : ( '')}
                </div>
                <div class="custom-option-content">
                    <slot />
                </div>
            </div>
        );
    }
}
```

```html
<custom-select>
    <div hidden class="reference-node"></div>
</custom-select>
<script>
    const newChild = document.createElement('custom-option');
    const referenceNode = document.querySelector('.reference-node');
    document.querySelector('custom-select').insertBefore(newChild, referenceNode);
</script>
```

**Other information:**

The real case occurs in a Ember app where `insertBefore` is called by glimmer during the template render.

I would recommend verifying that the calling node is equivalent to the reference node's parent in the wrapping DOM polyfill where the native `insertBefore` method is called (`J.call(this, a, c);`) Below is what we implemented in the short term before we import the Stencil code:

```ts
function remapInsertBefore(): void {
    const nativeInsertBefore = window.Node.prototype.insertBefore;
    function wrappedInsertBefore<T extends Node>(this: any, newChild: T, refChild: Node | null) : T { 
        let referenceNode = this;
        if (refChild && refChild.parentNode && referenceNode !== refChild.parentNode) {
            referenceNode = refChild.parentNode;
        }
        return nativeInsertBefore.call(referenceNode, newChild, refChild) as T;
    }

    window.Node.prototype.insertBefore = wrappedInsertBefore;
}

function remapRemoveChild(): void {
    const nativeRemoveChild = window.Node.prototype.removeChild;
    function wrappedRemoveChild<T extends Node>(this: any, oldChild: T) : T {
        let referenceNode = this;
        if (oldChild.parentNode && referenceNode !== oldChild.parentNode) {
            referenceNode = oldChild.parentNode;
        }
        return nativeRemoveChild.call(referenceNode, oldChild) as T;
    }

    window.Node.prototype.removeChild = wrappedRemoveChild;
}

if (!window.Element.prototype.attachShadow) {
    remapInsertBefore();
    remapRemoveChild();
}

```

**Comment by abdulmhamid** [comment]
Related Error in Edge
![MicrosoftTeams-image](https://user-images.githubusercontent.com/23287916/72646613-292f2d00-393c-11ea-9725-064dc2fd8d79.png)

**Comment by abdulmhamid** [comment]
Dug a bit more and saw that Stencil pulls the same polyfill used in webcomponentsjs.  We previously used the webcomponentsjs polyfill directly without this issue.  I believe the difference surfaces due the how shadowDOM content is polyfilled in Stencil vs in webcomponentsjs;  Stencil surfaces shadowDOM content as children of the element while it is only in the `outerHTML` in webcomponentsjs.

**Comment by christian-bromann** [comment]
Hi @abdulmhamid  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
