### ISSUE TITLE
Noticeable flickers due to rAF scheduling of updates

### ISSUE THREAD

**Issue by jkieboom** [ionic-team/stencil#2148]
**Stencil version:**

```
 @stencil/core@1.8.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Async component initialization and queue management using rAF are causing noticeable flickers when custom components are composed. Updates that should be dealt with within a single animation frame now instead will be spread out over multiple frames. This deteriorates the app experience.

![bug](https://user-images.githubusercontent.com/10029826/72667371-7a621e00-3a1b-11ea-8015-b3f9dd9cb876.gif)

**Expected behavior:**
I'd expect a single render update caused by prop/state changes to be completed as a whole. I managed to emulate this by either replacing the rAF with a direct call, or by disabling `initializeNextTick`.

![expected](https://user-images.githubusercontent.com/10029826/72667343-396a0980-3a1b-11ea-9b60-cf72df357a84.gif)

**Other information:**

A somewhat related problem occurs when combining multiple component libraries. I assume that each component library will have its own runtime and scheduler, in which case updates will be uncoordinated/decoupled even more.

**Comment by jordanranz** [comment]
I was able to get around the flicker by adding 
```
extras: {
  initializeNextTick: false,
},
```
to my `stencil.config.ts`

[Here](https://github.com/ionic-team/stencil/commit/cb71057b7fc4123738f83d03713a06d8f0a50d64) is the commit that adds this to the config/

[Here](https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-1124-2020-04-15) is the version notes about it.

**Comment by manucorporat** [comment]
There is also a new option called `taskQueue: 'async'` that might help
