### ISSUE TITLE
Example with Next.js 

### ISSUE THREAD

**Issue by rohmanhm** [ionic-team/stencil#2154]
Hi, you might need to link the Next.js example in here. https://github.com/zeit/next.js/tree/canary/examples/with-stencil

**Comment by grantlouisherman** [comment]
hey @adamdbradley Im happy to take this on if it's still available. Could you maybe provide more context? Is it simply just adding the link to the Readme or the stencil website?

**Comment by rwaskiewicz** [comment]
Closing, as I don't believe that this is something we're currently interested in. Thanks!
