### ISSUE TITLE
The "value" prop of <input> should be set after (...) but is not declared

### ISSUE THREAD

**Issue by max-scopp** [ionic-team/stencil#2158]
**Stencil version:**

```
@stencil/core@1.8.3
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When rendering a `<input />` element without value, a warning is logged, mentioning the importance of order. Although there are no attributes set to order them so.

**Expected behavior:**
To *NOT* show a warning, when there is *NO* value.

**Steps to reproduce:**
Make a component that just renders an input field, without defining a value.

**Related code:**

```tsx
    render() {
        return (
            <input
                ref={ref => (this.inputElement = ref)}
                type="text"
                id="filterText"
                placeholder="Full name search..."
            />
        );
    }
```

**Other information:**
The problem is caused because the index of the `value` attribute is checked against the index of the `type` attribute. Because there is no value, it's index is `-1`, therefor a misleading warning will be logged.

**Comment by xLama** [comment]
I agree
