### ISSUE TITLE
shadow-DOM slots are visible all the time in IE11 and Edge .This issue is still present in 1.8.5

### ISSUE THREAD

**Issue by learnwithratnesh** [ionic-team/stencil#2162]
This issue is still present in 1.8.5

_Originally posted by @learnwithratnesh in https://github.com/ionic-team/stencil/issues/1560#issuecomment-578009616_

**Comment by learnwithratnesh** [comment]
I'm submitting a:
[x] bug report

Current behavior:
Components which are using  slots are improperly rendered inside of Internet Explorer 11 and Edge. Slotted content is visible no matter if condition is fulfilled or not. This is not the case in other supported browsers and is probably caused by the lack of shadow DOM polyfill in Stencil, since adding it manually fixes the issue.

Expected behavior:
Conditionally rendered slots behave the same way in all of the browsers, since full IE compatibility was supposed to be baked in into Stencil.

Steps to reproduce:
1.clone: [https://github.com/learnwithratnesh/stencil-1.8.5](url)
2.npm install
3.stencil build --prod --watch --serve

**Comment by michaeljsalo** [comment]
@learnwithratnesh Was this issue ever resolved satisfactorily?  I'm still seeing the same IE slot trouble on Stencil v1.17.3.
