### ISSUE TITLE
Incorrect components.d.ts generated when types has the same name

### ISSUE THREAD

**Issue by kazamov** [ionic-team/stencil#2165]
Stencil version: 1.8.5

**I'm submitting a:**

[+] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I have two different types with the same name, used in two different components, `components.d.ts` generated incorrectly.

**Expected behavior:**
Different types but with the same names should be correctly used in different components typings.

**Related code:**

```ts
// Example:
`import {
  ValueGetter,
  ValueSetter,
} from './components/grid/grid-data-cell-checkbox/types';
import {
  ValueGetter as ValueGetter1,
  ValueSetter as ValueSetter1,
} from './components/grid/grid-data-cell-select/types';

interface CasGridDataCellCheckbox {
    /**
    * This function used to update the cell model when the state is changed
    */
    'setValueGetter': (valueGetter: ValueGetter) => Promise<void>;
    /**
    * This function used to update the cell view when the state is changed
    */
    'setValueSetter': (valueGetter: ValueSetter) => Promise<void>;
  }

interface CasGridDataCellCheckboxSelect {
    /**
    * This function used to update the cell model when the state is changed
    */
    'setValueGetter': (valueGetter: ValueGetter) => Promise<void>;
    /**
    * This function used to update the cell view when the state is changed
    */
    'setValueSetter': (valueSetter: ValueSetter) => Promise<void>;
  }`

// So as you can see, the import is correct but types from first import statement used in both components' interfaces.
```

**Other information:**

**Comment by rwaskiewicz** [comment]
👋 

I apologize it took so long for someone on the team to acknowledge this ticket. This has been resolved in https://github.com/ionic-team/stencil/pull/3337, and was a part of the [2.15.2](https://github.com/ionic-team/stencil/releases/tag/v2.15.2) release. As a result, I'm going to close this ticket. Should this issue reappear, please open a new issue using the latest version of Stencil. Thanks!
