### ISSUE TITLE
Preamble config option doesn't work

### ISSUE THREAD

**Issue by danschultz** [ionic-team/stencil#2169]
**Stencil version:**

```
 @stencil/core@1.8.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Specifying a `preamble` value in my Stencil config doesn't show up in my JS bundle.

**Expected behavior:**
The main JS bundle in `./dist` should contain the preamble value set in Stencil's config.

**Steps to reproduce:**
Set the preamble in your `stencil.config.ts` file. Something like:

```ts
export const config: Config = {
  preamble: "Test preamble"
}
```

Run `npm run build`.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**
Issue was previously reported with in https://github.com/ionic-team/stencil/issues/1723 but was closed due to inactivity.

https://stenciljs.com/docs/config#preamble

**Comment by simonhaenisch** [comment]
https://github.com/ionic-team/stencil/blob/d04fb902bfd3e0834e59677e15a5cd0710fc802c/src/utils/util.ts#L91

is still not used.

**Comment by donskov** [comment]
Hello. Any progress?

**Comment by dutscher** [comment]
why this is still ignored? 
this is also reported here last year: https://github.com/ionic-team/stencil/issues/1723

cheers

**Comment by cgpro** [comment]
It would be great if the fix will be merged!

**Comment by rwaskiewicz** [comment]
This was fixed in https://github.com/ionic-team/stencil/pull/3085, and should be available in the next release of Stencil

**Comment by rwaskiewicz** [comment]
I'm going to close this issue, as [v2.9.0 of Stencil](https://github.com/ionic-team/stencil/releases/tag/v2.9.0) resolves this issue. Please feel free to open a new issue if you feel the current functionality doesn't meet your expectations!
