### ISSUE TITLE
package.json unpkg behavior

### ISSUE THREAD

**Issue by kamilzielinskidev** [ionic-team/stencil#2172]
**Stencil version:**

```
 @stencil/core@latest
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I am not sure why it works this way, but unpkg property in package.json in out of the box solution for component (didn't check ootb for app) serves the component .js file. And this file is requested by .html, by docs by linking to the specific dist/file.js:
```
Put a script tag similar to this
<script src='https://unpkg.com/my-name@0.0.1/dist/myname.js'></script>
in the head of your index.html
```

**Expected behavior:**
In .html I would like to link without the dist/file.js
<script src='https://unpkg.com/my-name@0.0.1'></script>
as it makes more sense while using the packacke.json unpkg property

**Related code:**
This is caused by the code in ootb dist/my-component/my-component.js and its url construct.

```tsx
  var parts = scriptElm.src.split('/');
  parts.pop();
  parts.push('my-component');
  var url = parts.join('/');

  var scriptElm = doc.createElement('script');
  scriptElm.setAttribute('type', 'module');
  scriptElm.src = url + '/my-componentjs';
```

**Comment by christian-bromann** [comment]
@kamilzielinskidev thanks for raising the issue!

> <script src='https://unpkg.com/my-name@0.0.1'></script>

You can totally use this url and unpkg.com should be able to resolve it if you've define the export property in your `package.json` correctly. I will go ahead and close this issue but let me know if you have further questions.
