### ISSUE TITLE
globalStyles in dist output target

### ISSUE THREAD

**Issue by schadenn** [ionic-team/stencil#2174]
```
 @stencil/core@1.8.6
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The `globalStyles` setting in `stencil.config.ts` is only used for builds using the `www` output target.

**Expected behavior:**
The styles defined as `globalStyles` should be included in a component bundle (`dist` output target) in some way.
I think it would be good to add some script in the `defineCustomElements` function that will add a `<style>` block in the `<head>` that contains the global styles.

**Comment by dogoku** [comment]
The globalStyles are included in `dist/packagename/packagename.css` and in `www/packagename.css`.

this is documented here: https://stenciljs.com/docs/styling#global-styles
