### ISSUE TITLE
Strange Issue with @Event(): Build fails with error message : "Value of type '{ new (type: string, eventInitDict?: EventInit): Event; prototype: Event; readonly AT_TARGET:            number; readonly BUBBLING_PHASE: number; readonly CAPTURING_PHASE: number; readonly NONE: number; }' is not callable. Did you mean to include 'new'?". Changing EventEmitter's accessor (i.e: add/remove) successfully builds component.

### ISSUE THREAD

**Issue by ninishi** [ionic-team/stencil#2175]
**Stencil version:**
```
 @stencil/core@1.8.4
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Been following the method of adding event emitters using the ```@Event``` decorator to Stencil components here: https://stenciljs.com/docs/events. i.e: 
```
  @Event() btnClicked: EventEmitter;
```

Been getting some teething issues where:
- When using code as per events documentation page, IDE (Webstorm) shows the following error: ```Value of type '{ new (type: string, eventInitDict?: EventInit): Event; prototype: Event; readonly AT_TARGET: number; readonly BUBBLING_PHASE: number; readonly CAPTURING_PHASE: number; readonly NONE: number; }' is not callable. Did you mean to include 'new'?```
- If you ignore it and push on to make a code change, the build will report a failure with the exact same above message in the terminal console. When you go to the browser, the index page will report the exact same error message.
- Funnily enough, if you add/remove the ```public``` keyword depending on its presence for the event emitter variable, the build and browser error funnily disappears, but the IDE error still remains. Event emitters work perfectly.
i.e:
```
  @Event() public btnClicked: EventEmitter;
```
OR If originally ```public``` was in the code when build broke.
```
  @Event() btnClicked: EventEmitter;
```

I have attached a link to a GIF so you can see the issue in its full:
[GIF of the error in full view. Hopefully should be able to load this file but if not, then please let me know.](https://raw.githubusercontent.com/ninishi/wierd-stencil-error-event/master/wierd-stenciljs-event-issue%20(1).gif)

**Expected behavior:**
Component with event emitter provided it follows documentation should build successfully without error and when you run that component it should emit custom event successfully.
 
**Steps to reproduce:**
1. Create a Stencil project with default settings with a Stencil component like so:
```
// Example button component.
import {Component, EventEmitter, h, Prop} from '@stencil/core';
import classNames from 'classnames';

@Component({
  tag: 'sui_wc-btn',
})
export class Btn {

  @Prop() themeVariant: string = 'primary';
  @Prop() size: string = '';
  @Prop() btnOverrideClasses: string;
  @Prop() isBlock: boolean = false;
  @Prop() isOutline: boolean = false;
  @Prop() isDisabled: boolean = false;

  @Event() btnClicked: EventEmitter;

  getBtnClassNames(): string {
    const sizeVariantClass = {};
    sizeVariantClass[`btn-${this.size}`] = !!this.size;

    return classNames(
      'btn',
      `btn-${ this.themeVariant }`,
      { 'btn-block': this.isBlock },
      { 'btn-outline': this.isOutline },
      sizeVariantClass,
    );
  }

  onClick(): void {
    this.btnClicked.emit();
  }

  render() {
    const btnClasses = this.getBtnClassNames();

    // Note: From ReactJS attributes that disappear when false are done this way
    let disabled = this.isDisabled ? { 'disabled': true } : {};

    return (
      <button class={btnClasses} onClick={() => this.onClick()} {...disabled}>
        <slot />
      </button>
    );
  }
}
```
2. Have the following code in the```src/index.html``` file

```
<sui_wc-btn>
    Check out this button text!
  </sui_wc-btn>

  <script type="text/javascript">
    const button = document.querySelector('sui_wc-btn');
    button.addEventListener('btnClicked', (event) => {
      event.preventDefault();
      console.info('Button inside webcomponent has been clicked');
    });
  </script>
```
3. Start stencil. 
4. If the build fails:
   - Add or remove the ```public``` keyword depending on its presence. Save the file. i.e: 
        ```
           @Event() public btnClicked: EventEmitter;
       ```
       OR If originally ```public``` was in the code when build broke.
       ```
         @Event() btnClicked: EventEmitter;
       ```
5. Doing step 4 should make the build succeed. Go to browser, click on button and you should see the console message.
6. Do a code change e.g: in the ```render()``` method. Save file. Repeat Step 4 if build breaks again. Repeat step 5 to retest event emitter.
7. Repeat step 6 a couple of times to get a good replication.

**Other information:**

**Comment by tricki** [comment]
You forgot to import `Event` from `@stencil/core`.

**Comment by manucorporat** [comment]
Indeed, you have to import `Event`  from stencil:
```
import {Component, Event, EventEmitter, h, Prop} from '@stencil/core';
```
