### ISSUE TITLE
Receiving Dev Mode Console Logs in Prod Mode

### ISSUE THREAD

**Issue by bellindj** [ionic-team/stencil#2179]
**Stencil version:**
```
 @stencil/core@1.8.5
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I am receiving a [STENCIL-DEV-MODE] warning when using my library built in prod mode. I confirmed that I am performing a prod build (not passing any dev flags) because I have the es5 output which only outputs during prod builds.

This specific warning is surrounded by an if statement in set-value.ts which checks for a dev build. I don't understand how BUILD.isDev is returning true if I am not passing the --dev flag.

```
    if (BUILD.isDev) {
      if (hostRef.$flags$ & HOST_FLAGS.devOnRender) {
        consoleDevWarn(
          `The state/prop "${propName}" changed during rendering. This can potentially lead to infinite-loops and other bugs.`,
          '\nElement', elm,
          '\nNew value', newVal,
          '\nOld value', oldVal
        );
      } else if (hostRef.$flags$ & HOST_FLAGS.devOnDidLoad) {
        consoleDevWarn(
          `The state/prop "${propName}" changed during "componentDidLoad()", this triggers extra re-renders, try to setup on "componentWillLoad()"`,
          '\nElement', elm,
          '\nNew value', newVal,
          '\nOld value', oldVal
        );
      }
    }
```

Error: `The state/prop "${propName}" changed during rendering. This can potentially lead to infinite-loops and other bugs.`

**Expected behavior:**
I don't expect to see any dev console logs if I don't pass the --dev flag.

**Steps to reproduce:**

**Related code:**

**Other information:**

**Comment by rwaskiewicz** [comment]
Hey @bellindj 👋 

I apologize that it took so long for someone on the Stencil team to acknowledge this issue. If you're willing, able to and interested, I'd love to take a closer look if you have a minimal reproduction case for the team to test out. If not, I completely understand.

Thanks!
