### ISSUE TITLE
Setting 'hashFileNames: false' not working on all generated files

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil#218]
_From @siedentm on September 27, 2017 7:21_

It's working as intended for the bundle files, but not for the core.js and core.pf.js, which still receive hash names. 
![screenshot_20170927_090612](https://user-images.githubusercontent.com/6476810/30900677-3196a9a6-a365-11e7-89d5-7a1f1080ef36.png)

_Copied from original issue: ionic-team/stencil-component-starter#9_

**Comment by siedentm** [comment]
should be a duplicate of #190. I opened an issue here as well.

**Comment by joewoodhouse** [comment]
In the latest version (well 1.8.5) I still see lots of hashed filenames when I set `hashFilenames: false`. Lots of these appear to be my user code, but also lots are not e.g. `swipe-back-f1625998.js`, `ios.transition-47f51320.js`  etc.

Any ideas? I really need to disable hashing in my production builds.
