### ISSUE TITLE
Spellcheck attribute is a boolean, but should be an enumeration

### ISSUE THREAD

**Issue by MrAntix** [ionic-team/stencil#2181]
**Stencil version:**

```
@stencil/core v1.8.6
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
cannot get result spellcheck="false"
setting spellCheck={false} means the attribute is not rendered, which defaults it to on

**Expected behavior:**

should be declared as         ```spellCheck?: 'true' | 'false';```

**Other information:**

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

**Comment by kraftwer1** [comment]
Related #2186 (including a workaround).
