### ISSUE TITLE
spellCheck={false} doesn't render

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#2186]
**Stencil version:**

```
 @stencil/core@1.8.5
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
```tsx
<input spellCheck={false} /> 
```
...renders to:
```tsx
<input>
```

While...
```tsx
<input spellCheck="false" /> 
```
...leads to an error:
```
[ ERROR ]  TypeScript: input.tsx: Type 'string' is not assignable to type 'boolean | undefined'.
```

My current workaround that works fine...
```tsx
<input spellCheck={"false" as any as boolean} /> 
```

...renders to:
```tsx
<input spellcheck="false">
```

**Expected behavior:**
```tsx
<input spellCheck={false} /> 
```
...renders to:
```tsx
<input spellcheck="false">
```

**Comment by frerepoulet** [comment]
I'm on version `@stencil/core v1.13.0`
this:
`<input spellcheck="false" />`
always renders to:
`<input spellcheck="true" />`

**Comment by ingomc** [comment]
i have the same problem, open a new issue

**Comment by kraftwer1** [comment]
True, "false" renders to "true". Passing it as a boolean works, however:

<input spellcheck={false} />
