### ISSUE TITLE
Bug: Rendered order is incorrect if the DOM and @State arrays are both manipulated.

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#2187]
**Stencil version:**
 @stencil/core@1.9.0-14

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Circumstances:**
* a list of items are rendered from a state array.
* the order of those items are modified using native DOM methods, such as `node.insertBefore`. (practically, this happens if using a drag and drop library, like sortable.js)
* the order of data in the array is updated to reflect the new order in the DOM. For example if the original order was `1,2,3` and 1 was dragged between 2 and 3, so the DOM ordering was `2,1,3` then the array would also be updated to be `2,1,3`.

**Current behavior:**
When the state change triggers a re-render, it swaps the items back, so you end up with `1,2,3`.

**Expected behavior:**
It would be expected that even if the state did trigger a re-render, it would re-render it in the new order of `2,1,3`.

**Steps to reproduce:**
Simplest way to reproduce is to use a contrived example where you have a component with a state array and loop over that array to render nodes in the render function. Then use the javascript console to modify the order of those rendered nodes. Then call a method on the component which changes the order of that array to match the dom changes.

**Related code:**

```tsx
```
...
  tag: "foo-component",
...
@State() items: string[] = ["one", "two", "three"];
@Method() async reorder() {
    this.items = ["two", "one", "three"];
  }
render() {
    return (
      <Host>
        {this.items.map((item) => {
            return (
              <div id={item}> {item} </div>
            );
          })}
      </Host>
    );
  }
```
```js
const foo = document.querySelector("foo-component");
const two = foo.shadowRoot.querySelector("#two");
two.parentElement.insertBefore(two, two.previousElementSibling);
foo.reorder();
```

**Other information:**
It appears what's happening is when the state changes, it's comparing the items previous index with its new index, then it's modifying the rendered nodes based on their new index. This causes the first two positions in the DOM to swap. It seems to be skipping a text node comparison or something that would help it identify which node truly belongs with which index, but this is just a guess.

I've tried adding the `key` attribute to the rendered list items but that doesn't help. It also only happens the first time the elements are re-ordered. After that the re-ordering and subsequent re-rendering (in situations where the order in the `reorder` function aren't hardcoded) will work.

**Comment by manucorporat** [comment]
This is the expected behaviour, Stencil vdom implementation tracks the DOM references and tries to reduce/reuse existing DOM nodes. When you move the node manually, stencil does not have a way to know, so when it re-renders it tries to reorder it again.

You should rely on stencil reordering when the state changes, otherwise it will be reordered twice. Try to avoid the manual DOM manipulation, and if it's not possible, then create the DOM nodes manually too, and avoid using stencil as render.

In fact it's how we implemented ion-reorder-group: https://ionicframework.com/docs/api/reorder-group
