### ISSUE TITLE
bug with named slots in nested components

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2188]
**Stencil version:**

```
 @stencil/core@1.8.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
We have 2 components: one simple `content` and another simple `slotted` component.
The `content` component is **shadowed**, the `slotted` component is **not shadowed**.
Inside the `slotted` component we place the `content` component.

**Expected behavior:**
Named slots should render in no-shadow mode even if they are placed inside other components.

**Steps to reproduce:**
We have set up an open GitHub repo with a simple test project which reflects this bug:
https://github.com/porscheui/stencil-bugfix-project

**Related code:**

**Example HTML:**
```html
<my-slotted-component>
  <span slot="label">This is a named slot label and should render also in "shadow:false" mode</span>
  <p>Default slot content and there should be a label text above (which does not render!)</p>
  <span slot="content">This is a named slot content and should render also in "shadow:false" mode (and does it, because it is wrapped with a span tag)</span>
</my-slotted-component>
```

**Example slotted component:**
```javascript
render() {
  return <div class="slotted-component">
    <my-component> 
      <slot name='label'/> {/* this component will not render! */}
    </my-component>
    <slot/>
    <my-component>
      <span> {/* this wrapper is needed to render the component */}
        <slot name='content'/>
      </span>
    </my-component>
  </div>;
}
```

The 1st named slot is not rendered, the 2nd named slot is rendered because it is wrapped inside an `<span>`.

**Comment by rwaskiewicz** [comment]
👋 

I'm going to be closing this issue - as of Stencil v4.8.1, this issue is fixed when `experimentalSlotFixes: true` ([docs link)](https://stenciljs.com/docs/config-extras#experimentalslotfixes) is set in a project's Stencil config file.

If anyone is running into this issue with the flag enabled, please feel free to open a new issue! Thanks!
