### ISSUE TITLE
Problem with component generation

### ISSUE THREAD

**Issue by juny58** [ionic-team/stencil#2189]
**Stencil version:**

```
 @stencil/core@<1.8.7>
```

**I'm submitting a:**

[x ] bug report

**Current behavior:**

In the generate component section, I see there is written, use npm run generate or if "stencil globally installed, invoke stencil cli by stencil generate". How to install stencil globally? I am absolutely clueless about that statement. Where on earth did you guys give us a hint in your whole websiite about how to install it globally? All I see is "npm init stencil".

Secondly, there seems to be a bug with component generation even with npm generate. It always cuts out the file name for first hyphen separator. If I give name a-b-c-d, it will name the files as b-c-d, component class BCD and followes.

**Expected behavior:**

We should not be toiling, doing trial and errors and mend our ways to even try a thing that you boast of as a "Next Big Thing". I am stuck even in start! I was just trying to start my day with a nice experience and it did the opposite. I don't think I will believe anything again so easily from stencil team.

**Steps to reproduce:**

Use "npm generate tab-swiper". It will create a folder with swiper, filenames as swiper and class name as Swiper.

**Comment by cmddavid** [comment]
@juny58 This depends on the package manager you are using. For example with NPM you would use the `-g` flag to install a package globally, while with Yarn! you would use the `global` prefix.

**Comment by rwaskiewicz** [comment]
Hey @juny58 👋 

I apologize that getting started with Stencil was a a frustrating experience. I'll make changes to the Stencil docs to try to clarify how Stencil can be installed globally.


Regarding the second issue reported here, I have confirmed that it no longer reproduces in the latest version of Stencil (v3.1.0):
```
➜  gen-test git:(main) ✗ npm run generate a-b-c-d

> gen-test@0.0.1 generate
> stencil generate a-b-c-d

[28:31.4]  @stencil/core
[28:31.6]  v3.1.0 🍕
✔ Which additional files do you want to generate? › Stylesheet (.css), Spec Test  (.spec.tsx), E2E Test (.e2e.ts)

$ stencil generate a-b-c-d

The following files have been generated:
  - ./src/components/a-b-c-d/a-b-c-d.tsx
  - ./src/components/a-b-c-d/a-b-c-d.css
  - ./src/components/a-b-c-d/test/a-b-c-d.spec.tsx
  - ./src/components/a-b-c-d/test/a-b-c-d.e2e.ts
➜  gen-test git:(main) ✗ tree src/components/a-b-c-d
src/components/a-b-c-d
├── a-b-c-d.css
├── a-b-c-d.tsx
└── test
    ├── a-b-c-d.e2e.ts
    └── a-b-c-d.spec.tsx

1 directory, 4 files

```
