### ISSUE TITLE
docs-json output

### ISSUE THREAD

**Issue by dmartinjs** [ionic-team/stencil#2196]
**Stencil version:**

```
 @stencil/core@1.8.8
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently, the json documentation generated by Stencil don't match the effort made by https://github.com/webcomponents/custom-elements-json to have a standard for describing custom-elements (used by Storybook in [Docs addon](https://github.com/storybookjs/storybook/tree/v5.3.13/addons/docs/web-components) to generate documentation for webcomponents). 

**Expected behavior:**

Expect the output to be formatted like standardised in https://github.com/webcomponents/custom-elements-json

**Comment by manucorporat** [comment]
There is not any standard about a json describing web components, the docs-json includes way more information than other projects do, however stencil already has a output target for vscode's json:
```
    {
      type: 'docs-vscode',
      file: 'custom-elements.json'
    },
```

Add the `docs-vscode` to outputTargets in your stencil.config.ts!
