### ISSUE TITLE
missing 'platform' import in vNext npm package

### ISSUE THREAD

**Issue by gluck** [ionic-team/stencil#2200]
**Stencil version:**
```
 @stencil/core@1.9.0-17
```

**I'm submitting a:**
[X] bug report

**Current behavior:**
Compiling a standalone component generates imports to `@stencil/core/internal/client` which imports `@stencil/core/internal/runtime`, which imports `@stencil/core/internal/platform`, which doesn't exist.
Adding a rollup alias from platform->client makes (some) things work, albeit with a cyclic dependency (client->runtime->client).

**Expected behavior:**
Every import from `@stencil/core/internal/client` gets resolved.

**Steps to reproduce:**
https://unpkg.com/browse/@stencil/core@1.9.0-17/internal/runtime/index.mjs - line 4:
```
import { ... } from '@stencil/core/internal/platform';
```

**Comment by adamdbradley** [comment]
I think we'll remove the internal runtime package entirely and bundle it directly into client. Thanks for creating the issue.

**Comment by adamdbradley** [comment]
As of 1.9.0-21, the runtime is now bundled within the client/hydrate/testing builds, which allows us to remove the `@stencil/core/internal/platform` import that needed to be aliased. Thanks for opening the issue.
