### ISSUE TITLE
CSS Mods Require Browser Reload to see

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2205]
**Stencil version:**

```
 @stencil/core@1.9.0-18
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Changes to CSS are not immediately displayed in the browser. Rather, you have to refresh the browser.

**Expected behavior:**
CSS changes would be displayed via the browser without a need for refresh.

**Steps to reproduce:**

1. `git clone https://github.com/jcfranco/stencil-changes-from-partials-are-not-picked-up.git`
1. `cd stencil-changes-from-partials-are-not-picked-up`
1. `npm i`
1. `npm start`
1. change some styling in `scss/includes/_partial.scss` or `components/my-component/my-component.scss`
1. note that the project is rebuilt due to the file change
1. note that the change is _not_ reflected in the browser
1. refresh the browser, and see the change is now reflected

Next `npm i @stencil/core@latest` to get latest 1.8.x and redo the above steps starting with the `npm start`.

Now the changes _are_ reflected in the browser right away as expected.

Also tested using https://github.com/kensodemann/kws-weather-widgets, which uses CSS instead of SASS. Same issue: 1.8.x works fine, 1.9.x requires a reload of the browser to see CSS mods.

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil/commit/9a015e90268be842bf640096ac87368d65c9ab31

**Comment by kensodemann** [comment]
I am getting reports of there being a regression with this in current versions of Stencil (`1.17.3` specifically), but in testing this it is not so much a "regression" as it appears to be an issue that the fix that was released above in `1.9.1` did not make it into the `next` compiler (which at the time was hidden behind the `--next` option).

If you do the following
1. git clone https://github.com/jcfranco/stencil-changes-from-partials-are-not-picked-up.git
1. cd stencil-changes-from-partials-are-not-picked-up
1. npm i
1. npm i @stencil/core@1.9.1
1. npm start
1. modify the color specified in `src/scss/includes/_partial.scss`

Notice that the source does a rebuild and the text color changes.

1. stop the dev server
1. restart the dev server via: `npm run start -- --next`
1. modify the color specified in `src/scss/includes/_partial.scss`

The source still does a rebuild, but the color does not change. In order to see the change you must restart the server.

This is the consistent with how it works in `1.17.3` but you no longer need the `--next` flag.
