### ISSUE TITLE
TypeError: node.compareDocumentPosition is not a function

### ISSUE THREAD

**Issue by marksyzm** [ionic-team/stencil#2207]
**Stencil version:**

```
 @stencil/core@1.8.9
```

**I'm submitting a:**

- [x] bug report

**Current behavior:**
When using DOM elements in jest (probably not recommended) and that element is expected to use `node.compareDocumentPosition()` it returns the following error:
```
TypeError: node.compareDocumentPosition is not a function
```

**Expected behavior:**
`node.compareDocumentPosition` should work

**Comment by adamdbradley** [comment]
Stubbed out the method on Node, but did not implement the return value. Closing for now and can revisit if it's a highly requested feature. Thanks

**Comment by marksyzm** [comment]
That will probably do :)
