### ISSUE TITLE
Do you guys use a Custom Elements polyfill?

### ISSUE THREAD

**Issue by trusktr** [ionic-team/stencil#221]
I don't seem to see one in package.json.

**Comment by WebReflection** [comment]
https://twitter.com/kennethrohde/status/916273305400815617

**Comment by trusktr** [comment]
Oh I see, they check the file in: https://github.com/ionic-team/stencil/blob/868cfd2bc91babb2777eb9e1dd552bbb762412b6/scripts/polyfills/document-register-element.js
