### ISSUE TITLE
Allow  event names using constants

### ISSUE THREAD

**Issue by mojadev** [ionic-team/stencil#2213]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I intentionally don't create a bug as I guess this is intended behaviour or a limitation due to the static compiler. 
I'm writing a library for cross-custom-elements redux support and added stencil support now. As I use DOM Events for dispatching Actions, I need to use the EventEmitter with custom event names.
The Problem: Right now it's not possible to use constants for the event name, so consumers of my library would need to write the exact name of the DOM event, even if I don't want this to be exposed (as I would need to make it 100% stable or force everyone to rewrite their entire app when I change an implementation detail)

See: https://github.com/mojadev/customelement-store-binding/blob/master/examples/todo-stencil/src/components/todo-list/todo-list.tsx

The relevant part is:
```
  @Event({ eventName: "dispatchStoreAction", bubbles: true, composed: true })
  private dispatchAction: EventEmitter;
``` 

**Expected behavior:**
The nicest variant would be :

```
  @Event(dispatchStoreAction)
  private dispatchAction: EventEmitter;
``` 

But I could also live with

```
  @Event({ eventName: dispatchActionEventName, bubbles: true, composed: true })
  private dispatchAction: EventEmitter;
``` 

Right now both versions lead to the eventhandler not working.

**Steps to reproduce:**

* Create a component with an `@Event`
* Use a constant for the event name or configure it using a predefined object

**Related code:**
The commit showing the issue quite well is here; https://github.com/mojadev/customelement-store-binding/commit/b75c313990516abeb3a3e7a5e4ae4666be0e73b3#diff-aac10365e0ff4b06c5f8d17e04682b25

**Other information:**

I understand the static analysis makes it hard to determine the type of event - but other than the non-supported class decorators (which I understand is quite complex) I don't really see the any benefit here. Is there a reason why this decorator cannot be evaluated during runtime?

**Comment by claviska** [comment]
See also: https://github.com/ionic-team/stencil/issues/398

**Comment by rwaskiewicz** [comment]
Hey all,

I'm going to close this in favor of https://github.com/ionic-team/stencil/issues/2924. While https://github.com/ionic-team/stencil/issues/2924 appears different, these two issues stem from the same constraint within the compiler. Thanks!
