### ISSUE TITLE
Cannot acccess element inside connectedCallback()

### ISSUE THREAD

**Issue by erichstark** [ionic-team/stencil#2215]
**Stencil version:**
```
 @stencil/core@1.8.9 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
console.log prints null

**Expected behavior:**
console.log should print child element element of the web component and add class

**Related code:**
shadow is true on this component

```tsx
...
  @Element() el: HTMLElement;
  @Prop() color: string;
...

  connectedCallback() {
    console.log('color: ', this.el.shadowRoot.querySelector('.progress-bar'));
    this.el.shadowRoot.querySelector('.progress-bar').classList.add(`progress-bar--${this.color}`);
  }
```

**Comment by tanner-reits** [comment]
This doesn't appear to be an issue anymore with the latest version of Stencil.
