### ISSUE TITLE
InputHTMLAttributes type missing `directory` and `webkitdirectory`

### ISSUE THREAD

**Issue by cramshaw** [ionic-team/stencil#2218]
**Stencil version:**

```
 @stencil/core@1.8.7
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

InputHTMLAttributes type is missing `directory` and `webkitdirectory`. You can find the type declaration here.
https://github.com/ionic-team/stencil/blob/e80cfc20b564d1624feda8bb5a3e23713e1ffe44/src/declarations/stencil-public-runtime.ts#L859
This allows file inputs to select a folder, rather than just a single file.

**Expected behavior:**

InputHTMLAttributes type should allow me to set `directory` and `webkitdirectory` attributes on input.

**Steps to reproduce:**

Create a component containing an input thus:
`<input type="file" directory webkitdirectory />`

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

I believe it should just require adding to the InputHTMLAttributes type. Let me know if I can do anything else to help! Thanks!

**Comment by adamdbradley** [comment]
Updated thanks, but did not add `directory` since it's not listed by MDN: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
