### ISSUE TITLE
IE11/Edge setAttribute at runtime caseSensitive Bug

### ISSUE THREAD

**Issue by dutscher** [ionic-team/stencil#2225]
**Stencil version:**
```
 @stencil/core@1.8.5
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
IE11  & Edge has an a camelCase attribute bug. When i set an attribute at runtime and its camelcase, which should unimportant for attributes then i doesnt recognize the value.
In chrome works well as "excpected".

**Expected behavior:**
Attributes should be caseinsensitive, on init and on runtime.
We dont speak about PROPS!

**Steps to reproduce:**
```html
<!-- attributes on init will work -->
<custom-input maxlength="10" /> <!-- lowercase-->
<custom-input maxLength="10" /> <!-- camelCase -->
```
--- 
```html
<!-- attributes at runtime -->
<custom-input />
<script>
 // camelCase: wont work in ie11/edge but works in chrome
  document.querySelector('custom-input').setAttribute("maxLength", "10");
// lowercase: will work everywhere
  document.querySelector('custom-input').setAttribute("maxlength", "10");
</script>
```

**Related code:**
```tsx
@Component({
  tag: 'custom-input',
})
export class Input  {
@Prop() maxlength: number | undefined = undefined;
render() {
 <Host>
  <input maxlength={this.maxlength} />
 </Host>
}
}
```
Thanks in advance :)

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize that it took so long for a member of the team to acknowledge this ticket. With Stencil v3, we've officially deprecated support for IE 11/older versions of Edge. I've labeled this for the team to consider prior to dropping all support for IE 11. Thanks!
