### ISSUE TITLE
Prerendering failing to detect URLs in netlify

### ISSUE THREAD

**Issue by shreeshbhat** [ionic-team/stencil#2226]
**Stencil version:**
@stencil/core@1.8.10 

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**

I have an app setup using www as output.
Prerendering is failing to detect URLs in Ubuntu Xenial 16.04 Netlify build.
It is working fine when I do `npm run prerender` locally in Mac and Windows.
Not sure why the same config is failing in Netlify.

I have added sitemap.xml to make sure it detects the URLs. 
Prior to adding sitemap.xml, it was not detecting URLs locally as well.

Error message : 
prerendering failed: no urls found in the prerender config

**Expected behavior:**
Expecting prerendering to detect URLs and complete the build successfully.

**Steps to reproduce:**
https://github.com/shreeshbhat/strike-off
https://app.netlify.com/sites/strike-off/deploys/5e587e4ae3048d00086a7dd4

**Comment by harrysolovay** [comment]
@shreeshbhat have you set `baseUrl` in your stencil config? If not, this is likely the cause.

**Comment by shreeshbhat** [comment]
@harrysolovay : Yep, I have baseUrl set

**Comment by harrysolovay** [comment]
Sorry I can't be more helpful!

**Comment by corysmc** [comment]
FYI I just got my build running on netlify on the latest stencil/core@1.13.0 - might be worth giving it a try @shreeshbhat

**Comment by shreeshbhat** [comment]
@corysmc : Ah thanks. :)
Yes, this is working for me with latest stencil after trying a bunch of things. 
I believe I had to update the prerender command to the following : 
`stencil build && stencil prerender dist/prerender/index.js`
With the latest version, the following command is working for me : 
`stencil build --prerender --config stencil.config.ts`

**Comment by shreeshbhat** [comment]
I ll close this issue out since the prerender documentation has been updated with this info.
