### ISSUE TITLE
Contributing documentation doesn't mention how to debug stencil

### ISSUE THREAD

**Issue by shreeshbhat** [ionic-team/stencil#2227]
**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
For beginners, it is hard to figure out how to debug stencil build.
Steps to debug are not mentioned in Contributing.md and I am not able to figure out how to debug a prerender build.

**Expected behavior:**
Contributing.md should cover how to debug and run stencil locally.

**Comment by shreeshbhat** [comment]
@manucorporat / @adamdbradley : Could you please help with debug setup?

**Comment by manucorporat** [comment]
We are recently working in new docs, including debugging for prerendering. and we have plans for include vscode debugger scripts in the starters
