### ISSUE TITLE
Markup renders inside SD component w/o slot in IE11 & Edge (pre-chromium)

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2229]
**Stencil version:**

```
 @stencil/core@1.8.11
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
With a SD component (`my-component`) with the following rendering (note no slot):

```html
<div></div>
```

The following markup with render "SOME TEXT" on IE11 and pre-chomium Edge even though there is no default slot:

```html
<my-component>
  SOME TEXT
</my-component>
```

On Chrome, Firefox, etc. it will render just fine w/o the "SOME TEXT" since there is nowhere to slot it. 

**Expected behavior:**
Work the same way on IE11 / Edge as on Chrome

**Related code:**

https://github.com/learnwithratnesh/stencil-1.8.5
https://github.com/learnwithratnesh/stencil-1.8.5/blob/master/src/index.html#L14-L16
https://github.com/learnwithratnesh/stencil-1.8.5/blob/master/src/components/my-component/my-component.tsx#L10-L11

**Other information:**
Seems similar to this: https://github.com/ionic-team/stencil/issues/1759

Visual examples of IE vs Chrome follow.

**IE11 / Edge**

<img width="1424" alt="IE" src="https://user-images.githubusercontent.com/1526846/75582369-090d8600-5a31-11ea-8ae9-ce77dcb598e8.png">

**Chrome**

<img width="1424" alt="Chrome" src="https://user-images.githubusercontent.com/1526846/75582375-0b6fe000-5a31-11ea-9930-e90b2ac623bd.png">

**Comment by cheesestringer** [comment]
Had the same issue, using this as a temporary workaround:
`  @Element() host: HTMLDivElement;

  connectedCallback() {
    this.host.innerHTML = '';
  }`

**Comment by adamdbradley** [comment]
The scenario where a shadow component, without a <slot>, being ran within IE11 or Old Edge, should hide all content because there is no default slot we've decided to close without a fix. It is very rare that this scenario would come up in a production build (adding light-dom content that shouldn't every render).

**Comment by cheesestringer** [comment]
One scenario is people use the light dom as fallback content when the web component fails to render. Having inconsistent behaviour between browsers is pretty annoying.
