### ISSUE TITLE
import build errors every other recompile

### ISSUE THREAD

**Issue by coryrylan** [ionic-team/stencil#223]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Importing third party libs cause build errors every other recompile.

![stencil-bug](https://user-images.githubusercontent.com/2021067/31310003-c421f274-ab55-11e7-9356-4ba334140f0d.gif)

**Expected behavior:**
Build should be consistent.

**Steps to reproduce:**
1. Using the stencil starter project use npm to install and import one of the following libs:
`import flatpickr from 'flatpickr';` (https://github.com/chmln/flatpickr)
`import lozad from 'lozad';` (https://github.com/ApoorvSaxena/lozad.js)

2. Start the dev server and save the file containing the import.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by Hotell** [comment]
have you  installed type definitions ? `npm i -D  @types/flatpicker`  I  got no errors at all

**Comment by coryrylan** [comment]
I'll give that a shot thanks @Hotell

**Comment by coryrylan** [comment]
@Hotell that works thanks! Closing the issue.
