### ISSUE TITLE
IE11 removing node with stencil component cause a crash

### ISSUE THREAD

**Issue by telubeer** [ionic-team/stencil#2231]
**Stencil version:**

```
 @stencil/core@1.8.8
 @stencil/core@1.19.*
older versions too.
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

at IE11 removing a node with mounted stencil component cause a crash

**Expected behavior:**

IE11 do not crash

**Steps to reproduce:**

1. create fresh stencil.js project with "component" starter
```npm init stencil```
and name it as "ie11-crash"
2. move to project folder
```cd ie11-crash ```
3. copy src/index.html to ./index.html
```cp ./src/index.html ./index.html```
4. adjust ./index.html for using packages from dist
replace script tags with
```
  <script type="module" src="/dist/ie11-crash/ie11-crash.esm.js"></script>
  <script nomodule src="/dist/ie11-crash/ie11-crash.js"></script>
```
5. add "crash" button at end of the body
```
<button onclick="document.querySelector('body').innerHTML = ''">broke IE11</button>
```
6. build it
```
npm run build
```
7. use some http server for serving
```
npm i http-server
./node_modules/.bin/hs
```
8. open index.html at IE11 and click the "crash" button

**Other information:**

demo here https://github.com/telubeer/stencil-ie11-crash-demo

**Comment by adamdbradley** [comment]
This should be fixed in 1.8.11, thanks
