### ISSUE TITLE
CSS inside tsx components

### ISSUE THREAD

**Issue by lazylazyllama** [ionic-team/stencil#2234]
**Stencil version:**

```
 @stencil/core@1.8.11
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Right now it is not possible to write your css within your components tsx file. Like you do with jsx.

**Expected behavior:**
It would be nice if there were a way to write your css code under your jsx code within the component. So you don't have to create a folder for each component because it consits of a css and a tsx file... Also its nicer to have everything together in one file.

Lit-Element already works like that.

**Related code:** lit-Element example

```ts
import { LitElement, css, html } from 'lit-element';

class MyElement extends LitElement {
  render() { 
    return html`
      <div>I'm styled!</div> 
    `;
  }
 static get styles() {
    return css`
      div { color: red; }
    `;
  }
}
```

**Comment by juanmiguelbesada** [comment]
If i'm not wrong, it should be possible to use the "styles" decorator property

```tsx
@Component({
  tag: 'my-component',
  styles: `div { color: red; }`
})
export class MyComponent {
   render() { 
    return <div>I should be red!</div>;
  }
}
```

**Comment by lazylazyllama** [comment]
@juanmiguelbesada 
But that would be above the HTML tree and everything. I would very much prefer to have it below as you don't change the CSS very often compared to everything else.

**Comment by valadas** [comment]
I did not try this at all but what about:

```ts
import { Component, Host, h } from '@stencil/core';

@Component({
  tag: 'my-component'
})
export class MyComponent {
  render() {
    return (
      <Host style={this.styles}>
        <slot></slot>
      </Host>
    );
  }
  private styles= {
    color: "red"
  };
}
```

As a bonus you get intellisense on your css as opposed to a string and you can use other class variables in your css ?

Again don't quote me on this, I did not try it out :)

**Comment by valadas** [comment]
Oh, nevermind, this would not have selectors, it would only style the element where it is used...

**Comment by adamdbradley** [comment]
Using `static get styles()` was working, except it was missing looking for template literals. So you can import a css file, use a static string in the component decorator, or use `static get styles()`. The next release will have  the template literal fix. Thanks

**Comment by lazylazyllama** [comment]
Omg thank you for fixing this so fast :O

But I'm quite surprised that there even is a `static get styles()` feature in stencil.
I couldn't find anything like that in the docs. Did I miss it, or is this feature not documented yet?
