### ISSUE TITLE
EPERM: operation not permitted, copyfile

### ISSUE THREAD

**Issue by mmakrzem** [ionic-team/stencil#2235]
**Stencil version:**

```
 @stencil/core@1.8.8
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

This bug was reported in https://github.com/ionic-team/stencil/issues/1468 and claimed to be fixed, however I can still reproduce the problem.

See simple source code that I published here:
https://github.com/mmakrzem/stencilCopyBug

After grabbing all the files, make sure you **mark src/assets/images/readOnlyImage.jpg to be readOnly** (ie not writeable).

Now from the command line, run:

**npm i**
**npm run start**

Everything should work fine the first time when it builds the component, copies the src files over to www and launches the browser.

Now execute **npm run start** one more time.

You should now see the error:

[ ERROR ]  EPERM: operation not permitted, copyfile
           'C:\copybug\src\assets\images\readOnlyImage.jpg' ->
           'C:\copybug\www\assets\images\readOnlyImage.jpg'

**Comment by mmakrzem** [comment]
Just tried it with 1.8.10 and still a problem.

**Comment by manucorporat** [comment]
I remember some node versions had problems with some OSX. Updating node should fix it.

**Comment by mmakrzem** [comment]
Nope, I'm on Windows and no amount of updates fix the problem.

**Comment by manucorporat** [comment]
Could it be related with this?
https://stackoverflow.com/questions/26545837/how-to-copy-a-read-only-file?answertab=active#tab-top

**Comment by mmakrzem** [comment]
@manucorporat  That's exactly the problem.  Stencil takes a read only file and places it into the www folder automatically.  The problem with this is that it doesn't remove the readonly flag on the file, so that when it tries to do the exact same operation again, it fails, because the last time it did it, it put a readonly file there that now can not be overwritten.

Stencil should be smarter about it's copy operations so that it doesn't get itself into this mess!

**Comment by MetaGrenade** [comment]
I am also running into this issue when running `npm run watch`, it will compile the first few changes then error out (running on local environment).

**A small section of the debug log:**
`2 info using npm@6.13.1
3 info using node@v13.3.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle @~prewatch: @
6 info lifecycle @~watch: @`

**Comment by mmakrzem** [comment]
@manucorporat please re-open this issue as it has not been fixed

**Comment by Ezylpro** [comment]
Im having the same problem, did you find any solution?

**Comment by kevinch3-shoutly** [comment]
Hi! I do have the same Issue

**Comment by slpkbt** [comment]
same issue

**Comment by Mykola-Veryha** [comment]
It can be fixed with 

`sudo chown $USER:$USER -R __PROJECT__DIRECTORY `

**Comment by PiyushHUB** [comment]
This issue is coming again and again , is it really resolved?

**Comment by leocb** [comment]
I was having a simmilar issue. Found the solution in [this reddit comment](https://www.reddit.com/r/truenas/comments/1b1weo9/comment/l132fuj/), seems like it's an issue with js using chmod wrongly(?)
In my case, the library folder is in a TrueNAS Scale server. setting the ACL Mode to Passthrough solved this.

In the TrueNAS web UI, go to Datasets -> Select your data set -> Dataset Details [EDIT] -> Advanced Options -> ACL Mode -> Set to Passthrough
