### ISSUE TITLE
Support for generating Stylus documentation

### ISSUE THREAD

**Issue by skai-ste** [ionic-team/stencil#2241]
**Stencil version:**

```
@stencil/core@1.8.11
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Stencil has information on how to document your css/scss [files](https://stenciljs.com/docs/docs-json#css-variables), but our project use [Stylus](https://stylus-lang.com/) and I can't find a way how to generate it.

**Expected behavior:**

Generates documentation for Stylus. 

**Steps to reproduce:**

1. Write comments in the jsdoc-style.
2. Documentation gets generated in readme file.

**Comment by chenyulun** [comment]
me too
