### ISSUE TITLE
Upgrade puppeteer to v2.0.0

### ISSUE THREAD

**Issue by scifihotchoc** [ionic-team/stencil#2247]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently puppeteer is at v1.2 in Stencil.  This works fine when working on a local machine as puppeteer installs a local chromium.  But if you try to make this work from a container then you have to install Chromium separately using either alpine apk or from Chrome repository itself.  However, Puppeteer 1.2 uses Chromium version v78 which is not archived in either place.  But if you upgrade puppeteer to v2.0.0 then you can match that up with chromium v79 which is stored in the alpine apk repository v3.11.

My motivation for this is to use stencil.js in Google Cloud Build, which is Google's CI/CD tool.

**Expected behavior:**
Puppeteer is upgraded to v.2.0.0
(please do not update to v.2.1.1 as that Chrome is also hard to get)

**Steps to reproduce:**

**Related code:**

**Other information:**
- [Alpine apk repository](https://pkgs.alpinelinux.org/packages?name=chromium&branch=v3.11)
- [Puppeteer chrome version](https://github.com/puppeteer/puppeteer/releases)
- [Reference code that uses puppeteer in a container](https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/yarn-puppeteer/Dockerfile)
- [Puppeteer documentation on using it in a dockerfile](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker)

**Comment by scifihotchoc** [comment]
[Puppeteer v2.0.0 stating Chrome version](https://github.com/puppeteer/puppeteer/releases/tag/v2.0.0)

**Comment by manucorporat** [comment]
You can use Puppeteer 2.0 just fine, have you updated your package.json?
