### ISSUE TITLE
build stencil/core produces incorrect type definitions with TS errors

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#225]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

index.d.ts which is emitted under /testing tries to import  from  non-existing core/renderer/h ambient type definition 

![image](https://user-images.githubusercontent.com/1223799/31310967-9102a63e-aba2-11e7-95c1-acc6c1d35a1c.png)

**Expected behavior:**

No errors when running TSC

**Comment by jthoms1** [comment]
@kensodemann Any thoughts on this?
