### ISSUE TITLE
Conditional slots are not rendered correctly in IE11/Edge

### ISSUE THREAD

**Issue by cwaespi** [ionic-team/stencil#2257]
**Stencil version:**

```
 @stencil/core@1.9.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When a slot within a component is dynamically added or removed, stencil (es5 builds only) does not render correctly.

**Expected behavior:**
If a slot within a component is removed dynamically, the corresponding content should also be removed. If the slot is added again, the content should also reappear.

**Steps to reproduce:**
___
Issue A (toggle slot directly):

***Component***
```tsx
@Component({
  tag: 'dynamic-slot',
  styles: `
    div {
      display: block;
      width: 200px;
      height: 100px;
      background-color: lightcoral;
    }
  `,
  shadow: true
})
export class DynamicSlot implements ComponentInterface {
  @State() toggle: boolean;

  @Listen('click')
  clickHandler() {
    this.toggle = !this.toggle;
  }

  render() {
    return (
      <div>
        <p>{this.toggle ? 'Toggle true' : 'Toggle false'}</p>
        {this.toggle ? <slot /> : null}
      </div>
    );
  }
}
```
***HTML***
```html
<dynamic-slot>
  <a>Should be rendered if toggle is true</a>
</dynamic-slot>
```
***Before click***
The text should be hidden because toggle is false.
![IssueA-before-click](https://user-images.githubusercontent.com/14320406/76290338-5a2c3e00-62ab-11ea-822c-fe31b4388d5b.JPG)

***After first click***
Correct rendering after the first click.
![IssueA-after-first-click](https://user-images.githubusercontent.com/14320406/76290346-5ef0f200-62ab-11ea-9800-f45f1a52104b.JPG)

***After second click***
The text should be removed because toggle is false.
![IssueA-after-second-click](https://user-images.githubusercontent.com/14320406/76290360-63b5a600-62ab-11ea-8503-c50fe6067e3a.JPG)

***After nth click***
The text does not toggle. Always same result.
![IssueA-after-second-click](https://user-images.githubusercontent.com/14320406/76290360-63b5a600-62ab-11ea-8503-c50fe6067e3a.JPG)

___
Issue B (toggle slot with div wrapper):

***Component***
```tsx
import {
  Component,
  ComponentInterface,
  h,
  State,
  Listen,
} from '@stencil/core';

@Component({
  tag: 'dynamic-slot',
  styles: `
    div {
      display: block;
      width: 200px;
      height: 100px;
      background-color: lightcoral;
    }
  `,
  shadow: true
})
export class DynamicSlot implements ComponentInterface {
  @State() toggle: boolean;

  @Listen('click')
  clickHandler() {
    this.toggle = !this.toggle;
  }

  render() {
    return (
      <div>
        <p>{this.toggle ? 'Toggle true' : 'Toggle false'}</p>
        {this.toggle ? <div><slot /></div> : null}
      </div>
    );
  }
}
```
***HTML***
```html
<dynamic-slot>
  <a>Should be rendered if toggle is true</a>
</dynamic-slot>
```
***Before click***
The text should be hidden because toggle is false.
![IssueB-before-click](https://user-images.githubusercontent.com/14320406/76291099-c52a4480-62ac-11ea-846d-95d5a3e44d31.JPG)

***After first click***
Correct rendering after the first click.
![IssueB-after-first-click](https://user-images.githubusercontent.com/14320406/76291111-cb202580-62ac-11ea-8a80-af4723fede6d.JPG)

***After second click***
Correct rendering after the second click (text was removed).
![IssueB-after-second-click](https://user-images.githubusercontent.com/14320406/76291118-ce1b1600-62ac-11ea-8b1c-e9badcb1a326.JPG)

***After nth click***
The text should be displayed because toggle is true again.
![IssueB-after-third-click](https://user-images.githubusercontent.com/14320406/76291125-d1160680-62ac-11ea-86bb-69bfe6427a40.JPG)

---

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**
In the pre-release @stencil/core 1.9.0-14 it still worked.

**Comment by Gbuomprisco** [comment]
I am experiencing the same issue - but on all browsers.

**Comment by kensodemann** [comment]
I am working with someone who has fundamentally the same issue on Edge. Their repro repo is here: https://github.com/pmenichelli/angularjs-interpolation-in-slots

Despite the name of the repo, this one has nothing to do with AngularJS, they are just re-using a repo from a different issue... :)

Be sure and use the `test/unused-slots-in-edge` branch. 

so: https://github.com/pmenichelli/angularjs-interpolation-in-slots/tree/test/unused-slots-in-edge

**Comment by Knockdown26** [comment]
I am experiencing the same issue with `@stencil/core@1.9.0`  IE 11 and Edge. Will this be fixed any soon?

**Comment by antoniosZ** [comment]
same issue with "@stencil/core": "2.3.0",

**Comment by antoniosZ** [comment]
I just tried `2.4.0-1` and it fixes the slot issue but the named slots, still have similar problems

**Comment by antoniosZ** [comment]
actually, sorry, it is still not fixed for either unnamed or named slots

**Comment by antoniosZ** [comment]
I was able to get named and unnamed slots work properly on IE11 with `2.4.0-1` but with really specific workarounds.

1. the conditional slots must be wrapped with an element, rendering just `<slot></slot>` or `<slot name="test"></slot>` does not work well, if at all
2. the hidden attribute that gets added to the hidden slots, does not get removed properly and stays depending on what got rendered and when

I managed to get everything working by doing the following:

1. as mentioned, wrap the conditional slots in an element (note: Fragment does not work, I tried) ie. `<span><slot></slot></span>`, `<span><slot name="test"></slot></span>`
2. use CSS as fallback in IE11, to target the slotted elements by their names ie `::slotted(*[slot='test'])` and hide/show them depending on my state. this ensures the slots that should be hidden are hidden but also the ones that should be visible are visible (remember, the hidden attribute does not get applied/removed correct at this point in time)

I hope this helps with further fixing stencil+ie11 conditional slots or if nothing else, when `2.4.0-1` becomes stable, if the fix stays as-is, others will know the workaround...

**Comment by alvarocjunq** [comment]
Hi, seems not fixed until the version 2.5.2 =/
Having the same problem here, conditionals slots do not reappear in IE11

**Comment by Amerr** [comment]
I face similar issues, the slots are rendering not in the expected order
```

  render() {
    return (<section>
      <div>
        <slot name="heading"></slot>
      </div>
      {this.description ? <div>
        <slot name="description"></slot>
      </div> : ''}
    </section>);
  }

```


```
<cms-section>
	<h2 slot="heading">Hello</h2>
	<p slot="description">Welcome to world</p>
</cms-section>
```

Expected Result: 
```
<cms-section>
	<section>
		<div><h2 slot="heading">asd</h2></div>
		<div><p slot="description">asd</p></div>
	</section>
</cms-section>
```

Actual Result: 
```
<p slot="description" hidden="">Welcome to world</p>
<section>
	<div> <h2 slot="heading">Hello</h2>
	</div>
</section>
```

**"@stencil/core": "^2.0.1"**

**Comment by rwaskiewicz** [comment]
Hey folks - I apologize that it took so long for someone on the team to respond to this. After taking a look at the two reproduction cases in the original post, as well as the case provided in @kensodemann's comment, I've concluded that this bug does not present itself on the latest versions of MS Edge.

Starting with Stencil v4, we have dropped support for earlier version of Edge, as well as IE. As such, I'm going to close this issue out.

If you feel that this bug still exists, please feel free to take a look at our open issues to see if someone else has reported it. If not, please feel free to open a new issue.

Thank you, and once again I apologize for the lack of response from someone on this issue.
