### ISSUE TITLE
@stencil/core has breaking updates

### ISSUE THREAD

**Issue by beenotung** [ionic-team/stencil#2263]
**Stencil version:**

```
 @stencil/core@1.9.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I notice the core stencil package is having breaking updates but the semver didn't do major update.
For example, as of @stencil/core@1.8.8, we can import VNode from '@stencil/core/dist/declaration'.
But in @stencil/core@1.9.1, that folder is removed, we need to instead import VNode from '@stencil/core/internal/stencil-core'

**Expected behavior:**

Either the folder and types should remind available in the old path or the package version should jump up the major version (e.g. into 2.0.0)

**Steps to reproduce:**

npm install @stencil/core@1.8.8 and @stencil.core@1.9.1 then check for the folder 'dist' under the root direction of the downloaded packages.

**Related code:**

```tsx
// fine in 1.8.8, but cannot compile in 1.9.1
import { VNode } from '@stencil/core/dist/declarations';

// this path works for both versions
import { VNode } from '@stencil/core/internal/stencil-core';
```

**Other information:**

**Comment by adamdbradley** [comment]
Both imports are from private APIs and should not be imported.

**Comment by beenotung** [comment]
If I should not import those types, should I copy them when I need the type?
Any suggestion beside using any type?
