### ISSUE TITLE
Name clash bug in @stencil/core@~1.9

### ISSUE THREAD

**Issue by beenotung** [ionic-team/stencil#2268]
**Stencil version:**

```
 @stencil/core@1.9.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When a stencil component using `@State()` decorator and import other typescript file that has own class also named `State`, the runtime error `State is not defined` is throw, and the page cannot be shown. This bug only happens in `@stencil/core@~1.9`, it was fine in `@stencil/core@~1.8`.

**Expected behavior:**

The compiled code should resolve name clash automatically.

**Steps to reproduce:**

Create a ionic pwa project with below component and typescript file, try with @stencil/core@1.8.11 and @stencil/core@1.9.2.

**Related code:**

setting-page.tsx
```tsx
import { Component, h, State } from '@stencil/core';
import { state } from '../../global/state';

@Component({
  tag: 'settings-page',
})
export class SettingsPage {
  @State()
  loading = state.loading;

  render() { return 'hello' }
}
```

state.ts
```ts
class State {
  loading = 0;
}
export let state = new State()
```

**Comment by beenotung** [comment]
This problem is also in the latest build (@stencil/core v1.12.1)

**Comment by manucorporat** [comment]
I can't reproduce it with thee provided code, can you provide a full project?
