### ISSUE TITLE
Doc Gen: Generate documentation for listeners

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2271]
**Stencil version:**

```
 @stencil/core@1.9.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently, listeners are not part of the automatic document generation.

**Expected behavior:**

Include them...

Use Case from requesting community member:

I'm building a component viewer that would allow developers to visualize a component and see all the props, events, methods on a component. We are also constructing some components to listen for events like a loss of network connectivity. The component can then react to this event by disabling if a netsensitive' prop is enabled. The developers need to know however what events the component is listening for in order to generate them. Having the document generator provide this would be good otherwise we would have to manually document it.

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/stencil/pull/2272
