### ISSUE TITLE
Feature Request: Component prefixes

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2274]
**Stencil version:**

```
 @stencil/core@1.9.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Can only use one version of a component in an application.

**Proposed Solution:**

Since we do have a lot of consumers, that build web components based on our components, it may happen that multiple versions of our components are required on the same page.
The browsers CustomElementRegistry is global and doesn't allow to have multiple versions of the same component with the same name.
To solve this problem we want to provide the consumers the possibility to prefix the components at runtime.
Changes that would be required from stencil side are:
1. extend CustomElementsDefineOptions with a new string option (for example "prefix")
2. use the new option from CustomElementsDefineOptions in bootstrap-lazy.ts to prepend it to the tagname in the line `const tagName = cmpMeta.$tagName$;`

**Comment by manucorporat** [comment]
fixed by #2343
