### ISSUE TITLE
Testing component logic results in warning

### ISSUE THREAD

**Issue by scifihotchoc** [ionic-team/stencil#2275]
**Stencil version:**

```
 @stencil/core@1.10.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Running a unit test in .spec.ts for component logic gives out a warning:

   ` console.warn node_modules/@stencil/core/internal/testing/index.js:2900
      Use newSpecPage() to instanciate component instances.
   `
Comment out the component logic test and the warning disappears.  Example of component logic test:
` it('builds', () => {
     expect(new Note()).toBeTruthy();
   });`

**Expected behavior:**
No warning should come out.

**Steps to reproduce:**
Already described above

**Related code:**
Already shown above

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by manucorporat** [comment]
This is the expected behaviour, we recommend to use newSpecPage() instead of `new`:
https://stenciljs.com/docs/unit-testing#newspecpage-

**Comment by notbear** [comment]
> This is the expected behaviour, we recommend to use newSpecPage() instead of `new`:

@manucorporat but a few lines below you can find a chapter named 'Testing Component Class Logic' https://stenciljs.com/docs/unit-testing#testing-component-class-logic which shows an instatiation example with new. Inconsistency in the code or outdated documentation?

**Comment by apillard** [comment]
See corresponding issue against stencil docs site here. Either the stencil cli or docs site needs a fix.

https://github.com/ionic-team/stencil-site/issues/594

**Comment by ashika01** [comment]
@manucorporat Why was this issue closed? The warning message is kinda misleading considering both in docs and the app created through the CLI has the usage mentioned [here ](https://stenciljs.com/docs/unit-testing#testing-component-class-logic)

**Comment by doliG** [comment]
@manucorporat agree with op, could you please reopen and handle the issue ?
These warnings pollute test logs.
