### ISSUE TITLE
.toEqualHtml does not exist

### ISSUE THREAD

**Issue by scifihotchoc** [ionic-team/stencil#2276]
**Stencil version:**

```
 @stencil/core@1.10.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
In test code `expect(page.root.shadowRoot).toEqualHtml(...`
Typescript compiler complains .toEqualHtml does not exist

**Expected behavior:**
No error

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by warapitiya** [comment]
May I know more info about this?

Below repo uses 1.10.1 and looks like ```.toEqualHtml``` is working.
 https://github.com/warapitiya/stencil-unit-test-issue

```sh
yarn list v1.22.0
└─ @stencil/core@1.10.1
✨  Done in 0.32s.
```

**Comment by scifihotchoc** [comment]
It's not a matter of it not working .. it works fine.  
It's a matter of Typescript not recognizing the type.  I've added a screen grab:
<img width="605" alt="Screen Shot 2020-03-18 at 3 30 24 PM" src="https://user-images.githubusercontent.com/11839167/77013601-9b68c180-692d-11ea-8725-29b0dcb4ef03.png">

**Comment by scifihotchoc** [comment]
FYI my import statement:
`import { newSpecPage } from '@stencil/core/testing';
`

**Comment by warapitiya** [comment]
Can you verify the type definition file is there?

```node_modules/@stencil/core/internal/stencil-private.d.ts```

**Comment by scifihotchoc** [comment]
Yes.  It is there.  Just FYI quoting the entire error message:

Property 'toEqualHtml' does not exist on type
'JestMatchersShape<Matchers<void, any>, Matchers<Promise<void>,
any>>'.ts(2339)

**Comment by scifihotchoc** [comment]
Also note this is in a spec.ts file and my only
imports are @stencil/core/testing and my component which in this case
happens to be AppHome.

**Comment by scifihotchoc** [comment]
Ok .. now also adding a second error of the same type here:

"Property 'toHaveClass' does not exist on type 'JestMatchersShape<Matchers<void, E2EElement>, Matchers<Promise<void>, E2EElement>>'.ts(2339)"

This error now occurs in an e2e.ts file.

Also, I'm using @ts-ignore to get rid of this, but it would really nice to have a fix suggested.

**Comment by warapitiya** [comment]
I believe this is not an issue with `@stencil/core`.  

Below image show it's working for me.
<img width="1552" alt="Screenshot 2020-03-22 at 9 51 28 AM" src="https://user-images.githubusercontent.com/6380518/77240663-57263b80-6c23-11ea-95e1-4815b758582e.png">

May I confirm, whether you have `@types/jest` installed as a dev dependency?

**Comment by scifihotchoc** [comment]
Yes, that is installed.  But note that toEqualHTML is not a jest type.
Reference: https://jestjs.io/docs/en/expect.

**Comment by scifihotchoc** [comment]
Ok .. it looks like a full upgrade solves the problem.

**Comment by warapitiya** [comment]
Can you close this issue?
