### ISSUE TITLE
Change readme.md to uppercase

### ISSUE THREAD

**Issue by luenmuvel** [ionic-team/stencil#2278]
I find in the stencil/core, that the readme.md file is hardcoded in lowercase in the line 12435 of the file:
> @stencil\core\dist\compiler\index.js

![imagen](https://user-images.githubusercontent.com/34595961/72463427-2fd56d00-37a1-11ea-8ac0-49c54f143d6c.png)

I think that it's important to have the opportunity to configure the output of that file, to choose between lowercase and uppercase.

**Comment by manucorporat** [comment]
It would require to expose a new API and updating a lot paths, the JSON generations actually reads the readme too in order to generate the json output, too many moving parts, risky change for no big win. But thank's for the idea, we will keep it on mind for future apis.
