### ISSUE TITLE
compiler: class property function expressions are not bound correctly

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#228]
**Stencil version:**
```
@stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
class property function are not bound correctly

**Expected behavior:**
properly handle `this` within callbacks from within VDom inside `render()`

**Related code:**

following doesn't work, but it should ( arrow function is always bound to MyCmp )

```tsx
class MyCmp {
  private handleChange = (e: Event) => {
     console.log(e)
  }
  render(){
    return <input type="checkbox" onChange={this.handleChange} />
}
```

when called explicitly everything works ofc

```tsx
class MyCmp {
  private handleChange = (e: Event) => {
     console.log(e)
  }
  render(){
    return <input type="checkbox" onChange={e=>this.handleChange(e)} />
}
```

**Comment by jgw96** [comment]
Pretty sure @jthoms1 has talked about this before and might have some feedback for this issue.

**Comment by jthoms1** [comment]
I believe this should be fixed with release 0.0.6-11.

**Comment by Hotell** [comment]
link to commit pls ? :) 👍

**Comment by jthoms1** [comment]
https://github.com/ionic-team/stencil/commit/646618a5411000611704775e190203b89fc625a7

**Comment by Hotell** [comment]
just tested again with latest `0.0.6-13`. Works. thx!
