### ISSUE TITLE
No style block in lit-html or React

### ISSUE THREAD

**Issue by whoisryosuke** [ionic-team/stencil#2281]
**Stencil version:**

```
 @stencil/core@^1.8.4
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request

I created [this issue in the lit-html repo](https://github.com/Polymer/lit-html/issues/1119), but after testing in React I was able to replicate the same issue, so it must be derived from StencilJS (or my component code 😅).

**Current behavior:**
No style block is displayed when I render StencilJS components with `lit-html` or `React`. StencilJS web components render properly, complete with styles -- but the styles are non-existent in the DOM (shadow or light/regular). If you inspect the component, you can see styles applied, but you can't go to where it's defined (unlike other styles, which will point you to <style> blocks or CSS files).

**Expected behavior:**

Should see a `<style>` block inside the web component's shadow root that contains the components styles. 

- [Here you can see the style block (when I don't use lit-html to render the components)](https://i.imgur.com/1nq3kt6.png)
- [Here you can see the lack of a style block (when I use lit-html)](https://i.imgur.com/hw2ohLo.png)

lit-html seems capable of making `<style>` blocks. [If you run a test](https://codepen.io/justinfagnani/pen/mBQpqJ) where you place the style directly in lit's `html()`, you can see the `<style>` block in the shadow root. But for some reason the way StencilJS handles styles, it doesn't get picked up by lit to render in the DOM (but still gets applied?).

**Steps to reproduce:**

1. Setup new vanilla JS project (index.html and index.js files)
2. Add my StencilJS web components to the index.html in a script tag:

```html
<script src="https://unpkg.com/sui-web-components@0.0.1/dist/sui-web-components.js"></script>
```

3. Add this to index.js

```ts
import { html, render } from "lit-html";

const myTemplate = name =>
  html`
    <sui-base>
      <sui-box display="flex">
        <sui-text as="h2" width="50%">Side by side</sui-text>
        <sui-text as="h2" width="50%">Side by side</sui-text>
      </sui-box>
    </sui-base>
  `;

render(myTemplate("World"), document.body);
```

4. See components side by side (complete with font styling). But if you inspect, no style block inside any of the web component's shadow root.

Same with React. Just import and use the components. Same result.

**Live Reproduction Link**
https://codesandbox.io/s/jovial-mccarthy-qtckg

**Related code:**

React code if necessary:

```tsx

import {
  applyPolyfills,
  defineCustomElements
} from "sui-web-components/loader";

ReactDOM.render(<App />, document.getElementById("root"));

applyPolyfills().then(() => {
  defineCustomElements(window);
});
```

```tsx
import React from "react";
import logo from "./logo.svg";
import "./App.css";

function App() {
  return (
    <div className="App">
      <sui-base>
        <sui-box display="flex">
          <sui-box
            width={[1, 1/2, 1/4]}
            color="black"
            font-size="24px"
            bg="green"
            letter-spacing="1em"
            padding={2}
          >
            Stacked Box
          </sui-box>
          <sui-box
            width={[1, 1/2, 1/4]}
            color="white"
            bg="blue"
            font-size="24px"
            text-align="center"
            padding={2}

          >
            Stacked Box
          </sui-box>
          <sui-box
            width={[1, 1/2, 1/4]}
            color="white"
            bg="black"
            text-align="right"
            font-weight="bold"
            padding={4}
          >
            Stacked Box
          </sui-box>
        </sui-box>
      </sui-base>
    </div>
  );
}

export default App;

```

**Other information:**

**Comment by manucorporat** [comment]
This is the expected behaviour, stencil uses constructable stylesheets when possible to improve performance!
https://developers.google.com/web/updates/2019/02/constructable-stylesheets
