### ISSUE TITLE
`stencil generate` completely broken

### ISSUE THREAD

**Issue by alexandertrefz** [ionic-team/stencil#2282]
**Stencil version:**
```
 @stencil/core@1.10+
```

**I'm submitting a:**
[ x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
`npm run-script generate` causes stencil to generate a new component called "run-script", it doesnt allow me to set a name. It also creates a deep folder hierachy from the base of the path. If it is executed in `/x/y/z` it will create `/x/y/z/x/y/z/src/components/run-script/`

If called via `yarn generate` the name can be set, but the path issue remains.

The package.json script is simply `stencil generate`.

**Expected behavior:**
It should allow me to name the components and create it in the correct place.

**Steps to reproduce:**
Install a stencil version past 1.9.2 and run `npm run-script generate` or `yarn generate`

**Comment by manucorporat** [comment]
I can't reproduce it, can you provide more details? your stencil.config.js, is it a monorepo?

**Comment by manucorporat** [comment]
actyually, i am sorry, yes i can reproduce, fixing!

**Comment by manucorporat** [comment]
Thanks for the issue!
