### ISSUE TITLE
Bug: Failure to import JavaScript library module

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2287]
**Stencil version:**

```
 @stencil/core@1.10.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Cannot import the `he` library:
https://www.npmjs.com/package/he

**Expected behavior:**
It would load...

**Steps to reproduce:**
1. `git clone git@github.com:miguelyoobic95/test-component.git`
1. `cd test-component`
1. `git checkout bug-commonjs`
1. `npm i`
1. `npm run build`

At that point, you should see the following error in the build:

```
[16:42.8]  @stencil/core v1.10.1 [NEXT] 🍋
[16:43.8]  build, test-component, dev mode, started ...
[16:43.8]  transpile started ...
[16:44.9]  transpile finished in 1.14 s
[16:44.9]  copy started ...
[16:44.9]  generate lazy started ...
[16:45.1]  copy finished (0 files) in 175 ms
[16:45.5]  generate lazy finished in 599 ms

[ ERROR ]  Rollup: Missing Export: ./src/components/my-component/my-component.tsx:3:7
           'default' is not exported by ./node_modules/he/he.js

      L2:  import he from 'he';
      L4:  @Component({

[16:45.5]  build failed in 1.79 s
```

**Related code:**
https://github.com/miguelyoobic95/test-component/blob/bug-commonjs/src/components/my-component/my-component.tsx

**Comment by manucorporat** [comment]
The library is not authored with a good format for rollup to bundle:
https://unpkg.com/browse/he@1.2.0/he.js

Notice it lacks ESM and commonjs

**Comment by ghaiat** [comment]
@manucorporat anything we can do ? we cannot modify the lib and it s not the only one with the same issue. it was working fine in 1.8

**Comment by Jagget** [comment]
I had the same issue
Adding 
```typescript
  nodeResolve: {
    browser: true
  },
```

into `stencil.config.ts` solved it.

**Comment by darondel-yoobic** [comment]
Adding `browser: true` does not work for us.

Just a few notes on tests that I tried so far. In [this repository](https://github.com/miguelyoobic95/test-component/blob/bug-commonjs/src/components/my-component/my-component.tsx), I tried to downgrade to 1.9.2:
- `stencil build --prod` works.
- `stencil build --dev --watch --serve` works.
- `stencil build --esm --next --dev` fails. By removing `--next`, it works again.

**Comment by darondel-yoobic** [comment]
In order to fix this issue, add this in your `stencil.config.ts` file:
`rollupPlugins: { after: [nodePolyfills()] }`

Should work.

**Comment by PatrickNausha** [comment]
For anybody still stumbling on this years later, I ran into the same issue when installing Quill and here's how I fixed it:

My error was
```
[ ERROR ]  Rollup: Missing Export: ./src/components/comment-drawer-text-input/comment-drawer-text-input.tsx:2:7
           'default' is not exported by ./node_modules/quill/dist/quill.js, imported by
           ./src/components/comment-drawer-text-input/comment-drawer-text-input.tsx
```

> In order to fix this issue, add this in your stencil.config.ts file:
rollupPlugins: { after: [nodePolyfills()] }

This helped me ☝️, but I think my exact problem was what's covered by the docs already: https://stenciljs.com/docs/module-bundling#node-polyfills

> rollup-plugin-node-polyfills is a code-transform plugin, so it needs to run AFTER the commonjs transform plugin, that's the reason it's placed in the "after" array of plugins.

If you have `nodePolyfills()` in the `plugins` array in your `stencil.config.ts`, you want to move it down into `rollupPlugins: { after: [nodePolyfills()] }` to satisfy the commonjs transform warning above.

The same would apply to anyone using `rollup-plugin-node-globals` in an older project that hasn't yet switched to `rollup-plugin-polyfill-node`
