### ISSUE TITLE
Server side rendering changes broke generic ssr.js script

### ISSUE THREAD

**Issue by mortenson** [ionic-team/stencil#229]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
$ npm list @stencil/core
drupal-stencil@1.0.0 /Users/samuelmortenson/Sites/ame-docker/ame/web/modules/contrib/stencil
└── @stencil/core@0.0.6-11
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Two weeks ago I wrote a generic Node script that would allow arbitrary HTML to be server side rendered using Stencil, which was working great until I upgraded to 0.0.6-11. This script is used by the Drupal Stencil module to pipe HTML output through the script with for a given Stencil component collection, but I published it for other users here: https://gist.github.com/mortenson/24f4959b07acd4e0cef83d4344f53807

I think that something changed when the SSR middleware example was added - maybe some internal refactoring changed how the script works?

**Expected behavior:**
I expect that I can SSR arbitrary HTML with a component collection, as not everyone is running a Node server and still wants to use Stencil with SSR.

**Steps to reproduce:**

1. `git clone git@github.com:mortenson/ame-components.git`
1. `cd ame-components && npm install && npm run build`
1. `wget https://gist.githubusercontent.com/mortenson/24f4959b07acd4e0cef83d4344f53807/raw/646408ec3120edf29b4b78b28bac4994e1e0769d/ssr.js`
1. `echo '<ame-text>Hello</ame-text>' | node ssr.js . ../dist ame`

See that there's no output or errors from the script. In 0.0.5 this code would at least return whatever HTML was passed to it, even if SSR failed to run.

I've also tried to just load the `stencil.config.js` and use that, i.e. instead of doing:

```
var config = stencil.loadConfig({
    rootDir: args[0],
    buildDir: args[1],
    namespace: args[2]
  });
```

do

```
var config = stencil.loadConfig(__dirname);
```

but that isn't working either. 😢 

**Related code:**

You can find the SSR script here: https://gist.github.com/mortenson/24f4959b07acd4e0cef83d4344f53807

**Other information:**

Thanks for helping me out!

**Comment by jgw96** [comment]
Talked with Sam about this on slack today, he is going to post more info soon.

**Comment by adamdbradley** [comment]
Thanks for opening the issue, but SSR has since been refactored. We're adding more unit tests to minimize regressions like this in the future, thanks
