### ISSUE TITLE
Gatsby build error with Stencil v1.10.x: "window" is not available during server side rendering.

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#2290]
**Stencil version:**
v1.10.x

**I'm submitting a:**
[X] bug report

**Current behavior:**
Follow up of previous issue #1724 which has been marked as resolved.

I'm still unable to import Stencil Web Component in Gatsby website without workarounds even if Stencil v1.10.x has been used to bundle the component.

**Build error:**

```
failed Building static HTML for pages - 1.777s

 ERROR #95312 

"window" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


   8 | import { defineCustomElements as deckdeckgoLazyImgLoader } from "@deckdeckgo/lazy-img/dist/loader"
   9 | 
> 10 | deckdeckgoLazyImgLoader(window)
     |                         ^
  11 | 
  12 | const IndexPage = () => (
  13 |   <Layout>


   WebpackError: ReferenceError: window is not defined
  
  - index.js:10 Module../src/pages/index.js
    src/pages/index.js:10:25
  
  - index-a6d55a59.js:288 Module._compile
    node_modules/@deckdeckgo/lazy-img/dist/esm-es5/index-a6d55a59.js:288:1
  
  - index-a6d55a59.js:308 Object.Module._extensions..js
    node_modules/@deckdeckgo/lazy-img/dist/esm-es5/index-a6d55a59.js:308:1
  
  - index-a6d55a59.js:137 Module.load
    node_modules/@deckdeckgo/lazy-img/dist/esm-es5/index-a6d55a59.js:137:1
  
  - index-a6d55a59.js:37 Function.Module._load
    node_modules/@deckdeckgo/lazy-img/dist/esm-es5/index-a6d55a59.js:37:1
  
  - index-a6d55a59.js:177 Module.require
    node_modules/@deckdeckgo/lazy-img/dist/esm-es5/index-a6d55a59.js:177:1
```

**Steps to reproduce:**

```
git clone https://github.com/peterpeterparker/stencil-imort
cd stencil-import
npm install
npm run build
```

**Comment by peterpeterparker** [comment]
@viljamis in the previous issue you said it worked out for you with the `--next` flag and `1.9.0-14`, is it still the case? How do you import your component?

**Comment by peterpeterparker** [comment]
It works like a charm if the loader is used without `window`, my bad

```
import { defineCustomElements } from '@deckdeckgo/highlight-code/dist/loader';
defineCustomElements();
```

Gatsby dev and prod build tested.

**Comment by seanaguinaga** [comment]
@peterpeterparker how did you remove ```window```?

I'm still not having luck with this

**Comment by peterpeterparker** [comment]
@seanaguinaga umm I think I "just" upgraded the Stencil version in my component

as you can see in my website [imports](https://github.com/peterpeterparker/daviddalbusco.com/blob/2f4b84a20ef8d89c7de2f8b1401937b1a1482a50/src/components/layout/layout.js#L23) I use the loader, no window
