### ISSUE TITLE
Bug: All but the first stylesheet in styleUrls are ignored

### ISSUE THREAD

**Issue by patrickhaug** [ionic-team/stencil#2291]
```
 @stencil/core@1.10.3
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
```

@Component({
  tag: "component",
  styleUrls: [
    "../../shared/flex.css",
    "../../shared/width.css",
    "../../shared/height.css"
  ],
  shadow: true
})
```

Only first reference in styleUrls array is added to the component with the rest beeing ignored. Works normal with the legay compiler.

**Expected behavior:**
All references should be included in the component.

**Steps to reproduce:**
Provide an array with multiple style urls to the styleUrls key.

**Comment by Nightmaster** [comment]
Is this post ignored because Ionitron-bot didn't mark it?!

**Comment by Nightmaster** [comment]
@patrickhaug I let you see the answer in #2324

**Comment by patrickhaug** [comment]
Thanks! But I go with the last comment. I worked in earlier versions and interface also says something diferent, no?

**Comment by LukePammant** [comment]
I also got stuck on this trying to figure out why all of a sudden half of my styles weren't getting loaded after `npm update`. I'm using scss so I fixed it by just making a single scss file that has `@import` statements for my other styles:

Change the styleUrls to just a single styleUrl string:
` styleUrl: 'button.scss'`

button.scss:
`
    @import './button-block.scss';
    @import './button-link.scss';
`

**Comment by patrickhaug** [comment]
Thats true. But then you dont have a constructible stylesheet for each css file, thus lots of repitition?
