### ISSUE TITLE
Stencil compiler warnings not consistent. 

### ISSUE THREAD

**Issue by threeaccents** [ionic-team/stencil#2293]
**Stencil version:**
```
@stencil/core@1.11.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'll run `npm run build` and get a bunch of helpful compiler warnings about prop names and not using prop methods. I do some clean up to the code and run `npm run build` again and a lot of the warnings from the first command don't show up.

**Expected behavior:**
Always show all compiler warnings.

**Steps to reproduce:**
Run `npm run build` make some code changes and run again. See if the same warnings show up.

**Comment by rwaskiewicz** [comment]
Hey @threeaccents 👋 

I apologize that it took so long for someone on the team to acknowledge this ticket.

It's a little difficult to diagnose an issue here without seeing the messages that Stencil was producing at the time alongside the code. Generally speaking, a compiler might have different information available to it once the source code changes, which in theory could have explained the differences in error messages. However, without a concrete example, I can't be 100% sure.

Stencil v1.X is no longer supported. However, if you're still seeing this issue and are willing/able to make a new issue with a reproduction case, the team and I would be more than happy to take a look.

Thanks again!
