### ISSUE TITLE
Timeout on DOM writes is very short

### ISSUE THREAD

**Issue by ryanhollister** [ionic-team/stencil#2294]
**Stencil version:**

```
 @stencil/core@1.11.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When there is a large number of nested components stencil builds up a large queue of DOM writes. This large queue of DOM writes causes significant initial rendering delays. Stencil does not account for the size of the queue. It only increases the servicing time of the queue by 0.45 milliseconds each time it services the queue but fails to finish.

**Expected behavior:**
The DOM writes should be serviced more aggressively as the size grows

**Related code:**
https://github.com/ionic-team/stencil/blob/master/src/client/client-task-queue.ts#L63
```tsx
const timeout = (plt.$flags$ & 6 /* queueMask */) === 2 /* appLoaded */ ? performance.now() + 10 * Math.ceil(queueCongestion * (1.0 / 22.0)) : Infinity;
```

This line of code client-task-queue.ts is the amount of time stencil will spend on servicing the queued DOM writes. This timeout increases very slowly each attempted servicing run. 

Can we discuss the formula? Right now, the very first run will only service the queue for 10 milliseconds. It will never spend more than 10 milliseconds on a service run till its serviced the queue > 22 times without completely flushing it.

The complexity of the code to compute this fairly static number of '10' or '20' makes me think there is a bug.

On slower mobile devices I am seeing only a dozen or so items get serviced in the queue on a single run; with hundreds of items in the queue. 

@adamdbradley @manucorporat  looks like you guys have worked on this file in the past, can you share any insight into this calculation?

Playing with the number/calculation a bit just so it spends 50-100ms servicing the queue improves rendering performance signficantly.

The other thing I noticed is that prior to 'appLoaded' it will spend 'Infinity' time servicing the queue. Is there any way to allow the slotted content to be written prior to appLoaded = true? This would allow the queue to be completely flushed for the slotted content.

Could be similar to #2058

**Comment by manucorporat** [comment]
This might make the trick:https://github.com/ionic-team/stencil/pull/2318

**Comment by ryanhollister** [comment]
This looks interesting, thanks @manucorporat. I'll pull down this branch and do some testing with the various queue options.

Also, I see you updated the calculation for congestionAsync's timeout. 

It still still seems low (14ms servicing until the 10th incomplete run)... What do you think about changing the calculation to something a little more dynamic like:

`performance.now() + 14 * Math.ceil(queueDomWritesLow.length * (1.0 / 10.0))`

**Comment by manucorporat** [comment]
The whole purpose of that number of the be lower than 16ms, so we don’t block css animations, it really can’t be longer than that in this queue. Please let me know what you find with this!
