### ISSUE TITLE
Bug : Cannot run prerender without running build

### ISSUE THREAD

**Issue by shreeshbhat** [ionic-team/stencil#2295]
**Stencil version:**
```
  @stencil/core@1.11.0
```
**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => 
**Current behavior:**
Have to run `stencil build` before running `stencil prerender dist/prerender/index.js`
I see that dist folder doesn't get generated with stencil prerender and stencil build generates the dist folder.
**Expected behavior:**
I am expecting prerender to the build as well. 
Currently, I can work around this by running `stencil build && stencil prerender dist/prerender/index.js`.

**Comment by adamdbradley** [comment]
This is a documentation issue, as the reason for the `stencil prerender path/to/prerender/index.js` is so that build is not required and "rebuilds" the `index.js` file each time. Thanks for helping to identify the issue, would you be able to update the docs to reflect this? Thanks

**Comment by shreeshbhat** [comment]
Sure, happy to update the documentation. 
Expect a PR by tomorrow 💃
