### ISSUE TITLE
Bug : Prerendering is not registering service worker

### ISSUE THREAD

**Issue by shreeshbhat** [ionic-team/stencil#2296]
**Stencil version:**
```
 @stencil/core@1.11.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request

**Current behavior:**
Currently, I see that prerendering is not registering service worker.
In www/index.html, I don't see the following code snippet which registers sw.

```
window.addEventListener('load', function () {
        navigator.serviceWorker.register('/sw.js')
          .then(function (reg) {
            reg.onupdatefound = function () {
              var installingWorker = reg.installing;
              installingWorker.onstatechange = function () {
                if (installingWorker.state === 'installed') {
                  window.dispatchEvent(new Event('swUpdate'))
                }
              }
            }
          })
          .catch(function (err) { console.error('service worker error', err) });
      });
```

**Expected behavior:**
I see service worker being registered for `stencil build`. Expectation is that, service worker registers and works fine in prerendering as well.

**Steps to reproduce:**
I am using prerendering build for the following project.
https://github.com/shreeshbhat/strike-off

**Comment by shreeshbhat** [comment]
@manucorporat : Please let me know if any help needed.
Tried going through the source code to figure out the issue.

**Comment by shreeshbhat** [comment]
I changed the following command 
`stencil build && stencil prerender dist/prerender/index.js`
to 
`stencil build --prerender --config stencil.config.ts`
And I am able to see service worker registeration in index.html

**Comment by christian-bromann** [comment]
Thanks for providing a solution to the issue you've discovered. I will go ahead and close this.
