### ISSUE TITLE
stenciljs.com - newsletter signup form is not working

### ISSUE THREAD

**Issue by mikkelrom** [ionic-team/stencil#2298]
**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When trying to sign up for the newsletter on the https://stenciljs.com/ homepage, it fails.

**Expected behavior:**
It should not fail 😉 

**Steps to reproduce:**
1. Go to https://stenciljs.com/ and scroll to the bottom
1. Enter an e-mail in the e-mail field
1. Click the Subscribe button

![image](https://user-images.githubusercontent.com/6212369/77326153-afd80000-6d19-11ea-99ca-9b5a25cea686.png)

![image](https://user-images.githubusercontent.com/6212369/77326505-2ffe6580-6d1a-11ea-8ac8-53eda408d239.png)

**Comment by rwaskiewicz** [comment]
This appears to have been fixed, but the issue was never closed 😢 Sorry about that, and thanks for reporting this!
