### ISSUE TITLE
--next does not import ionic css

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#2300]
**Stencil version:**
```
 @stencil/core@1.1.2
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
When upgrading Stencil to a version that uses the `--next` compiler the ionic css no longer loads.  I am just using Stencil and Ionic (not React or Angular)

```css
// my.scss
@import '~@ionic/core/css/core.css';
```

When I run the app I get the following error:
```
GET http://localhost:3333/~@ionic/core/css/core.css net::ERR_ABORTED 404 (Not Found)
```

This causes the UI to lose font, colors, etc.

**Comment by peterpeterparker** [comment]
Looks like the issue I opened this weekend too, therefore here the reference: https://github.com/ionic-team/stencil/issues/2292

**Comment by manucorporat** [comment]
We are working on it!

**Comment by cjorasch** [comment]
This appears to be working now.  Thanks!

**Comment by rwaskiewicz** [comment]
> This appears to be working now. Thanks!

Looks like this issue wasn't closed when it was completed. Closing
