### ISSUE TITLE
E2E .find find element in nested shadow dom using multiple '>>>' notations

### ISSUE THREAD

**Issue by scifihotchoc** [ionic-team/stencil#2302]
**Stencil version:**

```
 @stencil/core@1.10.0
```

**I'm submitting a:**

[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Currently it is not possible to find an element in a component that is a child of another component where both components have shadow doms.

**Expected behavior:**
it would be great if we could have a feature like so:

`const page = await newE2EPage();
await page.setContent('<component1></component1>');
const el = await page.find('component1 >>> component2 >>> #div-in-component2');`

Failing this we could have something like this:
`const comp2 = await page.find('component1 >>> component2');
const el = await comp2.find(':host >>> #div-in-component2');`

**Steps to reproduce:**
N/A

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**
Refer to [stackoverflow question](https://stackoverflow.com/questions/60804053/stenciljs-e2e-testing-how-to-find-a-child-of-a-child-in-the-shadow-dom/60814091#60814091)

**Comment by scifihotchoc** [comment]
Formatting up the code snippets from above

`const page = await newE2EPage(); `
`await page.setContent('<component1></component1>'); `
`const el = await page.find('component1 >>> component2 >>> #div-in-component2');`

Failing this we could have something like this:

`const comp2 = await page.find('component1 >>> component2');`
`const el = await comp2.find(':host >>> #div-in-component2');`

**Comment by doctor-house** [comment]
I was able to get around this in my tests with the following:

```javascript
const page = await newE2EPage();
await page.setContent('<component1></component1>');
const comp1shadow = await page.find('component1 >>> :first-child');
const divincomp2 = await comp1shadow.find('component2 >>> #div-in-component2');
```

**Comment by alexanderkjeldaas** [comment]
@doctor-house for me the `divincomp2` is null for these cases.

**Comment by doctor-house** [comment]
@alexanderkjeldaas can you provide some context for what your DOM looks like and what selectors you're using? This is still currently working in my tests.
