### ISSUE TITLE
Import JS library inside component using shadow

### ISSUE THREAD

**Issue by erichstark** [ionic-team/stencil#2309]
**Stencil version:**
```
 @stencil/core@1.11.2 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I am trying to import library inside web component and initialize it. When shadow is enabled, it is not possible.

**Expected behavior:**
Initialize library when using shadow: true

**Steps to reproduce:**
```
stencil generate tooltip
yarn add tippy.js
```

**Related code:**
```
import { Component, ComponentInterface, Host, h } from "@stencil/core";

import tippy from "tippy.js";

@Component({
  tag: "tooltip",
  styleUrl: "tooltip.scss",
  shadow: true
})
export class Tooltip implements ComponentInterface {
  componentDidRender() {
    tippy("#button", {
      content: "Tooltip"
    });
  }

  render() {
    return (
      <Host>
        <slot></slot>
        <button id="button" aria-describedby="tooltip">
          My button
        </button>
      </Host>
    );
  }
}
```

**Other information:**
I have this problem with every single library what I have tried.

**Comment by Westbrook** [comment]
You should try passing a [reference to the element](https://atomiks.github.io/tippyjs/v6/creation/#target-types) (see the `// Element` option) as tippy shouldn't be able to query through the shadow boundary (shadow DOM encapsulation and all):

```
componentDidRender() {
    tippy(this.shadowRoot.querySelector('#button'), {
      content: "Tooltip"
    });
  }
```

I'm not 100% on the Stencil APIs, but something similar to this should get you what you want.

**Comment by erichstark** [comment]
@Westbrook Of course, I forgot to use it that way. It works. 

But I have had similar problems with integration select2 into stencil component. Could it be problem because select2 is not a pure es2015 library?

**Comment by Westbrook** [comment]
Not sure if you're able to supply an element reference in that case. For more advanced UI, you might check out Ionic based alternatives here: https://ionicframework.com/docs/components

**Comment by erichstark** [comment]
I need that component for custom design system. But thanks anyway.

**Comment by kunal-ganglani-rise** [comment]
I got this working
`
import { Component, Prop, h, Element } from '@stencil/core';
import * as NavIcons from './nav-icons';
import tippy from 'tippy.js';
import 'tippy.js/dist/tippy.css';

@Component({
  tag: 'rcl-nav-list-item',
  styleUrl: 'nav-list-item.scss',
  shadow: true,
  assetsDirs: ['../../assets/platform'],
})
export class NavListItem {
  @Element() el: HTMLElement;

  @Prop() icon: string;

  @Prop() isActive: boolean;

  @Prop() imgTitle: string;

  componentDidRender() {
    const target = this.el.shadowRoot.querySelector('.imgContainer') as HTMLDivElement;
    // const template = this.el.shadowRoot.querySelector('#template') as HTMLDivElement;
    console.log(target);
    debugger;
    tippy(target, {
      content: 'Tooltip',
    });
  }
  render() {
    return (
      <div class="nav-list-item">
        {this.icon && this.icon !== '' ? (
          <div class="imgContainer">
            <img class={`${this.isActive ? 'active' : ''}`} alt={this.imgTitle} src={NavIcons[this.icon]}></img>
          </div>
        ) : null}
      </div>
    );
  }
}

`
