### ISSUE TITLE
App doesn't render since v1.10.0

### ISSUE THREAD

**Issue by sh-a-v** [ionic-team/stencil#2311]
**Stencil version:**

```
 @stencil/core@1.11.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

App doesn't render, root component is empty.

**Expected behavior:**

Render works well.

**Steps to reproduce:**

npm install @stencil/core@1.11.2

**Related code:**
No code changes since version 1.9.x

**Comment by sh-a-v** [comment]
app-root.tsx:
![image](https://user-images.githubusercontent.com/7159528/77587848-c046d100-6ef9-11ea-9a8f-80c5e2d2a6c0.png)

components.d.ts:
![image](https://user-images.githubusercontent.com/7159528/77587891-d8b6eb80-6ef9-11ea-8469-862148485ff7.png)

It looks like no component is found.
Build folder also doesn't contain component files.

![image](https://user-images.githubusercontent.com/7159528/77587738-91c8f600-6ef9-11ea-84a9-11a9f5066ce9.png)

**Comment by manucorporat** [comment]
can you share your tsconfig and stencil.config.ts files?

**Comment by sh-a-v** [comment]
> 
> 
> can you share your tsconfig and stencil.config.ts files?

tsconfig:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": false,
    "strictPropertyInitialization": false,
    "experimentalDecorators": true,
    "lib": ["dom", "es2017"],
    "moduleResolution": "node",
    "module": "esnext",
    "target": "es2017",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowJs": true,
    "noEmit": true,
    "strict": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "jsx": "react",
    "jsxFactory": "h",
    "baseUrl": "./",
    "paths": {
      "~/*": ["./src/*/index.ts", "./src/*"],
    }
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}
```

stencil.config.ts:
```
import { Config } from '@stencil/core'
import replace from '@rollup/plugin-replace'
import dotenv from 'dotenv'

dotenv.config({
  path: `.env.${process.argv.includes('--prod') ? 'prod' : 'dev'}`
})

export const config: Config = {
  outputTargets: [{
    type: 'www',
    dir: 'pwa',
    serviceWorker: null,
    copy: [
      { src: '../node_modules/tdweb/dist/**/*.worker.js', dest: '' },
      { src: '../node_modules/tdweb/dist/**/*.wasm', dest: '' },
      { src: '../node_modules/tdweb/dist/**/*.mem', dest: '' }
    ]
  }],
  plugins: [
    replace({
      values: process.env,
      delimiters: ['env.', ''],
      exclude: '**/node_modules'
    })
  ],
  devServer: {
    openBrowser: false
  }
}
```

**Comment by sh-a-v** [comment]
`"noEmit": true` breaks all. Maybe write this in the readme?

**Comment by mkay581** [comment]
@sh-a-v we're having this same issue even in latest Stencil versions. How are you able to use `noEmit`?

**Comment by sh-a-v** [comment]
@mkay581 I deleted this option from config.

**Comment by mkay581** [comment]
Yeah but shouldn't the library still work if it's set? 🤔
