### ISSUE TITLE
StencilJS 1.10, 1.11 loader does not compile to ES5

### ISSUE THREAD

**Issue by smzelek** [ionic-team/stencil#2315]
**Stencil version:**

```
 @stencil/core@1.11.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running an Angular 8 app that imports a StencilJS library via the `loader` output target, and properly configuring Angular 8 to compile to IE11 compatible code, StencilJS is an offending exception. The code for `defineCustomElements` fails to compile down to ES5, and therefore the app does not run on IE11, but instead outputs an error on startup:
```
SCRIPT1002: Syntax error.
main.js (299,13)
```
![image](https://user-images.githubusercontent.com/11831150/77651848-bfd32800-6f43-11ea-965f-d5592a33c74a.png)

**Expected behavior:**

This exact setup works when using StencilJS on version `1.9.2`, but does not work on `1.10` or `1.11`. 

**Steps to reproduce:**

You can reproduce this error in any Angular 8/9 repo, created fresh with the Angular CLI and with the minimal steps to run in IE11 followed.
* change tsconfig compile target to ES5
* add recommended polyfills in `polyfills.ts`
* update `browserslist` file

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by smzelek** [comment]
I would also like to note that this feature is broken on Stencil version `1.11.3-0` (at time of writing). I suspected it had to do with the "next" compiler.

However I found that the feature _does_ still work correctly when I use version `1.9.2` if I supply the "--next" flag and run `stencil build --next`.

**Comment by smzelek** [comment]
After running "stencil build" (any options) on `1.11.2`, the file path
`lib\dist\esm-es5\index-a468004f.js` has the following contents:

```
const NAMESPACE = 'web-component-pattern-lib';

let scopeId;
let contentRef;
let hostTagName;
let useNativeShadowDom = false;
let checkSlotFallbackVisibility = false;
let checkSlotRelocate = false;
let queueCongestion = 0;
let queuePending = false;
const win = typeof window !== 'undefined' ? window : {};
const CSS =  win.CSS ;
const doc = win.document || { head: {} };
const plt = {
    $flags$: 0,
    $resourcesUrl$: '',
    jmp: h => h(),
    raf: h => requestAnimationFrame(h),
    ael: (el, eventName, listener, opts) => el.addEventListener(eventName, listener, opts),
    rel: (el, eventName, listener, opts) => el.removeEventListener(eventName, listener, opts),
};
. . . .
// more below.
```

as you can see, this file contains arrow syntax which is NOT es5 compatible, despite being in the file path called es5.

**Comment by rjaguilar** [comment]
I have the same issue from from versions 1.10.2 -> 1.11.2+, 1.10.1 is the last known working version for IE11 for me.

**Comment by smzelek** [comment]
@rjaguilar I can confirm as well that it works in 1.10.1.

The es5 bundle at `lib\dist\esm-es5\index-8590b20f.js` @ compiler version 1.10.1 has:
```
var plt = {
    $flags$: 0,
    $resourcesUrl$: '',
    jmp: function (h) { return h(); },
    raf: function (h) { return requestAnimationFrame(h); },
    ael: function (el, eventName, listener, opts) { return el.addEventListener(eventName, listener, opts); },
    rel: function (el, eventName, listener, opts) { return el.removeEventListener(eventName, listener, opts); },
};
```

**Comment by smzelek** [comment]
@manucorporat I see that you closed this issue with a commit. I am not familiar with Stencil's versioning scheme. When do commits make it into a patch version?

**Comment by manucorporat** [comment]
Soon, expect it today or tomorrow :)

**Comment by rjaguilar** [comment]
@smzelek thanks for writing this bug ticket and verifying! @manucorporat thanks for fixing so fast!
