### ISSUE TITLE
<marker> attributes have changed and are incompatible with svg

### ISSUE THREAD

**Issue by yanfali** [ionic-team/stencil#2321]
**Stencil version:**

```
@stencil/core@1.11.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

```
      <div id="workarea">
        <svg class="default-height" width="100%">
          <defs>
            <marker
              id="arrow"
              marker-width="10"
              marker-height="10"
              ref-x="0"
              ref-y="3"
              orient="auto"
              marker-units="strokeWidth"
            >
              <path d="M0,0 L0,6 L9,3 z" fill="#f00" />
            </marker>
          </defs>
          <g transform="translate(0,0) scale(1)">
            <g class="stuff" />
          </g>
        </svg>
      </div>
```
Is no longer compatible with the types expected by SVG or @types/react.  It used to accept

```
              markerWidth="10"
              markerHeight="10"
```
This is now considered an error because of the type definitions embedded within stencil itself.
If I hand edit the elements using browser and restore this, then the correct svg behavior happens.

**Expected behavior:**

It should render an arrow correctly whenever I use the definition.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

It would be great if you could revert the behavior. Otherwise I may just go back to 1.8 where this wasn't an issue. Thanks again for a great platform.

**Comment by manucorporat** [comment]
Fixes in @stencil/core 1.11.3!
