### ISSUE TITLE
Event Emission Doesn't Work Between Router-using Component and Children

### ISSUE THREAD

**Issue by harrysolovay** [ionic-team/stencil#2329]
**Stencil version:** 1.12.1
**Stencil Router Version**: 1.0.1

**I'm submitting a:**

[x] bug report

**Current behavior:**

I'm attempting to trigger a custom event `routeDidRender` from the component which uses `stencil-router`. The render method:

```tsx
render() {
  return (
    <stencil-router>
      {/* https://github.com/ionic-team/stencil-router/issues/104 */}
      <stencil-route-switch scrollTopOffset={1} ref={this.setRef}>
        {routes.map((route) => (
          <stencil-route
            key={route}
            url={route}
            component="app-page"
            exact={true}
          />
        ))}
      </stencil-route-switch>
    </stencil-router>
  );
}
```

Then there's the `setRef` method, which––upon the router switch being rendered––takes in the switch ref and registers a mutation observer, which triggers a custom event `@Event() routeDidRender: EventEmitter;`:

```ts
setRef = (ref: HTMLElement | undefined) => {
  if (Build.isBrowser) {
    if (this.observer) {
      this.observer.disconnect();
    }

    if (ref) {
      this.observer = new MutationObserver(
        () => this.routeDidRender.emit(),
      );

      this.observer.observe(ref, {
        childList: true,
        attributes: true,
        subtree: false,
      });
    }
  }
};
```

> The mutation observer is properly triggering the fn passed to it. It's firing off properly, but the event isn't captured elsewhere.

Within the `app-page` component, which gets rendered by the various routes, we listen for the event:

```ts
@Listen("routeDidRender")
routeRenderHandler(_event: CustomEvent) {
  console.log("route did render");
}
```

**Expected behavior:**

I'd expect the `routeRenderHandler` to be triggered upon changes to route (mutated `display` styles). This is not the case.

Is it possible that event transmission across router boundary is broken? Any advice would be greatly appreciated. Thank you!

**Comment by alex-ketch** [comment]
@harrysolovay not sure, but have you tried changing the Listen `target` option?
https://stenciljs.com/docs/events#target

**Comment by harrysolovay** [comment]
Yes, I did. I've since moved away from this approach. Given the lack of a repro, closing this out.
