### ISSUE TITLE
Add flag to set the path of the tsconfig.json file

### ISSUE THREAD

**Issue by jdnichollsc** [ionic-team/stencil#2333]
**Stencil version:**
```
 @stencil/core@1.12.2
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request

**Current behavior:**
We don't have a option to have multiple **tsconfig.json** files for multiple environments

**Expected behavior:**
Having a flag to set the **tsconfig.json** file for the **build** command, like the **--config** flag https://stenciljs.com/docs/cli
With this option we can exclude files from build command having another tsconfig, it's useful when you have components to debug from the stencil project itself. E.g with a **tsconfig** for **build**:
```json
  "exclude": [
    "node_modules",
    "src/pages/**",
    "src/assets/**"
  ]
```

Thanks in advance! <3

**Comment by AlexSapoznikov** [comment]
This is really needed!

**Comment by simonhaenisch** [comment]
This is already possible, by using multiple `stencil.config.ts`.

```ts
// stencil.config.ts

export const config: Config {
  // ...
  tsconfig: 'tsconfig.json',
}
```

```ts
// stencil.config.prod.ts

import { config } from './stencil.config'

export const config: Config = {
  ...config,
  tsconfig: 'tsconfig.prod.json',
}
```

```js
// pacakge.json

{
  // ...
  "scripts": {
    "build": "stencil build",
    "build.prod": "stencil build --config stencil.config.prod.ts"
  }
}
```
