### ISSUE TITLE
I am getting a deprecated dev-warning from stencil/core

### ISSUE THREAD

**Issue by stanley85** [ionic-team/stencil#2341]
**Stencil version:**
```
 @stencil/core@1.12.3
```

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I am getting a deprecated dev-warning from stencil/core:
*element.forceUpdate() is deprecated, use the "forceUpdate" function from "@stencil/core" instead*

**Comment by Francois-Belanger** [comment]
Hi, if using Ionic, update to latest release.
