### ISSUE TITLE
Console logging newSpecPage root causes error

### ISSUE THREAD

**Issue by mkay581** [ionic-team/stencil#2344]
**Stencil version:**

```
 @stencil/core@1.12.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request 

It appears that tests fail with a `Cannot convert a Symbol value to a number` Type error when console logging the page's root (see code snippet below)

**Current behavior:**
Test fails with following error:

```bash
TypeError: Cannot convert a Symbol value to a number
        at isNaN (<anonymous>)

      at Object.get (node_modules/@stencil/core/mock-doc/index.js:15:10)

```

**Expected behavior:**
Test passes

**Steps to reproduce:**

**Related code:**

```tsx
import { newSpecPage } from '@stencil/core/testing';
import { MyCmp } from './my-cmp';

it('does not fail', async () => {
  const page = await newSpecPage({
    components: [MyCmp],
    html: '<my-cmp></my-cmp>',
  });
  console.log(page.root); // TypeError: Cannot convert a Symbol value to a number
  expect(true).toBe(true);
});
```

**Other information:**

**Comment by mkay581** [comment]
FWIW, this seems to happen even when running a component that console logs `currentTarget` from a mouse event after a click 

```tsx
// my-cmp.tsx
import { h, Component } from '@stencil/core';

@Component({
  tag: 'my-cmp',
})
export class MyCmp {
  private mouseClick = (e: MouseEvent): void => {
    console.log(e.currentTarget); // error
  };
  render() {
    return <div onClick={this.mouseClick}></div>;
  }
}
```

```ts
// my-cmp.spec.ts
import { newSpecPage } from '@stencil/core/testing';
import { MyCmp } from './my-cmp';

describe('MyCmp', () => {
  it('processes child clicks', async () => {
    const page = await newSpecPage({
      components: [MyCmp],
      html: '<my-cmp></my-cmp>',
    });
    const div = page.root.querySelector('div');
    div.click();
    expect(div).toBeTruthy();
  });
});

```

Not sure if this is isolated to just clicks or with components that have console logs in general

**Comment by Kira2** [comment]
Hi,

I do not know if it Can help, but I had the same error just by doing a `console.log` (no click event was involved). I could solve it by using `toString()`

Maybe you can try to use `console.log(e.currentTarget.toString());` instead into your code to see if it allow you to log what's into `currentTarget`

**Comment by manucorporat** [comment]
Can you provide a full repo that reproduces it?

**Comment by mkay581** [comment]
@manucorporat was that a question for @Kira2 or me? I've provided the full set of code in the examples above.

**Comment by manucorporat** [comment]
<img width="731" alt="Screenshot 2020-05-06 at 20 37 26" src="https://user-images.githubusercontent.com/127379/81215283-67c72100-8fd9-11ea-9b0f-1bf771bbcfb0.png">
I can't reproduce with the provided code, most of the time there is another thing, that the developer submitting thee issue is not considering, a full repo solves that problem.
