### ISSUE TITLE
Stencil CLI component generation config

### ISSUE THREAD

**Issue by nathanb21** [ionic-team/stencil#2348]
**Stencil version:**
```
@stencil/core@1.12.1
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
`npx stencil generate app-component` provides toggles for a `.css`, `.spec.tsx`, `.e2e.ts` options.

As we are using @stencil/sass we manually rename the `.css` file to `.scss`.

I also use `scoped` instead of `shadow` so also change these both in the `.tsx` file.

**Expected behavior:**
At project generation, and within a config, the ability to specify the type of CSS files that are generated and other configurable options that could be used (custom templates?).

**Comment by JasonGrant** [comment]
I would love to not have to change css to scss every time I create a new component

**Comment by manucorporat** [comment]
We want to keep it simple, we encourage developers to use .css when possible, not plans for the moment to add other format options in the time being. 
That would involve a lot new moving parts, new issues, more things to support out of our control.
