### ISSUE TITLE
A way to have dynamic Meta tags for each pre-rendered page

### ISSUE THREAD

**Issue by saiy2k** [ionic-team/stencil#2350]
**I'm submitting a:**

[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
All pre-rendered pages, have common meta description, keyword tags and even the Page titles.

**Expected behavior:**
A way to define meta tags for each page. And the page should be pre-rendered with those values.

**Other information:**
Like how Angular has this `Meta` class (https://angular.io/api/platform-browser/Meta)

**Comment by adamdbradley** [comment]
As of `1.13.0-3` you can use the `prerender.config.ts` file that has many of the options to manipulate the document before it's serialized: https://github.com/ionic-team/stencil/blob/0d3ed7d4cb7983f1e949d3a9d31c7b5ecfe58f1a/src/declarations/stencil-public-compiler.ts#L498-L528

In this case you can use `afterHydrate(doc) {..}` to update the dom however you'd like. Further, you can also update the document and its meta tags within your app and that'd apply during prerendering too. Hope that helps, thanks
