### ISSUE TITLE
Item not properly bound to data in AngularJS when using ng-show

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2351]
**Stencil version:**

```
 @stencil/core@1.12.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
With the following, `outer-component` is a Stencil built component that is not using shadow DOM:

```html
      <div ng-if="todoList.show === true">
        <outter-component name='test name'>
          <h2>Hi there!</h2>
          <div>{{todoList.description}}</div>
        </outter-component>
      </div>
```

When rendered, the slotted `div` reads on the page as `{{todoList.description}}` rather than as the data bound value.

When using shadow DOM, however, this works.

**Expected behavior:**
The inner text of the `div` should be whatever the value of todoList.description is.

**Steps to reproduce:**
See this repo: https://github.com/pmenichelli/angularjs-interpolation-in-slots

**Related code:**

https://github.com/pmenichelli/angularjs-interpolation-in-slots/blob/master/src/index.html#L33-L38

https://github.com/pmenichelli/angularjs-interpolation-in-slots/blob/master/src/components/outter-component/outter-component.tsx

If you put a `shadow: true` here it works (at least in Firefox, I have not tried it on an insane browser like IE or Edge): https://github.com/pmenichelli/angularjs-interpolation-in-slots/blob/master/src/components/outter-component/outter-component.tsx#L4

**Comment by rwaskiewicz** [comment]
Hello 👋 

I'm believe this was discussed with a previous iteration of the Stencil team (via Slack, searched this issue's URL). I'm not sure what the _exact_ resolution was for this (or even if it was satisfactory). At this time, since we don't support AngularJS, I'd be inclined to closed this issue out.  LMK if you have any questions (feel free to DM me or shoot a msg in the Stencil channel). Thanks!
