### ISSUE TITLE
custom-elements.json from --docs-vscode is faulty

### ISSUE THREAD

**Issue by runarberg** [ionic-team/stencil#2353]
**Stencil version:**

```
 @stencil/core@1.8.8
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The generated `custom-elements.json` has the wrong structure for the `description` field:

```json
{
  "tags": [
    {
      "name": "my-component",
      "description": {
        "kind": "markdown",
        "value": "My component’s doc comment"
      },
      "...": ""
    },
    "...",
  ]
}
```

This has implications when generating content for [storybooks](https://github.com/storybookjs/storybook/tree/next/addons/docs/web-components), where storybook generation fails with the following error:

```
markdown-to-jsx: the first argument must be a string
```

It is simply saying we got an object in the `description` field where we expected a string.

**Expected behavior:**

The description field should be a simple string:

```json
{
  "tags": [
    {
      "name": "my-component",
      "description":  "My component’s doc comment",
      "...": "",
    }
    "...",
  ]
}
```

**Steps to reproduce:**

**Related code:**

Add the following to the `outputTargets` of  `stencil.config.ts`:

```ts
import { Config } from '@stencil/core';

export const config: Config = {
  // ...
  outputTargets: [
    // ...
    {
      type: 'docs-vscode',
      file: 'custom-elements.json'
    },
  ]
};
```

**Other information:**

**Note**: I am not a user of the vs-code editor, so the structure might be correct for it. However this not according to the [custom-elements.json](https://github.com/webcomponents/custom-elements-json) draft of the standard. I suggest we create a new output target (say `docs-custom-elements`) where this is fixed as well as the new fields added in the draft version 1.2 of the spec

**Comment by runarberg** [comment]
Related to #2048

**Comment by manucorporat** [comment]
It follows correctly the vscode format spec: https://github.com/microsoft/vscode-html-languageservice/blob/88d2e5ce4a998c63f2aaa95788988a6a84151f40/docs/customData.schema.json#L28-L42

**Comment by runarberg** [comment]
I see. I guess the fault is at storybook then for instructing the use of this output target.

**Comment by runarberg** [comment]
Closing since this is not a bug in stencil
