### ISSUE TITLE
Add possibility to document CSS shadow parts

### ISSUE THREAD

**Issue by runarberg** [ionic-team/stencil#2355]
**Stencil version:**

```
 @stencil/core@1.8.8
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Stencil does not have a way to document which [shadow parts](https://www.w3.org/TR/css-shadow-parts-1/) are exported by the component.

E.g. a consuming developer cannot look at the generated documentation to know whether the following will work:

```css
my-custom-element::part(some-exported-part) {
  /* Custom styles go here */
}
```

They will be forced to look at the source, or ask the author.

**Expected behavior:**

Add a possibility to mark and document which shadow parts are available for CSS styling.

This is already cleverly done for [CSS custom-properties](https://drafts.csswg.org/css-variables/#defining-variables) using the `@prop` pragma in the stylesheet. Perhaps something similar can be done for shadow parts:

```tsx
/**
  * My component lorem ipsum
  *
  * @part some-exported-part - The part which consumers can style
  */
@Component({
  // ...
})
export class MyComponent {
  // ...
}
```

**Steps to reproduce:**

none

**Related code:**

none

**Other information:**

* [mdn doc for `::part`](https://developer.mozilla.org/en-US/docs/Web/CSS/::part)
* [mdn doc for the `part` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/part)
* [shadow parts spec](https://www.w3.org/TR/css-shadow-parts-1/)

**Comment by manucorporat** [comment]
This feature is already implemented in the latest release of stencil!
