### ISSUE TITLE
Feature Request: Prop default value & validation & required

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/stencil#236]
Prop should have the same propeties that props in vue has
type (already have)
required
default (should be callback)
validation

**Comment by Hotell** [comment]
All of this is already within stencil :)

### default values

```tsx
@Component({ tag: 'x-greet' })
class Hello {
  @Prop() who = 'World'
  render(){  return <div>Hello  {this.who} !</div>
}
```

```html
<x-greet></x-greet>
```

will render -> `<x-greet><div>Hello World !</div></x-greet>`

### required / validations

```tsx
@Component({ tag: 'x-greet' })
class Hello {
  @Prop() who: string
  @PropWillChange('who')
  validateWho(newValue: string) {
    const isBlank = typeof newValue == null
    const atLeast2chars = typeof newValue === 'string' && newValue.length >= 2
    if (isBlank){ throw new Error('who: required') } 
    if ( !atLeast2chars ) { throw new Error('who: atLeast2chars')  }
  }
}
```

also I would definitely turn off those validations only in Development

**Comment by adamdbradley** [comment]
Right, thanks @Hotell!

**Comment by adamdbradley** [comment]
Reminds me to add this to the docs.

**Comment by leonheess** [comment]
Docs: https://stenciljs.com/docs/reactive-data#watch-decorator
