### ISSUE TITLE
[BUG] require 'shams' is not defined

### ISSUE THREAD

**Issue by guidoknoll** [ionic-team/stencil#2360]
**Stencil version:**

```
 @stencil/core@1.12.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When updating from 1.8.11 to 1.12.3 the following error is thrown:
`ReferenceError: require is not defined`.

It's thrown in this line: `var hasSymbolSham = require('./shams');`.

Because of this the complete application crashes.

**Expected behavior:**

The error is not thrown. In the 1.8.11 build the shams file doesn't get required.

**Steps to reproduce:**

I don't really know why this gets required, but there was already a similar issue which is now closed due to inactivity: #2136.

**Other information:**

Error stack:
![image](https://user-images.githubusercontent.com/23310365/78886306-3f8de600-7a5e-11ea-92e4-75d45819ac1c.png)

**Comment by manucorporat** [comment]
Please provide some source code to reproduce the issue, in addition, you can't use `require` in the source code isnide the `src` folder. Only ESM import.

**Comment by guidoknoll** [comment]
The use of `require` in the dist folder surprised me too. I didn't use the require statement anywhere in the src folder. 
Sadly i can't share the source and i couldn't reproduce a minimal example yet. 

Any ideas on why this happens anyway?

**Comment by guidoknoll** [comment]
So for some reason this issue suddenly disappeared for me. I'll reopen this if i encounter the issue again.
