### ISSUE TITLE
Upgrading from Stencil 1.9.2 to any newer version breaks docs-vscode url generation

### ISSUE THREAD

**Issue by viljamis** [ionic-team/stencil#2362]
**Stencil version:**
```
 @stencil/core@1.12.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
After upgrading from Stencil 1.9.2 to 1.12.3 `docs-vscode` output target now incorrectly generates the urls to source code. It basically adds `./` in the url in a location where it doesn’t belong. Example:

**Previously, generated url looked like:**
`"url": "https://xxx?path=/packages/components/src/components/duet-alert/duet-alert.tsx"`

**With the new version the generated url is broken:**
`"url": "https://xxx?path=/packages/components/./src/components/duet-alert/duet-alert.tsx"`

**Expected behavior:**

`docs-vscode`output target should not add `./` in the middle of the url.

**Steps to reproduce:**

We’re configured the output target like this:

```
outputTargets: [{
      type: "docs-vscode",
      file: "lib/html.html-data.json",
      sourceCodeBaseUrl: "https://xxx?path=/packages/components/"
}]
```

**Comment by manucorporat** [comment]
A PR would be welcomed!

**Comment by viljamis** [comment]
@manucorporat sure, we can look into that next week!

**Comment by viljamis** [comment]
@manucorporat Nick from our team created a PR for this, see above :)
