### ISSUE TITLE
Choosing stencil over others

### ISSUE THREAD

**Issue by johncooper1** [ionic-team/stencil#2364]
I am in the process of evaluating frameworks for creating web components and require some guidance on choosing stencil over others available in the market. 

I also see vue-custom-element and also with Angular 9 you can too as an option for creating web-components. Vue and Angular are large community and there is large documentation and support towards it. 
https://github.com/karol-f/vue-custom-element

Can someone help me in understanding what makes stencil better compared to vue-custom-element or Angular 9 Custom Element in specific? @adamdbradley

**Comment by bitflower** [comment]
I think you will way better feedback on the official Slack: https://join.slack.com/t/stencil-worldwide/shared_invite/zt-d1hmuo91-PX4Qu5Mre_Vz2m0eH3NGlA
