### ISSUE TITLE
Prerendered Components Missing Props and Children

### ISSUE THREAD

**Issue by harrysolovay** [ionic-team/stencil#2365]
**Stencil version:**
```
 @stencil/core@1.12.3
```

**I'm submitting a:**

[x] bug report

**Current behavior:**

When prerendering, the scraped HTML does not reflect the actual structure & props of the first render.

For instance, my `docs-universal-nav` component renders out as the following:

```
<docs-universal-nav
  brand-icon="/assets/logo-light.svg"
  brand-icon-blend="/assets/logo-dark.svg" c-id=5.1.0.1
></docs-universal-nav>
```

This is inaccurate. At a quick glance, this is the TSX behind this component:

```tsx
<amplify-container
  class={{
    "background-color-orange-hv":
      this.blend === undefined || !this.blend,
  }}
>
  <div
    class={{
      [universalNavContentStyle]: true,
      blend: this.blend !== undefined && this.blend,
    }}
  >
    <stencil-route-link
      url="/"
      anchorTitle="Amplify Docs"
      class={brandStyle}
    >
      <img src={this.blend ? this.brandIconBlend : this.brandIcon} />
      <span>{this.heading}</span>
      <sup>NEW</sup>
    </stencil-route-link>

    <div class={linksStyle}>
      <amplify-external-link
        redirect
        href="https://amplify.aws/community/"
        anchorTitle="Amplify Community"
      >
        <span>Community</span>
      </amplify-external-link>
      <amplify-external-link
        href="https://aws.amazon.com/amplify/"
        anchorTitle="AWS Amplify Homepage"
        graphic={this.blend ? "black" : "white"}
      >
        <span>
          About<span class={hideAboutLinkStyle}>{` Amplify`}</span>
        </span>
      </amplify-external-link>
    </div>
  </div>
</amplify-container>
```

**Expected behavior:**

To get static HTML that reflects the actual state of the page.

---

Something to note: the data used to render the page is fetched in `componentWillLoad` (which returns a promise). This effectively pauses the render.If we––within the render markup––create a `<div>{JSON.stringify(this.pageData)}</div>`, it prerenders the correct data. Hence, this is not an issue relating to lifecycle race conditions, nor conditional rendering flows run amuck... the data is there.

This bug manifests elsewhere. One such instance, is in `shadow: false` components with slot use. It seems there are many cases where prerendered components don't contain the correct props or children.

**Potentially-related Issues:**
* https://github.com/ionic-team/stencil/issues/1854
* https://github.com/ionic-team/stencil/issues/2301
* https://github.com/ionic-team/stencil/issues/2226

**Comment by brene** [comment]
+1

**Comment by christian-bromann** [comment]
Hi @harrysolovay  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
