### ISSUE TITLE
Ionic Menu no longer works as in 1.9.1

### ISSUE THREAD

**Issue by stanley85** [ionic-team/stencil#2368]
**Stencil version:**
```
 @stencil/core@1.12.3
```

**I'm submitting a:**
[X ] bug report

**Current behavior:**
When upgrading the stencil version to the latest 1.12.3 build from 1.9.1 the ion-menu no longer finds its content element to listen on drag events. During development the problem does not accur, but when releasing the code to web with the prod build the ion-menu no longer is rendered and the console states: "Menu: must have a "content" element to listen for drag events on."

**Expected behavior:**
The Menu renders as it did with version 1.9.1

**Comment by bitflower** [comment]
I can't upgrade due to this: https://github.com/ionic-team/stencil/issues/2349

But would love to test this.

**Comment by rwaskiewicz** [comment]
👋 

I apologize it took so long for someone on the Stencil team to acknowledge this ticket.  if someone would be able to create a minimal reproduction case with the latest version of Stencil + Ionic Framework, the team would be happy to take a look!
