### ISSUE TITLE
`getRootNode` Polyfill Not Applied when `customElements.min` Polyfill is Applied Separately

### ISSUE THREAD

**Issue by sledsworth** [ionic-team/stencil#2369]
**Stencil version:**
```
 @stencil/core@1.12.3
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

An application trying to consume my stencil components ran into an issue where `getRootNode` isn't being polyfilled in Edge.

**Expected behavior:**
`getRootNode` should be polyfilled in Edge if not available on `Element`.

**Steps to reproduce:**
Reproduction may be difficult, my suspicion is that the Angular Elements components that are loaded before mine are using [customElements.min](https://github.com/webcomponents/polyfills/tree/master/packages/custom-elements) and the polyfill check stencil is making doesn't check that `getRootNode` is filled, so the polyfill isn't applied when it ought to be.

**Other information:**
I plan on opening a PR to address this issue.

**Comment by OliverLeitner** [comment]
this probably relates to my error in edge as well:

[object Error]: {description: "Object doesn't support property or method 'getRootNode'", message: "Object doesn't support property or method 'getRootNode'", number: -2146827850, stack: "TypeError: Object doesn't support property or method 'getRootNode' at attachStyles (http://stencil.localnet:3131/build/index-ca8ee563.js:282:5) at updateComponent (http://stencil.localnet:3131/build/index-ca8ee563.js:1323:9) at update (http://stencil.localnet:3131/build/index-ca8ee563.js:1284:26) at consumeTimeout (http://stencil.localnet:3131/build/index-ca8ee563.js:2729:13) at flush (http://stencil.localnet:3131/build/index-ca8ee563.js:2753:9)"}
description: "Object doesn't support property or method 'getRootNode'"
message: "Object doesn't support property or method 'getRootNode'"
number: -2146827850
stack: "TypeError: Object doesn't support property or method 'getRootNode' at attachStyles (http://stencil.localnet:3131/build/index-ca8ee563.js:282:5) at updateComponent (http://stencil.localnet:3131/build/index-ca8ee563.js:1323:9) at update (http://stencil.localnet:3131/build/index-ca8ee563.js:1284:26) at consumeTimeout (http://stencil.localnet:3131/build/index-ca8ee563.js:2729:13) at flush (http://stencil.localnet:3131/build/index-ca8ee563.js:2753:9)"

__proto__: Error
