### ISSUE TITLE
Feature request: Get all props from a component (Utility)

### ISSUE THREAD

**Issue by jdnichollsc** [ionic-team/stencil#2372]
**Stencil version:**

```
@stencil/core@1.8.1
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
We don't have an option to get all props as an object, without state properties.

**Expected behavior:**
Having an utility function to get all props from a component easily, it would be very useful when you have the same props from multiple components and you want to extract these props for common logic. 

**Related code:**

```tsx
// Common logic
export const loadComponent = (props) => {
  doSomething(props)
}

export class MyComponent1 {
  @Prop() prop1: string
  @Prop() prop2: string
  @Prop() propN: string

  @State() property1: string;
  @State() property2: string;

  componentWillLoad() {
    // Get all props of the component => { prop1, prop2, propN }
    loadComponent(this.props)
  }
}

export class MyComponent2 {
  @Prop() prop1: string
  @Prop() prop2: string
  @Prop() propN: string

  @State() property1: string;
  @State() property2: string;

  componentWillLoad() {
    // Get all props of the component => { prop1, prop2, propN }
    loadComponent(this.props)
  }
}
```

Thanks in advance! 👍

**Comment by eriklharper** [comment]
Sounds like what you need is a Typescript `interface` that would look something like this:

```
export interface MyComponent1Props {
    prop1: string;
    prop2: string;
    propN: string;
}
```
You can also do the same for state if need be too, and if you export the interface as shown you'll be able to share it across any component that shares that prop interface.

**Comment by jdnichollsc** [comment]
But you need to paste from both components all same decorators, pasting the same code in every component, it's very complicated for reusability

**Comment by jdnichollsc** [comment]
Also, you can't use destructuring of ES6 with this:
```
const props = {
  ...this
};
// props.prop1 => undefined
```
All props are `undefined` always

**Comment by eriklharper** [comment]
I guess you could always just make your own decorator that provides this higher level abstraction where you pass your props object to the function that then returns your stencil component.

**Comment by jdnichollsc** [comment]
Do you have any example to do that? :)

**Comment by jdnichollsc** [comment]
It would be very useful because **JSON.stringify(this)** returns an empty object => "{}", it's used when you want to clone an object

**Comment by manucorporat** [comment]
While I see how this could be useful, we try very hard to keep stencil as small as possible from a runtime and API point of view, i am afraid of adding new apis to cover certain use cases that can be solved in different ways. In stencil we try to limit feature in order to keep coupling very low beetweeen components, which turns out to be a good thing when the collection scales.

I will close this, since it's very unlikely we add this feature.

**Comment by jdnichollsc** [comment]
Hello @manucorporat, I understand 🙂but can you give me an example to scale when you have multiples components with the same props and you want to apply the same logic, what's the right way to get the value of all props?
In my tests, if you try to clone the current context, using Object.assign or ES6 spread operator, all props are **undefined**. It's complicated because you can't extend that data in another objects dynamically. For example, in React class components we have the option to get props via `this.props`.

Gracias por tu colaboración 👍

**Comment by eriklharper** [comment]
@jdnichollsc have you considered doing something like this?
```
export class MyComponent1 {
  props = {
    @Prop() prop1: string
    @Prop() prop2: string
    @Prop() propN: string
  };
}

export class MyComponent2 {
  props = MyComponent.props;

  componentWillLoad() {
    // Get all props of the component => { prop1, prop2, propN }
    loadComponent(this.props)
  }
}
```

**Comment by jdnichollsc** [comment]
@eriklharper that's very strange, is that working for you?

**Comment by eriklharper** [comment]
I haven't tried this in real code, it was just a thought I had as I read your latest response.  The reason I thought of this is because this is pretty much how React handles props and state, it just defines class members called `props` and `state` and just uses those names internally to refer to them, so for a web component, you could do the same thing even though Stencil doesn't use that same convention for storing props and state.  At the end of the day, it's just properties on a class, so you're really free to structure it anyway you want for your particular needs.

**Comment by eriklharper** [comment]
I've never come across a real world use case where I needed two components to share the exact same prop interface before, but I have come across the case where I wanted to reuse a `propType` definition in one React component in another React component, so I would do something like:

```
export class ReactComponent1 extends React.Component {
  propTypes = {
    sharedPropType: string,
    ...
  }
};
class ReactComponent2 extends React.Component {
  propTypes = {
    name: string,
    sharedPropType: ReactComponent1.propTypes.sharedPropType
  };
}
```

**Comment by jdnichollsc** [comment]
Yeah, but about decorators that's not supported as far as I know

**Comment by eriklharper** [comment]
Yeah, I suppose that's the trade-off to using Stencil's decorators is that you are kinda nailed down to only specifying shallow own properties on the class.  Bummer.  Another option you could explore is creating a factory function that takes in a prop interface (in the form of a typescript interface defining the prop types) and have that factory function return a new ES6 class with all the Stencil-decorated props on it, and then you could programmatically add the specific elements onto the derived class using `FactoryCreatedClass.newProperty` syntax.

**Comment by jdnichollsc** [comment]
ok so it looks like we need to create a utility function to do that :)
@manucorporat On the other hand, getting **undefined** values using **JSON.stringify** is not an issue? :)
