### ISSUE TITLE
Errors using Stencil built components in NextJS project

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2374]
**Stencil version:**

```
 @stencil/core@1.12.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

While setting up test-projects with usage of generated react components in NextJS, we encountered two issues which should be resolved.

1. While building the application, Stencils own bootstrapLazy is mocking document and document.head when it´s not available with an empty object. This causes console errors, because functions are still called on them.
Automatically optimizing pages .(node:14624) UnhandledPromiseRejectionWarning: TypeError: head.querySelector is not a function
at Object.bootstrapLazy
The Application still runs though.
2. The 'isCoveredByReact' function used by 'attachEventProps' is accessing 'document' without checking if it´s available by passing’s it as default parameter.

**Expected behavior:**
No errors thrown.

**Related code:**

Sample projects are pending from the user

**Comment by juanmiguelbesada** [comment]
The second part is due react-output-target. Issue and PR here https://github.com/ionic-team/stencil-ds-plugins/issues/39

**Comment by adamdbradley** [comment]
PR merged, thanks!
