### ISSUE TITLE
All changes not available in componentWillUpdate

### ISSUE THREAD

**Issue by jgroth** [ionic-team/stencil#2378]
**Stencil version:**

```
 @stencil/core@1.12.4
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If multiple props are changed on a component, only one of the props have changed to the new value when `componentWillUpdate` is called, making calculations based on all the props impossible

**Expected behavior:**
When `componentWillUpdate` is called, all props on the component should have the new values

**Steps to reproduce:**

Working example available in this repo
https://github.com/jgroth/stencil-bug

**Comment by romanroe** [comment]
I can confirm this bug. To be honest, I was quite surprised to see this in version 1.x 😫

**Comment by manucorporat** [comment]
It should be fixed in https://github.com/ionic-team/stencil/commit/8302fed01b13b18436dc1a8d6bde231643f8f448

**Comment by romanroe** [comment]
@manucorporat Great to hear! Thanks a lot!

**Comment by adrianschmidt** [comment]
> It should be fixed in [8302fed](https://github.com/ionic-team/stencil/commit/8302fed01b13b18436dc1a8d6bde231643f8f448)

…which is in v1.13.0-3, so should be in release 1.13.0 once that's available. For anyone who comes after me, so they don't also have to go looking 😊
