### ISSUE TITLE
consider additional folders/files while building

### ISSUE THREAD

**Issue by gparida1989** [ionic-team/stencil#2379]
Hi,

how to including extra html or image files .
Capture
![Capture](https://user-images.githubusercontent.com/44637258/79645135-0aeefc80-81cb-11ea-9f3d-100e2dcc1ce3.JPG)

I want to include Assets folder in the root lavel and one html file per component folder to be considered while building to WWW or dist folder.

**Comment by manucorporat** [comment]
Move assets inside the src folder
