### ISSUE TITLE
Strong typing for components

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#238]
**Stencil version:** 

```
@stencil/core@0.0.6-13
```

**I'm submitting a ...**
[x] feature request

**Current behavior:**
It is not possible to enforce strong typing for component code.

**Expected behavior:**
There should be a type safe way to utilize Stencil components.

**Related code:**

```
// my-name.tsx
// Modified from stencil-app-starter
@Component({
  tag: 'my-name',
  styleUrl: 'my-name.scss'
})
export class MyName {

  @Prop() first: string;

  @Prop() last: string;

  @Prop() color: string;

  @Prop() id: number;

  getFullName(): string {
    return this.first + ' ' + this.last;
  }

  @Method()
  private getFullName2(): string {
    return this.first + ' ' + this.last;
  }

  @Method()
  public getFullName3(first: string, last: string): string {
    return first + ' ' + last;
  }

  render() {
    return (
      <div>
        Hello, my name is {this.getFullName2()}
      </div>
    );
  }
}

```

**Other information:**

- If you use `querySelector` to get an instance of a component then it is desirable to use strong typing when working with that component.  If you cast to `MyName` then it includes members that are not actually available (`@State`, properties without `@Prop`, methods without `@Method`, etc.).  What you actually get is an extension of HTMLElement with additional members driven by the decorators that map back to the class.  The generated `HTMLMyNameElement` interface in `components.d.ts` is close because it combines `MyName` and `HTMLElement` but still includes members in `MyName` that may not exist (e.g. methods without `@Method` decorator).
- Stencil members.  The MyName class gets extended with additional Stencil members including mode, color, __el, __values.  Does this cause any conflicts if the component is attempting to implement properties with the same name?  For example, `mode` might be meaningful in a component but different from the Stencil meaning (and a different data type). 
- HTMLElement members.  The `my-name` class extends HTMLElement and includes many common property names (id, children, hidden, etc.).  Does this cause any conflicts if the names overlap with the property names used in the component?  In the above code sample, the `HTMLMyNameElement` interface generated in `components.d.ts` has a TypeScript error (because the id properties have different types) but does not result in a build error.
- `@Method()` decorator - should public / private drive exposing methods vs. decorator?  It seems like if you are declaring a method as public it means that it supports external usage of the method and if it is private then it means it shouldn't be called from outside.  When would something be public but not exposed to outside callers?  If a method is private should it be able to be called?

**Comment by jthoms1** [comment]
- We are looking for a way to hide the methods,  Not sure what the best solution is.  I had assumed that `/** @internal **/` would work but apparently it does not.  If you are using query selector the methods actually do exist, just not something that you want to expose for usage.

- The stencil members are unavoidable.  These are reserved names that we use internally on each html element.  We might find a better way of naming these so that it is apparent they are reserved other than 'color' or 'mode'.

- Your components will actually extend HTMLElements in the browser so this is expected behavior. But this is a good point that I will need to research.

- I would say that all methods that do not contain the `@Method()` should be private

Good points, we wanted types to be exposed as a starting point and I think we will need to do some work to ensure these will work as expected.

**Comment by cjorasch** [comment]
Thanks for the feedback.  Some follow up comments below.

> We are looking for a way to hide the methods, Not sure what the best solution is. I had assumed that /** @internal **/ would work but apparently it does not. If you are using query selector the methods actually do exist, just not something that you want to expose for usage.

`querySelector` returns an instance of the class that extends `HTMLElement` rather than an instance of `MyName`.  This class includes proxies to `MyName` for members marked with `@Prop()` or `@Method()`.  The `MyName` instance is in `el.$instance`.  If you use `el as MyName` then it will imply members that do not necessarily exist.  There does not seem to be any interface you can use that describes this generated class instance.

> The stencil members are unavoidable. These are reserved names that we use internally on each html element. We might find a better way of naming these so that it is apparent they are reserved other than 'color' or 'mode'.

Some possible ideas:
- Use a naming prefix like ion to help isolate from developer properties.  `color` and `mode` are pretty common names and it seems like you might end up adding more later.
- Have a different base class that has these properties built in.  It is surprising to not be able to use those names but also not be able to access those properties.  If a method tries to use `this.color` it will result in a TypeScript error since they do not exist until later.
- If there are reserved names then the compiler should flag any use of those names as an error.  Otherwise it is easy to use them for property names and not realize they will cause problems.

> Your components will actually extend HTMLElements in the browser so this is expected behavior. But this is a good point that I will need to research.

One possible alternative is to access the component class instance from the HTMLElement rather than also extending the HTMLElement.  For example, `const myName = el.$instance as MyName;`. This would avoid naming conflicts with HTMLElement, provide strong typing, enforce all private / public settings, avoid need for `@Method()`, etc.  There are many properties in HTMLElement that could cause conflicts (id, title, prefix, children, etc.)

Thanks for the reply.  I figured I might as well share some ideas in case they help.

**Comment by jthoms1** [comment]
Maybe I am mis understanding but bear with me.  Stencil components are just web components, so all props/attributes/state interactions are on an HTMLElement.  Collisions such as name/id, etc could occur.

But I think maybe we just need to make in more obvious when you are writing code that could cause collisions even though some will probably intend to do so.
