### ISSUE TITLE
How to register multiple stencil components in react application ?

### ISSUE THREAD

**Issue by zengyuangai** [ionic-team/stencil#2384]
**Stencil version:**

```
 @stencil/core@1.12.5
```

**I'm submitting a:**

[X] bug report
[X] feature request
Problem statement:
I have three stand alone stencil component published in npm registry, want to consume in create-react-app.

test-components1 -- >Stand alone stencil component published in npm registry.
test-components2-- >Stand alone stencil component published in npm registry.
test-components3 -- >Stand alone stencil component published in npm registry.

create-react-app -- >React app created via create-react-app. Inside this i want to consume above three stencil components.

Current approach
index.js --> file
import { applyPolyfills as applyPolyfills1, defineCustomElements as defineCustomElements1 } from 'test-components1/loader';
import { applyPolyfills as applyPolyfills1, defineCustomElements as defineCustomElements2 } from 'test-components2/loader';
import { applyPolyfills as applyPolyfills1, defineCustomElements  as defineCustomElements3} from 'test-components3/loader';

applyPolyfills1().then(() => {
  defineCustomElements1();
});
applyPolyfills2().then(() => {
  defineCustomElements2();
});
applyPolyfills3().then(() => {
  defineCustomElements3();
});

Expected approach
In above approach i need to call three times defineCustomElements.
Is there any work around i can call defineCustomElements only once and pass all three components as parameters.

Thanks

**Comment by adrianschmidt** [comment]
How is this not a support request? 😄

> Please do not submit support requests here, use one of these channels: stencil-worldwide.herokuapp.com or forum.ionicframework.com

**Comment by manucorporat** [comment]
You should apply applyPolyfills() just once:
```
applyPolyfills().then(() => {
defineCustomElements1();
defineCustomElements2();
defineCustomElements3();
});
```
The other workaround is to create an empty 4th stencil collecion that includes all 3, that way you import a single collection that includes all of them
