### ISSUE TITLE
Allow to cherry-pick web-components from a stencil compiled project

### ISSUE THREAD

**Issue by milottit** [ionic-team/stencil#2394]
**Stencil version:**

```
 @stencil/core@1.12.6
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

It is not possible to select only the components we want to include from a stencil compiled project. The only way is to import the whole library within all its web-components. It will result to have all the components of the imported library in the output targets.

**Expected behavior:**

Even though Stencil load lazily the components using esm lazy import or with StencilJS, the output is larger for nothing. One may need to keep small output on the server. Also, the library-name.esm.js in dist/ gets bigger and bigger. The `bootstrapLazy` method does not need to load all the components if they will never be used. If a project uses  a lot of different libraries, it could end up with thousand and thousand of unused components added in the output targets.

**Steps to reproduce:**

 Import a stencil library in a stencil project

**Related code:**

```tsx
// In any file in the src directory
import '@stencil-project-example/libraryname';
```

**### Workaround:**

I found out a workaround after reading the source code. To cherry-pick the components wanted, it is necessary to create a project with the following structure:

```
- package.json
- lib
    - collection
    - types
    - index.js // empty is enough
```

In the `package.json`, you must include

```json5
{
  "name": "@stencil-project-example/libraryname",
  "version": "0.0.1",
  "collection": "lib/collection/collection-manifest.json",
  "collection:main": "lib/collection/index.js",
  "main": "lib/index.js",
  "types": "lib/types/index.d.ts",
  "files": [
    "lib/" /* -----> not necessary. It depends if you will publish it on npm or whatever you need */
  ]
}
```

In the `lib` directory, you need to copy-paste the `dist/collection`  and `dist/types` directories from the compiled stencil library. (You are not obliged to keep physically the `dist/types` directory. Just the field `"types"` in the `package.json` is required. But it is good to keep it anyway).

Now you have to edit the `lib/collection/collection-manifest.json` and remove all the web-components you do not want and keep only what you wish. In the `dist/{collection and types}`, you can of course delete if you wish all the component files/directories you do not need.

In the project you want to include the components you want, you have to import the package created anywhere in the `src/` directory:

```tsx
// In any file in the src directory
import '@stencil-project-example/libraryname';
```

Note that is important to keep a node_modules import syntax. A relative (starting with a .) or an absolute path (starting with a /) will not work. If you use a local package, use a symlink (with npm link or whatever you prefer).

And voilà. You just cherry-picked the components you wanted.

### **Possible solution to implement**

The `parseCollection` is the method handling the import of the stencil collection. It is called in `addExternalImport` (src/compiler/transformers/collections/add-external-import.ts). This method is called in `parseModuleImport` only if the imported path is not a relative or absolute path. It would be possible to add a StencilConfig field called `collections` where a user could select the libraries to be include and pick the components wanted. Maybe something like:

```ts
interface StencilConfig {
   // ...
   collections: Collection[];
}

interface Collection {
  libraryName?: string; // for node_modules packages
  libraryPath?: string; // if it is a local package without a symlink or whatever
  components?: Component[]; // list of components to include if specified
}

type Component = string | ComponentInterface; // the tag-name or the component class
```

**Comment by manucorporat** [comment]
you can use:

```
export const config: Config = {
  excludeUnusedDependencies: true,
}
```
That will exclude unused components from the emitted output!

**Comment by milottit** [comment]
i will give it a try. Though, there is no documentation on this setting. Maybe it should be added somewhere.

**Comment by milottit** [comment]
Anyway, someone could want to cherry-pick the components emitted. A component can be used somewhere else in a project (in an Angular, React or native html) without being used inside the package generated. So the setting `excludeUnusedDependencies` would be useless because the unused components in the package would not be emitted but still be used outside the library in a project. So there should be a different configuration.

**Comment by milottit** [comment]
@manucorporat I am not sure you can close this issue so quickly. Could you check my comment please?

**Comment by trazek** [comment]
This could be very useful. Can we re-open this and perhaps discuss a course of action for contribution?
