### ISSUE TITLE
Correction for step test in validateInputProperties function

### ISSUE THREAD

**Issue by alexbartfeld** [ionic-team/stencil#2406]
**Stencil version:**
```
@stencil/core@1.13.0-0 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Current input validation function checks index of step parameter against an index of min property.
```
const validateInputProperties = (vnodeData: any) => {
  const props = Object.keys(vnodeData);
  const typeIndex = props.indexOf('type');
  const minIndex = props.indexOf('min');
  const maxIndex = props.indexOf('max');
  const stepIndex = props.indexOf('min');
  ...
```

**Expected behavior:**
Step should be checked against step property.
```
const validateInputProperties = (vnodeData: any) => {
  const props = Object.keys(vnodeData);
  const typeIndex = props.indexOf('type');
  const minIndex = props.indexOf('min');
  const maxIndex = props.indexOf('max');
  const stepIndex = props.indexOf('step');
  ...
```

**Steps to reproduce:**
validateInputProperties function is in src/runtime/vdom/h.ts file

**Comment by rwaskiewicz** [comment]
https://github.com/ionic-team/stencil/pull/3196 fixes this issue, and was included in the [v2.12.1 release](url) that was released a few hours ago. I'm going to close this issue as fixed, but please feel free to open a new one if the problem persists!
