### ISSUE TITLE
Using construct stylesheet polyfill breaks stencil on Firefox

### ISSUE THREAD

**Issue by gluck** [ionic-team/stencil#2407]
**Stencil version:**
```
 @stencil/core@1.12.7
```

**I'm submitting a:**
[X] bug report

**Current behavior:**
If we import `https://unpkg.com/construct-style-sheets-polyfill@2.3.5/dist/adoptedStyleSheets.js` on Firefox, it breaks the [code](https://github.com/ionic-team/stencil/blob/63595bc540db9aa85295f5a8dc8738beb2a37611/src/client/client-window.ts#L21) stencil uses to detect native shadowDom support:
```
(doc.head.attachShadow + '').indexOf('[native') > -1)()
```
(as the polyfill replaces the attachShadow method)

It follows an error `TypeError: setting getter-only property "shadowRoot"` because stencil then tries to assign shadowRoot [here](https://github.com/ionic-team/stencil/blob/2d716b3afa184a4afe3da01f34e978910ff00558/src/runtime/bootstrap-custom-element.ts#L84-L90):
```
  if (supportsShadow) {
    el.attachShadow({ mode: 'open' });
  } else {
    (el as any).shadowRoot = el;
  }
```

**Expected behavior:**
Works fine, like when the polyfill isn't loaded.

**Steps to reproduce:**
Create a stencil component on webcomponents.dev on Firefox.

**Comment by manucorporat** [comment]
Fireefox supports shadow-dom natively, why is the polyfill messing with it?

**Comment by gluck** [comment]
The polyfill is for adoptedStyleSheets (which FF still doesn't support, like Safari), not shadow-dom, but it seems it needs to hook into attachShadow to create a MutationObserver on the shadow roots to adopt stylesheets.

**Comment by adamdbradley** [comment]
How can I replicate this? I tried a component with shadow dom, in a production build, with firefox and I'm not seeing any errors. What component and command are you using that I can see the error in FF? Thanks

**Comment by adamdbradley** [comment]
Forgot to mention my demo also has `<script src="https://unpkg.com/construct-style-sheets-polyfill@2.3.5/dist/adoptedStyleSheets.js"></script>` as the first script. That right?

**Comment by gluck** [comment]
Should be enough to reproduce, you can see it happening on wc.dev on any stencil component, if you want to confirm, e.g:
https://webcomponents.dev/edit/vVm8zSg4d9jbARaZsnrV

(first exec may be ok due to cache miss and stencil loading before the polyfill)

It may depend on Firefox version though, I'm using beta channel: `77.0b3-1`, I'll try the stable channel.

I guess I can work around it by injecting the `[native` string into attachShadow method after its replacement by the polyfil, but I'd rather not go this way.
