### ISSUE TITLE
Invalid URL './'

### ISSUE THREAD

**Issue by WisaniShilumani** [ionic-team/stencil#2408]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**
[x ] bug report

**Current behavior:**
When running Ionic in SSR mode, upload loading the server, I get the error:
`TypeError [ERR_INVALID_URL]: Invalid URL: ./`

This comes from the line 35 of https://github.com/ionic-team/stencil/blob/master/src/runtime/bootstrap-lazy.ts
`plt.$resourcesUrl$ = new URL(options.resourcesUrl || './', doc.baseURI).href;`
`URL` does not support relative paths

**Comment by sanskrit-today** [comment]
I also face the same issue. What is the fix and how to get the fix?

**Comment by sanskrit-today** [comment]
@WisaniShilumani Any workaround or pointer for this issue?

**Comment by WisaniShilumani** [comment]
@sanskrit-today I recall fixing this by updating my ionic packages; what versions are you on?

**Comment by sanskrit-today** [comment]
Here is my dependencies in package.json

`  "dependencies": {
    "@angular/animations": "^10.0.6",
    "@angular/common": "^9.1.4",
    "@angular/core": "^9.1.4",
    "@angular/fire": "6.0.0",
    "@angular/forms": "^9.1.4",
    "@angular/platform-browser": "^9.1.4",
    "@angular/platform-browser-dynamic": "^9.1.4",
    "@angular/platform-server": "^9.1.4",
    "@angular/router": "^9.1.4",
    "@angular/service-worker": "^9.1.4",
    "@capacitor/android": "^2.1.0",
    "@capacitor/cli": "^2.1.0",
    "@capacitor/core": "^2.1.0",
    "@capacitor/ios": "^2.1.0",
    "@ionic/angular": "^5.3.1",
    "@ionic/angular-server": "^5.4.0-dev.202007272004.5f28aa0",
    "@ionic/storage": "^2.3.0",
    "@nguniversal/express-engine": "^9.1.1",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@stencil/core": "1.17.2",
    "angular-pipes": "^10.0.0",
    "capacitor-firebase-auth": "^0.3.1",
    "core-js": "^2.6.11",
    "dayjs": "^1.8.26",
    "domino": "^2.1.6",
    "express": "^4.15.2",
    "firebase": "^7.14.2",
    "google-libphonenumber": "^3.2.9",
    "jetifier": "^1.6.5",
    "mock-browser": "^0.92.14",
    "npm": "^6.14.5",
    "parse": "^2.15.0",
    "parse5": "^6.0.1",
    "rxjs": "6.5.5",
    "sanscript": "0.0.2",
    "tslib": "^1.11.2",
    "videogular2": "^7.0.2",
    "zone.js": "~0.10.2"
  },  
`

**Comment by Sriya-namavarapu** [comment]
I had the same issue. I have updated all my dependencies and still stuck with the same issue.

**Comment by christian-bromann** [comment]
@Sriya-namavarapu can you provide a reproducible example?
