### ISSUE TITLE
Slot content appears outside of mock:shadow-root in spec tests.

### ISSUE THREAD

**Issue by cloudsociety** [ionic-team/stencil#2415]
**Stencil version:**
```
 @stencil/core@1.12.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Asked the slack channel, but didn't get a response. The docs seem to be missing information on `mock:shadow-root`.

When using `stencil generate`, I can include the different test suites. If I alter the `spec` test suite to use the slot, the slot content appears after `mock:shadow-root`. I would expect the slot content to appear *in* the slot *within* the `mock:shadow-root`.

```
// blah-blah.tsx
import { Component, ComponentInterface, Host, h, Prop } from "@stencil/core";

@Component({
  tag: "blah-blah",
  styleUrl: "blah-blah.css",
  shadow: true,
})
export class BlahBlah implements ComponentInterface {
  @Prop() heading: string;

  render() {
    return (
      <Host>
        <h2>{this.heading}</h2>
        <slot></slot>
      </Host>
    );
  }
}
```

With test: 

```
// blah-blah.spec.tsx
import { newSpecPage } from "@stencil/core/testing";
import { BlahBlah } from "./blah-blah";

describe("blah-blah", () => {
  it("renders", async () => {
    const page = await newSpecPage({
      components: [BlahBlah],
      html: `<blah-blah heading="My heading"><span>Success!</span></blah-blah>`,
    });
    // console.log(page.root);
    expect(page.root).toEqualHtml(`
      <blah-blah heading="My heading">
        <mock:shadow-root>
          <h2>My heading</h2>
          <slot>
            <span>Success!</span>
          </slot>
        </mock:shadow-root>
      </blah-blah>
    `);
  });
});
```

**Fails.** `toEqualHtml()` wants to be the following in order to pass:

```
<blah-blah heading="My heading">
  <mock:shadow-root>
    <h2>My heading</h2>
    <slot>
    </slot>
  </mock:shadow-root>
  <span>Success!</span>
</blah-blah>
```

**Note that the slot is outside the shadow-root element.**

**Expected behavior:**
```
expect(page.root).toEqualHtml(`
      <blah-blah heading="My heading">
        <mock:shadow-root>
          <h2>My heading</h2>
          <slot>
            <span>Success!</span>
          </slot>
        </mock:shadow-root>
      </blah-blah>
    `);
```

**should pass**

**Steps to reproduce:**

1. `stencil generate`
2. alter default `*.spec.tsx` to use the slot
3. run the test

If this is expected behaviour, is there a better way to test the output of the components? I'm still new to testing Stencil components, so trying to learn the best way to do this.

**Comment by manucorporat** [comment]
Slotted content is not part of the shadow-dom that's why, you can think of shadow-dom as a encapsulated world that has a projection feature called the slot.

The slotted content outside mock:shadow-root is expected behaviour

**Comment by mplesec** [comment]
@manucorporat what's the correct way to use `toEqualHtml` in this case then? It seems using `expect(page.root).toEqualHtml` won't work in any case since the expect statement's HTML will be rearranged.

**Comment by pabloelisseo** [comment]
@mplesec I am not an expert on stencil but as previously said, this is the expected behaviour. That means that if you use `toEqualHtml` in your testing clause (which I do not recommend) you should include the `<mock:shadow-root>` tags in your testing clause as in the following example.
``` jsx
describe('app-home', () => {
    it('renders', async () => {
        const page = await newSpecPage({
            components: [AppHome],
            html: `<app-home></app-home>`,
            supportsShadowDom: false,
        });
        expect(page.root).toEqualHtml(`
            <app-home>
                <mock:shadow-root>
                    Success!
                </mock:shadow-root>
            </app-home>`);
    });
});
```

Another option is changing the value of `supportShadowDOM` to `false` as in the following example:
``` jsx
describe('app-home', () => {
    it('renders', async () => {
        const page = await newSpecPage({
            components: [AppHome],
            html: `<app-home></app-home>`,
            supportsShadowDom: false,
        });
        expect(page.root).toEqualHtml(`
            <app-home>
                    Success!
            </app-home>`);
    });
});
```

Both solutions work with the following super simple component:
``` jsx
import { Component, Fragment, h} from '@stencil/core';

@Component({
  tag: 'app-home',
  styleUrl: 'app-home.css',
  shadow: true,
})

export class AppHome {
  render() {
    return (
      <>
        Success!
      </>
    );
  }
}
```

And just for you to know, if you want to try this example locally you shoud add this line to your `tsconfig.json` compiler options:
`"jsxFragmentFactory": "Fragment"`

**Comment by marckassay** [comment]
@mplesec I've been recently developing with Stencil, and came across this discussion. The test below confirms what @manucorporat mentioned, and it passed:

```javascript
// my-button.tsx
import { Component, Host, h, Prop } from '@stencil/core';
import clsx from 'clsx';
import { Color, Shape } from '../globals';

@Component({
  tag: 'my-button',
  styleUrl: 'my-button.scss',
  shadow: true,
})
export class MyButton {
  @Prop() color?: Color = 'primary';
  @Prop({ reflect: true }) disabled?: boolean = false;
  @Prop({ reflect: true }) elevation?: boolean = false;
  @Prop() shape?: Shape = 'smooth';
  @Prop() size?: 'large' | 'medium' | 'small' = 'medium';

  render() {
    return (
      <Host>
        <button
          class={clsx(`MyButton ${this.color} ${this.shape} ${this.size}`, {
            elevation: this.elevation,
          })}
          disabled={this.disabled}
        >
          <slot></slot>
        </button>
      </Host>
    );
  }
}
```

```javascript
// my-button.spec.tsx
import { newSpecPage } from '@stencil/core/testing';
import { MyButton } from '../my-button';

describe('my-button', () => {
  it('renders', async () => {
    const page = await newSpecPage({
      components: [MyButton],
      html: `<my-button>Lorem Ipsum</my-button>`,
    });
    expect(page.root).toEqualHtml(`
      <my-button>
        <mock:shadow-root>
          <button class="MyButton medium primary smooth">
            <slot></slot>
          </button>
        </mock:shadow-root>
        Lorem Ipsum
      </my-button>
    `);
  });
});
```
HTH
