### ISSUE TITLE
TypeScript src/components.d.ts Cannot find name

### ISSUE THREAD

**Issue by CamJN** [ionic-team/stencil#2416]
**Stencil version:**
```
 @stencil/core@1.12.7 
```

**I'm submitting a:**
- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**
I get a typescript error when trying to import a class from another file.

**Expected behavior:**
No typescript error.

**Steps to reproduce:**
see code

**Related code:**
// fetch.ts
```ts
export default class Fetch {
...
}
```

// blah.tsx
```tsx
import { Component, ComponentInterface, Prop, h } from '@stencil/core'; 
import Fetch from "./fetch";
class Blah  implements ComponentInterface {
  @Prop() controls: boolean;
  @Prop() proxy: Fetch;
...
}
```
// compiler output
```bash
[ ERROR ]  TypeScript: ./src/components.d.ts:22:18
           Cannot find name 'Fetch'.

     L21:      "controls": boolean;
     L22:      "proxy": Fetch;
     L23:  }
```

**TypeScript Version:**
```
 typescript@3.8.3
```

**Other information:**
This seems to be related to https://github.com/microsoft/TypeScript/issues/26391 but worse, because the `import {default as Fetch} from './fetch';` workaround doesn't work.

**Comment by dtanzer** [comment]
I am facing the same issue, but with a non-default-export. Can it be related to the fact the we are exporting a class?

```typescript
export class GameRules {
    ...
}
```

Imported here:

```typescript
import { Column, GameRules, Row } from './GameRules';

@Component({
	tag: 'game-board',
	styleUrl: 'game-board.css',
	shadow: true,
})
export class GameBoard {
    @Prop() player1: string = '';
    @Prop() player2: string = '';
    @Prop() gameRules = new GameRules();
    ...
}
```

Resulting in this error:

```
[ ERROR ]  TypeScript: ./src/components.d.ts:12:22
           Cannot find name 'GameRules'.

     L11:  interface GameBoard {
     L12:      "gameRules": GameRules;
     L13:      "player1": string;
```

**Comment by dtanzer** [comment]
**Definitely a bug that has to do with the class:**

When I do not export the class, everything works:

```typescript
class GameRulesClass {
    ...
}

export type GameRules = {
    field(row: Row, column: Column): FieldContent
}

export const defaultGameRules: GameRules = new GameRulesClass()
```

Used in the stencil component like that:

```typescript
import { Column, defaultGameRules, GameRules, Row } from './GameRules';

@Component({
	tag: 'game-board',
	styleUrl: 'game-board.css',
	shadow: true,
})
export class GameBoard {
    @Prop() gameRules: GameRules = defaultGameRules;
}
```

**Comment by tanner-reits** [comment]
Hey all!

Sorry there was never a reply from the team here! But, looking at this issue now, obviously things are a little out of date. So, if this is still an issue, please let us know here and provide a minimum reproduction repo using the latest version of Stencil so we can validate the issue. Otherwise, we'll look at closing this issue out in a few weeks.

Thanks!
