### ISSUE TITLE
[Bug] Stencil breaks on AMD builds in IE 11

### ISSUE THREAD

**Issue by warapitiya** [ionic-team/stencil#2418]
**Stencil version:**

```
 @stencil/core@1.12.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Stencil does not load Promise polyfill on IE correctly for AMD builds. This is because @stencil/core use `es6-promise` as promise polyfill and it is not patching promise auto for AMD.

**Expected behavior:**
Stencil should render polyfills for AMD build in IE 11.

**Steps to reproduce:**
[stencil-require-js](https://github.com/warapitiya/stencil-require-js)

1. Clone the repository https://github.com/warapitiya/stencil-require-js.
2. Install dependencies: yarn install
3. Build project: yarn build
4. Serve the files: npx serve
5. Navigate to URL on IE 11: http://localhost:5000/example
6. Open console to see the error.

**Related code:**

[stencil polyfill](https://github.com/ionic-team/stencil/blob/master/src/client/polyfills/promise.js)
[es6-promise-PR](https://github.com/stefanpenner/es6-promise/pull/263)

**Other information:**

**Comment by manucorporat** [comment]
Would you be open to create a PR? does this mean we need to update the es6-promise polyfill?

**Comment by warapitiya** [comment]
Hmm, the Issue here is that the polyfills like `es6-promise` and `fetch` are UMD supported modules. Which means we need to change the polyfills entirely.

I was hoping that we can use `core-js/es/promise` and `unfetch` instead.

Any comments?

**Comment by warapitiya** [comment]
OK. Manage to get fix this by changing below:

- Remove `es6-promise` polyfill and replace it with `core-js/es/promise`.
- Use `fetch` [polyfill's IIFE version](https://cdnjs.cloudflare.com/ajax/libs/fetch/3.0.0/fetch.js).

**Comment by viljamis** [comment]
Our team ran into this same issue as well just today. @manucorporat Did you get a chance to look at the pull yet?
