### ISSUE TITLE
Add an option to open E2EPage in a separate browser context

### ISSUE THREAD

**Issue by pheekus** [ionic-team/stencil#2419]
**Stencil version:**

```
 @stencil/core@1.12.7
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
At the moment of writing every `E2EPage` is created in the default browsing context, which is perfectly fine for most test cases. However, when a component is using cookies, localStorage and other persistence APIs, sharing the context may produce undesired side effects. For example, when parallel testing components that display different UI depending on the auth state (logged in/out), devs will see occasional and rather odd-looking failures in random test suites.

**Expected behavior:**
It would be great to have an option to [open a page in a new incognito browser context](https://pptr.dev/#?product=Puppeteer&version=v3.0.2&show=api-browsercreateincognitobrowsercontext). Something like this in terms of public API to make it a non-breaking change:
```ts
const page = await newE2EPage({
  url: "/index.e2e.html",
  incognito: true
});
```

**Steps to reproduce:**
N/A

**Related code:**
N/A

**Other information:**
I've forked the repo and added the `incognito` parameter to the `newE2EPage()` options as per example above because this change turned out to be crucial for a project I'm working on. You can [take a look at it here](https://github.com/dantothefuture/stencil/commit/682f2f46a8492dcc2cca180f53799b7f5b50b9b1) and if everything's alright I'm happy to submit a PR. Thanks :)

**Comment by manucorporat** [comment]
In theory all pages should be in incognto mode, ie the default mode is incognito:

https://github.com/ionic-team/stencil/blob/63595bc540db9aa85295f5a8dc8738beb2a37611/src/compiler/config/validate-testing.ts#L25

Does each page require a new incognito context?

**Comment by dantothefuture** [comment]
@manucorporat yeah I should've chosen a better name for this – the point is to be able to open a particular page in a separate browser context during the test run. The project I'm working on requires only _some_ pages to be opened in a new context, but for now we're just creating a fresh one in every test for simplicity.

**Comment by dantothefuture** [comment]
@manucorporat sorry to keep bugging you with this, but what about a different naming? Something like the following:

```ts
const page = await newE2EPage({ ...otherOptions, context: "new" });
```

The property would still be optional and with the default value of `default` opening the existing (default) browser context it also wouldn't be a breaking change. If you'd like to see the code, here it is: https://github.com/dantothefuture/stencil/commit/86bb9ab3fb9ff5076b4285c462396ac0a8848656

Again, I'm happy to make any changes to my approach and submit a PR if you're interested in adding this feature to Stencil. Just point me in the right direction :)

**Comment by christian-bromann** [comment]
Unfortunately it is currently not possible to create different browsing context with Puppeteer. You can take a look at [Playwright](https://stenciljs.com/docs/testing/playwright/overview) which supports this behavior with the downside of having you to run tests in a "fake" browser engine. Once this finds support for standard of-shelfs browser, we would be interested to support this.

Until then I will go ahead and close the issue. Let me know if you have any further questions! Thanks.
