### ISSUE TITLE
Listen : Cannot pass an object to or use another nested Listen

### ISSUE THREAD

**Issue by hexadecy** [ionic-team/stencil#242]
**Stencil version:**
```
@stencil/core@0.0.6-13
```

**I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
- You cannot pass an event name to Listen in an object.
`Uncaught ReferenceError: Listen is not defined`
- You cannot have another Listen nested.

**Expected behavior:**
Can pass an object or use a ternary operator with Listen.
Also be able to have another Listen under it for event like mousedown+mousemove

**Steps to reproduce:**
1. Get : https://github.com/hexadecy/time-picker-comp/releases/tag/v0.2.0
2. Uncomment
3. Change with code below

**Related code:**
```
isTouch() {
  return ('ontouchstart' in window) ? true : false;
}

@State() EVENTS = {
  POINTER_DOWN : this.isTouch() ? 'touchstart' : 'mousedown',
  POINTER_UP : this.isTouch() ? 'touchend' : 'mouseup',
  POINTER_MOVE : this.isTouch() ? 'touchmove' : 'mousemove'
}

@Listen(this.EVENTS.POINTER_MOVE)
onMoveEvent(event) {
  ...
}
```

**Original working AngularJS code**
```
var isTouch= ('ontouchstart' in window) ? true : false,
EVENTS = {
  POINTER_DOWN : isTouch ? 'touchstart' : 'mousedown',
  POINTER_UP   : isTouch ? 'touchend'   : 'mouseup',
  POINTER_MOVE : isTouch ? 'touchmove'  : 'mousemove'
};

var onMoveEvent = function(e) {
  e.preventDefault();
  ...
}

element.on(EVENTS.POINTER_DOWN, function() {
  element.on(EVENTS.POINTER_MOVE, onMoveEvent);
});

element.on(EVENTS.POINTER_UP, function() {
  element.off(EVENTS.POINTER_MOVE);
});
```

**Comment by adamdbradley** [comment]
Because the directive is metadata to collect info ahead of time, you cannot use `this` in the argument. Ionic has already created an `ion-gesture` component that may be able to accomplish what you're looking for. https://github.com/ionic-team/ionic/blob/core/packages/core/src/components/gesture/gesture.tsx
