### ISSUE TITLE
Running tests fails on opening the browser

### ISSUE THREAD

**Issue by efattal** [ionic-team/stencil#2424]
**Stencil version:**

```
 @stencil/core@1.12.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
`npm init stencil` and create a component
cd component folder
`npm test`
puppeteer is unable to run a throws this error 
`[ ERROR ]  Failed to launch the browser process! TROUBLESHOOTING:
           https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md Error: Failed to launch the
           browser process! TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
           at onClose (C:\workspace\test\node_modules\puppeteer\lib\Launcher.js:750:14) at ChildProcess.<anonymous>
           (C:\workspace\test\node_modules\puppeteer\lib\Launcher.js:740:61) at ChildProcess.emit (events.js:322:22) at
           Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`

OS: Windows 10

Currently with `@stencil/core 1.8.11` and `puppeteer 1.19.0` I have no issue.

**Expected behavior:**
The test should run

**Steps to reproduce:**
See above

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by tricki** [comment]
Complete shot in the dark but there might be a version mismatch between Stencil in puppeteer. Try uninstalling puppeteer and running `npm test` which should install the correct version.

If that works then I think it's a bug that Stencil doesn't update testing dependencies automatically.

**Comment by rwaskiewicz** [comment]
Hey folks 👋 

I apologize that is took so long for a member of the Stencil team to respond to this issue. Given the versions of Stencil and Puppeteer (1.8.11 & 1.19.0) are out of sync with the latest versions of the libraries (3.2.1 and 19.X), and that I'm unable to reproduce this with the latest version of the Stencil Component Starter, I'm going to close this issue. Once again, I apologize for the lack of response here.  Should this issue reappear, please feel free to open a new issue.
