### ISSUE TITLE
Specify where to insert style element

### ISSUE THREAD

**Issue by gregorypratt** [ionic-team/stencil#243]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.6-2 
```

**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Stencil inserts the complied CSS styles into the top of the `head` element.

**Expected behavior:**
I would like to be able to specify where in the HTML I would like to inject the complied styles. This has the benefit of overriding other imported CSS files from CDNs for example.

I think this line in Stencil: https://github.com/ionic-team/stencil/blob/master/src/client/loader.ts#L14

Could be something like this:
```js
const insertCSS = document.querySelector('[data-styles-here]');
insertCSS ? document.head.replaceChild(x, insertCSS) : document.head.insertBefore(x, document.head.firstChild);
```

**Comment by adamdbradley** [comment]
The next version, 0.0.7 changes a little bit on how styles are included (not a breaking change, but its different internally). For simplicity at these early stages I think we'll set it and if it becomes a larger problem we'll address it then. Thank you for the feedback and we'll keep this in mind, thank!
