### ISSUE TITLE
styleUrls not working properly

### ISSUE THREAD

**Issue by juny58** [ionic-team/stencil#2430]
**Stencil version:**

```
 @stencil/core@"^1.12.2"
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

When entering multiple css file paths, it applies only the first one and ignores the rest. That is really frustrating.

**Expected behavior:**

As the name of the property oes, it should support multiple style files.

**Steps to reproduce:**

Put multiple files in styleUrls array, only first one applies.

**Comment by Nightmaster** [comment]
Duplicate of #2324

**Comment by rwaskiewicz** [comment]
Closing as a duplicate of #2324
