### ISSUE TITLE
bug: Cannot read property 'data-opts' of undefined

### ISSUE THREAD

**Issue by micahlt** [ionic-team/stencil#2431]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When using the latest version of Ionic (downloaded via npm) in the browser, I receive the following error in the console: 
```javascript
Cannot read property 'data-opts' of undefined
at Fe (p-1b73df01.js:1)
    at Object.parcelRequire.node_modules/@ionic/core/dist/ionic/ionic.esm.js../p-1b73df01.js (ionic.esm.js:1)
    at newRequire (ionic.esm.496e7286.js:47)
    at ionic.esm.496e7286.js:81
    at ionic.esm.496e7286.js:120
```
The page is not hydrated.

**Expected behavior:**

No errors and a hydrated website.

**Steps to reproduce:**

1) Download the latest Ionic version: 
```bash
$ npm install --save ionic
```
2) Link to the respective Ionic scripts and styles
```html
<script type="module" src="node_modules/@ionic/core/dist/ionic/ionic.esm.js"></script>
<script nomodule src="node_modules/@ionic/core/dist/ionic/ionic.js"></script>
<link href="node_modules/@ionic/core/css/ionic.bundle.css" rel="stylesheet">
```
3) Build with a bundler (I use Parcel)
```bash
parcel index.html
```

**Other information:**
It's a possibility that it could be a Parcel (bundler) issue instead of Ionic, but I don't think so.

**Ionic info:**

```bash
Ionic:

   Ionic CLI : 6.8.0 (/home/micahlt/.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (/home/micahlt/.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.14.4
   OS     : Linux 5.4

```

**Comment by micahlt** [comment]
Ahh, that makes sense.  So if I disable Parcel's hashing, it should work, correct?

**Comment by micahlt** [comment]
Just giving a bump here, because offline functionality is a key feature of my app.  Any solutions?

**Comment by erichstark** [comment]
I have similair problem with stenciljs. I have to add hash/tag to the resource because of server caching.

**Comment by erichstark** [comment]
@micahlt try to add attribute to script with namespace of components

based on this code
`Array.from(e.querySelectorAll("script")).find(s=>RegExp(`/${r}(\\.esm)?\\.js($|\\?|#)`).test(s.src) || s.getAttribute("data-stencil-namespace") === r)`
stencil (i dont know why) is trying to find exact resource. So can also identify it with this attribute.

`<script data-stencil-namespace="my-components" src="...esm.js"></script>`

You have to find out namespace for those components, but I think it could be just "ionic".

Let me know if that helps.

**Comment by micahlt** [comment]
@erichstark Thanks for the help!  Unfortunately, due to this slowdown my team has switched from Ionic to Material Components.

**Comment by TimPietrusky** [comment]
I would also be interested in a solution to this, I want to import ionic into my typescript web app `import '@ionic/core/dist/ionic/ionic.esm.js'` and also receive the error  `Cannot read property 'data-opts' of undefined`.

**Comment by BerkeAras** [comment]
> I would also be interested in a solution to this, I want to import ionic into my typescript web app `import '@ionic/core/dist/ionic/ionic.esm.js'` and also receive the error `Cannot read property 'data-opts' of undefined`.

Same issue and don't know how to fix. Any ideas @liamdebeasi

**Comment by AlexNaga** [comment]
This is still a current issue with "@stencil/core": "2.10.0"

**Comment by pvandrunen** [comment]
Bump to this. The only method for using Vanilla Ionic that has worked for me is using the CDN links, trying to use an import to the package doesn't work. In fact, manually copying the entire ionic project into the project folder and using the local path 1) assumes all of the generated files are in the root / and if I copy all of those files to the root it throws the error:
``` 
3e2f13040bdb459fc502.js:4 Uncaught TypeError: Cannot read properties of undefined (reading 'data-opts')
    at 3e2f13040bdb459fc502.js:4:295
    at 3e2f13040bdb459fc502.js:4:10191
```

**Comment by rwaskiewicz** [comment]
The fix for this bug has gone out with the Stencil v3.1.0 release 🎉
