### ISSUE TITLE
WebWorker cross domain issue

### ISSUE THREAD

**Issue by fbasco81** [ionic-team/stencil#2438]
**Stencil version:**

```
 @stencil/core@1.13.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
We have a file named "updater.worker.ts" in our src folder. Inside the file there is a function "doSomething" that is supposed to do some kind of task in background using a WebWorker. Everything works fine when the webcomponent assets files and hosting web application run on the same domain. However, if the webcomponent is hosted on the domain "http://www.domainone.com" and the web application is hosted on the domain "http://www.domaintwo.com" , due to the security limitation of the webworker API we receive a CORS policy exception.

**Expected behavior:**
I would like the stencil runtime make it transparent to use remote WebWorker. If this is not an option, I would like to have a way to register Inline Workers as explained in the documentation here:
https://www.html5rocks.com/en/tutorials/workers/basics/#toc-inlineworkers

**Comment by manucorporat** [comment]
Stencil can already perform an efficient inlining of the service worker. Instead of inlining the worker in the critical path, we rely on a dynamic import() to a chunk contantaining the inlined worker. 

Opened a PR
