### ISSUE TITLE
Object property @Prop not working as expected

### ISSUE THREAD

**Issue by milottit** [ionic-team/stencil#2439]
**Stencil version:**
```
 @stencil/core@1.12.6
```

**I'm submitting a:**

[x] bug report
[] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

A property with the `attribute` option set as follow `@Prop({ attribute: 'array' }) array: any[];` will not get the attribute's value passed in the html tag's attribute during `componentWillLoad` phase as would be the case for a primitive property (string/number/boolean)

**Expected behavior:**

`@Prop({ attribute: 'array' }) array: any[];` and `@Prop() prop: string` should get the attribute's value during `componentWillLoad` lifecycle phase.

**Related code:**

Let's define a simple component with the 2 properties we want to test:

```tsx
import { Component, Host, h, Prop, Watch } from '@stencil/core';

@Component({
    tag: 'el-test'
})
export class ElTest {
    @Prop({ attribute: 'array' }) array: any[];
    @Prop() prop: string;


    @Watch('prop')
    @Watch('array')
    watch(newValue: any, _, propName: string) {
        console.log({ propName, newValue });
    }

    componentWillLoad() {
        this.watch(this.array, undefined, 'array');
        this.watch(this.prop, undefined, 'prop');
    }

    render() {
        return (<Host></Host>);
    }
}
```

Now let's instantiate it and see the output:

```html
<el-test id="test" prop="a little test" array="[1,2,3,4]"></el-test>

<script>
    const test = document.getElementById('test2');

    setTimeout(() => {
        test.prop = 'a second test'
        test.array = [10, 11, 12];
    }, 1000);
</script>
```

Here is the console output:

```
23:04:57.390 el-test.entry.js:8 {propName: "array", newValue: undefined}
23:04:57.391 el-test.entry.js:8 {propName: "prop", newValue: "a little test"}
23:04:57.946 el-test.entry.js:8 {propName: "prop", newValue: "a second test"}
23:04:57.946 el-test.entry.js:8 {propName: "array", newValue: Array(3)}
```

As we can see,  for the `array` property, the value is `newValue: undefined` during `componentWillLoad` phase, while it is not the case for `prop` being `newValue: "a little test"`.

**Comment by trazek** [comment]
I think this may be because you are giving it in a string at first with 
```
<el-test id="test" prop="a little test" array="[1,2,3,4]"></el-test>
```
And then later on, assigning it correctly in the setTimeout. You are actually passing a string initially so the types don't match up.

**Comment by manucorporat** [comment]
This should be fixed in the latest version, please upgrade! Let me know if you still have problems, so I reopen

**Comment by milottit** [comment]
The typing of the array properties is not `string` but `any[]`. I pass it as a string in the html tag's attribute because only string are accepted. But in js/ts, it should be the typescript type being passed. The HTML and JS api should be coherent.

The [documentation](https://stenciljs.com/docs/properties) seems to go towards it saying 

```tsx
import { Component, Prop } from '@stencil/core';

@Component({ tag: 'my-cmp' })
class Component {
  @Prop() value: string;
  @Prop({ attribute: 'valid' }) isValid: boolean;
  @Prop({ attribute: 'controller' }) controller: MyController;
}```

> By using this option, we are being explicit about which properties have an associated DOM attribute and the name of it

**Comment by milottit** [comment]
> This should be fixed in the latest version, please upgrade! Let me know if you still have problems, so I reopen

I updated the original issue with `@stencil/core/1.13.0`. The problem still persists with the same output.

**Comment by manucorporat** [comment]
it was fixed in `https://github.com/ionic-team/stencil/pull/2414`
however, you are not passing an array here:
```
<el-test id="test" prop="a little test" array="[1,2,3,4]"></el-test>
```
you are passing an string

**Comment by trazek** [comment]
> it was fixed in `https://github.com/ionic-team/stencil/pull/2414`
> however, you are not passing an array here:
> ```
> <el-test id="test" prop="a little test" array="[1,2,3,4]"></el-test>
> ```
> you are passing an string

@milottit this is what I meant in my earlier comment. You are passing a string when doing it like this

**Comment by milottit** [comment]
@manucorporat @trazek 

Yes I do know it is a string. But I am not using the element inside the `render` method of a component, but directly in a plain html file. Only string/boolean values can be passed in attributes. That's why I am passing a string and then converting it in an array with `JSON.parse` in the @Watch method.

Maybe I am wrong and so, could you explain me how to passe a js object through a tag's attribute in a plain html file?

**Comment by trazek** [comment]
The watch will not fire on first render. If you did something like that, you'd need to handle it in a lifecycle hook for the initial value.

It's suggested to not use attributes for rich data like this however. It's better to get an element reference and assign the data via property.

https://developers.google.com/web/fundamentals/web-components/best-practices

**Comment by milottit** [comment]
From the page mentioned [web-components/best-practices](https://developers.google.com/web/fundamentals/web-components/best-practices), it is said:

> Unless you have a use case that can only be solved with this feature

Best practices are guidelines that one can opt to follow or not. It is really subjective and it cannot be generalized. For instance when it is written:

>  any object references will be lost

Who cares if you use functional programming. Not relevant.

When you say:

> you'd need to handle it in a lifecycle hook for the initial value

I know it and it is what I am doing. But it can be tiresome to repeat line of codes while it could be avoided just adding an option in the @Watch decorator

**Comment by trazek** [comment]
So even if the watch had the option to run on initial render, the real issue is the willLoad hook isn't seeing the array string for some reason. I've only ever set complex properties after initial load and have never tried to parser a json string.

**Comment by milottit** [comment]
Yes, at least, the string representation should be available inside willLoad.

**Comment by trazek** [comment]
Have you tried setting the prop to to just any, rather than array?

**Comment by milottit** [comment]
Yes and it is working. The only problem comes from the typing.

**Comment by trazek** [comment]
Then I wonder if it's really a "problem" then. If the prop is typed as an array and it gets a string representation of an array, what should we expect?

**Comment by milottit** [comment]
Of course it is given a string representation as only string can be passed in html's attributes. But attributes and properties and 2 different notions. Here I want my property to be an array and of course the attribute a string (being the only possibility). Afterwards, I manage the conversion between the attribute and the property in the @Watch method.

By the way, if I type the property `string | any[]`, it is not working also. So if the "typing" is your argument to say it is not a "problem", so it is falling apart.

**Comment by trazek** [comment]
Oh I just wondering. I actually just don't think the watch should pick up the first render and using the will load to capture the first initial data is fine. But now I clearly understand your stance and context. Thanks for sharing

**Comment by erichstark** [comment]
This is still problem to use Prop as array
`@Prop({ reflect: true }) validators: Array<string>;`

But [documentation](https://stenciljs.com/docs/properties) says, it can be also Array.
So is it a bug?

**Comment by claviska** [comment]
From the docs:

> Components need to explicitly declare the Props they expect to receive using the @Prop() decorator. Props can be a number, string, boolean, or even an Object or Array.

The idea of "props" is an abstraction of attributes and properties, but they are two different concepts entirely. This tends to cause confusion so, to clarify, Stencil uses properties internally and does some magic to map attributes => properties (and optionally reflect them back with `reflect: true`).

An _attribute_ is set in HTML and can only be a string ("boolean" true attributes are technically `""` and false is the absence of the attribute).

```html
<my-el attribute="value">
```

A _property_ is set on the element instance with JavaScript and can be any type.

Technically, an element can have an attribute called `something` and a property of the same name that have totally different values:

```html
<div something="foo"></div>

<script>
  const div = document.querySelector('div');
  div.something = 'bar';
  
  console.log(div.getAttribute('something')); // foo
  console.log(div.something);                 // bar
</script>
```

> could you explain me how to passe a js object through a tag's attribute in a plain html file?

Because the types are defined, Stencil will cast strings, numbers, and booleans to the correct values, but we can't expect arrays and objects to work the same way. They must be set in JavaScript:

```html
<el-test id="test" prop="a little test"></el-test>

<script>
  const el = document.querySelector('el-test');
  el.array = [1, 2, 3, 4];
</script>
```

You could make the argument that Stencil should look at the type and cast arrays and objects similarly, but it doesn't and IMO it shouldn't. What should the behavior be in this case?

```tsx
@Prop() array: [] | string;

<my-el array="[1, 2, 3, 4]">
```

Would you expect this to be a string or an array? Even if Stencil formed the opinion that it should be one or the other, it now has to parse and decode the value when getting and setting. This will cause performance problems with large object and arrays, not to mention a nasty DOM if you were to reflect them.

Even if Stencil allowed it, I'd consider it an antipattern. I know it seems nice to set simple arrays and objects in your HTML, but if you really want to do that you'll need to handle it in your component. In my experience, it's just not worth the boilerplate and performance hit you're going to undertake.
