### ISSUE TITLE
[Feature Request] Global entry point for scss

### ISSUE THREAD

**Issue by siedentm** [ionic-team/stencil#244]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Other information:**
It would be great if we can have a global entry point for scss/sass. That would open up stencil for most sass/scss based frameworks.

edit:
On top, it favors working with ShadowDOM since we still need resets on the HTML and probably initialize some things in css.

**Comment by manucorporat** [comment]
@siedentm why you can't just add the global .css as a new `<link>` in stencil's index.html?

**Comment by adamdbradley** [comment]
Closed by https://github.com/ionic-team/stencil/commit/b65528cf144006fa04b71e691a749e4d9a142f59
