### ISSUE TITLE
Stencil copy fails at second time

### ISSUE THREAD

**Issue by Fdom92** [ionic-team/stencil#245]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
 @stencil/core@0.0.6-4 
```

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I have this command on the stencil config:
```
 copy: [
    { src: 'assets', dest: 'assets' }
 ]
```
And the first time (if there is not an assets folder on build folder) it works great, but if i run it again i got this error:

> [ ERROR ]  ENOENT: no such file or directory, unlink '/Users/fer/repos/stencil-voice2text/www/assets/....' 

**Expected behavior:**
Maybe if the assets folder is there just ignore the command and don't do anything

**Comment by adamdbradley** [comment]
Can you describe how your copy task is working more? It looks like you're copying to the same directory.

**Comment by Fdom92** [comment]
For sure :)

I have this stencil conf:

```
exports.config = {
  namespace: 'voice2text',
  generateDistribution: true,
  bundles: [
    { components: ['st-voice2text'] }
  ],
  copy: [
    { src: 'assets', dest: 'assets' }
  ]
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}

```

So the first time without doing anything this is my build folder:
<img width="271" alt="captura de pantalla 2017-10-19 a las 8 13 35" src="https://user-images.githubusercontent.com/7361737/31756694-91a9c6ba-b4a5-11e7-8ccc-a6b69a26d6d9.png">

Then i run `npm start` and this are the results:
<img width="274" alt="captura de pantalla 2017-10-19 a las 8 15 30" src="https://user-images.githubusercontent.com/7361737/31756720-b59f54e0-b4a5-11e7-94f9-a38c1de7ba5a.png">

That's great, but if i do another `npm start` for example i got that error:
> ERROR ] ENOENT: no such file or directory, unlink '/Users/fer/repos/stencil-voice2text/www/assets/....'

Is trying to copy again my folder src/assets on build/assets and fails, so i don't know if the copy task was designed to be used only once.

**Comment by jgw96** [comment]
Hey @Fdom92 , you shouldnt need to include assets in your copy config. If you have an assets folder in your src directory, it should be copied over automatically. Could you give that a try?

**Comment by Fdom92** [comment]
Okey, i tried once more.

I deleted my www and dist folder like this:

<img width="227" alt="captura de pantalla 2017-10-20 a las 8 10 40" src="https://user-images.githubusercontent.com/7361737/31807439-710d58d0-b56e-11e7-8491-aeac8e8c0ca9.png">

Then run `npm run build` with this stencil conf:
```
exports.config = {
  namespace: 'voice2text',
  generateDistribution: true,
  bundles: [
    { components: ['st-voice2text'] }
  ]
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}
```

And the results:
<img width="236" alt="captura de pantalla 2017-10-20 a las 8 11 47" src="https://user-images.githubusercontent.com/7361737/31807480-b163a3b2-b56e-11e7-92d0-9386661d3253.png">

So.. it was my mistake, sorry guys. 😢

**Comment by jgw96** [comment]
All good! Glad its working for you (:
