### ISSUE TITLE
NVDA screen reader reads text twice in edge browser

### ISSUE THREAD

**Issue by urvesh86** [ionic-team/stencil#2452]
Hi, 

Can anyone please help me on below point. 

I am using stencil framework in my project. I am facing the strange issue in my current implementation. When I render a block of markup using NVDA screen reader, it reads many of text block twice.  But the screen reader (NVDA) reads the same markup fine using plain html page.

Please note, I observed, this issue is only produced when the combination is NVDA + Edge browser. It works well in rest of the browsers.

I am using the nested components structure. i.e couple of markup elements are rendered from component and rest of markup elements are rendered from main component.

Thank you in advance.

**Comment by manucorporat** [comment]
Unfortunately, we can look at this issues with the provided information, please follow the issue template.
