### ISSUE TITLE
dist-custom-elements-bundle output is not tree-shakeable

### ISSUE THREAD

**Issue by evaneus** [ionic-team/stencil#2454]
**Stencil version:**

```
 @stencil/core@1.12.2 
```

**I'm submitting a:**

[ X ] bug report

**Current behavior:**

The bundle generated by a `dist-custom-elements-bundle` output target is not tree shakeable.

**Expected behavior:**

According to the docs this should be tree-shakeable:

>The output can be "single" bundle because it's generated to ensure components are tree-shakable. For example, if a component library has 100 components, but an external project only imported one component from the bundle, then only the code used by that one component would be pulled into the project. 

**Steps to reproduce:**
See readme.md here:

https://github.com/evaneus/stencil-output-target-test

**Other information:**
I don't want to use the `dist` target because I am trying to create a library of components with which the clients can register custom elements themselves, just providing the constructor for the custom element. 

Also want to allow imports of just some of the components so smaller tree-shaken bundles can be made from this bundle.

**Comment by manucorporat** [comment]
your project uses lodash, which is not treeshakable, use lodash-es, or avoid lodash completely!

**Comment by evaneus** [comment]
Thanks, and another problem is that agadoo seems to give a false negative, even with lodash-es.

I updated the repo to have a working example with rollup building one of the exported stencil components from `dist/custom-elements-bundle` at a time.

**Comment by Singh30K** [comment]
Hello Guys, 
still facing issue with stencil tree shakable I integrated stencil with react and integrated only one button but in bundle getting all the components created so far :
this is my config : 
import { Config } from '@stencil/core';

export const config: Config = {
  namespace: 'web-component-stencil',
  outputTargets: [
    {
      type: 'dist',
    },
    {
      type: 'dist-custom-elements-bundle',
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
  ],
};
