### ISSUE TITLE
stencil build generated intelligible error messages

### ISSUE THREAD

**Issue by milottit** [ionic-team/stencil#2458]
**Stencil version:**
```
 @stencil/core v1.13.0
```

**I'm submitting a:**

[x] bug report
[] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

`stencil build` generates incomprehensible error messages without any clue from where it is originated.

**Expected behavior:**

Error messages should indicate which file produced an error and the message should explain a bit more what is happening. I understand, the error message comes from Terser and they are responsible of the output. But stencil is responsible to display the file producing the errors.

It is a nightmare to spot the culprit file without any clue, especially when a project has dependencies that can go deep. I spent almost 2 days to understand from what file was coming this error message:

![Screenshot_20200519_125151](https://user-images.githubusercontent.com/8853905/82470704-f6ea3380-9ac5-11ea-9823-7712f093c423.png)

```js
     n = "stack" in t;
 return "stack" in i || !n || "number" != typeof Error.stackTraceLimit ? function (v, ) {
    if (v === void 0) { v = function (t, e) { return "string" == typeof t ? t : "object" != typeof e && "function" != typeof e || void 0 === e.name || void 0 === e.message ? W(e) : e.toString(); }; }
```

Firstly the message is not obvious at all. It is hard to understand that the error is that the "trailing comma in function arguments" is not supported until ECMAScript 2017. That message comes from Terser and I understand they are responsible to improve it. But, as you can see, the file producing the error is not mentioned. 

I spent 2 days to understand that the mistake was coming from a "node_modules" dependency, from the package "csvtojson".

**Comment by manucorporat** [comment]
This is an error directly from terser,we can't do much to improve/change it! I am sorry.

However the error gives a good clue of what is going on.

**Comment by milottit** [comment]
@manucorporat  Yes it is right. But one thing you can do is to keep track of the culprit file. Spending 2 days to find that the error comes from a node_modules dependency, and the the error at the end comes from typescript transpiling the code to es5 in stencil build process, is not acceptable.
