### ISSUE TITLE
stencil build generates a wrong terser error

### ISSUE THREAD

**Issue by milottit** [ionic-team/stencil#2459]
**Stencil version:**
```
 @stencil/core v1.13.0
```

**I'm submitting a:**

[x] bug report
[] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

`stencil build` generates a wrong Terser error

**Expected behavior:**

Compiling my project with the command `stencil build`, stencil generates the following error:

![Screenshot_20200519_125151](https://user-images.githubusercontent.com/8853905/82470704-f6ea3380-9ac5-11ea-9823-7712f093c423.png)

```js
     n = "stack" in t;
 return "stack" in i || !n || "number" != typeof Error.stackTraceLimit ? function (v, ) {
    if (v === void 0) { v = function (t, e) { return "string" == typeof t ? t : "object" != typeof e && "function" != typeof e || void 0 === e.name || void 0 === e.message ? W(e) : e.toString(); }; }
```

Firstly the message is not obvious at all. It is hard to understand that the error is that the "trailing comma in function arguments" is not supported until ECMAScript 2017. That message comes from Terser and I understand they are responsible to improve it. After digging 2 days I found the culprit file being "node_modules" dependency, from the package "csvtojson".

And looking at the source code, I noticed the code in the error message was not exactly the same. Here the piece that allegedly triggered the error:

```js
// bla bla
  n = "stack" in t
}
 return "stack" in i || !n || "number" != typeof Error.stackTraceLimit ? (v = function(t, e) {
return "string" == typeof t ? t : "object" != typeof e && "function" != typeof e || void 0 === e.name || void 0 === e.message ? W(e) : e.toString()
        }, null) : (_ = t, v = e, function(t) {
// bla bla
```

As you can see, the culprit function being `function (v, )` does not exist in the original source code. I suppose that stencil makes a first processing step changing the code. And here, the new code generated includes a code that is not compliant with the options passed to Terser.

Could you explain what's happening here. Maybe it is Rollup doing the transformation?

**Comment by milottit** [comment]
After having dug a bit longer, I have found that disabling es5 build with the option `buildEs5: false` will not generate any error. Maybe the culprit is `transpileToEs5` calling `ts.transpileModule` with `target: ts.ScriptTarget.ES5` option set.

**Comment by milottit** [comment]
Someone could handle this issue? I cannot build for es5 targets because of it.

**Comment by tricki** [comment]
Since it's a problem with minification adding `minifyJs: false` to the config might help until there is a fix.

**Comment by milottit** [comment]
Yes it is working without minimizing. But I cannot go on production this way!

**Comment by tanner-reits** [comment]
Hey all!

Sorry there was never a reply from the team here! But, looking at this issue now, obviously things are a little out of date. So, if this is still an issue, please let us know here and provide a minimum reproduction repo so we can validate the issue. Otherwise, we'll look at closing this issue out in a few weeks.

Thanks!
