### ISSUE TITLE
Prod build don't use the copy config

### ISSUE THREAD

**Issue by Fdom92** [ionic-team/stencil#246]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.6-4```

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I have the copy config on the stencil config file and it appears on build folder after `npm run`
but on `npm run build` i don't see the folder on dist.

**Expected behavior:**
Run the copy config on build prod too.

**Comment by adamdbradley** [comment]
Would you be able to post what the config looks like?

**Comment by Fdom92** [comment]
Yea, sorry for so little information.

This is my stencil conf:
```
exports.config = {
  namespace: 'voice2text',
  generateDistribution: true,
  bundles: [
    { components: ['st-voice2text'] }
  ],
  copy: [
    { src: 'assets', dest: 'assets' }
  ]
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}
```
The thing is, im trying to publish a stencil component to npm with assets but after a prod build `npm run build`  assets folder does not exist.

**Comment by jgw96** [comment]
This looks to me to be a bug, albeit a small one that can be solved by just manually moving your assets folder to your `dist` directory. With this config ```copy: [
    { src: 'assets', dest: 'dist/assets' }
  ] ``` it createst a `dist/assets` folder in `www` instead of putting the assets in `dist`.

**Comment by Fdom92** [comment]
Okay, i tried once more.

I deleted my dist folder and modify the stencil config file:

<img width="206" alt="captura de pantalla 2017-10-20 a las 8 19 14" src="https://user-images.githubusercontent.com/7361737/31807614-89ee074a-b56f-11e7-8693-8fa8e511d794.png">

```
exports.config = {
  namespace: 'voice2text',
  generateDistribution: true,
  bundles: [
    { components: ['st-voice2text'] }
  ],
  copy: [ { src: 'assets', dest: 'dist/assets' } ]
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}
```

And run `npm run build` with this results on dist folder:
<img width="266" alt="captura de pantalla 2017-10-20 a las 8 21 23" src="https://user-images.githubusercontent.com/7361737/31807661-bdcdf534-b56f-11e7-9a5c-e87ca3f4158c.png">

**Comment by Fdom92** [comment]
I tried what that, copy src/assets folder on dist/assets folder and publish. But even with that the component don't show the assets. 

Maybe i have to copy the assets folder somewhere else?

Thanks

**Comment by jgw96** [comment]
Is your project on Github @Fdom92 ?

**Comment by Fdom92** [comment]
Yes Justin, here https://github.com/Fdom92/stencil-voice2text
