### ISSUE TITLE
stencil build is not generating types/components/index.d.ts

### ISSUE THREAD

**Issue by milottit** [ionic-team/stencil#2460]
**Stencil version:**
```
 @stencil/core v1.13.0
```

**I'm submitting a:**

[x] bug report
[] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

`stencil build` is not generating `dist/types/components/index.d.ts`

**Expected behavior:**

`stencil build` should generate a `dist/types/components/index.d.ts` file including all the component types.

Currently, there is nothing generated inside `dist/types/components` and so the line 
```ts
export * from './components';
```
from `dist/types/index.d.ts` is not valid.

**Comment by manucorporat** [comment]
It should be generating `dist/types/component.d.ts`, so it's valid.

**Comment by milottit** [comment]
@manucorporat  Here you find a screenshot of the dist folder after running `stencil build`.

![image](https://user-images.githubusercontent.com/8853905/82663335-c1615980-9c2f-11ea-9943-9eca319c74eb.png)

Now, tell me where is `component.d.ts`. Maybe it should be there but it is not the case. So maybe the issue was closed again a bit to fast.

**Comment by manucorporat** [comment]
Can you give `1.14.0-1` version a try? also, remove node_modules and the dist folder  too

Otherwise we might need a repo case to figure this out.
