### ISSUE TITLE
"Cannot load undefined" error using video.js

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2461]
**Stencil version:**

```
 @stencil/core@1.14.0-0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
(1.14.0-0). Using video.js leads to that error during the build:
[ ERROR ]  Rollup: Plugin Error
           Could not load undefined (imported by ../node_modules/video.js/node_modules/global/document.js): The “path”
           argument must be of type string. Received undefined (plugin: lazyTypescriptPlugin, load)

**Expected behavior:**
Would work

**Related code:**
Repro repo: https://github.com/darondel-yoobic/angular-stencil-playground/tree/bug-videojs-rollup (note the branch of `bug-videojs-rollup`

**Comment by joewoodhouse** [comment]
Also getting this when using rxdb (unload is dependcy of it)
```
[ ERROR ]  Rollup: Plugin Error
           Could not load undefined (imported by ./node_modules/unload/dist/es/index.js): The "path" argument must be
           of type string. Received undefined (plugin: lazyTypescriptPlugin, load)
```

**Comment by peterpeterparker** [comment]
Thx for the fix, works like a charm 👍
