### ISSUE TITLE
Incorrect slot relocation behaviour in hydrate app.

### ISSUE THREAD

**Issue by George-Payne** [ionic-team/stencil#2467]
**Stencil version:**
```
 @stencil/core@1.13.0
```

**I'm submitting a:**
[x] bug report

**Current behavior:**

`Build.slotRelocation` is set to false in hydrate app unless you have a non-shadow dom element with a slot. This results in incorrect location of slotted content in outputted HTML. (Similar to #2068)

![image](https://user-images.githubusercontent.com/11861797/82814340-40a49680-9e97-11ea-85a7-01a709a12b32.png)

**Expected behavior:**
Slotted content should replace slot when hydrating:

![image](https://user-images.githubusercontent.com/11861797/82814510-99742f00-9e97-11ea-8f87-0afc9d2099a5.png)

**Steps to reproduce:**
Create a stencil app with only shadow components, generate a hydrate app and observe incorrect output on hydrate.

**Other information:**

**bug location**
`src/compiler/app-core/app-data.ts:9`

**suggested fix** 
Set `Build.slotRelocation` to true if within hydrate app.

**workaround**
Add a shadowless component containing a `<slot />` as a child. This allows all other components to work correctly.

**Comment by rwaskiewicz** [comment]
Reopening - this shouldn't have been closed. Sorry about that!

**Comment by rwaskiewicz** [comment]
I'm going to close this issue out due to lack of activity. If you're experiencing this issue today, please feel free to open a new issue! Thanks!
