### ISSUE TITLE
Shared services

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#247]
**Stencil version:** 

```
@stencil/core@0.0.6-13
```

**I'm submitting a ...**
[x] feature request

**Current behavior:**
In order for a component to utilize code that is outside of the component it can request a shared component using the `connect` feature.  This is not documented yet but I think I was able to get it to work from poking around in the code.  Here is an example of using `connect` with an outside service:

```typescript

export class MyComponent {

  // The service loader
  @Prop({ connect: 'my-service' }) myServiceLoader;

  // The service instance
  @State() myService: MyService;

  componentDidLoad() {
    // Get the service instance
    this.myServiceLoader.componentOnReady().then((cmp) => {
      this.myService = cmp.$instance;
    });
  }

  render() {

    if (!this.myService) return null;

    return <div>{this.myService.getData()}</div>
  }
}

```

This is a simple example with a single external service but it is common that more than one would be utilized in a component which further complicates the code related to loading.  For example, many angular components use DI to access 5 or more external services.

**Proposed behavior:**
It seems like the component needs to do a bunch of work to deal with the potential for async loading and that it could be simplified for the common use case.

One potential alternate approach would be as follows:

```typescript

export class MyComponent {

  @Prop({ connect: 'my-service' }) myService: MyService;

  render() {
    return <div>{this.myService.getData()}</div>
  }
}
```

In this approach the component loader would detect the external dependencies from the `connect` props and defer `componentDidLoad` and `render` until the dependencies finished loading.  Once the app is already running this would likely not even need to wait because they would already be loaded.

This is more in line with the Angular style of dependency injection where the component does not get created until the dependencies have been loaded.

There might be cases where the service is not needed until after rendering (e.g. an alert controller used in a button click handler).  This could use different decorator props to indicate that it can be async loaded like the current pattern.

It is possible that future ES6 module imports support would provide an alternate approach but it is not yet clear about how that is going to be implemented.

I have been trying to use Stencil as the basis for an app (vs. just creating some simple components) and it seems like the biggest missing feature is how to handle shared data, external libraries, services, etc.

**Comment by romulocintra** [comment]
Hi , i see it like and is a nice ideia , but you have the@props to pass properties over attr, following this rule i believe code will be simpler, and with single responsability.

I for in similar cases is :

Have a molecule that is a stencil component that encapsulate service and your atom that receive data as prop and emit events if you need to call specific service 

In polymer you have similar example iron-ajax “callback” can be binded direct to component @props

**Comment by jgw96** [comment]
Hey @cjorasch, thanks for using Stencil! Since this seems more like a question / discussion than an actual issue in Stencil I am going to close this issue for now and ask this question on our slack channel https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjYwNjg5NDMzODQwLTdiNWZiNDMyMWRjZTBiMjIzMGFlOTZiZWVkNDVjNzc2ZTI5MzI2Y2VjZDgwYjczMjU3NWIxMDYzMzI2ZjY3NjM . Thanks again!

**Comment by FelschR** [comment]
I'm facing this "problem" atm.

It seems that I can only pass normal JSON via Props?
I tried to set one of my properties to a (service) object with some functions on it. But within my stencil component I was only able to use the properties from that object, the functions were gone.

**Comment by mcelotti** [comment]
Hi, I'm trying to figure out how to create a shared service (singleton) in stenciljs app but I'm a bit confused, no official docs for a quite common feature. Any help would be great!

**Comment by gino8080** [comment]
I'm interested in singleton shared service too

**Comment by mcelotti** [comment]
Ok, here's a workaround I'm using right now, not too elegant but... it's really simple since it's based on global context.

Inside "src/global/app.ts" I have:
```
declare const Context: any;
Context.myService = new MyService();
```
Then inside my components:
```
declare const App: any;

@Component({
  tag: "app-my-cmp"
})
export class AppMyCmp {
  componentWillLoad() {
    App.Context.myService.doSomething();
    ...
  }
```

**Comment by deleanuradu** [comment]
In case anyone comes across this topic, I found this article that suggests using a plain class with a static _instance property (to turn it into a singleton), then passing that reference in the component where you need to use it.

[https://medium.com/@nerdic.coder/stencil-tutorial-tour-of-heroes-part-3-9b0e128ee664](url)
