### ISSUE TITLE
Component loaded twice in pre-rendered build

### ISSUE THREAD

**Issue by saiy2k** [ionic-team/stencil#2472]
**Stencil version:**

```
 @stencil/core@1.12.2 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I load a pre-rendered page (https://farmers-app-cce97.web.app/profile/thozhan/), the following happens
 * The Component is constructed, lifecycle methods (componentWillLoad, componentDidLoad, render) are called with the @Prop values as undefined
 * Then again the Component is constructed and lifecycle methods are called. This time with proper values of @Props extracted from route (url)

Issue doesnt happen in localhost, only in pre-rendered build.

**Expected behavior:**
First time invocation of component with the @Prop values as undefined shouldn't happen

**Steps to reproduce:**
Look at log of this page: https://farmers-app-cce97.web.app/profile/thozhan/

**Related code:**
Issue can be replicated by cloning this repo: https://github.com/saiy2k/stencil-lifecyle-prerender-issue, pre-rendering it and deploying it.

**Other information:**

**Comment by peterpeterparker** [comment]
Might be the same issue as the following which is also open: https://github.com/ionic-team/stencil/issues/2366
