### ISSUE TITLE
State() being reset on disconnectedCallback

### ISSUE THREAD

**Issue by MostafaNabi** [ionic-team/stencil#2480]
**Stencil version:**

```
 @stencil/core@<1.7.5>
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
On the disconnectedCallback() my state, a Map is being reset. I have logged its size, and it goes
disconnectedCallback 1
connectedCallback 0

**Expected behavior:**
I would not expect state to reset everytime the parent component re-renders, and this behaviour is not documented anywhere.

**Steps to reproduce:**
Create two components, with the parent re-rendering on an event emitted by the child and watch the state reset.

**Comment by manucorporat** [comment]
When a component is removed by stencil, and rendered again later, it's a brand new instance. That means, it's not being reset, it's just a new instance of the component.

**Comment by MostafaNabi** [comment]
Yeah i messed this up, i thought my component was being disconnected every time my parent re-rendered which just really confused me.

Turns out there was an if statement buried deep inside the code that was momentarily not rendering it.
