### ISSUE TITLE
Environment variable in styleUrl

### ISSUE THREAD

**Issue by github-rj** [ionic-team/stencil#2481]
**Stencil version:**

```
 @stencil/core1.9.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Build failed
```
[ ERROR ]  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object at
           validateString (internal/validators.js:125:11) at Object.dirname (path.js:646:5) at useCss
           (D:\Project\co\node_modules\@stencil\core\compiler\index.js:14987:43) at compilerStyleUrls.(anonymous
           function).styleUrls.(anonymous function).map.s
           (D:\Project\co\node_modules\@stencil\core\compiler\index.js:14982:58) at Array.map (<anonymous>) at
           Object.keys.forEach.key (D:\Project\co\node_modules\@stencil\core\compiler\index.js:14982:49) at Array.forEach
           (<anonymous>) at normalizeExtension (D:\Project\co\node_modules\@stencil\core\compiler\index.js:14981:28) at
           styleToStatic (D:\Project\co\node_modules\@stencil\core\compiler\index.js:14934:34) at
           componentDecoratorToStatic (D:\Project\co\node_modules\@stencil\core\compiler\index.js:15029:5)
```
**Steps to reproduce:** 
`npm install rollup-plugin-dotenv @types/node --save-dev`
create .env file at project root 
define environment variable PROJECT_NAME="projectname" in .env file
change config file:
```
import dotenvPlugin from 'rollup-plugin-dotenv';
...
 plugins: [
      dotenvPlugin()
]
```
use environment variable in styleurl
```tsx
@Component({
  tag: 'co-login',
  styleUrl: `co-login-${process.env.PROJECT_NAME}.scss`,
 })
```

**Related code:**
```tsx
@Component({
  tag: 'co-login',
  styleUrl: `co-login-${process.env.PROJECT_NAME}.scss`,
 })
```
**Other information:**
https://stencil-worldwide.slack.com/archives/C79EANFL7/p1591085710157700

**Comment by adamdbradley** [comment]
Sorry but this information must be static at build time.

**Comment by cgpro** [comment]
Is it not possible to modify the build process so that variables are also possible here?
In my case, I want to compile a version with and a version without CSS.
