### ISSUE TITLE
Documentation outputs don't work as expected/documented

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil#2483]
**Stencil version:**

```
 @stencil/core@1.13.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The only way to get the various docs outputTargets is to pass `--docs` to the cli, contrary to what the docs say. The problem here is that with `--docs` you will always get generated `readme.md` files and there is no way to opt out of them.

**Expected behavior:**
- When `--docs` cli option is not present:
  - docs outputTargets still run
  - No readmes are generated
- When `--docs` cli option IS present:
  - readmes are generated
  - docs outputTargets still run

**Comment by tricki** [comment]
Looks like the cause is in [`validate-docs.ts:27`](https://github.com/ionic-team/stencil/blob/3349692213133950843e91005d3230a43761c5de/src/compiler/config/outputs/validate-docs.ts#L27) which will automatically add a `docs-readme` target if the `--docs` flag was passed.
