### ISSUE TITLE
`draggable={false}` doesn't render correctly

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#2484]
**Stencil version:**

```
 @stencil/core@1.14
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Image tags have `draggable` enabled by default and there's no way to turn it off currently, because using `draggable={false}` in JSX doesn't render the attribute correctly but simply omits it:

```html
<img src="http://place-hold.it/200" alt="Placeholder" draggable={false} />
```

=> `<img src="http://place-hold.it/200" alt="Placeholder" />`

**Expected behavior:**

=> `<img src="http://place-hold.it/200" alt="Placeholder" draggable="false" />`

**Other information:**

From https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable:

`draggable` can have the following values:

* `true`: the element can be dragged.
* `false`: the element cannot be dragged.

This attribute is **enumerated and not Boolean**. A value of `true` or `false` is mandatory, and shorthand like `<img draggable>` is forbidden. The correct usage is `<img draggable="false">`.

**Suggested Solution:**

Fix the types so that it's `draggable?: 'true' | 'false'` instead, because as the docs state it's an enumerated attribute and not a Boolean attribute.

---

BTW I tried suggesting `draggable={"false" as any}` as a workaround, but that ends up being interpreted as truthy I guess, because it renders as `draggable="true"` 😅

---

Duplicate of #1441 which has been closed because the description wasn't very clear.

**Comment by simonhaenisch** [comment]
@manucorporat I think that happens automatically as the attribute is set?

<img src="https://user-images.githubusercontent.com/3410759/83667677-0e014900-a5cf-11ea-98a9-35c718e4a0f1.png" width="493">

**Comment by manucorporat** [comment]
What i meant is that stencil is working correctly setting the property, when you do:`draggable={false}`, even if the attribute is not visible. no?

**Comment by simonhaenisch** [comment]
No, it doesn't, but I can add a test for that in my PR?

**Comment by simonhaenisch** [comment]
<img width="1157" alt="Screen Shot 2020-06-03 at 7 51 52 PM" src="https://user-images.githubusercontent.com/3410759/83670640-c630f080-a5d3-11ea-8566-c9d6ac3d5317.png">

**Comment by cerkiner** [comment]
According to [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable#:~:text=The%20correct%20usage%20is%20%3Cimg,and%20links%20can%20be%20dragged.) text selections, images, and links can be dragged by default.

Absence of `draggable` attribute means false for many tags but true for `img` tag.  
When `<img draggable={false} />` is rendered as `<img />`, the output is the opposite of what is intended.

Furthermore, the boolean approach might not be the best dor this attribute according to [the same documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable#:~:text=This%20attribute%20is%20enumerated%20and%20not%20Boolean.)

**Comment by simonhaenisch** [comment]
> Furthermore, the boolean approach might not be the best dor this attribute according to [the same documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable#:~:text=This%20attribute%20is%20enumerated%20and%20not%20Boolean.)

I had already put that section in the initial issue description:

> This attribute is **enumerated and not Boolean**. A value of `true` or `false` is mandatory, and shorthand like `<img draggable>` is forbidden. The correct usage is `<img draggable="false">`.

But since MDN has this nice red warning box for it, maybe I'll put it here again as a screenshot 😂

<img src="https://user-images.githubusercontent.com/3410759/83729753-6163ad80-a648-11ea-8b56-64e27084c67f.png" width="688" />

@manucorporat Stencil currently also renders `draggable={true}` incorrectly as `draggable`, which you can see from the failing test of my PR:

```
● jsx › attributes › draggable › true

    expect(received).toBe(expected) // Object.is equality

    Expected: "<img draggable=\"true\">"
    Received: "<img draggable=\"\">"
```

**Comment by manucorporat** [comment]
This should fix it:
https://github.com/ionic-team/stencil/commit/0d72aeea51cb754615fed74020b035b1853ad740

Can you try 1.15.0-1?
