### ISSUE TITLE
Missing `toHaveLastReceivedEventDetail` convenience matcher

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#2488]
**Stencil version:**

```
 @stencil/core@1.14.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

There is no convenience method to assert on the last received event detail. [`toHaveNthReceivedEventDetail`](https://github.com/ionic-team/stencil/blob/22f3f23783e5bd0790c13c0e7f3720c0d7be28c0/src/declarations/stencil-private.ts#L2290) can be used in the meantime, but it would be nice to not have to manage the last event index.

**Expected behavior:**

Similar to [`toHaveFirstReceivedEventDetail`](https://github.com/ionic-team/stencil/blob/22f3f23783e5bd0790c13c0e7f3720c0d7be28c0/src/declarations/stencil-private.ts#L2284), having a `toHaveLastReceivedEventDetail` matcher would simplify assertions on the most recent event.

**Comment by tanner-reits** [comment]
This was included in today's [v4.19.0 release](https://github.com/ionic-team/stencil/releases/tag/v4.19.0)!
