### ISSUE TITLE
Rollup: Plugin Error Could not load undefined (imported by ./node_modules/xlsx/xlsx.js): The "path" argument must be of type string. Received undefined (plugin: lazyTypescriptPlugin, load)

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/stencil#2494]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

After update to stencil/core 1.14.0 I get this error.
**Expected behavior:**

**Steps to reproduce:**

Install that version of stencil code and try to import a package. It was working on previous versions.
**Related code:**

```tsx
import XLSX from 'xlsx';

```

It doesn't load the app and I get that error after Stencil attempts to build.

**Other information:**

**Comment by Bandito11** [comment]
I was told this by the authors of xlsx. I saw the @types for this in the Stencil package.json but the packages per se, I only saw rollup.js.

https://github.com/SheetJS/sheetjs/issues/1984#issuecomment-640276143

**Comment by peterpeterparker** [comment]
This seems like the same error as #2461

**Comment by peterpeterparker** [comment]
Fixed to me with v1.15. This issue can be closed I think.
