### ISSUE TITLE
Hardcoded app load timeout failing tests intermittently

### ISSUE THREAD

**Issue by carl-ellis** [ionic-team/stencil#2497]
The hardcoded timeout is causing intermittent failures on our tests.

https://github.com/ionic-team/stencil/blob/8a18112de392dfdd70529dcefdd8436cec29402a/src/testing/puppeteer/puppeteer-page.ts#L263

Causes:

```
App did not load in allowed time. Please ensure the content loads a stencil application.
      at waitForStencil (node_modules/@stencil/core/dist/testing/index.js:39878:15)
```

Adding this as a configurable value would make sense.

**Comment by bitflower** [comment]
Same here, can we make it configurable?

**Comment by bitflower** [comment]
Made a PR - for me locally it works from a local build.

I've triggered @adamdbradley on Slack reg. this.

**Comment by rwaskiewicz** [comment]
Closing, as this appears to have been fixed in https://github.com/ionic-team/stencil/commit/8b69731080efd5febab83620e6624870e4f45dc5. If the problem is still occurring, please feel free to open a new issue. Thanks!
