### ISSUE TITLE
 It's recommended to set the "main/module" property to "index.js/mjs"

### ISSUE THREAD

**Issue by dtaalbers** [ionic-team/stencil#2501]
**Stencil version:**

```
 @stencil/core@1.12.2<version>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Changing to the recommended settings breaks my project import.

**Expected behavior:**

Changing to the recommended settings should not break my project import.

**Steps to reproduce:**

**Related code:**

My stencil component project is called `@platform/ux`. The UX package is published to a private NPM feed. Via that feed I am able to install the UX package and import it into my other projects with `import '@platform/ux'`. At the moment it works fine when having the following settings in my package.json

```
"main": "dist/platform-ux.js",
"module": "dist/platform-ux.mjs",
"es2015": "dist/esm/platform-ux.mjs",
"es2017": "dist/esm/platform-ux.mjs",
"types": "dist/types/index.d.ts",
"collection": "dist/collection/collection-manifest.json",
"collection:main": "dist/collection/index.js",
"unpkg": "dist/platform-ux/platform-ux.js",
```

I do get the following warning in the console when using the UX package with above settings.

```
[platform-ux] Deprecated script, please remove: <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');</script>
To improve performance it is recommended to set the differential scripts in the head as follows:
<script type="module" src="platform-ux/platform-ux.esm.js"></script>
<script nomodule="" src="platform-ux/platform-ux.js"></script>
```

When I build the UX project I get the following warnings:

```
[ WARN  ]  Package Json: package.json:12:5
           package.json "main" property is set to "dist/platform-ux.js". It's recommended to set the "main" property to:
           ./dist/index.js

     L11:  "version": "1.0.17",
     L12:  "main": "dist/platform-ux.js",
     L13:  "module": "dist/platform-ux.mjs",

[ WARN  ]  Package Json: package.json:13:5
           package.json "module" property is set to "dist/platform-ux.mjs". It's recommended to set the "module" property
           to: ./dist/index.mjs

     L12:  "main": "dist/platform-ux.js",
     L13:  "module": "dist/platform-ux.mjs",
     L14:  "es2015": "dist/esm/platform-ux.mjs"
```
I think the warning in my console and warning in my build logs might be related so I though I would change it to the recommended file names. When I change the file names in the package.json to the following, the warnings disappear. But once the package is published the `import '@platform/ux'` in my other projects don't work anymore. No errors or whatsoever.

```
"main": "dist/index.js",
"module": "dist/index.mjs",
"es2015": "dist/esm/index.mjs",
"es2017": "dist/esm/index.mjs",
"types": "dist/types/index.d.ts",
"collection": "dist/collection/collection-manifest.json",
"collection:main": "dist/collection/index.js",
"unpkg": "dist/platform-ux/platform-ux.js",
```

Any idea on how to solve this? Sadly following the recommended settings just breaks my setup. Help would be appreciated!

**Other information:**

**Comment by rwaskiewicz** [comment]
Hey @dtaalbers 👋 

I apologize that it took so long for a member of the team to acknowledge this issue.  Without a reproduction case, it's tough for us to understand the exact nature of the issue. If you have the time/desire to put together a reproduction, we'd greatly appreciate it. If not, I completely understand. Thanks!
