### ISSUE TITLE
Support event properties in addition to addEventListener

### ISSUE THREAD

**Issue by elclanrs** [ionic-team/stencil#2504]
I asked [this question](https://forum.ionicframework.com/t/using-event-properties-instead-of-addeventlistener/189192) on the Ionic forum about a month ago, but not sure that was the right place. Re-posting here.

---

Currently, when using a Stencil web component you can add an event listener like:

```javascript
myComponent.addEventListener('foobar', fn);
```

Ideally, this should work too:

```javascript
myComponent.onfoobar = fn;
```

But currently it doesn’t work, and this prevents me from using the Stencil web component with JSX in other virtual-doms. As far as I know, this is because simple vdom implementations do not use addEventListener and instead assign to the event property so the events can be transferred more easily during patching.

Is this something that has been considered before? I think it would improve interoperability with other libraries, and also match the expectation that users have with native events.

**Comment by tanner-reits** [comment]
Apologies that this has been open so long without a response. That being said, looks like this hasn't gained much attention over the years. I'm gonna close this out, but if this is still something of interest, please feel free to open a new interest using the feature request template which may provide more context and visibility!
