### ISSUE TITLE
RFC: peer dependencies/external components config

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#2512]
## Problem

Not sure what to call this yet but the scenario is something like the following... I want to distribute a component that uses Ionic components:

```ts
import '@ionic/core';
import { h, Component } from '@stencil/core';

@Component({ tag: 'my-cmp' })
export class MyCmp {
  render() {
    return <ion-icon name="bulp" />;
  }
}
```

Building this as a `dist` will bundle `ion-icon` as a component and define it at runtime. Because of that it's not possible to use my component within another Stencil + Ionic project as there would be two `ion-icon` definitions. I'd rather want to specify that `@ionic/core` is a peer dependency.

## Proposal

I propose a new config option that allows to specify that `ion-icon` will already be defined and should not be bundled along with the dist... two options I see for doing that (open to naming suggestions):

```ts
export const config: Config {
  /* 1) */ peerDependencies: ['@ionic/core'],
  /* 2) */ externalComponents: ['ion-icon'],
}
```

1\) would not bundle any of the components that `@ionic/core` exposes, 2\) would just be a list of components to assume to be defined, and therefore always exclude from the bundle.

## Challenges

* If a Stencil + Ionic app uses `my-cmp` but doesn't use `ion-icon` elsewhere, Stencil wouldn't know that it needs to bundle `ion-icon`. But afaik all components (even unused ones) are bundled anyway?

## Workarounds

1. Don't `import '@ionic/core'` (or whatever distributed Stencil component library) and loose Intellisense for Ionic components. Then Stencil will take these components as defined, I assume?
2. Write a custom rollup plugin that removes the component library import.
3. Find a way to import the component library only for types, like in a declaration file.

I'll try these soon and see whether they are sufficient and convenient enough.

---

BTW there's a request for scoped custom element registries (https://github.com/w3c/webcomponents/issues/716) which would also solve this but afaik it's not even a proposal yet.

**Comment by lxg** [comment]
Not sure if I understand your situation correctly, but could the [`dist-custom-elements-bundle`](https://stenciljs.com/docs/custom-elements) target solve your problem?

It’s [somewhat broken](https://github.com/ionic-team/stencil/issues/2516) right now, but the general idea is that you can import only the components you need, assign your own element name, and tree-shake the ones you don’t need at build time.

**Comment by simonhaenisch** [comment]
Ionic is not distributed with that output target though? But yeah if it was, that could be an option!

**Comment by jdnichollsc** [comment]
@simonhaenisch thanks for your help mate! do you know if this proposal configuration can help with this other issue? https://github.com/proyecto26/ion-phaser/issues/18#issuecomment-640125339
