### ISSUE TITLE
Can't build with @rollup/plugin-replace

### ISSUE THREAD

**Issue by Sh1d0w** [ionic-team/stencil#2515]
**Stencil version:**

```
 @stencil/core@1.14.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
In one of our stencil projects we need to replace env variables from CLI parameters, thus we ended up adding https://www.npmjs.com/package/@rollup/plugin-replace . However the build then breaks with:

```
[ ERROR ]  Rollup: Parse Error: ./src/components/my-component.tsx:11:50
           Unexpected token (Note that you need plugins to import files that are not JavaScript)

     L10:  export class MyComponent implements ComponentInterface {
     L11:    @Prop() someProp: string;

[55:16.8]  build failed in 1.67 s
```

The plugin was added as the doc suggest before any other plugins:

```
rollupPlugins: {
    before: [
      replace({
        API_ENDPOINT: endpoint,
      })
    ]
  }
```

Adding it in `after` , or in `plugins` section still does produce errors.

**Expected behavior:**
The build does not break and successfully replaces all matches.

**Comment by gbbarroso** [comment]
I see you closed this, but I just had the same issue @Sh1d0w , what was the solution?

**Comment by antoniosZ** [comment]
@gbbarroso 

try
```
rollupPlugins: {
    before: [
      replace({
        API_ENDPOINT: JSON.stringify(endpoint),
      })
    ]
  }
```
