### ISSUE TITLE
Add quiet switch to stencil cli

### ISSUE THREAD

**Issue by lukeshay-sa** [ionic-team/stencil#2518]
**Stencil version:**

```
 @stencil/core@1.12.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

There is not a cli switch to quiet the output. It would be nice to have a switch for stencil build that would only print the result of the build.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by rwaskiewicz** [comment]
After giving this some thought, I don't know if this is something that we're interested in pursuing at this time. If anyone who's subscribed to this issue (or finds it later on) believes they have a use case, can you please open a new issue that describes your use case an the specific scenario(s) in which you're looking to quiet the output and what that would look like to you? (e.g. do errors show? do warnings? etc.). Thanks!
