### ISSUE TITLE
@Prop() does not handle null values correctly

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#252]
**Stencil version:**
```
 @stencil/core@0.0.6-21
```

**I'm submitting a:**
- [x] bug report

**Current behavior:**
If you specify component property values as `null` or `undefined` values they do not get initialized correctly.

**Expected behavior:**
It should be possible to specify a property as `null` or `undefined` and have the property value in the child component match the value specified in the parent component.

Since Stencil is providing a low level of component binding it is important that it handles all edge cases for values of any data type.

**Related code:**

```tsx
@Component({
    tag: 'my-component'
})
export class MyComponent {
    render() {
        const boolValue = null;
        const numValue = null;
        const strValue = null;
        const objValue = null;

        return (
            <div>
                 <my-child str={strValue} bool={boolValue} num={numValue} obj={objValue}  />
            </div>
        );
    }
}

@Component({
    tag: 'my-child'
})
export class MyChild {

    @Prop() str: string;
    @Prop() bool: boolean;
    @Prop() num: number;
    @Prop() obj: any;
    
    render() {
        console.log( this);
        return 'MyChild';
    }
}

```

**Other information:**

String properties
- Setting to `null` in the parent sets the value as "" (an empty string).  The property in the child component should be set to `null`.  Note: it is important to specifically set it to `null` vs. `undefined` since those are not the same value and there are cases where you need to be able to distinguish between the two.
- Setting to `undefined` sets the value as `"undefined"` (a string vs. an undefined value).  The property should be set to `undefined`.

Boolean properties
- Setting to `null` sets the value as `true`.  The value should be `null`.
- Setting to `undefined` sets the value as `true`.  The value should be `undefined`.

Number properties
- Setting to `null` sets the value as `NaN`.  The value should be `null`.
- Setting to `undefined` sets the value as `NaN`.  The value should be `undefined`.

Object properties
- Setting to `null` sets the value as `""` (empty string).  The value should be `null`.
- Setting to `undefined` sets the value as `"undefined"`.  The value should be `undefined`.

**Comment by adamdbradley** [comment]
We think we're getting this fix for what's in the `props` branch. Thanks for detailing this, we'll use this and make sure all our unit tests cover this. Thanks!

**Comment by adamdbradley** [comment]
This should be fixed in master, thanks
