### ISSUE TITLE
1.15.0-4 breaks boolean reflected properties behavior

### ISSUE THREAD

**Issue by jpzwarte** [ionic-team/stencil#2522]
```tsx
@Prop({ reflect: true }) hideLabel: boolean;
```

In 1.14.0 the following code results an a host element with *no* attribute when `!hideLabel` and `hide-label` when `!!hideLabel`. My CSS is written accordingly: `:host([hide-label]) { ... }`.

In 1.15.0-4 the following code results in a host element that *always* has a `hide-label` attribute, but without any value when `!!hideLabel` and `hide-label="false"` when `!hideLabel`.

I assume this is some sort of regression?

**Comment by jpzwarte** [comment]
I can trace it to this commit + line: https://github.com/ionic-team/stencil/commit/0d72aeea51cb754615fed74020b035b1853ad740#diff-819778c11515eb2f58b160e2d1cbf9d0R126
cc @manucorporat 

At the moment it does `if (newValue !== false || elm.getAttribute(memberName) === '') {`, in the DOM, i can see `hide-label="false"` (memberName === 'hide-label'). So the if statement is false, and the attribute is not removed.

**Comment by jerrod** [comment]
👍 This issue is blocking us from updating - have you found any reasonable workarounds @jpzwarte

**Comment by jpzwarte** [comment]
@jerrod Nope, I started setting the attribute myself (and removed `reflect: true` from `@Prop`):

```
<Host
        disabled={this.disabled ? true : null}
        has-anchor={this.hasAnchor ? true : null}
        has-icon={this.hasIcon ? true : null}
        tabindex={this.disabled ? -1 : this.tabOrder}
      >
```

There seems little interest in restoring the behavior from 1.14.0 cc @adamdbradley

**Comment by bjolletz** [comment]
I've run into this issue as well. It's certainly not consistent that `myBooleanProp=true` reflects to `myBooleanProp` while `myBooleanProp=false` reflects to `myBooleanProp=false`. And as the OP says, this breaks CSS attribute styling like `:host([myBooleanProp])`.

**Comment by tanner-reits** [comment]
Hey all! Sorry this issue has sat so long.

If anyone here is still experiencing this problem, please update the issue with a minimum reproduction repo (this helps the team verify issues and gives us something to reference when we go to resolve the problem). Otherwise, we'll look to close this out in the near future. Sorry again for the delay!
