### ISSUE TITLE
The namedExports option from "@rollup/plugin-commonjs" is deprecated

### ISSUE THREAD

**Issue by milottit** [ionic-team/stencil#2523]
**Stencil version:**
```
 @stencil/core@1.14.0
```

**I'm submitting a:**

[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

stencil.config.ts allows to specify commonjs plugin option. Firstly, only `namedExports` is allowed in `commonjs?: BundlingConfig. Secondly, the `namedExports` option is deprecated in `@rollup/plugin-commonjs`.

Running `stencil build`, the following message is shown:

```
[ WARN  ]  Bundling Warning PLUGIN_WARNING
           The namedExports option from "@rollup/plugin-commonjs" is deprecated. Named exports are now handled
```

Looking at the `@rollup/plugin-commonjs` code [commonjs/src/index.js](https://github.com/rollup/plugins/blob/master/packages/commonjs/src/index.js#L115), the option is ignored. So it is really misleading and error prone when updating the version up as it was working before.

**Expected behavior:**

Remove namedExports from `BundlingConfig` and show an error message. And if possible, allow the other commonjs options.

**Comment by rwaskiewicz** [comment]
The fix for this issue has been released as a part of today's [Stencil v4.0.2 release](https://github.com/ionic-team/stencil/releases/tag/v4.0.2). We've officially deprecated the field and marked it as such in our documentation site. To avoid a (small) breaking change, we will not remove this field until Stencil v5
