### ISSUE TITLE
Fix e2e readiness flag on slow or overloaded computers

### ISSUE THREAD

**Issue by dcylabs** [ionic-team/stencil#2524]
**Stencil version:**

```
 @stencil/core@1.14.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running e2e tests on slow, or overloaded computers, the stencilReady flag may not be triggered and got this error :  
```
  ● my-component › should display icon

    App did not load in allowed time. Please ensure the content loads a stencil application.
```

**Expected behavior:**
`window.stencilAppLoaded` should be initialized even on slow or overloaded computers.

**Steps to reproduce:**
* Use a standard computer as a GitLab Runner. 
* Launch 1 test pipeline => Success 
* Launch 3 or 4 tests pipelines simultaneously => The error occurs randomly

**Related code:**

Code that triggers the stencil readiness : 
```typescript
// puppeteer-events.ts
// ... 
  const stencilReady = () => {
    return allReady()
      .then(() => waitFrame())
      .then(() => allReady())
      .then(() => {
        ((window as unknown) as pd.BrowserWindow).stencilAppLoaded = true;
      });
  };
// ... 
  if (window.document.readyState === 'complete') {
    stencilReady();
  } else {
    window.addEventListener('load', stencilReady);
  }
}
```

What leads me to this conclusion is that when analysing the readyState flow : 
```
loading > interactive > loaded 
``` 

It seems that on overloadded computers, you can fall into a *hole* that you are not in the `complete` readyState, but the `load` event is fired before the `else` block is executed and the listener attached. 

As recommended by [mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#readystatechange_as_event_listener_to_insert_or_modify_the_DOM_before_DOMContentLoaded) it would be better to use this syntax. 

```typescript
  if (window.document.readyState === 'complete') {
    stencilReady();
  } else {
    document.addEventListener('readystatechange', function (e) {
      if ((e.target as Document).readyState == "complete") {
        stencilReady();
      }
    }, false);
  }
```

**Other information:**

I'm preparing a PR to use the mozilla recommendations

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/stencil/pull/2525
