### ISSUE TITLE
Property 'my-component' does not exist on type 'JSX.IntrinsicElements'.

### ISSUE THREAD

**Issue by ianldgs** [ionic-team/stencil#2527]
**Stencil version:**

```
 @stencil/core@1.12.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When using web components in storybook and TypeScript (or even JavaScript + using TypeScript to check js files), I get the error:
```
Property 'my-component' does not exist on type 'JSX.IntrinsicElements'.
```
However, I don't think this has anything todo with storybook. It's the fact that it's a react project, using stencil components without `react-output-target`.

**Expected behavior:**
No errors, TypeScript build/check sucessful.

**Steps to reproduce:**
Create a stencil starter project, integrate with storybook using [this tutorial](https://paulcpederson.com/articles/stencil-storybook/), use TypeScript to check the code and get autocomplete.

**Related code:**
React component:
```tsx
export function story() {
  return <my-component></my-component>;
}
```
tsconfig of the project that uses the stencil components:
```json
{
  "compilerOptions": {
    "module": "ES6",
    "typeRoots": ["../experimental/dist/types/index.d.ts"],
    "allowJs": true,
    "noEmit": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "moduleResolution": "node"
  },
  "exclude": ["node_modules"],
  "include": ["./globals.d.ts", "../experimental/dist/types/index.d.ts", "./stories/**/*"]
}

```

**Other information:**
The fix should be simple. I'm editing `component-lib/dist/components.d.ts` manually and replacing:
`declare module '@stencil/core'` with `declare global` and it works.
Is there a reason why this isn't `global`?
https://github.com/ionic-team/stencil/blob/8391b1d552ef08611ff478cebcaba803199c4270/src/compiler/types/generate-app-types.ts#L112

I also tried to do a local fix, by creating a `index.d.ts` and putting:
```ts
import type { JSX } from "@stencil/core";

type LocalIntrinsicElements = JSX.IntrinsicElements;

declare global {
  namespace JSX {
    interface IntrinsicElements extends LocalIntrinsicElements {}
  }
}
```

But in this case, `"@stencil/core"` gets replaced with `"./stencil-public-runtime"`, and my component defitions aren't in this file.

**Comment by ianldgs** [comment]
Ok, just realized that I can't really use those definitions in react projects, because in react, for example, you don't use `class=`, it's `className=`.
I believe those are meant for stencil projects that use other stencil projects.

**Comment by TiagoFuelber** [comment]
I am going through the same problem, does anyone found a solution for this?

**Comment by angelangelov88** [comment]
The only solution I found is to declare the types manually in my consuming app src/components.d.ts
