### ISSUE TITLE
`abbr` attribute is missing from type definition for <th>

### ISSUE THREAD

**Issue by WickyNilliams** [ionic-team/stencil#2530]
**Stencil version:**

```
@stencil/core@1.14.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The following code results in a type error:

```jsx
<th abbr="Monday">Mo</th>
```

**Expected behavior:**
The code should not result in a type error. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-abbr

**Steps to reproduce:**
Try to render the above

**Comment by aburkowsky9** [comment]
Id like to submit a PR for this one. Should be a pretty simple fix to add here: https://github.com/ionic-team/stencil/blob/b47093b2f86be777c39f79abc691a8a6d1ec50d7/src/declarations/stencil-public-runtime.ts#L1176

**Comment by WickyNilliams** [comment]
I only just saw you made a PR for this. Thanks @aburkowsky9!
