### ISSUE TITLE
cannot use Template literals for the component's tag

### ISSUE THREAD

**Issue by antoniosZ** [ionic-team/stencil#2540]
**Stencil version:**
```
@stencil/core@1.15.0
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
cannot use a Template Literal (template string) as the component tag.
it throws `tag missing in component decorator` because it checks the type of the property's value.

**Expected behavior:**
it should allow Template Literal (template string) as the component tag.

ie. working on unstable code, that the tag format hasn't been finalized, it would be helpful to be able to have a constant for the tag prefix of all components. This would make it easier to change, versus having to do a search and replace of the string...

**Steps to reproduce:**

**Related code:**

```tsx
...
const prefix: string = 'my-prefix-';
...
@Component({
  tag: `${prefix}button`,
  shadow: true,
})
...
```

**Other information:**
https://github.com/ionic-team/stencil/blob/v1.15.0/src/compiler/transformers/decorators-to-static/component-decorator.ts#L94
`if (typeof tag !== 'string' || tag.trim().length === 0) {` returns true, because `typeof tag` returns `NodeObject` for Template Literals, instead of string.

**Comment by adamdbradley** [comment]
Sorry but the component tag name must be a static value.
