### ISSUE TITLE
Testing chained events on shadowDom

### ISSUE THREAD

**Issue by bfleischer-alti** [ionic-team/stencil#2542]
**Stencil version:**

```
 @stencil/core@1.12.2
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When testing fired events by nested shadow dom elements, the chain of events is broken

**Expected behavior:**
Chained events work correctly, and the parent component's event (shown below) is triggered in the document.

**Steps to reproduce:**

**Related code:**

Child Component:
```
@Component({
  tag: 'child-comp',
  styleUrl: 'child.css',
  shadow: true
})
export class Child {

  @Event() childEvent: EventEmitter

  onClick = (e) => {
    this.childEvent.emit(e)
  }

  render() {
    return (
      <button id="child" onClick={this.onClick}>
        <p>Hello Child!</p>
      </button>
    );
  }
}
```
Parent component
```
@Component({
  tag: 'parent-comp',
  styleUrl: 'parent.css',
  shadow: true
})
export class Parent {

  @Event() parentEvent: EventEmitter

  @Listen('childEvent')
  childEmitted() {
    console.log('Child event fired')
    this.parentEvent.emit();
  }

  render() {
    return (
      <div>
        <p>Hello Parent!</p>
        <child-comp></child-comp>
      </div>
    );
  }
}
```

Spec:
``` 
describe('change event', () => {
  it('should emit selected date', async () => {
    const page = await newSpecPage({
      components: [Parent, Child],
      html: `<parent-comp></parent-comp>`,
    });

    const root = page.body.querySelector('parent-comp').shadowRoot;
    console.log(root)
    const childComp = root.querySelector('child-comp');
    console.log(childComp)
    const btn = childComp.shadowRoot.querySelector('button');
    const click = jest.fn();
    page.doc.addEventListener('parentEvent', click);
    btn.click();
    await page.waitForChanges();

    expect(click).toHaveBeenCalled();
  });
});
```

**Other information:**

**Comment by christian-bromann** [comment]
@bfleischer-alti thanks for raising the issue. At this point the Stencil team recommends to evaluate the migration to alternative testing tools such as WebdriverIO or Playwright. We have been working in better integration for these tools which help you to test your components in real browser environments instead of using Stencils DOM reimplementation.

Let me know if you have any further questions.
