### ISSUE TITLE
target: es5 empties components.d.ts

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#2544]
**Stencil version:**

```
 @stencil/core@1.15.0 (happens since v1.10.0)
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
When setting `"target": "es5"` in `tsconfig.json`, the generated `components.d.ts` loses type information of all components.

**Expected behavior:**
`components.d.ts` should *always* be generated.

**Steps to reproduce:**
```js
// 1. edit tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    // ...
}

// 2. run "stencil build"
```

**Comment by manucorporat** [comment]
Please always use the es2017 target, and let stencil generated the es5 build in production.
Stencil always generate a es5 build in production, or also in dev mode if the --es5 flag is set
