### ISSUE TITLE
Named export not imported after upgrading to  @stencil/core@1.15.0

### ISSUE THREAD

**Issue by rishikeshjoshi** [ionic-team/stencil#2545]
**Stencil version:**
```
 @stencil/core@1.15.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
- I recently upgraded from version: @stencil/core v1.8.0) to the version 1.15.0.
- The component uses a third-party dependency which has a default export and other named exports
- When using the version @stencil/core v1.8.0, the dependent classes were imported correctly after adding the plugin as below:
```
commonjs: {
        namedExports: {
            'eyeson': ['StreamHelpers']
        }
},
```
- However after upgrading to 1.15.0, its seen that I get errors suggesting that the named exports weren't imported.
- I also noticed that there's a warning message saying that the plugin @rollup/plugin-commonjs is deprecated and the named exports are handled automatically and removed the plugin, but the result was the same.

**Expected behavior:**
- Named exports should be imported successfully after the upgrade

**Steps to reproduce:**

**Related code:**

```tsx
//Component using a 3rd party library - eyeson
//Named export exported by the eyeson library.
import { StreamHelpers } from "eyeson";

//The below log statement prints **undefined** after upgrading to @stencil/core@1.15.0
console.log('StreamHelpers', StreamHelpers);

//Error after upgrading: TypeError: Cannot read property 'enableAudio' of undefined.
StreamHelpers.enableAudio(this.localStream);
```

**Other information:**
- Rollup plugin was added as referenced on this link: [Rollup Plugin](https://github.com/ionic-team/stencil/issues/1343#issuecomment-511108353)

**Comment by rwaskiewicz** [comment]
Hey folks,

I apologize that it took so long for someone on the team to acknowledge this issue. Unfortunately, this issue predates the current team, and some of the context is lost on us. If anyone who is willing and able to create a minimal reproduction case using the latest version of Stencil for us to take a look at, it'd be greatly appreciated. Once again, I apologize that this issue sat for so long.
