### ISSUE TITLE
Error with Inputmask and stencil@1.15.0

### ISSUE THREAD

**Issue by de-dan** [ionic-team/stencil#2546]
**Stencil version:**

```
 @stencil/core@1.15.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

After upgrading from 1.14.0 I get an error with [Inputmask](https://github.com/RobinHerbots/Inputmask)-libraray. See error below:
````
DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "input-mask" has already been used with this registry
````
My component is not rendered.

**Expected behavior:**

No errors are thrown, and the component is rendered, as in Version 1.14.0

**Steps to reproduce:**

1. Create a new Stencil project
2. add Inputmask `npm i inputmask@5.0.3`
3. Create a component and import input mask
````
import Inputmask from 'inputmask';
@Component({
    tag: 'my-input'
})
export class Input {
Inputmask;
...
}
````
4. Run stencil ("start": "stencil build --dev --watch --serve")

**Comment by de-dan** [comment]
Successful retested with 1.17.2

**Comment by dtaalbers** [comment]
@de-dan Is this still working for you? I am on `2.0.3` but I am getting the error you had gotten. 

```
Failed to execute 'define' on 'CustomElementRegistry': the name "input-mask" has already been used with this registry
```

**Comment by de-dan** [comment]
Hey, @dtaalbers
I had the same issue. The only thing I could do was downgrading Inputmask to 5.0.3. There is already an issue opened on the Inputmask repo, which you should push.

Regards,
Daniel

**Comment by dtaalbers** [comment]
Ah ok, yeah found a different workaround.

```
import 'inputmask';
window.Inputmask('mask', { placeholder: 'placeholder' }).mask('a input);
```

🙄  Guess I'll have to wait for a `inputmask` fix then!
