### ISSUE TITLE
Support multiple globalStyle

### ISSUE THREAD

**Issue by reda-alaoui** [ionic-team/stencil#2550]
**Stencil version:**
```
 @stencil/core@1.15.0
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
We can pass a single `globalStyle` to Stencil.

**Expected behavior:**
I have a collection of web components with shadow dom disabled. I use SASS.
I want to output one css file per theme.

**Comment by AThiyagarajan** [comment]
Yep, good to have this feature.

**Comment by rwaskiewicz** [comment]
👋 I apologize that this issue hasn't been officially acknowledged by a member of the team and has sat in limbo while it and #497 stayed open, which #2552 was closed. At this time, we don't plan on pursuing this feature request. As a result, I'm going to close this out to keep our stance consistent with #2552. Thanks!
