### ISSUE TITLE
SyntaxError: Identifier '__extends' has already been declared (11501:9)

### ISSUE THREAD

**Issue by ps011** [ionic-team/stencil#2553]
**Stencil version:**

```
 @stencil/core@1.15.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I have created a collection of web components and in that, I have created a Chart/Data Visualization component for which I have used Vega Charts Library. When I compiled the project and used that as a node module inside my react application, it threw a compilation warning. Which looked like this: 

SyntaxError: Identifier '__extends' has already been declared (11501:9)

  11499 |     return extendStatics(d, b);
  11500 | };
> 11501 | function __extends(d, b) {
        |          ^
  11502 |     extendStatics(d, b);
  11503 |     function __() { this.constructor = d; }
  11504 |     d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Expected behavior:**
There should not be any warning.

**Steps to reproduce:**
1. Create a web component
2. Compile that using Stencil
3. Add Vega Charts dependency to it
4. Compile again
5. Install this component as a node module inside a react application
6. Start the app.

**Comment by safalkishore** [comment]
@ps011 did you have any leads on this issue ? Found a similar issues logged [here](https://github.com/ionic-team/stencil/issues/2807).

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize it took so long for someone on the team to acknowledge this issue. If you’re willing/able, would you be able to create a minimal reproduction case for the team? If not, I completely understand. Again, I apologize for the lack of response here
