### ISSUE TITLE
'stencil build' error after updating from 1.15.0 to 1.16.0 (android, termux)

### ISSUE THREAD

**Issue by ajmchambers** [ionic-team/stencil#2565]
Bit of an unusual setup but have been doing some development with stencil on Android via Termux (node v14.4.0).

After updating stencil from 1.15.0 to 1.16.0 I get the following error after running `"stencil build --dev --watch --serve"`:

```
/node_modules/@stencil/core/sys/node/index.js:434
  cpuModel: s[0].model,
                 ^
TypeError: Cannot read property 'model' of undefined
  at createNodeSys (/node_modules/@stencil/core/sys/node/index.js:434:22)
  at Object.createNodeSysWithWatch (/node_modules/@stencil/core/sys/node/index.js:1294:40)
  at Object.<anonymous> (/node_modules/@stencil/core/bin/stencil:47:23)
```

This seems to be an issue because `os.cpus()` is returning the value `[]`

(It appears to have also returned `undefined` in the past according to this issue: https://github.com/termux/termux-packages/issues/1798)

Part of the code that has changed is here: https://github.com/ionic-team/stencil/commit/9d27e2d00a295b4ed3f4aa2523ee6c5e37fbbaea#diff-ae24169c4a161afc393d3aa065567366L288

Understandably termux on android (chromebook too?) is pretty niche, though would be awesome to have this working again.

**Comment by adamdbradley** [comment]
Closed from https://github.com/ionic-team/stencil/commit/05ea6dfb61be3cd64dad1abc86e4d88a338ee961
Thanks
