### ISSUE TITLE
dist-custom-elements-bundle output depends on @stencil/core/internal/client

### ISSUE THREAD

**Issue by edtownend** [ionic-team/stencil#2566]
**Stencil version:**

```
@stencil/core@1.16.0 
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The first line of the output from the dist-custom-elements-bundle output target  in `/dist/custom-elements/index.js` is:
```
import { attachShadow, createEvent, h, readTask, Host, proxyCustomElement } from '@stencil/core/internal/client';
```
This means when importing the build in another project I get the following error: `Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'xxx.../dist/custom-elements'`

**Expected behavior:**
I don't think the built components should require any additional dependencies?

**Steps to reproduce:**
Build a project with the dist-custom-elements-bundle output target
Import in another project: `import { MyComponent } from 'my-component/dist/custom-elements';`

**Related code:**

stencil.config.ts
```tsx
import { Config } from '@stencil/core';
import { sass } from '@stencil/sass';
import { inlineSvg } from 'stencil-inline-svg';

export const config: Config = {
  namespace: 'my-app',
  taskQueue: 'async',
  plugins: [sass(), inlineSvg()],
  devServer: {
    openBrowser: false,
  },
  outputTargets: [
    {
      type: 'dist-custom-elements-bundle',
    },
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
  ],
};
```

**Other information:**

**Comment by adamdbradley** [comment]
Yes, for a custom elements build, `@stencil/core` will have to be a dependency of your project.

**Comment by MotassemJa** [comment]
> Yes, for a custom elements build, `@stencil/core` will have to be a dependency of your project.

Can it be added only as a devDependency?
