### ISSUE TITLE
Option to disable logging failed requests during E2E tests

### ISSUE THREAD

**Issue by mihar-22** [ionic-team/stencil#2572]
**Stencil version:** 1.16.0

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request 

**Current behavior:**

Currently it defaults to logging errors to the console when requests abort/fail in E2E tests.

**Expected behavior:**

I'm writing tests for a video player and sometimes there are requests lingering at the end of my tests from buffering frames and other stuff. I'd like an option when creating `newE2EPage` to to stop the errors from logging.

Maybe an option to disable requests that were simply aborted `req.failure()?.errorText === 'net::ERR_ABORTED'` would be more specific?

**Related code:**

https://github.com/ionic-team/stencil/blob/b47093b2f86be777c39f79abc691a8a6d1ec50d7/src/testing/puppeteer/puppeteer-page.ts#L141

**Comment by christian-bromann** [comment]
Hey @mihar-22 👋 

sorry for getting back to you with a 4 year delay but I raised a PR that will enable this capability.

**Comment by tanner-reits** [comment]
This was included in today's [v4.19.0 release](https://github.com/ionic-team/stencil/releases/tag/v4.19.0)!
