### ISSUE TITLE
Importing stencil web component build mjs file in Angular

### ISSUE THREAD

**Issue by Swappea** [ionic-team/stencil#2573]
**Stencil version:**
```
 -- @stencil/core@1.12.2
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
In stencil config file, I have specified output Target type as "dist-custom-elements-bundle". This generates 2 files with .mjs  extension. I am not able to integrate this component with angular. Angular doesn't recognize this as a module. What should be the steps to use this?

**Expected behavior:**
Should be able to import mjs file and use the webcomponent.

**Related code:**

```tsx
import { HelloWorld } from '../../bh-hello-world/dist/custom-elements-bundle/index.mjs';
```

**Comment by anupbui** [comment]
In stencil.config.ts and below import after `npm install @stencil/X-output-target`
```
import { angularOutputTarget, ValueAccessorConfig } from '@stencil/angular-output-target';
import { reactOutputTarget } from '@stencil/react-output-target';
import { vueOutputTarget, ComponentModelConfig } from '@stencil/vue-output-target'; 
```

AND add in outputTarget array

```angularOutputTarget({
      componentCorePackage: 'your-web-component-name',
      directivesProxyFile: './angular-lib/component/your-web-component-name.ts',
      valueAccessorConfigs: angularValueAccessorBindings
    }),
 ```

Please follow the steps mentioned below.
https://github.com/ionic-team/stencil-ds-angular-template

Download zip or fork this template and copy paste output of /angular-lib in your earlier project. 
Do changes for importing your web component and run `npm install` and then run `npm run dist` check the output directory of dist for angular component
