### ISSUE TITLE
Bug: `hydratedFlag` config option does not work

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2574]
**Stencil version:**

```
 @stencil/core@1.16.2
```

**Note:** last working version from my testing is 1.13.0

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Add the following to the `stencil.config.ts` file:

```typescript
  hydratedFlag: {
    selector: 'attribute',
    name: 'calcite-hydrated'
  },
```

Any of your rendered components will no longer be displayed because rather than having the appropriate markup of:

```html
<kws-temperature temperature="273.15" scale="C" calcite-hydrated=""></kws-temperature>
```

It has the markup of:

```html
<kws-temperature temperature="273.15" scale="C" hydrated=""></kws-temperature>
```

Note that the attribute name is wrong.

Examining the Stencil build output, it appears that we changed the code that applies the hydrated attribute / class so this code here no longer does anything: https://github.com/ionic-team/stencil/blob/master/src/compiler/bundle/core-resolve-plugin.ts#L96-L101

**Expected behavior:**
The proper class or attribute is applied based on the stencil config `hydratedFlag` value if applicable.

**Steps to reproduce:**
A repro case can be found here: https://github.com/driskull/stencil-component-starter

I also replicated this in my training project (https://github.com/kensodemann/kws-weather-widgets) by:

- adding the config above
- installing newer version of `@stencil/core` until it broke (last version to work was `1.13.0`)

**Comment by adamdbradley** [comment]
Closed by https://github.com/ionic-team/stencil/commit/013ca8c8ae79ea76ae8fe78daf4d856c96cb6454
