### ISSUE TITLE
When using > `@stencil/core@1.15.0`, am experience two odd runtime errors

### ISSUE THREAD

**Issue by chrisweight** [ionic-team/stencil#2577]
**Stencil version:**
```
@stencil/core@1.16.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
In https://github.com/chrisweight/jsonschema-build-failure (a sample repo demonstrating a build error in an RxDB dependency I have since had advice on how to work around), when building with `stencil/core@1.16.2` and `stencil/core@1.16.3` I receive the following error in the console:

![image](https://user-images.githubusercontent.com/468638/87695925-0b763f80-c788-11ea-8251-94dec929f95e.png)

With a blank screen, no build errors are thrown, however there are a good number of `Bundling Warning UNRESOLVED_IMPORT` build warnings for the `rxdb` dependency. 

If I comment out the call to `await Database.instance().init()` then the build runs without issue.

Similarly, if I roll back to `@stencil/core@1.15.0`, the build functions as expected, with no errors.

**Expected behavior:**

The app should build and run without errors.

**Steps to reproduce:**

```
git clone https://github.com/chrisweight/jsonschema-build-failure
cd ./jsonschema-build-failure
npm i
npm start
```

**Related code:**
https://github.com/chrisweight/jsonschema-build-failure

**Other information:**
Originally came about investigating build errors that appeared to be due to the `rxdb` dependency and its dependents.
Reported here: https://github.com/pubkey/jsonschema-key-compression/issues/114

**Comment by glenveegee** [comment]
Getting the same when running 1.16.x

**Comment by glenveegee** [comment]
looks like @stencil/core@1.16.4 fixes this issue

**Comment by chrisweight** [comment]
Yep, it appears to, though I'm now in a world of hurt with other errors :(

**Comment by glenveegee** [comment]
What other errors

**Comment by denyo** [comment]
Dupe of #2554

**Comment by chrisweight** [comment]
> I'm curious to know what other errors? I've been through the wringer following an upgrade to 1.16.x so I might be able to help. At the very least I'll be able to sympathise.

Managed to get things building in the end, involved much npm cache clearing and having to fudge other dependency imports
