### ISSUE TITLE
Error: vNode passed as children has unexpected type. 

### ISSUE THREAD

**Issue by deepakrout** [ionic-team/stencil#2579]
Why am I getting this error?

**Stencil version:**

stencil-component@0.0.1 /Users/der9078/nodeProjects/stencil-component/stencil-component
└── @stencil/core@1.12.2 

```
"devDependencies": {
    "@stencil/core": "^1.12.2",
    "@stencil/sass": "^1.3.2"
  },
```

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
```
stencil vNode passed as children has unexpected type.
Make sure it's using the correct h() function.
Empty objects can also be the cause, look for JSX comments that became objects.
```

**Expected behavior:**
Should compile successfully

**Steps to reproduce:**

**Related code:**

```tsx
import { Component, h, Prop } from "@stencil/core";
 
 
@Component({
    tag: 'dk-side-drawer',
    styleUrl: 'side-drawer.scss',
    shadow: true
})
 
export class SideDrawer {
    @Prop({reflect: true}) drawerTitle: string;
    @Prop({reflect: true, mutable: true}) open: boolean;
 
    onCloseDrawer() {
        this.open = false
    }
 
    render() {
       
        return (
            <aside>
                <header>
                    <h1>{this.drawerTitle}</h1>
                    <button onClick={ this.onCloseDrawer.bind(this) }>X</button>
                </header>
                <main>
                    <slot/>
                </main>
            </aside>
        );
    }
}
```

**Other information:**

<img width="413" alt="Screen Shot 2020-07-17 at 9 34 32 PM" src="https://user-images.githubusercontent.com/7481986/87841728-6afe4900-c875-11ea-9508-2c64f2fda3ea.png">

**Comment by max-scopp** [comment]
Please use Stencil's Slack channel for support from the community. This is a common error and very much an user error.

But I believe this specific one is not caused from that component, as it works on 1.17 and apart that inefficient bound context, there is nothing special to it.

**Comment by deepakrout** [comment]
Thanks for your response! This error seems to be random. It can appear while in the process of live-reload and can crash the application. But, if you kill the application and re-start, application works fine again. BTW, subsequently the error can re-occur and you have to repeat the same step.

Not sure what is the user error here though; such a basic code here.
