### ISSUE TITLE
Stencil error on production site

### ISSUE THREAD

**Issue by Firebrand** [ionic-team/stencil#2581]
I use Stencil in production and recently this error popped up, sending my entire site to a grinding halt.
How do I completely avoid this in the future?

![image](https://user-images.githubusercontent.com/7831979/87962630-19c0a600-ca7d-11ea-9ce3-0a3d3bcc48cb.png)

**Comment by bitflower** [comment]
Just change it once? I think it won't change any time soon again.

**Comment by Firebrand** [comment]
Thanks @bitflower but that's not going to work for me. I'm using Stencil on the client-facing site of a huge corporation. 5 minutes of downtime could mean millions of dollars of lost transactions.

**Comment by wjhdev** [comment]
Unfortunately I've experienced reasonably frequent breaking changes on @stencil/core upgrade as well. As is the nature of a v1 piece of software.

I'd suggest updating stencil on a staging site or locally before deploying updates in production. This should help catch breaking changes before they cause downtime.

**Comment by Firebrand** [comment]
@wjhdev Yeah that's what happened in my case. We have enough testing/qa/dev etc. layers in place and safeguards to prevent anything huge but I was just wondering if there was a more elegant way to just disable Stencil's non-graceful error msgs altogether.

**Comment by simonhaenisch** [comment]
@Firebrand this info should only show up for dev builds. Can you confirm that you didn't use the `--dev` flag when deploying your production app?

**Comment by rwaskiewicz** [comment]
Hey @Firebrand 👋 

I apologize it took so long for someone to acknowledge this issue. Although I can't say for sure what the circumstances around how this happened without your knowledge on your site, I apologize for any inconvenience this caused.

It appears the verbiage here was introduced in 56b1b221, so I'm not entirely sure how this happened almost a year later.

If this is continuing to happen sporadically and is able to be reproduced, please feel free to open a new ticket with a minimal reproduction case.

 Thanks!
