### ISSUE TITLE
Issue loading component via script tag in Firefox when using file URI

### ISSUE THREAD

**Issue by kwchan22** [ionic-team/stencil#2582]
**Stencil version:**

```
 @stencil/core@1.16.4 (1.15.x and above)
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I open the html file that loads the components in Firefox (Ex: file:///Users/test/development/test.html), I get
**TypeError: null is not a valid URL.**

**Expected behavior:**
Components loaded successfully.

**Steps to reproduce:**
1) npm init stencil
2) Pick component
3) npm run build
4) Create a html file
```
<html lang="en">
<head>
  <script src="test-stencil.js"></script>
</head>
<body>
  <test-component></test-component>
</body>
</html>
```
5) Open file in Firefox.

**Related code:**

**Other information:**
In Firefox, I see the error occurs at **window.location.origin** in test-stencil.js and it is null.
```
var resourcesUrl = scriptElm ? scriptElm.getAttribute('data-resources-url') || scriptElm.src : '';
var start = function() {
    var url = new URL('./p-7af54b95.system.js', new URL(resourcesUrl, window.location.origin)); 
    System.import(url.href);
};
```

When using @stencil/core@1.14.0 and below, there is no window.location.origin in test-stencil.js and it works in Firefox
```
var resourcesUrl = scriptElm ? scriptElm.getAttribute('data-resources-url') || scriptElm.src : '';
var start = function() {
    var url = new URL('./p-ce5723e7.system.js', resourcesUrl);
    System.import(url.href);
};
```

**Comment by kwchan22** [comment]
The #2410 fix  in **src/compiler/output-targets/dist-lazy/generate-system.ts** is causing this issue. 
It changed this
`var url = new URL('${corePath}', resourcesUrl);`
  to
`var url = new URL('${corePath}', new URL(resourcesUrl, window.location.origin));`

In Firefox, when using file URI, window.location.origin is null.

**Comment by jasperbosch** [comment]
In case of a iframe without `src`-attribute `window.location.origin` will be `"null"` (yes a string with value "null").
In case of a iframe without `src`-attribute `window.parent.location.origin` should be used.
