### ISSUE TITLE
Parent component don't emit children events

### ISSUE THREAD

**Issue by vinioo** [ionic-team/stencil#2586]
**Stencil version:**
@stencil/core@1.16.2

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If i have a parent component that implements a children component and both components are ```shadow: true```, all the events emitted by the children component aren't catchable by the DOM event listener in an **external** project (It works on the stencil development mode).

**Expected behavior:**
The parent component should re-emit all the events emitted by a children component.

**Steps to reproduce:**
The components above are a reduced representation of the original components. I have a parent input and a new component that implements this parent input. This new component should emit all the events emitted by the root input component, but this is not happening outside the Stencil project.

**Related code:**

Children component:
```tsx
@Component({
  tag: 'bds-input',
  styleUrl: 'input.scss',
  shadow: true,
})
export class Input {
  /**
   * Emitted when the input has changed.
   */
  @Event() bdsInput!: EventEmitter<KeyboardEvent>;

  private onInput = (ev: Event): void => {
    const input = ev.target as HTMLInputElement | null;
    if (input) {
      this.value = input.value || '';
    }
    this.bdsInput.emit(ev as KeyboardEvent);
  };

  render(): HTMLElement {
    return <input onInput={this.onInput}></input>;
  }
}
```

Parent component:
```tsx
@Component({
  tag: 'bds-input-password',
  styleUrl: 'input.scss',
  shadow: true,
})
export class InputPassword {
  render(): HTMLElement {
    return <bds-input></bds-input>;
  }
}
```

The <bds-input-password> should emit all the <bds-input> events.

**Other information:**
I fixed this scenario adding scoped: true and removing shadow: true in the parent component. 

My question is, I think it is a bug related to something at the build of the project because I am able to listen to the events on the development mode, and outside it, in an Angular project I'm not able to catch the custom event ```bdsInput```.

I'd like to know if it should be this way or if it is a limitation caused by the shadow dom. Thank you!

**Comment by glenveegee** [comment]
You'll probably have to set the `composed` option on the event to allow the event to propagate across the shadow barrier. See event options documentation here https://stenciljs.com/docs/events

**Comment by vinioo** [comment]
Even using ```composed``` or ```bubbles``` the events aren't being emitted

**Comment by messeiliMAF** [comment]
@vinioo You'll probably have to  set the `composed` option on the event also to set `{ target: 'document' }` to the listener like this:

`@Event({ bubbles: true, composed: true }) eventExample: EventEmitter;

  @Listen('eventExample', { target: 'document' })
  async eventExamplehandler(e : CustomEvent) {
// do your logic here
  }
`

**Comment by tanner-reits** [comment]
@vinioo I'm going to close this issue out due to inactivity and assuming the proposed solution above worked. If you are still experiencing issues here, you can pose a question in our [Slack channel](https://stencil-worldwide.herokuapp.com/)!
