### ISSUE TITLE
Npm package installation

### ISSUE THREAD

**Issue by Adhityaganesh** [ionic-team/stencil#2590]
How can we install and use npm packages in stencil.js?

**Comment by claviska** [comment]
We just updated the docs yesterday with more info on distributing and consuming via the custom elements bundle. I think this may be what you're looking for: https://stenciljs.com/docs/custom-elements

**Comment by adamdbradley** [comment]
Additionally there is publish info here https://stenciljs.com/docs/distribution#publishing
