### ISSUE TITLE
Question: Programmatically providing an Angular service to a Prop through `setAttribute`

### ISSUE THREAD

**Issue by ScottMGerstl** [ionic-team/stencil#2593]
### Background:

Most of my application is built using Stencil (design system, form elements, higher-order composed elements) while Angular is used for the application framework (routing, resolves, guards, api calls, intercepters).

### Scenario Background:

I have a modal service that presents and hides stencil components as a modal. In one of these modals I have a type-ahead/live-search stencil component used to search for profiles in the system. This type-ahead is rather agnostic and typically has an Angular component wrapping it so it can access the injected HTTP service.

Since the modal only renders stencil components and this specific modal needs to include a live search, I need to find a way to provide the Angular service to the stencil component.

### Specific Question:
Providing a constructed service works when using binding from Angular and Stencil but trying to provide a service to the stencil component by programmatically setting an attribute does not work (see below):

- Serializing causes a Circular structure error
- Not serializing it causes it to be undefined in the component

Is there something in the Stencil framework I can use to provide the service in this way?

### Code: 

Attempted implementation:

NoteService.ts (Angular)
```typescript
    const result = await ModalService.showComponent({
            id: 'new-note',
            componentTag: 'arc-ui-note-editor',
            headerOptions: {
                title: 'Make a note',
                confirmButtonText: 'Save'
            },
            componentProps: {
                asModal: true,
                fetchAllService: this.profilesService // The attempted injection of an angular service
            }
        });
```

Applicable portion of the modal service:

modal.service.ts (Plain ts)
```typescript
  private renderModal(options: Partial<ModalMessageOptions & ModalComponentOptions>, isComponent: boolean) {
        const modal = document.createElement('arc-ui-modal');
        modal.setAttribute('id', options.id);

        if (options.headerOptions != null) {
            modal.setAttribute('header-options', JSON.stringify(options.headerOptions));
        }

        if (options.footerOptions != null) {
            modal.setAttribute('footer-options', JSON.stringify(options.footerOptions));
        }

        modal.setAttribute('type', isComponent ? 'component' : options.type);

        if (options.message != null) {
            modal.setAttribute('message', options.message);
        }

        // Render component if available
        if (options.componentTag != null) {
            const view = document.createElement(options.componentTag);

            if (options.componentProps != null) {
                Object.keys(options.componentProps).forEach(key => {
                    const snakeKey = key.replace(/[A-Z]/g, x => '-' + x.toLowerCase());

                    let propValue = options.componentProps[key];

                    if (propValue instanceof Object) {
                        propValue = JSON.stringify(propValue); // Where it's failing. Objects don't work if I don't serialize.
                    }

                    view.setAttribute(snakeKey, propValue);
                });
            }

            modal.append(view);
        }

        document.body.append(modal);
    }
```

**Comment by max-scopp** [comment]
If you're using `setAttribute` you're only able to define strings, as this is the implementation for reading/setting the pure html - in the traditional sense.

**Prop !== Attribute**
A Prop can be any type, an Attribute can only be a string.

```javascript
const myCmp = document.createElement('my-stencil-component');
const myApiServiceInstance = window.getApiThing();
const myObject = {
  autosuggest: 'something',
  noteThatYouPassAnObjectAsPropHere: true
};

// this will set a Prop
myCmp.apiService = myApiServiceInstance;
myCmp.complexProp = myObject;

// this will set the **Attribute**, which will be read as Prop
myCmp.setAttribute('complexProp', myObject); // will result in setting the string "[object Object]"
```

You can define props directly on the element in order to keep the exact type. I strongly dislike the idea to pass framework things down to your design library again, as this simply strengthens the connection between Angular and Stencil, therefor making your library a lot less flexible for the future.

Our aproach to this is to provide basic framework-like functions in a close to dependency-free, vanilla JS way in order to
a) bridge those basic functions with the framework-specific one's, or
b) directly leverage those functions without any framework at all

**Comment by ScottMGerstl** [comment]
Thanks! I very much appreciate the help. 

I completely understand and agree with where you're coming from. If there was room in the budget, I would look at doing this differently but, I think I'll have to take the tech debt for now. 

I didn't realize there was a slack channel. Thanks for pointing that out. I've signed up and will post any further questions there, first.
