### ISSUE TITLE
Prerender in combination with instanceof Element

### ISSUE THREAD

**Issue by SheepFromHeaven** [ionic-team/stencil#2594]
**Stencil version:**

```
 @stencil/core@1.16.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When I have code in my components that checks if the `@Element() el: HTMLElement` is an instance of `window.Element`, the prerender fails, as `this.el` in the prerender will no be `instanceof Element`.
This contradicts the part in the docs, saying: "Stencil uses its own internal DOM APIs which strictly follow the web standards, but optimized for prerendering"

**Expected behavior:**

I can use `instanceof Element` on an HTMLElement in prerender as well as in client side render and get the same result (`true`)

**Steps to reproduce:**

Put the following code somewhere in your component and run a prerender of this component:

**Related code:**

```tsx
@Element el: HTMLElement;

...

if(!(this.el instanceof Element)) {
  throw new TypeError('THIS FAILS');
}
```

**Other information:**

This is a major issue as other packages may use this pattern. See:
https://github.com/que-etc/resize-observer-polyfill/blob/master/src/ResizeObserverSPI.js#L81

**Comment by SheepFromHeaven** [comment]
Already pinned it down to `MockElement` being extended in:
https://github.com/ionic-team/stencil/blob/0d730d672ef477266b12b31cf93bc98fc86ba8f0/src/mock-doc/window.ts#L203
But the components elements are direct instances of `MockElement`.

So: `class extends MockElement !== MockElement`

**Comment by adamdbradley** [comment]
I'd recommend adding a Build conditional around the resize observer polyfill. Even if the Element instance is changed, in a node environment the resize observer code will not be able to work, and I'm sure another API later in the code will also break. https://stenciljs.com/docs/static-site-generation-basics#things-to-watch-for

**Comment by SheepFromHeaven** [comment]
@adamdbradley Thanks a lot for the answer. Just figured I want the prerendered page to display same as the client side rendered. But I got it mixed up with screenshots. Thanks nevertheless!

**Comment by pragatheeswarans** [comment]
I am using a library which in turn uses `fast-copy` to copy objects. `fast-copy` uses `instanceof` to determine object types. This is breaking while prerendering the page with the error 

```
Right-hand side of 'instanceof' is not an object
```

The `fast-copy` library [provides an option](https://github.com/planttheidea/fast-copy#realm) to pass the `window` context. Can you help me on what to pass to get the `Date`, `regexp` objects inside it?

Example:
```JS
const iframe = document.querySelector("iframe");
const arr = iframe.contentWindow.arr;

console.log(copy(arr, { realm: iframe.contentWindow })); // ['foo', 'bar']
```
