### ISSUE TITLE
Type for default export not work for Prop types

### ISSUE THREAD

**Issue by shadowvzs** [ionic-team/stencil#2598]
**Stencil version:**

```
 @stencil/core@ 1.16.2
```
**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
```tsx
import FileExplorerService from "..";
...............
    @Prop()
    service: FileExplorerService;
```
cannot find FileExplorerService (ofc it is exported correctly in index.ts just with different name since make no difference if it is default exported class)

and this work without type error
```typescript
import { FileExplorerService } from "..";
...............
    @Prop()
    service: FileExplorerService;
```

**Expected behavior:**
Type should work well for default export too

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize that it took so long for someone on the team to respond to this issue. I tried to replicate this with Stencil v3.1.0 (the latest version of the library) and was unable to replicate it. If you're willing and able, could you please add a minimal reproduction case for the team to take a look at? If not, I completely understand - thanks!
