### ISSUE TITLE
img tags do not support draggable=false in JSX

### ISSUE THREAD

**Issue by michael-speed-elder** [ionic-team/stencil#2601]
**Stencil version:**

```
 @stencil/core@1.2.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The attribute in `<img draggable="false" />` is marked as an error: "draggable: type 'string' is not assignable to 'boolean'".  

**Expected behavior:**

`"true"`, `"false"`, and `"auto"` should all be acceptable values for the `draggable` attribute.

**Steps to reproduce:**

1. Copy and paste the related code into any .tsx component file

**Related code:**

```tsx
<img draggable="false" />
```

**Other information:**

Writing `<img draggable={false} />` simply doesn't set the `draggable` attribute on the element.  Since `img` tags are draggable by default, and `draggable` is [not a boolean attribute in HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable), this is an issue.  Images (and anchors) should be able to be marked as non-draggable.  I know the Stencil version listed is several minor versions back, but a glance in the `declarations/` directory of the `1.17.2` version shows this is still an issue.

**Comment by rwaskiewicz** [comment]
After some internal discussion with the rest of the Stencil team, we've decided that in the context of writing TSX, we'd like to continue to stay aligned with the types provided by TypeScript (at the time of this writing, Stencil & TypeScript define `draggable` as an optional `boolean` property).

> Writing <img draggable={false} /> simply doesn't set the draggable attribute on the element...

I wasn't able to reproduce this locally with Stencil v4.2.1 in any of the latest versions of Firefox, Safari, Edge or Chrome. If anyone is running into this, please feel free to open a new issue.
