### ISSUE TITLE
JSX - EventEmitter type error

### ISSUE THREAD

**Issue by shadowvzs** [ionic-team/stencil#2602]
**Stencil version:**
```
 @stencil/core@ 1.16.2
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
           Type '{ fs: FSObject; size: "big"; align: "bottom"; editable: true;
           key: number; onSelect: (e: any) => void; }' is not assignable to
           type 'FsIcon & HTMLAttributes<HTMLFsIconElement>'.**Property
           'onSelect' does not exist on type** 'FsIcon &
           HTMLAttributes<HTMLFsIconElement>'.

**Expected behavior:**
No type error about inexisting event listener

**Related code:**

```tsx
@Event() onSelect: EventEmitter<IFSObject>;
```

**Comment by rwaskiewicz** [comment]
Hey @shadowvzs 👋 

I apologize that it took so long for a member of the team to acknowledge this issue. If you're willing/able to, could you please provide a minimal reproduction case for the team and I to take a look at? If not, I completely understand. Thanks!
