### ISSUE TITLE
Svelte support #103

### ISSUE THREAD

**Issue by andrewragy** [ionic-team/stencil#2605]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

Please Add official svelte support!!

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil-ds-output-targets/issues/103
