### ISSUE TITLE
HTMLSlotElement assignedElements / assignedNodes not available in spec tests

### ISSUE THREAD

**Issue by jrburke** [ionic-team/stencil#2606]
**Stencil version:**

```
@stencil/core@1.12.2 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
In a .spec.tsx test, The mock HTML element returned from `shadowRoot.querySelector('slot[name="items"]')` does not have the `assignedElements` or `assignedNodes` functions on it.

**Expected behavior:**
It would have `assignedElements` and `assignedNodes` available, as per the [HTMLSlotElement API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement).

I am able to call `assignedElements()` when running the component in the browsers I support.

**Steps to reproduce:**

**menu-list.tsx**

```tsx
import { Component, ComponentInterface, Host, h } from '@stencil/core';

@Component({
  tag: 'menu-list',
  styleUrl: 'menu-list.css',
  shadow: true,
})
export class MenuList implements ComponentInterface {

  render() {
    return (
      <Host>
        <slot name="items"></slot>
      </Host>
    );
  }
}
```

**menu-list.spec.tsx**

```tsx
describe('menu-list', () => {
  it('renders', async () => {
    const page = await newSpecPage({
      components: [MenuList],
      html:
      `<menu-list>
        <div slot="items">One</div>
        <div slot="items">Two</div>
        <div slot="items">Three</div>
      </menu-list>`,
    });

    const slotElement:HTMLSlotElement = page.root.shadowRoot.querySelector(
      'slot[name="items"]'
    );

    expect(slotElement.assignedElements()).toBeTruthy();
  });
});
```

**Comment by CloudyMcStrife** [comment]
+1

**Comment by stephenbe** [comment]
I do not know if this is related, but when I console log a querySelector of a slot element, it returns an empty object

**Comment by chavlji** [comment]
I have the same problems. When running jest it reports this:
![Screenshot 2021-01-15 at 16 24 20](https://user-images.githubusercontent.com/5729421/104745471-6e07c280-574e-11eb-8f5e-ce044623cf64.jpg)

Here's the source:
![Screenshot 2021-01-15 at 16 26 42](https://user-images.githubusercontent.com/5729421/104745574-8aa3fa80-574e-11eb-943e-8a676794ce10.jpg)


Any workaround or plan on when this will be supported?
