### ISSUE TITLE
Debugging e2e-tests not working because devServer does not start

### ISSUE THREAD

**Issue by RS-Sautter** [ionic-team/stencil#2612]
**Stencil version:**

```
 @stencil/core@1.12.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When debugging e2e-tests, an error get's thrown when doing page.setContent(...). I am debugging in Webstorm, but in VSCode its probably similar.
The error is: 
```
dev server error: Debugger listening on
ws://127.0.0.1:49749/17399cd6-9e71-46d8-bf65-661dffb4d28e For help,
see: https://nodejs.org/en/docs/inspector Debugger attached. ,
hasStarted: false
```
The same tests are working when being run from the command line. Just debugging doesn't work.

**Expected behavior:**

Debugger could stop also at breakpoints after page.setContent(...)

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

I did a bit of investigation with the debugger: The "debugger listening on ws://..." message is getting misinterpreted as error from the process. This happens [here](https://github.com/ionic-team/stencil/blob/91564f4dd954575843273d4437165cb408c735ef/src/dev-server/index.ts#L105).

**Comment by WickyNilliams** [comment]
Can confirm the same issue in vscode. The error message logged in each test is:

```
 invalid e2eSetContent() app script url
```

This occurs on any call to `page.setContent`

**Comment by adamdbradley** [comment]
@RS-Sautter would you be able to submit a PR that addresses the issue? Thanks

**Comment by RS-Sautter** [comment]
@adamdbradley I'm not sure how to fix this, but I can help investigating.
It seems like Node.JS debugger is always reporting this message to stderr and tools are filtering this out at the moment.
So should we just add a regex and ignore the message here?

**Comment by stephenbe** [comment]
Also happening to me
