### ISSUE TITLE
Import Stencil components into other Stencil apps breaks compilation if the components are built with v1.14.0 or greater

### ISSUE THREAD

**Issue by nathanb21** [ionic-team/stencil#2614]
**Stencil version:**
```
 @stencil/core@1.17.3
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Installing another stencil component library and importing it within index.ts results in a compilation error.

**Expected behavior:**

It should compile

**Steps to reproduce:**
For example, I want to use `@shoelace-style/shoelace` within a Stencil app. I will `npm i @shoelace-style/shoelace` and then within `index.ts` reference this using `import '@shoelace-style/shoelace';`.

Either `npm run start` or `npm run build` results in:

```
Rollup: Unresolved Import
           Could not resolve './components' from
           ./node_modules/@shoelace-style/shoelace/dist/collection/index.js
```

**Other information:**

In Stencil v1.13.0 `dist/collection/index.js` would be empty. In v1.14.0 or greater `dist/collection/index.js` now contains `export * from './components';`. `./components` does not exist within `dist/collection`.

**Comment by nathanb21** [comment]
Duplicates https://github.com/ionic-team/stencil/issues/2600 which does fix the issue.

It'd be helpful if `npm init stencil` was updated to latest so that the `index.ts` is generated correctly.

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil-component-starter/commit/badd5b8b77f7e672d5f85e288514356e675e78ce
