### ISSUE TITLE
Feature Request - Allow same name asset directories

### ISSUE THREAD

**Issue by jaredcbaum** [ionic-team/stencil#2615]
**Stencil version:**

```
 @stencil/core@ v1.12.2 and v1.17.3 (I know it says v1.12.2 in the picture but I updated to latest and built with the same results) 
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

![Screenshot from 2020-08-06 10-25-42](https://user-images.githubusercontent.com/61951482/89550503-4ab80f00-d7cf-11ea-896f-924336f33937.png)

**Current behavior:**
(See Screenshot)
**1 ->** Asset directories in two separate component folders
**2 ->** The build output only includes the image from the first of the two assets directories

**Expected behavior:**
I would like both of the components assets folders to combine under www -> build -> assets

**Steps to reproduce:**
Create new stencil project
Update to newest stencil version (1.17.3)
Create assets folder with image in two different component subfolders
Set the @Component decorator 'assetDir' option to 'assets'
Add images to both of the 'assets' folder
Run 'npm run build' or 'npm run start'
The 'www' -> 'build' -> assets folder should now contain only the image from the first of the two 'assets' folders

**Indended Use**
On the new slew of ionic repos (ionic.io and getcapacitor so far), we have a **src -> pages** directory that contains components that represent a single page of a website.  It would be nice for each of those folders to contain an 'assets' or 'img' directory so we could keep all assets together with the component styles and .tsx file.  Right now the workaround is naming the asset directory some like 'assets-app-home' or 'img-app-home' so that it is unique between components.

**Other information:**

**Comment by momenelkamri** [comment]
Here’s a revised version of your text:

---

**How can I copy a CSS file to a different file name?**

```json
{
  src: 'src/global.scss',
  dest: 'styles/webcomponents.css',
}
```

**Current Behavior:**

- `global.scss` is copied into the `styles/webcomponents.css` folder.

**Expected Behavior:**

- `global.scss` should be copied and renamed to the `styles/webcomponents.css` file.
