### ISSUE TITLE
Dev warning for mapping without keys

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#2618]
Not sure this is very straight-forward to do but someone else pointed this out again, and I recall needing about a day to debug some very weird behavior in my early days with Stencil, where I wasn't using keys when rendering a dynamic list of elements.

React shows _Warning: Each child in an array or iterator should have a unique "key" prop._

Just looking at the react implementation a little bit, I think it checks whether the parent node has an iterator, and then issues a warning if it does but there's no explicit `key` on some of the child nodes. Maybe we can do something similar.

**Comment by alicewriteswrongs** [comment]
@jackdriscollukg thanks for pointing out this issue! I'm going to close in favor of #3564, a newer issue with a lot more context. Feel free to give that a read, and know that the team is working on addressing various problems / outstanding issues in this area at present.
