### ISSUE TITLE
Build process breaks when symbolic links are used

### ISSUE THREAD

**Issue by vjekoart** [ionic-team/stencil#2619]
**Stencil version:**

```
 @stencil/core@1.17.3
```

**I'm submitting a:**

[] bug report
[x ] feature request

*I'm not sure whether this is a bug or a feature request. Current behaviour results in an error, but the error is not caused by the Stencil itself. On the other hand, error could be prevented only by extending the possibilities of Stencil.*

**Current behavior:**

I'm working on a project which has two Stencil projects (generated by `npm init stencil`) inside a single Git repository. Both Stencil projects use common UI components, which are placed in `common` folder outside Stencil projects. Those components are source `tsx` and `css` Stencil files.

Every Stencil project has symbolic link to `common` folder which is placed in `src/components` directory.

When running `npm run start` or `npm run build` following error is displayed:

```
[ ERROR ]  Rollup: Parse Error: ../common/custom-button/custom-button.tsx:3:0
           Unexpected character '@' (Note that you need plugins to import files that are not
           JavaScript)
```

On the other hand, file `src/components.d.ts` in every Stencil project is generated as expected. That is, it contains information about components from `common` folder.

I'm aware that this behaviour is caused by the `@rollup/plugin-node-resolve` package which relies on [resolve package](https://www.npmjs.com/package/resolve). Furthermore, there is not a problem with those packages, but rather this behaviour is caused by default configuration options which do not fit with our environment.

**Expected behavior:**

Components and documentation are successfully built in an environment with symbolic links.

Since default value of `preserveSymlinks` is `false` ([defined by Node](https://nodejs.org/api/cli.html#cli_preserve_symlinks)), we would like to be able to pass `preserveSymlinks: true` configuration option to Rollup. Ideally, from `stencil.config.ts`.

**Steps to reproduce:**

```shell
# Create root project folder with `common` subfolder.
mkdir -p root-project/common
cd root-project

# Initialize two different Stencil projects
npm init stencil # lib-a
npm init stencil # lib-b

# Add symbolic link to `common` folder to both projects
ln -s common lib-a/src/components/common
ln -s common lib-b/src/components/common

# Generate dummy common component in any project
cd lib-a
npm run generate common/custom-button

# Component "custom-button" is available in both projects

# Run build job to get an error
npm run build # or "npm run start"
```

**Other information:**

I've created a workaround for this issue, but unfortunately with this approach Stencil is locked to a specific version. With each release, it's required to check if manually if everything is working as expected.

Stencil has been extended to support custom Rollup options in `stencil.config.ts`:

```ts
import { Config } from '@stencil/core';

export const config: Config = {
  namespace: 'lib-a',
  taskQueue: 'async',
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader'
    },
    {
      type: 'docs-readme',
      dir: 'docs',
      strict: true
    }
  ],
  // Available due to modified version of "node_modules/@stencil/core/compiler/stencil.js"
  rollupOptions: {
    preserveSymlinks: true
  }
};
```

The solution was to extend `getRollupOptions` method in `src/compiler/bundle/bundle-output.ts` file. Existing return statement has been changed from `return rollupOptions;` to `return Object.assign(rollupOptions, config.rollupOptions);`.

With that change it's possible to add custom Rollup options from `stencil.config.ts` file.

**Comment by bitflower** [comment]
Hi together!

I think I'm experiencing something similiar when bundling several symlinked packages ( in a lerna monorepo) with Stencil.

I'm getting suplicate code in multiple chunks.

Has this been investigated @rwaskiewicz @sean-perkins ?

Would love to contribute and solve this.

**Comment by christian-bromann** [comment]
Hey @bitflower , thanks for checking in. Apology that this issue has been lost in the triage state for so long. I think a good first step is to create a minimal reproducible example so we can both verify the issue. After that I am happy to help to make the right contribution to get this fixed. What do you think?
