### ISSUE TITLE
CSS file changes in assets dir detected but not updated in live reload

### ISSUE THREAD

**Issue by Tera3yte** [ionic-team/stencil#262]
**Stencil version:**
```
 @stencil/core v0.0.6-22
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I created a css file (main.css) inside src/assets/css and linked it to the index.html file
```
<link rel="stylesheet" href="/assets/css/main.css">
```
I styled the body-tag with an specific backgound-color, run `npm run dev` and the color will apear. Now if i change the color, stencil will detected the change and recompile, but the live reload is still showing the same background color. Also DOM-Inspector shows the wrong color. If you cancel live reload and restart `npm run dev` the new styles will be loaded

**Expected behavior:**
After compiling, live reload should also show the new css styles from css-file

**Steps to reproduce:**
Create .css-File, link it to index.html, style something, run `npm run dev`, change styling

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil-utils#2
