### ISSUE TITLE
toEqualHtml wildcards

### ISSUE THREAD

**Issue by NewDark90** [ionic-team/stencil#2620]
**Stencil version:**

```
 @stencil/core@1.17.1
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

For testing, toEqualHtml is such a useful and cool method to use. However, it's somewhat limiting if small parts of the output aren't useful for a test. Having the ability to use some form of wildcard would be an amazing feature. 

An example: 
```html
<div>
  Some text
  <input value="value data" />
  <img src="data:image/gif;base64,ALotOfBase64ImageHere..." />
</div>
```

It would be nice to be able to ignore specific things, like a big blob of base64 data. 

Super rough examples & syntax:
```html
<div>
   <* /> <!-- Ignore all tags/content in this tag -->
</div>

<div>
   <span></span>
   <* /> <!-- would be valid if there are a couple elements in here -->
   <span></span>
</div>

<div *></div> <!-- Can have any attribute -->

<img src=* /> <!-- attribute can have any value -->
```
Maybe some parts leverage jest expect methods: https://jestjs.io/docs/en/expect

**Other information:**

While this does have some potential for misuse and being overly permissive with tests, I think having some flexibility outweighs how rigid it currently is. Totally a "nice to have" type of addition. I don't see any other tickets with any similar suggestion.

**Comment by christian-bromann** [comment]
@NewDark90 thanks for raising this issue.

The Stencil team has taken a look at the proposal and decided not to move forward with it. We believe it would add a lot of complexity and as you mentioned before could be mis-used, causing false/positive or prevents regressions to be elevated. I recommend not to snapshot a large HTML section and instead focus on the parts and are important for you. There is nothing wrong to have multiple `toEqualHtml` for a single html output.

Let me know if you have any further ideas or questions!

Cheers
