### ISSUE TITLE
Stencil doesn't work with linaria rollup plugin

### ISSUE THREAD

**Issue by hankhester** [ionic-team/stencil#2622]
**Stencil version:**

```
 @stencil/core@1.17.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Stencil breaks when trying to use the linaria css-in-js rollup plugin

**Expected behavior:**

Stencil should be able to work with the linaria rollup plugin

**Steps to reproduce:**

`npm init stencil (app)`
`npm install linaria`
add to stencil.config.js:
```
import linaria from 'linaria/rollup'
...
rollupPlugins: {
    after: [ linaria() ]
}
```
add to app-home.tsx:
```tsx
import { css } from 'linaria'

const coralBackground = css`
  background-color: coral;
`
...
<div class={coralBackground}>hello :)</div>
```

**Other information:**

`npm start` errors with:
```
[ ERROR ]  Rollup: Plugin Error
           Cannot read property 'includes' of undefined (plugin: extTransformsPlugin,
           transform)

[33:17.8]  rebuild failed, watching for changes... in 709 ms
```

**Comment by adamdbradley** [comment]
Should be fixed in the next release, thanks
