### ISSUE TITLE
Prerender ignores native image lazy-loading

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#2623]
**Stencil version:**
```
 @stencil/core@1.7.2
```

**I'm submitting a:**
[X] bug report

**Current behavior:**
Prerender (`npm run build --prerender`) supress the native image lazy-loading capabilities. 

Images such as `<img loading="lazy"/>` are instantly loaded even though these would find place outside of the viewport and safe area.

**Expected behavior:**
Native lazy loaded images should be lazy loaded.

**Steps to reproduce:**

```
git clone https://github.com/peterpeterparker/stencil-prerender-lazy-img
cd stencil-prerender-lazy-img
npm i
npm run build
npx serve www
```

open localhost:5000 and observe the network tab.

note that  if you run `npm run start` with the same project,  you will notice that the image is lazy loaded correctly (as long as you  use Chrome or Firefox) 

**Related code:**

```tsx
render() {
  return [
    <div style={{display: 'block', background: 'red', width: '100vw', height: '3000px'}}>Image should not be loaded yet, check network tab.</div>,

        <img src="https://....svg" loading="lazy" alt="…" width="200" height="200"/>
  ]
}
```

**Other information:**

<img width="1148" alt="Capture d’écran 2020-08-09 à 14 36 25" src="https://user-images.githubusercontent.com/16886711/89732249-b90a0500-da4d-11ea-881b-dd84ede9795f.png">

**Comment by peterpeterparker** [comment]
@ghingis discovered this is happening because apostrophes are removed by prerendering

is

```
<img alt=… c-id=5.3.1.1 class="sc-app-home" height=200 loading=lazy
     src="https://deckdeckgo.com/assets/img/deckdeckgo-logo.svg" width=200>
```

should be

```
<img alt="…" c-id="5.3.1.1" class="sc-app-home" height="200" loading="lazy"
     src="https://deckdeckgo.com/assets/img/deckdeckgo-logo.svg" width="200">
```

**Comment by peterpeterparker** [comment]
update: with a custom configuration such as 

```
import {PrerenderConfig} from '@stencil/core';
import {PrerenderHydrateOptions} from '@stencil/core/internal/stencil-public-compiler';
export const config: PrerenderConfig = {
  hydrateOptions(_url: URL): PrerenderHydrateOptions {
    const hydrate: PrerenderHydrateOptions = {
      removeAttributeQuotes: false
    };
    return hydrate;
  },
};
```

I am able to get apostrophes

```
<img src="https://....svg"
loading="lazy" alt="…" width="200" height="200" class="sc-app-home" c-id="5.3.1.1">
```

but it does not solve the issue as the image is still loaded instantly

**Comment by adamdbradley** [comment]
Stencil doesn't control the heuristics of when the browser decides to download the image, all it's doing is adding the attribute to the `img`. Are you seeing the same thing if you remove all javascript and just have a plain HTML file?

**Comment by ghingis** [comment]
Nope, if you remove the javascripts, it works as expected.

**Comment by adamdbradley** [comment]
I wonder if it's from when the the prerendered html is being hydrated by clientside js, and when it sets the loading attribute it triggers it to load? Can you debug that further?

**Comment by ghingis** [comment]
I think I found the issue.. 
![Screenshot_2](https://user-images.githubusercontent.com/3637899/89998474-e80eb980-dc8d-11ea-9f35-0dcc31d6955e.png)
When it comes to `updateElement` it thinks the `$attrs$` of the old element is null (since it were never a VNode in the first place it looks fine for me). 
So during the creation of the new VNode it creates the new img and once the `setAccessor` sets the src the image gets downloaded.
This is the line that triggers the download of the image:
![Screenshot_3](https://user-images.githubusercontent.com/3637899/89999685-6a4bad80-dc8f-11ea-9398-1c41fe6c1f53.png)
It seems, if you set the src of the image after it is in the dom, the browser (at least chrome) will download the image immediately, maybe we could do something like this:
![Screenshot_4](https://user-images.githubusercontent.com/3637899/90003237-155e6600-dc94-11ea-83f3-d2fc063b50e6.png)

**Comment by ghingis** [comment]
I tested a bit more, and it's not an issue in chromium 86.0.4231.0 and in firefox 79.0.
The last chrome version I tested and it still failed: 84.0.4147.125
The latest chrome canary does not seems to be affected: 86.0.4231.0
After all of this, I think this issue should be closed as soon as the chrome get updated to the next version where it is no longer an issue.

**Comment by peterpeterparker** [comment]
neiter is is an error with Chrome v85, for sure we can close this issue.

thank you @ghingis for all the debugging and help, you are a hear!
