### ISSUE TITLE
Support more complex pattern for namespace

### ISSUE THREAD

**Issue by elebetsamer** [ionic-team/stencil#263]
**Stencil version:**

```
 @stencil/core@0.0.6
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Right now the `namespace` in the config only supports using a string without dashes or anything. It would be great to support camelCase, snake_case and kebab-case. These are all well known techniques for creating well named and organized code, so it would be great to support this for the stencil output as well.

**Comment by adamdbradley** [comment]
In the latest release you should be able to use camelCase and kebab-case: https://github.com/ionic-team/stencil/blob/019d005f85c7943993fda201a907fd251971d2b2/src/util/test/validate-config.spec.ts#L255-L316

You're saying it should also add snake_case too?

**Comment by elebetsamer** [comment]
Oh, excellent, I didn't know this was added already. That is great.

I personally will be using kebab-case, but I was adding in snake_case to be inclusive.

**Comment by elebetsamer** [comment]
So I tried this just now and it doesn't seem to work as expected with kebab-case at least. I changed my `namespace` to `bs-stencil` and then ran `npm start` and it loaded it the browser. But my components didn't load, so I checked the dev console and found this: `Uncaught ReferenceError: bs is not defined at bs-card.js:3`. Line 3 of bs-card.js is `bs-stencil.loadStyles("bs-card","bs-card {\n  display: block;\n}\nbs-card.hydrated{visibility:inherit}","bs-card-link","bs-card-link a:hover {\n  text-decoration: none;\n}\nbs-card-link.hydrated{visibility:inherit}");`. Of course, `bs-stencil` isn't a valid name in javascript, so that is why it errors.

I can confirm that camelCase (`bsStencil`) worked as expected though.

**Comment by adamdbradley** [comment]
Ok thanks for letting us know, we'll take a look.

**Comment by dimi-nk** [comment]
I'm having the same issue. Even though hyphens in the namespace are allowed and generate a validate namespace, they're also used inside the generated components. For example, I've used `web-components` as my namespace and I'm getting the following code in my components:
`web-components.loadStyles(...)`. Should we open a separate issue for this bug?

**Comment by dimi-nk** [comment]
@elebetsamer I've opened a new [bug issue](https://github.com/ionic-team/stencil/issues/308) for the hyphen problem.
