### ISSUE TITLE
Slot tag with attribute slot does not work with shadow false

### ISSUE THREAD

**Issue by stevenbriscoeca** [ionic-team/stencil#2632]
**Stencil version:**

```
 @stencil/core@1.17.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Button does not appear when it is supposed to.

**Expected behavior:**

I expect the button to appear

**Steps to reproduce:**

I have two components : 

- my-component 
- my-test

```html
    <my-component first="Stencil" last="'Don't call me a framework' JS">
      <button slot="action">Transfer me in the my-test component</button>
    </my-component>
```

Inside my-component (has shadow false)
```tsx
  render() {
    return (
      <Host>
        <my-test>
          <slot name="action" slot="inception-action"></slot>
        </my-test>
      </Host>
    );
  }
}
```

Inside my-test (has shadow true)
```tsx
  render() {
    return (
      <Host>
        <div>
          <slot name="inception-action"></slot>
        </div>
      </Host>
    );
  }
```

If I change inception-action to just action in my-component it works : 
```tsx
  render() {
    return (
      <Host>
        <my-test>
          <slot name="action" slot="action"></slot>
        </my-test>
      </Host>
    );
  }
```

Thanks!

**Comment by tanner-reits** [comment]
This was fixed in #4940 and released in [Stencil v4.7.0](https://github.com/ionic-team/stencil/releases/tag/v4.7.0)
