### ISSUE TITLE
Stats output target not producing anything

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil#2633]
**Stencil version:**
After the next compiler was added: everything after  @stencil/core@v1.9.2
Tested this with: 
@stencil/core v1.9.2 (Works)
@stencil/core v1.10.3 (Not Produced)
@stencil/core v1.10.3 (Not Produced)
@stencil/core v1.11.3 (Not Produced)
@stencil/core v1.12.7 (Not Produced)
@stencil/core v1.13.0 (Not Produced)
@stencil/core v1.14.0 (Not Produced)
@stencil/core v1.15.0 (Not Produced)
@stencil/core v1.16.5 (Not Produced)
@stencil/core v1.17.3 (Not Produced)

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When using either the --stats flag in a build, or the entry in outputTargets - `{ type: 'stats' }` - a json file would be produced when doing `npm run build`

**Expected behavior:**
Well, a few options: 
1) it's been removed for the past 5 months, and I'm not sure how many people use it... remove the code that implies it exists. But that makes it so that we cannot do performance tweaks with other languages. 

2) Rebuild this, and improve support since mode's styles are also split out now too, potentially.  

It would really help server side apps using any given design system - this is the lighthouse topic it intends to solve https://web.dev/uses-rel-preload

I used it in a couple rails apps during Stencil 1.7 but I haven't maintained that app in a while, even though it's still chugging along. Knowing that upgrading would nix that performance gain blocks me. I'd also like to open source whatever solution this file would provide in PHP - WordPress - and Ruby on Rails, if we can get it back. 

**Steps to reproduce:**
Build any app or design system after v1.9.2 with the --stats flag or with `{ type: 'stats' }` in the stencil config. 

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by rwaskiewicz** [comment]
I’m going to close this issue, as #3030 has landed in the main branch and is a part of the v2.9.0 release.
