### ISSUE TITLE
Expose ShadowDOM properties

### ISSUE THREAD

**Issue by greaka** [ionic-team/stencil#2634]
**Stencil version:**

```
 @stencil/core@1.17.3
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently, stencil does not expose all of the shadow dom properties.

**Expected behavior:**

I expected #1623 to also include the attach mode.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

Why is mode not supported? Is there a workaround for now?

**Comment by rwaskiewicz** [comment]
Closing this in favor of https://github.com/ionic-team/stencil/issues/4111, which I believe is asking for the same thing (and has a little more visibility/upvotes)
