### ISSUE TITLE
FR: asset dirs from subfolder

### ISSUE THREAD

**Issue by mburger81** [ionic-team/stencil#2636]
**Stencil version:**
```
@stencil/core@1.17.3
```

**I'm submitting a:**

[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If you have now a structure like
```
- my-component
   - my-component-sub1
        - assets1
        my-component-sub1.tsx
   - my-component-sub2
       - assets2
       my-component-sub2
```

The assets folders are not bundled as expected. That means only once of them is bundled in the right position, the other one is bundled outside of the project.

**Expected behavior:**
support (close bug) asset dirs in nested folders

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize it took so long for someone on the team to acknowledge this issue. I’m having trouble reproducing this on my end with the latest version of Stencil (v4). If you’re willing/able, would you be able to create a minimal reproduction case for the team? If not, I completely understand. Again, I apologize for the lack of response here
