### ISSUE TITLE
D3js rendering but not display

### ISSUE THREAD

**Issue by b-barry** [ionic-team/stencil#264]
**Stencil version:**

```
@stencil/core@0.0.6
```

**I'm submitting a:**

- [X] bug report

**Current behaviour:**

- Install d3js version 3
- I created a component and used @Element() to retrieve the component container 
```
  @Element() container: HTMLElement;
```
- Import d3js in global
- In the  componentDidLoad() , add the following code : 
```ts
.d3
      .select(this.container)
      .append('svg')
      .attr('class', 'sg-root')
      .style('height', `500px`)
      .style('width', `500px`)
     .append('text).text('hello');
```
- When inspecting, I see the element in the DOM  but  I don't  the see the text 'hello'. Moreover, I try to diable the shadow ans the CSS scoping in the component but it seems not working also

**Expected behaviour:**
- I should see the text with 'hello'

If I render a simple p with a text, the text appears. I think that stencil don't track the rendering done by d3js

**Comment by jgw96** [comment]
Hey @b-barry , mind posting a repo I could use to reproduce this issue?

**Comment by b-barry** [comment]
Hello @jgw96 ,

I was playing with it now, I thought  that I found a solution
```
this.svg = this.d3
      .select(this.container.shadowRoot) // giving the shadowRoot allows the render
      .append('svg') 
```

However, my "global" css was not applied but I set:
```
@Component({
  tag: 'sunburst-one-level',
  styleUrl: 'sunburst-one-level-component.scss',
  shadow: false,
  scoped: false
})
```

**Comment by xBILLYjr123** [comment]
Your fucken done you fuck for hate crimeing me

**Comment by jgw96** [comment]
Hey @b-barry since this seems more like a question specific to this library in your project and not an issue in Stencil, im going to recommend you join our Stencil worldwide slack https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjYwNjg5NDMzODQwLTdiNWZiNDMyMWRjZTBiMjIzMGFlOTZiZWVkNDVjNzc2ZTI5MzI2Y2VjZDgwYjczMjU3NWIxMDYzMzI2ZjY3NjM as there are a ton of awesome devs on there that can help you. Thanks!

**Comment by b-barry** [comment]
@jgw96 Thanks for the help, I will join the slack
