### ISSUE TITLE
using --prerender causes the app to be rendered multiple times on the same page

### ISSUE THREAD

**Issue by khaledosman** [ionic-team/stencil#2644]
**Stencil version:**
```
└── @stencil/core@2.0.0-4
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
When using the `--prerender` flag the app is rendered multiple times on the same page and the rendered app components overlap with each others

![image](https://user-images.githubusercontent.com/2937633/90871615-a40d6a00-e39b-11ea-9ee7-08ae1fab9056.png)

**Expected behavior:**
The app should be rendered only once

**Steps to reproduce:**

clone the repository https://github.com/khaledosman/stencil-realworld-app
1. run `yarn build --prerender`
2. `npm i -g serve`
3. `serve www/`

The problem doesn't happen without the `--prerender` flag

**Comment by peterpeterparker** [comment]
@khaledosman  have you try with the last release?

**Comment by khaledosman** [comment]
@peterpeterparker yup, same issue, I've updated the repo to v2.0.3

**Comment by khaledosman** [comment]
Adding `rm -rf www/` in my npm build script before running `stencil build` fixed my issue

**Comment by peterpeterparker** [comment]
Nice @khaledosman  👍  I guess this can be solved / closed.
