### ISSUE TITLE
Stencil sass conflict with Stencil 2.0

### ISSUE THREAD

**Issue by pixelbucket-dev** [ionic-team/stencil#2658]
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

I am not sure if this is the right location for this bug or it should move to the https://github.com/ionic-team/stencil-sass repo?
**Current behavior:**

> npm WARN @stencil/sass@1.3.2 requires a peer of @stencil/core@^1.0.2 but none is installed. You must install peer dependencies yourself.

**Expected behavior:**

`"@stencil/sass"` package should work with the latest `"@stencil/core"` version.

**Steps to reproduce:**

Install the latest 2.x stencil and you will see the warning coming from `npm`. The sass compilation still works, but the warning is irritating.

**Comment by claviska** [comment]
Fixed in https://github.com/ionic-team/stencil-sass/pull/39
