### ISSUE TITLE
PWAs do not work offline with v2

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/stencil#2659]
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Stencil PWAs built with > v2 and a generated service worker don't work offline.

**Expected behavior:**

Stencil PWAs should function offline when using a generated service worker to cache the build files and fetch them from the cache automatically.

**Steps to reproduce:**

1. Generate a new stencil project with type `ionic-pwa` using `npm init stencil`
2. Enable the service worker by removing `serviceWorker: null` from the `www` output target
3. `npm install --save-dev workbox-build@4.3.1`
4. Build the project with `npm run build`
5. Either deploy the app or run the build directory on a local server
6. Using Chrome dev tools, check `Disable cache` on the network tab (to prevent using the disk cache, which should not be necessary if using a service worker) and also check `Offline` in Application / Service Workers. (You could also perform a real word test by installing the PWA on a phone or with Chrome and then manually turning off the network)
7. See that the app doesn't load at all (`app.esm.js` and `app.css` have 404 errors in the network tab)

Demo created using the above steps: https://sharp-goldstine-65dc8a.netlify.app/

**Other information:**

I believe this is happening because of some change from v1 -> v2 that changed how the build scripts are imported into the final `index.html`.

Here is what the app script tags look like from v2:
```html
  <script type="module" src="/build/app.esm.js" data-stencil data-resources-url="/build/"
    data-stencil-namespace="app"></script>
  <script nomodule="" src="/build/app.js" data-stencil></script>
  <link href="/build/app.css" rel="stylesheet">
```
and from v1:
```html
  <link rel="modulepreload" href="/build/p-be07d25c.js">
  <link rel="modulepreload" href="/build/p-177ede88.js">
  <link rel="modulepreload" href="/build/p-3a5bd1b8.js">
  <link rel="modulepreload" href="/build/p-58d13c5e.js">
  <link rel="modulepreload" href="/build/p-718ae824.js">
  <link rel="modulepreload" href="/build/p-9121f02b.js">
  <link rel="modulepreload" href="/build/p-9701a0dd.js">
  <script type="module" src="/build/p-be07d25c.js" data-stencil data-resources-url="/build/"
    data-stencil-namespace="app"></script>
  <script nomodule="" src="/build/app.js" data-stencil></script>
  <link href="/build/p-27da9c36.css" rel="stylesheet">
```
See that in v1 there are no references to `app.esm.js` or `app.css`. The default stencil configuration for the generated service worker explicitly excludes those files from being cached (https://github.com/ionic-team/stencil/blob/master/src/compiler/config/validate-service-worker.ts#L68-L77) so it makes sense why the app would not function offline. Maybe those files should have been removed from the `globIgnores` in v2?

**Comment by MrAntix** [comment]
relates to https://github.com/ionic-team/stencil/issues/2687

**Comment by claviska** [comment]
Thanks for posting this. There are a few similar issues that seem to be related:

https://github.com/ionic-team/stencil/issues/1631
https://github.com/ionic-team/stencil/issues/2687

I'm looking into this to see what's going on.
