### ISSUE TITLE
@Event() inside <Host /> element fire an error that stops hot reload

### ISSUE THREAD

**Issue by loiacon** [ionic-team/stencil#2663]
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When we have a component with `@Event()` decorator, hot reload stop working until you reload the page. These first two errors occurs even when you don't have the component inside a `<Host />`:
```
Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.
``` 
```
Uncaught (in promise) TypeError: Cannot read property 's-ol' of null
```
---
```
TypeError: Cannot read property '$instanceValues$' of undefined
```
```
vNode passed as children has unexpected type.
```

**Expected behavior:**

It just works.

**Steps to reproduce:**

1. Init a Stencil example.
3. Create a component that use `@Event()` from `@stencil/core`
4. Try to put this component inside another component that use `<Host />`

**Related code:**

Component example
```tsx
import { Component, Host, h, Event } from '@stencil/core';

@Component({
  tag: 'app-anything',
  shadow: true,
})
export class AppAnything {
  @Event() anyEvent;

  render() {
    return (
      <Host>
        <slot></slot>
      </Host>
    );
  }
}

```

**Other information:**

**Comment by alicewriteswrongs** [comment]
Hello @loiacon, thanks for filing this issue and sorry it took so long for someone from the Stencil team to get back to you about this.

Is there any chance you'd be able to provide a reproduction case in the form of a git repo, stackblitz project, etc? It really helps us to deal with bug reports when we do.

Again, sorry about the delay!
