### ISSUE TITLE
Node.js version warning

### ISSUE THREAD

**Issue by erichstark** [ionic-team/stencil#2665]
**Stencil version:**

```
npm list @stencil/core
@o2/web-components@202005.0.5 /Volumes/Data/Projects/O2/web-components
└── UNMET PEER DEPENDENCY @stencil/core@2.0.3 

npm ERR! peer dep missing: @stencil/core@^1.0.2, required by @stencil/sass@1.3.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I run npm run start I get an warning about use of Node.js version. I have an LTS and the compiler suggest to use LTS only because of the support. But v14 is not currently LTS.

**Expected behavior:**
Show this warning after v14 will become LTS.

**Steps to reproduce:**
npm run start

> @o2/web-components@202005.0.5 start /Volumes/Data/Projects/O2/web-components
> stencil build --dev --watch --serve

Your current version of Node is v12.18.3, however Stencil's recommendation is v14.5.0 or greater. Note that future versions of Stencil will eventually remove support for non-LTS Node versions and an Active LTS version is recommended (https://nodejs.org/en/about/releases/).

**Comment by claviska** [comment]
Sorry for the delay. Node 14 went into LTS on 2020-10-27 so this appears to be resolved.

**Comment by erichstark** [comment]
Good tactics to wait for Node 14 LTS ;)
