### ISSUE TITLE
Rollup parse error with typescript files

### ISSUE THREAD

**Issue by juanmiguelbesada** [ionic-team/stencil#2673]
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When importing a library that contains typescript files, component do not compile, and Rollup parse error appears.

````
[51:34.0]  @stencil/core
[51:34.3]  v2.0.3 🍮
[51:37.4]  build, rollup-typescript-issue, dev mode, started ...
[51:37.4]  transpile started ...
[51:39.1]  transpile finished in 1.72 s
[51:39.1]  copy started ...
[51:39.1]  generate lazy started ...
[51:39.2]  copy finished (0 files) in 66 ms
[51:39.7]  generate lazy finished in 511 ms

[ ERROR ]  Rollup: Parse Error: ./node_modules/@google-web-components/google-chart/loader.ts:31:20
           Unexpected token (Note that you need plugins to import files that are not JavaScript)

     L30:  // Try to find existing loader script.
     L31:  let loaderScript: HTMLScriptElement|null = document.querySelector(
     L32:      'script[src="https://www.gstatic.com/charts/loader.js"]');

[51:39.7]  build failed, watching for changes... in 2.27 s

[51:39.7]  http://localhost:3333/
````
**Expected behavior:**
Allow co import npm packages that contains typescript files

**Steps to reproduce:**
Create a new project using npm init stencil, install library "@google-web-components/google-chart": "^4.0.0" and types "@types/google.visualization": "0.0.51".

````json
  "dependencies": {
    "@google-web-components/google-chart": "^4.0.0",
    "@stencil/core": "^2.0.1"
  },
  "license": "MIT",
  "devDependencies": {
    "@types/google.visualization": "0.0.51"
  }
````

Import library in component using
````ts
import "@google-web-components/google-chart";
````

and render a sample chart

```tsx
<google-chart data='[["Month", "Days"], ["Jan", 31]]'></google-chart>
```

**Related code:**

Example repository: https://github.com/juanmiguelbesada/stencil-typescript-rollup-issue
Related issues in ionic forums: https://forum.ionicframework.com/t/rollup-parse-error/193177

**Other information:**

I guess is miss configuration in tsconfig or in stencil.config.ts but I tried evering I could figure, but nothing works. so maybe its a stencil bug

**Comment by popcorn245** [comment]
I also have this issue when upgrading from 1.9.2 to ^2.0.0.  We use GraphQL Code Generator to bundle an SDK and it pulls in a TypeScript file.

![image](https://user-images.githubusercontent.com/4184680/94069829-dbb26c00-fdb6-11ea-986f-d31d0ef94848.png)

Link to GraphQL Code Generator
https://graphql-code-generator.com/

**Comment by Prince7195** [comment]
i'm getting same error on building the app

**Comment by popcorn245** [comment]
I have resolved the issue by add Typescript rollup plugin.

```
npm install --save-dev rollup-plugin-typescript
```
And these changes in stencil.config.ts
![image](https://user-images.githubusercontent.com/4184680/97834183-ce817a80-1c9c-11eb-8e86-40e495d23ad2.png)

You can also fix issues with importing commonjs ect using this method of passing custom rollup plugins. Hope this helps someone.

**Comment by jwillmer** [comment]
@popcorn245 you made my day! Looked all over the internet for this.

**Comment by christophsaile** [comment]
@popcorn245 thanks for your solution :) 
the solution worked for me but only with the "rollup-plugin-typescript" - package, "@rollup/plugin-typescript" did still fail for me.

**Comment by rwaskiewicz** [comment]
I'm unable to reproduce this locally with the provided reproduction case with the following libraries:
```
➜  stencil-typescript-rollup-issue git:(master) ✗ npm ls @types/google.visualization
└── @types/google.visualization@0.0.51

➜  stencil-typescript-rollup-issue git:(master) ✗ npm ls @google-web-components/google-chart
└── @google-web-components/google-chart@4.0.2

➜  stencil-typescript-rollup-issue git:(master) ✗ npm ls @stencil/core
└── @stencil/core@2.22.3
```

After running `npm install` and `npm run build`/`npm start`, the build here seems to be passing. If there are any particular steps I'm missing here, please let me know!
