### ISSUE TITLE
Focus in/out callbacks doesn't work on contenteditable spans

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil#2674]
**Stencil version:**
```
 @stencil/core@1.17.2
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Focus in/out callbacks never execute on `contenteditable` `span`s

**Expected behavior:**
Focus in/out callbacks do execute on `contenteditable` `span`s

**Related code:**

```tsx
<span
  contenteditable
  ref={(e) => {
    /* These work just fine */
    e.addEventListener('focusin', () => console.log('focusin WORKS!'))
    e.addEventListener('focusout', () => console.log('focusout WORKS!'))
  }}
  /* These don't */
  onFocusIn={() => console.log('DOESN’T WORK!')}
  onFocusOut={() => console.log('DOESN’T WORK!')}
>Edit me!</span>
```

**Other information:**

**Comment by claviska** [comment]
Confirmed. The declaration was added in 8796aa81edd13bf4367155d5bbd9609482024f34 but it's definitely not working for `contenteditable` elements.

Thanks for posting this!

**Comment by claviska** [comment]
Looks like a dup of https://github.com/ionic-team/stencil/issues/2628
