### ISSUE TITLE
taskQueue in stencil.config.ts is a NOOP when using dist-custom-elements-bundle

### ISSUE THREAD

**Issue by jpzwarte** [ionic-team/stencil#2675]
**Stencil version:**
```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

I am replacing the internals of my angular design system with stencil web components. The web components have been built with `dist-custom-elements-bundle` output target. While trying to get the angular jasmine tests running again (the replacement procedure should be unnoticeable for the angular users), I ran into an issue where *everything* that happens in my stencil web components, happen asynchronously (in the next tick). This is especially nasty in my jasmine tests, where the code expects changes to happen synchronously.

After looking at the docs, I tried setting `taskQueue: 'immediate'`, but after reading *lots* of stencil source code, it seems `dist-custom-elements-bundle` and `taskQueue` do not mix.

Is there a way to make things behave synchronously? I'm afraid this behavior will also make writing jasmine tests in applications using the stencil web components more complex.

Workaround for now:

```js
    it('should have an error type', async () => {
      await new Promise(resolve => setTimeout(resolve, 0));

      expect(alert).toHaveAttribute('type', 'error');
    });
```

**Comment by alicewriteswrongs** [comment]
Hey @jpzwarte, thanks for filing this issue and sorry that it took so long for anyone on the Stencil team to get back to you about this issue.

I know it's been a while and possibly you've moved on at this point, but would it be possible for you to provide a reproduction case for this issue? That could be a small repo starting from `npm init stencil` as a base or a StackBlitz or something along those lines. Having a reproduction greatly helps us to resolve issues.

Thanks and sorry again this sat for so long!

**Comment by jpzwarte** [comment]
@alicewriteswrongs Hi, like you correctly guessed, I've moved on from Stencil, so I can't help anymore.

**Comment by alicewriteswrongs** [comment]
@jpzwarte thanks for circling back anyhow, and good luck with whatever you're working on now! 🙂

**Comment by k1w1** [comment]
This issue seems to be caused by/related to this other issue: https://github.com/ionic-team/stencil/issues/2566. The problem is that the @stencil/core code is loaded directly from the npm module, bypassing the `BUILD` configuration output from `stencil.config.ts` - so the configuration is not applied.
