### ISSUE TITLE
Stencil postcss conflict with Stencil 2.0

### ISSUE THREAD

**Issue by olivier65** [ionic-team/stencil#2677]
**Stencil version:**
```
@stencil/core@2.0.3
```

**I'm submitting a:**
[ X] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
npm complains:
```
@stencil/postcss@1.0.1 requires a peer of @stencil/core@^1.0.2 but none is installed. You must install peer dependencies yourself
```

**Expected behavior:**
npm should not complain.

**Steps to reproduce**
Install Stencil 2.0

**Other information:**
This is a cousin of issue #2658.

**Comment by claviska** [comment]
This will be fixed as soon as this gets merged https://github.com/ionic-team/stencil-postcss/pull/29

**Comment by Flowrome** [comment]
I know that this is closed but we'd like to have news when this will be merged due to the fact that we're unable to install these dependencies without --force (As you may know this can break dev-ops pipelines).
