### ISSUE TITLE
transformTagName does not impact scope id

### ISSUE THREAD

**Issue by softwaymedical** [ionic-team/stencil#2678]
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When defining a `transformTagName` function to change how the custom elements are defined, it doesn't change the component CSS scope id. In a usecase where you use two different version of the same component, there respective CSS overlaps. 

**Expected behavior:**
When defining a `transformTagName` function, it should change how the custom elements are defined *and* change their CSS scope id.

**Steps to reproduce:**
```
// V1 component 

import {
  Component, Host, JSX
} from '@stencil/core';

@Component({
  tag: 'swm-simple-component',
  styleUrl: 'simple-component.scss',
  /*
    Contains 
    :host { font-weight: bold }
  */
  shadow: false,
  scoped: true,
})
export class SimpleComponent {
  render(): JSX.Element {
    return <Host>
      <slot></slot>
    </Host>;
  }
}
```

```
// V2 component 

import {
  Component, Host, JSX
} from '@stencil/core';

@Component({
  tag: 'swm-simple-component',
  styleUrl: 'simple-component.scss',
  /*
    Contains 
    :host { text-decoration: underline }
  */
  shadow: false,
  scoped: true,
})
export class SimpleComponent {
  render(): JSX.Element {
    return <Host>
      <slot></slot>
    </Host>;
  }
}
```

Results in : 

```
// Load V1 with a tranformTagName function : (tn) => 'V1-${tn}'
// Load V2 with a tranformTagName function : (tn) => 'V2-${tn}'
<style>
// from V1
.sc-swm-simple-component-h { font-weight: bold }
</style>
<style>
// from V2
.sc-swm-simple-component-h { text-decoration: underline }
</style>
<v2-swm-simple-component class="sc-swm-simple-component-h">
Some text
</v2-swm-simple-component>
```

**Other information:**
We are writing a PR to fix that :

**Comment by ch3rub1** [comment]
Did someone found some time to look into this issue and/or the associated PR ? We would love to have some feedback on this :)
