### ISSUE TITLE
Remove component tag 

### ISSUE THREAD

**Issue by mahyar33** [ionic-team/stencil#2683]
@stencil/core@2.0.3 

**I'm submitting a:**
[ ] bug report
[ x] feature request
[ ] support request 

I'm trying to remove the called component tag from HTML to prevent some broken CSS from external libraries and just show the inner content.

**something.component.html**

```
<div>
    Hello World
</div>
```
**another.component.html**

 ```
<div>
    <app-something [config]="somethingConfig"></app-something>
 </div>
```
**Then outputs:**

```
 <div>
    <app-something>
      <div>
          Hello World
      </div>
    </app-something>
</div>
```
**And I want:**

```
<div>
  <div>
     Hello World
  </div>
</div>

```

**Comment by dogoku** [comment]
The only thing that vaguely reminds me of this, are functional components: https://stenciljs.com/docs/functional-components

But do not, these are not full fledged stencil components, but rather a feature of JSX

**Comment by claviska** [comment]
Custom elements can't be renderless like those of a framework. There's really no way Stencil can do something like this and maintain scoping through shadow roots. It's just not how custom elements are designed to work.

The closest I've come is using `display: contents` which does render the component in the DOM, but visually the child element will be "hoisted" to the same level.

For example, [Shoelace's animation component](https://shoelace.style/components/animation) uses this technique to wrap an arbitrary element without worrying about its `display` property.
