### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Prince7195** [ionic-team/stencil#2685]
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[1] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Rollup: Parse Error
           Unexpected token (Note that you need plugins to import files that
           are not JavaScript) 1: export { MyComponent as my_component } from
           'Code/charts-component/src/components/my-component/my-component.tsx';

**Expected behavior:**
  Build the components

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by de-dan** [comment]
Can you show the content of my-component.tsx? Are you importing anything not JavaScript-like?

**Comment by Prince7195** [comment]
import { Component, Prop, h } from '@stencil/core';
import { format } from '../../utils/utils';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true,
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: string;

  /**
   * The last name
   */
  @Prop() last: string;

  private getText(): string {
    return format(this.first, this.middle, this.last);
  }

  render() {
    return <div>Hello, World! I'm {this.getText()}</div>;
  }
}


I did not change any code in  the default templated generated by stencil

**Comment by Prince7195** [comment]
I found the reason for the issue, It is due to the parent folder name, parent folder name has 's and space
