### ISSUE TITLE
Prop()'s type should be inferred using the TS's type-checker

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#269]
Some props that does not work correctly because the type is not inferred correctly.
```ts
// Using union types of strings
@Prop() a: 'hola' | 'hello';

// Giving a default value from a const 
const DEFAULT_VALUE = 'hello';
@Prop() b = DEFAULT_VALUE;

// Using an enum (numbers)
const enum Type {
    Overlay = 'Overlay'
}
@Prop() c: Type = Type.overlay;

const enum TypeNumber {
    Overlay
}
@Prop() d = TypeNumber.Overlay;

type Type3 = 'hola' | 'hello';
@Prop() e = Type3;
```
https://github.com/ionic-team/stencil/blob/master/src/compiler/transpile/transformers/prop-decorator.ts#L66-L70

The current approach is too strict. I think by using the built-in typescript type-checker we could fix this. https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker

In the meantime, as @jthoms1 pointed out, we could make the `string` type a catch all.

**Comment by Hotell** [comment]
may be related to https://github.com/ionic-team/stencil/issues/280
