### ISSUE TITLE
assets with same name clash when used in multiple components

### ISSUE THREAD

**Issue by jaredcbaum** [ionic-team/stencil#2690]
**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Stencil Version**: 2.0.3

**Current behavior:**
![Screenshot from 2020-10-01 20-51-41](https://user-images.githubusercontent.com/61951482/94880307-26bc2700-0428-11eb-8166-70c3c2fbccbf.png)

If both of the 'assets' directories in the picture above contain an image with the same name, only the second image will appear in the build output.  That would lead me to believe that the first image is being overwritten by the second image with the same name.

**Expected behavior:**
I'd expect both images to appear somewhere in the build output.  It may require structuring the assets folder differently.  Images could be put in a folder that is named after the component for example, eliminating any clashes.  A change like this could also affect ```getAssetPath()```, among other things.

**For Example:**
![Screenshot from 2020-10-01 21-05-24](https://user-images.githubusercontent.com/61951482/94880973-2755bd00-042a-11eb-97f3-b50840336c0c.png)
There are two images here name "hero-image.jpg" in different components assets directories.

![Screenshot from 2020-10-01 21-07-14](https://user-images.githubusercontent.com/61951482/94881072-6257f080-042a-11eb-9db0-9be60d754af3.png)
Here is the build output with only one image.

**Comment by claviska** [comment]
> That would lead me to believe that the first image is being overwritten by the second image with the same name.

Looks like the entire directory is overwritten when the name isn't unique. They don't get merged.

> I'd expect both images to appear somewhere in the build output. It may require structuring the assets folder differently. Images could be put in a folder that is named after the component for example, eliminating any clashes.

I just tested this out. Looks like it's currently possible by using a unique folder name for each component. For example:

```tsx
@Component({
  tag: 'some-component',
  shadow: true,
  assetsDirs: ['some-component-assets'],
})

@Component({
  tag: 'another-component',
  shadow: true,
  assetsDirs: ['another-component-assets'],
})
```

Gives you:

```
dist/<project>/another-component-assets/*
dist/<project>/some-component-assets/*
```

I'm not convinced that Stencil should be opinionated by using the component name as a namespace here. That would prevent the overwriting issue, but what happens if there are two files of the same name? We can't just rename it since you'd have no idea what the resulting filename is. I think an error would be more appropriate when the folder name isn't unique.

Any thoughts on this one @adamdbradley?

**Comment by jaredcbaum** [comment]
Yeah that was the workaround I was currently doing (should have posted it).
Since assetsDirs is defined as a Component decorator prop, ideally it shouldnt have to be namespaced.  Imo since theres nothing telling me it's global, I wouldn't expect it to work that way.

**Comment by jaredcbaum** [comment]
Throwing an error would work but would kind of be a retroactive action.
