### ISSUE TITLE
Stencil config generating files in dist that dosent work standalone

### ISSUE THREAD

**Issue by rahulrsingh09** [ionic-team/stencil#2691]
I have started on stencil development and tried to create the hello world from it but while trying to build and deploy and use it stand alone the dist file is generating some random files which dosent seem to work standalone .

I have published the files to npm and trying to run it standalone in a html file.using unpkg
https://unpkg.com/browse/rahulrsingh09-stenciltest2@0.0.2/dist/

    <!DOCTYPE html>
    <html>

    <head>
      <meta charset="utf-8">
      <title></title>
      <meta name="author" content="">
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      
    </head>

    <body>

     <my-component first="FF" last="'Don't call me a framework' JS"></my-component>

    <script src='https://unpkg.com/rahulrsingh09-stenciltest2@0.0.2/dist/index.js'></script>
    </body>

    </html>

and this one is a test from a different package i found in npm and this seems to work .

    <!DOCTYPE html>
    <html>

    <head>
      <meta charset="utf-8">
      <title></title>
      <meta name="author" content="">
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      
    </head>

    <body>

     <my-component first="FF" last="'Don't call me a framework' JS"></my-component>

    <script src='https://unpkg.com/web-component-stencil-test@0.0.1/dist/test.js'></script>
    </body>

    </html>

The only difference i found is https://unpkg.com/browse/web-component-stencil-test@0.0.1/dist/

the dist contains a root file for the main of project which runs standalone but this is not generated in the new stencil config build. the documentation on this is very sparse , can some one point me what am i doing wrong.. here or something missing by stencil.

**package.json** 

    "name": "stenciltest2",
      "version": "0.0.2",
      "description": "Stencil Component Starter",
      "main": "dist/index.cjs.js",
      "module": "dist/custom-elements/index.js",
      "es2015": "dist/esm/index.mjs",
      "es2017": "dist/esm/index.mjs",
      "types": "dist/custom-elements/index.d.ts",
      "collection": "dist/collection/collection-manifest.json",
      "collection:main": "dist/collection/index.js",
      "unpkg": "dist/test/test.js",
      "files": [
        "dist/",
        "loader/"
      ],

**stencil config**

    import { Config } from '@stencil/core';
    
    export const config: Config = {
      namespace: 'test',
      buildEs5: true,
      outputTargets: [
        {
          type: 'dist',
          esmLoaderPath: '../loader',
        },
        {
          type: 'dist-custom-elements-bundle',
        },
        {
          type: 'docs-readme',
        },
        {
          type: 'www',
          serviceWorker: null, // disable service workers
        },
      ]
    };

**Comment by phanmn** [comment]
Let try this one @rahulrsingh09:
`<script src='https://unpkg.com/rahulrsingh09-stenciltest2@0.0.2/dist/test/test.js'></script>

**Comment by rahulrsingh09** [comment]
@phanmn That one works i figured that out but why this ,, why is there no index.js up in the dist is there something missing in the config ?

**Comment by phanmn** [comment]
`index.js` exist in `dist`, but in `index.js` it import empty file, and I don't know why it empty

**Comment by christian-bromann** [comment]
Hi @rahulrsingh09 👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue. Please checkout our latest [docs](https://stenciljs.com/docs/publishing) on publishing Stencil components.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
