### ISSUE TITLE
Stencil force including 130KB of prebuilt ES5 polyfills in every build (?)

### ISSUE THREAD

**Issue by chriswep** [ionic-team/stencil#2692]
This is somewhat related to https://github.com/ionic-team/stencil/issues/2682 - a potential fix might solve both issues though. However its still a separate issue that is relevant in contexts outside of the differential build part not working.

**Stencil version:**
I'm using Ionic Angular 5.3.3

**I'm submitting a:**
[x] bug? / feature?

**Current behavior:**
When building an Ionic project via Angular, the following polyfills files from Stencil are included in the build files:
```
chunk {5} polyfills-core-js.79ebeed52926c7a46d5b.js (polyfills-core-js) 91.8 kB  [rendered]
chunk {6} polyfills-css-shim.cb3ce672a1e335049b39.js (polyfills-css-shim) 7.91 kB  [rendered]
chunk {7} polyfills-dom.740cf840969ed7443ba5.js (polyfills-dom) 36 kB  [rendered]
```

Angular has its own (dynamic) polyfills mechanism:
```
chunk {4} polyfills.479c714c8555b532c330.js (polyfills) 36.2 kB [initial] [rendered]
```

**Expected behavior:**
A lot of the Stencil polyfills are not needed in most contexts. I would also expect that most of the remaining polyfills are already included by existing polyfill mechanisms in builds (like Angular).

**Steps to reproduce:**
Create a new Ionic project, build.

Stencil is pulling in more than 130KB of minified code here that is potentially duplicate or not necessary. This is a huge number in the context of web-apps.

Maybe Ionic should tap into the Angular polyfill mechanism here and not ship prebuilt polyfills. Maybe it could be a solution to add an option to let the user take care of polyfills.

**Comment by chriswep** [comment]
polyfills are only loaded on runtime if necessary. closing.

**Comment by USG-barrettn** [comment]
thanks dude. stay classy.
