### ISSUE TITLE
[Question/Bug] Autoprefixer/caniuse-lite in NOTICE.md

### ISSUE THREAD

**Issue by Purii** [ionic-team/stencil#2700]
`Autoprefixer` is currently listed as `devDep`: https://github.com/ionic-team/stencil/blob/master/package.json#L80
But also defined as `entryDep` in the license script: https://github.com/ionic-team/stencil/blob/master/scripts/license.ts#L11

This leads to an entry of `caniuse-lite`, which is a dependency of `autoprefixer`  in the `NOTICE.md`. Is there a reason for that?
I assume `autoprefixer` won' t be shipped with a created bundle.

Asking, because `autoprefixer` depends on `caniuse-lite` which has some discussions about its license (CC 4.0), which could be a critical licenses for some orgs.

**Comment by claviska** [comment]
`NOTICE.md` isn't shipped with a bundle — [it's generated](https://github.com/ionic-team/stencil/blob/master/scripts/license.ts#L56) for the Stencil source code.

Are you seeing it somewhere in your bundle?

**Comment by Purii** [comment]
@claviska No it's not part of the bundle. I know that, because I understand what the package does and roughly understand how it is used by `stencil`. But open source compliance scanners don't have that knowledge and just scan the whole package (which includes the `NOTICE.md` with a license text for CC-BY-4.0).

`autoprefixer` is already listed in the `devDependencies`, which would prevent that issue. But because of that entry it is included in the `NOTICE.md`: https://github.com/ionic-team/stencil/blob/master/scripts/license.ts#L11

I'm wondering why it's included there explicitly.
