### ISSUE TITLE
Property 'sl-button' does not exist on type 'JSX.IntrinsicElements'

### ISSUE THREAD

**Issue by doronnac** [ionic-team/stencil#2708]
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Solid-js (jsx) + typescript produces the following errors:
`Property 'sl-button' does not exist on type 'JSX.IntrinsicElements'.`
Then when it's [fixed](https://gist.github.com/doronnac/152ebcbf3338ae3a6c92ec5f8612ced6#file-shoelace-solid-first-fix-d-ts):
`Type '{ children: string; }' has no properties in common with type 'SlButton'.`
[Fix for both errors](https://gist.github.com/doronnac/152ebcbf3338ae3a6c92ec5f8612ced6#file-shoelace-solid-final-fix-d-ts)

**Expected behavior:**
No errors should occur I suppose

**Steps to reproduce:**
- `npm init solid app-ts my-app`
- `npm install @shoelace-style/shoelace`
- Go to `App.tsx`
- Add any element i.e `<sl-button>hi</sl-button>`

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**
https://github.com/shoelace-style/shoelace/issues/250

**Comment by bitflower** [comment]
Did you `import @shoelace-style/shoelace`?

**Comment by doronnac** [comment]
Hi, thanks for your response.
I haven't imported it, I did try just now and the error came back when I removed the declaration file

**Comment by claviska** [comment]
Looks like a dup of #1636. Please subscribe to that issue.
