### ISSUE TITLE
importing @ionic/core will fail every other build

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil#271]
**Stencil version:**

```
 @stencil/core@0.0.7-0 (can also repro with latest master branch)
```

**I'm submitting a:**

- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

While developing you will run into an issue where the `@ionic/core` module will not be found every other build. The `every other build` part is key.

**Steps to reproduce:**

- git clone https://github.com/jgw96/stencil-beer.git
- npm run dev
- make changes while running the dev build

**Comment by jthoms1** [comment]
Example of failure.
<img width="571" alt="screen shot 2017-11-01 at 9 37 21 pm" src="https://user-images.githubusercontent.com/1425431/32307111-e321d0ee-bf4c-11e7-9a82-b1281d862fe6.png">

**Comment by jthoms1** [comment]
I am not sure how this worked for @ionic/core. The files in the package.json file do not exist.

**Comment by jthoms1** [comment]
Tried to reproduce in stencil-beer using ```import format from 'date-fns/format'``` but was unable to see the error. Using `date-fns@1.29.0`.

**Comment by jthoms1** [comment]
@jgw96 to provide a repo to contains the issue.

**Comment by julesjanssen** [comment]
Just FYI, the same happened for me whenever I tried to import `lodash.chunk`. Every other build attempt failed.

**Comment by jthoms1** [comment]
This should be fixed with PR https://github.com/ionic-team/stencil/pull/325
