### ISSUE TITLE
Make "forceUpdate" re-render the whole tree

### ISSUE THREAD

**Issue by pixelbucket-dev** [ionic-team/stencil#2711]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Only update/re-renders the component where `forceUpdate` is called.

**Context:**
I am working on a i18n solution in our stencil app. When the user changes the language the whole app should re-render. For this I want to wrap the root node in a `translator` component that handles language change detection and calls `forceUpdate`. I want to avoid having to add this to every translated component that needs re-render on language change.

**Proposed solution:**
```tsx
forceUpdate(this, true)
```
… with the boolean to invalidate the whole tree. This would be much simpler than to add this code in each component that needs re-render, almost all of them.

In the stencil source I see this being called:
```tsx
scheduleUpdate(hostRef, false);
```
Could `scheduleUpdate` be called with `isInitialLoad = true` (derived from the `forceUpdate` arg)? Would that re-render the whole tree under that component?

**Comment by claviska** [comment]
Using `forceUpdate()` is typically a bad practice and should be avoided when possible. Ideally, this should be done with [Stencil store](https://stenciljs.com/docs/stencil-store) so when the locale changes, everything utilizing the store updates automatically.

In other words, you shouldn't have to call force update yourself, much less call it on an entire tree. Based on the discussion in the Stencil Slack, it looks like you've found a solution so I'm closing this one.

**Comment by pixelbucket-dev** [comment]
Thanks for the suggestion. The issue with stencil store is that I would have to import it in each component that should react to that change. And I would have to expose a prop that I don't even want to render. Feels wrong.

**Comment by Arvind6353** [comment]
@pixelbucket-dev hi. Did u get a way to solve tis?

**Comment by shilpihjp12** [comment]
Hi @pixelbucket-dev, Hi @claviska,

I also have the same requirement as @pixelbucket-dev proposed the share the context. 

I am also trying to re-render complete application. But, it is not working with forceUpdate() method. As per you previous discussion, there is some solution that got discussed on Stencil Slack.

Is this possible for you guys to share the solution here. it will help me as well for my application.

Thanks in Advance!

**Comment by pixelbucket-dev** [comment]
What I did do is to have a wrapper component that wraps the whole component tree (I call it provider). That provider component has a method, that I can call externally (by dom-selecting that element). This method receives a DOM element/node, which then is added to a Set (`private readonly elements = new Set<ComponentInterface>();`). I also have an event handler on that component. Every time that event is called, I run through the Set of components and call `this.elements.forEach(el => forceUpdate(el));` on them. This will only rerender the components I want.
