### ISSUE TITLE
The [event name] event was emitted, but the dispatcher node is no longer connected to the dom.

### ISSUE THREAD

**Issue by pixelbucket-dev** [ionic-team/stencil#2714]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When dispatching an event in the `disconnectedCallback` I get above warning. That is obviously the correct behaviour. The problem is, that I would like to notify another component when an element got removed. Unfortunately, there is not life-cycle hook `willDisconnectCallback` or similar to handle this case. Could such a feature be added? If not, is there an alternative workaround?

**Comment by claviska** [comment]
Both `connectedCallback()` and `disconnectedCallback()` map to the [native custom element methods](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) of the same names. I'm not sure we can tap into the DOM in such a way to offer a `beforeDisconnect` event, as many things can cause a node to disconnect.

Perhaps what you're looking for is a [mutation observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) on an ancestor that can detect when nodes are added or removed.

**Comment by pixelbucket-dev** [comment]
Thanks, mutation observer sounds like a good idea :).
