### ISSUE TITLE
Using standard event names

### ISSUE THREAD

**Issue by axross** [ionic-team/stencil#2715]
**Stencil version:**

```
 @stencil/core@7.12.3
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Hi all, after I shortly explored, I found that we don't allow to use event names that typically used in the DOM (such as `change`, `focus` and `keydown`). But as long as creating a design system is one of use cases for Stencil, sometimes we want to create thin "fancy" components, which are elements just styled up with CSS so it looks good with their branding. In this case, it's pretty common and safe choice to use standard event names for events.

I want to know how and what do you think about it and hopefully I want to create a pull request to configure an allow-list to ignore event name conflict.

**Related code:**

```tsx
@Component({
  /// ...
})
export class FancyInput {
  @Event({
    eventName: 'change',
  })
  changeEvent: EventEmitter<any>;
```

```sh
[ WARN  ]  Build Warn: ./src/components/fancy-input/fancy-input.tsx:22:3
           The event name conflicts with the "change" native DOM event name.

     L21:    })
     L22:    changeEvent: EventEmitter<any>;
```

**Comment by claviska** [comment]
@adamdbradley do you know if there's a technical reason for this limitation? If not, does it make sense to offer a way to suppress this warning somehow?
