### ISSUE TITLE
Create JS benchmark

### ISSUE THREAD

**Issue by alexkreidler** [ionic-team/stencil#2716]
This repository: https://github.com/krausest/js-framework-benchmark is a benchmark of many frontend libraries.

It would be great if a contributor could add Stencil to that benchmark so we could compare!

**Comment by claviska** [comment]
You'll probably get a better response by posting an issue there, as folks familiar with those benchmarks will be more apt to write the code for it. Somebody also mentioned Stencil on [this issue](https://github.com/krausest/js-framework-benchmark/issues/441).

Closing since this isn't an issue.
