### ISSUE TITLE
react output targets generating export from other packages. 

### ISSUE THREAD

**Issue by marcello0liveira** [ionic-team/stencil#2717]
**Stencil version:**

```
 @stencil/core@<2.1.1>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

react output targets generating export from other packages. 

**Expected behavior:**

react output targets only generate export from the current package.

**Steps to reproduce:**

1. create foo stencil component package:
`npm init stencil > components > foo`
2. create bar stencil component package:
`npm init stencil > components > bar`
3. replace `my-component` with `foo-duck` component at foo
4. replace `my-component` with `bar-dog` component at bar
5. link foo in bar
6. import foo at bar/src/index.ts by: `import "foo";`
7. add `import { reactOutputTarget } from '@stencil/react-output-target';` to foo and bar at `stencil.config.ts`
8. generate foo-react and bar-react

at `bar-react` you will be able to see the following code:

```tsx
import type { JSX } from 'bar';

export const BarDog = /*@__PURE__*/createReactComponent<JSX.BarDog, HTMLBarDogElement>('bar-dog');
export const FooDuck = /*@__PURE__*/createReactComponent<JSX.FooDuck, HTMLFooDuckElement>('foo-duck');
```
as FooDuck doesn't exist in JSX, the build will break.

How can we fix that?

**Comment by alicewriteswrongs** [comment]
Hello @marcello0liveira, this looks like a support request or possibly a bug report which should be filed on the separate repo where the code for the React output target lives (https://github.com/ionic-team/stencil-ds-output-targets). If you're still experiencing this issue please feel free to re-open it over there with a reproduction case. Thanks!
