### ISSUE TITLE
Make dev server startup timeout configurable

### ISSUE THREAD

**Issue by softwaymedical** [ionic-team/stencil#2718]
**Stencil version:**

```
 @stencil/core@2.1.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Dev server startup timeout is fixed to 15 seconds. On some slow or overloaded computers the dev server need more than 15 seconds to start.

**Asked behavior:**

We would like to configure it to be more than 15 seconds and allow it to start on slow or overloaded computers

**Steps to reproduce:**

- Use a standard computer as a GitLab Runner.
- Launch 1 test pipeline => Success
- Launch 3 or 4 tests pipelines simultaneously => The error occurs randomly

**Related code:**

```ts
  // src/dev-server/index.ts 
  // ... 
  const startupTimeout =
    logger.getLevel() !== 'debug'
      ? setTimeout(() => {
          reject(`dev server startup timeout`);
        }, 15000)
      : null;
  // ... 
```

**Other information:**

I'm preparing a PR to add an option to specify the dev server startup timeout.

**Comment by simonhaenisch** [comment]
Nice I had exactly the same problem and while going through the Stencil source I noticed that the timeout is skipped when using `--debug` which I used as a temporary workaround for our Github Actions e2e testing pipeline 😅

Thanks 🙌

**Comment by simonhaenisch** [comment]
Just trying to use this, I think you might have used the wrong interface to expose this?

```
'startupTimeout' does not exist in type 'StencilDevServerConfig'.
```

Your PR added this to DevServerConfig which I think is only used internally as an extension of the user's config.

**Comment by softwaymedical** [comment]
Well, I just saw this, and you are right, we didn't put it in the good interface. 
Thanks for your PR :)

**Comment by claviska** [comment]
Thanks everyone! This was merged in #2719 and #2733.

**Comment by simonhaenisch** [comment]
@claviska except #2733 hasn't been merged yet 😅

**Comment by claviska** [comment]
@simonhaenisch whoops, got click happy after seeing the purple above. Good call!
