### ISSUE TITLE
Unable to import @ionic/core

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/stencil#2720]
**Stencil version:**

```
 @stencil/core@2.2.0
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I'm importing `@ionic/core` to use for example `createAnimation`. When i try to present my newly created overlay, i get the following error:

```
TypeError: Module specifier, '@ionic/core' does not start with "/", "./", or "../". Referenced from http://localhost:3333/dist/core/simplify-toast.entry.js
```
```
Unhandled Promise Rejection: Error: Constructor for "simplify-toast#undefined" was not found
```

**Expected behavior:**

To be able to import `@ionic/core` 😃

**Comment by claviska** [comment]
It looks like you're trying to import the module from a file in your `dist` directory, so it's falling back to a standard ES6 import handled by the browser (hence the error).

Try importing it from your component file or from `src/index.ts`.

Using the app starter, I modified the top of `app-root.tsx` to look like this:

```js
import { Component, h } from '@stencil/core';
import * as ionic from '@ionic/core';

console.log(ionic);
```

Result:
<img width="614" alt="CleanShot 2020-11-16 at 13 31 45@2x" src="https://user-images.githubusercontent.com/55639/99293047-16151400-2810-11eb-8365-3f58941ffda9.png">

**Comment by EinfachHans** [comment]
This happens in my tests (if i run `npm run`), so of course it is imported from the `dist` Folder 🤔 I import for example `createGesture` to create a gesture for my own component. Whats the correct way to import if i want to test it? @claviska

**Comment by claviska** [comment]
As shown above, anything can be imported from `@ionic/core` using the syntax above. The dist should never be referencing npm packages, so it looks like the import isn't being processed by the bundler.

> This happens in my tests

Which test(s)? Can you narrow it down and post the offending test(s) for review? Thanks!

**Comment by EinfachHans** [comment]
@claviska I configured my `npm start` to work like in Ionic: `stencil build --dev --watch --serve` to display all packages and be able to navigate through the packages. I also add a test folder to my component where some html's are. There when i try to present my new Component (it's an overlay) the error occurs.

I'm also importing this from **@ionic/core**:

```
import {AnimationBuilder, Color, CssClassMap, Gesture, OverlayEventDetail, OverlayInterface} from '@ionic/core';
```

I can't Import these from the `ionic` reference if i import it like you said, so i need both, but in the dist folder at the end of the day it is just:

```
import { createGesture, getTimeGivenProgression } from '@ionic/core';
```
