### ISSUE TITLE
 export 'setAssetPath' was not found in 'mylib/dist/custom-elements'

### ISSUE THREAD

**Issue by SwatiMaheshwari** [ionic-team/stencil#2722]
Stencil version:
@stencil/core@2.2.0

I'm submitting a:

[ ] bug report

Current behavior:
export 'setAssetPath' was not found in 'mylib/dist/custom-elements'

Expected behavior:
it should set path

Related code:

// insert any relevant code here
```
import {
  applyPolyfills,
  defineCustomElements,
} from "@paypay/pp-components/loader";
import { setAssetPath } from '@paypay/pp-components/dist/custom-elements';

setAssetPath(document.currentScript.src);

Vue.config.ignoredElements = [/pp-\w*/];

applyPolyfills().then(() => {
  defineCustomElements();
});
```

Other information:
import from loader works fine

**Comment by claviska** [comment]
You might need to import it like this (note the full filename):

```js
import { setAssetPath } from '@paypay/pp-components/dist/custom-elements/index.js';
```

If that doesn't work, can you look in `dist/custom-elements/index.js` to make sure you see something like this near the top?

```js
export { setAssetPath } from '@stencil/core/internal/client';
```
