### ISSUE TITLE
Edge 16-18: 'customElements' is not defined

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#2725]
**Stencil version:**

```
 @stencil/core@2.2.0 (also happens in earlier versions)
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
This works in IE11 (and also in Firefox, Chrome and Safari):

```
<script type="module" src="/app.esm.js"></script>
<script nomodule src="/app.js"></script>

<script>
  customElements.whenDefined()...
</script>
```

However, it throws an error on Edge 16-18:

```
'customElements' is not defined
```

The reason is that Edge 16-18 is loading the `app.esm.js` file, which seems to assume that the browser is "modern" and uses another polyfill handling.

**Expected behavior:**
Maybe Edge 16-18 should also use the "legacy" `app.js` file, like IE11 does?

**Other information:**
However, using `setTimeout()` works, but it's ugly and possibly unstable:

```
// Edge 16-18
<script type="module" src="/app.esm.js"></script>
<script nomodule src="/app.js"></script>

<script>
  setTimeout(function() {
    customElements.whenDefined()... // 'customElements' is here now
  }, 1000);
</script>
```

**Comment by claviska** [comment]
Have you tried the approach [outlined here?](https://stenciljs.com/docs/angular#edge-and-ie11-polyfills)

```js
import { applyPolyfills, defineCustomElements } from 'test-components/loader';
...
applyPolyfills().then(() => {
  defineCustomElements()
})
```

Edge 16-18 is unique in that it supports modules but not custom elements or shadow DOM. This approach will ensure the required polyfills are loaded before defining the elements.

We should probably update the docs to reflect this approach on the [vanilla JS page](https://stenciljs.com/docs/javascript) too.

**Comment by kraftwer1** [comment]
@claviska I think including the app using the `script` tag already does that?
Importing stuff from the loader should only happen if the app is included using a bundler or module system.
Including the app using the `script` tag should be plug'n'play IMHO.

**Comment by claviska** [comment]
It might be that the ESM version simply doesn't provide the polyfills or there's an old Edge-specific timing issue with them (I'm not certain, just making a guess here). The point is, if you call it explicitly, that should avoid the issue and may serve as a workaround.

I don't think we plan on spending much effort on IE11 and old Edge at this point, but if anyone has the time to dive in and submit a PR that would be awesome!
