### ISSUE TITLE
No typings for HTMLElement properties on component

### ISSUE THREAD

**Issue by mkay581** [ionic-team/stencil#2730]
**Stencil version:**

```
 @stencil/core@1.17
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
TS Error when trying to access `this.localName` on component:
```bash
Property 'localName' does not exist on type 'MyComponent'
```

**Expected behavior:**
No TS error.

**Steps to reproduce:**

```tsx
@Component()
export class MyComponent {
  connectedCallback() {
    console.log(this.localName) // TS error: Property 'localName' does not exist on type 'MyComponent'
  }
}
```

**Other information:**

**Comment by mkay581** [comment]
FYI extending `HTML` explicitly fixed TS error and makes `localName` available. But doing so causes a Stencil error.

```tsx
@Component()
export class MyComponent extends HTMLElement {
  connectedCallback() {
    console.log(this.localName) // Stencil error: Classes decorated with @Component can not extend from a base class.
  }
}
```

Here's full error:

```bash
Classes decorated with @Component can not extend from a base class.
Stencil needs to be able to switch between different base classes in order to implement the different output targets such as: lazy and raw web components.
```

**Comment by mkay581** [comment]
Another thing I noticed is that `localName` is not available on properties in tests. Should I file another issue on this?

**Comment by tricki** [comment]
Stencil component classes aren't HTML elements but are used to generate them. To get a reference to the actual HTML element you have to use the [Element Decorator](https://stenciljs.com/docs/host-element#element-decorator):

```ts
import { Component, Element } from '@stencil/core';

@Component()
export class MyComponent {
  @Element() el: HTMLElement;

  connectedCallback() {
    console.log(this.el.localName);
  }
}
```

You can also use the type of the generated class that inherits HTMLElement (e.g. [HTMLIonTabsElement](https://github.com/ionic-team/ionic-framework/blob/60aa027903a6865ec7bcdf971f681ce8d9517abf/core/src/components/tabs/tabs.tsx#L20)).

**Comment by mkay581** [comment]
Yes that helps me get the actual element but how do I test `this.el.localName` usage in tests? Currently it isnt defined when running unit tests.

**Comment by claviska** [comment]
Are you able to post a sample test (or at least the relevant code) where this is happening? Thanks!

**Comment by mkay581** [comment]
Hey sorry. I'm pretty busy these days. but all that's needed to reproduce is create a web component using Stencil and try to query the `localName` of the component in a Stencil unit test file.
