### ISSUE TITLE
not able to schematically link stencil package to angular before i publish that to npm

### ISSUE THREAD

**Issue by kk185212** [ionic-team/stencil#2737]
issue: not be able to schematically link my stencil package with angular 10, it is showing ivy engine issues.I am using yarn and along with that a monorepo space so that i can generate output targets for the code components in Angular,React and Vue.
1. I am not able to include my stencil components in app.module.ts file as defineCustomelements because my angular project does not  identify that and my package name in package.json file looks something like this:

"sample-package-name":"workspace:*"

**Comment by claviska** [comment]
Can you show exactly how you're trying to import the components? Thanks!
