### ISSUE TITLE
[Bug] Browser env transpile inside hydrate renderToString

### ISSUE THREAD

**Issue by somehowchris** [ionic-team/stencil#2742]
**Stencil version:**

```
 @stencil/core@1.17.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
We are trying to use stencils hydrate renderToString function on a nuxt server but currently we get an error that **HTMLCollection is not defined**. Inside the *hydrate/index.js* we found these lines
```js
if (typeof HTMLElement !== "undefined") {
        // browser env
        HTMLCollection.prototype.flatpickr = NodeList.prototype.flatpickr = function (config) {
            return _flatpickr(this, config);
        };
        HTMLElement.prototype.flatpickr = function (config) {
            return _flatpickr([this], config);
        };
}
```
They are generated by the compiler as we do not wrote those inside the components library. The problem is that HTMLCollection is not part of the nodejs env but somehow HTMLElement seems to be or seems to be some kind of emulated thing. 

Besides this everything works 💯 

**Expected behavior:**

Generate a check if HTMLCollection !== "undefined" and if so apply the needed thing.

**Steps to reproduce:**

We added the output target `dist-hydrate-script` to our *stencil.config.ts* and built it

I am currently not able to supply any futher example but if I can help with anything further I would be honored to help.

**Other information:**

https://stenciljs.com/docs/hydrate-app

**Comment by rwaskiewicz** [comment]
Hey @somehowchris 👋 

I apologize that it took so long for someone on the team to acknowledge this issue. If you're willing/able to, would you mind creating a minimal reproduction case for the team and I to take a look at? If not, I completely understand. Again, I apologize that this issue was never acknowledged.
