### ISSUE TITLE
Possibility to run "generateCustomDocs" after other docs generated.

### ISSUE THREAD

**Issue by AlexSapoznikov** [ionic-team/stencil#2751]
**Stencil version:**

```
 @stencil/core@2.3.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Currently all documentation generators run at the same time with Promise all like that:
``` 
await Promise.all([
    generateReadmeDocs(config, compilerCtx, docsData, docsOutputTargets),
    generateJsonDocs(config, compilerCtx, docsData, docsOutputTargets),
    generateVscodeDocs(compilerCtx, docsData, docsOutputTargets),
    generateCustomDocs(config, docsData, docsOutputTargets),
    outputCustom(config, compilerCtx, buildCtx, docsData, docsOutputTargets),
  ]);
```

**Expected behavior:**
I need to modify my readme files after they are generated by stencil.
Could you add for example a flag to **docs-custom** outpuTarget like this:
```
    {
      type: 'docs-custom',
      strict: true,
      generator: (docs: JsonDocs) => generateCustomDocs(docs),
      runGeneratorAsLast: true // not sure what could be the good name for it
    },
```

**Other information:**
I need to modify readme.md file after it is generated by stencil. I would like it to be a part of *stencil build --docs* process.
I am trying to add more documentation to readme files and I am trying to add them **after** the generated part of the documentation.

**Comment by claviska** [comment]
This isn't likely to happen, at this would complicate the way docs are generated. Plus a `runGeneratorAsLast` argument may  have collisions if it's set in more than one place.

What you can do is run a script after the build completes that will ensure all the docs are built before executing.

```json
"scripts": {
  "build-docs": "stencil build --docs && npm run my-docs-script",
  "my-docs-script": "[your custom script here]"
}
```

**Comment by AlexSapoznikov** [comment]
Alright, that was indeed my plan B. Thanks!
