### ISSUE TITLE
Production build Watch value unexpected returning undefined

### ISSUE THREAD

**Issue by liho98** [ionic-team/stencil#2753]
**Stencil version:**

```
 @stencil/core@2.3.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

![image](https://user-images.githubusercontent.com/44250267/100402383-12e31900-3097-11eb-9455-4d574b5b3d79.png)
![image](https://user-images.githubusercontent.com/44250267/100402436-33ab6e80-3097-11eb-914b-cc329598cb1c.png)
Watching value returned undefined at most of the time unexpectedly. But it working fine in development mode.

**Expected behavior:**

I never passing undefined to the props, hence it should not get undefined when watching the value.

**Steps to reproduce:**

Create a watch function for prop "value". Im using react, hence i have a react wrapper.
```
const RadioGroup = ({ name, onChange, disabled, value, ...props }) => {
  const elementRef = useRef(null);
  useEffect(() => {
    elementRef.current.name = name;
    elementRef.current.onChange = onChange;
    elementRef.current.disabled = disabled;
    elementRef.current.value = value;
    elementRef.current.class = props.className;
  }, []);
  return (
    <rm-radio-group
      ref={elementRef}
      class={props.className}
      style={props.style}
      name={name}
      disabled={disabled}
      value={value}
      onChange={onChange}>
      {props.children}
    </rm-radio-group>
  );
};
```

**Related code:**
```
  @Watch('value')
  async onValueChanged(newVal: string) {
    console.log('value', newVal);
    if(newVal !== undefined){
      await (async () => {
        await customElements.whenDefined('rm-radio');
        const rmRadiolements = [...Array.from(this.host.querySelectorAll('rm-radio'))];
        rmRadiolements.forEach((each: any) => {
          each.checked = each.value === newVal;
        });
      })();
    }
  }
```

**Other information:**

**Comment by rwaskiewicz** [comment]
Hey @liho98 👋 

I apologize that it took so long for someone on the team to get back to you. If you're willing/able to provide us with a full reproduction case so that we can look into this further, we'd really appreciate it. If not, I totally understand! Thanks so much for taking the time to put this together and help make Stencil better 💙 

Thanks again!
