### ISSUE TITLE
SyntaxError in Chrome/39.0.0.0

### ISSUE THREAD

**Issue by chenyulun** [ionic-team/stencil#2755]
**Stencil version:**

```
 @stencil/core@1.17.3<version>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

```shell
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
```

**Expected behavior:**

Old browsers should be able to load the polyfills.

**Steps to reproduce:**

Open a simple page using on  `Chrome/39.0.0.0`
`"Mozilla/5.0 (Linux; Android 5.1.1; vivo X7 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 MyAppHybrid/3.4.0 (MYAPPNAME 4.39.0) UnionPay/1.0 MYAPPNAME deviceId/AUUID_d0d6a8dc52d4247cc815328f5d72cca9b7abb81e deviceType/1 device-dpr/3.0 device-dr/640.0*360.0 networkState/WIFI"`
The stenciljs generated file won't be loaded and no custom element is defined in the page.

**Related code:**

```tsx
// insert any relevant code here
```
```js
'use strict';
(function () {
  var currentScript = document.currentScript;

  // Safari 10 support type="module" but still download and executes the nomodule script
  if (!currentScript || !currentScript.hasAttribute('nomodule') || !('onbeforeload' in currentScript)) {
```
If I comment out the if statement, it works fine

**Other information:**

**Comment by chenyulun** [comment]
`chrome39``index-3187e9a7.system.js`
```js
if (n.$flags$&8) { // if  n.$flags === 9
                    var t = e.__lookupGetter__("childNodes"); // t = undefined
                    Object.defineProperty(e, "children", {get: function() {
                            return this.childNodes.map((function(e) {
                                return e.nodeType === 1
                            }))
                        }});
                    Object.defineProperty(e, "childElementCount", {get: function() {
                            return e.children.length
                        }});
                    Object.defineProperty(e, "childNodes", {get: function() {
                            var e = t.call(this); // error There is no ’call‘ method in undefined 
                            if ((p.$flags$ & 1) === 0 && He(this).$flags$ & 2) {
                                var n = new r;
                                for (var a = 0; a < e.length; a++) {
                                    var i = e[a]["s-nr"];
                                    if (i) {
                                        n.push(i)
                                    }
                                }
                                return n
                            }
                            return r.from(e)
                        }})
                }
```
The element objects in chrome39 do not require proxy methods (children, childElementCount, childNodes), which are native existing methods

Now my solution is to block access to the current judgment
```js
const fs = require('fs-extra');
const glob = require("glob");
const path = require('path');
const hasIfstatemenReg = /\('onbeforeload' in currentScript\)\) \{/;
const firstStrictStrReg = /^[\n|'][']?use strict';\n?/

// fs.readFileSync('/package.json', 'utf-8')

const fixStrict = function (es5Path) {
  const source = fs.readFileSync(es5Path, 'utf-8')
  // const newSource = source.replace(`if (!currentScript || !currentScript.hasAttribute('nomodule') || !('onbeforeload' in currentScript)) {`, '').replace(/\}\n\}\)\.call\(window\);/, `}).call(window);`);
  if (hasIfstatemenReg.test(source)) {
    const newSource = source.replace(firstStrictStrReg, '').replace(hasIfstatemenReg, `('onbeforeload' in currentScript)) {\n'use strict';`);
    fs.removeSync(es5Path)
    fs.outputFileSync(es5Path, newSource)
  }
}

const fixChildNodes = function (puiDir) {
  const fileList = glob.sync(path.join(puiDir, 'index-*.system.js'))
  const outPutPath = fileList[0]
  if (outPutPath) {
    const source = fs.readFileSync(outPutPath, 'utf-8')
    const newSource = source.replace('n.$flags$&8', 0) // TODO: FIX e.__lookupGetter__("childNodes") is undefined
    fs.removeSync(outPutPath)
    fs.outputFileSync(outPutPath, newSource)
  }
}

module.exports = {
  fixStrict,
  fixChildNodes
}
```
![Jietu20201201-093832](https://user-images.githubusercontent.com/15979948/100686658-bf840a00-33b9-11eb-87e8-2b65e43f3441.jpg)
Fix these two problems and you're ready to run chrome39 and 89.0.4335.0 (official version) canary (x86_64)
![image](https://user-images.githubusercontent.com/15979948/100686860-27d2eb80-33ba-11eb-84b4-2ece55de4dd6.png)

**Comment by chenyulun** [comment]
I now have `slotChildNodesFix:false` in my configuration,
I think this fix should determine whether the browser has native methods to determine whether or not it is fixed

**Comment by chenyulun** [comment]
fix #2761

**Comment by chenyulun** [comment]
> `` chrome39``index-3187e9a7.system.js ``
> 
> ```js
> if (n.$flags$&8) { // if  n.$flags === 9
>                     var t = e.__lookupGetter__("childNodes"); // t = undefined
>                     Object.defineProperty(e, "children", {get: function() {
>                             return this.childNodes.map((function(e) {
>                                 return e.nodeType === 1
>                             }))
>                         }});
>                     Object.defineProperty(e, "childElementCount", {get: function() {
>                             return e.children.length
>                         }});
>                     Object.defineProperty(e, "childNodes", {get: function() {
>                             var e = t.call(this); // error There is no ’call‘ method in undefined 
>                             if ((p.$flags$ & 1) === 0 && He(this).$flags$ & 2) {
>                                 var n = new r;
>                                 for (var a = 0; a < e.length; a++) {
>                                     var i = e[a]["s-nr"];
>                                     if (i) {
>                                         n.push(i)
>                                     }
>                                 }
>                                 return n
>                             }
>                             return r.from(e)
>                         }})
>                 }
> ```
> 
> ![Jietu20201201-093832](https://user-images.githubusercontent.com/15979948/100686658-bf840a00-33b9-11eb-87e8-2b65e43f3441.jpg)
> Fix these two problems and you're ready to run chrome39 and 89.0.4335.0 (official version) canary (x86_64)
> ![image](https://user-images.githubusercontent.com/15979948/100686860-27d2eb80-33ba-11eb-84b4-2ece55de4dd6.png)

@adamdbradley Please help to check the problem

**Comment by chenyulun** [comment]
#1280

**Comment by chenyulun** [comment]
chrome39 and chrome87 canary can cache childNodes using variables. The cache variables will change synchronously when the element changes
![chrome39fix](https://user-images.githubusercontent.com/15979948/101887889-6c3f6200-3bd8-11eb-894f-5337d1f0929f.jpg)

![Uploading chrome89childNodes.jpg…]()

**Comment by rwaskiewicz** [comment]
Hey there! 👋 

I'm sorry it took someone this long to get to this ticket.  The Stencil team is currently only supporting Stencil 2.0+. As of [Stencil 2.0, Chrome 39 is not supported. ](https://stenciljs.com/docs/browser-support).  I'm going to close this ticket, and apologize again for how long it went unacknowledged.
