### ISSUE TITLE
Fallbacked slots inside Light DOM are broken

### ISSUE THREAD

**Issue by dahfazz** [ionic-team/stencil#2760]
**Stencil version:**

```
 @stencil/core@2.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Fallbacked slots are not working anymore. (on any browser)

**Expected behavior:**

When using a slot in a Light DOM stencil component, the default value set inside component slot is not replaced by slot content given by component consumer.
Instead, the content is happened eight after the fb-slot but, fb-slot remains visible.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by claviska** [comment]
Just tested a few things and here's what I'm seeing.

### Example Component
```tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'my-component',
  shadow: false,
})
export class MyComponent {
  render() {
    return <slot>FALLBACK</slot>;
  }
}
```

### HTML
```html
  <my-component></my-component>

  <br><br>

  <my-component>SLOTTED</my-component>
```

### Expected

```
FALLBACK

SLOTTED
```

### Actual

```
FALLBACK

FALLBACKSLOTTED
```

This is with Stencil 2.3.0 and only occurs with `shadow: false`. Can you confirm this is what you're seeing as well as your Stencil version?

**Comment by claviska** [comment]
If this is indeed what you're seeing, then #2650 fixes it and will be available in the next release.

**Comment by dahfazz** [comment]
> If this is indeed what you're seeing, then #2650 fixes it and will be available in the next release.

This is exactly what I can see.
Good news for #2650 fix
Tks!
