### ISSUE TITLE
::slotted does not convert properly when needs to work as scoped.

### ISSUE THREAD

**Issue by romulocintra** [ionic-team/stencil#2768]
**Stencil version:**

```
 @stencil/core@latest // Testing from local build of master
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently when building an component that wraps another component you can style the slot when using modern browsers :

````html
<!-- index.html -->
<my-wrapper>
  <my-component slot="start">start1</my-component>
   <my-component slot="end">start1</my-component>
</my-wrapper>
````

````css
/* .my-wrapper.css */
::slotted([slot="start"]) {
  --button-font-size: 50px;
  --button-dynamic: purple;
}

::slotted([slot="end"]) {
  --button-font-size: 50px;
  --button-dynamic: pink;
}
````

That styles correctly components using shadow=true but only on Modern Browser when they are  polyfilled/scoped in ie11  styles aren't scoped nor given a fallback behaviour giving a not styled inner component `my-component`.

**Expected behavior:**

Expect that scopes deal with css similar way to give same look & feel.

**Steps to reproduce:**

Here repository that reproduces this https://github.com/romulocintra/error-slotted-ie11/blob/master/src/components/my-wrapper/my-wrapper.scss#L14

Keep attention if you add any dummy `  font-size: var(--button-color);` inside your slotted css that will correctly show in modern and old browsers.

**Related code:**
https://github.com/romulocintra/error-slotted-ie11/blob/master/src/components/my-wrapper/my-wrapper.scss#L1
**Other information:**

I was looking in how the scoped css is applied on templates https://github.com/ionic-team/stencil/blob/master/src/client/polyfills/css-shim/template.ts and how they detect var() cause looks like having a trigger to this generates compatible css for both generation of browsers

**Comment by romulocintra** [comment]
@adamdbradley  if you can guide on this one will be appreciated

**Comment by claviska** [comment]
To clarify, is this only happening with `shadow: true` in unsupportive browsers? If so, it sounds like this may be a bug in the polyfill — or possibly something it just doesn't support.

**Comment by romulocintra** [comment]
Yes, only happens with shadow true
