### ISSUE TITLE
Some component's types are not output if `components.d.ts` is not present in src directory

### ISSUE THREAD

**Issue by WickyNilliams** [ionic-team/stencil#2769]
**Stencil version:**

```
@stencil/core@2.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If there is no `src/components.d.ts` file present, and one component (A) references another's type (B)...

On first build, the types _are not_ generated for (A) in the output directory `dist/types/components`. If (A) exports any types, this can also result in broken imports in `dist/types/components.d.ts`. No error is reported during build.

On second build (where there is now a `src/components.d.ts` present as a result of the first build), the types _are_ generated for (A) in the output directory `dist/types/components`.

I do not like committing auto-generated files to source control, as they result in needless churn, hence why i do not have `src/components.d.ts` (this was a fresh clone of my repo).

**Expected behavior:**
Ideally it should Just Work(tm), and not rely on committing auto-generated files to source control. On both the first (broken) build and the second (successful) build, the `src/components.d.ts` file is exactly the same, so it may be a timing/ordering issue?

An alternative would simply be to raise an error in this case. 

**Steps to reproduce:**
1. create new stencil project with `npm init stencil`
2. `rm src/components.d.ts`
3. add the components from the Related code section below
4. `npm run build`
5. open `dist/types/components.d.ts` and see a broken import
6. `ls dist/types/components/` and notice there are no types for `my-other-component`

**Related code:**

```tsx
// src/components/my-component/my-component.tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'my-component',
  shadow: true,
})
export class MyComponent {
  render() {
    return <div>Hello, My Component</div>;
  }
}
```

```tsx
// src/components/my-other-component/my-other-component.tsx
import { Component, h, ComponentInterface, State, Prop } from '@stencil/core';

// this is just here to create a broken import in dist/types/components.d.ts
export type Test = { foo: string; bar: string };

@Component({
  tag: 'my-other-component',
  shadow: true,
})
export class MyOtherComponent implements ComponentInterface {
  // this reference to `HTMLMyComponentElement` breaks things.
  // if the type is `any`, the build is correct first time
  @State() children: HTMLMyComponentElement[];

  @Prop() test: Test;

  render() {
    return (
      <div>
        <div>Hello, My Other Component</div>
        <slot></slot>
      </div>
    );
  }
}

```

**Other information:**

n/a

**Comment by MBlanquett** [comment]
We "fixed" this by always running "npm run build" two times in a row.

**Comment by mendeza** [comment]
> We "fixed" this by always running "npm run build" two times in a row.

I seem to have "fixed" this by versioning `components.d.ts`...which as mentioned causes real friction on an active project.

Many thanks to @WickyNilliams for the diagnosis and filing the issue!

**Comment by mendeza** [comment]
"Fixed" this again in a different way, and un-versioned `components.d.ts`.

I learned by serendipitous observation that the common side effect of _any_(?) type of stencil build is to regenerate `components.d.ts`.
 
So this output config is used to trick Stencil into regenerating the file, and asynchronously checking for the file's existence. No docs are output, merely the function is run. This runs first (obviously), then the full `npm run build`.

This dropped the duration of the relevant portion of the CI pipeline from 3.5 minutes to just under 17 seconds, in my particular case.

```
import { Config } from '@stencil/core';
const fs = require('fs');
async function regenMessage() {
  fs.access('./src/components.d.ts', (err) => {
      if (err) {
          console.log("Component types NOT regenerated!");
      } else {
          console.log("Component types regenerated?");
      }
  });
}
export const config: Config = {
  outputTargets: [
    {
      type: 'docs-custom',
      generator: regenMessage
    }
  ]
};
```
(Immediately after: `ls -la src/components.d.ts` shows proof)

Hope it helps!

**Comment by claviska** [comment]
May I ask what the aversion to committing `components.d.ts` is?

**Comment by WickyNilliams** [comment]
Personally I try to avoid committing any auto generated file. They create noise and needless churn in git history, add extra complexity to merges/rebases. Basically the same reasons you wouldn't commit your dist/output directory
