### ISSUE TITLE
question: how does @Component.host work ?

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#277]
Just quick question:

what doest `host` do within `@Component({})` ?

I skimmed through ionic/core and you're using only `host: { theme: 'alert' }` which just adds `alert` class to the element, which is not very intuitive indeed 

thanks !

**Comment by adamdbradley** [comment]
`host` is referring to the host element. So if you need to add a css class or attribute you can use this option in the decorator. We're mainly using this for Ionic so we can dynamically change the theme. Ionic has a config that figures out which mode/theme to use for each component, and then it applied different css classes depending on that info. We'll get some docs written up on it, thanks!

**Comment by adamdbradley** [comment]
Moved: https://github.com/ionic-team/stencil-site/issues/82
