### ISSUE TITLE
jest.mock does not get hoisted to top of imports

### ISSUE THREAD

**Issue by r3dDoX** [ionic-team/stencil#2778]
**Stencil version:**
```
@stencil/core@2.3.0
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
Currently when we want to mock modules with `jest.mock` we do have to add this call above all imports. This can be problematic when IDEs add automatic imports and organize/reorder them. In this case we need to manually add the `jest.mock` call to the top again.

**Expected behavior:**
In other environments the plugins "babel-jest" or "ts-jest" get used which ensure that `jest.mock` calls get hoisted above the imports.

**Steps to reproduce:**
Use `jest.mock` to mock a module and try it when adding it after the import statement of that module.

**Comment by rmirro** [comment]
I was able to get hoisting working today by adding this `transform` to the `testing` property of `stencil.config.ts`:
```js
import { Config } from '@stencil/core';
import { pathsToModuleNameMapper } from 'ts-jest/utils';
import { compilerOptions } from '../../tsconfig.base.json';

export const config: Config = {
  namespace: 'components',
  taskQueue: 'async',
  testing: {
    moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
      prefix: `${process.cwd()}/`,
    }),
    transform: {
      '^.+\\.[tj]s$': 'ts-jest',
    },
  },
};
```
`ts-jest` is required as a dependency and `spec` files are assumed to use a `ts` extension.

I left `pathsToModuleNameMapper` above as well because tsconfig `paths` didn't seem to be working with `ts-jest` and I didn't want to have to hardcode/duplicate them in `stencil.config.ts`.

**Comment by christian-bromann** [comment]
@r3dDoX are you still experiencing any issues? Sorry this hasn't been picked up by the team until now. Is there anything I can do to help?

**Comment by r3dDoX** [comment]
Hey @christian-bromann 
Sorry, by now I am not working with stencil anymore.

**Comment by christian-bromann** [comment]
Thanks for confirming @r3dDoX. I will go ahead and close this issue. If anyone is still experiencing this problem I am happy to re-open.
