### ISSUE TITLE
unable to import h directly

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#278]
**Stencil version:**

```
@stencil/core@0.0.7-0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

`h` is not directly exposed from `@stencil/core`

**Expected behavior:**
There might be situations when user wan't dynamically render DOM node types. Yes he can do if/else but  that will lead to not DRY code if children are more complicated.
Anyway it should be default behaviour to be able to import `h` because JSX is used anyway

**Steps to reproduce:**

**Related code:**

Following doesn't work

```tsx
import { Component, Prop, h } from '@stencil/core'

@Component({})
class Foo {

  @Prop() type: 'a | div'
  render(){
    return h(this.type, null, h('slot'))
  }
}
```

![image](https://user-images.githubusercontent.com/1223799/32396871-681bd45c-c0e7-11e7-83db-0cb7200ddc7c.png)

**Comment by manucorporat** [comment]
You can still do it:
```
  render() {
    const TagType = this.type;
    return <TagType><slot></slot></TagType>;
  }
```

**Comment by manucorporat** [comment]
Take `ionic-core/button` as an example: https://github.com/ionic-team/ionic/blob/core/packages/core/src/components/button/button.tsx#L204-L221

**Comment by Hotell** [comment]
well, still it should be possible to import `h`, it's there anyway so. With that approach btw, you won't be able to escape TS errors so no go :)

![image](https://user-images.githubusercontent.com/1223799/32408721-e466a15c-c19d-11e7-9645-3269537e5c15.png)

**Comment by manucorporat** [comment]
@Hotell ah! that's very interesting... it is fixed if the variable is capitalized... maybe that's part of the JSX spec... not sure

const Tag = 'a'; works just fine, without TS errors. mmmm

Regarding important h, @adamdbradley probably has an expert opinion here.

I know a mayor goal for us is to keep the API as small as possible, so exporting more stuff always brings some discussion (healthy discussion :) )

**Comment by Hotell** [comment]
> const Tag = 'a'; works just fine, without TS errors. mmmm

yup you're correct ! good catch , thanks

> Regarding important h

So during my flight to angular connect today, I skimmed through stencils interfaces, and I found that `h` is available as global ( oh no globals! hit that panic button now :D )

![image](https://user-images.githubusercontent.com/1223799/32453238-99d5614c-c313-11e7-88c0-a72e78b2bb9d.png)

I understand why is it this way ( so consumers don't have to import `h` all the time, but feels like bad black magic, for advance users, used to work with VDom for sure

**Comment by adamdbradley** [comment]
I think we'll keep it a global for now. Technically it's there and available, but I'd like to not expose more than we need to to keep our API footprint down. Thanks
