### ISSUE TITLE
Readme.md not generated automatically

### ISSUE THREAD

**Issue by bloureiro7** [ionic-team/stencil#2780]
**Stencil version:**
`-- (empty)
```
 @stencil/core@2.3.0
```

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
when the following command is used 
> stencil build --docs-readme

If I have a ionic-pwa type project, the readme.md files are automatically created for each component, which is correct
If I have a components type project, the readme.md files are **NOT** automatically generated for each component

**Expected behavior:**
Generate automatically the readme.md files for each component

**Steps to reproduce:**

1. npm init stencil    
2. Choose the option components 
3. complete the setup 
4. stencil build --docs-readme

**Comment by rwaskiewicz** [comment]
👋 hello there!

I was unable to reproduce this with the latest version of the create-stencil CLI. Specifically I performed the following steps:
```

1. Generate a project using the component starter, called 'readme'. Then commit the output of running `build` to git.
```bash
npm init stencil@latest component readme
cd readme
npm i
npm run build
git init
git add .
git commit -m 'default'
```

2. update `package.json`:
```diff
diff --git a/package.json b/package.json
index d94d2b4..155cfce 100644
--- a/package.json
+++ b/package.json
@@ -19,7 +19,7 @@
     "loader/"
   ],
   "scripts": {
-    "build": "stencil build --docs",
+    "build": "stencil build --docs-readme",
     "start": "stencil build --dev --watch --serve",
     "test": "stencil test --spec --e2e",
     "test.watch": "stencil test --spec --e2e --watchAll",
```

3. Rerun the build, where I don't see any changes made:
```bash
npm run build
git diff
```


Am I understanding this correctly? Or perhaps this has been resolved?
