### ISSUE TITLE
stencil 2.4.0-1 npm start failed!

### ISSUE THREAD

**Issue by anlexN** [ionic-team/stencil#2781]
**Stencil version:**

```
 @stencil/core@2.4.0-1
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

![image](https://user-images.githubusercontent.com/8686739/103291452-b8870080-4a26-11eb-95f5-d39a34c57abc.png)

**Expected behavior:**

i need stencil is running. i am reviewing how to test component in your stencil source code.

**Comment by claviska** [comment]
Can you provide some steps and/or a reduced test case so we can reproduce what you're seeing?

**Comment by anlexN** [comment]
![image](https://user-images.githubusercontent.com/8686739/103391314-d30ac800-4b53-11eb-81aa-b164d39218b2.png)
![image](https://user-images.githubusercontent.com/8686739/103392051-f5eaab80-4b56-11eb-9e42-b4c5af094dcd.png)
![image](https://user-images.githubusercontent.com/8686739/103392069-0e5ac600-4b57-11eb-92c0-11f6b8e085ea.png)
![image](https://user-images.githubusercontent.com/8686739/103392093-27637700-4b57-11eb-8d04-3b5590477d22.png)
[2020-12-31T02_53_26_603Z-debug.log](https://github.com/ionic-team/stencil/files/5756341/2020-12-31T02_53_26_603Z-debug.log)
i am in windows 10, node 15.2.1, npm 7.0.8. i use powershell not git bash, it is also this problem. help me, please.

**Comment by mmakrzem** [comment]
does it work if you downgrade to npm v6.x ?

I just noticed a bunch of things don't work properly if I use npm v7.x

**Comment by anlexN** [comment]
i don't do it. i wait stencil to fix.

**Comment by rwaskiewicz** [comment]
Hey all 👋 

This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
