### ISSUE TITLE
Cannot find module '../stencil-public-runtime' or its corresponding type declarations.

### ISSUE THREAD

**Issue by anlexN** [ionic-team/stencil#2782]
**Stencil version:**

```
 @stencil/core@2.4.0-1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

![image](https://user-images.githubusercontent.com/8686739/103292927-d43fd600-4a29-11eb-9b5e-b75278778fa4.png)

**Expected behavior:**

i need vscode no errors, please.

**Comment by rwaskiewicz** [comment]
Hey there @anlexN 

I'm unable to reproduce this locally with Stencil v2.15.1. If possible, can you please add a reproduction case? Thanks!

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a minimal code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
