### ISSUE TITLE
runJest: Error: Cannot find module 'yargs'

### ISSUE THREAD

**Issue by anlexN** [ionic-team/stencil#2785]
**Stencil version:**

```
 @stencil/core@<version> 2.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

![image](https://user-images.githubusercontent.com/8686739/103397374-14f73680-4b73-11eb-84fe-4b30d5adaf8c.png)

**Expected behavior:**
i make sure that i success npm install @stencil/core

`npm run test` need to be success

**Comment by lukeundtrug** [comment]
We're encountering the same problem in our app using 2.4.0. The interesting part is that the error only occurs when the tests run on our CI pipelines (after using `npm ci` to install). Locally everything works fine although I haven't installed `yargs` globally.

Adding `yargs` to the dependencies works of course but it would be really interesting to know what could cause such an error.

**Comment by jan-paulus** [comment]
Same as @lukeundtrug

**Comment by VladimirPittner** [comment]
Experiencing the same with 2.6.0. What is the status on this?

**Comment by jjmato** [comment]
the same with 2.12.0

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!

**Comment by snaptopixel** [comment]
@rwaskiewicz  I'm seeing this now too in cli with `@stencil/core@2.17.4` after clearing npm cache and re-creating package-lock.json. In core, testing/index.js there is `require("yargs")` but afaict `yargs` is not in core's package.json so I think this is intermittent, if yargs is there from some other package no problem, but if not, stencil blows up. Did any of the others here have a workaround? I'm going to try adding yargs as a direct dependency and see if that fixes things for now.

**Comment by rwaskiewicz** [comment]
@snaptopixel that sounds correct to me. I believe yargs is a transitive dependency of Stencil (and gets included by jest normally). I have a task on the books to resolve the transitive dependency issue, but had de-prioritized it since we couldn't find a way to reliably repro it (and I had wondered if it would be necessary once we rolled out Jest 28/29 support, which is going to require quite a few under the hood Stencil releases).

LMK if you can repro reliably, and we can re-open see what the effort to require yargs might look like.

**Comment by Zkrgu** [comment]
Depending on package-duplication, yargs might be installed nested. This occurs every time when `install-strategy` is set to anything else than `hoisted`.
