### ISSUE TITLE
Incorrect warning during e2e test

### ISSUE THREAD

**Issue by jpzwarte** [ionic-team/stencil#2793]
**Stencil version:**

```
 @stencil/core@2.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

There is a bug in stencil's e2e runner where it incorrectly detects that a property has changed during rendering; this is due to the property having the same name as a host attribute:

```typescript
@Prop({ mutable: true }) active: boolean;

render() {
  return <Host active={this.active ? true : undefined}>...</Host>;
}
```

The warning is `STENCIL: The state/prop "active" changed during rendering. This can potentially lead to infinite-loops and other bugs.`

The test is: 

```typescript
  it('should mark the second tab as active after clicking the second tab button', async () => {
    const button = await page.find('dna-tab-button:last-of-type'),
      tab = await page.find('dna-tab:last-of-type');

    expect(button.getAttribute('active')).toBeNull();
    expect(tab.getAttribute('active')).toBeNull();

    // Warnings are triggered here
    await button.click();

    expect(button.getAttribute('active')).not.toBeNull();
    expect(tab.getAttribute('active')).not.toBeNull();
  });
```

**Expected behavior:**

No warnings.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by claviska** [comment]
Just tried replicating this with a similar tab component with `active` being set on the host element as shown above. I wasn't able to reproduce the warning you're showing, though.

Can you post a reduced example so I can try to replicate this...maybe based on the starter app?

Side note: I needed to add `await page.waitForChanges()` after `await button.click()` otherwise I was seeing an error.
