### ISSUE TITLE
cache busting problems

### ISSUE THREAD

**Issue by Scan0815** [ionic-team/stencil#2796]
I have a problem with cache busting in stencil 2.3.0. Maybe someone can help me how he implemented it. Most of the js files are hashed, but unfortunately not in the index.html. /build/app.js and /build/app.esm.js. with cdn and local caching it is difficult to get the current page on some devices. Does anyone have a solution/trick for this? thanks.

**Comment by claviska** [comment]
Have you tried asking [on the forum](https://forum.ionicframework.com/c/stencil/21) or in the [Slack community](https://stencil-worldwide.herokuapp.com/)? You're more apt to get help there, especially from the folks on Slack.

**Comment by Scan0815** [comment]
@claviska i will check on slack, thx!
