### ISSUE TITLE
ES5 Build error caused by checkIfURLIsSupported() in polyfills

### ISSUE THREAD

**Issue by nj-coder** [ionic-team/stencil#2797]
While building my react which requires es5 varitant, using `buildEs5: 'prod'`, the build using [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) breaks with the below error

`In strict mode code, functions can only be declared at top level or immediately within another function.`

**Stencil version:**

```
 @stencil/core@v2.3.0
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
The es5 variation of stencil core build references the polyfill file which causes a build system for es5 to break dues to strict mode configurations

**Expected behavior:**
The app in which the stencil is integrated should build fine after including stencil.

**Other information:**
After some digging around, this is caused by checkIfURLIsSupported() in the [polyfills/index.js](https://github.com/ionic-team/stencil/blob/master/src/client/polyfills/index.js) file. This can be fixed by converting checkIfURLIsSupported as a function expression. I am happy to put a PR if this can be a fix that solves the issue without hurting any other setup.

**Comment by claviska** [comment]
That sounds like a good fix. Looking forward to the PR 😄

**Comment by nj-coder** [comment]
Thanks, its up [here](https://github.com/ionic-team/stencil/pull/2799) @claviska

**Comment by claviska** [comment]
Thanks, fixed in #2799.
