### ISSUE TITLE
compiler doesn't create ambient types properly from string literals

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#280]
**Stencil version:**

```
 @stencil/core@0.0.7-0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
`@Prop() size: 'lg' | 'sm' | string`  will end up being `size?: any,` within **components.d.ts**
although simple types resolve correctly: `@Prop() size: string` -> `size?: string`

![stencil-ambient-type-bug](https://user-images.githubusercontent.com/1223799/32408943-e51f8f10-c1a1-11e7-8a88-c9709e882d7b.gif)

**Expected behavior:**

create ambient types with appropriate `@Prop` type annotations

**Comment by jthoms1** [comment]
This is a totally valid scenario and something we will be fixing.

**Comment by Hotell** [comment]
🍻
