### ISSUE TITLE
Custom Events with uppercase characters no longer work in Vue

### ISSUE THREAD

**Issue by alexanderbenavides** [ionic-team/stencil#2804]
I created an input in stenciljs  and I have register a valueChanged event in there. Then I want to use the input in vue with the  v-model directive. But the the event @valueChanged  does not work in vue 3, but it does in vue 2. 

Vue 3:

![image](https://user-images.githubusercontent.com/42325199/104984791-6dd12680-59dd-11eb-8643-c992f1ec803a.png)

vue 2:
![image](https://user-images.githubusercontent.com/42325199/104984873-a2dd7900-59dd-11eb-8102-2a193de230b0.png)

My code in vue2 and vue3 are the same:

```html
<template>
    <cb-input label="Name: " @valueChanged="onValueChanged"></cb-input>
</template>

<script>

export default {
  name: 'App',
  components: {},
  methods: {
    onValueChanged(evt) {
      console.log(evt);
    }
  }
}
</script>
```

**Comment by jackchoumine** [comment]
> I created an input in stenciljs and I have register a valueChanged event in there. Then I want to use the input in vue with the v-model directive. But the the event @valueChanged does not work in vue 3, but it does in vue 2.
> 
> Vue 3:
> 
> ![image](https://user-images.githubusercontent.com/42325199/104984791-6dd12680-59dd-11eb-8643-c992f1ec803a.png)
> 
> vue 2: ![image](https://user-images.githubusercontent.com/42325199/104984873-a2dd7900-59dd-11eb-8102-2a193de230b0.png)
> 
> My code in vue2 and vue3 are the same:
> 
> ```
> <template>
>     <cb-input label="Name: " @valueChanged="onValueChanged"></cb-input>
> </template>
> 
> <script>
> 
> export default {
>   name: 'App',
>   components: {},
>   methods: {
>     onValueChanged(evt) {
>       console.log(evt);
>     }
>   }
> }
> </script>
> ```

same issue: [stencil components events not working in Vue 3](https://github.com/ionic-team/stencil/issues/3022)

**Comment by dmartinjs** [comment]
a small "fix" when waiting a fix from Vue 3
```
// Apply polyfills and declare components
applyPolyfills().then(() => {
  defineCustomElements(window, {
    ael: (el: any, eventName: string, cb: any, opts: any) => el.addEventListener(eventName.toLowerCase(), cb, opts),
    rel: (el: any, eventName: string, cb: any, opts: any) => el.removeEventListener(eventName.toLowerCase(), cb, opts),
    ce: (eventName: string, opts: any) => new CustomEvent(eventName.toLowerCase(), opts)
  } as any);
});
```
this will lowercase all your events,
it will work for directives to (@Listen and @Event ) but will not modify manual `addEventListener` be aware of that.

Since this problem is for all web components and not only Stencil, I don't think the Stencil team can do something about it.

this issue is referenced in the Vue repo (vuejs/vue-next#2460).

**Comment by ALexander4295502** [comment]
> a small "fix" when waiting a fix from Vue 3
> 
> ```
> // Apply polyfills and declare components
> applyPolyfills().then(() => {
>   defineCustomElements(window, {
>     ael: (el: any, eventName: string, cb: any, opts: any) => el.addEventListener(eventName.toLowerCase(), cb, opts),
>     rel: (el: any, eventName: string, cb: any, opts: any) => el.removeEventListener(eventName.toLowerCase(), cb, opts),
>     ce: (eventName: string, opts: any) => new CustomEvent(eventName.toLowerCase(), opts)
>   } as any);
> });
> ```
> 
> this will lowercase all your events, it will work for directives (@listen and @event ) but will not modify manual `addEventListener` be aware of that.
> 
> Since this problem is for all web components and not only Stencil, I don't think the Stencil team can do something about it.
> 
> this issue is referenced in the Vue repo ([vuejs/core#2460](https://github.com/vuejs/core/issues/2460)).

I am using `@stencil/core@2.14.0` seems like there is no property `ce` defined in `CustomElementsDefineOptions` in this version, I was wondering if there is any workaround for it?

**Comment by bjankord** [comment]
Just ran into this issue. Going to be updating all of our custom events from camelCase to kebab-case so they work with Vue 3. I think it would be good to update Stencil's event docs to use kebab-case as well:
https://stenciljs.com/docs/events

**Comment by jeco123** [comment]
Have you tested the v-model feature with this "hack" ? on my side, nothing happens with the v model directive

**Comment by tanner-reits** [comment]
Hey all 👋 

Based on the conversation, it sounds like this evolved into more of a support request/topic as it falls outside Stencil's scope. As such, I'm going to get this labeled and closed out appropriately. Hopefully everyone was able to work around the issue within Vue!
