### ISSUE TITLE
Reflect Properties Values to Attributes not working with Booleans

### ISSUE THREAD

**Issue by alxhrtng** [ionic-team/stencil#2806]
**Stencil version:**

```
 @stencil/core@2.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Reflect Properties Values to Attributes do not work if the property is type "boolean". The property in the DOM does not get updated and is not in sync anymore.

**Expected behavior:**

Boolean property is in sync with the DOM

**Steps to reproduce:**

**Related code:**

```tsx
@Prop({ mutable: true, reflect: true}) prop: boolean;
this.prop = true; // is not reflected to the DOM
```

**Comment by rwaskiewicz** [comment]
Hey @alxhrtng 👋 

I apologize that it took so long for a member of the Stencil team to respond to this issue.

I took a look using Stencil v2.22.1 and believe that this is working correctly. For the component:
```tsx
import { Component, Prop, h } from '@stencil/core';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true,
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop({mutable: true, reflect: true}) first: boolean = true;

  public componentDidLoad() {
    setInterval(() => { this.first = !this.first; }, 500)
  }

  render() {
    return <div>Hello, World! I'm {this.first.toString()}</div>;
  }
}
```
I get the following behavior, where the boolean property is in sync with the DOM
https://user-images.githubusercontent.com/1930213/213701920-22da998e-afac-4652-be41-4543cfc705e4.mov

As such, I'm going to close this ticket out. I apologize again that it sat for so long. I appreciate you taking the time to put this together to help make Stencil better.

Should you or anyone else come upon this issue and believe this bug still exists, please feel free to open a new issue.
