### ISSUE TITLE
There is no option to turn off Polyfills

### ISSUE THREAD

**Issue by bvramesh219** [ionic-team/stencil#2812]
**Stencil version:**
 @stencil/core@2.1.0

**I'm submitting a:**
[ x] feature request

**Current behavior:**
Polyfills are generating even though those are not required. I am developing web application for Electron Container which uses latest chrome browser engine, which supports all the latest HTML5, ES6 features. However Stencil is still generating Polyfills. I do not need polyfiils if I am targeting browser which is complaint to all latest standards. I have some restrictions on foot print. How can I prevent generation of polyfills and other unwanted build artifacts.

**Expected behavior:**
Stencil should not generate poly fills and other unwanted artifacts, if targeted browser is standard complaint.

**Steps to reproduce:**
Create a project with stencil with default options and just do build.  Observe in dist/esm folder. you will see polyfills file

**Comment by csisy** [comment]
Just found this issue, 1.5 years after it has been opened. Unfortunately it's still not working as expected. Explicitly turning off things, like `css vars shim` doesn't help.

**Comment by rwaskiewicz** [comment]
Closing in favor of https://github.com/ionic-team/stencil/issues/3786. Thanks!

**Comment by pixobe** [comment]
Is there a way to turn polyfills off? even after setting polyfills false in stenci.confg under dist, its still generating.
