### ISSUE TITLE
Output target collection does not transpile ts path config

### ISSUE THREAD

**Issue by patrickhaug** [ionic-team/stencil#2815]
```
 @stencil/core@2.0.4>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When setting paths in tsconfig:
`"paths": {
      "@utils/*": ["./app/utils/*"]
    }`
it gets transpiled to this in output target collection. 
`import("@utils/xxx"))`

Other output targets work fine.

**Expected behavior:**
It should resolve to the correct file path from ts config and not the alias.

**Comment by abdolian** [comment]
I have the same problem

**Comment by liamdebeasi** [comment]
We are running into the same issue. I have provided a GitHub repo: https://github.com/liamdebeasi/stencil-alias

Steps to reproduce:

1. Clone repo.
2. Run `npm install`.
3. Run `npm run start`. Observe that there are no errors.
4. Quit the dev server.
5. Run `npm run build`.
6. Open `dist/collection/components/my-component/my-component.js`. Observe that the `format` is still being imported from `@utils/utils`;
7. Open `dist/components/my-component.js`. Observe that the `format` util is correctly inlined.

**Comment by rwaskiewicz** [comment]
Thanks all! I spoke with @liamdebeasi about this issue today and confirmed its an issue. I've labeled it so that it gets ingested into our backlog
