### ISSUE TITLE
Stencil app is disabled message is too persistent

### ISSUE THREAD

**Issue by metalass** [ionic-team/stencil#2823]
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When browser is not supported stencil rewrites the whole body with error message.

**Expected behavior:**
Such behavior could be ok when the whole page (application) is built with Stencil. I build one component of the page. Even though it's a critical component I would like Stencil not to overwrite the body and maybe put my own message.

I would like to have a config parameter which will replace this document body rewriting into some custom event triggering, so I can handle it respectively.

**Steps to reproduce:**
Run in IE11 without es5 build

**Other information:**
Such behavior is hardcoded here: https://github.com/ionic-team/stencil/blob/cfd5d39bad4ce2cab431595ae8c8f11d1fabb192/src/compiler/app-core/app-es5-disabled.ts#L126

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize that it took so long for a member of the team to acknowledge this ticket. With Stencil v4, we've officially dropped support for IE 11/older versions of Edge. As a result, I'm going to close this ticket out as "won't fix". Thanks for raising this, and again I apologize that it took so long for someone on the team to respond to this issue.
