### ISSUE TITLE
compiler errors out on normal Typescript code - using ambient definitions

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#283]
**Stencil version:**

```
 @stencil/core@0.0.7-0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

when we wanna create app/component wide ambient types so we don't have to import them all the time ,within a `globals.d.ts`, stencil will error out and compilation will fail.

event if we explicitly set `global: 'src/globals.d.ts',` within `stencil.config.js` the outcome is the same

![image](https://user-images.githubusercontent.com/1223799/32409405-97199ee6-c1ab-11e7-981d-ff5b3068fe89.png)

**Expected behavior:**

no compilation errors. When you run `tsc` explicitly there are no compilation errors

![image](https://user-images.githubusercontent.com/1223799/32409415-b798d1a0-c1ab-11e7-9041-e03bcabb9a5c.png)

**Steps to reproduce:**

**Related code:**

tsconfig.json
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "strict": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "lib": ["dom", "es2015"],
    "outDir": "ts-out",
    "moduleResolution": "node",
    "module": "es2015",
    "target": "es2015",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "react",
    "jsxFactory": "h",
    "sourceMap": true,
    "pretty": true
  },
  "include": [
    "src"
  ],
  "exclude": ["node_modules"]
}

```

**Comment by jthoms1** [comment]
This issue should be fixed with commit 1246d955f1e5eab4faee114f120ac6538fb34bb3.
