### ISSUE TITLE
Cannot read property 'original' of undefined on build

### ISSUE THREAD

**Issue by joao-m-santos** [ionic-team/stencil#2831]
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When building (`stencil build --dev --watch`) a Stencil component that has other, Polymer 2-built Web Components in its JSX template, I get the following error:
```
 TypeError: Cannot read property 'original' of undefined at
           path\to\project\node_modules\@stencil\core\compiler\stencil.js:57208:33 at
           Array.map (<anonymous>) at generatePropTypes
           (path\to\project\node_modules\@stencil\core\compiler\stencil.js:57206:27) at
           generateComponentTypes
           (path\to\project\node_modules\@stencil\core\compiler\stencil.js:57236:26) at
           path\to\project\node_modules\@stencil\core\compiler\stencil.js:57382:12 at
           Array.map (<anonymous>) at generateComponentTypesFile
           (path\to\project\node_modules\@stencil\core\compiler\stencil.js:57380:30) at
           generateAppTypes
           (path\to\project\node_modules\@stencil\core\compiler\stencil.js:57354:35) at
           runTsProgram
           (path\to\project\node_modules\@stencil\core\compiler\stencil.js:59950:33) at
           build (path\to\project\node_modules\@stencil\core\compiler\stencil.js:60258:39)
```

**Expected behavior:**
It would compile with no errors.

**Other information:**
No errors on the component code.

**Comment by joao-m-santos** [comment]
It appears this is related to type imports. I am importing TS interfaces from the files that contain the Polymer element class definitions. Am I unable to import types/interfaces from files other than Stencil Components?

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I'm sorry this took so long to get to. If you're willing and able, could you please create a minimal reproduction case with the latest version of Stencil for the team to take a look at for triage? Thanks!
