### ISSUE TITLE
Multiple Issues with HostRef When Using a StencilJS Component Library in Rollup

### ISSUE THREAD

**Issue by milky2028** [ionic-team/stencil#2835]
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm trying to use a Stencil component library in an app that is bundled with Rollup, but I keep having issue with `hostRef`.

In my reproduction library, I see `app.js:826 TypeError: Cannot read property '$instanceValues$' of undefined`, but in the library I'm using with work, I see `TypeError: Cannot rad property $hostElement$ of undefined` (unfortunately, private code). The error in the reproduction repo is not quite the same, but I think this illustrates that there's some kind of issue with `hostRef`.

I also saw this about a year ago when I was trying to setup something similar with Rollup, so I don't think this is new behavior.

**Expected behavior:**
Component should load as normal.

**Steps to reproduce:**

1. [Clone this repo](https://github.com/milky2028/rollup-stencil-preact).
2. `npm install && npm run build`
3. Open your browser.

**Other information:**

TypeError: hostRef is undefined
    setValue core-78af3966.js:1250
    set core-78af3966.js:1307
    Table picasa-alert_27.entry.js:4398
    initializeComponent core-78af3966.js:1398
    step core-78af3966.js:45
    verb core-78af3966.js:26
    fulfilled core-78af3966.js:17
    promise callback*step core-78af3966.js:19
    __awaiter core-78af3966.js:20
    __awaiter core-78af3966.js:16
    initializeComponent core-78af3966.js:1358
    connectedCallback core-78af3966.js:1495
    promise callback*nextTick core-78af3966.js:197
    connectedCallback core-78af3966.js:1495
    connectedCallback core-78af3966.js:1588
    jmp core-78af3966.js:72
    connectedCallback core-78af3966.js:1588
    x bootstrap-b33ce811.js:148
    m bootstrap-b33ce811.js:127
    $ bootstrap-b33ce811.js:218
    m bootstrap-b33ce811.js:127
    $ bootstrap-b33ce811.js:218
    g bootstrap-b33ce811.js:101
    g bootstrap-b33ce811.js:99
    k bootstrap-b33ce811.js:93
    setState bootstrap-b33ce811.js:360
    setState bootstrap-b33ce811.js:427
    __ Preact
    CaseSearch CaseSearch.tsx:79
    CaseSearch CaseSearch.tsx:72
    Preact 6
    $ bootstrap-b33ce811.js:221
core-78af3966.js:106:49

TypeError: getHostRef(...) is undefined
    getValue http://localhost:10001/app.js:541
    get http://localhost:10001/app.js:575
    getText http://localhost:10001/my-component.entry.js:14
    render http://localhost:10001/my-component.entry.js:17
    callRender http://localhost:10001/app.js:453
    updateComponent http://localhost:10001/app.js:427
    dispatchHooks http://localhost:10001/app.js:414
    then http://localhost:10001/app.js:523
    dispatchHooks http://localhost:10001/app.js:414
    dispatch http://localhost:10001/app.js:406
    consume http://localhost:10001/app.js:865
    flush http://localhost:10001/app.js:880
 
<my-component class="hydrated" chidlren="from my component" first="Tyler">
app.js:826:52

**Comment by christian-bromann** [comment]
Hi @milky2028  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
