### ISSUE TITLE
Using LocalStorage breaks npm run build

### ISSUE THREAD

**Issue by foreggs** [ionic-team/stencil#284]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

using e.g. `localStorage.getItem("token")` causes a runtime error during the build process.

**Expected behavior:**

Compile without errors.

**Steps to reproduce:**

In the stencil starter, add 
```tsx
componentDidLoad() {
  const token = localStorage.getItem("token")
}
```
Then run `npm run build`

**Other information:**
Using Windows 10.

**Comment by foreggs** [comment]
Removing the `--prerender` flag fixes the issue, but obviously, prerendering is an awesome feature. Valve please fix.

**Comment by adamdbradley** [comment]
I'm not able to reproduce the error, which version of stencil are you using?

**Comment by foreggs** [comment]
v0.0.7.1

**Comment by adamdbradley** [comment]
What is the error message you're receiving?

**Comment by jgw96** [comment]
Hey @foreggs , thanks for using Stencil! localStorage is not available on the "server side" (jsDom with prerendering) but Stencil provides a nice utility to work with this. You can use something like  ```  
@Prop({ context: 'isServer'}) private isServer: boolean;

  componentDidLoad() {
    if (!this.isServer) {
      localStorage.getItem("token");
    }
  } ``` to tell the Stencil compiler to not try to run certain code on the server side (or local jsDom in prerendering). This gets rid of the error during compile.
