### ISSUE TITLE
Recreate the Collection Package CSS in to node_modules

### ISSUE THREAD

**Issue by chenyulun** [ionic-team/stencil#2852]
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

 monorepo project
 after build, create node_modules in the `package` folder? 
@pa/pui-icons build in `node_modules/@pa/pui-icons/dist/collection/collection-manifest.json`
```js
{
  "entries": [
    "./components/icon/icon.js"
  ],
  "compiler": {
    "name": "@stencil/core",
    "version": "1.17.4",
    "typescriptVersion": "3.9.7"
  },
  "collections": [],
  "bundles": []
}
```
![image](https://user-images.githubusercontent.com/15979948/110882475-f5238200-831c-11eb-9115-bb2afc171b40.png)

copy collection package css in to package folder?

**Expected behavior:**

Do not create node_modules in the package folder
**Steps to reproduce:**

**Related code:**
`packages/core/src/index.ts`
```ts
import '@pa/pui-icons'; // build by @stencil/core@1.17.4 and typescriptVersion 3.9.7

export { Components, JSX } from './components';

```
Everything else is initialization Settings

**Other information:**

**Comment by splitinfinities** [comment]
Hey there! It seems like you're using an outdated version of Stencil in the icons package. If you could update that and add a reproduction repo, that could help us track down the root cause.

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
