### ISSUE TITLE
@Prop <prop_name> on <>is immutable on <stencil_router_component>

### ISSUE THREAD

**Issue by pranjalworm** [ionic-team/stencil#2853]
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Stencil throws many warnings:-
 - @Prop() "history" on <stencil-route> is immutable but was modified from within the component 
 - @Prop() "location" on <stencil-route> is immutable but was modified from within the component.
 - @Prop() "routeViewsUpdated" on <stencil-route> is immutable but was modified from within the component.
 - @Prop() "historyType" on <stencil-route> is immutable but was modified from within the component.

**Expected behavior:**
N/A

**Steps to reproduce:**
The issue is happening on stencil's starter app also. 
1. Follow the steps mentioned here: https://stenciljs.com/docs/getting-started and create an app.
2. Serve the app and open it in a browser.
3. You'll the see the above listed warnings.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by prats8m2** [comment]
I'm also facing this same exact issue.

**Comment by Perronef5** [comment]
I'm also facing the same issue. Additionally, some of my components are outputting this as well as soon as I updated to Stencil `v2.4.0`

**Comment by trazek** [comment]
I too am facing this issue

**Comment by rafael-leal-mccormack** [comment]
Can we add an option in the stenci.config or environment variable that will stop these warnings from showing? I would be willing to PR it myself worst case scenario

**Comment by rwaskiewicz** [comment]
Hey folks,

I apologize this has taken so long to get looked at. As of earlier this month, [we've moved the router to the Stencil Community group](https://ionicframework.com/blog/announcing-the-stencil-github-community/).  As a result, the Stencil team is no longer maintaining the Stencil router. While these warnings are expected of `@Prop`s in Stencil components that are mutated in a component, I believe to properly silence them for the router specifically would require some rework of the router.

I'm going to see if GH will let me move this issue to the [new stencil community repo for the router...](https://github.com/stencil-community/stencil-router)

**Comment by rwaskiewicz** [comment]
> I'm going to see if GH will let me move this issue to the [new stencil community repo for the router...](https://github.com/stencil-community/stencil-router)

Hmmm looks like I can't 

> Note: You can only transfer issues between repositories owned by the same user or organization account. A private repository issue cannot be transferred to a public repository.

I've recreated this issue at https://github.com/stencil-community/stencil-router/issues/139. Please follow that new issue for updates.
