### ISSUE TITLE
Broken render of SVG

### ISSUE THREAD

**Issue by neslinesli93** [ionic-team/stencil#2854]
**Stencil version:**
```
 @stencil/core@2.4.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
We are experiencing wrong render of SVG elements in our stencil components. What we've noticed is that `viewBox` attribute is added in lowercase format to elements, resulting in no-rendering happening in the browser. **However** there are two different scenarios:
- if we render an svg right from a webcomponent, the element is **rendered fine** and all the attributes are in the correct case
- if we create a stencil bundle with functional components that render svg elements, when we try to import it in another stencil application, attributes are rendered in the **wrong format** unexpectedly

**Expected behavior:**
We expect SVG elements to render properly when used inside web components

**Steps to reproduce:**
1) Create a stencil application that exports a **functional component** that renders and svg element with a `viewBox` attribute
2) Create an `index.ts` that exports the functional component you created
3) Build the application
4) Import the resulting bundle in a new stencil application and render it.
5) The svg is not rendered

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**
There are already a couple issues (https://github.com/ionic-team/stencil/issues/2726, https://github.com/ionic-team/stencil/issues/1847) that describe the problem, and it seems it has been fixed at some point in the past... It seemed to be that `hasSvg` property existed at some point in the past, but right now it can't be injected from a `Component`

**Comment by ngfk** [comment]
Having this same issue in stencil `v2.6.0`.

In my case I was rendering some dynamic component without using `jsx`, so directly using the `h` function. The thing is stencil does some simple checks to determine if your build contains svg elements ([here](https://github.com/ionic-team/stencil/blob/45388e95edb46ef357eb9ae37cd32bbb5bc1ed23/src/compiler/app-core/app-data.ts#L51) I think).

This gif shows that stencil detects the presence of svg elements when directly specified (jsx would compile to something similar). But when setting the tag using a param stencil no longer thinks there are svg elements and doesn't render properly.
![Jun-07-2021 11-57-43](https://user-images.githubusercontent.com/25618095/121033342-6653c380-c7ac-11eb-8dc9-df2ca30e556e.gif)

Here's my initial render method, the important part to note is that stencil has no way of telling that this component will render an svg element.
```typescript
  renderElement(el: AbstractElement): VNode {
    return h(
      // stencil doesn't know this tag could be an svg
      el.tag,
      el.attributes,
      el.children?.map(c => this.renderElement(c)) || []
    );
  }

  render() {
    const { classes, name: iconName, pre: prefix } = this;

    const i: FaIcon | undefined =
      icon({ iconName, prefix }, { classes }) ||
      icon({ iconName: 'square', prefix: 'far' }, { classes });

    if (i?.iconName !== iconName || i?.prefix !== prefix)
      console.warn('Could not find one or more icon(s)', { iconName, prefix });

    return i && this.renderElement(i.abstract[0]);
  }
```

The svg check is a global thing so any component rendering an svg element will enable the svg checks which fixes the problem for any dynamic svg elements. In my component I simply turned the fallback element to an empty svg.
```typescript
  render() {
    const { classes, name: iconName, pre: prefix } = this;

    const i: FaIcon | undefined =
      icon({ iconName, prefix }, { classes }) ||
      icon({ iconName: 'square', prefix: 'far' }, { classes });

    if (i?.iconName !== iconName || i?.prefix !== prefix)
      console.warn('Could not find one or more icon(s)', { iconName, prefix });

    // Returning an empty svg as fallback sets the global svg flag allowing the
    // dynamic render method (other case) to render properly
    return i ? this.renderElement(i.abstract[0]) : <svg />;
  }
```

**Comment by splitinfinities** [comment]
Hey folks! Can you help by creating a reproduction repo as well as updating to the latest version of Stencil?

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
