### ISSUE TITLE
Allow removal of service worker in config

### ISSUE THREAD

**Issue by ajonp** [ionic-team/stencil#286]
**Stencil version:**

```
 @stencil/core@0.0.6
```

**I'm submitting a:**

- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
There is no way of removing serviceworker from stencil build.

**Expected behavior:**
Allow in stencil.config.js serviceWorker : false

**Steps to reproduce:**
Run build with serviceWorker:false you will still see index.html with code.

**Related code:**

```tsx
https://github.com/ionic-team/stencil/blob/e4a44b5ebe2e53a103d3b712490dcc23bd3fa7b6/src/compiler/service-worker/inject-sw-script.ts#L13

Change
if (match) {
    indexHtml = indexHtml.replace(match[0], `${getRegisterSwScript(swUrl)}\n${match[0]}`);
  }
if (match && config && config.serviceWorker) {
    indexHtml = indexHtml.replace(match[0], `${getRegisterSwScript(swUrl)}\n${match[0]}`);
  }

```

**Other information:**

**Comment by jgw96** [comment]
Fixed by https://github.com/ionic-team/stencil/pull/322 . Thanks @ajonp for opening this issue (:
