### ISSUE TITLE
Unrecognized TypeScript custom path when compiling

### ISSUE THREAD

**Issue by jimyhdolores** [ionic-team/stencil#2860]
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request

**Current behavior:**
I am using custom paths from typescript, in development it gives no problems, but when compiling the d.ts does not recognize the custom path, any solution?

![image](https://user-images.githubusercontent.com/10909792/111817266-cfadef80-88ab-11eb-87b5-74c01b2c57e1.png)
![image](https://user-images.githubusercontent.com/10909792/111817363-ec4a2780-88ab-11eb-969b-9cd6af78ee6e.png)

**Comment by splitinfinities** [comment]
We vendor our own version of TypeScript into Stencil in order to make Stencil's input and output reliable. We don't currently have any plans to support custom TypeScript versions in Stencil.
