### ISSUE TITLE
Different `class`es when pre-rendering vs. in browser causes the two to merge instead of overwrite

### ISSUE THREAD

**Issue by tjleing** [ionic-team/stencil#2871]
## **Stencil version:**

```
 @stencil/core@2.5.2
```

## **I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

## **Current behavior:**

If the classes on a DOM element differ when pre-rendering vs. in a real browser environment, the two classes both get applied to the DOM element.  For example, if a `<div>` has `class="class-a"` when pre-rendering but `class="class-b"` when running in the browser, it will result in `<div class="class-a class-b">`.

## **Expected behavior:**

Should just be `<div class="class-b">` -- i.e., the browser class should overwrite the pre-rendering class.

## **Steps to reproduce:**

One easy way to see this is by using local storage, as is the case on the Amplify docs website (issue linked below).

After running `npm init stencil`:
```tsx
// app-switcher.tsx
import {Component, h} from "@stencil/core";

@Component({tag: "app-switcher", shadow: false})
export class AppSwitcher {
  setLocalStorage() {
    localStorage.setItem("test", "test");
  }

  render() {
    let divClass = "class-a";
    if(localStorage.getItem("test") === "test") {
      divClass = "class-b";
    }

    return (
      <div class={divClass}>
        <button onClick={this.setLocalStorage}>set local storage</button>
      </div>
    );
  }
}
```

```tsx
// app-home.tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'app-home',
  styleUrl: 'app-home.css',
  shadow: true,
})
export class AppHome {

  render() {
    return (
      <app-switcher></app-switcher>
    );
  }
}
```
Then after `npm build` and `npx run serve`, click the button, refresh, and see that the `<div>` has `class="class-a class-b"`.  On the other hand, note that `npm start` and following the same steps leaves the `<div>` with `class="class-b"`.

Similarly, the `if` statement could just be
```tsx
let divClass = "class-a";
if(Build.isBrowser) {
  divClass = "class-c";
}
```
which also reproduces the bug, but that seemed a little bit artificial to give as the motivating example.

As a side note to aid reproduction, I found that the app doesn't function properly the first time `npm build`ing it (it 404s on some compiled files), but the second time building it works.  Hope that helps!

## **Other information:**

In production: https://github.com/aws-amplify/docs/issues/3091.  Thank you very much for the help!

**Comment by tjleing** [comment]
We ended up having to just not pre-render the component where the problem was presenting itself in production.  The issue is left open because it is still unresolved (we would very much like to be able to pre-render every component).  Any response would be appreciated.

**Comment by splitinfinities** [comment]
Hey there! If you could help by creating a reproduction repo, that would be a huge help!

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
