### ISSUE TITLE
Problem with hide fallback slot

### ISSUE THREAD

**Issue by chenyulun** [ionic-team/stencil#2878]
**Stencil version:**

```
 @stencil/core@2.5.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Fallback slot messes between parent and child components

**Expected behavior:**

Correctly handle fallbak slot issues for parent and child components

**Steps to reproduce:**

```tsx
// my-component
import { Component, h } from '@stencil/core';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: false,
})
export class MyComponent {

  render() {
    return <div><slot><span>my-component fallback</span></slot></div>;
  }
}
// my-button
import { Component, h } from '@stencil/core';

@Component({
  tag: 'my-button',
  styleUrl: 'my-button.css',
  shadow: false,
})
export class MyButton {

  render() {
    return <div>
      <my-component>
        <div data-txt="Insert into the default slot of my-component">
          <slot data-tip="lun-button The default slot of the lun-button"><span>LunButton fallback</span></slot>
        </div>
      </my-component>
    </div>;
  }
}
```
```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0" />
    <title>Stencil Component Starter</title>

    <script type="module" src="/build/lun-button.esm.js"></script>
    <script nomodule src="/build/lun-button.js"></script>
  </head>
  <body>
    <!-- <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component> -->
    <my-button></my-button>
  </body>
</html>
```
<div style="color:red;">The result of the actual rendering，The page is blank<div>  
```html
<my-button class="hydrated">
    <!---->
    <div>
      <my-component class="hydrated">
        <!---->
        <div>
          <slot-fb hidden=""><span>my-component fallback</span></slot-fb>
          <div data-txt="Insert into the default slot of my-component">
            <slot-fb data-tip="lun-button The default slot of the lun-button" hidden=""><span>LunButton fallback</span>
            </slot-fb>
          </div>
        </div>
      </my-component>
    </div>
  </my-button>
```  
The actual rendering hides the parent component's slot fallback as well  

![Snipaste_2021-04-09_11-11-47](https://user-images.githubusercontent.com/15979948/114123207-707c5180-9924-11eb-8c98-cb85fa78c804.png)

**Other information:**

1. I think there should be a boundary between the elements of the parent component and the elements of the child component, and should not be mixed
2. In fact, the problem of slot passthrough cannot be handled correctly
```jsx
<div><slot name"abc" slot="abc"></slot></div>
```

**Comment by chenyulun** [comment]
@adamdbradley @WickyNilliams
Request help to analyze, quite anxious
tks!

**Comment by chenyulun** [comment]
fix advice:
```ts
// keep drilling down
      updateFallbackSlotVisibility(childNode);
```
Suggest to change the above code to
```ts
// keep drilling down
// If it is a slot node element passed in from outside, it will not be processed in depth
if(!childNode['s-ol']) {
    updateFallbackSlotVisibility(childNode);
}
```

**Comment by chenyulun** [comment]
Hidden slot and hidden slot fallback should be processed centrally and not separately.
Initialization should hide all slots,
When checking for slot in a Web component, move the external slot into the component, unhide the slot, and set the slot fallback to hidden.

**Comment by chenyulun** [comment]
When a Web component initializes the hidden slot tag, the component records $flags$of 4 because the external slot elements are processed only when the internal check reaches the slot tag, so the external slot elements are not hidden

**Comment by nicolas-skrzek** [comment]
Is the problem solved? I see there is a PR that contains a fix for this issue. But I'm in `@stencil/core@2.7.0` and I've this issue.

**Comment by tanner-reits** [comment]
This doesn't appear to be an issue in the latest version of Stencil (v4.9.1 at the time of this comment). Please let us know if you encounter this issue on the latest or future version(s).
