### ISSUE TITLE
Unable to pass JSX between components in different libraries

### ISSUE THREAD

**Issue by gtranter** [ionic-team/stencil#2884]
**Stencil version:**

```
 @stencil/core@2.5.2
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

We have multiple component libraries. In one library for "common" components we have dialog and dialog-launcher components. The purpose of the dialog launcher is to reuse a common dialog component and to live at the body root to ensure that the dialog backdrop appears above any other elevated elements.

Components in other libraries use the dialog launcher by passing JSX that the launcher sets in the dialog's slot. This worked well in Stencil 1.12.7 but no longer works in 2.5.2 (we are in the process of updating all our libraries but this problem has delayed us and may end up preventing the update entirely). The rendered elements lose inner content and properties/attributes - leaving the the bare empty element e.g. `<div></div>`. Because the inner content is missing, only the top level of DOM is included. If an element is a custom element, it is hydrated and renders correctly, but will be missing any child (slotted) content.

If the components are in the same library it works fine.

And most strangely of all - it works fine in IE11 - Chrome and Firefox don't work. That seems to suggest that it is shadow DOM related.

**Expected behavior:**

Passing JSX as content into another component by way of a function should work fine as it did in Stencil 1.12.7.

**Steps to reproduce:**

**Related code:**

_Dialog Launcher_
```tsx
@Component({
    tag: 'dialog-launcher'
})
export class DialogLauncher {

    /**
     * Reference element for dialog so that it can be closed.
     */
    private _dialogElement: HTMLDialogElement;

    /**
     * Dialog configuration object used to create the dialog.
     */
    @State() config: DialogConfiguration = null;

    /**
     * Called after the component state changes and the component is ready.
     * When `openDialog` is used, the `dialog` will be opened here.
     */
    componentDidUpdate() {
        if (this.config && this._dialogElement) {
            this._dialogElement.open();
        }
    }

    /**
     * This method is used to close an open dialog - 'blocking' dialogs will need to use this,
     * as well as any action buttons that cause the dialog to close.
     */
    @Method()
    async closeDialog() {
        if (this._dialogElement) {
            await this._dialogElement.close();
        }
    }

    /**
     * This is the main method to open the dialog.
     *
     * @param config DialogConfiguration
     * @returns The ti-dialog element
     */
    @Method()
    async openDialog(config: DialogConfiguration): Promise<HTMLDialogElement> {
        this.config = config;
        return new Promise(resolve => resolve(this._dialogElement));
    }

    render() {
        if (!this.config) {
            return <Host></Host>;
        }

        return (
            <Host>
                <dialog
                    class={this.config.class}
                    modal={this.config.modal}
                    ref={(el) => this._dialogElement = el}
                >
                    {this.config.content}
                </dialog>
            </Host>
        );
    }
}
```
_Dialog Configuration_
```tsx
export interface DialogConfiguration {
    class?: string;
    content: JSXBase.HTMLAttributes<HTMLElement> | JSXBase.HTMLAttributes<HTMLElement>[];
    modal?: boolean;
}
```
_Dialog User_
```tsx
@Component({
    tag: 'dialog-user'
})
export class DialogUser {

    private _dialogLauncher: HTMLDialogLauncherElement;

    private _openDialog() {
        if (!this._dialogLauncher) {
            this._dialogLauncher = document.querySelector('dialog-launcher') as HTMLDialogLauncherElement;
            if (!this._dialogLauncher) {
                this._dialogLauncher = document.createElement('dialog-launcher') as HTMLDialogLauncherElement;
                document.body.appendChild(this._dialogLauncher);
            }
        }

        const config = {
            class: 'dialog-user',
            content: <div>Hello World</div>,
            modal: true
        };

        this._dialogLauncher.openDialog(config);
    }

    /**
     * render function
     */
    render() {
        return (
            <button onClick={() => this._openDialog()} >Open dialog</button>
        );
    }
}
```
The Dialog component can be anything that renders and uses shadow DOM.

**Other information:**

**Comment by LukePammant** [comment]
My team is facing the same issue. We have a generic table element that we want to pass a custom 'renderDelegates' to indicate how to render each column. It works if its in the same code base but doesn't work across code bases. Our goal is to support this sort of method in a framework agnostic way so perhaps a render delegate that returns JSX isn't a good idea...

**Comment by gtranter** [comment]
I think that using JSX in this manner should be supported. Without it there is really no good way to "bind" content back to the originating component.

It was supported (worked) in Stencil 1, so I assume that something was rewritten for Stencil 2 and that didn't consider this use case - an oversite if you will.

**Comment by gtranter** [comment]
Has anyone from the Ionic team seen this? Any comment would be appreciated.

**Comment by gtranter** [comment]
@splitinfinities Could you clarify the reason for closing this as a duplicate of #2925? Based on the description and test cases, they are a similar problem but a *very different* cause/use case - the problem here is passing JSX between `different libraries` whereas the other report it is between different classes within the `same library`. Have you determined the root causes of each and found them to be the same? If so, does that mean that a fix will be provided soon?

**Comment by adrm** [comment]
I would understand for this feature to not be supported, but I would love to get some confirmation or explainer about it. Thanks a lot!
