### ISSUE TITLE
Props passed via state tunnel throw "immutable but was modified from within the component" warning message

### ISSUE THREAD

**Issue by dhrumil83** [ionic-team/stencil#2888]
Worked fine till 2.3.0. See this warning when updating from 2.3.0 to 2.5.2 for any prop passed via state tunnel.
@Prop() "propName" on < custom-element-name > is immutable but was modified from within the component.
More information: https://stenciljs.com/docs/properties#prop-mutability

https://github.com/ionic-team/stencil-state-tunnel ( @stencil/state-tunnel": "1.0.1")

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

This repo has the steps to reproduce this issue:
https://github.com/dhrumil83/state-tunnel-issue

**Comment by samk-ayyagari** [comment]
@dhrumil83  Can you please let me know how did you solve this problem ?

**Comment by dhrumil83** [comment]
It's only warnings in the console and does not seem to affect behavior. But will be good to get rid of the warnings.
Still waiting on the fix.

**Comment by splitinfinities** [comment]
If you could do me a favor, update to the latest Stencil and let me know if this is still the case. We did ship some related fixes recently. 

If it's still the case, let me know. Thank you!

**Comment by dhrumil83** [comment]
Updated  `"@stencil/core": "2.10.0"` and still seeing the warnings.
