### ISSUE TITLE
EventEmitter not found in @stencil/core

### ISSUE THREAD

**Issue by deltaGPhys** [ionic-team/stencil#2890]
**Stencil version:**

```
@stencil/core@2.5.2 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I import `EventEmitter`, I get this TS error: `TS2305: Module '"@stencil/core"' has no exported member 'EventEmitter'.` Additionally, `EventEmitter` objects are undefined, and an exception is thrown when trying to emit

**Expected behavior:**
The event should be emitted, as described in the docs

**Steps to reproduce:**

**Related code:**

```tsx
import { Component, Host, h, Prop, State, Watch, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'child',
  shadow: true,
})
export class ChildComponent {

  @Event() submitEvent: EventEmitter<any>;

  submit() {
    this.submitEvent.emit(null);
  }

  render() {
    return (
      <Host>
      <slot>
        <input type="submit" value="Submit" onClick={this.submit}/><br/><br/>
      </slot>
      </Host>
    );
  }

}

```

```tsx
import { Component, h, Listen } from '@stencil/core';

@Component({
  tag: 'app-home',
  styleUrl: 'app-home.css',
  shadow: true,
})
export class AppHome {

  @Listen('submitEvent')
  submit(e: CustomEvent) {
    e.preventDefault();
    console.log('event heard');
  }

  render() {
    return (
      <div class="app-home">
            <stencil-router>
              <stencil-route url="/" component="child-component" exact={true}/>
            </stencil-router>
      </div>
    );
  }
}

```

**Other information:**

**Comment by DaSchTour** [comment]
I get a similar error for Prop. And when looking into file where it should be (compiler says it's `node_modules/@stencil/core/internal/client/index.js`) then I don't see any export for Prop.

**Comment by rwaskiewicz** [comment]
Hey @deltaGPhys,

Can you please provide some additional information so we can take a further look? Unfortunately I was unable to replicate this with the information provided. Would you be able to provide us with both
- a minimal reproduction repo that we can pull from GitHub
- details as to where you're seeing this error? IE is it strictly in your IDE, after running a specific npm script (like `npm run build`, in the browser like @DaSchTour's comment suggests, or a combination of any of the above

**Comment by DaSchTour** [comment]
Maybe it was also an issue with the [NX Plugin for stencil](https://github.com/nxext/nx-extensions)

I migrated my components from Stencil to Angular Elements, because that's also used in my stack. So I'm out. Sorry.
