### ISSUE TITLE
srcset values gets striped, when defined more than one.

### ISSUE THREAD

**Issue by selodev** [ionic-team/stencil#2891]
example:
```
<img src="..." srcSet="img.jpg 200w, imgtwo.jpg 300w, imgthree.jpg 400w">
```
becomes:
```
<img src="..." srcSet="img.jpg?v=1234567891 200w">
```
https://github.com/ionic-team/stencil/blob/45388e95edb46ef357eb9ae37cd32bbb5bc1ed23/src/compiler/prerender/prerender-optimize.ts#L327

**Comment by splitinfinities** [comment]
Is this still the case in latest versions of Stencil? Would love to have a quick reproduction repo that we can test against.

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
