### ISSUE TITLE
Lazy slot assignment

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#290]
**Stencil version:**

```
 @stencil/core@0.0.7
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request

**Current behavior:**
Named slot assignment is only determined during initial load of the elements. If the child does not have the `slot="some-name"` attribute, then it is slapped into the default slot when there is more than one. 

**Expected behavior:**
If the slot attribute is self-assigned by the child element, then it should render in the expected space. Perhaps with a MutationObserver and an attributeFilter?

**Related code:**

```tsx
@Component({
    tag: 'some-panel',
    styleUrl: 'some-panel.scss',
    shadow: true
})
export class SomePanel {
    @Prop() isActive: boolean;
    render() {
        return [<slot name="header" />, <slot />, <slot name="footer" />];
    }
}
//----
@Component({
    tag: 'some-header',
    styleUrl: 'some-header.scss',
    shadow: true
})
export class SomeHeader {
    @Element() host: HTMLElement;
    constructor() {
        // It is not allowed to modify the attributes during construction
    }
    componentWillLoad() {
        !this.host.hasAttribute('slot') && this.host.setAttribute('slot', 'header');
    }
    protected render() {
        return <slot />;
    }
}
```
- Does not work : IE11, Edge, Firefox.
- Works: Chrome

**Other information:**

We really love what you have created here because it provides us a way to build towards the coming functionality without tons of polyfills. If we can avoid the boilerplate `slot="some-name"` by building it into the related elements, that would be fantastic! 

I also understand if this causes too much issue but it never hurts to ask. In the meantime we will be using `shadow: false` to make sure browsers act the same.

Thanks!

**Comment by adamdbradley** [comment]
Thanks for opening the issue. At this time the slot polyfill is pretty limited, and things like dynamic slots has been excluded in order to keep the runtime small. I would recommend staying away from dynamic slots for now as it can be pretty tricky for polyfills and browsers that do not support shadow dom. Thanks

**Comment by dgibson666** [comment]
We're causing child headers and footers and the like to automatically slot inside of their parent by defining the slot in hostData(). I'm not 100% sure if that's the same as what you're saying, but this works everywhere for us. E.g.,

```javascript
    hostData() {
        return {
            'slot': 'template-footer'
        };
    }
```

**Comment by cary-smith** [comment]
This does work in Chrome but has some odd behavior when using default slotted content in the last polyfilled browser (IE11 continues to make the interwebz sad). We have several components that have default behaviors through simplistic means (like a string input) but allow 'overrides' via slotted elements for more customized DOM. 

It is an excellent suggestion, but unfortunately will not work for us at the moment. Thanks @dgibson666!
