### ISSUE TITLE
Scoped slots

### ISSUE THREAD

**Issue by pierrebaronqumu** [ionic-team/stencil#2901]
**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Other information:**

I would like to request the ability to do scoped slots like in Vue (https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots) in StencilJS. 

Several frameworks allow for it in different ways (Scoped slots in VueJS, Actions in [https://github.github.io/catalyst/guide/actions/](Catalyst), ...) It would be good to have this feature in StencilJS too.

**Why**

This can help us provide headless components, in the same way than https://headlessui.dev/

**Comment by splitinfinities** [comment]
Hey great ask! I'm going to tag this with Request for Comments. If anybody would like to pile on so we can get stronger community signal, that'd be awesome!

**Comment by christian-bromann** [comment]
@pierrebaronqumu thanks for raising the issue.

This is definitely a nice feature, however we've decided not to move forward with it at this point.
