### ISSUE TITLE
ChildNode before() and after() are missing in testing-library

### ISSUE THREAD

**Issue by javo2223** [ionic-team/stencil#2903]
**Stencil version:**
```
 @stencil/core@2.5.0
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
We miss the [ChildNode.before()](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/before) and [ChildNode.after()](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/after) methods inside the testing library of stenciljs. Other standard Web API methods are mocked. At the moment our test methods are failing if we use this methods.
`child.before is not a function`

**Expected behavior:**
We want to use these methods and the test code should not fail anymore. 

**Steps to reproduce:**

Put the following code into your component.

**Related code:**

```tsx
componentDidLoad() {
    const parent = document.createElement('div');
    const child = document.createElement('p');
    parent.appendChild(child);
    const span = document.createElement('span');

    child.before(span);
  }
```

**Comment by christian-bromann** [comment]
Thanks @javo2223  for raising the issue.

At this point we recommend to look into our alternative testing solution for Stencil which are WebdriverIO or Playwright which allow you to run Stencil component test in a more realistic browser environment. The team is currently not planning into improving the custom DOM implementation we use for these types.

Let me know if you have further questions. Cheers!
