### ISSUE TITLE
Generating docs does not works for multiple tsx files in a folder

### ISSUE THREAD

**Issue by amitjindal** [ionic-team/stencil#2910]
**Stencil version:**

```
@stencil/core 1.17.4                                                                                                                                                       
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

In `src/components/my-component` folder I have my-component.tsx and my-component-subcomponent.tsx.
When I generate markdown documentation with command: `stencil build --docs`, I only get documentation for one of these components. Usually second one: my-component-subcomponent

**Expected behavior:**

Documentation for both/all components should be generated in same or different files. In my humble opinion it is not desirable to keep these in separate folders as subcomponent by itself has no purpose and is a part of component.

**Steps to reproduce:**

1. Generate a new component
2. Add a subcomponent in same folder.
3. Generate docs: stencil build --docs

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Additionally, it is Stencil's opinion to ask folks to organize their component definitions into their own structured folders. Co-locating component definitions isn't the opinion of a Stencil component library, though we may revaluate that in the future. 

Let me know if you need anything else!

**Comment by rwaskiewicz** [comment]
I'm going to close this issue for now following @splitinfinities's explanation above. Thanks again for your patience!
