### ISSUE TITLE
How to setup stencil component library with version 1

### ISSUE THREAD

**Issue by patriciamarchand** [ionic-team/stencil#2913]
Hello, 
I would start a component library with stencil version 1.
the script **npm init stencil** add the version2. How to start with version 1?

thanks

**Comment by prbaron** [comment]
Hi,

you can manually downgrade the version in your package.json and rerun `npm install`.

**Comment by rwaskiewicz** [comment]
Hey @patriciamarchand,

@prbaron is correct, although I would suggest using the latest version of Stencil if possible. Is there a reason you need to use v1 of Stencil?

**Comment by rwaskiewicz** [comment]
Since Stencil v2 is the preferred way of creating a component library, I'm going to close this issue. Please feel free to open a new issue if there's a use case for using v1 of Stencil that we aren't considering at this time!
