### ISSUE TITLE
Web worker compiler pollutes the namespace

### ISSUE THREAD

**Issue by romanroe** [ionic-team/stencil#2914]
**Stencil version:**

```
 @stencil/core@2.5.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When using the web worker feature, the Stencil compiler inserts generated code:

```
const GET_TRANSFERABLES = `
const isInstanceOf = ...
const getTransferables = ...
`
```

These symbols (isInstanceOf, getTransferable) live in the same namespace as any top-level and imported symbol inside the worker.  This leads to a runtime exception if the web worker declares a variable, function, etc. with the same name. Symbols imported from libraries will also conflict.

**Expected behavior:**

Any generated symbol must not compete with user symbols.

**Steps to reproduce:**

1. Create a worker, e.g. my.worker.ts
2. write a function isInstanceOf
3. Import the worker from a component
4. Browser will log the error "Uncaught SyntaxError: Identifier 'isInstanceOf' has already been declared"

**Other information:**

https://github.com/ionic-team/stencil/blob/f91548fa90da39937a8f7b7320134a2ca8db71e0/src/compiler/bundle/worker-plugin.ts#L198

**Comment by splitinfinities** [comment]
Hey! Thank you for pointing this out. We're going to do some investigation. I'll circle back when we have more information. 

Thank you!
