### ISSUE TITLE
Build file generating `.stencil` folder inside `dist/types` but  interface  constants inside`component.d.ts` referring `component`s

### ISSUE THREAD

**Issue by shyam528** [ionic-team/stencil#2915]
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Build file generating `.stencil` folder inside `dist/types` but  interface constants inside`component.d.ts` referring `component`s

**Expected behavior:**

Interface constant file inside the component.d.ts should refer to `.stencil` or it should create `components` folder inside the `dist/types`.

**Steps to reproduce:**

**Related code:**

```
dist/types/.stencil/tux-icon/tux-icon.d.ts                 
dist/types/.stencil/tux-icon/tux-icons.stories.d.ts        
dist/types/.stencil/tux-input/tux-input-interface.d.ts     
dist/types/.stencil/tux-input/tux-input.d.ts               
dist/types/.stencil/tux-input/tux-input.stories.d.ts       
dist/types/.stencil/tux-row/tux-row.d.ts                   
```

```
Inside dist/types/component.d.ts

`import { InputChangeEventDetail } from "./components/tux-input/tux-input-interface"`

```
Its path reference pointing to `components` but stencil generating `.stencil` folder

Here is my stencil config

```
namespace: 'tuxedo',
  // globalStyle: 'src/styles/common.css',
  outputTargets: [
    reactOutputTarget({
      componentCorePackage: '@bsn/TuxComponents',
      proxiesFile: './dist/react/components.ts',
    }),
    {
      type: 'dist',
    },
    {
      type: 'docs-readme',
      footer: `*For more information, please refer to [Website Platform Wiki]*`,
    },
  ],
  plugins: [
    inlineSvg(),
    sass({
      includePaths: ['node_modules'],
    }),
  ],

```

**Other information:**

**Comment by splitinfinities** [comment]
Hi there! I'm curious if you could help by adding a reproduction repo? I can see you're using react bindings. I can see that the cached folder is being picking up at some point, and I don't believe that should be the case. A reproduction repo should help us to understand and identify the problem.

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
