### ISSUE TITLE
Missing piece in "Components without a Framework"

### ISSUE THREAD

**Issue by danielleroux** [ionic-team/stencil#2917]
Iam a little bit confused about the follwing documentation:
https://stenciljs.com/docs/javascript
```html
  <head>
    <script src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic.js"></script>
  </head>
```

If i create a new stenciljs library project (example-test) and build the package with `npm run build`.

Which `.js` should i load with the "<script>"-tag? In my "example-test"-project is no example-test.js in `/dist/`

**Comment by splitinfinities** [comment]
Hey! We're going to close this as a wontfix. Firstly, that page includes examples of how you could do this with your own package published to NPM. I put each of the examples into a codepen and they each worked. You should be able to use that to make your own distribution examples with Stencil. 

Second, [check out the Stencil slack](https://stencil-worldwide.herokuapp.com/) for support questions. Folks there would happily help you along your journey with Stencil!
