### ISSUE TITLE
Add (and/or document?) setting to get detailed build debugging/error output

### ISSUE THREAD

**Issue by kristianmandrup** [ionic-team/stencil#292]
Is there a setting to somehow get the build logger to output which file is currently being processed?This delightful feature would make it is feasible to track down which file is causing an error :)
I was getting these types of build errors ... which sadly weren't very helpful. 

```bash
[ ERROR ]  Undefined variable: "$secondary-border-color". 

[12:09.1]  rebuild failed, watching for changes... in 1.44 s 
```

With 50 odd `.scss` stylesheets, all with imports, kinda hard to track down :O
How about this format with a `--verbose` setting

```bash
[ ERROR ]  my/path/to/component/styles/bad.csss - Undefined variable: "$secondary-border-color". 

[12:09.1]  rebuild failed, watching for changes... in 1.44 s 
```

Or even better with a full stack trace...

```bash
...
[OK] my/path/to/component/styles/good.scss
[WARN] my/path/to/component/styles/ugly.scss - empty file
[ ERROR ]  my/path/to/component/styles/bad.scss - Undefined variable: "$secondary-border-color". 

[12:09.1]  rebuild failed, watching for changes... in 1.44 s 
```

Much improved dev experience :)

**Comment by jgw96** [comment]
Hey @kristianmandrup , are you using the `stencil-app-starter` ?

**Comment by kristianmandrup** [comment]
Yes, I'm using the `stencil-app-starter`. Why?

**Comment by jgw96** [comment]
Hey! Sorry for the delay on this. In the stencil starter you can run `npm run build --debug` and that will tell you exactly which files are being worked on by the compiler, along with some other helpful output. Thanks!
