### ISSUE TITLE
Breaking change with Jest CLI 27

### ISSUE THREAD

**Issue by deleonio** [ionic-team/stencil#2922]
**Stencil version:**

```
 @stencil/core@2.5.2
```

![image](https://user-images.githubusercontent.com/6279703/120053833-b1433d80-c02c-11eb-83fb-c05e383fa33b.png)

**Comment by hvgeertruy** [comment]
I have the same problem.
Possibly related to: https://github.com/facebook/jest/issues/11486

It seems that stencil imports jest files directly from 'build', which is considered a bad practice.

**Comment by ilteoood** [comment]
+1 here, any news?

**Comment by splitinfinities** [comment]
Will be solved with #2980

**Comment by rwaskiewicz** [comment]
https://github.com/ionic-team/stencil/pull/3189 includes support for Jest 27, and will be included in the next minor release of Stencil (v2.13.0)

**Comment by rwaskiewicz** [comment]
Hey folks, this should be fixed in [v2.13.0](https://github.com/ionic-team/stencil/releases/tag/v2.13.0) of Stencil, which was just released with Jest 27 support. I'm going to close this issue for now, but if this comes up again, please feel free to file a new ticket!
