### ISSUE TITLE
CLI Flag --stats does nothing

### ISSUE THREAD

**Issue by pekayde** [ionic-team/stencil#2926]
**Stencil version:**
```
 @stencil/core@2.6.0
```
same issue already in
```
 @stencil/core@2.0.1
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The command `stencil build --stats` does not produce a stencil-stats.json as it is described here https://stenciljs.com/docs/cli

**Expected behavior:**
A file stencil-stats.json is created like described herehttps://stenciljs.com/docs/cli

**Steps to reproduce:**
Add `--stats` to your build script
Run `npm run build`

**Comment by splitinfinities** [comment]
Hey there! Thanks for adding this. We don't have a timeframe, but we have identified this issue. I'll circle back around as we make progress on this.

**Comment by rwaskiewicz** [comment]
I'm going to close this issue, as [v2.9.0 of Stencil](https://github.com/ionic-team/stencil/releases/tag/v2.9.0) resolves this issue. If it does not, please feel free to open another ticket!
