### ISSUE TITLE
Error: Property 'style' does not exist on type 'Element'

### ISSUE THREAD

**Issue by henrykode** [ionic-team/stencil#293]
**Stencil version:**

```
 @stencil/core@0.0.6-10
```

**I'm submitting a:**

- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
With this code:
```tsx
children[i].style.display = 'none';
```
I had this error: Property 'style' does not exist on type 'Element'.

**Expected behavior:**
The code
```tsx
children[i].style.display = 'none';
```
shouldn't be an error.

**Steps to reproduce:**

**Related code:**

```tsx
children[i].style.display = 'none';
```

**Other information:**
I fixed with:

```tsx
children[i]['style'].display = 'none';  no error. 
```

I think the problem is in a kind of  declaration file of typescript.

**Comment by manucorporat** [comment]
Well... it gives an error if children has type Element[], just cast it to HTMLElement

```
(children[i] as HTMLElement).style.display = 'none';
```

**Comment by henrykode** [comment]
Ok thank you very much

**Comment by sureshokp** [comment]
@henrykode what is the solution of this error? i have also same problem

**Comment by henrykode** [comment]
@sureshokp try the solution of manucorporat

**Comment by njokusomto** [comment]
> **Stencil version:**
> 
> ```
>  @stencil/core@0.0.6-10
> ```
> 
> **I'm submitting a:**
> 
> * [x]  bug report
> * [ ]  feature request
> * [ ]  support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com
> 
> **Current behavior:**
> With this code:
> 
> ```tsx
> children[i].style.display = 'none';
> ```
> 
> I had this error: Property 'style' does not exist on type 'Element'.
> 
> **Expected behavior:**
> The code
> 
> ```tsx
> children[i].style.display = 'none';
> ```
> 
> shouldn't be an error.
> 
> **Steps to reproduce:**
> 
> **Related code:**
> 
> ```tsx
> children[i].style.display = 'none';
> ```
> 
> **Other information:**
> I fixed with:
> 
> ```tsx
> children[i]['style'].display = 'none';  no error. 
> ```
> 
> I think the problem is in a kind of declaration file of typescript.

Yep. This worked for me.
