### ISSUE TITLE
Watcher fails in docker container

### ISSUE THREAD

**Issue by maxkarkowski** [ionic-team/stencil#2930]
**Stencil version:**

```
 @stencil/core@2.5.0 or higher
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
i use cypress with stencil and the npm package start-server-and-test. Since version 2.5.0 i get the following error

```
yarn run v1.22.10
$ stencil build --dev --watch --serve
[56:51.7]  @stencil/core
[56:52.0]  v2.6.0 📟

[ ERROR ]  stderr: events.js:292 throw er; // Unhandled 'error' event ^ Error: spawn xdg-open ENOENT at
           Process.ChildProcess._handle.onexit (internal/child_process.js:269:19) at onErrorNT
           (internal/child_process.js:465:16) at processTicksAndRejections (internal/process/task_queues.js:80:21)
           Emitted 'error' event on ChildProcess instance at: at Process.ChildProcess._handle.onexit
           (internal/child_process.js:275:12) at onErrorNT (internal/child_process.js:465:16) at
           processTicksAndRejections (internal/process/task_queues.js:80:21) { errno: -2, code: 'ENOENT', syscall:
           'spawn xdg-open', path: 'xdg-open', spawnargs: [ 'http://localhost:3333/~dev-server-init' ] } undefined
```
the test should run in docker image cypress/base:14

**Expected behavior:**
with version 2.40 i got no error 

**Steps to reproduce:**
run a stencil project in docker (with image cypress/base:14)

run:  stencil build --dev --watch --serve

**Comment by nielsboogaard** [comment]
+1 Experiencing the same with Stencil 2.6.0 when trying to run it in a NodeJs docker container. Running solely Stencil (not wrapped in a docker container) runs just fine.

**Comment by maxkarkowski** [comment]
yeah this breaks all me stencil projects, so i guess i need to stick to version 2.4.0 until this issue is resolved

**Comment by rwaskiewicz** [comment]
Hey @maxkarkowski, would it be possible for you to provide a minimal reproduction repository for us to take a look at? Between containerization of your project, using cypress, etc., it can be difficult to whittle the problem down without any additional information.  If you were able to reduce the problem as much as possible while still reproducing the error, that'd be a big help!

**Comment by maxkarkowski** [comment]
hey @rwaskiewicz i am trying to set up a repo. will maybe take a while because i cannot use the repo i have due to customers agreement

**Comment by rwaskiewicz** [comment]
@maxkarkowski, completely understood! 🙂

**Comment by maxkarkowski** [comment]
@rwaskiewicz https://github.com/maxkarkowski/stencil-docker/blob/main/package.json
if u run `yarn run docker:build` and look in the docker hub you should see the error

![image](https://user-images.githubusercontent.com/622841/125039372-b2897080-e096-11eb-9225-2e8e3d89ae21.png)

**Comment by rwaskiewicz** [comment]
Thanks @maxkarkowski! I am able to replicate the issue and have narrowed this down to the specific commit where this was introduced. I need to schedule some more time to investigate a little more thoroughly,  I appreciate the helpful reproduction case!

**Comment by maxkarkowski** [comment]
i am not quite sure if changing the port fixes the issue entirely. i have to check that in the original customer repo.

**Comment by rwaskiewicz** [comment]
Hey @maxkarkowski, sorry if that PR I sent you wasn’t clear. Changing the port alone does not fix the issue. Rather, it makes it so that when we apply a fix I think I have, the app can be accessed via the browser. The reason for the port swap PR was so that when I ask the team to review my changes, I can refer to it without asking them to change anything to test things out. Sorry about that!

**Comment by maxkarkowski** [comment]
no problem @rwaskiewicz maybe the github action in my repo helps u guys to isolate the problem more
