### ISSUE TITLE
Build fails with duplicate identifier error in components.d.ts

### ISSUE THREAD

**Issue by gtranter** [ionic-team/stencil#2936]
**Stencil version:**

```
 @stencil/core@2.6.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When building, the typescript error "Duplicate identifier" is thrown in components.d.ts. This only happens when components.d.ts already exists before building.
```
[ ERROR ]  TypeScript: ./src/components.d.ts:7:10
           Duplicate identifier 'HTMLStencilElement'.

      L7:  import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";

[ ERROR ]  TypeScript: ./src/components.d.ts:7:30
           Duplicate identifier 'JSXBase'.

      L7:  import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
```
Line 11 contains the same import statement.

**Expected behavior:**
Build succeeds.

**Steps to reproduce:**
We have a component that imports `JSXBase` and `HTMLStencilElement`. This causes two lines with the same import to be included in components.d.ts. If I remove the import from the component (replace types with `any`), the error does not occur.

**Related code:**

```tsx
import { Component, h, Host, Prop } from '@stencil/core';
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';

@Component({
    tag: 'my-component'
})
export class MyComponent {
    @Prop() jsx: JSXBase.HTMLAttributes<HTMLStencilElement>;

    render() {
        return <Host>
            {this.jsx}
        </Host>;
    }
}
```

**Comment by loudmouth** [comment]
also seeing this one

**Comment by kingdun3284** [comment]
You could try adding a `global.d.ts` with following code first

```ts
import { JSXBase } from '@stencil/core/internal';
export as namespace JSXBase;
export = JSXBase;
```

It may solve your problem temporarily.

**Comment by gtranter** [comment]
@kingdun3284 That doesn't seem to do anything - does the file need to be in a specific location?

**Comment by kingdun3284** [comment]
> @kingdun3284 That doesn't seem to do anything - does the file need to be in a specific location?
After adding this global.d.ts, you have to remove your import jsxbase statement in your component as well

**Comment by gtranter** [comment]
Right. That fixes JSXBase, but HTMLStencilElement is still a problem.

**Comment by kingdun3284** [comment]
> Right. That fixes JSXBase, but HTMLStencilElement is still a problem.

The solution is the same. Redeclare the HTMLStencilElement in global.d.ts and remove the import statement in the component

**Comment by gtranter** [comment]
Sorry for my ineptitude - not much experience with types configuration.

If you mean
```
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export as namespace HTMLStencilElement;
export = HTMLStencilElement;
export as namespace JSXBase;
export = JSXBase;
```

I already tried that - didn't work. Only one `export=` is allowed, and `HTMLStencilElement` can't be used as a namespace anyway. Is there some other way to export `HTMLStencilElement` from global.d.ts?

**Comment by kingdun3284** [comment]
> Sorry for my ineptitude - not much experience with types configuration.
> 
> If you mean
> 
> ```
> import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
> export as namespace HTMLStencilElement;
> export = HTMLStencilElement;
> export as namespace JSXBase;
> export = JSXBase;
> ```
> 
> I already tried that - didn't work. Only one `export=` is allowed, and `HTMLStencilElement` can't be used as a namespace anyway. Is there some other way to export `HTMLStencilElement` from global.d.ts?

```ts
import { HTMLStencilElement as _HTMLStencilElement} from '@stencil/core/internal';

declare global {
    interface HTMLStencilElement extends _HTMLStencilElement { }
}
```

**Comment by gtranter** [comment]
That works - thanks.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now.

[Since importing from the @stencil/core/internals is discouraged](https://github.com/ionic-team/stencil/blob/master/src/internal/readme.md), I'm going to close this as a wontfix.
