### ISSUE TITLE
Styling attributes causes problems with TS

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#294]
Ionic styling attributes cause problems with the ts type-checker. 
Adding some exception for “padding” is not enough, there are more attributes like main, and so on.

<img width="800" alt="screen shot 2017-11-11 at 19 07 08" src="https://user-images.githubusercontent.com/127379/32730956-d1bdbbe8-c888-11e7-83d3-86fea9f473cd.png">

**Comment by jgw96** [comment]
@manucorporat what eversion of ionic/core are you using here? I havent seen this issue in my demos.

**Comment by jgw96** [comment]
Closing this issue for now as it has been a while since there was any activity. Thanks!
