### ISSUE TITLE
Generated HTMLElement types exposed at the global scope

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#295]
Custom HTMLElement types generated by stencil should be exposed at the global scope, not need to import them. Importing all them will not make bundlers bigger (they are ts types).

No need for this:
<img width="494" alt="screen shot 2017-11-11 at 19 12 38" src="https://user-images.githubusercontent.com/127379/32731003-f965ce4c-c888-11e7-8d57-a5a1eacc0bfd.png">

Since they are NOT user-created types, we should consider this a low-level thing that developers do not need to import explicitly.

**Comment by jthoms1** [comment]
Actually we should not export these. Should we move this issue to @ionic/core

**Comment by jthoms1** [comment]
This is fixed with commit 1904e75dbf404c7507f4e0783975e914cd0ef856.
