### ISSUE TITLE
你好，现在为什么npm init stencli会出现create-stencli@latest 404

### ISSUE THREAD

**Issue by xinFengQi** [ionic-team/stencil#2952]
**Stencil version:**
2.6.0
```
 @stencil/core@2.6.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
执行npm init stencli

**Expected behavior:**
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-stencli - Not found
npm ERR! 404 
npm ERR! 404  'create-stencli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Other information:**
在npm中不存在create-stencli包

**Comment by Slevinski** [comment]
You have a typo.  Use "stencil", not "stencli"

**npm init stencil**

**Comment by rwaskiewicz** [comment]
Hey @xinFengQi , I think that @Slevinski is right here. Could you please give their suggestion a try and report back for us please?

**Comment by tinet-dongfb** [comment]
十分抱歉，是我的失误，拼写cli单词习惯了

**Comment by rwaskiewicz** [comment]
Not a problem! Thanks again!
