### ISSUE TITLE
Wrong event listener assumption

### ISSUE THREAD

**Issue by Bibi1606** [ionic-team/stencil#2958]
```
 @stencil/core@2.5.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The assumption whether a member name should be treated as an event listener or not doesn't work properly.
In file set-accessor.ts is a comment starting in line 58 which says, that a member name is an event listener when it starts with "on" and the 3rd letter is in capital. But there is no check in the code for the capital letter. Therefore names like "onlinecheck" are treated as an event listener and lead to errors like:
![Bildschirmfoto 2021-07-12 um 13 24 31](https://user-images.githubusercontent.com/19948547/125279675-82e79c00-e314-11eb-934a-2d175f896386.png)

**Expected behavior:**
Names starting with "on" and not having a capital letter in 3rd place don't get treated as an event listener when the bug gets fixed by implementing the capital letter check.

**Other information:**
Stack trace:
```
index-07229c38.js:2706 TypeError: Failed to execute 'addEventListener' on 'EventTarget': parameter 2 is not of type 'Object'.
    at Object.ael (index-07229c38.js:27)
    at setAccessor (index-07229c38.js:574)
    at updateElement (index-07229c38.js:654)
    at createElm (index-07229c38.js:703)
    at addVnodes (index-07229c38.js:784)
    at patch (index-07229c38.js:975)
    at renderVdom (index-07229c38.js:1171)
    at callRender (index-07229c38.js:1419)
    at updateComponent (index-07229c38.js:1341)
    at index-07229c38.js:1322
```

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. Can you do me a favor and add a link to a Reproduction repo on Github? Also, seems like this only occurs in IE11, based on what I'm seeing. Is that the case?
