### ISSUE TITLE
Importing custom HTMLElement types break stencil build

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#296]
When adding:
```
import { HTMLIonNavElement } from '@ionic/core';
```

I get this issue:
<img width="712" alt="screen shot 2017-11-11 at 19 15 15" src="https://user-images.githubusercontent.com/127379/32731039-0e4acf2e-c889-11e7-901a-2108a939aee1.png">

**Comment by jthoms1** [comment]
This is no longer an issue with commit: 1904e75dbf404c7507f4e0783975e914cd0ef856. These definitions are now in global scope and should be referenced in that way instead of being imported.
