### ISSUE TITLE
RegExp broken sticky flag support in polyfills (core-js)

### ISSUE THREAD

**Issue by gtranter** [ionic-team/stencil#2991]
**Stencil version:**

```
 @stencil/core@2.6.0
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

RegExp does not work properly in IE11 because of a core-js bug. The bug is https://github.com/zloirock/core-js/issues/810. It does not seem like the core-js developer/team is interested in fixing this - they appear to be waiting for someone else to contribute.

**Expected behavior:**

No issues with RegExp in IE11.

**Steps to reproduce:**

See https://github.com/zloirock/core-js/issues/810.

**Other information:**

It would be greatly helpful if Stencil could revert to `core-js@3.5.x` or maybe fix the bug in polyfills.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now.

We're going to hold off on this for the time being, hopefully corejs can incorporate a fix sooner than later. We'll keep our eye out.

**Comment by gtranter** [comment]
@splitinfinities Thanks for the response. Maybe you didn't see it in the linked core-js issue - but they don't appear to be at all interested in fixing it.
