### ISSUE TITLE
Ideas for simplified syntax for components

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#300]
**Stencil version:**
```
@stencil/core@0.0.7
```

**I'm submitting a:**
- [x] feature request

**Current behavior:**

Currently components are implemented as an instance class and then bi-directional links are created between the component instance and the html element that is the actual web component instance.  Some members are implemented on both the component instance and the HTMLElement.

As an example, a component might look like this:
```tsx
@Component({
    tag: 'old-hello'
})
export class OldHello {

    @Element()
    private el: HTMLElement;

    @Prop({
        mutable: true
    })
    name: string;

    @Method()
    updateName(): void {
        this.name += '*';
    }

    render(): JSX.Element {
        return <span>Hello {this.name} from {this.el.tagName}</span>
    }

}
```
The component is a pseudo MixIn class where some of the members are used to extend the HTMLElement that is created along with other extensions related to the Stencil infrastructure.

**Proposed behavior:**

A potential change to the component syntax might look like this:
```tsx
export class NewHello extends StencilComponent {

    name: string;

    updateName(): void {
        this.name += '*';
    }

    render(): JSX.Element {
        return <span>Hello {this.name} from {this.tagName}</span>
    }
}
```

Stencil would define an underlying base class with the appropriate Stencil and HTMLElement interfaces.  For polyfill environments it might not actually extend the actual HTMLElement class but would end up with the same interface result.  The base class would look something like:

```tsx
export abstract class StencilComponent extends HTMLElement {

    // private _values, _vNode, etc.

    mode: string;
    color: string;

    // other private/protected/public members

    public abstract render(): JSX.Element
}
```

In this case the component derives from a base component class rather than mixing with other interfaces.

Another part of the change is to embrace TypeScript features vs. having potentially conflicting definitions.

Some of the decorators would not be needed or could be optional.
- `Component()` implicit from base class.  Default `tag` could be calculated from class name (e.g. `new-hello` in the example).
- `Prop()` implicit from `public` properties.
- `Element()` not needed.
- `Method()` not needed.

**Benefits:**
There are a variety of potential benefits to this approach including:

Simplifies component authoring
- No instance vs. element confusion.  All type definitions refer to a strongly typed element with the appropriate members from HTMLElement, Stencil and the component.
- `Render()` method.  Render method is required and uses the appropriate method signature from the abstract base class.
- `@Element()` decorator.  No need to use the `@Element()` decorator.  The component can just use `this` to refer to the element.
- `@Method()` decorator.  No need to use the `@Method()` decorator.  Simply declare a method as `public` to have it available from external access.
- Ability to use getters and setters.  The current Stencil approach does not work if properties are defined with getters and setters.  This is in part because the properties are implemented on the element as direct access to the value storage which does not allow for logic in getters/setters.

Improved TypeScript type checking
- The component interface at design time is identical to the interface at runtime.  Currently Stencil generates `OldNameAttributes` which somewhat matches public properties (but complex types are `any`) and `HTMLOldNameElement` which matches neither the component nor the resulting HTMLElement instance (includes union of members which implies combined instance).
- All Stencil members available in the component interface.  This includes things like `mode` and `color` that are currently merged into the component definition.
- All HTMLElement members are available on the component interface since they are part of the `StencilComponent` base class.
- `public`, `protected`, `private`, `readonly`, etc. can be enforced correctly.  Currently it is possible to use `@Method()` with a private method which causes it to actually be public.  Currently if you mark a method as `public` but do not specify a decorator then it is not really public.
- Mutable properties.  Use `readonly` modifier to designate whether properties should be immutable.  This allows TypeScript to enforce it at design time rather than waiting for runtime errors.
- `Prop` vs. `State`.  Could use public / private modifier to indicate current `Prop` vs. `State` distinction.  `@Prop() private myProp` does not makes sense and `@State() public myState` would imply external set was ok.

Performance
- All component transformation could be done on the class prototype so that there is very little code that needs to run when each instance is created.  Currently each component instance has getter and setter functions defined for every property which results in lots of functions created and destroyed with the associated memory requirements, garbage collection, etc.

There may be some underlying reasons why some or all of these things can not be done but I thought it was worth throwing the idea out there while Stencil is still in its formative stage.

**Comment by adamdbradley** [comment]
Thanks for the feedback, and this is something we've been kicking around a lot, but I think in general we've been attempting to stay away from extending a stencil component as much as possible for a few reasons. One of the biggest reasons is so that we're not bundling all of the components together, but allowing them to each be independent. It's certainly still possible to lazy load components that extend classes, but to keep code splitting and lazy loading simple, one of the easiest way is to not have every component import the same base class.

Additionally, we'd like to keep our options open for the user to easily decide which base HTML class to extend, which right now defaults to HTMLElement.

I do agree we can come up with some better interfaces though, or document better how to use our interfaces to ensure lifecycle methods and spelled correctly. Also should add that none of this is final and we're absolutely listening, but also being very careful right now about introducing any API. Thank you for your feedback!

**Comment by cjorasch** [comment]
Here is another idea: what if the component is treated as a MixIn for HTMLElement so that everything is done on the element vs. having both an element and a component instance.

For example:

```tsx
// components.d.ts
declare global {

    // Extensions from Stencil
    export interface StencilComponent extends HTMLElement {
        mode: string;
        color: string;
    
        componentDidLoad?: () => void;
        componentDidUnload?: () => void;
        // etc.
    
        render(): JSX.Element
    }

    // Combined interface after extending HTMLElement
    export interface HTMLHelloWorldElement extends HelloWorld, StencilComponent { }
}

// hello-world.tsx
@Component({
    tag: 'hello-world'
})
export class HelloWorld {

    name: string;

    render() {
        const el = (this as any) as HTMLHelloWorldElement;
        return <span>Hello {el.name} from {el.tagName} with color {el.color}</span>
    }

}
```

This would allow for a well defined, strongly typed interface on the generated class without any imports on the component definition.  Alternate base classes could also be incorporated into the global interface where appropriate.  

Simple components that did not need access to Stencil or HTMLElement members could continue to use `this` without need to cast to the global interface.

All of the class members could be implemented on the prototype so that component instances would not need to be initialized.  Essentially there would be a generated class that would be the union of the members of HTMLElement, StencilComponent and HelloWorld.

For example, something like:

```tsx
// --- Stencil core ---

// Define base class for components
class StencilComponent extends HTMLElement {
    name: string;
    mode: string;
    // implementation of all base component methods
}

// --- For each component prior to loading component ---

class HostElement extends StencilComponent {}
customElements.define('hello-world', HostElement);

// --- When component has been lazy loaded (class definition now available) ---

// Extend with members defined on component class implementation
Object.assign(HostElement.prototype, HelloWorld.prototype);

// Other prototype initialization from meta-data (getters, setters, etc.)

// --- When a component instance is created ---

// No need to define getters and setters because already in prototype
// No need to create bi-directional links or additional component instance
// No need to define Stencil extensions to class
```
