### ISSUE TITLE
“dist-custom-elements-bundle” does not set delegatesFocus when attaching shadow

### ISSUE THREAD

**Issue by Amiiiirali** [ionic-team/stencil#3002]
**Stencil version:**
```
 @stencil/core@2.6.0
```

**I'm submitting a:**
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The output target dist-custom-elements-bundle does not attachShadow with delegatesFocus parameter.

**Expected behavior:**
It's expected that when you include delegatesFocus in component options, instances of components have shadow root with this option too.

**Steps to reproduce:**
I have created a demo here: https://github.com/Amiiiirali/delegates-focus-test
It needed to build first, then serve and uncomment scripts in index.html to test two different outputs.
the registered element must have the "delegatesFocus" option, independent from the kind of output target.
unlike the dist or www output target, dist-custom-elements-bundle does not register the element with this option and just attaches shadow with the 'mode' option.

**Other information:**
I had a look into the stencil runtime and seems It just looks as if the build is lazy, and the compiler just adds delegatesFocus to components when lazy outputs have been chosen.

**Comment by splitinfinities** [comment]
Hey there! Thank you for submitting this with a Reproduction repo! I'll circle back on this issue soon.

**Comment by splitinfinities** [comment]
We don't have a timeframe, but we have identified the issue. We'll let you know when we have a fix.

**Comment by Amiiiirali** [comment]
thank you a lot
we handled the issue by the below approach as a workaround (for anybody else who encountered the same issue)
We've set the shadow with false in the component decorator, and attached it manually in the constructor.
I could create a PR if you mind so

**Comment by rwaskiewicz** [comment]
Hey @Amiiiirali 👋 

This issue has been patched in #3117 and has been released as a part of [Stencil v2.10.0](https://github.com/ionic-team/stencil/releases/tag/v2.10.0), which was released earlier today. I've tested it against your reproduction repository and everything appears to be working as expected now*. I'm going to close this issue, but please feel free to open a new issue if that's not the case! Thanks again!

\*  Please note that Firefox does not support `delegatesFocus` natively until v94, which as of this writing has not been released in the stable channel (but is available in the 'developers edition' right now)
