### ISSUE TITLE
Slot content flickering when we working with visibility

### ISSUE THREAD

**Issue by ChandruMoger** [ionic-team/stencil#3008]
**Stencil version:**

```
 @stencil/core@2.6.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When the component loads, slot content flickers before hiding from view.

**Expected behavior:**
The content passed to the slot shouldn't show till manually click the button to show.

**Steps to reproduce:**
Run the project with **npm start**.
Project link: https://github.com/ChandruMoger/stencil-slot-demo

**Related code:**

```tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true,
})
export class MyComponent {
  detailBox: HTMLElement;
  showDetails = () => {
    this.detailBox.classList.remove('display-none');
  };
  render() {
    return (
      <div>
        <button onClick={this.showDetails}>Show detail</button>
        <span
          id="detail"
          ref={elem => {
            this.detailBox = elem;
          }}
          class="display-none"
        >
          <slot></slot>
        </span>
      </div>
    );
  }
}
```

**Other information:**

**Comment by splitinfinities** [comment]
#2989 may solve your problem. When it lands, let me know.

**Comment by ChandruMoger** [comment]
@splitinfinities , Is this PR yet to be merging right.
How can I use it now, any documentation on how can I use this?

**Comment by ChandruMoger** [comment]
> #2989 may solve your problem. When it lands, let me know.

@splitinfinities is #2989 available now?

**Comment by rwaskiewicz** [comment]
@ChandruMoger is available in `@stencil/core@2.8.0`, please let us know how it works out!

**Comment by ChandruMoger** [comment]
@rwaskiewicz Still issue exists after update the stencil core.
Please see this https://github.com/ChandruMoger/stencil-slot-demo repo to reproduce.
If I miss something, please let me know.

**Comment by splitinfinities** [comment]
Hi @ChandruMoger - I took another look at your repro and this is working as expected. During the time between your javascript parsing  and your component mounting and hydrating, the way you have coded slots do in fact create a flicker by your design of the element. Javascript needs to add the class to the part of the slot in your render function, which will cause this behavior.

I recommend one best practice: if you'd like to hide slotted content, you can add a css rule to the globalStyles css file to target and hide anything within the custom element. After which, your component code can force any visibility it needs with more a more specific CSS selector.
