### ISSUE TITLE
Missing upgrade step in non-bundled .js

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#303]
Here's a repo case:

Library A (ionicons): distributed with version 5

Library B (ionic-core): distributed with version 6
- Uses Library A as dependency 

App C (starter): using stencil 6
- Uses Library B as dependency

Problem:
Compiled Library B in prod mode includes the upgraded Library A:
https://unpkg.com/@ionic/core@0.0.2-21/dist/ionic/zpjtgobv.js

<img width="844" alt="screen shot 2017-11-13 at 20 47 18" src="https://user-images.githubusercontent.com/127379/32752708-7e09560a-c8ca-11e7-82a1-44be8a051666.png">

BUT, the non-prod output still contains the old version (5)

https://unpkg.com/@ionic/core@0.0.2-21/dist/collection/dependencies/icon/icon.js

When compiling App C, it thinks that upgrade step is not needed since the manifest of Library B is version 6.

**Comment by manucorporat** [comment]
Closing https://github.com/ionic-team/stencil/issues/299 since this issue points to the root cause.

**Comment by adamdbradley** [comment]
Ionicons has been updated, should be good now
