### ISSUE TITLE
bug: Incorrect Error Page Message About ES5 Support in Production

### ISSUE THREAD

**Issue by deltaGPhys** [ionic-team/stencil#3041]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.5.2

### Current Behavior

This error message appears when using IE11 in a production app:

This Stencil app is disabled for this browser.
- ES5 builds are disabled during development...
- Please see...
- **Note that, by default, ES5 builds and polyfills are enabled during production builds**
- ...

This does not appear to be the case: `buildEs5` has to be opted in to via `true` or `prod` in the config, or `--es5` switch on the build command. If this is indeed the case, then the error page is incorrect and can lead to frustration when the build doesn't work with IE11.

### Expected Behavior

Error page correctly describes defaults and options

### Steps to Reproduce

Build app without `buildEs5` option activated

**Comment by rwaskiewicz** [comment]
👋 Thanks! This issue was fixed in https://github.com/ionic-team/stencil/pull/2993, and is slated for the next Stencil release (which will be later this week)

**Comment by deltaGPhys** [comment]
Excellent - thanks!

**Comment by rwaskiewicz** [comment]
v2.8.0 has been [released](https://github.com/ionic-team/stencil/releases/tag/v2.8.0). I'm going to close this issue, please let us know if this is not resolved in this version of Stencil
