### ISSUE TITLE
Add componentOnReady: Promise<TheElementType> to types for all stencil elements

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/stencil#305]
Add componentOnReady: Promise<TheElementType> to types for all stencil elements

Right now if you do this:

```
const element = document.querySelector('ion-nav');
return element.componentOnReady().then(() => {
   console.log(`I'm Hydrated!`);
});
```

You get a compile error due to the definition not existing.

Thanks,
Dan

**Comment by jthoms1** [comment]
I think we should create an interface for all HostElements methods and have the components extend from it in the types file. https://github.com/ionic-team/stencil/blob/b921c10038204f23a498a41471c30ed6219c2a20/src/util/interfaces.ts#L882-L917

**Comment by danbucholtz** [comment]
Yeah I think that would be totally fine as well.

Thanks,
Dan

**Comment by jthoms1** [comment]
Based on the discussion between @danbucholtz @adamdbradley and myself we realized that no one has asked for this outside of the need within ionic-core.  We are going to punt on this for now until more people are using stencil to build web components for outside libraries then we will see if this is something that is needed.

**Comment by kevinmpowell** [comment]
Resurrecting this...I'd like to see this feature.

**Comment by jthoms1** [comment]
At some point this was added and should be available on all Stencil Components.

**Comment by kevinmpowell** [comment]
Yeah, just found it. But not in the docs... :(

**Comment by JimGaleForce** [comment]
This sample, directly from the ion-action-sheet fails due to this missing... https://github.com/ionic-team/ionic-docs/blob/master/src/demos/api/action-sheet/index.html. Not sure people know to complain that this fails in order to drive up this request.

**Comment by gen2work** [comment]
Where did you see it @kevinmpowell please I need this, 

I need to be able to detect if stencil component is ready outside the component

Thanks
