### ISSUE TITLE
feat: Allow Host attributes to be overwritable prior to componentWillLoad

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil#3052]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Host, when setting values on attributes within a render function - with the exception of class - will toss a value that's set on the html element prior to the lifecycle. Ideally, we can have some mechanism to allow all attributes to be overwritten - or a select few attributes.

### Describe the Use Case

Consider this naive render function: 

```jsx
<Host role="header">...</Host>
```

Right now, if users did:

```html
<ion-header role="somethingelse"></ion-header>
```
 that would not work and the `somethingelse` value would be lost. 

### Describe Preferred Solution

```tsx
@Component({
  host: { 
    mutableAttributes: true // or ["role"] 
  }
})
```

Which will allow attributes the element has set to be read and overwritten prior to when the lifecycle is called. 

### Describe Alternatives

```tsx
import {Host} from "@stencil/core"

Host.mutableAttributes = ["role"] // or true

export class Component {
  render() {
    return <Host role="header" />
  }
}
```

or

```tsx
import {Host} from "@stencil/core"

export class Component {
  render() {
    Host.inherit = ["role"];
    return <Host role="header" />
  }
}
```

### Additional Information

(Via @willmartian) 

For context, this is what we do right now: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/input/input.tsx#L237

And then this: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/input/input.tsx#L439

**Comment by tanner-reits** [comment]
This was resolved in [Stencil v4.0.3](https://github.com/ionic-team/stencil/releases/tag/v4.0.3). Please re-open this issue if you are still experiencing issues after updating.
