### ISSUE TITLE
bug: making wrapper component.

### ISSUE THREAD

**Issue by OlekRia** [ionic-team/stencil#3058]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.7.1

### Current Behavior

I cannot make a wrapper component

### Expected Behavior

I can make a wrapper component :)

### Steps to Reproduce

Use stenciljs

### Code Reproduction URL

https://github.com/ionic-team/stencil/issues/new?assignees=&labels=&template=bug_report.yml&title=bug%3A+

### Additional Information

Guys.
I need to write a wrapper component to HTMLInput component. Simply adding some styling for example.
I searched in the internet for the answer how to make it properly:

I found this:
import { Component, Element } from '@stencil/core';

```
@Component()
export class MyComponent {
  @Element() el: HTMLInputElement;

  connectedCallback() {
    console.log(this.el.localName);
  }
}
```

So the idea is to make a component which has the same properties as Input control. All of those properties should be passed to the inner <input /> component. 

I am not sure this is a bug. But I couldn't find any other way to implement it well.
Agree with me,  it's a horror to copypaste all the properties.
Please help.

**Comment by dmartinjs** [comment]
you have multiple way to do it,
[as Ionic](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/input/input.tsx) by recreating all the props of the native input,
or just [using a slot](https://stenciljs.com/docs/templating-jsx#slots) and your wrapper provide only the styling but not the input.

**Comment by OlekRia** [comment]
@dmartinjs , I couldn't get it well. For example, this <input /> may have tons of properties, which a user may use randomly.
Implement the interface for each of them - that's a madness :)

<my-component {...there-are-properties-from-HTMLInputElement}>

and those pops should get directly to wrapped input element. Ionic sample is a madness, man :)
Slot - is not a suitable one, it's something else.
I thought it possible like this:

export class IoInput extends HTMLInputElement {

....

render() {
....
<input {...this} />
....
}

**Comment by OlekRia** [comment]
I tried to make like this: 

```
export class IoInput {
  @Element() el!: HTMLIoInputElement & HTMLIoInputElement
....

render() {
const aaa = this.el as  HTMLInputElement
...
< input { ...aaa} />
...
}
```

Unfortunately, it doesn't work.
But it would be great if it could work.

**Comment by dmartinjs** [comment]
Unfortunately, Stencil doesn't support extending native component
https://stenciljs.com/docs/faq#why-doesn-t-stencil-extend-htmlelement

and it doesn't work in some browser (https://caniuse.com/custom-elementsv1)
Safari supports "Autonomous custom elements" but not "Customized built-in elements" see [WebKit bug 182671](https://bugs.webkit.org/show_bug.cgi?id=182671).

I know we use it a lot in React but it's a pain to reproduce it with web component APIs 😞

**Comment by cjorasch** [comment]
Wrapper components that pass through all properties are pretty easy to do when implemented as Functional Components but not easy as full components.  You end up needing to implement all of the properties (e.g. like `<ion-input>`.

**Comment by OlekRia** [comment]
A Functional component has own limits: It cannot be used as a tag :)
 Implementing all of the properties is so... stupid and boring task... Is that possible in this way to make a king of generator?

**Comment by dmartinjs** [comment]
@OlekRia 
I made a copy/paste from the `ion-input` of Ionic code base on my side 😅

**Comment by splitinfinities** [comment]
Hey all, this seems like a support question. Also, something like #2921 may solve your problem here if you're looking to do that. If so, would you mind adding a 👍 to the PR summary (please not as a comment!) so we can gather community signal around that? Thank you!
