### ISSUE TITLE
bug: React - Class constructor Button cannot be invoked without 'new' when using dist-customs-element bundle 

### ISSUE THREAD

**Issue by Arvind6353** [ionic-team/stencil#3063]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.8

### Current Behavior

**Getting Class constructor Button cannot be invoked without 'new' when using dist-customs-element bundle** 

Am using `import {defineCustomElements, setAssetPath, FwButton} from "fw-design-core/dist/custom-elements"

defineCustomElements();

<FwButton color="link" onFwClick={(e) => console.log("cliekd")}>
          Primary with out wrapper{" "}
        </FwButton>

`
Am getting **Class constructor Button cannot be invoked without 'new'** 

![Uploading image.png…]()

### Expected Behavior

FWButton should render as a webcomponent

### Steps to Reproduce

use the below sample

`import {defineCustomElements, setAssetPath, FwButton} from "fw-design-core/dist/custom-elements"

defineCustomElements();

<FwButton color="link" onFwClick={(e) => console.log("cliekd")}>
          Primary with out wrapper{" "}
        </FwButton>`

### Code Reproduction URL

https://github.com/Arvind6353/react-wc/blob/master/src/App.js#L41

@splitinfinities

**Comment by Arvind6353** [comment]
@splitinfinities Kindly help with the above error.

**Comment by Arvind6353** [comment]
@dmartinjs Can you please help on the above issue ?

**Comment by liamdebeasi** [comment]
Hi @Arvind6353,

You do not need to tag us. The Stencil Team regularly checks the GitHub issues and will reply when they are able to.
