### ISSUE TITLE
Absolute URL set at Stencil collection build time is a challenge for deployment

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/stencil#307]
So my suggestion for the URL sort of fell through the cracks

[4:14] 
Rather than hard-coding in a url for stencil

[4:14] 
What if we did something like

[4:14] 
`SomeUserDefinableGlobal.absoluteUrlBase || '/build/ionic.js'`

[4:14] 
where `/build/ionic.js` is also user definable of course

[4:14] 
By doing it this way

[4:15] 
We would allow the user to specify it in the header of their html file

[4:15] 
and it would make it easier to configure

[4:15] 
'cause right now it is kind of a pain, when I use `ionic/core` in my blank starter, I manually go in to `node_modules` and change this path first

[4:16] 
Which is totally fine but not upgrade friendly

[4:16] 
Where as getting that into a user-assignable global is much more friendly

**Comment by adamdbradley** [comment]
Something we need to document better is that the publicPath which is hardcoded into the loader script is just a fallback. But the loader script does figure out the correct relative path which all lazy loaded files should use.

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil-site/issues/93
