### ISSUE TITLE
bug: Declaration files not generated for imported stencil compents - dist custom elements bundle

### ISSUE THREAD

**Issue by Arvind6353** [ionic-team/stencil#3075]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.8

### Current Behavior

Hi Team, 

Am importing a stencil component inside another stencil component library.

When I use dist-custom-elements bundle, declaration files are not generated for the imported components . It is causing issues when trying to build react binding wrapper.

### Expected Behavior

Declaration files must be generated for the imported components too.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/23059431/133934845-d1dcbd39-4113-4617-95f8-9ab9d5a46a55.png)

### Code Reproduction URL

https://github.com/Arvind6353/fw-crayons-mono/blob/master/packages/fw-crayons-extended/stencil.config.ts#L46

**Comment by splitinfinities** [comment]
Hey @Arvind6353 - We're going to look into this and report back to you. Thank you for the patience!

**Comment by rwaskiewicz** [comment]
Hey @Arvind6353, thanks for the patience. It looks like that reproduction case no longer exists - can you provide a new one to us?

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
