### ISSUE TITLE
bug: e2e Testing CustomEvents omits Object methods in details

### ISSUE THREAD

**Issue by stanley85** [ionic-team/stencil#3076]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.7.0

### Current Behavior

We wrote a small CustomEvent called "validate" that carries a dataObject in its details. The object also contains a method member that is prensent inside the object placed in the CustomEvent details. When firing the Event all childcomponents validate themself and look if there is an object present for them having name and group selectors match.
```
@Prop() rules: ValidateRules = [
    {
      group: 'address',
      name: 'test',
      validate: text => {
        return text.length > 3;
      },
      success: 'ok',
      error: 'not ok',
    } as ValidateRule,
  ];

@Event({
    eventName: 'tc-form-validate',
    composed: true,
    cancelable: true,
    bubbles: true,
  })
  formValidate: EventEmitter<FormValidate>;

this.formValidate.emit({ rules: this.rules, submit: false });
```
The array named this.rules houses the objects that makeup the validation rules for the child components. Inside the browser this behaviour works as expected. During testing with Jest the validate member method is missing when the object arrives at the child component. This has something todo with security trust between the components I guess.

Jest testing e2e
```
it('should validate on request', async () => {
    const page = await newE2EPage();
    await page.setContent('<tc-input group="address" name="test" type="text"></tc-input>');
    const spyValueValidate = await page.spyOnEvent('tc-input-validation');
    const component = await page.find('tc-input');
    await component.callMethod('setValue', 't');
    await page.waitForChanges();
    var eventDetail = {
      submit: true,
      rules: [
        {
          group: 'address',
          name: 'test',
          validate: function (text) {
            console.log('zed', text);
            return text.length > 3;
          },
          success: 'ok',
          error: 'not ok',
        },
      ],
    };
    await component.triggerEvent('tc-form-validate', {
      bubbles: true,
      composed: true,
      cancelable: true,
      detail: eventDetail,
    });
    await page.waitForChanges();
    const expectedSubmit = {
      group: 'address',
      name: 'test',
      result: false,
      value: 't',
    };
    expect(spyValueValidate).toHaveReceivedEventDetail(expectedSubmit);
  });
```

The expectedSubmit missmatches because the result is fed with null when there is no validate member typeof 'function' to validate against. 

In the jest runner one of the rules is logged as
`{"group":"address","name":"test","success":"ok","error":"not ok"}`

I have string conversion here but the validate method is not present at all - checked this with typeof rule.validate === 'function' results false and JSON.stringify(typeof rule.validate) results 'undefined'

In the browser the object is not missing its member method validate
`{group: "address", name: "test", success: "ok", error: "not ok", validate: ƒ}`

### Expected Behavior

The EventDetail housing objects should behave like in the browser not omitting any object methods during testing with the jest test runner. Maybe the testrunners context providing the event-detail is not trusted the way a parent component would emit the Event?

### Steps to Reproduce

Hand down a member method inside a CustomEvent detail during testing. Expect this member method to reach the child components scope inside the event listener.

### Code Reproduction URL

https://github.com/stanley85/tc-jest-test-repo

### Additional Information

Inside the real app the rules are handed down from the parent component inside the event. There is no member method lost when the parent component provides the event instead of the CustomEvent inside the jest testrunner environment.

**Comment by christian-bromann** [comment]
Thanks @stanley85 for raising the issue.

At this point we recommend to look into our alternative testing solution for Stencil which are WebdriverIO or Playwright which allow you to run Stencil component test in a more realistic browser environment. The team is currently not planning into improving the custom DOM implementation we use for these types.

Let me know if you have further questions. Cheers!
