### ISSUE TITLE
Hyphens in namespace cause invalid component JS files

### ISSUE THREAD

**Issue by dimi-nk** [ionic-team/stencil#308]
**Stencil version:**

```
 @stencil/core@0.0.8-0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Even though hyphens are allowed in the namespace, the namespace string is used as is in JS as a variable name (actually as a property of window, which is then used without the window object). Hyphens in variable names are invalid in JS.

**Expected behavior:**

Be able to choose a valid namespace which doesn't cause the generated files to be invalid

**Steps to reproduce:**

0. Clone `stencil-component-starter` & `npm install`
1. In `stencil.config.js` set a namespace using hyphens, e.g. `foo-bar`
2. Change `package.json`'s browser to `dist/foo-bar.js`
3. Change `src/index.html`'s `script` to `src="/build/foo-bar.js`
4. run `npm run dev`
5. Check the console of your browser for errors
6. `dist/foo-bar/my-component.js` is invalid because of var identifier `foo-bar`

**Related code:**

```tsx
foo-bar.loadStyles("my-component","\n:host(.hydrated){visibility:inherit !important}");
foo-bar.loadComponents(...);
```

**Other information:**

Chrome console:
```
Uncaught ReferenceError: foo is not defined
    at my-component.js:3
```

**Comment by adamdbradley** [comment]
Should be fixed as of this commit, thanks! https://github.com/ionic-team/stencil/commit/0e403fe890ecda79716ed0b7dde1ae0015757098

**Comment by dimi-nk** [comment]
@adamdbradley Thanks for the quick reply. Out of curiosity, why are you conditionally using 'window'? Why not use it always?

**Comment by adamdbradley** [comment]
No real good reason other than it looks ugly and adds a 0.00001 bytes to the file size. I'm joking cuz it really is just me being crazy, but a majority of the time we don't need `window[..]`. But yeah, mostly me just being crazy.

**Comment by dimi-nk** [comment]
Thanks mate ;)
![](https://media1.tenor.com/images/55150cb68b0c172b8088dd3c888522d0/tenor.gif?itemid=5155775)
