### ISSUE TITLE
bug: [!] Error: 'Prop' is not exported by node_modules/@stencil/core/internal/stencil-core/index.js, imported by src/stencil/input.tsx

### ISSUE THREAD

**Issue by skiv71** [ionic-team/stencil#3080]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.8.1

### Current Behavior

Have a small test project, manually installed stencil, created a basic tsx, using vscode, tsconfig.json all happy... but at build time, rollup (and also parcel) complain that the stencil/core (internal/stencil-core/index.js) don't export Prop or Component.

I've checked the source, and technically that's correct, the plain js don't... but the .ts does.

I'm using 2 plugins, node resolve and typescript.. and despite my attempts to fix this with options.. nothing has worked.

Can anyone help please?

### Expected Behavior

Module resolved?

### Steps to Reproduce

create *.tsx as per the stencil page

### Code Reproduction URL

not public yet

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
