### ISSUE TITLE
bug: Scoped CSS classnames wrongly escaped

### ISSUE THREAD

**Issue by nemzes** [ionic-team/stencil#3083]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

v2.8.1

### Current Behavior

When using `scoped: true` on a component, CSS class names with special characters are mangled due to incorrect escaping. This is particularly obvious when using a framework like Tailwind, which makes extensive use of special characters (`:`) in class names.

### Expected Behavior

When using selectors in CSS like `.foo\:bar` the scoped selector in JS should be in the format `.scopeName.foo\:bar`.

Instead we currently get `.foo\.scopeName:bar`, which won't match anything.

### Steps to Reproduce

Create a CSS file with a classname using escaped special characters:

```css
.foo\:bar {
  color: red;
}
```

Use the class in a component that has `scoped: true`:

```jsx
@Component({
  tag: 'my-component',
  styleUrl: 'styles.css',
  scoped: true,
})
export class MyComponent {
  render() {
    return <div class="foo:bar">Hello</div>;
  }
}
```

### Code Reproduction URL

https://github.com/nemzes/stencil-scoped-classes-bug

### Additional Information

Specifically for Tailwind, it is possible to work around this bug by using the `separator` configuration to use a character that doesn't require escaping (e.g. "`_`"): https://tailwindcss.com/docs/configuration#separator

**Comment by nemzes** [comment]
Someone had previously reported this on the Tailwind repo: https://github.com/tailwindlabs/tailwindcss/issues/1985

**Comment by say25** [comment]
Is this closable?

**Comment by rwaskiewicz** [comment]
This bug should be closable now with the [release of v2.11.0](https://github.com/ionic-team/stencil/releases/tag/v2.11.0) of Stencil, which happened ~30 minutes ago. Should anyone find a new instance of it (this bug), please open a new issue!
