### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by dahfazz** [ionic-team/stencil#3084]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

I did not find a way to listen for @stencil/store changes from component side.

I tried and failed using @Listen

### Describe the Use Case

My component is a multilevel picker which mean anytime the request change (value in store) each item knows if it has to be displayed comparing itself to store value but, I want to display a badge on item showing result number in children.
For that I need to know when to recalculate that number, and it is when request changes.

### Describe Preferred Solution

Might be the ability to use @Listen() on stencil/store values.

**Comment by diegovallarta** [comment]
Hi, 
If you have a reference to the store you can just use the onChange method

**Comment by dahfazz** [comment]
Thank you @diegovallarta 
I read it in doc but understood it was available in store only
