### ISSUE TITLE
Invalid data if using property name 'list' or 'type'

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#309]
**Stencil version:**
 @stencil/core@0.0.8-3

**I'm submitting a:**
- [x] bug report

**Current behavior:**
If you use `list` or `type` as the name of a component property then the property values will always be converted to a string.

For example:

```tsx
@Component({
    tag: 'my-test'
})
export class MyTest {
    public render() {
        const list = [1, 2];
        return (
            <div>
                <my-component list={list} list2={list} type={list} />
            </div>
        );
    }
}

@Component({
    tag: 'my-component',
})
export class List {

    @Prop() list: object[];
    @Prop() list2: object[];
    @Prop() type: object[];

    public render() {
        return 'test';
    }
}

```

When MyComponent is loaded it ends up with the following values:
- list = '1,2'   (a string value)
- list2 = [1,2] (an array value)
- type = '1,2' (a string value)

**Expected behavior:**

The properties should be the value specified in the parent component.
- list = [1,2] (an array value)
- list2 = [1,2] (an array value)
- type = [1,2] (an array value)

**Other information:**

It looks like this is because of the line 90 in `update-dom-node.ts`.

```ts
  } else if (name !== 'list' && name !== 'type' && !isSvg &&
```

It looks like there is also special handling for names starting with "on" but did not test if that impacted properties like "once".

**Comment by jthoms1** [comment]
I think we will need to add some special considerations for when an item being modified is a custom element.  The offending code in this situation is to account for attributes on specific HTML elements, but with custom elements there are a really large number of possible attribute names.
