### ISSUE TITLE
bug: import external scripts from different folder in to stencil components

### ISSUE THREAD

**Issue by arvindanta** [ionic-team/stencil#3091]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.8

### Current Behavior

Hi, 
I am having an monorepo with **certain lib folder with js files and packages folder containing stencil components.**

the lib folder contains some commonly used code across components in different packages.

Am re exporting them in src/utils/util.ts
`export * from '../../../../lib/utils/Translation';
`
and consuming it in one of the component. 

Dev build is working fine. But when I do prod build and try the www folder , am getting 404 errors for few files .
```
/build/index-38429703.js
/build/app-globals-0f993ce5.js
```

### Expected Behavior

Should allow external js files to be loaded in to the components and prod build should work fine.

### Steps to Reproduce

I am having an monorepo with **certain lib folder with js files and packages folder containing stencil components.**

the lib folder contains some commonly used code across components in different packages.

Am re exporting them in src/utils/util.ts
`export * from '../../../../lib/utils/Translation';
`
and consuming it in one of the component. 

Dev build is working fine. But when I do prod build and try the www folder , am getting 404 errors for few files .
```
/build/index-38429703.js
/build/app-globals-0f993ce5.js
```

### Additional Information

How would I use external assets and build them as part of custom-elements-bundle and dist lazy load bundle. 

Am trying load json files using fetch. I have moved my assets under dist/<<name>> and dist/custom-elements folder but still getting 404.

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
