### ISSUE TITLE
feat: Enable Storybook stories to use Stencil's Compiler API or jsx

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil#3104]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Storybook stories often have a requirement of writing templates, and a common requirement today of writing Stories is adding Lit for templating. If Stencil's Compiler API could be used to compile Storybook stories in order to eliminate the need to separate dependencies, this would solve a large adoption problem that Storybook users have. 

### Describe the Use Case

Stories in Stencil integrations with Storybook today often use Lit and lit tools to spread properties and their set values across the template of an element - e.g. 

```ts
import notes from './readme.md';
import { html } from 'lit-html';
import { spreadProps } from '@open-wc/lit-helpers';

export default {
  title: '@midwest-design/core/avatar',
  component: 'midwest-avatar',
  notes: {
    markdown: notes,
  },
  argTypes: {
    name: {
      defaultValue: 'William Riley',
    },
    processing: {
      defaultValue: false,
    },
    // Etc
  },
};

export const WebComponent = args => html`<midwest-avatar ...="${spreadProps(args)}"></midwest-avatar>`;
```

### Describe Preferred Solution

Ideally, we could be able to use the Compiler API for Story templating e.g. 

```tsx
// Pseudo-code
import notes from './readme.md';
import { h } from '@stencil/core';

export default {
  title: '@midwest-design/core/avatar',
  component: 'midwest-avatar',
  notes: {
    markdown: notes,
  },
  argTypes: {
    name: {
      defaultValue: 'William Riley',
    },
    processing: {
      defaultValue: false,
    },
    // Etc
  },
};

export const WebComponent = args => <midwest-avatar {...args} />;
```

### Describe Alternatives

1. Something to do with the literal Compiler API: https://stenciljs.com/docs/compiler-api

**Comment by ericis** [comment]
Also, see #2328

**Comment by rwaskiewicz** [comment]
Closing this in favor of #2328, which has a little more discussion
