### ISSUE TITLE
bug: `result.html` of hydrateDocument is `null`

### ISSUE THREAD

**Issue by weaintplastic** [ionic-team/stencil#3114]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.7.1

### Current Behavior

When using `hydrateDocument` the result returned doesn't include the hydrated HTML but yields `null` for `result.html`.
The original document though is correctly hydrated an it's HTML can be fetched via the DOM Api with `document.documentElement.outerHTML`.

```js
import { hydrateDocument } from 'yourpackage/hydrate';

export function hydrateComponents(doc) {
  return hydrateDocument(doc)
    .then((result) => {
      console.log(result.html); // --> null
      console.log(doc.documentElement.outerHTML); // --> is hydrated correctly
      return hydrateResults;
    });
}
```

### Expected Behavior

It is expected that the result returned from `hydrateDocument` includes the hydrated document HTML in `html` like stated in stencil's docs:

https://stenciljs.com/docs/hydrate-app#how-to-use-the-hydrate-app

### Steps to Reproduce

To reproduce, we've followed the same approach like in ionics prereder test:

https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/scripts/testing/prerender.js#L57

### Code Reproduction URL

https://stenciljs.com/docs/hydrate-app#how-to-use-the-hydrate-app

**Comment by danbellinski-8451** [comment]
I'm having the same issue on 2.9.0.

**Comment by rwaskiewicz** [comment]
Hey @weaintplastic, thanks for this! Can you do me a favor and add a reproduction case? I'd like to see how you're creating the `Document` that's passed into `hydrateDocument` in the context of a minimal reproduction case (having the whole app/component library is a huge help!).

**Comment by christian-bromann** [comment]
I will go ahead and close the issue as no reproduction case was provided. I am happy to re-open if we get a reproduction case that can enable investigations into this issue. Thank you!
