### ISSUE TITLE
bug: @Prop can't work with typescript's Type alias 

### ISSUE THREAD

**Issue by zhuxindaba** [ionic-team/stencil#3124]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.7.0

### Current Behavior

![image](https://user-images.githubusercontent.com/17308154/139258696-2adfe580-023f-4465-b7f4-2ee2981db492.png)
![image](https://user-images.githubusercontent.com/17308154/139258737-abb784ad-1bea-41fa-adfa-d66fc7fc987a.png)

### Expected Behavior

can work correctly

### Steps to Reproduce

none

### Code Reproduction URL

none

**Comment by rwaskiewicz** [comment]
Hey @zhuxindaba,

@MarkChrisLevy is correct here - it's difficult to declare a `type` that's used by a class member that's annotated with `@Prop`, because the type checker needs to know about it when you're passing props to it, at least in the context of a parent TSX component:

```tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'my-parent',
  shadow: true,
})
export class MyParent {
  render() {
    // if we don't make the type of `first` public with `export`, how do we know it is
    // that 'primary' is allowed?
    return <my-component first={"primary"}></my-component>;
  }
}
```

However, I think this could be improved on the Stencil end in 2 ways:
1. This is not documented anywhere, and we should add it
2. The developer experience for using a component in HTML (like in your example) should be improved.

I'm going to label this issue to get it added to our backlog + for the team to discuss this further

**Comment by zhuxindaba** [comment]
> oing to label this issue to get it ad

thanks for your reply，i'm look forward stencil will solve the problem dynamically when compiling project.

**Comment by zhuxindaba** [comment]
> Hey @zhuxindaba,
> 
> @MarkChrisLevy is correct here - it's difficult to declare a `type` that's used by a class member that's annotated with `@Prop`, because the type checker needs to know about it when you're passing props to it, at least in the context of a parent TSX component:
> 
> ```tsx
> import { Component, h } from '@stencil/core';
> 
> @Component({
>   tag: 'my-parent',
>   shadow: true,
> })
> export class MyParent {
>   render() {
>     // if we don't make the type of `first` public with `export`, how do we know it is
>     // that 'primary' is allowed?
>     return <my-component first={"primary"}></my-component>;
>   }
> }
> ```
> 
> However, I think this could be improved on the Stencil end in 2 ways:
> 
> 1. This is not documented anywhere, and we should add it
> 2. The developer experience for using a component in HTML (like in your example) should be improved.
> 
> I'm going to label this issue to get it added to our backlog + for the team to discuss this further

thanks for your reply，i'm look forward stencil will solve the problem dynamically when compiling project.

**Comment by rwaskiewicz** [comment]
https://github.com/ionic-team/stencil-site/pull/784 has been created to address the documentation gap
