### ISSUE TITLE
bug: esnext target (Public Instance Fields) breaks State props rerendering

### ISSUE THREAD

**Issue by bashmish** [ionic-team/stencil#3130]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.10.0

### Current Behavior

updates of the `@State` props don't trigger rerendering when `tsconfig.json` sets target to `esnext`, because Public Instance Field for `@State` is shadowing getters/setters defined by StencilJS to observe state changes

<img src="https://user-images.githubusercontent.com/137844/140067757-753b8df7-6efd-4d91-9237-2b7da7f35c67.png" width="250">

### Expected Behavior

state updates trigger rerendering

### Steps to Reproduce

Just clone https://github.com/bashmish/bug-stenciljs-state-public-field-esnext, `npm install && npm start` and play with `+` `-` buttons.

Or:
1. Create a component with `npm init stencil`
2. Set `compilerOptions.target` to `esnext` in `tsconfig.json` (activates Public Instance Fields in modern browsers)
3. Add a `@State` prop and some logic to update it and display in the DOM new value (in my repo I use a simple counter example)
4. Try to update the state and see it doesn't rerender

### Code Reproduction URL

https://github.com/bashmish/bug-stenciljs-state-public-field-esnext

### Additional Information

Suddenly this problem doesn't happen for `@Prop` in exactly the same situation.
I debugged why and found this code which remove the shadowing property from the component instance here https://github.com/ionic-team/stencil/blob/16b8ea4dabb22024872a38bc58ba1dcf1c7cc25b/src/runtime/connected-callback.ts#L84
I assume you can use a similar approach for `@State` and maybe explicitly for `@Prop` too, because this code purpose seems to be different.

**Comment by splitinfinities** [comment]
Thank you for the detailed report and the reproduction repo! I flagged this to be validated and @rwaskiewicz will follow up with next steps.

**Comment by rwaskiewicz** [comment]
Hey @bashmish,

I've confirmed this bug. It appears to be the result of Stencil not handling `useDefineForClassFields` being enabled in v4.3.5 properly. Would adding the following to your `tsconfig.json` fix the issue temporarily?

```json
{
  ...
  useDefineForClassFields: false
}
```

Either way, I'm going to label this so that it gets ingested into our backlog to get looked at in the near future. Thanks for such a detailed bug report and repro, the team and I really appreciate it! ❤️

**Comment by rwaskiewicz** [comment]
Thanks @bashmish, that definitely helps, both from a context standpoint and as a separate feature request. CC'ing the product manager, @splitinfinities, for visibility

**Comment by bashmish** [comment]
I learned that `lit` has a similar issue and recommends the same workaround in https://lit.dev/docs/components/decorators/#decorators-typescript

**Comment by rwaskiewicz** [comment]
This has been fixed in [Stencil v2.19.0](https://github.com/ionic-team/stencil/releases/tag/v2.19.0), which was just released. I'm going to close this issue as a result. If this bug should reappear, feel free to open a new issue. Thanks!

**Comment by bashmish** [comment]
Thanks, great job 🤩  I especially like the explainer in the commit message, very clear and detailed, I'm gonna refer to this as an example how to maintain good and healthy history.
