### ISSUE TITLE
Trouble importing external library... and minification fails on build

### ISSUE THREAD

**Issue by deltaepsilon** [ionic-team/stencil#314]
**Stencil version:**

```
 @stencil/core@0.0.8-4
```

**I'm submitting a:**

- [ x] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I'm trying to import and external node module ```@material/ripple```.
```
import { MDCRipple } from '@material/ripple';
```

The import fails on every other build with the following error:

```
typescript: src/components/mdc-button/mdc-button.tsx, line: 3
           Cannot find module '@material/ripple'.
```

What's insane is that if I change a file to force a rebuild, the file imports!

Now I run into my second problem. The ```yarn build``` works if I don't try to use MDCRipple... but if I 
use it, I get the following:

```
[ ERROR ]  Minify JS
           Unexpected token: keyword (var)
```

**Expected behavior:**

**Steps to reproduce:**

1. ```npm install @material/ripple```
2. Try to import MDCRipple and actually use it: ```import { MDCRipple } from '@material/ripple';``

**Related code:**

```tsx
import { Component, Prop } from '@stencil/core';
import { getClassesFromMap } from '../../modules';
import { MDCRipple } from '@material/ripple';

@Component({
  tag: 'mdc-button',
  styleUrl: 'mdc-button.scss',
  shadow: false,
})
export class MDCButton {
  // Classes
  @Prop() icon: boolean;
  @Prop() raised: boolean;
  @Prop() unelevated: boolean;
  @Prop() stroked: boolean;
  @Prop() dense: boolean;
  @Prop() compact: boolean;

  // Functionality
  @Prop() disabled: boolean;
  @Prop() ripple: boolean;

  get button() {
    return this['__el'].querySelector('button');
  }

  get classes() {
    return getClassesFromMap(this.classesMap);
  }

  get classesMap(): Map<String, Boolean> {
    return new Map([
      ['mdc-button', true],
      ['icon', this.icon],
      ['mdc-button--raised', this.raised],
      ['mdc-button--unelevated', this.unelevated],
      ['mdc-button--stroked', this.stroked],
      ['mdc-button--dense', this.dense],
      ['mdc-button--compact', this.compact],
    ]);
  }

  componentDidLoad() {
    if (this.ripple) {
      MDCRipple.attachTo(this.button);
      console.log('ripple', this.button);
    }
  }

  render() {
    return (
      <button
        class={this.classes}
        disabled={this.disabled}
        data-mdc-auto-init={this.ripple ? 'MDCRipple' : null}
      >
        <slot />
      </button>
    );
  }
}

```

**Other information:**

**Comment by jgw96** [comment]
Thanks for opening an issue with us! We are tracking this issue here https://github.com/ionic-team/stencil/issues/271.

**Comment by manucorporat** [comment]
@jgw96 I don't think it is the same issue, I am also having this issue, impossible to build for production because a bug in the minifier

**Comment by manucorporat** [comment]
Opened a new issue: https://github.com/ionic-team/stencil/issues/329
