### ISSUE TITLE
feat: Generate Documentation For Classes/Interfaces

### ISSUE THREAD

**Issue by zimaah** [ionic-team/stencil#3146]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

`class` and `interface` documentation generated along with `props` documentation.

### Describe the Use Case

As a developer consuming a web component library built with `StencilJS` I would like to see the `component` documentation (from its `class` or `interface`) when hovering its markup.

### Describe Preferred Solution

```ts
// my-interface.ts

/**
 MyInterface Docs
*/
interface MyInterface {

   /**
    prop Docs
   */
   prop: string;
}

// my-component.tsx
export class MyComponent implements MyInterface {
   // ...
}
```

```ts
// consuming the lib

<my-component prop={"hello world"} />
```

When hovering `<my-component>` I should be able to see the `class`/`interface` documentation.

**Comment by splitinfinities** [comment]
Going to close this as a duplicate, but mark this https://github.com/ionic-team/stencil/issues/2906 as the leading issue.
