### ISSUE TITLE
bug: mock-doc Node.contains is not inclusive

### ISSUE THREAD

**Issue by kevinleedrum** [ionic-team/stencil#3149]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.10.0

### Current Behavior

In unit tests, `myNode.contains(myNode)` is returning `false`.

### Expected Behavior

`myNode.contains(myNode)` should return `true`.

### Steps to Reproduce

Create a simple unit test like this:

```js
const el = document.createElement('div');
expect(el.contains(el)).toBe(true);
```

The test will fail, but it should pass.  [The spec says](https://dom.spec.whatwg.org/#dom-node-contains) that the passed node should be checked against "inclusive descendants".  The "inclusive" part means that it should include the object (the parent node) itself when comparing.

You can see the correct behavior in the console:
![image](https://user-images.githubusercontent.com/3342530/142670357-d91d7e29-380a-40df-8bbd-5a279f6a4e74.png)

### Code Reproduction URL

https://codesandbox.io/s/stencil-mock-node-contains-test-kcwn2?file=/src/nodeContains.spec.ts

### Additional Information

I can probably submit a PR for this shortly.  I don't see any tests for the mock `Node` implementation, by the way, or I would update the test.

**Comment by rwaskiewicz** [comment]
This fix has been included in the [v2.12.0 release](https://github.com/ionic-team/stencil/releases/tag/v2.12.0). I'm going to close this issue, however if the problem reappears, please feel free to open a new issue!
