### ISSUE TITLE
Unable to import material-ui in the tsx files

### ISSUE THREAD

**Issue by anvesh437** [ionic-team/stencil#315]
When importing material-ui in stencil component it is throwing 'React' dependency error.

How can we add [Material-UI](http://www.material-ui.com/#/get-started/usage) in our own components and use them

**Comment by jgw96** [comment]
Hey! Material-UI is built with react and therefore needs React installed too. This means that in a stencil-starter app, its not going to work. But, we do have alot of the Ionic components ported over to web components (meaning they will work in Stencil starters perfectly) and they all have a material design theme by default. You can check out this repo https://github.com/ionic-team/ionic-stencil-hn-app as an example. All you need to do is `npm install @ionic/core --save` and then put https://github.com/ionic-team/ionic-stencil-hn-app/blob/master/stencil.config.js#L11 in your stencil config. Thanks for using Stencil!
