### ISSUE TITLE
feat: Styled-component support

### ISSUE THREAD

**Issue by Maxou44** [ionic-team/stencil#3173]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Hello,

It would be really nice to natively support styled-component for Stencil 😀

Styled component was initially created for React/JSX : https://github.com/styled-components/styled-components

Some people started a port of styled-components for Stencil but it's limited : 
- https://github.com/auderer/stencil-styled-components
- https://github.com/fifthbeat/styled-stencils

You don't have the "css" import to make complex CSS conditions and it can't use the shadow dom 😨

The styled-componenet project have 35.4k stars and it is used by a lot of people, make it workable with Stencil could improve the visibility and the community around Stencil

I could be really nice to support it natively and allow support for shadow DOM 😍

### Describe the Use Case

Use stencil component syntax with stencil, officially

**Comment by cinchy-m** [comment]
I've got [stitches](https://stitches.dev/docs/framework-agnostic) working with Stencil pretty well. Stitches is pretty similar to styled components.

**Comment by rwaskiewicz** [comment]
Hey folks 👋 

After a few years, it doesn't appear there's much community interest in this feature. I'm going to close this out in favor of steering folks towards 3rd party libraries. We're happy to revisit this in the future though should there be a renewed interest though!
