### ISSUE TITLE
bug: It's recommended to set the "main" property to: ./dist/index.cjs.js

### ISSUE THREAD

**Issue by wbern** [ionic-team/stencil#3175]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.11.0

### Current Behavior

In order to run jest/jsdom tests, we load in the web components to do proper integration testing between the apps and components.

However, if we load in `./dist/index.cjs.js`, all we get is a file that has this content:

```js
'use strict';

```

Setting the path to `"main": "dist/cjs/package.cjs.js"` makes jest work, but it seems stenciljs does not like that?

### Expected Behavior

I would like to be able to disable this warning, since it seems it's just a recommendation?

### Steps to Reproduce

Just change to `./dist/index.cjs`

### Code Reproduction URL

n/a

**Comment by rwaskiewicz** [comment]
Hey @wbern 👋 

Would you be able to provide the team and I with a code reproduction URL? It would greatly help make sure I understand your issue better and expedite the time it takes to look into this.  Thanks!
