### ISSUE TITLE
bug: The attributes x, y, width, height passed by the foreignObject element cannot take effect

### ISSUE THREAD

**Issue by achuanVVVVV** [ionic-team/stencil#3192]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.12.0

### Current Behavior

```tsx
// The input
          <foreignObject
            data-x={100}
            data-y={100}
            data-width={200}
            data-height={200}
            x={100}
            y={100}
            width={200}
            height={200}
         / >
         
// The output
<foreignObject
            data-x=“100”
            data-y=”100“
            data-width=”200“
            data-height=”200“
         / >
   // The attributes x, y, width, height are not valid on the foreignObject element
```

### Expected Behavior

```tsx
// The input
          <foreignObject
            data-x={100}
            data-y={100}
            data-width={200}
            data-height={200}
            x={100}
            y={100}
            width={200}
            height={200}
         / >
         
// The output
<foreignObject
            data-x=“100”
            data-y=”100“
            data-width=”200“
            data-height=”200“
            x="100"
            y="100"
            width="200"
            height="200"
         / >
         //The attributes x, y, width, height have effects on the foreignObject element


```

### Steps to Reproduce

         
          <foreignObject
            data-x={100}
            data-y={100}
            data-width={200}
            data-height={200}
            x={100}
            y={100}
            width={200}
            height={200}
         / >

### Code Reproduction URL

I'm sorry I don't have time

### Additional Information

Can you tell me why? If you can solve it, please help me. Thank you

**Comment by peterpeterparker** [comment]
I just opened an issue regarding the same subject with sample repo: https://github.com/ionic-team/stencil/issues/3193

**Comment by achuanVVVVV** [comment]
> I just opened an issue regarding the same subject with sample repo: #3193
Thank you!

**Comment by rwaskiewicz** [comment]
Thanks @achuanVVVVV! This is a valid issue that I've confirmed on my side and have the team look into this further. If you don't mind, I'm going to close this issue and use #3193 to continue our investigation (to avoid duplicates). Thank you for understanding!
