### ISSUE TITLE
import { applyPolyfills, defineCustomElements } is not working in Vue3 + Vite 

### ISSUE THREAD

**Issue by akhi-ninja** [ionic-team/stencil#3195]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.11.0

### Current Behavior

Created components with stencil 2.11.0 and publish to npm (https://www.npmjs.com/package/bulma-stencil) , when i am trying to import the component in Vue3 application ( built on vite) not working as per this documentation https://stenciljs.com/docs/vue  
But its working when load the module in index.html  like this `<script type='module' src='node_modules/bulma-stencil/dist/bulma-stencil/bulma-stencil.esm.js'></script>` 
here is the warning from vite console 

![image](https://user-images.githubusercontent.com/5537438/147361167-a1372a2b-d1a8-41d0-b03a-1ca4af7ca224.png)

### Expected Behavior

component should load work when we do 
`import { applyPolyfills, defineCustomElements } from 'bulma-stencil/loader';` 

### Steps to Reproduce

Create a package or use test component which is mentioned in https://stenciljs.com/docs/vue  load in vue3 application 

### Code Reproduction URL

https://github.com/akhi-ninja/bulma-stenciljs

**Comment by jeco123** [comment]
Hi guys,

in case you did not already tried, it works when bootstraping vue3 with [vue-cli](https://cli.vuejs.org/).

**Comment by dgateles** [comment]
Awaiting a resolution. Not working with Vite yet.

**Comment by rwaskiewicz** [comment]
👋 The bug reported in this issue has been fixed with the [v2.16.0 release](https://github.com/ionic-team/stencil/releases/tag/v2.16.0) of Stencil.  As a result, I'm going to close this issue.  If you believe that the bug still exists, please feel free to open a new ticket.  Thanks again!

**Comment by zstundys** [comment]
Looks like the `experimentalImportInjection` flag does not work with the `vue-output-target` guide outlined in the [docs](https://stenciljs.com/docs/vue) :/ Would be nice to include Vite-specific guide in the FAQ section :)

**Comment by jeco123** [comment]
from my side everything is ok. I tried react and vue from vite, and vue via the cli.

**Comment by zstundys** [comment]
> from my side everything is ok. I tried react and vue from vite, and vue via the cli.

How have you load the stencil components in Vite Vue project? I thought all that's needed was:

```ts
// main.ts
import { ComponentLibrary } from "vue-output-target-components";
app.use(ComponentLibrary);
```

And then using them in `.vue` files:

```vue
<script setup lang="ts">
import { FdsButton } from "vue-output-target-components";

defineComponent({ components: { FdsButton } }); 
</script>

<template>
  <FdsButton>Hello</FdsButton>
</template>
```

**Comment by jeco123** [comment]
```
js
// main.js
import { createApp } from 'vue'
import App from './App.vue';

createApp(App).mount('#app')
```

```js
// app.vue
<script setup>
import { FdsButton } from "vue-output-target-components";
</script>

<template>
  <main>
    <FdsButton>Hello</FdsButton>
  </main>
</template>
```

**Comment by thijsw** [comment]
I think you also need to setup Vue to recognize the custom elements, like this:

```ts
template {
  compilerOptions: {
    isCustomElement: (tag: string) => tag.startsWith('fds-')
  }
}
```

See https://www.npmjs.com/package/@vitejs/plugin-vue

**Comment by jeco123** [comment]
here is my config into stencil.config.ts

```
js
    vueOutputTarget({
      componentCorePackage: '@tds/web-components',
      proxiesFile: '../vue/src/proxies.ts',
      includeDefineCustomElements: true,
      componentModels: vueComponentModels,
    }),
```

**Comment by tytusplanck** [comment]
For others debugging this issue, this new flag also fixed issues I was having SvelteKit since it also uses Vite.
