### ISSUE TITLE
bug: changing baseURL breaks builds for static websites

### ISSUE THREAD

**Issue by dodgyville** [ionic-team/stencil#3198]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.7.0

### Current Behavior

I would like to serve a static stencil website from a subfolder on an apache2 install.

If I install the app in the top level directory it works fine, however, all attempts to move it to the subfolder have failed.

Setting the baseURL does not appear to affect assets or js files, so when it is deployed by copying the files from the stenciljs build in www/subfolder/ there are a lot of broken links. Manually changing the links does not appear to help and wouldn't be a good long-term solution anyway.

Other than that, stenciljs is great!

### Expected Behavior

I would expect setting baseURL to generate a build that works entirely at that baseURL.

### Steps to Reproduce

1. In `stencil.config.js`, set `baseUrl` to "/" 
2. Execute 'npm run build'
3. Copy contents of `www` to the apache2 html directory.
4. Visit "/", website loads as expected.
5. In `stencil.config.js`, set `baseUrl` to "/app/" 
6. Execute 'npm run build'
7. Copy contents of `www` to the apache2 html directory.
8. Visit "/app/", website partially loads but assets and build files 404 not found.

### Code Reproduction URL

https://github.com/ionic-team/stencil/

**Comment by rwaskiewicz** [comment]
Hey @dodgyville 👋 

Can you please provide me with a minimal reproduction code base where following the steps you've provided will result in the 404's you mentioned? Although the steps themselves make sense, it's difficult to diagnose without seeing the stencil configuration file used, the build command contents etc.  Thank you so much!

**Comment by JStiller** [comment]
This Issue could be related to #1998

**Comment by rwaskiewicz** [comment]
@JStiller agreed! I'm going to leave this issue as-is for now, and see if we can get a full reproduction case (in the event this isn't related to #1998)

**Comment by dodgyville** [comment]
Hi, I have updated to stencil 2.13.0 (was on 2.7) and can not recreate this issue in production. I didn't solve it but I'm going to close it. Thanks for your support!

**Comment by GerardvdStelt** [comment]
I would like to re-open this issue as I (and some others on your StencilJS's Slack channel) am facing the same problem.

The steps to reproduce this are quite simple:
1. npm init stencil or npm init stencil@latest
2. update package file to have a build entry for static files
"build.static": "stencil build --prerender",
3. run: npm run build.static

This indeed creates a static version of the (standard) web app but when hosted from a subfolder (e.g. in an S3 bucket in /www/my-subfolder/) all the /build and /assets references break in the index file. I tried every possible configuration setting but unfortunately without success. Hosting from root level indeed works fine but is not what I need right now.

-Gerard
