### ISSUE TITLE
bug: renderToString: ReferenceError: HTMLCollection is not defined

### ISSUE THREAD

**Issue by danyball** [ionic-team/stencil#3209]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.12.0

### Current Behavior

Using `renderToString` from generated hydrated folder throws this error when using at a node app. A dependency of one of our web components use the code below. No problem with `HTMLElement`, just with `HTMLCollection`:

```
// browser env
        HTMLCollection.prototype.flatpickr = NodeList.prototype.flatpickr = function (config) {
            return _flatpickr(this, config);
        };
        HTMLElement.prototype.flatpickr = function (config) {
            return _flatpickr([this], config);
        };
```

Exact error message:
```
      level: 'error',
      type: 'build',
      header: 'Hydrate Error',
      messageText: 'ReferenceError: HTMLCollection is not defined\n' +
(...)
  url: 'https://hydrate.stenciljs.com/',
  host: 'hydrate.stenciljs.com',
  hostname: 'hydrate.stenciljs.com',
  href: 'https://hydrate.stenciljs.com/',
  pathname: '/',
  port: '',
  search: '',
  hash: '',
  html: null,
  httpStatus: null,
  hydratedCount: 0,
  anchors: [],
  components: [],
  imgs: [],
  scripts: [],
  staticData: [],
  styles: [],
  title: null

```

### Expected Behavior

No error.

### Steps to Reproduce

1. add dependency "flatpickr": "4.6.9" to project
2. use it `import flatpickr from "flatpickr"` in a component
3. generate "hydrated" folder of stencil project 
4. import renderToString to your SSR nodeJS project und use it:

```
    renderToString("<my-element></my-element>", {
        prettyHtml: true
    }).then((err) => {
         console.log(err)
    })
```

### Code Reproduction URL

...comming tomorrow...

**Comment by rwaskiewicz** [comment]
Hey @danyball 👋 

I've marked this issue as 'awaiting reply'. If you could add a comment to this bug report once there's a reproduction url (as of this writing it says "coming tomorrow"), that'll auto flag this issue for the team to take a closer look.  Thanks!

**Comment by danyball** [comment]
Bug is fixed by latest flatpickr version. Closing issue.
