### ISSUE TITLE
bug: relative link in href gets modified in tests to absolute links

### ISSUE THREAD

**Issue by raspyweather** [ionic-team/stencil#3214]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.7.0

### Current Behavior

Unit Tests for Components cannot properly test href's due to relative url's being manipulated by the framework.

### Expected Behavior

relative href values staying unchanged or documentation to exist

### Steps to Reproduce

Example component
```  
render() {
    return (
      <Host>
        <a href={this.link}>Test</a>
        <slot></slot>
      </Host>
    );
```

Related test case:
```describe('link-test', () => {
  // OUTPUT:
  // Expected: "/"
  // Received: "http://testing.stenciljs.com/"
  it('expect link not to be changed', async () => {
    const page = await newSpecPage({
      components: [LinkTest],
      html: `<link-test link="/"></link-test>`,
    });
    const element = page.root.querySelector<HTMLAnchorElement>("a");
    expect(element.href).toBe("/");
  });
});
```

### Code Reproduction URL

https://github.com/raspyweather/stencil-issues/blob/master/src/components/link-test/test/link-test.spec.tsx

**Comment by tricki** [comment]
The `href` property of anchor tags is [always the resolved absolute value](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/href). You can access the attribute with `element.getAttribute('href')`.

Does that fix your issue?

**Comment by raspyweather** [comment]
Yes, thank you.
