### ISSUE TITLE
bug: rollup's 'external' option is not supported in stencil.config

### ISSUE THREAD

**Issue by awk** [ionic-team/stencil#3226]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.13.0

### Current Behavior

Rollup provides an option to supply a value for `external` (a string, regex, array of either or a function) - https://rollupjs.org/guide/en/#external However stencil does not support this option in the rollupConfig.inputOptions section of a stencil.config

### Expected Behavior

With an external option specified the matching packages would be excluded from the output bundle (per rollups default behavior)

### Steps to Reproduce

Add
```
rollupConfig: {
    inputOptions: {
      external: /foo*/,
    }
  },
```
to a stencil.config.ts in a new project and observe that the option is flagged as an error by typescript and that it has no impact on the generated bundle files.

### Code Reproduction URL

-

### Additional Information

There is commentary about supporting this rollup option in https://github.com/ionic-team/stencil/issues/1938  - but that issue is now stale and only contributors can comment.

**Comment by rwaskiewicz** [comment]
Thanks for this issue report! I see the accompanying both for the team to take a look at both a little more closely.

**Comment by tanner-reits** [comment]
A fix for this was included in today's [v4.19.0 release](https://github.com/ionic-team/stencil/releases/tag/v4.19.0)!

**Comment by tanner-reits** [comment]
A fix for this was included in today's [v4.19.0 release](https://github.com/ionic-team/stencil/releases/tag/v4.19.0)!

**Comment by dantman** [comment]
I tried using `rollupConfig.inputOptions.external` to mark some dependences that must not be included in the library bundle as external. It works in the library. However when running with `--serve` the Integrated Dev Server has a `TypeError: Failed to resolve module specifier "{the module}". Relative references must start with either "/", "./", or "../". undefined` error for anything marked as external.

It seems we may need some way to ensure things marked as external are bundled for the Integrated Dev Server?

**Comment by christian-bromann** [comment]
@dantman thanks for reporting, is there a chance you can provide a reproducible example?

**Comment by dantman** [comment]
> @dantman thanks for reporting, is there a chance you can provide a reproducible example?

I'm not sure, I may have finished that project and I didn't usually work with Stencil. I can say that the project was using multiple output targets. www output for a demo component, web components, es5, and react if I recall correctly. It used various dependencies and the web component build would end up bundling them into the library. And there was a stateful module that would end up duplicated breaking things. Externalizing dependencies would fix the issue in the web component build but break the demo component in --serve.

**Comment by christian-bromann** [comment]
Thanks. If anyone comes across the same issue, please feel free to raise an issue with a reproduction case. At this point I cam't do further investigations on this.
