### ISSUE TITLE
bug:  unable to load js bundle remotely

### ISSUE THREAD

**Issue by Elvis116** [ionic-team/stencil#3238]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.11.0

### Current Behavior

I'm trying to load a remote bundle created by stencil/react to my host application. It failed to load the content when I imported defineCustomElements from NAMESPACE/loader in the remote application. If I commented it in remote and call defineCustomElements() in the host application, it is working fine.

### Expected Behavior

The host application can load the remote application even if defineCustomElements() was called in remote application.

### Steps to Reproduce

no

### Code Reproduction URL

https://github.com/no

### Additional Information

Normally after the remote js bundle was loaded in the host application, a global namespace would be registered in window object. But with defineCustomElements in remote application, the global namespace failed to register. I'd like to know the reason this function stopped the registeration. Thanks.

**Comment by rwaskiewicz** [comment]
Hi @Elvis116,

Thank you for the issue report.  Can you please include a github reproduction URL for us to take a look at? This helps the team narrow down on the exact issue.  

Thanks!

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
