### ISSUE TITLE
bug: Adding style tag via component does not work as expected

### ISSUE THREAD

**Issue by raspyweather** [ionic-team/stencil#3245]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.14.0

### Current Behavior

While it is technically possible to include style Tags in JSX, it is not reliably possible to use those together with stencilJS. Components which do so in a static manner, keep the desired/expected behavior while dynamic evaulated Styles don't get applied reliably.

### Expected Behavior

No matter whether `<style>` is added in a dynamic or static manner should it behave similar.

This behavior can be useful to implement e.g. Dialog/Overlays to disable scrolling in background without direct coupling to document.

### Steps to Reproduce

1. Create two components (both `shadow:false, scoped: false`)
``` TSX
  render() {
    return (
      <Host>
        <h3>DynamicFoo</h3>
        <style>{"body{overflow-x: hidden;}"}</style>
        <slot></slot>
      </Host>
    );
  }
```

``` TSX
  render() {
    return (
      <Host>
        <h3>StaticFoo</h3>
        {this.shouldApplyStyle && (<style>{"body{overflow-y: hidden;}"}</style>)}
        <slot></slot>
      </Host>
    );
  }
```
2. Add both components to `index.html`
3. See Static style applied, dynamic one inserted without effect

(see Repro Repo, run `npm run start ` to see the issue with only static style being applied)

### Code Reproduction URL

https://github.com/raspyweather/stencil-issues

**Comment by christian-bromann** [comment]
It is not recommended to inject styles like this. Stencil's scope is within the component level and doesn't go out further, e.g. managing `style` tags outside of the component. I think generally this would be not an ideal approach to solve this. What I would recommend is to set an attribute to the `<html />` tag that allows to trigger this style being enabled, e.g.:

```ts
if (this.shouldApplyStyle) {
  document.body.parentElement.setAttribute('data-background-behavior', 'yOverflowHidden')
```
then define a style like this:

```css
html[data-background-behavior="yOverflowHidden"] body {
  overflow-y: hidden;
}
```

Let me know if you have any further questions!
