### ISSUE TITLE
bug: Cannot import enum - Rollup: Missing Export

### ISSUE THREAD

**Issue by stevenbriscoeca** [ionic-team/stencil#3258]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

"@stencil/core": "^2.13.0"

### Current Behavior

When I import an enum from @duetds which is a stencil based open source component library I get this error : 

[ ERROR ]  Rollup: Missing Export: ./src/components/my-component/my-component.tsx:4:9
           'DaysOfWeek' is not exported by

![image](https://user-images.githubusercontent.com/3018441/156059879-1bf64499-7845-4e91-aa01-80ae0be9a48d.png)

### Expected Behavior

I expect to use the enum without an error from rollup : 
return <div>Hello, World! I'm {this.getText()} **{DaysOfWeek.Friday}**</div>;

### Steps to Reproduce

1. import { DaysOfWeek } from '@duetds/date-picker/dist/types/components/duet-date-picker/date-utils';
2. use {DaysOfWeek.Friday} in the jsx

### Code Reproduction URL

https://github.com/stevenbriscoeca/stencil-enum-bug

### Additional Information
There is a stackoverflow issue pretty similar to my question  here that doesn't have an answer and although when I was searching issues, I saw the same error reported, not exactly the same as my bug. 
https://stackoverflow.com/q/68310447/1646514

**Comment by rwaskiewicz** [comment]
Hey @stevenbriscoeca 👋 

Does Duet export a concrete implementation of `DaysOfWeek`? Looking through the distributable that's installed in the reproduction URL, I only see an [ambient declaration](https://www.typescriptlang.org/docs/handbook/enums.html#ambient-enums):

![Screen Shot 2022-03-07 at 9 30 13 AM](https://user-images.githubusercontent.com/1930213/157053425-c1b08bd1-8e98-498b-9637-01ae260b738b.png)

**Comment by stevenbriscoeca** [comment]
Hey @rwaskiewicz ! 

Thanks for taking the time, I really appreciate it. I don't think so either. 

Could you let me know what do you mean as a "concrete" implementation. 

I was just using that library as an example, if you have a library that works perfectly with stencil, I could test out importing the enums in the repo.

Thanks again! 👋🏻

**Comment by rwaskiewicz** [comment]
> I was just using that library as an example, if you have a library that works perfectly with stencil, I could test out importing the enums in the repo.

Ah, I see. I used the term 'concrete' to differentiate it from an ambient declaration.  In an ambient declaration (specifically the one in the example above), we don't have an actual implementation created by TypeScript. The screenshot of [this playground link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEIB2BXAtvAIlAngZwHkAzAdRBAGsBBNAIwEtkAXeAbwCh4v4BlFJYLngBeeAAYANJ24BZAPYChogIxTu8ACooQeQThHwATGu5lgSHXoMBmE1w0ALGCl1L4AFjvwAYjHpXRAFYvHigmFBgA+AA2KQBfdnZkdCxcQlJyCgBhBTA4JgQOdT5FfVFJaS55UoNVSs1tVzKjLzMLJpsvR2cO0U963383YPrQ8Mi3WPY4oA) shows that when we have an ambient enum declaration (denoted by the `declare` keyword, there's no actual JS emitted (for `DaysOfWeekAmbient`:

![Screen Shot 2022-03-09 at 2 01 54 PM](https://user-images.githubusercontent.com/1930213/157547212-761fc4b3-9638-4967-99fd-e9bbc33d06dc.png)

However, there is JS (or a 'concrete') implementation emitted for the non ambient version, `DaysOfWeekConcrete` (note the lack of the `declare` keyword.

I think we can test this with a small library we build out ourselves - in an empty directory, I did the following:
- `npm init -y` to create an empty project
- `tsc --init` to initialize a TypeScript project
- Created `index.ts` with the following text:
```typescript
enum DaysOfWeek {
  Sunday,
  Saturday,
}

export {DaysOfWeek};
```
- Compiled the code with `tsc index.ts`, which generated the following JS in `index.js`:
```
"use strict";
exports.__esModule = true;
exports.DaysOfWeek = void 0;
var DaysOfWeek;
(function (DaysOfWeek) {
    DaysOfWeek[DaysOfWeek["Sunday"] = 0] = "Sunday";
    DaysOfWeek[DaysOfWeek["Saturday"] = 1] = "Saturday";
})(DaysOfWeek || (DaysOfWeek = {}));
exports.DaysOfWeek = DaysOfWeek;
```
- Created a tarball of the project by running `npm pack`, which generated a `.tgz` file in my directory.

You could then install this in your reproduction case, and verify importing works with the following `my-component.tsx` content (be sure to `npm i the_path_to_that_tgz_file` first):

```tsx
import { Component, h } from '@stencil/core';
import {DaysOfWeek} from 'your_package_name';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true,
})
export class MyComponent {

  render() {
    console.log(DaysOfWeek.Saturday)
    return <div>Hello, World! I'm Ryan</div>;
  }
}

```

Can you give that a go and see if it solves your problem? (or at least if that replicates the issue?)

**Comment by stevenbriscoeca** [comment]
Wow! Thank you so much for the reply so detailed. My apologies for not answering earlier.

It seems like this is working. I was wondering in the context of stencil, how would we export the ts files to js files as this seems like part of the solution for it to work, am I correct?

So for example, if in my-component I have :

./src/components/my-component/my-component.model.ts

in this file I have something like this : 
```ts
enum myComponentTypeEnum {
  INFORMATION = 'information',
  CONFIRMATION = 'confirmation',
  WARNING = 'warning',
  ERROR = 'error',
  INACTIVE = 'inactive',
  CRITICAL = 'critical',
}
export { myComponentTypeEnum };
```
I want this enum to be available for other devs. 

For context, I am producing a design system where developpers from my company consumes our components. I want them to have these enums available for them when they are using our components in their stencil app, angular, react app, etc.

how would I config stencil to say : take this ts file and generate also a js file. 

do I have to do it custom or am I missing something?

Thank you so much 👍🏻

**Comment by rwaskiewicz** [comment]
Hey @stevenbriscoeca, I'm glad that helped! 

Without knowing too much about the organization of your design system/component library, one possible way to go about this would be to re-export `myComponentTypeEnum` from your project's `index.ts` file.  

Normally, these types of questions are best suited to the [#technical-questions in the Stencil Slack](https://stencil-worldwide.slack.com/archives/C79EANFL7), where community members help each other out with types of questions like these.  

I'm going to close this issue out, but feel free to open a new one if needed. Thanks again!

**Comment by nbrugger-tgm** [comment]
Hello @rwaskiewicz i have been sitting on this bug in my project for longer than i am willing to admit.

Is there an explanation why it only works when packing the dependency?

Assuming the folder structure
```
root
|--- library
|    |--- src
|    |--- dist
|    |--- package.json, tsconfig, .....
|    |--- library-version.tgz
|
|--- app
      |--- src
      |--- package.json, tsconfig, .....
```

When i depend on "library" like this (`app/package.json`) 
1. `"deploy-api-client": "file:./../library"` It fails with the so often stated `"SomeTsEnum" is not exported by "../library/dist/index.js", imported by "src/lib/components/SomeComponent.svelte"`
2. `"deploy-api-client": "file:../library/library-1.0.0-SNAPSHOT.tgz"`: It works at compile time **and** at runtime!

It might not be a good idea to post on github after 2 days of straight debugging for how to get a library working but:
_**why?? the f*****_

On a more constructive note: Where do i find documentation about it?

**Comment by rwaskiewicz** [comment]
@nbrugger-tgm I'm not sure. If you can create a minimal reproduction case for us and open a new issue, someone can certainly take a look

**Comment by nbrugger-tgm** [comment]
Well, for the "what am i trying to accomplish"

I have a monorepo, in this repo i have a shared library (`root/library`) in the structure above and i am trying to use it as a dependency in the  (browser) app `root/app`. This shouldn't be such an exotic use case imo.

Regarding the "what's failing": `npm run buil` which is "just" a `vite build`

>  If you can create a minimal reproduction case 
I would love to, but I have very little knowledge about roll-up and even less so if "wrapped" by vite and even less when mangled with by SvelteKit. If a reproducer with sveltekit+vite+rollup (from a sveltekit degit/init) is OK, then I can provide one. But there is no way that I manage to create a reproducer from scratch

**Comment by rwaskiewicz** [comment]
@nbrugger-tgm For a minimal reproduction case, we often ask folks to spin up a minimal reproduction case with the Create-Stencil CLI (`npm init stencil@latest component`). If you're able to determine if that issue you're seeing can be replicated in a simplified way, that would be ideal (I.E. Answering the question "Does this only happen with Sveltekit, or can we reproduce this if we try to import it in a TypeScript project?").  

If not, we may still be able to take a look - with the caveat that we're likely to be a little slower to respond/ask you to do a little more work to minimize the reproduction case. 

If that sounds amenable to you, I encourage you to open a new issue. Moving forward, let's move this conversation there in order to stop notifying other watchers of this issue 🙂
