### ISSUE TITLE
Integrate PostCSS

### ISSUE THREAD

**Issue by equinusocio** [ionic-team/stencil#326]
**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Other information:**
Hi, here we need to drop sass and switch to PostCSS, is there a way to integrate and configurate it with stencil?

**Comment by manucorporat** [comment]
Related: https://github.com/ionic-team/stencil/issues/285

**Comment by jgw96** [comment]
Hello all! Going to close this as a duplicate of #285 as that would be necessary for this to work. Thanks for using Stencil!
