### ISSUE TITLE
index.js file is empty in dist > collection folder

### ISSUE THREAD

**Issue by mu250234** [ionic-team/stencil#327]
background : I want develop a common UI libarary that contains stencils webcomponents as well as some Utils .
I have started with stencils starter, and able to develop webcomponents . but not able to export utils . any ideas ?
my index.ts is :
export function foo() { }

But after "npm run build" , dist > collection > index.js and index.d.ts has no contents . sothat I am not able to export my Utils .

**Comment by jgw96** [comment]
Hey! Would you be able to provide a demo repo? Thanks!

**Comment by mu250234** [comment]
Hi ,Thanks for your response mate . here is
"https://github.com/mu250234/commomUI "
my git repo

**Comment by rolandjitsu** [comment]
I am actually experiencing the same issue. Both `index.js` and `index.d.ts` files are empty.

My `stencil.config.js` file:
```js
exports.config = {
    namespace: 'bbpviz',
    generateDistribution: true,
    bundles: [
        {components: ['bbpviz-transfer-function']}
    ]
};

exports.devServer = {
    root: 'www',
    watchGlob: '**/**'
}
```

And everything else (besides the name of the component) is the same as the stencil component starter.

**Comment by jthoms1** [comment]
@rolandjitsu Can you provide what version of stencil you are using? `npx stencil -v`

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
