### ISSUE TITLE
bug: stencil 2.14.1 skips e2e.ts files

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/stencil#3275]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.14.1

### Current Behavior

In Stencil 2.14.1, any test named "e2e.ts" no longer runs. Previously this worked in Stencil 2.14.0 and older.

### Expected Behavior

I would expect test files like `e2e.ts` to run.

### Steps to Reproduce

1. Clone https://github.com/ionic-team/ionic-framework
2. In `core`, run `npm install`.
3. Run `npm run test src/components/modal/test/basic`. Observe that no tests are run even though there is an `e2e.ts` file in there.

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework

**Comment by rwaskiewicz** [comment]
Thanks for this report! This issue has been fixed in Stencil [v2.14.2](https://github.com/ionic-team/stencil/releases/tag/v2.14.2), and as a result I'm going to close this issue. Thanks again!
