### ISSUE TITLE
feat: Custom HTMLElement type for event targets

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/stencil#3291]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Export additional type data on the generated component interfaces, that allows developers to have typings for the event target with custom events.

i.e.:
```ts
"onIonInfinite"?: (event: CustomEvent<void> & { target: HTMLIonInfiniteScrollElement }) => void;
```

Usage:
```ts
<ion-infinite onIonInfinite={ev => ev.target.complete()} />
```

The `ev.target` would allow accessing all the public methods available on the host element. 

Additionally it would be valuable to export the custom event type as an interface for each event, so that development eco-systems like Angular can access the reusable type:

```ts
handleInfiniteScroll(ev: InfiniteScrollEvent<void>) {
  ev.target.complete();
}
```

### Describe the Use Case

When the event is emitted, it already contains information around the `target`, but does not include any type information in the generated types. This is problematic because developers have to re-cast or use `any` for event handlers. 

Ideally, developers would like to directly access the correct typings the event target, without having to recast:

```ts
<ion-infinite onIonInfinite={ev => ev.target.complete()} />
```

### Describe Preferred Solution

There are two changes that are necessary to support this (from the generated output).

1. Each custom event will need a type that includes a reference to the `HTMLElement`, such as:
```ts
"onIonInfinite"?: (event: CustomEvent<void> & { target: HTMLIonInfiniteScrollElement }) => void;
```
2. Ideally this event type is not inlined and rather a generated public type that is consumed for this type, but available to implementers:
```ts
"onIonInfinite"?: InfiniteScrollEvent<void>;
```

```ts
export type InfiniteScrollEvent = <T=any>(event: CustomEvent<T> & { target: HTMLIonInfiniteScrollElement }) => void;
```

### Related Code

I have the first case outlined above handled with this:
```ts
export const generateEventTypes = (cmpEvents: d.ComponentCompilerEvent[], cmpHtmlElementInterface: string): d.TypeInfo => {
  return cmpEvents.map((cmpEvent) => {
    const name = `on${toTitleCase(cmpEvent.name)}`;
    const targetType = `{ target: ${cmpHtmlElementInterface} }`;
    const type = cmpEvent.complexType.original
      ? `(event: CustomEvent<${cmpEvent.complexType.original}> & ${targetType}) => void`
      : `CustomEvent & ${targetType}`;
    return {
      name,
      type,
      optional: false,
      required: false,
      internal: cmpEvent.internal,
      jsdoc: getTextDocs(cmpEvent.docs),
    };
  });
};
```

I will investigate the work effort of the second item.

### Additional Information

Related issues: 

Framework:
- Angular issue: https://github.com/ionic-team/ionic-framework/issues/24245
- React issue: https://github.com/ionic-team/ionic-framework/issues/24952

Stencil output targets:
- https://github.com/ionic-team/stencil-ds-output-targets/issues/219

**Comment by rwaskiewicz** [comment]
I'm going to close this issue, as the related-PR (#3296) is a part of today's Stencil v2.16.0 release.  Thanks again!
