### ISSUE TITLE
bug:  element doesn't work when created document.createElement

### ISSUE THREAD

**Issue by ridvandmrc** [ionic-team/stencil#3320]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.13.0

### Current Behavior

Hi All,
 I am using [custom-element-exporting](https://stenciljs.com/docs/custom-elements) but some our components have dependency and due to some reason we have to use dependency with` document.createElement('depencey-tag')`. 

then I used this component some framework (Angular, React ....)., dependencies components is not working as expected
sample code snipped here:
```
<my-button>
    <Host onClick={()=> {
       const chip = document.createElement('my-chip'); 
        document.body.appendChild(chip) }) >

         ... some code ...
      </Host>
</my-button>
```

How can I declerate dependency when using custom element dependency?

### Expected Behavior

dependency component should added DOM correctly.

### Steps to Reproduce

* crate two component that names (first-component, second-component)
* use `document.createElement('second-componentn)` in first-component

### Code Reproduction URL

#

**Comment by rwaskiewicz** [comment]
This issue is being closed due to the lack of a minimal code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!
