### ISSUE TITLE
bug: jest defaults are overriding passed args.

### ISSUE THREAD

**Issue by George-Payne** [ionic-team/stencil#3328]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

12.15.0

### Current Behavior

Command line flags passed to `stencil test` are being overridden by the stencil defaults.

Running `stencil test --spec --passWithNoTests` will log out the correct arguments:
```
[35:48.6]  @stencil/core
[35:48.8]  v2.15.0 ⛷
[35:48.9]  testing spec files
[35:48.9]  jest args: --passWithNoTests --spec --max-workers=8
```

But then fail with: 

```
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
```

You can see the override happening on line:
https://github.com/ionic-team/stencil/blame/main/src/testing/jest/jest-config.ts#L62

And if we add some logs, we can see the passed flag being overridden:

![image](https://user-images.githubusercontent.com/11861797/163181205-dbc590de-cc26-46c6-8c46-2b13db3e745a.png)

### Expected Behavior

Defaults should be the default, and not override the passed flags

### Steps to Reproduce

In a stencil repo with no tests, run `stencil test --spec --passWithNoTests` and observe failure.

or see `overridden-test-flags` branch in repo: https://github.com/George-Payne/stencil-custom-target-example/tree/overridden-test-flags

### Code Reproduction URL

https://github.com/George-Payne/stencil-custom-target-example/tree/overridden-test-flags

**Comment by rwaskiewicz** [comment]
The fix for this issue has been released as a part of [Stencil v2.15.1](https://github.com/ionic-team/stencil/releases/tag/v2.15.1). As a result I'm going to close this issue. Thanks again for your help with this!
