### ISSUE TITLE
bug: unable to externalize modules using stencil config

### ISSUE THREAD

**Issue by selodev** [ionic-team/stencil#3336]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.15.0

### Current Behavior

We are not able to externalize or share NPM modules between projects because the external option has been removed in the stenciljs config. Why would you even lock down stencil js config ? We would like that stencil.config.ts to be fully unopinionated so that developer or the consumer of stencil js can have full control over both stencil js and rollup config. We are a huge company wanting to use stencil js but not being able to extend the current stencil js config options is a huge bottleneck. We would like at least the external option in the output targets be enabled again.

Best regards,
Any feedback is greatly appreciated.

### Expected Behavior

We should be able to externalize npm modules `by using external and globals options for rollup config in stencil js config.

### Steps to Reproduce

```
export const config = {
  namespace: 'my-component',
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader',
      external: ["moment"]
    },
    {
      type: 'dist-custom-elements',
      external: ["moment"]
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
      external: ["moment"]
    },
  ],
  rollupPlugins: {
    before: [
      {
        name: 'externalize-dependency',
        resolveId(source) {
          if (source === 'moment') {
            return { id: 'moment', external: true };
          }
          return null;
        },
      },
    ]
  },
  rollupConfig: { outputOptions: { globals: { moment: 'moment' } } },
};
```

### Code Reproduction URL

n/a

### Additional Information

We are not able to externalize or share npm modules at all.

**Comment by rwaskiewicz** [comment]
Hey @selodev 👋 

Would #3227 address your desire to externalize dependencies? It adds the `external` option to the Stencil configuration file (via the `rollupConfig` field)

**Comment by selodev** [comment]
@rwaskiewicz yes that would be great. thank you.

**Comment by selodev** [comment]
I just want to say that Ionic Team has done a great job with Stencil JS bundling and all the rest of the features. It is just also good to be able to customize and extend existing bundling features, I can go ahead and close this bug. Please let me know.

**Comment by rwaskiewicz** [comment]
@selodev Thanks! If you wouldn't mind, I think closing this issue would be appropriate. We have it linked to Issue 3227 now, so we have the context & details that you provided associated with the PR should we need them

Thanks again!
