### ISSUE TITLE
Slotted Scope

### ISSUE THREAD

**Issue by bmidget** [ionic-team/stencil#334]
**I'm submitting a:**

- [x] feature request

**Current behavior:**
Currently slots only function as pre-rendered templates passed into the child.

**Expected behavior:**
Scoped slots (like Vuejs scoped slots) allow powerful templating inside components necessary for reusable components that allow custom templates to be used in the component.

Even, say, a basic list component requires this functionality.

Here is a simple example:

```
<my-awesome-list items="items">
  <li
    slot-scope="props"
    class="my-fancy-class">
    {props.text}
  </li>
</my-awesome-list> 
```

And the template for the list component, something like this:
```
<ul>
  {this.items.map( (item) => 
    <slot text="{item.text}"></slot>
  )}
</ul>
```

Other frameworks allow this. I'm personally familiar with the Vuejs implementation which is excellent. (https://vuejs.org/v2/guide/components.html#Scoped-Slots).

**Comment by adamdbradley** [comment]
Definitely a good feature, but at this time we're going to limit the API footprint in order to keep stencil small and focused. We'll revisit this later if it becomes a large issue. Thanks

**Comment by amazzoccone** [comment]
Good suggestion @bmidget ! I understand the goal of Stencil, and really don't know the performance impact of this feature, but it would be great. I used in VueJS sometimes.
For example, we could replicate `Apollo GraphQL` query as React does:
```
<Query query={gql`...`}>
    {({ loading, error, data }) => {
      ...
    }}
</Query>
```

**Comment by liho98** [comment]
This feature is really useful. For example, I created a drop-down menu component.With slotted scoped, I am able to obtain the visible value of the drop-down menu. So, with the value, I can easily customize the drop-down button slot (such as an arrow indicator).

Without slotted scope, it will be difficult for web component developers to customize the layout of the drop-down buttons and its contents.

Hope that this function can be realized in the stenciljs.

**Comment by wallid** [comment]
I'm trying to do a similar concept with tables - the design system will allow the user to dedicate how the data is represented in each row.

**Comment by runarberg** [comment]
@liho98 You can take advantage of dynamic slots to build a custom element. In a nutshell:

* You listen for the slot change event.
* See how many of the nested structure components are in the slot.
* Add equally many named and enumerated slots inside the structure you prefer (e.g. `<li><slot name={`item-${i}`}></slot></li>).
* Rename the slot attribute on the assigned nodes to match this enumeration.

I wrote a [tutorial about this technique](https://dev.to/runarberg/my-menu-a-more-involved-stencil-component-k7a).

However this technique will not scale for deeply nested structure, e.g. `<table>`.
