### ISSUE TITLE
Transpile browser-specific CSS

### ISSUE THREAD

**Issue by TravisFolck** [ionic-team/stencil#335]
**Stencil version:**

```
 @stencil/core@0.0.8-6
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

Please provide the ability to configure SCSS to transpile browser-specific CSS . For example, -moz -webkit -o, etc.

**Comment by obedm503** [comment]
sass doesn't do that, you would need to use something like [autoprefixer](https://github.com/postcss/autoprefixer) on the css output

**Comment by jgw96** [comment]
Hey! At this time we do not include autoprefixer by default in Stencil as it would bloat the built css, but we have talked about including it as either a config option or turned on by default.

**Comment by adamdbradley** [comment]
We'll soon be creating a `@stencil/autoprefixer` plugin that can be added to `config.plugins`.

**Comment by adamdbradley** [comment]
As of 0.6.0-0 you can now use autoprefixer as a plugin: https://www.npmjs.com/package/@stencil/postcss
