### ISSUE TITLE
feat: defineCustomElements() always uses `sty-id` styles (if they exist), even for non-scoped components (shadow: true)

### ISSUE THREAD

**Issue by mayerraphael** [ionic-team/stencil#3352]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently, if i use the `hydrate` script for SSR in NextJS and use the `esm` dist for the frontend part and the call to `defineCustomElements`, the CSS of the components also used for SSR gets broken. 

This is because `hydrate` `scopes` the css classes and puts them into `<style>` elements in the `<head>` part. Later they are reused but not `de-scoped`. 

It would be nice if an easy way to rehydrate the server-side rendered components exists.

I'm not quite sure if this is a bug or i am or stencil is missing something.

## How its used

The problem is the following:
- `hydrate.renderToString()` on the server adds a `<style sty-id="sc-my-component-name">` to the `<head>`
- Calling `defineCustomElements` in the frontend loads those `styles` used for SSR (and have scoped css class names) for the frontend components (rehydration). This ofc results that the component styles are broken, because the `esm` component expects other css classes.
- Only if i remove all `style[sty-id]` elements, rehydration of the stencil components results in correct css classes.

`de-scoping` means:
- `sc-my-component-h` becomes `:host` again.
- `button.sc-my-component` becomes `button` again.
- and so on

## Technical digging

In `bootstrapLazy()`, the `<style>` elements from `hydrate` are loaded.
![image](https://user-images.githubusercontent.com/25869389/166464150-60e36a7a-bf78-421d-a28e-fcb75ecb0849.png)

In `initializeComponent()`, styles from the Constructor Object are only added if not already a `<style[sty-id]>` exists with the same `scopeId`:

```js
if (Cstr.style) {
            // this component has styles but we haven't registered them yet
            let style = Cstr.style;
            const scopeId = getScopeId(cmpMeta); // sc-my-component

           // <style sty-id="sc-my-component"></style> exists because of `hydrate`. 
           // The style of the component itself is not registered, but the <style> created by hydrate is re-used, with the wrong scoped css class names.
            if (!styles.has(scopeId)) { 
                const endRegisterStyles = createTime('registerStyles', cmpMeta.$tagName$);
                if (cmpMeta.$flags$ & 8 /* needsShadowDomShim */) {
                    style = await import('./shadow-css-dfa0587f.js').then((m) => m.scopeCss(style, scopeId, false));
                }
                registerStyle(scopeId, style, !!(cmpMeta.$flags$ & 1 /* shadowDomEncapsulation */));
                endRegisterStyles();
            }
        }
```

So if `hydrate` adds a `style` for the component, this means the scoped styles are used instead of the correct styles at the component object.

I have found the `convertScopedToShadow()` method, but this does not seem to de-scope the css classes.

### Describe Preferred Solution

- `defineCustomElements` does `de-scope` the css classes inside the `<style[sty-id] >` tags when loading
- `defineCustomElements` has a parameter which allows me to ignore those <style> elements and always uses the styles of the component object `Cstr.style`.
- `defineCustomElements`, if not required for SSR, should ignore the `<style[sty-id]>` elements and always use the ones provided with the object inself (`Cstr.style`)

**Comment by mayerraphael** [comment]
I've checked further cases:

- Adding `scoped: true` to a component also adds a `<style></style>` element to the head and creates the same naming conventions as the `hydrate` package, but the `style` element does not contain a `sty-id` attribute.

This would mean that the styles provided with the hydrate package can only work if all my components would also have `scoped: true`. But they are `shadow: true`. Why is `defineCustomElements()` always `sty-id` styles even though none of my components is scoped?

My recommendation would be that somehow the generated package checks or holds the information if my component is `scoped` or `shadow`. 

`scoped` -> check for existing `style[sty-id]` -> use if exists, otherwise use style of the constructed component object
`shadow` -> always use styles of the constructed component object.

The more i look at it, the more it looks like if i use `hydrate`, you guys expected that all components use `scoped` so they will still work with the generated `dist` package?

**Comment by mayerraphael** [comment]
I've created a new project and the problem does not appear anymore. So it must be a problem with my project. Closed.

**Comment by mayerraphael** [comment]
I've created a new project and the problem does not appear anymore. So it must be a problem with my project. Closed.

**Comment by leopuleo** [comment]
Hi @mayerraphael,
we are experiencing a similar issue...do you have any idea how you solved it with the new project?

🙏

**Comment by mayerraphael** [comment]
> Hi @mayerraphael, we are experiencing a similar issue...do you have any idea how you solved it with the new project?
> 
> 🙏

We had a Tailwind plugin configured to remove css comments. Stencil requires those css comments to correctly map between scoped and non-scoped css class names.
