### ISSUE TITLE
How to add plugins such as styled-jsx?

### ISSUE THREAD

**Issue by kristianmandrup** [ionic-team/stencil#336]
Would it be possible to add something like [styled jsx](https://github.com/zeit/styled-jsx) ?
I guess not, since the stencil compilation engine is not yet designed to be pluggable?

**Comment by jthoms1** [comment]
We don't have a system for this right now, but we are having some internal discussions on the appropriate way to implement.  I hope to have a path forward on this in January.

**Comment by jgw96** [comment]
Hello! I am going to close this issue as a duplicate of https://github.com/ionic-team/stencil/issues/285 as that issue will also resolve this feature. Thanks for using Stencil!
