### ISSUE TITLE
How can I delete a component created via "generate"

### ISSUE THREAD

**Issue by prakashraman** [ionic-team/stencil#3361]
Let's say, I created a component 

```
npx stencil generate first-component
```

What is the proposed/suggested way if I liked to 

1. Delete the component (and all its references) all together
2. Rename the component
3. Move the component to a different path

And, is there the CLI API reference for the "stencil" command?

Thanks, and I love the tool!

**Comment by rwaskiewicz** [comment]
Hey @prakashraman 👋 

The CLI reference can [be found here on our doc site](https://stenciljs.com/docs/cli#command-line-interface-cli)

For your other questions, I'd encourage you to check out the [#technical questions channel in the Stencil Slack](https://stencil-worldwide.slack.com/archives/C79EANFL7).  It's a great place to get answers to questions such as best ways to delete, rename and move a component.

I'm going to close this issue, but please feel free to open a new one if you determine there's a bug in the stencil CLI. Thanks again for using Stencil!
