### ISSUE TITLE
bug: unable to import linked module/component using Angular demo

### ISSUE THREAD

**Issue by gnesher** [ionic-team/stencil#3362]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.13.0

### Current Behavior

Following the https://stenciljs.com/docs/angular guide, I've created a blank Angular workspace with a component library and linked it to the stencil component that comes from a new install.

I've then created a new demo application within the Angular workspace and tried to import the shared component, resulting in a run time error:
```
ERROR Error: NG0203: inject() must be called from an injection context
```

Using the same process (Angular workspace with a shared library and a demo application) without linking to the stencil library works fine - which I assume means there's a specific problem with the link/documentation.

### Expected Behavior

Demo application should be able to load/display the demo component

### Steps to Reproduce

Follow instructions in https://stenciljs.com/docs/angular then create a new demo application within the Angular workspace and try to import the module/component. Error happens at runtime 

### Code Reproduction URL

https://github.com/gnesher/angular-stencil-error

### Additional Information

Using Angular 13.3

**Comment by tfrijsewijk** [comment]
I'm experiencing the same issue, did you ever sort this out?

**Comment by SepehrSepahi** [comment]
The same here.

Stencil 2.13.0
Angular 14.2.0

**Comment by jvlobo** [comment]
I'm also getting this same error.
Was anyone able to solve it?

@gnesher you closed the issue, did you solve it?

Thanks.

**Comment by Grimm1994** [comment]
The same issue

**Comment by awaisocchealth** [comment]
I am having the same issue. Issue has been closed without fix?

**Comment by Grimm1994** [comment]
Can you please update the documentation for Angular integration, because it's weird that the Stencil universal library doesn't work properly for one of the most used js framework (at least from what I tried from the [documentation](https://stenciljs.com/docs/angular))

**Comment by TiagoFuelber** [comment]
Has anyone solved this issue? 
I am having the same issue.
Stencil: 3.3.0
Angular: 16.1.0

**Comment by jakemer** [comment]
@gnesher Was this fixed? The issue has been reported several more times since this was closed and I don't see a pull request for the fix. It has been over a year, maybe a new issue should be opened

**Comment by grantwforsythe** [comment]
I running into the same problem with Angular v17.0.0 and Stencil v4.7.0. To reproduce, just follow the example provided in the official Stencil [documentation](https://stenciljs.com/docs/angular). I have tried importing the wrapper module into an application within the same workspace and in a different workspace.

@gnesher are you able to reopen this issue as there isn't a solution?

**Comment by tfrijsewijk** [comment]
@rwaskiewicz could you chip in? I experienced this error yesterday. After a quick google I found this issue with [this](https://github.com/ionic-team/stencil/issues/3362#issuecomment-1158973391) comment 😄
