### ISSUE TITLE
Polyfill order (IE bug)

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#337]
**Stencil version:**

```
 @stencil/core@0.0.8-7
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

The template polyfill is not fully applied to `<template>` elements created on the fly (like [those used for styling](https://github.com/ionic-team/stencil/blob/7fe897bd0f02bba6729beb9aa9f8cd8f7b7df500/src/client/platform-client.ts#L191) components). This throws the dreaded `Unable to get property 'cloneNode' of undefined or null reference ` error.

**Expected behavior:**

IE stops being so "special" and actually works correctly without errors. Most of this is out of your hands but there is something to be done to allow `<template>`s to function properly.

**Other information:**

The issue stems from how each polyfill decided to apply functionality that is not available out-of-the-box. The order in which they are run seems to matter in this case. 

- **document-register-element.js** [modifies certain functionality](https://github.com/WebReflection/document-register-element/blob/2ed9c8fa9fbdd587c13fb09c4846bce7fbab7bd9/src/document-register-element.js#L216) by aliasing and replacing  `document` functions. 
- **template.js** modifies [some of the same functionality](https://github.com/webcomponents/template/blob/27b55d7f93d623a33d12a82ffd9f166a43e6a5a9/template.js#L124) but aliases and replaces `Document.prototype` functions instead. 

If the template polyfill runs _after_ the CE polyfill ([as it does right now](https://github.com/ionic-team/stencil/blob/37135c8d53cfbc730092b0879fa6f3df2c810cd4/src/compiler/app/app-core.ts#L79)), then the modifications of the Document.prototype are not applied through the CE polyfill because the template polyfill does not alias the **document** methods directly. This has the side-effect of the template "decorate" method only firing under certain DOM events/scenarios instead of every time a `<template>` is created.

Placing the template polyfill first alleviates the issue for the special snowflake that is IE11 because then the CE polyfill will reference the template polyfill as well.

Once again, I am sorry for bringing up IE issues. 😞  I can likely create a scenario if truly needed but the switch seems a simple fix.

**Comment by adamdbradley** [comment]
Gahh, every time I think we've got it IE gets me again! Sorry, my mistake, I should have tested more on IE11. Here's where the ordering is happening: https://github.com/ionic-team/stencil/blob/f113478be0c26e963a5a578a939a05d8b58e0605/src/compiler/app/app-core.ts#L79-L87

So you're saying if we put template above document-register it should be good? We'll make the updates and test some more on ie11, thanks!

cc @jgw96

**Comment by cary-smith** [comment]
@adamdbradley TBH I would avoid testing in IE11 personally but we support it (for now) plus this particular issue does not immediately show itself. Should anything be missed while you develop, we are still banging away at it since we support a sad browser 😄. 

From my local testing simply switching the order made all the difference because then `document-register-element.js` will pick up the modifications made by `template.js` via prototypal inheritance.

*Special Note* This library just keeps getting better. Thank you for solving so many issues for the rest of us developers.

**Comment by jgw96** [comment]
Hmm this is interesting! Did not see this on my last IE11 tests, but that admittedly was a couple of releases ago (were releasing so fast lately haha). Ill take a look. Thanks for opening this issue @cary-smith !
