### ISSUE TITLE
bug: stencil components not showing on cordova iOS 15.4

### ISSUE THREAD

**Issue by bluethunder626** [ionic-team/stencil#3371]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.15.2

### Current Behavior

Stencil component won't show using `cordova run ios` on simulator iOS 15.4.

Works using `cordova run browser`. Tested on both Google Chrome v101.0.4951.64 and Safari v15.4 (17613.1.17.1.13).

Works using `cordova run android`.

### Expected Behavior

Stencil components should work on cordova iOS app.

### Steps to Reproduce

I have created a base cordova and stencil app. https://github.com/bluethunder626/cordova-app

`blue-components` folder is the stencil components folder and the root folder is the cordova app.

I have put all the `build` from stencil on root `www/build` folder. `www/index.html` is also updated with the stencil build import.

 > stencil 2.15.2
 > cordova-ios 6.2.0
 > ios 15.4

1.  `npm install -g cordova`
2.  `cordova platform add ios`
3.  `cordova run ios`

### Code Reproduction URL

https://github.com/bluethunder626/cordova-app

### Additional Information

I have tried the following issues but didn't work for me:

https://github.com/ionic-team/stencil/issues/2392
https://github.com/ionic-team/stencil/issues/1900

**Comment by rwaskiewicz** [comment]
Hey @bluethunder626 👋 

Thanks for the detailed bug report and simple repro case! 

Can you help me out a little bit here? Can you provide any errors you see? If there aren't any, can you provide me with any debugging statements you've used? That should help us narrow this problem down. Thanks!

**Comment by bluethunder626** [comment]
Hi @rwaskiewicz ,

Thank you for the reply.

This is the error that I have encountered.
> file:///[.....]/HelloCordova.app/www/build/blue-components.esm.js
> Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin. Status code: 0

I have not used any debugging statements as of the moment.

**Comment by bluethunder626** [comment]
Hi @rwaskiewicz ,

This works now. Thank you for the help!
