### ISSUE TITLE
JsonDocsComponent's slots property is always an empty array in custom docs output target 

### ISSUE THREAD

**Issue by RobM-ADP** [ionic-team/stencil#3384]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.6.0

### Current Behavior

When created a custom output target, there is no access to the "slots" for a component despite the fact that the JsonDocsComponent interface exposes a property called `slots`

### Expected Behavior

I would expect the `slots` property to contain an array of slot names used within the component

### Steps to Reproduce

In stencil config:
```
 {
      type: 'docs-custom',
      generator: (docs: JsonDocs) => {
          docs.components.forEach(component => {
             console.log(component.slots.length);
          });
      }
  }
  ```    
  This will output `0` for every component regardless of how many slots a component uses.

### Code Reproduction URL

https://github.com/RobM-ADP/stencil-output-target-issue

**Comment by alicewriteswrongs** [comment]
Hey @RobM-ADP, thanks for reporting this and for providing a reproduction repo!

I was able to get slots documentation to show up by adding a `@slot` tag to a JSDoc comment on the component in your repro case, like so:

```diff

**Comment by alicewriteswrongs** [comment]
Hey @RobM-ADP, thanks for reporting this and for providing a reproduction repo!

I was able to get slots documentation to show up by adding a `@slot` tag to a JSDoc comment on the component in your repro case, like so:

```diff
diff --git a/src/components/my-component/my-component.tsx b/src/components/my-component/my-component.tsx
index 8c95773..f6db76b 100644
--- a/src/components/my-component/my-component.tsx
+++ b/src/components/my-component/my-component.tsx
@@ -1,6 +1,11 @@
 import { Component, Prop, h } from '@stencil/core';
 import { format } from '../../utils/utils';
 
+/**
+ * MyComponent
+ *
+ * @slot My Best slot ever!!!
+ */
 @Component({
   tag: 'my-component',
   styleUrl: 'my-component.css',
```

If you check out the [documentation for slots in the `docs-json` output target](https://stenciljs.com/docs/docs-json#slots) there's some further explanation of how this works.

Give that a try and and let us know if that works and we'll take it from there! We're also going to be looking at polishing up the document for this output target in the future.
