### ISSUE TITLE
feat: Support for @mixin, @function and @class annotations to document scss features using docs-readme

### ISSUE THREAD

**Issue by sandeeppatidar30** [ionic-team/stencil#3395]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Stencils compiler provides a nice support to document components features like props, events, methods, listeners etc. but does provide any way to document @mixin, @functions in readme.md using docs-readme output target. 

It would be good to get an in-built support to document scss features using docs-readme output target. 

### Describe the Use Case

I want to document scss features in README.md file using docs-readme.

**Comment by rwaskiewicz** [comment]
Hey @sandeeppatidar30 👋 

Can you do me a favor and include some examples (small code snippets would be perfect) of what you expect to write & what you'd expect Stencil to create as a result of the former?  I think I understand the feature request here, but want to make sure I fully understand 🙂
