### ISSUE TITLE
Problem importing njl07/rx-http-request

### ISSUE THREAD

**Issue by gdjennings** [ionic-team/stencil#340]
**Stencil version:**

```
 @stencil/core@0.0.8-8
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Wanted to encapsulate remote data in component but getting compiler errors. It seems to fail on every second build.
```
[ ERROR ]  typescript: .....tsx, line: 3
           Cannot find module '@akanass/rx-http-request/browser'.
       
    L3:  import http from '@akanass/rx-http-request/browser';
```

**Expected behavior:**

To compile every time.

**Steps to reproduce:**

Try and import ```@akanass/rx-http-request/browser```

**Other information:**

typescript  2.6.2
https://github.com/njl07/rx-http-request browser package isn't super friendly so it might be on that side but thought I might start here.

**Comment by jgw96** [comment]
Hey! This was just fixed in master and will be in the next release. Thanks for using Stencil!
