### ISSUE TITLE
bug: Stencil not produce Markdown when launched from CLI

### ISSUE THREAD

**Issue by vRuslan** [ionic-team/stencil#3405]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.16.0

### Current Behavior

Currently reading the guide [Docs Readme Markdown File Auto-Generation](https://stenciljs.com/docs/docs-readme) there is another option for generating the md files: add the flag --docs-readme, such as: ``` stencil build --docs-readme ```. I'm trying to generate the files via CLI but nothing is produced. Instead if I launch those two commands 
 - ``` stencil build --docs ```
 -  ``` stencil docs```

the files are produced.

### Expected Behavior

Not sure if this is a typo in documentation or a bug. In the case is a typo, I think that the documentation should be updated, otherwise I identified where to put the fix and can send a PR.

### Steps to Reproduce

Run in a new project, ``` stencil build --docs-readme``` to see that nothing is produced. Try to launch ``` stencil build --docs``` or  ```stencil docs```

### Code Reproduction URL

https://github.com/vRuslan/stencil-doc

**Comment by alicewriteswrongs** [comment]
Hi @vRuslan, thanks for reporting this! I was just able to confirm that `--docs-readme` is not a supported CLI flag, and therefore that the documentation is out of date. Thanks for reading closely!
