### ISSUE TITLE
Generated components.d.ts file is invalid in 0.0.8-9

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#341]
**Stencil version:**

```
 @stencil/core@0.0.8-9
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Unable to build project using `stencil-component-starter`. 
Compile errors: "tsHost.getSourceFile unable to find C:/Users/me/dev/stencil-component-starter/src/index.d.ts"

**Expected behavior:**

Should be able to run the app.

**Steps to reproduce:**

Just attempted to run `npm start` on the `stencil-component-starter` without any changes.

**Related code:**
Looks like a typo for component paths?
From the generated `components.d.ts` file:
```javascript
import {
  MyComponent as MyComponent
} from './components\my-component\my-component';
```

This breaks the build.

**Comment by cantsdmr** [comment]
This `'./components\my-component\my-component'` line has backslashes breaking the build. Changing the backslashes to forwardslashes fixes the issue but I couldn't set up config that adds forwardslashes automatically.

**Comment by cary-smith** [comment]
Definitely related to #344. 
- Windows 10
- Node 6.12.0
- npm 5.4.2.

**Comment by rolandjitsu** [comment]
I'm having a similar issue, but I'm running on OS X and the path seems to be fine (the `index.d.ts` exists, but it's empty):
```text
> @bbpviz/components@0.0.0 dev /Users/agroza/Projects/@bbpviz/components
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

[03:27.2]  @stencil/core v0.0.8-9
[03:27.5]  build, bbpviz, dev mode, started ...
[03:27.5]  compile started ...
[ ERROR ]  tsHost.getSourceFile unable to find /Users/agroza/Projects/@bbpviz/components/src/index.d.ts
[ ERROR ]  tsHost.getSourceFile unable to find /Users/agroza/Projects/@bbpviz/components/src/index.d.ts
[03:36.1]  compile finished in 8.56 s

[ ERROR ]  typescript error
           File '/Users/agroza/Projects/@bbpviz/components/src/index.d.ts' not found.

[03:36.4]  build failed, watching for changes... in 8.84 s
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, I will look into this.

**Comment by jgw96** [comment]
Hey all! I just fixed this here https://github.com/ionic-team/stencil/commit/c327eb01ea5c3529f88ea3767a81946523b9b7c8  and this fix will be in the next release (which should happen this afternoon). Thanks for using Stencil!
