### ISSUE TITLE
bug: Vue-Library doesn't work. Module not found: Error: Can't resolve 'vue-library'

### ISSUE THREAD

**Issue by dgateles** [ionic-team/stencil#3417]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.16.0

### Current Behavior

I followed the step-by-step to generate the vue-library as per the tutorial in the [documentation](https://stenciljs.com/docs/vue) . I generated the package and went to use it in an application with Vue3, but it doesn't work. After importing into `main.js`, as explained, when running the application it returns the error: `Module not found: Error: Can't resolve 'vue-library' in src`

### Expected Behavior

Import of components performed with the vue-library

### Steps to Reproduce

Just follow the [documentation](https://stenciljs.com/docs/vue) on Stencil website.

### Code Reproduction URL

https://github.com/ionic-team/stencil/

**Comment by rwaskiewicz** [comment]
Hey @dgateles 👋 

Can you please a reproduction error case for us? Unfortunately its difficult to see what's not working for you/where we can improve our documentation. Thanks!

**Comment by dgateles** [comment]
> Hey @dgateles 👋
> 
> Can you please a reproduction error case for us? Unfortunately its difficult to see what's not working for you/where we can improve our documentation. Thanks!

Ir hard to reproduce that, because i need to make a Stencil application; Stencil vue-library application, and a Vue application with this packages

**Comment by rwaskiewicz** [comment]
I'm not sure I follow - is there anything preventing you from putting all three in a single git repository and `npm link`'ing them together to show the issue? Or is there something else that makes it difficult?

**Comment by dgateles** [comment]
> I'm not sure I follow - is there anything preventing you from putting all three in a single git repository and `npm link`'ing them together to show the issue? Or is there something else that makes it difficult?

Sorry, I had other things on my mind and mixed up the cases. Here it is: [Application](https://github.com/dgateles/stencil-vue-library-issue)

Note: if using the `npm link`, no error occurs but the component is not displayed. If used via npm package installation, the error mentioned at the beginning happens.
