### ISSUE TITLE
Missing Release Notes

### ISSUE THREAD

**Issue by elmariofredo** [ionic-team/stencil#342]
**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I can't find Release Notes anywhere

**Expected behavior:**
There should be Release Notes for every release as more developers are using StencilJS they need to be up to date what has changed since last version. You consider using https://github.com/semantic-release/semantic-release to do automated versioning/release notes generation, which should be easy as you are already having standardised git commits.

Thanks!

**Comment by elmariofredo** [comment]
Thank you! 🎄

**Comment by kensodemann** [comment]
You're welcome! Thank-you for the feature request.
