### ISSUE TITLE
dist-custom-elements docs conflict with scaffolded project

### ISSUE THREAD

**Issue by mjuniper** [ionic-team/stencil#3438]
I think this is a docs issue but I'm not sure.

The [docs](https://stenciljs.com/docs/custom-elements) for the dist-custom-elements build say that you should set the `module` property in package.json to:

```json
"module": "dist/components/index.js",
```

However, when I do that, I get a warning when I attempt to  publish the project:

> package.json "module" property is set to "dist/components/index.js". It's recommended to set the "moduls" property to: ./dist/index.js.

![image](https://user-images.githubusercontent.com/942837/160436831-1e670418-2c76-4f0a-83d3-bb1c039e3095.png)

I can't tell if that warning is coming from stencil or npm.

Also, I notice that when I scaffold a new stencil project with `npm init stencil`, the resulting project has the dist-custom-elements build enabled but does not have the module property set as prescribed.

**Comment by rwaskiewicz** [comment]
The fix for this issue has been officially released as a part of [Stencil v2.17.2](https://github.com/ionic-team/stencil/releases/tag/v2.17.2). As a result, I'm going to close this issue and mark it as completed. If the bug re-appears, please feel free to open a new issue!

**Comment by sorozco653** [comment]
I am seeing a similar issue on v2.17.2. However, this time the path adds an extra layer of components for the recommended path.  I tried both relative and absolute path with no success.  Im not sure if this helps, but  I dont see the warning when I add the --watch command 

![Screen Shot 2022-08-02 at 11 00 55 AM](https://user-images.githubusercontent.com/96745226/182419948-acd347ac-ea58-4efb-b665-b961201c3ac3.png)

**Comment by rwaskiewicz** [comment]
Thanks @sorozco653 ! Tracking this in https://github.com/ionic-team/stencil/issues/3507
