### ISSUE TITLE
Unexpected newline in generated file on Windows

### ISSUE THREAD

**Issue by hufan-akari** [ionic-team/stencil#346]
**Stencil version:**

```
 @stencil/core@0.0.6
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

![default](https://user-images.githubusercontent.com/7829098/33598051-50d5d6e0-d9dc-11e7-93bd-1f92a5f47a14.PNG)

**Expected behavior:**

the `App.loadStyles` statement should be one line.

**Steps to reproduce:**

- Windows 10
- node 8.9.1
- npm 5.5.1

clone the [stencil documents](https://github.com/ionic-team/stencil-site), and build it on windows.

**Related code:**
https://github.com/ionic-team/stencil/blob/01f78203b9f60e25199db3758b5852b1bbc6fa11/src/util/data-serialize.ts#L202

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
Would you be able to try out the latest build, `0.0.8-10` and see if that fixes it? Thanks

**Comment by hufan-akari** [comment]
@adamdbradley no, the generated file is still  broken.

Additionally, When I try to use the latest @stencil/core, I get another error in browser console.
```
LiveReload disabled because it could not find its own <SCRIPT> tag
```

and there is some info on the page.

> # This app is disabled for this browser.
> 
> ## Developers:
> 
> - ES5 builds are disabled during development to take advantage of 2x faster build times.
> - Please see the example below or our config docs if you would like to develop on a browser that does not fully support ES2015 and custom elements.
> - Note that by default, ES5 builds and polyfills are enabled during production builds.
> - When testing browsers it is recommended to always test in production mode, and ES5 builds should always be enabled during production builds.
> - This is only an experiement and if it slows down app development then we will revert this and enable ES5 builds during dev.
> ## Enabling ES5 builds during development:
> 
>     npm run dev --es5  
> ## Enabling full production builds during development:
> 
>     npm run dev --prod  
> ## Current Browser's Support:
> 
> - ES Module Imports: true
> - Custom Elements: true
> - fetch(): true


I am sure my browser is ok, since I can run the stencil-app-starter without any errors.

**Comment by adamdbradley** [comment]
Awesome thanks for the report! The related code you pin pointed was the ticket, thanks!
