### ISSUE TITLE
feat: CLI - rebuild react-output target, when --watch flag triggers 

### ISSUE THREAD

**Issue by dmaniak** [ionic-team/stencil#3465]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

For generating a component library I am using the [react-output-target](https://www.npmjs.com/package/@stencil/react-output-target) as suggested by the [framework integration guide for react](https://stenciljs.com/docs/react).

As followed by the guide this "wrapper-lib" is located in another directory, thus also not affected when --watch rebuilds the project on a change.

As a solution I've tried chaining commands in my `package.json` scripts to `cd `in the "wrapper-lib" and execute it after `stencil build --watch` in `my package.json`, like this: `stencil build --watch --docs && cd ../my-lib-react && npm run build`
As you might have guessed `--watch` is blocking the CLI for any further input.

It would be pleasurable to also rebuild any additional output targets, which are not directly tied to the project, as listed [here](https://github.com/ionic-team/stencil-ds-output-targets)

### Describe the Use Case

local development, when using "custom-output-targets" as listed here: https://github.com/ionic-team/stencil-ds-output-targets

### Describe Preferred Solution

rebuild (react-)output-target as well, when --watch flag rebuilds the project

### Describe Alternatives

- add `--exec` flag to CLI to execute additional commands, so manual call for rebuild is possible

**Comment by alicewriteswrongs** [comment]
Hello @dmaniak, thanks for filing this issue and I hope Stencil + React are working well for developing your component library!

To make sure I understand what you're asking: you are developing your Stencil components with the Stencil compiler running in `--watch` mode, and you'd like to have changes made to your Stencil components automatically trigger a rebuild of the React library. Is that right?

If so, I think you can accomplish this by running Stencil in watch mode within your Stencil project's directory and, in another terminal window or tab, running TypeScript in `watch` mode within the react wrapper library directory.

You should be able to try this out by starting Stencil in watch mode and, in another window, running

```sh
npx tsc --watch
```

at the same time.
