### ISSUE TITLE
do not bundle 3rd party imports with the components

### ISSUE THREAD

**Issue by rolandjitsu** [ionic-team/stencil#347]
**Stencil version:**

```
@stencil/core@0.0.8-8
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Currently, any 3rd party imports inside the components will be bundled with the dist for the component.
In some cases we may not want to do this. A good example is rxjs, which is relatively large. And in my specific case, where I use the components I already import rxjs.

**Expected behavior:**

There should be a way to not bundle 3rd party imports with the components. With rollup this can be done by using a combination of `globals` and `external`:
```js
module.exports = {
    globals: {
        'rxjs/Observable': 'Rx'
    },
    external: [
        'rxjs/Observable'
    ]
}
```

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
Closing this as a dup of https://github.com/ionic-team/stencil/issues/162 Thanks

**Comment by rolandjitsu** [comment]
@adamdbradley true, I missed that issue.
