### ISSUE TITLE
bug: Since v1.7.1 our tests doesn't work anymore [fix with PR #3472]

### ISSUE THREAD

**Issue by deleonio** [ionic-team/stencil#3471]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

1.7.1

### Current Behavior

`npm run test`

```bash
testMatch:  - 0 matches
```

### Expected Behavior

```bash
testMatch:  - >0 matches
```

### Steps to Reproduce

Try test exec with v1.7.1 with project should work in v.1.7.0

### Code Reproduction URL

-

**Comment by alicewriteswrongs** [comment]
Hi deleonio, thanks for filing this issue! Would you mind providing a reproduction for the issue you're seeing?

**Comment by alicewriteswrongs** [comment]
I think this is the same issue as #3481

**Comment by alicewriteswrongs** [comment]
Thanks for reporting this! Just to update you, there's a bugfix PR up here: https://github.com/ionic-team/stencil/pull/3483 which just merged into `main`.

If you want to test it out to make sure it fixes your issue you could

- clone the repo locally
- check out [the branch](https://github.com/ionic-team/stencil/tree/ap/flag-parsing-bug)
- do `npm install`, `npm run build` and `npm pack`
- try installing the resulting `.tgz` file in our project by doing `npm install ./path/to/stencil.tgz`

If you'd rather wait for a pre-release or release build to try that out no worries :)

**Comment by rwaskiewicz** [comment]
The fix for this issue has been officially released as a part of [Stencil v2.17.2](https://github.com/ionic-team/stencil/releases/tag/v2.17.2).
