### ISSUE TITLE
Bundling components with a mix of styleUrl/styleUrls breaks them

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/stencil#349]
**Stencil version:**

```
@stencil/core@0.0.8-9
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

If you have a component that includes `styleUrls` and a component with only a `styleUrl` bundled together, the styles for the component with the `styleUrl` won't work. 

**Expected behavior:**

The styles should work for both when bundled together. 

**Steps to reproduce:**

1. Clone `ionic/core`: https://github.com/ionic-team/ionic/tree/core
2. Run `npm run dev` from `packages/core` 
3. Navigate to: http://localhost:3333/src/components/fab/test/basic
4. Change the `stencil.config.js` to bundle these three together:

```
    { components: ['ion-fab', 'ion-fab-list'] },
    { components: ['ion-fab-button'] },
```

5. Notice that the styles for `ion-fab` and `ion-fab-list` are no longer applied because it is including mode specific styles that don't exist

**Related code:**

```tsx
@Component({
  tag: 'ion-fab',
  styleUrl: 'fab.scss'
})

@Component({
  tag: 'ion-fab-button',
  styleUrls: {
    ios: 'fab-button.ios.scss',
    md: 'fab-button.md.scss'
  }
})

@Component({
  tag: 'ion-fab-list',
  styleUrl: 'fab-list.scss'
})
```

**Other information:**

My workaround is to bundle them separately.

**Comment by adamdbradley** [comment]
Should be fixed in latest
