### ISSUE TITLE
provide exit code other then 0 when typescript errors occur during build

### ISSUE THREAD

**Issue by dellfort** [ionic-team/stencil#351]
**Stencil version:**

```
 @stencil/core@0.0.8-8 
```

**I'm submitting a:**

- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When a typescript error occurs during build the correct typescript error message is shown in the console and it says 'build failed'. But the exit code is 0. Do "echo $?" to verify. This is a problem when building with e.g Jenkins which expects proper exit code (non-zero) to know that the build failed.

**Expected behavior:**

When a typescript error occurs during build the the exit code is 1. ( Could actually be any other non-zero value I think this is convention. e.g. Angular exits with "1" on typescript errors during builds)

**Steps to reproduce:**

Make a typescript error in your component code, e.g. misspell an interface. Do "npm run build". You see the error output in the console, pointing to the typescript error. Output ends with "build failed". Do Do "echo $?" in the console. This results in "0".

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

Could be seen as a feature request, but since it is unexpected behaviour and it breaks a common CI pipelines I'd say it rather qualifies as a bug.

**Comment by adamdbradley** [comment]
Good call, we'll make the fix, thanks
