### ISSUE TITLE
feat: copy component doc blocks to generated types

### ISSUE THREAD

**Issue by jgroth** [ionic-team/stencil#3524]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

The doc blocks from all props and events are currently copied from the component to the generated types in `components.d.ts`. However, if the component class has a doc block it will not be copied so the documentation will be missing from the generated types. It would be great to have this documentation in the generated types as well so other tools and IDEs can display appropriate documentation.

### Describe the Use Case

When using a component in an IDE I would get documentation about the component.

### Describe Preferred Solution

The documentation is already parsed during the build process and is available, it just needs to be included in `components.d.ts`. I have worked on a small PR to fix this

**Comment by rwaskiewicz** [comment]
Thanks @jgroth ! I'll get this labeled to get put into the backlog for us to review (the PR) further!
