### ISSUE TITLE
Proposal: drop event comma-separated API

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#354]
Starting with stencil 0.0.8-11:

```ts
// Decorator composition
@Listen('event')
@Listen('event2')
event() {
}
```

and 
```ts
// Comma-separated string value
@Listen('event, event2')
event() {
}
```

both generate the same output, same compiler/runtime cost.

Because of that I propose to drop or deprecated the comma-separated version.

My arguments:

- It is just another API that we have to maintain and code that can fail.
- Both versions of the code generate exactly the same output, no runtime overhead.
- Comma separated events is a stencil-only API, while decorator composition is a ES6 API. ie. people will expect several @Listen() to work together, while they will have to learn about the comma-separated API in the docs.
- It is just another api we need to document.
- Right now it is not even documented in stenciljs ( https://stenciljs.com/docs/events )
- Code consistency across stencil projects. We don't want two ways of doing exactly the same thing.
- It's probably easier to do typescript magic, like automatically infer the event types based in the `Listen` decorator.

**Comment by adamdbradley** [comment]
Yeah I think this is fair. Only thing I'd ask is that the old way continues to "work" except it'd print out a warning for a long time before we remove it.

**Comment by mhartington** [comment]
Second this. The comma separated way always confused me. Either push for multiple `@Listen`s or allow the value passed to be an array of event strings. But probably easier to just use multiple listen

**Comment by jgw96** [comment]
Hello all! Closing this as it is in the latest release. Thanks for using Stencil!
