### ISSUE TITLE
Loader's package.json does not have private:true attribute

### ISSUE THREAD

**Issue by supersabillon** [ionic-team/stencil#3565]
**Stencil version:**

```
 @stencil/core@2.16.1
```

**Current behavior:**
When generating a loader, the package.json does not have a private: true attribute

**Expected behavior:**
It should have a private: true attribute since we don't intend to publish to npm.

**Comment by rwaskiewicz** [comment]
Hey @supersabillon 👋 

Can you explain the motivation for this issue/its PR for me a little to help me understand a bit better? Did you run into an issue where `loader` was accidentally published to NPM? Some other issue perhaps? No issue at all? 

Thanks!

**Comment by supersabillon** [comment]
hi @rwaskiewicz yeah apologies I should have provided more context. Some tools used in monorepos for publishing packages, for example we are using [Changesets](https://github.com/changesets/changesets), use this property to check if a package needs to be published.

So Changesets tries to publish this package and throws an error when it can't find it in the registry. Not sure if this is happening with other tools like Lerna.

So this is not a Stencil issue, but more of an improvement we will get when working in monorepos and using tooling to help publish packages. 

Here is the PR: https://github.com/ionic-team/stencil/pull/3566

**Comment by rwaskiewicz** [comment]
Thanks!

This seems like a reasonable enough request. I’m not an expert on Changesets (the project) by any means. I did some reading up on how Changesets operates, and if there was an alternative to making a change in Stencil.
Like I said though, this is a reasonable enough request, we’re just a little wary of making a change to fit any given tool/repo setup.

It seems that Changesets [provides an `ignore` field,](https://github.com/changesets/changesets/blob/main/docs/config-file-options.md#ignore-array-of-packages) but it’s not “meant” to be used permanently:

> This option allows you to specify some packages that will not be published, even if they are referenced in changesets. Instead, those changesets will be skipped until they are removed from this array.

> THIS FEATURE IS DESIGNED FOR TEMPORARY USE TO ALLOW CHANGES TO BE MERGED WITHOUT PUBLISHING THEM - If you want to stop a package from being published at all, set private: true in its package.json.
Which, while I don’t agree with their stance, is reasonable I suppose.

So I think this is all reasonable enough/something we can potentially merge 👍 Let me test it out a bit 🙂

**Comment by rwaskiewicz** [comment]
A fix for this bug has been release as a part of [Stencil v2.18.0](https://github.com/ionic-team/stencil/releases/tag/v2.18.0). I'm going to close this issue, but please feel free to open a new issue should the bug reoccur. Thanks!
