### ISSUE TITLE
bug: "module" property warning on `www` output target

### ISSUE THREAD

**Issue by George-Payne** [ionic-team/stencil#3571]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.17.4

### Current Behavior

When building an `www` output target you get the warning:

> [ WARN  ]  Package Json: package.json
>           package.json "module" property is required when generating a
>           distribution.

### Expected Behavior

No warning, a `www` target doesn't need a module property

### Steps to Reproduce

1. clone reproduction repo
2. switch to branch `www-warning`
1. `npm install`
2. `npm run dev`
Observe:

```
[01:16.3]  @stencil/core
[01:16.6]  v2.17.4 🐞
[01:18.8]  build, example, prod mode, started ...
[01:18.8]  transpile started ...
[01:21.8]  transpile finished in 2.95 s
[01:21.8]  copy started ...
[01:21.8]  generate lazy started ...
[01:21.8]  copy finished (0 files) in 38 ms
[01:22.7]  generate lazy finished in 968 ms

[ WARN  ]  Package Json: package.json
           package.json "module" property is required when generating a distribution.

[01:22.7]  build finished in 3.95 s
```

4. Note the warning

### Code Reproduction URL

https://github.com/George-Payne/stencil-bug-reproductions/tree/www-warning

### Additional Information

Introduced in: #3475

**Comment by tanner-reits** [comment]
This should no longer be an issue in Stencil v4 with the introduction of [primary package output target validation](https://stenciljs.com/docs/config#validateprimarypackageoutputtarget)
