### ISSUE TITLE
@Event decorator stop non-composed events at the "shadow border"

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#359]
**Stencil version:**

```
 @stencil/core@0.0.8
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Non-shadowDOM-supporting browsers allow events to propagate as any event even if `{composed: false}`

**Expected behavior:**

Non-composed events should automatically be stopped at the emulated 'shadow border'

**Other information:**

I am unsure on performance penalties, but it would be nice if the emulated shadow border acted like it does in chrome where non-composed events are swallowed. This would ensure that when browsers implement the functionality (which sounds like it will be soon), behaviors remain consistent.

**Comment by adamdbradley** [comment]
Thank you for the feedback, but I think at this time we'll hold off for adding this into the shadow dom polyfill. Well keep an eye on the feature request and if it becomes and issue we'll readdress it. Thanks
