### ISSUE TITLE
bug: component content duplicated (with hydrate app on a SSG)

### ISSUE THREAD

**Issue by bsastregx** [ionic-team/stencil#3593]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [x] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.13.0

### Current Behavior

Hi, greetings.
I am using stencil with **[hydrate app output target](https://stenciljs.com/docs/hydrate-app)**, since I need to use my library of components with a static site generator (Eleventy). On stenciljs everything works fine, but on eleventy, I am experiencing a buggy behavior with a specific component: **gwds-button**. This component prints a simple a tag along with some css classes: 

![image](https://user-images.githubusercontent.com/54677414/189261772-ddb237fa-bc89-405a-8f1f-f68ad8d1f483.png)

On eleventy, I am using another component (**gwds-loot-at-me**), which has as slotted content a gwds-button component (along with other content such as a paragraph). Here is where the strangeness begins: two link elements gets printed inside gwds-button, where just one is expected to be display.

![image](https://user-images.githubusercontent.com/54677414/189262395-6091f571-b5bc-4dbf-8fa2-4329fc981013.png)

Now, if I place a gwds-button **outside** of another component, the button behaives as expected, tag duplication does not ocurrs. The duplication only seems to happen when gwds-button is nested inside another gwds-component.

### Expected Behavior

gwds-component to display only one a tag.

### Steps to Reproduce

1. clone the repo
2. npm install
3. npm start
4. open the site
5. see the first big component with green background. you will see two pink buttons, and two white buttons, and you should see one pink and one white only.
6. To check the markup, go to src/en/index.html

### Code Reproduction URL

https://github.com/bsastregx/gwds-eleventy

### Additional Information

May be this helps, not sure: https://github.com/ionic-team/stencil/issues/2611 | https://github.com/ionic-team/stencil/issues/3413

**Comment by bsastregx** [comment]
Hi @alicewriteswrongs 

You are welcome.
Yes, it is a duplicate.
You can close this issue if you would like.

Thanks for your time.

**Comment by alicewriteswrongs** [comment]
@bsastregx thanks for letting me know, any updates on the problem will be on #3413 and, as I wrote over there, while I can't promise it will be addressed on any particular timeline at present I _can_ promise that we will take a look at it soon.

Thanks again!

**Comment by bsastregx** [comment]
@alicewriteswrongs I understand. I really appreciate the time you took to respond. Thanks very much. I hope this bug gets fixed whenever you can. Bests, Bruno.
