### ISSUE TITLE
bug: missing prop for HTMLDialogElement

### ISSUE THREAD

**Issue by DavideMininni-Fincons** [ionic-team/stencil#3594]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.17.4

### Current Behavior

The native `<dialog>` is no more experimental.
However, it seems that props are missing in the stencil's lib.dom.d.ts:

![image](https://user-images.githubusercontent.com/101575400/189305210-1759b83b-71cd-4549-8b4b-6fd79a4e5fac.png)

So, if you declare a variable as `public dialog: HTMLDialogElement` you can't use methods like `showModal` or `close`.

I found an issue in the typescript repo and is has been closed recently, see https://github.com/microsoft/TypeScript/issues/48267.

### Expected Behavior

A correct API in order to avoid `any`, e.g. `public dialog: HTMLDialogElement | any`.

### Steps to Reproduce

- Checkout https://github.com/DavideMininni-Fincons/stencil-demo-issues.git
- Run `npm install`
- Run `npm start`
- See console
[ ERROR ]  TypeScript: ./src/components/example-dialog/example-dialog.tsx:29:18
 Property 'showModal' does not exist on type 'HTMLDialogElement'.

[ ERROR ]  TypeScript: ./src/components/example-dialog/example-dialog.tsx:34:18
Property 'close' does not exist on type 'HTMLDialogElement'.

### Code Reproduction URL

https://github.com/DavideMininni-Fincons/stencil-demo-issues.git

**Comment by rwaskiewicz** [comment]
Thanks @DavideMininni-Fincons!

I've confirmed that this is an issue with the reproduction case you provided. I was also able to test it against a dev build of Stencil that resolves the issue. This coming Monday's Stencil release, v2.18.0, will contain the fix (#3530)!

**Comment by rwaskiewicz** [comment]
A fix for this bug has been release as a part of [Stencil v2.18.0](https://github.com/ionic-team/stencil/releases/tag/v2.18.0). I was able to confirm the fix by running `npm i @stencil/core@2.18.0` in the reproduction case. Thanks for that - they're super helpful for things like this!

I'm going to close this issue, but please feel free to open a new issue should the bug reoccur. Thanks!
