### ISSUE TITLE
Introduce props member to improve handling of unknown properties and re-rendering

### ISSUE THREAD

**Issue by dermaschinenraum** [ionic-team/stencil#362]
**Stencil version:**

```
 @stencil/core@0.0.8-8
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Currently props must be annotated by `@Props` one by one. Properties are then available as members of the class. It would be better to group properties in a dedicated member and automatically assign all attributes of the DOM node to this object. Also every change of any attribute should trigger a re-rendering.

I can think of at least two things which are not possible in the current implementation:
1. I cannot pass properties that are not known to the user (e.g. data-attributes) to an underlying component. At least the component is not re-rendered automatically when those attributes change.
2. I cannot extract a subset of the properties and use rest operator for all other properties.

I guess this would require a major change in the philosophy, but I think it could be worth the effort. In my opinion this would give the developer a much better programming experience.

**Expected behavior:**

Think of a custom wrapper around the native HTML Button

```html
<my-button iconName="foo" disabled data-test-id="some-id">My Button</my-button>
```

```jsx
@Component(...)
export class MyButton {
  render() {
    const { iconName, ...otherProps } = this.props;  // otherProps would cover `disabled` for example
    return (
      <span>
        <my-icon name={iconName} />
        <button {...otherProps}><slot /></button>
      </span>
    )
  }
}
```

How would I do this in the current implementation?

**Steps to reproduce:**

```jsx
@Component(...)
export class MyButton {
  @Props() iconName: string;
  @Element() el: HTMLElement;
  
  render() {
    // Get all properties by accessing the underlying HTML DOM node
    // But what happens if properties other than `iconName` are updated? They don't
    // call a re-render automatically because they are not annotated by `@Props`.
    const { iconName, ...otherProps } = Array.prototype.slice.call(this.el.attributes)
      .reduce((acc, { name, value }) => {acc[name] = value; return acc;}, {});

    return (
      <span>
        <my-icon name={this.iconName} />
        <button {...otherProps}><slot /></button>
      </span>
    )
  }
}
```

**Comment by jthoms1** [comment]
I understand why this feature would be useful.  There are cases where we could benefit from this in Ionic, but each component is just a custom element. Properties of custom elements are on the element themselves and not abstracted into a 'props' attribute.  This should give you some ideas about why we have taken this approach.

So the primary reason it is designed this way is for interop with the outside world.  Does this answer the question?

**Comment by dermaschinenraum** [comment]
@jthoms1 Thanks for your answer. 
Sure I can understand the reasoning of the current solution. But it does not answer the question because it's still unclear how to annotate unknown properties.

So the question is: Given that attributes are set as class members and must be annotated with `@Props`, how would you pass unknown attributes to one of the children as I have outlined in "Steps to reproduce"? They should be connected in such a way that a change of these attributes trigger a re-render of the component. Is this even possible?

If interop with outer world is the main reason for not having an abstract layer such as a `props` member, this could also be done by creating getters from every property on the fly. Would that fit both requirements?

**Comment by jthoms1** [comment]
@adamdbradley any thoughts?

**Comment by adamdbradley** [comment]
Definitely a good feature, but at this time we're going to limit the API footprint in order to keep stencil small and focused. We'll revisit this later if it becomes a larger issue. Thanks
