### ISSUE TITLE
Angular infinity loading

### ISSUE THREAD

**Issue by Alert1437** [ionic-team/stencil#363]
**Stencil version:**

```
 @stencil/core@0.0.9-0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I have tried to integrate my web components built with stencil to Angular 2 project. 
At first glance, everything is fine, web components work perfectly. But sometimes Angular stuck with infinity "Loading..." and nothing gonna happened anymore. There are no errors, no pending requests nothing. It happens pretty often.  The angular project's code has not been changed, so it does not depend on it. if I remove the integration script everything is fine as well. So it does not work properly together.  
P.S. Just in case:  I am using  not exactly the Angular cli project  but the Angular Seed https://github.com/mgechev/angular-seed 

**Expected behavior:**

Angular should not stuck with infinity "Loading..." (It seems to me web components bundle block the main thread but I m not sure)

**Steps to reproduce:**

**Related code:**
```html
//Angular side part  in the index.html 
<script src="node_modules/web-components/dist/web-components.js"></script>
```
```tsx
// Stencil config
exports.config = {
  namespace: 'web-components',
  generateDistribution: true,
  generateWWW: false,
  bundles: [
    { components: ['collapsible-section', 'section-wrapper'] },
    { components: ['items-page'] },
    { components: ['item-grid', 'inventory-item'] }
  ],
  collections: [
    { name: '@stencil/router' }
  ]
}
```

**Other information:**

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! 

Are you able to share both the Stencil based web components project and the Angular project with us? That would be a great help to us in debugging this if you can.

If you cannot (private code or something), would you be able to put together a small component collection and sample application that demonstrate the issue and share that?

Thanks for using Stencil!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Stencil!
