### ISSUE TITLE
Error on Build version 0.0.9-3

### ISSUE THREAD

**Issue by romulocintra** [ionic-team/stencil#366]
**Stencil version:**

```
 @stencil/core@0.0.9-3
```

**I'm submitting a:**

- [x ] bug report

**Steps to reproduce:**
After update stencil to latest version 0.9.3 start giving errors on build/ npm run dev : 

```[ ERROR ]  package.json error
           package.json "main" property is required when generating a distribution and must be set to:
           dist/mycomponent.js

[ ERROR ]  package.json error
           package.json "types" property is required when generating a distribution and must be set to:
           dist/types/index.d.ts```

**Comment by julesjanssen** [comment]
Same issue here for 'types', as the actual types file is written to `dist/types/components.d.ts` (Stencil v0.0.9-4)

**Comment by adamdbradley** [comment]
@romulocintra If you have `generateDistribution` enabled in the stencil config, then it'll validate that the package.json file has the correct properties. If you're not creating a distribution, like a component library others could use from npm, then you can remove the config. If you are generating a distribution, then you'll need to correct those errors within the package.json file.

@julesjanssen We just put in a fix for that, thanks https://github.com/ionic-team/stencil/commit/5083ff14ca1c05917faff8b896f3551b270c56a4
