### ISSUE TITLE
Feature request : Adding experimental AOT/JIT Web Assembly compilation.

### ISSUE THREAD

**Issue by glemiere** [ionic-team/stencil#367]
**Stencil version:**

```
 @stencil/core@<1.0.0>
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Feature request**
Experimental Web Assembly compilation of TS/JS sources using [assemblyscript](https://github.com/AssemblyScript/assemblyscript) ([demo](https://maxgraey.github.io/Assembleash/#AssemblyScript)) and/or [walt](https://github.com/ballercat/walt) when components use Virtual DOM instead of Shadow DOM. I have no idea what result to expect, as I didn't play a lot with WASM yet, but I guess it would work with the virtual DOM since WASM doesn't have Shadow DOM access, and it would be truly interesting for us to be able to build WASM web components, as it would greatly increase the performances and match the philosophy of speed and reusability of Stencil.

I don't think I'm the only one who wants to explore this way, and I think Stencil would be the perfect project for this kind of implementation, the time is also well chosen now that Web Assembly is supported on every browsers. Let me know about your opinion on the feasibility of such a feature, can't wait for your answer!

**Comment by adamdbradley** [comment]
Absolutely, and I think we'll be able to explore more of this as stencil stabilizes and after we ship all of ionic/core components. Closing for now but we'll definitely look into this in the future, thanks.

**Comment by glemiere** [comment]
You're welcome! Keep me in touch ;-)

**Comment by touseefbsb** [comment]
just wondering if you want to reopen this? @adamdbradley
