### ISSUE TITLE
bug: our stencil repo has started emitting typescript errors on your mock-doc implementation

### ISSUE THREAD

**Issue by klh** [ionic-team/stencil#3706]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

v2.16.0

### Current Behavior

@stencil/core
v2.16.0 🎉
build, duet, prod mode, started ...
transpile started ...
transpile finished in 14.20 s

TypeScript: ./node_modules/@stencil/core/mock-doc/index.d.ts:635:15
Class 'MockPerformance' incorrectly implements interface
'Performance'.Property 'prototype' is missing in type
'MockPerformance' but required in type 'Performance'.

L634: 
L635:  declare class MockPerformance implements Performance {
L636:    timeOrigin: number;

build failed in 14.21 s

### Expected Behavior

should build without issues / and or not check types in node_modules

### Steps to Reproduce

think this has crept in on a recent dependency upgrade that hasn't been versionlocked in stenciljs

### Code Reproduction URL

na

**Comment by klh** [comment]
perhaps it would be a good idea to version lock you package.json files to exact versions instead of using ^ ?

**Comment by rwaskiewicz** [comment]
Hey @klh,

Can you do me a favor and provide a minimal reproduction case for the team to pull down? We directly bundle the TypeScript compiler to avoid these types of issues, which makes this type of issue interesting 🤔 Thanks!

**Comment by klh** [comment]
> Hey @klh,
> 
> Can you do me a favor and provide a minimal reproduction case for the team to pull down? We directly bundle the TypeScript compiler to avoid these types of issues, which makes this type of issue interesting 🤔 Thanks!

I'll try, however - i suspect its because there's no package-lock.json file in the repo so version float - happened with no code changes in all our ci builds as well as on local installations

**Comment by klh** [comment]
//ts config:

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": false,
    "experimentalDecorators": true,
    "lib": ["dom", "es2017"],
    "moduleResolution": "node",
    "module": "esnext",
    "target": "es2017",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "react",
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment",
    "noFallthroughCasesInSwitch": true,
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "include": ["src", "types/jsx.d.ts","node"],
  "exclude": ["node_modules"]
}


//.npmrc

save-prefix = ""
save-exact = true
package-lock = false
prefer-offline=true
audit=false

cache="../../.npm-cache"


other than that its a pretty standard setup, and the breaking happenned today (spontaneously) so 100% sure its a stencil/core dependency that has been release today that broke it
