### ISSUE TITLE
Styles missing from mode-less component when bundled

### ISSUE THREAD

**Issue by camwiegert** [ionic-team/stencil#372]
**Stencil version:**
```
0.0.9-4
```

**I'm submitting a:**
- [x] bug report

**Current behavior:**

When using `ionicons` as a collection within `@ionic/core`, the component is pulled in correctly, but there are no component styles. After speaking with @adamdbradley, we suspect this is because `ion-icon` itself doesn't use a mode, but is bundled with components that share a mode in `stencil.config.js`:

```js
{ components: ['ion-button', 'ion-buttons', 'ion-icon'] }
```

**Expected behavior:**

Styles should load despite the mode of components within its bundle.

**Steps to reproduce:**

```
git clone git@github.com:ionic-team/ionic.git
cd ionic/
git checkout core
npm i
npm run dev
```

Navigate to `/src/components/icon/test/basic`.

Observe that `<ion-icon>` doesn't have any of its own styles.

<img width="1392" alt="screen shot 2017-12-19 at 3 51 07 pm" src="https://user-images.githubusercontent.com/2547860/34180487-80b29756-e4d4-11e7-8d0b-e50c28d8dfb5.png">

**Comment by camwiegert** [comment]
I should add that moving the component into its own bundle gets around this:
```js
{ components: ['ion-button', 'ion-buttons' },
{ components: ['ion-icon'] }
```

**Comment by jgw96** [comment]
Closing this as it is fixed in the latest release. Thanks, everyone!
