### ISSUE TITLE
bug: TypeError: Cannot read properties of null (reading 'addEventListener') on Stencil when implementing Subscribe with Google

### ISSUE THREAD

**Issue by adiandroo** [ionic-team/stencil#3739]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.5.2

### Current Behavior

When I implementing SwG on Stencil, it gives me this error, I'm stuck fixing this. I already using componentDidLoad() to load the function
![image](https://user-images.githubusercontent.com/40738612/197193414-e296847d-2678-4d63-855d-9c0632742dbc.png)

### Expected Behavior

SwG button is show without error in console

### Steps to Reproduce

Implement SwG in stencil and give the error when it run on development (not on local)

### Code Reproduction URL

https://epaper.kompas.cloud/pdf/show/20221020

**Comment by rwaskiewicz** [comment]
Hey @adiandroo 👋 

Can you please provide a link to a code reproduction URL for the team to take a look at? While I understand that it sounds like this bug does not happen locally, the steps to reproduce here:

> Implement SwG in stencil and give the error when it run on development (not on local)

are not enough for the Stencil team to look into this further. There are too many unknowns here, including:
- how SwG should be implemented to reproduce the bug
- what the Stencil configuration is set up to look like

Thanks!

**Comment by adiandroo** [comment]
It's on private repo because it's my company project. Can I copy paste the code to here or I still have to give link to repo?
