### ISSUE TITLE
html after a <svg> node fails to render

### ISSUE THREAD

**Issue by kirkhoff** [ionic-team/stencil#375]
**Stencil version:**

```
 @stencil/core@0.1.0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Inside the return block for the `render` function, any html added after the inclusion of a `<svg>` node will not render. The `<svg>` itself will render, but nothing after it.

**Expected behavior:**

The `<svg>` node should not prevent subsequent html from rendering.

**Steps to reproduce:**

1. Add any valid `<svg>` node to the return block in your render function.
2. Ensure you have some sort of html that you expect to be rendered after the `<svg>` node.
3. View the result in the browser, and notice that the svg renders but nothing after it.

I've simplified my problem and included it below.

**Related code:**

```tsx
import { Component } from '@stencil/core';

@Component({
  tag: 'svg-oops'
})
export class SvgOops {
  render() {
    return (
      <div>
        <span>foo</span>
        <svg />
        <span>bar</span>
      </div>
    );
  }
}

```

**Other information:**

**Comment by jgw96** [comment]
Thanks for opening an issue with us! I am able to reproduce this issue with the latest release. Marking this as a bug.
