### ISSUE TITLE
bug: readme overview duplicates markdown content

### ISSUE THREAD

**Issue by jeripeierSBB** [ionic-team/stencil#3762]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.19.0

### Current Behavior

Until now we documented our components in the readme file before the `<!-- Auto Generated Below -->`.

so possible our readme could look like following:
<img width="945" alt="Bildschirmfoto 2022-10-25 um 08 06 51" src="https://user-images.githubusercontent.com/29278232/197695298-f630b9d9-799b-4e67-855a-ad48d3984021.png">

------------------------------------
Since the 2.19.0 update, stencil automatically generates the following:
<img width="973" alt="Bildschirmfoto 2022-10-25 um 08 07 53" src="https://user-images.githubusercontent.com/29278232/197695445-c499abf8-faba-482f-9165-561120ff162b.png">

So the sum up, the part until the first title is copied to overview while the other parts remaining only before the auto generated part.

### Expected Behavior

No duplication of written lines in readme before auto generated section.

### Steps to Reproduce

Write some lines and sections before auto generated code and run build.

### Code Reproduction URL

.

### Additional Information

As a possible workaround, we can move all the markdown docs into jsdocs of the component. But it's not convenient to write markdown inside a jsdoc block.

Most probably related to: https://github.com/ionic-team/stencil/pull/3635

**Comment by rwaskiewicz** [comment]
Hey @jeripeierSBB 👋 

Sorry about that! I was able to confirm that this is indeed a bug that I introduced in #3635. I'm going to take a look at this later today

**Comment by rwaskiewicz** [comment]
@jeripeierSBB 

I've created a pre-release version of Stencil, [v2.19.1-0](https://github.com/ionic-team/stencil/releases/tag/v2.19.1-0), which contains #3766, a commit that fixes the issue.

Can you do me a favor and install this version of Stencil and verify this fixes the issue? Afterwards I can release an official v2.19.1 version

**Comment by rwaskiewicz** [comment]
The fix for this has been officially released under [v2.19.1](https://github.com/ionic-team/stencil/releases/tag/v2.19.1).  I'm going to close this issue as a result. Thanks again!
