### ISSUE TITLE
Prerendering isServer utility is undefined

### ISSUE THREAD

**Issue by ajmchambers** [ionic-team/stencil#377]
**Stencil version:**
```
 @stencil/core@0.1.0
```

**I'm submitting a:**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Attempting to use the **isServer** utility mentioned in the [Prerendering docs](https://stenciljs.com/docs/prerendering):

```javascript
@Prop({ context: 'isServer' }) private isServer: boolean;
```

The docs mention that the value should be a boolean but I'm getting undefined.

**Expected behavior:**

isServer should be true if running on server or false if running on client.

**Steps to reproduce:**

Using a clone of the stencil-app-starter, attempt to use the isServer utility in a component.

**Related code:**

```tsx
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'prerender-test'
})
export class PrerenderTest {
  @Prop({ context: 'isServer' }) private isServer: boolean;

  render() {
    return (
      <div>
        <h1>Prerender Test</h1>
        <p>Value of this.isServer: <strong>
          {this.isServer
            ? this.isServer.toString()
            : 'undefined' 
          }
        </strong></p>
      </div>
    );
  }
}
```

**Other information:**

Here's a screenshot:

![prerender-test](https://user-images.githubusercontent.com/5426717/34272990-67facf46-e68a-11e7-832d-a8d23abb32ff.png)
:

**Comment by jgw96** [comment]
Hey @ajmchambers , I can not reproduce this issue with the latest release and therefore will be closing this issue for now. Thanks for using Stencil!
