### ISSUE TITLE
Runtime Error when Adding script tag in html file

### ISSUE THREAD

**Issue by eavichay** [ionic-team/stencil#378]
**Stencil version:*0.1.0*

```
 @stencil/core@<0.1.0>
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
using stencil starter app
in index.html file, inside the `<head>` section I am adding the following tag: `<script src="/build/a.js"></script>`
alongside the index.html there is `a.js` file that contains only `console.log("hello")`
When app starts I see the following error in the debugger:
`a.js:1 Uncaught SyntaxError: Unexpected token <`

**Expected behavior:**
Script should load and execute

**Comment by adamdbradley** [comment]
It's more than likely a 404 error, just not a very good error message with "Uncaught SyntaxError: Unexpected token <". If you create `a.js` and put it next to the `index.html` file, the path would be `/a.js` instead of `/build/a.js`. Hope that helps.

**Comment by eavichay** [comment]
Sorry but that didn't work as well

**Comment by eavichay** [comment]
@adamdbradley ping? Buidling stencil apps is impossible when you attempt mixing vendor scripts
