### ISSUE TITLE
bug: Unnecessary files generated

### ISSUE THREAD

**Issue by csisy** [ionic-team/stencil#3786]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.19.2

### Current Behavior

Despite explicitly turning off ES5 build, there is no way to let the compiler know that we are trying to target a modern browser that doesn't need (for example) nomodule js files.

Targeting `www`, a very basic single-component library/app generates 5 files in prod mode and 9 files in dev mode. The dev build contains additional unnecessary files, like `css-shim` and `shadow-css`. No matter what I set in the config file.

Files generated in `dev` mode under `www/build`:

- app-globals-[hash].js
- css-shim-[hash].js
- dom-[hash].js
- my-app.esm.js
- my-app.js
- index-[hash].js
- my-component.entry.js
- shadow-css-[hash].js

In `prod` mode, the polyfill/shim files are not present, fortunately.

Lastly, executing a dev build then a prod build generates one additional unnecessary file that is not generated in a second prod build. So build dev > build prod (+1 file for a total of 6 files) > build prod (5 files)

### Expected Behavior

Either provide a config option to completely disable any kind of legacy support, or better examine the project files.

For example, despite the `nomodule` script tag is removed from the `index.html`, the unnecessary `my-app.js` file and an empty `index.js` is generated. By better examining the root html file, the compiler *could* find out that no `nomodule` file is needed.

The unnecessary shim and other polyfill files should not be generated when not needed.

Lastly, the 1 extra file on the first prod build must not be created.

### Steps to Reproduce

Follow the getting started documentation.

- `npm init stencil`
- choose `component`
- `npm install`
- `npm run build`
- examine the `www/build` directory

### Code Reproduction URL

-

**Comment by Tragio** [comment]
Hi @rwaskiewicz 👋,

Is there any news regarding this issue? With more and more browser support, having all this legacy code is a bit unnecessary.

Thank you for all the great work 🚀

**Comment by rwaskiewicz** [comment]
@Tragio 

> Is there any news regarding this issue? With more and more browser support, having all this legacy code is a bit unnecessary.

This effort is up for consideration for Stencil v5. I don't have a timeline for this version of Stencil ATM, other than I'm quite literally doing the planning work as we speak.

> Thank you for all the great work 🚀

❤️

**Comment by rwaskiewicz** [comment]
Related: https://github.com/ionic-team/stencil/issues/3786

**Comment by christian-bromann** [comment]
The fix for this issue has been released as a part of today's [Stencil v4.18.1 release](https://github.com/ionic-team/stencil/releases/tag/v4.18.1)!
