### ISSUE TITLE
Non-stencil custom element loses own state when updating stencil state

### ISSUE THREAD

**Issue by eavichay** [ionic-team/stencil#379]
**Stencil version:*0.1.0*

```
 @stencil/core@<0.1.0>
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
nested "vanilla" custom element loses own state (recreated) when updating wrapper stencil element's state (forcing render and moving element)

The state affects the order of the elements

**Expected behavior:**
custom-element should not be destoryed and re-created as another instance

**Related code:**
```tsx
render() {
  return (<div>
    { this.x === 1 ? <span></span><custom-e></custom-e> : <custom-e><custom-e><span></span>
  </div>)
}
```

**Other information:**
This is probably a jsx issue or virtual dom related.
I have tried manually switching the places using this['__el'].insertBefore... but this also breaks the virtual DOM.

How to re-organize stateful custom elements?

**Comment by eavichay** [comment]
This applies both to stateful stencil elements

**Comment by jgw96** [comment]
Hey @eavichay , mind trying this with `npm install @stencil/core@next --save` ? 0.1.0 is a really old version of Stencil.

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Stencil!

**Comment by eavichay** [comment]
I'm not sure why you are closing the issue. The problem persists and Stencil does not provide a solution to it. I think you may want to allocate time to target this issue instead of ignoring it.

**Comment by eavichay** [comment]
@jgw96 Just installed latest. Still not working (0.7.0). Repoen?
