### ISSUE TITLE
Using globals causes build to fail every other time

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#380]
**Stencil version:**
```
 @stencil/core@0.1.0
```

**I'm submitting a:**
- [x] bug report

**Current behavior:**
If I define types in `globals.d.ts` then the build fails every other time.

For example, if I create the following globals and use them in a component:

```tsx
// globals.d.ts
declare global {
    namespace MyNamespace {
        interface MyType { myProp: string; }
    }
}

// my-component.tsx
@Component({
    tag: 'my-component'
})
export class MyComponent {
    @Prop() prop: MyNamespace.MyType;
    render() {
        return this.prop.myProp;
    }
}

```

Intellisense works correctly and the first time I build with Stencil the app runs fine.  If I make any changes to the source file, however, I get the following error:

```
[20:55.2]  changed file: my-component.tsx
[20:55.2]  rebuild, app, dev mode, started ...
[20:55.2]  compile started ...
[20:57.3]  compile finished in 2.01 s

[ ERROR ]  typescript: src/system/components/my-component.tsx, line: 47
           Cannot find namespace 'MyNamespace'.

     L47:      prop: MyNamespace.MyType;

[20:57.3]  rebuild failed, watching for changes... in 2.01 s
```
If I make any change to the file and build again the error goes away.  This continues so that every other time the build fails and alternates with the build working.

**Expected behavior:**
It should be possible to define global types.

My reason for trying to use globals is to get around some of the inlined code where I want to use strong typing without having lots of code in-lined into each component.  I understand this will change with ES6 imports but I want to use an approach that will also work on older browsers.

**Comment by cjorasch** [comment]
FYI - this appears to be working correctly in `0.2.0-1`.

**Comment by adamdbradley** [comment]
Awesome, thanks for testing the updates @cjorasch!
