### ISSUE TITLE
Issue when consuming an es6 module or when an interface is defined in a component file.

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil#385]
**Stencil version:**

```
 @stencil/core@0.1.0 and @stencil/core@0.1.1-0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**
I have an npm package I'm using that contains my presentational layer components on a project. When I use an npm package that has a commonjs export instead of an es6 export or typescript definition, the production build doesn't generate the type definition file for the component that imports the package. Code linked below. 

Another lead I have is, potentially, I do have two interfaces defined in the component file to model some data. That may also fail the definition file from compiling.

Either way, I would expect the build to fail or at least notify if a file wasn't created. 

**Expected behavior:**
The type definition files that would consumed as a collection in an app should be created. 

**Steps to reproduce:**

**Related code:**

```tsx
import zxcvbn from "zxcvbn";

// typical component code

interface ValidationMessage {
  errors: any
  valid: boolean
  level?: number
}
```

**Other information:**
Running `npm run build --prod` results in a successful build, but the ambient definitions file at `/dist/types/input/input` isn't created. Bumping the version on the NPM package, publishing, updating the app that consumes the package, then doing an `npm run dev` results in the consumer failing the build, stating...

```tsx
[ ERROR ]  typescript: node_modules/@splitinfinities/presentational/dist/types/components.d.ts, line: 595
           Cannot find module './components/input/input'. 

    L594:    prototype: HTMLSplitInfinitiesInputElement;
    L595:    new (): HTMLSplitInfinitiesInputElement;
    L596:  };
```

**Comment by jthoms1** [comment]
@splitinfinities could you provide me with the components.d.ts file?

**Comment by bitflower** [comment]
Hexy @splitinfinities Do you happen to have trouble with this error using Typescript interfaces #458 ?

**Comment by julesjanssen** [comment]
Just FYI: I had (almost) the same issue, which was fixed by putting the custom interfaces in their own namespace inside a `declare global`.

**Comment by jgw96** [comment]
Hello all! Closing this one for now as it has been a while since there was any activity from the OP. Thanks for using Stencil!
