### ISSUE TITLE
bug: jest takes --max-workers as a file pattern when it is not specified and a pattern is provided

### ISSUE THREAD

**Issue by andrew9994** [ionic-team/stencil#3855]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

`> 2.19.0`

### Current Behavior

When stencil test is called with a file pattern, without specifying the max workers in the pool like this:

`npx stencil test --e2e -- some-file-name.e2e.ts`

stencil adds the `--max-workers` argument to the end of the passed arguments, and gets passed to jest like this:

`jest args: --e2e -- some-file-name.e2e.ts --max-workers=8`

but jest expects that `'--'` is _only_ followed by filename patterns and that all flags like `--json` are before it in the argument list, therefore the ```--max-workers``` has no effect and indeed jest interprets it as a file pattern:

`Ran all test suites matching /some-file-name.e2e.ts|--max-workers=8/i.`

The bug got introduced with: https://github.com/ionic-team/stencil/pull/3730/commits/8a221e8ed41e5dc4dd932c5d7a011d54e0a3acb2

### Expected Behavior

Jest `--max-workers` arg should be passed before `--` when not specified.

### Steps to Reproduce

Run a test with a file pattern, without specifying the num of max-workers. Like:
`npx stencil test --e2e -- some-file-name.e2e.ts`

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework

### Additional Information

I would open a PR to solve this issue.

**Comment by rwaskiewicz** [comment]
Hey @andrew9994 :wave:

We've added https://github.com/ionic-team/stencil/pull/3827 since the commit you linked in:

> The bug got introduced with: https://github.com/ionic-team/stencil/commit/8a221e8ed41e5dc4dd932c5d7a011d54e0a3acb2

which sounds very much like the issue you're seeing.

Can you please add a minimal reproduction URL for the team to look at?  Thanks!

**Comment by andrew9994** [comment]
Sorry, I noticed that it was fixed already in https://github.com/ionic-team/stencil/commit/eb440602d79396eebbf3f8a509f60f3e03417440, but it is not yet released.

**Comment by rwaskiewicz** [comment]
Ah, not a problem!

**Comment by andrew9994** [comment]
Thanks @rwaskiewicz !

**Comment by rwaskiewicz** [comment]
@andrew9994

👋 I wanted to follow up and let you know that [v2.20.0](https://github.com/ionic-team/stencil/releases/tag/v2.20.0) has been released with the fix for this issue. Should the fix in the release not solve the one you reported, please feel free to open a new issue. Thanks!
