### ISSUE TITLE
Cannot find module '../core/renderer/h'.

### ISSUE THREAD

**Issue by mu250234** [ionic-team/stencil#387]
where  :  
/node_modules/@stencil/core/testing/index.d.ts, line: 3
   
Actual problem :+1:

hi, how to exclude node_modules while doing stencil build . actually error is:Cannot find module '../core/renderer/h'.        L3:  export { h, t } from '../core/renderer/h';  if i comment out this line in /node_modules/@stencil/co                                                                                      re/testing/index.d.ts, everything work fine  please help me

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks!
