### ISSUE TITLE
bug: Cant use stencil components in React project with Typescript

### ISSUE THREAD

**Issue by mJarsater** [ionic-team/stencil#3909]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.20.0

### Current Behavior

Experiencing the same issue that was described in: https://github.com/ionic-team/stencil/issues/1636

### Expected Behavior

Expecting to be able to use the stencil components with typescript. 

### Steps to Reproduce

Install https://www.npmjs.com/package/@scania/tegel in a react project with typescript and try to use components. Link to library github in Code Reproduction URL

### Code Reproduction URL

https://github.com/scania-digital-design-system/sdds/tree/main/tegel

**Comment by rwaskiewicz** [comment]
Hey @mJarsater 👋 

Can you do me a favor and create a minimal reproduction case please? The issue linked in the PR summary is from an unsupported version of Stencil, and I'd love to get a reproduction case that uses a more modern version that the team could pull down and try to run. Thanks!

**Comment by mJarsater** [comment]
> Hey @mJarsater 👋
> 
> Can you do me a favor and create a minimal reproduction case please? The issue linked in the PR summary is from an unsupported version of Stencil, and I'd love to get a reproduction case that uses a more modern version that the team could pull down and try to run. Thanks!

Howdy!

We are updating the project to use v 2.20.0. I can ping you here when it is done 👍🏻

**Comment by mJarsater** [comment]
Now it has been updated and we are still experiencing the same issue. We have published a npm package also, and here you can find how we instruct our users to  install the package for typescript currently: https://www.npmjs.com/package/@scania/tegel/v/0.0.1-beta.10

Feels like it should be less cumbersome than that?

**Comment by rwaskiewicz** [comment]
@mJarsater Can you create a minimal reproduction case for us in that case? Is this reproducible without Tegel?

**Comment by mJarsater** [comment]
> @mJarsater Can you create a minimal reproduction case for us in that case? Is this reproducible without Tegel?

Here is a create-react-app with typescript example: https://github.com/mJarsater/example

**Comment by rwaskiewicz** [comment]
@mJarsater Looking at the example you provided above, it doesn't look like the example project is using [our React bindings](https://stenciljs.com/docs/react) - I don't see them listed as a dependency in either [the example project](https://github.com/mJarsater/example/blob/master/package.json) or the [Tegel](https://github.com/search?q=repo%3Ascania-digital-design-system%2Fsdds+stencil%2Freact-output-target&type=code), itself. Are you importing/configuring them somewhere I'm not seeing?

**Comment by mJarsater** [comment]
> @mJarsater Looking at the example you provided above, it doesn't look like the example project is using [our React bindings](https://stenciljs.com/docs/react) - I don't see them listed as a dependency in either [the example project](https://github.com/mJarsater/example/blob/master/package.json) or the [Tegel](https://github.com/search?q=repo%3Ascania-digital-design-system%2Fsdds+stencil%2Freact-output-target&type=code), itself. Are you importing/configuring them somewhere I'm not seeing?

You are right. Our component library are not set-up with the framework bindings right now. Should we not expect typescript support until that is in place (it's on our roadmap and will be implemented in the next couple of months)

**Comment by rwaskiewicz** [comment]
@mJarsater 

> You are right. Our component library are not set-up with the framework bindings right now. Should we not expect typescript support until that is in place (it's on our roadmap and will be implemented in the next couple of months)

That is correct. The bindings generate type declarations for your components to be easily used in a React project and are the expected/official way to use Stencil in a React project.

I'm going to close this issue in ~24 hours. Thanks!

**Comment by mJarsater** [comment]
> @mJarsater
> 
> > You are right. Our component library are not set-up with the framework bindings right now. Should we not expect typescript support until that is in place (it's on our roadmap and will be implemented in the next couple of months)
> 
> That is correct. The bindings generate type declarations for your components to be easily used in a React project and are the expected/official way to use Stencil in a React project.
> 
> I'm going to close this issue in ~24 hours. Thanks!

Thanks!
