### ISSUE TITLE
IE11 does not render fallback CSS custom props with data URIs

### ISSUE THREAD

**Issue by mattdsteele** [ionic-team/stencil#393]
**Stencil version:**

```
 @stencil/core@0.1.1-0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I'm building a set of components which need to support custom background images. I'd like to do this with CSS Custom Properties, with the "default" value set as a data URI. This pattern fails to work in IE11.

For example, code like this:

```scss
$logoAsDataUri: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...')

.logo {
  background: var(--logo, $logoAsDataUri);
}
```

If the `--logo` property is absent, the `$logoAsDataUri` data URI gets loaded. This seems to work well in Edge, Chrome, and Firefox, but does not work in IE11.

In IE11, the generated CSS appearing in the page's `<head>` is missing part of the `url('` prefix:

```
app-home .logo {
  background-image: iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAHVElEQVRoQ92aW2yURRTHz24vu1B63V62LTWSAL2ILQFBASEF5WpQEwy1BIhGCAGDkUrKCw+Q8AAqwYSID2gCIkWJPhgSLuXWcAelBYWWAglRoO12u223F6B7aT3/2emypbvLfLtQwF/y5euc2W9mzpwzZ84M6HoY+h+gl+8XnidqkTNnztGxYxV08WIVXb9xg+7eqaMHDx6IOqPRSJlDM2jkiOE0duwYmjqtkCZNfEPUPRGgSDgcOXKsZ8477/NkRPBj7DEY4ntiY5N7EhLMPSZTRk9ycqZ48DdkqDPyb/BbfINv0Ua4hGyRXbv20MrPVpG9tYViY+PEjOt0OlmrBrqGxdrb2yg+PpG2bt1CixYVy1ptaFbk2rVamjp1JjU0WCgpKZEiIyNlTXi4XC5qbm6hNHMaVRw/RDk52bJGDU2LveSLNZSbm0NdXV2UmpryxJQAaAttOrht9FFSskbWqKFskYKC8XTlylUymZI0u5BWMKRmWzO9MiqPLl/+Q0qDo6RIamoW3bt3j2JiYqRkYOjs7KTBgwdTY+NtKQnMYxWBEliQgwYNkpKB5f79+2TgQGJ9jDJB10hBwThhiWelBEDf93kM+fnjpMQ/ARXBYrt6pXrA3ckfGEN1dTWtKimVkv74da2amlrKy8uhlJShT31hq4JhWq13WKEaEdUexa8iZvPL5HB0UVRUlJSogaZcLjf+8ggCouNwG6F5kpxOJ0VHR/Me9o+UPKSfa+38cTdHCYsmJdxut9jMrNYGDs+JlJ6ezpNh9vugDr+xWi3iG3yrCsbU2NhIO3f+JCUP6WcRzocoIkKvvNkhqrjd3bR9+7e0YMGHUqrGnj2/0NKlK0iv1ysHFGQALlbe3mqREg99LFJ++CjZ7a3KSmCHz8jI4Hhv06wEKC4uoo4OG2VmZoq2VMDY2ux2Ki8/IiUe+lhk9uz36PTpM0qzg8+sViu/PWl6uOh0Rg4uKUrrBl4wadJEOnDgdyl5RBGdLpIbS1dqDCZOS+MEr6Jc+G04IMcqLJxJFotFyRs8k1jPb5eU+Chy4sQpbmy6mBVVPBlrsyyFR1JSkrJLA3hDRcVhmjLlTVH2KrJu3QbatOlriouLExXPO21tbVRauprWr18ryt7FjuOp1n3jWYKxVlZWypKPRXJzRwsf1aKM0+milpa+YVCdKM5sYzj9GKx5YwTYHFNTU/mgd1mUvRapq6sX8VwVKJGensYLzh3SU1t7hRYvXsC+flesNa1grHX19bLkYxGDIZ7XR6yyMvgMO7nFUieiTqggWGRlDRchPyIiQkofT3d3N6+Tdt5/7KKsboJHgDuYTKk0bFh2WJEL0erWrVqy2RrF5ISKVxGDIVpzQ5hB3J6YTMm0fPlKun79pqzRBiyalzdKJpxqYKwYcy9e18rOfpVdpSmkyIUmOjvv8SGsk0tOj1AjiYlp3Lf6PoLFnpyczJP3tyh7FZk16106e/acmOEXARy/J0x4nQ4e3CfKXtcaPTpfaPmigLEWFOTLko9F9u8/SHPnzmNzmUSFCs8yRWlqstG+fb/RnDmzRNmrCF56fTTnWmblpNFsTqPjxw9x0miV0tDAxlZYOENj0thA3e4u0sntwqsIwFVoZWWV0jrxNPZs0nisjzFjRvMklkvJI/vIsmWfUHt7hywFBx3Gx8eL1CZccnIKRFuqqQrGuGzZElny0MciIC4uRRzwVXdZHHKwy27fvk2c+LRQVvYzH3U/FUdr1aMuzvgOh4N39b7u3E+RzZu/oTVr1oo7XlXQuN3exuumi4YPH8ETYRCu5w/MOm5obt68zuvByJaI05Sa2GzNtHHjBlq9+nMp8dBPEYD7LMyyligC0NTTvA5CgME3TU13peQhfnOt3bt3cFi1BJzVQKAT7M7IDoI/kZqVwFgwprKyHVLSF7+KzJjxNqfYH7O7eDLL5wGMZfHij3hs06WkL35dC8C1cnMLqL6+QXkhPi0QUNLTzVRTczngMSOgIsDW1EQjs/OF3xuNBikdWHDfhWBQW/uXSBID4V89SZLJRJcunRcLE7My0KBPKIExmHgswQiqCBYkbgGrq6uEaVtb7ZoDQCigD/SFPtE3xvC44BBUEQCfhEkvVZ2novnzOC2pF2HwaYG20cd87quK+0TfKsfvoGvEFyx+t9tFBw4coiVLVlBLS6vmzSwYvZtqQkI8/fD9dzR7zkxuO1L5DkFZkV6QHnRx0rZ16zb68qst1NHRSUOGxIi0JpS9Ae2hDVwLlZaW0MqVK0TSiva0oFkRAOs4ulghTjX27v1V/C+IkydPcVCIEgNARgBLIYfyBf/8gJmH+0ABl8tJkydPooULi6mo6AM+g3sUULWCLyEp0gsG5nI5yOlwig3r6LEKunDhT6qpvkb/3r4tzikOrgPR0VHikuGlrCzKzcuh8eNeo2lvFVICZ71RXBcZxYlqCAr0EpYivmCWe2cb7+5uXMRxRW/z7HbwPL0elorwWk1rPheIJ6aIP+CCvoTiMmoQ/Qfk2TCbSm2n3gAAAABJRU5ErkJggg==");
}
</style>
```

Whether I set the URL directly or using Sass variables appears irrelevant.

Strangely, a non-data URI appears to work fine as well (i.e. `url('/assets/icon/icon.png');`)

**Steps to reproduce:**

1. Clone and run repo: https://github.com/mattdsteele/stencil-ie11-css-vars
2. Open in IE11. The page should show the Stencil logo.
3. Uncomment line 19 in [app-home.scss](https://github.com/mattdsteele/stencil-ie11-css-vars/blob/master/src/components/app-home/app-home.scss#L19)

**Other information:**

My guess is this is an issue with shadycss, but I'm not sure if the Stencil compiler is doing anything else behind the scenes.

I'm open to other ways of enabling customization, so if you have another recommendation I'd be open to it. Thanks!

**Comment by mattdsteele** [comment]
I've found this workaround:

```scss
.logo {
 background: $logoAsDataUri;
 background: var(--logo, $logoAsDataUri);
}
```

This works but has the drawback that the data URI is included twice for all browsers, which inflates the size of the deliverable.

**Comment by alexstaroselsky** [comment]
Does the behavior change if you remove the quotes from around the data URI?

```sass
$logoAsDataUri: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...)
````

**Comment by mattdsteele** [comment]
@alexstaroselsky Same behavior, unfortunately.

**Comment by adamdbradley** [comment]
Thanks for the report. The unit tests for this can be found here that could be used to improve the parsing: https://github.com/ionic-team/stencil/blob/master/src/client/css-shim/test/css-shim.spec.ts 

Would love to get some help from the community on fixing this one, thanks.

**Comment by ssawant-continuum** [comment]
unhandled promise rejection securityerror in ie11 for using images in pdf
