### ISSUE TITLE
feat: Remove focus from the RESERVED_PUBLIC_MEMBERS (as for hidden also)

### ISSUE THREAD

**Issue by deleonio** [ionic-team/stencil#3934]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

If we allow `focus` Method - we can solved the accessible focus with interactive html elements inside the web components.

### Describe the Use Case

Accessiblity keyboards usage / modal focus and so on

### Describe Preferred Solution

We make a comment with the two lines in the compiler reserved key lists - as like `hidden`.

### Describe Alternatives

no

### Related Code

https://github.com/ionic-team/stencil/blob/80ef14361613706d38ad6799a03d3e5f1e1e6cbe/src/compiler/transformers/reserved-public-members.ts#L138

Like ;-)

https://github.com/ionic-team/stencil/blob/80ef14361613706d38ad6799a03d3e5f1e1e6cbe/src/compiler/transformers/reserved-public-members.ts#L42

**Comment by rwaskiewicz** [comment]
Thanks @deleonio ! Can you do me a favor and provide us with a minimal code reproduction using `focus` that doesn't work with the current version of Stencil, but does when a build of Stencil with [your changes](https://github.com/ionic-team/stencil/pull/3935) is installed for us to test the PR out? Thanks!
