### ISSUE TITLE
feat: Can shadow option be set as a function  

### ISSUE THREAD

**Issue by ZengTianShengZ** [ionic-team/stencil#3940]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

If the outermost layer of the component has a shadow set, then the components inside can ignore the shadow setting, but it is not currently possible, or is there any other way to do it. I want shadow configuration to support function for dynamic control.

![image](https://user-images.githubusercontent.com/15622519/209917527-651846bf-0b82-49e9-a9f6-0f4441b2c5c2.png)

### Describe the Use Case

```js
@Component({
  tag: 'gdwc-auth-next',
  styleUrl: 'auth-next.scss',
  shadow: () => {
         return some conditions ....
  }
})
```

**Comment by rwaskiewicz** [comment]
Hey @ZengTianShengZ 👋 

Can you help me understand the use case and desired functionality here? Specifically:
- Can you give an example as to when something like this would be helpful for you?
- In the code snippet in the issue summary above, would `gdwc-auth-next` have `shadow` set to `true` or `false` if `gdwc-auth-next-dialog` has `shadow: true`?
- In the code snippet in the issue summary above, if `gdwc-auth-next` was a component that could be used independently of `gdwc-auth-next-dialog` (i.e. it can be used without `gdwc-auth-next-dialog`), what would it's `shadow` value be if it were not a child of `gdwc-auth-next-dialog`?

**Comment by ZengTianShengZ** [comment]
- I expect `shadow` set to `true` when `gdwc-auth-next` is used alone
- I expect that when `gdwc-auth-next` is a subcomponent of `gdwc-auth-next-dialog`, the `shadow`  of `gdwc-auth-next` is `false`, and the `shadow`  of `gdwc-auth-next-dialog` is `true`

The  `shadow` of the outermost `gdwc-auth-next-dialog` is set to `true` to ensure that the style will not affect the outside, and I also want to override the style of the sub-component, so the `shadow`  of the sub-component needs to be `false` to do so.

```js
@Component({
  tag: 'gdwc-auth-next-dialog',
  styleUrl: 'dialog.css',
  shadow: true,
})
export class AuthNextDialog {
  render() {
    return (
      <div>
        gdwc-auth-next-dialog
        <gdwc-auth-next></gdwc-auth-next>
      </div>
    );
  }
}

.auth-next {
  background: blue !important;
}

```


```js

@Component({
  tag: 'gdwc-auth-next',
  styleUrl: 'auth.css',
  // shadow: true,
})
export class AuthNext {
  render() {
    return <div class="auth-next">gdwc-auth-next</div>;
  }
}

.auth-next {
  color: #fff;
  background: red;
}

```

**Comment by rwaskiewicz** [comment]
Thanks @ZengTianShengZ!

After discussing this with the team, we feel that this type of functionality isn't a great fit for Stencil as we don't want to get into conditionally setting the ShadowDOM at this time. As a result, I'm going to close this feature request and mark it as "won't do". 

Thanks again!
