### ISSUE TITLE
DOMException during render

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#395]
**Stencil version:**

```
 @stencil/core@0.1.0
```

**I'm submitting a:**
- [x] bug report

**Current behavior:**
I am getting a DOMException when a component is being rendered.

Here is a simplified version of the component:

```tsx
@Component({
    tag: 'my-component'
})
export class MyComponent {
    @State() private message: string;

    componentDidLoad() {
        setTimeout(() => {
            this.message = 'Done';
        }, 2000);
    }

    render() {
        const content = (this.message && <ion-card>{this.message}</ion-card>) || 'Loading';
        return <ion-page>
                <ion-content>{content}</ion-content>
            </ion-page>;
    }
}
```

When the component renders the first time it renders correctly.  The second time it renders (after the message gets updated) the following error occurs:

```
app.core.js:17552 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.$insertBefore (http://localhost:3333/build/app/app.core.js:16265:75)
    at updateChildren (http://localhost:3333/build/app/app.core.js:16644:26)
    at patchVNode (http://localhost:3333/build/app/app.core.js:16679:11)
    at updateChildren (http://localhost:3333/build/app/app.core.js:16609:11)
    at patchVNode (http://localhost:3333/build/app/app.core.js:16679:11)
    at updateChildren (http://localhost:3333/build/app/app.core.js:16609:11)
    at patchVNode (http://localhost:3333/build/app/app.core.js:16679:11)
    at Object.patch [as render] (http://localhost:3333/build/app/app.core.js:16714:7)
    at render (http://localhost:3333/build/app/app.core.js:17291:24)
    at renderUpdate (http://localhost:3333/build/app/app.core.js:17365:7)
```

I tried to eliminate possible causes using a bunch of permutations of elements and discovered that it renders correctly if any of the following are changed:
- If a `div` element is used instead of `ion-card` then it works.  If I use one of my own components instead of `<ion-card>` I get an error.
- If a `div` element is used instead of `ion-content` then it works.
- If a `div` element is used to wrap the content then it works (`<ion-content><div>{content}</div></ion-content>`).

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind sharing a repo we can use to reproduce this issue?

**Comment by cjorasch** [comment]
Created a repo on GitHub.

https://github.com/cjorasch/stencil-issue-395

**Comment by jgw96** [comment]
Hey @cjorasch , sorry for the delay here. I was able to reproduce this issue and will be triaging it. Thanks for using Stencil!

**Comment by cjorasch** [comment]
I am running into this in a bunch of places and it seems like it might be related to components with named slots.  For example, an `<ion-item>` where I toggle display of an icon like a checkmark.

**Comment by adamdbradley** [comment]
Great issue, once again thanks for filling this and creating a way to replicate it. Should be fixed in the next release, thanks!
