### ISSUE TITLE
bug: Use Stencil with Vite is not possible? isProxied

### ISSUE THREAD

**Issue by deleonio** [ionic-team/stencil#3961]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.21

### Current Behavior

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/6279703/211133606-4fc29ac5-9f6d-4d77-831a-117c70d20f4e.png">

### Expected Behavior

ESM load

### Steps to Reproduce

https://stackblitz.com/edit/vitejs-vite-wfjw85?file=src%2Fmain.tsx

### Code Reproduction URL

https://stackblitz.com/edit/vitejs-vite-wfjw85?file=src%2Fmain.tsx

**Comment by rwaskiewicz** [comment]
Hey @deleonio 

Have you set the [experimentalImportInjection](https://stenciljs.com/docs/config-extras#experimentalimportinjection) field in your `stencil.config` by chance? If not, can you set and give that a try?
