### ISSUE TITLE
CamelCase @Prop() declaration don't work

### ISSUE THREAD

**Issue by matteobortolazzo** [ionic-team/stencil#397]
**Stencil version:**

```
 @stencil/core@0.1.1-0
```

**I'm submitting a:**

- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When declaring a @Prop() in camelCase the value is undefined. If it's all lower case it works.

**Expected behavior:**
The variable should have a value.

**Steps to reproduce:**

New component,
Declare a prop in camelCase 
Use the component and set the attribute
Check the prop value in the componentDidLoad method

**Related code:**

```tsx
export class HomeButton {

   @Prop() isSelected: boolean;

  render() {
    return (
      <div class="tag-button">
        <div class="tag-button-image"></div>
      </div>
    );
  }

  componentDidLoad() {
      console.log(this.isSelected); // undefined
  }
}
```

**Other information:**

**Comment by adamdbradley** [comment]
As an attribute it should be `<home-button is-selected="true">`

**Comment by matteobortolazzo** [comment]
I agree with you but I follow the docs.
![stencil-props](https://user-images.githubusercontent.com/15217470/34711463-c9882828-f51f-11e7-823a-c8d8432ea8fb.PNG)

**Comment by adamdbradley** [comment]
Ok I see what you mean, this is a good question. In the example we're using JSX, and we can assign the element's properties. But if you're using the element in just HTML, and want to assign the value using attributes it uses dash case. 

@jgw96 @jthoms1 any ideas how we can better document this? Or many any internal changes?

**Comment by matteobortolazzo** [comment]
This explains a lot. Also, nothing other than "string" works as a type for @Props() an I think this is why.

**Comment by jthoms1** [comment]
For me this is definitely a documentation issue. I think that we need to create more examples on the website of how to accomplish these things JSX vs HTML etc. Does this sound right to everyone?

**Comment by jgw96** [comment]
I tend to agree with Josh here that this is a documentation issue. I can add this, probably to this section https://stenciljs.com/docs/templating. If everyone is in agreement that this is a docs issue then I will move this issue over to the stencil site repo.

**Comment by matteobortolazzo** [comment]
Yes thanks, it's a documentation issue.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil-site#114

**Comment by jgw96** [comment]
Hello all! I moved this issue to the stencil site as it is a documentation issue. Thanks (:
