### ISSUE TITLE
bug: "profile" option makes loading very slow on Chrome 109

### ISSUE THREAD

**Issue by aslushnikov** [ionic-team/stencil#3978]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.21.0

### Current Behavior

WebSite loading is slow if it's built with "profile: true" and Chrome M109+ is used.

### Expected Behavior

Everything is fast!

### Steps to Reproduce

See https://bugs.chromium.org/p/chromium/issues/detail?id=1406736

### Code Reproduction URL

https://github.com/aslushnikov/stencil-js-regression-chrome-109

### Additional Information

Hi folks!

Recent change in chromium regressed the `performance.getEntriesByName()` API performance, which StencilJS uses here:

https://github.com/ionic-team/stencil/blob/80ef14361613706d38ad6799a03d3e5f1e1e6cbe/src/runtime/profile.ts#L24-L39

This regression has been filed & is under investigation by Chromium team, see https://bugs.chromium.org/p/chromium/issues/detail?id=1406736

I'm filing this issue to let you know that, according to the discussion in the chromium bug, StencilJS can do proactive steps to mitigate the regression by a slightly different API usage, see: https://bugs.chromium.org/p/chromium/issues/detail?id=1406736#c8

P.S. I myself came here as part of the investigation of https://github.com/microsoft/playwright/issues/19946

**Comment by alicewriteswrongs** [comment]
@aslushnikov thanks for reporting, and for supplying a helpful repro case, and for linking to the Chromium bug. I can confirm that it is perceptively slower in Chrome 109.0.5414.87 than in FF 😢 I'm going to add this to our backlog so we can prioritize addressing the issue.

**Comment by rwaskiewicz** [comment]
The fix for this issue (#3995) has been released as a part of [Stencil v2.22.2](https://github.com/ionic-team/stencil/releases/tag/v2.22.2). Anyone affected by this bug should update their Stencil projects to v2.22.2 (or higher, if you're reading this message from the future). I'm going to close this issue as completed, anyone running into this post-v2.22.2 should feel free to open a new issue. Thanks again!
