### ISSUE TITLE
feat: Support solidjs

### ISSUE THREAD

**Issue by PaulOst** [ionic-team/stencil#3979]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Add support for an output target that will emit a native solidjs library.

### Describe the Use Case

Giving more options to developers along with Angular, React, and Vue.

**Comment by rwaskiewicz** [comment]
Hey @PaulOst 👋 

Thanks for the suggestion! At this time, we're not looking to add SolidJS support to Stencil's Framework Wrappers. While we understand that there are developers who are interested in using Stencil with frameworks other than Angular, React and Vue, we are still currently a smaller team that needs to be judicious about where we invest our efforts. However, this may change in the future, as we are constantly evaluating whether or not it makes sense to begin to support newer frameworks. I'm going to close this issue for the time being, to reflect the current stance of the team. Thanks!
