### ISSUE TITLE
feat: start watch without initial rebuild

### ISSUE THREAD

**Issue by miqmago** [ionic-team/stencil#4009]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Start `stencil build --watch` without initial rebuild.

### Describe the Use Case

When running `stencil build --watch --serve`, the first thing it does is to rebuild whole app. Most of the times nothing has changed since yesterday or few minutes ago when we clicked Ctrl+C, so initial build is not necessary.

### Describe Preferred Solution

I'm imagining something like `--watch-skip-first-build` flag:

```
stencil build --watch-skip-first-build --serve --no-open
```

**Comment by tanner-reits** [comment]
Hey @miqmago 👋 

I brought your request back to the team and we had some internal discussion. Based on that discussion, this functionality is not something we're looking to implement. This behavior has some nuances around identifying outdated builds, or potentially starting the dev server with a flag like this with no prior build existing.

That being said, there are a few other issues logged related to the dev server's performance and problems with live reloading. The team will be looking into these issues which will hopefully result in higher performance and lower dev-server startup times!

Thanks for the request, and hope you understand where the team stands on this!

**Comment by miqmago** [comment]
Ok thanks for the response, let's hope the team can improve performace, that way we'll be not "scared" of Ctrl+C on big apps  😄
