### ISSUE TITLE
Require type on EventEmitter

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/stencil#401]
I would like to require a type on EventEmitter, or at least be able to validate a type.

For example, in `@ionic/core`, if I have an event emitter like this:

```
@Event() myEmitter : EventEmitter<MyInterface>
```

In the above example, I can build without compile errors, etc even if I attempt to emit something that does not implement the `MyInterface` contract. It is actually a tricky behavior currently because one could think the compiler is validating and ensuring correctness, when in reality it's not and you could be emitting something unexpected.

Perhaps for users that don't care about types, they could simply tack an `<any>` on to the end of the `EventEmitter`.

Thanks,
Dan

**Comment by jgw96** [comment]
Moved to our Github Project under the discussions / enhancements tab.

**Comment by danbucholtz** [comment]
Actually this is fixed now.

Thanks,
Dan
