### ISSUE TITLE
Target TypeScript version support

### ISSUE THREAD

**Issue by marinho** [ionic-team/stencil#405]
Currently Stencil requires typescript ^2.6.2 as dependency and generates d.ts files based on  syntax as defined in TypeScript 2.4.2.

So that we have the issue already described in #338 that it requires importing (in consumer applications) Stencil d.ts files, which includes the following block of code:

```
export interface EventEmitter<T = any> {
    emit: (data?: T) => void;
}
```

**Stencil version:**
```
 @stencil/core@0.1.0
```

**I'm submitting a:**
- [x] feature request
- [ ] bug report
- [ ] support request

**Current behavior:**

Generic with type parameter inference as in `<T = any>` was introduced in TypeScript 2.4, so, an app that's based on TypeScript 2.3 or lower could experience issues here importing that file.

Once #338 is fixed, this will no longer be a problem, but I still see that compiler could generate code that is only compatible with latest TypeScript versions, which can be a problem for consuming Stencil based components.

**Expected behavior:**

It would be nice that Stencil supports target TypeScript version when generating `dist` files. I'm aware that's tricky and might not be priority for the moment, but still desirable if we want Stencil based components to be more widely accepted.

A good alternative would be to support external/customized code renderers, so, the community could write their target generators and plug Stencil to output through them.

**Comment by adamdbradley** [comment]
I think at this time we're going to stay with the dependency version of typescript, and if this becomes a larger issue we'll revisit this. Thanks.
