### ISSUE TITLE
Dashed events do not compile properly

### ISSUE THREAD

**Issue by mattdsteele** [ionic-team/stencil#406]
**Stencil version:**

```
 @stencil/core@0.1.2
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When creating an `@Event`, specifying an `eventName` using a dash causes runtime errors.

For example, ` @Event({ eventName: 'event-emitted' })` fails, while ` @Event({ eventName: 'eventEmitted' })` works fine.

**Expected behavior:**

Previous Stencil versions allowed for eventNames with dashes.

**Steps to reproduce:**

Clone and run https://github.com/mattdsteele/stencil-dashed-events.

Press the "Emit Event" button and you'll see this error:

> Uncaught TypeError: Cannot read property 'emit' of undefined
>    at HTMLButtonElement.AppHome.emitEvent (app-home.js:9)

https://github.com/mattdsteele/stencil-dashed-events/blob/master/src/components/app-home/app-home.tsx#L8 is the specific event causing issues.

**Other information:**

**Comment by jgw96** [comment]
Hey @mattdsteele , thanks for opening an issue with us. I am able to reproduce this with the latest version of Stencil. If you really need the event to be dash cased then you can use the normal custom events api https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events . In the meantime i would suggest just using camelCase.

**Comment by manucorporat** [comment]
@mattdsteele @jgw96 There is a PR ready to be merged that fixes this issue
