### ISSUE TITLE
bug: Stencil components won't load in Next.js app directory

### ISSUE THREAD

**Issue by lodybo** [ionic-team/stencil#4061]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.15.2

### Current Behavior

I'm trying out the `app` directory feature from Next.js 13, and I'm running into an issue when using our components in a route that's defined in the `app` directory:

```shell
[Error]  (2)
TypeError: undefined is not an object (evaluating 'getHostRef(ref).$instanceValues$')
undefined
	(anonymous function) (hydration-error-info.js:26)
	(anonymous function) (index-40d602e9.js:1308)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

When using the same component in a route from the `pages` directory (even in a Next.js 13 application), everything works as expected.

The `TestPage.tsx` file where I'm currently testing it out is very barebones and looks like this:

```tsx
'use client';

import { MyButton } from '@our-ui-library/react';
import { useEffect } from 'react';

export default function TestPage() {
  useEffect(() => {
    import('@our-ui-library/core/dist/loader').then(({ defineCustomElements }) => {
      defineCustomElements();
    });
  }, []);

  return (
    <div>
      <MyButton primary>Click me!</MyButton>
    </div>
  );
}
```

While we're using a custom server approach in order to server-side render our components, even if I turn that off (and use Next.js's own `next dev` command), the error is there.

### Expected Behavior

We'd expect the component (the button in this case) to be rendered on the screen when using a route defined inside `/app`.

### System Info

```shell
System: macOS Ventura
Node version: v16.16.0
npm version: 8.15.0
Browser: Safari 16.2
```

### Steps to Reproduce

- Create a Next.js 13 application
- Import a Stencil component library (with React integration)
- Create the required `/app/layout.tsx`, `/app/page.tsx` files and a Client Component.
- Inside the Client Component, dynamically import the loader and call `defineCustomElements()`.
- Boot up Next.js app and navigate to route.
- Open up dev console, and the error is there.

We're using an in-house component library which I'm not allowed to share, but I kept all my steps in Next.js as basic as possible. Our current component library is running on production in a few applications without hassle, and even the `/pages` directory in Next.js 13 is working.

I created an example repo where you can check this out.
While the Stencil version in the example repo is pinned to `2.15.2`, the error also occurs if Stencil is updated to v3.

### Code Reproduction URL

https://github.com/lodybo/stencil-nextjs-13-repro

**Comment by rwaskiewicz** [comment]
Thanks @lodybo!

I can confirm this is occurring using the reproduction case you provided. I'm going to label this to get it ingested into our backlog

**Comment by michaelbeutler** [comment]
+1

**Comment by sawden** [comment]
+1

**Comment by janforland** [comment]
+1

**Comment by rwaskiewicz** [comment]
Hey folks,

Please do me a favor and add 👍's to the issue summary to upvote it instead of "+1" style comments.  GitHub doesn't give us an easy way to track those types of comments, which makes them more likely to not be properly counted when we prioritize issues.

Thanks!

**Comment by AndreKristensen** [comment]
👍

**Comment by michaelbeutler** [comment]
Hello there, for now, I was able to come up with the following workaround:
Simply import the Web components with the `Script` object.

```tsx
"use client";

import Script from "next/script";

const Sencil: React.FC = () => {
  return (
    <>
      <Script
        type="module"
        src="webcomponents.esm.js"
      />
    </>
  );
};

export default Sencil;
```

It's not the most elegant solution, but it works for now.

**Comment by lodybo** [comment]
I can confirm that @michaelbeutler's workaround above worked with Next.js 13.4.

The steps I took were:
- Updating Next.js to 13.4.
- I created a `<Stencil />` component like he described. I did had to add `async` because Next.js pointed out an error.
- I copied the `dist/component-lib` folder to the public folder (since the `<Script />` component references the public path).
- Added the `<Stencil />` component to the `<RootLayout />` component.

I committed my changes to a new branch called `workaround` and pushed it. You can [check the commit](https://github.com/lodybo/stencil-nextjs-13-repro/compare/main...workaround) to see what I changed.

I agree that it's not an elegant solution, and I'm not sure if this approach is tree-shakeable. In a component library with a lot of components, would they all be loaded?

**Comment by michaelbeutler** [comment]
Since Next 13.4.4 the issue seems to be resolved. Can somebody confirm?

**Comment by lodybo** [comment]
@michaelbeutler I've just updated the reproduction repo to use Next.js 13.4.7, but I still get the same error as described in the ticket.

**Comment by michaelbeutler** [comment]
> @michaelbeutler I've just updated the reproduction repo to use Next.js 13.4.7, but I still get the same error as described in the ticket.
> 
> I also updated Stencil to the latest version and rebuild everything, but unfortunately the `undefined is not an object (evaluating 'getHostRef(ref).$instanceValues$')` error stays.

@lodybo did you use the useEffect hook with a client only component?

**Comment by lodybo** [comment]
@michaelbeutler Even then, I still get the error. I [adjusted the code](https://github.com/lodybo/stencil-nextjs-13-repro/commit/87a9adb9e6ababdb06a1a59c32d397b42c496ae3) so that the `component-library` is loaded inside a `useEffect` (I marked the page component as Client component) and I even added the `client-only` package in the `<ButtonRow/>` component to ensure it only gets executed on the client.

The same error appears in my console.

**Comment by michaelbeutler** [comment]
This works for me:
```tsx
// webcomponent.tsx
"use client";
import React, { useEffect } from "react";
import { defineCustomElements } from "my-stnecil-lib/dist/js/webcomponents/loader";

const Webcomponents = () => {
  useEffect(() => {
    defineCustomElements();
    return () => {};
  }, []);

  return <></>;
};

export default Webcomponents;

```
```tsx
// layout.tsx
import { Webcomponent } from "@/components";
import React from "react";

import "./globals.css";

export const metadata = {
  title: "Foo",
  description: "Bar",
};

const RootLayout = async ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <html lang={"en"}>
      <head>
        <base href="/" />
      </head>
      <body>        
          <div className="main-wrapper">{children}</div>
        <Webcomponent />
      </body>
    </html>
  );
};

export default RootLayout;

```

**Comment by lodybo** [comment]
@michaelbeutler Yes, that worked! I can see the my component now and events even work.
The error is also gone from the console, so now I can have functioning web app.

I'm going to see if it's possible to server side render the components first but this is already a massive step forward.

Thanks a lot!
