### ISSUE TITLE
Issue with .hydrated on Ionic e2e tests

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/stencil#408]
**Stencil version:**

```
@stencil/core@0.1.3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Some of our e2e tests are timing out with the upgrade to stencil. Our e2e tests run fine when reverting stencil to `0.1.1-0`. 

<img width="671" alt="screen shot 2018-01-12 at 10 46 01 am" src="https://user-images.githubusercontent.com/6577830/34882849-d19e9ae8-f785-11e7-9883-5a8894d79e17.png">
 

**Expected behavior:**
The e2e tests should be passing.

**Steps to reproduce:**
1. Clone core: https://github.com/ionic-team/ionic/tree/core
2. `npm i` and all that fun stuff in `packages/core`
3. Run `npm run e2e` or `npm run e2e -- -f=action-sheet/test/standalone` as that is a known failing test
4. Profit

**Related code:**

The init test fails on navigate here: https://github.com/ionic-team/ionic/blob/core/packages/core/scripts/e2e/page.js#L11-L15

```tsx
navigate(tagName = '') {
  this.driver.navigate().to(this.url);
  this.driver.wait(until.elementLocated(By.css('.hydrated')));
  return this.driver.wait(until.elementIsVisible(this.driver.findElement(By.css(`${tagName}.hydrated`))));
}
```

**Other information:**
If I pass a tag name to look for in the navigate then it works:

https://github.com/ionic-team/ionic/blob/core/packages/core/src/components/action-sheet/test/standalone/e2e.js#L20-L24

```
register('should init', driver => {
  const page = new E2ETestPage(driver, platform);
  return page.navigate('ion-button');
});
```

I can also switch the order so the button is first before the `ion-action-sheet-controller` and the test will run successfully:

https://github.com/ionic-team/ionic/blob/core/packages/core/src/components/action-sheet/test/standalone/index.html#L12-L14

So it seems the issue here has to do with the `ion-action-sheet-controller` element not meeting the `elementIsVisible` requirements for some reason.

**Comment by adamdbradley** [comment]
I think the changes to the visibility of controllers, which shouldn't be visible anyways, was the cause of breaking these e2e tests. I just moved the controller elements, which really are never visible, to be the second element, so that the e2e test finds the `ion-button`'s `.hydrated` class instead of the hidden controller. https://github.com/ionic-team/ionic/commit/8f6b4b90ceb898842cf2bc269f57687516955a23
