### ISSUE TITLE
Cannot build inside a directory called test

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil#410]
**Stencil version:**

```
 @stencil/core@0.1.3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

`npm run build` fails with the following error:

![testdir](https://user-images.githubusercontent.com/8823093/34896543-d36e1be4-f7af-11e7-903b-1ba42d38abdf.png)

when inside a directory called `test`

**Expected behavior:**

build would finish succesfullly

**Steps to reproduce:**

- `mkdir test`
- `git clone https://github.com/ionic-team/ionic-pwa-toolkit.git`
- `npm install && npm run build`

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
In the stencil config, used `excludeSrc: []`, otherwise the default has `excludeSrc: ['**/test/**', '**/*.spec.*']`
