### ISSUE TITLE
feat: index.html include link stylesheet and script src

### ISSUE THREAD

**Issue by twoco** [ionic-team/stencil#4123]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

I want to outsource the styles and scripts from the `src/index.html` in separate files.

```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0" />
    <title>Stencil Component Starter</title>

    <script type="module" src="/build/my-components.esm.js"></script>
    <script nomodule src="/build/my-components.js"></script>

    <link rel="stylesheet" href="index.css" />  <!-- here -->
  </head>
  <body>
    <my-component></my-component>

    <script src="index.js"></script> <!-- and here -->
  </body>
</html>
```

### Describe the Use Case

Reduce the mass of code in index.html.

Is there already a way to include this in the dev build?

**Comment by rwaskiewicz** [comment]
Hey @twoco 👋 

I'm not sure I fully understand this feature request.

Today, the `src/index.html` file that's generated by `npm init stencil component` looks very similar to what you have in the feature request:
```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0" />
    <title>Stencil Component Starter</title>

    <script type="module" src="/build/css-test.esm.js"></script>
    <script nomodule src="/build/css-test.js"></script>
  </head>
  <body>
    <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>
  </body>
</html>
```

First and foremost, is this the file you're talking about? Or perhaps a different one?

If this is the correct file, I think where I get stuck is this use case:
> Reduce the mass of code in index.html


Could you please explain a little more for me? Are you seeing additional scripts/css imports in your project's `index.html`? Or are you looking to other, existing code into these `index.css` and `index.js` files that you have in the code block of the issue summary?

Thanks!

**Comment by twoco** [comment]
Yes, I mean the `src/index.html` of a Stencil component project where I can test/see my components when I run `stencil build --dev --watch --serve`. I just want to move CSS styles and JS scripts from that `index.html` to separate files to make it more clean/organized. But it seems that this is not working. When I understand correctly, the `index.html` of a Stencil components project is for me as dev only and is not included in the production build. I guess that the `index.html` is used for the web-server, which does not include links inside the HTML file. So I maybe have to define a list of all files I want to include for the dev server. Is this [webpack dev server](https://webpack.js.org/configuration/dev-server/) under the hood? So in this case we could define `static` files to include for to www folder.

**Comment by twoco** [comment]
Damn it already works. Sorry, not seen. Solution: 

**stencil.config.js**

```json
{
  type: 'www',
  serviceWorker: null,
  copy: [
    {
      src: 'assets',
    },
  ],
}
```

See [docs](https://stenciljs.com/docs/copy-tasks).
