### ISSUE TITLE
Global "use strict" in bundles

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#413]
Since stencil uses TS in "use strict" mode, it would make sense to ship the "use strict" pragma at the root level.

Also it would save `13bytes*(N-1)`, when a bundle includes `N` components.

```ts
"use strict";
ApploadStyle(...)
App.loadComponent(...)
```

instead of:

<img width="681" alt="screen shot 2018-01-14 at 15 07 21" src="https://user-images.githubusercontent.com/127379/34916708-c427cdfe-f93c-11e7-9d09-a5a9d8acb987.png">

**Comment by jgw96** [comment]
Hey @manucorporat ! Since this is more of a discussion that we could have on Slack I am going to close this issue for now. Thanks!
