### ISSUE TITLE
Stencil build hangs

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#414]
Sometimes when building stencil in prod mode:
```
npm run build
```

The build finishes but the process never does, forcing me to `Ctrl-C` the terminal process.

<img width="586" alt="screen shot 2018-01-14 at 15 27 10" src="https://user-images.githubusercontent.com/127379/34917131-8c4beb08-f942-11e7-8a49-9bf3c8757395.png">

The JS runtime is a event loop that does not return until the event loop is empty (there are not scheduled events). That means a forgotten timeout timer can lead to process that never ends.

I feel like this can be easily fixed by doing `exit(0)` in the stencil's CLI when the build is successful.

**Comment by jgw96** [comment]
Hello! This has been refactored and we will re-evaluate this issue after that re-factor has been finished.
