### ISSUE TITLE
feat: Pass JSX or HTML Element as a Prop

### ISSUE THREAD

**Issue by tonyle-geocomply** [ionic-team/stencil#4141]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

I used Stencil.js to build ReactJS version and I wonder how can I pass a prop with JSX Component
I read about Prop Types and cannot find a solution for it: 
https://stenciljs.com/docs/properties#advanced-prop-types
Sincerely, I don't want to use String type for this Prop and then use InnerHTML for this case

### Describe the Use Case

Example:
`
<MyTable data={<div>My JSX</div>} />
`
Could we have a solution for this?

**Comment by tanner-reits** [comment]
Hey @tonyle-geocomply 👋 

Passing HTML through as a prop opens the door for lots of security vulnerabilities. Instead of trying to pass the HTML/JSX through as a string, Stencil recommends using [slots](https://stenciljs.com/docs/templating-jsx#slots) as a means of rendering dynamic child content. Stencil polyfills the slot behavior to work with both shadow and non-shadow DOMs so they can be used in all situations.

Please let us know if this satisfies your use case, or provide some additional details about your scenario if it does not. 

Thanks!

**Comment by aoilti** [comment]
> While slots are better whenever possible (static content or a specific amount of items), there are use cases where we want to be able to render dynamic amount of items, such as a virtualized data grid with custom cell renderers.
> 
> However, If you are expecting that you will pass JSX directly from a React component, that is not possible, because React JSX transpiles to React VDOM nodes, which are not compatible with Stencil's VDOM nodes.
> 
> The best you can do is export Stencil's `h` function with your package and you can use it to create Stencil VNodes, either by manually calling it or by separating the JSX in its own file and changing the jsx pragma that is used during transpilation
> 
> ```js
> /** @jsx h */
> 
> // assuming you add `export {h} from '@stencil/core'` in your component lib src/index.ts
> import { h } from 'my-component-lib';
> // or alternatively, if you don't mind consumers of your library to depend on stencil directly
> import { h } from '@stencil/core';
> 
> /*
>  * JSX in this file will be transpiled to calls to h(), thanks to the magic comment at the top,
>  * which generates Stencil VDOM nodes that can be passed as props and used directly in stencil
>  */
> 
> export const getAvatar = user => (
>   <div>
>     <img src="avatar.png" className="profile" />
>     <h3>{[user.firstName, user.lastName].join(" ")}</h3>
>   </div>
> );
> ```
> 
> However there are limitations to this approach, as **YOU CANNOT USE THIS TO RENDER REACT COMPONENTS** I cannot stress that enough! Don't expect to use hooks or any other React feature. The JSX in this file is not React, it's Stencil JSX and as such you are limited to just HTML and custom elements (i.e your stencil components)
> 
> If you need to be able to render React Components, use `slots` as suggested.

Hello, there is a solution within our team that you may refer to.

In Vue, you can use `h` function，for example：
```
import { h } from 'vue';

<WebComponentExample
  :custom-template="(context) => {
    return h('vue-button', {...otherProps}, context.label)
  }"
/>;
```
In React, you first need to add a function to the React hydration package，this function call `ReactDom.render` to create element, then in your react project use this function. for example:
```
// in React hydration package
export function createElement(vnode: any) {
            const element = document.createElement('div');
            const { slot } = vnode.props;
            if (slot !== undefined) {
              element.setAttribute('slot', slot);
            };
            ReactDOM.render(vnode, element);
            return element;
 }


// in your react project 
import { createElement } from '@stencil-component/react';
<WebComponentExample
  customTemplate={(context) =>
    createElement(<ReactButton>{context.label}</ReactButton>)
  }
/>;
```

Last, in `WebComponentExample` component, the `customTemplate` props needs to be implemented as：
```
render() {
  return <div>{
     (() => {      
         const element = this.customTemplate();
        const slotName = 'a' +Math.random()*100;
        element.slot = slotName;
        this.el.appendChild(element);

        return <slot name={slotName}></slot>
     })()
  }</div>
}
```

This solution is provided by @gikey

**Comment by tonyle-geocomply** [comment]
> While slots are better whenever possible (static content or a specific amount of items), there are use cases where we want to be able to render dynamic amount of items, such as a virtualized data grid with custom cell renderers.
> 
> However, If you are expecting that you will pass JSX directly from a React component, that is not possible, because React JSX transpiles to React VDOM nodes, which are not compatible with Stencil's VDOM nodes.
> 
> The best you can do is export Stencil's `h` function with your package and you can use it to create Stencil VNodes, either by manually calling it or by separating the JSX in its own file and changing the jsx pragma that is used during transpilation
> 
> ```js
> /** @jsx h */
> 
> // assuming you add `export {h} from '@stencil/core'` in your component lib src/index.ts
> import { h } from 'my-component-lib';
> // or alternatively, if you don't mind consumers of your library to depend on stencil directly
> import { h } from '@stencil/core';
> 
> /*
>  * JSX in this file will be transpiled to calls to h(), thanks to the magic comment at the top,
>  * which generates Stencil VDOM nodes that can be passed as props and used directly in stencil
>  */
> 
> export const getAvatar = user => (
>   <div>
>     <img src="avatar.png" className="profile" />
>     <h3>{[user.firstName, user.lastName].join(" ")}</h3>
>   </div>
> );
> ```
> 
> However there are limitations to this approach, as **YOU CANNOT USE THIS TO RENDER REACT COMPONENTS** I cannot stress that enough! Don't expect to use hooks or any other React feature. The JSX in this file is not React, it's Stencil JSX and as such you are limited to just HTML and custom elements (i.e your stencil components)
> 
> If you need to be able to render React Components, use `slots` as suggested.

Thank you @theo-staizen That's a great idea 👍

**Comment by tonyle-geocomply** [comment]
> > While slots are better whenever possible (static content or a specific amount of items), there are use cases where we want to be able to render dynamic amount of items, such as a virtualized data grid with custom cell renderers.
> > However, If you are expecting that you will pass JSX directly from a React component, that is not possible, because React JSX transpiles to React VDOM nodes, which are not compatible with Stencil's VDOM nodes.
> > The best you can do is export Stencil's `h` function with your package and you can use it to create Stencil VNodes, either by manually calling it or by separating the JSX in its own file and changing the jsx pragma that is used during transpilation
> > ```js
> > /** @jsx h */
> > 
> > // assuming you add `export {h} from '@stencil/core'` in your component lib src/index.ts
> > import { h } from 'my-component-lib';
> > // or alternatively, if you don't mind consumers of your library to depend on stencil directly
> > import { h } from '@stencil/core';
> > 
> > /*
> >  * JSX in this file will be transpiled to calls to h(), thanks to the magic comment at the top,
> >  * which generates Stencil VDOM nodes that can be passed as props and used directly in stencil
> >  */
> > 
> > export const getAvatar = user => (
> >   <div>
> >     <img src="avatar.png" className="profile" />
> >     <h3>{[user.firstName, user.lastName].join(" ")}</h3>
> >   </div>
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However there are limitations to this approach, as **YOU CANNOT USE THIS TO RENDER REACT COMPONENTS** I cannot stress that enough! Don't expect to use hooks or any other React feature. The JSX in this file is not React, it's Stencil JSX and as such you are limited to just HTML and custom elements (i.e your stencil components)
> > If you need to be able to render React Components, use `slots` as suggested.
> 
> Hello, there is a solution within our team that you may refer to.
> 
> In Vue, you can use `h` function，for example：
> 
> ```
> import { h } from 'vue';
> 
> <WebComponentExample
>   :custom-template="(context) => {
>     return h('vue-button', {...otherProps}, context.label)
>   }"
> />;
> ```
> 
> In React, you first need to add a function to the React hydration package，this function call `ReactDom.render` to create element, then in your react project use this function. for example:
> 
> ```
> // in React hydration package
> export function createElement(vnode: any) {
>             const element = document.createElement('div');
>             const { slot } = vnode.props;
>             if (slot !== undefined) {
>               element.setAttribute('slot', slot);
>             };
>             ReactDOM.render(vnode, element);
>             return element;
>  }
> 
> 
> // in your react project 
> import { createElement } from '@stencil-component/react';
> <WebComponentExample
>   customTemplate={(context) =>
>     createElement(<ReactButton>{context.label}</ReactButton>)
>   }
> />;
> ```
> 
> Last, in `WebComponentExample` component, the `customTemplate` props needs to be implemented as：
> 
> ```
> render() {
>   return <div>{
>      (() => {      
>          const element = this.customTemplate();
>         const slotName = 'a' +Math.random()*100;
>         element.slot = slotName;
>         this.el.appendChild(element);
> 
>         return <slot name={slotName}></slot>
>      })()
>   }</div>
> }
> ```
> 
> This solution is provided by @gikey

The solution from your team is exactly what I found about React JSX
I'll try. Thank you @aoilti 🙇‍♂️ 
But may I ask you a question about if I had an event onClick in <ReactButton> like that
```
<ReactButton onClick={myFunc}>{context.label}</ReactButton>
```
Is this solution still correct?

**Comment by cjorasch** [comment]
Another potential issue with JSX in props is that you can not reuse the same JSX content again if the component needs to re-render.  In general this is not a problem for functional components because the caller is causing the render so it will provide new JSX content each time.

For Stencil components you can pass a function that renders JSX as a prop and then it can be used multiple times if needed.

```jsx
<MyTable data={() => <div>My JSX</div>} />
```

In general I find JSX in props much more flexible and convenient than slots if you are writing code in Stencil and calling functional components.  If you are publishing components to be used by other frameworks then you generally need to stick with simple props.

**Comment by aoilti** [comment]
> > > While slots are better whenever possible (static content or a specific amount of items), there are use cases where we want to be able to render dynamic amount of items, such as a virtualized data grid with custom cell renderers.
> > > However, If you are expecting that you will pass JSX directly from a React component, that is not possible, because React JSX transpiles to React VDOM nodes, which are not compatible with Stencil's VDOM nodes.
> > > The best you can do is export Stencil's `h` function with your package and you can use it to create Stencil VNodes, either by manually calling it or by separating the JSX in its own file and changing the jsx pragma that is used during transpilation
> > > ```js
> > > /** @jsx h */
> > > 
> > > // assuming you add `export {h} from '@stencil/core'` in your component lib src/index.ts
> > > import { h } from 'my-component-lib';
> > > // or alternatively, if you don't mind consumers of your library to depend on stencil directly
> > > import { h } from '@stencil/core';
> > > 
> > > /*
> > >  * JSX in this file will be transpiled to calls to h(), thanks to the magic comment at the top,
> > >  * which generates Stencil VDOM nodes that can be passed as props and used directly in stencil
> > >  */
> > > 
> > > export const getAvatar = user => (
> > >   <div>
> > >     <img src="avatar.png" className="profile" />
> > >     <h3>{[user.firstName, user.lastName].join(" ")}</h3>
> > >   </div>
> > > );
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > However there are limitations to this approach, as **YOU CANNOT USE THIS TO RENDER REACT COMPONENTS** I cannot stress that enough! Don't expect to use hooks or any other React feature. The JSX in this file is not React, it's Stencil JSX and as such you are limited to just HTML and custom elements (i.e your stencil components)
> > > If you need to be able to render React Components, use `slots` as suggested.
> > 
> > 
> > Hello, there is a solution within our team that you may refer to.
> > In Vue, you can use `h` function，for example：
> > ```
> > import { h } from 'vue';
> > 
> > <WebComponentExample
> >   :custom-template="(context) => {
> >     return h('vue-button', {...otherProps}, context.label)
> >   }"
> > />;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In React, you first need to add a function to the React hydration package，this function call `ReactDom.render` to create element, then in your react project use this function. for example:
> > ```
> > // in React hydration package
> > export function createElement(vnode: any) {
> >             const element = document.createElement('div');
> >             const { slot } = vnode.props;
> >             if (slot !== undefined) {
> >               element.setAttribute('slot', slot);
> >             };
> >             ReactDOM.render(vnode, element);
> >             return element;
> >  }
> > 
> > 
> > // in your react project 
> > import { createElement } from '@stencil-component/react';
> > <WebComponentExample
> >   customTemplate={(context) =>
> >     createElement(<ReactButton>{context.label}</ReactButton>)
> >   }
> > />;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Last, in `WebComponentExample` component, the `customTemplate` props needs to be implemented as：
> > ```
> > render() {
> >   return <div>{
> >      (() => {      
> >          const element = this.customTemplate();
> >         const slotName = 'a' +Math.random()*100;
> >         element.slot = slotName;
> >         this.el.appendChild(element);
> > 
> >         return <slot name={slotName}></slot>
> >      })()
> >   }</div>
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This solution is provided by @gikey
> 
> The solution from your team is exactly what I found about React JSX I'll try. Thank you @aoilti 🙇‍♂️ But may I ask you a question about if I had an event onClick in `<ReactButton>` like that
> 
> ```
> <ReactButton onClick={myFunc}>{context.label}</ReactButton>
> ```
> 
> Is this solution still correct?

Of course, that's right. in fact, The component is ultimately transformed by the  `ReactDOM.render` in the hydration layer

**Comment by tanner-reits** [comment]
Hey all!

We've had some internal discussion on the Stencil team regarding this topic and have come to the conclusion that passing React components/JSX as a prop is not something that Stencil can/will support. Runtime interoperability is a slippery slope and we don't feel it is appropriate for Stencil to try to support handling lifecycle events for other frameworks inside Stencil's runtime. 

I'm going to go ahead and close this issue out. We hope everyone can understand our decision regarding this behavior. And thank you again for using Stencil!
