### ISSUE TITLE
feat: Deprecate experimentalImportInjection, introduce enableImportInjection (baseline Vite support)

### ISSUE THREAD

**Issue by sandrooco** [ionic-team/stencil#4148]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

The [config option](https://stenciljs.com/docs/config-extras#experimentalimportinjection) `experimentalImportInjection` should be deprecated and replaced by a stable pendent, `enableImportInjection` for example.

Further info for the "why": [thread on the support slack](https://stencil-worldwide.slack.com/archives/C79EANFL7/p1678436275806629)

### Describe the Use Case

1. Enables basic Vite support
2. Removes a holdback for some component libraries to use the flag due to insecurities

### Additional Information

@rwaskiewicz outlined some of the required steps that had to be done (thanks again for your great support!):

1. Adding a new flag, enableImportInjection to the config API to [this file, perhaps right under `experimentalImportInjection`](https://github.com/ionic-team/stencil/blob/c564a0788fd5fecf20dde8f444b2510aa27a8783/src/declarations/stencil-public-compiler.ts#L306)
1.1. Something like `enableImportInjection?: boolean` (it would need to be optional for now)
1.2. We’d want a JSDoc above it similar to experimentalImportInjection

1. Replacing experimentalImportInjection with `enableImportInjection` in the following files
2.1. https://github.com/ionic-team/stencil/blob/c564a0788fd5fecf20dde8f444b2510aa27a8783/test/bundler/component-library/stencil.config.ts#L19
2.2. https://github.com/ionic-team/stencil/blob/c564a0788fd5fecf20dde8f444b2510aa27a8783/src/compiler/config/test/load-config.spec.ts#L45
2.3. https://github.com/ionic-team/stencil/blob/c564a0788fd5fecf20dde8f444b2510aa27a8783/src/compiler/config/test/fixtures/stencil.config2.ts#L9

1. Updating [this conditional](https://github.com/ionic-team/stencil/blob/c564a0788fd5fecf20dde8f444b2510aa27a8783/src/compiler/output-targets/dist-lazy/generate-lazy-module.ts#L51) to something like: `if ((!!config.extras?.experimentalImportInjection || !!config.extras?.enableImportInjection) && !isBrowserBuild) {`

1. Updating the documentation (this lives in a separate repo):
4.1. Mark [experimentalImportInjection as deprecated](https://github.com/ionic-team/stencil-site/blob/04199fcba4f85562e184852f8c091da9bd8b3db3/docs/config/extras.md?plain=1#L93)
4.2. Add a new section for `enableImportInjection`

**Comment by rwaskiewicz** [comment]
The PR associated with this issue has landed and is included in today's [v3.2.0 release](https://github.com/ionic-team/stencil/releases/tag/v3.2.0). As a result, I'm going to close this issue. Thanks again!
