### ISSUE TITLE
Compiler prevents to use a service worker configuration in dev mode

### ISSUE THREAD

**Issue by akserg** [ionic-team/stencil#415]
**Stencil version:**
```
 @stencil/core@0.1.4
```

**I'm submitting a:**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
The Stencil compiler doesn't generate service worker when `serviceWorker` is specified in `stencil.config.js` file and `--service-worker`as an argument in stencil command in dev mode:
```
"devWithSW": "sd concurrent \"stencil build --dev --service-worker --watch\" \"stencil-dev-server\" "
```
It's impossible to use Workbox boilerplate code in custom service worker via `serviceWorker.swSrc` as well.

**Expected behavior:**
The combination of `serviceWorker` in `stencil.config.js` file and `--service-worker`as an argument in stencil command should generate the service worker in `www` folder` in dev mode.

**Found problem:**
I have found the problem  here: 
https://github.com/ionic-team/stencil/blob/d8978964fbbb3b5116b5b88054e3fb50934706f2/src/cli/cli-utils.ts#L30-L47

The line https://github.com/ionic-team/stencil/blob/d8978964fbbb3b5116b5b88054e3fb50934706f2/src/cli/cli-utils.ts#L40 removes the `serviceWorker` configuration from `stencil.config.js`.

**Solution:**
The solution I'm suggesting is that remove first `else` from the condition. Resulting code:
```
if (config.devMode) {
    if (argv.serviceWorker && config.serviceWorker === undefined) {
      // dev mode, but forcing service worker
      // but they didn't provide a sw config
      // so still force it to generate w/ our defaults
      config.serviceWorker = true;
    }

  } else if (config.serviceWorker === undefined) {
    // prod mode, and they didn't provide a sw config
    // so force it generate with our defaults
    config.serviceWorker = true;
  }
```

I'm ready to make a PR.

**Comment by vovikdrg** [comment]
I have the same problem. Using stencil-pwa template wont start service worker untill I remove it from config

**Comment by jgw96** [comment]
Hey @akserg , thanks for looking into this. If you want too feel free to make that PR!

**Comment by akserg** [comment]
Hi @jgw96 

Please review the PR #423

**Comment by jgw96** [comment]
Thanks for the PR @akserg , just merged it!
