### ISSUE TITLE
Stencil watcher seems to break components.d.ts every other build

### ISSUE THREAD

**Issue by dimi-nk** [ionic-team/stencil#416]
**Stencil version:**

```
 @stencil/core@0.1.5
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I am trying to use one of the generated 'HTMLElement' types inside `components.d.ts`. Namely, I have a component called `Icon` and I want to use `HTMLIconElement` in another component. I have a dev server running. Every other change I'm making, `components.d.ts` seems to just include the component I just changed, e.g.

> I have components `Icon` and `IconDemo`. If I change something inside `Icon`, `components.d.ts` only includes the generated code for `Icon` and removes *everything* else. If I do another change on `Icon`, then the whole file is generated. Similarly, if I change `IconDemo`, only that component is generated, but the definitions for `Icon` are missing, so the compilation fails.

I think this is purely a problem with compilation expecting the definitions. Even though `components.d.ts` is not properly generated, it doesn't seem to cause any other problems to the app (it's just a definitions file after all). Consecutive `npm run build` do not fail, which means that this only happens when `watch` is running.

**Expected behavior:**

The `components.d.ts` file is always generated correctly.

**Steps to reproduce:**

- Create two components, e.g. `Icon` and `IconDemo`
- Inside `IconDemo`, do something like this:

```tsx
    componentDidLoad() {
        const $icons = this.$host.shadowRoot.querySelectorAll('icon');
        Object.values($icons).forEach(($icon: HTMLIconElement) => {
            $icon.addEventListener('click', () => {
                console.log($icon.icon); // icon is a property of Icon
            }, true);
        })
    }
```
- Make a change on `IconDemo` (I usually just add a space and save)
- Build should fail every other time
- Inspect if `components.t.ds` contains all components or not

**Other information:**

**Comment by jgw96** [comment]
Hey! Mind putting together a repo we can use to reproduce this issue?

**Comment by dimi-nk** [comment]
Sure, I'll do one now

**Comment by jgw96** [comment]
Thanks!

**Comment by cjorasch** [comment]
I have the same problem when I use my own `.d.ts` file.  In this case I do not reference the `components.d.ts` file.  Every time I build I need to build twice.

**Comment by jgw96** [comment]
Thanks for the repo @dimi-nk ! We will be looking into this.

**Comment by dimi-nk** [comment]
I'm using `0.2.0` and this seems to be fixed

**Comment by jthoms1** [comment]
Going to mark this as resolved. Thanks!
