### ISSUE TITLE
how to create a brand new application without cloning from app base?

### ISSUE THREAD

**Issue by Mahesh18374** [ionic-team/stencil#418]
I would be glad if i get some help out here.

Thanks

**Comment by jgw96** [comment]
Hey! At the moment our recommended way to get started with Stencil is cloning either our https://github.com/ionic-team/stencil-app-starter if you want to build an entire app with Stencil, or the https://github.com/ionic-team/stencil-component-starter. We do not have a CLI at this time. Thanks!

**Comment by Mahesh18374** [comment]
Thanks for the reply
