### ISSUE TITLE
bug: object returned by MockWindow.matchMedia missing properties

### ISSUE THREAD

**Issue by cam-narzt** [ionic-team/stencil#4193]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.2.0

### Current Behavior

in a test `window.matchMedia('(prefers-color-scheme: dark)')` returns an object that is missing the `media`,      `addEventListener`,      `dispatchEvent`,      `removeEventListener`, and      `onchange`  properties that should exist on it.

### Expected Behavior

in a test `window.matchMedia('(prefers-color-scheme: dark)')` should return an object with all expected  properties

### System Info

```shell
System: node 19.8.1
     Plaform: darwin (22.3.0)
   CPU Model: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 cpus)
    Compiler: ~/Developer/Javascript/stencil/compiler/stencil.js
       Build: 20220401204908
     Stencil: 0.0.0-dev.20220401204908 🛳
  TypeScript: 4.5.4
      Rollup: 2.42.3
      Parse5: 6.0.1
      Sizzle: 2.42.3
      Terser: 5.6.1
```
```


### Steps to Reproduce

Run the following in a stencil unit test:

```
console.log(Object.keys(window.matchMedia('(prefers-color-scheme: dark)')))
```

### Code Reproduction URL

https://github.com/cam-narzt/stencilbug

### Additional Information

in reproduction repo run `npm run test` to see failing test that demonstrates the problem

**Comment by cam-narzt** [comment]
There is a PR with the fix linked.

**Comment by kittyyueli** [comment]
Hi! I'm still running into this issue with version 3.2.1. 

In my unit tests, I see this error: 
![image](https://user-images.githubusercontent.com/52163182/234148529-2e1e7ec1-4dba-4b11-903d-b6fa01ae1f0f.png)

However, if I change to use the `onchange` function instead of `addEventListener('change', ...)` it works.

**Comment by rwaskiewicz** [comment]
@kittyyueli can you do me a favor and [create a new issue](https://github.com/ionic-team/stencil/issues/new?assignees=&labels=&template=bug_report.yml&title=bug%3A+) with a minimal reproduction case for the team to take a look?
