### ISSUE TITLE
bug: impossible to make individual unit test

### ISSUE THREAD

**Issue by JEricaM** [ionic-team/stencil#4237]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.2.0

### Current Behavior

Not able, from CLI , to run individual unit tests.

### Expected Behavior

This command should run the tests only for COMPONENT instead, runs all the test.
`npx stencil test --e2e --spec component`

### Steps to Reproduce

Launch `npx stencil test --e2e --spec component` where component is the name of the individual test

### Code Reproduction URL

https://github.com/JEricaM/StencilUserTest

### Additional Information

I've already checked this previous issue 
https://github.com/ionic-team/stencil/issues/3276
but I think that the bug is still present.
I've also done the steps from [alicewriteswrongs](https://github.com/alicewriteswrongs) https://github.com/ionic-team/stencil/issues/3276#issuecomment-1113668673 but nothing worked. Always all the tests runs.

**Comment by JEricaM** [comment]
hi @alicewriteswrongs , thanks for the quick reply.
Can I confirm you that now it works! thank you very very much!

**Comment by alicewriteswrongs** [comment]
Great, happy to help!
