### ISSUE TITLE
app.js meta data and code size

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#426]
**Stencil version:**
```
 @stencil/core@0.1.5
```

**I'm submitting a:**
- [x] feature request

**Current behavior:**
The `app.js` file that is generated by Stencil contains all of the meta data for all of the components that might be used by the application.  Even if I am only rendering a single component I get over 50K of meta data for my current application.  As I add more components and pages this size continues to increase.

Even if you only want to use a single component from `@ionic/core`, you get meta data for every property and every method that is used by every component that is in `@ionic/core`.

If third parties develop other components libraries and publish them as a collection then all of the collection meta data will be included as well.

**Expected behavior:**
The app probably needs to be able to map tag names to bundle ids in order to dynamically load the component but is the rest of the meta data really needed in advance?  Can it be in the bundle so that it is available once the bundle loads?

Something like: 
```ts
{
    bundle1: ['ion-list', 'ion-item', ...],
    bundle2: ['ion-card', ...]
}
```

It could potentially be further simplified by optionally listing the components that you want to be able to use in `stencil.config.js` but that could get complicated with complex component dependencies.

The meta data also contains some components that would not be used (e.g. `test-demo-four`).  This is probably more related to the component publishing process though.

**Comment by adamdbradley** [comment]
Absolutely, there is an `includeBundledOnly` option which we need to document yet to solve part of this problem. 50K does seem quite high though, i'm guessing that's not gzipped? Also, the metadata we'll be minifying further, and looking into not including listener data by default. Still a work in progress.

**Comment by adamdbradley** [comment]
This would be an example of using it, but we need to work out a few bugs yet, so the up coming release will have this ability.

```  bundles: [
    { components: ['my-app', 'app-home'] },
    { components: ['ion-button'] }
  ],
  collections: [
    { name: '@ionic/core', includeBundledOnly: true }
  ]
```

So above, it'd only pull in the `ion-button` for your app because you were explicit about which ones you wanted to use. Open for any API ideas or naming. Thanks

**Comment by jthoms1** [comment]
One thing I thought about with this is that with the exposed components.d.ts file there will be no type errors if a component is included that is not added to the bundle.

We might be able to only adhere to types that are included through this configuration.

**Comment by cjorasch** [comment]
Sounds promising.  I like the idea of being able to specify the exact bundling to use both for app components and for included collections.  It looks pretty straightforward from your example.

I don't think the lack of component type errors if the component is not included is a big issue.  The typings are still valid even if a component is not registered.

Probably the bigger risk is omitting components that are referenced by other components internally.  E.g. using `<ion-button>` which in turn uses `<ion-image>` and not including it in a bundle.  Possibly the dependency could be found at compile time but I am sure this would be hard in some cases.  Maybe at runtime log warnings in dev mode when a custom element is being loaded and the tag name is unknown?  You could also document the feature as an advanced option with warnings that you need to know what you are doing with selective bundling.

**Comment by cjorasch** [comment]
This is a little off topic but I thought I would share some bundling related things I am doing with the current version fo Stencil.

Because it does not yet support imports of external code in components without all the problems associated with duplicated code I have come up with some hacks as work arounds.

For any shared services I include them in container component files so that they can be dynamically loaded.  For example, `my-services.tsx` can contain some services including `MyLogger`.  This file then adds the services to global data.

```ts
// my-services.tsx
window.MyApp.MyLogger = { ... }; // define global services
@Component({tag: 'my-services'}) ...
```

I created a global function that is then used to provide async access to global data.

```ts
function ensureComponent(tagName: string): Promise<void>`
```

This function check to see if the component is already loaded, and, if needed, creates the element and waits for the `componentOnReady` callback.

With this in place I can use async loading with the services.

```tsx
// my-component.tsx

function log(message) {
    ensureComponent('my-services').then(() => MyApp.MyLogger.log(message) )
}
```

This is much more painful than simply using import statements but it is also pretty flexible so that you have complete control of async loading of services.

The reason I mention it here is that the notion of defining bundles that can include both components and other code would be powerful.  It would require some form of late bound string identifier for the services but could probably leverage most of the existing async loading code.

**Comment by adamdbradley** [comment]
Cool, thanks for the feedback. Also, as an opt-in feature, we're thinking we'll be able to automatically only compile what is being used, basically only the components found in JSX. Additionally, it could check for components found within any `document.createElement()` calls.
