### ISSUE TITLE
If I modify file stencil.config.js i am getting an error

### ISSUE THREAD

**Issue by vovikdrg** [ionic-team/stencil#430]
**Stencil version:**

```
 @stencil/core@0.1.5
```

**I'm submitting a:**

- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
If I modify file stencil.config.js i am getting an error

```
[07:34.7]  generate bundles started ...
[07:34.7]  generate bundles finished in 13 ms

[ ERROR ]  ENOENT: no such file or directory, open
           'C:\Projects\FULLPATH\customer\C:\Projects\FULLPATH\customer\src\global\app.css' 

[07:34.7]  rebuild failed, watching for changes... in 4.02 s

```
**Expected behavior:**
I should be able to modifle stencil.config.js without any compilation issues.

**Steps to reproduce:**
Save stencil.config.js many times and you will get an error

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us, I was just able to reproduce this.

**Comment by adamdbradley** [comment]
@vovikdrg thanks for submitting the issue! Fix is in and should be good to go for the next release, thanks!
