### ISSUE TITLE
svg "clipPath" renders as "clippath"

### ISSUE THREAD

**Issue by LloydVincent** [ionic-team/stencil#435]
**Stencil version:**

```
 @stencil/core@0.1.6
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
A stencil component renders a `<clippath>` inside an `<svg>` where it should be a `<clipPath>`, the template in render() is written "clipPath"

**Expected behavior:**
elements inside rendered templates should maintain their specified casing, at least in cases such as clipPath where the casing is critical to the functionality of the element

**Steps to reproduce:**
Render an svg with a clipPath child element inside a stencil component

**Other information:**
This issue appeared after upgrading from 0.1.1 to 0.1.6

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! I was able to reproduce this issue and we will look into it.

**Comment by LloydVincent** [comment]
After updating to 0.6.1 this issue appears to have been resolved. Thank you and keep up the awesome work!
(ps. updating was kind of a nightmare, it'd be great if you could indicate a recommended node/npm configuration and provide a _blank_ starter repo)
