### ISSUE TITLE
feat: computed @Prop name

### ISSUE THREAD

**Issue by mailinger-mate** [ionic-team/stencil#4350]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Could the `@Prop` decorator support computed names similar to the computed property names feature of ES6?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names

### Describe the Use Case

Avoid code repetition when prop names are shared across multiple components in case of a design system library.

### Describe Preferred Solution

```tsx
@Prop() [name]: Type;
```

### Related Code

```tsx
enum Spacing {
    Margin = 'm',
    MarginX = 'mx',
    MarginY = 'my',
};

@Component({
  tag: 'button',
  styleUrl: 'button.css',
  shadow: true,
})
export class MyComponent {
  @Prop() label: string;
  @Prop() [Spacing.Margin]: SpacingSize;

  render() {
    const className = this[Spacing.Margin] && Spacing.Margin + '-' + this[Spacing.Margin];
    return (
      <button class={className}>{this.label}</button>
    );
  }
}
```

### Additional Information

Currently the related code does not compute the prop name while transpiling to React:
```ts
declare namespace LocalJSX {
    interface AdsButton {
        "[Spacing.Margin]"?: SpacingSize;
        "label"?: string;
    }
 }
```

**Comment by rwaskiewicz** [comment]
Thanks @mailinger-mate !

I'm going to label this for folks to upvote if they're interested in having the team take a closer look at what a solution might look like!
