### ISSUE TITLE
--watch flag not triggering SASS rebuild in 0.2.0

### ISSUE THREAD

**Issue by camwiegert** [ionic-team/stencil#438]
**Stencil version:**

```
 @stencil/core@0.2.0
```

**I'm submitting a:**

- [x] bug report

**Current behavior:**

Making changes to a `*.scss` file does not trigger a rebuild when using the `--watch` flag. No changed detection is logged. However, making changes to a `*.tsx` file triggers a rebuild as expected.

**Expected behavior:**

Changing a `*.scss` file should trigger a rebuild in the same way as changing as `*.tsx` file.

**Steps to reproduce:**

1. `npx stencil build --dev --watch`
2. Change any `*.scss` file in `src/`.

**Other information:**

When running with `--debug`, I get this output after changing an SCSS file.

```
[20:28.0]  watcher, fileUpdate: /Users/cam/Desktop/ionic/packages/core/src/components/alert/alert.md.scss, 1516731628062 
            MEM: 242.6MB 
[20:28.1]  copyTasks started ...  MEM: 242.6MB 
[20:28.3]  copyTasks finished in 190 ms  MEM: 243.1MB 
```

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil/commit/e2a8632eebbf902934a5471b0d2572804ec4fb5a
