### ISSUE TITLE
bug: Not possible anymore to run specific test(s)

### ISSUE THREAD

**Issue by kvandenhaute** [ionic-team/stencil#4398]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.2.0

### Current Behavior

`npm test -- utils.spec.ts` will no longer run a single test, but will just run all tests.

### Expected Behavior

`npm test -- utils.spec.ts` will only run this test

### System Info

```shell
System: node 16.15.1
    Platform: darwin (22.3.0)
   CPU Model: Apple M1 (8 cpus)
    Compiler: /Users/kevin/dev/stencil-bug/node_modules/@stencil/core/compiler/stencil.js
       Build: 1682947516
     Stencil: 3.2.2 🏒
  TypeScript: 4.9.5
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.17.1
```

### Steps to Reproduce

Try to run a single test: `npm test -- utils.spec.ts`

### Code Reproduction URL

https://github.com/kvandenhaute/stencil-bug

**Comment by katywatkins** [comment]
I'm not the original poster, but I ran into this exact same issue. Thank you so much for providing a solution @alicewriteswrongs!

**Comment by kvandenhaute** [comment]
Thanks for the input @alicewriteswrongs 

Going to try it, but I expect that it will work. But that does mean that something changed, no? Because it worked before.

But for me this solution is fine, I will update our documentation to make it clear how to run individual tests :)

**Comment by alicewriteswrongs** [comment]
Just curious, what version where you on previous where you could do `npm test -- testname`?

**Comment by kvandenhaute** [comment]
@alicewriteswrongs 3.1.0

**Comment by alicewriteswrongs** [comment]
Interesting, thanks for the info! I'm going to go ahead and close this issue since we've got a workaround and I don't believe that there is currently a CLI bug in Stencil. Thanks!
