### ISSUE TITLE
element attributes not converted to component props in ssr hydration.

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#440]
**Stencil version:**

```
 @stencil/core@0.2.0
```

**I'm submitting a:**

- [x] bug report
- [x] feature request

Not sure how it's supposed to work :/

**Current behavior:**

Following the [ssr docs for node-js](https://stenciljs.com/docs/server-side-rendering#node-js-example).

Given I have a `my-button` component 

```tsx
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'my-button'
})
export class MyButton {
  @Prop() size: string = 'default';
  render() {
    return <button class={`size-${this.size}`}><slot /></button>;
  }
}

```

When I hydrate a html string with this component
```js
const { Renderer } = require('@stencil/core/server');
/* snip... */
new Renderer(config).hydrate({
    html: '<my-button size="big">Test</my-button>'
}).then(results => console.log(results.html));
```

Then the result contains `<button class="size-default"`

**Expected behavior:**

But I expect the result to contain `<button class="size-big"`

**Steps to reproduce:**

https://github.com/Xiphe/stencil-attribute-to-prop-issue

~~**Related code:**~~

~~**Other information:**~~

**Comment by Xiphe** [comment]
Noticed that when I monkey-patch `attr: 'size'` in the compiled component, everything works as expected...

```js
Object.defineProperty(e, 'properties', {
  get: function() {
    return { size: { type: String, attr: 'size' } };
  },
}),
```

Got the Idea from [`proxy-instance.spec.ts`](https://github.com/ionic-team/stencil/blob/master/src/core/instance/test/proxy-instance.spec.ts#L11) - no idea how to use the official API to achieve this.

**Comment by adamdbradley** [comment]
Ok thanks for the report, we'll dig into this, thanks

**Comment by Xiphe** [comment]
Adding this spec to `hydrate.spec.ts` illustrates my intent but does not fail 😁 

```tsx
it('should use component attributes as props', async () => {
  const ctx: CompilerCtx = {};
  const registry: ComponentRegistry = {
    'ion-test': {
      componentConstructor: class {
        render() {
          return h('div', null, this.foo);
        }
      } as any,
    },
  };

  registry['ion-test'].componentConstructor.properties = {
    foo: { type: String, attr: 'foo' },
  };

  const opts: HydrateOptions = {
    html: `<ion-test foo="bar"></ion-test>`,
  };

  const hydrateResults = await hydrateHtml(config, ctx, registry, opts);

  expect(hydrateResults.diagnostics.length).toBe(0);

  expect(compareHtml(hydrateResults.html)).toEqual(
    compareHtml(`
    <html dir="ltr" data-ssr="">
      <head>
        <link rel="canonical" href="/">
      </head>
      <body>
        <ion-test foo="bar" data-ssrv="0" class="${config.hydratedCssClass}">
          <div data-ssrc="0.0"><!--s.0.0-->bar<!--/--></div>
        </ion-test>
      </body>
    </html>
  `)
  );
});
```

**Comment by Xiphe** [comment]
To me it seems to be a problem of the compiler but I can't find where the `@Prop` decorator is implemented/handled.

I'd assume that something like `@Prop({ attr: 'foo' })` should be possible but it isn't

**Comment by adamdbradley** [comment]
Yeah I think you're on the right track there. Should have it fixed soon...

**Comment by Xiphe** [comment]
Here is a running and isolated version of the problem (also updated to `@stencil/core@0.2.2`): https://github.com/Xiphe/stencil-attribute-to-prop-issue

**Comment by Xiphe** [comment]
Thanks for picking this up so fast. Let me know when I can help
