### ISSUE TITLE
Integrate Puppeteer for SSR/Prerendering/Testing

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil#442]
Replace JSDom with https://github.com/GoogleChrome/puppeteer

**Comment by romulocintra** [comment]
I @adamdbradley  any help on this !?  this should fix shadow dom on tests and few more other little bugs related with using dom inside node. Correct?

**Comment by adamdbradley** [comment]
@romulocintra yes it'll make our SSR and prerendering much easier to do, and we'll be able to add more tooling which is what I'm excited about.

**Comment by romulocintra** [comment]
@adamdbradley  just started looking some code to integrate with Puppeteer(PPT) and i  have few doubts/questions 

My initial approach is just use PPT for generate SSR and later solve other issues related with testing with shadow dom. 

At first look i need to replace mostly createDom function on node-dom  , and my initial approach is:

1. Run dev server with app
2. Crawl all application with PPT
3. Output html generated.
4. SSR html generated

If i do like this  i guess most of code on this folder won't be needed anymore... but we have a dependency on chrome , that i don't really know if is a problem.  Please if you have any different ideia let me know ... i already have something ... going on but not perfect yet

**Comment by splitinfinities** [comment]
Would you be able to have this run in multiple browsers as well? [web component tester](https://github.com/Polymer/web-component-tester) does a great job of allowing this experience, even offloading the tests to Sauce Labs.

**Comment by romulocintra** [comment]
CC @manucorporat

  Just pump up this issue , cause i think could be time to start looking again at ...  and i probably would have time to start looking at it again , but since we spoke  few things happen .. firefox headless etc ... should we start a discussion topic about the best solution for this !? 

@adamdbradley  @splitinfinities   should we open new issue to discuss tech design of this feature!?

**Comment by adamdbradley** [comment]
I think at this time we'll hold off on the upgrade. JSDom is working great for its purposes. So while I think we will move to puppeteer evetually, there's no real gain at the moment after going through a large refactor.

**Comment by balupton** [comment]
Would puppeteer eliminate the ability to use stencil in serverless environments? Which seems a important environment for server side rendered apps. Especially Zeit's Now and Cloudflare Workers.
