### ISSUE TITLE
feat: Custom attribute converter

### ISSUE THREAD

**Issue by TheCelavi** [ionic-team/stencil#4430]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

In year 2019 an feature request was opened: https://github.com/ionic-team/stencil/issues/1691 and last comment was set in year 2021. Issue is open, but closed for comments. 

In meantime, Lit, an alternative library provided this functionality: https://lit.dev/docs/components/properties/#conversion-converter

Maybe this is a high time for Stencil team to revisit this idea.

[ NOTE ]: I am sorry for opening new issue even though there is existing - however, I was unable to leave comment on existing one. Feel free to close issue immediately after you read it.

### Describe the Use Case

This feature is a extremely useful when web components are used in non-js context (server side rendering application), per example, as replacement for legacy jQuery plugins. 

I repeat, just to emphasise - extremely useful when web components are used outside javascript context. 

```
<app-datetime-picker value="2023-01-21"></app-datetime-picker>
```

### Describe Preferred Solution

Stencil can provide extension of current @Prop decorator, supporting both object oriented approach as well as functional approach:

```
export interface AttributeTransformer<T> {
     transform(attribute?: string): T
     reverse(value: T): string;
}

export type AttributeTransformFn<T> = (attribute?: string) => T;
export type AttributeReverseTransformFn<T> = (value: T) => string;
export type AttributeConverter<T> = AttributeTransformer<T> | [ AttributeTransformFn<T>,  AttributeReverseTransformFn<T> ];

// modified existing PropOptions interface
export interface PropOptions {
    attribute?: string | null;
    mutable?: boolean;
    reflect?: boolean;
    // addition
    converter?: AttributeConverter<T>;
}
```

### Describe Alternatives

No viable alternative available.

### Related Code

```

// Using OO approach

export class DateConverter implements AttributeTransformer<Date> {
          
          transform(attribute?: string): Date {
                 // .....
                 return new Date();
          }

          reverse(value: T): string {
                return value.toISOString();
          }
}

// ..... component code ...

@Prop({ converter: new DateConverter() })
public value: Date;

// Using functional approach

// ..... component code ...

@Prop({ converter: [
     (attribute?: string): Date => {
           // ...
           return new Date();
     },
     (value: Date): string => {
           return value.toISOString();
     }
] })
public value: Date;

```

**Comment by tanner-reits** [comment]
Hey @TheCelavi 👋 

Thanks for bringing this to our attention (again)! I'm sorry the original issue was locked. I went ahead and unlocked that so anyone can contribute to the conversation over there. That being said, I'm going to close this as a duplicate. If there's anything here you want to bring over to the original issue, that would be great and make it easy for the team to track when we evaluate the feature request.

Thanks again!
