### ISSUE TITLE
Paths aliases

### ISSUE THREAD

**Issue by bfmatei** [ionic-team/stencil#444]
**Stencil version:**
```
 @stencil/core@0.2.2
```

**I'm submitting a:**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Currently the compiler ignores the tsconfig file placed at the root of the project, so defining paths aliases is impossible. I created a separate branch on my fork which allows you to define the same structure of paths, but in the stencil.config.js file under the name "aliases". I would like to create a pull request in the master branch.

**Later edit:** I just tested my code. It is not ready yet (it needs the appropiate rollup plugin - i am writing one now).

**Expected behavior:**
Have a way to define paths aliases (via reading the tsconfig file or have an object named aliases in the stencil.config.js file).

**Steps to reproduce:**
1. Define paths object in tsconfig.
2. Try to use the alias in one of the project files

**Related code:**
Link to my branch: [https://github.com/bfmatei/stencil/tree/aliases-support](https://github.com/bfmatei/stencil/tree/aliases-support)

**Comment by adamdbradley** [comment]
I think what we could do is have the compiler use many of the values from the actual tsonfig.json file. Think that could work? There's a few typescript APIs we can use to pick apart the user's tsconfig, and when they are provided then we'd add them to the internal config options. I'd to stay away from adding more configuration to the stencil config. Think that'd work?

**Comment by bfmatei** [comment]
Hello Adam!

I agree with you regarding the config file. Additionally, it forces the user to duplicate code (declare the paths in tsconfig for IDEs and then declare them in stencil.config for Stencil).

I will start working on reading the user’s tsconfig and load a couple of flags (strict, strictNullChecking etc.) if nobody is assigned on this.

Unfortunately I have a couple of things which I need to take care @ work, so I hope to have something by the end of Sunday.

**Comment by jgw96** [comment]
@bfmatei thanks for offering to look into this issue, let us know if you need any help with the codebase!

**Comment by bfmatei** [comment]
Hello again!

I managed to read the user's tsconfig file using internal "convertCompilerOptionsFromJson".

The mechanism has a fallback for the default options just in case the user forgets something or he does not provide a valid tsconfig file.

I worked until now at the mechanism of resolving path aliases. Hopefully I will have it ready tonight and i will make a pull request in order to be analyzed :).

@jgw96: thanks, but you guys made a very solid architecture of the app and I didn't feel the need to ask for help. A code is like a joke: if you have to explain it, then it's bad xD. It's not the case here.

**Comment by adamdbradley** [comment]
Closed with https://github.com/ionic-team/stencil/pull/451

**Comment by MattMcFarland** [comment]
Sadly #451 doesn't solve the edge case of using baseUrl, which is a required param, I've created a new issue: #1291

**Comment by RafaelKr** [comment]
Unfortunately the paths are also ignored in the unit tests (*.spec.ts)

**Comment by t7tran** [comment]
This is an issue with Jest, I reckon. I fixed it by adding `moduleNameMapper` to `stencil.config.js` under `testing`. See [ts-jest docs](https://kulshekhar.github.io/ts-jest/docs/getting-started/paths-mapping/).
