### ISSUE TITLE
host option of the Component decorator only works with theme

### ISSUE THREAD

**Issue by ncardeli** [ionic-team/stencil#445]
**Stencil version:**
```
 @stencil/core@0.2.2
```

**I'm submitting a:**
- [X] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**
The `host` property of the Component decorator doesn't consider anything other than `theme`. For example, if I set the `role` property, the custom element doesn't have the `role` attribute:

If I do the following:
```
@Component({
  tag: 'my-button',
  styleUrl: 'button.scss',
  shadow: false,
  host: {
    role: 'button'
  }
})
```
I get something like this:

```
<my-button class="hydrated">...</my-button>
```

**Expected behavior:**
I expect to get this instead:

```
<my-button class="hydrated" role="button">...</my-button>
```

**Steps to reproduce:**
Set the host option of the Component decorator with attributes other than `theme`

```tsx
@Component({
  tag: 'my-button',
  styleUrl: 'button.scss',
  shadow: false,
  host: {
    role: 'button'
  }
})
```

**Other information:**
I took a look into the compiled code and found that the host data (stored in `hostMeta` variable) doesn't make it into the render function, that receives the empty `vnodeHostData` variable:

```
      if (instance.render || instance.hostData || hostMeta) {
        // tell the platform we're actively rendering
        // if a value is changed within a render() then
        // this tells the platform not to queue the change
        plt.activeRender = true;
        const vnodeChildren = instance.render && instance.render();
        let vnodeHostData;
        false;
        // tell the platform we're done rendering
        // now any changes will again queue
        plt.activeRender = false;
        false;
        // looks like we've got child nodes to render into this host element
        // or we need to update the css class/attrs on the host element
        // if we haven't already created a vnode, then we give the renderer the actual element
        // if this is a re-render, then give the renderer the last vnode we already created
        const oldVNode = elm._vnode || new VNode();
        oldVNode.elm = elm;
        // each patch always gets a new vnode
        // the host element itself isn't patched because it already exists
        // kick off the actual render and any DOM updates
                elm._vnode = plt.render(oldVNode, h(null, vnodeHostData, vnodeChildren), isUpdateRender, elm._hostContentNodes, cmpConstructor.encapsulation);
      }
```
Initializing `vnodeHostData` with the value of hostMeta might work, but I'm sure there are other cases to consider (for example, I noticed that when the `theme` option is set, the compiled code is different and `vnodeHostData` is set with an object for the `theme` option.

**Comment by adamdbradley** [comment]
For now we're going to limit the API footprint in order to keep stencil small and focused. We'll revisit this later if it becomes a larger issue. Thanks

**Comment by ncardeli** [comment]
Adam, in that case please consider removing the role attribute from the example of the host option of the Component decorator from this page: https://stenciljs.com/docs/decorators

How do you recommend setting attributes to the component, if the host option doesn't work?

Thanks!

**Comment by jthoms1** [comment]
For anyone coming to this issue looking for a new solution.  You should use the `hostData` function. An example can be seen here. https://github.com/ionic-team/ionic/blob/master/core/src/components/range-knob/range-knob.tsx#L37-L58
