### ISSUE TITLE
bug: Stencil with Typescript 5 doesnt Support Jest

### ISSUE THREAD

**Issue by mwaldheim** [ionic-team/stencil#4461]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.3.x

### Current Behavior

We upgraded to Stencil 3.3.x, and in the process we also upgraded directly to TypeScript 5.1.

Unfortunately, Jest, which is still required by Stencil in version 27.x, is not compatible with TypeScript 5 or newer.

### Expected Behavior

I would have expected that if Stencil was supported with TS 5.x, all dependencies in it, such as Jest, would finally be upgraded to the latest version. 

Because of this I could not go up to TS 5.1 now.

### Steps to Reproduce

Install Stencil 3.3.x with TS 5.1, Install Jest 29.x which is compatible with TS 5. Try to run Tests, it will failed

### Code Reproduction URL

-

**Comment by rwaskiewicz** [comment]
Hey @mwaldheim 👋 

Thanks for the bug report!

Based on your initial comments, I'm unsure what the nature of failure is with Jest 27 (e.g. whether type checking fails, tests fail, etc). Can you please do me a favor and create minimal reproduction case with Stencil 3.3 and Jest 27 that captures the issue that you're seeing? Thanks!

**Comment by mwaldheim** [comment]
Hello here is a repo to reproduce:

https://github.com/mwaldheim/stencil-jest-test

![image](https://github.com/ionic-team/stencil/assets/31657644/42010234-5ba2-41f3-9b43-1ce1f2a41da0)

**Comment by rwaskiewicz** [comment]
Thanks! You are correct that Stencil errors on Jest 29, as you previously stated. We are working on a new architecture that'll allow us to support newer versions of Jest, but that's functionality is not available at this time.

Can you help me understand how/why Jest 27 doesn't work for you? For context, both the Stencil and Ionic Framework repositories are using Stencil 3.3 and TypeScript 5.0 with Jest 27 successfully.

**Comment by mwaldheim** [comment]
Is there a timeline for when the update for this will come?

**Comment by rwaskiewicz** [comment]
> Is there a timeline for when the update for this will come?

I don't have an exact timeline, other than it is the next large scale effort the team will be working on. 

> Jest 27 does not actually support TS 5, but in our project it is important for security reasons that we always stay up to date.

If I understand correctly, the issue is that using Jest 29 is the problem with Stencil? It's unclear if you're having issues with Jest 27, or would rather prefer to use Jest 29 and that's resulting in the errors we've discussed?

**Comment by gavindoughtie** [comment]
FYI On my project, Jest 29 and Typescript 5 can be installed via overrides or --force, but moving from stencil 3.2.2 to 3.4.0 starts failing to compile jest tests.

**Comment by b3nab** [comment]
I was having the same issue, for the moment I solved it adding to my tsconfig.json this to the compilerOptions:
`
    "skipLibCheck": true
    `

**Comment by mwaldheim** [comment]
However, it cannot be the solution that we overwrite Jest. How to override the version without -f when installing?

**Comment by mwaldheim** [comment]
There is no way to upgrade Jest to version 29. Installation runs without errors, but the Jest tests cannot be run with it.

Every time I get the error that I should install Jest 27.

**Comment by rwaskiewicz** [comment]
> There is no way to upgrade Jest to version 29. Installation runs without errors, but the Jest tests cannot be run with it.
> 
> Every time I get the error that I should install Jest 27.

This is the current expected behavior. It is not ideal, and is being tracked by #3348. The team and I are beginning to work on this initiative to bring newer Jest-version support to Stencil, and appreciate everyone's patience here!
