### ISSUE TITLE
When doing a dev build AFTER a production build we need to clear the pre-rendered files

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil#450]
**Stencil version:**

```
 @stencil/core@0.2.2
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

- do a production build
- then do a dev build. Refresh on a route and notice that it is trying to pull the pre-rendered production build

**Steps to reproduce:**

- git clone stencil-beer
- npm run build
- npm run dev
- go to localhost:333/beers
- refresh and notice issue. Service worker will kick in and if you do a view source you will notice its the pre-rendered html

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by richrd** [comment]
I was just hit by this problem. I didn't realize what I had done wrong to make it stop refreshing the build. Good job I found this issue :+1:. I just removed the following directories and the reloading works again.
- `dist`
- `www/profile`
- `www/build`
