### ISSUE TITLE
bug: A slot gets the attribute hidden when it shouldn't

### ISSUE THREAD

**Issue by asik** [ionic-team/stencil#4523]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.0.0 (also seen on 3.4.0)

### Current Behavior

StencilJS is adding the attribute hidden to a slot that it shouldn't. I wrote a repro accessible at the url below. There's quite a bit going on, but if I tried to simplify it further, the problem went away, so this is as minimal as I could make it. Basically I have three components:
```
text-input
  input-base
    input-group
```

![image](https://github.com/ionic-team/stencil/assets/1631157/049bfbac-6ba2-4b3b-88ec-23ad392bec18)

For some reason, StencilJS adds the `hidden` attribute to the "message" slot in the `input-base` component.
I noticed that if I use `input-base` directly, it works as expected. It also works as expected if I add a wrapper div in `input-base`.

### Expected Behavior

The slot should not be hidden.

### Steps to Reproduce

Clone the repo, `yarn && yarn start`.

### Code Reproduction URL

https://github.com/asik/stencil-repro

**Comment by rwaskiewicz** [comment]
The fix for this issue has been released as a [part of today's Stencil v4.7.0 release](https://github.com/ionic-team/stencil/releases/tag/v4.7.0). Should the issue reappear, please feel free to open a new ticket. Thanks!
