### ISSUE TITLE
DashCase attribute are not watched

### ISSUE THREAD

**Issue by dpellier** [ionic-team/stencil#454]
**Stencil version:**

```
 @stencil/core@0.2.3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When using a Prop like:
`@Prop() maxLength: number;`
`@Watch('maxLength')` is never called
When looking in the code the `attributeChangedCallback` is never called, seems to be because the `HostElementConstructor.observedAttributes` is filled with 'maxLength' instead of 'max-length' on `defineComponent`.

**Expected behavior:**

When using a Prop like:
`@Prop() maxLength: number;`
`@Watch('maxLength')` should be called

**Steps to reproduce:**

```tsx
class SomeElement {
  @Prop() maxLength: number;

  @Watch('maxLength')
  protected onMaxLengthChange(_newValue: string): void {
    console.log('maxLength has changed');
  }
}
```

**Other information:**
Pull Request: https://github.com/ionic-team/stencil/pull/455

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us and thanks for the PR! I just tried to reproduce this locally and unfortunately could not. Mind posting a repo we could use to reproduce this?

**Comment by dpellier** [comment]
Sure, here is a small dummy component that reproduce the problem: https://github.com/dpellier/stencil-issue

**Comment by adamdbradley** [comment]
I think this may have been fixed in https://github.com/ionic-team/stencil/commit/73aabd247259221235791dc54c39d7469c279d11

Would you be able to test the latest and double check it's working?

**Comment by dpellier** [comment]
Indeed it work now with 0.3.0.
Thanks 👍

**Comment by adamdbradley** [comment]
great, thanks for testing!

**Comment by liho98** [comment]
I have the exactly same problem with the Author when using Stencil JS v1.17.3
