### ISSUE TITLE
App is disabled in Firefox developer edition.

### ISSUE THREAD

**Issue by ansarizafar** [ionic-team/stencil#457]
I am using Firefox developer edition 59.0b5 (64-bit) and I have enabled ES Module Imports but I am still getting this message

````
This app is disabled for this browser.
Developers:

    ES5 builds are disabled during development to take advantage of 2x faster build times.
    Please see the example below or our config docs if you would like to develop on a browser that does not fully support ES2015 and custom elements.
    Note that by default, ES5 builds and polyfills are enabled during production builds.
    When testing browsers it is recommended to always test in production mode, and ES5 builds should always be enabled during production builds.
    This is only an experiement and if it slows down app development then we will revert this and enable ES5 builds during dev.

Enabling ES5 builds during development:

    npm run dev --es5  

Enabling full production builds during development:

    npm run dev --prod  

Current Browser's Support:

    ES Module Imports: true
    Custom Elements: true
    fetch(): true
    CSS Variables: true

Current Browser:

    Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0  
````

**Comment by ansarizafar** [comment]
I am also seeing the same problem in Google Chrome. I am using @stencil/core@latest

````
This app is disabled for this browser.

Developers:

ES5 builds are disabled during development to take advantage of 2x faster build times.
Please see the example below or our config docs if you would like to develop on a browser that does not fully support ES2015 and custom elements.
Note that by default, ES5 builds and polyfills are enabled during production builds.
When testing browsers it is recommended to always test in production mode, and ES5 builds should always be enabled during production builds.
This is only an experiement and if it slows down app development then we will revert this and enable ES5 builds during dev.
Enabling ES5 builds during development:

    npm run dev --es5  
Enabling full production builds during development:

    npm run dev --prod  
Current Browser's Support:

ES Module Imports: true
Custom Elements: true
fetch(): true
CSS Variables: true
Current Browser:

    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36  
````

**Comment by jgw96** [comment]
Hello all! I am unfortunately unable to reproduce this issue currently, what are the repro steps? Are you all using one of the starters?

**Comment by ansarizafar** [comment]
I am using ionic pwa tool kit Here are the steps.
1. Git clone ionin pwa tool kit repo
2. npm  install
3. npm start

**Comment by giotramu** [comment]
In Stencil Component Starter and Firefox Developer Edition v59.0b6:

1. git clone
2. npm install
3. npm run dev or npm run start

![screen shot 2018-02-07 at 10 18 10](https://user-images.githubusercontent.com/14157578/35908376-bdc1967c-0bf0-11e8-9a8a-e6f1770bb342.png)

**Comment by ansarizafar** [comment]
I am still having the same problem with latest ver 0.4. Is there any solution available?

**Comment by jgw96** [comment]
Hello all! As @giotramu 's screenshot shows above ES modules are not currently fully implemented in firefox dev edition or firefox nightly which means that Stencil will try to use the ES5 build. We will revisit this issue in the future once these features make it into Firefox stable, which should not be long from now hopefully (: .

**Comment by ansarizafar** [comment]
I am getting same error in Google chrome. Please check above screenshot.

**Comment by lclaytont** [comment]
Also getting this error in chrome. Using @latest and following same steps listed above.

**Comment by joewoodhouse** [comment]
Same error here with all checks showing true
<img width="701" alt="screen shot 2018-04-03 at 13 36 02" src="https://user-images.githubusercontent.com/3168135/38249565-ffc2ea02-3743-11e8-8d5f-aca4cecec2bc.png">

**Comment by wojciemanhsd** [comment]
I have the same problem. I installed the stencil-app-starter and followed the described steps. After starting the app the shell confirmed that the build is finished. Starting firefox the above message is shown on the browser. Starting the same url in chrome it showed a blank screen. There are no error messages in the chrome debug console. debugging through the init-function of app.js the App.components seems to be an empty Array until the end.

**Comment by dacrypt** [comment]
I'm experiencing this problem with a production build.
1. ionic build --prod
2. open it in Firefox:

`This Stencil app is disabled for this browser.
Developers:

    ES5 builds are disabled during development to take advantage of 2x faster build times.
    Please see the example below or our config docs if you would like to develop on a browser that does not fully support ES2017 and custom elements.
    Note that by default, ES5 builds and polyfills are enabled during production builds.
    When testing browsers it is recommended to always test in production mode, and ES5 builds should always be enabled during production builds.
    This is only an experiement and if it slows down app development then we will revert this and enable ES5 builds during dev.

`

**Comment by ettoredn** [comment]
Same here with the latest firefox version, both in development and production builds!

**Comment by ettoredn** [comment]
Same here with Firefox latest. In production I get the following error:

TypeError: "r is null"
    render https://production.domain/components/build/js/my-components/etr-banners-2019.es5.entry.js:1
    Y https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
    Y https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
    c https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
    r https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
    o https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
 8 ETR-BANNERS-2019 my-components.core.pf.js:122:21125
    in https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
    Y https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
    Y https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
    c https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
    r https://production.domain/components/build/js/my-components/my-components.core.pf.js:122
    o https://production.domain/components/build/js/my-components/my-components.core.pf.js:122

This is definitely critical.
