### ISSUE TITLE
Decorating an extended element breaks in polyfilled browsers

### ISSUE THREAD

**Issue by mattdsteele** [ionic-team/stencil#459]
**Stencil version:**

```
 @stencil/core@0.2.3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
So I'd like to extract some common behavior from a few components. My intention was to use [mixin classes](https://github.com/Microsoft/TypeScript/pull/13743) to accomplish this. This pattern requires extending a class, e.g. `class Foo extends withBar()`

I'm finding that in polyfilled browsers (Firefox, IE11, Edge), extending any Stencil component causes weird errors, like failing to render at all. This is true even for simple things like `class Foo extends Object`. I don't see any compiler or run-time errors.

In Chrome it's working fine.

**Steps to reproduce:**
1. Clone and `npm i` https://github.com/mattdsteele/stencil-extended-elements
2. `npm run dev --es5`
3. Open in Firefox and note the `<my-component>` element, [which extends Object](https://github.com/mattdsteele/stencil-extended-elements/blob/master/src/components/my-component/my-component.tsx#L8), does not render.

**Other information:**

Other issues make me think this should be possible: https://github.com/ionic-team/stencil/issues/133#issuecomment-327350839, https://github.com/ionic-team/stencil/issues/272

**Comment by adamdbradley** [comment]
Related: https://github.com/Microsoft/TypeScript/issues/13819
