### ISSUE TITLE
Is there a trick to determine if a custom element has slots passed in?

### ISSUE THREAD

**Issue by wabi-habi** [ionic-team/stencil#4590]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

I've tried to write my own method, changed it and changed it again, but it's all flawed, there's no way to guarantee a complete success of the judgment, is there any official slot that I can get with any tricks in this piece?

### Describe the Use Case

I've tried to write my own method, changed it and changed it again, but it's all flawed, there's no way to guarantee a complete success of the judgment, is there any official slot that I can get with any tricks in this piece?

**Comment by wabi-habi** [comment]
I'm having a real headache too, I've changed my method of judgment no less than ten times, but it's still lacking!

**Comment by alicewriteswrongs** [comment]
Hey @wabi-habi, this looks like a support request or question. The best place to get a good answer for your question is likely the Stencil discord - you can join that conversation [here](https://chat.stenciljs.com/).

We prefer to keep the issue tracker just for bugs and feature requests, so the discord would be the best place to answer your question. Accordingly, I'm going to close this issue. Good luck!
