### ISSUE TITLE
Setting Boolean attributes with hostData() should add or remove the attribute depending on the value

### ISSUE THREAD

**Issue by nborelli** [ionic-team/stencil#461]
**Stencil version:**

```
 @stencil/core@0.2.3
```

**I'm submitting a:**

- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Setting a Boolean attribute sets the value to true or false and does not add or remove the attribute as expected.  For example
```
    hostData(): any {
        return {
            'aria-selected': this.isSelected
        };
    }
```
will set the `aria-selected` attribute to true if isSelected is true and false if it is false.
**Expected behavior:**

The expected behavior is that the attribute will be present is isSelected is true and the attribute will be removed when the value of isSelected is false.

**Steps to reproduce:**

**Related code:**

```tsx
    hostData(): any {
        return {
            'aria-selected': this.isSelected
        };
    }
```

**Other information:**

Other web component frameworks like Polymer and SkateJS handle attributes as I described above.

**Comment by nborelli** [comment]
FYI, This is how I set attribute values in a `@Watch`  decorator function.

```tsx
  @Watch('isCool')
  protected _reflectToAttribute(newValue: any, _oldValue: any, propertyName: string): void {
    updateAttributeFromProperty(this._element, propertyName, newValue);
  }
```
And from my util module:
```ts
export function updateAttributeFromProperty(element: HTMLElement, propertyKey: string, value: any): void {
    if (!element || !propertyKey) {
        return;
    }

    const attributeName = camelToKebabCase(propertyKey);
    const attributeValue = serializeAttributeValue(value);
    if (attributeValue !== undefined) {
        element.setAttribute(attributeName, attributeValue);
    } else {
        element.removeAttribute(attributeName);
    }
}

export function serializeAttributeValue(value: any): string | undefined {
    switch (typeof value) {
        case 'boolean':
            return value ? '' : undefined;

        case 'object':
            if (value instanceof Date) {
                return value.toString();
            } else if (value) {
                try {
                    return JSON.stringify(value);
                } catch {
                    return '';
                }
            }
            return undefined;

        default:
            return value !== null ? value.toString() : undefined;
    }
}
```

**Comment by adamdbradley** [comment]
Should be available as

```
@Prop({ reflectToAttr: true } )
```

We'll have better docs up soon, thanks
