### ISSUE TITLE
bug: type import paths are invalid for `dist-custom-elements` if `dir` matches location of `types` output location

### ISSUE THREAD

**Issue by tanner-reits** [ionic-team/stencil#4630]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.0.2

### Current Behavior

If you configure the `dist-custom-elements` output target to write to the default output location for Stencil (i.e. `dist`), the import paths for typedefs results in an invalid path:

```ts
{
  type: 'dist-custom-elements',
  dir: 'dist'
}
```

Results in import paths like: `.types/components`

### Expected Behavior

A config like this should result in a valid path like: `./types/components`

### Steps to Reproduce

Set this `dir` property on the `dist-custom-elements` output target in a Stencil component starter to `dist`

### Code Reproduction URL

https://github.com/ionic-team/stencil-component-starter

**Comment by D4RKAR117** [comment]
Same behavior around here, the path must be at least in my case `export * from './types'` on index.d.ts but instead i get `export * from '.types'` the `/` is missing

**Comment by tanner-reits** [comment]
This was resolved in [Stencil v4.0.3](https://github.com/ionic-team/stencil/releases/tag/v4.0.3). Please re-open this issue if you are still experiencing issues after updating.
