### ISSUE TITLE
Test fails with ReferenceError: _{method}_decorators is not defined when using custom decorators

### ISSUE THREAD

**Issue by Aadhisivam** [ionic-team/stencil#4631]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.0.2

### Current Behavior

*.spec.tsx test fails when using custom decorators in the component.
---
![image](https://github.com/ionic-team/stencil/assets/76022798/0501deb1-bb41-4f56-b025-e3d055c4bebb)

### Expected Behavior

Expect test should not fail due to decorators.

### System Info

```shell
System: node 18.16.1
    Platform: darwin (22.5.0)
   CPU Model: Apple M1 Pro (8 cpus)
    Compiler: /stencil-demo/stencil-demo/node_modules/@stencil/core/compiler/stencil.js
     Stencil: 4.0.2 😈
  TypeScript: 5.0.4
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.19.1
```

### Steps to Reproduce

Add a custom decorator and use within component, test script will fail with reference error.

### Code Reproduction URL

https://github.com/Aadhisivam/stencil-demo/

**Comment by rwaskiewicz** [comment]
Thanks! I'm going to label this to get it ingested into our internal issue tracking system!

**Comment by rwaskiewicz** [comment]
It looks like this bug can be traced back to v2.19.0 - updated the title of the bug accordingly

**Comment by Aadhisivam** [comment]
FYI, it worked previously in stencil **v3.0.1** with jest and jest-cli **v26.0.1.**

Sharing the dependencies of working tests, for your reference


```
"dependencies": {
    "@stencil/core": "3.0.1"
  },
  "devDependencies": {
    "@types/jest": "^25.2.3",
    "@types/node": "^16.18.11",
    "jest": "26.0.1",
    "jest-cli": "26.0.1",
    "puppeteer": "^20.7.3"
  },
```

@rwaskiewicz

**Comment by rwaskiewicz** [comment]
Thanks @Aadhisivam! Upon closer inspection, it looks like this was introduced in v3.2.0.

**Comment by louis-bompart** [comment]
After some troubleshooting, I do think the issues might either be in TypeScript or how the class decorator is expunged from the source code.
I managed to reproduce an identical behavior without Stencil here:
https://github.com/louis-bompart/typescript-standalone-troubles
