### ISSUE TITLE
feat: How to output as `vue2`?

### ISSUE THREAD

**Issue by wabi-habi** [ionic-team/stencil#4635]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

What if the component library for `stencil` is exported as `vue2`?

### Describe the Use Case

What if the component library for `stencil` is exported as `vue2`?

**Comment by rwaskiewicz** [comment]
Hey @wabi-habi 👋 

At one time, we did support Vue 2 using the Stencil Vue Output Target. However, in order to focus on the latest and greatest version of Vue, we no longer support Vue 2 and do not plan on reintroducing it at this time.

**Comment by wabi-habi** [comment]
> Hey @wabi-habi 👋
> 
> At one time, we did support Vue 2 using the Stencil Vue Output Target. However, in order to focus on the latest and greatest version of Vue, we no longer support Vue 2 and do not plan on reintroducing it at this time.

Ok, thanks, that will have to be supported by a third party!
