### ISSUE TITLE
Add publicUrl option to config

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#464]
**Stencil version:**

```
@stencil/core@future
```

**I'm submitting a:**

- [x] feature request

**Current behavior:**

> [the loader script does figure out the correct relative path which all lazy loaded files should use](https://github.com/ionic-team/stencil/issues/307#issuecomment-344462145)

Which is nice for most use cases and allows the config to not care about urls.
Drawback of this approach:

 - does not support async scripts
 - does not support moving the loader script relative to the lazy loaded files which might be useful for
    - inlining the loader
    - serving loader from different url (for CDN/caching reasons)

**Expected behavior:**

I would love to be able to provide a publicUrl via the config from which all lazy loaded files are loaded

**Steps to reproduce:**
 - build a stencil app
 - move the loader to another place
 - update index.html to still load the loader
 - see failing requests in network 

**Related code:**

[src/client/loader.ts#L28-L34](https://github.com/ionic-team/stencil/blob/a13c61b0539de3781856d343d10f788a77c2f16a/src/client/loader.ts#L28-L34)

**Other information:**

ref https://github.com/ionic-team/stencil/issues/307

If this sounds feasible to you, I'd love to work on a PR.

This is a sub-issue of https://github.com/ionic-team/stencil/issues/523

**Comment by jgw96** [comment]
Hey! We have a `publicPath` config https://stenciljs.com/docs/config that changes the path where the loader file looks for your components. Is that what you are looking for in this case?

**Comment by Xiphe** [comment]
As @adamdbradley mentioned in [his comment on #307](https://github.com/ionic-team/stencil/issues/307#issuecomment-344462145): "the publicPath which is hardcoded into the loader script is just a fallback"

So this config is not used - thats why I opened this issue.

**Comment by adamdbradley** [comment]
Should be fixed in the next release, thanks!
