### ISSUE TITLE
 JavaScript heap out of memory

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/stencil#466]
**Stencil version:**

```
 @stencil/core@0.2.3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

After a while of working on a project the build process kills itself with the following error in the console.
<--- Last few GCs --->

[112176:000001D23E903B20] 18021246 ms: Mark-sweep 1410.3 (1477.0) -> 1410.3 (1476.5) MB, 1282.4 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000008A482A5EC1 <JSObject>
    2: getResolvedMembersOrExportsOfSymbol(aka getResolvedMembersOrExportsOfSymbol) [D:\apps\TrackMyGiving\node_modules\typescript\lib\typescript.js:29288] [bytecode=000000EFE995E469 offset=113](this=000000C67C482311 <undefined>,symbol=000000935695BD71 <SymbolObject map = 0000001136EE24F9>,resolutionKind=00000198C9A765F9 <String[15]: resolvedMembers>)
    4: getMembersOfSymbol(aka getMembersOf...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Other information:**

From doing some Google-fu it may be related to generating sourcemaps or closure compiler, but this is a very vague error. I only started getting this after updating from an older version (v0.2.1) and this project is substantially sized, but this could all just be circumstantial.

**Comment by bfmatei** [comment]
This might actually be related to TypeScript itself (note `D:\apps\TrackMyGiving\node_modules\typescript\lib\typescript.js`).

As a workaround, you can try to run the build like this: `node --max_old_space_size=4096 --optimize_for_size --stack_size=4096 ./node_modules/.bin/stencil`

**Comment by jgw96** [comment]
@popcorn245 could you update to the latest (0.3.0-5) and see if you get the same errors? We recently refactored our build process.

**Comment by popcorn245** [comment]
I will try this today and let you know if I experience the issue again. Thanks Justin! ^_^

**Comment by popcorn245** [comment]
Have been using it all day and it hasn't crashed on me.  I will close the issue and reopen if it resurfaces. Thanks for the quick response guys! ^_^

**Comment by wangchongchong1007** [comment]
I have the same issue. Then I resolved it by this way.

modify the content of the stencil.cmd file (${yourProject}/node_modules/.bin/stencil.cmd) to :

```
@ECHO off
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

"%_prog%" --max_old_sapce_size=4096 "%dp0%\..\@stencil\core\bin\stencil" %*
ENDLOCAL
EXIT /b %errorlevel%
:find_dp0
SET dp0=%~dp0
EXIT /b
```
