### ISSUE TITLE
discussion: Name conflict between @Event decorator and Event JSX type

### ISSUE THREAD

**Issue by cam-narzt** [ionic-team/stencil#4681]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

I wonder if it might be wise to address the name collision between the `@Event` decorator and the `Event` JSX type. Currently if your component's file imports `Event` from `@stencil/core`, then accessing a property of the js `Event` class such as [Event.BUBBLING_PHASE](https://developer.mozilla.org/en-US/docs/Web/API/Event/eventPhase#value) throws an error unless you prefix the `Event` with `global.`. This is totally expected behaviour of typescript as the JSX `Event` type gets shadowed by the stencil `@Event` decorator when the latter is imported, but it's not exactly nice either.

### Describe the Use Case

It'd be nice to be able to use the js `Event` object and the stencil decorator in the same file more ergonomically.

### Describe Preferred Solution

I don't have a preferred solution as there are tradeoffs either way.

### Describe Alternatives

It might be possible to make the `@Event` decorator be exposed as a sum type of itself and the JSX `Event` type so it can stand in for the `Event` object, but i don't know what ts would transpile that into, so it might require using a `Proxy` object to delegate to the real `Event` which is less efficient than directly using `Event`...

It might be worth renaming the `@Event` decorator to not shadow the `Event` JSX type, but that would be a breaking change.

Doing nothing is also an option, it's not a bug after all.

### Related Code

```tsx
import { Component, Event, EventEmitter, Host, h } from '@stencil/core';

@Component({
    tag: 'pr-demo',
    styleUrl: 'pr-demo.css',
    shadow: true,
})
export class PrDemo {
    @Event() move: EventEmitter<null>;

    clickHandler(ev: MouseEvent){
        if (ev.eventPhase == Event.BUBBLING_PHASE) this.move.emit()
    }

    render() {
        return <Host onClick={this.clickHandler.bind(this)}>
            Hello world!
        </Host>;
    }
}
```

**Comment by rwaskiewicz** [comment]
Hey @cam-narzt 👋 

We agree that this ought to be addressed. We recently [added documentation](https://stenciljs.com/docs/events#event-decorator) with the workaround you suggested after a [discussion in the Stencil Discord](https://discord.com/channels/520266681499779082/1131898715217612911/1131898715217612911). However, this is a temporary measure.

We're currently operating under the belief that we'll be able to fix this in a non-breaking way once we begin supporting TypeScript 5.2 (which introduces a few useful changes to decorators). This would allow folks to import Stencil's `Event` under any alias/name they wish, e.g.
```ts
import { Event as StencilEvent } from '@stencil/core';
```
which is a current limitation of Stencil,[ tracked here](https://github.com/ionic-team/stencil/issues/3037) and [here](https://github.com/ionic-team/stencil/issues/3137). That is to say, it's on our minds & radar, but we're waiting for TS 5.2 to release for us to firm up our plans as to how we decide to tackle this. We're currently using #3037 to track this. As a result, I'm going to close this out. Thanks! (and please feel free to join the discussion on the Discord!)
