### ISSUE TITLE
bug: The `img` tag doesn't support the `crossOrigin` attribute

### ISSUE THREAD

**Issue by wabi-habi** [ionic-team/stencil#4685]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

^4.0.0

### Current Behavior

<img width="281" alt="iShot_2023-08-16_10 21 34" src="https://github.com/ionic-team/stencil/assets/99811051/3b183c4d-b45f-4e05-9a10-8f07cea3d2ae">

### Expected Behavior

Both `video` and `audio` are supported, I would expect `img` to support the `crossOrigin` attribute as well!

### Steps to Reproduce

<img width="281" alt="iShot_2023-08-16_10 21 34" src="https://github.com/ionic-team/stencil/assets/99811051/3b183c4d-b45f-4e05-9a10-8f07cea3d2ae">

### Code Reproduction URL

No Link

**Comment by wabi-habi** [comment]
> Thanks!

It will be updated in the next version yes? How do I temporarily fix this error in the current version?

**Comment by rwaskiewicz** [comment]
https://github.com/ionic-team/stencil/pull/4686 has been created to fix this issue. In the interim, you'll need to us `@ts-ignore` pragmas in order to suppress the error

**Comment by wabi-habi** [comment]
> #4686 has been created to fix this issue. In the interim, you'll need to us `@ts-ignore` pragmas in order to suppress the error

Okay, thanks.

**Comment by rwaskiewicz** [comment]
The fix for this issue has been released as a part of today's [Stencil v4.1.0 release](https://github.com/ionic-team/stencil/releases/tag/v4.1.0)

**Comment by wabi-habi** [comment]
> The fix for this issue has been released as a part of today's [Stencil v4.1.0 release](https://github.com/ionic-team/stencil/releases/tag/v4.1.0)

It's really great!
