### ISSUE TITLE
Custom relative wwwIndexHtml broken

### ISSUE THREAD

**Issue by finneganh** [ionic-team/stencil#469]
**Stencil version:**

```
 @stencil/core@0.2.3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
A relative `wwwIndexHtml` config value gets converted into the absolute path of `wwwDir`, ignoring `wwwIndexHtml` entirely. Additionally, since `wwwDir` is a directory, this means that no index.html file is written at all.

**Expected behavior:**
The index.html file is written to the path at `wwwIndexHtml` relative to `wwwDir`.

**Steps to reproduce:**
1. Set a `wwwIndexHtml` value in the config
1. Run `stencil build`
1. See that no `wwwIndexHtml` file is written

**Other information:**

Looks like a copy-paste error in `validate-paths.ts`. Submitting a PR to fix.

**Comment by adamdbradley** [comment]
merged 🎉 thanks!
