### ISSUE TITLE
bug: Stencil is not finding dependencies in Functional Components

### ISSUE THREAD

**Issue by tfrijsewijk** [ionic-team/stencil#4702]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.3.1

### Current Behavior

I have a Stencil component that references another Stencil component in a Functional Component:

```
✅ my-parent -> my-icon
❌ my-parent -> MyFunctionalComponent -> my-icon
```

Stencil does not create a dependency graph for `my-parent` that contains a reference to `my-icon`.

### Expected Behavior

I would expect that transitive dependencies are also created through Functional Components

### Steps to Reproduce

* Create a parent and child Stencil component.
* In the parent call the child
* ✅ The dependency graph contains `my-parent -> my-child`
* Move the call to `my-child` to a Functional Component and call the Functional Component in the parent
* ❌ Notice the dependency graph for `my-parent` does not contain a reference to `my-child`.

### Code Reproduction URL

https://github.com/dso-toolkit/dso-toolkit/pull/2284

### Additional Information

This is problematic not only for documentation purposes, but also for lazy loading. The runtime loader does not load all necessary dependencies for a parent component.

I've run into this problem in my own project. The links below are talking about `dso-viewer-grid -> dso-icon`:
* Here you can see the dependency (`dso-icon`) removed from the parent component (`dso-viewer-grid`): https://github.com/dso-toolkit/dso-toolkit/pull/2284/files#diff-d6730c851abeb3a1e61c5b6f7d5d8979bd53b4125456479ff5223601521ab702L62
* Here you can see the new Functional Component: https://github.com/dso-toolkit/dso-toolkit/pull/2284/files#diff-6a334b4bb2c20eb01366edfdf8054fdb1ace0bbaa7cf826267f6ec8b76f04e26R12
* Here you can see the new Functional Component called from the parent: https://github.com/dso-toolkit/dso-toolkit/pull/2284/files#diff-27d2f695142d8314270bc85e9dcdcb1e167e93c08ad54eead5d2706532bdadf9R209
* Here you can see the previous call to `<dso-icon>`: https://github.com/dso-toolkit/dso-toolkit/pull/2284/files#diff-27d2f695142d8314270bc85e9dcdcb1e167e93c08ad54eead5d2706532bdadf9L212

**Comment by tfrijsewijk** [comment]
> First off, you're not expecting the functional components to show up in the dependency graph, correct? You're just expecting the graph to show other Stencil components that the functional component might be outputting?

Correct. I'm using Functional Components only to make my Stencil components smaller, I don't use Functional Components to "share" templates.

> Second, where are you seeing the graph get generated incorrectly? I tested things out in a new Stencil project running Stencil v4 and v3.3.1 (version you reported), and the compiler was resolving dependencies through functional components correctly in the compiler metadata we capture and in the generated documentation for the `docs-json` and `docs-readme` output targets. There very well could be something I'm overlooking, so if you can point me somewhere specific I'd be happy to take a look!

The best I can do is refer you to the commits I mentioned in my first message. Here you can see a reference being removed purely because I moved the call to a Web Component to a Functional Component: https://github.com/dso-toolkit/dso-toolkit/pull/2284/files#diff-d6730c851abeb3a1e61c5b6f7d5d8979bd53b4125456479ff5223601521ab702L62

Thanks for looking into this! 👋

**Comment by tanner-reits** [comment]
@tfrijsewijk I spent some more time playing around with this and am still not experiencing what you're seeing. I tried chaining functional components, placing functional components in conditionally rendered blocks, including multiple functional components, etc.. These were all patterns I noticed looking through the commit you pointed me to.

Have you or would you be able to reproduce the issue at a smaller scale? Even if you are able to lift a subset of the components out of your project and get the same result.

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk I spent some more time playing around with this and am still not experiencing what you're seeing. I tried chaining functional components, placing functional components in conditionally rendered blocks, including multiple functional components, etc.. These were all patterns I noticed looking through the commit you pointed me to.
> 
> Have you or would you be able to reproduce the issue at a smaller scale? Even if you are able to lift a subset of the components out of your project and get the same result.

Yes, please give me a week or two.

But if I understand you correctly: If you call a Web Component through in a Functional Component in another Web Component, you are seeing the two Web Components referend in both readme.md files?

```
my-web-component -> MyFunctionalComponent -> my-other-web-component
```

my-web-component/readme.md:

```
Depends on

* my-other-web-component
```

my-other-web-component

```
Uses

* my-web-component
```

Because I am not seeing this behavior, but I will provide a reprorepo.

**Comment by tanner-reits** [comment]
Yep, I'm seeing the expected output you listed above. Our automation may close this issue in the meantime until you can provide a repo, but feel free to re-open it once you have one!

**Comment by tanner-reits** [comment]
Closing this out as it's been a while since any activity happened here. Feel free to re-open this with a reproduction case if it's still an issue!

**Comment by tfrijsewijk** [comment]
@tanner-reits In your tests, were your Function Components in separate files? Because mine are, and when I move the Function Component to the Stencil Component file, I immediately get my dependencies back:

![image](https://github.com/ionic-team/stencil/assets/9696261/00e09c87-e57e-404b-bff3-8559e5e66b3f)

**Comment by tfrijsewijk** [comment]
@tanner-reits Hi! I would like to have this issue re-opened, but I don't have the permission to do so. Could you please re-open this issue?

**Comment by tanner-reits** [comment]
@tfrijsewijk I had them in different files when testing, yes.

**Comment by tfrijsewijk** [comment]
I'm creating a reproduction repository, but I'm having a hard time reproducing my bug 😄 

The commits I'm refering to have been garbage collected by GitHub, since there is no branch anymore. I'll post an update next Friday.
