### ISSUE TITLE
Stencil components duplicate inside angular component when ngIf is used

### ISSUE THREAD

**Issue by sebastien-yoobic** [ionic-team/stencil#471]
**Stencil version:**

```
  "@stencil/core": "0.2.3",
```
**Angular version:**
```
Angular CLI: 1.6.6
Node: 8.9.4
OS: darwin x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```
**I'm submitting a:**

- [ X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When a stencil component is inside an Angular component using *ngIf on the angular component leads to the duplication of the stencil component.

**Expected behavior:**

Stencil components do not duplicate.

**Steps to reproduce:**

Steps if you want to reproduce it: 
  ->Create a stencil component,
  ->Create an Angular component with `<ng-content>`
  ->Insert the stencil component inside the angular component
  ->Play with a boolean linked to an *ngIf directive in the angular component

**Related code:**

Stencil component
```tsx
import { Component, Prop } from "@stencil/core";

@Component({
  tag: "my-button",
  styleUrl: "my-button.scss"
})
export class MyButton {
  @Prop() name: string;

  render() {
    return (
      <div>
        <p>I am the button: {this.name}</p>
      </div>
    );
  }
}
```

Angular comp 
```
<div *ngIf="visible">
    <p>This is the content of the component</p>
    <ng-content></ng-content>
</div>
```
```

@Component({
  selector: "app-comp-hidden",
  templateUrl: "./comp-hidden.component.html",
  styleUrls: ["./comp-hidden.component.scss"]
})
export class ComponentHidden implements OnInit, OnDestroy {
  @Input() visible: boolean;
  
  constructor() {}

  ngOnInit() {}

  ngOnDestroy() {}
}
```

App Component html
```
<app-comp-hidden [visible]="hidden">
  <my-button name="Button"></my-button>
</app-comp-hidden>
```
**Other information:**

I have created a repo which reproduces the bug here: https://github.com/sebastien-yoobic/stencil-angular-duplicate

**Comment by danbucholtz** [comment]
Hi @sebastien-yoobic,

Thank you for the issue. I unfortunately cannot reproduce it with any of the `@ionic/core` components. If this is still an issue, please open another issue including a link to this issue and a sample project where I can easily see the issue. We appreciate it, and have a good day.

Thanks,
Dan
