### ISSUE TITLE
Unable to run example app

### ISSUE THREAD

**Issue by promethyttrium** [ionic-team/stencil#473]
**Stencil version:**

```
 @stencil/core@0.2.3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Unable to run. Page hangs with "Initializing First Build..." message

**Expected behavior:**
Able to see example app

**Steps to reproduce:**
Just did everything in the Getting started guide

**Related code:**

Console output
```
$ npm start

> @stencil/starter@0.0.1 start E:\.learn\stenciljs\widgets
> npm run dev


> @stencil/starter@0.0.1 dev E:\.learn\stenciljs\widgets
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

[35:52.6]  @stencil/core v0.2.3
[35:52.7]  build, app, dev mode, started ...
[35:52.7]  compile started ...
[35:55.3]  compile finished in 2.68 s

[ ERROR ]  typescript: E:/.learn/stenciljs/widgets/node_modules/@stencil/core/dist/testing/index.d.ts, line: 8
           Cannot find module '../core/renderer/h'.

      L7:  export * from './transpile';
      L8:  export { h } from '../core/renderer/h';

[35:55.6]  build failed, watching for changes... in 2.94 s
```

**Comment by jgw96** [comment]
Hello! What operating system are you running this on? Also what version of node?

**Comment by promethyttrium** [comment]
Thanks for replying. I'm on Windows 10 running node v8.4.0.

**Comment by jgw96** [comment]
@promethyttrium mind updating to @stencil/core@0.3.0 and trying again? I cannot reproduce this on my windows 10 machine.

**Comment by promethyttrium** [comment]
![image](https://user-images.githubusercontent.com/3183017/35897024-39052092-0b8d-11e8-8504-037b940538e9.png)

**Comment by promethyttrium** [comment]
That error does not appear on a different system running Node 6.x.

**Comment by jgw96** [comment]
@promethyttrium unfortunately we are still unable to reproduce this issue. I am running node 8 on the latest build of windows 10 on my Surface Book. I would recommend deleting your node_modules and package-lock.json and doing a fresh npm install. Unfortunately because we are unable to reproduce this issue we are going to close this issue for now. Thanks for using Stencil!

**Comment by yesobo** [comment]
I was able to reproduce the issue in windows 10 with node 8.9.4, npm 5.6.0 and @stencil/core 0.4.3
![missing_module](https://user-images.githubusercontent.com/1735109/36116615-230ca2de-1037-11e8-98cc-74c247993c79.png)
