### ISSUE TITLE
stop using readFileSync

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#474]
**Stencil version:**

```
 @stencil/core@<=0.3.0
```

**I'm submitting a:**

- [x] feature request

**Current behavior:**
Given I want to hook into the file system and provide stencil files dynamically

When `fs.readFileSync` is heavily being used thought the codebase 
Then I can not easily do async operations based on a file being read

**Expected behavior:**

`fs.readFile` should be used everywhere.

**Other information:**

I know that this is probably out of scope, a very niche problem and surely not an intended use-case. Just wanted to bring this up since it would help with my project. I'd happily work on a PR for this.

**Comment by adamdbradley** [comment]
readFileSync is rarely used, and really only used which is required by typescript. We use our InMemoryFS https://github.com/ionic-team/stencil/blob/master/src/util/in-memory-fs.ts to rarely touch the file system, and cache it's information. Here are some unit test around our fs: https://github.com/ionic-team/stencil/blob/master/src/util/test/in-memory-fs.spec.ts
