### ISSUE TITLE
Import/use ionicons v4

### ISSUE THREAD

**Issue by Aaron-Sterling** [ionic-team/stencil#475]
**Stencil version:**
any

**I'm submitting a:**
- [ x ] feature request

**Current behavior:**
I can't figure out how to use an Ionicon v4 in a Stencil component I am building.

**Expected behavior:**
It sounds as though Ionicons are being ported in by default? Has that already happened and I just can't get it? Or is there something I need to do?

**Steps to reproduce:**
I looked at the documentation and got confused. I'm pretty sure I could reproduce that behavior!

I've read [ionicons #499](https://github.com/ionic-team/ionicons/issues/499) a few times, but I couldn't quite get how to connect it with Stencil.

Thank you!

**Comment by bfmatei** [comment]
It's simple. Just make sure you use the next version of ionicons: `npm install --save ionicons@next`, add `{ name: 'ionicons' }` to `collections` array in `stencil.config.js` and then just use the icons as described `<ion-icon name="star"></ion-icon>`

**Comment by manucorporat** [comment]
@bfmatei is right!
```
npm install --save ionicons@next
```
and:

https://github.com/ionic-team/ionic/blob/6d52b722e40811fd5b83d71bffbe7fa1ba81ae3b/packages/core/stencil.config.js#L46-L48

**Comment by Aaron-Sterling** [comment]
FYI, I posted a follow-up [support question](https://forum.ionicframework.com/t/stencil-how-to-import-exactly-two-v4-ionicons-into-a-stencil-component/120561?u=aaronsterling) on the forum, but I don't think anyone knows the answer there yet! So if anyone here does and you have time to pop over there, please do.

**Comment by leon-tno** [comment]
Collections is now deprecated, any idea how to import ionicons to the app's root component ?   
```
As of v0.6.0, "config.collections" has been deprecated in favor of standard ES module imports. Instead of
           listing collections within the stencil config, collections should now be imported by the app's root
           component or module. The benefit of this is to not only simplify the config by using a standards approach
           for imports, but to also automatically import the collection's types to improve development. Please remove
           "config.collections" from the "stencil.config.js" file, and add this import to your root component or root
           module: import 'ionicons';
```

**Comment by Dellos7** [comment]
I was able to make it working by adding `import 'ionicons';` in my root component. Also works adding it in `src/components.d.ts`.

**Comment by ihackalot** [comment]
You can import Ionicons from within the `globalScript` config property.

1. Install Ionicons: `npm install ionicons`
2. In `stencil.config.ts`: Add `globalScript: 'src/global/app.ts'` to the config object.
3. In `src/global/app.ts`: Add `import 'ionicons'`
4. Restart/Rebuild.

**Comment by gino8080** [comment]
how to build ONLY the used icons and NOT all??

**Comment by miqmago** [comment]
Using ionicons@4.6.3 icons are being loaded but they do not appear:

Inspected html is the following one:

```html
<ion-fab-button class="md ion-activatable ion-focusable hydrated">
    <ion-icon role="img" class="md hydrated" aria-label="add"></ion-icon>
</ion-fab-button>
```
With shadow dom:
![Captura de Pantalla 2020-01-22 a les 14 30 19](https://user-images.githubusercontent.com/1849488/72898217-f31af000-3d23-11ea-87d6-ea92d4d7e88f.png)


```css
.icon-inner, svg {
    display: block;
    height: 100%;
    width: 100%;
}
.close-icon, ::slotted(ion-icon) {
    font-size: 24px;
}
::slotted(ion-icon) {
    line-height: 1;
}
```

Also the image seems to have been correctly downloaded:

![Captura de Pantalla 2020-01-22 a les 14 19 30](https://user-images.githubusercontent.com/1849488/72897545-80f5db80-3d22-11ea-9687-172ae501498d.png)

But in fact the button is empty:

![Captura de Pantalla 2020-01-22 a les 14 21 24](https://user-images.githubusercontent.com/1849488/72897606-9e2aaa00-3d22-11ea-984c-829873058709.png)


I'm using:

"@stencil/core": "^1.8.3",
"ionicons": "^4.6.3",

And in app.ts:
```ts
import '@ionic/core';
import 'ionicons';
```

And stencil.config.ts:
```ts
export const config: Config = {
    outputTargets: [{
        type: 'www',
        serviceWorker: null,
    }],
    globalScript: `src/global/app.ts`,
    globalStyle: 'src/global/app.css',
};
```

**Comment by gino8080** [comment]
same here :(

> Using ionicons@4.6.3 icons are being loaded but they do not appear:
> 
> Inspected html is the following one:
> 
> ```
> <ion-fab-button class="md ion-activatable ion-focusable hydrated">
>     <ion-icon role="img" class="md hydrated" aria-label="add"></ion-icon>
> </ion-fab-button>
> ```
> 
> With shadow dom:
> ![Captura de Pantalla 2020-01-22 a les 14 30 19](https://user-images.githubusercontent.com/1849488/72898217-f31af000-3d23-11ea-87d6-ea92d4d7e88f.png)
> 
> ```css
> .icon-inner, svg {
>     display: block;
>     height: 100%;
>     width: 100%;
> }
> .close-icon, ::slotted(ion-icon) {
>     font-size: 24px;
> }
> ::slotted(ion-icon) {
>     line-height: 1;
> }
> ```
> 
> Also the image seems to have been correctly downloaded:
> 
> ![Captura de Pantalla 2020-01-22 a les 14 19 30](https://user-images.githubusercontent.com/1849488/72897545-80f5db80-3d22-11ea-9687-172ae501498d.png)
> 
> But in fact the button is empty:
> 
> ![Captura de Pantalla 2020-01-22 a les 14 21 24](https://user-images.githubusercontent.com/1849488/72897606-9e2aaa00-3d22-11ea-984c-829873058709.png)
> 
> I'm using:
> 
> "@stencil/core": "^1.8.3",
> "ionicons": "^4.6.3",
> 
> And in app.ts:
> 
> ```ts
> import '@ionic/core';
> import 'ionicons';
> ```
> 
> And stencil.config.ts:
> 
> ```ts
> export const config: Config = {
>     outputTargets: [{
>         type: 'www',
>         serviceWorker: null,
>     }],
>     globalScript: `src/global/app.ts`,
>     globalStyle: 'src/global/app.css',
> };
> ```
