### ISSUE TITLE
PostCSS files are not triggering rebuild

### ISSUE THREAD

**Issue by bfmatei** [ionic-team/stencil#476]
**Stencil version:**
```
 @stencil/core@v0.3.0-5
```

**I'm submitting a:**
- [x] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
PostCSS files (.pcss) are not triggering rebuilds.

**Expected behavior:**
PostCSS files (.pcss) should trigger rebuilds.

**Steps to reproduce:**
Create a component and point `styleUrl` to a .pcss file. Edit the pcss file and observe the output of the build process.

**Related code:**
```tsx
const WEB_DEV_EXT = ['js', 'jsx', 'html', 'htm', 'css', 'scss', 'sass', 'less', 'styl'];
```

**Other information:**
I will create a PR in a few minutes with a fix for this.

**Comment by bfmatei** [comment]
PR created: https://github.com/ionic-team/stencil/pull/477

**Comment by adamdbradley** [comment]
merged 🎉
