### ISSUE TITLE
platform-client-legacy.ts needs startsWith polyfill

### ISSUE THREAD

**Issue by finneganh** [ionic-team/stencil#481]
**Stencil version:**

```
 @stencil/core@0.3.0-5
```

**I'm submitting a:**

- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Under IE Edge, Stencil throws an exception on load because there's no implementation for startsWith.

**Expected behavior:**
Stencil should include a startsWith polyfill to work in IE.

**Steps to reproduce:**

1. Clone https://github.com/ionic-team/stencil-component-starter.git
1. `npm install @stencil/core@0.3.0-5`
1. Edit `package.json` to change `--dev` to `--prod`
1. `npm run dev` and load in IE

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
Good catch, would you be able to submit a PR for this?

**Comment by bfmatei** [comment]
There might be a discussion about which version of polyfill we want to use: the one available on the Mozilla page or the more complex one built by Mathias here: https://github.com/mathiasbynens/String.prototype.startsWith

Strictly from my pov I would go for the Mozilla one or the v0.1.0 from Mathias (available [here](https://github.com/google/traceur-compiler/blob/315bdad05d41de46d25337422d66686d63100d7a/src/runtime/polyfills/String.js#L19-L37)) as v2 is extending support for IE8 and other small things which might represent an overhead.

**Comment by manucorporat** [comment]
@bfmatei Since we are support up to IE11, I think it makes more sense to choose the smallest:

https://github.com/google/traceur-compiler/blob/315bdad05d41de46d25337422d66686d63100d7a/src/runtime/polyfills/String.js#L19-L37

but let's see what @adamdbradley thinks

**Comment by finneganh** [comment]
I sent a PR, #485, which you can use or not.

I picked the Mozilla polyfill, since it's small and I think the use case here is straightforward.
