### ISSUE TITLE
Property 'outline' does not exist on type 'ButtonHTMLAttributes'

### ISSUE THREAD

**Issue by kael** [ionic-team/stencil#482]
**Stencil version:**

```
 @stencil/core@0.3.0-5
 @ionic/core@0.0.2-48
 NPM 5.6.0
 Node v8.9.4
 OS Ubuntu 16.04.3 LTS
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Using Ionic buttons, the `outline` attribute is not recognized by the compiler:

```jsx
  render() {
    return(
      <ion-item>
        Left Icon Button
        <button ion-button color="secondary" outline>Secondary Outline</button>
      </ion-item>
    );
  }
```

The compiler returns:
```bash
[ ERROR ]  typescript: src/components/my-component/my-component.tsx, line: 85
           Property 'outline' does not exist on type 'ButtonHTMLAttributes'. 

     L84:  Left Icon Button
     L85:  <button ion-button outline item-end icon-left>
     L86:    <ion-icon name="star"></ion-icon>
```

Using the `button-outline` attribute (as seen @ https://github.com/ionic-team/stencil/issues/37) fixes the error but the button is not displayed correctly with Chrome 64.0.3282.140 (see the screenshot).
**Expected behavior:**

**Steps to reproduce:**

**Other information:**

![ion-button](https://user-images.githubusercontent.com/2463/35853668-734b21b6-0b2e-11e8-86dd-6bdafac44c59.png)

BTW, is there a way to generate an IDL defintions documentation of Ionic elements ? (The documentation of the button API on the site doesn't seem to correspond to the API of the element).

**Comment by manucorporat** [comment]
https://github.com/ionic-team/ionic/tree/core/packages/core/src/components/button

Stencil generates the JSX types, but it is not longer `<button>` that's because each web component needs his own tag:

```html
<ion-button color="secondary" fill="outline">Secondary Outline</ion-button>
```

Docs for ionic-core (ie ionic 4):
https://github.com/ionic-team/ionic/tree/core/packages/core/src/components/button
