### ISSUE TITLE
@Prop({ context:'isServer' }) not working

### ISSUE THREAD

**Issue by BoHellgren** [ionic-team/stencil#483]
**Stencil version:**

stencil/starter@0.0.1 D:\newPWA\my-app
-- stencil/core@0.2.3

**I'm submitting a:**

- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

@Prop({ context:'isServer' }) private isServer: boolean;
isServer is undefined

**Expected behavior:**

should set isServer to true or false

**Steps to reproduce:**
 I downloaded stencil-app-starter. I then added only two lines to app-profile.tsx:

`export class AppProfile {
  
  @Prop({ context:'isServer' }) private isServer: boolean;
  @Prop() match: MatchResults;
 
  render() {
    console.log('this.isServer:', this.isServer);`

**Other information:**

**Comment by BoHellgren** [comment]
@stencil/core v0.3.0 made no difference

**Comment by adamdbradley** [comment]
Thanks for filing the issue, should be fixed in the next release. Thanks!
