### ISSUE TITLE
bug: dist/types not generated when extending tsconfig.json with multiples components

### ISSUE THREAD

**Issue by dpellier** [ionic-team/stencil#4834]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.2.1

### Current Behavior

We have a monorepo with multiple components looking like:
```
packages/
    components/
        component1/
            ...
            stencil.config.ts
            tsconfig.json
        component2/
            ...
            stencil.config.ts
            tsconfig.json
        ...
        tsconfig.json
```

The root `tsconfig.json` contains the `declaration` option:
```
{
    ...
    "compilerOptions": {
        "declaration": true
    },
}
```

Each component `tsconfig.json` extends this config:
```
{
    "extends": "../tsconfig.json",
    "include": [
        "src"
    ]
}
```

When we build a component using `stencil build --docs --prod --config stencil.config.ts` we get two different results.

If the project has just one component, the `dist/types` dir is generated correctly
ex:
```
component1/
    src/
        my-component/
```

If the project has multiple components, the `dist/types` dir is not generated
ex:
```
component2/
    src/
        my-component1/
        my-component2/
```

If we run the build command a second time, the `dist/types` is correctly generated, but not on first build.

When running the `--verbose` build we see the following regarding declarations:
```
generate types started ...  MEM: 593.2MB
generated app types started ...  MEM: 593.2MB
generated app types started ...  MEM: 593.2MB
generateAppTypes: dist/types/components.d.ts has changed  MEM: 593.2MB
generated app types finished: dist/types/components.d.ts in 1 ms  MEM: 593.2MB
generateAppTypes: dist/types/components.d.ts has changed  MEM: 593.2MB
generated app types finished: dist/types/components.d.ts in 4 ms  MEM: 593.2MB
generate types finished in 4 ms  MEM: 593.2MB
```

### Expected Behavior

The expected behaviour would be that the `dist/types` generation works for each component regardless of the number of sub-component inside.

### System Info

```shell
System: node 18.17.1
    Platform: darwin (22.6.0)
   CPU Model: Apple M1 (8 cpus)
    Compiler: /Users/.../node_modules/@stencil/core/compiler/stencil.js
       Build: 1694444858
     Stencil: 4.2.1 😀
  TypeScript: 5.1.6
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.19.4
```

### Steps to Reproduce

- create a component with a sub dir
- create a component with two sub dir
- setup a tsconfig with `declaration: true` at root level
- setup a tsconfig on each component that extends the root one
- run `stencil build --docs --prod --config stencil.config.ts` on both
- check if the `dist/types` has been generated

The stencil config is the same for both components:
```
{
  devServer: { startupTimeout: 30000 },
  namespace: '...',
  outputTargets: [
    { dir: 'dist', esmLoaderPath: '../loader', type: 'dist' },
    {
      dir: 'custom-elements',
      copy: [...],
      generateTypeDeclarations: true,
      includeGlobalScripts: false,
      type: 'dist-custom-elements'
    },
    { dir: 'dist/docs', type: 'docs-readme' },
  ],
  plugins: [
    { name: 'inlineSvg', transform: [Function: transform] },
    {
      name: 'postcss',
      pluginType: 'css',
      transform: [Function: transform]
    },
    {
      name: 'sass',
      pluginType: 'css',
      transform: [Function: transform]
    }
  ],
  sourceMap: false,
  tsconfig: 'tsconfig.json'
}
```

### Code Reproduction URL

I've tried to reproduce it on a smaller app, but without success so far.

You can reproduce it on this branch on our project : https://github.com/ovh/design-system/tree/refactor/stencil4
- clone the branch
- run `yarn` at root (need node 18.17+)
- go to `packages/components/select`
- remove the `compilerOptions` from the `tsconfig.prod.ts`
Either:
- run `yarn build:stencil`
- check `dist` dir, `types` should be missing
Or:
- run  `yarn build:prod`
- the build should fails because `dist/types` are missing

At first I thought that adding the `declaration` in the lowest tsconfig fixed the issue and it did but locally only, it fails the same on the CI. It looks like some kind of racing issue when generating types for two sub components.

**Comment by rwaskiewicz** [comment]
Thanks @dpellier! Can you do me a favor and `@`- me when you have the repro case up?

**Comment by rwaskiewicz** [comment]
Hey @dpellier 👋 

Thanks! Unfortunately, this is a little too large of a project for us to dive into. Would you be able to take another crack at putting together a smaller minimal reproduction case?
