### ISSUE TITLE
Differentiate rerender caused by Prop update vs State update

### ISSUE THREAD

**Issue by Aaron-Sterling** [ionic-team/stencil#484]
**Stencil version:**
any

**I'm submitting a:**

- [ x  ] feature request

**Current behavior:**

I'd like a clean way to differentiate between rerender caused from outside, and from inside. Right now, I can do this by saving the values of the Props upon first load, and checking in a life cycle hook whether the new Prop values are === to the old Prop values. 

**Expected behavior:**
A cleaner way to do this.

**Comment by manucorporat** [comment]
can you develop your use case? I want to understand first why you need this

**Comment by Aaron-Sterling** [comment]
The goal is to avoid the possiby-expensive step of initializing States from the input of Props. (For example, a serarch component where array manipulation is immutable.)  If the Props have not changed, I only need to worry about the States that changed during the most recent render. If the Props have changed, then I need to refire everything.

Right now, I am handling this with the following code, which I would prefer not to use as boilerplate:

```
componentWillLoad() {
    this.firstRun();
  }

  firstRun() {
    this.backupOriginalProps();
    this.initializeInternalState();
  }

  backupOriginalProps() {
    // initialize private variable backups of original Props
  }

  initializeInternalState() {
    // initialize States based on Props
  }

  propsHaveChanged(): boolean {
    // return true if current Props are not === to the private backups
  }
  componentDidLoad() {
    if (this.propsHaveChanged) {
      this.firstRun();
    }
  }
```

**Comment by bfmatei** [comment]
You can setup a real case example in a repo? I cannot possibly think of a situation you really need this and it might be a broken logic somewhere.

**Comment by Aaron-Sterling** [comment]
Delete element in the context of ngrx. The local component shows a deletion instantly, and the delete action gets propagated over time to the global store (and eventually the remote database). You could think of it as a component localization of ngrx effects.

**Comment by adamdbradley** [comment]
For now we're going to limit the API footprint in order to keep stencil small and focused. We'll revisit this later if it becomes a larger issue. Thanks
