### ISSUE TITLE
bug: build failures when verbatimModuleSyntax is set to true

### ISSUE THREAD

**Issue by KiryZabrodski** [ionic-team/stencil#4849]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.3.0

### Current Behavior

Hello!

I have an issue with build stencil app after version upgrade. I had @stencil/core version - 2.17 After` yarn add @stencil/core@3`  it builds and works correctly without any changes. I want to upgrade Stencil's version to 4.

But after `yarn add @stencil/core@4` and adding to `tsconfig.json` `"verbatimModuleSyntax": true` instead of `"importsNotUsedAsValues": "error"` I have build failed after stencil build without any error messages:

```
[06:08.0]  @stencil/core
[06:08.5]  v4.3.0
[06:13.4]  build, search, prod mode, started ...
[06:13.6]  transpile started ...
[06:20.7]  transpile finished in 7.10 s

[ ERROR ]  build error

[06:20.7]  build failed in 7.29 s
```
`stencil build --verbose` also not shows any messages about error.

I've also checked: https://stenciljs.com/docs/introduction/upgrading-to-stencil-four

### Expected Behavior

How I can check what I should to fix for normal build?

### System Info

```shell
System: node 18.17.1
    Platform: windows (10.0.19045)
   CPU Model: AMD Ryzen 5 PRO 5650U with Radeon Graphics      (12 cpus)
    Compiler: C:\search\node_modules\@stencil\core\compiler\stencil.js
       Build: 1695049867
     Stencil: 4.3.0
  TypeScript: 5.1.6
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.19.4
```

### Steps to Reproduce

try to `stencil build --verbose` after switch to 4th version form 3rd

### Code Reproduction URL

https://github.com/

**Comment by rwaskiewicz** [comment]
Hey @KiryZabrodski 👋 

Thanks for the issue! Can you do me a favor and create a minimal reproduction case for the team to take a look at? This helps us greatly in understanding the error (especially in cases like this when the output of the build missing details & not very helpful) and ensures we're fixing the right thing.

You can do so by running the following in a terminal window to spin up a basic Stencil component  project with the latest version of Stencil:
```
npm init stencil@latest component stencil-4849-repro
```

I tried to replicate this locally by spinning up a project using that same command, and adding the following to my `tsconfig.json`:
```diff
diff --git a/tsconfig.json b/tsconfig.json
index 09367ce..cdac40a 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -4,6 +4,7 @@
     "allowUnreachableCode": false,
     "declaration": false,
     "experimentalDecorators": true,
+    "verbatimModuleSyntax": true,
     "lib": [
       "dom",
       "es2017"
@@ -22,4 +23,4 @@
   "exclude": [
     "node_modules"
   ]
}
```
And while I did receive an error:
```
[ ERROR ]  TypeScript: ./node_modules/@stencil/core/mock-doc/index.d.ts:1025:275
           Cannot access ambient const enums when 'verbatimModuleSyntax' is enabled.

   L1024:  declare function constrainTimeouts(win: any): void;
   L1025:  , MockResponse, MockResponseInit, MockTextNode, MockWindow, NODE_TYPES, SerializeNodeToHtmlOptions, cloneAttr

[55:27.4]  build failed in 1.04 s
```
I'd like to confirm that it's the same issue you're running into (or if we have two separate issues here). 

Thanks!
