### ISSUE TITLE
Imports - circular references

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#487]
**Stencil version:**
```
 @stencil/core@0.3.0
```

**I'm submitting a:**
- [x] feature request

**Current behavior:**
If there is a circular reference in the imports then the build process does not complain but the component will fail at runtime.

For example:

```tsx
// imports-circular.tsx
import { Component } from "@stencil/core";
import { valueA } from "./module-a";
import { valueB } from "./module-b";

@Component({
  tag: "imports-circular"
})
export class ImportsCircular {
  render() {
    return (
      <div>
        <div>valueA: {valueA}</div>
        <div>valueB: {valueB}</div>
      </div>
    );
  }
}

// module-a.ts
import { valueB } from "./module-b";
export const valueA = 'value A';
console.log(valueB);

// module-b.ts
import { valueA } from "./module-a";
export const valueB = 'value B';
console.log(valueA);
```

After building the app, the following file is generated:
```js
/*! Built with http://stenciljs.com */
const { h, Context } = window.App;

const valueB = 'value B';
console.log(valueA);

const valueA = 'value A';
console.log(valueB);

class ImportsCircular {
    render() {
        return (h("div", null,
            h("div", null,
                "valueA: ",
                valueA),
            h("div", null,
                "valueB: ",
                valueB)));
    }
    static get is() { return "imports-circular"; }
}

export { ImportsCircular };
```

When the component is used, the following error message occurs:
```
app.core.js:2067 ReferenceError: valueA is not defined
    at imports-circular.js:5
```

This simple example is pretty easy to debug but in a large application with complex object graphs it can be tricky.

There are some subtle cases where circular references to interfaces work in pure typescript but end up failing after inlining the generated code.  For example a parent reference to IChild and a child reference to IParent.

**Expected behavior:**
It would be great if circular references could be flagged with a warning or error during the build process to avoid surprises at runtime.  

This may require the ability for it to be done in Rollup so not sure if this is even possible.

**Comment by adamdbradley** [comment]
@jthoms1 was able to replicate this in a unit test here: https://github.com/ionic-team/stencil/commit/1d2162cb9d50e2efd94ccab67d1c0d2918a20cba

**Comment by jthoms1** [comment]
Currently there is not really a good way of solving this with Rollup. I believe the most recent version does supply the circular dependency warning.
