### ISSUE TITLE
bug: Parent calls disconnectedCallback() but not the children (since stencil 4.0.3)?

### ISSUE THREAD

**Issue by danyball** [ionic-team/stencil#4884]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.0.3

### Current Behavior

There is a special situation in a complex angular app with our stencil component:
There are 2 stencil components: select and option. The option is a child of select. Nothing special here.

But in that angular app, the disconnectedCallback of select is called, without calling the disconnectedCallback of the option.
When I stop the browser at select:disconnectedCallback I could see:
1. that "hydrated" class is **not** set yet
2. `this.el.children` has the option in its array
3. a parent element has `display:none`

### Expected Behavior

`disconnectedCallback` of `option` (the child) is called after parent `disconnectedCallback` finished. This is how it is in version 4.0.2.

### System Info

```shell
"@angular/core": "16.2.4",

Angular app uses multiple "DOM modifier" directives like ngIf, ng-template, formControl.
```

### Steps to Reproduce

This is my issue. I cant :-( Maybe your team can help me with that? My first question is: "How to manage that a stencil component gets disconnected without being `hydrated`"?

### Code Reproduction URL

TBD

### Additional Information

Initial discussion: https://discord.com/channels/520266681499779082/1107707233153855559/threads/1157327671143977020

**Comment by rwaskiewicz** [comment]
Thanks @danyball ! I've added the 'needs reproduction' label for now, please let us know when it's up! Thanks!

**Comment by rwaskiewicz** [comment]
@danyball I did, unfortunately, we don't have the capacity to try to try to replicate issues like this at this time - there are too many variables in play, which is why we require a reproduction case.
