### ISSUE TITLE
Empty comment gets inserted before the component body

### ISSUE THREAD

**Issue by paulpatarinski** [ionic-team/stencil#489]
**Stencil version:**

```
 @stencil/core@0.3.0-5
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
A comment
``` 
<!----> 
```
is inserted in the DOM before each component.

**Expected behavior:**
Only the body of the component is rendered in the DOM (whatever render() returns)

**Steps to reproduce:**

1. Clone https://github.com/paulpatarinski/emoji-mart-stencil/tree/bugfix/comment-before-emoji
2. Make sure you are under the bugfix/comment-before-emoji branch
3. Run npm install, followed by npm start
4. Inspect the DOM of the emoji

**Related code:**
Take a look at the emoji.tsx only a span gets returned
```tsx
return (
                <span
                    onClick={e => this._handleClick(e, this)}
                    onMouseEnter={e => this._handleOver(e, this)}
                    onMouseLeave={e => this._handleLeave(e, this)}
                    title={title}
                    class={className}
                >
                    <span style={style}>{children}</span>
                </span>
            )
```

**Other information:**
This started happening after upgrading to the latest Stencil build

**Comment by adamdbradley** [comment]
The HTML comments are used for the slot polyfill within the vdom renderer. They're basically a way for the renderer to know where the the "light dom" part of the user's content is. So if you have: 

```
<ion-button>MyContent</ion-button
```

But then the `<ion-button>` component adds more nodes inside of there, like:

```
<ion-button>
  <div class="inner-button">
    MyContent
  </div>
</ion-button
```

The comments are a way to keep track of the correct light dom as things get moved around. But these comments don't hurt performance and won't be rendered so they should be fine. Hope that helps, thanks.

**Comment by paulpatarinski** [comment]
Is it possible to insert both the comment & the body in a single insert statement to the DOM currently it results in 2 calls? Assuming it does not have a negative impact...this will mostly be for debugging purposes (to avoid confusion)
