### ISSUE TITLE
feat: generate strict types for addEventListener and removeEventListener for components

### ISSUE THREAD

**Issue by m-thompson-code** [ionic-team/stencil#4908]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

This feature would give type safety when using `addEventListener` or `removeEventListener`. This would improve the developer experience of TypeScript developers.

This would also make consuming Stencil components in an Angular project with or without using the Angular build target manageable with [strictTemplates flag](https://angular.io/guide/angular-compiler-options#stricttemplates) set to true.

### Describe the Use Case

This feature would allow developers to use Stencil components in a TypeScript project where using `addEventListener` and `removeEventListener` would use proper types and would eliminate the need always to use type assertion, create custom types, or overloads to each component's html element type and define them ourselves in `HTMLElementTagNameMap`.

Consider the following:
```tsx
import { Component, Event, EventEmitter, Prop, h } from '@stencil/core';

@Component(/* ... */)
export class MyComponent {
  // Add an event `example`:
  @Event() example!: EventEmitter<number>;
 // ...
}
```

```ts
// HTMLMyComponentElement
const myComponent = document.createElement('my-component');

myComponent.addEventListener('example', (event) => {
  // Property 'detail' does not exist on type 'Event'.ts(2339)
  console.log(event.detail);
});
```
<img width="1038" alt="Screenshot 2023-10-08 at 6 35 11 PM" src="https://github.com/ionic-team/stencil/assets/9206193/f0bcb3f8-ae72-43c1-bd4c-7661ae8ea296">

This type for the event callback shouldn't be `Event` but instead `MyComponentCustomEvent<number>`.

This issue makes working with Stencil in an Angular project very difficult since there are less options and is unclear to influence this behavior in an Angular template:

<img width="1037" alt="Screenshot 2023-10-08 at 7 17 51 PM" src="https://github.com/ionic-team/stencil/assets/9206193/6ce42bc8-d9e8-43ee-9d64-cb00d3028192">

### Describe Preferred Solution

Stencil should provide types to Stencil component's html elements such that using `addEventListener` and `removeEventListener` have specific types instead of just `Event`, which is typically wrong since most events are likely a `CustomEvent` of some kind.

Since there are no overloads for each component's html element, they all fallback to [HTMLElement for   `addEventListener` and `removeEventListener`](https://github.com/microsoft/TypeScript/blob/v4.2.4/lib/lib.dom.d.ts#L6698):

```ts
interface HTMLElement {
    // ...
    addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}
```

If Stencil generated these overloads, there wouldn't be any extra steps needed to use `addEventListener` and `removeEventListener`:

```ts
/** demo/src/components.d.ts */

// ...

export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
declare global {
    interface HTMLMyComponentElementEventMap {
        example: number;
    }
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
    }
}
```

This would make dealing with events a lot easier in general:
<img width="850" alt="Screenshot 2023-10-08 at 7 44 38 PM" src="https://github.com/ionic-team/stencil/assets/9206193/6386f174-45d3-49f8-8a35-cbef44094bf0">

And especially Angular:
<img width="973" alt="Screenshot 2023-10-08 at 7 46 18 PM" src="https://github.com/ionic-team/stencil/assets/9206193/06ccd5d0-9021-4543-9dc3-db91ad55777e">

### Describe Alternatives

Creating a custom build target to create types that overload `addEventListener` and `removeEventListener` for each Stencil component's html element type. Or add types with overloads somewhere in your project when consuming your Stencil components. Or modifying your generated `components.d.ts` through some other kind of automation.

Example:

```ts
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
declare global {
    interface HTMLMyComponentElementEventMap {
        example: number;
    }
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
    }
}
```

Another workaround is to use Another workaround to this issue is this custom output target I made: https://github.com/m-thompson-code/event-listener-types-output-target#event-listener-types-output-target to automate creating event listener types.

### Related Code

1. Generate a stencil component library:
  ```bash
  npm init stencil
  cd demo
  ```
  Choose component --> Project name: demo --> Confirm Y

2. Add an event named `example` with type `EventEmitter<number>` to `MyComponent` found at `demo/src/components/my-component/my-component.tsx`:
  ```tsx
  // Add `Event` to import
  import { Component, Event, EventEmitter, Prop, h } from '@stencil/core';
  // ...
  @Component(/* ... */)
  export class MyComponent {
    // Add an event `example`:
    @Event() example!: EventEmitter<number>;
   // ...
  }
  ```

3. Build stencil library:
  ```bash
  npm run build
  ```
4. Add the following to any TypeScript find such as `index.ts` found at `demo/src/index.ts`:
```ts
// HTMLMyComponentElement
const myComponent = document.createElement('my-component');

// Add event listener
myComponent.addEventListener('example', (event) => {
  // Property 'detail' does not exist on type 'Event'.ts(2339)
  console.log(event.detail);// <-- Type error
});
```

When trying to access `event.detail`, this leads to a type error:

```
Property 'detail' does not exist on type 'Event'.ts(2339)
```

### Additional Information

This issue relates to https://github.com/ionic-team/stencil-ds-output-targets/issues/219 but is not the same issue. The difference is that this issue is about Stencil as custom elements and consuming them as custom elements with or without Angular and without using the Angular output target.

That being said, a solution would likely resolve the majority of the problems involving Outputs / Events with the Angular output target.

**Comment by m-thompson-code** [comment]
Another workaround to this issue is this custom output target I made: https://github.com/m-thompson-code/event-listener-types-output-target#event-listener-types-output-target

**Comment by rwaskiewicz** [comment]
The fix for this issue has been released as a part of today's [Stencil v4.6.0 release](https://github.com/ionic-team/stencil/releases/tag/v4.6.0). As a result, I'm going to close this issue. Should the bug/issue reappear after v4.6.0, please feel free to open a new issue.

**Comment by FabioGimmillaro** [comment]
Unfortunately the provided solution for Stencil 4.6.0 didn't work for me. 

I'm getting following error in my Angular-Project: 
**Event valueChange is not emitted by any applicable directives nor by dx-text-input element**.
The compilation still works fine but I cannot get any autocompetion for my event.

I'm using following dependencies: 
- @stencil/angular-output-target: **0.8.2**
- @stencil/core: **4.6.0**

The event map within my dist/types is generated properly:
```typescript
interface HTMLDxTextInputElementEventMap {
        "valueChange": string;
        "valueComplete": string;
        "autocomplete": TextInputAutocompleteController;
        "selectAutocomplete": any;
        "enterPress": void;
    }
    /**
     * Form element for capturing text input.
     * @path /Form/Inputs
     * @name Text Input
     * @shortname Text
     * @icon font
     * @stable 
     * @slot-example info
     */
    interface HTMLDxTextInputElement extends Components.DxTextInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDxTextInputElementEventMap>(type: K, listener: (this: HTMLDxTextInputElement, ev: DxTextInputCustomEvent<HTMLDxTextInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDxTextInputElementEventMap>(type: K, listener: (this: HTMLDxTextInputElement, ev: DxTextInputCustomEvent<HTMLDxTextInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDxTextInputElement: {
        prototype: HTMLDxTextInputElement;
        new (): HTMLDxTextInputElement;
    };
```

Angular HTML-file
```html
  <dx-text-input (valueChange)="onTextInputValueChanged($event.detail)"></dx-text-input>
```

Angular Typescript-file
```typescript
  onTextInputValueChanged(detail: string) {
    console.log(detail);
  }
```

**Comment by FabioGimmillaro** [comment]
Adding an Event-Listener through Typescript however works fine:
![image](https://github.com/ionic-team/stencil/assets/56021095/1b82ab60-02d6-429b-864e-b37e9c76e5b8)

**Comment by rwaskiewicz** [comment]
@FabioGimmillaro can you please open a new issue? The team does not actively monitor closed PRs/Issues
