### ISSUE TITLE
Fail Gracefully When Cannot Generate Types

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/stencil#493]
When building `@ionic/core` with `@stencil/core@0.3.0`, I am seeing an issue with the `src/components.range.tsx` file.

When an interface used within the file is not exported, the Stencil build succeeds, but the `dist/types/components.d.ts` references a path that doesn't exist because it could not generate types for the Range.

Steps to recreate:
1. Clone Ionic repo, checkout `core` branch at the following commit:`6d37c6320098e5f154025f0c9d56382905b625b5`
2. Run npm install to ensure that you have the correct deps
3. Open `src/components/range/range.tsx`, on line 5 notice the interface for `Tick` is not exported.
4. Run `npm run build` to do the Stencil build
5. Open `dist/types/components.d.ts` and observe the invalid import statement to `components/range/range.d.ts`.
6. Open `src/components/range/range.tsx`, add an `export` statement in front of the `Tick` interface on line 5.
7. Run `npm run build` to do the Stencil build
8. Open `dist/types/components.d.ts` and observe the import statement is now valid for `components/range/range.d.ts`. The `range.d.ts` was successfully generated.

This is an important issue because a project consuming `@ionic/angular`, which uses `@ionic/core` types, cannot be used because of the TypeScript compile issue. So, basically, with this issue, we cannot use `@ionic/angular` in an Angular app.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I have seen the same issue with a different component now.

```
1. Check out the `demos` branch of Ionic repo.
2. Make sure it's up to date, it should be at commit d197a1d3b75d849c13d729388a1760e9da2b1ff0
3. Run `npm install` to get the latest version of stencil, other deps
4. Run `npm run build`
5. Open `dist/types/components.d.ts`
6. Observe that line 1781, there is an import statement to `./components/nav-pop/nav-pop` that does not exist
```

**Comment by adamdbradley** [comment]
Closing for now, we'll revisit this if it becomes a larger issue.
