### ISSUE TITLE
bug: onClickCapture not working?

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#4955]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.5.0

### Current Behavior

This is not working, "click" won't appear in the console:

    onClickCapture={() => console.log('click')}

### Expected Behavior

"click" appears in the console.

### Steps to Reproduce

In the stencil-component-starter repo, add this line:

    render() {
      return <div onClickCapture={() => console.log('click')}>Hello, World! I'm {this.getText()}</div>;
    }

### Code Reproduction URL

https://github.com/ionic-team/stencil-component-starter/

### Additional Information

I know I can add use `@Listen("click", { capture: true })` and do some filtering, but I'd prefer the simpler, declarative JSX variant. If there's a reason that `onClickCapture` does not work, maybe it should be removed from the `stencil-public-runtime.d.ts`.

Note that I've tested using the latest 4.5.0, but it also happens on lower versions.

**Comment by tanner-reits** [comment]
Hey @kraftwer1 👋 

Thanks for reporting this issue! I was able to confirm there's a problem and should have a fix up soon. Someone from the team will post again here once it makes it into an upcoming release!
