### ISSUE TITLE
bug: Stencil components do not render correctly in Google Chrome versions 57-65

### ISSUE THREAD

**Issue by goldyukol** [ionic-team/stencil#4965]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

"@stencil/core": "3.2.2", "@stencil/react-output-target": "0.0.9"

### Current Behavior

Stencil components do not render components correctly in Google Chrome versions 57-65. I understand that these versions of Google Chrome are not officially supported, but I would like to be able to make it work in these versions of the Google Chrome browser. I have the same problem with version 2.0 of Stencil, although it is stated that the second version supports Google Chrome 60+ - https://stenciljs.com/docs/support-policy

<img width="771" alt="Screenshot 2023-10-23 at 12 47 22" src="https://github.com/ionic-team/stencil/assets/50366889/7580022b-0b0c-4172-a388-677d33a454ff">

Seems like constructor is not called in the HostElement class, because of this, the **connectedCallback** method is not called in the future, which in turn prevents the render for the stencil components from loading

Google Chrome 63:
<img width="1287" alt="Screenshot 2023-10-23 at 12 43 46" src="https://github.com/ionic-team/stencil/assets/50366889/4000913f-01ce-4165-8636-4f14704e99c0">

### Expected Behavior

The google chrome > 65:
<img width="1511" alt="Screenshot 2023-10-23 at 12 50 15" src="https://github.com/ionic-team/stencil/assets/50366889/23930be5-e0f3-4850-ada6-8430b7fcf02b">

You can see the styles are working

### System Info

```shell
System: node 16.20.2
CPU Model: Apple M1 Pro (10 cpus)
Stencil: 3.2.2 🏒
TypeScript: 4.9.5
```

### Steps to Reproduce

You can use this repo - https://github.com/goldyukol/tizen-5-app for reproduce in Google Chrome 57-65

### Code Reproduction URL

https://github.com/goldyukol/tizen-5-app

**Comment by rwaskiewicz** [comment]
Hey @goldyukol 👋 

Thanks for the issue!

You are correct in that Stencil v3.x does not currently support Chrome 57-65. The minimum version of Chrome we support for Stencil v3.x is Chrome v79. Stencil v3.x is [currently in "maintenance mode"](https://stenciljs.com/docs/support-policy#stencil-maintenance-and-support-status) meaning we will only apply critical bug and security fixes. Unfortunately, extending support for additional versions of Chrome do not fall under this policy.  As a result, I'm going to close this issue out. If you have any questions, please feel free to ask.

**Comment by goldyukol** [comment]
Hey @rwaskiewicz

I caught the same problem for 2.4.0. The stencil documentation says that 2.xx should support Google Chrome 60+ - https://stenciljs.com/docs/support-policy. Could you help with this question?

**Comment by rwaskiewicz** [comment]
@goldyukol Could you try the latest version of Stencil v2.X? I cannot guarantee this will fix the problem, but trying the latest version Stencil v2 is likely your best bet here. Stencil v2 is in extended maintenance mode, and is highly unlikely to receive additional support moving forward.

**Comment by goldyukol** [comment]
@rwaskiewicz I have tried the latest versions of Stencil:
2.21.0: https://github.com/goldyukol/tizen-5-app/tree/2.21.0
2.22.3: https://github.com/goldyukol/tizen-5-app/tree/2.22.3

<img width="1282" alt="Screenshot 2023-10-23 at 17 11 28" src="https://github.com/ionic-team/stencil/assets/50366889/e0cb994a-52a7-4447-a2a0-daa0a5f65605">

Problem didn't fix. Could you please suggest how to use stenciljs 2.x.x in the Google Chrome 63?

**Comment by rwaskiewicz** [comment]
@goldyukol Unfortuately, it appears that at some point something along the way broke with regard to Chrome 63 support. I don't have a solution for you, as we no longer maintain Stencil v2. My best advice is to create a fork of Stencil for your use case
