### ISSUE TITLE
Chart.JS not rendering  when changing routes in Stencil

### ISSUE THREAD

**Issue by MichaelVonWolfen** [ionic-team/stencil#4970]
**Stencil version:**

```
@stencil/core@2.13.0
```

**Current behavior:**

I am trying to incorporate Chart.JS (`v. 4.4.0`) in an Stenciljs (`v. 2.13.0`) application with stencils router, but unortunatelly, I can't get it to work when I change routes. Whenever I reload the page (`Ctrl+R or F5`) I can get the chart to load, but if I attempt to go on another route and then come back to the route I have the chart, it simply doesn't render/show. I don't receive any error in the console.

**Expected behavior:**
When I switch the route from` /route-1` to `/route-with-chart`, I should get the chart to render, similarly to when I refresh the page (using `F5 or Ctrl+R` when I'm at `/route-with-chart`)

**GitHub Reproduction Link:**
[Repository URL](https://github.com/MichaelVonWolfen/stenciljs-chartjs-bug)

**Other information:**
[StackOverFlow  for the same issue](https://stackoverflow.com/questions/77351718/integration-of-chart-js-in-stenciljs)

**Comment by alicewriteswrongs** [comment]
Hey @MichaelVonWolfen, thanks for filing this issue! I see in your repository that you're using Stencil v2.13.0, are you able to reproduce this with a newer version of Stencil? As per [our support policy](https://stenciljs.com/docs/support-policy#stencil-maintenance-and-support-status) Stencil v2 is now in "extended support" mode and as such the team isn't able to provide ongoing support for it.

**Comment by MichaelVonWolfen** [comment]
Sorry for the late response, but the issue was on my part. I just had to add the canvas inside a div element ant that solved it.
