### ISSUE TITLE
bug: watch build does not copy files on outputtarget www

### ISSUE THREAD

**Issue by Famoose** [ionic-team/stencil#4980]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.6.0

### Current Behavior

On "stencil build --dev --watch --serve" with files to copy in for example /dev folder. It does not copy them after the hot reload.

stencil.config.ts:
```ts
  {
      type: 'www',
      serviceWorker: null, // disable service workers
      copy: [{src:'dev/**/*.html', dest:'.', keepDirStructure: true}]
    },
```
```
[38:22.1]  rebuild, project, dev mode, started ...
[38:22.1]  transpile started ...
[38:22.1]  transpile finished in 3 ms
[38:22.1]  generate lazy + source maps started ...
[38:22.2]  generate lazy + source maps finished in 133 ms
[38:22.3]  rebuild finished, watching for changes... in 146 ms
<- the copy task is missing
```

Maybe it's a windows problem, we have spotted the error on multiple windows machines, but on Unix file system it seems to work.
We did upgrade from stencil 2.x and with 4.6 it's not working anymore. So the issue may be in previous versions too.

### Expected Behavior

on file changes the file should be reflected in the /www folder

### System Info

```shell
System: node 20.8.0
    Platform: windows (10.0.19045)
   CPU Model: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 cpus)
    Compiler: C:\dev\projects\sten-starter\node_modules\@stencil\core\compiler\stencil.js        
       Build: 1698073283
     Stencil: 4.6.0
  TypeScript: 5.2.2
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.22.0
```

### Steps to Reproduce

* on windows checkout https://github.com/Famoose/sten-starter (its a starter project with one html file and the copy config)
* run `npm start`
Initial everything gets copied correctly
even the watch works.
* change something in the file.
* watch triggers and recompile
   but the file is not updated

### Code Reproduction URL

https://github.com/Famoose/sten-starter

**Comment by rwaskiewicz** [comment]
@Famoose Thanks for your patience!

Can you do me a favor and give the following dev build of Stencil a try when you get a chance?
```
npm i @stencil/core@4.7.1-dev.1699535671.a4c3950
```

**Comment by tanner-reits** [comment]
The fix for this went out as a part of today's [v4.7.2 release](https://github.com/ionic-team/stencil/releases/tag/v4.7.2)!
