### ISSUE TITLE
bug: vite v5 warning

### ISSUE THREAD

**Issue by aeharding** [ionic-team/stencil#5008]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.7.0

### Current Behavior

When building an Ionic project with Vite v5 (beta 14), I get the following warning:

```
vite v5.0.0-beta.14 building for production...
node_modules/.pnpm/@stencil+core@4.7.0/node_modules/@stencil/core/internal/client/index.js (3800:17) A comment

"/*@__PURE__*/"

in "node_modules/.pnpm/@stencil+core@4.7.0/node_modules/@stencil/core/internal/client/index.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
```

### Expected Behavior

No warning

### System Info

`npx stencil info` doesn't work - this is an Ionic project with stencil used under the hood I assume

`ionic info`:

```
Ionic:

   Ionic CLI       : 7.1.1 (/Users/aeharding/.nvm/versions/node/v20.8.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.5.2

Capacitor:

   Capacitor CLI      : 5.2.3
   @capacitor/android : 5.2.3
   @capacitor/core    : 5.2.3
   @capacitor/ios     : 5.2.3

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.8.1 (/Users/aeharding/.nvm/versions/node/v20.8.1/bin/node)
   npm    : 10.1.0
   OS     : macOS Unknown
```

### Steps to Reproduce

- Clone repro
- `pnpm i`
- `pnpm build`
- Observer warning in console

### Code Reproduction URL

https://github.com/aeharding/stencil-warning

**Comment by rwaskiewicz** [comment]
Thanks!

**Comment by rwaskiewicz** [comment]
@aeharding Can you give the following dev builds a try when you get a chance?

```
pnpm i @ionic/react@7.5.4-dev.11699023297.172bb30f  @ionic/react-router@7.5.4-dev.11699023297.172bb30f ionicons@7.2.2-dev.11699022363.15a70775
```

**Comment by tanner-reits** [comment]
The fix for this went out as a part of today's [v4.7.2 release](https://github.com/ionic-team/stencil/releases/tag/v4.7.2)!
