### ISSUE TITLE
bug: Stencil 4.7.x & Jest 29.5.7 TypeScript error

### ISSUE THREAD

**Issue by marksy** [ionic-team/stencil#5030]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.7.0

### Current Behavior

When running `stencil build` with StencilJS `4.7.0` and Jest `29.5.7`, a TypeScript error occurs and the build fails:

```bash
TypeScript: node_modules/@stencil/core/testing/jest/jest-stencil-connector.d.ts:81:31
       Could not find a declaration file for module '@jest/types/build/Config'.
       '/Users/mark.chambers/Sites/timely/TimelyApp/Timely.UI/node_modules/@jest/types/build/Config.js' implicitly
       has an 'any' type.If the '@jest/types' package actually exposes this module, try adding a new declaration
       (.d.ts) file containing `declare module '@jest/types/build/Config';`

 L80:  coverageProvider: "v8" | "babel";
 L81:  coverageReporters: import("@jest/types/build/Config").CoverageReporters;
 L82:  coverageThreshold: {
```

### Expected Behavior

The build should succeed without type errors.

### System Info

```shell
* MacOS 14.1
* M2 Max
* Yarn `3.6.3`
* TypeScript `^5.1.6`
```

### Steps to Reproduce

From the Code Reproduction URL:

1. run `yarn` to install the dependencies
2. run `yarn start` (which runs `stencil build --dev --watch --serve --port 2003`) to start the build

### Code Reproduction URL

https://github.com/marksy/stencil-jest-example

### Additional Information

Posted the original question on Discord under the stencil-help section:
https://discord.com/channels/520266681499779082/1170864699361996830

**Comment by rwaskiewicz** [comment]
@marksy Can you give the following dev build a try?

```
yarn add @stencil/core@4.7.1-dev.1699392001.7335898
```

**Comment by marksy** [comment]
> @marksy Can you give the following dev build a try?
> 
> ```
> yarn add @stencil/core@4.7.1-dev.1699392001.7335898
> ```

Yeah that fixed the issue - thanks for the quick turnaround on this 👍🏼

**Comment by tanner-reits** [comment]
The fix for this went out as a part of today's [v4.7.2 release](https://github.com/ionic-team/stencil/releases/tag/v4.7.2)!

**Comment by marksy** [comment]
Amazing how fast this fix was put through, thank you @rwaskiewicz & @tanner-reits  🙏🏼
