### ISSUE TITLE
Mapbox-gl  import

### ISSUE THREAD

**Issue by ghaiat** [ionic-team/stencil#509]
**Stencil version:**

```
 @stencil/core@0.3.0
```

**I'm submitting a:**

- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Cannot dynamically import mapbox into a stencil component.

**Expected behavior:**
Beeing able to use mapboxgl inside a stencil component.

**Steps to reproduce:**
`npm install --save mapbox-gl`

**Related code:**

```tsx
import { Component, Element } from '@stencil/core';
import * as mapboxgl from 'mapbox-gl';

@Component({
    tag: 'my-map',
    styleUrl: 'my-map.scss',
    scoped: true
})
export class MyMapComponent {
    @Element() mapEl: HTMLElement;
    private map: any;

    componentDidLoad() {
        let options: any = {
            container: this.mapEl
        };
        this.map = new mapboxgl.Map(options);
        
    }

    render() {
        return (
            <div class="container"></div>
        );
    }
}

```

**Other information:**
it will fail at runtime saying `ReferenceError: mapboxgl is not defined`

**Comment by mhartington** [comment]
The main issue here is how the library is imported and the type information provided

Talking with @ghaiat  in slack, the issue came down to the way the library was being imported

```
import * as mapboxgl from 'mapbox-gl';
```
 
The correct way to use mapbox was to run 


```
npm install mapbox-gl @types/mapbox-gl
```

Then import mapbox as 

```
import mapboxgl from 'mapbox-gl';
```

**Comment by ericclemmons** [comment]
Wanted to note for those who find this via Google, there are still unresolved issues due to `components.d.ts` not correctly importing `mapbox` types when auto-generating:

> https://stackoverflow.com/questions/52351620/stenciljs-typescript-cannot-find-name-when-exporting-an-enum

^ That solution works for enums, but even moving `mapbox` to `./mapbox.ts`, `@Method()` isn't able to correctly infer the type in `components.d.ts`, causing a blocking build error.
