### ISSUE TITLE
Multiple Outputs

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil#510]
Currently the config uses `generateWWW` and `generateDistribution`. Instead we'd like to adjust the config to have an array `outputs`, so we can make it easy to add many different types of outputs.

**Comment by Aaron-Sterling** [comment]
I was about to post an issue about `generateWWW: false`, which is present in the distribution doc but does not seem to be strictly necessary. (Or is it?) Does your opening this issue mean that config syntax is in flux?

**Comment by adamdbradley** [comment]
@Aaron-Sterling Right now it's only necessary to disable it, but the default is `true`. Eventually we'll move to the `outputs` array instead.

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil/commit/c808dee2acf57e4700c69654d5323087341aa81d

**Comment by kassem-abboud** [comment]
Hello, I know this is a closed issue, but could you please provide me with an example of configuring the `outputs` array?
Sorry the trouble and thank you.
