### ISSUE TITLE
bug: can't access `this` in form-associated callbacks

### ISSUE THREAD

**Issue by alicewriteswrongs** [ionic-team/stencil#5106]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.8.0

### Current Behavior

In #4939 we added support for form-associated custom element lifecycle callbacks like `formAssociatedCallback`, however the way they're currently being called doesn't resolve the correct `this` value to ensure that properties on a Stencil component (e.g. ones decorated with `@State`) can be resolved properly.

So a little component like this one won't work correctly 😢:

```jsx
import { Component, h, State } from '@stencil/core';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true,
  formAssociated: true,
})
export class MyComponent {
  @State() showWords: boolean = false;

  formAssociatedCallback(form: any) {
    console.log('formAssociated called');
    console.log(this.showWords);
  }

  render() {
    return <div>Hello, World!</div>;
  }
}
```

### Expected Behavior

If I try to access `this` in a method as in the example it should work correctly.

### Steps to Reproduce

In any of the form-associated callbacks (e.g. `formAssociatedCallback`) try to access something on `this`, like a `@State` property. You should get an error that it's not found (cannot read property 'so and so' of undefined). See the attached repro case.

### Code Reproduction URL

https://github.com/alicewriteswrongs/stencil-fa-cb-repro

**Comment by tanner-reits** [comment]
The fix for this was included as a part of today's [v4.8.1 release](https://github.com/ionic-team/stencil/releases/tag/v4.8.1)!
