### ISSUE TITLE
Configuration: port setting?

### ISSUE THREAD

**Issue by kristianmandrup** [ionic-team/stencil#514]
Just tried to create a new app using the starter app, based on 0.4.0 release.

`npm start` Launches with port 333, but somehow I have an old StencilJS running on same port which is displayed instead! 

Is there a way to configure Stencil with the port to be used to host the http server?

Thanks.

In the meantime, I guess I need to shutdown my laptop to have the old instance terminated.

**Comment by jgw96** [comment]
Hey! Since this sounds like a dev-server related issue and not a stencil issue I am going to move this issue for now. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil-dev-server#23

**Comment by kristianmandrup** [comment]
Thanks, I didn't even know about that project. Is it mentioned in the docs?
Will look into it shortly.
Cheers!

**Comment by Urigo** [comment]
if anyone stumbles on it its `--port`, so `yarn start --port 3000` for example
