### ISSUE TITLE
Blank page when starting stencil

### ISSUE THREAD

**Issue by vnheros** [ionic-team/stencil#516]
I try to test @stencil/core@0.4.0
I follow **getting started** at: https://github.com/ionic-team/stencil#getting-started
When I run **_npm start_** I expect to see _app-home_ component loaded with sentence:

> Welcome to the Stencil App Starter.
> ...
> 

But it is blank page at http://localhost:3333
Pls help to fix it.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Stencil!
