### ISSUE TITLE
Integration in Ionic: Failed to load module script: The server responded with a non-JavaScript MIME type of “”

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#517]
**I'm submitting a:**
- [X] bug report

**Current behavior:**
I'm developing a web component built with StencilJS which I include in a Ionic project.

It works fine locally (ionic serve), on with productive build (ionic cordova build xxxx --prod) on real iPhones and Android 6 but doesn't on Android 8.1

When I run my app on my Nexus 5X (I linked it with an usb cable to debug the error msg in Chrome) I get following error:

> Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

**Expected behavior:**
It would be cool to be able to use the component on Android 8.1 too

**Related code:**

My component:

https://github.com/peterpeterparker/web-photo-filter/tree/dev

How I integrate it in my Ionic project:

1. Add `CUSTOM_ELEMENTS_SCHEMA` to the module where the component is use

        @NgModule({
            declarations: [
                MyPage
            ],
            imports: [
                IonicPageModule.forChild(MyPage)
            ],
            schemas: [CUSTOM_ELEMENTS_SCHEMA]
        })
        export class MyPageModule {
        }
        
2. In `app.modules.ts` add a reference to the component to load it

         import 'web-photo-filter/dist/webphotofilter';
         
3. Add a custom hook in a local copy.config.js to copy the component to the www/build folger

       copyWebPhotoFilter: {
           src: ['{{ROOT}}/node_modules/web-photo-filter/dist/webphotofilter**/*'],
           dest: '{{BUILD}}'
       }

in package.json

        "config": {
            "ionic_copy": "./scripts/copy.config.js"
          }

**Steps to reproduce:**

It's also possible to reproduce this problem with the `stencil-component-starter` without changing a single line of code. So I guess that on one side my way of importing a web component build with StencilJS in a Ionic app is wrong or maybe that there is a problem.

     git clone https://github.com/ionic-team/stencil-component-starter my-component
     git remote rm origin
     npm install
     npm run build
     npm pack

and then to import it, same as described above, in a Ionic app. After build, run it on a Android 8.1 device

**Comment by jgw96** [comment]
Hey! So yeah, this is a known issue that i ran into last week. It looks like the latest chrome webview has issues with ES modules, so in the meantime we have to force "es5" builds for cordova. You can do this with `npm run build --es5`.

**Comment by jgw96** [comment]
Note for team, we could probably detect cordova under the hood in stencil and load ES5 builds then.

**Comment by peterpeterparker** [comment]
@jgw96 thx for the feedback, really appreciated!

About your workaround, do you mean using `--es5` flag to build the component or to build the component and to build the Ionic app? do ionic-app-scripts supports that flag too?

But if only the component, unfortunately that didn't worked out for me :(

**Comment by peterpeterparker** [comment]
Actually, after having test on another device, I have just noticed that this problem happens on Android 7 too

I tried again the above `--es5` option, didn't work neither

**Comment by JStumpp** [comment]
Same issue with Capacitor and Stancil. Here you find the example:
https://github.com/JStumpp/stencil-capacitor

As a workaround you can search for a statement like "return t.location.search.indexOf("core=es5")>-1" in index.html or app.js and replace it by "true" ;-)

**Comment by adamdbradley** [comment]
Ok, I think what we can do is also have the loader check if it's actively running on the `file:` protocol, and if so always default to es5.

**Comment by peterpeterparker** [comment]
I could confirm the fix works like a charm, just successfully tested my component in my Ionic app on an Android device 👍 

Thx!
