### ISSUE TITLE
ES modules: chunks are not minified

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#518]
When building an stencil website in prod mode, the resulting chunk{x}.js files are not minified.

**Comment by dangodev** [comment]
@adamdbradley I know this was an old ticket, but was this added? I’m seeing ESM files not minified for the `dist` output in `1.x` (and adding `rollup-plugin-terser` breaks `loader.mjs` as well as the Puppeteer E2E tests).

Is there a recommended path to minifying the ES modules? (Happy to ask in the Slack or create a new issue; just thought I’d search through existing issues first and this seemed to be closest).
