### ISSUE TITLE
styleUrl isn't working properly for components

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/stencil#52]
Adding the following to a Component:

```
@Component({
  tag: 'ion-fixed',
  styleUrl: 'fixed.scss'
})
```

generates the following, and doesn't get the right styles:

```
"tagNameMeta": "ion-fixed",
"styleMeta": {
  "$": {
    "styleUrls": [
      "components/fixed/fixed.scss"
    ]
  }
},
```

However, if I include `styleUrls` for all of the modes:

```
@Component({
  tag: 'ion-fixed',
  styleUrl: 'fixed.scss',
  styleUrls: {
    ios: 'fixed.scss',
    md: 'fixed.scss',
    wp: 'fixed.scss'
  }
})
```

it works fine and generates the following

```
"tagNameMeta": "ion-fixed",
"styleMeta": {
  "$": {
    "styleUrls": [
      "components/fixed/fixed.scss"
    ]
  },
  "ios": {
    "styleUrls": [
      "components/fixed/fixed.scss"
    ]
  },
  "md": {
    "styleUrls": [
      "components/fixed/fixed.scss"
    ]
  },
  "wp": {
    "styleUrls": [
      "components/fixed/fixed.scss"
    ]
  }
},
```

**Comment by jgw96** [comment]
@brandyscarney i may not be testing the right thing, but `styleUrl` seems to work fine in the latest stencil?

**Comment by brandyscarney** [comment]
You might need to make a change to the styles in order to rebuild them if you are just removing `styleUrls` from the component, but this is still an issue.

To replicate: 

1. Run `npm run dev` in ionic/core
2. Navigate to http://localhost:3333/src/components/fab/test/basic.html
3. Remove the following code: https://github.com/ionic-team/ionic/blob/mono-refactor/packages/core/src/components/fixed/fixed.tsx#L10-L14
4. Make a change in `fixed.scss` and see it rebuild & you will notice the fab buttons shift (most notably the one at the top right goes off screen) 

Or create a brand new component with a brand new stylesheet and see that it doesn't get included.

**Comment by adamdbradley** [comment]
Fixed in https://github.com/ionic-team/stencil/commit/2f20cd00a8fd5f15c6c71f667a9a1109ce0703d7
