### ISSUE TITLE
bug: Image data size does not match width/height in compareScreenshot

### ISSUE THREAD

**Issue by Spirielle** [ionic-team/stencil#5208]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.9.0

### Current Behavior

e2e tests with screenshots failing with the error "Image data size does not match width/height." when calling method `compareScreenshot` .

I have noticed that it happens only when

1. There's a visual difference between the 2 screenshots
AND
2. The screenshot is taken in a different size than 600 x 600.
    
   
So it happens if we don't change anything when calling `compareScreenshot` like this:
` await page.compareScreenshot();`
Or if the image is clipped to something else than 600 x 600, for example:
` await page.compareScreenshot('', { clip: { x: 0, y: 0, width: 800, height: 800 } });` 
 
 However, using the following does not cause any error:
`  await page.compareScreenshot('', { clip: { x: 0, y: 0, width: 600, height: 600 } });` 
    
I noticed that when not setting any clip size, the screenshot saved in my screnshot folder is 800 x 600.

### Expected Behavior

When the 2 screenshots compared are of the same size, I would expect no unhandled exception when calling `compareScreenshot`. 

### Steps to Reproduce

- Use clip option in a e2e with compare screenshot
 `await page.compareScreenshot('', { clip: { x: 0, y: 0, width: 800, height: 800 }` });
- Run test a first time to have an initial screenshot
- Change e2e slightly to trigger a visual change
- Run test a second time -> error occurs

### Code Reproduction URL

https://github.com/Spirielle/bug-stencil-getMismatchedPixels

### Additional Information

This issue follows this other issue: https://github.com/ionic-team/stencil/issues/4866

In the other one, the same underlying error caused a timeout when calling compareScreenshot.
It has been fixed, so we fortunately do not get any timeout anymore.

**Comment by christian-bromann** [comment]
I raised a PR with a resolution for this in https://github.com/ionic-team/stencil/pull/5205

**Comment by Spirielle** [comment]
Thanks a bunch really <3 can't wait to update :3
