### ISSUE TITLE
Component file hash similar between different stencil versions

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#522]
**Stencil version:**

```
 @stencil/core@0.2.3 && @stencil/core@0.4.1
```

**I'm submitting a:**

- [x] bug report

**Current behavior:**

When compiling the same source, es5 component files created with `v0.4.1` have the same hash as files created with `0.2.3` but different content.

The compiled esnext files are identical and have the same hash (all fine here)

This causes issues when trying to cache component files on a CDN with unlimited cache lifetime.

**Expected behavior:**

Files with different content should have different content hashes.

**Steps to reproduce:**

run `stencil build` in the same project but with both versions

see the file names.

**Other information:**

As always, I'd be happy to provide a PR to fix this. Given you confirm this bug.

This is a sub-issue of https://github.com/ionic-team/stencil/issues/523

**Comment by jgw96** [comment]
Hey @Xiphe , lets continue this issue once our conversation in #523 is done (:

**Comment by Xiphe** [comment]
In my opinion this should still be solved, even if you decide that https://github.com/ionic-team/stencil/issues/523 is not a usecase for stencil.

**Comment by adamdbradley** [comment]
Can you try disabling cache, by using the `--no-cache` flag? What's interesting is that if the content is exactly the same, and we do get the same hash, it's strange that your changes not working.

**Comment by Xiphe** [comment]
Tried it with `--no-cache` 

But what's interesting is that the esNext version is exactly same content & same hash.

The Issue is in the es5 files (which may just use the hash from esNext version?).

compiling the exact same source file, I receive:

### with `0.2.3`

```js
/*! Built with http://stenciljs.com */
my_lib.loadComponents(function(e, t, r) {
  'use strict';
  Object.defineProperty(e, '__esModule', { value: !0 });
  var n = (function() {
      /* ...same-ish from here on */
```

### with `0.4.3`

```js
/*! Built with http://stenciljs.com */
my_lib.loadBundle('wqlrtpejnc2o', ['exports'], function(e) {
  var t = window.my_lib.h,
    n = (window.my_lib.Context,
    (function() {
      /* ...same-ish from here on */
```

**Comment by Xiphe** [comment]
updated the description to reflect latest findings

**Comment by Xiphe** [comment]
Possible solutions (IMO): 

 - give esnext and es5 files different content hashes and put both in the registry.json
    - blows up registry, best caching
 - base the content hash on the es5 file since it will always change 
    - smaller registry, may cause unnecessary cache invalidations for esnext file
 - put loader api version into the component files (which then causes new content hashes on update)
    - same as above but less obvious
 - don't care for any of this
    - will break again once es5 loader api changes

**Comment by adamdbradley** [comment]
Should be good with stencil one, thanks
