### ISSUE TITLE
Stencil library versioning

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#523]
**Stencil version:**

```
 @stencil/core@all
```

**I'm submitting a:**

- [x] feature request

Most of the other issues i'm opening aim at this vision so I wanted to share it.

I want to use stencil in a way that I can build multiple versions of the same library and serve these in parallel.

I also want components that did not change between multiple versions to be cachable across versions

**Current behavior:**

Stencil deletes existing builds completely before creating a new build. And has no version support.

**Expected behavior:**

Not sure if I'd expect this from stencil but this is what i'm currently doing manually

 - Rename loader and registry files to be version specific `[mylib].[hash].js` to `[mylib].[version].js`
 - Move loader and registry into separate folder (together with loader and version of older versions)
   - ref: https://github.com/ionic-team/stencil/issues/464
 - Merge component file folder with those of older versions
   - ref: https://github.com/ionic-team/stencil/issues/522
 - publish everything to a CDN where everything is cached forever

**Other information:**

I wonder if this is generally an intended use-case of stencil, in which case I'd continue to dig into this direction and report issues. Otherwise I'd maybe look for another tool or fork the project ;)

**Comment by jgw96** [comment]
Hey! Interesting proposal. What is the exact use case for this? So one of our goals with Stencil when we started is to make sure that versions did not matter in Stencil itself or web components built with Stencil. In practice this has turned out to work well. You can have multiple web components on one page built using different versions of Stencil and they will all work. This is why we don't really have any specific versioning of the components on our end.

**Comment by Xiphe** [comment]
My main work is to build component libraries for big web applications. Imagine you have an application maintained by a few hundert people in multiple teams where several areas of the product are legacy. 

1. You do want to use a shared library across all teams and product areas in order to create consistency and prevent people from reinventing the wheel/dropdown.
2. You do **not** want to always use the latest version of this library across all product areas. In order to prevent (maybe unintended) breaking changes to brick your app.
3. You still want to be able to introduce breaking changes in order to be agile
4. You also want to utilise all possible caching. So that the user does not need to re-download the whole library if just a subpart changed.

Technology-wise web-components (and therefore stencil) are an awesome tool to write the library in.
Even though it might not be a primary use case of stencil, I'd really appreciate if you'd continue into a direction where I can enable this with little custom tooling.

**Comment by adamdbradley** [comment]
Absolutely agree, and this is a large priority for us. Stencil components themselves should already be versionless (meaning any version could work with any version and you don't have to keep upgrading for them to communicate). We'll do another deep dive and make sure the build steps make it easy for your use-case to work well. Thanks

**Comment by Xiphe** [comment]
Sweet!

As i described in https://github.com/ionic-team/stencil/issues/522, component files created with `0.2.3` will not work with a loader from `0.4.1` but It's great to hear that this is what you're aiming for.

Let me know when there's anything I can help with.
