### ISSUE TITLE
bug: Component stylesheet media queries not working in Firefox

### ISSUE THREAD

**Issue by jonearley** [ionic-team/stencil#5277]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.7

### Current Behavior

CSS media queries for component stylesheets seem to have no effect in Firefox.

Preview application:
https://5z5slq-3333.csb.app/

### Expected Behavior

CSS media queries for component stylesheets work as they do in Chrome.

### System Info

```shell
Firefox version 121.0.1
```

### Steps to Reproduce

Make any basic component with a stylesheet that includes a media query. I've replicated the issue in an codesandbox environment:

https://codesandbox.io/p/sandbox/stenciljs-media-queries-5z5slq

### Code Reproduction URL

https://codesandbox.io/p/sandbox/stenciljs-media-queries-5z5slq

**Comment by christian-bromann** [comment]
Hey @jonearley 👋 thanks for filing the issue. With the preview application you've shared it seems that everything works as expected:

<img width="793" alt="Screenshot 2024-01-19 at 12 55 48 PM" src="https://github.com/ionic-team/stencil/assets/731337/12cdf69d-e73c-45e8-aedd-330a6f288a3a">

Mind verifying it?

**Comment by jonearley** [comment]
Hmm, you're right. With the latest version of Firefox it's working as expected. I must of not restarted after clicking update w/ Firefox to use the latest.
