### ISSUE TITLE
bug: `globalStyle` SCSS dependency not rebuilding

### ISSUE THREAD

**Issue by silvertech-daniel** [ionic-team/stencil#5287]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.11.0

### Current Behavior

https://github.com/ionic-team/stencil/pull/5244#issuecomment-1904583097
> `globalStyle` dependency `.scss` files are being noticed (it triggers a rebuild) but not actually including the changes unless I touch the `globalStyle` file.
---
> Another is that a component without a `styleUrl` will be rebuilt when unrelated styles are updated.

This one I could not find a way to minimally replicate but I did observe it in a large closed-source project

### Expected Behavior

Updating any dependency is treated the same as updating the dependent file

### System Info

```shell
System: node 19.6.0
    Platform: windows (10.0.19045)
   CPU Model: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 cpus)
    Compiler: C:\Users\daniel.ethridge\Desktop\repos\stencil-bug\node_modules\@stencil\core\compiler\stencil.js
       Build: 1705946070
     Stencil: 4.11.0
  TypeScript: 5.3.3
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.27.0
```

### Steps to Reproduce

Update ./src/global/_x.scss and notice that it does not update until you touch ./src/global/_global.scss as well.

### Code Reproduction URL

https://github.com/silvertech-daniel/stencil-bug

**Comment by christian-bromann** [comment]
@silvertech-daniel thanks for providing the reproducible example. Unfortunately I am not able to really reproduce this. After starting the dev server via `npm run dev` I can go to ` ./src/global/_x.scss ` and successfully change the file and get an update:

![repro-failed](https://github.com/ionic-team/stencil/assets/731337/d580b9a2-f0dc-4554-8b41-a4a19b5a1252)

Can you maybe help me understand what I need to do to repro this?

**Comment by silvertech-daniel** [comment]
it's probably something that only happens on windows. Stencil says that a rebuild gets triggered even when I edit an unrelated file like `README.md`

**Comment by christian-bromann** [comment]
Oh, I think this has been fixed in a different package which hasn't been released yet, see https://github.com/ionic-team/stencil-sass/pull/459

**Comment by christian-bromann** [comment]
@silvertech-daniel we have cut a dev release of our sass plugin, can you run `npm i @stencil/sass@3.0.9-0` and see if this resolves the issue?

**Comment by silvertech-daniel** [comment]
@christian-bromann that works perfectly &mdash; lmk when that gets released!
