### ISSUE TITLE
Attributes on embedded components are not always rendered to the DOM

### ISSUE THREAD

**Issue by scottopherson** [ionic-team/stencil#529]
**Stencil version:**

```
 @stencil/core@0.4.2
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Attributes on embedded components are not always rendered to the DOM.

**Expected behavior:**

Attributes on components are always rendered to the DOM, whether embedded or not.

**Steps to reproduce:**

Using example components from https://stenciljs.com/docs/decorators#embedding-or-nesting-components:

my-parent-component.tsx:
```
@Component({
  tag: 'my-parent-component'
})
export class MyParentComponent {

  render() {
    return (
      <div>
        <my-embedded-component color="red"></my-embedded-component>
      </div>
    );
  }
}
```

my-embedded-component.tsx:
```
@Component({
  tag: 'my-embedded-component'
})
export class MyEmbeddedComponent {
  @Prop() color: string = 'blue';

  render() {
    return (
      <div>My favorite color is {this.color}</div>
    );
  }
}]
```

index.html:
```
<!-- `my-embedded-component` will render WITHOUT `color` attribute -->
<my-parent-component></my-parent-component>

<!-- `my-embedded-component` will render WITH `color` attribute -->
<my-embedded-component color="red"></my-embedded-component>
```

Result:
![screen shot 2018-02-13 at 12 37 03 pm](https://user-images.githubusercontent.com/479121/36170342-52510122-10bc-11e8-8092-7645fffbc2fc.png)

The `color` property on `my-embedded-component` gets set correctly in all cases, but the `color` attribute on the DOM element doesn't always get rendered. Is this intended behavior? We only noticed this when we started embedding components elsewhere and some of our `[attribute]` selectors in CSS started to no longer work.

**Comment by adamdbradley** [comment]
Right, the problem we have is that when it's a property, when written with JSX it doesn't bother adding the attribute. 

So here's a question for everyone, when is it ok to write the attribute?
Obviously it'd be pointless for functions, objects and arrays, because the attribute value must be a string that they wouldn't make sense there.

But for strings, numbers and booleans, should they ALWAYS set the attribute? For example, let's say we have:

```
@Prop somestring: string;
@Prop someboolean: boolean;
@Prop somenumber: number;
```

If you write these attributes in HTML they it already are attributes and everything is fine. However, if you write them in JSX you're actually setting the property directly on the element, so everything is good to go. However, in this case we'd WANT to have an attribute on the element. 

So! If it's a non-standard attribute, and it's a string/number/boolean, should the property set via JSX also always set the html attribute??

**Comment by splitinfinities** [comment]
I would like to see the non-standard attribute set, because this quirk has made me need to add `data-property=“value”` to my components wrapper `div` and write css to accomodate for that... but it would be so great to lean on the attribute that’s initially set.

**Comment by mattdsteele** [comment]
There was a good conversation the other day re: reflecting properties back to attributes: https://twitter.com/rob_dodson/status/962845317807919104

Skate's moving away from this kind of reflection, if that's any indication.

**Comment by bfmatei** [comment]
I woudn’t reflect every property. We have hostData which allows you to do it programatically, when needed. The “jquery era” is (or should be, at least) gone, querying the DOM for elements should be used less frequent, the DOM representation would look extremely heavy, there’s no uniformity (we map strings, numbers and booleans but not arrays etc.), CSS should be written using classes, not attributes etc.

There are two things which should help you decide: respecting the web specs if they specify something like this and asking the community (which @adamdbradley already did) and see what people expect.

**Comment by scottopherson** [comment]
FWIW some native HTML elements implement the behavior of reflecting property values to attributes. Here's an example of the `details` element and its `open` property/attribute:

![details](https://user-images.githubusercontent.com/479121/36275928-88e30436-1249-11e8-91e8-c38dca405141.gif)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

The ability to do `details[open]` selector in your CSS is convenient (should you need special styling on `open` for whatever reason). I agree classes/IDs are better selectors but attribute selectors are a well supported CSS feature and are necessary sometimes. Especially useful with attributes like `disabled`, `selected`, or `required` that are used on form inputs.

**Comment by mpeck** [comment]
Why don't you just make reflection opt-it? Something like `@Prop({ reflect: true }) myProp`.

**Comment by adamdbradley** [comment]
@mpeck yeah I like that idea!

**Comment by adamdbradley** [comment]
```
@Prop({ reflect: true })
```

or

```
@Prop({ reflectAttr: true })
```

Thoughts?

**Comment by bfmatei** [comment]
You can do it for *some* components in currently using ‘hostData’ as I mentioned previously.

And yeah, a prop for the decorator is a great idea!

**Comment by mhartington** [comment]
I like `reflect: true` more

**Comment by scottopherson** [comment]
+1 Polymer has something similar when configuring props; the easy opt-in was nice.

**Comment by juanmiguelbesada** [comment]
Isn't this related to #588 and fixed in https://github.com/ionic-team/stencil/commit/741d97fb6d215fd5740f1f3fe47a53b20e2e5f47?

**Comment by adamdbradley** [comment]
Oh, yup. Thanks, should be shipped now. `reflectAttr`
