### ISSUE TITLE
Run components within webworkers

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil#533]
Components already have async rendering, bundles are already lazy loaded, the host element and component instance are already disconnected, and the host element and component instance can communicate asynchronously. So all the pieces are in place to allow component instances to run within webworkers, and let the main thread only concern itself about rendering nodes while the webworker asynchronously tells the main thread what to do.

Goal for the public API:

```
@Component({
  tag: 'my-cmp',
  webWorker: true
})
```

👯

**Comment by romulocintra** [comment]
Love it!!!!!’

**Comment by Aaron-Sterling** [comment]
I'd recommend a best practices guideline for use. I talked to Rob Wormald of ngrx about putting reducers in web workers, and he thought that would slow things down, because of the expense of setup and takedown of a web worker. He thought, on the other hand, that web workers would be a perfect fit for ngrx side effects. I haven't tested this independently myself.

**Comment by thielCole** [comment]
This would be really cool!

**Comment by kael** [comment]
There's  [worker-dom](https://github.com/ampproject/worker-dom) which is _"The same DOM API and Frameworks you know, but in a Web Worker_". See the presentation _[ WorkerDOM: JavaScript Concurrency and the DOM ](https://speakerdeck.com/cramforce/workerdom-javascript-concurrency-and-the-dom)_
.
I haven't tested it yet but I'm considering using it for updating the elements of a virtual-scroll.

**Comment by kael** [comment]
I've come across [react-webworker](https://github.com/ghengeveld/react-webworker) with fancy stuff like:

```jsx
import WebWorker from "react-webworker"

const MyComponent = () => (
  <WebWorker url="/worker.js">
    <WebWorker.Pending>
      {({ postMessage }) => <button onClick={() => postMessage("hello")}>Hello</button>}
    </WebWorker.Pending>
    <WebWorker.Data>
      {data => (
        <div>
          <strong>Received some data:</strong>
          <pre>{JSON.stringify(data, null, 2)}</pre>
        </div>
      )}
    </WebWorker.Data>
    <WebWorker.Error>{error => `Something went wrong: ${error.message}`}</WebWorker.Error>
  </WebWorker>
)
```

Could be of inspiration.
