### ISSUE TITLE
feat(render): support JSX fragment

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#534]
JSX fragments allows to have several nodes at the root level without returning an array.
It is now part of the JSX spec, and has some advantages:
```
return (<>
   <div>node</div>
   {this.condition && <div>now visible</div>}
 </>);
```

VS
```
return [
   <div>node</div>,
   this.condition && <div>now visible</div>,
];
```

Right now, refactoring JSX can be tricky when nodes move from the root to a nested position, JSX fragments makes the syntax for nodes at the top the same as nested nodes.

VS code support since October 2017:
https://github.com/Microsoft/TypeScript/pull/19249

**Comment by adamdbradley** [comment]
Going to close for now until it becomes a larger issue. We'll revisit later.

**Comment by michaelauderer** [comment]
I created an implementation of Fragment for Stencil. It's literally 1 line of code. (52 chars)

https://github.com/michaelauderer/stencil-fragment

**Comment by matthew-dean** [comment]
Can this be re-opened? Using fragments is much easier to work with than exporting an array for the same purpose.

**Comment by p-vogt** [comment]
I'd love to see this beeing added, too. I sometimes find myself using dummy elements (div/span) to avoid using the array notation.
