### ISSUE TITLE
Can't use Polymer Web Components in Stencil

### ISSUE THREAD

**Issue by jadjoubran** [ionic-team/stencil#535]
**Stencil version:** 0.5.0-0

**I'm submitting a:**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Cannot use Polymer Web components from WebComponents.org

**Expected behavior:**
Be able to use Polymer Web Components from WebComponents.org by installing them and adding a `link rel="import"`

**Steps to reproduce:**

```
git clone https://github.com/ionic-team/stencil-starter.git my-app
cd my-app
git remote rm origin
npm install
bower install --save PolymerElements/paper-ripple
npm start
```
Add `<link rel="import" href="/bower_components/paper-ripple/paper-ripple.html">` at the end of the `<head>` in `index.html`

And then I get an error message saying:

`GET http://localhost:35729/app/app.core.js net::ERR_ABORTED`

**Other information:**
<img width="659" alt="screen shot 2018-02-14 at 3 15 49 pm" src="https://user-images.githubusercontent.com/2265232/36209020-e3790ba2-119a-11e8-99ca-930f1ed04ff6.png">
<img width="472" alt="screen shot 2018-02-14 at 3 13 42 pm" src="https://user-images.githubusercontent.com/2265232/36209021-e39bd8bc-119a-11e8-9638-886a5e631811.png">
<img width="644" alt="screen shot 2018-02-14 at 3 13 31 pm" src="https://user-images.githubusercontent.com/2265232/36209022-e3b87058-119a-11e8-852b-8d0a7268c7f0.png">

**Comment by mhartington** [comment]
So I think this is more of an issue with the way the dev server loads content.
I put together this demo 

https://github.com/mhartington/stencil-polymer

Which was able to use the paper-ripple element, but I had to place it in `src/assets`.

**Comment by jadjoubran** [comment]
Confirmed, I was able to make it work 👍 
This is good enough for me to continue working on my sample app
But I think we should probably keep it open until it's fixed or documented
Thanks Mike 😄

**Comment by mhartington** [comment]
For sure. Though with the move away from html imports to ES modules in polymer 3, I see this becoming less of a common issue in the future 😄

**Comment by jadjoubran** [comment]
yeah indeed! I can't wait for Polymer 3
Feel free to close it if you think this won't be fixed because of ES modules

**Comment by fangyuanziti** [comment]
Actually I am using `polymer-webpack-loader` to build all the polymer components into one js file. Import that file in html makes thing work.
