### ISSUE TITLE
JSX is not rendering attributes in the DOM

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/stencil#536]
**Stencil version:**

```
 @stencil/core@0.5.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

If you have an element in the render function with an attribute, it is not rendered in the DOM:

```
render() {
  return (
    <ion-list>
      <ion-item-sliding>
        <ion-item>
          <ion-label>Item</ion-label>
        </ion-item>
        <ion-item-options side="left">
          <ion-item-option expandable>
            <ion-icon name="star"></ion-icon>
            Button Left A
          </ion-item-option>
          <ion-item-option>
            <ion-icon name="mail"></ion-icon>
            Button Left B
          </ion-item-option>
        </ion-item-options>
      </ion-item-sliding>
    </ion-list>
  );
}
```

<img width="428" alt="screen shot 2018-02-14 at 11 10 15 am" src="https://user-images.githubusercontent.com/6577830/36215802-15411a32-117b-11e8-9597-a258d5a9a91f.png">

See that `side=left` is missing. 

Related issue: https://github.com/ionic-team/ionic/issues/13993

Possibly related: https://github.com/ionic-team/stencil/issues/529

**Comment by manucorporat** [comment]
Updating a DOM attributes causes a style invalidation. We have to understand the perf impact of updating the attribute each time a prop changes, it is not free.

React does not

**Comment by adamdbradley** [comment]
dup of #529
