### ISSUE TITLE
Routing doesn't work if deploy is in a subfolder.

### ISSUE THREAD

**Issue by Gafilipoie** [ionic-team/stencil#541]
**Stencil version:**

```
 @stencil/core@0.2.3
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I'm running a build with npm run build command which outputs the folder www.
I'm deploying the folder to a server (xampp or heroku) and the routing doesn't work.
User visits http://localhost/www/,
then click the Alerts link,
it directs him to http://localhost/alerts/

**Expected behavior:**
If a user visits http://localhost/www/,
then click the Alerts link,
it should direct him to http://localhost/www/alerts/

**Steps to reproduce:**
http://localhost/www/ works, but if I click the Alerts link the url changes to http://localhost/alerts/ and that returns a 404 page not found.
It's like the routing doesn't work when the website is in a subfolder.

**Related code:**

```tsx
<stencil-route-link url="/alerts" activeClass="active" exact={true}> Alerts </stencil-route-link>
<stencil-router id="router"><stencil-route  url={['/', '/alerts']} component="alerts-page" exact={true} > </stencil-route>
```

**Other information:**

**Comment by jthoms1** [comment]
This issue was moved to ionic-team/stencil-router#29
