### ISSUE TITLE
Documentation request: context

### ISSUE THREAD

**Issue by Aaron-Sterling** [ionic-team/stencil#542]
**Stencil version:**
```
 @stencil/core@ any
```

**I'm submitting a:**

[ x ] feature request (documentation request)

**Current behavior:**

`@Prop(context)` appears briefly on the pre-rendering page. From a conversation I had in Slack, it appears context could be very useful for something I'd like to do with Stencil.

**Expected behavior:**

Requested behavior: confirmation that context is a long-term feature of the framework, and some docs about it.

Context for request (heh): I'm thinking of adding reselect, normalizr and generics to a Stencil redux framework. That would give me 99% of what I'd be abandoning if I left Ionic-Angular.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is a docs issue I am going to move this to the site repo, thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil-site#140
