### ISSUE TITLE
bug: jeep-sqlite broken by version 4.12.2

### ISSUE THREAD

**Issue by joewoodhouse** [ionic-team/stencil#5457]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.12.2

### Current Behavior

When trying to create and mount the jeep-sqlite component the following errors are seen in the console
<img width="1419" alt="Screenshot 2024-03-11 at 22 12 56" src="https://github.com/ionic-team/stencil/assets/3168135/68594cad-3c41-4e6b-ad04-cd96a6b902ce">

### Expected Behavior

The component should mount/initialise without error as in the previous version of Stencil

### System Info

```shell
System: node 18.18.2
    Platform: darwin (23.3.0)
   CPU Model: Apple M1 Pro (8 cpus)
    Compiler: /Users/joewoodhouse/src/stencil-issue-test/node_modules/@stencil/core/compiler/stencil.js
       Build: 1707755243
     Stencil: 4.12.2 🎯
  TypeScript: 5.3.3
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.27.0
```

### Steps to Reproduce

Clone the following repository:
https://github.com/joewoodhouse/stencil-sqlite-issue

Run 
```npm install```

To see the working behaviour run
```npm run working```
This will install Stencil v.4.12.1 and then run the very basic app which just attempts to render a jeep-sqlite component

To see the broken behaviour run
```npm run broken```
This will install Stencil v4.12.2 and then run the same app. Open the console to see the errors

### Code Reproduction URL

https://github.com/joewoodhouse/stencil-sqlite-issue

### Additional Information

The only change included in 4.12.2 (https://github.com/ionic-team/stencil/commit/8a129ce7342ba737db70e0db6eda088cc9461d7f) relates to global scripts, and as my simple app runs the jeep-sqlite custom elements loader with the global script I assume that is relevant.

**Comment by christian-bromann** [comment]
Thanks for raising the issue @joewoodhouse!

The issue here is that the custom component is registered before the main Stencil application got registered. The `defineCustomElements` returns a promise as it is implemented as follows:

```ts
const defineCustomElements = async (win, options) => {
  if (typeof window === 'undefined') return undefined;
  await globalScripts$1();
  return bootstrapLazy([["jeep-sqlite",[[...]], options);
};
```

With the patch introduced in 4.12.2 (https://github.com/ionic-team/stencil/commit/8a129ce7342ba737db70e0db6eda088cc9461d7f) we now ensure that `bootstrapLazy` for the custom component is loaded before the main application. You can work around this by doing this in your global script:

```patch
--- a/src/global/app.ts
+++ b/src/global/app.ts
@@ -1,11 +1,3 @@
 import 'jeep-sqlite';
 import { defineCustomElements } from 'jeep-sqlite/loader';
-
-export default async () => {
-  /**
-   * The code to be executed should be placed within a default function that is
-   * exported by the global script. Ensure all of the code in the global script
-   * is wrapped in the function() that is exported.
-   */
-  await defineCustomElements(window);
-};
+setTimeout(() => defineCustomElements(window))
```

I will ingest the issue into our backlog so we can address this.

**Comment by christian-bromann** [comment]
Let's also verify that the fix works in https://github.com/ionic-team/stencil/issues/5596

**Comment by christian-bromann** [comment]
Hey @joewoodhouse 👋  I took another look into your issue again after evaluating the referenced issues and it seems that using the loader import approach does not work in this use case. You can get the `jeep-sqlite` component working by just importing the package directly:

```diff
diff --git a/src/global/app.ts b/src/global/app.ts
index d8cd166..bfd3ef9 100644
--- a/src/global/app.ts
+++ b/src/global/app.ts
@@ -1,5 +1,4 @@
 import 'jeep-sqlite';
-import { defineCustomElements } from 'jeep-sqlite/loader';

 export default async () => {
   /**
@@ -7,5 +6,4 @@ export default async () => {
    * exported by the global script. Ensure all of the code in the global
script
    * is wrapped in the function() that is exported.
    */
-  await defineCustomElements(window);
 };
```

I will check in with the team to see how we can improve the loader documentation to provide more information on when to use it and when not.

**Comment by christian-bromann** [comment]
I will go ahead and close this. There is a broader underlying issue where Stencil may encounter issues if multiple runtimes are in play. We have created a ticket for this to address this in near future. This particular problem can be resolved with the instructions in [my comment above](https://github.com/ionic-team/stencil/issues/5457#issuecomment-2058802513).
