### ISSUE TITLE
bug: `emulate.userAgent` is not used in E2E Screenshot tests

### ISSUE THREAD

**Issue by mlechler** [ionic-team/stencil#5459]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.12.2-dev.1709767698.0a1aa6b

### Current Behavior

The `emulate.userAgent` is ignored. The sample project should write `Dark`, `Default`, `Condensed` and `Presentation` to the console, but it writes `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/116.0.5814.0 Safari/537.36`.

### Expected Behavior

In an earlier version (v3) the `emulate.userAgent` was used and we could generate different screenshots with different color/spacing themes.

Is there a new way to do stuff like this? Or should it work this way?

### System Info

```shell
System: node 20.11.0
    Platform: darwin (23.4.0)
   CPU Model: Apple M1 Pro (10 cpus)
    Compiler: /node_modules/@stencil/core/compiler/stencil.js
       Build: 1709767698
     Stencil: 4.12.2-dev.1709767698.0a1aa6b 🤓
  TypeScript: 5.3.3
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.27.0
```

### Steps to Reproduce

Run `npm run test.screenshot` in the test repo.
Check the console output.

### Code Reproduction URL

https://github.com/mlechler/stencil-e2e-test-bug

**Comment by alicewriteswrongs** [comment]
Hey @mlechler, just was able to confirm that this is indeed an issue! I'll ingest it into our backlog for the team to prioritize. Thanks for reporting!

**Comment by mlechler** [comment]
@alicewriteswrongs @rwaskiewicz @tanner-reits 
Is there any timeline for this issue?

**Comment by christian-bromann** [comment]
@mlechler the Stencil team has decided to discontinue the screenshot testing feature in favor of screenshot testing capabilities of other more established tools like [WebdriverIO](https://stenciljs.com/docs/testing/webdriverio/overview) or [Playwright](https://stenciljs.com/docs/testing/playwright/overview). Moving forward we are looking into making Stencil lighter to keep it maintainable. Testing is one of the areas where we believe other tools do much better and should be the choice when testing Stencil components.

I am happy to assist with transitioning to e.g. WebdriverIO which provides similar component / screenshot testing capabilities as the current stencil test feature. It allows you to emulate the user agent via the [`emulate`](https://webdriver.io/docs/emulation/#user-agent) command.

I will go ahead and close the issue.
