### ISSUE TITLE
Cannot test emitting custom event

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#546]
**Stencil version:**

```
 @stencil/core@0.5.2
```

**I'm submitting a:**

[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

Trying to test emitting a custom event. Please see this repo with a failing test: 
https://github.com/Tallyb/stencil-component-test

**Comment by adamdbradley** [comment]
Thanks for the repo! Should be good to go since: https://github.com/ionic-team/stencil/commit/d388430adc9ebbf14977bb64720f165a4ac7636a

thanks!
