### ISSUE TITLE
feat: create a 'web-types' doc output target

### ISSUE THREAD

**Issue by duhem-s** [ionic-team/stencil#5460]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like to propose the addition of a new feature to Stencil, which is the ability to export [web-types](https://plugins.jetbrains.com/docs/intellij/websymbols-web-types.html) alongside the existing VS Code documentation export.

### Describe the Use Case

Currently, Stencil provides an export feature for VS Code documentation, which is immensely helpful for providing auto-completion and documentation support within VS Code. However, it would be beneficial to extend this functionality to include web-types, which would facilitate auto-completion and documentation support in other IDEs such as WebStorm.

### Describe Preferred Solution

I envision the preferred solution as an enhancement to the existing Stencil build system to generate web-types metadata in addition to the current VS Code documentation. This could be achieved by introducing a new build target that generates web-types-compatible metadata files alongside the existing VS Code documentation files. This feature would greatly enhance the usability of Stencil components across a wider range of development environments.

**Comment by rwaskiewicz** [comment]
Thanks! I've marked this to ingest it into our internal backlog

**Comment by rwaskiewicz** [comment]
As a hack day project, I created https://github.com/stencil-community/stencil-web-types. Feel free to give that go! Feedback welcome!

**Comment by duhem-s** [comment]
> As a hack day project, I created https://github.com/stencil-community/stencil-web-types. Feel free to give that go! Feedback welcome!

Looks nice, thanks for the project.
Now I'm wondering why this is not included in Stencil builds since it provides a vscode build.

**Comment by christian-bromann** [comment]
Thanks @rwaskiewicz for contributing this awesome plugin! Let's continue further discussions in [that project](https://github.com/stencil-community/stencil-web-types). So if anyone runs into issues or would like to add features, raise an issue there and we can take it from there.
