### ISSUE TITLE
bug: stencil build throws errors from node_modules

### ISSUE THREAD

**Issue by candiotti-ca** [ionic-team/stencil#5462]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.13.0

### Current Behavior

When using some dependencies in the project (i.e. `i18next`), the build fails ans points out errors from the library.

### Expected Behavior

No errors from node_modules

### System Info

System: node 21.6.1
     Plaform: windows (10.0.22000)
   CPU Model: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 cpus)
    Compiler: ...\stencil-i18next\node_modules\@stencil\core\compiler\stencil.js
       Build: 20220124181123
     Stencil: 2.13.0
  TypeScript: 4.3.5
      Rollup: 2.42.3
      Parse5: 6.0.1
      Sizzle: 2.42.3
      Terser: 5.6.1

### Steps to Reproduce

1. Create a stencil app
2. Install `i18next` dependency: `npm i i18next`
3. Just `import i18next from 'i18next'` in `index.ts` or `app-root.tsx` triggers the error
4. Run `npm run build` ans see error in terminal

### Code Reproduction URL

https://github.com/candiotti-ca/stencil-i18next

### Additional Information

I tried to use this library in an Angular project, and everything is working fine.

I also tried to use other npm packages in the stencil app (`@material/web`)

**Comment by rwaskiewicz** [comment]
Hey @candiotti-ca 👋 

Stencil v2 is no [longer supported](https://stenciljs.com/docs/support-policy) as of Jan 25, 2024. Can you please update your reproduction case to use Stencil v4 and verify if the issue still exists?

**Comment by candiotti-ca** [comment]
Oh my... I've used `npm init stencil` to create my project and I didn't check the dependencies version as I trusted the script. That was the issue, many thanks and sorry for that...

**Comment by rwaskiewicz** [comment]
Understandable! Stencil "App"s are no longer an officially supported use case by Ionic, which is why that option in the CLI belongs to the Stencil Community these days. At the time of this writing, that starter still hasn't upgraded to v4 just yet, which is why you see that.

I'm going to close this out, but please feel free to open a new issue if this appears when using the Stencil Component Starter/Stencil v4. Thanks!
