### ISSUE TITLE
bug: hydrate app | unhandledRejection TypeError: Cannot read properties of undefined (reading 'nextTick')

### ISSUE THREAD

**Issue by guidoknoll** [ionic-team/stencil#5469]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.12.6

### Current Behavior

When running the renderToString method we encounter the following error:
```
unhandledRejection TypeError: Cannot read properties of undefined (reading 'nextTick')
    at writeTask (/Users/guidoknoll/Development/ssr-server/versions/local/hydrate/index.js:7656:12)
    at scheduleUpdate (/Users/guidoknoll/Development/ssr-server/versions/local/hydrate/index.js:7331:9)
    at i (/Users/guidoknoll/Development/ssr-server/versions/local/hydrate/index.js:7502:45)
    at initializeComponent (/Users/guidoknoll/Development/ssr-server/versions/local/hydrate/index.js:7503:39)
    at connectedCallback (/Users/guidoknoll/Development/ssr-server/versions/local/hydrate/index.js:7529:4)
    at s (/Users/guidoknoll/Development/ssr-server/versions/local/hydrate/index.js:6916:7)
    at L (/Users/guidoknoll/Development/ssr-server/versions/local/hydrate/index.js:6929:5)
    at Array.map (<anonymous>)
    at y (/Users/guidoknoll/Development/ssr-server/versions/local/hydrate/index.js:6933:40)
    at hydrateApp (/Users/guidoknoll/Development/ssr-server/versions/local/hydrate/index.js:6946:23)
```
This happenend since the update to the newest version, with version 3.2.1 everything worked fine. The part where the error occurs looks like this:

```javascript
}, win = window, doc = win.document, writeTask = e => {
 process$1.nextTick((() => {
  try {
   e();
  } catch (e) {
   consoleError(e);
  }
 }));
```

When adding optional chaining to process$1 we just get a timeout error.

### Expected Behavior

The error should not be thrown.

### System Info

```shell
System: node 20.11.1
    Platform: darwin (23.1.0)
   CPU Model: Apple M1 Pro (10 cpus)
    Compiler: /Users/guidoknoll/Development/serp-widget/node_modules/@stencil/core/compiler/stencil.js
       Build: 1710170895
     Stencil: 4.12.6 🍍
  TypeScript: 5.3.3
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.29.1
```

### Steps to Reproduce

We can't really tell how this could be reproduced yet. Sadly we cannot share our code.

### Code Reproduction URL

Sadly we cannot share our code.

**Comment by rwaskiewicz** [comment]
Hey @guidoknoll 👋 

While we understand you may not be able to share code, we can't move forward with this issue without a minimal reproduction case. I recommend spinning up a new project with `npm init stencil@latest component` and use that as a foundation for building something that represents the issue, without giving us any confidential code/details. Thanks!

**Comment by guidoknoll** [comment]
So, after a lot of debugging i found the solution to the problem. It occurs in this line of the generated hydrate app:

`var process$1 = commonjsGlobal.process;`

The problem lies in `commonjsGlobal.process` being undefined. Replacing this with `require('node:process')` fixes the problem!

Do you know why this occurcs or could you adjust the affected line in an upcoming update?

**Comment by rwaskiewicz** [comment]
I don't - `commonjsGlobal` refers to something going on in the `@rollup-plugin-commonjs` package, but without a reproduction case, I can't say for sure why this happens. Similarly, I don't feel comfortable making a change without a reproduction case/something I can actively test against.

**Comment by guidoknoll** [comment]
Understandable. We found a solution for us by replacing that line in our hydrate app for now. Maybe this will be fixed on the long run, sadly i couldn't find any similar issues at @rollup-plugin-commonjs.

Thank you a lot, maybe this helps others, too! I'll close this for now.
