### ISSUE TITLE
SyntaxError: Identifier 'en$1' has already been declared

### ISSUE THREAD

**Issue by Aaron-Sterling** [ionic-team/stencil#548]
[ x ] bug report

**Current behavior:**
I solved this problem, but it took me a day (because I didn't know why it was happening, and when I asked on Slack, no one else knew either), so I figured I should document the issue here. I was getting the error
```
SyntaxError: Identifier 'en$1' has already been declared
```
caught at the end of function loadBundle(). It appears this was due to the fact that date-fns was importing the English locale as default, and when I tried to import it into a separate name, the same bundle was being declared again.

I resolved this by removing the import statement for the English locale, and using an if statement instead, sending "default locale" if the user wanted the Ehglish locale. The import statement
```
import * as en from 'date-fns/locale/en';
```
caused no Typescript error or warning - no compile-time error, only a run-time error. Also, I used very similar logic in an Angular pipe, and Angular did not throw the runtime error.

Note: the error persisted when I imported the module as "test". So it appears the runtime error occurred not because of a naming reason, but because the same module was imported twice -- once by the node module, and a second time by me.

**Comment by Aaron-Sterling** [comment]
I'm not able to reproduce the error with the current version of Stencil, just tried with the same project that gave me trouble. Maybe it's fixed? I'll do some more testing, but I can't produce a repo at the moment.

**Comment by jthoms1** [comment]
Thanks!
