### ISSUE TITLE
support for generic class in components.d.ts

### ISSUE THREAD

**Issue by Aaron-Sterling** [ionic-team/stencil#549]
**Stencil version:**
```
 @stencil/core@ 0.6.0
```

**I'm submitting a:**

[ x ] bug report

**Current behavior:**
A component defined by a generic class does not receive generic definition of classes and interfaces in components.d.ts

**Expected behavior:**
Generic support.

**Steps to reproduce:**
This class definition
```
export class AsyncPipe<T> {
  @Prop() stream: Observable<T> | Promise<T>;
  @State() output: T = null;
  @Event() change: EventEmitter<T>;
//etc
}
```
produces lines in component.d.ts like
```
interface HTMLAsyncPipeElement extends AsyncPipe, HTMLStencilElement
```
which throws a Typescript error bc TS expects an argument for AsyncPipe.

**Comment by Aaron-Sterling** [comment]
After sleeping on this, I realized I might not have asked for quite the right thing, because a JSX expression can't accept generics. I would like to be able to do [this](https://gist.github.com/RocketPuppy/2095d48968b9e829ed5c87e997ed2a4b), where generics can be used to ensure type safety deep into an object (using keyof etc), and then adding boilerplate at the end to get something that can be plugged into a render function. Specifically for the particular project I'm working on now, I'd like to duplicate the logic of the way the Angular async pipe processes inputs, which is:
```
transform<T>(obj: null): null;
  transform<T>(obj: undefined): undefined;
  transform<T>(obj: Observable<T>|null|undefined): T|null;
  transform<T>(obj: Promise<T>|null|undefined): T|null;
transform(obj: Observable<any>|Promise<any>|null|undefined): any {}
```
The wrapping class AsyncPipe is not genericized, but the transform function is, if possible.

**Comment by jthoms1** [comment]
So would transform have a `@Method` decorator on it? Just trying to grok an example of how it would get used.

**Comment by Aaron-Sterling** [comment]
I tried to recreate the Angular pipe by putting @Method on transform, but I'm not wedded to that as the best way to make it happen. I'm requesting some provider-like structure that can be strongly typed. Maybe that's an "invisible" component that is just a bunch of Method decorators, maybe something else, I'm not sure what structures you are building or have planned.

Expressed as a simple question: how could I define a pipe in Stencil? I see two main possible answers. Either at compile time I can type a component, StencilComponent<T> then allows me to define the methods inside it as transform<T> etc.  Or I assign types method by method, and components don't have any types of their own.
