### ISSUE TITLE
Is there a way to DISABLE service worker?

### ISSUE THREAD

**Issue by kirillgroshkov** [ionic-team/stencil#551]
Is there a way to DISABLE service worker completely?

I've tried setting `swSrc` to my own empty file, but then build fails.

**Comment by bfmatei** [comment]
‘serviceWorker: false’ in stencil.config.js.

**Comment by kirillgroshkov** [comment]
Thanks!

**Comment by DavidFrahm** [comment]
Worth noting that your IDE might not like the typing (because its expecting the value of `serviceWorker` to be an object, not a boolean) but this does work.

**Comment by manucorporat** [comment]
It can be `null`
