### ISSUE TITLE
bug: Boolean property not removing corresponding attribute when set to false programmatically

### ISSUE THREAD

**Issue by a7medm7med** [ionic-team/stencil#5510]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.12.6

### Current Behavior

The `disabled` attribute remains on the element even after setting the property to false.

### Expected Behavior

The `disabled` attribute should be removed from the element when the corresponding property is set to false.

### System Info

```shell
System: node 18.19.0
    Platform: windows (10.0.22631)
   CPU Model: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 cpus)
    Compiler: D:\Projects\web-components\node_modules\.pnpm\@stencil+core@4.12.6\node_modules\@stencil\core\compiler\stencil.js
       Build: 1704730339
     Stencil: 4.12.6
  TypeScript: 5.2.2
      Rollup: 2.42.3
      Parse5: 7.1.2
      Terser: 5.26.0
```

### Steps to Reproduce

1- Set up a StencilJS component with a boolean property, for example:
2- Instantiate the component and set the property to false programmatically, for example:
3- Observe that the disabled attribute is not removed from the element.

### Code Reproduction URL

https://github.com/a7medm7med/stencil-bug-3

**Comment by rwaskiewicz** [comment]
Thanks! Something doesn't appear to be right here, I'll get it ingested into our backlog

**Comment by tanner-reits** [comment]
@a7medm7med I took a look at this issue again and your provided reproduction case. I was able to get the expected behavior by applying the following patch:
[Changes-On-fb174e.patch](https://github.com/ionic-team/stencil/files/14837773/Changes-On-fb174e.patch)

I did need to update your component's `render` function to render a tag since when I added `reflect` to the prop, the text no longer appeared... I'll look into that separately from this issue.

Let me know if that works for you!

**Comment by tanner-reits** [comment]
@a7medm7med I'm a little confused what you mean by "in my case, I found that I don't need to use the reflect option". `reflect` is what keeps the property value in sync with an attribute value. If `reflect: true` is not set on the `@Prop()`, then the attribute cannot be removed by the runtime. You can read a bit more about this option in the [Stencil docs](https://stenciljs.com/docs/properties#reflect-properties-values-to-attributes-reflect).
