### ISSUE TITLE
Empty component with shadow dom enabled after building 

### ISSUE THREAD

**Issue by ray-kay** [ionic-team/stencil#553]
**Stencil version:**

```
 @stencil/core@0.4.0
also tested with
 @stencil/core@0.6.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When setting "shadow: true", building and running the build my component seems empty/not rendered.

**Expected behavior:**

With or without using shadow dom I expect the same visual outout.

**Steps to reproduce:**

I tested it again from scratch with the starter app

- git clone https://github.com/ionic-team/stencil-app-starter my-app
- cd my-app
- npm install
- npm run build
- cd www 
- http-server -o -p 1234

=> you should see the expected starter app web component

- now go to src/components/my-app/my-app.tsx
- add shadow: true after line 6
- npm run build
- cd www 
- http-server  -o -p 1235

=> I see an empty white page (make sure you use a different port or open an incognito window)

**Related code:**

```tsx
@Component({
  tag: 'my-app',
  styleUrl: 'my-app.css',
  shadow: true
})
```

**Other information:**

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us. I was just able to reproduce this issue and we are looking into it.

**Comment by adamdbradley** [comment]
Looks to be related to components that use shadow dom and prerendering is enabled.
