### ISSUE TITLE
Elements to a named slot are still rendered even when slot doesn't exist

### ISSUE THREAD

**Issue by marinho** [ionic-team/stencil#554]
**Stencil version:**
```
 @stencil/core@0.5.1
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**

Take this example of a component

```
@Component({ tag: 'my-toggle-button' })
export class MyToggleButton {
  render() {
    if (pressed) {
      return (<slot name="pressed">);
    } else {
      return (<slot name="released">);
    }
  }
}
```

```
<my-toggle-button checked>
  <span slot="pressed">On</span>
  <span slot="released">Off</span>
</my-toggle-button>
```

Even though only one of the given slots will be presend in the template, both spans will be rendered in DOM.

Is that a limitaton of `slot` itself or a bug in Stencil?

**Expected behavior:**
Only one `span` should be rendered, as the other slot isn't present.

**Steps to reproduce:**
Hope the example above is enough.

**Comment by adamdbradley** [comment]
Currently this is a limitation of the slot polyfill. At this time this will have to be a limitation. If this further becomes and issue we'll reopen this and address it then. Thanks.

**Comment by marinho** [comment]
well, I've solved it by hiding one of the elements that would go to the slots (setting `hidden` attribute). Is there a better work around?
