### ISSUE TITLE
Hosting the app for another application to consume.

### ISSUE THREAD

**Issue by mnemanja** [ionic-team/stencil#556]
**Stencil version:**

```
 @stencil/core@0.4.0
```

**I'm submitting a:**
[X] feature request

**Current behavior:**
When serving the app it comes without the `CORS` enabled.

**Expected behavior:**
I would like to serve the stencil app and then import it via `http-import` in another app.

**Steps to reproduce:**
Simply clone, install, start and make an http-import in another app.

**Other information:**
The request preview shows the content of the `www/index.html` file, but it doesn't get rendered.

**Comment by jgw96** [comment]
Hello, thanks for using Stencil! Setting up `CORS` when serving an app built with Stencil is not something that Stencil handles, but instead is something your hosting service or your web server should handle. Because of this I am going to close this issue for now. Thanks for using Stencil!
