### ISSUE TITLE
bug: `emulate.viewport` crops the screenshot in E2E Screenshot tests

### ISSUE THREAD

**Issue by mlechler** [ionic-team/stencil#5563]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.13.0

### Current Behavior

When using the `emulate.viewport` in the `stencil.config.ts` the produced screenshot is just cropped to the sizes. 

Looks like this (see the background color, which exceeds the screenshot border):
<img width="349" alt="Screenshot 2024-03-21 at 16 46 54" src="https://github.com/ionic-team/stencil/assets/22612468/afcec6d3-206f-46ed-a4dc-0f1dd34a9f36">

### Expected Behavior

I would expect, that the size of the screenshot is adapted, so we can test different device sizes. In an earlier version this was exactly the behaviour.

Should look like this:
![Screenshot 2024-03-21 at 16 46 02](https://github.com/ionic-team/stencil/assets/22612468/fc5244ef-51a8-482f-bcb5-b64f860784a1)

### System Info

```shell
System: node 20.11.0
    Platform: darwin (23.4.0)
   CPU Model: Apple M1 Pro (10 cpus)
    Compiler: /node_modules/@stencil/core/compiler/stencil.js
       Build: 1710782619
     Stencil: 4.13.0 🚞
  TypeScript: 5.4.2
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.29.2
```

### Steps to Reproduce

Run `npm run test.screenshot` in the test repo.
Check the produced screenshots.

### Code Reproduction URL

https://github.com/mlechler/stencil-e2e-test-bug

**Comment by mlechler** [comment]
@alicewriteswrongs @rwaskiewicz @tanner-reits 
Is there any timeline for this issue?

**Comment by christian-bromann** [comment]
@mlechler the Stencil team has decided to discontinue the screenshot testing feature in favor of screenshot testing capabilities of other more established tools like [WebdriverIO](https://stenciljs.com/docs/testing/webdriverio/overview) or [Playwright](https://stenciljs.com/docs/testing/playwright/overview). Moving forward we are looking into making Stencil lighter to keep it maintainable. Testing is one of the areas where we believe other tools do much better and should be the choice when testing Stencil components.

I am happy to assist with transitioning to e.g. WebdriverIO which provides similar component / unit testing capabilities as the current `stencil test` feature.

I will go ahead and close the issue.
