### ISSUE TITLE
Cannot find module '../dist/testing/index.js'

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#558]
**Stencil version:**

```
 @stencil/core@0.6.3
```

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Tests fail with `Cannot find module '../dist/testing/index.js'`

**Expected behavior:**
tests to pass

**Steps to reproduce:**
Can use stencil_component_starter updated to 0.6.3. dist/testing is missing from the build. 

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
Should be fixed in this commit, thanks https://github.com/ionic-team/stencil/commit/90b295b9101c8db5f02b7fcde1835e972bbab93f
