### ISSUE TITLE
:host css selector with shadow-dom

### ISSUE THREAD

**Issue by ray-kay** [ionic-team/stencil#559]
**Stencil version:**

```
 @stencil/core@0.6.5
also tested with
 @stencil/core@0.6.0
 @stencil/core@0.4.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I followed the instructions here https://stenciljs.com/docs/shadow-dom/ and used the :host css selector instead of the tag name but it doesn't seem to apply changes. Furthermore I get build warnings:

[ WARN  ]  Minify CSS
           Unexpected '}' at 17:0.

[ WARN  ]  Minify CSS
           Invalid character(s) '} ' at 17:0. Ignoring.

[ WARN  ]  Minify CSS
           Invalid property name 'header { background' at 2:2. Ignoring.

**Expected behavior:**

With or without using shadow dom and the :host css selector I expect the same visual output.

**Steps to reproduce:**

I tested it again from scratch with the starter app

- git clone https://github.com/ionic-team/stencil-app-starter my-app
- cd my-app
- npm install
- npm run build
- cd www 
- http-server -o -p 1234

=> you should see the expected starter app web component nicely styled :)

- now go to src/components/my-app/my-app.tsx
- add shadow: true after line 6
- insert a new first line in  src/components/my-app/my-app.css with `:host {` and add the closing } at the end of the file
- npm run build
- cd www 
- http-server  -o -p 1235

=> it doesn't apply the styling + we get warnings during the build  (make sure you use a different port or open an incognito window)

**Related code:**

```tsx
@Component({
  tag: 'my-app',
  styleUrl: 'my-app.css',
  shadow: true
})

:host {
  header { 
   ...
}
```

**Other information:**

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. The `:host` selector is a css selector and therefore should be in the css file for that component. Thanks for using Stencil!

**Comment by ray-kay** [comment]
Hi @jgw96,
thanks for checking out this issue and sorry if the "Related code" snippet was confusing for you. Of course I added the :host selector in the css file otherwise the build would fail ;)
Could you please have another look into it. We are planing to us Stencil in production soon.

Thanks again.
