### ISSUE TITLE
Hydrated causes issues with components using visibility style

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/stencil#56]
We have some components in `Ionic` which override the `visibility` to `hidden` by default. For example:

```
ion-item-options {
  visibility: hidden;
}
```

The styling added by the `hydrated` class overrides this:

```
ion-item-options.hydrated {
  visibility: visible;
}
```

If it is possible to just add the style directly to the element and remove it once hydrated that might be the best solution. I'm up for discussion though!

**Comment by bmlyon** [comment]
Was this resolved? I too have this issue.
