### ISSUE TITLE
Use Facebook's Prepack during rollup bundling

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#561]
**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request

Facebook is working on this amazing sounding runtime optimizer: [Prepack](https://github.com/facebook/prepack)

Theres even a [rollup plugin](https://www.npmjs.com/package/rollup-plugin-prepack).

Would this fit into the "Stencil world" to make it even faster?

**Comment by jgw96** [comment]
Hey @bitflower , thanks for opening an issue with us! We have looked at Prepack before but deemed it not worth the extra tooling overhead since our compiled code is already so tiny and efficient. Also, we are trying not to bake in a ton of rollup plugins out of the box to keep things simple.
