### ISSUE TITLE
Component's host meta works only for theme, not for role or tabindex

### ISSUE THREAD

**Issue by marinho** [ionic-team/stencil#562]
**Stencil version:**
```
 @stencil/core@0.6.5
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

When using Component decorator `host` meta attribute, if informed `role` or `tabindex`, they don't render in host element. But it works for `theme` (which adds a class).

For the given component

```tsx
@Component({
    tag: 'my-button',
    host: {
        theme: 'my-button',
        role: 'button',
        tabindex: '0'
    }
})
export class MyButton {
}
```

This is the result:

```html
<my-button class="my-button"></my-button>
```

I guess that's happening for any attribute other than `theme`.

**Expected behavior:**

Virtually any valid attribute should be supported and set to the host element, as below.

```html
<my-button class="my-button" role="button" tabindex="0"></my-button>
```

**Steps to reproduce:**

Try the example above.

**Other information:**

Documentation available in https://stenciljs.com/docs/decorators/ mentions at least `role` attribute.

**Comment by ozee** [comment]
I can also replicate this trying to do the same thing.

**Comment by marinho** [comment]
I forgot to mention that it works though when using `hostData()`

**Comment by marinho** [comment]
@adamdbradley this is fixed, thanks for that! But there's still an open issue very much about it:

Say you have a component such as this:

```
@Component({
    tag: 'my-button',
    host: {
        theme: 'my-button',
        role: 'button',
        tabindex: '0'
    }
})
export class MyButton { }
```

Now given this usage of it:

```
<my-button class="my-button--primary" tabindex="1"></my-button>
```

Probable result you likely want:

* to have `class` as "my-button my-button--primary"
* to have `role` as "1"

Currently in version 0.7.24, what we have is:

* `class` is "my-button--primary my-button"
* `role` is "0"

Naturally the "you likely want" is already something to be explicit anyhow.

But, can you see that even though `theme` works as expected, `role` isn't neither consistent with the most likely result nor with `theme`?

`hostData()` method has the same issue.

**Comment by RezaRahmati** [comment]
Hi,
Seems `host` doesn't exists any more in componentOptions, what is the alternative for that?

**Comment by natemoo-re** [comment]
@RezaRahmati The `host` component option has been replaced with the `<Host>` element. [The documentation is here.](https://stenciljs.com/docs/host-element#host)
