### ISSUE TITLE
bug: generated documentation does not display custom properties when included in loud comments

### ISSUE THREAD

**Issue by duhem-s** [ionic-team/stencil#5623]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

v4.14.0

### Current Behavior

When I document custom CSS properties using syntax within loud comments in my CSS files, the generated documentation does not display them.

In Sass, to preserve comments we have to set them as loud comments using the following format:
```SCSS
/*!
 * @prop --mg-badge-size: Badge size
 */
```
https://sass-lang.com/documentation/syntax/comments/#in-scss

However, these loud comments do not seem to be interpreted by the documentation generation process.

### Expected Behavior

I expect the documentation to display the --mg-badge-size custom property with its associated description, indicating that it represents the badge size.

### Steps to Reproduce

Add loud comment in CSS like: https://github.com/duhem-s/stencil-css/blob/main/src/components/my-component/my-component.css

Run build command.

Custom properties are not displayed in readme.

### Code Reproduction URL

https://github.com/duhem-s/stencil-css/tree/main

**Comment by rwaskiewicz** [comment]
Thanks for the issue + reproduction case! I verified that Stencil can "see" comments that begin with a `/*!`, but it's currently not doing anything with them. I'm going to label this to get it added to our backlog.

Thanks again!

**Comment by rwaskiewicz** [comment]
The fix for this issue was included in today's release of [Stencil v4.17.2](https://github.com/ionic-team/stencil/releases/tag/v4.17.2)
