### ISSUE TITLE
dist/collection does not resolve json import path. When one Stencil distribution imports another: 

### ISSUE THREAD

**Issue by shroffshyam** [ionic-team/stencil#5627]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.18.1

### Current Behavior

When i try to refer package.json in global-script.ts file. The import package.json file path is not resolved.

```import {version} from './../../package.json';

export default function(): void{
const _VERSION = version; 
}```

Then When i import this stencil library into another Stencil library
using 
```import from 'library1';```

Getting Error 
```
Rollup: Unresolved Import
Could not resolve  './../../package.json'; from './node_module.....`
```

### Expected Behavior

Stencil Js config 'transformAliasedImportPathsInCollection` should handle this. 

### System Info

```shell
stenciljs 2.18.1
```

### Steps to Reproduce

When one Stencil distribution imports another;

### Code Reproduction URL

https://forum.ionicframework.com/

**Comment by christian-bromann** [comment]
@shroffshyam thanks for raising the issue.

> 2.18.1

Please note that we are not supporting Stencil v2 anymore. Please see our [support policy](https://stenciljs.com/docs/support-policy#stencil-maintenance-and-support-status).

If you can provide a reproducible example using one of the supported Stencil versions, I am happy to take a look at this.
