### ISSUE TITLE
index.html file written even with custom wwwIndexHtml config

### ISSUE THREAD

**Issue by finneganh** [ionic-team/stencil#563]
**Stencil version:**

```
 @stencil/core@0.6.5
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

If you set a `wwwIndexHtml` path to control where, relative to `wwwDir` `index.html` is written, Stencil copies the `srcIndexHtml` file to it, but the prerendered output is always written to `index.html`.

**Expected behavior:**

The prerendered content should go to `wwwIndexHtml`.

**Steps to reproduce:**

Config:

```
  wwwDir: "assets",
  wwwIndexHtml: "out.html",
  buildDir: "web-components",
```

`assets` will contain both `index.html` and `out.html` (and a `web-components` directory, which is expected)

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by jgw96** [comment]
Ahh good find!
