### ISSUE TITLE
bug: `E2EPage.find()` throws error when using piercing selector targeting a non-existing element

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#5639]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.14.0

### Current Behavior

Calling `find` with a piercing selector where the target does not exist throws an error instead of returning `null` as the doc states.

### Expected Behavior

For `find()` to return `null` for shadow DOM elements that are not found.

### System Info

```shell
System: node 20.10.0
    Platform: darwin (23.3.0)
   CPU Model: Apple M1 Pro (10 cpus)
    Compiler: /Users/juan6600/dev/projects/stencil-4.14.0-breaks-piercing-selector-for-non-existent-elements/node_modules/@stencil/core/compiler/stencil.js
       Build: 1711981251
     Stencil: 4.14.0 🚡
  TypeScript: 5.4.3
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.30.0
```

### Steps to Reproduce

See repro case readme.

### Code Reproduction URL

https://github.com/jcfranco/stencil-4.14.0-breaks-piercing-selector-for-non-existent-elements

### Additional Information

4.13.0 does not throw an error and works as expected.

This was previously fixed for another version in https://github.com/ionic-team/stencil/issues/5113.

**Comment by tanner-reits** [comment]
Hey @jcfranco Thanks for reporting this (again 😅). I've identified the issue and will have a PR up to fix this shortly!

**Comment by jcfranco** [comment]
@tanner-reits Thanks for the speedy fix! When is the next `@stencil/core` release planned?
