### ISSUE TITLE
bug: Unit test --watchAll argument parsed incorrectly

### ISSUE THREAD

**Issue by maxpatiiuk** [ionic-team/stencil#5640]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.15.0

### Current Behavior

Regardless of the argument value, if the argument is present, Stencil sets `watch=true`:

https://github.com/ionic-team/stencil/blob/76c5d5410068cdb43296911a33b20d47531383a3/src/testing/testing.ts#L235-L237

This causes this command to be incorrectly interpreted as if `watchAll` is true:

```bash
npx stencil test --spec -- --watchAll=false
```

Besides confusion, this causes third-party tools to fail or freeze: https://github.com/jest-community/vscode-jest/issues/1124#issuecomment-2000596099

### Expected Behavior

If `--watchAll` is false, it should not be treated as a `true`

Jest's documentation explicitly mentions this:

> Use `--no-watchAll` (or `--watchAll=false`) to explicitly disable the watch mode if it was enabled using `--watchAll`. In most CI environments, this is automatically handled for you.

https://github.com/jestjs/jest/blob/726ca20752e38c18e20aa21740cec7aba7891946/docs/CLI.md?plain=1#L545

For reference, Jest defines it as a boolean argument using the `typebox` library:
https://github.com/jestjs/jest/blob/726ca20752e38c18e20aa21740cec7aba7891946/packages/jest-schemas/src/raw-types.ts#L346
Which would parse the value as false if it's anything other than `true`: https://github.com/sinclairzx81/typebox/blob/480ba12942cf908fab6e2ad16b3276b035ddcb54/test/runtime/value/cast/boolean.ts#L5

### System Info

```shell
System: node 20.11.0
    Platform: darwin (23.3.0)
   CPU Model: Apple M1 Pro (10 cpus)
    Compiler: /Users/mak13180/site/esri/arcgis-web-components/node_modules/@stencil/core/compiler/stencil.js
       Build: 1702922611
     Stencil: 4.15.0 🐏
  TypeScript: 5.2.2
      Rollup: 2.42.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.26.0
```

### Steps to Reproduce

Run `npx stencil test --spec -- --watchAll=false`

### Code Reproduction URL

https://github.com/maxpatiiuk/vscode-jest-bug-reproduction

**Comment by rwaskiewicz** [comment]
Thanks! I was able to confirm this is a bug and have labeled it to get it ingested into our backlog.

**Comment by alicewriteswrongs** [comment]
Hey @maxpatiiuk I just put up a PR (#5672) which I believe fixes this issue. I published a [dev build](https://www.npmjs.com/package/@stencil/core/v/4.16.0-dev.1713194811.e1f6157) that includes the change if you want to try it out!

You can install it in a stencil project like so:

```sh
npm i @stencil/core@4.16.0-dev.1713194811.e1f6157
```
