### ISSUE TITLE
Firefox and IE11 shadow dom error showing unassigned slot content and unable to remove node

### ISSUE THREAD

**Issue by jagreehal** [ionic-team/stencil#565]
**Stencil version:**

0.6.5

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
The first issue is that IE11 seems to be showing unassigned slot content whereas Chrome does not. 

The second issue is an error 'removing nodes' when assigning/rendering (I'm not sure which) the slot element.

![Example](https://raw.githubusercontent.com/jagreehal/shadow-dom-ie11-issue/master/ie11-error.gif)

**Expected behavior:**

Should behave like Chrome :)

![Example](https://raw.githubusercontent.com/jagreehal/shadow-dom-ie11-issue/master/chrome-ok.gif)

**Steps to reproduce:**
See the repo https://github.com/jagreehal/shadow-dom-ie11-issue

**Comment by jagreehal** [comment]
This also happens in Firefox

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Just discussed this with my team lead and this is not something we want to support at this time in non native shadow dom browsers. It would add a lot of potentially really buggy code to Stencil. Also, browsers are fast implementing shadow dom (including Firefox) so we would be writing code for a dying issue. Finally, this same functionality can be accomplished without using slots. I will update our shadow dom docs to make a note that some advanced usage of slot will not work in non-native shadow dom browsers. Thanks for using Stencil!

**Comment by jagreehal** [comment]
Hey, @jgw96 I agree there's no point in adding code that doesn't add value, but I'd appreciate any tips for accomplishing this without using slots?

Thanks for building Stencil! :)
