### ISSUE TITLE
ES5 build invalid when using shared library

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#566]
**Stencil version:**

```
 @stencil/core@0.6.6
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When an external library (like `resize-observer-polyfill`) is imported and used in multiple components, the es5 module does not convert the reference to the incoming 'chunk' argument.

**Expected behavior:**

`__chunk#__js` argument object is used properly

**Steps to reproduce:**

1. Clone the `stencil-starter-component` repo
2. Install the npm lib `resize-observer-polyfill`
3. Create 2 components that use the ResizeObserver
4. Run `npm start` (using the `--es5` flag) and open it in IE11

- IE11 reports: `ReferenceError: 'index' is undefined...`
- Firefox does not error, but also does not load the ResizeObserver.

5. Comment out the lines related to the resize observer in either component
6. ....
7. Stuff works again! (because it no longer is used in 2 places, it just combines the external into the component)

**Related code:**
Can be used in both elements with different tag names
```tsx
import { Component, Element } from '@stencil/core';
import ResizeObserver from 'resize-observer-polyfill';

@Component({
  tag: 'x-one',
  shadow: true
})
export class XOne {
  @Element() private host: HTMLElement;

  protected componentWillLoad() {
    const observer = new ResizeObserver(() => console.log('Resizing!!!'));
    observer.observe(this.host);
  }

  protected render() {
    return <div>Hello World</div>;
  }
}

```

**Other information:**

Darn these saucy old browsers! 

This bug is not specific to 0.6.6 and I am unsure of where it started.

Still loving the library. Please keep up the amazing work. :)

**Comment by cary-smith** [comment]
I sometimes feel like I am here to plague you with IE11 (or older browser) problems 😞

**Comment by jgw96** [comment]
All good! While supporting old browser like IE11 can be challenging, it is worth it to enable users who need to support these browsers to be able to use modern tools like Stencil.

**Comment by thielCole** [comment]
Hey guys, would like to add that I believe this is the same issue I am seeing with a firebase implementation. 

```js
import '@ionic/core';
import '@stencil/core';
import { Component, Prop, Listen } from '@stencil/core';
import { ToastController } from '@ionic/core';
import { firebaseConfig } from '../../helpers/config';
import firebase from 'firebase';

@Component({
  tag: 'my-app',
  styleUrl: 'my-app.scss'
})
export class MyApp {

  @Prop({ connect: 'ion-toast-controller' }) toastCtrl: ToastController;

  configureFirebase() {
    firebase.initializeApp(firebaseConfig);
    console.log('Firebase Configured!', firebase);
  }

  componentWillLoad() {
    this.configureFirebase();
  }
```

Errors when running

```
npm run build --es5
[ ERROR ]  Runtime error detected during componentWillLoad(): my-app
           index_node is not defined ReferenceError: index_node is not defined at t.configureFirebase
           (evalmachine.<anonymous>:2:466) at t.componentWillLoad (evalmachine.<anonymous>:2:588) at
           update
```

I get a similar error when running a standard build, but the web app still builds...

**Comment by thielCole** [comment]
I believe this might not be a solo IE11 issue.

While testing functionality on safari (installed on iOS 10.3.3) I found that firebase would not work. This is also the case in Firefox.

```js
import { Component, State, Listen } from '@stencil/core';
import firebase from 'firebase';

@Component({
  tag: 'app-home',
  styleUrl: 'app-home.scss'
})
export class AppHome {

  @State() jobList: Array<any> = [];
  @State() user: any;

  componentDidLoad() {
    // Load Data!
    this.setDataListners();
    this.getUser();
    // add job...
    // this.addJob();
  }

  setDataListners() {
    // Setup Firebase Listeners To Push Data...
    let jobsRef = firebase.database().ref('jobs').orderByChild('points').limitToLast(25);
    jobsRef.once('value', (snapshot) => {
      console.log('got snapshot change');
      let tmpJobList = [];
      snapshot.forEach( (childSnapshot): any => {
        tmpJobList.push({ id: childSnapshot.key , ...childSnapshot.val() });
      });
      this.jobList = tmpJobList;
    }, (err) => {
      console.warn('Error Getting Data', err);
    });
  }
```

Also, at buildtime, I see these "runtime errors" that dont seem to have an effect on the build in chrome...

```
 ERROR ]  Runtime error detected during componentDidLoad(): app-home
           index_node is not defined ReferenceError: index_node is not defined at e.setDataListners
           (evalmachine.<anonymous>:2:1827) at e.componentDidLoad (evalmachine.<anonymous>:2:1582) at
           initComponentLoaded
```

**Comment by cary-smith** [comment]
I am not sure what commit did it, but this seems to be fixed in 0.6.13.

**Comment by thielCole** [comment]
@cary-smith Let me check. It would super nice if it did.

**Comment by thielCole** [comment]
Edit: It now works!

I had to upgrade my ionic/core version as well. My dependencies look like this.

```
  "dependencies": {
    "@ionic/core": "0.0.3",
    "@stencil/core": "0.6.13",
    "@stencil/router": "latest",
    "firebase": "^4.10.1"
  },
```

**Comment by jgw96** [comment]
Hello all! As it seems this issue has been fixed I am going to close this issue for now. Thanks for using Stencil!
