### ISSUE TITLE
[Github] The semver dependency defined in package-lock.json has a known high severity security ...

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#568]
**Stencil version:**
stencil/core": "0.6.6

**I'm submitting a:**
[X ] feature request

**Current behavior:**
After the upgrade from 0.4.0 to 0.6.6 and a push in my repo, Github trigger the following error:

> We found a potential security vulnerability in one of your dependencies.
> 
> The semver dependency defined in package-lock.json has a known high severity security vulnerability in version range < 4.3.2 and should be updated.
> 

**Expected behavior:**
No error

**Steps to reproduce:**

     npm install @stencil/core --latest
     rm -r node_modules
     rm package-lock.json
     npm install

and then commit/push in your Github repo

**Related code:**

All my dependencies:

     "dependencies": {
         "@stencil/core": "0.6.6"
       },
       "devDependencies": {
         "@stencil/dev-server": "latest",
         "@stencil/sass": "0.0.2",
         "@stencil/utils": "latest",
         "@types/jest": "^21.1.1",
         "jest": "^21.2.1"
       }

**Comment by jgw96** [comment]
Hey, thanks for the heads up. Looks like this is coming from a dependency of one of our built-in rollup plugins. Were looking into it.

**Comment by jgw96** [comment]
After further research, it looks like this is coming from the browserify-fs package. I opened an issue with them here https://github.com/mafintosh/browserify-fs/issues/13 . Luckily this does not impact Stencil itself, so we are going to close this for now. As I said above, thanks for the heads up!

**Comment by peterpeterparker** [comment]
@jgw96 thx for digging into this 👍

**Comment by jgw96** [comment]
No problem at all!
