### ISSUE TITLE
bug: cannot get value of inherited custom CSS prop in a shadow DOM element via `E2EElement` APIs

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#5681]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.16.0

### Current Behavior

It is not possible to get the value of an inherited custom CSS prop in a shadow DOM `E2EElement` via `getComputedStyle` + `getPropertyValue`. This is due to the [implementation](https://github.com/ionic-team/stencil/blob/4393a729f618f93babfd58cbce25da0dc1e1ca9a/src/testing/puppeteer/puppeteer-element.ts#L381) relying on custom CSS props being exposed on the computed style object. 

### Expected Behavior

For `shadowDomElStyles.getPropertyValue(--some-custom-prop);` to resolve to the custom CSS prop value.

### Steps to Reproduce

See README from repro case repo.

### Code Reproduction URL

https://github.com/jcfranco/stencil-e2eelement-getComputedStyle-result-is-missing-custom-css-props

**Comment by christian-bromann** [comment]
@jcfranco thanks for reporting, I raised a PR in #5682 with a fix for this.

**Comment by tanner-reits** [comment]
A fix for this was included in today's [v4.18.2 release](https://github.com/ionic-team/stencil/releases/tag/v4.18.2)!
