### ISSUE TITLE
bug: `autofocus` prop/attr is defined on other HTML attribute types instead of `HTMLAttributes`

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#5726]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.17.2

### Current Behavior

Setting the global `autofocus` attribute/prop will cause TypeScript to complain about missing definition.

The following [codepen](https://codepen.io/jcfranco/pen/dyLBvJg) shows that custom elements inherit it from `HTMLElement`.

### Expected Behavior

For `autofocus` prop/attr to be included in the base Stencil HTML attr/prop types.

### Steps to Reproduce

Follow provided steps in repro case.

### Code Reproduction URL

https://github.com/jcfranco/stencil-autofocus-missing-on-base-html-attr-type

### Additional Information

This could apply to other global attributes.

**Comment by rwaskiewicz** [comment]
Hey @jcfranco 👋 

Thanks for the bug report! 

I wasn't able to see the build failure you were describing, but _was_ able to see errors in my editor related to the type checker (see the screenshot below).
![Screenshot 2024-05-03 at 10 12 15 AM](https://github.com/ionic-team/stencil/assets/1930213/683b1610-0576-479d-bc5f-6b409328a792)

Regardless, I think this is a reasonable request/bug/thing we can fix. I see #5727 - I'll discuss that with the team internally today. 

Thanks again!

**Comment by tanner-reits** [comment]
A fix for this was included in today's [v4.18.2 release](https://github.com/ionic-team/stencil/releases/tag/v4.18.2)!
