### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by will-hu-0** [ionic-team/stencil#5736]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.18.0

### Current Behavior

We are using stencils to wrap [Carbon card groups](https://www.ibm.com/standards/carbon/v1/web-components/?path=/docs/components-card-group--default).

The internal `@state() data` is used to hold the data source. However, when updating the `@state() data`, it is found that the  description values are not updated (item.name is updated):

```
<dds-card-group>
  {data.map(item => (
    <dds-card-group-item>
      <dds-card-heading>{item?.name}</dds-card-heading>
      <p>{item.description}</p> {/* item.description is NOT being updated when the data is updated */}
    </dds-card-group-item>
  ))}
</dds-card-group>
```

It can be reproduced easily from here: https://stackblitz.com/~/github.com/will-hu-0/carbon-card-stencil-issue

The gif indicates that the card name changes while the card description keeps the same.
![May-07-2024 09-51-13](https://github.com/ionic-team/stencil/assets/4235291/ddc81cc0-7ca9-47b0-baac-2667b1474c0d)

Furthermore, the weird thing is that "removing the <p>" can resolve the issue. No idea what happened. Hope any one helps with this. Thanks.

### Expected Behavior

The values from cards should be updated.

### System Info

```shell
System: node 20.4.0
    Platform: darwin (23.4.0)
   CPU Model: Apple M1 Pro (8 cpus)
    Compiler: /Users/will/Documents/carbon-card-stencil-issue/node_modules/@stencil/core/compiler/stencil.js
       Build: 1715010794
     Stencil: 4.18.0 🍵
  TypeScript: 5.4.5
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.31.0
```

### Steps to Reproduce

In the sample code [readme](https://github.com/will-hu-0/carbon-card-stencil-issue) file

### Code Reproduction URL

https://github.com/will-hu-0/carbon-card-stencil-issue

**Comment by alicewriteswrongs** [comment]
Hey @will-hu-0 I've actually tried to reproduce this without the carbon components and I don't _think_ I'm able to - if I make the following changes to the component in your reproduction case I don't see the issue anymore:

```tsx
  render() {
    return (
    <Host>
      <button onClick={() => this.handleNext()}>
        Next
      </button>
      <div>
        {this.dataForUI.map(card => (
          <p>{card.description}</p>
        ))}
      </div>
     </Host>
    )
  }
```

Have you been able to reproduce the issue using only Stencil? We're not able to offer support for issues that crop up in third-party libraries unfortunately

**Comment by will-hu-0** [comment]
Hey @alicewriteswrongs Thanks for the quick response! I cannot reproduce it outside Carbon lib..I guess it's something weird that stencil plays with Carbon.

**Comment by Sukaato** [comment]
@will-hu-0 I can see that the issue is already closed, but I think it's important to clarify something.

The problem is that the `key` attribute is missing from the `dds-card-group-item` element.

The `key` is an important element in JSX, and must be unique to each element in the list (it's not advisable to use the index of an array).

**Comment by christian-bromann** [comment]
@Sukaato fwiw Stencil has an automatic [key insertion](https://github.com/ionic-team/stencil/pull/5594) capability but there might be situations where this doesn't work as expected. If you experience a situation like this and can create a reproducible example, we are happy to look into this.
