### ISSUE TITLE
tests break on 0.6.8

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#574]
**Stencil version:**

```
 @stencil/core@0.6.8
```

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Cannot render during tests: 
`Error: h is not a function`

**Expected behavior:**
tests will run. 

**Steps to reproduce:**
You can reproduce  with component-starter. 
@stencil/core0.6.7 will pass the tests, while 0.6.8 will fail.

**Comment by jgw96** [comment]
Hey @Tallyb , unfortunately, i cant reproduce this error. What version of node are you running? Also, is this with a completely vanilla clone of the component starter? Can you also reproduce it with the app-starter?

**Comment by jagreehal** [comment]
@Tallyb @jgw96 using https://github.com/jagreehal/stencil-boilerplate I can reproduce the error with 0.6.8. All good in 0.6.7
