### ISSUE TITLE
Stencil app deployment - caching

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#575]
**Stencil version:**
```
 @stencil/core@0.6.8
```

## Summary

There are a number of issues that arise when deploying a Stencil application.

We are using the following deployment process:
- Static build output is copied to Amazon S3
- Static content (html, js, images, etc.) is served using Amazon CloudFront CDN sourcing from S3
- All API requests are handled from app servers

We want to use an approach that not only works with service workers but also works for browsers that do not support service workers.

## Cache response headers

Our goal is to have immutable static resources (based on unique names) that can be cached forever (like the default Stencil bundle outputs).  This allows us to copy new versions of the app to S3 and not have to worry about old files that may exist on CDN / intermediate cache servers / client cache / service worker cache.  Strongly typed file versioning avoids the need for cache busting, CDN invalidations, etc.

To do this we use the following settings:
- / (root directory) - cache forever
- /index.html - override parent settings so this file is not cached

There are a number of issues with the Stencil build output that prevent this from working correctly today.  These include files that are currently not versioned:

- `/assets/*`
- `/build/app/svg/*` - may be harder to version - some discussion below
- `/build/app/vendor/swiper.d.ts` - should this be in the build output?
- `/build/app/vendor/swiper.js` - also may want to minify
- `/build/app/app.global.js`
- `/build/app/app.registry.json`
- `/build/app/chunk*.js` - I know there is an existing issue for this related to rollup
- `/build.app.js`
- `/manifest.json`
- `/sw.js`

The impact of incorrect file versions can be significant and can completely break the app from working.  For example:
- If `chunk1.js` loads an old version it may contain not only old versions of code, but may even include entirely different modules that the output from a prior build.
- If `/build/app.js` is not versioned then it is possible to have the meta data that is loaded be different than the current version of a component.
- etc.

## Proposed approach

- Every build should generate an `index.html` file that uniquely identifies all other files that comprise the application via a tree of references.  For example, if a component changes then it's bundle changes, app.js changes, and index.html changes. 
- Use a filerev type approach to add versioning to file references

## SVG icons

SVG icons may be more difficult to handle because of the way icon names are specified at runtime.

Some possible approaches include:
- A lookup table that maps name to versioned id
- An overall version prefix that changes when icons are changed (e.g. `/build/app/svg/v1/...`)
- Import desired icons as code vs dynamic file loading so that they end up in a versioned file

## Extra resources loaded

- When loading the app in the browser, the service worker cache includes all of the javascript code for both ES5 and ES6.  Does it need to load both when the browser version would likely use one or the other?
- `sw.js` looks like it includes every single SVG icon.  Does that mean they are all loaded (even if not used)?
- `sw.js` includes both iOS and md versions of all components.  Does that mean that all the iOS code is loaded into cache even on an Android device?

Possible solution would be to have multiple `sw.js` files based on platform and ES5 or ES6 support.

**Comment by adamdbradley** [comment]
In general, only the `/build/app` directory should be forever cached.

These files are only used by SSR, so they do not have to be versioned:

```
/build/app/app.global.js
/build/app/app.registry.json
```

I don't think we can safely hash any of these filenames because we're not sure how the user is referencing: `/assets/*`. We wouldn't be able to catch all the possible ways any of the user files are being used. We might be able to make an opt-in option for this and do a best guess, but I'd be worried it doesn't catch everything by default.

The `chunk` file is a known issue with rollup and is being addressed.

If you're either prerendering or not prerendering with stencil, the `/build/app.js` file get's inlined in the index.html file, which should not be forever cached. If you opted to not do that, then `/build/app.js` should not be forever cached. But again, only the `/build/app/` directory should have a forever cache.

These we could look into hashing:

```
/manifest.json
/sw.js
```

Thanks for putting this together, we'll keep improving this!

**Comment by cjorasch** [comment]
> In general, only the /build/app directory should be forever cached.

Does this include the `svg` and `vendor` subdirectories?  Or are you thinking those will remain the way they are and require checking for updates?

> I don't think we can safely hash any of these filenames because we're not sure how the user is referencing: /assets/*. 

We have been using `gulp filerev` with Ionic 3 and it works pretty well for things like assets.  It uses RegExp pattern matching so there probably are some corner cases that would be hard to catch (e.g. path calculations in js function).  If we want to do our own `gulp` processing after the Stencil build is there any prescribed way to do that or simply run both from our build scripts?

The reason we are bothering to do versioning with assets is that it is very hard to come up with caching settings with a CDN that do not lead to potential sync issues.  For example, a 10 minute TTL on an image could result in an out of date image being displayed when a new version of the app is released.

> /sw.js

I noticed`sw.js` is now in the generated `host.config.json` file with `Cache-Control: no-cache, no-store, must-revalidate`.  This file is pretty large (100K in our case) so definitely beneficial to cache on CDN.

**Comment by adamdbradley** [comment]
Started working on it: https://github.com/ionic-team/stencil/commit/65c5783baeecb5b6bc39e3f6748a2a07bffb6473

Only does HTML elements and text files in this commit, and turned off by default.

**Comment by cjorasch** [comment]
FYI - here is what I have been using for assets.  I am guessing you would not want to add gulp to the tool chain but the plugin may have some useful ideas in it since it targets the same problem.  In particular, it does a good job of thinking through cascading renaming.

```js
const gulp = require('gulp');const 
revAll = require('gulp-rev-all');

gulp.task('filerev', function() {

    return (gulp
            .src('www/**')
            .pipe(
                revAll.revision({
                    dontGlobal: [
                        /build\/app\/svg/ // Skip processing files in the svg directory
                    ],
                    dontUpdateReference: [
                        /build\// // Do not hash files in build directory
                    ],
                    dontRenameFile: [/build\//, 'host.config.json', 'index.html']
                })
            )
            .pipe(gulp.dest(config.DEST)) );
});
```

This works not only for references in the html file but also for references in the components.

**Comment by adamdbradley** [comment]
These have been removed from being in the service worker's `sw.js` file:
/build/app/app.global.js
/build/app/app.registry.json

We'll keep chipping away at these.

**Comment by henrikra** [comment]
I agree with @cjorasch that this caching problem is huge turn off when developing with StencilJS. This is the reason I am moving away from this framework because I cannot rely that up to date versions of assets file are there :(

**Comment by manucorporat** [comment]
Stencil one takes a new approach where all files stating with `p-[hash]` are cacheable! servers can now be configured to follow this rule and properly cache all the files without any risk!

**Comment by henrikra** [comment]
So which version supports this?
