### ISSUE TITLE
Listeners are registered before componentWillLoad

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#576]
Not sure if this is the expected behaviour.

```
  called = false;
  componentWillLoad() {
     called = true;
  }

  @Listen('body:event')
  onEvent(event: CustomEvent) {
      // at this point this.called should be true?
   }
```

I would say it's not safe to receive events before "willLoad" since the component might be in a inconsistent state.

**Comment by adamdbradley** [comment]
Yes, we need events to be able to be handled even before instances are created. This matters if a child component that is ready fires and event, but the parent component isn't ready MUST catch this. This is largely for ion-item to catch child events if it's not ready.
