### ISSUE TITLE
bug:  When i try to integrate with react application, the slot element contains hidden attribute instead of displaying the content. Note: This stencil component is using scoped element.

### ISSUE THREAD

**Issue by muthupriyashanmugam** [ionic-team/stencil#5799]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

v4.7.0

### Current Behavior

The stencil component contains the non shadow dom which renders the slot-based element.

The below-mentioned code is added in the component-a

```html
<div><slot name="cta"/></div>
``` 

The below-mentioned code is added to the index.html file

```html
<component-a><div slot="cta"></div></component-a>
``` 
But the output shown in the react application

```html
<slot name="cta" hidden>click here</slot>
``` 

### Expected Behavior

The slot element content should shown in the react application if it is a scoped slot element.

### System Info

```shell
npm version 10.7.0
node version 20.11.1
```

### Steps to Reproduce

Try to include the slot element in the stencil component and include it in the react application.

### Code Reproduction URL

https://github.com/muthupriyashanmugam/stencil-issue

**Comment by muthupriyashanmugam** [comment]
We are using the Stenciljs version ^4.7.0 in the package json. Let me check with the recent version and let you know.

**Comment by muthupriyashanmugam** [comment]
@tanner-reits  I have tried the latest version of stencil v4.18.0 but still it shows the hidden attribute added to the slot element.

Note: we are using the stencil library as a web component and compiling those code as a react component and used as a react npm module in another react application.

When we use the react application, we face this kind of issue.

**Comment by muthupriyashanmugam** [comment]
@tanner-reits Any update on this issue?

**Comment by tanner-reits** [comment]
@muthupriyashanmugam Can you create a complete reproduction case including the React portions? That way we can be sure to see the same behavior. Also, in your case, are you using the [React output target](https://stenciljs.com/docs/react)?

**Comment by muthupriyashanmugam** [comment]
@tanner-reits Yes, we are using the react output target option to generate the react component. In our case, the slot is adding the **hidden** attribute rendering when we use it in the **react nextjs** application.

I have tried to test this case in a sample react application, it's working fine. Then only I come to know that it may be the react nextjs makes an issue.

**Comment by muthupriyashanmugam** [comment]
@tanner-reits  Could you please help me to find out the cause for the issue which i am facing is that if i include my stencil scoped component in a nextjs react application as a node module, it's rendering as a shadow-root component.
