### ISSUE TITLE
Missing minimist dependency

### ISSUE THREAD

**Issue by dpellier** [ionic-team/stencil#580]
**Stencil version:**

```
 @stencil/core@0.6.15
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I think the core miss a dependency on 'minimist'

**Expected behavior:**

**Steps to reproduce:**

Create a fresh project with just `@stencil/core` as a dependency, `npm i`, then `./node_modules/.bin/stencil build`.

You'll get the error `Error: Cannot find module 'minimist'`

**Related code:**
In `cli-utils.ts`
```tsx
const minimist = require('minimist');
```

**Other information:**

Node: v8.9.1
Npm: 5.6.0

**Comment by adamdbradley** [comment]
Thanks for filing the issue! Crazy this hasn't come up earlier, guess it was a coincidence all projects had minimist already installed some how. Should be fixed now, thanks!
