### ISSUE TITLE
add `namedExports` config to common js rollup plugin

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil#583]
If a commonjs library exports some kind of global, such as `L` for leaflet, this config will make sure that global gets exported correctly in a project. 

Also, a note from @jthoms1 ``` I think it is doable, we would need to add some configuration for it to expose the interface for devs. We can add it to the roadmap for next release.```

Thanks for the idea on this @finneganh !

**Comment by jgw96** [comment]
@jthoms1 added this to 0.8 for now, but feel free to move that around

**Comment by jthoms1** [comment]
This configuration option was added with commit d807ea17ecb5b68762c35ddbdd86bdd0e5c34664.  This will be available as the following configuration in the next release of stencil.
```js
  commonjs: {
    namedExports: {
      'red': ['blue', 'green']
    }
  }
```
