### ISSUE TITLE
bug: Generation of src/components.d.ts typing broken in latest build

### ISSUE THREAD

**Issue by joewoodhouse** [ionic-team/stencil#5859]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.19.0

### Current Behavior

The generated `src/components.d.ts` file is corrupt, with missing identifiers in the import and export statements. For example:

```
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import {  as BBox } from "geojson";
export {  as BBox } from "geojson";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "bbox": BBox;
    }
    interface AppRoot {
    }
}
...
```

### Expected Behavior

The `src/components.d.ts` file should be built correctly.

If you switch back to @stencil/core@4.18.0 then the issue is no longer present.

### System Info

```shell
❯ npx stencil info

      System: node 18.18.2
    Platform: darwin (23.5.0)
   CPU Model: Apple M1 Pro (8 cpus)
    Compiler: /Users/joewoodhouse/src/stencil-import-type-issue/node_modules/@stencil/core/compiler/stencil.js
       Build: 1719433468
     Stencil: 4.19.0 🏄
  TypeScript: 5.4.5
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.31.1
```

### Steps to Reproduce

```
git clone https://github.com/joewoodhouse/stencil-import-types-issue
cd stencil-import-types-issue
npm install
npm run build
cat src/components.d.ts
```

### Code Reproduction URL

https://github.com/joewoodhouse/stencil-import-types-issue

### Additional Information

Almost certainly related to this change
https://github.com/ionic-team/stencil/commit/7ffb25d259de5b863e7dc3bc43270265cc786557#diff-1079cab98429d9a563cc8bb366896edc0ccf6b1c3e113771acf0ddaa3f52484b

**Comment by tanner-reits** [comment]
@joewoodhouse I've confirmed the issue here. We'll get a fix up for this ASAP!
