### ISSUE TITLE
bug: `./cli` and `./sys/node` excluded from exports field in the package.json

### ISSUE THREAD

**Issue by dgonzalezr** [ionic-team/stencil#5864]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.19.0

### Current Behavior

I'm trying to update to the latest stencil version released but we are getting the following error now:
```
Package subpath './cli' is not defined by "exports" in {WorkspaceDir}/node_modules/@stencil/core/package.json
```
we have an NX monorepo that uses @nxext/stencil to handle stencil CLI commands, and it seems that ./cli has. been omitted in the exports field here: https://github.com/ionic-team/stencil/pull/5842/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R25 

Do you know if this was on purpose? 🤔  Because [according to the documentation](https://stenciljs.com/docs/cli-api), we should be able to use the CLI API.

You can see here 👇  how @nxext/stencil import some stuff from @stencil/core/cli:
https://github.com/nxext/nx-extensions/blob/main/packages/stencil/src/executors/stencil-runtime/stencil-config.ts#L1:weary: 

### Expected Behavior

We should be able to import stuff from `@stencil/core/cli`.

### System Info

```shell
System: node 22.3.0
    Platform: darwin (23.5.0)
   CPU Model: Apple M1 (8 cpus)
    Compiler: /Users/dgonzalezr/PROJECTs/ENDAVA/BEEQ-Design-System/node_modules/@stencil/core/compiler/stencil.js
       Build: 1719433468
     Stencil: 4.19.0 🏄
  TypeScript: 5.4.5
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.31.1
```

### Steps to Reproduce

1. Create a stencil starter project: `npm init stencil`
2. Open the `stencil.config.ts` file and add the following:

```ts
import { Logger } from '@stencil/core/cli';
import { createNodeLogger } from '@stencil/core/sys/node';

const logger: Logger = createNodeLogger({ process });
```

Here is a screenshot of the issue in a brand-new Stencil starter project.

![CleanShot 2024-06-27 at 19 53 29@2x](https://github.com/ionic-team/stencil/assets/328492/7fba365e-d6d4-48f9-91ff-b72853015848)

**Comment by christian-bromann** [comment]
Apologies for missing the CLI export. I've raised a PR in https://github.com/ionic-team/stencil/pull/5865 and plan to release this today.

**Comment by dgonzalezr** [comment]
Thank you @christian-bromann 🙌🏼.
Just a quick question, what about ’./sys/node’? Because ’createNodeLogger’ seems to be imported from there on ’@nxext/stencil’

**Comment by christian-bromann** [comment]
Interesting 🤔  these are not public APIs but I will add them anyway to preserve backwards compatibility.
