### ISSUE TITLE
bug: Broken exports for testing

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#5871]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.19.0 

### Current Behavior

Using in jest config file the following: 
```
preset: @stencil/core/testing
transform: @stencil/core/testing/jest-preprocessor
```
Worked ok until 4.18.2
currently getting error: 
```
  Preset @stencil/core/testing not found.

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

### Expected Behavior

work as before
quite likely as a result of this:  https://github.com/ionic-team/stencil/commit/a2fa93b504d2ff2a3a3534ed5489af977552a273
Partial fix was only for mockDoc imports. https://github.com/ionic-team/stencil/issues/5860

### System Info

```shell
node 20. 
npm 10.7
```

### Steps to Reproduce

build a simple jest config with preset @stencil/core/testing
Try to run jest. 

### Code Reproduction URL

n/a

**Comment by christian-bromann** [comment]
@Tallyb thanks so much for reporting the bug and apologize for the regression. I have raised a PR with a bug fix. We were not aware that this was a use case for Stencil users. Moving on we have tests for this in place to ensure it won't break again.
