### ISSUE TITLE
Attribute changes doesn't reflect on properties after initialization

### ISSUE THREAD

**Issue by kurtlobato** [ionic-team/stencil#588]
**Stencil version:**

```
 @stencil/core@0.6.16
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Changing an attribute in runtime won't reflect on the corresponding element property, wich breaks integration with angularjs

**Expected behavior:**

Changes on an attribute should be reflected on the property

**Steps to reproduce:**

- Download and run stencil app starter
- Change an attribute on runtime with dev tools
- Nothing changes

**Comment by adamdbradley** [comment]
Added Prop decorator option, `reflectToAttr`

```
@Prop({
  reflectToAttr: true
})
```
