### ISSUE TITLE
bug: Cannot find module '@stencil/core/testing/jest-preset' after upgrading to Stencil 4.19.2

### ISSUE THREAD

**Issue by geovanesantana** [ionic-team/stencil#5896]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.19.2

### Current Behavior

This error occurs when trying to import `moduleNameMapper` from `@stencil/core/testing/jest-preset` in the Stencil configuration file:

```typescript
import { moduleNameMapper } from '@stencil/core/testing/jest-preset';

### Expected Behavior

Should work as it did in previous versions, allowing the use of `moduleNameMapper` from `@stencil/core/testing/jest-preset`.

### System Info

```shell
Node 20.11.1
PNPM 9.3.0
CPU Model: Apple M3
Stencil: 4.19.2
```

### Steps to Reproduce

1. Upgrade @stencil/core to version 4.19.2
2. Attempt imports `moduleNameMapper` from @stencil/core/testing/jest-preset
3. Observe the mentioned error

### Code Reproduction URL

n/a

### Additional Information

```
Error: Cannot find module
@tc/stencil-library:build:            '/Users/xxxx/Documents/work/cars/node_modules/@stencil/core/testing/jest-preset' at
```

**Comment by christian-bromann** [comment]
@geovanesantana would `@stencil/core/testing/jest-preset.js` work?

**Comment by geovanesantana** [comment]
Hey @christian-bromann,
Thanks for the help! It’s working now. Thanks!

**Comment by christian-bromann** [comment]
Thanks for validating @geovanesantana , I raised a PR https://github.com/ionic-team/stencil/pull/5900 to fix the regression we've introduced.

**Comment by mattclough1** [comment]
Noticing the same thing with importing `@stencil/core/compiler`. I'm fixing currently by importing `@stencil/core/compiler/stencil.js`
