### ISSUE TITLE
Default tsconfig settings for "dev" mode

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/stencil#590]
Okay okay, hear me out.

I _really_ like having `noUnusedLocals` and `noUnusedParameters` set in my TSConfig so that when I do a production build, I am not accidentally including something that I don't intend to, etc. It is a super useful feature of TypeScript. Generally the stricter settings the better.

_but_

It is incredibly annoying having these settings on during active development because builds that technically would/should compile fail when you comment something out, etc.

Does it make sense to loosen up the TSConfig rules during development, or expose a setting in the stencil config to do so?

Low priority feature request but it would improve the developer experience I think.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Oooo, proposal!

Maybe if there is a `tsconfig.dev.json` or something, some convention, use that when in "dev" mode? That might be the most pragmatic option.

Thanks,
Dan

**Comment by ahmadalfy** [comment]
That's a great point, initially during development people tend to continuously refactor, add and remove stuff all of the time.

**Comment by adamdbradley** [comment]
This is a developer preference and is configurable in all projects. Thanks
