### ISSUE TITLE
bug: [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './screenshot' is not defined by "exports" in …/node_modules/@stencil/core/package.json

### ISSUE THREAD

**Issue by ryuran** [ionic-team/stencil#5906]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

`>= v4.19.0`

### Current Behavior

If we set a screenshot cnnector like told by the documentation https://stenciljs.com/docs/screenshot-connector
When run test with screensot : `stencil test --e2e --screenshot`

This error appear
```
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './screenshot' is not defined by "exports" in …/node_modules/@stencil/core/package.json
```

### Expected Behavior

Run screenshot test as before without this error message.

### System Info

```shell
System: node 18.18.2
    Platform: darwin (23.5.0)
   CPU Model: Apple M1 Pro (10 cpus)
    Compiler: …/node_modules/@stencil/core/compiler/stencil.js
       Build: 1719938890
     Stencil: 4.19.2 🏉
  TypeScript: 5.4.5
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.31.1
```

### Steps to Reproduce

Add a screenshot connector like the doc say https://stenciljs.com/docs/screenshot-connector#methods
Then run the command
run `stencil test --e2e --screenshot`

### Code Reproduction URL

https://github.com/ryuran/stencil-bugs/tree/screeshot-export-bug

### Additional Information

The connector try to import `const { ScreenshotLocalConnector } = require('@stencil/core/screenshot');` but `@stencil/core/screenshot` is not exposed by `@stencil/core` package.json

**Comment by christian-bromann** [comment]
@ryuran thanks for reporting. This was a regression and I opened a PR to resolve the bug.
