### ISSUE TITLE
bug: incorrect TestingConfig/JestConfig type

### ISSUE THREAD

**Issue by punit-shah** [ionic-team/stencil#5908]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [x] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [x] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Stencil version

`4.19.2`

### Current behavior

When setting certain properties in Stencil's testing config, such as `restoreMocks: true`, I get TypeScript errors.

Full list of properties in the `JestConfig` interface that are incompatible with Jest's `Config` type:
- `bail`
- `globalSetup`
- `globalTeardown`
- `preset`
- `prettierPath`
- `resolver`
- `restoreMocks`
- `testRegex`
- `transform`

### Expected behavior

These errors should not occur. Setting this property to a boolean is correct, why does it expect a string?

### Steps to reproduce

Set the `testing.restoreMocks` property in `stencil.config.ts`

```ts
export const config: Config = {
  // ...
  testing: {
        // ...
        restoreMocks: true,
    },
};
```

TypeScript will throw the following error:
```
Types of property 'restoreMocks' are incompatible.
  Type 'boolean' is not assignable to type 'string'.
```

### Additional information

Looks like the `JestConfig` interface contains incorrect types.
https://github.com/ionic-team/stencil/blob/7ae36aa5caae278787ff79e63093d4337bfd13c0/src/declarations/stencil-public-compiler.ts#L1790

Could this be updated to use the `Config` type directly from Jest, instead of defining your own interface?
```ts
import type { Config as JestConfig } from 'jest';

export interface TestingConfig extends JestConfig {
  // ...
}
```

**Comment by christian-bromann** [comment]
@punit-shah thanks for reporting. These types were updated in Jest but never revisited in Stencil. I raised a PR with an update.
