### ISSUE TITLE
Static node map

### ISSUE THREAD

**Issue by arjunyel** [ionic-team/stencil#597]
**Stencil version:**

```
 @stencil/core latest
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Example from [ionic-pwa-toolkit](https://github.com/ionic-team/ionic-pwa-toolkit/pull/29/files#diff-6ff4e0c3b0812975d50d337948bf36dbR31)

When there are static DOM elements an optimization would be to querySelector them  by ID on load

**Expected behavior:**

There is two ways to approach this:

1. Generate a node list at run time and make it available like [Polymer's static node map](https://www.polymer-project.org/2.0/docs/devguide/dom-template#node-finding)

1.  A new Stencil decorator, Node, that queries for static elements with the given DOM id like [Angular's ViewChild](https://angular.io/api/core/ViewChild).

```typescript
import {Component, Node, Prop} from '@stencil/core';

@Component({
  tag: 'lazy-img',
  styleUrl: 'lazy-img.css'
})
export class LazyImg {
  @Prop() src: string;
  @Prop() alt: string;
  @Node('#image') image: HTMLImageElement;

  componentDidLoad() {
    console.log(this.image);
  }

  render() {
    return (<img id="image" src={this.src} alt={this.alt}></img>);
  }
}
```

**Comment by adamdbradley** [comment]
We have debated this in the past, and it would be very similar to what Angular and Polymer provides. However, like you pointed out it'd just end up using querySelector, which is already an API which developers understand. What we're trying to avoid is teaching new concepts and new ways of doing something developers already know how to do. We don't want to shy away from DOM apis that are already documented across the web and work well. Additionally, it would involve adding more runtime code to everyone's build. We may very well end up doing this, but this early in the stage I'd like to try to not introduce new custom APIs if we don't have to. Thanks.

**Comment by jthoms1** [comment]
You could also just use ref to accomplish the same thing.
```ts
import {Component, Node, Prop} from '@stencil/core';

@Component({
  tag: 'lazy-img',
  styleUrl: 'lazy-img.css'
})
export class LazyImg {
  @Prop() src: string;
  @Prop() alt: string;
  image: HTMLImageElement;

  componentDidLoad() {
    console.log(this.image);
  }

  render() {
    return (<img ref={(el) => this.image = el} src={this.src} alt={this.alt}></img>);
  }
}
```

**Comment by arjunyel** [comment]
Wow that's perfect, I haven't seen ref/that syntax before, where can I find documentation on it? Does that work on dynamically added DOM nodes? Thanks!

**Comment by jthoms1** [comment]
It does work on dynamic nodes as well. The function gets called as soon as the node hits the dom.  Unfortunately I am finding that we do not have documentation on this.  I will work with @jgw96 to ensure we get some added. Thanks!

**Comment by arjunyel** [comment]
For the documentation it would be great if you touch on how to reference a single node like above and also how to reference an array of nodes, for example if I rendered out multiple <img> tags. Thanks again!
