### ISSUE TITLE
bug: TypeError: Cannot read properties of undefined (reading 'createHTMLDocument') when using renderToString in NextJS

### ISSUE THREAD

**Issue by vivere-dally** [ionic-team/stencil#5978]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.21.0

### Current Behavior

Followed the [hydrate](https://stenciljs.com/docs/hydrate-app) docs and added a new output target:
```json
  {
    type: 'dist-hydrate-script',
  },
```

Running build produces and output.

```js
import { renderToString } from 'mypkg';

export default async function handler(req, res) {
  const resp = await renderToString('<mycomponent></mycomponent>', {
    fullDocument: false,
  });
  res.status(200).send(resp);
}
```

causes
> error - TypeError: Cannot read properties of undefined (reading 'createHTMLDocument')
    at .../node_modules/mypkg/index.js:12292:37
    at .../node_modules/mypkg/index.js:12295:4
    at .../node_modules/mypkg/index.js:2226:4
    at .../node_modules/mypkg/index.js:2236:4
    at hydrateAppClosure (.../node_modules/mypkg/index.js:12857:2)
    at hydrateFactory (.../node_modules/mypkg/index.js:23821:3)
    at .../node_modules/mypkg/index.js:39166:37

### Expected Behavior

work

### System Info

```shell
System: node 20.12.2
    Platform: darwin (23.6.0)
   CPU Model: Apple M3 Pro (12 cpus)
    Compiler: .../node_modules/@stencil/core/compiler/stencil.js
       Build: 1724698030
     Stencil: 4.21.0 🐷
  TypeScript: 5.5.3
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.31.1
```

### Steps to Reproduce

Just add the hydrate output to an existing working stencil components project

### Code Reproduction URL

no

**Comment by tanner-reits** [comment]
@vivere-dally I checked things out in a prerender app I have and didn't experience any errors. If you have a reproduction case that's failing I can take a look at that, but won't be able to offer help otherwise.
