### ISSUE TITLE
bug: Asset Copying Issue Folder Structure Flattened in Version 4.21.0

### ISSUE THREAD

**Issue by luisbytes** [ionic-team/stencil#5983]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.21.0

### Current Behavior

Files in subfolders, like `assets/icons/home.svg`, are copied to the top-level folder (`assets/home.svg`), losing the original folder structure.

### Expected Behavior

The folder structure should be preserved, so `assets/icons/home.svg` should remain in `assets/icons/home.svg`.

### System Info

```shell
System: node 20.15.0
    Platform: darwin (22.6.0)
   CPU Model: Apple M1 Pro (10 cpus)
    Compiler: /node_modules/.pnpm/@stencil+core@4.21.0/node_modules/@stencil/core/compiler/stencil.js
       Build: 1724698030
     Stencil: 4.21.0 🐷
  TypeScript: 5.5.3
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.31.1
```

### Steps to Reproduce

1. Create a subfolder inside assets (e.g., `assets/icons/`).
2. Place a file in that subfolder (e.g., `assets/icons/home.svg`).
3. Build with version `4.21.0`.
4. Observe that the file is copied to `assets/home.svg` instead of `assets/icons/home.svg`.

### Code Reproduction URL

https://github.com/ionic-team/stencil

### Additional Information

- This behavior was working correctly in version `4.20.0.`
- It seems the issue was introduced with PR #5899.
- Additionally, issues #5957, #5966, and #5956 appear to be related to the same PR #5899.

**Comment by tanner-reits** [comment]
@luisbytes I've confirmed the issue here. In fact, I think this was causing some issues for us in Ionic Framework recently. I'll get this in our backlog so we can take a closer look. Thanks for linking those other issues as well!

**Comment by Loic57** [comment]
@luisbytes @tanner-reits Same issue here.
It looks like there is a new prop keepDirStructure for the copy task.
I used it and everything was fixed : https://stenciljs.com/docs/copy-tasks#keepdirstructure
