### ISSUE TITLE
Components with digits-after-dashes in their name do not work in legacy browsers

### ISSUE THREAD

**Issue by vially** [ionic-team/stencil#599]
**Stencil version:**

```
 @stencil/core@0.6.16
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Components which contain digits-after-dashes in their name (e.g.: `my-3d-component`) do not work in legacy browsers (the ones requesting the `.es5.js` version of the component). The component works fine in the other browsers.

**Expected behavior:**

The name of the component should not affect it's behavior on legacy browsers, as long as the name is a valid component name.

**Steps to reproduce:**

Create a component named `my-3d-component` and try to load it in legacy browsers (e.g.: `Edge` or `Internet Explorer 11`. It will not render anything.

**Other information:**

The problem stems from the implementation of the [toDashCase](https://github.com/ionic-team/stencil/blob/59de9ce5ad3c395ee6170e76247ebef3675fb867/src/util/helpers.ts#L14) function.
It is called from [platform-client-legacy.ts](https://github.com/ionic-team/stencil/blob/59de9ce5ad3c395ee6170e76247ebef3675fb867/src/client/platform-client-legacy.ts#L198) and it converts `My3dComponent` to `my3d-component` instead of `my-3d-component`.

**Comment by adamdbradley** [comment]
thanks for opening, the issue, should be fixed in the next release, thanks

**Comment by vially** [comment]
Thanks for fixing this so quickly. 

I haven't tried this yet but looking at the commit it looks like if you now have a component like:

```ts
@Component({
    tag: 'my3d-component',
})
export class My3dComponent {}
```

the new code change will convert `My3dComponent` to `my-3d-component` which is wrong in this case (because now it should be `my3d-component`).

I'm not familiar with the code and there may be something I'm missing, but why is it necessary to rely on string conversion when the relationship between the class name and the tag name is clearly defined in the component? This string conversions do seem a bit unreliable.
