### ISSUE TITLE
Unable to use multiple bundles in an app

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil#60]
For some reason when I try to separate pages into multiple bundles in the stencil-site project, those pages are not generated. However, when I bundle them into one single bundle, it works again. 

Here's an example of the failing config:

<img width="823" alt="screen shot 2017-07-20 at 9 13 48 pm" src="https://user-images.githubusercontent.com/11214/28446442-5b9bbc74-6d90-11e7-8cc4-a2d8193c2c43.png">

with the console error:

<img width="1116" alt="screen shot 2017-07-20 at 9 17 49 pm" src="https://user-images.githubusercontent.com/11214/28446525-e955e3a0-6d90-11e7-8a7c-b210974cbe04.png">

Changing the config to this makes it work again:

<img width="949" alt="screen shot 2017-07-20 at 9 14 11 pm" src="https://user-images.githubusercontent.com/11214/28446454-64faa230-6d90-11e7-9590-32d8ecc0c5d5.png">

**Comment by motss** [comment]
Is this fixed?
