### ISSUE TITLE
Slow fiber demo

### ISSUE THREAD

**Issue by megaza** [ionic-team/stencil#600]
**Stencil version:**

```
 @stencil/core@0.6.18
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
On latest Chrome version (64.0.3282.186) Fiber Demo has delay during node update, and node highlight is not working on mouse hover. Maybe problem is in demo implementation, but should be fixed.

**Expected behavior:**
Demo should represent his description "This showcases the runtime performance of stencil using our async rendering". Comparing to react fiber there is no performance problem https://claudiopro.github.io/react-fiber-vs-stack-demo/

**Steps to reproduce:**
1. Clone https://github.com/ionic-team/stencil-fiber-demo.git
2. Update stencil to latest version
3. npm run dev

**Comment by jgw96** [comment]
Hey! This will be much better once we implement https://github.com/ionic-team/stencil/issues/443. I am going to close this issue for now and link to it in that issue. Thanks for using Stencil!
