### ISSUE TITLE
bug: Add missing HTML reserved keyword

### ISSUE THREAD

**Issue by Sukaato** [ionic-team/stencil#6000]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.21

### Current Behavior

the file `src/compiler/transformers/reserved-public-members.ts` does not have all reserved HTML keyword, and sometimes it can have unexpected behavior

(eg: if you have a `popover` property to store `HTMLElement`, in development mode it work perfectly fine, but when the web-component is transformed into Vue component the `popover` is reflected on HTML, and broke the style and the HTML

### Expected Behavior

Warn the developer about new reserved keyword

### System Info

```shell
System: node 20.16.0
    Platform: linux (5.15.153.1-microsoft-standard-WSL2)
   CPU Model: AMD Ryzen 7 5700X 8-Core Processor (16 cpus)
    Compiler: /home/sukaato/projects/poppy-ui/node_modules/@stencil/core/compiler/stencil.js
       Build: 1722623140
     Stencil: 4.20.0 🚐
  TypeScript: 5.5.3
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.31.1
```

### Steps to Reproduce

1. Run `sh demo.sh` (install project)
2. Run `npm start -w @test/core` to see how stencil handle the keyword `popover` in dev.
3. Run `npm start -w @test/demo` to see how outside stencil the keyword `popover` is handled.

### Code Reproduction URL

https://github.com/Sukaato/stencil-reserved-keyword

### Additional Information
Add the reserved keyword to `src/compiler/transformers/reserved-public-members.ts`in `HTML_ELEMENT_KEYS` array.

**Comment by christian-bromann** [comment]
A fix for this has been released in Stencil `v4.22.0` 🎉
