### ISSUE TITLE
EventEmitter is undefined

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#601]
**Stencil version:**

```
 @stencil/core@0.6.18
```

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Event emitters are not initialised during tests if the class is just instantiated and not rendered. 

**Expected behavior:**
Should be able to test components that emit events even without rendering. 

**Steps to reproduce:**
Emit an event in the code component. In testing, initialize the component and trigger the action that will emit the event. 
The following error will appear: 
`    TypeError: Cannot read property 'emit' of undefined`

**Related code:**
Add the following to stencil-component-starter project and run tests
```tsx
// my-component.ts
  @Event() myEvent: EventEmitter<boolean>

  doSomething() {
    this.myEvent.emit(true)
  }

// my-component.spec.ts
it('should emit on method call', () => {
    let comp = new MyComponent();
    comp.doSomething();
  });



```

**Other information:**

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Would you mind sharing what your whole test looks like?

**Comment by scottopherson** [comment]
I experienced this as well using `@stencil/core@0.6.5`. Here's a trimmed down version of the component and spec I was working with:

my-component.tsx:
```ts
import { Component, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'my-component'
})
export class MyComponent {

  @Event() toggle: EventEmitter<boolean>;

  opened: boolean = false;

  handleToggle() {
    this.opened = !this.opened;
    this.toggle.emit(this.opened);
  }

  render() {
    return (
      <div>my component</div>
    );
  }
}
```

my-component.spec.tsx:
```ts
import { MyComponent } from './my-component';

describe('my-component', () => {
  describe('handleToggle()', () => {
    it('toggles `opened`', () => {
      const cmp = new MyComponent();
      cmp.handleToggle();
      expect(cmp.opened).toEqual(true);
    });

    it('emits toggle event', done => {
      const cmp = new MyComponent();
      const spy = jest.spyOn(cmp.toggle, 'emit');
      cmp.handleToggle();
      expect(spy).toHaveBeenCalledWith(true);
    });
  });
});
```

Results:
```
FAIL  src/my-component/my-component.spec.tsx
 ● my-component › handleToggle() › toggles `opened`

   TypeError: Cannot read property 'emit' of undefined

 ● my-component › handleToggle() › emits toggle event

   Cannot spyOn on a primitive value; undefined given
```

**Comment by Tallyb** [comment]
@jgw96 the test above is the whole code and test. You can just add my code to stencil-component-starter. (just need to fix the relevant imports). There is not even a need to expect, as the test will fail because of the error.

**Comment by bitflower** [comment]
Related to #618 ?

**Comment by Tallyb** [comment]
@bitflower I don't think so. This is 0.6.18 thing.

**Comment by hartjus** [comment]
I'm experiencing this issue as well.  Is there a way to mock or provide the EventEmitter to the component when instantiated (vs rendered)?

**Comment by hartjus** [comment]
@Tallyb The event emitter is actually really easy to mock.  This will at least get you around the issue:
```
it('should test something', () => {
  // mock the event emitter
  component.someEventEmitter = {
    emit: () => {}
  };

  const spy = jest.spyOn(component.someEventEmitter, 'emit');
  component.methodThatCallsEventEmitter();
  expect(spy).toHaveBeenCalled();
});
```

Hope this helps!

**Comment by Tallyb** [comment]
@hartjus  - helps indeed. thanks for this solution.

**Comment by lukasIO** [comment]
I'm experiencing this issue after cloning the stencil-app-starter and copy pasting some event code from the documentation (updated to 0.17.1)

```tsx
import { Component, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'app-root',
  styleUrl: 'app-root.css',
  shadow: true
})
export class AppRoot {

  @Event() todoCompleted: EventEmitter;

  todoCompletedHandler() {
    this.todoCompleted.emit();
  }
  
  render() {
    return (
      <div>
        <header>
          <h1>Stencil App Starter</h1>
        </header>
        <main>
          <button onClick={this.todoCompletedHandler}></button>         
        </main>
      </div>
    );
  }
}

```

**Comment by mikeysteele** [comment]
You could also do it like using an arrow function.
`
todoCompleteHandler = () => {
     this.todoCompleted.emit();
}
`

**Comment by bwhiting2356** [comment]
> @Tallyb The event emitter is actually really easy to mock. This will at least get you around the issue:
> 
> ```
> it('should test something', () => {
>   // mock the event emitter
>   component.someEventEmitter = {
>     emit: () => {}
>   };
> 
>   const spy = jest.spyOn(component.someEventEmitter, 'emit');
>   component.methodThatCallsEventEmitter();
>   expect(spy).toHaveBeenCalled();
> });
> ```
> Hope this helps!

This was very helpful, thank you!!

I did find that typescript was complaining if I just mocked it with `emit: () => {}` but I solved that by changing it to this: `emit: (data?: any) => new CustomEvent(data)`, in case that helps anyone else...
