### ISSUE TITLE
CSS variable shimming messes up relative URLs in CSS

### ISSUE THREAD

**Issue by finneganh** [ionic-team/stencil#602]
**Stencil version:**

```
 @stencil/core@0.6.18
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

The `<style>` that the CSS variable shimming applies can cause relative resources to be loaded from the wrong server.

If the CSS file is loaded from another domain and contains relative URLs, the setting of `innerHTML` will cause those URLs to be loaded relative to the document’s domain, rather than the domain that the CSS file came from.

This can cause 404s, since the resources aren’t available, which in our experience it breaks `@font-face` declarations in IE, overwriting the correct URLs with ones that 404.

**Expected behavior:**

The resources loaded by the shimmed CSS should be the same as those in the original CSS, relative to the domain that the CSS came from.

**Steps to reproduce:**

1. Use IE 11, which needs CSS variable support shimmed.
1. `<link>` to a CSS file on another domain with relative URLs (_e.g._ `url(/images/logo.png)`) that also includes CSS variables (or has `--` somewhere in it). You can use our styles at: https://patterns.boston.gov/css/public.css
1. In the web inspector, notice the 404s for assets

**Related code:**

https://github.com/ionic-team/stencil/blob/6f27283729b3f4a20acf3c718ed3a6474515d14a/src/client/css-shim/init-css-shim.ts

**Other information:**

**Comment by petrinecp** [comment]
Hi I'm having the same issue, I've created a repository to demonstrate the issue
https://petrinecp.github.io/stencil-ie11-bem-bug/
https://github.com/petrinecp/stencil-ie11-bem-bug
The icon is correctly displayed in all browsers except IE11. After removing the BEM css style (or the generated JS file by stencil) the linked css file is no longer inlined.
