### ISSUE TITLE
CSS variable shimming triggers on "--" in class names

### ISSUE THREAD

**Issue by finneganh** [ionic-team/stencil#603]
**Stencil version:**

```
 @stencil/core@0.6.18
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
The CSS variable shimming code triggers if it sees `var(` or `--` anywhere in the CSS file. This means that it runs if any classes have `--` in them.

This means that the shimming gets applied even in cases that don’t use CSS variables, which can then trigger bugs like #602 and at the very least cause an unnecessary repaint.

**Expected behavior:**

The CSS variable shimming should look specifically for variable declarations, which would be some variant on the regexp: `/--[-a-ZA-Z0-9]+:/` to capture the “:” at the end.

**Steps to reproduce:**

1. Use IE 11
1. `<link>` a stylesheet that includes `--` but no CSS variables (such as https://patterns.boston.gov/css/public.css)
1. Notice the new `<style>` tag added 

**Related code:**

https://github.com/ionic-team/stencil/blob/6f27283729b3f4a20acf3c718ed3a6474515d14a/src/client/css-shim/init-css-shim.ts

**Other information:**

**Comment by adamdbradley** [comment]
Thanks for submitting the issue, should be fixed in the next release. thanks!

**Comment by finneganh** [comment]
@adamdbradley thanks for the quick fix! Parsing with regexps is almost always inexact, but I think you’d have to really be trying in order to get a false positive here.

**Comment by finneganh** [comment]
@adamdbradley Blargh. Looks like pseudo-classes breaks the check. E.g. `.lnk--white:hover{…}`

**Comment by finneganh** [comment]
I wonder if we can update the check to make sure things end in a semicolon?
