### ISSUE TITLE
Are Stencil decorators compile-time only? Or is there a runtime option?

### ISSUE THREAD

**Issue by trusktr** [ionic-team/stencil#6031]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

This isn't a feature request per se, however signing up for the forums requires handing over read/write permissions to my private repositories in order to log in which I can't accept.

I'm writing here because I'm curious if the new stage 3 standard decorator format has any impact on how decorators are implemented in Stencil.

My hunch is that if the decorators are compile-time annotations only, then runtime doesn't matter.

If Stencil does have a runtime decorator implementation, I would like to get feedback on whether the following problem and the solution idea make things eadier for decorator authors and/or decorator users:

[discrepancy: we're allowed to get/set private fields, but not public fields, and public auto accessors are not fields.](https://x.com/trusktr/status/1846989651543802133)

Maybe this has no impact on Stencil at all if it will not have decorators at runtime.

### Describe the Use Case

Define a Stencil component without using the compiler, while still using decorators (requires runtime implementation).

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
