### ISSUE TITLE
bug: @Listen event listeners are firing twice if `dist-custom-elements` component had been reconnected to DOM.

### ISSUE THREAD

**Issue by raqushque** [ionic-team/stencil#6045]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.19.0

### Current Behavior

Event listeners added via `@Listen` decorator are fired twice if component was reconnected to DOM.

Only components built with output target `dist-custom-elements` are affected.

Binding listeners in JSX works properly.

### Expected Behavior

Event listeners are fired once.

### Steps to Reproduce

- Create a Stencil component.
- Use `@Listen` decorator to listen to any event (like keydown).
- Build component using 'dist-custom-elements' target.
- Use built component on some html page.
- Move component in DOM (or reattach it with `el.remove()` + `appendChild(el)`).
- Event listener runs twice.

### Code Reproduction URL

https://github.com/raqushque/stencil-listen-bug

### Additional Information

Issue does not appear on versions prior to 4.19

**Comment by christian-bromann** [comment]
@raqushque thanks for raising this issue and providing a reproduction case.

A fix for it has been released in https://github.com/ionic-team/stencil/releases/tag/v4.22.3
