### ISSUE TITLE
Stencil app does not work from directory root location

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#605]
**Stencil version:**
```
 @stencil/core@0.6.18
```

**I'm submitting a:**
[x] bug report

**Expected behavior:**
The Stencil app I am building runs from a root directory.  For example: `www.mydomain.com/myapp`.

When I deploy the app to that location the page does not load.

I tried changing various config settings including `publicPath: "/myapp/build"` but was not able to get the app to run from the directory location.

There are several part of the build output that would need to change to handle the directory location.

- The generated `index.html` file has several references to files at a root location.  For example: `script src="/build/app.js"`, `href="/manifest.json"`, etc.  These did not change when I modified the `publicPath` setting.
- Dynamically loading bundles, chunks, etc. load from a root location.

**Use case:**

The use case is a domain name that is being used for a large public website and one or more apps that use the same domain name but do not provide all of the www marketing content.  I guess this would also apply to any time where multiple Stencil apps were using the same host name.

**Comment by hufan-akari** [comment]
related issue #555 .

**Comment by adamdbradley** [comment]
Since this is related to #555 I'll close this one, but continue the discussion there. Thanks
