### ISSUE TITLE
<svg detection doesn't work from external TSX file

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/stencil#607]
**Stencil version:**

```
 @stencil/core@0.6.18
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
`<svg` JSX elements defined outside stencil component files are rendered as `HTMLElement`s.

**Expected behavior:**
The `<svg` JSX element is rendered as an `SVGElement` no matter where the JSX element is created.

**Steps to reproduce:**
Create a function that returns svg JSX:

`new-tab-icon.tsx`:
```ts
const NewTabIcon = () => (
  <svg class="new-tab" viewBox="0 0 43 42">
    <rect class="new-tab__box" y="8" width="34" height="34" rx="6"/>
    <path class="new-tab__arrow" d="M37.078 3.268H23.617V.243h18.626v18.625h-3.026V5.407L16.13 28.494l-2.14-2.139z"/>
  </svg>
);

export default NewTabIcon;
```

Import the function and use it in a Stencil component:

`my-component.tsx`:
```ts
render() {
  ...
    <NewTabIcon />
  ...
}
```

**Other information:**
SVG JSX element detection appears to be done by regex. If the comment `// <svg` exists in the stencil component file, it somehow works.

**Comment by hufan-akari** [comment]
https://github.com/ionic-team/stencil/blob/c855353b8fb7b202f3d6575766ef83d749a662f2/src/compiler/app/build-conditionals.ts#L98-L137

It seems that if the string `svg` exist, it will set coreBuild.svg to true, whether in comment or not.
