### ISSUE TITLE
Slot nodes don't update on attributes changed

### ISSUE THREAD

**Issue by 43081j** [ionic-team/stencil#611]
```
 @stencil/core@0.6.1
```

If you have a slot element and change an attribute on it (through a render call in some way), the VNode updates but the DOM node does not.

This'll affect us when shadow DOM is enabled, at least, but not too sure if its also a problem with it disabled.

This means we can't dynamically distribute children into slots, because we can't change a slot's `name`.

**Steps to reproduce:**

Produce an element like [this](https://gist.github.com/43081j/c622316d231323401c933c8c910e5316) and change the property.

---

It looks like it may be related to [this condition](https://github.com/ionic-team/stencil/blob/3640715ae913c0996872183fda1fbbd816d93b80/src/renderer/vdom/patch.ts#L315). This means a slot never has its attributes updated, it seems. Maybe someone knows why we skip slots there?

**Comment by adamdbradley** [comment]
`<slot>` is a very difficult element to act the same when polyfilled, and when native. Currently the polyfill is able to implement most of the slot spec, but it isn't possible for all scenarios, and I believe this is one of the scenarios. For now we'll have to work with this limitation. Thanks.
