### ISSUE TITLE
Static method or public exported function

### ISSUE THREAD

**Issue by marinho** [ionic-team/stencil#613]
**Stencil version:**
```
 @stencil/core@0.7.0
```

**I'm submitting a:**
[ ] bug report
[X] feature request
[ ] support request

**Current behavior:**

Components created with Stencil are lazy loaded when they are found in DOM by their respective Custom Element `tag`, as in example below:

```
<body>
  ...
  <my-beloved-service></my-beloved-service>
</body>
```

Although that would be the case for most of web components, it might bring issues such as:

- parent is `display: flex`
- CSS `:first-item`, `:last-item`, and similar selectors
- a11y / tabbing

In other cases, the component might be created and destroyed when called by methods, such as dialogs, message strips, etc. and they might have to be added to different parents.

That can be solved by something like this:

```
const myService = document.createElement('my-beloved-service');
document.body.appendChild(myService);
myService.doSomething();
```

But that's not exactly delightful to work with.

**Expected behavior:**

It would be awesome if one of the ways below is possible:

Option 1:

```
@Component({ tag: 'my-beloved-service' })
export class MyBelovedService {
    static doSomething() { ... }
    // or this?
    // @Static()
    // doSomething() { ... }
}
```

Option 2, provide a public class with static method:

```
@Component({ tag: 'my-beloved-service' })
export class MyBelovedService {
    doSomething() { ... }
}

export function myBelovedServiceDoSomething() {
    const service = document.createElement('my-beloved-service');
    document.body.appendChild(service);
    return service.doSomething()
      .then(result => {
        document.body.removeChild(service);
        return result;
      });
}
```

Right now, Option 2 could be done by adding additional files in asset containing such function, which is not an elegant solution and doesn't fit well to TypeScript typings.

I'm not sure if it's currently possible to declare and export a function which will be shiped in `dist`. All I have tried was exporting a function from the components folder and calling it from an external HTML, but it wasn't found.

Additionally, I believe lazy loading capability would probably break anything done between `document.body.appendChild(service)` and when the component files are actually resolved, which would require some `async / await` arrangement in there.

Maybe it's related to https://github.com/ionic-team/stencil/issues/510 ?

**Comment by kael** [comment]
Not answering directly to the request.

It seems you're looking to create a shared state/service. I've done something similar to your example, but there's the - undocumented ? - `@Prop({connect})` property that can be used to achieve that goal according to that [HowTo](https://medium.com/@gilfink/creating-shared-state-in-stencil-3beac77477e8) (haven't tested it yet).

**Comment by marinho** [comment]
@kael, shared state injection is definitely something I was looking for, but it’s not exactly what I mean in this issue.

Bear in mind that although I gave example named “service”, the same feature would apply to any component that we want to create and destroy on the fly.

But I think a shared service could help on it. Once I’m back on my computer I’m going to try it. I’m afraid the lazy loading behavior might still be an issue.

Thank you very much for the golden hint.

**Comment by marinho** [comment]
humm, after some trial, I concluded the `@Prop`'s `connect` option actually doesn't help with my feature proposal here.

@Prop's connect still expect components to be present in the DOM, so it can inject an existing instance of a service which is shared among all components which need it.

It's different than creating components on-the-fly without declaring them in the initial template.

**Comment by jgw96** [comment]
So just to make sure I'm following here, you are wanting some kind of API for creating components dynamically? Basically an API that wraps ``` const myService = document.createElement('my-beloved-service');
document.body.appendChild(myService);
myService.doSomething();``` correct?

**Comment by adamdbradley** [comment]
Thank you for the feedback, but in an effort to keep a minimal API I think we'll close this feature request at this time. If this is a common request we'll open it back up for discussion again. Thanks

**Comment by marinho** [comment]
@jgw96 that's an example, but we can summarise that currently there's no support for static methods, neither to export functions as part of Stencil building process. If that's provided, then we would be able to have the service example or any other similar case.

@adamdbradley fine by me. I'm still wondering what's Web Component's best approach for "components and functions that aren't part of the DOM". I understand that's not in Stencil's radar for the moment.
