### ISSUE TITLE
Typescript complains about the @Element() decorator

### ISSUE THREAD

**Issue by richrd** [ionic-team/stencil#615]
**Stencil version:**

```
 @stencil/core@0.6.18
```

**I'm submitting a:**

- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I'm trying to use the `@Element` decorator, but I'm getting a typescript error::
```
[ ERROR ]  typescript: src/components/map/map.tsx, line: 24
           Value of type '{ new (): Element; prototype: Element; }' is not callable. Did you mean to include 'new'?
     L24:    @Element() mapElement: HTMLElement;
```

**Expected behavior:**

Expected no TS errors, as I think I'm doing this as the docs state it should be done.

**Steps to reproduce:**

Write a component using the `@Element` decorator.

**Related code:**

```tsx
class Map {
  @Element() mapElement: HTMLElement;
  [...]
}
```

**Other information:**

I based my project on `stencil-component-starter`.
I was able to work around this by adding the following code to the top of my file (and the decorator does actually work with this):
```ts
declare const Element: any;
```
EDIT:
Btw, I also want to express my gratitude to all the devs for building this project. I've been using it for a few things and it really makes creating web components smooth. Thank you!

**Comment by jthoms1** [comment]
I am not sure that you need to define this decorator.  The `Element` decorator should be imported from `@stencil/core`

```ts
import { Component, Element } from '@stencil/core';
```

**Comment by richrd** [comment]
Yes, I did import it as you said, but without the declare typescript gives me the error I mentioned. When I add the declare the error goes away and everything works correctly.

**Comment by jthoms1** [comment]
Could you provide me with the full component source? Thanks

**Comment by richrd** [comment]
I tried to reproduce this with a fresh stencil-component-starter but couldn't. Turns out I was somehow missing the import or something. It does actually work as the documentation states. Sorry for the confusion.
