### ISSUE TITLE
Test fail when capacitor plugin is used

### ISSUE THREAD

**Issue by JStumpp** [ionic-team/stencil#617]
**Stencil & Capacitor version:**
```
@stencil/core@0.7.0-3
@capacitor/core@1.0.0-alpha.13
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When a stencil capacitor plugin is used the following exception is thrown:
```
 FAIL  src\components\app-root\app-root.spec.ts
  ● Test suite failed to run

    C:\dev\git\xs-web-forms\node_modules\@capacitor\core\dist\esm\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './core-plugin-definitions';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/components/app-root/app-root.tsx:46:14)
      at Object.<anonymous> (src/components/app-root/app-root.spec.ts:40:18)
```

**Related code:**
app-root.tsx
```tsx
import { Component } from '@stencil/core';
import { Plugins } from '@capacitor/core'
const { SplashScreen } = Plugins

@Component({
  tag: 'app-root',
  styleUrl: 'app-root.css'
})
export class AppRoot {
  componentDidLoad() {
    SplashScreen.hide();
  }

  render() {
    return (
      <div></div>
    );
  }
}
```

app-root.spec.ts
```tsx
import { render } from '@stencil/core/testing';
import { AppRoot } from './app-root';

describe('app-root', () => {
  it('should build', () => {
    expect(new AppRoot()).toBeTruthy();
  });

  describe('rendering', () => {
    beforeEach(async () => {
      await render({
        components: [AppRoot],
        html: '<app-root></app-root>'
      });
    });
  });
});
```
Maybe related to this: https://github.com/ionic-team/stencil/issues/520

**Comment by mlynch** [comment]
What version of node do you have?

**Comment by JStumpp** [comment]
Node version: v8.9.4

**Comment by mlynch** [comment]
Sounds like this is a lack of a jest preprocessor. @adamdbradley knows more

**Comment by JStumpp** [comment]
Yes, I tried to specify the transformIgnorePatterns of jest, but did not get it to work. @adamdbradley any idea?

**Comment by adamdbradley** [comment]
When using jest, the typescript code being tested first needs to get transpiled to commonjs formatted javascript. In the stencil package we've got a jest preprocessor you can use. Here's an example of how Ionic uses it: https://github.com/ionic-team/ionic/blob/master/core/package.json#L90

**Comment by JStumpp** [comment]
Thanks, that is exactly what I use. Still get this error with the capacitor package.

**Comment by humblebountyhunter** [comment]
I am having the same issue. I created a fork of the stencil-app-starter: https://github.com/humblebountyhunter/stencil-app-starter/commit/abb7d8d79104a4b447e0da717d49b0f72543c956

Just added the capacitor dependency and the following error occurred: 
```
FAIL  src\components\my-app\my-app.spec.ts
  ● Test suite failed to run

    C:\dev\git\stencil-app-starter-\node_modules\@capacitor\core\dist\esm\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './core-plugin-definitions';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/components/my-app/my-app.tsx:10:14)
      at Object.<anonymous> (src/components/my-app/my-app.spec.ts:40:16)
```

@adamdbradley the jest preprocessor is also in the project: https://github.com/humblebountyhunter/stencil-app-starter/blob/abb7d8d79104a4b447e0da717d49b0f72543c956/package.json#L38

**Comment by JStumpp** [comment]
This is also fixed with 0.13.0. Thanks!

**Comment by ptitjes** [comment]
@JStumpp Hi. I stumbled upon the same error trying Jest on my Ionic/Capacitor/Angular app. I tried to add the said transformer without luck.

```json
{
  "jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts",
    "transformIgnorePatterns": [
      "node_modules/(?!(@capacitor)/)"
    ],
    "transform": {
      "^.+\\.(js|ts|tsx)$": "<rootDir>/node_modules/@stencil/core/testing/jest.preprocessor.js"
    }
  }
}
```

You said it is fixed in `@stencil/core@0.13.0`. Could you provide me more information please?

Thank you very much in advance for your help!

**Comment by Geroo** [comment]
You are right, this still might not work. It worked in my case, because I migrated the UI tests to the puppeteer Tests and I am not using Jest Unit test any more. Should be reopened if it is still an issue.

**Comment by adamdbradley** [comment]
Outdated
