### ISSUE TITLE
Tries to import from unavailable chunk

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#618]
**Stencil version:**
```
    "@stencil/core": "^0.7.0-3",
    "@stencil/redux": "0.0.4",
    "@stencil/router": "0.0.27",
    "redux": "3.7.2",
    "redux-thunk": "2.2.0"
```

**I'm submitting a:**

[ x ] bug report

**Current behavior:**
There's a reference to a non existing chunk file in the component file which causes `is not defined` errors when (lazy) loading the component:

<img width="1672" alt="bildschirmfoto 2018-03-13 um 17 51 20" src="https://user-images.githubusercontent.com/6666636/37357025-a5178c5a-26e7-11e8-9fed-18484c53c462.png">

The error:
```javascript
app-header.js:73 ReferenceError: EventEmitter is not defined
    at co-data-service-table.js:2606
    at createCommonjsModule (build/app/chunk9.js:1018)
    at co-data-service-table.js:2605 "http://localhost:3333/build/app/co-data-service-table.js"
then.catch.err @ build/app/app.core.js:2013
Promise.catch (async)
loadBundle @ build/app/app.core.js:2013
plt.queue.add @ build/app/app.core.js:1700
doHighPriority @ build/app/app.core.js:1407
Promise.then (async)
add @ build/app/app.core.js:1448
connectedCallback @ build/app/app.core.js:1695
HostElementConstructor.connectedCallback @ build/app/app.core.js:1795
$insertBefore @ build/app/app.core.js:315
updateChildren @ build/app/app.core.js:1228
patchVNode @ build/app/app.core.js:1269
patch @ build/app/app.core.js:1317
render @ build/app/app.core.js:732
renderUpdate @ build/app/app.core.js:816
update @ build/app/app.core.js:810
plt.queue.add @ build/app/app.core.js:760
doWork @ build/app/app.core.js:1416
requestAnimationFrame (async)
add @ build/app/app.core.js:1457
queueUpdate @ build/app/app.core.js:758
setValue @ build/app/app.core.js:942
setComponentProp @ build/app/app.core.js:845
unsubscribe.activeRouter.subscribe @ build/app/app-load.js:892
dispatch @ build/app/app.core.js:37
set @ build/app/app.core.js:22
history.listen @ build/app/app-load.js:880
listener @ build/app/app-load.js:347
listeners.forEach.listener @ build/app/app-load.js:357
notifyListeners @ build/app/app-load.js:357
setState @ build/app/app-load.js:444
transitionManager.confirmTransitionTo @ build/app/app-load.js:520
confirmTransitionTo @ build/app/app-load.js:339
push @ build/app/app-load.js:504
(anonymous) @ build/app/app-main.js:2361
(anonymous) @ build/app/app-main.js:50
(anonymous) @ build/app/app-main.js:1706
dispatch
(anonymous) @ build/app/chunk5.js:31
(anonymous) @ build/app/chunk5.js:9
__awaiter @ build/app/chunk5.js:5
(anonymous) @ build/app/chunk5.js:30
args @ build/app/app.core.js:126
elementClickHandler @ app-header.js:73
ev @ build/app/app.core.js:1488
```

It started to occur when I imported the same module the **second** time in another component. As long as I only use the module in **one** component all is working fine.

**Expected behavior:**
A "shared" module can be used in multiple components without errors.

**Steps to reproduce:**
That's the thing. The setup of the project is quite overwhelming (including backend dependency without which the code will not work). I would agree to grant access to the private repo though as I'm very much interested in
a) solving this for me and
b) stick with (super-duper) Stencil and
c) it is related to a very profilic npm module (FeathersJS)

**Comment by jgw96** [comment]
@bitflower So the repro case here is to import a module into two separate components correct?

**Comment by bitflower** [comment]
Hey, exactly, but maybe it depends on the imported module (in this case Feathers). But as a start it would be the same mod imported into 2 components, yes. Sorry didn't prepare this. Will you? Lemme know if we should chat on Slack...

**Comment by bitflower** [comment]
As you can see in the pic Stencil is trying to import from chunk9 which is obviously not loaded on the left side (?)

**Comment by bitflower** [comment]
I have prepared a private repo showcasing the issue. Who should I add as collaborator? You, @jgw96 or someone else?

**Comment by bitflower** [comment]
This seems to work in 0.7.2! Is this on purpose or random? Thanks for your continuous updates!

**Comment by jthoms1** [comment]
Great!  We recently updated the version of Rollup so most likely it was fixed.
