### ISSUE TITLE
bug(prerender): triggers css animations twice

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/stencil#619]
**Stencil version:**
```
@stencil/core@0.6.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
If an element has a css entry effect, it happens twice. once on prerender, second time on actual render

**Expected behavior:**
animation should happen once

**Steps to reproduce:**
just have an element with entry animation, build with prerender

**Comment by jthoms1** [comment]
Could you provide the code from your component where the animation resides? An example repo would be helpful as well. Thanks!

**Comment by adamdbradley** [comment]
Closing without a demo.

**Comment by AmitMY** [comment]
Could not reproduce on latest version of stencil & ionic.
