### ISSUE TITLE
bug(build): build should bundle stuff

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/stencil#620]
**Stencil version:**

```
 @stencil/core@0.6.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
build creates many many files, for a 1 page website without a router
![image](https://user-images.githubusercontent.com/5757359/37371094-f1679274-2716-11e8-954d-2f1cc45d631b.png)

**Expected behavior:**
should be just 1 js file and 1 css file, because it's just a one-page website.

**Steps to reproduce:**
Remove the router, just use `<app-home>`, and build

**Comment by adamdbradley** [comment]
Sorry but many of these files are external assets from other different locations, not just your app. Additionally, stencil isn't built to make one large file, there are many other options for that. We have optimizations to make yet, but I think this is more of a documentation issue. Thanks

**Comment by AmitMY** [comment]
I agree it is not built to make one big file, because most use cases benefit from many files for each thing lazy loaded.
However, for example here, there are 6 icon files all loaded, 2 css files, and 7 js files (not including icons), for kind of the simplest app there is, for 1 page. shouldn't stencil optimize for this use case as well?
