### ISSUE TITLE
Events emitted by elements such as `ionChange` should work with an `on` prefix

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil#622]
**Stencil version:**

```
 @stencil/core@latest
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

`<ion-toggle onIonChange={() => this.doStuff()}></ion-toggle>` does not work and throws a type error ```[ts] Property 'onIonChange' does not exist on type 'IonToggleAttributes'. ``` 
**Expected behavior:**

Something like `<ion-toggle onIonChange={() => this.doStuff()}></ion-toggle>` would work

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
Done and done: https://github.com/ionic-team/stencil/commit/527f2acb47791c8378a57d1afcaf4a837ed357e2
