### ISSUE TITLE
starter component does not re-render on property change in IE11

### ISSUE THREAD

**Issue by neonguru** [ionic-team/stencil#623]
**Stencil version:**

```
 @stencil/core@0.6.18
```

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Run a client of simple my-component starter in IE11 and it does not update (render) when a property is changed.

**Expected behavior:**

IE11 should behave the same as other browsers and re-render when a property is changed.

**Steps to reproduce:**

Create a starter component:
git clone https://github.com/ionic-team/stencil-component-starter.git my-component
cd my-component
git remote rm origin
npm install
npm build

cd ..
md my-client
cd my-client
npm link ../my-component

add index.html with the following content:

    <!DOCTYPE html>
    <html dir="ltr" lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
      <link rel="icon" href="data:,">
      <title>my-component client</title>
      <script src="node_modules/my-component/dist/my-component.js"></script>
    </head>
    <body>

      <my-component first="one" last="two"></my-component>
      <div style="margin:20px">
        <button onClick="setFirst()">first to three</button>&nbsp;
      </div>

      <script>
        function setFirst() {
          var h = document.querySelector('my-component');
          h.setAttribute('first', 'three');
        }
      </script>
    </body>

    </html>

The page renders correctly on load.
But clicking the button to change the attribute does not cause a re-render.
Notice that the setFirst method changes the first attribute value to "three"
This causes a re-render on most browsers but fails in IE11.
I confirmed the first attribute did change in the dom.

I ran this with the following command:

`http-server -p 3000`

and viewed it at:

`http://localhost:3000/`

**Comment by julesjanssen** [comment]
Probably the same as #588.
Attribute updates also fail to re-render in Firefox.

**Comment by jthoms1** [comment]
I have just verified that this does work in Chrome, but not in Firefox.  It appears that there is an issue with the es5 version of the build not correctly implementing change on setAttribute.  This does work however when you treat it as a prop. 

```h.first = 'three';```

**Comment by neonguru** [comment]
Thank you - yes that works.

But it won't work for boolean Props:
===

Change `first` Prop type to boolean

Change render text to:

`Hello, World! I'm {this.first ? 'true' : 'false'} {this.last}`

default `first` to "true", then try to change with:

`h.first = 'false'`

Does not work even in Chrome.

setAttribute DOES work in Chrome, but not in IE11.

**Comment by saltdotac** [comment]
Seeing the same boolean issue in Safari, IE 11, and Chrome
