### ISSUE TITLE
Sourcemap is not working correctly

### ISSUE THREAD

**Issue by tungd** [ionic-team/stencil#628]
**Stencil version:**

```
 @stencil/core@0.6.18
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Location in sourcemap is totally off, for example the following `console.log` statement was declared in `page-home.tsx`, but sourcemap showing it's from `float-label-input.js`. FYI I also have an element called `float-label-input`

<img width="997" alt="screen shot 2018-03-16 at 3 40 39 pm" src="https://user-images.githubusercontent.com/88299/37511335-091fb2ea-2931-11e8-867c-2b187a28d18b.png">

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by jthoms1** [comment]
We are even shipping sourcemaps.  Can I assume that the code you are running is currently in prod build not dev?

**Comment by bfmatei** [comment]
It is actually correct.

Stencil does not provide support for true source-mapping at the moment. What you see in the console is the location of the `console.log()` in the bundled file which:
- has a friendly filename due to using dev builds
- can contain multiple components

**Comment by tungd** [comment]
Oh I see, clicking the line number does send me to the correct source code line, just in a different file. The two components are combined into one file (I guess because of inlining) and Stencil picks the filename of the first. Honestly I still think this behavior might confuse developer but I'm okay with it. Will close the issue for now. Thanks :)

**Comment by splitinfinities** [comment]
Heads up everyone, Stencil supports sourcemaps as of v2.9.0! https://stenciljs.com/docs/config#sourcemap
