### ISSUE TITLE
Prevent Browser from auto-opening

### ISSUE THREAD

**Issue by AnthoniG** [ionic-team/stencil#658]
When you run `npm run dev` it auto opens your system registered browser and goes to the URL. My system browser is Pale Moon (which is a branch off of Firefox) and it doesn't support ES Modules.

Hence I do all my development using Chrome and then build production and test in other browsers.

**Is there a way to stop this from auto-opening the browser by default?**
_Also, can you have it display what port it's running on in the console please ?_ 

`create-react-app` tells you the port and gives you a sample address. It also supports adding a `.env` file into the root project and if you put `BROWSER=None` in there it stops the browser from opening.

Other than that I am really liking the system. Just testing out. I have some new projects to develop and looking around to see what to develop them in ;)

**Comment by adamdbradley** [comment]
Sorry we haven't fully documented all of this yet, but you can do `npm run dev --no-open`.

Additionally, in `0.8.0` we'll improve the integration of the dev server with the build, so many of these features will be fixed (and better documented).

Thanks
