### ISSUE TITLE
Would like to be able to configure which polyfills are included at build-time

### ISSUE THREAD

**Issue by thomasqbrady** [ionic-team/stencil#660]
**Stencil version:**
All

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
All polyfills are included at compile-time, and only the necessary ones are loaded at run-time (super cool!)

**Expected behavior:**
(More like “hoped-for behavior”) I’d like to be able to prevent certain polyfills from being available (for reasons like performance, security issues), and maybe would like to specify which polyfills I prefer when there are options.

**Other information:**
Mike Hartington told me to submit this at JazzCon 2018.

**Comment by adamdbradley** [comment]
Which polyfills would you not want added?

**Comment by thomasqbrady** [comment]
I’m answering on behalf of our users, to be honest. We build a component library that gets used in shipping products, and those users often want to choose.

They bring up performance as an issue, often, but I’m not convinced by that (meaning I’ve never seen/heard an actual instance of a slow polyfill being used when a faster one was available).

The more compelling case is security, simply because our users’ users are banks, who are very opinionated about what 3rd party packages/scripts can/can’t be included.

**Comment by adamdbradley** [comment]
These are the polyfills that come out of the box: https://github.com/ionic-team/stencil#polyfills

They're all well document, heavily test, widely used and have MIT licensing.

My fear of letting this become customizable is that we'd expose an area that would cause more issues for users and developers that would be very hard to debug and replicate. There's a very specific order and if it's modified it may not work on certain browsers, for certain reasons. 

Additionally, if the solution needs to work on as many browsers as possible, the default setup is the one they'll need. If this becomes a bigger issue we can reopen this. Thanks.
