### ISSUE TITLE
Imports of Common JS - failing in unit tests or in app code

### ISSUE THREAD

**Issue by bassettsj** [ionic-team/stencil#661]
**Stencil version:**

```
@stencil/core@0.7.6
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Imports from common js code in tests and compiled stencil code break.

**Expected behavior:**

One of the forms of the imports to work consistently in both.

**Steps to reproduce:**

[Demo repository](https://github.com/bassettsj/bug-example-inconsistent-imports-stencil)

1. clone the repository
2. `npm i`
3. `npm t` should pass
4. `npm dev` see failing in the web component
5. change the import type in `my-component.tsx`
6. and rerun `npm t` see failing
7.  npm dev see passing

**Other information:**

**Comment by jthoms1** [comment]
Commit 8520059d fixes this issue.  Using this fix in the demo repo allowed tests and build to both execute successfully.
