### ISSUE TITLE
Custom Event on Element Without Listener Decorater not Working

### ISSUE THREAD

**Issue by tkiddleYoobic** [ionic-team/stencil#662]
**Stencil version:**

```
 @stencil/core@0.7.6
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
In v0.7.6 this feature was added:

As of 0.7.6, Listeners can be added to specific elements within JSX.

For example, if a component emits the event `ionChange`, then the JSX attribute `onIonChange` can be added, such as:
```
<ion-input onIonChange={ev => this.someMethod(ev)}/> 
```

This method does not work, the event never gets trigged.

**Expected behavior:**
The new method in 0.7.6 would trigger an event.

**Steps to reproduce:**
Here is repo which reproduces the bug:
https://github.com/tkiddleYoobic/stencil-event-bug
The steps to build the repo and reproduce are in the readme

**Comment by jthoms1** [comment]
This is most likely an issue with using an older version of `@ionic/core`.  This behavior should work for all new stencil components generated.  We will be releasing a new version of `@ionic/core` today that should solve this issue.

I will keep this open until we do so. Thanks!
