### ISSUE TITLE
SVG elements don't add/remove classes when running npm run build

### ISSUE THREAD

**Issue by corysmc** [ionic-team/stencil#665]
**Stencil version:**
```
 @stencil/core@0.7.7
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Classes can be added and removed dynamically via `@State()` on any SVG sub element (circle, text, etc) when running in dev mode: `npm start` 
However, when running `npm run build`, the classes are no longer be added. Silently fails.

The workaround is to add the conditional classes to the parent SVG element rather than it's sub elements.

**Expected behavior:**
Classes can be added and removed when building for prod just as in the dev environment

**Steps to reproduce:**
1. Add conditional classes to sub elements of an svg.
2. `npm run build`
3. observe: classes aren't added/removed

**Related code:**

The following does not work when running `npm run build`:
```tsx
<svg viewBox="0 0 60 60">
  <circle 
    class={{
      'adding-reset': this.addingResetClass,
      'reset-added': this.resetClassAdded
    }}
    fill="none"
    cx={this.radius + this.strokeWidth / 2}
    cy={this.radius + this.strokeWidth / 2}
    r={this.radius}
    stroke={this.background}
    stroke-width={this.strokeWidth}
  />
</svg>
```
**Other information:**
Here's the workaround (place classes on parent SVG):
```tsx
<svg
  viewBox="0 0 60 60"
  class={{
    'adding-reset': this.addingResetClass,
    'reset-added': this.resetClassAdded
  }}
> 
... 
</svg>
```

**Comment by adamdbradley** [comment]
I'm not able to replicate this, would you be able to put together a test repo? Thanks

**Comment by adamdbradley** [comment]
Fixed as of https://github.com/ionic-team/stencil/commit/260b5388758b8f3ec1e490cfe8de01485ba9aafc thanks!
