### ISSUE TITLE
onClick - Not passing input parameters in the correct order

### ISSUE THREAD

**Issue by tonyawad88** [ionic-team/stencil#667]
**Stencil version:**

```
@stencil/core@0.6.1
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Currently I have an ion-card with an onClick event bound to it, and passing in the parameters this as parameter 1 and hero as parameter 2, as shown in the code section below.

The console.log inside the function is printing event(parm1) as the hero object(parm2) and vice versa.
![image](https://user-images.githubusercontent.com/3638322/37870307-a5cd3746-2fa0-11e8-991c-007c43e12fb8.png)

**Expected behavior:**
The proper parameter order that is passed in the onClick should be reflected in the function. 

**Related code:**
```
  heroSelected(event:UIEvent, hero:Hero) {
    console.log('event is:',event);
    console.log('hero is:', hero);
  }
...
{this.heroesModel.heroes.map((hero) =>
                <stencil-route-link url="/profile/1">
                  <ion-card class="thumbnail-card" onClick={this.heroSelected.bind(this,hero)}>
                    <div class="thumbnail-img">
                      <lazy-img src={hero.thumbnailPicUrl}></lazy-img>
                    </div>
                    <ion-card-content>
                      <ion-card-title>{hero.name}</ion-card-title>
                    </ion-card-content>
                  </ion-card>
                </stencil-route-link>
              )}
...
```

**Comment by manucorporat** [comment]
This is a not a bug nor a stencil issue, it's the expected behaviour of Function.prototype.bind

>Any additional parameters you later pass to the bound function will be passed in after the bound parameters.

https://stackoverflow.com/questions/2236747/use-of-the-javascript-bind-method

**Comment by tonyawad88** [comment]
@manucorporat thank you! sorry for this.
