### ISSUE TITLE
bug(environment): something about the environment makes firebase think this is not a web server

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/stencil#669]
**Stencil version:**
```
0.76
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
See: https://github.com/firebase/firebase-js-sdk/issues/558

On the stencil environment, doing:
```
import firebase from 'firebase';

firebase.initializeApp({ ... config ... });
firebase.auth().signInWithPopup(new firebase.auth.GoogleAuthProvider());
```

causes:

> code: "auth/operation-not-supported-in-this-environment"
> message: "This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled."

The environment is HTTP, on localhost, and `Storage` is defined.

**Expected behavior:**
Firebase should work here, stencil server should be a normal HTTP environment.

**Steps to reproduce:**
See: https://github.com/AmitMY/firebase-stencil-issue
The last commit (firebase issue) is the code I added to the starter.

**Comment by jgw96** [comment]
Hey! Does the same thing happen if you run `npm run build` and then just serve the www folder using python simple server or some other http server?

**Comment by AmitMY** [comment]
```
git clone https://github.com/AmitMY/firebase-stencil-issue.git
cd firebase-stencil-issue/
npm i
npm run build
cd www
http-server .
```

![image](https://user-images.githubusercontent.com/5757359/37898613-f6a6bf64-30f1-11e8-81c5-8c3e8f7207e2.png)

**Comment by jgw96** [comment]
hmmm does this only happen with this app, or any app you have that's using firebase and built with Stencil?

**Comment by AmitMY** [comment]
Any app using firebase built with stencil.
That repo is just a reproduction, look at the only commit by me there, nothing done but adding firebase

**Comment by cdock1029** [comment]
I think you're supposed to use the modular packages now.

This works fine for me:

```javascript
import { firebase } from '@firebase/app';
import '@firebase/database';
import '@firebase/auth';
```

**Comment by AmitMY** [comment]
I'll give it a shot and keep this thread posted this weekend. Thanks @cdock1029

**Comment by cdock1029** [comment]
Never mind this does **not** work now, since the compiler was updated in `0.7.7`.

Getting errors: 

```
[ ERROR ]  TypeError: Cannot read property 'kind' of undefined at Object.isImportClause
           (/Users/cdock/dev/wpm/web2/node_modules/typescript/lib/typescript.js:12964:21) at
           sourceFileObj.statements.find.st
           (/Users/cdock/dev/wpm/web2/node_modules/@stencil/core/dist/compiler/index.js:5349:16) at Array.find
           (native) at getTypeReferenceLocation
           (/Users/cdock/dev/wpm/web2/node_modules/@stencil/core/dist/compiler/index.js:5347:60) at
           getAllTypeReferences.reduce
           (/Users/cdock/dev/wpm/web2/node_modules/@stencil/core/dist/compiler/index.js:5311:29) at Array.reduce
           (<anonymous>) at getAttributeTypeInfo
           (/Users/cdock/dev/wpm/web2/node_modules/@stencil/core/dist/compiler/index.js:5310:10) at
           classNode.members.filter.reduce
           (/Users/cdock/dev/wpm/web2/node_modules/@stencil/core/dist/compiler/index.js:5694:33) at Array.reduce
           (<anonymous>) at getMethodDecoratorMeta
           (/Users/cdock/dev/wpm/web2/node_modules/@stencil/core/dist/compiler/index.js:5681:10)
```

It's having a problem with these imports:
```javascript
import '@firebase/auth'; 
import '@firebase/database'; 
```

`0.7.6` does not have this issue.
Something changed in this file I believe is causing this:

[src/compiler/transpile/datacollection/utils.ts](https://github.com/ionic-team/stencil/commit/ef304ea5f932b062505bc27a1874db54f2c7d758#diff-1e0f710a3b95e93ebb5016b269a99782)

**Comment by jthoms1** [comment]
I verified using the repo provided by @AmitMY that the issue does not occur with `@stencil/core@0.7.12`

**Comment by AmitMY** [comment]
@jthoms1 Verified 0.7.12 on that repo not working.

Same repo, just bumped dependencies:
```
├── @ionic/core@0.2.0
├── @stencil/core@0.7.12
├── @stencil/dev-server@0.0.18
├── @stencil/router@0.0.28
├── @stencil/sass@0.0.3
├── @stencil/utils@0.0.4
├── @types/jest@21.1.10
├── firebase@4.12.1
└── jest@21.2.1
```

**Comment by jthoms1** [comment]
@AmitMY I used the imports that @cdock1029 outlined.

```
import { firebase } from '@firebase/app';

import '@firebase/auth'; 
```

**Comment by AmitMY** [comment]
@jthoms1 @cdock1029 This works! Thank you so much.

**Comment by juanframart2011** [comment]
hi @AmitMY  sorry you could share the file or the part of how you configured it, since I have the same error and I could not solve it.

**Comment by AmitMY** [comment]
@juanframart2011 Not sure what you are asking. I used the different imports as stated above, and configured firebase using the config supplied in firebase online

**Comment by SouradeepMisra** [comment]
I also faced this issue. I faced this issue because of plugin version. try to update your 'webview' plugin version. It is work for me.
