### ISSUE TITLE
Cannot Run Dev Server for Reusable Component Starter Without Edit to stencil.config.js

### ISSUE THREAD

**Issue by danielleletarte** [ionic-team/stencil#673]
**Stencil version:**
```
 @stencil/core@0.7.6
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
After cloning the Reusable Components Starter (https://github.com/ionic-team/stencil-component-starter my-component), the 'start' script returns a 404 with the following JSON

```json
{
  "error": {
    "errno": -2,
    "code": "ENOENT",
    "syscall": "stat",
    "path": ".../my-component/www"
  }
}
```

**Expected behavior:**
'start' script should create the www directory and load the template component.

**Steps to reproduce:**
- Clone the Reusable Component Starter (https://github.com/ionic-team/stencil-component-starter my-component)
- Run 'npm start'

**Related code:**
Updating the stencil.config.js file to the following appears to resolve the issue.

```tsx
exports.config = {
  namespace: 'mycomponent',
  outputTargets:[{type: 'dist'}],
  generateWWW: true
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us! I just fixed this a minute ago https://github.com/ionic-team/stencil-component-starter/commit/eb7989206ddc1ffed01db6c48a850591a5871ab1. Thanks for using Stencil!
