### ISSUE TITLE
bug(testing): element creation doesn't error, but is nulll

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/stencil#674]
**Stencil version:**

```
@stencil/core@0.7.8
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Running for example:
![image](https://user-images.githubusercontent.com/5757359/37963959-93c35ea2-31c8-11e8-9ea3-cc682fd9191f.png)

Does not error on the actual element creation, but the value of `element` is `null` so everything doesn't work.

**Expected behavior:**
Either `element` to not be null, or error

**Steps to reproduce:**
Code is above

**Related code:**
```ts
import { render, flush } from '@stencil/core/testing';
import { PatternInput } from './pattern-input';

describe('pattern-input', () => {
  it('should build', () => {
    expect(new PatternInput()).toBeTruthy();
  });


  describe('rendering', () => {
    let element;

    beforeEach(async () => {
      element = await render({
        components: [PatternInput],
        html: '<pattern-input></pattern-input>'
      });
      console.log(element)
    });

    it("should render display mask in span", async () => {
      element.displayMask = 'abc';
      await flush(element);
      expect(element.querySelector('span')).toEqual(element.displayMask);
    });
  });
});
```

**Other information:**

**Comment by jgw96** [comment]
Hmm, I'm wondering if it cant find that custom component. Does this happen just with this component or any component?

**Comment by AmitMY** [comment]
Didn't try any component, just this one. If it couldn't find it, why no error on render?

**Comment by jgw96** [comment]
True. Hmm alright , let me get this to someone on the team who knows more about our unit testing system.

**Comment by adamdbradley** [comment]
This has been replaced with the `newSpecPage` api: https://stenciljs.com/docs/unit-testing
