### ISSUE TITLE
Exclude __mocks__ when building a collection

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#677]
**Stencil version:**

```
 @stencil/core@0.7.8
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
All files under the source folder are being generated into the output targets. 

**Expected behavior:**
Enable exclusion to exclude some files. specifically - this is required for excluding __mocks__ used in testing. Alternatively - you can ignore all files under all __mocks__ directories. 

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
The `excludeSrc` config has since been added.

```
  /**
   * The excludeSrc config setting specifies a set of regular expressions that should be excluded
   * from the build process.
   *
   * The defaults are meant to exclude possible test files that you would not want to include in your final build.
   */
```
