### ISSUE TITLE
Build stencil components into a single bundle js.

### ISSUE THREAD

**Issue by fangyuanziti** [ionic-team/stencil#683]
**I'm submitting a:**
[x] feature request

Can we add a config to build our stencil components into a bundle js instead of lazy loading multiple file.
That will be helpful when distribute our js library to other people who don't use stencil.

**Comment by jgw96** [comment]
Hey @fangyuanziti , our lazy loading works even outside of Stencil. For example, in Ionic/Angular v4 all of the ionic components will be lazy loaded since we built them with Stencil even though people will be using Angular in those projects instead of Stencil. Are you running into an issue with lazy loading?

**Comment by fangyuanziti** [comment]
@jgw96 Actually, I didn't have any problem when using lazy loading personly. 

I have a plan to implement a reusable components collection in stencil to helper other people to build their own web UI. I think the users of this collection library should multiple choices to intergrate it into their own code: using lazy loading or  a bundle js. So I want to distribute both lazy loading build and bundle build to them.

**Comment by jgw96** [comment]
Ahh got ya. So we don't currently allow bundling into one big file as this can really hurt loading performance, especially on slower mobile networks and lower end devices. Because of this, at this time we do not have any plans to allow bundling into one big file. Thanks for using Stencil!

**Comment by davidenke** [comment]
@jgw96 Since your arguments are completely valid, it should be up to the developers using the "framework". In my case I just want one single bundle file which is not lazy loading anything.

**Comment by ChristianUlbrich** [comment]
@jgw96 We do not use StencilJS for end consumers apps but for internal "big" enterprise apps. We want to have full control. Basically speaking, it should be up to us (developers! developers! developers! developers! developers! developers! developers! developers! developers!) whether lazy-loading is used or not. Composing your app of let's say 10+ components won't get you anywhere on a sketchy mobile network even with lazy-loading.

**Comment by DanielNetzer** [comment]
Any news regarding the simple ability to produce a proper single javascript file?

**Comment by obedm503** [comment]
would it be possible to implement this as a plugin? is there plugin api documentation somewhere?

**Comment by davidenke** [comment]
> would it be possible to implement this as a plugin? is there plugin api documentation somewhere?

Basically this is [rollup](https://rollupjs.org) and you can add plugins as you want. But after rollup has been run some magic inside stencil does the rest. And there's no way to hook into that.

**Comment by martinlombana** [comment]
Is this still not working or there is no solution for this?

I can not understand what is the advantage of 3000 js files and 3000 requests, including one request per svg in the ionicons... 

Everytime I need to deploy, specially in testing phase, it takes 1 minute to upload an ionic 4 project. Contrary to 10 seconds in ionic 4...

**Comment by chiqui3d** [comment]
I just created a demo with several ionic components, and it has generated 389 files, lol, this is unsmokable.

Is there a solution to this?

**Comment by zhaoyao91** [comment]
is there any update?

**Comment by claviska** [comment]
This is possible through the [dist-custom-elements-bundle](https://stenciljs.com/docs/custom-elements) output target.

**Comment by zhaoyao91** [comment]
> This is possible through the [dist-custom-elements-bundle](https://stenciljs.com/docs/custom-elements) output target.

@claviska thanks for you advise. 

I am currently using another rollup process to consume the output of dist-custom-elements-bundle because we want to make an iife module and wrap some logic outside the custom-elements bundle, since I didn't find a way to config the underlining rollup of stencil.

This works, but the experience is not integrated.

**Comment by phanithinks** [comment]
@zhaoyao91  can you guide us how to solve this issue using rollup ? we got stuck with the same issue.

**Comment by fermionboson101** [comment]
> > This is possible through the [dist-custom-elements-bundle](https://stenciljs.com/docs/custom-elements) output target.
> 
> @claviska thanks for you advise.
> 
> I am currently using another rollup process to consume the output of dist-custom-elements-bundle because we want to make an iife module and wrap some logic outside the custom-elements bundle, since I didn't find a way to config the underlining rollup of stencil.
> 
> This works, but the experience is not integrated.

can you please, explain how you're doing it?

**Comment by fermionboson101** [comment]
@zhaoyao91 please tell us how you did it
