### ISSUE TITLE
Documentation generator re-creates component folders when components are deleted

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#685]
**Stencil version:**
```
 @stencil/core@0.7.11
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
When you delete a component, the documentation generator re-creates the folder and readme file.

**Steps to reproduce:**

If the app contains a component, `my-component`.

- Run `nom start` to run the app.
- Delete the `my-component` folder.
- Watcher re-builds the app.
- The component folder is created by the compiler and contains the generated `readme.md` file.  the tsx file remains deleted.

A current work around is to stop the watcher first, delete the component folder, and then start again.

**Comment by adamdbradley** [comment]
Should be fixed now as of https://github.com/ionic-team/stencil/commit/0aad8e70cbdf8543a5ee87fc484f05b6f8920cf1 thanks
