### ISSUE TITLE
npm link not supported

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#686]
**Stencil version:**
0.7.12

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

**DETAILED DESCRIPTION in [demo repo](https://github.com/bitflower/stencil-npm-link)!**

[From Slack](https://stencil-worldwide.slack.com/archives/C789G3X1R/p1522743349000072): Does the stencil bundler check the `package.json`for a list of dependencies? I’m using `npm link` without a dep entry in `package.json`and have problems with `npm run dev`. I have the feeling that the source file is not found… 

I have this simple export in node_modules/@my-company/my-module/index.js (sym-linked via npm link):
```javascript
exports.Constants = {
    test: 'bla'
};
``` 

and get this error (see the path? it is not correct…):

```terminal
[ WARN  ]  'Constants' is not exported by '../my-module/index.js'
```

**Expected behavior:**
I can use `npm link` for development instead of `npm install`

**Steps to reproduce:**
See [demo repo](https://github.com/bitflower/stencil-npm-link)

**Comment by jthoms1** [comment]
What is the reason that the following line is commented out?  https://github.com/bitflower/stencil-npm-link/blob/master/stencil-app/src/components/my-component/my-component.tsx#L3

**Comment by jthoms1** [comment]
@bitflower As of Typescript 2.7 this changed with the `esModuleInterop` flag. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html

**Comment by bitflower** [comment]
Will check this next week...
