### ISSUE TITLE
Bundling `mongoose` fails

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#688]
```
 @stencil/core@0.7.12
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Repo creating the error and detailed description:**

Hey there, sorry to find another one ! Let me know if I can provide anything else!

[REPO](https://github.com/bitflower/stencil-mongoose-issue)

**Comment by jthoms1** [comment]
PR #760 should resolve this issue. Please update your config to the following. Note that the only change was adding `nodeResolve` with `browser` as `true`.

This is per the documentation provided by `rollup-plugin-node-resolve`. https://github.com/rollup/rollup-plugin-node-resolve#usage

exports.config = {
  nodeResolve: {
    browser: true
  }
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
};
