### ISSUE TITLE
Combine Properties and Attributes sections in readme.md

### ISSUE THREAD

**Issue by finneganh** [ionic-team/stencil#689]
**Stencil version:**

```
 @stencil/core@0.7.12
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

In the auto-generated readme.md files, there are separate sections for Properties and Attributes with duplicated JSDoc contents in each one.

**Expected behavior:**

Properties and Attributes would be combined, documenting both the camelCase property name and the kebab-case attribute name.

This would reduce all of the duplicated descriptions in the output.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
Yeah makes sense. Looking for some ideas on how to best format this.
