### ISSUE TITLE
Not able to use external libraries in components with chrome in production mode

### ISSUE THREAD

**Issue by albertvazquezm** [ionic-team/stencil#691]
**Stencil version:**
```
 @stencil/core@0.7.12
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When building the application for production: i.e `npm run build` and importing the bundle in chrome, the components aren't able to use classnames package, already imported. Works fine in firefox nightly (v61). When building the application using --dev param, it works fine in chrome but not in firefox (This Stencil app is disabled for this browser.)

**Expected behavior:**
The application loads the classnames (or any other) library in chrome using production build.

**Steps to reproduce:**
Just clone stencil component starter project repo https://github.com/ionic-team/stencil-component-starter, create a component that uses classnames (for example) and generate the bundle using npm run build. this library won't work in chrome for the generated components.

When exploring the code for both the development build (the one that works) and the production one, I see that classnames keyword just appears once in the production build `window.classNames=n` (in chunk1.js)while in the development build, in the same chunk1.js file, it appears up to 11 times, including the definition of the variable here: `var classnames = createCommonjsModule(function (module) {`

Is there any extra step for including external libraries in the web components? Why the same code works for FF and not in chrome for this prod build?

I'm attaching the screenshots for the prod and non-prod builds, to show that classnames library is not appearing in the production one.

**Production**
![captura de pantalla 2018-04-04 a las 12 57 27](https://user-images.githubusercontent.com/10158320/38303940-e8986eb4-3807-11e8-9023-9aae6420c3e7.png)
**Development (--dev)**
![captura de pantalla 2018-04-04 a las 12 57 37](https://user-images.githubusercontent.com/10158320/38303941-e8b43d38-3807-11e8-913a-325d7f1ca276.png)

**Comment by jthoms1** [comment]
Also very likely you don't need classnames, but this would be up to you. We support the following:

```jsx
<span class={{
   'red': true,
   'blue': false
}} />

**Comment by albertvazquezm** [comment]
Thanks @jthoms1 this solves my problem for the meantime. However, will find a bit of time to set up a repro of the issue for easiest fix.
