### ISSUE TITLE
Components with slots and JSX array renders out-of-order

### ISSUE THREAD

**Issue by mattdsteele** [ionic-team/stencil#694]
**Stencil version:**

```
 @stencil/core@0.7.14
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Using a component like:

```html
  <my-component first="Stencil" last="'Don't call me a framework' JS">
    <p>Hello friend!</p>
  </my-component>
```

With a component that has `shadow:false` and returns an array of JSX from its render() function:

```typescript
  render() {
    return [
      <p>
        Hello, World! I'm {this.first} {this.last}
      </p>,
      <slot />
    ];
  }
```

It'll render the slot first in the array, a la:

![image](https://user-images.githubusercontent.com/389077/38341774-e8cdd2a6-383f-11e8-88ad-c0059eefaa64.png)

**Steps to reproduce:**

1. Clone https://github.com/mattdsteele/stencil-array-render
1. Run `npm run start`
1. Note the `<my-component>` element renders its components backward

**Other information:**

Seems to work fine in native Shadow browsers when `shadow: true` is set, and also if you wrap things in a <div> rather than return an array.

Based on a few git bisects it looks like this got introduced either in  https://github.com/ionic-team/stencil/commit/00b6af6a822b89dfdf5aab45285fad9e1b9b3f3c or https://github.com/ionic-team/stencil/commit/f78f8744037d24478e5a41a7afc54cb6b4ef1661

**Comment by adamdbradley** [comment]
fixed with https://github.com/ionic-team/stencil/commit/79fbf50801b969a24911e06f99aee2ea18165690 thanks
