### ISSUE TITLE
Passing props in tests are breaking in 0.7.13 upwards

### ISSUE THREAD

**Issue by jagreehal** [ionic-team/stencil#697]
```
 @stencil/core@0.7.13
```

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
So something has changed between 0.7.13 breaks tests which pass in props (0.7.12 is OK) e.g. 

```tsx
describe('passing in props', () => {
    let element;
    beforeEach(async () => {
      element = await render({
        components: [MyApp],
        html: '<my-app first="Peter" last="Parker"><my-app>'
      });
    });

    it('should be able to pass in prop values in tests', async () => {
      await flush(element);
      expect(element.textContent).toEqual('Hello, my name is Peter Parker');
    });
  });
```

**Expected behavior:**
Tests props should continue to be passed

**Steps to reproduce:**
See the code above or https://github.com/jagreehal/stencil-boilerplate/blob/master/src/components/my-app/my-app.spec.tsx

**Comment by adamdbradley** [comment]
Thanks for opening the issue, we'll get the testing suite fixed up, and tested itself. Thanks

**Comment by sebastien-yoobic** [comment]
Hi I had the same issue and downloaded the new stencil version 7.16 but this test is still failling:
```tsx

it ('Should be displayed as a circle without progress', async () => {
            let element;
            element = await render({
                components: [ProgressBarComponent],
                html: '<progress-bar progress="34" circle="true" hide-progress="true"></progress-bar>'
              });
            expect(element.circle).toEqual(true); // PASS
            expect(element.hideProgress).toEqual(true); // FAIL
```

It used to pass with stencil v0.7.12. This might just be related to the case of the prop ?

**Comment by adamdbradley** [comment]
Ok thanks, i'll take another look and get this fixed up. One thing we'll be doing soon is changing the underlying testing architecture to use puppeteer, which should drastically help the testing suite.

**Comment by sebastien-yoobic** [comment]
Amazing ! Thanks :)
