### ISSUE TITLE
Cannot have multiple component distributions with ES5 build in the same page

### ISSUE THREAD

**Issue by alexcheng1982** [ionic-team/stencil#699]
**Stencil version:**

```
 @stencil/core@0.7.18
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When a page includes multiple component distributions with ES5 build, the page cannot be loaded and no components are rendered. Below is the error shown in the console.

```
myapp.core.pf.js:21 Uncaught TypeError: Cannot read property 'create' of undefined
    at t.e.(:8000/anonymous function) (http://localhost:8000/shared/myapp/myapp.core.pf.js:21:2778)
    at new t (ionic.ylxy3ivk.js:96)
    at HTMLDocument.n.createElement (ionic.ylxy3ivk.js:21)
    at HTMLDocument.n.createElement (myapp.core.pf.js:21)
    at EmulatedEncapsulationDomRenderer2.createElement (platform-browser.js:1983)
    at EmulatedEncapsulationDomRenderer2.createElement (platform-browser.js:2196)
    at DebugRenderer2.createElement (core.js:13017)
    at createElement (core.js:8725)
    at createViewNodes (core.js:11635)
    at callViewAction (core.js:12108)
```
The error occurs at [this line](https://github.com/WebReflection/document-register-element/blob/33fd3013bea75af04447473548bbed52a73a5c03/src/document-register-element.js#L967).

**Expected behavior:**
Components should be rendered.

**Steps to reproduce:**
1.  Create any custom component and its distribution with ES5.
2. Create a HTML page to include both JavaScript files of the custom component and Ionic 4.
3. View the page and force to use ES5 by adding `?core=es5`.

**Related code:**

**Other information:**

The issue is because the ES5 build has the [polyfill](https://github.com/WebReflection/document-register-element) for W3C Custom Elements. This polyfill maintains its own internal registration of defined custom elements. When multiple ES5 distributions are included, the later polyfill overrides previous one, so the custom elements defined before are lost. After I manually removed the polyfill code in other files, the page can be loaded. 

I searched the code, but couldn't find the option to exclude the polyfill. `BuildConditionals` has the property `polyfills` to control the inclusion of polyfill, but this property cannot be set as the build option.

**Comment by jgw96** [comment]
@alexcheng1982 Could you put together a demo repo we could use to reproduce this issue? Thanks!
