### ISSUE TITLE
npm test broken on windows - cannot find module ... '\' disappeared

### ISSUE THREAD

**Issue by rlasjunies** [ionic-team/stencil#700]
**Stencil version:**

```
 @stencil/core@<0.7.18>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
* running `npm test` of the starter app on windows 10
* error `Cannot fing module '... folder without \ ...' `

**Expected behavior:**
to have the test running ;-)

**Steps to reproduce:**
explained above

**Other information:**
I will propose a PR for this.
The problem come from the `node_modules\@stencil\core\testing\jest.preprocessor.js` line 15.

**Comment by rlasjunies** [comment]
PR proposed: #701

**Comment by adamdbradley** [comment]
Merged! https://github.com/ionic-team/stencil/pull/701 thanks!
