### ISSUE TITLE
Docs for distribution deprecated

### ISSUE THREAD

**Issue by franktopel** [ionic-team/stencil#703]
> [Distributing web components built with Stencil](https://stenciljs.com/docs/distribution)

still describes using

    generateDistribution: true,

while your compiler says
```
[ WARN  ]  As of v0.7.0, the config property "generateDistribution" has
           been deprecated in favor of a multiple output target
           configuration. Please use the "outputTargets" config which is
           an array of output targets. Note that not having an
           "outputTarget" config will default to have an { type: "www" }
           output target. More information aobut the new format can be
           found here: https://stenciljs.com/docs/stencil-config
```
Also I couldn't find a documentation on how to use the generated components through ES6-importing them into other (webpack) build processes which would be crucial to make StencilJS a tool that can be considered for real-life projects, like using

    import MyComponent from './dist/my-component/my-component.js'

in the entry point of my `webpack.config.js` e.g. in my `vue-webpack` project?

What else would I have to import to make the component be usable in the generated Javascript?

**Comment by jgw96** [comment]
Thanks for opening an issue with us! As this is a documentation issue I will be moving this issue to the stencil-site repo.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil-site#165
