### ISSUE TITLE
knockout interoperability

### ISSUE THREAD

**Issue by FelschR** [ionic-team/stencil#707]
I'm just wondering if anyone here is using stencil web components within a knockout application?

I want to slowly start replacing all the legacy knockout parts of the web app but I'm not sure how easy it is.
Does the knockout data binding interfere with stenciljs? Does anyone have examples of integrating them?

Thanks for your answers!

**Comment by adamdbradley** [comment]
We haven't tried stencil on knockout apps yet, but would love to have more testers to give it a shot. In theory it should work, but may require a shim here or there, but that's the part we need help testing. If you have an app you're porting over, it'd be easier for us to answer questions in slack, so feel free to ping us in there. Thanks

https://stencil-worldwide.herokuapp.com/

**Comment by shailensukul** [comment]
Disclaimer: I have just started looking into Stencil, so please take this feedback with a grain of salt.
According to the [stencil docs](https://stenciljs.com/docs/reactive-data):
```
..mutating an object will not trigger a view update in Stencil, but returning a new copy of the object will
```
In theory, if the bound property is wrapped by a knockout observable, acting as a shim, Stencil components can work with the KO model by refreshing themselves based on parent mutating the state. So you could have an observable on the parent and copy the changed value to a property bound to the Stencil web component.

To detect property updates from the component, you can use the [@Watch decorator](https://stenciljs.com/docs/reactive-data#watch-decorator)

[Additional Reference](https://github.com/ionic-team/stencil/issues/185)

**Comment by FelschR** [comment]
I created a small library for using web components within knockout using a ko binding handler:
https://github.com/FelschR/knockout-web-components
