### ISSUE TITLE
Unit test broken when importing external stencil component

### ISSUE THREAD

**Issue by dpellier** [ionic-team/stencil#713]
**Stencil version:**

```
 @stencil/core@0.7.19
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Since moving to 0.7.19, unit test are not working for component that import other external stencil component:
```
TypeError: Cannot read property 'getAttribute' of undefined
      at node_modules/@namespace/some-component/dist/some-component.js
      at Object.<anonymous> (node_modules/@namespace/some-component/dist/some-component.js)
      at Object.<anonymous> (src/current-component/current-component.tsx)
      at Object.<anonymous> (test/current-component/current-component.unit.spec.ts)
```

**Expected behavior:**

Unit test should work.
(previously, the exact same were executing correctly with version v0.6.6)

**Steps to reproduce:**

Install some component as a npm dependency.
Import this component in your current component.
Run some unit test.

**Related code:**
"src/current-component/current-component.tsx"
```tsx
import '@namespace/some-component';
...
```

"test/current-component/current-component.unit.spec.ts"
```tsx
import { TestWindow } from '@stencil/core/dist/testing';
import { CurrentComponent } from '../../src/current-component/current-component';

describe('current-component', () => {
	let element: any;
	let window: TestWindow;

	beforeEach(async() => {
		window = new TestWindow();
		element = await window.load({
			components: [CurrentComponent],
			html: '<current-component></current-component>',
		});
	});
        ...
```

**Other information:**

The external component was build using stencil v0.7.19 also.

**Comment by adamdbradley** [comment]
Thanks for the report, we'll get it fixed up

**Comment by juanmiguelbesada** [comment]
Related to #675?

**Comment by DennisJamin** [comment]
Any updates?

**Comment by DennisJamin** [comment]
Any updates on this issue? We're facing the same issue here and would really like to update to the latest Stencil components.

**Comment by adamdbradley** [comment]
`TestWindow` has been removed as of `0.13.0`. With the last testing updates it's broken up into unit testing and e2e testing: https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-0130-2018-09-26
