### ISSUE TITLE
Fail to load app.core.js when using defer script in dev mode.

### ISSUE THREAD

**Issue by daqst** [ionic-team/stencil#714]
**Stencil version:**

```
 @stencil/core@0.7.15
```

**I'm submitting a:**

[x] bug report

**Current behavior:**

Currently in development mode, if the main `app.js` script file is included with a `defer` tag, the code responsible for figuring out which script element is the "current script" will return the last script, rather than the correct script (unless `app.js` happens to be the last script).

**Expected behavior:**

The page/app should load without issue.

**Steps to reproduce:**

1. Clone a new copy of `stencil-starter`.
2. Add the `defer` attribute to `<script src="/build/app.js">`.
3. Run `npm run dev` to test the build.
4. Page will fail to load (throwing a CORS error when trying to load `app.core.js` from the livereload port).

**Related code:**

```tsx
// figure out the script element for this current script
y = doc.querySelectorAll('script');
for (x = y.length - 1; x >= 0; x--) {
    scriptElm = y[x];
    if (scriptElm.src || scriptElm.hasAttribute('data-resources-url')) {
        break;
    }
}
```

**Other information:**

This can be remedied by changing the `if` statement to check if the current script source is for the `fsNamespace` file rather than some other script:
```tsx
if (scriptElm.hasAttribute('data-resources-url') ||
    scriptElm.src && scriptElm.src.endsWith(fsNamespace + '.js')) {
  break;
}
```

**Comment by adamdbradley** [comment]
We'll need this so that it's able to figure out it's correct location in all browsers. Production builds inline the loader script avoid a separate request anyways. For now I'd recommend not using defer at all, and we should probably document this better, and create some warnings in the compiler to avoid this. Thanks
