### ISSUE TITLE
CustomEvent Typescript backwards compatible

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#724]
**Stencil version:**
stencil/core v0.7.20

**I'm submitting a:**
[X] bug report
[X ] feature request

**Current behavior:**
`CustomEvent` in Typescript < 2.7 isn't generic (https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#customevent-is-now-a-generic-type)

Therefore generating a `component.d.ts` file with non generic `CustomEvent` isn't backwards compatible with project using previous version of Typescript, notably currently all Ionic < 4 projects

**Expected behavior:**
Don't automatically generate annotated `CustomEvent` to `component.d.ts`

**Related Ionic error:**

`ionic serve`

> [13:37:27]  typescript: node_modules/web-photo-filter/dist/types/components.d.ts, line: 63 
>             Type 'CustomEvent' is not generic. 
> 
>       L62:  'level'?: number;
>       L63:  'onFilterLoad'?: (event: CustomEvent<WebPhotoFilterResult>) => void;
>       L64:  'src'?: string;

**Related code:**

After the update from Stencil v0.6.18 to v0.7.20 the CustomEvent (in this commit I try manually to make it generic)

https://github.com/peterpeterparker/web-photo-filter/commit/8a5e76cf00106c532403f09707170bb5bef1131b

**Comment by jgw96** [comment]
Hey! This is actually a known backwards compatibility issue in TypeScript. Because this is an issue in TypeScript and not Stencil, I am going to close this issue for now. Thanks for using Stencil!

**Comment by peterpeterparker** [comment]
@jthoms1 yes exactly it's the "workaround" I have now implemented in order to be compatible with my app using Ionic 3 (see https://github.com/peterpeterparker/web-photo-filter/blob/master/src/components/web-photo-filter/web-photo-filter.tsx)

but you now, non generic is just more clear ;)
