### ISSUE TITLE
Typescript paths alias compiler error

### ISSUE THREAD

**Issue by cdock1029** [ionic-team/stencil#728]
**Stencil version:**

```
 @stencil/core@0.7.21
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Attempting to use Typescript paths alias. 
`tsconfig.json`:

```json
"baseUrl": ".",
"paths": {
  "@services/*": ["src/components/services/*"]
}
```

Directory structure:
```
├── my-app
│   ├── my-app.scss
│   ├── my-app.spec.ts
│   └── my-app.tsx
├── pages
│   ├── app-home
│   │   ├── app-home.spec.ts
│   │   └── app-home.tsx
│   ├── app-profile
│   │   ├── app-profile.spec.ts
│   │   └── app-profile.tsx
│   └── login-page
│       └── login-page.tsx
└── services
    └── database-injector.tsx
```

Importing types in `login-page.tsx` 
```typescript
import { IDatabase } from '@services/database-injector'
```

**Compiler output**
```
[ ERROR ]  typescript: src/components.d.ts, line: 33
           An import path cannot end with a '.tsx' extension. Consider importing
           'src/components/services/database-injector' instead.
```
Debug/console.logging the `typeImportString` in 
https://github.com/ionic-team/stencil/blob/41e40898f0e45151d19e5661c547df4e013fc00e/src/compiler/transpile/create-component-types.ts#L123

shows this:

```typescript
import {
  IDatabase,
} from 'src/components/services/database-injector.tsx';
```

**Expected behavior:**
Has no problem compiling path aliases. VS Code is having no issues with the paths as defined.

**Comment by jgw96** [comment]
@cdock1029 would you mind posting a repo we can use to reproduce this issue?

**Comment by cdock1029** [comment]
https://github.com/cdock1029/ts-paths
