### ISSUE TITLE
npm start 。。。 error

### ISSUE THREAD

**Issue by lei1996** [ionic-team/stencil#731]
Browser  
{
  "error": {
    "errno": -2,
    "code": "ENOENT",
    "syscall": "stat",
    "path": "/Users/lin/project/test/stencil-starter/www"
  }
}

**Stencil version:**

```@stencil/core@0.7.15
 @stencil/core@<version>
```@stencil/core@0.7.15

**I'm submitting a:**
<!-- (check one with "x") -->
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
<!-- Describe how the bug manifests. -->

**Expected behavior:**
<!-- Describe what the behavior would be without the bug. -->

**Steps to reproduce:**
<!-- If you are able to illustrate the bug or feature request with an example, please provide steps to reproduce and if possible a demo
-->

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by lei1996** [comment]
mac os 10.13.4
node.js  v8.11.1

**Comment by lei1996** [comment]
npm v5.8.0

**Comment by lei1996** [comment]
git clone https://github.com/ionic-team/stencil-starter.git my-app
cd my-app
git remote rm origin
npm install
npm start

之后就 error  了

**Comment by jgw96** [comment]
Hey! Since this seems to be an issue with the stencil-app-starter and not Stencil itself I am going to move this issue to that repo. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil-app-starter#46
