### ISSUE TITLE
"Cannot read property 'type' of null": 0.7.16 -> 0.7.17+

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#733]
**Stencil version:**
```
 @stencil/core@0.7.17+>
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Doesn't compile anymore. Did without problems prior to 0.7.17+.
No other code changes.

The terminal out:
```terminal
{ TypeError: Cannot read property 'type' of null
    at error (/Users/matthias/Documents/Projekte/bitflower/Case OS/Prototype/v0.2/caseos-ui/node_modules/rollup/dist/rollup.js:168:15)
    at Object.error (/Users/matthias/Documents/Projekte/bitflower/Case OS/Prototype/v0.2/caseos-ui/node_modules/rollup/dist/rollup.js:19382:21)
    at /Users/matthias/Documents/Projekte/bitflower/Case OS/Prototype/v0.2/caseos-ui/node_modules/rollup/dist/rollup.js:19391:29
    at <anonymous>
  code: 'PLUGIN_ERROR',
  plugin: undefined,
  id: '/Users/matthias/Documents/Projekte/bitflower/Case OS/Prototype/v0.2/caseos-ui/node_modules/rollup-plugin-node-builtins/src/es6/http-lib/to-arraybuffer.js' }
[27:13.3]  module map finished in 2.57 s
[ ERROR ]  Cannot read property 'type' of null

[ ERROR ]  rollup died at /Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui/node_modules/@stencil/core/dist/compiler/index.js:16780:19
           at Generator.throw (<anonymous>) at rejected
           (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui/node_modules/@stencil/core/dist/compiler/index.js:16738:65)
           at <anonymous>

[27:13.5]  build failed, watching for changes... 
```

**Expected behavior:**
Compiles without errors.

**Steps to reproduce:**
Check out the repo, `npm install`, `npm run dev`
**(Check the remarks regarding the check in files from `node_modules`!)**

The repo is on `0.7.17` but the problem persist up to `0.7.24` (latest as of today)

[REPO](https://github.com/bitflower/stencil-type-null-issue)

I have added @jthoms1 and @adamdbradley to this private repo.

**Related code:**

```tsx
// insert any relevant code here
```

**Comment by adamdbradley** [comment]
Looks like it may have something to do with our dependencies: https://github.com/ionic-team/stencil/commit/57db81216d7fd012c12143bab6b3eb9db53cc6d6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by bitflower** [comment]
2 major ups involved... sounds like a potential!

Can this be covered with 1-2 tests?

**Comment by adamdbradley** [comment]
Sure can. Would you be able to help debug this? I'm not sure where in your app it's breaking.

**Comment by bitflower** [comment]
This would mean to debug the Stencil compiler right? Never went this "deep" LOL. But I can try....

**Comment by creal73** [comment]
Hi guys, I will investigate on my side too. I have the same kind of error using d3-force package

**Comment by jgw96** [comment]
@bitflower or @creal73 Could yall provide a repo we could use to reproduce this error? Preferrably a repo that has the minimal setup / code needed to repro the error. This will help speed up the debugging of this issue. Thanks for using Stencil!

**Comment by bitflower** [comment]
Hey @jgw96 The repo provided in the issue is "minimal" in the way that you only need to `npm install` and you're good to go. Sure, if you want to go ahead after fixing this issue you'll fall into #494 but this shouldn't mater for now....

I've added you to the collaborators.

**Comment by bitflower** [comment]
Hey guys, I tried to dig into the compiler but I‘m really having trouble setting up console logs, breakpoints and stuff. Anything else I can provide? Is the repo too „complicated“? Do you the smaller one requested by @jgw96?

**Comment by jthoms1** [comment]
I have validated that PR #760 resolves this issue. Please update your config to the following. Note that the only change was adding `nodeResolve` with `browser` as `true`.

This is not yet released but should be today.

This is per the documentation provided by `rollup-plugin-node-resolve`. https://github.com/rollup/rollup-plugin-node-resolve#usage

```js
exports.config = {
  nodeResolve: {
    browser: true
  }
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
};
```
