### ISSUE TITLE
SSR renderer stopped including styles

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#734]
**Stencil version:**

```
 @stencil/core@>=0.7.0
```

**I'm submitting a:**

[x] bug report

**Current behavior:**

Given I have created components with `stencil build` using this config
```js
exports.config = {};
```

And I hydrate a html document using this code:

```js
const stencil = require("@stencil/core/server");
new stencil.Renderer(stencil.loadConfig(__dirname))
  .hydrate({
    html: "<my-app></my-app>"
  })
  .then(results => {
    console.log(results.html);
  });
```

Then the hydrated html does not contain styles used by my component

**Expected behavior:**
Prior to `stencil@0.7.0` the component styles had been added to the result document.

**Steps to reproduce:**

1. check out the [stencil-app-starter](https://github.com/ionic-team/stencil-app-starter)
2. copy the above hydration script to `test.js`
3. run `npm run build && node ./test.js`
4. see -->no<-- included css 
5. downgrade stencil with `npm i @stencil/core@0.6.18`
6. run `npm run build && node ./test.js`
7. see included css 

**Other information:**

`stencil build --prerender` still includes all the css so this might as well just be a documentation issue. In wich case -> https://github.com/ionic-team/stencil-ssr-starter/issues/3

As always: I'd be happy to provide a PR for this. But right now I have no idea where to start looking.

**Comment by Xiphe** [comment]
works as expected with config:

```js
exports.config = {
  flags: { prerender: true }
};
```

Leaving this open because I think the docs should be updated about this.

**Comment by adamdbradley** [comment]
Thanks for opening this issue, it helped expose some issues, and now we've got some good tests around the entire process. Thanks!
