### ISSUE TITLE
[proposal] strict dependency graph generation

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#737]
The idea is that components can be "imported" statically:
```ts
import { IonContent } from '@ionic/core';
```

The trick is:
```ts
export const IonContent = 'ion-content';
```

That means it's not importing the real component but a "reference" to it, lazy loading will continue working the same.

That means the generated code will be the same as it's today, but there are some good advantages:

- The names of the components can be found using autocompletion.
- We can deprecated components (using the IDE)
- No typing issues (ion-item-sliding or ion-sliding-item)?
- *Better and more reliable graph analysis*

## Better and more reliable graph analysis

The stencil compiler can take these imports as the main source of graph information instead of the current heuristics (that usually fail).
The biggest advantage in my opinion is the ability to fine tune how components are referenced. For example:

```ts
render() {
  render() {
    return [
      this.deviceHacks && <ion-input-shims></ion-input-shims>,
      <ion-tap-click></ion-tap-click>,
      this.isDevice && <ion-status-tap></ion-status-tap>,
      <slot></slot>
    ];
  }
```

Today the stencil compiler bundles together `ion-status-tap` and `ion-tap-click` but this is not good, since it's a conditional reference. With the new "static" system, developers can fine tune this. By using `IonTapClick` they want a "strong" reference (used by the graph analysis), while using "ion-tap-click" is a weak reference that we don't want the graph analysis to take into account.

Another problematic with the current approach:

```ts
  @Method()
  create(opts?: ActionSheetOptions): Promise<HTMLIonActionSheetElement> {
    return createOverlay(document.createElement('ion-action-sheet'), opts);
  }
```

^ Here's another problem with overlays, We moved the createElement() to createOverlay(), but that *broke the graph analysis* since the compiler was not able to pick up the reference between `ion-action-sheet-controller` and `ion-action-sheet`. With the new system we could:

```ts
  @Method()
  create(opts?: ActionSheetOptions): Promise<HTMLIonActionSheetElement> {
    return createOverlay(IonActionSheet, opts);
  }
```

Bonus:

- it will look more similar for preact and react developers.
- it's a 100% backcompatible proposal

**Comment by romulocintra** [comment]
Sounds great ... in that situation IDE's can profit from type inference and overall Perf  would  be improved ... great and smart

**Comment by adamdbradley** [comment]
So for every component to be used requires an import of each component, in each component?

**Comment by manucorporat** [comment]
@adamdbradley no, you could still use:

**Comment by manucorporat** [comment]
@romulocintra the IDE can already infer the type information if you use the HTML tag. Also perf, should be the same, in fact the generated code will be exactly the same, but it gives additional information to the compiler, so bundling or preloading strategies would be more accurate .

**Comment by mattdsteele** [comment]
Might be an orthogonal concern, but this wouldn't address the "all custom elements are in a global registry" issue, right?

For example if I had two components, each with the same `<custom-comp>` tag:

```
import { CustomComp as CompV1 } from 'component-v1';
import { CustomComp as CompV2 } from 'component-v2';

render() {
  return [
    <CompV1 />,
    <CompV2 />
  ]
}
```

This would fail because both get registered by the browser as `custom-comp`?

I believe there was some work in addressing this (possibly by @treshugart?) but don't know how much is tied to Skate vs changes to the CE spec.

**Comment by jgw96** [comment]
@mattdsteele this is kinda just my opinion, but I would think we would want to stick with the spec here and not allow two separate components that have the same tag. Does that work in something like React?

**Comment by treshugart** [comment]
@mattdsteele skate just has a utility for generating a unique name: http://skatejs.netlify.com/utils/name. I've long wanted ways to get around the "globalness" of custom elements, which is one of the several criticisms I see coming from other communities. Maybe [scoped custom element registries](https://github.com/w3c/webcomponents/issues/716) will help this.

**Comment by manucorporat** [comment]
@mattdsteele @treshugart the point of this proposal is not to have another way to use components.

Exported references are just strings:
```
export const IonContent = 'ion-content';
```
