### ISSUE TITLE
Slot within table won't render tr nor td

### ISSUE THREAD

**Issue by vknabel** [ionic-team/stencil#738]
**Stencil version:**

```
 @stencil/core@0.7.24
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

`tr` and `td` will not be rendered within `<slot/>` inside a table

**Expected behavior:**
`tr` and `td` should render within `<slot/>` inside a table

**Steps to reproduce:**

1. Create new project as described in [Getting Started](https://stenciljs.com/docs/getting-started/).
2. Insert code below.
3. Run tests

**Related code:**

```tsx
@Component({
  tag: 'my-table'
})
export class MyTableComponent {
  @Prop() background = false;

  render() {
    const classList = {
      'table': true,
      'table--background': this.background
    };
    return (
      <table class={classList}>
        <slot />
      </table>
    );
  }
}

describe('my table', () => {
  it('renders children within table', async () => {
    const window = new TestWindow();
    const element: HTMLElement & Partial<MyTableComponent> = await window.load({
      components: [MyTableComponent],
      html: `
      <my-table>
        <p child><td>Hello</td></p>
        <tr child><td>Hi</td></tr>
      </my-table>
      `
    });
    const children = Array.from(element.querySelectorAll('[child]'));
    expect(children).toHaveLength(2);
  });
});
```

**Other information:**
The output of the failed test
```
my table › renders children within table

    expect(received).toHaveLength(length)

    Expected value to have length:
      2
    Received:
      [<p child="">Hello</p>]
    received.length:
      1
```

**Comment by jgw96** [comment]
Hey, thanks for opening an issue with us! Is this just breaking in tests or does it also break in the browser? Im seeing it work for me in the browser, but breaking during tests.

**Comment by vknabel** [comment]
It breaks differently. In my browser (latest Chrome on latest macOS) only the tags will be removed, but the text inside will still be rendered:

```html
<my-table class="hydrated">
  <table class="table"><!---->
        
          Hello
          World
        
        
          Hello
          User
          
      </table>
</my-table>
```

**For written HTML:**

```html
<my-table>
    <tr>
        <td>Hello</td>
        <td>World</td>
    </tr>
    <tr>
        <td>Hello</td>
        <td>User</td>
    </tr>
</my-table>
```

**Comment by jgw96** [comment]
Hey! We are currently refactoring slots to match native slots 1:1. Once that refactor is done I am going to give this another test as that should solve this issue

**Comment by juanmiguelbesada** [comment]
I'm not an expert but I don't think this could be fixed (at leas easly), as every browser parse the html before any js could be run.

At this moment, chrome (even FF or edge) strip the tr/td from any malformed html.

Try this in an empty html

```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
  <title>Malformed HTML</title>
</head>
<body>

  <my-table>
    <tr>
      <td>Hello</td>
      <td>World</td>
  </tr>
  <tr>
      <td>Hello</td>
      <td>User</td>
  </tr>
  </my-table>

<mytable2>
    <tr>
        <td>Hello</td>
        <td>World</td>
    </tr>
    <tr>
        <td>Hello</td>
        <td>User</td>
    </tr>
</mytable2>

<div>
    <tr>
        <td>Hello</td>
        <td>World</td>
    </tr>
    <tr>
        <td>Hello</td>
        <td>User</td>
    </tr>
</div>

</body>
</html>
```
Check the inspector and you will notice that the tr and td will gone.

@adamdbradley and @jgw96 did you agree or I'm wrong?
