### ISSUE TITLE
Stencil and AWS API JavaScript Error

### ISSUE THREAD

**Issue by keean** [ionic-team/stencil#740]
**Stencil version:**

```
@stencil/core@0.7.24
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

After fixing the issue with:
node_modules/rollup-plugin-node-builtins/src/es6/http-lib/to-arraybuffer.js
You get this error in the javascript console when doing `npm start`
```
TypeError: undefined is not an object (evaluating 'util_1.memoizedProperty')
"http://localhost:3333/build/app/my-app.js"
```
**Expected behavior:**

It should print the CISP object to the JavaScript console

**Steps to reproduce:**

clone the example repo, npm install and then npm start

Note: I have already fixed node_modules/rollup-plugin-node-builtins/src/es6/http-lib/to-arraybuffer.js in the GitHub repo.

**Related code:**
https://github.com/keean/stencil-aws

**Other information:**

**Comment by jgw96** [comment]
Hey @keean , thanks for opening an issue with us. What issue are you talking about with that `arraybuffer.js `file? Also I have talked to and assigned our resident rollup export to this issue.
