### ISSUE TITLE
Stencil "npm run build" fails with Material Design Components for Web.

### ISSUE THREAD

**Issue by keean** [ionic-team/stencil#741]
**Stencil version:**

```
 @stencil/core@0.7.24
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
It works when I do `npm start`
When doing `npm run build` I get the following error (git repo referenced later):
```
[ ERROR ]  runtime console.error: /
           Could not parse CSS stylesheet at exports.evaluateStylesheet
           (stencil-mdc/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:18:21)
           at HTMLStyleElementImpl._attach
           (stencil-mdc/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:23:5)
           at HTMLHeadElementImpl.insertBefore
           (stencil-mdc/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:230:22)
           at HTMLHeadElement.insertBefore
           (stencil-mdc/node_modules/jsdom/lib/jsdom/living/generated/Node.js:182:45)
           at insertStyles
           (stencil-mdc/node_modules/@stencil/core/dist/compiler/index.js:9762:18)
           at inlineComponentStyles
           (stencil-mdc/node_modules/@stencil/core/dist/compiler/index.js:9755:5)
           at
           stencil-mdc/node_modules/@stencil/core/dist/compiler/index.js:10100:17
           at Generator.next (<anonymous>) at
           stencil-mdc/node_modules/@stencil/core/dist/compiler/index.js:10076:71
           at Promise (<anonymous>),
           header{background:#5851ff;color:#fff;height:56px;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-align:center;-webkit-align-items:center;-ms-flex-align:center;align-items:center;-webkit-box-shadow:0
           2px 5px 0 rgba(0,0,0,.26);box-shadow:0 2px 5px 0
           rgba(0,0,0,.26);}h1{font-size:1.4rem;font-weight:500;color:#fff;padding:0
           12px;}@-webkit-keyframes
           mdc-ripple-fg-radius-in{from{-webkit-animation-timing-function:cubic-bezier(.4,0,.2,1);animation-timing-function:cubic-bezier(.4,0,.2,1);-webkit-transform:translate(var(--mdc-ripple-fg-translate-start,0))
           scale(1);transform:translate(var(--mdc-ripple-fg-translate-start,0))
           scale(1);}to{-webkit-transform:translate(var(--mdc-ripple-fg-translate-end,0))
           scale(var(--mdc-ripple-fg-scale,1));transform:translate(var(--mdc-ripple-fg-translate-end,0))
           scale(var(--mdc-ripple-fg-scale,1));}}@keyframes
           mdc-ripple-fg-radius-in{from{-webkit-animation-timing-function:cubic-bezier(.4,0,.2,1);animation-timing-function:cubic-bezier(.4,0,.2,1);-webkit-transform:translate(var(--mdc-ripple-fg-translate-start,0))

[43:11.7]  build failed in 15.57 s
```

**Expected behavior:**
build should be successful.

**Steps to reproduce:**

clone git repo: https://github.com/keean/stencil-mdc
npm install
npm start (button works)
npm run build (fails)

**Related code:**
https://github.com/keean/stencil-mdc

**Other information:**

**Comment by jgw96** [comment]
Hey @keean , so just to be clear, this issue only happens when you import the sass for that button component right?

**Comment by keean** [comment]
Right now it doesn't seem to work with 'npm start' either. I seem to be getting strangely inconsistent results. Normally the stencil compiler seems to output a "host.config.json" file, but right now the compiler seems to finish without an error, but file is missing, and the generated code is incomplete...

**Comment by jgw96** [comment]
Hey @keean , so just to clear things up, during a dev build the `host.config.json` file will not be created, so that is correct behavior. So this is breaking during dev builds (the sass is not getting pulled in) and prod builds?

**Comment by keean** [comment]
I was referring to a production build. The first production build fails with an error, subsequent ones look like they succeed but they are actually failing silently. I can't figure out where there could be any state that could be deleted to make it behave consistently. Also once it gets into this failure mode, even commenting out all the changes, it still won't produce good output.

**Comment by jgw96** [comment]
And the prod build only breaks after importing the sass for the material design components right?

**Comment by keean** [comment]
Yes, that's what seems to break it.

**Comment by jgw96** [comment]
Alright, thanks for the info. Im gonna check with some of the internal users we have that are using Sass and see if they have seen anything similar.

**Comment by keean** [comment]
I guess it generates incomplete .css when parsing the .scss, then uses the broken css which compiles, but does not work.

**Comment by keean** [comment]
I have just updated the GitHub repo, as I think it was getting confused by having the unused profile component from the initial example there. It looks like you can get 'npm start' to work again by deleting the output in the 'www' directory and the 'node_modules' directory, then doing a fresh 'npm install' before doing 'npm start', and this gets the dev mode working again, but I have not found a way to get the error out of the compiler reliably. Most of the time in a production build it fail silently, reporting a success, but the output in 'www' is incomplete, most noticably missing the 'host.config.json' file.

**Comment by jgw96** [comment]
@keean so after looking into this some more, it looks like the `@includes` is what is tripping things up. Continuing to debug

**Comment by keean** [comment]
Maybe the first step is to get the compiler to actually report the failure as a failed build? That would be a useful patch in itself, and would make debugging these kind of issues easier in the future.

**Comment by keean** [comment]
There is something else strange going on, the first time I run "npm run build" it fails, but on subsequent runs it appears to succeed, except there are files missing from the 'www' directory. The easiest way to tell if has silently failed seems to be to delete the 'www' directory before running the build, and then check afterwards for the "host.config.json" file, which will me missing if something has gone wrong.

**Comment by keean** [comment]
Does this still need a reply? I am happy to provide more information, I am just not sure what is needed.
