### ISSUE TITLE
Prerender build and direct link access for a white page.

### ISSUE THREAD

**Issue by kevin-lot** [ionic-team/stencil#744]
**Stencil version:**

```
@stencil/core@0.7.24 
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I try to access with a direct link to a page. Page are loaded, when the service worker starts, page becomes white. With an issue in console.
The website is compile with prerender option: stencil build --prerender.

**Steps to reproduce:**

You can see an effect here: https://keyclic.com/enterprise

**Comment by jgw96** [comment]
Hello! Thanks for using Stencil. Using chrome dev tools I bypassed the service worker and I was still able to reproduce this issue, so it seems like the issue is in the logic on that page. Do you have a minimal repro case you can share?

**Comment by kevin-lot** [comment]
I restarted from a blank project and I did not manage to reproduce the issue. I don't understand where it was.

So you can close it. Sorry for the inconvenience and thanks for the help.
