### ISSUE TITLE
Rollup died

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/stencil#745]
**Stencil version:**

```
 @stencil/core@0.7.24
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Adding this to my code:
```typescript
import Cesium from 'cesium';

this.map = new Cesium.Viewer(mapId, {
      scene3DOnly: true,
      selectionIndicator: false,
      baseLayerPicker: false
    });
```

I get:

> [ ERROR ]  bundling: node_modules/requirejs/bin/r.js, line: 1
>            Unexpected character '#' (1:0) in
>            /Users/admin/dev/map-leaflet/node_modules/requirejs/bin/r.js
> 
>       L1:  #!/usr/bin/env node
> 
> [ ERROR ]  rollup died at
>            /Users/admin/dev/map-leaflet/node_modules/@stencil/core/dist/compiler/index.js:16780:19
>            at Generator.throw (<anonymous>) at rejected
>            (/Users/admin/dev/map-leaflet/node_modules/@stencil/core/dist/compiler/index.js:16738:65)
>            at <anonymous>

**Expected behavior:**
Rollup should live

**Comment by jgw96** [comment]
Hey @AmitMY from that error, it looks like this is coming from the `map-leaflet` library. Are you importing that lib anywhere?

**Comment by AmitMY** [comment]
map-leaflet is my folder name, not a package. The erroring library is requirejs.

I have a webpack project with this code, works fine

**Comment by jgw96** [comment]
Hey @AmitMY , mind putting together a repo we can use to reproduce this?

**Comment by AmitMY** [comment]
I can’t make one today, so super simple:
Clone ionic-pwa repo
Add the above code to app-home

**Comment by jthoms1** [comment]
Could you please test this with v0.7.26? This has the newer Rollup release.

**Comment by AmitMY** [comment]
@jthoms1 Tried 0.7.26, Rollup died again

**Comment by jthoms1** [comment]
What OS are you on?

**Comment by AmitMY** [comment]
@jthoms1 macOS 10.13.4

**Comment by jthoms1** [comment]
PR #760 should resolve this issue. Please update your config to the following. Note that the only change was adding `nodeResolve` with `browser` as `true`.

This PR is not in a released version yet, but should be today.

This is per the documentation provided by `rollup-plugin-node-resolve`. https://github.com/rollup/rollup-plugin-node-resolve#usage

```js
exports.config = {
  nodeResolve: {
    browser: true
  }
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
};
```

**Comment by AmitMY** [comment]
@jthoms1 v0.8.0 same error.

**Comment by jthoms1** [comment]
@AmitMY did you make the configuration changes outlined above?  Can you provide the error again after making these changes?

**Comment by jthoms1** [comment]
@kraftwer1 Could you provide a simple repo that reproduces this so that I can troubleshoot your error? Thanks!

**Comment by kraftwer1** [comment]
Just run „npm -i gsap“ and add it into the Stencil starter kit.

**Comment by kraftwer1** [comment]
Reported to "gsap" as I think it's not a Stencil issue: greensock/GreenSock-JS#265

**Comment by kraftwer1** [comment]
@jthoms1 @AmitMY gsap fixed their modules and now it works fine. So this could be closed. Thank you guys.

**Comment by AmitMY** [comment]
This shouldn't, my reproduction is not with gsap.
