### ISSUE TITLE
life cycle (event) in Firefox and IE not same as Chrome

### ISSUE THREAD

**Issue by yupii7** [ionic-team/stencil#747]
**Stencil version:**

```
 @stencil/core@0.7.25
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I'm trying to get a collection of ion-card from a child function, it works with chrome (Version 65.0.3325.181) but I get undefined in firefox (59.0.2) and undefined  in ie (41.16299.371.0).

// chrome components life cycle output

```
The parent component is about to be rendered
The child component is about to be rendered
The grandchild component is about to be rendered
The grandchild component has been rendered
The child component has been rendered
(7) [ion-card.card.card-md.hydrated, ion-card.card.card-md.hydrated, ion-card.card.card-md.hydrated, ion-card.card.card-md.hydrated, ion-card.card.card-md.hydrated, ion-card.card.card-md.hydrated, ion-card.card.card-md.hydrated]
The parent component has been rendered
```

// firefox components life cycle output

```
The parent component is about to be rendered
The parent component has been rendered
The child component is about to be rendered
The child component has been rendered
undefined  **nothing**
The parent component will update
The parent component did update
The grandchild component is about to be rendered
The grandchild component has been rendered
```

// ie components life cycle output

```
 The parent component is about to be rendered
 The parent component has been rendered
 The child component is about to be rendered
 The child component has been rendered
 undefined -> **nothing**
 The grandchild component is about to be rendered
 The grandchild component has been rendered
 The parent component will update
 The parent component did update
```

**Expected behavior:**
Expect to get the collection of ion-card.

**Steps to reproduce:**
Three nested components: my-parent-component, my-child-component and my-grandchild-component.

// parent component
```
render() {
    return (
      <my-child-component>
          <slot />
      </my-child-component>
    );
  }
```

// child component
```
  componentDidLoad() {
    console.log('The child component has been rendered');

    this.gchild = this.element.querySelector('my-grandchild-component');
    console.log(this.gchild.getCollection());
  }
 ...
render() {
    return (
        <my-grandchild-component>
            <slot />
        </my-grandchild-component>
    );
  }
```

// grandchild component
```
@Method()
  getCollection(): Array<any>{
    return this.collection;
  }

  render() {
  return <slot />; // or just return;
  }
```

// index 

```
  <my-parent-component>
    <ion-card>
      <ion-card-content>
        ion content 1 
      </ion-card-content>
    </ion-card>
    <ion-card>
      <ion-card-content>
        ion content 2
      </ion-card-content>
    </ion-card>
    <ion-card>
      <ion-card-content>
        ion content 3
      </ion-card-content>
    </ion-card>
  </my-parent-component>
```

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by manucorporat** [comment]
@yupii7  does it work in `@stencil/core@0.7.24`?

**Comment by yupii7** [comment]
Nope ! Same behavior.

**Comment by manucorporat** [comment]
could you provide a repo that reproduces the issue? 

i am not sure where is `this.collection;` coming

**Comment by yupii7** [comment]
https://github.com/yupii7/nestedcompo-st

**Comment by yupii7** [comment]
Actually, if I'm not wrong, I'm facing this issue since version 0.7.7. I was fighting against a Flash of unstyled content (FOUC) with firefox and ie. Then I figure out that the life cycle sequence is not the same, comparing to chrome. So, for now I'm debugging my project with chrome and waiting for the fix.

**Comment by manucorporat** [comment]
@yupii7 thanks for your time! we will look at it ASAP!
