### ISSUE TITLE
Set value of a select

### ISSUE THREAD

**Issue by olivierscheffler** [ionic-team/stencil#752]
**Stencil version:**
```
 @stencil/core@0.7.22<version>
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
If I follow the documentation on https://stenciljs.com/docs/forms, Advanced form, it seems to be possible to set a value of the select on the state variable selectValue.
But if I set @State() selectValue: string = "saab"; nothing change on the select when reload.

**Expected behavior:**
As we see on this CodePen https://codepen.io/gaearon/pen/JbbEzX?editors=0010, it's possible to change the value.
I expect to get the same behaviour with a SpencilJS project.

**Steps to reproduce:**
Just take the code on https://stenciljs.com/docs/forms Advanced Form and put it in a Stencil project and try to set @State() selectValue: string = "saab" you will that nothing happen on the render.

**Comment by jthoms1** [comment]
Unfortunately this appears to be a documentation and types issue.  Value is not available on select elements. In order to make this work you will need to use 'selected={true}' on the options.

IE
```
<option value="volvo" selected={this.selectValue === 'volvo'}>Volvo</option>
```

**Comment by jthoms1** [comment]
We are updating the stencil site to reflect this today.

**Comment by PurpleEdge2214** [comment]
Except, you didn't!

https://stenciljs.com/docs/forms
