### ISSUE TITLE
Duplicate export compiler error

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil#754]
It's possible to get the compiler in a funk by copy/pasting a directory, which would have the same tag name and class name, which shouldn't be possible, and the compiler should warn saying you need to fix that. But when you do fix it, the compiler isn't letting it go and just holds onto anger.

![image](https://user-images.githubusercontent.com/452425/39195402-6290d236-47a5-11e8-9fc9-6e569fa3b573.png)

**Comment by franktopel** [comment]
This addresses the same problem as #763.
