### ISSUE TITLE
Slot components render wrong order of slot children on state change

### ISSUE THREAD

**Issue by corysmc** [ionic-team/stencil#757]
**Stencil version:**
```
 @stencil/core@0.7.27-2
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
If a slot component has content that is dynamically generated, it's order is changed on state change. 
(I think it's reverse order).

**Expected behavior:**
Content should be rendered in the same order it is declared inside the render function.

**Steps to reproduce:**
1. create a new component with a `<slot />` inside it
2. add that component to a parent component
3. add content inside the slot component: e.g. map over data or something that can be dynamically changed
4. change state of the content on load
5. observe order of dom

**Related code:**
This demo uses ionic:
https://github.com/corysmc/stencil-bug-demo/tree/slots-debug

This is a Stencil only demo:
https://github.com/corysmc/stencil-bug-demo/tree/content-reordered

**Comment by adamdbradley** [comment]
Fixed in https://github.com/ionic-team/stencil/commit/39d1afef2d03b90175d15869862030c4bff7889f
