### ISSUE TITLE
Stencil Config documentation error in namespace section

### ISSUE THREAD

**Issue by codyburleson** [ionic-team/stencil#769]
In the Stencil Config documentation, [namespace section](https://stenciljs.com/docs/config/#namespace) the following text is found:

> In the copy config below, it will copy the entire directory from `src/docs-content` over to `www/docs-content.`

That doesn't make sense in the namespace section. The very same copy text can also be found in the [copy section](https://stenciljs.com/docs/config/#copy) where it actually makes sense (and belongs). 

This seems to be a minor copy/paste error in the creation or editing of the document.

**Comment by jthoms1** [comment]
Corrected with https://github.com/ionic-team/stencil-site/commit/89f093fb99ffc41325ceaea3bbb2d6654c57eae1
