### ISSUE TITLE
How to import external angular component into stencil project

### ISSUE THREAD

**Issue by mu250234** [ionic-team/stencil#770]
HI,'
I am trying to import 'ionic-stepper' external npm module to existing stencils project. but getting errors, is it possible to import external angular components into stencils?
tried:
import { IonicStepperModule } from 'ionic-stepper';
 <ion-stepper # stepper (selectIndexChange) = "selectChange($event)" >
      <ion-step label="Step1"
        description="Step1 description">
        <h2>Step1 Content</h2>
        <p>Step1 Content</p>
        <button ion-button small ionicStepperNext>Next</button>
      </ion-step>
      <ion-step label="Step2 - Step2 - Step2"
        description="Step1 description">
        <h2>Step2 Content</h2>
        <p>Step2 Content</p>
        <button ion-button color="light" small ionicStepperPrevious>Previous</button>
      </ion-step>
    </ion - stepper >
error:
Cannot invoke an expression whose type lacks a call signature. Type 'Element' has no compatible call signatures.
[ts] The left-hand side of an assignment expression must be a variable or a property access.

**Comment by jthoms1** [comment]
This is not something that can be supported.  Angular Components can only be used in Angular Projects.

Its possible that you might just want to use Stencil components in an Angular Project which is possible.
