### ISSUE TITLE
Dynamic imported files are not working in the globalScript

### ISSUE THREAD

**Issue by nlx-sascha** [ionic-team/stencil#774]
**Stencil version:**

```
 @stencil/core@0.8.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When I use the new dynamic import feature in the global script file or in a file that is includes in the global script file the compile throws the following error:
```
[ ERROR ]  bundling: dist/collection/global/polyfill.js, line: 8
           Unexpected token

      L7:  if (!('IntersectionObserver' in window)) {
      L8:      await import('intersection-observer');

[34:12.9]  build failed in 17.28 s
```

**Expected behavior:**
The dynamic import feature should also work in the global script, to allow lazy loading of polyfills if needed 

**Steps to reproduce:**
Install the IntersectionObserver polyfill with `npm i intersection-observer`
Configure the globalScript in the `stencil.config.js`.

**Related code:**
src/global/foo-global.ts
```tsx
import { polyfill } from './polyfill';
const polyfill = polyfill();
```

src/global/polyfill.ts
```tsx
export async function polyfill() {
	const polyfill = [];
	if (!('IntersectionObserver' in window)) {
		polyfill.push(import('intersection-observer'));
	}
	return await Promise.all(polyfill);
}
```

**Comment by nlx-sascha** [comment]
It's more difficult then I thought.
Want I found out until now.
* generateBundles writes all jsModules before generateAppFiles is called
* GlobalScript is bundled way later
* GlobalScript(s) should be merged to jsModules, but this seems a big refactoring

**Comment by manucorporat** [comment]
In stencil one, global script is just like another script that rollup can parse! this should fix the issues with importing or using ESM from the global script!!

Stencil 1.0 will hit beta in the upcoming weeks!
