### ISSUE TITLE
Shadow mode + slot + prerendering results in duplicated markup

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#781]
**Stencil version:**

```
 @stencil/core@^0.7.25 || ^0.8.0
```

probably even earlier versions

**I'm submitting a:**

[x] bug report

not sure how its intended to work though

**Current behavior:**

Given I have a component

```tsx
import { Component } from '@stencil/core';

@Component({
  tag: 'my-header',
  shadow: true,
})
export class Header {
  render() {
    return (
      <div>
       <slot /> World
      </div>
    );
  }
}
```

And I use it in html

```html
<my-header>Hello</my-header>
```

And I pre-render it with `stencil build --prerender`

Then I receive some kind of double hydrated document after JS is loaded:

![image](https://user-images.githubusercontent.com/911218/39709044-0e1d1e16-5219-11e8-8194-80aa0233e66b.png)

**Expected behavior:**

I would expect to only see "Hello World" once in the document.

**Steps to reproduce:**

Use the stencil app starter and copy the above code into a component and the index.html. Build with `--prerender` and serve the `www` folder

**Other information:**

Not sure how to debug this one further and what the intended behaviour is.
Happy to submit a PR if you could help me get started.

**Comment by adamdbradley** [comment]
Would you be able to test w/ 0.8.0?

**Comment by Xiphe** [comment]
Tested with `0.8.0`, same issue

**Comment by Xiphe** [comment]
Any Ideas how to treat this? 

Proposals: 

 - do not prerender shadow-dom components. Since the web-component standard does not support pre-rendering of custom elements either.
 - move existing child elements into the shadow root on pre-rendering (is this even possible?)

**Comment by jagreehal** [comment]
I'm also encountering the same issue https://github.com/jagreehal/dumb-stencil

**Comment by andrewtennison** [comment]
any update on this, still have this issue

**Comment by jedihacks** [comment]
Having this issue as well:  https://github.com/openforge/OPENFORGE.IO

**Comment by adamdbradley** [comment]
this should be fixed in the most recent releases
