### ISSUE TITLE
Dedicated src/workers and www/workers directories

### ISSUE THREAD

**Issue by kael** [ionic-team/stencil#790]
**Stencil version:**

```
 @stencil/core@0.8.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request

**Current behavior:**

Currently when using Web Workers within components, it requires then to copy the web workers manually in the `ẁww/build` directory (unless I'm missing something ?).

**Expected behavior:**

It'd be nice to have a dedicated Web Workers folder in `src/workers` that would be copied to `ẁww/build/workers`.  

That way, it'd be possible to use the same path when calling the web worker, being internally from the Component:

```tsx
if ('Worker' in window) this.worker = new Worker('../workers/parser.js');
```
Or externally with the browser:
```
http://localhost:3333/workers/parser.js
```
Also, dependencies used by workers could be put in `*/workers/lib` for example or any arbitrary subfolder.

**Comment by adamdbradley** [comment]
Going to hold of on adding any worker features ATM. Thanks
