### ISSUE TITLE
Dynamic loading of multiple components from different contexts does not work

### ISSUE THREAD

**Issue by psimona** [ionic-team/stencil#793]
**Stencil version:**

```
 @stencil/core@0.8.1
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When loading multiple components dynamically (`document.body.appendChild(script);`) from URLs with different prefixes causes the second component (`*.<hash>.js`) to be fetched from the wrong context.

A concrete example:
```javascript
let scriptA = document.createElement('script');
scriptA.src = '/context-a/componentA.js'; // loader A location

let scriptB = document.createElement('script');
scriptB.src = '/context-b/componentB.js'; // loader B location

document.body.appendChild(scriptA);
document.body.appendChild(scriptB);
```

As the inserted scripts run asynchronously the following can happen:
scriptA 
- Expected: fetches core from /context-a/componentA/componentA.&lt;hash>.js --> 200
- Actual: fetches core from /**context-b**/componentA/componentA.&lt;hash>.js --> 404

**Expected behavior:**

Loading multiple components dynamically should work either:
- out of the box (requires `Document.currentScript` polyfill for IE11, does it exist?)
- by specifying the context '/context-a/', at build time (e.g. in stencil.config.js)

**Steps to reproduce:**

- Setup
```bash
git clone https://github.com/psimona/stenciljs-dynamic-loadng-bug.git stenciljs-dynamic-loadng-bug
cd stenciljs-dynamic-loadng-bug
npm install
npm start
```
- Browser opens to http://localhost:3000
- Open dev tools (F12/CMD+ALT+I)
- Use the link "Dynamic import NOK, bug -> here"
- Observe error condition: 404 in Network tab or console

**Related code:**

The underlying reason is that the last script in the document is now scriptB. The loader resolves the executing script tag with the following code (src/client/loader.ts)

```javascript
 // figure out the script element for this current script
  y = doc.querySelectorAll('script');
  for (x = y.length - 1; x >= 0; x--) {
    scriptElm = y[x];
    if (scriptElm.src || scriptElm.hasAttribute('data-resources-url')) {
      break;
    }
  }
```

This is a great polyfill for `Document.currentScript` when defining the scripts statically, but does not work at all for async or dynamically defined script elements.

**Other information:**

Using `baseUrl='/context-a'` in stencil.config.js does not fix the problem. 

If somebody can point me to the relevant code which creates the loader, I would be happy to contribute.

**Comment by msc654** [comment]
The loader is located in src/client/loader.ts. I am also seeing the same issue with ```<script defer src="some-path" />```.

**Comment by psimona** [comment]
With defer it is for the same reason, i.e. async processing breaking the Document.currentScript polyfill.

The fix has to be in the code that generates/packages the loader. Do you know where this is in the code? (Did not have the opportunity to go through the codebase)

**Comment by msc654** [comment]
This is the loader code. https://github.com/ionic-team/stencil/blob/c7c81165c07f91950a795c0e0191d940b323a02e/src/client/loader.ts#L76

**Comment by marinho** [comment]
I'm also experiencing this issue, and the way we found to solve it for now was to add an event handler on `load` of the first script and only when that's triggered we then add the second script. Dirty hack, but handy enough to wait until this bug is fixed on Stencil's side.

**Comment by psimona** [comment]
I haven't had the time to work on the issue in my own time unfortunately. 

I am confident that the workaround described by @marinho is going to work, could not test it though.

The approach does not allow for multiple components to be loaded in parallel (in the network sense). Which still leaves the correct solution open. 

I have been looking for an IE11 polyfill for Document.currentScript polyfill but have only found the approach currently used. This avenue I think is not worth investigating anymore.

In my opinion the best solution by embedding the context, i.e. the parameter baseUrl from the stencil config, in the loader script at build time. This would require:

1. Changing the loader marginally to accept the parameter
2. Changing the code that generates the distribution packet to include the parameter when calling the loader (could not find the related code, please refer to the 

Loader code:
https://github.com/ionic-team/stencil/blob/c7c81165c07f91950a795c0e0191d940b323a02e/src/client/loader.ts#L76)

Code that packages the loader:
? -> could not find
