### ISSUE TITLE
Transpiled es5 chunk is not minifiyed

### ISSUE THREAD

**Issue by nlx-sascha** [ionic-team/stencil#794]
**Stencil version:**

```
 @stencil/core@0.8.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I have a chunk that is already minified and after the transpileToEs5 the file growth from 100k characters to 150k characters.
<img width="1571" alt="bildschirmfoto 2018-05-10 um 20 21 03" src="https://user-images.githubusercontent.com/1643495/39887032-6d220a32-5491-11e8-873b-7a38baa0e27b.png">

**Expected behavior:**
The es5 chunk should be minified

**Steps to reproduce:**
Install swiper (npm i swiper)
Create 2 components that include swiper
Run production build

**Comment by adamdbradley** [comment]
Thanks for filing the issue, should be fixed in the next release. Thanks!
