### ISSUE TITLE
Import of an external type causes compile error in components.d.ts

### ISSUE THREAD

**Issue by apillard** [ionic-team/stencil#797]
**Stencil version:**

```
 @stencil/core@0.8.2
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

npm run build fails with the following error

```
[ ERROR ]  typescript: ...rs/IGEN964/Documents/source/stencil-component-starter-master/src/components.d.ts, line: 31
           Cannot find name 'Layer'.

     L31:    var HTMLMyComponentElement: {
     L32:      prototype: HTMLMyComponentElement;

[09:39.5]  build failed in 3.38 s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-component@0.0.1 build: `stencil build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-component@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Expected behavior:**

Compile should succeed

**Steps to reproduce:**

1. Start with the stencil component starter
2. Modify package.json, to add the following to devDependencies   
```json
"@types/arcgis-js-api": "3.23.0"
```
3. Modify the MyComponent so it looks like the component in "related code"
4. Run npm run build

**Related code:**

```tsx
import { Component, Method } from '@stencil/core';
import Layer from 'esri/layers/layer';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {

  @Method()
  addLayer(newLayer: Layer): void { // TODO trying to use layer type import won't resolve in components.d.ts
    console.log('new layer', newLayer);
  }
}

```

**Other information:**

**Comment by apillard** [comment]
Try this one: https://github.com/apillard/stencil-import-repro

Should be able to clone the repo, npm install, and then npm run build to reproduce.

**Comment by marisaoliva** [comment]
Has this case been resolved? I have the same problem but with Jquery ui, iexit a solution?

**Comment by jthoms1** [comment]
This should no longer throw an error but it will replace the type that is external with an 'any'.  I am currently working on a resolution to this.  Consider each prop as API so really you should be exporting the types from the Component that you wish to use.  More info to come after I have my tests passing on how best to handle the situation replicated in the example repo.
