### ISSUE TITLE
Context properties simplification

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#799]
**Stencil version:**
```
 @stencil/core@0.8.1
```

**I'm submitting a:**
[x] feature request

**Current behavior:**

Context is currently handled using the `Prop()` decorator with a key.

For example, in ionic core `menu.tsx`:

```tsx
@Prop({ context: 'config' }) config!: Config;
@Prop({ context: 'isServer' }) isServer!: boolean;
@Prop({ context: 'enableListener' }) enableListener!: EventListenerEnable;
@Prop({ context: 'window' }) win!: Window;
```

**Proposed behavior:**

Use standard `import` for accessing context information.

```tsx
import { Component, Prop, Context } from '@stencil/core';

render() {
    if (Context.isServer) return;
    ...
}
```

Benefits:
- Easier to use.  Leverages standard bundle chunk logic to load context when needed.
- Automatic strong typing from import.
- Improved type checking for context names and types.
- Reduced size of meta data loaded at startup.  For example: `["config",3,0,0,0,"config"]` is added to `build/app.js` for every component that uses a `config` context property.
- Stencil context could be distinct from ionic core context and other app context vs. sharing the same namespace and potential for collisions.

**Comment by danbucholtz** [comment]
The reason we did it this way was for dependency injection purposes. Basically you can assign a mock to the prop, where as with the import or global it's more difficult to do.

Thanks,
Dan

**Comment by manucorporat** [comment]
This is something we are looking at! in fact I think @jthoms1 is currently looking at it.

I wonder if we could do something like:

```
import { Context } from '@stencil/core';
const { config, window } = Context;
```

With that we could:

- Provide DI (like @danbucholtz pointed out)
- Reduce metadata
- Still provide typing inference


thoughts?
cc @adamdbradley @jgw96

**Comment by manucorporat** [comment]
Also, how about renaming Context to "Global"? I feel it gives a better sense of what it's a "global context".

I have the fear people will use Context for everything as the main pattern for data flow, which would not be a good idea.

**Comment by jthoms1** [comment]
What is the benefit of using context for these purposes when you could just use an import?

config.ts
```ts
export const isServer = (sometest);
```

component-file.ts
```ts
import { Component, Prop } from '@stencil/core';
import { isServer } from '../config';

render() {
    if (isServer) return;
    ...
}
```

**Comment by manucorporat** [comment]
@jthoms1 Dependency Injection.

Basically the same reason, it's not a good idea to use global "window" but instead use:

```
@Prop({context: 'window'}) window: Window;
```

"window" is undefined when running the tests, but that's to some flavour of context we can inject a mock.

**Comment by jthoms1** [comment]
Sure I understand that for window, but what about the cases where you are just trying to get access to a config value like detailed above?

**Comment by cjorasch** [comment]
The name probably depends on the intended purpose.  `Globals` feels a little better than `Context` but it is also not clear if it is better to have a single global root or have multiple root values.  Or even individual values rather than attempting to group them together.  For example:

```tsx
import { Environment, Browser } from '@stencil/core';
const { isServer } = Environment;
const { document, window } = Browser;
```

Another factor impacting naming is trying to avoid conflicts with other existing names so that intellisense can correctly auto import the appropriate source.  For example, `@Element()` overlaps with html `Element`.  This makes it a bit more awkward to export `document` vs. `Browser.document`, for example.

If you are attempting to put everything on a single global then you introduce loading dependencies even if some of the code is not needed.

Strong typing is also highly desirable so if the app has its own globals it would be better to import from something like `MyGlobals` than trying to extend an existing object which would risk collisions and require the extension properties to be cast to a strong type.

### Dependency Injection

With regards to DI I think there would need to be a further flushed out model for it to work well.  The current approach of using component props assumes that all consumers of DI are components and I think this is pretty limiting.  On my project more than 50% of the code is not directly in component files but rather in other services and ts code.  For example, Redux actions, capacitor scripts, utility functions, etc.  In order to effectively do DI it would need to be available from these contexts as well and `import` is the only option in those cases.

I also think the DI approach taken by Angular was one of their biggest design mistakes because it added significant complexity to the development process even though the vast majority of the applications did not actually take advantage of DI.  Writing a service as a simple export is vastly easier than dealing with all of the Angular overhead.  Injecting within constructors did not work well for stand alone utility functions, classes with inheritance, etc.

A good DI approach should be an extension that allows you to use it when you want to but not make coding harder if you are not using it.  If `window` needs to be mocked when running on the server then that can be done with an import rather than requiring the component prop.

**Comment by manucorporat** [comment]
@jthoms1 i guess the same thing, DI...
If my component's state depends somehow in something that can not be mocked, it's a failed pattern.

How do i test that component? can i mock the config dep?

ES is great, i am all in favour of using it, but it does not solve the DI problem.

**Comment by jthoms1** [comment]
Mock the dependency.  Jest has a really good mock system for this exact problem.

**Comment by jthoms1** [comment]
For values that are static this works, but in cases where the application should update based on changes to a global 'context' we need a separate system in place.

**Comment by manucorporat** [comment]
Context is finally going aways in Stencil 1.0, it will still working for backcompatibility reasons, but developers could use normal ESM imports in order to import shared functionality and state across components!

Stencil 1.0 will hit beta in the upcoming weeks!
