### ISSUE TITLE
Providing a "Context" object for components in unit tests 

### ISSUE THREAD

**Issue by DorianGrey** [ionic-team/stencil#802]
**Stencil version:**

```
@stencil/core@0.8.2
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

This a follow-up of https://github.com/ionic-team/stencil-redux/issues/6. After inspecting this further, I've recognized that there is a lack of documentation regarding the `Context` object in tests. The [docs](https://stenciljs.com/docs/context) only mention how to use the global `Context` object for the application, but not for the tests (there is no note about this on the [testing section](https://stenciljs.com/docs/unit-testing/) as well).
I've recognized that a local `Context` object is used to wrap a component for the tests (code [here](https://github.com/ionic-team/stencil/blob/093c42502e4b7fc65d6dbe82582a06d477dedb23/scripts/packages/testing/jest.preprocessor.js#L33)), but that one is not globally available, and thus cannot be modified for a particular purpose.
Suppose it is required to provide this object manually for the components under test, but there are no docs on how to achieve this.

**Expected behavior:**

The repo can be found here: https://github.com/DorianGrey/stencil-playground

**Steps to reproduce:**

- Clone the repository above
- `yarn` for installing dependencies 
- ` yarn test app-profile` will report an error like `Error: Cannot read property 'mapStateToProps' of undefined`, which is caused by the non-existing `Context` object.

**Related code:**
The component takes a `store` object (from `stencil-redux`, which is expected to be part of the `Context` object):
```tsx
@Prop({ context: "store" }) store!: Store;
```
The lifecycle hook that yields an error looks like:
```
componentWillLoad(): void {
  this.store.mapStateToProps(this, (state: any) => {
     return { visitTime: state.visitTime };
  });
 // ...
}
```
Since it's a lifecycle hook that executes early, I cannot even set the `store` property on the `element` before it gets executed. Thus, it seems that the only available option to get around this would be to provide the `Context` object, but it's not clear how.
The related test can be found [here](https://github.com/DorianGrey/stencil-playground/blob/master/src/components/app-profile/app-profile.spec.ts).

**Other information:**

Did not receive any response on the original issue: https://github.com/ionic-team/stencil-redux/issues/6
But considering my most recent inspections, I'd think that this issue isn't related to `stencil-redux` in particular, but more on a general level.

**Comment by goodslav** [comment]
I'm experiencing a similar problem. It looks like the components in my bundles are loading out of order since the new version. Their componentWillLoad() hooks are firing not in the order they are supposed to so my store ends up being undefined cause I set it in the root component's componentWillLoad method.

**Comment by lupiter** [comment]
The only example I can see of ionic writing unit tests for a component with a context is [icon.spec.tsx](https://github.com/ionic-team/ionicons/blob/c9a11ad2a336e15dafdf4551d44911c7cd9c7beb/src/components/icon/icon.spec.ts) which only tests the methods by directly instantiating the component, rather than using render/TestWindow.

**Comment by adamdbradley** [comment]
This is no longer applicable with the latest releases. Thanks
