### ISSUE TITLE
How to use / complie an Angular / Vue / React componet into Sentcil component ?

### ISSUE THREAD

**Issue by lordmos** [ionic-team/stencil#807]
RT

**Comment by jthoms1** [comment]
Not exactly sure what you are trying to accomplish.  Could you please provide a more detailed use case?

**Comment by nesbocaj** [comment]
Stencil components just compile to standard (W3C) custom elements. So correct me if I'm wrong, but I believe what you're asking is how to use Angular, React and Vue components as standard custom elements?

Both Angular ([@angular/elements](https://angular.io/guide/elements)) and Vue ([vue-web-component-wrapper](https://github.com/vuejs/vue-web-component-wrapper)) have official support for doing this by packaging their components as and wrapping them in custom elements.

React however, does not have official support for this, but there exists a third party solution: [react-web-component](https://github.com/WeltN24/react-web-component).
