### ISSUE TITLE
adding element in a <slot /> is not added into the slot

### ISSUE THREAD

**Issue by stevenao** [ionic-team/stencil#810]
**Stencil version:**

```
 @stencil/core@0.9.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
new elements are added outside of the slot:
<div> 
<slot> 
  <div>input a</div> 
  <div>input b</div> 
  <div>input c</div> 
</slot> 
<div> input (new date isoString) </div>
</div>

**Expected behavior:**
<div> 
<slot> 
  <div>input a</div> 
  <div>input b</div> 
  <div>input c</div> 
  <div> input (new date isoString) </div>
</slot> 
</div>

**Steps to reproduce:**

**Related code:**

```tsx
@Component({
  tag: 'my-slot-component',
})
export class MySlotComponent {
render() {
    return ( <div> <slot /> </div>);
}
}

@Component({
  tag: 'my-list',
  shadow: true
})
export class MyList {
  handleInputEvent(event: UIEvent) {
    this.items = [...this.items, new Date().toISOString()];
  }
  @Prop() id: string;
  @Prop({ mutable: true }) items: Array<string> = ['a', 'b', 'c'];
  render() {
    return (
      <my-slot-component>
          {this.items.map((item) =>
            <div>== <input type="text" value={item} onDblClick={(event: UIEvent) => this.handleInputEvent(event)} /></div>
          )}
      </my-slot-component>
    );
  }
}
```

**Other information:**

**Comment by adamdbradley** [comment]
Thanks for the issue! This should be fixed from: https://github.com/ionic-team/stencil/commit/9a36b0c02b94265b6e4da3f6d1b4e64b72407165

Also added your tests here: https://github.com/ionic-team/stencil/commit/2a1553fcde4b92efbbd422cbe3d2fd52765066fe

Thanks!
