### ISSUE TITLE
Q: Re-Rendering of new text inputs added to an array

### ISSUE THREAD

**Issue by stevenao** [ionic-team/stencil#811]
In Stencil:
- new input gets appended 
- value user typed in the existing  text inputs are lost

In Polymer (in a dom-repeat):
- new input gets appended 
- value user typed in the existing text inputs are not lost

I am wondering which one is a more desirable behavior, and what is the principle behind the behavior showing in stencil.

**Comment by jthoms1** [comment]
I am not sure I follow.  Could you provide a some example stencil code?

**Comment by stevenao** [comment]
bump

**Comment by AmitMY** [comment]
That is because stencil does not support 2 way binding, only 1 way, and while the new values are on the inputs, they are not in the array so the next render will reset them
