### ISSUE TITLE
first element of slotted elements will be relocated to the end

### ISSUE THREAD

**Issue by chrkulbe** [ionic-team/stencil#813]
**Stencil version:**
```
 @stencil/core@0.9.1

since
 @stencil/core@0.7.27-3
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Slotted elements won't render in correct order.

**Expected behavior:**
Should be rendered in correct order.

**Related code:**

```tsx
// tk-slotted.tsx
import {Component} from '@stencil/core';

@Component({
  tag: 'tk-slotted'
})

export class TKSlotted {
  render() {
    return <slot></slot>
  }
}
```
```tsx
// tk-text.tsx
import {Component} from '@stencil/core';

@Component({
  tag: 'tk-test'
})

export class TKTest {
  render() {
    return <tk-slotted>
      <input type="text"></input>
      <input type="number"></input>
      <input type="date"></input>
    </tk-slotted>
  }
}
```

**Other information:**
The resulting html looks like following code, but the component order isn't correct.
On the patching/relocation step each element will be moved, but the first element will be insertBefore with null as reference node -> added to the end of the childlist of the parent.
```html
<tk-test class="hydrated">
  <tk-slotted class="hydrated">
    <input type="number">
    <input type="date">
    <input type="text">
  </tk-slotted>
</tk-test>
```

**Comment by silentHoo** [comment]
Same problem here.

**Comment by vercasson** [comment]
I don't think position is guaranteed without using slot names

**Comment by chrkulbe** [comment]
That's not correct. Independent of using named slots they should have the correct order within a slot.
I verified the same issue with named slot also.

**Comment by adamdbradley** [comment]
Thanks for the report. This issue should be fixed from https://github.com/ionic-team/stencil/commit/9a36b0c02b94265b6e4da3f6d1b4e64b72407165

And added a karma test to replicate this issue: https://github.com/ionic-team/stencil/commit/45a99303022d0a04ffc9172886002cb0d5f74f0f

Thanks!
