### ISSUE TITLE
Bundling Error in Dev/Watch mode when add component to second/separate component

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/stencil#815]
**Stencil version:**
```
 @stencil/core@latest
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Create a page/component in an app. Include a component like a stencil-router-link. Do an `npm run dev` and turn on watch mode. Everything should be happy and cool.

Now, create a second component. Add `stencil-router-link` to it. Observe the error in the Stencil code after the dynamic important statement where it tries to find the element constructor within the dynamically imported bundle. Since the `stencil-router-link` is in a separate bundle, it isn't in the dynamically imported bundle and there is an exception.

**Expected behavior:**
I would expect that the watch mode would just keep on truckin'. I am not really sure how to get around this, though. Maybe in development mode, you don't bundle deps up or have a shared chuck? That seems to be the easiest way. Maybe you can see if a tag name or file name is in the a separate bundle and needs to be removed and added to the common/shared chunk? I'm not sure.

**Steps to reproduce:**

```
Create a page/component in an app. Include a component like a stencil-router-link. Do an `npm run dev` and turn on watch mode. Everything should be happy and cool.

Now, create a second component. Add `stencil-router-link` to it. Observe the error in the Stencil code after the dynamic important statement where it tries to find the element constructor within the dynamically imported bundle. Since the `stencil-router-link` is in a separate bundle, it isn't in the dynamically imported bundle and there is an exception.

```

Thanks,
Dan

**Comment by adamdbradley** [comment]
Fixed https://github.com/ionic-team/stencil/commit/ec716339d8912b914e60c5660e1f68a9936939b0
