### ISSUE TITLE
Allow type definitions to be generated without a full build

### ISSUE THREAD

**Issue by dimi-nk** [ionic-team/stencil#816]
I'm submitting a:

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

Current behavior:
The definitions file components.d.ts is only generated after a full build.

Expected behavior:
Directly generate the file without the need for a full build.

Steps to reproduce:

Other information:

The scenario is that I want to add a git pre-commit hook to update components.d.ts. However yarn build does take some time, since it’s compiling everything.

Cloned from #748

**Comment by jthoms1** [comment]
When would this be useful?  The `components.d.ts` file only changes when the api has changed in a component file and for this use case the full build should be done as well.

**Comment by dimi-nk** [comment]
As I said in the ticket, the compilation takes a few seconds which makes tools like the `pre-commit` hook to be slow. My proposal was to generate the definition file from the metadata of the component definition using something like reflection, e.g. field names and types.

**Comment by jthoms1** [comment]
So you mean the purpose is that this is needed because the types are used during dev in your own codebase. Got it. I think this would be useful.  I will leave it open as a future enhancement. Thanks!

**Comment by dimi-nk** [comment]
@jthoms1 cool thanks :)

**Comment by dimi-nk** [comment]
For anyone interested, we use `git-hooks` and have the following script on `pre-push` (I'd prefer `pre-commit` but it takes some time):

```sh
#!/bin/bash

RED='\033[0;31m'
RESET='\033[0m'

yarn build --dev

# adding the file to staging for cases when there's no actual diff
git add src/components.d.ts

# determine if components.d.ts has uncommited changes
git diff-index --quiet HEAD src/components.d.ts
if [ $? -eq 1 ]; then
  echo -e "\n${RED}[ERROR] src/components.d.ts has uncommited changes${RESET}"
  exit 1
fi
```
