### ISSUE TITLE
replaceing childs ends up in incorrect order

### ISSUE THREAD

**Issue by chrkulbe** [ionic-team/stencil#819]
**Stencil version:**

```
 @stencil/core@0.9.2

works until @stencil/core@0.7.27.2
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
wrong child order after child replacement

**Expected behavior:**
correct child order

**Related code:**

```tsx
// tk-slotted.tsx
import {Component} from '@stencil/core';

@Component({
  tag: 'tk-slotted'
})

export class TKSlotted {
  render() {
    return <slot></slot>;
  }
}
```
```tsx
//tk-test.tsx
import {Component, State} from '@stencil/core';

@Component({
  tag: 'tk-test',
  shadow: true
})

export class TKTest {

  @State() state = [
    <input type="text"></input>,
    <span>ABC</span>,
    <input type="number"></input>
  ];

  componentDidLoad() {
    setTimeout(this.addComponent, 2000);
  }

  addComponent = () => {
    this.state = [this.state[0], <input type="date"></input>, this.state[2]];
  };

  render() {
    return <tk-slotted>
      {this.state}
    </tk-slotted>
  }
}
```
```html
<!--before timeout-->
[input type=text]ABC[input type=number]
<!--after timeout-->
[input type=date][input type=text][input type=number]
<!--but should be-->
[input type=text][input type=date][input type=number]
```

**Other information:**
If the span will be replaced with an input the order will be correct after replacement.

**Comment by jthoms1** [comment]
Can you try using the latest version of stencil and verify that this still occurs? 
```
npm install @stencil/core@latest
```

**Comment by chrkulbe** [comment]
With 0.9.7 the behaivior fails also. sorry. nothing changed.

**Comment by Xiphe** [comment]
I observed similar issues, have not took the time to dig into it but in my case it was caused by multiple wrapping components with `slot`s
