### ISSUE TITLE
`globalScript` context doesn't update

### ISSUE THREAD

**Issue by brendensoares** [ionic-team/stencil#821]
**Stencil version:**

```
$ npm list @stencil/core
@stencil/starter@0.0.1 /Users/brenden/xxx/my-app
└── @stencil/core@0.9.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

The `globalScript` `Context` values don't update. 

**Expected behavior:**

The `src/globals/index.ts` `globalScript` should update the `www/build/app/app.core|global.js` output files when it is changed.

**Steps to reproduce:**

1. create new app from starter app [mentioned in docs](https://stenciljs.com/docs/getting-started/)
1. Add context [per the docs](https://stenciljs.com/docs/context)
1. include the `globalVar` value in a component's `render()` so you can see it in the browser
1. `npm run dev`
1. Notice the value in the browser.
1. change the `globalVar` string value in the `src/globals/index.ts` file
1. after rebuild from watched changes, notice the value has not changed.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

The only way to force an update is to move the app to a different directory. I assume this has something to do with path-based file caching somewhere. I even tried removed the text `Context.globalVar` from `src/global/index.ts` completely from the project and clearing the `www/build` path and even `node_modules` (and re-`npm installing`ing). The old values are in the app even though they no longer exist in the code.

This issue is mind blowing. I can't imagine why this is happening and why this hasn't been caught before when I followed the docs completely. I hope I'm not losing my mind here, because I don't know what else to do. HELP.

**Comment by brendensoares** [comment]
Thank you for confirming. Due to time, I was forced to return to Angular for the current project.

Were you able to fix the issue by disabling the cache?

Also, am I wrong in thinking the `Context` via `globalScript` as documented is how you should handle "injection" of "services" that would handle global functionality like session management?

**Comment by kael** [comment]
> Were you able to fix the issue by disabling the cache?

Yes, I'm developing with cache disabled. Having had cache issues, it was not that difficult to find the cause, although it's quite annoying.

> Also, am I wrong in thinking the Context via globalScript as documented is how you should handle "injection" of "services" that would handle global functionality like session management?

No, you are correct, `Context` is used for globally accessed variables, like data, session, etc. See the [doc](https://stenciljs.com/docs/context) and a [blog post (perhaps deprecated)](https://medium.com/@gilfink/creating-shared-state-in-stencil-3beac77477e8).

**Comment by kael** [comment]
Actually, now I recall that bug, and it's definitely a crazy one. To bypass that bug when editing `Context` I had to reboot my laptop, otherwise new code edition were never taken into account. So that looks like a real bug, though.

Thinking more about Context and Services, you might be able to still use caching while editing code related to `Context` services, but it'd require to write your Context code once (so that you come across the bug once, then you can edit your services related code as Web Workers without problem).

This is how it could be done (I don't guarantee it's a best practice, just the way I wrote it) :

- src/global/index.ts
```ts
import service from './service';
declare var Context: any;
Context.service = service;
```

- src/global/service.ts
```ts
  export class Service {
  _worker:Worker;
  get worker():Worker { return this._worker; }
  set worker(worker:Worker) {
    worker.onmessage = this.onmessage.bind(this);
    this._worker = worker;
  }

  constructor() {
    this.worker = new Worker('../worker/service.js');
  }

  async start() {
    return await true; // Start services here
  }

  async onmessage({ data }) {}

  async postMessage(service, method, params, channel = new MessageChannel()) {
    console.log('Worker Service postMessage', { service, method, params, channel });
    return await new Promise((ok) => {
      this.worker.postMessage({ service, method, params }, [channel.port2]);
      channel.port1.onmessage = ({ data }) => ok(data);
    });
  }

  /* Public API organised as a tree for my conveniency */

  db = {
    getItems: async (itemId) => await this.postMessage('db', 'getItems', [itemId]),
  };
  api = {
    fetchItem: async(itemId) => await fetch(`http://example.org/item/${itemId}`),
  };
  session = {
    ...
  };

}

const service = new Service();
(async () => {
  try { service.start(); }
  catch(error) { console.error('Default Service Start', { error }); }
})();
console.log('Default started', { service });

export default (() => service)();

```

- src/components/mycomponent/mycomponent.tsx
```tsx
export class MyComponent {
  ...
  @Prop({ context: 'service'}) service:any // 'any' or imported interface

  async clickData(itemId) {
    const data = await this.service.api.fetchItem(itemId);
  }

}

```

- src/worker/lib/session.js  (arbitrary folder, not a Stencil convention)
```js
class Session {}
```

- src/worker/service.js
```js

importScripts('lib/session.js'); // from src/worker/lib/session.js & available at http://host/worker/lib/session.js

console.log('Worker Service', { Session });

...

onmessage = async ({ origin, ports: [port], data }) => {
  console.log('Worker Service OnMessage', { origin, port, data });
  ...
  port.postMessage('Response');
}
```

Well, that's enough for a boilerplate. Don't forget to manually copy `src/worker` in `ẁww/` when editing the code or after building a prod version.

Enough of digression. :zipper_mouth_face:

**Comment by dimi-nk** [comment]
duplicate from #716
