### ISSUE TITLE
Component style information lost when deriving from base class

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#823]
**Stencil version:**
```
 @stencil/core@0.9.5
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
If a component has a base class then the css styles for the component get assigned to the base class rather than to the component.

For example, if you define a component as follows:

```tsx
abstract class ComponentBase {}

@Component({
    tag: 'my-component',
    styleUrl: 'my-component.scss'
})
export class MyComponent extends ComponentBase {
    @Element() el!: HTMLStencilElement;
    // --- more code ---
}
```

After running the build process the following code is generated in the `www` directory:

```js
class ComponentBase {
    static get is() { return "my-component"; }
    static get properties() { return {
        "el": {
            "elementRef": true
        }
        // --- other properties are here ---
    }; }
    static get style() { return ".my-component {... styles are here ...}"; }
}

class MyComponent extends ComponentBase {
    // --- component code ---

    static get is() { return "my-component"; }
    static get properties() { return {
        "el": {
            "elementRef": true
        }
        // --- other properties are here ---
    }; }
    static get style() { return "/**style-placeholder:my-component:**/"; }
}
```

Specific issues are:
- Base class incorrectly gets static properties relating to the derived class.
- MyComponent does not get any style information so it is not rendered with styles.

**Comment by colshacol** [comment]
I am seeing something similar with the basic stencil component starter kit.

```js
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'copart-app-bar',
  styleUrl: 'copart-app-bar.css',
  shadow: true
})
export class AppBar {

  @Prop() first: string;
  @Prop() last: string;

  render() {
    return (
      <div>
        Hello, World! Im {this.first} {this.last}
      </div>
    );
  }
}
```

```css
copart-app-bar {
  display: flex;
  background: blue;
}
```

<img width="1233" alt="screen shot 2018-06-08 at 2 57 50 am" src="https://user-images.githubusercontent.com/19484365/41146072-c91e1a00-6ac7-11e8-97fa-64ac49874746.png">

And here is my stencil.config.js:

```js
const postcss = require('@stencil/postcss');
const autoprefixer = require('autoprefixer');

exports.config = {
  namespace: 'copart',
  outputTargets:[
    {
      type: 'dist'
    },
    {
      type: 'www'
    }
  ],
  plugins: [
    postcss({
      plugins: [autoprefixer()]
    })
  ]
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}
```

```js
"devDependencies": {
    "@stencil/core": "^0.9.7",
    "@stencil/dev-server": "^0.0.18",
    "@stencil/postcss": "^0.0.4",
    "@stencil/utils": "^0.0.4",
    "@types/jest": "^21.1.1",
    "autoprefixer": "^8.6.1",
    "jest": "^21.2.1"
  },
```

I added these plugins to try to fix the issue, in case the plugins strike you as a potential suspect. :+1:

**Comment by jthoms1** [comment]
@cjorasch I would be surprised if this worked.  We never intended for components to work with inheritance.  I am going to add something in the compiler to prevent this situation from occuring.  I think discussion around this could occur within the currently opened issue #172.

@colshacol The issue you are seeing is because shadow is set to true.  If you changed the styles to be the following it should work.
```
:host {
  display: flex;
  background: blue;
}
```
