### ISSUE TITLE
Proposal: deprecate host prop in @Component

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#825]
```ts
@Component({
  tag: 'ion-item',
  host: {
    theme: 'item'
  }
});
```

Stencil's early days added the `host` prop to Component decorator as a required feature for ionic, but today it's not longer a requirement, i propose to remove/deprecate it:

- Reduce stencil runtime
- Reduce API surface

As long with this, I would also like to propose the removal of "color" as built-in prop.

**Comment by adamdbradley** [comment]
Yeah with the css variable updates I think you're right.

**Comment by adamdbradley** [comment]
Agreed. We'll be able to remove most, except for `mode`. Mode is actually something that could be used by developers, but you're right it's unlikely that most will. However, it is very important for it to work with ionic, but I do want to ensure that `mode` isn't an "ionic" thing, it's still a feature that useful and a large part of the core of stencil.

**Comment by manucorporat** [comment]
The host property will be completely removed in Stencil 1.0 becoming an error!

Stencil 1.0 will hit beta in the upcoming weeks!
