### ISSUE TITLE
@Element() property returns always false when calling element.hasAttributes()

### ISSUE THREAD

**Issue by fermmm** [ionic-team/stencil#828]
**Stencil version:**

```
@stencil/core@0.9.4
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
@Element() element
element.hasAttributes() returns always false also when receiving attributes:

```
@Component({
    tag: 'my-test',
    shadow: true
})
export class Test {

    @Element() element: HTMLStencilElement;
    @Prop() disabled: boolean;

    render() {
        console.log(this.element.hasAttributes());  // This returns false
        console.log(this.element.attributes.length);  // This returns 0
        return (
            <div></div>
        );
    }
}
```
I'm calling the component like this:
``` <my-test disabled={true}></my-test> ```

**Expected behavior:**
Attributes should be present in this.element.attributes

If this bug is fixed will be possible to make a wrapper component that forwards all props from the parent to the child without knowing and writing all props one by one. I could do it similar to this:
<child-component {...this.element.attributes} />

**Comment by jthoms1** [comment]
Change your prop definition to be
```
@Prop({reflectToAttr: true}) disabled: boolean;
```

By default all values set in JSX are passed as props.  If you want the data to be reflected as an attribute you need to explicitly state that.

Thanks!
