### ISSUE TITLE
Discussion around Context

### ISSUE THREAD

**Issue by yordis** [ionic-team/stencil#832]
From the Slack conversation

### `ubi` from Slack

`adam` mate, you are one of the core contributors and from the Polymer team, I would really love to hear your comments on this but probably this is more related to how Ionic sells the product and push for it, but I am really worry about it.
We can’t figure out how to properly connect the Redux store to the components in React ecosystem without hurting the underline architecture and make depending the whole application from Redux and I am 100% sure that people will code the same way `unless` somebody coach them and teach them how to properly think about it.

### `adam` from Slack
`ubi` that’s a good question, I guess better docs, diagrams and tutorials. What have you been trying or what do you suggest?

### `ubi` from Slack
`adam` I would remove the feature and go more plain, if people want a singleton pattern then create a single Javascript object that you point to.

At the end it comes down to actually train your community. Redux/React shouldn’t carry any blame from the community for the bad practices but at the same time as a OSS contributor I see my duty to train the community (specially on `stencil-redux` in this case) of how to properly code.

But it is hard that way to be honest.

I would go drastically but I don’t see that happening, maybe stencil figure out how to delegate that `Context` thing to something else, I believe that this is an architecture pattern that the components do not need to implement.

Maybe this could help

- A better doc on the `Context` feature with `Do` and `Don't`
- A better documentation on `stencil-redux` or any other package that uses `Context` with `Do` and `Don't`

### `justin-tmk` from Slack

My unsolicited 2 cents on Context, I think it would make great sense as a plug-in, like the router. Over time people could build their own, full frameworks out of plugins if they wanted or better ways of working with frameworks.

Keep the core pure. It's a slippery slope, however, because I think basic things like data binding are core.

**Comment by adamdbradley** [comment]
Thank you for your feedback. We're still working away on what we feel should be the public api or not, and context is still up in the air since `@stencil/state-tunnel` has been developed. https://www.npmjs.com/package/@stencil/state-tunnel
