### ISSUE TITLE
core 0.9.7 w/ router 0.2.0: app.core.js:2247 TypeError: Failed to resolve module specifier "@stencil/state-tunnel"

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#833]
**Stencil version:**
```
 @stencil/core@0.9.7
@stencil/router@0.2.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Updated to ´0.9.7´ from `0.9.4` and to router `0.2.0` from `0.1.7` getting this in the console:
<img width="1270" alt="bildschirmfoto 2018-05-31 um 20 30 45" src="https://user-images.githubusercontent.com/6666636/40801269-d3cfb41e-6512-11e8-84bf-e81e62a966aa.png">

Anything I need to adopt?

This is in `app-load.js`:
<img width="401" alt="bildschirmfoto 2018-05-31 um 20 35 10" src="https://user-images.githubusercontent.com/6666636/40801319-f2ce1338-6512-11e8-9cc9-09136b6861e4.png">

That second import looks strange?

In the build console:
```
[ WARN  ]  '@stencil/state-tunnel' is imported by node_modules/@stencil/router/dist/collection/global/active-router.js,
           but could not be resolved – treating it as an external dependency

```

Put this on slack as well:
https://stencil-worldwide.slack.com/archives/C789G3X1R/p1527791643000262

**Expected behavior:**
Compiles and runs without trouble as before ;-)

**Comment by jthoms1** [comment]
Looks like the router has state-tunnel as a devDependency when it should just be a dependency.  Releasing a new version.

**Comment by jthoms1** [comment]
This issue was moved to ionic-team/stencil-router#51
