### ISSUE TITLE
how to pass a return value of a function from html <script> to the .tsx component?

### ISSUE THREAD

**Issue by NiveditaDeveloper** [ionic-team/stencil#834]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by jthoms1** [comment]
Closing issue for inadequate information.
