### ISSUE TITLE
overlays.d.ts createOverlay "Type 'keyof B' does not satisfy the constraint 'string'"

### ISSUE THREAD

**Issue by daniell0gda** [ionic-team/stencil#835]
**Stencil version:**

```
@stencil/core@0.9.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
tslint throws 
```
[21:22.2]  changed file: carbonation-profile.tsx
[21:22.2]  rebuild, app, dev mode, started ...
[21:22.2]  compile started ...
[21:27.2]  compile finished in 5.01 s

[ ERROR ]  typescript: C:/Users/Daniel/Documents/projekty/browarManagerWeb/web-version/node_modules/@ionic/core/dist/types/utils/overlays.d.ts:9:82
           Type 'keyof B' does not satisfy the constraint 'string'. Type 'string | number | symbol' is not assignable
           to type 'string'. Type 'number' is not assignable to type 'string'.

      L8:  };
      L9:  ction createOverlay<T extends HTMLIonOverlayElement & Requires<keyof B>, B>(element: T, opts: B): Promise<T>;
     L10:  export declare function dismissOverlay(data: any, role: string | undefined, overlays: OverlayMap, id: number): Promise<void>;
```

**Steps to reproduce:**
All I did is update all basic stencil dependencies as latest.

```
   "dependencies": {
        "@ionic/core": "4.0.0-alpha.7",
        "@stencil/core": "0.9.7",
        "@types/lodash": "^4.14.109",
        "lodash": "^4.17.10",
        "micromatch": "^3.1.10"
    },
    "devDependencies": {
        "@stencil/dev-server": "latest",
        "@stencil/sass": "0.0.5",
        "@stencil/utils": "latest",
        "@types/jest": "^23.0.0",
        "jest": "^23.1.0"
    }
```

**Comment by codinronan** [comment]
@daniell0gda this issue is actually in `@ionic/core`, here is the corresponding PR: 

https://github.com/ionic-team/ionic/pull/14553

When they merge that and do a release, this will just work again.

**Comment by daniell0gda** [comment]
Got it, thanks. I will close this issue afterwards.

**Comment by miguelyoobic95** [comment]
As a temporary workaround you can remove ` & Requires<keyof B>` on line 9 and it should work.

**Comment by jthoms1** [comment]
Closing this as a duplicate considering it is covered in Ionic and there is a corresponding open PR. ionic-team/ionic#14553
