### ISSUE TITLE
How to get object through stenciljs routes

### ISSUE THREAD

**Issue by kchetans** [ionic-team/stencil#836]
I was trying to pass data through stencils routes

e.g...
    this.history.push(`/detail`,{detail_data:docs});
    when I check their interface I found 
       push: (path: string | LocationSegments, state?: any) => void;
      so my object is state how would I access these object to /detail page
      I tried
      Prop() detail_data: object;
      but it's not working

**Comment by jthoms1** [comment]
This issue was moved to ionic-team/stencil-router#53
