### ISSUE TITLE
DOMAttributes for onAnimation Attributes

### ISSUE THREAD

**Issue by lupiter** [ionic-team/stencil#838]
**Stencil version:**

```
 @stencil/core@0.9.7 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Loving Stencil. I'm trying to get some sweet animations and having trouble.

It seems it's not possible to capture the `onAnimationXXX` events in Stencil in Chrome (66.0.3359.181 on Mac), Safari (11.1), or Firefox (60.0.2 on Mac).

**Expected behaviour:**
These events _should_ be able to be captured with Stencil. There are DOMAttribute definitions for these properties, but the major browsers currently only support prefixed versions.

Stencil could copy the `onAnimationXXX` events as `onWebkitAnimationXXX` events, or the DOMAttributes interface definition could be expanded to add the prefixed properties. Either would solve my problem. Unless you have a polyfill to recommend?

**Steps to reproduce:**
A template like the following will not print to the console.
```
<div onAnimationStart={() => console.log("start animation")}></div>
```

If I manually edit the generated javascript and replace `onAnimationStart` with `onWebkitAnimationStart` the event handlers are called in all three browsers.

**Other information:**
[Fiddle using jQuery](https://jsfiddle.net/sircathywise/xpvt214o/199243/) to show two events so you can try removing onWebkitAnimationStart in different browsers and see what happens.

**Comment by jthoms1** [comment]
I don't think we would want to create a situation where we polyfill the animation events.  I think we can add JSX attribute definitions for the `webkitAnimation` type events.
