### ISSUE TITLE
srcDir can not contain "test" folder

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#846]
**Stencil version:**

```
 @stencil/core@^0.9.4
(also with 0.9.7, have not tested <0.9.4)
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
Given I have a stencil component in `test/components/f-oo/f-oo.tsx`
And I use the following stencil config:
```js
exports.config = {
  srcDir: `test`,
};
```

Then my `f-oo` component is not found by the compiler resulting in the following stats:
```json
{
  "compiler": {
    "name": "@stencil/core",
    "version": "0.9.7"
  },
  "app": {
    "namespace": "App",
    "fsNamespace": "app",
    "components": 0,
    "entries": 0,
    "bundles": 0
  },
  "options": {
    "minifyJs": true,
    "minifyCss": true,
    "hashFileNames": true,
    "hashedFileNameLength": 8,
    "buildEs5": true
  },
  "components": [],
  "entries": [],
  "sourceGraph": {},
  "collections": []
}
```

**Expected behavior:**
I expect the `f-oo`  component to be picked up

**Steps to reproduce:**

1. Checkout the [stencil-app-starter](https://github.com/ionic-team/stencil-app-starter)
2. rename the src folder to `test`
3. add `srcFolder: 'test'` option in `stencil.config.js` and point it to the renamed src folder
4. also add `suppressTypeScriptErrors: true` and `globalStyle: 'test/global/app.css'` to the config because otherwise the compiler will fail
5. run `$(npm bin)/stencil build --stats`
6. inspect `www/build` and see no component files

**Other information:**

 - also happens with `srcDir: 'nested/test'` or `srcDir: 'nested/test/foo'`
 - does not happen with `srcDir: 'nested/testr'` or `srcDir: 'nested/ftest'`

**Comment by jthoms1** [comment]
I think this is a documentation issue. You can overwrite the excluded files by setting the following in your config.  By default the value is set to: `['**/test/**', '**/*.spec.*']`

```
  excludeSrc: []
```

**Comment by jthoms1** [comment]
Closed with ionic-team/stencil-site commit. https://github.com/ionic-team/stencil-site/commit/0d985125f21750ff671a6d7e82db1e1520202d15

**Comment by Xiphe** [comment]
Hey @jthoms1 Thanks for the clarification.
