### ISSUE TITLE
Uncaught Error: Cannot find module "./components"

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#852]
**Stencil version:**

stencil/core >= v0.9.0

**I'm submitting a:**
[X] bug report
[X] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I have upgraded stencil/core in my library https://github.com/peterpeterparker/web-photo-filter and I notice that since stencil/core v0.9.0 I'm not able anymore to include it in my Ionic v3 app

No error at build time but at run time (ionic serve) I face the following error

> vendor.js:156742 Uncaught Error: Cannot find module "./components"
>     at Object.<anonymous> (vendor.js:156742)
>     at __webpack_require__ (bootstrap eac1c930851fef2145d3:54)
>     at Object.<anonymous> (vendor.js:156703)
>     at __webpack_require__ (bootstrap eac1c930851fef2145d3:54)
>     at Object.322 (main.ts:5)
>     at __webpack_require__ (bootstrap eac1c930851fef2145d3:54)
>     at Object.302 (resources.ts:591)
>     at __webpack_require__ (bootstrap eac1c930851fef2145d3:54)
>     at webpackJsonpCallback (bootstrap eac1c930851fef2145d3:25)
>     at main.js:1

**Steps to reproduce:**

1. In a Ionic v3 app
2. Install the last version of my component "npm install web-photo-filter --save"
3. Follow README to include it in your app
4. ionic serve

**Note:**

I could confirm that with stencil/core till v0.8.2 I do not face the problem

Also when switching to v0.9.0 I have updated the package.json with main and module keys

**Comment by codinronan** [comment]
@peterpeterparker So we meet again!

Yep I ran into this problem too, it's because they changed the way the modules are resolved. IIRC the next release of Stencil has a fix for this. In the meantime you can do this:

https://github.com/engineerapart/stencil-lift/blob/master/src/components/index.ts

Just add an `index.ts` file at the root of the `components` folder that exports the components inside it. This causes an `index.js` file (note the extension) that allows the folder contents to be resolved by webpack-based bundlers.

**Comment by jthoms1** [comment]
I believe the release of 0.9.8 should be happening today.  I will verify this after release and update the issue.

**Comment by peterpeterparker** [comment]
@jthoms1 have you give a try with 0.9.8 or 0.9.9?

**Comment by peterpeterparker** [comment]
@jthoms1 this is solved, looks like I don't face any error at runtime anymore but, a new error occurs now at later stage, the component isn't rendered anymore in the Ionic app with Stencil v0.9.11

https://github.com/ionic-team/stencil/issues/852
