### ISSUE TITLE
Duplicate class names outputted in pre-render

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil#853]
Stencil 0.8.1.

When using pre-rendering, a component is output with duplicated class names:

<img width="613" alt="screen shot 2018-06-15 at 9 23 14 am" src="https://user-images.githubusercontent.com/11214/41475031-3fafe03e-7083-11e8-99ad-674ee5c15775.png">

The code in the render that created this:

```javascript
  render() {
    return (
      <div class="site-header container">

        <stencil-route-link url="/" class="logo-link">
          <div class="logo"></div>
          <b class="version">Beta</b>
        </stencil-route-link>
```

**Comment by codinronan** [comment]
Can confirm I see this with pure SSR as well.
