### ISSUE TITLE
Jest test fail on latest build

### ISSUE THREAD

**Issue by MiguelC1990** [ionic-team/stencil#854]
**Stencil version:**

```
 @stencil/core@0.9.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Tests fail with the following error
```
Test Suites: 0 of 6 total
Tests:       0 total
Snapshots:   0 total
Time:        5s/Users/miguelc/NUIgnite/nu-navigation/node_modules/jest-worker/build/worker.js:200
        throw new TypeError('Unexpected response from worker: ' + response[0]);
        ^

TypeError: Unexpected response from worker: undefined
    at exports.default._receive (/Users/miguelc/NUIgnite/nu-navigation/node_modules/jest-worker/build/worker.js:200:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
**Expected behavior:**
Test should Pass

**Related code:**
Jest Configuration:
Version: 23.1.0
```tsx
"jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!@material)"
    ],
    "transform": {
      "^.+\\.js$": "babel-jest",
      "^.+\\.(ts|tsx)$": "<rootDir>/node_modules/@stencil/core/testing/jest.preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(tsx?|jsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json",
      "jsx"
    ]
  }
```

**Other information:**

From digging around, it seems the issue comes from the worker-farm introduced in version 0.9.6 and more specifically the `process.send` function

**Comment by Tallyb** [comment]
Workarounds: 
jest --runInBand will avoid the error (since no child processes). 
However, you may then run into node memory issue. Can be workarounded by using node --max_old_space_size=8096 jest

Started on 0.9.6

**Comment by adamdbradley** [comment]
Should be fixed now: https://github.com/ionic-team/stencil/commit/f678c8c039efc18f901d027024697315615448c2 
Thanks for filing the issue
