### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mailok** [ionic-team/stencil#855]
Sorry to use the Issues, but I did not find another place where they answer me this:

Is Stencil ready for production?
Are there projects in production?
If I use Stencil, I will have some advantages over Polymer 3 / LitElement?, What are they?
Are there suits components made with stencil?

**Comment by jthoms1** [comment]
Sorry these questions are best answered in the slack channel.

https://stencil-worldwide.herokuapp.com/

**Comment by mailok** [comment]
@jthoms1 this is Stencil on Slack, but I can not enter the site is prohibited for Cuba, Slack not allowed.

**Comment by jthoms1** [comment]
ugh that's no good.

Is Stencil ready for production?
Are there projects in production?
- We have built Ionic v4 with stencil.  We are using Stencil on a number of internal applications at Ionic as well as the https://www.stenciljs.com, https://ionicons.com, and the next release of https://ionicframework.com/docs/.

If I use Stencil, I will have some advantages over Polymer 3 / LitElement?, What are they?
- We think the advantages are more in the approach that Stencil takes.  Stencil components are built with JSX and our components provide a different dev workflow than Polymer. Some will prefer it, but some will not.  We think that it is a much more streamlined and simpler approach.

Are there suits components made with stencil?
- I assume you are asking if there are any collections of components that are available for usage.  All of Ionic 4 are web components that are built with stenciljs. There is also a community contributed list that can be found here: https://github.com/mappmechanic/awesome-stenciljs#list-of-awesome-components-made-using-stenciljs

**Comment by mailok** [comment]
Thank you very much @jthoms1

**Comment by codinronan** [comment]
@mailok 

**Is Stencil ready for production?**
I am rebuilding our corporate site in Stencil. I would not be doing so if I didn't think it was ready to take on the task :) Stencil still has some rough edges but I am building a series of packages that help to alleviate some of that.

**Polymer/Lit**
Stencil is alot more lightweight. One of the reasons I picked Stencil over other frameworks is that I am tired of delivering 3mb of JS to my users with the excuse that "it gives them a great experience." Our full site will end up being about 200kb of JS. For the entire site + webapp. I mean... damn.

@jthoms1 👍 🎉  😃
