### ISSUE TITLE
hydration process never closes 

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#856]
**Stencil version:**

```
 @stencil/core@0.9.7 (introduced in 0.9.6)
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
I use code similar to the [node-js-http-ssr-server](https://stenciljs.com/docs/server-side-rendering/#node-js-http-ssr-server) example but without wrapping it in a express server. (And run it in AWS lambda)

Since v0.9.6, `renderer.hydrate({ html: html })` resolves but causes the process to not close by itself. 

Probably due to background workers introduces in https://github.com/ionic-team/stencil/commit/5fa1b53

**Expected behavior:**

I would expect a node script to close automatically once hydation work is done.
Workers should only stay active in dev/watch mode

**Steps to reproduce:**

-> https://github.com/Xiphe/stencil-issue-856

**Related code:**

probably https://github.com/ionic-team/stencil/commit/5fa1b53

**Other information:**

Id happily contribute a PR once the bug is confirmed and we have a strategy on how to solve it.

**Comment by Xiphe** [comment]
added example repo (https://github.com/Xiphe/stencil-issue-856)

**Comment by adamdbradley** [comment]
Thanks for filing the issue and creating a repo! Should be fixed in the next release, thanks!
