### ISSUE TITLE
Interface 'HostElement' incorrectly extends interface 'HTMLElement'

### ISSUE THREAD

**Issue by joeltan** [ionic-team/stencil#858]
**Stencil version:**

```
@stencil/core v0.9.4
```

**I'm submitting a:**

[x] bug report
[  ] feature request
[  ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Error Message:**
```
typescript: node_modules/@stencil/core/dist/declarations/component.d.ts, line: 192
           Interface 'HostElement' incorrectly extends interface 'HTMLElement'.
           Types of property 'componentOnReady' are incompatible. Type '() =>
           Promise<HostElement>' is not assignable to type '() =>
https://guides.github.com/features/mastering-markdown/
           Promise<this>'. Type 'Promise<HostElement>' is not assignable to
           type 'Promise<this>'. Type 'HostElement' is not assignable to type
           'this'.

L192:  export interface HostElement extends HTMLElement {
L193:      connectedCallback?: () => void;

[26:48.1]  build failed, watching for changes... in 3.14
           s
```
And the web server page **http://localhost:3333** display:
**Initializing First Build...**
and a spinner keep spinning.

**Steps to reproduce:**
- I installed StencilJS by following the instruction provided on Stencil website.
- My current node version is **V10.4.1**
- After running the command: **npm start** immediately shows the error message as stated above.

**Comment by jthoms1** [comment]
Thanks for opening the issue.  I have updated the `stencil-app-starter` to use the latest version of stencil which fixes this issue.

If you would like to fix your local install just run the following command.
```
npm install @stencil/core@latest --save-exact
```

**Comment by joeltan** [comment]
Thanks for the quick response! It works perfectly now.
