### ISSUE TITLE
[0.9.8] Build fails with global styles if 'stats' target is enabled

### ISSUE THREAD

**Issue by codinronan** [ionic-team/stencil#865]
**Stencil version:**

```
 @stencil/core@0.9.8
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
Building with the 'stats' target enabled causes the global styles build to fail.

**Expected behavior:**
No failure :)

**Steps to reproduce:**
Executing build command:
```bash
NODE_ENV=production stencil build --ssr --es5
```

I've pasted my stencil config below. I traced the bug, in `generateGlobalStyles` it attempts to concat the output target (www, dist, stats) build dir with the root dir, but in the case of stats, there is no build dir, so `path` throws an exception because the input is `undefined`. 

![image](https://user-images.githubusercontent.com/13020457/41608695-a527fb3a-73ae-11e8-9563-c178dcb75f9e.png)

![image](https://user-images.githubusercontent.com/13020457/41608743-cf45b40c-73ae-11e8-91d3-79e51cea1d8f.png)

I've disabled the stats target for now, not a big deal, I use it to track changes in build size but we're not enforcing it right now.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

My Stencil config:

```js
exports.config = {
  namespace: 'rmx',
  srcDir: 'src',
  logLevel: 'info',
  flags: { prerender: true },
  buildEs5: true,
  buildStats: true,
  enableCache: false,
  hashFileNames: true,
  hashedFileNameLength: 12,
  globalStyle: 'src/styles/global.scss',
  globalScript: 'src/global/index.ts',
  copy: [
    { src: 'assets-svg/*.svg', dest: 'build/rmx/svg/' },
    { src: 'locales', dest: 'locales' }
  ],
  plugins: [
    sass({
      injectGlobalPaths: [ ], // Inject @ top of every scss file. SASS variables, mixins & functions only.
      includePaths: [
        'src/styles/',
      ]
    }),
  ],
  outputTargets: [
    {
      type: 'www',
      console: console,
      logLevel: 'debug',
      serviceWorker: {
        swSrc: 'src/sw.js',
        globPatterns: [
          '**/*.{js,css,json,html,ico,png,svg,jpg,jpeg}'
        ],
        globIgnores: [
          '**/build/rmx/svg/*',
          '**/index.html'
        ],
      },
    },
    {
      type: 'stats',
      file: 'stats.json'
    }
  ],
}
```

**Comment by jthoms1** [comment]
This issue is resolved in release `0.9.9`. Thanks!
