### ISSUE TITLE
Auto <slot> when not render function is defined

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#868]
Stencil includes an extensive polyfill for `<slot>` in components without native shadow-dom enabled or if it's not available by the user agent.

Since it's expensive, we are recommending to avoid doing this:

```ts
render() {
   return <slot/>
}
```

since the content is projected anyway, it we don't need the <slot> logic to kick in.

In Shadow-dom, this is not true though, leading to an inconsistency. The explicit `<slot/>` is required.

This causes several problems:

- Scoped components need to include the `<slot/>` forcing the slot runtime to be included when it's not needed
- Scope and shadow-dom behaviour is inconsistent
- Browsers do not supporting native shadow-dom will require the slot polyfill logic when not needed.
- Components like `ion-card` will force stencil to include the `slot` polyfill when it's not needed.

## Proposal

Instead of documenting the differences between shadow-dom and scoped regarding the `<slot>` and suggesting different recommendation, we should make component to project content by default, unless a render function is provided.

```
@Component({
  tag: 'ion-card',
  styleUrls: {
    ios: 'card.ios.scss',
    md: 'card.md.scss'
  },
  scoped: true
})
export class Card {}
```

## Conclusion

There are many performance advantages of this default behaviour, but imo, it also fits better the internal model of components.

Custom Element project content by default is how non-shadow-dom components work.

**Comment by adamdbradley** [comment]
Going to hold this off for a while and can discuss again when the next major release.
