### ISSUE TITLE
newly inserted, pre-hydrated DOM node gets double-wrapped content.

### ISSUE THREAD

**Issue by Xiphe** [ionic-team/stencil#871]
**Stencil version:**

```
 @stencil/core@0.9.7
```

**I'm submitting a:**

[x] bug report
[x] feature request

Not sure whats the intended behaviour here :)

**Current behavior:**

Given I have a running stencil app
Using a `my-button` component rendering to

```html
<my-button class="hydrated"><button>My content</button></my-button>
```

When I deep-clone this node and append it to the DOM
Then it gets this stucture

```html
<my-button class="hydrated"><button><button>My content</button></button></my-button>
```

**Expected behavior:**

I would expect the component to pick up existing child nodes similar to the way ssr hydration works.

**Steps to reproduce:**

1. Start a stencil app
2. select a stencil component in the dev tools
3. run `$0.parentElement.appendChild($0.cloneNode(true))`

**Related code:**

`¯\_(ツ)_/¯`

**Other information:**

The whole thing seems quite complicated to me because stencil needs to know if a node has been rendered by the component itself or is `slot`-content.

I find it interesting, that a similar effect of this also happens when the cloned element and it's children contain `data-ssrc` data.

this is probably also related to https://github.com/ionic-team/stencil/issues/781

Once you finished triaging this issue I'd happily help finding a solution.

Stumbled upon this while trying to build a bridge between stencil/web-component and react: https://github.com/patternsonio/web-component-to-react

**Comment by DennisJamin** [comment]
This seems to be very related to an issue that we are currently facing. I've created the following project to reproduce: https://github.com/DennisJamin/stenciljs-component-rerendering-issue

**Comment by jthoms1** [comment]
@Xiphe Can I assume this is not using shadow dom?
