### ISSUE TITLE
Stencil app disabled in spite of browser support.

### ISSUE THREAD

**Issue by ninachaubal** [ionic-team/stencil#872]
I'm testing out the [starter app](https://github.com/ionic-team/stencil-starter) on Firefox v60.0.2. The "Current Browser's Support:" section shows support for all the listed features, but the app is still disabled.
<img width="1680" alt="screen shot 2018-06-20 at 7 17 45 pm" src="https://user-images.githubusercontent.com/826592/41694329-a29a3f8e-74be-11e8-8148-4d6e642d8bfd.png">

Perhaps there are missing requirements not listed on that page? Or maybe a mismatch with the user agent?

**Comment by adamdbradley** [comment]
Fixed the es5 disabled html page logic to show the correct info. Good news is custom elements within Firefox isn't too far away! Thanks
