### ISSUE TITLE
Select element inside a slot causing issues in IE11

### ISSUE THREAD

**Issue by DMartMD** [ionic-team/stencil#874]
**Stencil version:**

```
 @stencil/core@0.9.11
```

**I'm submitting a:**

[x] bug report

**Current behavior:**

Placing a select element into a slot is not working as expected in IE11.

**Expected behavior:**

Select element's slot behavior matching other elements in IE11.

**Steps to reproduce:**

Slot a select and view it in IE11. See screenshots:

Chrome
![image](https://user-images.githubusercontent.com/20773263/41773774-328a1812-75eb-11e8-8993-0c90b1acc978.png)

IE11
![image](https://user-images.githubusercontent.com/20773263/41773842-722c7154-75eb-11e8-97eb-aa90e1c21d44.png)

**Related code:**

```tsx
// component code
import { Component } from '@stencil/core';

@Component({
  tag: 'my-component',
  shadow: true
})
export class MyComponent {

  render() {
    return (
      <div>
        <p>Before Slot</p>
        <slot></slot>
        <p>After Slot</p>
      </div>
    );
  }
}
```

```html
// html
<my-component>
  <select></select>
</my-component>
```

**Comment by cary-smith** [comment]
I have just run into this issue as well. Can kill the entire page in IE11.

**Comment by SymbiantChris** [comment]
I am on stencil version 0.15.2
using shadow: false;

In IE11, attempting to slot a select element is giving me an error with the below:

    // https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove
    // and it's polyfilled in es5 builds
    $remove: function(node) {
      return node.remove();
    }

The error is "Invalid Argument".


I have worked around the error by replacing select elements with another stencil web component that renders a select - this works fine, and can also be slotted into other components.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
