### ISSUE TITLE
Issue with `.stencil` folder in `0.9.11`

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#876]
**Stencil version:**
```
 @stencil/core@0.9.11
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Getting
```
unhandledRejection ENOENT: no such file or directory, stat
           '/Users/matthias/Documents/Projekte/bitflower/Case OS/Prototype/v0.2/caseos-ui/.stencil' Error: ENOENT: no
           such file or directory, stat '/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui/.stencil'
``` 
for missing `.stencil` folder after update from `0.9.7` to `0.9.11`

Result of `npm run dev --debug` gave @jgw96 enough insights to point me to the `enableCache` property of `stencil.config.js` which was set to `false`.

**Expected behavior:**
After removing the prop from `stencil.config.js` the build went smooth.

**Steps to reproduce:**
Add `enableCache: false` to `stencil.config.js` and run `npm run dev` with version `0.9.11`. It either works when set to `true` or when REMOVED completely.

Slack conversation:
https://stencil-worldwide.slack.com/archives/C789G3X1R/p1529679518000353

Thanks @jgw96!

**Comment by adamdbradley** [comment]
Cool thanks for the issue, should be fixed in the next release, thanks
