### ISSUE TITLE
Live Reload keeps breaking and makes development impossible

### ISSUE THREAD

**Issue by r0skar** [ionic-team/stencil#878]
**Stencil version:**

```
 @stencil/core@0.9.7
 @stencil/router: latest
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
I followed the [instructions](https://stenciljs.com/docs/getting-started/). When I start the app, with `yarn start` everything works just fine. However, as soon as I start editing files (doesnt matter which ones) in VS Code, I keep getting following errors:

`[ ERROR ]  Missing Export: ../../../../__HDD/__persistent/dev/stencil-app/entry:app-root.stencil-route.stencil-route`

This doesnt happen every time, but about 50% of the time. Waiting a little and than simply hitting Save again, sometimes solves the problem and sometimes it does not. Its really weird.

**Expected behavior:**
I expect Live Reloading to work without breaking.

**Steps to reproduce:**

1. Clone the Start App @ https://github.com/ionic-team/stencil-app-starter
2. Run `yarn install` and start the app with `yarn start`.
3. Open `app-root.tsx`, make an edit and save it.

**Other information:**
The issue happens a lot less frequently when using a text editor (Kate) instead of VS Code. However it still does happen from time to time.

**Comment by adamdbradley** [comment]
This should be fixed in the 0.10.0 prerelease. Thanks for reporting the issue!
