### ISSUE TITLE
[Feature Request] Customize parameters of UglifyJS

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/stencil#889]
**Stencil version:**

```
@stencil/core@0.10.0-9
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Im using the `mapbox-gl@0.45.0` library. When I'm running stencil in dev mode, everything works fine. But if I build in production it brakes with logging this error multiple times: `Uncaught ReferenceError: n is not defined`
I found out, that happens when compression in UglifyJS (uglify-es in stencils case) is enabled: https://github.com/mapbox/mapbox-gl-js/issues/4359
As temporary workaround I replace
`const opts = { output: {}, compress: {}, mangle: true };` with
`const opts = { output: {}, compress: { comparisons: false }, mangle: true };`
in the `node_modules/@stencil` folder (there are 3 occurences).

**Expected behavior:**
It would be really nice if there was a way to customize the uglify/minifyJS parameters with a custom config.

**Steps to reproduce:**
- Import mapbox-gl (https://www.npmjs.com/package/mapbox-gl)
- Create a map
- Build with `npm run build`

**Comment by adamdbradley** [comment]
Uglify has been known to change these parameters between versions, causing many issues for users and build tools, which is why we do not expose them. Additionally, we do not property rename user code. If you have any other questions please feel free to hit us up on stencil slack. Thanks
