### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by yordis** [ionic-team/stencil#891]
There is a lot of properties that are not documented on the website like `enableListener` `queue`, I notice the come form the Context because I am learning from Ionic code base but to be honest I am guessing at this point.

Knowing and learning about it will be beneficial specially `queue` which it seems to try to mitigate the layout thrashing which is good.

**Comment by adamdbradley** [comment]
Thank you for opening the issue, and yes we will be improving the docs. But would also like to ask the community to assist where possible. Happy to answer any questions on stencil slack, thanks.

**Comment by yordis** [comment]
@adamdbradley more than happy to assist and contribute but this is low level API that cores would know.
 #927 gave you a list of what we could improve but we need your support on this one or I will have to understand all the Stencil implementation which I am pretty sure that it is not simple task to do.
