### ISSUE TITLE
Integration with Angular Cli

### ISSUE THREAD

**Issue by Gafilipoie** [ionic-team/stencil#893]
**Stencil version:**

```
 @stencil/core@<0.7.24>
```

**I'm submitting a:**
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I'm trying to add 2 stencil projects through npm to angular.
None of them are working, but if I just let 1, then that one works just fine.

**Expected behavior:**
SHOULD I add 2 stencil projects through npm to angular,
THEN both of them should render their respective components.

**Steps to reproduce:**
Adding a stencil project through npm and inserting the code block:
```
    ...,
    {
        "glob": "**/*",
        "input": "../node_modules/stencil-project/dist",
        "output": "./"
    }
```
into the assets array in the angular-cli.json then adding 
```
import 'stencil-project';
```
to app.modules. It works.
Then add the second stencil project to angular.cli.json:
```
    ...,
    {
        "glob": "**/*",
        "input": "../node_modules/stencil-project/dist",
        "output": "./"
    },
    {
        "glob": "**/*",
        "input": "../node_modules/stencil-project-2/dist",
        "output": "./"
    }
```
then adding 
```
import 'stencil-project';
import 'stencil-project-2';
```
to app.modules. It breaks.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
This should be fixed in recent versions of Stencil. Additionally, we've recently updated our framework intergration docs: https://stenciljs.com/docs/framework-integration docs

**Comment by adamdbradley** [comment]
The slack channel or forum is a better place to ask questions, thanks.
