### ISSUE TITLE
Node children of component showing even without a <slot>

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#905]
**Stencil version:**
```
 @stencil/core@0.10.0-11
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
In browser not supporting shadow dom (?) and only running on ES5 (?) the children of a component are still shown even though there is not `<slot>` in the template.

**Expected behavior:**
Children of a custom components never show up when there is no `<slot>`.

**Steps to reproduce:**
https://github.com/bitflower/stencil-slot-test

**Comment by jthoms1** [comment]
Unfortunately if the browser does not support shadow then children cannot be hidden. This is just a function of the browser acting as expected. Thanks!

**Comment by bitflower** [comment]
Thanks for the verification Josh,

If anybody is looking for a fallback solution I have used this
```typescript
    const CAN_SHADOW: boolean = !!(document.head.attachShadow || (document.head as any).createShadowRoot);
    if (CAN_SHADOW === false) {
      while (this.el.lastChild) {
        this.el.removeChild(this.el.lastChild);
      }
    }
```
to prevent the children of the component to be rendered.

Or would this even be something for `@stencil/core`?
