### ISSUE TITLE
can't use same event name

### ISSUE THREAD

**Issue by ahadortiz** [ionic-team/stencil#906]
**Stencil version:**

```
 @stencil/core@0.7.24
```

I want to use 'change' or 'click' for events of my component.
But error occurs when I use these 'reserved' names.
Can't I use these names?

**Comment by jthoms1** [comment]
Can you provide a code example?

**Comment by ahadortiz** [comment]
Here is the codes.

`@Component({
  tag: 'cwc-multiselect',
  styleUrl: 'cwc-multiselect.scss'
})
export class CwcMultiselect {
  @Event() change: EventEmitter;
  ...
}

// on a new page
@Component({
  tag: 'multiselect-page',
  styleUrl: 'multiselect-page.scss'
})
export class MultiselectPage {
 handleChange = () => {
   console.log('change is called');
 }
  render() {
    return (<cwc-multiselect onChange={this.handleChange} />);
  }
}
`
