### ISSUE TITLE
Missing pop() function in RouterHistory

### ISSUE THREAD

**Issue by gusterwoei-veltra** [ionic-team/stencil#912]
**Stencil version:**
```
"@stencil/core": "^0.9.11",
"@stencil/router": "^0.2.2",
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
In Stencil documentation, there's a line in router section:
`this.history.pop('/home', {});`

**Expected behavior:**
`pop()` function found

**Steps to reproduce:**
But in actual implementation, no such function is found. Error is thrown in console
-->

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by jthoms1** [comment]
Updated docs.
