### ISSUE TITLE
@Prop() HTML attribute case

### ISSUE THREAD

**Issue by brendensoares** [ionic-team/stencil#918]
Given a component with `@Prop() propA: any`:
- `<comp-a propa="x" />` does not work.
- `<comp-a propA="x" />` does work.

Context: A server side script is filtering my HTML and downcasing all tags and attributes.

[HTML is case-insensitive](http://w3c.github.io/html-reference/documents.html#case-insensitivity) and both the above examples should work.

I am just now seeing that [props must use snake case](https://stenciljs.com/docs/decorators#prop). Is this issue the reason for that? It's unfortunate that you have to treat HTML attributes differently in textual HTML vs JSX.

**Comment by adamdbradley** [comment]
The reason attributes use snake case is for the exact reasons you described. When you're using `propA` then it's trying to apply the element property. If you're using `prop-a` then it's trying to apply the element attribute. With all things considered we decided to go with the the snake case. Thanks.
