### ISSUE TITLE
[Feature Request] globals option

### ISSUE THREAD

**Issue by ardatan** [ionic-team/stencil#920]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

An option in `stencil.config.js` for rollup globals.
https://rollupjs.org/guide/en#output-globals-g-globals

**Comment by jthoms1** [comment]
Could you please use the issue template and provide more details on what you are asking for?  Thanks!

**Comment by jthoms1** [comment]
Yes I can add this.

**Comment by jthoms1** [comment]
Commit 9f969a6b0fa0b8d3f899984ed42b15198e67f8a7 fixes this issue.
