### ISSUE TITLE
[Bug] livereloading not working when base url is set

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/stencil#921]
**Stencil version:**

```
@stencil/core@0.10.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I have an existing page where I integrated a stencil component for one page. This is working great, StencilJS is awesome!
But I wanted to load my assets from my original page, which is reachable at `https://staging.<domain>.com/`. So I set a `<base href="https://staging.<domain>.com/">` tag in my head. The assets are loading now, but livereload doesn't work anymore.

I found this iframe which src-attribute is set to `/~dev-server`. Stencil now tries to connect to `https://staging.<domain>.com/~dev-server` which isn't working of course. When I change the src of the iframe to the absolute URL `http://localhost:3333/~dev-server` everything is working.

**Expected behavior:**
You should be able to set a base href without breaking live reload.
I think you can achieve this with setting an absolute URL on your injected iframe.

**Steps to reproduce:**
- Create a new component
```
git clone https://github.com/ionic-team/stencil-component-starter.git my-component
cd my-component
git remote rm origin
npm i
npm start
```
- Replace your index.html with the one in `Related code` and save it
- Livereload should now be broken
- Manually set the URL of your iframe before the closing body tag to `http://localhost:3333/~dev-server` (check port)
- Livereload should be working until you change your index.html again.

**Related code:**

```html
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
  <title>Stencil Component Starter</title>
  <script src="/build/mycomponent.js"></script>
  
  <base href="https://www.google.com/">

</head>

<body>

  <img src="/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png">
  <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>

</body>

</html>
```

**Comment by adamdbradley** [comment]
Gotcha, yeah I guess it wouldn't hurt to use an absolute path for the dev server. We'll make the updates, thanks
