### ISSUE TITLE
Asset URLs for background-images resolve incorrecly in consuming app

### ISSUE THREAD

**Issue by Nudelsieb** [ionic-team/stencil#923]
**Stencil version:**
```
 @stencil/core@0.10.2
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Adding a background image either in the component's (s)css or in global/app.css breaks when the component is used in another app. When running the dev-server the image is resolved correctly.

**Expected behavior:**
I would expect the component to resolve the image relatively inside the dist package that gets later used inside the consuming app (by using `npm i` or `npm link`).

**Steps to reproduce:**

**Related code:**
Example from global/app.css
```css
background-image: url('/assets/img/background.svg');
```

Mitigation:
```css
background-image: url('/assets/img/background.svg'), url('/public/assets/img/background.svg') ;
```
The second URL would resolve in a dev environment inside an Electron app. So for every use case one would have to add a different URL to cover all those cases. There should be a way to just add a relative URL and the component always finds that. However, adding a relative URL would have StencilJS compile the absolute path to that image, which is very confusing.
Example:
```css
background-image: url('assets/img/background.svg');
```
ends up in compiled form as:
```css
background-image: url(src/global/assets/img/background.svg);
```
The latter path does not exist and would break the path resolution.

I believe this issue is not just related to background images. I think all assets are resolved incorrectly when compiled and consumed in another app.

**Other information:**

**Comment by jedihacks** [comment]
+1 @Nudelsieb 

This may be a hint - For us, I see that the scss styles are translated from 

```
@include media-breakpoint-down(md) {
      background-image: url('./assets/bg-hero-icons-md.jpg');
    }
```
to

```background-image: url(src/pages/app-opportunities/assets/bg-hero-mountain.jpg);```

after running `npm run build` for a production build.  The same doesn't seem to happen in dev. 
 You can access the [repo here ](https://github.com/openforge/OPENFORGE.IO) if you want to compare.  

We had an inelegant workaround by using "/assets/bg-hero-icons.jpg" in our SCSS for the parent element only, and then doing a 

```
@Listen('window:resize')
  componentDidLoad() {
    this.handleImage();
  }

  @Listen('window:resize')
  handleImage() {
    let element;
    try {
      element = document.querySelector('.about .hero');
      element.style.backgroundImage = `url('/assets/bg-hero-icons.jpg')`;
    } catch (e) {
      console.log('app-about-header undefined', e);
    }

    if (window.innerWidth < 576) {
      // small
      element.style.backgroundImage = `url('/assets/bg-hero-icons-sm.jpg')`;
    } else if (window.innerWidth < 992) {
      // medium
      element.style.backgroundImage = `url('/assets/bg-hero-icons-md.jpg')`;
    } else {
      // large
      element.style.backgroundImage = `url('/assets/bg-hero-icons.jpg')`;
    }
  }
```

Not sure if this helps.
