### ISSUE TITLE
capture attribute supports strings, but stencil doesn't

### ISSUE THREAD

**Issue by comixtrip** [ionic-team/stencil#925]
https://github.com/ionic-team/stencil/blob/534050e89d902bfdd4414336c0293f7266a57934/src/declarations/jsx.ts#L316

In the page linked in the comment on this line, the capture supports string like _user_ and _environment_. Stencil does not compile if I use a string there. Will this be fixed and is there a workaround until then?

**Comment by comixtrip** [comment]
Workaround until fix:
`` // @ts-ignore ``
`` capture="environment"``

**Comment by adamdbradley** [comment]
Thanks for the report, should be fixed in the next release, thanks
