### ISSUE TITLE
Can't import more than a single component in an Ionic v3 app

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#926]
**Stencil version:**
v0.8.6

**I'm submitting a:**
[X] bug report

**Current behavior:**
I want to use two of my web components build with Stencil in my Ionic v3 app. Therefore I import them both in `app.module.ts` respectively

    import 'web-photo-filter';
    import 'web-social-share';

Unfortunately, when I do so, the first component (at least) doesn't work anymore. If I remove the import of the second component then the first one works again like expected

**Expected behavior:**
I would like to be able to import more than just one single component

**Steps to reproduce:**
You could import both components in an Ionic app. I described in the README how to include them, for example https://github.com/fluster/web-photo-filter

**Other information:**

I have an unresolved open issue, maybe it's the same problem? https://github.com/ionic-team/stencil/issues/873

**Comment by peterpeterparker** [comment]
@adamdbradley tried, unfortunately it doesn't solve the problem

Side note:  after upgrading, while building I get the warning that I should remove the `browser` attribute from `package.json`. If I do so it breaks later at build time of my Ionic app

> Error: ./node_modules/web-social-share/dist/collection/index.js
> Module not found: Error: Can't resolve './components' in '/Users/me/Documents/projects/project/node_modules/web-social-share/dist/collection'
> resolve './components' in '/Users/me/Documents/projects/project/node_modules/web-social-share/dist/collection'
>   using description file: /Users/me/Documents/projects/project/node_modules/web-social-share/package.json (relative path: ./dist/collection)
>     Field 'browser' doesn't contain a valid alias configuration
>   after using description file: /Users/me/Documents/projects/project/node_modules/web-social-share/package.json (relative path: ./dist/collection)
>     using description file: /Users/me/Documents/projects/project/node_modules/web-social-share/package.json (relative path: ./dist/collection/components)
>       no extension
>         Field 'browser' doesn't contain a valid alias configuration
>         /Users/me/Documents/projects/project/node_modules/web-social-share/dist/collection/components is not a file
>       .ts
> 

Setting `browser: dist/index.js` solves the build error

**Comment by adamdbradley** [comment]
Before we dig too far into this, I'd recommend first getting up on the latest version. If there's an issue with updating to the latest, that'd be high priority to fix first.

**Comment by peterpeterparker** [comment]
@adamdbradley oki doki

I have then commented https://github.com/ionic-team/stencil/issues/873 in order to provide sample repos and details about how to reproduce the problem of upgrading Stencil in a component and using it in an Ionic v3 app

In brief, the component upgraded to last Stencil lib

        https://github.com/fluster/web-photo-filter/tree/stencil-upgrade

The Ionic v3 sample app

      https://github.com/peterpeterparker/ionic-v3-stencil

**Comment by adamdbradley** [comment]
Ok thanks, we'll love #873 open then.
