### ISSUE TITLE
docs: missing docs for various features

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#927]
So after a long time I came back to skim stencil docs, and again got confused by undocumented behaviors. This issue is a report of things that I didn't find answer to within the docs or just got confused by missing explanation :)

### `@Prop`  options

- What does `connect` option do? https://github.com/ionic-team/stencil/blob/bcc579ae9ad40e0a5737d31832141185e57fbf7a/src/declarations/decorators.ts#L30
  - related: what is this doing  `@Prop({ connect: 'ion-menu-controller' }) lazyMenuCtrl: Lazy<MenuController>;
`? 
- `reflectToAttr: true` how will casing work here ? ( I assume `camelCase` -> `dash-case` )
- where should be reactions to prop change executed ? within method decorated by `@Watch` or within `componentWillUpdate` LC hook?
- add [`context`](https://github.com/ionic-team/stencil/blob/bcc579ae9ad40e0a5737d31832141185e57fbf7a/src/declarations/decorators.ts#L29) docs to prop + reference to `Context` guide

### `@Component()` options

- how does `styleUrls` object resolution work ?

```ts
@Component({
  tag: 'ion-something',
  // this will be loaded by default
  styleUrl: 'something.scss',
  // how does following work ?
  styleUrls: {
    ios: 'something.ios.scss',
    md: 'something.md.scss',
    wp: 'something.wp.scss'
  }
})
```

### Special Class methods

- document  `hostData` from [style-guide chapter ](https://stenciljs.com/docs/style-guide#high-level-example-commented-)

```ts
  /**
   * 11. hostData() function
   * Used to dynamically set host element attributes.
   * Should be placed directly above render()
   */
  hostData() {
    return {
      attribute: 'navigation',
      side: this.isRightSide ? 'right' : 'left',
      type: this.type,
      class: {
        'something-is-animating': this.isAnimating
      }
    };
  }
```

### ShadowDOM

- what will happen in non nativeShadow DOM browsers if component uses `this.el.shadowRoot.querySelector()` for getting data imperatively within stencil component? Will it be transformed in runtime as fallback with CSS or it will throw and error and user is responsible to handle this on his own

**Expected behavior:**
- document all public API and guides mentioned above

related: https://github.com/ionic-team/stencil/issues/891

**Comment by adamdbradley** [comment]
Any assistance with improving the docs would be appreciated. The repo can be found here: https://github.com/ionic-team/stencil-site

**Comment by Hotell** [comment]
I would love to contribute to the docs, but how could I, when I don't have answers to all questions that I've asked? 🤔😶

**Comment by jlarmstrongiv** [comment]
For those coming after me wondering how `styleUrls` work, I found this [blogpost](https://veamospues.wordpress.com/2018/02/20/setting-context-mode-on-stenciljs/) to be helpful.

**Comment by jlarmstrongiv** [comment]
Some [more](https://github.com/ionic-team/stencil-site/issues/28#issuecomment-330868438) [information](https://github.com/ionic-team/stencil/blob/373e58ca6d880003f442705ffcdf6d0fef02df65/src/declarations/app-global.ts#L56) on PropOptions for `context`.  Couldn’t find anything on PropOptions for `attr` and `connect` though.

**Comment by manucorporat** [comment]
Context and connect were not documented for good reason, in stencil one are finally deprecated!!
