### ISSUE TITLE
Dev server ignores --root

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#928]
**Stencil version:**

```
 @stencil/core@0.10.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
stencil build --dev --watch --serve --root ./www2/
Ignores `--root`, still serving `'./'`

**Expected behavior:**
Serves `'./www2/'`

**Steps to reproduce:**
Try `--root`

**Comment by adamdbradley** [comment]
Thanks for the report, should be fixed up in the next release, thanks

**Comment by kraftwer1** [comment]
@adamdbradley thanks for fixing - but unfortunately, it still ignores `--root ./www2/`
