### ISSUE TITLE
@Listen decorator not working

### ISSUE THREAD

**Issue by IagoLast** [ionic-team/stencil#929]
**Stencil version:**

```
 @stencil/core@0.9.11
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
@Listen tag is not working as expected to me, the method is not being executed.

**Expected behavior:**
The @Listen decorator should force a method to be called when an event happens.

**Steps to reproduce:**
I just created a naive app to test stencil, the app has the following components:
```
src/components/app-search/
├── app-search.css
├── app-search.tsx
├── player-list
│   ├── list-item
│   ├── player-list.css
│   └── player-list.tsx
├── search-box
│   ├── search-box.css
│   └── search-box.tsx
└── search-panel
    ├── search-panel.css
    └── search-panel.tsx
```
The search panel goes like this:

```tsx
export class SearchPanel {

  @Event() updateFilters: EventEmitter;

  render() {
    // ...
  }

  _search() {
    const filters = {
//     ...
    };
    this.updateFilters.emit(filters);
  }
}
```

While the player list has the following code thats never execuded
```tsx

  @Listen('updateFilters')
  onFiltersUpdated(event: CustomEvent) {
    const filters = event.detail;
    const positions = [];
    for (const key in filters.positions) {
      if (filters.positions[key]) {
        positions.push(key);
      }
    }
    this._vmPlayers = this._players.filter(player => player.name.toLowerCase().includes(filters.name.toLowerCase()));
    this._vmPlayers = this._vmPlayers.filter(player => positions.indexOf(player.position.toLowerCase()) >= 0);
  }
}
```

**Other information:**
Im importing everything ok and its being compiled, if I manually listen to the event it works fine.

```js
componentWillLoad() {
  document.body.addEventListener('updateFilters', this.onFiltersUpdated.bind(this));
}
```

The component hierarchy is the following, maybe its related...

```html
 <div>
        <search-panel></search-panel>
        <search-box></search-box>
        <player-list></player-list>
</div>
```

Regards.

**Comment by adamdbradley** [comment]
It looks like all of the components are siblings, but when you manually add the event listener it's getting put on `body`.
