### ISSUE TITLE
ESM Module References Unavailable File

### ISSUE THREAD

**Issue by alexlafroscia** [ionic-team/stencil#930]
**Stencil version:**

```
 @stencil/core@0.10.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Trying to import a package using ESM through WebPack, I'm running into an issue.

In the `dist` after running `stencil build` the graph of files references a module that doesn't exist.

`dist/esm/index.js` imports `../collection/index.js`
`../collection/index.js` import `./components`
`./components` has no `index.js` file, and so the build is unable to complete.

**Expected behavior:**
I would expect that the `components` directory has an `index.js` inside it that itself imports the modules found within the `components` directory, and for the build not to break.

**Steps to reproduce:**

If you clone [this repo](https://github.com/alexlafroscia/ember-cli-stencil/tree/fix-stencil-compiler-update) (specifically checked out to the `fix-stencil-compiler-update` branch) and then run the following:

```bash
yarn install
cd packages/demo-components
yarn build
```

you should be able to see the same issue that I am.

**Comment by alexlafroscia** [comment]
I checked out a different version of `@stencil/core` (`0.9.1`) and am having the same problem...

**Comment by alexlafroscia** [comment]
Updated to the recent `0.10.9` release, this is still a problem.

**Comment by jthoms1** [comment]
@adamdbradley any thoughts on this?  I have seen the same issue with the router.

**Comment by jthoms1** [comment]
Keeping this as a documentation issue. @alexlafroscia You mentioned on twitter that this did work.  Is that correct?

**Comment by manucorporat** [comment]
T
