### ISSUE TITLE
Jsdom version

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#931]
**Stencil version:**

```
 @stencil/core@0.10.4
```

**I'm submitting a:**

[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
jsdom is currently fixed to version 11.5.1 on stencil. 
This prevents from using newer functions introduced in later versions of jsdom. specifically in my case that was getRootNode. 

**Expected behavior:**
Make jsdom version relaxed (i.e. use ^) or make it a peer dependency.

**Comment by adamdbradley** [comment]
When we last updated jsdom it had some regressions, so it's best that we locked it in. Additionally, the web standards shouldn't be changing so drastically and adding new APIs that we feel safer to control versions we know work well. Would you be able to test out that latest version of jsom and make sure it works and prerenderers without issues? thanks

**Comment by Tallyb** [comment]
testing with 11.11.0 seems to work fine. The current version (11.5.1) is dated back to Nov 2017...

**Comment by Tallyb** [comment]
Time to  move on... 11.12 is there (with a great addition!)
