### ISSUE TITLE
Stencil fails to resolve typescript paths

### ISSUE THREAD

**Issue by Fagl4** [ionic-team/stencil#933]
**Stencil version:**

```
 @stencil/core@0.10.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Stencil fails to resolve the paths, warns  the modules could not be imported and that will treat them external dependencies

**Expected behavior:**

Stencil resolves the paths based on tsconfig.json

**Steps to reproduce:**

Add a paths config on tsconfig and import it at any typescript file

**Related code:**

```json
"baseUrl": ".",
"paths": {
      "app/*": ["src/app/*"],
      "modules/*": ["src/app/modules/*"],
      "shared/*": ["src/app/shared/*"]
    }
```

```tsx
// insert any relevant code here
import {fetchAllSeries} from "shared/store/actions";
```

*Results in*
```
build warn
           'shared/store' is imported by
           src/app/modules/serie/g365-serie-list/g365-serie-list.js, but could
           not be resolved – treating it as an external dependency

```

**Other information:**

VS code and Webstorm both recognize and provide autocompletion for the paths

**Comment by jthoms1** [comment]
Do you mind creating an example project that exhibits this behavior?  I could take a look at resolving the reported error at that point.  Thank you!
