### ISSUE TITLE
File name hash missing for dynamic imports

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#934]
**Stencil version:**
```
 @stencil/core@0.10.7
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
Javascript code that is imported using dynamic imports does not get revision numbers in production builds.

For example, if a dynamic module is in the file `my-dynamic.ts` and used from another file as follows:

```tsx
const { myDynamic } = await import('./my-dynamic');
```

Then a production build generates the following file:

```
build/app/my-dynamic.js
```

In this case the file name does not include the content hash so cached copies of the code might not get updated if the source file is changed.  In the above example, if I change `my-dynamic.ts` and deploy the app again, then users will not necessarily get the changes to the file.

This also impacts `ionic/core`.  The production build directory contains several non-versioned files including `input-shims.js`, `ios-transition.js`, etc.  If Ionic changes the code in `input-shims` and the app is deployed then users may not get the updated copy of the code.

**Comment by adamdbradley** [comment]
@jthoms1 is this something rollup can do for us? Or will we have to create a typescript transform for this?

**Comment by jthoms1** [comment]
I think this could be accomplished with Rollup.  I would kind of assume that it did this anyway,  it could be from a missed configuration option.  Either way I would consider this a bug that we should investigate.

**Comment by jthoms1** [comment]
Do we have an example project that uses dynamic imports?  I just updated rollup and would like to test to see if this was fixed in the upgrade.

**Comment by cjorasch** [comment]
You can use any project that uses ionic core.  Do a production build and look in the `www/build/app` outputs.  If you see non versioned files for `input-shims.js` and `ios-transition.js` then the problem still exists.

**Comment by joewoodhouse** [comment]
Is this still in progress?

**Comment by manucorporat** [comment]
This was already fixed in both master and core-refactor, thanks to improvements in rollup!
