### ISSUE TITLE
Stencil 0.10 dev server with child directory

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#935]
**Stencil version:**
```
 @stencil/core@0.10.7
```

**I'm submitting a:**
[x] bug report

**Current behavior:**

We are building an app that runs from a domain directory.  For example: `www.mydomain.com/mydir`.

With Stencil 0.9 and `stencil-dev-server` we were able to build using the following settings:

```
// stencil.config.js
exports.config = {
    outputTargets: [
        {
            type: 'www',
            dir: 'www/mydir',
            baseUrl: '/mydir'
        }
    ]
};

// index.html
<script src="/mydir/build/app.js"></script>
```

This configuration supported the ability to do development in the dev environment and to have the application work when deployed to the production server.

**Changed behavior with Stencil 0.10**

When upgrading to Stencil 0.10 the configuration no longer works in the development environment.

When starting the app with:

```
stencil build --dev --watch --serve
```

The www output works as before

```
www/mydir/build.app.js
```

But running the app results in an error:

```
GET http://localhost:3333/mydir/build/app.js 404 (Not Found)
```

It looks like the integrated dev server is serving relative to `mydir`.  If I make a request to `http://localhost:3333/build/app.js` then the file is served correctly.

Unfortunately I can not change the `index.html` path to the javascript file because it needs to be rooted (to support routes resolving correctly).

Maybe there is some other setting to configure the dev server but I could not find anything documented in the release notes.

**Comment by adamdbradley** [comment]
Thanks for the report, should be fixed up from this fix: https://github.com/ionic-team/stencil/commit/29e25a464324a6f7d0c204d82afbb51d199a74ba thanks
