### ISSUE TITLE
Document doesn't have proper information Can I make any contribution in this ?

### ISSUE THREAD

**Issue by LalitKushwah** [ionic-team/stencil#937]
In the official document of the stenciljs which is available at  https://stenciljs.com/docs. I found that there is something lacking in provided information. So how can I contribute in that?

I am sorry if this the wrong place if this is the case please suggest me the right one.

**Comment by kael** [comment]
That's the [repo](https://github.com/ionic-team/stencil-site) to which you should send a pull request with your modification.

**Comment by adamdbradley** [comment]
Thanks @kael 

@LalitKushwah yes the stencil site is here https://github.com/ionic-team/stencil-site and we happily accept PRs. Thanks!

**Comment by LalitKushwah** [comment]
I have contributed to stencil and PR has been approved :)
