### ISSUE TITLE
Single file component for stencil

### ISSUE THREAD

**Issue by stalniy** [ionic-team/stencil#939]
**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Expected behavior:**
It'd be nice to use something like vue-loader, to build stencil components in a single file component

**Comment by adamdbradley** [comment]
Thank you for the feature request, but at this time we're not planning any refactors to how stencil components are built.

Additionally, if you'd like to put styles directly in the component file can you use the `styles` property in the `@Component` decorator. If you were to do that, everything about the component is in one file. Thanks for using stencil!

**Comment by stalniy** [comment]
I don't suggest to refactor how you write components. Basically I just wanted to understand whether Stencil will use something like this future.

Also I could create a stencil-loader for webpack similar to Vue ones
