### ISSUE TITLE
1.0 Roadmap?

### ISSUE THREAD

**Issue by ryan-edge-ck** [ionic-team/stencil#94]
I realize that this library has just been made public, but is there any roadmap for a 1.0 release?

**Comment by jgw96** [comment]
Hey! Good question. So we are hard at work right now and some members of the team are currently in europe, but once things settle down a bit we should definitely put together a 1.0 milestone (:

**Comment by obedm503** [comment]
This might be a good place for a suggestion. please provide an alternative to jsx. I noticed that @mlynch mentioned using lit-html in the polymer summit talk, but since stencil does async dom manipulation, a stencil specific alternative might be better. I guess it's also possible to use hyperx during compilation to convert to virtual dom, `h` calls.

my point is that a stencil component could look like this
```ts
import { Component, Prop, State, html } from '@stencil/core';
// or
import { html } from 'lit-html';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.scss'
})
export class MyComponent {
  // Indicate that name should be a property on our new component
  @Prop() first: string;

  @Prop() last: string;

  @State() isVisible: boolean = true;

  render() {
    return html`
      <p>
        Hello, my name is ${this.first} ${this.last}
      </p>`;
  }
}
```

**Comment by mg1075** [comment]
Please provide alternatives to JSX along with examples of those alternatives.

> ...inside the render function...this is kind of where we feel things are moving we compute the next view basically using JSX but in theory we could use template literals or anything in here...

From _Using Web Components in Ionic (Polymer Summit 2017)_
https://youtu.be/UfD-k7aHkQE?t=930

**Comment by adamdbradley** [comment]
We'll be actively working on improving stencil while porting over ionic to use it. But largely what you see today is the extent of what Stencil will do. We'd like to keep it small and focused, but need to dog food it a bit more. Thanks.

As for lit-html, that is something we'd like to investigate more as it becomes production ready.
