### ISSUE TITLE
ionic-issue-bot closes issues after 1 month of "inactivity"

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#942]
**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The ionic-issue-bot closes issues after 1 month of "inactivity".
Just because nobody had time to look into an issue, it doesn't mean it can be closed.

**Expected behavior:**
The ionic-issue-bot closes issues after 1 year of "inactivity".

**Comment by adamdbradley** [comment]
Sorry but we're a small team and it's becomes difficult to manage hundreds of issues which may have already been fixed. Also, we accept PRs that fix issues. Thanks.
