### ISSUE TITLE
StencilJS polyfill dynamic loader 

### ISSUE THREAD

**Issue by Tonyhliu** [ionic-team/stencil#943]
**Stencil version:**

```
 @stencil/core@0.10.1<version>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When integrating my Stencil web component into my project, the stencil polyfills dynamic loader seem to be loading polyfills that already exist

**Expected behavior:**

Stencil should know what the pre-existing polyfills are and not load them if they exist

**Comment by adamdbradley** [comment]
Thank you for opening the issue. To help us debug this further, would you be able to provide a way to replicate this? What browser? Which polyfills? Thanks
