### ISSUE TITLE
`this` converted to `undefined`

### ISSUE THREAD

**Issue by ardatan** [ionic-team/stencil#945]
In some UMD bundles, this reference is used for window, but rollup replaces this with undefined, but this can be changed by using options.context which is not available in stencil.config.
Is there any chance to add an option for context?
rollup/rollup#851

#842 Previous issue was closed.

**Comment by jthoms1** [comment]
Can you create a repo that shows the issue then I can use that as a test for adding exposing context? Not against it just wanted to make sure it works correctly.  Thanks!

**Comment by ardatan** [comment]
I am not sure if we need a repository to reproduce this. You can just add a line of code before class declaration like;
```ts
import { Component } from '@stencil/core';

console.log(
  `
    this => ${this}
  `
);


@Component({
...
```

**Comment by jthoms1** [comment]
Commit 9f969a6b0fa0b8d3f899984ed42b15198e67f8a7 fixes this issue.
