### ISSUE TITLE
Stencil fails to minify application/ld+json

### ISSUE THREAD

**Issue by John0x** [ionic-team/stencil#948]
**Stencil version:**
```
 @stencil/core@4.0.0-alpha.11
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Build fails with:
````
[ WARN  ]  build warn
           Generated an empty bundle

[ ERROR ]  Minify JS
           Unexpected token: punc (:)

      L2:  {
      L3:    "@context": "http://schema.org",
      L4:    "@type": "WebSite",
````

**Expected behavior:**
Shouldn't try to minify non-js script tags

**Steps to reproduce:**
Add following code to index.html:
````
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "WebSite",
  "url": "https://www.example.com/",
  "potentialAction": {
    "@type": "SearchAction",
    "target": "https://query.example.com/search?q={search_term_string}",
    "query-input": "required name=search_term_string"
  }
}
</script>
````

**Other information:**
Stencil tries to minify application/ld+json script tags, which doesn't work.

**Comment by adamdbradley** [comment]
Great, thanks for opening the issue. Should be fixed in the next release, thanks!
