### ISSUE TITLE
Cannot set global SASS variables using "globalStyle"

### ISSUE THREAD

**Issue by exotype** [ionic-team/stencil#949]
**Stencil version:**
```
@stencil/core@0.10.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I set SASS variables inside of a file src/global/styles/app.scss which includes some additional partials from src/global/styles/partials/**_.scss
I go to stencil.config.js and set  `globalStyle: 'src/global/styles/app.scss',`

I expect to be able to use any of the variables on my components style files such as `my-component.scss` however i get an error such as `Undefined variable: "$color-1--aqua"` 

**Expected behavior:**
The stencil compiler should pick up the global variables and apply them when it's building the components as suggested by the documentation which states:
*Additonally, the globalStyle config is can be used to precompile styles with Sass, PostCss, etc.*

**Steps to reproduce:**
Just attempt to use global sass variables in a partial and it shouldn't find them from your component's style files.

**Comment by CookieCookson** [comment]
@exotype With the SASS plugin, instead of using the `globalStyles` property you can use `injectGlobalPaths` on the SASS plugin directly:

stencil.config.js
```
...
sass({
  injectGlobalPaths: [
    "src/global/styles/app.scss"
  ]
})
...
```

**Comment by adamdbradley** [comment]
Thanks for the assistance @CookieCookson

**Comment by konrad-kinesso** [comment]
Its still a bug!
