### ISSUE TITLE
Strange behavior with CSSinJS Library

### ISSUE THREAD

**Issue by ryan-edge-ck** [ionic-team/stencil#95]
When attempting to set a class in JSX, the class is converted into numbers.  It will also happen if I pass in a simple variable.

```
import { Component, Prop } from '@stencil/core'
import { style } from 'typestyle'

const wrapper = style({
    color: 'blue'
})

//This will be something like "f1mb383g"

@Component({
    tag: 'my-first-component'
})
export class MyComponent {
    @Prop() firstName: string

    render() {
        return (
            <p class={wrapper}>
                My name is {`${this.firstName} `}
                <slot />
            </p>
        )
    }
}

```

Expected Behavior

The original class name is preserved in the JSX.

Actual Result

The class name is computed into some numeric value.

Example:

![image](https://user-images.githubusercontent.com/28316004/29634452-faca5912-8817-11e7-8e4a-9d2a084d80c6.png)

**Comment by jgw96** [comment]
Hey, thanks for opening an issue with us! Would you be able to share a repo we could use to reproduce this?

**Comment by ryan-edge-ck** [comment]
@jgw96 added an example [here](https://github.com/ryan-edge-ck/stencil-issue-95)

**Comment by xBILLYjr123** [comment]
Hmm

**Comment by adamdbradley** [comment]
Good catch, thanks for opening the issue. Should be fixed in the next release, thanks!
