### ISSUE TITLE
🐛 Error thrown when using HTTPS protocol on dev server

### ISSUE THREAD

**Issue by CookieCookson** [ionic-team/stencil#950]
**Stencil version:**
```
 @stencil/core@0.10.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request

**Current behavior:**
When setting the `protocol` property to `https` on the `devServer` object in `stencil.config.js`, an error is thrown and no dev server is started.

**Expected behavior:**
The dev server should start up and use the HTTPS protocol.

**Steps to reproduce:**
1. Edit `stencil.config.js`
2. In the `devServer` object, set `protocol` to `https`
3. Run `stencil build --dev --watch --serve`

**Related code:**
```
...
devServer: {
    protocol: "https"
},
...
```

**Other information:**

Terminal log:
```bash
[08:13.6]  transpile started ...
[08:15.7]  transpile finished in 2.07 s

[ ERROR ]bject]

[08:15.7]  module map started ...
[08:15.7]  generate styles started ...
[08:16.2]  generate styles finished in 475 ms
[08:16.4]  module map finished in 750 ms
[08:16.4]  generate bundles started ...
[08:17.7]  generate bundles finished in 1.23 s
[08:17.7]  generate app files started ...
[08:20.1]  generate app files finished in 2.46 s
```

**Comment by adamdbradley** [comment]
Thanks for opening the issue. If anyone is able to assist fixing this please hit us up on the stencil slack channel. Thanks

**Comment by CookieCookson** [comment]
@adamdbradley You mentioned in the PR that the `devcert-san` package and its dependencies are too involved for this, would you be happy for me to submit a PR using a different package?

e.g. `webpack-dev-server` uses https://www.npmjs.com/package/selfsigned for generating SSL certificates, which has a lot less dependencies!
