### ISSUE TITLE
🐛 When setting address on devServer, "Initializing first build..." never disappears on first load

### ISSUE THREAD

**Issue by CookieCookson** [ionic-team/stencil#951]
**Stencil version:**
```
 @stencil/core@0.10.7
```

**I'm submitting a:**
[x] bug report
[ ] feature request

**Current behavior:**
If you use the `address` property on the `devServer` configuration, the browser instance is never notified that the build has finished so you see "Initializing first build..." until you manually refresh the page. From here any subsequent changes work as expected.

**Expected behavior:**
After the first build has finished, it loads the application in the browser window when initial build has completed.

**Steps to reproduce:**
1. Set the `address` property in `devServer` to a domain of your choice
2. Add the chosen domain to your hosts file with it mapped to 127.0.0.1
3. Start the build with `stencil build --dev --watch --serve`
4. Watch as the dev server starts, the build finishes and the browser page has not changed

**Related code:**

stencil.config.js
```js
...
devServer: {
    address: "mysupercooldomain.com"
}
...
```

hosts
```
...
127.0.0.1    mysupercooldomain.com
```

**Comment by CookieCookson** [comment]
I'm afraid the same problem occurs with `@stencil/core@0.10.9`.

I did notice that none of the build console messages e.g. `generate bundles started ...` appear in the browser window either, which I assume is because it is not receiving messages from the build process?

Because of this, I thought I would check the console and found this nugget:

![screen shot 2018-07-26 at 09 00 03](https://user-images.githubusercontent.com/3473396/43249342-5a5bd240-90b2-11e8-955d-1ca27b5fdc40.png)

This might mean that it cannot access the `debugger` protocol on non-secure domains which are not localhost. Maybe the protocol must be set to `https` only if using the `address` property this way.

https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

**Comment by CookieCookson** [comment]
@adamdbradley still occurs with 0.10.10.

**Comment by adamdbradley** [comment]
Ok strange, not sure why that'd be, but you're right it does look like it's an origin issue. The dev server "should" be serving from all the same hosts, but apparently it's not. What are all the urls that are being requested?

**Comment by CookieCookson** [comment]
If I manage to catch `~dev-server-init` it throws the correct URLs instead of the url for the `debugger` protocol. (Must be a race condition thing to show the correct URL)

![screen shot 2018-08-06 at 11 50 33](https://user-images.githubusercontent.com/3473396/43712728-182f872a-996f-11e8-99e2-3c40aa08cd49.png)

From chasing the line numbers in the error message, it doesn't like doing the service worker `getRegistration()` on a domain that is not secure.

![screen shot 2018-08-06 at 11 52 49](https://user-images.githubusercontent.com/3473396/43712865-8f91c422-996f-11e8-9b2f-c6415cedb764.png)

![screen shot 2018-08-06 at 11 55 35](https://user-images.githubusercontent.com/3473396/43712889-a6ca7e9a-996f-11e8-8976-9512786b1167.png)

I am assuming this is the service worker for the server, and is required for development? If so it seems like the only way for this to work is if we have the HTTPS protocol enabled?

**Comment by adamdbradley** [comment]
Bad ionic bot, bad!
