### ISSUE TITLE
[data-my-component-slot] mixed with render()

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#956]
**Stencil version:**

```
 @stencil/core@<all>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The <slot /> polyfill for Firefox/IE11/... creates a data-attribute on the component itself. Later, if render() added more content, it is not differentiable what the „real“ assigned nodes passed from outside are.

**Expected behavior:**

Also using the polyfill, it should always be clear throughout the whole lifecycle, which elements are „brought in from outside“ by the <slot /> - like slot.assignedNodes() does in modern browsers.

**Comment by adamdbradley** [comment]
Sorry, but we will not be adding the extra runtime to the polyfill for the slot.assignedNodes property. Happy to discuss this further within the slack channel. Thanks
