### ISSUE TITLE
CLI perf: migrate to turbocolor

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#961]
https://github.com/jorgebucaran/turbocolor

Rollup already did: https://github.com/rollup/rollup/pull/2339

> This PR swaps chalk for turbocolor. It ought to give us a humble perf boost as turbocolor loads >20x faster and applies styles >18x faster than chalk. Terminal color detection is also built-in, so I was able to simplify the code in one place.

AND most important:

**No dependencies!**

**Comment by manucorporat** [comment]
cc @jorgebucaran

**Comment by adamdbradley** [comment]
You had me at "no dependencies" ❤️
