### ISSUE TITLE
Build a flat dist folder structure

### ISSUE THREAD

**Issue by jnorth** [ionic-team/stencil#963]
**Stencil version:**
```
 @stencil/core@0.10.0
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The current folder structure for the `dist` folder contains nested folders:
```
dist/
dist/mycomponent.js
dist/mycomponent/my-component.js
dist/mycomponent/my-component.core.js
```

**Desired behavior:**
I'm working on the Shopify platform, and all theme assets need to be shipped in a flat list of files—subdirectories are not possible. 

https://stackoverflow.com/a/46225424

I believe this makes shipping a Stencil component as a Shopify theme asset impossible.

**Other information:**
As a side-note, I can't find any documentation on the bundled format that Stencil uses. It could be useful to have a short write-up of what each of the dist files do.

**Comment by adamdbradley** [comment]
Sorry but how the dist directory is built will have to stay as is. I'd recommend using absolute paths, or or some custom logic within your components.
