### ISSUE TITLE
Importing global CSS from another package

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/stencil#968]
_From @jacobgelman on July 28, 2018 18:10_

In [this file](https://github.com/ionic-team/ionic-stencil-conference-app/blob/master/src/global.css) I see that it is possible to import CSS from another package. Does the package being imported from have to be published on NPM?

My app does not use Ionic, however, I have created my own package of UI components, `core-ui`. I would like to import the global CSS from this `core-ui` package into the global CSS file of my main app package.

In the global CSS file of my app package, I added:
```
@import "~core-ui/dist/cui.css";
```

However, in the console I receive this error:
```
[ ERROR ]  build error
                   Unable to resolve node module for CSS @import:
                   ~core-ui/cui.css
```

The `core-ui` package was installed from a private git repository like this:
```
npm install https://github.com/.../.../core-ui.git --save
```
As a result, the files from this package do not exist in the `node_modules` directory. However, I am able to use the components from the `core-ui` package within my app with no problem.

_Copied from original issue: ionic-team/ionic-stencil-conference-app#102_

**Comment by adamdbradley** [comment]
The `~` prefix specifically means for resolvable modules within node_modules, otherwise it won't work. I'd recommend using relative or absolute paths if it is not a node module within npm. Hope that helps, thanks
