### ISSUE TITLE
Improve auto-doc generated types

### ISSUE THREAD

**Issue by mattcosta7** [ionic-team/stencil#974]
**Stencil version:**

```
 @stencil/core@0.11.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When generating JSON documentation, enum proptypes are converted to plain types

ie.

```
@Prop() color: 'blue' | 'red' | 'green' = 'green'
@Prop() complexType: string | boolean
```

generates 

a readme with 

```
 #### color

string

#### complexType

any
```

or json like

```
{
    ...,
    props: [{
        name: color,
        type: 'string'
    }, {
        name: 'complexType',
        type: 'any'
    }]
}
```

**Expected behavior:**

I would expect that these more complicated are shown in a way that more expressly maps to their typings (when explicitly set).  not entirely sure of the best way to map this, but some ideas below

readme 
```
#### color

one of 'blue' | 'red' | 'green' 
default 'green'

#### complexType

one of string | boolean
```

json
```
{
    ...,
    props: [{
        type: 'blue' | 'red' | 'green',
        defaultValue: 'green'
    }, {
        type: 'string' | 'boolean'
    }]
}

// or, possibly

{
    ...,
    props: [{
        type: 'enum', // union?
        typeValues: 'blue' | 'red' | 'green'
        defaultValue: 'green'
    }, {
        type: 'enum', // union?
        typeValues: 'string' | 'boolean'
    }]
}
```

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

Happy to work on a PR for something like this if there's agreement it's valuable, and with a little direction on a suitable presentational format

**Comment by adamdbradley** [comment]
Doc generation can be found here if anyone is looking to contribute: https://github.com/ionic-team/stencil/tree/master/src/compiler/docs
