### ISSUE TITLE
IE11 & Firefox-60 have a tough time in the dev-server

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#975]
**Stencil version:**

```
 @stencil/core@0.11.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When making any change to the code while serving with the `--es5` flag, IE11 faceplants due to its lack of understanding of what [this use of CustomEvent](https://github.com/ionic-team/stencil/blob/e26e8007b404dbb46828310db16ff405d6a0bb9b/src/dev-server/dev-client/client-web-socket.ts#L85) means. Sadly this leads to an "out of stack space" issue.

**Expected behavior:**

IE11 does not faceplant while developing.

**Steps to reproduce:**

1. Open the [component-starter](https://github.com/ionic-team/stencil-component-starter) 
1. In the package.json:
    1. Change the stencil version to 0.11.0
    1.  Add `--es5` to the _start_ command
1. Serve the application via `npm start` opening in IE11 && FF
1. Add a `<slot/>` to the 'my-component' render method, save
1. Watch es5 browsers console logs

**Related code:**
```tsx
// insert any relevant code here
```

**Other information:**

+1 more reason to celebrate IE11 EOL when it happens.

Thanks for all the hard work! Normal browsers still seem to work quite well.

**Comment by cary-smith** [comment]
Actually testing the same methodology in Firefox has a recursion error. This may be more than an issue with CustomEvent.

**Comment by cary-smith** [comment]
I have reverted as far as 0.10.0. and still receive the following in Firefox 60 when attempting to change an element code or css. 
<details>
  <summary>
    InternalError
  </summary>
  columnNumber: 44
​
fileName: "http://localhost:3333/build/mycomponent/mycomponent.core.pf.js"
​
lineNumber: 2490
​
message: "too much recursion"
​
stack: "getLoadedBundle@http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:2490:44\nrequestBundle@http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:2582:11\ninitComponentHmr@http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:2291:9\ninitHostElement/HostElementConstructor[\"s-hmr\"]@http://localhost:3333/build/mycomponent/mycomponent.core.pf.js:2336:7\nhmrComponent@http://localhost:3333/~dev-server:299:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\nhmrComponent@http://localhost:3333/~dev-server:306:9\n"
</details>

I really am at a loss on how to test this. I have not begun to look into the server code.

**Comment by cary-smith** [comment]
This issue still exists in 0.11.3 and unfortunately breaks our ability to upgrade. I am not sure how to create a test case for live-editing a compiled file.

I know IE11 and es5 builds are not a primary concern since they will hopefully be dead subjects soon but I am hoping to avoid bot-closure due to being quiet.

**Comment by adamdbradley** [comment]
I'm sorry I'm not able to reproduce what you're seeing. Can you debug it further? Provide some error messages, or screenshots?

**Comment by cary-smith** [comment]
The 'InternalError' expandable in my above post has the error from Firefox 60 (we have to stay on the LTS version of it 😭 ) and the original issue ticket links the line that may be a start of the problem in IE11 since it does not support using CustomEvent as a function.

**Comment by cary-smith** [comment]
If I were to start digging into the code, could you at least point me in the likely area/location that may be involved? I assume you folks are super-busy and I might be able to track it down and provide a PR if I can get some time?

**Comment by cary-smith** [comment]
The infinite loop and IE11 errors no longer seems to occur in 0.12.3. Closing.
