### ISSUE TITLE
Page-specific index.html not generated in www causing flicker when refreshing

### ISSUE THREAD

**Issue by gusterwoei-veltra** [ionic-team/stencil#976]
**Stencil version:**
```
@stencil/core@0.10.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Imagine I have 2 routes:
```
<stencil-route url='/areas' component='area-list-page' />
<stencil-route url='/activities' component='activity-list-page' />                            
```

Somewhere in the code, I have specified `<stencil-route-link>` for path `/areas` but not `/activities` (it will be routed programmatically instead).

When I run `npm run build`, stencil will generate `www/areas/index.html` but not `www/activities/index.html`

**Problem**
When I deploy `www` to a server (eg. firebase), visiting `/activities` and try to refresh it, you can notice a slight flicker between the page in `/` and `/activities`. This however won't happen if I have `www/activities/index.html` generated in `www`

**Expected behavior:**
Refreshing the page should not flicker.

**Steps to reproduce:**
You can try it here:

The one with flicker:
https://testagent-670d9.firebaseapp.com

The one without flicker:
https://pwa-demo-123.firebaseapp.com

In both site, click GETTING STARTED button to go to /repos route, then try to refresh from there.

**Related code:**

**stencil.config.js**
```
const sass = require('@stencil/sass')

exports.config = {
    globalStyle: 'src/global/app.css',
    plugins: [
        sass()
    ],
    outputTargets: [
        {
            type: 'www',
            serviceWorker: {
                swSrc: 'src/sw.js',
                globPatterns: [
                    '**/*.{html,js,css,scss.json,ico,png,jpg}'
                ]
            }
        }
    ]
};

exports.devServer = {
    root: 'www',
    watchGlob: '**/**'
};
```

**Comment by jthoms1** [comment]
Stencil does a prerender in the same way that a bot would crawl your site.  If follows all of the URLs and then generates the corresponding pages.  It has no knowledge of the url structure.

Do you have code for this available that I could look at?

**Comment by gusterwoei-veltra** [comment]
Sure, here's the repo link:
https://github.com/gusterwoei/stencil-pwa-demo-grf

**Comment by jthoms1** [comment]
Ok I see.  The index page is being served and then being rerendered to the actual destination.  I think that there probably should be a way to indicate to the prerenderer that Routes exist.  But this would not be a stencil issue.  I would consider it a router issue so moving the issue there.

**Comment by jthoms1** [comment]
Turns Out I was wrong.  We have an undocumented config that would solve this exact problem.
Add `prerenderLocations` with a list of urls to your outputTarget.
```
   outputTargets: [
      {
         type: 'www',
         prerenderLocations: [
          { path: '/repos' }
         ],
         serviceWorker: {
            swSrc: 'src/sw.js',
            globPatterns: [
               '**/*.{js,css,json,html,ico,png}'
            ]
         }
      }
   ],

**Comment by gusterwoei** [comment]
`prerenderLocations` solved the issue, thank you!
