### ISSUE TITLE
PWA / Add To Homescreen code is missing

### ISSUE THREAD

**Issue by webmaxru** [ionic-team/stencil#979]
As stated in the description "By default we include a Web Manifest that has all the neccessary entries to get the Add to Homescreen prompt." Starting from Chrome 68 we need an explicit piece of code to show this prompt.

Changes: https://developers.google.com/web/updates/2018/06/a2hs-updates
Tech details: https://developers.google.com/web/fundamentals/app-install-banners/

**Stencil version:**

```
 @stencil/core@0.11.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request

**Current behavior:**
There is no way to invoke Add To Home Screen dialog from within the app after the automatic install prompt appearance will be removed from the browsers (for example, in Chrome 68 and later)

**Expected behavior:**
We need a button in the header appearing when the a2hs criteria met. Clicking on that button will show the native app install prompt

**Comment by mhartington** [comment]
@webmaxru we can update the docs to reflect the new changes. I think keeping the add to home screen functionality as part of the user code is ok. We'll make sure to add a snippet/example of this in the sample code.

**Comment by webmaxru** [comment]
Fair enough. Thanks for the immediate reaction! Closing this issue.
