### ISSUE TITLE
Consider removing the alwaysStrict TypeScript flag.

### ISSUE THREAD

**Issue by Karankang007** [ionic-team/stencil#982]
**Stencil version:**
```
@stencil/core@0.10.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Source code in dependent libraries is being scanned due to alwaysStrict TypeScript flag

**Expected behavior:**
If a dependent library is using a non-strict source code, Stencil compiler fails to build. 

**Steps to reproduce:**
- Add a library such as resize-polyfill to the project which uses (with keyword), stencil will fail to build.

**Comment by jthoms1** [comment]
Could you create an example repo that reproduces this?  It will help alot in fixing the problem.  Thanks!
