### ISSUE TITLE
StencilJS component imported in Angular app renders incorrectly in Firefox

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [ionic-team/stencil#986]
**Stencil version:**

```
 @stencil/core@0.9.11
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ x ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I've build a StencilJS component with styling confined in the shadowdom that I'm using in an Angular app, scaffolded with angular-cli. 
In chrome the component works just as expected, but not in firefox. It seems that the css styling isn't being rendered.

**Expected behavior:**

I expect that the component will look the same on both Chrome and Firefox.

**Steps to reproduce:**

1. build the StencilJS component with the `--es5` flag to enable es5 polyfills
2. publish the component to the company's private npm
3. install component in Angular app (`yarn add <component>`)
4. config the app (https://stenciljs.com/docs/framework-integration#angular)

**Related code:**
```
$ ng -v 
```
```
Angular CLI: 6.0.8
Node: 9.3.0
OS: darwin x64
Angular: 6.0.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

**Other information:**

Due to company policy I unfortunately cannot post any code samples, but I'm willing to answer any questions asked.

**Comment by jthoms1** [comment]
Can you provide at least the CSS code? Otherwise trying to troubleshoot this could be a problem.
Also what version of Firefox are you using?

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
