### ISSUE TITLE
Unable to get the anchor tag from the stenciljs <stencil-route-link>?

### ISSUE THREAD

**Issue by sudhakarlahane23** [ionic-team/stencil#992]
I am writing Unit Test cases in **jest**. I want select the anchor tag `<a href="/home">` which is present in route-link, using jest test code. Unfortunately I am not able to select the anchor tag. 

My rendered HTML of routing link looks like as follows in browser.

**HTML:**
```
<li class="nav-level-one"> 
    <stencil-route-link class="hydrated">
        <a class="nav-link" href="/contact" role="menuitem"> Contact Us </a>
    </stencil-route-link>
</li>
```

**Jest Unit Test Case Code:**
```
it('Main Menus visual text shoud equal to Data form JSON', async () => {
        let mainRouteLinks= element.querySelectorAll('.nav-level-one > stencil-route-link');
        for(let i = 0; i < mainRouteLinks.length; i++) {                
        expect(mainMenuRouteLinks[i].innerHTML).toEqual(navigation.navData.mainMenu[i].navigationTitle)
       }
  })
```

Please provide the solution for this.

**Comment by jthoms1** [comment]
Could you provide more code around the setup for the Jest unit tests?
