### ISSUE TITLE
Can't create Headers

### ISSUE THREAD

**Issue by theraccoonbear** [ionic-team/stencil#993]
**Stencil version:**
```
 @stencil/core@0.11
```

**I'm submitting a:**
[x] bug report
[ ] feature request

**Current behavior:**
Fails to pre-render when I try to instantiate a new `Headers` object.
https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers

**Expected behavior:**
A new `Headers` object should be created

**Steps to reproduce:**
`const headers = new Headers();`

**Comment by theraccoonbear** [comment]
Talked to @jthoms1 about this issue and he encouraged me to open an issue

**Comment by manucorporat** [comment]
fixed in master!
