### ISSUE TITLE
Blank screen when running output of npm init stencil

### ISSUE THREAD

**Issue by ryanhaney** [ionic-team/stencil#994]
**Stencil version:**
0.11.0

**I'm submitting a:**
[X ] bug report

**Current behavior:**
I'm trying to run the generated output of `npm init stencil`. No matter what option I chose, `npm start` always results in build steps being reported in the browser followed by a blank screen.

**Expected behavior:**
Should not see a blank screen after build completes.

**Steps to reproduce:**
run `npm init stencil` and follow the prompts.

**Other information:**
When selecting the app option, the build results in an error stating the `request` package is missing. Installing the dependency allows the build to complete, but still results in a blank screen. This error does not show up for the component or pwa options.

**Comment by adamdbradley** [comment]
Which operating system are you using? Thanks

**Comment by ryanhaney** [comment]
macos 10.13.6

**Comment by ryanhaney** [comment]
Following this path here, I still get the same error:

```sh
ryanhaney@tank  ~/Projects/appology/test  git clone https://github.com/ionic-team/stencil-app-starter.git cloned
Cloning into 'cloned'...
remote: Counting objects: 374, done.
remote: Total 374 (delta 0), reused 0 (delta 0), pack-reused 374
Receiving objects: 100% (374/374), 340.91 KiB | 1.95 MiB/s, done.
Resolving deltas: 100% (196/196), done.
 ryanhaney@tank  ~/Projects/appology/test  cd cloned 
 ryanhaney@tank  ~/Projects/appology/test/cloned   master  npm i

> fsevents@1.1.2 install /Users/ryanhaney/Projects/appology/test/cloned/node_modules/fsevents
> node install

[fsevents] Success: "/Users/ryanhaney/Projects/appology/test/cloned/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.2.4 install /Users/ryanhaney/Projects/appology/test/cloned/node_modules/sane/node_modules/fsevents
> node install

[fsevents] Success: "/Users/ryanhaney/Projects/appology/test/cloned/node_modules/sane/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 944 packages from 482 contributors and audited 24968 packages in 10.756s
found 366 vulnerabilities (361 low, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
 ryanhaney@tank  ~/Projects/appology/test/cloned   master  npm start

> @stencil/starter@0.0.1 start /Users/ryanhaney/Projects/appology/test/cloned
> stencil build --dev --watch --serve

[42:26.4]  @stencil/core v0.11.0 🍇
[42:26.5]  build, app, dev mode, started ...
[42:26.5]  module map started ...
[42:26.5]  generate styles started ...
[42:26.5]  module map finished in 2 ms
[42:26.5]  compile global style start ...
[42:28.0]  compile global style finish in 1.41 s
[42:28.0]  generate styles finished in 1.41 s
[42:28.0]  generate bundles started ...
[42:28.0]  generate bundles finished in 1 ms
[42:28.0]  generate app files started ...
[42:29.0]  generate app files finished in 1.07 s

[ ERROR ]  Cannot find module 'request' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load
           (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at
           /Users/ryanhaney/Projects/appology/test/cloned/node_modules/request-promise-native/lib/rp.js:8:12 at
           module.exports
           (/Users/ryanhaney/Projects/appology/test/cloned/node_modules/stealthy-require/lib/index.js:62:23) at
           Object.<anonymous>
           (/Users/ryanhaney/Projects/appology/test/cloned/node_modules/request-promise-native/lib/rp.js:7:15) at
           Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load
           (module.js:565:32)

[42:29.1]  dev server: http://localhost:3334/
^C
 ✘ ryanhaney@tank  ~/Projects/appology/test/cloned   master  
 ✘ ryanhaney@tank  ~/Projects/appology/test/cloned   master  npm i request --save-dev
+ request@2.87.0
added 12 packages from 24 contributors and audited 25026 packages in 5.182s
found 367 vulnerabilities (361 low, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details
 ryanhaney@tank  ~/Projects/appology/test/cloned   master ●  npm start

> @stencil/starter@0.0.1 start /Users/ryanhaney/Projects/appology/test/cloned
> stencil build --dev --watch --serve

[42:48.0]  @stencil/core v0.11.0 🍇
[42:48.1]  build, app, dev mode, started ...
[42:48.2]  module map started ...
[42:48.2]  generate styles started ...
[42:48.2]  module map finished in 2 ms
[42:48.2]  compile global style start ...
[42:48.2]  compile global style finish in 5 ms
[42:48.2]  generate styles finished in 6 ms
[42:48.2]  generate bundles started ...
[42:48.2]  generate bundles finished in 1 ms
[42:48.2]  generate app files started ...
[42:48.2]  generate app files finished in 18 ms
[42:50.2]  dev server: http://localhost:3334/
[42:50.2]  build finished, watching for changes... in 2.06 s
```

At this point, blank screen.

**Comment by ryanhaney** [comment]
INTERESTINGLY....I was able to get another copy of the repo up and running _using the same commands_. In the *working* repo, running `npm run build` results in no errors. In the *non-working* repo, running `npm run build` results in the following errors:

**Comment by ryanhaney** [comment]
I uploaded both projects to here: 
https://www.dropbox.com/sh/dhvkilevgn0s0p4/AADbX3Fs_Hhikz6ywJvyoYeCa?dl=0

**Comment by poolyfill** [comment]
I am seeing the same problem (MacOS, node 8.11.3, npm 6.4.0).  After this sequence:

- npm init stencil  (starter: “component”, name: “test-component”)
- cd test-component
- npm start

The build finishes successfully and the browser launches, but the page is blank.

Looks like the <my-component> custom element isn’t being registered.

I noticed that in mycomponent.js, the outer function is invoked with an empty “components” array:

```
(function(win, doc, namespace, fsNamespace, resourcesUrl, appCore, appCoreSsr, appCorePolyfilled, hydratedCssClass, components) {

// component impl here…

  })(window, document, "mycomponent","mycomponent",0,"mycomponent.core.js","es5-build-disabled.js","hydrated",[],HTMLElement.prototype);
```

This eventually leads to a failure to call defineComponent() in mycomponent.core.js, as App.components is the empty array.

Note that there is some also some arg misalignment in the above code.  HTMLElement.prototype is being passed in via the “components” arg and the components (empty) array is passed in via “hydratedCssClass”.  But this ends up getting straightened out by the subsequent init call, which is misaligned in the opposite way. :-)

**Comment by poolyfill** [comment]
Good news.  After my @stencil/core dependency from:

    "@stencil/core": "^0.11.0",

To:

    "@stencil/core": "^0.12.0",

I can no longer reproduce the issue.

FWIW, the tail end of mycomponent.js now looks like this:

  })(window, document, "mycomponent","mycomponent",0,"mycomponent.core.js","es5-build-disabled.js","hydrated",[["my-component","my-component",1,[["first",1,0,1,2],["last",1,0,1,2]],1]],HTMLElement.prototype);

No longer seeing an empty components array.

**Comment by poolyfill** [comment]
Sorry, one more comment...  This problem:

> When selecting the app option, the build results in an error stating the request package is missing.

Isn't solved by upgrading to @stencil/core 0.12.x.  However, after manually installing the request package as Ryan shows above *and* upgrading to @stencil/core 0.1.2.x, I am able to bring up the starter app.

**Comment by ryanhaney** [comment]
As simple as it is, I made a PR for the missing module. Sadly, it's been almost a month and no action.

https://github.com/ionic-team/stencil-app-starter/pull/59

**Comment by adamdbradley** [comment]
@ryanhaney Adding `request` isn't the solution because it's a dependency of a dependency issue. We're actively replacing jsdom which causes this issue with puppeteer.

**Comment by ryanhaney** [comment]
In the meanwhile, those that decide to give stencil a try are delivered a horrible out-of-box experience. I understand that this issue was not _caused_ by Ionic, but it can certainly be worked around, even if as a stop-gap until you release the jsdom replacement.

**Comment by jthoms1** [comment]
Closing as a duplicate of #800.
