### ISSUE TITLE
How to add attributes / custom attributes & properties on <stencil-route-link> router?

### ISSUE THREAD

**Issue by sudhakarlahane23** [ionic-team/stencil#996]
I am trying to create the Navigation component. I need to add some attributes/custom-attributes on Navigation links. I am able to add some of them, like follows.

- url="/"
- anchorClass="menu active"
- anchorRole="menuitem"
- anchorTabIndex="2"
- anchorTitle="Menu Title"

There are some more attributes I required to add on links, but I am not able to add these attributes on route-link , as follows.

- **aria-haspopup="true"**
- **id="consumers"**
- **aria-posinset="1"**
- **aria-setsize="2"**
- **aria-label="Home menu"**

**Following is my <stencil-route-link> code in .tsx file.**

`<stencil-route-link anchorClass="some classes" url="/home" anchorClass="menu active" anchorRole="menuitem" anchorTabIndex="2" anchorTitle="Menu Title" anchorAriaHaspopup="true" anchorId="consumers" anchorAriaPosinset="1" anchorAriaSetsize="2" anchorAriaLabel="Home menu">
Home
</stencil-route-link>`

**Browser source code:**

```
<li class="nav-level-one"> 
    <stencil-route-link class="hydrated">
        <a class="nav-link" href="/home" role="menuitem"> Home </a>
    </stencil-route-link>
</li>
```

There are some attributes are missing in output. (aria-haspopup="true", id="consumers", aria-posinset="1", aria-setsize="2", aria-label="Home menu")

**Comment by jthoms1** [comment]
Closing issue a recent PR was merged to router to resolve these. https://github.com/ionic-team/stencil-router/pull/61
