### ISSUE TITLE
prerenderer duplicates

### ISSUE THREAD

**Issue by DominicBoettger** [ionic-team/stencil#999]
As far as I remember should the prerenderer only run once per url. In my case I see that it runs sometime 7 or more times over the same url ( 10k pages ). This causes the process to take more than 2:30 hours to finish the prerendering.

**Stencil version:**

```
 @stencil/core@0.10.8
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The prerenderer runs multiple times per url. The console output show for example multiple times that it starts prerendering for a page which has been prerendered before. I figured that out when I watched the console and saw after a few minutes the same url again and cheked this for other url's too. They already had entries in the www folder but were recreated.

**Expected behavior:**
Prerenderer should only run once per url

**Steps to reproduce:**
Create a website where the contents link to each other multiple times.

**Other information:**
Additional information about prerenderer issues:
0.10.0 stops output after a looong time and after many duplicates
0.10.10 stops output after but still seems to render pages in the background

0.9.7 produces output, waiting for the results.

**Comment by DominicBoettger** [comment]
Okay. By changing the line
  if (!prerenderLocation || prerenderQueue.some(p => p.url === prerenderLocation.url)) 
to

  if (!prerenderLocation || prerenderQueue.some(p => p.path === prerenderLocation.path )) 
I removed the duplicate rendering. With version 0.11.2 it now stops at some point and is stuck.

**Comment by adamdbradley** [comment]
Ok thanks for the report. We'll get this fixed up. Thanks

**Comment by manucorporat** [comment]
Stencil One finally refactors the whole prerender and this should not longer be an issue!
